// The Worker's entry point: OpenNext's generated worker, plus a cron.
// wrangler.jsonc points `main` here and lists the cron under `triggers`.
// See https://opennext.js.org/cloudflare/howtos/custom-worker
//
// The cron doesn't do the work itself; it hands a request to the app's own
// /api/reminders route in-process (no network hop), with the shared secret,
// so all the logic stays in Next.js where it's typed and tested.

// Generated by `opennextjs-cloudflare build`; this file is excluded from tsconfig.
import { default as handler } from "./.open-next/worker.js";

type Env = { BATCH_IMPORT_SECRET?: string };

const worker = {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    const request = new Request("https://youdoido.com/api/reminders", {
      method: "POST",
      headers: { authorization: `Bearer ${env.BATCH_IMPORT_SECRET ?? ""}` },
    });
    ctx.waitUntil(
      handler.fetch(request, env, ctx).then(async (res: Response) => {
        // Shows up in Workers logs (observability is on in wrangler.jsonc).
        console.log("weekly digest", res.status, await res.text());
      }),
    );
  },
};

export default worker;

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
