import type { VendorBatch } from "@/lib/vendor-batches";

// Alabama vendor batches. Every row's State is "Alabama". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Birmingham: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Lynn Cummings Photography	Photography	1211 28th St S, Suite 203	Birmingham	Alabama	Greater Birmingham, Hoover, Tuscaloosa, Huntsville, Cullman and Montgomery	Wedding, engagement and portrait photographer shooting since 2008, working from an appointment-only studio on Birmingham's Southside.	lc@lynncummingsphoto.com	(205) 370-8599	https://www.lynncummingsphotography.com/	https://www.instagram.com/lynncummingsphoto/
Eric & Jamie Photography	Photography		Birmingham	Alabama	Birmingham, 30A, Atlanta and the Southeast	Husband-and-wife team photographing weddings in a classic, timeless style since 2014, with wedding videography also on offer.	info@ericandjamiephoto.com		https://ericandjamiephoto.com/	https://www.instagram.com/ericandjamiephoto/
Katie & Alec Photography	Photography		Birmingham	Alabama	Birmingham, Alabama and beyond	Husband-and-wife photographers known for light, bright and airy wedding images and relaxed, natural posing for a calm wedding day.			https://katieandalec.com/	https://www.instagram.com/katieandalecphoto/
Je Vois Photography	Photography		Birmingham	Alabama	Birmingham and the Southeast	Birmingham wedding and event photographer Hillary focuses on true-to-colour images that capture how the day actually felt.			https://jevoisphotography.com/	https://www.instagram.com/jevois_photography/
Mariée Ami	Planning		Birmingham	Alabama		Full-service planning and design firm whose name means 'bride's friend', organising wedding weekends at home and at destinations.	neillie@marieeami.com		https://www.marieeami.com/	https://www.instagram.com/mariee_ami/
Handley Breaux Designs	Planning		Mountain Brook	Alabama	Mountain Brook and beyond, with travel available	Luxury wedding planner and event designer handling full-service planning, from rehearsal dinner and hotel blocks to wedding-day design.	booking@handleybreauxdesigns.com	(205) 900-8804	https://www.handleybreauxdesigns.com/	https://www.instagram.com/handleybreauxdesigns/
Becky's Brides	Planning		Birmingham	Alabama	Throughout the Southern United States	Planning team of over a decade offering full-service planning, design and coordination, with an emphasis on Southern hospitality.	becky@beckysbrides.com		https://beckysbrides.com/weddings/	https://www.instagram.com/beckysbrides/
Laurel and Sage Florals	Florals		Birmingham	Alabama		Wedding floral design and event styling studio working since 2017 with seasonal blooms, distinctive colour palettes and organic texture.	laurelandsageflorals@gmail.com		https://laurelandsageflorals.com/	https://www.instagram.com/laurelandsageflorals/
Marigold Designs	Florals		Birmingham	Alabama	Birmingham and throughout the Southeast	Full-service floral studio led by Mary Cox Brown, trained at the New York Flower School, known for bold, rich colour in wedding work.	info@marigold-designs.com	(205) 447-4747	https://www.marigold-designs.com/	https://www.instagram.com/marigolddesign/
Wildly Rooted Floral Design	Florals		Birmingham	Alabama	Birmingham and the Southeast	Wedding and event florist creating colour-forward, nature-inspired arrangements with a chic, textural, slightly wild look.	wildlyrootedflorals@gmail.com		https://www.wildlyrootedfloraldesign.com/	https://www.instagram.com/wildlyrootedfloraldesign/
Dorothy McDaniel's Flower Market	Florals	3300 3rd Ave S	Birmingham	Alabama		Long-standing Birmingham flower shop designing wedding flowers since 1977, with venue walk-throughs, consultations and event rentals.		(205) 871-0092	https://dorothymcdaniel.com/weddings/	https://www.instagram.com/flowersfromdorothy/
Rocket Entertainment	Music		Birmingham	Alabama	Birmingham, Huntsville, Knoxville, Chattanooga and Nashville	Wedding DJ and lighting company with a Birmingham office, offering DJ-emcees, ceremony sound, dance floor lighting and bilingual DJs.	info@rocket-entertainment.com	(205) 360-1901	https://www.rocket-entertainment.com/wedding-dj-birmingham-al/	https://www.instagram.com/rocket_entertainment/
The Good Times Co	Music		Birmingham	Alabama		Birmingham wedding DJ outfit that puts reading the room and keeping the dance floor full ahead of flashy technique.	letsparty@thegoodtimesco.net		https://goodtimesco.net/	https://www.instagram.com/_goodtimesco/
Iron City Strings	Music		Birmingham	Alabama		String quartet drawn from Alabama Symphony Orchestra players, covering classical, pop, jazz, Irish tunes and hymns for ceremonies.	info@ironcitystrings.com	(281) 336-0983	https://www.ironcitystrings.com/	
Cahaba River Strings	Music		Birmingham	Alabama	Across Alabama, including Lake Martin, Smith Lake, Auburn, Huntsville, Tuscaloosa and Montgomery	Birmingham string quartet playing wedding ceremonies, receptions and private parties, with custom arrangements on request.			https://www.cahabariverstrings.com/	
The Happy Catering Company	Catering		Birmingham	Alabama	Birmingham metro area	Family-run caterer with Greek restaurant roots and over 25 years in Birmingham, offering custom wedding menus and full bar service.	info@happycatering.net	(205) 251-8925	https://happycatering.net/	https://www.instagram.com/happycateringco/
Corretti Catering	Catering	2101 2nd Ave N	Birmingham	Alabama		Birmingham caterer of over 20 years with customisable wedding menus, from Conecuh sausage bites to tomahawk steak displays.	info@corretticatering.com	(205) 503-4460	https://corretticatering.com/	
Table & Thyme	Catering		Birmingham	Alabama		Event caterer serving Southern-leaning wedding menus, with signature grazing tables, passed appetisers and plated or buffet dinners.	info@tableandthyme.co	(205) 597-4480	https://tableandthyme.co/	https://www.instagram.com/tableandthyme.co/
Eight Eleven Catering	Catering		Birmingham	Alabama		Chef-owned catering company run by Chef Lamar Lockett, cooking for weddings, private events and corporate functions.	eightelevencatering@gmail.com		https://eightelevencatering.com/	https://www.instagram.com/eightelevencatering/
Hair + Makeup by NAT	Hair & Makeup		Birmingham	Alabama	Birmingham and worldwide travel	On-location bridal hair and makeup for the bride and wedding party, plus styling for engagement shoots and other photo sessions.			https://www.hairandmakeupbynat.com/	https://www.instagram.com/hmu.bynat/
Makeup by SKN	Hair & Makeup		Birmingham	Alabama		Mobile hair and makeup artist Suki offers bridal and non-bridal glam for all genders, travelling to homes, hotels and venues.	makeupbyskn@gmail.com	(716) 255-5121	https://www.makeupbyskn.com/	https://www.instagram.com/makeupbyskn/
Bridal Beautique Co	Hair & Makeup		Birmingham	Alabama	Alabama, with travel worldwide	On-site bridal hair and makeup team with trials and long-wear products, styling brides, mothers and bridesmaids.	bridalbeautiqueco@gmail.com		https://bridalbeautiqueco.com/	https://www.instagram.com/bridalbeautiqueco/
Sara Elizabeth Artistry	Hair & Makeup		Hoover	Alabama		Hair and makeup artist Sara Elizabeth Roper works from a studio in Hoover, offering bridal styling, makeup and hair trials.			https://www.saraelizabethmua.com/	https://www.instagram.com/saraelizabethmua/
Daughters Baking	Cake	2812 Cahaba Rd	Birmingham	Alabama		Boutique cake shop on Cahaba Road making wedding cakes and celebration cakes, open to visitors Monday to Saturday.	orders@daughtersbaking.com	(205) 637-6238	https://www.daughtersbaking.com/	https://www.instagram.com/daughtersbaking/
Edgar's Bakery	Cake		Birmingham	Alabama	Central and north Alabama	Local bakery with several Birmingham-area shops, baking wedding cakes to order and offering a five-flavour wedding tasting box.	weddings@edgarsbakery.com		https://www.edgarsbakery.com/weddings/	https://www.instagram.com/edgarsbakery/
Louise's Cakes & Supply	Cake		Pelham	Alabama	Birmingham and surrounding areas	Pelham cake shop and baking supply store making custom wedding cakes for over 35 years, with consultations and dessert bars.	info@louises-cakes.com	(205) 823-6799	https://louises-cakes.com/weddings	https://www.instagram.com/louisescakesbhm/
New Heights Film	Videography		Birmingham	Alabama	Birmingham, Alabama and beyond	Husband-and-wife wedding filmmakers offering cinematic wedding films, Super 8 footage and next-day social reels.	newheightsweddings@gmail.com		https://www.newheightsfilm.com/	https://www.instagram.com/newheightsfilm/
Yonder Film Co.	Videography		Birmingham	Alabama	Birmingham and worldwide	Husband-and-wife duo making quiet, observational wedding films shot on 16mm and digital, travelling widely from Birmingham.	hello@yonderfilmco.com		https://www.yonderfilmco.com/	https://www.instagram.com/yonderfilmco/
Bright & Gray Creative	Videography		Birmingham	Alabama	Central Alabama and the greater Southeast	Video studio taking a limited number of weddings each year, filming in a fly-on-the-wall style that avoids staged moments.	hello@brightandgray.com	(386) 679-1818	https://www.brightandgray.com/weddings	https://www.instagram.com/brightandgraycreative/
`,
  },
  {
    name: "Huntsville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kubay Studio	Photography		Meridianville	Alabama	Huntsville, Madison, Decatur, Athens and the Southeast	Editorial-style wedding and engagement photographer just north of Huntsville, focused on romantic storytelling and clean, modern portraits.	kubaystudio@gmail.com	(938) 246-9616	https://www.kubaystudio.com/	https://www.instagram.com/kubay_studio/
Mariah Oldacre Photography	Photography		Huntsville	Alabama	Huntsville, Birmingham, Chattanooga, Nashville and beyond	Huntsville wedding and elopement photographer with a candid, emotive style, also covering engagements and proposals across the Southeast.	mariaholdacre@gmail.com		https://mariaholdacre.com/	https://www.instagram.com/m_graceo/
Rachel Carter Photography	Photography		Huntsville	Alabama	Birmingham, Nashville, Chattanooga, Florence, Atlanta and the Southeast	Huntsville photographer shooting weddings, elopements and engagements on medium format film, with a colourful, unposed and timeless look.			https://rachelcarterphotography.com/	https://www.instagram.com/rachelcarterphoto/
Bonnie Does Photos	Photography		Madison	Alabama		Madison wedding and portrait photographer offering affordable hourly wedding coverage, with full-resolution images and printing rights included.			https://bonniedoesphotos.com/	https://www.instagram.com/bonniedoesphotos/
Helping Hand Weddings & Events	Planning		Huntsville	Alabama	Huntsville, Madison, Athens, Guntersville, Decatur and North Alabama	Huntsville planning team led by Erica Thimsen, offering full, partial and month-of coordination plus rehearsal direction and event staffing.	erica@helpinghandparties.com	(256) 698-4048	https://helpinghandparties.com/	https://www.instagram.com/helpinghandparties/
Invited Weddings	Planning		Huntsville	Alabama	Alabama and the Southeast	Huntsville planning and design studio led by Tracy Sanchez, offering full-service planning for refined, personal weddings across the Southeast.			https://www.invitedweddingsco.com/	https://www.instagram.com/invitedweddings/
Juniper & Joelle Event Co.	Planning		Huntsville	Alabama		Huntsville planner for colourful, intentional weddings of any size, offering full, partial and day-of planning with an LGBTQIA+ inclusive approach.			https://juniperandjoelle.com/	https://www.instagram.com/juniperandjoelleevents/
Bela Lumiere Events	Planning		Huntsville	Alabama		Huntsville planning company run by Brianna Pyle, offering full-service planning and day-of coordination for weddings and elopements.	belalumiereevents@gmail.com	(256) 508-4186	https://belalumiereevents.com/	https://www.instagram.com/belalumiereevents/
Bishop's Flowers	Florals	502 Andrew Jackson Way NE	Huntsville	Alabama		Long-running full-service florist near downtown Huntsville, designing wedding bouquets and reception flowers alongside everyday arrangements.	info@bishopsflowers.com	(256) 539-2711	https://bishopsflowers.com/	https://www.instagram.com/bishopsflowers/
BouqYard	Florals		Huntsville	Alabama	Central and North Alabama, Middle Tennessee and West Georgia	Wedding and event florist run by Theresa Green, creating custom wedding flowers for couples across North Alabama and neighbouring states.	bouqyard@gmail.com	(256) 572-0903	https://www.bouqyard.com/	https://www.instagram.com/bouqyard/
Old Frond Floral Co.	Florals	2211 Seminole Dr SW, Railroad Room 3	Huntsville	Alabama		Appointment-only floral studio at Lowe Mill in Huntsville, creating ethereal, artfully arranged flowers for weddings and events since 2016.	anna@oldfrond.com		https://www.oldfrond.com/	https://www.instagram.com/oldfrond/
Felicity String Quartet	Music		Huntsville	Alabama		Huntsville string quartet playing wedding ceremonies, cocktail hours and receptions, with a song library to choose from for each moment.	felicitystringquartet@gmail.com	(256) 542-1601	https://felicitystringquartet.com/	
Metropolitan Disc Jockey Service	Music		Huntsville	Alabama	Huntsville, Madison, Decatur, Athens, Cullman, Guntersville, Florence, Scottsboro and Fayetteville, TN	Huntsville DJ company with a team of a dozen DJs, offering wedding packages with MC services, custom playlists and lighting add-ons.	bookings@metropolitandiscjockey.com	(256) 533-6065	https://www.metropolitandiscjockey.com/	https://www.instagram.com/metropolitandiscjockey/
Epic DJ Entertainment	Music	17 Moulton St E	Decatur	Alabama	Huntsville, Birmingham, Nashville and the Tennessee Valley	Decatur DJ and MC team founded by Drew and Stephanie Johnson, adding cold sparks, uplighting and photo booths to wedding receptions.	info@epicdjent.com	(256) 565-7882	https://www.epicdj-entertainment.com/	https://www.instagram.com/epicdj_entertainment/
LED Orange	Music		Huntsville	Alabama		Huntsville audio-visual production company offering wedding DJs with separate ceremony sound, uplighting and theatrical lighting effects.		(256) 288-7515	https://ledorange.com/wedding-dj/	https://www.instagram.com/ledorange/
Chef On Call Catering	Catering	1012 Jordan Ln NW	Huntsville	Alabama	Huntsville area	Mother-and-daughter Huntsville caterer running for over 25 years, building custom chef-led wedding menus with staffing and rentals.	contactus@chefoncallcatering.com	(256) 534-8648	https://www.chefoncallcatering.com/	
Honey Box Charcuterie & Catering	Catering		Huntsville	Alabama		Huntsville caterer known for grazing tables and charcuterie, offering buffet receptions, cocktail-hour stations and rehearsal dinners.	honeyboxhuntsville@gmail.com		https://www.honeyboxhuntsville.com/Catering/	
609 Social	Catering	609 Bank St NE	Decatur	Alabama	Decatur, Madison, Athens, Huntsville and North Alabama	Downtown Decatur market and caterer offering everything from drop-off to full-service wedding catering, plus private dining and bar service.		(256) 938-8350	https://www.609social.com/theannex-1	https://www.instagram.com/609socialmarket/
Society Salon	Hair & Makeup	20 Town Center Dr NW, Suite 1111	Huntsville	Alabama		Huntsville salon whose bridal team does hair and makeup for brides and wedding parties, in the salon or on location at the venue.	societysaloncontact@gmail.com	(256) 665-3651	https://www.societysalonal.com/our-services/bridal/	https://www.instagram.com/societysalonal/
Elleven Salon	Hair & Makeup	518 Madison St SE	Huntsville	Alabama		Downtown Huntsville salon offering full hair and makeup for brides and bridal parties, either in the salon or on site at the venue.	elleven@ellevensalon.com	(256) 489-4247	https://www.ellevensalon.com/bridal-elleven-salon-huntsville	https://www.instagram.com/hairelleven/
The Beautification Lounge	Hair & Makeup		Huntsville	Alabama		Huntsville makeup and skincare studio run by Ly Brease, doing bridal makeup at the studio, in hotel suites or on site before the ceremony.	getready@beautificationlounge.com	(256) 882-9181	https://www.beautificationlounge.com/	https://www.instagram.com/thebeautificationlounge/
Batter Up Cake Bakery	Cake	6125 University Dr NW, Suite B10	Huntsville	Alabama	North Alabama	Huntsville bakery making scratch-baked custom cakes since 2014, including wedding cakes, with allergy requests accommodated.			https://www.batterupcakebakery.com/	
Mason Dixon Bakery & Bistro	Cake	415 Church St NW	Huntsville	Alabama	Within an hour of Huntsville	Dedicated gluten-free bakery and bistro in Huntsville making wedding cakes every guest can eat, with full-service wedding catering too.	info@masondixonbakery.com	(256) 213-7545	https://masondixonbakery.com/weddings	https://www.instagram.com/masondixonhsv/
Hamley Bake Shoppe	Cake	12023 Hwy 231-431 N	Meridianville	Alabama	Meridianville and surrounding areas	Meridianville bakery with a storefront since 2017, baking custom wedding and groom's cakes alongside cookies and everyday treats.	hamleybakeshoppe@gmail.com	(256) 693-7595	https://www.hamleybakeshoppe.com/	https://www.instagram.com/hamleybakeshoppe/
The Flour Elise	Cake		Madison	Alabama	Alabama pickup and delivery	Nut-free bakery in Madison making custom celebration and wedding cakes, a safe choice for couples with nut-allergic guests.	theflourelise@gmail.com	(205) 807-6523	https://www.theflourelise.com/	https://www.instagram.com/the_flour_elise/
Renowned Media	Videography		Huntsville	Alabama	The Southeast	Huntsville wedding film team making chronological, full-day films with real vows and toasts in place of short highlight reels.	ben.ellis@renowned.media	(256) 203-9213	https://renowned.media/	https://www.instagram.com/renowned.weddings/
Kyle Root Photography	Videography		Decatur	Alabama	North Alabama	Decatur photographer and videographer with over 250 weddings captured, including Indian wedding events, plus headshots and commercial work.	info@kyleroot.com	(256) 616-1471	https://www.kyleroot.com/	https://www.instagram.com/kyle.root/
Chelsey K Films	Videography		Huntsville	Alabama	North Alabama and beyond	North Alabama wedding filmmaker Chelsey Kincaid, making cinematic, documentary-style films centred on real emotion, and travelling for weddings.	hello@chelseykfilms.com		https://chelseykfilms.com/	https://www.instagram.com/chelseykfilms/
`,
  },
];

export default batches;
