import type { VendorBatch } from "@/lib/vendor-batches";

// Alaska vendor batches. Every row's State is "Alaska". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Anchorage: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Emelia K Photography	Photography		Anchorage	Alaska	Anchorage, the Kenai Peninsula and Southeast Alaska	Documentary-style wedding and elopement photographer in Anchorage, covering relaxed weddings through to helicopter elopements and glacier vows.	emeliakphoto@gmail.com		https://emeliakphotography.com/	https://www.instagram.com/emeliakphoto/
Chugach Peaks Photography	Photography		Anchorage	Alaska	Alaska and destinations beyond	Anchorage team of five wedding photographers, known for glacier helicopter weddings, winter weddings and dramatic mountain backdrops.	joe@chugachpeaks.com	907-301-9400	https://chugachpeaks.com/	https://www.instagram.com/chugachpeaksphotography/
Pal Photography	Photography		Anchorage	Alaska	Anchorage, travelling throughout Alaska and the Lower 48	Peter Luchsinger photographs weddings in a relaxed, candid style, and every wedding couple gets free portrait sittings for life afterwards.	palphotography@gmail.com	907-244-8410	https://www.palphotography.com/	https://www.instagram.com/pal_photography_alaska/
Alborn Events	Planning		Anchorage	Alaska	Anchorage and remote locations across Alaska	Sarah Alborn offers partial planning, design and wedding-day coordination across Alaska, drawing on event experience dating back to 2004.	Albornevents@gmail.com	907-223-4200	https://www.albornevents.com/	https://www.instagram.com/albornevents/
AKhappenings	Planning		Anchorage	Alaska	Alaska and destination weddings	Jordan Lane plans and designs weddings and elopements, from month-of to full service, including glacier ceremonies and Homer celebrations.	akhappenings@gmail.com		https://akhappenings.com/	https://www.instagram.com/akhappenings/
Alaska Wild Hearts Events	Planning		Anchorage	Alaska		Anchorage planners offering day-of coordination to full planning, specialising in intimate weddings and all-inclusive adventure elopements.			https://akwildheartsevents.com/	https://www.instagram.com/wildheartsevents/
ONDAGO DJ Entertainment	Music		Anchorage	Alaska	Anchorage and Southcentral Alaska	DJ John Fernandez brings 20-plus years of wedding work, with battery-powered ceremony sound for outdoor sites, dance lighting and a photo booth.	info@ondagodj.com	(907) 222-6222	https://www.ondagodj.com/	https://www.instagram.com/ondagodj/
DJ KDean	Music		Anchorage	Alaska	Anchorage and surrounding Alaska	Wedding DJ and emcee with 19-plus years in Alaska, offering custom playlists and coverage of the whole event with no time minimums.	music@djkdean.com	(907) 209-3304	https://djkdean.com/	https://www.instagram.com/dj_kdean/
49 North Entertainment	Music		Anchorage	Alaska	Anchorage, Eagle River, Wasilla, Palmer, Girdwood, Kenai, Soldotna, Seward and Homer	Corinthian Wiley DJs and emcees weddings from ceremony to last dance, with wireless mics, uplighting, fog and confetti effects.	alaska49north@yahoo.com	907-350-5203	https://49-north-ak.org/	https://www.instagram.com/ak49party/
Peppercini's Deli & Catering	Catering	239 E 26th Ave	Anchorage	Alaska		Anchorage deli with a dedicated wedding menu, catering anything from appetiser-only receptions to full buffets, with gluten-free options.		(907) 279-3354	https://peppcatering.com/	https://www.instagram.com/peppercinis/
Casual Encounters Catering	Catering	3101 Eureka St	Anchorage	Alaska	Anchorage and surrounding areas	Fine-dining wedding caterer with a mobile kitchen that can cook at remote sites, plus its own banquet room for up to 100 guests.	Casualencounterscatering@gmail.com	907-632-1518	https://www.casualencounterscatering.com/	
Sis's Cafe and Catering	Catering	5445 Old Seward Hwy	Anchorage	Alaska		Chef-run Anchorage café catering weddings with custom from-scratch menus, led by an executive chef trained at the Culinary Institute of America.	davidsonsisscafe@gmail.com	907-562-3332	https://www.sisscafe.com/	
Vibe Artistry	Hair & Makeup		Anchorage	Alaska	All of Alaska	Tiffanee's bridal beauty team does hair and makeup for brides and wedding parties across Alaska, offering trials and touch-up bags.	muatiffee@gmail.com		https://vibeartistry.com/	https://www.instagram.com/vibe.artistry/
The Beauty Room	Hair & Makeup	1443 W Northern Lights Blvd Suite N	Anchorage	Alaska	Anchorage, with on-location service to Wasilla and Girdwood	Midtown salon doing bridal hair, makeup and nails in the studio or on location, for parties from a single bride to ten or more.	thebeautyroomalaska@gmail.com	(907) 279-9617	https://www.beautyroom.net/services/bridal	https://www.instagram.com/thebeautyroomboutique_/
Bridal Collective AK	Hair & Makeup	4050 Lake Otis Pkwy Ste 107	Anchorage	Alaska	Anchorage and surrounding areas	Bridal arm of Lady Wax Studio & Spa, pairing wedding hair and makeup with skin-prep and nail packages, each with a trial beforehand.	bridalcollectiveak@gmail.com	(907) 444-7415	https://lws-spa.com/bridal-collective-ak/	https://www.instagram.com/bridal_collective_ak/
Midnight Sun Cakery	Cake		Anchorage	Alaska		Appointment-only Anchorage cakery specialising in wedding and special-event cakes, each one baked and decorated to order.	inquiry@midnightsuncakery.com	907-229-0347	https://midnightsuncakery.com/	https://www.instagram.com/midnightsuncakery/
Arctic Moon Bakery	Cake		Anchorage	Alaska		Anchorage commercial kitchen making tiered buttercream and fondant wedding cakes, priced per serving; wedding dates book up well ahead.	arcticmoonbakery@gmail.com		https://arcticmoonbakery.com/	https://www.instagram.com/arcticmoonbakery/
Josh Vassar Films	Videography		Anchorage	Alaska	Alaska	Anchorage filmmaker blending cinematic and documentary styles, taking on a limited number of weddings and elopements each year.	hello@joshvassarfilms.com		https://www.joshvassarfilms.com/	https://www.instagram.com/joshvassar/
Yarrow & Co.	Florals		Girdwood	Alaska		Girdwood floral studio creating fresh and dried wedding and elopement flowers in earthy tones, inspired by foraging along Cook Inlet.	yarrow.and.co.alaska@gmail.com		https://yarrowandco.com/	https://www.instagram.com/yarrow.and.co/
Bagoy's Florist & Home	Florals	8250 Homer Dr	Anchorage	Alaska		Anchorage florist trading since 1922, whose professional design team handles wedding and event flowers alongside the shop.		(907) 522-1922	https://www.bagoys.com/	https://www.instagram.com/bagoys/
Wild Blossom Design	Florals		Anchorage	Alaska	Anchorage and surrounding areas	South Anchorage home-studio florist with 25 years' experience, now focused on wedding and event design and drawing on its own cutting garden.	jkennedy@wildblossomdesign.com	(907) 242-5843	https://wildblossomdesign.com/	https://www.instagram.com/wild.blossom.design/
Gardenwild Floral Design	Florals		Anchorage	Alaska	South-central Alaska including Talkeetna, Wasilla, Girdwood, Seward and Cooper Landing	Garden-inspired wedding flowers from an Anchorage grower and designer, using seasonal blooms that are locally grown wherever possible.	gretalewanski@gmail.com	907-300-5008	https://www.gardenwildfloral.com/wedding-flowers-alaska	https://www.instagram.com/gardenwildfloraldesign/`,
  },
  {
    name: "Anchorage: cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Vow & Velvet Co.	Cake		Anchorage	Alaska		Anchorage wedding cake studio designing from four signature collections, each tailored to the couple's palette, florals and venue.	vowandvelvetco@gmail.com		https://vowandvelvetco.com/	https://www.instagram.com/vowandvelvetco/
Lauren Roberts	Videography		Anchorage	Alaska		Anchorage filmmaker and photographer making editorial wedding films that weave personal archive footage in alongside the day itself.	hello@laurenroberts.com		https://laurenroberts.com/wedding-films	https://www.instagram.com/thatlaurengurl/
Wild & Beloved	Videography		Anchorage	Alaska	Alaska	Anchorage duo Trevor and Tyler filming weddings and elopements across Alaska, from Hatcher Pass to Girdwood, with photography as well.			https://www.thewildandbeloved.com/	https://www.instagram.com/thewildandbeloved/`,
  },
  {
    name: "Kenai Peninsula: photography, florals, catering and rentals",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jamie Taylor Photography	Photography	42365 Kalifornsky Beach Road	Soldotna	Alaska	Kenai Peninsula, Girdwood and Anchorage	Soldotna photographer covering weddings, elopements and vow renewals across the Kenai Peninsula, with engagement and portrait sessions also on offer.	jamie@jamietaylorphotography.com		https://jamietaylorphotography.com/	https://www.instagram.com/jamietaylorphotography/
Emily Jordan Photography	Photography		Seward	Alaska	Seward, Anchorage and the Kenai Peninsula	Seward-based photographer covering weddings, elopements, portraits and family sessions across the Kenai Peninsula, with published wedding packages.	emilyjordanphotos@gmail.com		https://emilyjordanphotography.com/	https://www.instagram.com/emilyjordanphotography_/
Joshua Veldstra Photography	Photography		Homer	Alaska	Alaska	Homer-raised photographer offering wedding, engagement, family and portrait sessions across Alaska, with published pricing and an online booking form.	joshuaveldstra@gmail.com		https://joshuaveldstra.com/	https://www.instagram.com/joshuaveldstra/
Jayme Huston Photography	Photography		Soldotna	Alaska	Kenai Peninsula, travelling for weddings elsewhere	Soldotna photographer covering weddings, elopements and portraits with a candid, cinematic style across the Kenai Peninsula and beyond.	jaymehustonphoto@gmail.com		https://www.jaymehustonphotography.com/	https://www.instagram.com/jaymehustonphotography/
Mary McKinley Photography	Photography		Homer	Alaska	Homer and the Kenai Peninsula	Homer-based photographer covering weddings and elopements, as well as couple, family, maternity and newborn sessions around the Kenai Peninsula.	marymckinleyphoto@gmail.com	907-435-1303	https://marymckinleyphoto.com/	
Alaska Stems	Florals		Homer	Alaska	Homer and the Kenai Peninsula	Homer flower farm and design studio that grows tulips and designs natural, elegant florals for weddings and events.	rachel@alaskastems.com	907-435-7209	http://www.alaskastems.com/	
Cook Inlet Gardens	Florals		Kenai	Alaska	Kenai, Soldotna and Nikiski	Peony farm and florist near Nikiski supplying fresh-cut wedding flowers, with full-service and DIY options and delivery across the northern Peninsula.	Office@cookinletgardens.com	907-953-1964	http://www.cookinletgardens.com	https://www.instagram.com/kenaiflowers/
Mel's Bakery & Cafe	Catering	43335 Kalifornsky Beach Road, Suite 22	Soldotna	Alaska	Soldotna and Kenai	Soldotna bakery and cafe whose catering arm supplies bridal suite brunches, cocktail hour appetisers, charcuterie carts and small cakes for weddings.		907-953-2351	https://melsalaska.com/	https://www.instagram.com/lavish_catering_ak/
CBC Rental & Supply	Rentals		Soldotna	Alaska	Soldotna, Kenai, Sterling, Kasilof, Homer and Seward	Soldotna rental shop hiring out tents with walls and lighting, tables, chairs, linens, dance floors and staging for weddings and parties.		907-262-7368	https://www.cbcrental.com/	`,
  },
];

export default batches;
