import type { VendorBatch } from "@/lib/vendor-batches";

// Arizona vendor batches. Every row's State is "Arizona". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Phoenix: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
The Hoskins	Photography		Phoenix	Arizona	Phoenix and Arizona	Aaron Hoskins photographs weddings in a documentary style with an editorial finish, working across Phoenix, Scottsdale and northern Arizona.	hoskinsa@gmail.com		https://www.thehoskinsphoto.com/	
Lia's Photography	Photography		Phoenix	Arizona	Phoenix, Scottsdale, Sedona and across Arizona	Husband-and-wife photographers Lia and Max, with over 15 years and more than 1,500 weddings behind them; a photo booth is also offered.	info@liasphotography.com	602-503-8019	https://www.liasphotography.com/	https://www.instagram.com/liasphotography2011/
Thomas Shull Photography	Photography		Phoenix	Arizona	Arizona and beyond	Phoenix photographer with a bright, colourful natural-light style, covering weddings, adventure elopements and South Asian celebrations.	hello@thomasshull.com	760-803-9444	https://www.thomasshull.com/	https://www.instagram.com/tjshull/
Mindy DeLuca Photography	Photography		Phoenix	Arizona	Arizona and destination weddings	Phoenix photographer with a candid, vivid style for Arizona and destination weddings, with wedding films also offered.	info@mindydeluca.com	602-332-6463	https://mindydeluca.com/	https://www.instagram.com/mindydeluca/
O'Honey Events	Planning		Scottsdale	Arizona	Scottsdale, Phoenix, Paradise Valley, Tempe, Mesa and across Arizona	Scottsdale planning studio offering full-service planning and day-of coordination at resorts and venues across the Phoenix area.	weddings@ohoneyevents.com	480-202-3365	https://www.ohoneyevents.com/	https://www.instagram.com/ohoneyevents/
Revel Wedding Co.	Planning		Scottsdale	Arizona	Arizona	Scottsdale planning company offering full-service planning, day-of logistics and custom celebration design for weddings across Arizona.			https://revelweddingco.com/	https://www.instagram.com/revelweddingcompany/
Satin & Slate Weddings	Planning		Scottsdale	Arizona	Scottsdale, Phoenix and destination weddings	Planner offering full, partial and wedding-day management, led by a founder trained in special events management and travelled in 30-plus countries.	satinandslateweddings@gmail.com		https://satinandslateweddings.com/	https://www.instagram.com/satinandslateweddings/
LUX Wedding Florist	Florals	2050 S 16th St Suite 107	Phoenix	Arizona	Phoenix and beyond	Full-service wedding and event floral design studio in the Phoenix Flower District, creating events since 2011.		602-707-6295	https://luxweddingflorist.com/	https://www.instagram.com/luxflorist/
White Poppy Floral Design	Florals	4024 E Weldon Ave	Phoenix	Arizona	Phoenix, Scottsdale and surrounding cities	Phoenix wedding and event florist designing bouquets and centrepieces, with work featured in magazines and on local news.	jb@whitepoppy.com	602-758-2581	https://whitepoppy.com/	https://www.instagram.com/white_poppy_floral/
Fleur de Vie	Florals		Scottsdale	Arizona	Scottsdale, Phoenix, Paradise Valley, Sedona and Southern California	Fine-art floral designer and stylist in Scottsdale creating wedding flowers and event styling, with an online floral estimate builder.	fleurdeviestudio@gmail.com		https://fleurdeviestudio.co/	https://www.instagram.com/fleurdeviestudio/
Ray the DJ	Music	201 E Southern Ave Suite 110	Tempe	Arizona	Phoenix and across Arizona	DJ company founded more than 45 years ago by Ray and Barbara Grace, providing ceremony and reception music, sound and lighting across the Valley.	info@raythedj.com	480-921-9665	https://raythedj.com/	https://www.instagram.com/ray.the.dj/
DJ G Weddings & Events	Music		Chandler	Arizona	All of Arizona, based in the Phoenix metro	Chandler-based DJ with 25-plus years and over 500 weddings, who also helps plan the running order and liaises with your other vendors.	garybsanders@gmail.com	480-280-7422	https://djgweddingsaz.com/	https://www.instagram.com/djgweddings/
No Limit Events	Music		Scottsdale	Arizona	Arizona, Las Vegas and destination events	Scottsdale DJ and production team specialising in South Asian and multicultural weddings, with MC, dhol, lighting and LED video walls.			https://www.nolimiteventsaz.com/	https://www.instagram.com/nolimiteventsaz1/
Elite Event Services	Music		Phoenix	Arizona	Scottsdale, Phoenix, Peoria, Gilbert, Chandler and surrounding areas	DJ company run by owners Jay and Heather, providing wedding and event DJ services across the Valley since 2001.			https://www.eliteeventaz.com/	
Fresh From The Kitchen	Catering	3316 N 3rd St Suite 8	Phoenix	Arizona	Phoenix, Scottsdale, Paradise Valley, Chandler, Avondale, Glendale and statewide	Chef-owned Phoenix caterer established in 2008, cooking with locally sourced, hormone-free ingredients for weddings and events.		602-694-1197	https://www.freshfromthekitchenllc.com/	https://www.instagram.com/fftk_catering2/
Chef Phoenix Catering	Catering	1440 S Country Club Dr Ste 10	Mesa	Arizona	Phoenix, Scottsdale, Paradise Valley, Mesa, Chandler, Gilbert and Tempe	Mesa-based caterer serving weddings at venues and private locations across Phoenix and the East Valley, from intimate dinners to large receptions.	chef@chefphoenix.com	602-818-2779	https://chefphoenix.com/catering/weddings	https://www.instagram.com/chefphoenix/
Classic Catering	Catering	9855 W Peoria Ave	Peoria	Arizona	Phoenix, Scottsdale, Mesa, Tempe, Peoria, Glendale and surrounding areas	Peoria caterer dating from 1982, with wedding menus spanning Italian, Mexican, Indian and barbecue, plus complimentary tastings.	events@classiccateringltd.com	623-933-4903	https://classiccateringltd.com/	
First Blush Beauty	Hair & Makeup		Scottsdale	Arizona	Scottsdale, Paradise Valley, Fountain Hills, Mesa, Chandler, Gilbert and surrounding areas	On-location bridal hair and makeup team led by Leah, focused on natural, classic glam, with lashes included in bridal packages.	hello@firstblushbeauty.com	480-868-5680	https://www.firstblushbeauty.com/	
Kensington Makeup	Hair & Makeup		Scottsdale	Arizona	Greater Phoenix area and beyond	Woman-owned, on-location hair and makeup team with in-house trained artists, working across all skin tones and hair textures.	hello@kensingtonmakeup.com	480-717-2077	https://kensingtonmakeup.com/	https://www.instagram.com/kensingtonmakeup/
Viviana Bridal Beauty	Hair & Makeup		Phoenix	Arizona	Phoenix and surrounding areas, plus destination weddings	Phoenix team bringing bridal hair styling and makeup to the wedding party on site, for local and destination weddings.	vivianabridalbeauty@gmail.com		https://www.vivianabridalbeauty.com/	https://www.instagram.com/vivianmarianibeauty/
Silver Rose Bakery	Cake	2814 W Bell Rd Suite 1451	Phoenix	Arizona	Phoenix, Scottsdale and beyond	North Phoenix bakery making custom wedding cakes along with cake pops and pastries, delivering across Phoenix and Scottsdale.		623-499-2222	https://silverrosebakery.com/collections/wedding-cakes	https://www.instagram.com/silverrosebakery/
Bamboo Bakery	Cake	1619 E Monte Vista Rd	Phoenix	Arizona	Phoenix, Scottsdale, Glendale and Tempe	Central Phoenix bakery making tiered wedding cakes to order, with regular cake-tasting evenings for couples.	orders@bamboobakery.com	602-246-8061	https://www.bamboobakery.com/	
Pasteleria Azteca	Cake	5602 N 27th Ave	Phoenix	Arizona		Mexican bakery and custom cake shop in west Phoenix making wedding cakes and sheet cakes alongside traditional Mexican pastries.	contact@bakeryazteca.com	623-247-8493	https://www.bakeryazteca.com/weddings-cakes-phoenix/	https://www.instagram.com/azteca_bakery/
Serendipity Cinematography	Videography		Phoenix	Arizona	Scottsdale, Gilbert, Mesa, Chandler, Queen Creek, Sedona and destination weddings	Phoenix team of filmmakers and editors led by Taryn, making hand-crafted cinematic wedding films across the Valley.	taryn@serendipitycinema.com		https://serendipitycinema.com/	https://www.instagram.com/serendipitycinema/
Mina Studio	Videography		Phoenix	Arizona	Phoenix, Scottsdale, Chandler, Gilbert, Mesa, Tempe and across Arizona	Phoenix photo and video studio making cinematic wedding films, with a specialism in Indian and South Asian weddings.			https://www.minavideoproduction.com/	https://www.instagram.com/minavideoproduction/
AZ Film Company	Videography		Phoenix	Arizona	Arizona and out-of-state destinations	Phoenix videographer making documentary-style wedding films with a candid, unstaged approach, travelling out of state for about half the season.			https://www.azfilmcompany.com/	https://www.instagram.com/azfilmcompany/
Heartcraft Wedding Films	Videography		Phoenix	Arizona	Phoenix and across Arizona	Phoenix studio founded by Nick Gaiski, making cinematic, heirloom-style wedding films with an unobtrusive presence and limited yearly bookings.	contact@heartcraftweddingfilms.com	480-415-8288	https://heartcraftweddingfilms.com/	https://www.instagram.com/heartcraftweddingfilms/
`,
  },
  {
    name: "Tucson: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Lucy B. Photography	Photography		Tucson	Arizona	Tucson, Phoenix, Sedona, Grand Canyon, Utah and Southern California	Tucson photographer for elopements and intimate weddings, with adventure-style, multi-location coverage across desert and mountain settings.	hello@lucybouman.com		https://www.lucybouman.com/	https://www.instagram.com/lucybphotography/
Melissa Holland Photography	Photography		Tucson	Arizona	Tucson and all of Southern Arizona	Tucson photographer with a fine-art, documentary approach to weddings and engagement sessions across Southern Arizona.			https://www.mhollandphotography.com/	https://www.instagram.com/mhollandphoto/
Anita McLeod Photography	Photography		Tucson	Arizona	Tucson and Arizona	Documentary-style wedding and elopement photographer working between Tucson and Willcox, with more than 200 weddings since 2014.			https://anitamcleodphotography.com/	https://www.instagram.com/anitamcleodphotography/
Jane Castle Events	Planning		Tucson	Arizona	Tucson and all of Arizona	Tucson planner offering full planning, month-of or day-of coordination and a la carte support for weddings, running since 2014.	hello@janecastleevents.com	520-222-6551	https://www.janecastleevents.com/	
Paloma Events	Planning		Tucson	Arizona	Tucson, Arizona and destination weddings	Tucson planning and design studio that takes on about ten weddings a year and avoids back-to-back weekends.			https://palomaeventsco.com/	https://www.instagram.com/palomaevents/
Celebrations by Design	Planning		Tucson	Arizona	Tucson, Arizona	Small Tucson event design company offering day-of coordination, planning and handcrafted design for weddings and other celebrations.	cbdweddingsaz@gmail.com	520-405-1400	https://www.celebrationsbydesignaz.com/	
In Full Bloom	Florals		Tucson	Arizona		Tucson floral studio that works only on weddings, helping couples choose blooms that fit their personal style.	tanya@infullbloomweddings.com	520-498-0505	https://www.infullbloomweddings.com/	https://www.instagram.com/infullbloomfloralstudio/
Thistle	Florals		Tucson	Arizona	Tucson	Women-owned Tucson flower shop on East 22nd Street making textural, romantic seasonal florals for weddings and events.	info@thistletucson.com	520-812-2687	https://www.thistletucson.com/	
Alexis Grace Florals	Florals		Tucson	Arizona	Tucson and Southern Arizona	Tucson wedding florist offering bouquets, corsages and ceremony arch additions with a colourful, romantic style.			https://www.alexisgraceflorals.com/	
Mariachi Tucson	Music		Tucson	Arizona	Tucson	Tucson mariachi group for weddings, quinceaneras and other celebrations, with online booking and a weekly restaurant residency.	mariachitucson@aol.com	520-339-4630	https://www.mariachitucson.com/	
Mariachi Alegre de Tucson	Music		Tucson	Arizona	Tucson and Southern Arizona	Four-piece traditional mariachi band playing ceremonies, cocktail hours, rehearsal dinners and receptions in Southern Arizona.		520-981-3459	https://mariachialegredetucsonaz.com/	
Classy Events 520	Music		Tucson	Arizona	Southern Arizona	Tucson wedding DJ service that also supplies photo booths, cold spark fountains, up-lighting and party buses.		520-260-5085	https://www.tucsondeejay.com/	
Atlas Catering & Events	Catering		Tucson	Arizona	Southern Arizona	Chef-driven Tucson caterer with scratch-made menus and bar service, and the house caterer for the Historic Bates Mansion.	orders@atlascateringtucson.com	520-909-3979	https://www.atlascateringtucson.com/weddings	https://www.instagram.com/atlascateringevents/
Salsa Verde Catering	Catering	3894 N Oracle Rd	Tucson	Arizona	Tucson	Family-owned Tucson Mexican caterer making fresh dishes from scratch for weddings and family celebrations of any size.		520-771-8607	https://www.salsaverdemx.com/catering	https://www.instagram.com/salsaverdemx/
Creative Catering	Catering		Tucson	Arizona	Tucson and surrounding areas	Family-run Tucson off-premise caterer in business for over 36 years, handling weddings with full event and vendor coordination.	info@tucsoncreativecatering.com	520-690-0146	https://tucsoncreativecatering.com/	https://www.instagram.com/creativecateringtucson/
The Powder Room	Hair & Makeup		Tucson	Arizona	Tucson	On-location Tucson team of bridal hair and makeup artists, with a preferred-vendor list and online enquiry for booking.		520-487-6561	https://www.powderroomartistry.com/	
Mery's Beauty	Hair & Makeup		Tucson	Arizona	Tucson	Tucson hair and makeup artist offering personalised bridal looks that aim to enhance natural features and photograph well.			https://www.merysbeauty.com/	https://www.instagram.com/meribelastudio/
Heather Van Houten Makeup & Hair	Hair & Makeup		Tucson	Arizona	Tucson and Arizona	Tucson team of hair and makeup artists for weddings, including South Asian bridal styling, boudoir and special events.			https://www.hvhartists.com/	
Ambrosia Cakes	Cake		Tucson	Arizona	Tucson and surrounding areas	Tucson wedding cakery making custom cakes and dessert tables, with attention to both flavour and design.	annie@ambrosiacakestucson.com	520-390-9319	https://ambrosiacakestucson.com/	https://www.instagram.com/ambrosiacakestucson/
Dolce Pastello	Cake	120 S Avenida del Convento	Tucson	Arizona	Tucson	Award-winning Tucson cake shop known for tres leches cakes, making pasteles for weddings and other celebrations.	dolcepastello2011@gmail.com	520-207-6765	https://www.dolcepastello.com/	https://www.instagram.com/dolcepastellocakes/
Jamie-Cakes Bakery Boutique	Cake	314 S Convent Ave	Tucson	Arizona	Tucson area	By-appointment Tucson cake boutique specialising in custom wedding cakes, with gourmet cupcakes and desserts on the side.		520-548-1946	https://www.jamie-cakes.com/	https://www.instagram.com/jamiecakesarizona/
Jen Sawyer Video	Videography		Tucson	Arizona	Arizona	Tucson filmmaker making cinematic wedding films that focus on real moments, with recent work at Tubac and Tohono Chul.			https://jensawyervideo.com/	https://www.instagram.com/jensawyervideocreator/
Artifact Video Productions	Videography		Tucson	Arizona		Tucson video and photo production company covering weddings alongside commercial work.	artifactvideo@gmail.com		https://www.artifactvideo.com/	https://www.instagram.com/artifact_video/
Black Sheep Filmworks	Videography		Tucson	Arizona		Tucson videographer making modern wedding films, also working on corporate video.	stepheny@blacksheepfilmworks.com		https://blacksheepfilmworks.com/	
`,
  },
  {
    name: "Sedona and Flagstaff: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hailey Golich Photography	Photography		Sedona	Arizona	Sedona and Northern Arizona	Sedona-based wedding and elopement photographer covering ceremonies, portraits and adventurous sessions among the red rocks.	haileygolichphotography@gmail.com	928-651-9103	https://haileygolich.com/	
Julia Romano Photography	Photography		Flagstaff	Arizona	Flagstaff, Sedona and Northern Arizona	Flagstaff photographer and NAU alum shooting colourful, natural weddings, micro-weddings and elopements across Northern Arizona.	info@juliaromanophotography.com		https://juliaromanophotography.com/	https://www.instagram.com/juliaromanophotography/
Ryan Williams Photography	Photography		Flagstaff	Arizona	Sedona, Flagstaff and the Grand Canyon	Former newspaper photographer now in Flagstaff, covering weddings and elopements from Sedona to the Grand Canyon and Horseshoe Bend.	info@ryanwilliamsphotography.com	928-864-6074	https://www.ryanwilliamsphotography.com/	https://www.instagram.com/ryanwilliamsphotography/
Heart of Sedona Weddings	Planning		Sedona	Arizona	Sedona	Husband-and-wife team pairing a wedding planner with an officiant, offering Sedona and Tlaquepaque packages and ceremonies in Spanish.		928-862-0329	https://heartofsedonaweddings.com/	https://www.instagram.com/heartofsedonaweddings/
Hitch Without A Glitch	Planning		Gilbert	Arizona	Phoenix, Sedona and Tucson	Day-of and month-of wedding coordination from a Gilbert-based coordinator who regularly works Sedona weddings as well as Phoenix and Tucson.	janet@hitchwithoutaglitch.com	480-757-5668	https://www.hitchwithoutaglitch.com/	https://www.instagram.com/hitch_without_a_glitch/
Mazon Signature Services	Planning		Gilbert	Arizona	Flagstaff, Sedona, Prescott and Arizona	Gilbert-based planners offering full, partial and day-of coordination, with mountain weddings around Flagstaff, Sedona and Prescott.	connect@mazonsignatureservices.com	480-256-9540	https://www.mazonsignatureservices.com/areas/flagstaff.html	https://www.instagram.com/mazonsignatureservices/
Four Sisters Floral	Florals		Flagstaff	Arizona	Northern Arizona	Appointment-only floral design studio in Flagstaff that takes wedding and event contracts only, working across Northern Arizona.	hello@foursistersflagstaff.com		https://www.foursistersflagstaff.com/	https://www.instagram.com/foursistersfloral/
Floral Arts of Flagstaff	Florals	124 S Beaver St	Flagstaff	Arizona	Flagstaff	Downtown Flagstaff flower shop open since 1973, offering wedding packages from bouquets and boutonnieres to ceremony and reception flowers.	floralartsofflagstaff@gmail.com	928-779-0319	https://www.floralartsltd.com/wedding-flowers	https://www.instagram.com/floralartsofflagstaff/
7000 Feet of Sound	Music		Flagstaff	Arizona	Flagstaff, Sedona, Prescott and Phoenix	Flagstaff DJ company with more than 1,000 weddings behind it, offering tiered DJ and MC packages across Northern Arizona.	bookings@7000ftofsound.com	928-224-2523	https://www.7000ftofsound.com/	https://www.instagram.com/7kofsound/
SKM Entertainment	Music		Scottsdale	Arizona	Flagstaff, Sedona and Prescott	Scottsdale DJ and MC company of 35 years with a dedicated Northern Arizona team, plus photo booths and event lighting.	info@skmentertainment.com	480-423-1114	https://www.skmentertainment.com/contact-flagstaffsedonaprescott	https://www.instagram.com/skmentertainment/
Main Street Catering	Catering	408 E Route 66	Flagstaff	Arizona	Flagstaff, Sedona and the Grand Canyon	Flagstaff caterer since 1988 serving cocktail receptions, buffets, plated dinners and family-style feasts across Northern Arizona.	info@mainstreetcateringflagstaff.com	928-851-4293	https://mainstreetcateringflagstaff.com/weddings	https://www.instagram.com/mainstreetcateringflagstaff/
Northern Arizona Glam Squad	Hair & Makeup	9 N Elden St, Ste 101	Flagstaff	Arizona	Northern Arizona	Flagstaff team of bridal hair stylists and makeup artists that travels to weddings around Northern Arizona.	info@nazglamsquad.com	928-255-3788	https://nazglamsquad.com/	https://www.instagram.com/northernazglamsquad_weddings/
Sedona Beauty Team	Hair & Makeup		Sedona	Arizona	Sedona	Sedona group of hair stylists and makeup artists that comes to the venue for brides, wedding parties and elopements.	sedonabeautyteam@gmail.com		https://sedonabeautyteam.com/	https://www.instagram.com/sedonabeautyteam/
Take The Cake Custom Cakes	Cake		Cottonwood	Arizona	Cottonwood, Sedona and Camp Verde	Custom wedding cake maker in Cottonwood designing tiered, quilted and floral cakes for couples in Sedona and the Verde Valley.	takethecakeaz@gmail.com		https://www.takethecakeaz.com/	https://www.instagram.com/takethecakeaz/
Dulce Passion Bakery	Cake	320 N State Rte 89A	Sedona	Arizona	Northern Arizona	Sedona bakery making custom wedding cakes and dessert tables since 2018, also known locally for quinceañera cakes.	dulcepassionbakery@gmail.com		https://dulcepassionbakery.com/	
Sedona Wedding Films	Videography		Sedona	Arizona	Sedona and Northern Arizona	Sedona team making story-driven wedding films, from adventure elopements and micro-weddings to full traditional celebrations.	shannon@sedonaweddingfilms.com	928-275-4145	https://www.sedonaweddingfilms.com/	
Leslie Allred Films	Videography		Flagstaff	Arizona	Sedona, Flagstaff and Northern Arizona	Videographer working out of Sedona and Flagstaff, filming weddings alongside commercial work across Northern Arizona and beyond.	leslieallredfilms@gmail.com		https://www.leslieallredfilms.com/	https://www.instagram.com/leslieallredfilms/
`,
  },
  {
    name: "Phoenix: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
One Take Photography	Photography		Gilbert	Arizona	Gilbert, Queen Creek, Chandler, Mesa, Tempe, Scottsdale	Gilbert photographer covering weddings alongside maternity, newborn and family sessions, which suits couples who want one photographer for every stage.			https://www.onetakephotography.com/	https://www.instagram.com/onetakephotographyaz/
Santiago Almada Photography	Photography		Phoenix	Arizona	Arizona and destination	Phoenix photographer specialising in South Asian celebrations, with a storytelling approach centred on candid moments and the wider family.	contact@salmada.com	480-845-2098	https://salmada.com/	https://www.instagram.com/santiagoalmadaphotography/
Maya Papaya Pictures	Photography		Phoenix	Arizona	Arizona	Photographer with a filmmaking background who shoots weddings in a cinematic, fly-on-the-wall style and coaches camera-shy couples with relaxed prompts.			https://mayapapayapictures.com/	https://www.instagram.com/mayapapayapictures/
Tara Nichole Photo	Photography		Phoenix	Arizona	Southwest and destination	Phoenix photographer with a documentary-leaning, adventurous approach, keeping weddings unforced so couples can enjoy the day.			https://taranicholephoto.com/	https://www.instagram.com/_thetaranichole_/
Anna Marisol Photography	Photography		Goodyear	Arizona	Phoenix area	West Valley photographer covering the whole wedding day from getting ready to the evening, with a bright, artistic style praised by past couples.	anna@annamarisol.com	(480) 652-8943	https://www.annamarisol.com/	https://www.instagram.com/anna_marisol/
All Occasions Photography	Photography		Queen Creek	Arizona	Arizona	Queen Creek group of Arizona photographers handling weddings and engagements as well as family, newborn and corporate work, a practical option for East Valley couples.	admin@alloccasionsphotographyaz.com	(602) 761-7733	https://alloccasionsphotographyaz.com/	https://www.instagram.com/alloccasionsphotography/
Wedding Mode	Planning		Scottsdale	Arizona	Scottsdale and Phoenix	Scottsdale planner offering month-of coordination and partial design for resort and luxury venue weddings, including Four Seasons and El Chorro.	hello@wedding-mode.com		https://www.wedding-mode.com/	https://www.instagram.com/weddingmodeco/
Events to Remember LLC	Planning		Chandler	Arizona	Greater Phoenix	Chandler wedding coordinator known for hands-on day-of support, from setup and rehearsal through to cleanup.	nicki@eventstorememberllc.com	602-741-2920	https://eventstorememberllc.com/	https://www.instagram.com/eventstorememberllc/
Simply Beautiful Weddings and Events	Planning		Chandler	Arizona	Arizona	Chandler planner combining full planning, day-of coordination and custom floral design, with no fixed packages so each wedding is priced to suit.			https://weddingplanningaz.com/	https://www.instagram.com/simplybeautifulweddings/
Laki Events + Design	Planning		Scottsdale	Arizona	Scottsdale and Phoenix	Planning and design team giving each couple a custom planning portal and a design deck with options at several price points.			https://lakieventsanddesign.com/	https://www.instagram.com/lakievents/
Desert Daisy Events	Planning		Mesa	Arizona	Mesa and Arizona	Bilingual Mesa planner for weddings and quinceañeras, with full planning, day-of coordination, micro weddings, elopements and a decor rental catalogue.			https://desertdaisyevents.com/	https://www.instagram.com/desertdaisyaz/
Apropos Creations	Planning	101 N. Colorado Street #1015	Chandler	Arizona	Arizona and destination	Chandler planner focused on South Asian and multicultural weddings, handling multi-day, multi-event celebrations as well as traditional American ones.	joann@aproposcreations.com	480-216-4630	https://aproposcreations.com/	https://www.instagram.com/aproposcr8ions/
Journey Flowers	Florals	9318 N 95th Way, Suite A109	Scottsdale	Arizona	Scottsdale and Valley-wide	Scottsdale studio designing custom wedding flowers from classic to modern, with a consultation followed by a personalised proposal.	wecare@scottsdalesflorist.com	(602) 679-9871	https://www.scottsdalesflorist.com/	
La Paloma Blanca Floral Designs	Florals	8711 E Pinnacle Peak Rd, Suite A101	Scottsdale	Arizona	North Scottsdale, Cave Creek, Carefree, Paradise Valley	North Scottsdale florist creating bouquets, arches and centrepieces in styles from romantic garden to sophisticated urban.		480-515-1478	https://blancafloral.com/	https://www.instagram.com/lapalomablancafloral/
Le Bouquet Florist	Florals		Scottsdale	Arizona	Scottsdale	Family-run Scottsdale flower shop doing wedding bouquets, arches, bud vases and garlands in any colours, with no minimum order.		(480) 991-8800	https://www.lebouquetaz.com/	https://www.instagram.com/lebouquetflorist/
Azelly Flowers	Florals	1841 S Balboa Dr	Gilbert	Arizona	Gilbert, Phoenix, Chandler, Scottsdale, Mesa	Gilbert studio offering bridal, ceremony and reception florals with free consultations, plus a detailed quote after the meeting.		(833) 329-3559	https://www.azelly.com/	
The Sage Farm	Florals		Gilbert	Arizona	Gilbert and East Valley	Home-based Gilbert florist specialising in lush garden-style wedding and event flowers, who also teaches floral workshops.			https://thesagefarm.com/	https://www.instagram.com/thesagefarm/
Cactus Bloom Floral	Florals		Phoenix	Arizona	Phoenix	Phoenix florist making romantic, garden-inspired wedding designs with a luxury finish.			https://www.cactusbloomaz.com/	
Citron Sound Services DJs	Music	9450 E. Nance Street	Mesa	Arizona	Phoenix, Scottsdale, Chandler, Tempe, Fountain Hills	Mesa DJ service whose specialty is weddings, also covering anniversaries, bar and bat mitzvahs and corporate events across the Valley.		480-966-2929	https://www.citronsound.com/	
Allegro Quartet	Music		Phoenix	Arizona	Metro Phoenix and Arizona	String quartet with over 35 years of wedding work, offering classical ceremony music and a large contemporary playlist for receptions.	allegroquartet.arizona@gmail.com	(480) 948-1866	https://allegroquartet.com/	
Erimos String Quartet	Music		Phoenix	Arizona	Phoenix area, Scottsdale, Glendale, Sedona	Phoenix string quartet playing hundreds of weddings since 2016, with a pop-heavy song library for prelude, ceremony and cocktail hour.		(480) 741-8218	https://www.erimosquartet.com/	
Innocenti Strings	Music		Phoenix	Arizona	Phoenix, Scottsdale, Tempe, Mesa, Chandler, Glendale, Peoria	Phoenix string solo, duo, trio, quartet and orchestra options mixing classical and pop, with free travel within 25 miles of downtown.		773-217-9007	https://www.innocentistrings.com/	https://www.instagram.com/innocentistrings/
Shining Star Entertainment	Music		Phoenix	Arizona	Arizona	Phoenix concierge entertainment company booking local and national acts for weddings, charities and corporate events.	jodi@shiningstarentertainmentaz.com	(602) 370-6928	https://shiningstarentertainmentaz.com/	
Benedict's Catering & Events	Catering	5555 East Bell Road, Suite 6	Scottsdale	Arizona	Scottsdale, Paradise Valley and the Phoenix metro	Full-service Scottsdale caterer running weddings with its own events team, from menu design through service across the north Valley.	hello@benedictscaterers.com	602-992-3337	https://www.benedictscaterers.com/	https://www.instagram.com/benedictscaterers/
Santi's Catering	Catering		Phoenix	Arizona	Throughout the Phoenix Valley	Phoenix caterer that focuses on weddings and corporate events, shaping menus around each couple's style, theme and budget.			https://www.santiscatering.com/	https://www.instagram.com/santiscatering/
The Local Caterer	Catering		Mesa	Arizona	Mesa, Phoenix, Scottsdale, Chandler and Gilbert	Mesa caterer building chef-made wedding menus for East Valley couples, from small ceremonies to large receptions, with quotes returned within a day.	info@thelocalcaterer.com	480-718-1671	https://thelocalcaterer.com/	https://www.instagram.com/thelocalcaterer/
AZ Inspirations Catering	Catering	2400 W Medtronic Way, Suite 2	Tempe	Arizona	Phoenix, Paradise Valley, Tempe, Scottsdale, Gilbert and Peoria	Tempe caterer offering plated dinners, buffets, stations and bar service, with linens and rentals handled and dietary needs planned in at tastings.	info@inspirationscateringaz.com	480-241-7621	https://inspirationscateringaz.com/	https://www.instagram.com/azinspirationscatering/
Tableside Gourmet	Catering		Scottsdale	Arizona	Scottsdale and the greater Phoenix area	Family-run Scottsdale caterer with over 25 years behind it, using locally sourced ingredients and handling setup, service and clear-down for weddings.	tablesidegourmet@gmail.com	480-748-8194	https://www.tablesidegourmet.com/	https://www.instagram.com/tableside_gourmet/
Carmen's AZ Catering	Catering	2375 E Camelback Rd, Suite 600	Phoenix	Arizona	Phoenix, Scottsdale, Chandler, Mesa, Tempe, Gilbert, Glendale, Peoria and Queen Creek	Family-run Mexican caterer making tortillas and taco bars from scratch, a relaxed, budget-friendly pick for receptions, rehearsal dinners and showers.		480-242-5160	https://www.carmenstamalesonline.com/	https://www.instagram.com/carmensazcatering/
Winové Pro Artists	Hair & Makeup	4700 W Thomas Rd, Ste 102	Phoenix	Arizona	Phoenix Valley, with virtual consultations for destination brides	Phoenix hair and makeup team, formerly Bridal4theWin, known for airbrush glam and long-wear hair, with no travel fees across the Valley.	winoveproartists@gmail.com	623-521-5553	https://www.winoveprobeauty.com/	https://www.instagram.com/winoveprobeauty/
Makeup by Diana	Hair & Makeup		Chandler	Arizona	Phoenix metro, with travel across Arizona	Chandler makeup artist travelling to homes, hotels and venues, with bridal packages sized for the bride alone or a larger party and work across all skin tones.	contactmakeupbydiana@gmail.com	734-765-9073	https://www.makeupbydiana.com/	https://www.instagram.com/makeupbydianaaz/
Work with Menaka	Hair & Makeup	7102 E Baseline Rd #106	Mesa	Arizona	Phoenix, Scottsdale, Glendale, Chandler, Tempe, Gilbert and Peoria	Mesa artist specialising in South Asian bridal makeup and hair, including men's grooming, bridal facials and travel to micro weddings.	workwithmenaka@gmail.com	425-686-5245	https://www.workwithmenaka.com/	
Le Beige Beauty	Hair & Makeup	4203 N Brown Ave, Ste F	Scottsdale	Arizona	Scottsdale studio, travelling across Arizona	Old Town Scottsdale studio doing South Asian and Western bridal makeup and hair, plus flower girls, hair extensions and private makeup classes.	info@lebeigebeauty.com	480-618-1328	https://lebeigebeauty.com/	https://www.instagram.com/LEBEIGEBEAUTY/
Makeup by Laly Harr	Hair & Makeup		Mesa	Arizona	Mesa, Chandler, Gilbert, Tempe, Scottsdale, Queen Creek and Phoenix	Mobile Mesa artist offering airbrush and traditional bridal makeup, updos, boho braids and tape-in extensions, with trial sessions available.			https://affordableeventmakeup.com/	https://www.instagram.com/makeupbylalyharr/
Savante Salon	Hair & Makeup	1110 S Gilbert Rd, Suite 102	Gilbert	Arizona	Gilbert and East Valley venues	Gilbert Town Square salon doing bridal hair and makeup previews and wedding-day styling for the bride and bridesmaids, in the salon or at the venue.	info@savantesalon.com	480-503-4247	https://www.savantesalon.com/	
Floured Bakery	Cake		Mesa	Arizona	Mesa and the Valley	Mesa bakery making custom wedding cakes from simple to elaborate, with a $30 tasting box credited back if you book.			https://flouredbakery.com/	https://www.instagram.com/flouredcupcakes/
Piece of Cake Desserts	Cake	1275 East Baseline Road #116	Gilbert	Arizona	Gilbert and across Arizona	Gilbert wedding cake studio recommended by many Arizona venues, with a tasting consultation, cupcakes and a wider dessert menu.		602-628-4194	https://www.pieceofcakeaz.com/	https://www.instagram.com/pieceofcakeaz/
K-Cakes Bakery	Cake		Chandler	Arizona	Chandler and the Phoenix metro	Woman-owned Chandler bakery specialising in eggless and vegan custom cakes, including Indian fusion flavours, for wedding tiers by appointment.		480-370-7468	https://chandlercustomcake.com/	
Maeflour	Cake		Phoenix	Arizona	Phoenix, Scottsdale and the Valley	Phoenix bakery making hand-painted fondant wedding cakes priced by guest count, with gluten-free macarons and dairy-free options on request.			https://maeflourcakes.com/	https://www.instagram.com/siftbakehouseaz/
Tacos n Cakes	Cake	2610 W Baseline Rd #114	Phoenix	Arizona	Phoenix and surrounding Valley	Phoenix pastelería, formerly Pastelería Elizabeth, baking wedding and quinceañera cakes from scratch, with tres leches as its signature flavour.		602-460-0658	https://www.tacosncakes.com/	https://www.instagram.com/tacosncakes/
Whisk & Paddle Bakeshop	Cake	1140 N Gilbert Road, #106	Gilbert	Arizona	Gilbert and the East Valley	Gilbert bakeshop, formerly Sue Jacobs Cakes, making custom wedding cakes and dessert tables with cupcakes, pies, bars and tarts.	info@whiskandpaddleaz.com	602-502-7809	https://www.whiskandpaddleaz.com/	https://www.instagram.com/whiskandpaddle_az/
Chase Kunkel Films	Videography		Phoenix	Arizona	Phoenix, Arizona	Phoenix filmmaker making story-driven wedding films, with highlight reels, teasers and separate edits of toasts, ceremonies and receptions.			https://www.chasekunkelfilms.com/	https://www.instagram.com/chasekunkelfilms/
Everlasting Cinema	Videography		Phoenix	Arizona	Phoenix, Sedona and destination weddings	Phoenix wedding film team using slow motion, aerial footage and careful audio, and covering Indian and destination weddings.	booking@everlastingcinema.com	602-769-3963	https://everlastingcinema.com/	https://www.instagram.com/everlasting_cinema/
Arizona Wedding Video	Videography		Phoenix	Arizona	Phoenix, Scottsdale, Mesa, Sedona, Flagstaff and the Grand Canyon	Owner-filmed documentary and cinematic wedding videos since 2005, with highlight films and Grand Canyon coverage across Arizona.	rmresler@gmail.com	602-618-2033	https://azweddingvideo.com/	https://www.instagram.com/azweddingvideo/
Awesome Phoenix	Videography		Scottsdale	Arizona	Arizona	Scottsdale videographer and photographer making relaxed, playful wedding films, with a short highlight reel and proposal coverage on offer.			https://www.awesome-phoenix.com/	https://www.instagram.com/awesomephoenix_/
`,
  },
  {
    name: "Tucson: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
LaShay and Light	Photography		Tucson	Arizona	Tucson, Vail, Oro Valley, Marana, Sahuarita	Documentary-style wedding and elopement photographer who delivers every usable photo and mixes candid frames with posed portraits.			https://lashayandlight.com/	https://www.instagram.com/lashayandlight/
Chisum Portrait Co.	Photography		Tucson	Arizona	Tucson, Oro Valley, Marana and Southern Arizona	Editorial-style wedding and elopement photography with shorter ceremony-only or full-day coverage, plus engagement sessions.	ChisumPortraitCo@gmail.com	(520) 261-7135	https://www.chisumportraitco.com/	
Melissa Fritzsche Photography	Photography		Tucson	Arizona	Tucson and destination weddings	Refined, romantic and natural wedding and elopement photography, with time spent getting to know each couple before the day.			https://melissafritzschephotography.com/	https://www.instagram.com/melissafritzschephotography/
Amore Events Tucson	Planning		Tucson	Arizona	Tucson	Mother-daughter team handling budgets, timelines and day-of coordination for Tucson weddings and other celebrations.			https://amoreeventstucson.com/	https://www.instagram.com/amoreevents.tucson/
Perfectly Planned Celebrations & Design	Planning	460 W. Roger Rd, Ste. 101	Tucson	Arizona	Arizona, California and Nevada	Tucson planner and florist who also handles decor, invitations and rentals in-house, led by an owner with over 20 years in the trade.		(520) 603-4971	https://www.perfectlyplannedbycandida.com/	https://www.instagram.com/perfectlyplannedcelebrations/
Bloom Maven	Florals	160 South Avenida del Convento	Tucson	Arizona	Tucson	Floral studio making custom wedding flowers with desert-inspired textures and a modern, polished look.	info@bloommaven.com	(520) 534-9997	https://www.bloommaven.com/	https://www.instagram.com/bloommaven/
Willows and Whimsy Flower Shop	Florals		Tucson	Arizona	Greater Tucson, Oro Valley, Marana, Vail, Sahuarita, Green Valley	Natural, whimsical wedding and everyday flowers with delivery to Tucson-area resorts and venues across the south-east valley.	willowsandwhimsyflowershop@gmail.com	(520) 401-1344	https://willowsnwhimsyflowershop.com/	
Posh Petals	Florals	1171 East Rancho Vistoso Blvd, Suite 121	Oro Valley	Arizona	Oro Valley and Tucson	Custom wedding and event florals from an Oro Valley studio that also runs workshops and daily flower delivery.	petalspetalspetals@gmail.com	520-408-0101	https://petalspetalspetals.com/	https://www.instagram.com/petalspetalspetals/
DJ Raza	Music	4558 N 1st Ave Suite 130	Tucson	Arizona	Tucson, Phoenix and across Arizona	Wedding DJ offering live mixing, a polished MC and a coordinated timeline for weddings and upscale events around the state.	mail@djraza.com	(520) 449-0993	https://www.djraza.com/	https://www.instagram.com/djrazaofficial/
Phox Entertainment Group	Music		Tucson	Arizona	Tucson and surrounding areas	Veteran-owned wedding DJ company with over 20 years of experience, focused on filling the dance floor with the couple's requests.	nathaniel@phoxentertainmentgroup.com	520-222-6233	https://www.phoxentertainmentgroup.com/	https://www.instagram.com/phoxentertainmentgroup/
Tony G DJ and Karaoke Service	Music		Tucson	Arizona	Tucson	Tucson DJ and karaoke service with over 40 years in music, treating weddings as its specialty alongside other private events.	TonyG@TonyGDJ.com	(520) 250-8669	https://tonygdj.com/	
Tucson Catering Company	Catering		Tucson	Arizona	Tucson, Oro Valley, Marana	Chef-led wedding caterer with culinary-school trained cooks and a white-glove approach to receptions in Tucson, Oro Valley and Marana.	Events@TucsonCatering.com	520-500-7072	https://tucsoncatering.com/	https://www.instagram.com/tucsoncatering/
Si Charro Catering	Catering		Tucson	Arizona	Tucson	Catering and banquet menus from a long-running Tucson Mexican restaurant group, suited to weddings, quinceañeras and family gatherings.			https://www.sicharro.com/catering-banquets/	https://www.instagram.com/sicharrorestaurants/
Karina Romero Beauty	Hair & Makeup		Tucson	Arizona	Tucson area, studio or on location	Licensed esthetician and bridal makeup artist offering skin-first, camera-ready looks from a private studio or at the getting-ready venue.	hello@karinaromerobeauty.com		https://karinaromerobeauty.com/	https://www.instagram.com/krbeauty_studio/
Haus of Dreams	Hair & Makeup		Tucson	Arizona	Tucson and beyond	Bridal hair and makeup team handling the whole getting-ready morning for the bride and her wedding party.	hello@hausofdreamsaz.com		https://www.hausofdreamsaz.com/	https://www.instagram.com/hausofdreams_/
Beauty by Beth	Hair & Makeup		Tucson	Arizona	Southern Arizona, available to travel	Hairstylist and makeup artist for brides and bridal parties, who also works on photoshoots, film and commercial sets.	bethannmaguire94@gmail.com	520-309-5951	https://www.bethannmaguire.com/	https://www.instagram.com/beautybybeth__/
UnCommyn Cakes	Cake		Marana	Arizona	Marana and Tucson	Made-to-order cakery baking custom scratch-made wedding cakes and cupcakes from a home kitchen in Marana.	uncommyncakes@gmail.com		https://www.uncommyncakes.com/	https://www.instagram.com/uncommyncakes/
Custom Cakes by Dulce	Cake		Tucson	Arizona	Tucson area, delivery for a fee	Home-based Tucson baker making custom wedding cakes, cupcakes and cookies, with delivery available for an extra charge.		520-639-4512	https://www.customcakesbydulce.com/	https://www.instagram.com/custom_cakes_by_dulce/
Her Little Cakery	Cake		Tucson	Arizona	Tucson	Tucson custom baker making bespoke wedding cakes and desserts, with a wedding inquiry form on the site.			https://www.herlittlecakery.com/	https://www.instagram.com/herlittlecakery/
Anstar Productions Group	Videography		Marana	Arizona	Tucson and Marana	Marana video studio, founded in 1989, making wedding highlight films with aerial footage alongside corporate and commercial work.	anstarproductions@gmail.com	(520) 888-3653	https://anstarproductions.com/	
D. James Videography	Videography		Tucson	Arizona	Tucson and Arizona	Cinematic wedding films in 4K, shot with multiple cameras, drone footage and clean audio from ceremony to toasts.	djamesvideography@gmail.com	520-495-9074	http://www.djamesvideography.com/	https://www.instagram.com/djamesvideography/
Laughing Dog Productions	Videography		Tucson	Arizona	Tucson	Tucson wedding videography with teasers and highlight films, and quinceañera films too, plus a free wedding checklist.	m.vidal@ldpfilm.com		https://www.ldpstudios.com/	https://www.instagram.com/ldpfilm/
`,
  },
  {
    name: "Sedona and Flagstaff: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Andrew Holman Photography	Photography		Sedona	Arizona	Sedona and Flagstaff	Sedona wedding and elopement photographer working since 2002, blending photojournalism with posed portraits at red rock locations.		928.202.4922	https://andrewholman.com/	https://www.instagram.com/andrewholman/
Mama Bear Studios	Photography		Prescott	Arizona	Prescott, Prescott Valley, Sedona, Flagstaff, Verde Valley	Photojournalism-minded wedding photographer with over two decades behind the lens and budget-friendly packages from about $900.		623-695-0746	https://mamabearstudiosaz.com/	https://www.instagram.com/mamabearstudiosaz/
Wilder West Elopements	Photography		Sedona	Arizona	Sedona and surrounding areas	Husband-and-wife team who plan, photograph and film adventure elopements and micro-weddings, with permit help and location scouting.	wilderwestelopements@gmail.com		https://wilderwestelopements.com/	
Special Occasions AZ	Planning		Cottonwood	Arizona	Sedona and the Verde Valley	Planner with 14 years of wedding experience offering virtual planning sessions, full or partial planning and day-of coordination.	specialoccasionsaz@gmail.com	928-451-6307	https://www.specialoccasionsaz.com/	
Ceremony of Love	Planning		Sedona	Arizona	Sedona and Lake Tahoe	Minister-led coordination, elopements and vow renewals in Sedona, with an on-site coordinator overseeing vendors since 1995.			https://ceremonyoflove.com/	
Desert Mountain Laurel	Florals		Prescott	Arizona	Northern Arizona, Sedona, Flagstaff, Cottonwood, Prescott Valley	Full-service wedding florals with delivery, set-up and cleanup, plus à la carte blooms for smaller elopements.	info@desertmountainlaurel.com	(928) 224-9295	https://www.desertmountainlaurel.com/	https://www.instagram.com/desertmountainlaurel/
White Sage Floral	Florals		Sedona	Arizona	Sedona and northern Arizona	Wedding and elopement florist blending modern minimalism with organic shapes drawn from the Sedona landscape, plus boutique rentals.	info@whitesagefloral.com		https://www.whitesagefloral.com/	https://www.instagram.com/whitesagefloralarts/
Old Soul Floral	Florals		Prescott	Arizona	Prescott and surrounding Yavapai venues	Appointment-only wedding florist mixing romantic European blooms with forest and desert elements, run by a certified designer.	oldsoulfloral@gmail.com	928-636-3789	https://oldsoulfloral.com/	https://www.instagram.com/oldsoulfloral/
DJ Carma	Music		Flagstaff	Arizona	Northern Arizona, Sedona, Prescott and statewide	Flagstaff DJ and MC with a playful, high-energy style, covering both ceremony and reception for weddings and elopements.			https://djcarma.love/	https://www.instagram.com/djcarma.love/
Brian David Guitarist	Music		Sedona	Arizona	Sedona and Northern Arizona	Live guitar for ceremonies and resort weddings, with over 20 years of experience and more than 1,000 weddings played.			https://www.briandavidguitarist.com/	
Echo Rose Rising	Music		Sedona	Arizona	Sedona and Arizona	Live violin, vocals and guitar for Sedona weddings and elopements, with separate pricing for micro-weddings and full ceremonies.	julia@echoroserising.com		https://echoroserising.com/sedonaweddingviolinist	https://www.instagram.com/echoroserising/
Main Street Catering	Catering	408 East Route 66	Flagstaff	Arizona	Flagstaff, Sedona, Oak Creek Canyon, Page Springs, Grand Canyon	Flagstaff wedding caterer since 1988 offering buffets, plated and family-style dinners, with customised ethnic and themed menus.	info@mainstreetcateringflagstaff.com	928-851-4293	https://mainstreetcateringflagstaff.com/	https://www.instagram.com/mainstreetcateringflagstaff/
Bigfoot Catering	Catering		Flagstaff	Arizona	Flagstaff, Sedona and Northern Arizona	Northern Arizona caterer with over 20 years of experience, offering several wedding and reception menus with trained service staff.	info@bigfootcatering.com	928-556-3082	https://bigfootcatering.com/	https://www.instagram.com/bigfootcateringaz/
Sedona Catering Co.	Catering		Sedona	Arizona	Northern Arizona	Full-service caterer building custom wedding menus in Southwestern, BBQ and wood-fired pizza styles, plus a private rental home.	catering@sedonacateringco.com	928.301.0791	https://www.sedonacateringco.com/	
Chef Nicholas Di Paolo	Catering		Sedona	Arizona	Sedona, Flagstaff and the Verde Valley	Private chef offering family-style dinners and buffets for casual weddings of 30 to 100 guests around Sedona and the Verde Valley.			https://chefnicholasdipaolo.com/	https://www.instagram.com/sedonachefnick/
Salon Studio 450	Hair & Makeup	450 West Goodwin Street, Suite 107	Prescott	Arizona	Prescott and on-location across Arizona	Prescott salon team offering on-site bridal hair and makeup, with trial sessions and bridesmaid packages at published prices.		928-710-9375	https://www.salonstudio450prescott.com/wedding	https://www.instagram.com/salonstudio450prescott/
Beauty By Yes	Hair & Makeup		Lake Montezuma	Arizona	Verde Valley, with travel available	Bilingual makeup artist offering bridal and party makeup, trials and hairstyling, with travel for weddings beyond the local area.	beautybyyes.mua@gmail.com		https://beautybyyes.glossgenius.com/services	https://www.instagram.com/beautybyyes.mua/
Sugar Mamas	Cake	2612 N. Steves Blvd	Flagstaff	Arizona	Flagstaff	Small-batch Flagstaff bakery taking pre-orders for simply decorated, classic-recipe wedding cakes after a consultation call.	sugarmamasflagstaff@gmail.com	928-221-8440	https://www.sugarmamasflagstaff.com/	https://www.instagram.com/sugarmamasflagstaff/
Cupcakes by Leanne	Cake		Prescott	Arizona	Prescott and the Quad Cities	State-licensed home bakery making floral and succulent cupcakes, cupcake bouquets and cakes for weddings and dessert tables.			https://sites.google.com/view/cupcakesbyleanne/home	
Tex Kelly Productions	Videography		Prescott Valley	Arizona	Yavapai, Coconino, Maricopa and Pima Counties	Cinematic wedding films with a highlight edit and longer feature cut, plus FAA-certified drone aerials across northern Arizona.		(928) 968-8374	https://texkelly.com/	https://www.instagram.com/texkellyproductions/
Granite & Sky	Videography		Prescott	Arizona	Prescott, Prescott Valley, Sedona, Flagstaff	Prescott studio filming weddings and engagements together with photography, shown at venues like Hassayampa Inn.	info@graniteandsky.com	928-775-3272	https://graniteandsky.com/	https://www.instagram.com/graniteandsky/
Like Morning Sun	Videography		Flagstaff	Arizona	Northern Arizona and greater Phoenix	Husband-and-wife photo and film team in Flagstaff, with calm direction, warm natural films and an option for Super 8 footage.	hello@likemorningsun.com	623-824-1621	https://www.likemorningsun.com/	https://www.instagram.com/likemorningsun/
`,
  },
];

export default batches;
