import type { VendorBatch } from "@/lib/vendor-batches";

// Arizona vendor batches. Every row's State is "Arizona". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Phoenix: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
The Hoskins	Photography		Phoenix	Arizona	Phoenix and Arizona	Aaron Hoskins photographs weddings in a documentary style with an editorial finish, working across Phoenix, Scottsdale and northern Arizona.	hoskinsa@gmail.com		https://www.thehoskinsphoto.com/	
Lia's Photography	Photography		Phoenix	Arizona	Phoenix, Scottsdale, Sedona and across Arizona	Husband-and-wife photographers Lia and Max, with over 15 years and more than 1,500 weddings behind them; a photo booth is also offered.	info@liasphotography.com	602-503-8019	https://www.liasphotography.com/	https://www.instagram.com/liasphotography2011/
Thomas Shull Photography	Photography		Phoenix	Arizona	Arizona and beyond	Phoenix photographer with a bright, colourful natural-light style, covering weddings, adventure elopements and South Asian celebrations.	hello@thomasshull.com	760-803-9444	https://www.thomasshull.com/	https://www.instagram.com/tjshull/
Mindy DeLuca Photography	Photography		Phoenix	Arizona	Arizona and destination weddings	Phoenix photographer with a candid, vivid style for Arizona and destination weddings, with wedding films also offered.	info@mindydeluca.com	602-332-6463	https://mindydeluca.com/	https://www.instagram.com/mindydeluca/
O'Honey Events	Planning		Scottsdale	Arizona	Scottsdale, Phoenix, Paradise Valley, Tempe, Mesa and across Arizona	Scottsdale planning studio offering full-service planning and day-of coordination at resorts and venues across the Phoenix area.	weddings@ohoneyevents.com	480-202-3365	https://www.ohoneyevents.com/	https://www.instagram.com/ohoneyevents/
Revel Wedding Co.	Planning		Scottsdale	Arizona	Arizona	Scottsdale planning company offering full-service planning, day-of logistics and custom celebration design for weddings across Arizona.			https://revelweddingco.com/	https://www.instagram.com/revelweddingcompany/
Satin & Slate Weddings	Planning		Scottsdale	Arizona	Scottsdale, Phoenix and destination weddings	Planner offering full, partial and wedding-day management, led by a founder trained in special events management and travelled in 30-plus countries.	satinandslateweddings@gmail.com		https://satinandslateweddings.com/	https://www.instagram.com/satinandslateweddings/
LUX Wedding Florist	Florals	2050 S 16th St Suite 107	Phoenix	Arizona	Phoenix and beyond	Full-service wedding and event floral design studio in the Phoenix Flower District, creating events since 2011.		602-707-6295	https://luxweddingflorist.com/	https://www.instagram.com/luxflorist/
White Poppy Floral Design	Florals	4024 E Weldon Ave	Phoenix	Arizona	Phoenix, Scottsdale and surrounding cities	Phoenix wedding and event florist designing bouquets and centrepieces, with work featured in magazines and on local news.	jb@whitepoppy.com	602-758-2581	https://whitepoppy.com/	https://www.instagram.com/white_poppy_floral/
Fleur de Vie	Florals		Scottsdale	Arizona	Scottsdale, Phoenix, Paradise Valley, Sedona and Southern California	Fine-art floral designer and stylist in Scottsdale creating wedding flowers and event styling, with an online floral estimate builder.	fleurdeviestudio@gmail.com		https://fleurdeviestudio.co/	https://www.instagram.com/fleurdeviestudio/
Ray the DJ	Music	201 E Southern Ave Suite 110	Tempe	Arizona	Phoenix and across Arizona	DJ company founded more than 45 years ago by Ray and Barbara Grace, providing ceremony and reception music, sound and lighting across the Valley.	info@raythedj.com	480-921-9665	https://raythedj.com/	https://www.instagram.com/ray.the.dj/
DJ G Weddings & Events	Music		Chandler	Arizona	All of Arizona, based in the Phoenix metro	Chandler-based DJ with 25-plus years and over 500 weddings, who also helps plan the running order and liaises with your other vendors.	garybsanders@gmail.com	480-280-7422	https://djgweddingsaz.com/	https://www.instagram.com/djgweddings/
No Limit Events	Music		Scottsdale	Arizona	Arizona, Las Vegas and destination events	Scottsdale DJ and production team specialising in South Asian and multicultural weddings, with MC, dhol, lighting and LED video walls.			https://www.nolimiteventsaz.com/	https://www.instagram.com/nolimiteventsaz1/
Elite Event Services	Music		Phoenix	Arizona	Scottsdale, Phoenix, Peoria, Gilbert, Chandler and surrounding areas	DJ company run by owners Jay and Heather, providing wedding and event DJ services across the Valley since 2001.			https://www.eliteeventaz.com/	
Fresh From The Kitchen	Catering	3316 N 3rd St Suite 8	Phoenix	Arizona	Phoenix, Scottsdale, Paradise Valley, Chandler, Avondale, Glendale and statewide	Chef-owned Phoenix caterer established in 2008, cooking with locally sourced, hormone-free ingredients for weddings and events.		602-694-1197	https://www.freshfromthekitchenllc.com/	https://www.instagram.com/fftk_catering2/
Chef Phoenix Catering	Catering	1440 S Country Club Dr Ste 10	Mesa	Arizona	Phoenix, Scottsdale, Paradise Valley, Mesa, Chandler, Gilbert and Tempe	Mesa-based caterer serving weddings at venues and private locations across Phoenix and the East Valley, from intimate dinners to large receptions.	chef@chefphoenix.com	602-818-2779	https://chefphoenix.com/catering/weddings	https://www.instagram.com/chefphoenix/
Classic Catering	Catering	9855 W Peoria Ave	Peoria	Arizona	Phoenix, Scottsdale, Mesa, Tempe, Peoria, Glendale and surrounding areas	Peoria caterer dating from 1982, with wedding menus spanning Italian, Mexican, Indian and barbecue, plus complimentary tastings.	events@classiccateringltd.com	623-933-4903	https://classiccateringltd.com/	
First Blush Beauty	Hair & Makeup		Scottsdale	Arizona	Scottsdale, Paradise Valley, Fountain Hills, Mesa, Chandler, Gilbert and surrounding areas	On-location bridal hair and makeup team led by Leah, focused on natural, classic glam, with lashes included in bridal packages.	hello@firstblushbeauty.com	480-868-5680	https://www.firstblushbeauty.com/	
Kensington Makeup	Hair & Makeup		Scottsdale	Arizona	Greater Phoenix area and beyond	Woman-owned, on-location hair and makeup team with in-house trained artists, working across all skin tones and hair textures.	hello@kensingtonmakeup.com	480-717-2077	https://kensingtonmakeup.com/	https://www.instagram.com/kensingtonmakeup/
Viviana Bridal Beauty	Hair & Makeup		Phoenix	Arizona	Phoenix and surrounding areas, plus destination weddings	Phoenix team bringing bridal hair styling and makeup to the wedding party on site, for local and destination weddings.	vivianabridalbeauty@gmail.com		https://www.vivianabridalbeauty.com/	https://www.instagram.com/vivianmarianibeauty/
Silver Rose Bakery	Cake	2814 W Bell Rd Suite 1451	Phoenix	Arizona	Phoenix, Scottsdale and beyond	North Phoenix bakery making custom wedding cakes along with cake pops and pastries, delivering across Phoenix and Scottsdale.		623-499-2222	https://silverrosebakery.com/collections/wedding-cakes	https://www.instagram.com/silverrosebakery/
Bamboo Bakery	Cake	1619 E Monte Vista Rd	Phoenix	Arizona	Phoenix, Scottsdale, Glendale and Tempe	Central Phoenix bakery making tiered wedding cakes to order, with regular cake-tasting evenings for couples.	orders@bamboobakery.com	602-246-8061	https://www.bamboobakery.com/	
Pasteleria Azteca	Cake	5602 N 27th Ave	Phoenix	Arizona		Mexican bakery and custom cake shop in west Phoenix making wedding cakes and sheet cakes alongside traditional Mexican pastries.	contact@bakeryazteca.com	623-247-8493	https://www.bakeryazteca.com/weddings-cakes-phoenix/	https://www.instagram.com/azteca_bakery/
Serendipity Cinematography	Videography		Phoenix	Arizona	Scottsdale, Gilbert, Mesa, Chandler, Queen Creek, Sedona and destination weddings	Phoenix team of filmmakers and editors led by Taryn, making hand-crafted cinematic wedding films across the Valley.	taryn@serendipitycinema.com		https://serendipitycinema.com/	https://www.instagram.com/serendipitycinema/
Mina Studio	Videography		Phoenix	Arizona	Phoenix, Scottsdale, Chandler, Gilbert, Mesa, Tempe and across Arizona	Phoenix photo and video studio making cinematic wedding films, with a specialism in Indian and South Asian weddings.			https://www.minavideoproduction.com/	https://www.instagram.com/minavideoproduction/
AZ Film Company	Videography		Phoenix	Arizona	Arizona and out-of-state destinations	Phoenix videographer making documentary-style wedding films with a candid, unstaged approach, travelling out of state for about half the season.			https://www.azfilmcompany.com/	https://www.instagram.com/azfilmcompany/
Heartcraft Wedding Films	Videography		Phoenix	Arizona	Phoenix and across Arizona	Phoenix studio founded by Nick Gaiski, making cinematic, heirloom-style wedding films with an unobtrusive presence and limited yearly bookings.	contact@heartcraftweddingfilms.com	480-415-8288	https://heartcraftweddingfilms.com/	https://www.instagram.com/heartcraftweddingfilms/
`,
  },
];

export default batches;
