import type { VendorBatch } from "@/lib/vendor-batches";

// Arkansas vendor batches. Every row's State is "Arkansas". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Little Rock: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Katie Childs Photo	Photography		Little Rock	Arkansas		Documentary-style photographer drawn to bold colour and candid moments, covering weddings alongside editorial and family work.	hello@katiechildsphoto.com		https://katiechildsphoto.com/	https://www.instagram.com/katiechildsphoto/
Jessica Carder, Inc.	Photography	525 N Pine St	Little Rock	Arkansas		Photographer and painter working from a Little Rock studio, offering wedding coverage plus bridal and engagement portraits.		(501) 749-7422	https://www.jessicacarder.com/	https://www.instagram.com/jessica.carder/
Sterling Imageworks	Photography		North Little Rock	Arkansas		Husband-and-wife photography team photographing weddings, bridals and engagements since 2010, with some work further afield in Arkansas.	jc@sterlingimageworks.com	(501) 413-0841	https://sterlingimageworks.com/	https://www.instagram.com/sterlingimageworks/
AMaggio Photo	Photography		Conway	Arkansas	Central Arkansas and nationwide	Bright, bold wedding photography by Anne Henry, focused on natural, unposed moments for couples across central Arkansas.			https://amaggiophoto.com/	https://www.instagram.com/amaggiophoto/
Bella Baxter Special Events	Planning		Little Rock	Arkansas	Little Rock, Memphis and destination weddings	Luxury wedding planning and design firm working between Little Rock and Memphis, with more than 400 events behind it.	bellabaxterevents@gmail.com		https://www.bellabaxterevents.com/	https://www.instagram.com/bellabaxterevents/
Evergreen Events	Planning		Little Rock	Arkansas	Little Rock and central Arkansas	Lillie Peterson's planning and design studio, offering full and partial planning with an emphasis on calm, well-prepared wedding days.			https://evergreeneventsar.com/	https://www.instagram.com/evergreeneventsar/
Point B Events Co.	Planning		Little Rock	Arkansas	Central Arkansas and destination weddings	Wedding planning led by Malia Binge, with month-of coordination, full planning and event design for central Arkansas couples.			https://pointbeventsco.com/	https://www.instagram.com/pointbeventsco/
Tipton & Hurst	Florals	1801 N Grant St	Little Rock	Arkansas	Central and northwest Arkansas	Florist dating back to 1886, designing custom wedding flowers from its Little Rock shop, with further branches across Arkansas.		(501) 666-3333	https://www.tiptonhurst.com/	https://www.instagram.com/tiptonhurst/
Cabbage Rose	Florals		Little Rock	Arkansas	Little Rock area	Locally owned boutique florist designing wedding and event flowers alongside everyday arrangements and delivery around Little Rock.	cabbageroseflorist@gmail.com	(501) 664-4042	https://cabbageroseflorist.com/	https://www.instagram.com/cabbageroseflorist/
Hodge Podge Etc Flowers & Gift Baskets	Florals	2101 Main St	North Little Rock	Arkansas	North Little Rock and surrounding areas	Argenta flower shop custom-designing bouquets, buttonholes, ceremony pieces and centrepieces for each couple it works with.		(501) 372-6501	https://www.northlittlerockflowershop.com/wedding-flowers	https://www.instagram.com/hodgepodgerocks/
Central Arkansas Entertainment	Music	8110 Scott Hamilton Dr, Suite C-1	Little Rock	Arkansas	Central Arkansas	DJ and event production company handling wedding music, lighting, staging, dance floors and live-band bookings.		(501) 772-0067	https://www.centralarkansasentertainment.com/	https://www.instagram.com/cae_lr/
Arkansas Capital String Quartet	Music		Little Rock	Arkansas	Central Arkansas	String ensemble founded in 2004, formerly the Little Rock String Quartet, playing ceremony and reception music around the region.	nancymcgrawviolin@yahoo.com	(501) 944-6311	https://www.arkansascapitalstringquartet.com/	
Premier Entertainment	Music		Little Rock	Arkansas	Little Rock and surrounding area	Wedding DJ and MC service run by Adam, mixing music to keep the dance floor busy from ceremony through the last song.			https://arpremierentertainment.com/	https://www.instagram.com/thepremierdj/
Rx Catering	Catering	921 W Capitol Ave	Little Rock	Arkansas	Central and northwest Arkansas	Full-service caterer cooking for weddings of 10 to 500-plus guests since 2001, with staffing, setup and dietary options.		(501) 221-3929	https://rxcatering.net/	https://www.instagram.com/rxcateringlr/
Catering To You	Catering	8121 Cantrell Rd	Little Rock	Arkansas	Little Rock area	Long-running Little Rock caterer offering wedding menus from drop-off spreads to fully staffed meals, with options for most budgets.			https://cateringtoyoulr.com/	
Vibrant Occasions Catering	Catering	1305 Hot Springs Hwy, Ste 102	Benton	Arkansas	Arkansas statewide	Chef-led catering company from Benton handling weddings and galas, with a large trained service team and a mobile kitchen.	mary@vibrantoccasionscatering.com	(501) 408-2111	https://vibrantoccasionscatering.com/	https://www.instagram.com/vibrantoccasionscatering/
Heritage Catering	Catering		Little Rock	Arkansas	Central Arkansas	Wedding and event caterer run by Shane and Kim, building custom menus from plated dinners to buffets and late-night dessert bars.			https://heritagecateringar.com/	https://www.instagram.com/heritagecateringar/
Lavonne Beauty	Hair & Makeup	11220 N Rodney Parham Rd, Suite 1	Little Rock	Arkansas	Little Rock, with travel and destination weddings	Bridal hair and makeup studio specialising in corrective beauty and skincare prep, available on location and for destination weddings.			https://lavonnebeauty.com/	https://www.instagram.com/lavonnebeauty/
Belle & Blush	Hair & Makeup		Little Rock	Arkansas	Little Rock area, with travel for a mileage fee	Beauty shop offering bridal makeup with an in-store consultation beforehand and on-site application for the bride and wedding party.		(501) 448-2290	https://www.belleandblush.com/pages/bridal-makeup-application	https://www.instagram.com/belleandblush/
Elevated Arkansas Artists	Hair & Makeup		Conway	Arkansas	Arkansas and neighbouring states	Owner-run team of 14 licensed stylists and estheticians providing on-site bridal hair and makeup for wedding parties of any size.		(501) 504-5411	https://www.elevatedarkansasartists.com/	https://www.instagram.com/elevatedarkansas/
Dempsey Bakery	Cake	323 S Cross St	Little Rock	Arkansas		Dedicated gluten-free, soy-free and nut-free bakery making custom wedding cakes, a rare option for couples with allergic guests.		(501) 375-2257	https://dempseybakery.com/	https://www.instagram.com/dempseybakery/
SugarDumplin's Cupcakes	Cake	5407 Hwy 5 N, Ste 12	Bryant	Arkansas	Saline County	Bryant bakery making tiered wedding cakes and groom's cakes alongside its cupcakes, voted Saline County's favourite bakery for a decade.	jessica@sugardumplinscupcakes.com	(501) 952-3472	https://www.sugardumplinscupcakes.com/	https://www.instagram.com/sugardumplins_cupcakes/
Mental Bakedowns & Pastry Attacks	Cake		Little Rock	Arkansas		Order-only custom cake studio run by a trained pastry chef, making wedding cakes plus cupcakes, macarons and decorated cookies.	MentalBakeDowns.PastryAttacks@gmail.com	(470) 249-3766	https://mentalbakedownsandpastryattacks.com/	https://www.instagram.com/mentalbakedowns.pastryattacks/
Tony Baker Photography & Video	Videography	2115 Stagecoach Village Ct	Little Rock	Arkansas	Little Rock and beyond	One team filming and photographing the same wedding, so the video and stills crews already know how to work together.	tony@tonybakerphotography.com	(501) 804-4031	https://tonybakerphotography.com/	https://www.instagram.com/tonybakerphotography/
Cary Clayton Media	Videography	11908 Kanis Rd, Suite G7	Little Rock	Arkansas	Arkansas, Texas, Tennessee and worldwide	Little Rock studio offering wedding films and photography together, known for quick turnaround and flexible payment options.			https://caryclaytonmedia.com/	https://www.instagram.com/caryclaytonmedia/
EMH Visuals	Videography		Alexander	Arkansas	Arkansas and beyond	Central Arkansas wedding film company offering highlight, classic and feature-length packages, filming weddings across the state and further afield.	info@emhvisuals.com	(844) 582-0847	https://emhvisuals.com/	https://www.instagram.com/emhvisuals/
`,
  },
];

export default batches;
