import type { VendorBatch } from "@/lib/vendor-batches";

// California vendor batches. Every row's State is "California". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Los Angeles: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Callaway Gable	Photography		Los Angeles	California	Los Angeles, Beverly Hills, Malibu, Santa Monica, Orange County, San Diego and beyond	Husband-and-wife studio with an editorial, cinematic style and more than 15 years shooting LA weddings, including many South Asian celebrations.	allison@callawaygable.com	(323) 394-9997	https://callawaygable.com	https://www.instagram.com/callawaygable/
Lupe Juarez Photography	Photography		Los Angeles	California		Bilingual Spanish-English photographer with 15 years' experience, known for guided posing and candid, timeless coverage of Southern California weddings.	info@lupejuarez.com		https://lupejuarez.com	
Mindy Weiss	Planning		Los Angeles	California	Los Angeles and destinations worldwide	Luxury planner and designer with a 30-year career and a team of twelve, producing high-profile and destination weddings with highly personal detail.		(310) 205-6000	https://mindyweiss.com	https://www.instagram.com/mindyweiss/
Live Love Create Events	Planning		Los Angeles	California		Boutique full-service planning firm founded in 2009, experienced in Korean paebaek ceremonies and blending Asian heritage with modern weddings.	christine@livelovecreateevents.com	(323) 380-8149	https://livelovecreateevents.com	https://www.instagram.com/livelovecreate/
Mark's Garden	Florals	13838 Ventura Blvd	Sherman Oaks	California	Los Angeles area	Long-running Sherman Oaks floral studio designing for weddings and red-carpet events, with work seen at the Oscars and Golden Globes.	info@marksgarden.com	(818) 906-1718	https://marksgarden.com	https://www.instagram.com/marksgarden/
Eddie Zaratsian Lifestyle & Design	Florals	7430 San Fernando Rd	Sun Valley	California	Greater Los Angeles and destinations	Floral and event design house that also plans and produces weddings, known for sculptural work with orchids and mosses at large-scale celebrations.	concierge@eddiezaratsian.com	(310) 508-6126	https://www.eddiezaratsian.com	https://www.instagram.com/eddiezaratsian/
Lark Cake Shop	Cake		Los Angeles	California	Throughout Los Angeles	Family-run Silver Lake bakery open since 2007, offering free consultations and tastings for custom wedding cakes with a modern bohemian look.		(323) 667-2968	https://www.larkcakeshop.com	https://www.instagram.com/larkcakeshop/
Sweet E's Bake Shop	Cake		Los Angeles	California	Los Angeles, with nationwide shipping	Los Angeles bake shop making custom wedding and engagement cakes and logo cookies, with vegan, gluten-free and kosher-certified options.	hello@sweetesbakeshop.com		https://www.sweetesbakeshop.com	https://www.instagram.com/sweetesbakeshop/
Marry Motion	Videography		Los Angeles	California	Los Angeles and worldwide	Owner-led film studio whose founder shoots every wedding himself, offering drone coverage, Super 8 film and next-day preview edits.	themarrymotion@gmail.com	(747) 476-9169	https://marrymotion.com	https://www.instagram.com/themarrymotion/
HeirloomLA	Catering		Los Angeles	California	Los Angeles and beyond	Los Angeles caterer known for simple, farm-sourced food and family-style service, with chefs cooking in front of guests and vegan options.	info@heirloomla.com	(855) 456-6652	https://heirloomla.com	https://www.instagram.com/heirloomla/
International Entertainment LA	Music		Los Angeles	California	Southern California and destination events	DJ and live-music company running since 1991, playing Armenian, Arabic, Assyrian, Persian and Indian sets alongside mainstream pop.	events@internationalentertainmentla.com	(866) 352-7736	https://internationalentertainmentla.com	
Angels Music Productions	Music		Los Angeles	California	Los Angeles, Orange, San Diego and Ventura counties	Valley Village DJ and MC team specialising in Jewish and Israeli weddings, with bilingual MCs in Hebrew, Persian and Spanish.		(949) 394-2572	https://angelsmusic.net	https://www.instagram.com/angelsmusicproductions/
Special Occasions DJ & Lighting	Music	390 Cliffwood Park St	Brea	California	Los Angeles, Orange County, San Diego, the Bay Area and destinations	South Asian wedding DJs with over 20 years' experience across Punjabi, Gujarati and Persian celebrations, plus lighting and LED video walls.	info@specialoccasionsla.com	(714) 253-3118	https://www.sodjla.com	https://www.instagram.com/sodjla/
Brand Videography	Videography		Los Angeles	California	West Coast	Documentary-style wedding film team founded in 2012 by a film and television editor, letting couples pick their music and request re-edits.	info@brandvideography.com	(310) 923-0062	https://brandvideography.com	https://www.instagram.com/brandvideography/
The Taco Catering Company	Catering		Los Angeles	California	Los Angeles, Orange County and the Inland Empire	Family-owned taco caterer run by Michelle and Hector, offering taco bars, on-site taqueros and a taco truck at budget-friendly per-guest prices.	info@tacocateringcompany.com	(213) 232-4255	https://tacocateringcompany.com	https://www.instagram.com/tacocateringcompany/
Jay Lawrence Goldman Photography	Photography	6139 Wilshire Blvd	Los Angeles	California		Wilshire Boulevard studio photographer with 30 years behind the camera, shooting weddings and mitzvahs in a relaxed, editorial style.	studio@jlgphoto.com	(323) 954-7436	https://www.jaylawrencegoldman.com	https://www.instagram.com/jay_lawrence_goldman/
3 Little Birds Event Planning	Planning		Burbank	California	Los Angeles area	Burbank planning team offering full planning, month-of and day-of coordination, with its own rental inventory for styling the day.		(818) 915-8870	https://3littlebirdseventplanning.com	https://www.instagram.com/3littlebirdseventplanning/
The Hidden Garden	Florals	2250 Cotner Ave	Los Angeles	California	Los Angeles and surrounding areas	West LA floral studio founded in 1999 by Amy Marella, designing lavish installations for luxury hotel weddings, with full packages from $25,000.		(310) 575-6600	https://hiddengardenflowers.com/pages/weddings	https://www.instagram.com/hiddengardenflowers/
Winston & Main	Florals		Los Angeles	California	Southern California, Santa Barbara, Ojai, Palm Springs and beyond	LGBTQIA+-owned floral studio working with local blooms and foam-free mechanics, composting waste and donating repurposed arrangements.			https://winstonandmain.com	https://www.instagram.com/winstonandmain/
Emily Lynn & Co.	Hair & Makeup		Los Angeles	California	Southern California and destination weddings	On-site hair and makeup team founded in 2017, known for airbrush makeup and natural looks, with artists experienced across skin tones and hair types.	info@emilylynnandcompany.com	(323) 310-4404	https://www.emilylynnandcompany.com	https://www.instagram.com/emilylynnandcompany/
Bright Crystal Wedding	Hair & Makeup	21880 Hawthorne Blvd Suite 342	Torrance	California	Los Angeles, Orange County and Temecula	Torrance bridal beauty studio working since 2012, offering on-site or in-studio hair and makeup for weddings, quinceañeras and debuts.	info@brightcrystal-wedding.com	(213) 260-1531	https://www.brightcrystal-wedding.com	https://www.instagram.com/brightcrystalwedding/
17 Catering	Catering	425 N Brand Blvd	Glendale	California	Los Angeles area	Glendale caterer with more than 15 years of LA events, known for Mediterranean menus and lavish Persian sweets and fruit tables.	17cateringandevents@gmail.com	(818) 660-5373	https://17catering.com	https://www.instagram.com/17events/
A Colored Mind	Videography		Los Angeles	California	Southern California and destinations worldwide	LGBTQ+-inclusive cinematic film and photo studio with over 400 weddings filmed across Southern California and abroad.		(213) 999-8966	https://acoloredmind.com	https://www.instagram.com/a.colored.mind/
One Story Weddings	Videography		Los Angeles	California	Los Angeles, Orange County, San Diego, Temecula, Santa Barbara and Ventura County	Wedding film company founded in 2017, sending two cinematographers with wireless audio and drone for 4K highlight films, from $3,900.	info@onestoryweddings.com		https://www.onestoryweddings.com/los-angeles-wedding-videographer	https://www.instagram.com/onestory.weddings/
Butter Cake Shoppe	Cake		Los Angeles	California	Los Angeles	Sister-run Los Feliz cake studio making custom wedding cakes from scratch since 2015, with a mix-and-match menu of flavours and fillings.			https://www.buttercakeshoppe.com	https://www.instagram.com/buttercakeshoppe/
Fairytale Hair and Makeup	Hair & Makeup		Los Angeles	California	Los Angeles, Orange County, Ventura, Santa Barbara and the Inland Empire	Mobile bridal beauty team of more than a dozen artists who travel to the venue, with separate crews also serving Las Vegas and Orlando.	fairytalehairandmakeup@gmail.com	(877) 324-7977	https://fairytalehairandmakeup.com/los-angeles-county/	https://www.instagram.com/fairytalehairandmakeup/`,
  },
  {
    name: "San Francisco Bay Area: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jasmine Lee Photography	Photography		San Francisco	California	San Francisco Bay Area and destination weddings	San Francisco photographer covering City Hall elopements, intimate weddings and destination celebrations with an artistic, editorial eye.			https://www.jasmineleephotography.com	https://www.instagram.com/jasmineleephoto/
Paula LeDuc Fine Catering & Events	Catering	1350 Park Ave	Emeryville	California	Northern California	Long-established East Bay caterer and event producer handling full-service weddings, galas and private celebrations across Northern California.	sales@paulaleduc.com	510-547-7825	https://www.paulaleduc.com	https://www.instagram.com/paulaleduc/
Taste Catering	Catering	201 Adrian Road	Millbrae	California	San Francisco and the Bay Area	Peninsula caterer offering full-service wedding menus, bar service and event design, plus regional Indian cuisine through its Taste & Jalsa partnership.	info@tastecatering.com	(415) 550-6464	https://www.tastecatering.com	https://www.instagram.com/tastecateringsf/
Kathleen Deery Design	Florals	4240 Holden Street	Emeryville	California		Emeryville floral and event design studio creating refined ceremony, cocktail-hour and reception arrangements for Bay Area weddings.	info@kathleendeerydesign.com	510.229.5444	https://www.kathleendeerydesign.com	https://www.instagram.com/kathleendeerydesign/
Tamtastic Creations	Planning		San Jose	California	Bay Area and Northern California	San Jose planner offering full, partial and day-of planning, experienced with South Asian, Muslim, Middle Eastern, Afghan and interfaith weddings.	hello@tamtasticcreations.com		https://www.tamtasticcreations.com	https://www.instagram.com/tamtastic.creations/
Sugar Butter Flour	Cake	669 S Bernardo Ave	Sunnyvale	California		Sunnyvale cake shop and French patisserie baking custom wedding cakes, with tastings offered before you order.	orders@sugarbutterflour.com	(408) 732-8597	https://www.sugarbutterflour.com	https://www.instagram.com/sugarbutterfloursv/
Masse's Pastries	Cake	1469 Shattuck Ave	Berkeley	California		Berkeley pastry shop on Shattuck making custom wedding cakes alongside its seasonal tarts and well-known honey cake.	massespastries@aol.com	510-649-1004	https://www.massespastries.com	
Christina Flach	Hair & Makeup		Corte Madera	California	San Francisco Bay Area, Marin, Napa, Sonoma, Silicon Valley and destinations	Marin-based bridal makeup and hair artist known for natural, camera-ready looks, with particular experience in Indian and South Asian bridal beauty.	prettygirlmakeup@gmail.com	415-717-9864	https://www.christinaflach.com	
Bun Bun Bridal Lab	Hair & Makeup	459 Fulton St #10	San Francisco	California	All Bay Area and beyond	San Francisco team of 15+ makeup artists and hairstylists doing soft, natural glam for bridal parties of any size, with WeChat booking available.	info@bunbunbridallab.com		https://www.bunbunbridallab.com	https://www.instagram.com/bun_bun_bridal_lab/
M-Sutra Bride	Hair & Makeup		San Ramon	California	Bay Area and Northern California, plus destination weddings	San Ramon bridal beauty team specialising in South Asian hair and makeup, including dupatta draping and looks for sangeet, mehndi and haldi events.	msutrabride@gmail.com	925-325-4618	https://www.msutrabride.com	https://www.instagram.com/msutra_bride/
The Hot Club of San Francisco	Music		San Francisco	California	San Francisco Bay Area and beyond	Gypsy-jazz string ensemble playing ceremonies, cocktail hours and dinner sets as a duo, trio or quartet, with swing for the dance floor.			https://www.hotclubsf.com/wedding-jazz-band	https://www.instagram.com/hotclubsf/
Sunrose Floral	Florals		Oakland	California	San Francisco Bay Area and beyond	Woman-owned Oakland studio designing loose, romantic and sustainably minded wedding florals, from full-service design to à la carte pieces.		(510) 495-0928	https://www.sunrosefloral.com	https://www.instagram.com/sunrosefloral/
Ashley Smith Events	Planning		San Francisco	California	San Francisco and destinations worldwide	San Francisco design-led planning firm with 15+ years producing high-end weddings that pair minimalist settings with bold, fashion-inspired details.			https://www.ashleysmithevents.com	
T.D.E. Wedding	Planning	216 Broadway	Millbrae	California	San Francisco Bay Area, from Santa Rosa to Carmel	Millbrae firm specialising in Chinese weddings, with all-inclusive packages covering planning, tea ceremonies, décor, photo, video and MCs.	info@tdewedding.com	(650) 686-6101	https://www.tdewedding.com	https://www.instagram.com/tdewedding/
Kindlewood Films	Videography		San Francisco	California	San Francisco, Napa Valley, Santa Cruz, Monterey, Big Sur and San Luis Obispo	San Francisco film studio with 300+ weddings behind it, building story-led films around the day's vows, toasts and dialogue.	hello@kindlewoodfilms.com	(415) 209-5817	https://kindlewoodfilms.com	
martinFILMS	Videography		Oakland	California	Bay Area and Wine Country, including Napa, Sonoma and Marin	Oakland filmmaker Martin Meyer shooting cinematic wedding films at vineyards, city venues and historic estates around Northern California.	bymartinmeyer@gmail.com	510-325-7750	https://www.martinfilms.com	https://www.instagram.com/martinfilms/
Wedding Documentary	Videography		San Jose	California	Bay Area, Napa, Sonoma and destinations worldwide	San Jose studio filming and photographing Indian and South Asian weddings since 2004, covering multi-day Hindu, Sikh and Gujarati celebrations.	info@Weddingdocumentary.com	(408) 656-1014	https://www.weddingdocumentary.com	https://www.instagram.com/weddingdocumentary/
C Wagner Photography	Photography		Oakland	California	Northern and Southern California	Oakland documentary photographer shooting weddings and elopements in a hybrid of digital, 35mm, medium-format and Super 8 film since 2013.	cw@cwagnerphotography.com	(510) 338-4186	https://www.c-wagnerphotography.com	https://www.instagram.com/cwagnerphotography/
Anna Wu Photography	Photography		Oakland	California	Bay Area, nationwide and international	Oakland-area photojournalistic photographer with 15+ years of weddings, from San Francisco City Hall ceremonies to multicultural celebrations.			https://annawu.com	https://www.instagram.com/annawuphoto/
Butter&	Cake	690 Indiana St	San Francisco	California		Dogpatch cake studio known for less-sweet cakes with sculptural, modern designs, offering wedding tasting boxes and custom consultations.	hello@butterand.com	415-707-7414	https://www.butterand.com	https://www.instagram.com/butter_and/
Bay Area Beats DJs	Music		Oakland	California	Oakland, Berkeley, San Francisco, Napa, Sonoma and San Jose	Oakland DJ and MC company founded in 2012, experienced with Indian, Mexican, Jewish and Arabic weddings and offering lighting and sound.			https://www.bayareabeatsdjs.com	
All Ears DJ	Music		Oakland	California	San Francisco Bay Area, Chicago, Kansas City and beyond	Oakland-rooted collective of DJs with 1,000+ events since 2012, known for tasteful, genre-spanning sets from electronic to queer dance classics.	allearsdj@gmail.com	785-766-2596	https://www.allearsdj.com	https://www.instagram.com/allearsdj/
Ash + Oak	Florals		Oakland	California	California, Mexico and beyond	Oakland floral atelier founded in 2014, designing sculptural, editorial wedding florals and large installations for luxury and destination weddings.	ashley@ashandoak.co		https://www.ashandoak.co	https://www.instagram.com/ashandoakfloral/
D-D Catering	Catering	1645 Flickinger Ave	San Jose	California	San Jose and the Bay Area	San Jose caterer serving Vietnamese and modern Asian fusion menus for weddings, from family-style banquets to buffets with carving stations.	ddcatering2016@gmail.com	(408) 717-1131	https://d-ddelightsanjose.com/catering/	https://www.instagram.com/d_ddelight/`,
  },
  {
    name: "San Diego: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
True Photography and Video	Photography		San Diego	California	San Diego and destinations nationwide	Long-running San Diego studio since 2000 offering photo and video together, with a choice of film, pop or organic editing treatments.	inquiry@truephotography.com	619-340-0992	https://www.truephotography.com	
Laura K Moore Photography	Photography		San Diego	California	North County San Diego, Carlsbad, Encinitas and Rancho Santa Fe; destinations	Documentary-leaning lifestyle and editorial photographer for North County weddings, including Indian weddings and elopements, in clean natural colour.	contact@laurakmoore.com	951-756-2960	https://www.laurakmoore.com	https://www.instagram.com/laurakmoorephotography/
Violet Cake Company	Cake	672 San Fernando St	San Diego	California	San Diego and surrounding areas	Point Loma cake studio making fine-art wedding cakes with hand-crafted sugar flowers, vintage piping and soft romantic textures.	info@violetcakeco.com	619-993-3992	https://www.violetcakeco.com	https://www.instagram.com/violetcakecosd/
cupCAKES a la Yola	Cake	6850 Mission Gorge Rd	San Diego	California		Family-owned San Diego bakery since 2015 making tiered wedding cakes, cupcake towers and dessert tables, with delivery and set-up.	cakeinfosd@gmail.com	619-708-5088	https://cupcakesalayola.com	https://www.instagram.com/cupcakesalayola/
Liz's Flowers	Florals	6690 Mission Gorge Rd Suite F	San Diego	California	San Diego County, including Rancho Santa Fe, Poway, Del Mar and Solana Beach	Family-owned San Diego florist since 1990 designing wedding bouquets and venue flowers with seasonal peonies, ranunculus, dahlias and protea.	liz@lizsflowers.com	(619) 285-3847	https://lizsflowers.com	https://www.instagram.com/lizsflowerssd/
Adelaide Shea Films	Videography		San Diego	California	San Diego and worldwide	San Diego videographer making documentary-style wedding films that stay unobtrusive on the day, with Super 8 film available as well.	adelaidesheafilms@gmail.com		https://adelaidesheafilms.com	https://www.instagram.com/adelaidesheafilms/
Sweet Blossom Weddings	Planning		Encinitas	California	San Diego and beyond	Encinitas planning boutique running since 2010, offering full planning, design and day-of coordination with a team of planners on the day.	hello@sweetblossomweddings.com	858-668-8263	https://sweetblossomweddings.com	https://www.instagram.com/sweetblossomweddings/
Aficial Events	Planning		San Diego	California	San Diego, travelling further when available	San Diego planning team offering full and partial planning, design-plus-coordination and day-of management for weddings and rehearsal dinners.	karen@aficialevents.com		https://aficialevents.com	https://www.instagram.com/aficialevents/
Ann's Plans	Planning		San Diego	California	San Diego region	San Diego planner with over twenty years of coordinating weddings, offering full-service planning through to week-of coordination by appointment.	ann@annsplans.com	619-206-5676	https://annsplans.com	
Captured by Suarez	Photography		San Diego	California		Husband-and-wife photography duo, high-school sweethearts, shooting candid, natural wedding coverage with an eye for golden-hour light.			https://capturedbysuarez.com	https://www.instagram.com/capturedbysuarez/
Feral Rose Floral Design	Florals		San Diego	California	Southern California	Designer-led studio taking a limited number of weddings each year, creating lush, garden-style arrangements and installations.	feralrosefloral@gmail.com	805-689-6460	https://feralrosefloral.com	https://www.instagram.com/feralrosefloral/
Tessfresh Flowers	Florals	1405 Morena Blvd Suite A	San Diego	California	San Diego County	Family-run Morena district florist since 2002 handling fresh and silk wedding flowers plus event decor for hundreds of events a year.	info@tessfreshflowers.com	(619) 276-4221	https://www.tessfreshflowers.com	https://www.instagram.com/tessfreshflowers/
Kota Video Productions	Videography		Carlsbad	California	San Diego, Riverside and Orange counties	Owner-operated Carlsbad videographer making story-led cinematic wedding films, with drone, full ceremony edits and social cuts available.	kotavideopro@gmail.com	858-333-7006	https://kotavideo.com	
Maseloo Films	Videography	321 E San Ysidro Blvd Unit A	San Ysidro	California	Greater San Diego, plus Los Angeles, Riverside and Orange County	South Bay wedding film studio producing emotive, cinematic films with drone coverage and multiple shooters, from small ceremonies upwards.		(619) 540-1244	https://www.maseloo.com	https://www.instagram.com/maseloofilms/
Terra Catering & Events	Catering	7091 El Cajon Blvd	San Diego	California	San Diego	Chef-led caterer with nearly three decades in San Diego, cooking farm-to-table menus on site as buffets, stations, plated or family style.	events@terracatering.com	619-993-1437	https://www.terracatering.com	https://www.instagram.com/terracatering/
Bekker's Catering	Catering		San Diego	California	San Diego	Family-owned full-service caterer since 1958, known for pit-smoked barbecue alongside themed menus, rentals and staffing for weddings.		619-287-9027	https://www.bekkerscatering.com	https://www.instagram.com/bekkerscatering/
Tacos Don Jorge	Catering		San Diego	California	San Diego area	Mexican taco caterer pressing handmade tortillas on site, with cocktail-hour bites, vegan options and a churro dessert station for weddings.		844-822-6626	https://www.tacosdonjorge.com	https://www.instagram.com/tacosdonjorgeinc/
Coast Catering	Catering		San Diego	California	San Diego and Southern California	San Diego caterer of over twenty years creating chef-driven custom menus cooked on site, with event design and rentals through a sister company.	info@coastcatering.com	(877) 577-1718	https://www.coastcatering.com	https://www.instagram.com/coastcatering/
Sound Prodigy	Music		San Diego	California	Southern California	Independent San Diego DJ and MC company running since 1999, also offering a vintage VW bus photo booth and an audio guestbook.	info@soundprodigy.com	619-972-6086	https://soundprodigy.com	https://www.instagram.com/soundprodigy/
Sundown Sound Co.	Music		San Diego	California	San Diego region	Boutique San Diego audio team providing wedding DJs, sound for live bands and uplighting, with set-up and technicians included in packages.	info@sundownsoundco.com	619-389-9299	https://sundownsoundco.com	https://www.instagram.com/sundownsoundco/
Caprice Strings	Music		San Diego	California	San Diego, La Jolla, Del Mar, Temecula and Orange County	Locally owned string group with almost forty years of San Diego weddings, playing as a trio, duo, quartet or solo violin, classical to pop.	victoria@capricestrings.com	619-363-3368	https://capricestrings.com	https://www.instagram.com/capricestrings/
Eliana Strings	Music		San Diego	California	San Diego	San Diego string ensemble founded in 2011, offering a quartet or trio for wedding ceremonies, cocktail hours and receptions.	info@elianastrings.com	619-363-7083	https://www.elianastrings.com	https://www.instagram.com/eliana_strings/
Glam On The Run	Hair & Makeup		San Diego	California	San Diego area, including La Jolla, Carlsbad and Del Mar	Mobile team of licensed stylists and certified make-up artists doing on-location bridal hair and airbrush or traditional make-up.		917-743-0887	https://www.glamontherun.com	https://www.instagram.com/glam_on_the_run/
Del Beauty Box	Hair & Makeup	910 Camino Del Mar Unit C	Del Mar	California	Del Mar and coastal San Diego	Del Mar beauty studio specialising in soft, skin-focused bridal make-up and hair styling for brides and their wedding parties.		(858) 259-4247	https://delbeautybox.com	https://www.instagram.com/delbeautybox/
Makeup by Dali	Hair & Makeup		San Diego	California	Southern California	Freelance San Diego make-up artist with over seven years of experience, focused on long-wearing make-up for weddings and elopements.	dalisatoro.mbd@gmail.com	(619) 736-8649	https://makeupbydali.com	https://www.instagram.com/makeup.by.dali/
Mili's Sweets	Cake		San Diego	California	San Diego County	Home-based cake maker since 2010 making custom wedding cakes and dessert tables, all peanut and tree-nut free, with vegan and gluten-free options.	sweetsbymili@gmail.com	(760) 571-9876	https://milissweets.com	https://www.instagram.com/milis_sweets/`,
  },
  {
    name: "Sacramento: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Eye Connoisseur Photography	Photography	1200 S St, Ste B	Sacramento	California	California and beyond	Sacramento studio on S Street photographing weddings for over 15 years, known for an unconventional, editorial take and a black-and-white collection.	info@eyeconnoisseur.com	916-444-1222	https://eyeconnoisseur.com	https://www.instagram.com/eyeconnoisseurphotography/
Doug Miranda Photography	Photography		Sacramento	California	Sacramento, Lake Tahoe and Napa	Brooks Institute-trained wedding and engagement photographer with hundreds of weddings behind him, covering Sacramento venues through to Tahoe.	doug@dougmiranda.com	916-422-2256	https://dougmiranda.com	
AB Event Co	Planning		Roseville	California	Northern California	Roseville-based planner offering full, partial and month-of coordination for modern couples, with a relaxed, humorous and transparent approach.			https://abeventco.com	https://www.instagram.com/abeventco/
Blissfully Elegant Events	Planning		Sacramento	California	Sacramento and Northern California	Planning team led by Janelle, who brings 16 years of hotel events experience, offering full service, partial planning and month-of coordination.	blissfullyeleganteventsca@gmail.com		https://www.blissfullyeleganteventsca.com	https://www.instagram.com/blissfullyelegantevents/
Asteria Florals	Florals		Sacramento	California	Sacramento region	East Sacramento floral studio, formerly Mahina + Soul, designing bespoke one-of-a-kind wedding arrangements from seasonal blooms.	info@asteriaflorals.com	916-898-2570	https://www.asteriaweddings.com	https://www.instagram.com/asteriaflorals/
Sacramento DJ Service	Music		Sacramento	California	Greater Sacramento area	Long-running DJ and entertainment company working Sacramento events since 1995, pairing a wide music library with lighting for wedding receptions.	DjKris@SacramentoDjService.com	916-941-5747	https://sacramentodjservice.com	https://www.instagram.com/1djkris/
Beat Fleet DJs	Music		Sacramento	California	Northern California	Sacramento DJ and MC company since 2010, pairing dedicated event hosts with DJs and offering add-ons such as cold sparklers, uplighting and photo booths.		916-866-9698	https://beatfleetdjs.com	https://www.instagram.com/beatfleetdjs/
AnyThyme Catering	Catering		Elk Grove	California	Sacramento, Elk Grove and Northern California	Family-run, women-owned and LGBTQ+ inclusive caterer from Elk Grove, offering buffet wedding menus with full coordination and private tastings.	AnyThymeCateringEG@gmail.com	916-602-9961	https://www.anythymecatering.com	https://www.instagram.com/anythymecateringco/
Spilled Milk Company	Cake		Elk Grove	California	Sacramento, Elk Grove, the Bay Area and San Francisco	Elk Grove cake studio making buttercream and sculpted fondant wedding cakes, with white-glove delivery and on-site styling from about $11 a serving.			https://spilledmilkcompany.com/weddings	https://www.instagram.com/spilledmilk_co/
Cake Castle Bakery	Cake	5601 66th Ave	Sacramento	California		South Sacramento bakery designing one-of-a-kind custom wedding and groom cakes, alongside cake-decorating classes and supplies.	info@cakecastlebakery.com	916-394-4040	https://cakecastlebakery.com	
Anna Bakalym Artistry	Hair & Makeup		Sacramento	California	Sacramento, the Bay Area and destination weddings	Sacramento bridal hair and makeup team led by Anna, favouring soft, timeless looks that enhance rather than change, with clearly published pricing.	hello@annabakalym.com		https://annabakalym.com	https://www.instagram.com/anna_bakalym/
Foxy Glamour	Hair & Makeup		Rocklin	California	Rocklin, Sacramento, Roseville, Folsom, Auburn and Northern California	Rocklin-based bridal hair and makeup artist specialising in skin-first soft glam with a calm, concierge-style wedding morning.	Foxyglamourmua@gmail.com	916-741-8742	https://foxyglamour.com	https://www.instagram.com/foxyglamourmua/
CineCrown Multimedia Studios	Videography	1015 25th St	Sacramento	California	Sacramento, Napa, San Francisco, San Jose and the Bay Area	Midtown Sacramento studio, running since 2005, filming and photographing multicultural weddings including Indian, Filipino, Mexican, Chinese and Vietnamese.		916-800-3388	https://cinecrown.com	https://www.instagram.com/cinecrown/
Wild Flowers Design Group	Florals		Sacramento	California		Family-run Sacramento floral studio, three generations in, working by appointment and focusing on weddings and large events.	DesignTeam@wfdg.info	916-899-1289	https://www.wildflowersdesigngroup.com	https://www.instagram.com/wildflowersdg/
Blooms In Ribbon	Florals	8300 Sierra College Blvd, Ste F	Roseville	California	Greater Sacramento	Roseville flower shop with a full wedding service covering bouquets and ceremony installs, with full wedding florals starting from around $800.	orders@bloomsinribbon.com	916-203-3662	https://bloomsinribbon.com/weddings	https://www.instagram.com/blooms_in_ribbon/
Randy Peters Catering	Catering	105 Vernon St	Roseville	California	Northern California	Caterer with decades of experience and its own Roseville event centre, offering full-service wedding menus, BBQ and bar service.	sales@randypeterscatering.com	916-726-2339	https://randypeterscatering.com	https://www.instagram.com/rpeterscatering/
The Hidden Table	Catering	1767 Tribute Rd, Ste D	Sacramento	California	Sacramento and Lake Tahoe	Farm-to-fork caterer founded by Chef Russ and Linda Lande, cooking locally sourced menus on site for vineyard, backyard and larger weddings.	info@thehiddentablegourmet.com	916-337-8613	https://www.thehiddentablegourmet.com	https://www.instagram.com/thehiddentable/
Authentic Street Taco	Catering		Roseville	California	Greater Sacramento, the Bay Area and San Jose	Family-run Mexican caterer with a fleet of taco trucks, cooking fresh tacos, burritos and homemade tortillas and salsas for relaxed, casual weddings.	Info@authenticstreettaco.com	916-749-8059	https://www.authenticstreettaco.com/wedding-catering/	https://www.instagram.com/authenticstreettaco/
Amid Films	Videography	6929 Sunrise Blvd, Ste 205	Citrus Heights	California	Sacramento, the Bay Area, Lake Tahoe and destinations	Wedding film team working since 2016 from a Citrus Heights studio, making emotional, elegant films across Sacramento, Tahoe and further afield.	info@amidfilms.com	916-521-5299	https://amidfilms.com	
Aperina Studios	Photography	6929 Sunrise Blvd, Ste 202	Citrus Heights	California	Sacramento, across the US and abroad	Sacramento-rooted photo and video team with over 15 years of wedding photography, offering both stills and cinematic films under one booking.	info@aperina.com	916-802-4136	https://aperina.com	https://www.instagram.com/aperinastudios/
New Legacy Films	Videography		Sacramento	California	Greater Sacramento, all of California and destination weddings	Sacramento wedding videography studio crafting cinematic films focused on real emotion, from Sierra elopements to wine-country celebrations.			https://newlegacyfilms.studio	https://www.instagram.com/newlegacy_films/
The Groove Thang Band	Music		Sacramento	California	Northern California and Nevada	Sacramento variety dance cover band playing R&B, funk, Motown, disco, rock and country hits, with hundreds of weddings across Northern California.	manager@groovethangband.com	916-873-2257	https://www.groovethangband.com	
Dragonfly Events & Co.	Planning		Sacramento	California	Sacramento, Napa, Tahoe and destinations	Design-led Sacramento planning firm for high-touch weddings, with full service and design priced at 12% of budget from a $12,000 minimum.	hello@dragonflyeventsandco.com	916-945-6575	https://dragonflyeventsandco.com	https://www.instagram.com/dragonflyeventsco/
MAI Makeup & Hair	Hair & Makeup		Sacramento	California	Sacramento and Northern California	Sacramento bridal artist offering natural, long-wearing makeup and hair with all-day support, experienced with Vietnamese weddings and outfit changes.	mai@maimakeuphair.com		https://maimakeuphair.com	https://www.instagram.com/maimakeuphair/
Pastry Heaven Bakery	Cake	8069 Madison Ave	Citrus Heights	California		Family-owned bakery since 2005, led by a pastry chef with over 30 years of experience, making everything from two-tier rosette cakes to towering designs.		916-965-5408	https://www.pastryheavenbakery.com/pages/wedding-cakes	`,
  },
  {
    name: "Orange County: photography, planning, florals, music, catering, hair and makeup, cake, videography and desserts",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Three16 Photography	Photography	1290 N. Hancock St. Suite 230	Anaheim	California	Orange County, Los Angeles County and wider Southern California	Anaheim studio offering journalistic, natural-light wedding and engagement photography, with videography, albums and photo booth add-ons.	jerrick@three16photography.com	714-408-8428	https://three16photography.com/	https://www.instagram.com/three16photography/
Adam Levinstein Photography	Photography		Laguna Beach	California	Orange, San Diego and Los Angeles counties, plus destination weddings	Laguna Beach photographer with 500-plus weddings behind him, known for candid moments mixed with directed portraits; also offers video and photo booths.	Adam@adam11stein.com	(949) 315-5977	https://adamlevinstein.com/	https://www.instagram.com/adam11stein/
Starry Night Weddings	Photography	519 Alabama Street	Huntington Beach	California	Orange County and destination weddings	Huntington Beach studio photographing weddings across Orange County and further afield, with a separate films section in its portfolio.		(949) 436-9357	https://www.starrynightweddings.com/	https://www.instagram.com/starrynightweddings/
Andy Rodriguez Photography	Photography		Westminster	California	Orange County, Los Angeles, San Diego and destinations	Westminster-based wedding and engagement photographer with about two decades of experience, favouring relaxed direction over stiff posing.	arod@andyrodriguezphoto.com		https://www.andyrodriguezphoto.com/	https://www.instagram.com/arodphoto/
Prince Weddings	Photography	5505 East Santa Ana Canyon Road	Anaheim	California	Orange County, Los Angeles, Temecula and San Diego	Anaheim firm with over 20 years in business, covering weddings with photography and cinematic video, plus same-day edits and film options.	Nprince@PrinceWeddings.net	(949) 478-5322	https://www.princeweddings.net/	
Todd Avery Photo	Photography		Newport Beach	California	Newport Beach, Orange County, Kauai, New York and London	Newport Beach wedding, engagement and family photographer with more than 20 years of experience, travelling to Kauai, New York and London.			https://www.toddaveryphoto.com/	
Wish Wonder Dream	Planning		Newport Beach	California	California, Great Britain and Cabo San Lucas, with worldwide travel	Newport Beach wedding coordination and styling team, working since 2007, with its own planning tools and weekday, evening and weekend appointments.	inquiries@wishwonderdream.com	626-689-4004	https://www.wishwonderdream.com/	https://www.instagram.com/wishwonderevents/
KLLR Events	Planning		Costa Mesa	California	Orange County and Los Angeles	Costa Mesa planner with over 15 years behind her, handling full planning and day-of coordination for weddings, parties and corporate events.	roschlynn@gmail.com		https://www.kllrevents.com/	
The Marigold Company	Planning		Irvine	California	Southern California, with weddings in Newport Beach and beyond	Irvine planner focused on South Asian weddings, blending traditional customs with modern design across multi-day celebrations; a decade in business.	hello@themarigoldcompany.com		https://www.themarigoldcompany.com/	https://www.instagram.com/marigoldcompany/
Love & Life Events	Planning		Huntington Beach	California	Orange County and Los Angeles	Huntington Beach planners experienced with Filipino, Asian-American and blended celebrations, offering full planning, day management and design.	hello@loveandlife.events		https://www.loveandlife.events/	https://www.instagram.com/loveandlife.events/
Events by Katherine	Planning		Lake Forest	California	Southern California	Lake Forest wedding planning team, running since 2009, offering options from full planning through to day-of coordination.			http://www.eventsbykatherine.com/	
Cherished Moments Weddings and Events	Planning		Cypress	California	Los Angeles, Orange, Riverside, San Bernardino and San Diego counties, plus Long Beach	Cypress planning and coordination team covering Orange County and much of Southern California, with day-of coordination among its services.	info@eventsbycherishedmoments.com	(714) 310-2734	https://www.eventsbycherishedmoments.com/	https://www.instagram.com/eventsbycherishedmoments/
Memory Machine Films	Videography		Laguna Niguel	California	Orange County, Los Angeles, San Diego and the Inland Empire	Laguna Niguel videographers offering highlight films with documentary-style edits of ceremonies and toasts across Southern California.		(949) 441-1227	https://www.memorymachinefilms.com/	https://www.instagram.com/memorymachinefilms/
Once & Always Films	Videography		Lake Forest	California	Orange County	Lake Forest wedding videographer making personal, emotional films with attention to small details rather than conventional wedding video styles.	onceandalwaysfilms@gmail.com		https://onceandalwaysfilms.com/	
Tustin Florist	Florals	920 N Main St	Orange	California	Orange County, Los Angeles County	Long-running family flower shop in Orange offering custom wedding designs, consultations and delivery to venues across Orange County.	henry@tustinflorist.com	(714) 289-4420	https://tustinflorist.com/	https://www.instagram.com/tustinflorist/
Blooming Gala	Florals		Fountain Valley	California	Orange County, Los Angeles, Riverside and parts of San Diego County	Fountain Valley florist making wedding bouquets, boutonnieres, arches and centrepieces from locally sourced flowers, with delivery and setup included.	bloominggala@gmail.com	(714) 329-7272	https://www.bloominggala.com/	https://www.instagram.com/bloominggala/
Laguna Beach Florist	Florals	540 S Coast Hwy #105	Laguna Beach	California	Laguna Beach, South Orange County	Family-run Laguna Beach flower shop and design studio creating wedding and event florals, from intimate dinners to larger installations, since 2006.		(949) 464-0509	https://www.lagunabeachflorist.com/	https://www.instagram.com/lagunabeachflorist/
Little Shop By The Sea	Florals	506 W Balboa Blvd Unit B	Newport Beach	California	Newport Beach, Orange County	Newport Beach studio designing airy, seasonal bridal and event flowers using plastic-free, foam-free methods, from bud vases to full weddings.	hello@littleshopbythesea.com	(949) 662-0111	https://www.littleshopbythesea.com/	https://www.instagram.com/thelittleshopbythesea/
M Floral Design	Florals		Irvine	California	Orange County, Los Angeles, San Diego	Irvine florist, by appointment only, doing ceremony arches, aisle flowers, reception centrepieces and bridal bouquets with delivery, setup and breakdown.	mfloraldesign@outlook.com		https://www.mfloraldesign.com/	https://www.instagram.com/mfloraldesign.ca/
Kate Flowers LA-OC	Florals	17155 Von Karman, Unit 107	Irvine	California	Orange County, Los Angeles	Irvine floral design studio providing wedding ceremony and reception flowers, bouquets, tablescapes and custom installations, plus corporate and private events.	kate@kateflowersla.com	(949) 558-4605	https://www.kateflowersla.com/	https://www.instagram.com/kateflowersla/
Radiate Productions	Music		Westminster	California	Orange County	Wedding DJ and photo booth company with bilingual English and Vietnamese MC services, ceremony sound and a 50,000-song reception library.	info@radiatepro.com		https://radiatepro.com/	https://www.instagram.com/radiateproductions/
Harp Enchants	Music		Newport Beach	California	Orange County, Los Angeles, San Diego	Newport Beach harpist Sonia Marie Olivas, playing ceremonies and receptions around Orange County, from Laguna Beach and Irvine to Anaheim and Costa Mesa.		949.734.0249	https://www.harpenchants.com/	
Beauty By Lishma	Hair & Makeup		Irvine	California	Orange County, Los Angeles, wider California	Irvine bridal team offering hair, makeup, henna and saree setting for South Asian brides and their families, travelling to the wedding.	info@BeautyByLishma.com	(714) 721-8502	https://www.beautybylishma.com/	https://www.instagram.com/beautybylishma/
Makeup by Coyotzi	Hair & Makeup		Irvine	California	Orange County, Los Angeles, Southern California	Irvine artist Elizabeth Coyotzi does on-location bridal hair and makeup, with trial previews, bridal party packages and quinceañera looks.	Info@makeupbycoyotzi.com		https://www.makeupbycoyotzi.com/	https://www.instagram.com/makeupbycoyotzi/
The Vanity Belle	Hair & Makeup	10090 Adams Avenue	Huntington Beach	California	Orange County, San Diego	Network of artists offering bridal makeup, including airbrush, plus hairstyling, trials and group lessons, travelling to couples on location.	info@thevanitybelle.com	657.204.0408	https://www.thevanitybelle.com/	https://www.instagram.com/vanitybelles/
Brivbeauty	Hair & Makeup	13011 Newport Ave Unit 110	Tustin	California	Orange County, Los Angeles, San Diego, Palm Springs	Bridal hair and makeup team working on location or in a Tustin salon, including multi-day looks for mehndi, sangeet and haldi celebrations.	Info@Brivbeauty.com	(949) 501-1973	https://www.brivbeauty.com/	https://www.instagram.com/brivbrides/
OC Beauty by Elizabeth	Hair & Makeup		Irvine	California	Orange County, LA, Riverside and San Diego counties	Irvine-based mobile bridal hair and makeup, offering airbrush or traditional makeup, updos and waves, with paid trials ahead of the day.	ocbeautybyelizabeth@gmail.com	949-306-7846	https://www.ocbeautybyelizabeth.com/	https://www.instagram.com/ocbeautybyelizabeth/
Blossom Beauty Team	Hair & Makeup		Huntington Beach	California	Orange County, Los Angeles, San Diego	Wedding-only on-location hair and makeup team led by Sasha, covering bridal parties from Newport Beach to San Clemente and Laguna Beach.		+1 (657) 365-9249	https://www.blossombeautyteam.com/	https://www.instagram.com/blossom_beautyteam/
24 Carrots Catering & Events	Catering	150 Baker Street East	Costa Mesa	California	Orange County and wider Southern California	Full-service wedding caterer in Costa Mesa with a planning team that guides couples through menus, service style and event logistics.	info@24carrots.com	714.942.6000	https://www.24carrots.com/	https://www.instagram.com/24carrotscatering/
Saiga Vietnamese Eatery	Catering	17805 Sky Park Circle, Suite B	Irvine	California	Orange County	Irvine Vietnamese kitchen that builds custom catering menus for weddings, corporate events and home celebrations.	info@saigaeatery.com		https://saigaeatery.com/	https://www.instagram.com/saiga.eatery/
Canyon Catering	Catering		Anaheim	California	Anaheim, Orange, Santa Ana, Fountain Valley, Tustin, Irvine, Huntington Beach, Newport Beach	Family-run Anaheim caterer, in business since 1991, offering scratch-made menus, plated dinners, BBQ options and custom bars for weddings.	info@canyoncatering.net	714-970-7777	https://canyoncatering.net/	https://www.instagram.com/canyoncatering/
Taylor Made Cuisine	Catering	17945 Sky Park Circle, Suite G	Irvine	California	Orange County and Los Angeles	Irvine caterer with dedicated wedding coordinators, offering plated dinners, cocktail hours and grazing tables with vegan and gluten-free choices.		714.342.6454	https://www.taylormadecuisine.com/	https://www.instagram.com/_taylormadecatering/
Love At First Bite Catering	Catering	18281 Gothard St #108	Huntington Beach	California	Orange County, Los Angeles, Riverside and the Inland Empire	Family-founded Huntington Beach caterer, operating since 1982, providing wedding menus, hors d'oeuvres, rentals and venue recommendations.	info@lafbcatering.com	(714) 375-5566	https://www.lafbcatering.com/	https://www.instagram.com/loveatfirstbitecatering/
Nomada Gourmet Taco Catering	Catering	2 Park Plaza #450	Irvine	California	Orange County and Los Angeles County	Irvine taco-catering company serving modern Mexican menus from a mobile kitchen for weddings, corporate events and private parties.	info@tastenomada.com		https://www.tastenomada.com/	https://www.instagram.com/tastenomada/
SOHO TACO	Catering	132 E Dyer Rd.	Santa Ana	California	Orange County and Los Angeles	Santa Ana taco caterer offering on-site grilling, taco carts and wedding packages with salsa bars and appetisers.	info@sohotaco.com	714-793-9392	https://sohotaco.com/	https://www.instagram.com/sohotaco/
Rasta Taco	Catering	170 Beach Street	Laguna Beach	California	Orange County, Los Angeles, Inland Empire, Palm Springs, San Diego County and Santa Barbara	Laguna Beach taco caterer providing full-service wedding catering with signature tacos, fresh salads and vegetarian options across Southern California.	info@rastataco.com	866-967-3782	https://rastataco.com/	https://www.instagram.com/rastataco/
CocoaBerry Cake Co.	Cake		Placentia	California	Orange County	Placentia bakery making custom wedding cakes in themed collections, alongside macarons, cupcakes and decorated cookies.	info@cocoaberrycake.com	(949) 478-0440	https://www.cocoaberrycake.com/	https://www.instagram.com/Cocoaberrycakeco/
Simply Sweet Cakery	Cake	2930 Grace Lane F	Costa Mesa	California	Orange County	Costa Mesa bakery making wedding cakes from rustic to modern, plus cookies, cupcakes and dessert spreads to match.			https://www.simplysweetcakery.com/	https://www.instagram.com/simplysweetcakery/
Pacific Patisserie	Cake	2630 Walnut Ave. Unit H	Tustin	California	Orange County	Tustin patisserie making custom wedding cakes and pastries, with tasting consultations available by appointment only.		1.714.549.2808	https://pacificpatisserie.com/	https://www.instagram.com/pacificpatisserieofficial/
French's Cupcake Bakery	Cake	273 E. 17th Street	Costa Mesa	California	Orange County	Costa Mesa full-line bakery making custom wedding cakes and cupcakes, with a menu of cookies, pies, breads and pastries too.		(949) 642-0571	https://frenchscupcakebakery.com/	https://www.instagram.com/frenchs_cupcake_bakery/
Beverly's Bakery	Cake	3020 Brea Blvd.	Fullerton	California	Orange County	Fullerton family bakery making custom wedding and quinceañera cakes, cupcakes and dessert tables, with a dedicated wedding cakes page.	cake@beverlysbakery.com	714-529-3989	https://www.beverlysbakery.com/	https://www.instagram.com/beverlysbakery/
Plumeria Cake Studio	Cake	27001 La Paz Rd, Ste 460	Mission Viejo	California	Orange County	Mission Viejo studio designing wedding cakes and desserts around each couple's flavours and style.	info@plumeriacakes.com	(949) 422-1945	https://plumeriacakes.com/	
Sweet Traders	Cake	5362 Oceanus Drive, Suite C	Huntington Beach	California	Orange County	Huntington Beach boutique bakery, open since 2004, handmaking wedding cakes and chocolate desserts, with a dedicated wedding inquiry form.		714-903-6800	https://www.sweettraders.com/	https://www.instagram.com/sweettraders/
Something Sweet Catering Co.	Desserts		Anaheim	California	Orange County, Los Angeles and the Inland Empire	Anaheim mobile dessert caterer running churro, mini-pancake, banana-split, paleta and açaí carts for weddings and private events.			https://www.somethingsweetchurros.com/	
`,
  },
  {
    name: "Napa and Sonoma: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Lily Rose Photography	Photography	1055 Broadway, STE. E1	Sonoma	California	Napa, Sonoma and Northern California	Sonoma studio run by Debbie and Larry Labrot, photographing weddings at Napa and Sonoma wineries and resorts alongside portrait and corporate work.	info@lilyrosephotography.com	(707) 603-9062	https://www.lilyrosephotography.com	
Alicia Parks Photography	Photography		Santa Rosa	California	Sonoma County, Napa Valley and San Francisco	Santa Rosa photographer focused on vineyard weddings, intimate elopements and San Francisco city celebrations across Sonoma and Napa.	info@aliciaparksphotography.com	707-843-1126	https://aliciaparksphotography.com	https://www.instagram.com/alicia_parks_photography/
Viva Sonoma Photography	Photography		Santa Rosa	California	Sonoma, Napa, Lake and Marin counties	Family-run Santa Rosa studio with 15 years behind it, offering wedding and quinceañera photography, highlight films and photo booths.	info@vivasonomaphotography.com	707.508.1344	https://www.vivasonomaphotography.com	https://www.instagram.com/vivasonomamedia/
Loren Hansen Photography	Photography		Petaluma	California	Sonoma County, Santa Rosa, Marin and Mendocino	Petaluma photographer shooting candid, documentary-style weddings and non-traditional celebrations, working with a small team and avoiding posed fluff.	lorenhansenphotography@gmail.com		https://lorenhansenphotography.com	
Holly B Rose Photography	Photography		Santa Rosa	California	Sonoma, Napa, Petaluma, Healdsburg, Mendocino Coast and Sea Ranch	Santa Rosa photographer making relaxed, natural wedding, couple and family images across Wine Country and the Mendocino coast.	hollybrosephotography@gmail.com		https://www.hollybrosephotography.com	https://www.instagram.com/holly.b.rose/
Michelle Angeli	Photography		Sonoma	California	California	Sonoma photographer who also shoots Super 8 video, plans and does florals, running all-inclusive weddings for fun-loving couples.	hello@michelleangeli.com		https://michelleangeli.com	https://www.instagram.com/michelleangeliphoto/
Wedlock Cinema	Videography		Napa	California	Napa Valley and beyond	Napa filmmaker Sean Pettis, making luxury wedding films at Napa Valley wineries and resorts for over twenty years.	info@wedlockcinema.com	707-280-6056	https://www.wedlockcinema.com	https://www.instagram.com/wedlockcinema/
Moonstruck Films	Videography		Napa	California	Sonoma County, Napa County and Northern California	Napa-based filmmaker Lenon creating cinematic, emotion-led wedding films at wineries and venues across Northern California.			https://moonstruck-films.com	https://www.instagram.com/moonstruck_films/
Mendocino Photo & Video	Videography	716 Mill St	Santa Rosa	California	Sonoma, Mendocino and Northern California	Santa Rosa studio filming and photographing weddings in a warm, documentary style across Sonoma, Mendocino and Northern California.	weddings@mendocinophoto.com	707-397-5557	https://mendocinophoto.com	https://www.instagram.com/nilesprague/
Jana Contreras Photography & Videography	Videography		Sonoma	California	California	Sonoma duo Jana and Eli, filming and photographing weddings with a documentary feel and live sound, and featured in Sonoma Magazine.	Janacontrerasphotography@gmail.com		https://janacontrerasphotography.com	https://www.instagram.com/janacontrerasphotography/
Denise Kramer Weddings	Planning		Petaluma	California	Sonoma and Napa Valley wine country	Petaluma planner working since 2007, offering month-of coordination, mid-range and full planning, plus a fixed-price elopement package across 22+ venues.	denisemkramer@gmail.com	(707) 775-7931	https://www.denisekramerweddings.com	
Detailed Dreams Events	Planning		Napa	California	Napa Valley and Sonoma wine country	Napa full-service planning and design studio that curates venue, vendors and timeline, and is booking weddings into 2028.		(707) 779-9266	https://detaileddreamsevents.com	https://www.instagram.com/detaileddreamsevents/
Cole Drake Events	Planning	1447 Fourth Street, Suite 3	Napa	California	Napa and Sonoma wine country	Napa luxury planning and design studio that pairs practical timelines and family-dynamics handling with an understated, unperformative style.	info@coledrake.com	(707) 304-5921	https://www.coledrake.com	https://www.instagram.com/coledrakeevents/
Amoureux Events	Planning		Napa	California		Napa planner offering full and partial planning, day-of coordination, design and decor, with a free initial consultation for couples.	amoureuxevents@gmail.com	707-738-3790	https://www.amoureuxevents.com	https://www.instagram.com/amoureux_events/
Jaime Tosti Events	Planning		Santa Rosa	California		Santa Rosa planner covering full-service planning, partial planning, wedding coordination and design for couples marrying around Sonoma County.	jaime@jaimetostievents.com		https://www.jaimetostievents.com	https://www.instagram.com/jaimetostievents/
Vanda Floral Design	Florals	501 Petaluma Blvd. North	Petaluma	California	Petaluma area	Petaluma florist with a shop and separate design studio, supplying ceremony, personal and reception flowers plus a wedding FAQ for couples.	info@vandafloral.com	(707) 763-9271	https://www.vandafloral.com	https://www.instagram.com/vandafloraldesign/
SoCo In Bloom	Florals	150 Professional Center Dr., Suite B	Rohnert Park	California	Sonoma County	Rohnert Park studio inside Point West Flower Market, designing weddings and events with Sonoma County flowers, with full-service and a-la-carte options.	hello@socoinbloom.com	707-489-3138	https://www.socoinbloom.com	https://www.instagram.com/socoinbloom/
Violets of the Valley	Florals		Napa	California	Northern California and destination	Napa Valley studio known for modern, sculptural and slightly edgy wedding florals, also working on corporate and destination events.		707-297-9545	https://www.violetsofthevalley.com	https://www.instagram.com/violetsofthevalley/
EV Floral Design	Florals	1373 Lincoln Ave	Calistoga	California	Napa Valley	Calistoga atelier creating bespoke wedding florals, from bouquets to ceremony arches and wearables, and now booking the 2027 season.	erica@evfloraldesign.com	(707) 341-3474	https://www.evfloraldesign.com	https://www.instagram.com/evfloraldesign/
Old Skool DJs & Photo Booth	Music		Napa	California	Napa, Sonoma and surrounding Northern California counties	Napa DJ and photo booth team led by DJ Marcus T of Timex Social Club, offering MC duties and a music library spanning the 1920s to 2010s.		(707) 410-0083	https://oldskooldjs.com	
Santa Rosa DJ	Music		Santa Rosa	California	Sonoma County, Napa Valley, Marin and the wider Bay Area	Independent Santa Rosa DJ service running since 1982, offering ceremony and reception music, MC work, lapel mics and LED uplighting.		707-263-7690	https://www.santarosadj.com	https://www.instagram.com/bayareadj/
Aon Events	Music		Santa Rosa	California	Sonoma County, Napa, Marin, Healdsburg, Sebastopol and Novato	Santa Rosa DJ and MC company since 2013, with 600 weddings behind it and sound, lighting and photo booths available as add-ons.	Info@aonevents.net	(760) 525-7794	https://www.aonevents.net	
Case Entertainment	Music	1731 Walnut Creek Dr	Santa Rosa	California	North Bay, including Napa, Sonoma and Marin counties	Santa Rosa wedding DJ and emcee service with packages that include cordless mics, dance floor lighting, uplighting and monogram projection.		707-591-3397	https://www.caseentertainment.net	https://www.instagram.com/case_entertainment/
Harpeggio Music	Music		Petaluma	California	Sonoma, Napa, Marin and the wider San Francisco Bay Area	Harpists based in Petaluma and San Jose playing classical and popular repertoire for ceremonies, cocktail hours and dinner receptions.		(707) 338-3176	https://www.harpeggio.com	
Oak Avenue Catering	Catering	1314 Oak Avenue	St. Helena	California	Napa and Sonoma Valleys	St. Helena caterer with four decades in wine country, cooking farm-to-table menus from plated dinners to family-style spreads, plus a food truck.		707.963.9278	https://www.oakavenuecatering.com	
Marks The Spot Fine Food Catering & Events	Catering	20 Enterprise Court, #9	Napa	California	Wine Country and Napa Valley	Chef-owned Napa caterer with a mobile kitchen, wood-fired oven and food truck, offering plated, family-style and buffet wedding menus.	events@marksthespotfinefood.com	707.738.8404	https://www.marksthespotfinefood.com	https://www.instagram.com/marksthespotfinefood/
Chef Adair	Catering	538 East Cotati Ave	Cotati	California	Sonoma, Napa, Marin and the San Francisco Bay Area	Cotati chef-owned caterer since 2004, serving scratch-made California menus for 2 to 300 guests with bartenders, servers and wine pairing.		707-795-3675	https://www.chefadair.com	https://www.instagram.com/chefadair/
Nomad Provisions	Catering	545 Pacific Ave	Santa Rosa	California	Sonoma County, from Santa Rosa to Healdsburg, Petaluma and Sonoma	Wood-fired caterer cooking pizzas, proteins and oysters live from a self-contained oven built in Sonoma County, needing no kitchen on site.	info@nomad-provisions.com	(707) 909-0374	https://www.nomad-provisions.com	https://www.instagram.com/nomadprovisionsco/
Rancho Los Potrillos	Catering	4246 Whistler Ave	Santa Rosa	California	Santa Rosa, Petaluma, Rohnert Park, Cotati, Windsor, Sebastopol and Sonoma County	Family-run Santa Rosa taqueria catering wedding taco bars with a spit of al pastor, carne asada and chicken for 50 to 300+ guests.		(707) 331-4228	https://www.rancholospotrillos.com	
Heidi West Catering	Catering		Healdsburg	California	Sonoma County, Napa Valley and the greater Bay Area	Chef-led caterer with bases in Healdsburg and Larkspur, catering weddings at select wineries alongside private and corporate events.		707.696.9120	https://www.heidiwestcatering.com	
Contour Bridal	Hair & Makeup		Santa Rosa	California		Santa Rosa team of bridal hair stylists and makeup artists offering consultations and multi-stylist bookings for larger wedding parties.	taylor@contourbridal.com	(888) 719-4646	https://www.contourbridal.com	https://www.instagram.com/contourbridal/
Ritual Salon	Hair & Makeup	480 Mendocino Ave	Santa Rosa	California	Sonoma, Napa, Marin and Mendocino counties	Santa Rosa salon whose collective of stylists and makeup artists handles wedding mornings, with a dedicated weddings team and in-house coordination.	info@ritualsr.com	707-890-5546	https://ritualsalons.com	https://www.instagram.com/ritual.salons/
Bella Bridal Napa Valley	Hair & Makeup	700 Central Ave, Suite C	Napa	California	Napa Valley and wider Wine Country, including Sonoma	Napa team of hair and makeup artists working on location at wine country venues, with natural, polished looks and airbrush offered through selected artists.	bellabridalnv@gmail.com	408.206.1534	https://www.bellabridalnv.com	
Rachel Lusk Hair & Makeup	Hair & Makeup		Napa	California	Napa Valley and destination weddings worldwide	Napa Valley bridal hair and makeup artist offering on-location styling for weddings, who also runs education work for other artists.	hello@rachellusk.com		https://www.rachellusk.com	https://www.instagram.com/rachel.luskhmua/
Devotion Studio	Hair & Makeup		Sebastopol	California	Sonoma County, Napa Valley, Marin, Mendocino, Lake and Shasta counties	Sebastopol bridal team doing romantic hair and natural makeup, with studio previews, travel to venues and lash and extension options.			https://www.devotedtobeauty.com	
Costeaux French Bakery	Cake	417 Healdsburg Ave	Healdsburg	California		Long-established Healdsburg French bakery and cafe, open since 1923, making customised classic wedding cakes alongside its everyday baking.	info@costeaux.com	707.433.1913	https://www.costeaux.com	https://www.instagram.com/costeauxfrenchbakery/
SWEET Wedding Cakes	Cake		Sonoma	California		Sonoma custom cake studio of designer Jill Habansky, making wedding cakes to order and offering paid tastings in town.	jill@sweetcakesonoma.com	415-852-2586	https://www.sweetcakesonoma.com	https://www.instagram.com/sweetcakesonoma/
Scandia Bakery	Cake	500 W Napa St Ste 542	Sonoma	California		Neighbourhood Sonoma bakery in the Valley Mart shopping centre that bakes wedding and custom cakes alongside sandwiches, soups and coffee.	scandiabakery@hotmail.com	(707) 938-5820	https://www.scandiabakery.com	
Sonoma Cake Creations	Cake		Santa Rosa	California	Wine Country and the Bay Area	Santa Rosa bakery with over 20 years behind it, known for smooth frosted cakes and award-winning cheesecake wedding cakes.		(707) 486-8581	https://sonomacake.com	https://www.instagram.com/sonomacake/
Preferred Sonoma Caterers	Catering	416 East D Street	Petaluma	California	Sonoma, Napa and Marin counties	Petaluma wine country caterer offering custom menus, staffing, rentals and event planning, with vegan, vegetarian and gluten-free options.	letsparty@sonomacaterers.com	(707) 769-7208	https://www.sonomacaterers.com	
`,
  },
  {
    name: "Santa Barbara: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Pinnel Photography	Photography		Santa Barbara	California	California and destinations	Santa Barbara wedding photographer who documents celebrations with close attention to light, architecture and design.			https://pinnelphotography.com	https://www.instagram.com/pinnelphotography/
Vita-Bella Photography	Photography	1233-B State Street	Santa Barbara	California	Santa Barbara, Santa Ynez, Montecito and the Central Coast	Santa Barbara studio with more than twenty years of experience, shooting weddings, engagements, elopements and family portraits.	info@amylundstromphotography.com	(805) 637-1933	https://vita-bellaphotography.com	https://www.instagram.com/vitabellaphoto/
Kaitie Brainerd Photography	Photography		Santa Barbara	California	Southern California and beyond	Santa Barbara wedding photographer shooting film and digital, with a relaxed, party-minded style of candid moments and portraits.	kaitiebrainerd@gmail.com	805-680-4363	https://kaitiebrainerd.com	https://www.instagram.com/kaitiebrainerdphoto/
ByCherry Photography	Photography		Santa Barbara	California	Santa Barbara and beyond	Santa Barbara photographer for weddings, courthouse elopements, engagements and portraits, working in an informal, relaxed style.	bycherryphoto@gmail.com		https://www.bycherryphotography.com	https://www.instagram.com/bycherryphotography/
Anna Delores Photography	Photography		Santa Barbara	California	Central California, San Luis Obispo, Ventura County, Ojai, Big Sur	Santa Barbara wedding and elopement photographer offering a clean, refined style for couples who want a calm, unhurried day.	studio@annadelores.com		https://annadelores.com	https://www.instagram.com/annadelores/
Katrina Marie Photography	Photography		Santa Barbara	California	California coast and destinations	Santa Barbara wedding photographer using digital and 35mm film for warm, story-led images with a documentary and editorial feel.			https://kcmariephoto.com	https://www.instagram.com/katrina.marie.photo/
Leslie Joy Photography	Photography		Santa Barbara	California	Santa Barbara, Montecito, Summerland, Carpinteria, Ventura, Ojai	Santa Barbara wedding photographer making light-filled, modern editorial images with quiet direction and an emphasis on real emotion.			https://lesliejoyphotography.com	https://www.instagram.com/lesliejoyphotography/
Hovey Films	Videography		Santa Barbara	California		Santa Barbara wedding filmmakers making cinematic, documentary-style films that centre on natural light and emotional vows.			https://www.hoveyfilms.com	https://www.instagram.com/hoveyweddingfilms/
Jeremy Foster Films	Videography		Santa Barbara	California	Santa Barbara, Montecito, Ojai and Southern California	Santa Barbara wedding videographer making calm, documentary-style films built around real moments and thoughtful composition.	jeremy@jeremyfosterfilms.com		https://jeremyfosterfilms.com	https://www.instagram.com/jeremyfosterfilms/
Agape Films	Videography	827 State St	Santa Barbara	California	Santa Barbara, Montecito and the California coast	Santa Barbara wedding videographer making cinematic films that give weight to family and faith as well as the couple's romance.	nico@agapefilms.net	(805) 364-4475	https://www.agapefilms.net	
Santa Barbara Wedding Films	Videography		Santa Barbara	California	Santa Barbara, with travel	Boutique Santa Barbara wedding videography studio that takes on a limited number of weddings a year, with drone footage available.	SantaBarbaraWeddingFilms@gmail.com	805-886-3463	https://www.santabarbaraweddingfilms.com	https://www.instagram.com/santabarbaraweddingfilms/
Onyx & Redwood	Planning		Santa Barbara	California	Santa Barbara, California and destinations	Santa Barbara wedding planner offering full-service planning and coordination with an unconventional, personality-led approach to the day.	info@onyxandredwood.com	805-335-1598	https://onyxandredwood.com	https://www.instagram.com/onyxandredwood/
Coastal Rose Events	Planning		Santa Barbara	California	Santa Barbara County	Santa Barbara planning company running weddings, elopements, micro-weddings and other events, with work shown at local wineries and clubs.			https://coastalroseevents.com	https://www.instagram.com/coastalrose.events/
SB Wedding Coordinator	Planning		Santa Barbara	California	Santa Barbara	Toby has coordinated Santa Barbara weddings for around 25 years, handling organisation and day-of running so couples can relax.			https://sbweddingcoordinator.com	https://www.instagram.com/sbweddingcoordinator/
Gatherings for Good	Planning		Santa Barbara	California	Santa Barbara County and Central Coast	Brenda Cali plans weddings, micro-weddings, elopements and courthouse ceremonies, as well as non-profit and corporate events, across the county.	brenda@gatheringsforgood.com	805-399-2585	https://gatheringsforgood.com	https://www.instagram.com/gatheringsforgoodevents/
Weddings with Angie	Planning		Santa Barbara	California	Santa Barbara, Montecito, Santa Ynez Valley and Central Coast	Full-service wedding planning and coordination company with over 20 years of event experience, offering tiered packages for weddings and other events.	angie@weddingswithangie.com		https://weddingswithangie.com	https://www.instagram.com/weddingswithangie/
Magnolia Event Design	Planning		Santa Barbara	California	Santa Barbara, Montecito, Santa Ynez Valley and Los Angeles	Wedding planning and design led by Santa Barbara native Lindsey Hartsough since 2006, including winery and private-estate weddings.			https://www.magnoliaeventdesign.com	https://www.instagram.com/magnoliaed/
KB Events	Planning		Santa Barbara	California	Santa Barbara	Full-service wedding planning company established in 2008, producing weddings at venues such as the Biltmore and Montecito estates.	info@kbeventssb.com	805-895-2030	https://kbeventssb.com	https://www.instagram.com/kbeventssb/
Our Society's Events	Planning		Santa Barbara	California	Montecito, Santa Ynez Valley, Ojai and Los Angeles	Event planning company covering budgeting, design and day-of execution for weddings, plus corporate and private events.	Admin@OurSocietysEvents.com	805-869-1793	https://www.oursocietysevents.com	https://www.instagram.com/oursocietysevents/
Jaus of Vern	Florals		Santa Barbara	California	Santa Barbara, Ventura, Ojai and Los Angeles counties	Wedding florist with a low-intervention, nature-led approach to design, serving the Central Coast and Los Angeles area.	events@jausofvern.com		https://www.jausofvern.com	https://www.instagram.com/jausofvern/
Jenny Mann Floral Design	Florals		Santa Barbara	California	Santa Barbara, Goleta, Montecito and Santa Ynez Valley	Florist with over 20 years of experience offering full-service wedding flowers or DIY options, plus vase rentals and consultations.			https://www.jennymannfloraldesign.com	https://www.instagram.com/jennymannfloral/
ella & louie flowers	Florals		Santa Barbara	California	Ventura, Ojai, Santa Barbara and Santa Ynez Valley	Florist taking bookings for weddings and events, with a pricing guide and a la carte centerpieces, bouquets and cocktail-table arrangements.	studio@ellaandlouie.com		https://www.ellaandlouie.com	https://www.instagram.com/ellaandlouieflowers/
Blue Blossoms	Florals		Santa Barbara	California	Santa Barbara and Goleta	Santa Barbara and Goleta florist offering seasonal wedding and event florals alongside daily flower delivery and workshops.	events@blueblossoms.online	805-689-8438	https://blueblossoms.online	https://www.instagram.com/blueblossoms.online/
Coco Rose Design	Florals		Santa Barbara	California		Floral design company for weddings and events, led by designer Nina Morris, working with a classic, charming style.	hello@cocorosedesign.com	805-455-7944	https://www.cocorosedesign.com	https://www.instagram.com/cocorosedesign/
Alpha Floral	Florals	1810A Cliff Drive	Santa Barbara	California	Santa Barbara, Goleta, Montecito, Carpinteria, Santa Ynez and Ojai	Family florist trading since 1935 with a Cliff Drive shop, offering wedding flower consultations as well as daily delivery.	alphafloral@gmail.com	805-965-5165	https://alphafloralsb.com	https://www.instagram.com/alphafloral/
Santa Barbara Floral Artistry	Florals		Santa Barbara	California	Santa Barbara, Goleta, Montecito, Carpinteria and Santa Ynez	Florist led by Ruben Casillas with over 15 years of design experience, handling personal and large-scale wedding and event flowers.	sbfloralartistry@gmail.com	805-570-0774	https://santabarbarafloralartistry.net	https://www.instagram.com/santa_barbara_floral_artistry/
DJ JAS Productions	Music		Santa Barbara	California	Santa Barbara and Los Angeles	Wedding DJ offering mixing for ceremony, cocktail hour, dinner and dancing, with room lighting, uplighting and optional day-of coordination.	info@djjasproductions.com	(805) 204-4037	https://djjasproductions.com	https://www.instagram.com/djjasproductions/
Scott Topper DJ Productions	Music		Santa Barbara	California	Santa Barbara, the Central Coast, Ventura and Los Angeles	Team of three DJ and MC hosts providing wedding sound, LED uplighting, photo booth, dance floor and silent disco hire.	scott@scotttopperproductions.com	(805) 965-7978	https://santabarbaraweddingdjs.com	https://www.instagram.com/scotttopperproductions/
DJ Zeke SB	Music		Santa Barbara	California	Central Coast tri-county area	Mobile DJ and MC service for weddings and events on the Central Coast, with photo booth hire available alongside the music.		(805) 698-0791	https://www.djzekesb.com	https://www.instagram.com/djzekesb/
Santa Barbara String Quartet	Music		Santa Barbara	California	Santa Barbara, Montecito, Goleta, Carpinteria, Ojai, Santa Ynez and Los Olivos	Strings ensemble, established 1985, playing quartet, trio, duo or solo sets for wedding preludes, ceremonies and cocktail hours.	emily.sommermann@gmail.com		https://santabarbarastringquartet.com	https://www.instagram.com/santabarbarastringquartet/
Sam Adams Guitarist	Music		Santa Barbara	California	Santa Barbara, Montecito, Santa Ynez Valley, Ventura, Ojai and Los Angeles	Solo guitarist playing flamenco, classical, Spanish and Brazilian styles for wedding ceremonies and receptions, with over 1,000 weddings played.			https://www.sbguitarist.com	
Rare Harmony (Valerie Saint Martin)	Music		Santa Barbara	California	Santa Barbara and beyond	Harpist and opera singer offering solo harp or harp with vocals for wedding ceremonies and receptions, with PA system provided for up to 120 guests.	music@valeriesaintmartin.com		https://www.valeriesaintmartin.com	https://www.instagram.com/harpeggiovoice/
Kailey Shaffer Violinist	Music		Santa Barbara	California	Santa Barbara, Montecito, Carpinteria, Ojai, Ventura, Solvang and San Luis Obispo	Wedding and event violinist creating custom setlists for ceremonies and receptions, mixing classical sound with a modern feel.			https://www.kaileyshafferviolinist.com	https://www.instagram.com/kaileyshafferviolinist/
Solera & Co.	Catering		Santa Barbara	California	Santa Barbara County, Santa Ynez Valley, Montecito and Goleta	Full-service wedding caterer with seasonal local menus from plated dinners to street-food stations, plus bar service, staffing and private tastings.	info@soleraandcompany.com	(805) 566-1822	https://soleraandcompany.com	https://www.instagram.com/soleraandcompany/
Ann Rose Events	Catering		Santa Barbara	California	Travels for events of any size	Mother-daughter team making grazing tables, charcuterie boards and picnics for weddings, rehearsal dinners and other celebrations.	annroseeventssb@gmail.com		https://annroseevents.com	https://www.instagram.com/annroseevents/
Central Coast Catering	Catering	205 W Canon Perdido St	Santa Barbara	California	Central Coast, events of 50 to 250 guests	Barbareño restaurant's catering arm, serving red oak-grilled tri-tip from a Santa Maria grill trailer or farm-to-table menus, with staffing and rentals.	ccc@barbareno.com	(805) 963-9591	https://www.centralcoastcateringsb.com	https://www.instagram.com/centralcoastcatering/
Rudy's Fresh Mexican Food	Catering	305 W Montecito Street	Santa Barbara	California	Santa Barbara County, including Carpinteria and Buellton	Local Mexican restaurant group catering taco bar buffets, passed appetizers and full dinners from a mobile kitchen across its five Santa Barbara County restaurants.			https://www.rudys-mexican.com	https://www.instagram.com/rudys_mexican/
Big Joe's Tacos & Catering	Catering		Santa Barbara	California	Santa Barbara, Goleta, Montecito and Carpinteria	Taco bar and buffet caterer offering on-site cooking with staff, drop-off service, dessert stations and bartenders for weddings.		(805) 680-7250	https://app.bigjoestacoscatering.com	
Oak and Fire Catering	Catering		Santa Barbara	California	Santa Barbara County	Santa Maria style barbecue caterer cooking tri-tip, chicken and spiny lobster on a mobile red oak grill, with staffing for weddings of 100 or more.		(805) 951-0208	https://oakandfiresb.com	https://www.instagram.com/oakandfire_bbq/
All Purpose Flower Fine Catering & Events	Catering		Santa Ynez Valley	California	Santa Ynez Valley, Santa Barbara, Los Olivos, Solvang, Montecito and Paso Robles	Family-run wine country caterer with Persian-influenced California menus, craft cocktails and event coordination for weddings.	info@allpurposeflowerco.com	(805) 456-1464	https://www.allpurposeflowerco.com	https://www.instagram.com/allpurposeflower_/
Unveiled Makeup & Hair	Hair & Makeup		Santa Barbara	California	Santa Barbara, Montecito, Ojai, Santa Ynez, Ventura and beyond	On-location bridal hair and makeup team run by two sisters, styling large wedding parties at the venue or hotel.			https://www.unveiledmakeup.com/	https://www.instagram.com/unveiledmakeup/
Dreamcatcher Artistry	Hair & Makeup		Santa Barbara	California	Santa Barbara, San Francisco, San Luis Obispo and Los Angeles	Makeup and hair team founded in 2011 that styles brides and bridal parties at venues, plus film and editorial work.	info@dreamcatcherartistry.com	805.453.5029	https://www.dreamcatcherartistry.com/	https://www.instagram.com/dreamcatcherartistry/
Santa Barbara Hair and Makeup	Hair & Makeup		Santa Barbara	California	Santa Barbara, Montecito, Santa Ynez, Ventura, Malibu and Los Angeles	On-location bridal beauty team led by founder Whitney, also offering makeup classes and live wedding painting.	contact@santabarbarahairandmakeup.com		https://www.santabarbarahairandmakeup.com/	https://www.instagram.com/santabarbarahairandmakeup/
Carlyle Salon and Style Bar	Hair & Makeup	350 Chapala Street	Santa Barbara	California	Santa Barbara, with travel to your venue	Downtown salon whose stylists and makeup artists do bridal hair in its Corner Room getting-ready suite or on location.		(805) 963-8787	https://carlylesalon.com/	https://www.instagram.com/carlylesalon/
NV Glam Team	Hair & Makeup	3455 State Street	Santa Barbara	California	Santa Barbara, Los Angeles, New York and destinations	Bridal makeup and hair team with a Santa Barbara studio, quoting custom packages per wedding after an inquiry form.	hello@nvglamteam.com	(805) 253-2835	https://nvglamteam.com/	https://www.instagram.com/nvglamteam/
Crushcakes & Café	Cake	1315 Anacapa Street	Santa Barbara	California	Santa Barbara and Goleta	Cafe and bakery making cupcakes and cakes from scratch, with tastings by appointment for wedding orders.	crushcakesevents@gmail.com	(805) 963-9353	https://www.crushcakes.com/	https://www.instagram.com/crushcakescafe/
Cakes by Heather Ashley	Cake		Santa Barbara	California		Bespoke wedding cakes baked from scratch and finished with hand-made sugar flowers, tasted at a downtown winery room.	info@cakesbyheatherashley.com		https://www.cakesbyheatherashley.com/	https://www.instagram.com/cakesbyheatherashley/
Room for Cake	Cake		Santa Barbara	California		Boutique cake studio making custom wedding cakes and mini desserts to order, taking a limited number of orders each week.	info@roomforcakebakery.com	(805) 335-1815	https://www.roomforcakebakery.com/	https://www.instagram.com/roomforcakesb/
Frances Baking Co.	Cake		Santa Barbara	California	Santa Barbara and the Central Coast	Micro-bakery run by pastry chef Heather Frances, making custom wedding cakes plus smaller ready-to-order cakes for elopements.	info@francesbakingco.com		https://www.francesbakingco.com/	https://www.instagram.com/francesbakingco/
The Little Things Bakery	Cake	2018 Cliff Drive	Santa Barbara	California		Neighbourhood bakery making tiered wedding cakes, cupcakes and cookies, with tastings by booking and a quote form.	info@thelittlethingsbakerysb.com	805-845-5519	https://www.thelittlethingsbakerysb.com/	https://www.instagram.com/thelittlethingsbakerysb/
Big Red Baking Company	Cake		Santa Barbara	California		Cake designer Jocelyn Kuzminski makes custom wedding cakes and cupcakes, with a separate wedding inquiry form and ready-to-order designs.	jocelyn@bigredbaking.com		https://www.bigredbaking.com/	https://www.instagram.com/bigredbakingco/`,
  },
  {
    name: "Orange County: music and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
DJ Pooya	Music		Irvine	California	Los Angeles, Orange County, San Diego	Irvine wedding DJ and bilingual MC focused on multicultural celebrations, with sound, lighting and live musicians available.	info@djpooya.com	(206) 291-2876	https://www.djpooya.com	https://www.instagram.com/djpooya/`,
  },
  {
    name: "Palm Springs: photography, planning, florals, music and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Matthew David Studio	Photography		Palm Springs	California		Palm Springs wedding photographers who also shoot Super 8 and 16mm film, often at Korakia, the Ace Hotel and on Joshua Tree elopements.	hello@matthewdavidstudio.com	626.353.4120	https://matthewdavidstudio.com/	https://www.instagram.com/matthewdavidstudio/
Brianna Broyles Photography	Photography		Palm Springs	California		Palm Springs studio with a small team offering both photography and videography of bright, joy-filled weddings across the desert.			https://www.briannabroyles.com/	https://www.instagram.com/briannabroyles/
Kellie Jane Creative	Photography		Palm Springs	California	Palm Springs, Los Angeles, San Diego and Santa Barbara	Palm Springs wedding photographer working since 2015 in a candid, warm and slightly nostalgic style, travelling across Southern California.			https://kelliejanecreative.com/	https://www.instagram.com/kelliejanephoto/
The Events Department	Planning		Palm Springs	California	Palm Springs and Borrego Springs	Wedding planning and coordination firm working in Palm Springs and Borrego Springs since 1988, with a long-standing local vendor network.	laurie@eventsdepartment.com	760-200-1365	https://eventsdepartment.com/	https://www.instagram.com/theeventsdepartment/
After the Engagement	Planning		Palm Springs	California	Greater Palm Springs and San Diego	Hospitality-minded planner offering full planning for relaxed, party-focused destination weddings around Palm Springs and San Diego.	aftertheengagement@gmail.com		https://www.aftertheengagement.com/	https://www.instagram.com/courtneytibbets/
Wildly Collective	Planning		Joshua Tree	California	Joshua Tree, Palm Springs and the American West	Planning and design studio for multi-day micro-weddings and elopements in Joshua Tree, Palm Springs and further across the West.	hi@wildlycollective.com		https://wildlycollective.com/	https://www.instagram.com/wildlycollective_/
My Little Flower Shop	Florals	861 N Palm Canyon Dr	Palm Springs	California		Full-service floral and event design shop on North Palm Canyon Drive making bouquets, centrepieces and flowers for outdoor weddings.		760-778-7111	https://mylittleflowershop.com/	
Palm Springs Florist	Florals	894 N Palm Canyon Dr	Palm Springs	California		Long-running Palm Springs florist with a dedicated wedding studio for bridal bouquets, ceremony pieces and reception flowers.		760.325.7441	https://www.palmspringsfloristweddings.com/	https://www.instagram.com/palmspringsflorist/
Vaso Bello Celebrations	Florals		Palm Springs	California		Palm Springs wedding florist designing bouquets, centrepieces and event décor for resort and estate weddings across the desert.	Weddings@vasobello.com		https://www.vasobello.com/	
Posy Laboratory	Florals	61607 29 Palms Hwy, Suite E1	Joshua Tree	California	Joshua Tree, Palm Springs and the surrounding desert	LGBTQIA+ woman-owned Joshua Tree studio making seasonal, low-waste wedding and elopement flowers that suit the Mojave landscape.			https://www.posylaboratory.com/	https://www.instagram.com/posylaboratory/
Bass + Bliss	Music		Palm Springs	California	Palm Springs, Joshua Tree and Temecula	Boutique DJ and MC company for desert weddings, focused on packed dance floors and polished hosting from ceremony to last song.	Alex@BassAndBliss.com	(760) 218-2625	https://www.bassandbliss.com/weddings	https://www.instagram.com/bass_and_bliss/
JSM Event Services	Music		Palm Springs	California	Southern California	One-person DJ business run by DJ Jeffree out of Palm Springs, who personally handles the music and lighting at every wedding.	jeffree@jsmeventservices.com	(760) 638-0748	https://www.jsmeventservices.com/	https://www.instagram.com/djjeffree/
Supermoon DJs	Music		Palm Springs	California		Palm Springs vinyl DJs building one-off wedding soundtracks of funk, soul and disco from a detailed questionnaire for each couple.	sabrina@supermoondjs.com		https://www.supermoondjs.com/	https://www.instagram.com/supermoondjs/
Desert Dine	Catering		Palm Springs	California	Greater Palm Springs, Joshua Tree, Temecula and Orange County	Palm Springs caterer and private-chef service for weddings, from intimate dinners to large receptions across the desert.	info@desertdine.com	(760) 507-2209	https://www.desertdine.com/	
New Leaf Catering	Catering	69032 E Palm Canyon Dr	Cathedral City	California	Coachella Valley	Full-service event caterer based in Cathedral City, cooking for weddings and parties around the Coachella Valley since 2000.	info@newleaf-catering.com	(760) 770-3636	https://www.newleaf-catering.com/	https://www.instagram.com/new_leaf_catering/
CVBBQ	Catering	83214 Requa Ave	Indio	California	Coachella Valley, from Palm Springs to Coachella	Indio barbecue restaurant catering open-pit BBQ for weddings and celebrations across the Coachella Valley.	info@cvbbq.com	(760) 668-3370	https://www.cvbbq.com/catering-service	https://www.instagram.com/cvbbq/`,
  },
];

export default batches;
