import type { VendorBatch } from "@/lib/vendor-batches";

// California vendor batches. Every row's State is "California". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Los Angeles: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Callaway Gable	Photography		Los Angeles	California	Los Angeles, Beverly Hills, Malibu, Santa Monica, Orange County, San Diego and beyond	Husband-and-wife studio with an editorial, cinematic style and more than 15 years shooting LA weddings, including many South Asian celebrations.	allison@callawaygable.com	(323) 394-9997	https://callawaygable.com	https://www.instagram.com/callawaygable/
Lupe Juarez Photography	Photography		Los Angeles	California		Bilingual Spanish-English photographer with 15 years' experience, known for guided posing and candid, timeless coverage of Southern California weddings.	info@lupejuarez.com		https://lupejuarez.com	
Mindy Weiss	Planning		Los Angeles	California	Los Angeles and destinations worldwide	Luxury planner and designer with a 30-year career and a team of twelve, producing high-profile and destination weddings with highly personal detail.	info@mindyweiss.com	(310) 205-6000	https://mindyweiss.com	https://www.instagram.com/mindyweiss/
Live Love Create Events	Planning		Los Angeles	California		Boutique full-service planning firm founded in 2009, experienced in Korean paebaek ceremonies and blending Asian heritage with modern weddings.	christine@livelovecreateevents.com	(323) 380-8149	https://livelovecreateevents.com	https://www.instagram.com/livelovecreate/
Mark's Garden	Florals	13838 Ventura Blvd	Sherman Oaks	California	Los Angeles area	Long-running Sherman Oaks floral studio designing for weddings and red-carpet events, with work seen at the Oscars and Golden Globes.	info@marksgarden.com	(818) 906-1718	https://marksgarden.com	https://www.instagram.com/marksgarden/
Eddie Zaratsian Lifestyle & Design	Florals	7430 San Fernando Rd	Sun Valley	California	Greater Los Angeles and destinations	Floral and event design house that also plans and produces weddings, known for sculptural work with orchids and mosses at large-scale celebrations.	concierge@eddiezaratsian.com	(310) 508-6126	https://www.eddiezaratsian.com	https://www.instagram.com/eddiezaratsian/
Lark Cake Shop	Cake		Los Angeles	California	Throughout Los Angeles	Family-run Silver Lake bakery open since 2007, offering free consultations and tastings for custom wedding cakes with a modern bohemian look.		(323) 667-2968	https://www.larkcakeshop.com	https://www.instagram.com/larkcakeshop/
Sweet E's Bake Shop	Cake		Los Angeles	California	Los Angeles, with nationwide shipping	Los Angeles bake shop making custom wedding and engagement cakes and logo cookies, with vegan, gluten-free and kosher-certified options.	hello@sweetesbakeshop.com	(323) 442-2885	https://www.sweetesbakeshop.com	https://www.instagram.com/sweetesbakeshop/
Marry Motion	Videography		Los Angeles	California	Los Angeles and worldwide	Owner-led film studio whose founder shoots every wedding himself, offering drone coverage, Super 8 film and next-day preview edits.	themarrymotion@gmail.com	(747) 476-9169	https://marrymotion.com	https://www.instagram.com/themarrymotion/
HeirloomLA	Catering		Los Angeles	California	Los Angeles and beyond	Los Angeles caterer known for simple, farm-sourced food and family-style service, with chefs cooking in front of guests and vegan options.	info@heirloomla.com	(855) 456-6652	https://heirloomla.com	https://www.instagram.com/heirloomla/
International Entertainment LA	Music		Los Angeles	California	Southern California and destination events	DJ and live-music company running since 1991, playing Armenian, Arabic, Assyrian, Persian and Indian sets alongside mainstream pop.	events@internationalentertainmentla.com	(866) 352-7736	https://internationalentertainmentla.com	
Angels Music Productions	Music		Los Angeles	California	Los Angeles, Orange, San Diego and Ventura counties	Valley Village DJ and MC team specialising in Jewish and Israeli weddings, with bilingual MCs in Hebrew, Persian and Spanish.		(949) 394-2572	https://angelsmusic.net	https://www.instagram.com/angelsmusicproductions/
Special Occasions DJ & Lighting	Music	390 Cliffwood Park St	Brea	California	Los Angeles, Orange County, San Diego, the Bay Area and destinations	South Asian wedding DJs with over 20 years' experience across Punjabi, Gujarati and Persian celebrations, plus lighting and LED video walls.	info@specialoccasionsla.com	(714) 253-3118	https://www.sodjla.com	https://www.instagram.com/sodjla/
Brand Videography	Videography		Los Angeles	California	West Coast	Documentary-style wedding film team founded in 2012 by a film and television editor, letting couples pick their music and request re-edits.	info@brandvideography.com	(310) 923-0062	https://brandvideography.com	https://www.instagram.com/brandvideography/
The Taco Catering Company	Catering		Los Angeles	California	Los Angeles, Orange County and the Inland Empire	Family-owned taco caterer run by Michelle and Hector, offering taco bars, on-site taqueros and a taco truck at budget-friendly per-guest prices.	info@tacocateringcompany.com	(213) 232-4255	https://tacocateringcompany.com	https://www.instagram.com/tacocateringcompany/
Jay Lawrence Goldman Photography	Photography	6139 Wilshire Blvd	Los Angeles	California		Wilshire Boulevard studio photographer with 30 years behind the camera, shooting weddings and mitzvahs in a relaxed, editorial style.	studio@jlgphoto.com	(323) 954-7436	https://www.jaylawrencegoldman.com	https://www.instagram.com/jay_lawrence_goldman/
3 Little Birds Event Planning	Planning		Burbank	California	Los Angeles area	Burbank planning team offering full planning, month-of and day-of coordination, with its own rental inventory for styling the day.		(818) 915-8870	https://3littlebirdseventplanning.com	https://www.instagram.com/3littlebirdseventplanning/
The Hidden Garden	Florals	2250 Cotner Ave	Los Angeles	California	Los Angeles and surrounding areas	West LA floral studio founded in 1999 by Amy Marella, designing lavish installations for luxury hotel weddings, with full packages from $25,000.		(310) 575-6600	https://hiddengardenflowers.com/pages/weddings	https://www.instagram.com/hiddengardenflowers/
Winston & Main	Florals		Los Angeles	California	Southern California, Santa Barbara, Ojai, Palm Springs and beyond	LGBTQIA+-owned floral studio working with local blooms and foam-free mechanics, composting waste and donating repurposed arrangements.			https://winstonandmain.com	https://www.instagram.com/winstonandmain/
Emily Lynn & Co.	Hair & Makeup		Los Angeles	California	Southern California and destination weddings	On-site hair and makeup team founded in 2017, known for airbrush makeup and natural looks, with artists experienced across skin tones and hair types.	info@emilylynnandcompany.com	(323) 310-4404	https://www.emilylynnandcompany.com	https://www.instagram.com/emilylynnandcompany/
Bright Crystal Wedding	Hair & Makeup	21880 Hawthorne Blvd Suite 342	Torrance	California	Los Angeles, Orange County and Temecula	Torrance bridal beauty studio working since 2012, offering on-site or in-studio hair and makeup for weddings, quinceañeras and debuts.	info@brightcrystal-wedding.com	(213) 260-1531	https://www.brightcrystal-wedding.com	https://www.instagram.com/brightcrystalwedding/
17 Catering	Catering	425 N Brand Blvd	Glendale	California	Los Angeles area	Glendale caterer with more than 15 years of LA events, known for Mediterranean menus and lavish Persian sweets and fruit tables.	17cateringandevents@gmail.com	(818) 660-5373	https://17catering.com	https://www.instagram.com/17events/
A Colored Mind	Videography		Los Angeles	California	Southern California and destinations worldwide	LGBTQ+-inclusive cinematic film and photo studio with over 400 weddings filmed across Southern California and abroad.		(213) 999-8966	https://acoloredmind.com	https://www.instagram.com/a.colored.mind/
One Story Weddings	Videography		Los Angeles	California	Los Angeles, Orange County, San Diego, Temecula, Santa Barbara and Ventura County	Wedding film company founded in 2017, sending two cinematographers with wireless audio and drone for 4K highlight films, from $3,900.	info@onestoryweddings.com		https://www.onestoryweddings.com/los-angeles-wedding-videographer	https://www.instagram.com/onestory.weddings/
Butter Cake Shoppe	Cake		Los Angeles	California	Los Angeles	Sister-run Los Feliz cake studio making custom wedding cakes from scratch since 2015, with a mix-and-match menu of flavours and fillings.			https://www.buttercakeshoppe.com	https://www.instagram.com/buttercakeshoppe/
Fairytale Hair and Makeup	Hair & Makeup		Los Angeles	California	Los Angeles, Orange County, Ventura, Santa Barbara and the Inland Empire	Mobile bridal beauty team of more than a dozen artists who travel to the venue, with separate crews also serving Las Vegas and Orlando.	fairytalehairandmakeup@gmail.com	(877) 324-7977	https://fairytalehairandmakeup.com/los-angeles-county/	https://www.instagram.com/fairytalehairandmakeup/`,
  },
  {
    name: "San Francisco Bay Area: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jasmine Lee Photography	Photography		San Francisco	California	San Francisco Bay Area and destination weddings	San Francisco photographer covering City Hall elopements, intimate weddings and destination celebrations with an artistic, editorial eye.			https://www.jasmineleephotography.com	https://www.instagram.com/jasmineleephoto/
Paula LeDuc Fine Catering & Events	Catering	1350 Park Ave	Emeryville	California	Northern California	Long-established East Bay caterer and event producer handling full-service weddings, galas and private celebrations across Northern California.	sales@paulaleduc.com	510-547-7825	https://www.paulaleduc.com	https://www.instagram.com/paulaleduc/
Taste Catering	Catering	201 Adrian Road	Millbrae	California	San Francisco and the Bay Area	Peninsula caterer offering full-service wedding menus, bar service and event design, plus regional Indian cuisine through its Taste & Jalsa partnership.	info@tastecatering.com	(415) 550-6464	https://www.tastecatering.com	https://www.instagram.com/tastecateringsf/
Kathleen Deery Design	Florals	4240 Holden Street	Emeryville	California		Emeryville floral and event design studio creating refined ceremony, cocktail-hour and reception arrangements for Bay Area weddings.	info@kathleendeerydesign.com	510.229.5444	https://www.kathleendeerydesign.com	https://www.instagram.com/kathleendeerydesign/
Tamtastic Creations	Planning		San Jose	California	Bay Area and Northern California	San Jose planner offering full, partial and day-of planning, experienced with South Asian, Muslim, Middle Eastern, Afghan and interfaith weddings.	hello@tamtasticcreations.com		https://www.tamtasticcreations.com	https://www.instagram.com/tamtastic.creations/
Sugar Butter Flour	Cake	669 S Bernardo Ave	Sunnyvale	California		Sunnyvale cake shop and French patisserie baking custom wedding cakes, with tastings offered before you order.	orders@sugarbutterflour.com	(408) 732-8597	https://www.sugarbutterflour.com	https://www.instagram.com/sugarbutterfloursv/
Masse's Pastries	Cake	1469 Shattuck Ave	Berkeley	California		Berkeley pastry shop on Shattuck making custom wedding cakes alongside its seasonal tarts and well-known honey cake.	massespastries@aol.com	510-649-1004	https://www.massespastries.com	
Christina Flach	Hair & Makeup		Corte Madera	California	San Francisco Bay Area, Marin, Napa, Sonoma, Silicon Valley and destinations	Marin-based bridal makeup and hair artist known for natural, camera-ready looks, with particular experience in Indian and South Asian bridal beauty.	prettygirlmakeup@gmail.com	415-717-9864	https://www.christinaflach.com	
Bun Bun Bridal Lab	Hair & Makeup	459 Fulton St #10	San Francisco	California	All Bay Area and beyond	San Francisco team of 15+ makeup artists and hairstylists doing soft, natural glam for bridal parties of any size, with WeChat booking available.	info@bunbunbridallab.com		https://www.bunbunbridallab.com	https://www.instagram.com/bun_bun_bridal_lab/
M-Sutra Bride	Hair & Makeup		San Ramon	California	Bay Area and Northern California, plus destination weddings	San Ramon bridal beauty team specialising in South Asian hair and makeup, including dupatta draping and looks for sangeet, mehndi and haldi events.	msutrabride@gmail.com	925-325-4618	https://www.msutrabride.com	https://www.instagram.com/msutra_bride/
The Hot Club of San Francisco	Music		San Francisco	California	San Francisco Bay Area and beyond	Gypsy-jazz string ensemble playing ceremonies, cocktail hours and dinner sets as a duo, trio or quartet, with swing for the dance floor.			https://www.hotclubsf.com/wedding-jazz-band	https://www.instagram.com/hotclubsf/
Sunrose Floral	Florals		Oakland	California	San Francisco Bay Area and beyond	Woman-owned Oakland studio designing loose, romantic and sustainably minded wedding florals, from full-service design to à la carte pieces.		(510) 495-0928	https://www.sunrosefloral.com	https://www.instagram.com/sunrosefloral/
Ashley Smith Events	Planning		San Francisco	California	San Francisco and destinations worldwide	San Francisco design-led planning firm with 15+ years producing high-end weddings that pair minimalist settings with bold, fashion-inspired details.			https://www.ashleysmithevents.com	
T.D.E. Wedding	Planning	216 Broadway	Millbrae	California	San Francisco Bay Area, from Santa Rosa to Carmel	Millbrae firm specialising in Chinese weddings, with all-inclusive packages covering planning, tea ceremonies, décor, photo, video and MCs.	info@tdewedding.com	(650) 686-6101	https://www.tdewedding.com	https://www.instagram.com/tdewedding/
Kindlewood Films	Videography		San Francisco	California	San Francisco, Napa Valley, Santa Cruz, Monterey, Big Sur and San Luis Obispo	San Francisco film studio with 300+ weddings behind it, building story-led films around the day's vows, toasts and dialogue.	hello@kindlewoodfilms.com	(415) 209-5817	https://kindlewoodfilms.com	
martinFILMS	Videography		Oakland	California	Bay Area and Wine Country, including Napa, Sonoma and Marin	Oakland filmmaker Martin Meyer shooting cinematic wedding films at vineyards, city venues and historic estates around Northern California.	bymartinmeyer@gmail.com	510-325-7750	https://www.martinfilms.com	https://www.instagram.com/martinfilms/
Wedding Documentary	Videography		San Jose	California	Bay Area, Napa, Sonoma and destinations worldwide	San Jose studio filming and photographing Indian and South Asian weddings since 2004, covering multi-day Hindu, Sikh and Gujarati celebrations.	info@Weddingdocumentary.com	(408) 656-1014	https://www.weddingdocumentary.com	https://www.instagram.com/weddingdocumentary/
C Wagner Photography	Photography		Oakland	California	Northern and Southern California	Oakland documentary photographer shooting weddings and elopements in a hybrid of digital, 35mm, medium-format and Super 8 film since 2013.	cw@cwagnerphotography.com	(510) 338-4186	https://www.c-wagnerphotography.com	https://www.instagram.com/cwagnerphotography/
Anna Wu Photography	Photography		Oakland	California	Bay Area, nationwide and international	Oakland-area photojournalistic photographer with 15+ years of weddings, from San Francisco City Hall ceremonies to multicultural celebrations.			https://annawu.com	https://www.instagram.com/annawuphoto/
Butter&	Cake	690 Indiana St	San Francisco	California		Dogpatch cake studio known for less-sweet cakes with sculptural, modern designs, offering wedding tasting boxes and custom consultations.	hello@butterand.com	415-707-7414	https://www.butterand.com	https://www.instagram.com/butter_and/
Bay Area Beats DJs	Music		Oakland	California	Oakland, Berkeley, San Francisco, Napa, Sonoma and San Jose	Oakland DJ and MC company founded in 2012, experienced with Indian, Mexican, Jewish and Arabic weddings and offering lighting and sound.			https://www.bayareabeatsdjs.com	
All Ears DJ	Music		Oakland	California	San Francisco Bay Area, Chicago, Kansas City and beyond	Oakland-rooted collective of DJs with 1,000+ events since 2012, known for tasteful, genre-spanning sets from electronic to queer dance classics.	allearsdj@gmail.com	785-766-2596	https://www.allearsdj.com	https://www.instagram.com/allearsdj/
Ash + Oak	Florals		Oakland	California	California, Mexico and beyond	Oakland floral atelier founded in 2014, designing sculptural, editorial wedding florals and large installations for luxury and destination weddings.	ashley@ashandoak.co		https://www.ashandoak.co	https://www.instagram.com/ashandoakfloral/
D-D Catering	Catering	1645 Flickinger Ave	San Jose	California	San Jose and the Bay Area	San Jose caterer serving Vietnamese and modern Asian fusion menus for weddings, from family-style banquets to buffets with carving stations.	ddcatering2016@gmail.com	(408) 717-1131	https://d-ddelightsanjose.com/catering/	https://www.instagram.com/d_ddelight/`,
  },
  {
    name: "San Diego: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
True Photography and Video	Photography		San Diego	California	San Diego and destinations nationwide	Long-running San Diego studio since 2000 offering photo and video together, with a choice of film, pop or organic editing treatments.	inquiry@truephotography.com	619-340-0992	https://www.truephotography.com	
Laura K Moore Photography	Photography		San Diego	California	North County San Diego, Carlsbad, Encinitas and Rancho Santa Fe; destinations	Documentary-leaning lifestyle and editorial photographer for North County weddings, including Indian weddings and elopements, in clean natural colour.	contact@laurakmoore.com	951-756-2960	https://www.laurakmoore.com	https://www.instagram.com/laurakmoorephotography/
Violet Cake Company	Cake	672 San Fernando St	San Diego	California	San Diego and surrounding areas	Point Loma cake studio making fine-art wedding cakes with hand-crafted sugar flowers, vintage piping and soft romantic textures.	info@violetcakeco.com	619-993-3992	https://www.violetcakeco.com	https://www.instagram.com/violetcakecosd/
cupCAKES a la Yola	Cake	6850 Mission Gorge Rd	San Diego	California		Family-owned San Diego bakery since 2015 making tiered wedding cakes, cupcake towers and dessert tables, with delivery and set-up.	cakeinfosd@gmail.com	619-708-5088	https://cupcakesalayola.com	https://www.instagram.com/cupcakesalayola/
Liz's Flowers	Florals	6690 Mission Gorge Rd Suite F	San Diego	California	San Diego County, including Rancho Santa Fe, Poway, Del Mar and Solana Beach	Family-owned San Diego florist since 1990 designing wedding bouquets and venue flowers with seasonal peonies, ranunculus, dahlias and protea.	liz@lizsflowers.com	(619) 285-3847	https://lizsflowers.com	https://www.instagram.com/lizsflowerssd/
Adelaide Shea Films	Videography		San Diego	California	San Diego and worldwide	San Diego videographer making documentary-style wedding films that stay unobtrusive on the day, with Super 8 film available as well.	adelaidesheafilms@gmail.com		https://adelaidesheafilms.com	https://www.instagram.com/adelaidesheafilms/
Sweet Blossom Weddings	Planning		Encinitas	California	San Diego and beyond	Encinitas planning boutique running since 2010, offering full planning, design and day-of coordination with a team of planners on the day.	hello@sweetblossomweddings.com	858-668-8263	https://sweetblossomweddings.com	https://www.instagram.com/sweetblossomweddings/
Aficial Events	Planning		San Diego	California	San Diego, travelling further when available	San Diego planning team offering full and partial planning, design-plus-coordination and day-of management for weddings and rehearsal dinners.	karen@aficialevents.com		https://aficialevents.com	https://www.instagram.com/aficialevents/
Ann's Plans	Planning		San Diego	California	San Diego region	San Diego planner with over twenty years of coordinating weddings, offering full-service planning through to week-of coordination by appointment.	ann@annsplans.com	619-206-5676	https://annsplans.com	
Captured by Suarez	Photography		San Diego	California		Husband-and-wife photography duo, high-school sweethearts, shooting candid, natural wedding coverage with an eye for golden-hour light.			https://capturedbysuarez.com	https://www.instagram.com/capturedbysuarez/
Feral Rose Floral Design	Florals		San Diego	California	Southern California	Designer-led studio taking a limited number of weddings each year, creating lush, garden-style arrangements and installations.	feralrosefloral@gmail.com	805-689-6460	https://feralrosefloral.com	https://www.instagram.com/feralrosefloral/
Tessfresh Flowers	Florals	1405 Morena Blvd Suite A	San Diego	California	San Diego County	Family-run Morena district florist since 2002 handling fresh and silk wedding flowers plus event decor for hundreds of events a year.	info@tessfreshflowers.com	(619) 276-4221	https://www.tessfreshflowers.com	https://www.instagram.com/tessfreshflowers/
Kota Video Productions	Videography		Carlsbad	California	San Diego, Riverside and Orange counties	Owner-operated Carlsbad videographer making story-led cinematic wedding films, with drone, full ceremony edits and social cuts available.	kotavideopro@gmail.com	858-333-7006	https://kotavideo.com	
Maseloo Films	Videography	321 E San Ysidro Blvd Unit A	San Ysidro	California	Greater San Diego, plus Los Angeles, Riverside and Orange County	South Bay wedding film studio producing emotive, cinematic films with drone coverage and multiple shooters, from small ceremonies upwards.		(619) 540-1244	https://www.maseloo.com	https://www.instagram.com/maseloofilms/
Terra Catering & Events	Catering	7091 El Cajon Blvd	San Diego	California	San Diego	Chef-led caterer with nearly three decades in San Diego, cooking farm-to-table menus on site as buffets, stations, plated or family style.	events@terracatering.com	619-993-1437	https://www.terracatering.com	https://www.instagram.com/terracatering/
Bekker's Catering	Catering		San Diego	California	San Diego	Family-owned full-service caterer since 1958, known for pit-smoked barbecue alongside themed menus, rentals and staffing for weddings.		619-287-9027	https://www.bekkerscatering.com	https://www.instagram.com/bekkerscatering/
Tacos Don Jorge	Catering		San Diego	California	San Diego area	Mexican taco caterer pressing handmade tortillas on site, with cocktail-hour bites, vegan options and a churro dessert station for weddings.		844-822-6626	https://www.tacosdonjorge.com	https://www.instagram.com/tacosdonjorgeinc/
Coast Catering	Catering		San Diego	California	San Diego and Southern California	San Diego caterer of over twenty years creating chef-driven custom menus cooked on site, with event design and rentals through a sister company.	info@coastcatering.com	(877) 577-1718	https://www.coastcatering.com	https://www.instagram.com/coastcatering/
Sound Prodigy	Music		San Diego	California	Southern California	Independent San Diego DJ and MC company running since 1999, also offering a vintage VW bus photo booth and an audio guestbook.	info@soundprodigy.com	619-972-6086	https://soundprodigy.com	https://www.instagram.com/soundprodigy/
Sundown Sound Co.	Music		San Diego	California	San Diego region	Boutique San Diego audio team providing wedding DJs, sound for live bands and uplighting, with set-up and technicians included in packages.	info@sundownsoundco.com	619-389-9299	https://sundownsoundco.com	https://www.instagram.com/sundownsoundco/
Caprice Strings	Music		San Diego	California	San Diego, La Jolla, Del Mar, Temecula and Orange County	Locally owned string group with almost forty years of San Diego weddings, playing as a trio, duo, quartet or solo violin, classical to pop.	victoria@capricestrings.com	619-363-3368	https://capricestrings.com	https://www.instagram.com/capricestrings/
Eliana Strings	Music		San Diego	California	San Diego	San Diego string ensemble founded in 2011, offering a quartet or trio for wedding ceremonies, cocktail hours and receptions.	info@elianastrings.com	619-363-7083	https://www.elianastrings.com	https://www.instagram.com/eliana_strings/
Glam On The Run	Hair & Makeup		San Diego	California	San Diego area, including La Jolla, Carlsbad and Del Mar	Mobile team of licensed stylists and certified make-up artists doing on-location bridal hair and airbrush or traditional make-up.		917-743-0887	https://www.glamontherun.com	https://www.instagram.com/glam_on_the_run/
Del Beauty Box	Hair & Makeup	910 Camino Del Mar Unit C	Del Mar	California	Del Mar and coastal San Diego	Del Mar beauty studio specialising in soft, skin-focused bridal make-up and hair styling for brides and their wedding parties.		(858) 259-4247	https://delbeautybox.com	https://www.instagram.com/delbeautybox/
Makeup by Dali	Hair & Makeup		San Diego	California	Southern California	Freelance San Diego make-up artist with over seven years of experience, focused on long-wearing make-up for weddings and elopements.	dalisatoro.mbd@gmail.com	(619) 736-8649	https://makeupbydali.com	https://www.instagram.com/makeup.by.dali/
Mili's Sweets	Cake		San Diego	California	San Diego County	Home-based cake maker since 2010 making custom wedding cakes and dessert tables, all peanut and tree-nut free, with vegan and gluten-free options.			https://milissweets.com	https://www.instagram.com/milis_sweets/`,
  },
  {
    name: "Sacramento: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Eye Connoisseur Photography	Photography	1200 S St, Ste B	Sacramento	California	California and beyond	Sacramento studio on S Street photographing weddings for over 15 years, known for an unconventional, editorial take and a black-and-white collection.	info@eyeconnoisseur.com	916-444-1222	https://eyeconnoisseur.com	https://www.instagram.com/eyeconnoisseurphotography/
Doug Miranda Photography	Photography		Sacramento	California	Sacramento, Lake Tahoe and Napa	Brooks Institute-trained wedding and engagement photographer with hundreds of weddings behind him, covering Sacramento venues through to Tahoe.	doug@dougmiranda.com	916-422-2256	https://dougmiranda.com	
AB Event Co	Planning		Roseville	California	Northern California	Roseville-based planner offering full, partial and month-of coordination for modern couples, with a relaxed, humorous and transparent approach.			https://abeventco.com	https://www.instagram.com/abeventco/
Blissfully Elegant Events	Planning		Sacramento	California	Sacramento and Northern California	Planning team led by Janelle, who brings 16 years of hotel events experience, offering full service, partial planning and month-of coordination.	blissfullyeleganteventsca@gmail.com		https://www.blissfullyeleganteventsca.com	https://www.instagram.com/blissfullyelegantevents/
Asteria Florals	Florals		Sacramento	California	Sacramento region	East Sacramento floral studio, formerly Mahina + Soul, designing bespoke one-of-a-kind wedding arrangements from seasonal blooms.	info@asteriaflorals.com	916-898-2570	https://www.asteriaweddings.com	https://www.instagram.com/asteriaflorals/
Sacramento DJ Service	Music		Sacramento	California	Greater Sacramento area	Long-running DJ and entertainment company working Sacramento events since 1995, pairing a wide music library with lighting for wedding receptions.	DjKris@SacramentoDjService.com	916-941-5747	https://sacramentodjservice.com	https://www.instagram.com/1djkris/
Beat Fleet DJs	Music		Sacramento	California	Northern California	Sacramento DJ and MC company since 2010, pairing dedicated event hosts with DJs and offering add-ons such as cold sparklers, uplighting and photo booths.		916-866-9698	https://beatfleetdjs.com	https://www.instagram.com/beatfleetdjs/
AnyThyme Catering	Catering		Elk Grove	California	Sacramento, Elk Grove and Northern California	Family-run, women-owned and LGBTQ+ inclusive caterer from Elk Grove, offering buffet wedding menus with full coordination and private tastings.	AnyThymeCateringEG@gmail.com	916-602-9961	https://www.anythymecatering.com	https://www.instagram.com/anythymecateringco/
Spilled Milk Company	Cake		Elk Grove	California	Sacramento, Elk Grove, the Bay Area and San Francisco	Elk Grove cake studio making buttercream and sculpted fondant wedding cakes, with white-glove delivery and on-site styling from about $11 a serving.			https://spilledmilkcompany.com/weddings	https://www.instagram.com/spilledmilk_co/
Cake Castle Bakery	Cake	5601 66th Ave	Sacramento	California		South Sacramento bakery designing one-of-a-kind custom wedding and groom cakes, alongside cake-decorating classes and supplies.	info@cakecastlebakery.com	916-394-4040	https://cakecastlebakery.com	
Anna Bakalym Artistry	Hair & Makeup		Sacramento	California	Sacramento, the Bay Area and destination weddings	Sacramento bridal hair and makeup team led by Anna, favouring soft, timeless looks that enhance rather than change, with clearly published pricing.	hello@annabakalym.com		https://annabakalym.com	https://www.instagram.com/anna_bakalym/
Foxy Glamour	Hair & Makeup		Rocklin	California	Rocklin, Sacramento, Roseville, Folsom, Auburn and Northern California	Rocklin-based bridal hair and makeup artist specialising in skin-first soft glam with a calm, concierge-style wedding morning.	Foxyglamourmua@gmail.com	916-741-8742	https://foxyglamour.com	https://www.instagram.com/foxyglamourmua/
CineCrown Multimedia Studios	Videography	1015 25th St	Sacramento	California	Sacramento, Napa, San Francisco, San Jose and the Bay Area	Midtown Sacramento studio, running since 2005, filming and photographing multicultural weddings including Indian, Filipino, Mexican, Chinese and Vietnamese.		916-800-3388	https://cinecrown.com	https://www.instagram.com/cinecrown/
Wild Flowers Design Group	Florals		Sacramento	California		Family-run Sacramento floral studio, three generations in, working by appointment and focusing on weddings and large events.	DesignTeam@wfdg.info	916-899-1289	https://www.wildflowersdesigngroup.com	https://www.instagram.com/wildflowersdg/
Blooms In Ribbon	Florals	8300 Sierra College Blvd, Ste F	Roseville	California	Greater Sacramento	Roseville flower shop with a full wedding service covering bouquets and ceremony installs, with full wedding florals starting from around $800.	orders@bloomsinribbon.com	916-203-3662	https://bloomsinribbon.com/weddings	https://www.instagram.com/blooms_in_ribbon/
Randy Peters Catering	Catering	105 Vernon St	Roseville	California	Northern California	Caterer with decades of experience and its own Roseville event centre, offering full-service wedding menus, BBQ and bar service.	sales@randypeterscatering.com	916-726-2339	https://randypeterscatering.com	https://www.instagram.com/rpeterscatering/
The Hidden Table	Catering	1767 Tribute Rd, Ste D	Sacramento	California	Sacramento and Lake Tahoe	Farm-to-fork caterer founded by Chef Russ and Linda Lande, cooking locally sourced menus on site for vineyard, backyard and larger weddings.	info@thehiddentablegourmet.com	916-337-8613	https://www.thehiddentablegourmet.com	https://www.instagram.com/thehiddentable/
Authentic Street Taco	Catering		Roseville	California	Greater Sacramento, the Bay Area and San Jose	Family-run Mexican caterer with a fleet of taco trucks, cooking fresh tacos, burritos and homemade tortillas and salsas for relaxed, casual weddings.	Info@authenticstreettaco.com	916-749-8059	https://www.authenticstreettaco.com/wedding-catering/	https://www.instagram.com/authenticstreettaco/
Amid Films	Videography	6929 Sunrise Blvd, Ste 205	Citrus Heights	California	Sacramento, the Bay Area, Lake Tahoe and destinations	Wedding film team working since 2016 from a Citrus Heights studio, making emotional, elegant films across Sacramento, Tahoe and further afield.	info@amidfilms.com	916-521-5299	https://amidfilms.com	
Aperina Studios	Photography	6929 Sunrise Blvd, Ste 202	Citrus Heights	California	Sacramento, across the US and abroad	Sacramento-rooted photo and video team with over 15 years of wedding photography, offering both stills and cinematic films under one booking.	info@aperina.com	916-802-4136	https://aperina.com	https://www.instagram.com/aperinastudios/
New Legacy Films	Videography		Sacramento	California	Greater Sacramento, all of California and destination weddings	Sacramento wedding videography studio crafting cinematic films focused on real emotion, from Sierra elopements to wine-country celebrations.			https://newlegacyfilms.studio	https://www.instagram.com/newlegacy_films/
The Groove Thang Band	Music		Sacramento	California	Northern California and Nevada	Sacramento variety dance cover band playing R&B, funk, Motown, disco, rock and country hits, with hundreds of weddings across Northern California.	manager@groovethangband.com	916-873-2257	https://www.groovethangband.com	
Dragonfly Events & Co.	Planning		Sacramento	California	Sacramento, Napa, Tahoe and destinations	Design-led Sacramento planning firm for high-touch weddings, with full service and design priced at 12% of budget from a $12,000 minimum.	hello@dragonflyeventsandco.com	916-945-6575	https://dragonflyeventsandco.com	https://www.instagram.com/dragonflyeventsco/
MAI Makeup & Hair	Hair & Makeup		Sacramento	California	Sacramento and Northern California	Sacramento bridal artist offering natural, long-wearing makeup and hair with all-day support, experienced with Vietnamese weddings and outfit changes.	mai@maimakeuphair.com		https://maimakeuphair.com	https://www.instagram.com/maimakeuphair/
Pastry Heaven Bakery	Cake	8069 Madison Ave	Citrus Heights	California		Family-owned bakery since 2005, led by a pastry chef with over 30 years of experience, making everything from two-tier rosette cakes to towering designs.		916-965-5408	https://www.pastryheavenbakery.com/pages/wedding-cakes	`,
  },
];

export default batches;
