import type { VendorBatch } from "@/lib/vendor-batches";

// Colorado vendor batches. Every row's State is "Colorado". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Denver: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
From the Hip Photo	Photography	8842 E 47th Ave	Denver	Colorado	All of Colorado and beyond	A five-person photography team in Denver's Central Park neighbourhood with 17 years of weddings, covering Front Range and mountain venues alike.	chat@fromthehipphoto.com	720-390-5995	https://fromthehipphoto.com/	https://www.instagram.com/fromthehipphoto/
Be Boulder Photography	Photography		Boulder	Colorado	Boulder and Colorado	Eleanor Williamson's Boulder studio for weddings and elopements, mixing posed portraits with candid storytelling and openly welcoming every couple.			https://beboulderphotography.com/	https://www.instagram.com/beboulderphotography/
DGASS Photography	Photography		Denver	Colorado	Denver, Omaha and destination weddings	A Denver photo and film team of five with one editor for a consistent look, known for multi-day Indian weddings as well as elopements.			https://dgassphotography.com/	https://www.instagram.com/dgass_photography/
Molly Margaret Photography	Photography		Denver	Colorado	Colorado and worldwide	Molly shoots weddings and elopements on both film and digital, and offers video too, with a candid, documentary approach to the day.	hello@mollymargaretphotography.com		https://www.mollymargaretphotography.com/	https://www.instagram.com/mollymargaretphotos/
Sapphire Celebrations	Planning		Denver	Colorado	Denver, Aspen, Vail, Colorado Springs and throughout Colorado	A family-led planning firm working across Colorado for over 20 years, handling full planning and destination weddings in the city and the mountains.		303-617-3984	https://www.sapphirecelebrations.com/	https://www.instagram.com/sapphirecelebrations/
Pink Champagne Events	Planning		Denver	Colorado	Denver and the Colorado mountains	A Denver planning and design boutique focused on full-service destination wedding weekends in mountain towns such as Vail, Keystone and Steamboat.	events@pinkchampagneevents.com	720-872-1642	https://www.pinkchampagneevents.com/	
Cloud 9 Weddings & Papers	Planning	821 Santa Fe Dr	Denver	Colorado	Colorado	A Denver planner since 2002 with over 400 weddings behind it, offering full planning and design alongside its own custom invitation studio.	brittany@cloud9bliss.com	720-570-1168	https://cloud9bliss.com/	https://www.instagram.com/cloud9denver/
The Nouveau Romantics	Planning		Denver	Colorado	Colorado and worldwide	Elizabeth McKellar's Denver studio plans destination weddings with an architect's eye for layout and flow, taking a small number of couples.			https://thenouveauromantics.com/	https://www.instagram.com/thenouveauromantics/
Sanctuary	Florals	3138 N Milwaukee St	Denver	Colorado	Denver metro	A Denver florist with a theatre and design background, building wedding flowers around colour, movement and texture rather than set formulas.	sanctuaryflorals@gmail.com	303-435-7992	https://sanctuaryflorals.com/	https://www.instagram.com/sanctuaryfloraldenver/
Landfall Floral Co.	Florals	5505 W 20th Ave	Edgewater	Colorado	Lakewood and west Denver	A florist at Edgewater Public Market making airy, garden-style wedding flowers, with full-service, intimate and a la carte options.		720-409-3265	https://landfallfloral.com/	https://www.instagram.com/landfallfloralco/
Petals Colorado	Florals		Denver	Colorado	Denver metro and all of Colorado	A Denver wedding florist led by Lora and Courtney, designing original arrangements with couples from a free first consultation through to the day.	petalscolorado@gmail.com	720-636-4857	https://www.petalscolorado.com/	https://www.instagram.com/petalscolorado/
DJ Guy	Music		Denver	Colorado	Denver metro	A family-run Denver DJ company with decades of weddings behind it, offering DJs, MC work and online quotes for receptions across the metro.	yourdj@djguy.com	303-754-0004	https://djguy.com/	https://www.instagram.com/djguy_denver/
A Music Plus Entertainment	Music	6870 Broadway	Denver	Colorado	Throughout Colorado	A Denver entertainment agency of 30-plus years that trains its own DJs and can also book live bands, string quartets and other acts.	events@amusicplus.com	303-426-9990	https://amusicplus.com/	
Funkiphino	Music		Boulder	Colorado	Colorado and nationwide	A 13-piece Boulder funk band with a full horn section and Hammond organ, playing weddings and private events as well as public shows.			https://funkiphino.com/	
Footers Catering	Catering	6543 Wadsworth Blvd	Arvada	Colorado	Denver metro and Colorado	An Arvada caterer founded in 1981 that cooks on site at weddings and provides full event coordination for large and small receptions.		303-762-1410	https://footerscatering.com/	https://www.instagram.com/footerscatering/
Biscuits & Berries	Catering	14818 W 6th Ave	Golden	Colorado	Denver metro	A Golden caterer cooking from scratch on site at weddings, from intimate dinners to receptions of 300 or more guests.	info@biscuitsandberries.com	303-277-9677	https://www.biscuitsandberries.com/	https://www.instagram.com/biscuitsandberries/
Mountain Crust	Catering	3880 S Lowell Blvd	Denver	Colorado	Denver and beyond	Wood-fired pizza wedding catering served from a fleet of vintage trucks, with salads, seasonal starters and beer on tap; also runs its own venue.	party@mountaincrust.com	720-515-0917	https://www.mountaincrust.com/	https://www.instagram.com/mountaincrusteventvenue/
GLAM5280	Hair & Makeup		Denver	Colorado	On location throughout Colorado	A Denver on-location bridal hair and makeup team that scales to large wedding parties and favours natural, modern looks.	Hello@glam5280.com	720-341-9626	https://www.glam5280.com/	https://www.instagram.com/glam5280/
Jaded Beauty	Hair & Makeup	277 Broadway	Denver	Colorado	Colorado	A Denver salon and wedding team doing on-site bridal hair and makeup for whole wedding parties, including hair extensions.	info@jadedbeauty.com	720-295-0441	https://jadedbeauty.com/	https://www.instagram.com/jadedbeauty__/
Amy DaCosta & Co.	Hair & Makeup		Denver	Colorado	Denver and all of Colorado	A Denver collective of bridal hair and makeup artists, each trained by Amy DaCosta, working weddings from mountain lodges to city hotels.	hello@amydacosta.com		https://www.amydacosta.com/	https://www.instagram.com/amydacostaandco/
Cate Hair Makeup	Hair & Makeup		Denver	Colorado	Denver and worldwide	A Denver bridal artist with over 750 weddings who takes one booking a day and stays through the morning for veils and touch-ups.			https://catehairmakeup.com/	https://www.instagram.com/catehairmakeup/
Das Meyer Fine Pastry Chalet	Cake	13251 W 64th Ave	Arvada	Colorado		A family-run Arvada bakery since 1981, baking everything from scratch on site, with wedding cakes from traditional to modern and Saturday tastings.		303-425-5616	https://www.dasmeyerpastry.com/	https://www.instagram.com/dasmeyerpastry/
Gingerly Baked	Cake		Denver	Colorado	Colorado	A Denver wedding cake baker making everything from scratch, with careful stacking and piping, published menus and a tasting process.			https://www.gingerlybaked.com/	https://www.instagram.com/gingerly_baked/
Snarky Sweet Cake Chick	Cake		Arvada	Colorado		Nicole's Arvada cake business makes custom wedding cakes and treats, using edible image printing for detailed textures and personal designs.	cakechick@snarkysweetcakechick.com		https://www.snarkysweetcakechick.com/	https://www.instagram.com/snarkysweetcakechick/
14er Films	Videography		Denver	Colorado	Denver, Colorado Springs, Boulder and Vail	A Colorado wedding film company making cinematic films of Rocky Mountain weddings in Denver, Boulder, Colorado Springs and Vail.	14erfilms@gmail.com		https://www.14erfilms.com/	https://www.instagram.com/14erfilms/
Birch and Blush	Videography		Denver	Colorado	Denver metro and within two hours, including Fort Collins and Colorado Springs	A Denver team of wedding videographers filming unscripted, documentary-style stories set against Colorado's mountain scenery.			https://birchandblush.com/	https://www.instagram.com/birchandblush/
Veiled Rose Films	Videography		Denver	Colorado	Denver, Boulder, Estes Park and throughout Colorado	Brian Alan's Denver studio makes boutique cinematic wedding films and guarantees delivery within 12 weeks, with drone coverage available.	info@veiledrosefilms.com	720-840-5541	https://www.veiledrosefilms.com/	https://www.instagram.com/veiledrosefilms/
`,
  },
  {
    name: "Colorado Springs: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Michelle Betz Photography	Photography		Colorado Springs	Colorado	Colorado Springs, Denver, Boulder, Breckenridge and across Colorado	Wedding and elopement photographer based in Colorado Springs, with an emphasis on elegant, true-to-life images and tight timelines.		719.310.0837	https://michellebetzphotography.com	https://www.instagram.com/michellebetzphotography/
Bobak Radbin Photography	Photography		Colorado Springs	Colorado	Colorado Springs and all of Colorado	Elopement and intimate-wedding photographer who helps couples choose mountain locations and sort out permits across Colorado.			https://www.bobakradbin.com	https://www.instagram.com/bobakradbin/
Whitney Marshall Photo	Photography		Colorado Springs	Colorado	Colorado	Colorado Springs wedding photographer working in natural light with relaxed posing, also offering engagement and family sessions.			https://whitneymphoto.com	
The Paper Ring Collective	Planning		Colorado Springs	Colorado	Colorado Springs and surrounding areas	Wedding planning and day-of coordination studio in Colorado Springs, led by Tomi Erfe, focused on intimate, story-led weddings.	hello@thepaperringcollective.com		https://www.thepaperringcollective.com	https://www.instagram.com/thepaperringcollective/
Wakefield Event Co	Planning		Colorado Springs	Colorado	Colorado Springs and greater Colorado	Colorado Springs planner offering full-service, partial planning and day-of coordination, plus party planning for other celebrations.	paige.wakefieldeventco@gmail.com		https://www.wakefieldeventco.com	https://www.instagram.com/wakefieldeventco/
Flourish Event Co	Planning		Colorado Springs	Colorado	Colorado and Southern California	Colorado Springs event company coordinating weddings, from vendor introductions and timelines through to day-of management.	hello@flourisheventco.com	719-217-0992	https://flourisheventcompany.com	https://www.instagram.com/flourisheventcompany/
Kind Floral	Florals		Colorado Springs	Colorado	Colorado Springs and Colorado	Wedding florist led by designer Kristin Hay, making wild, romantic arrangements with local blooms for ceremonies and receptions.	info@kindfloral.com		https://www.kindfloral.com	https://www.instagram.com/kind_floral/
Layers of Lovely	Florals		Colorado Springs	Colorado	Colorado Springs and surrounding areas	Floral arts studio in Colorado Springs designing wedding flowers, with work at venues such as The Broadmoor and Garden of the Gods Resort.		702.281.9145	https://www.layersoflovely.com	https://www.instagram.com/layersoflovely/
Yes Dear Florals	Florals	180 Highway 67, Suite G	Woodland Park	Colorado	Woodland Park, Teller County and the Front Range	Woodland Park florist with a shop and studio doing wedding and elopement flowers as well as event design across the Front Range.		719-374-6370	https://yesdearflorals.com	https://www.instagram.com/yesdearflorals/
Springs Sounds Entertainment	Music		Colorado Springs	Colorado		Colorado Springs DJ and entertainment team with professional sound and lighting, playing across many genres at weddings.		(719) 232-6038	https://www.springssounds.com	https://www.instagram.com/springssounds/
Warren Entertainment	Music		Colorado Springs	Colorado	Colorado Springs and Monument	Family-run DJ company in Colorado Springs offering disc jockey, lighting and photo booth services for weddings and celebrations.			https://www.coloradospringsdj.com	
HEPS DJ & Photo Booth	Music		Colorado Springs	Colorado	Colorado Springs, Denver, Fort Collins, Pueblo, Estes Park and Silverthorne	DJ service led by Brian Hepperle since 2011, adding photo booth hire, lighting and audio guestbooks to wedding receptions.			https://www.hepsdj.com	https://www.instagram.com/hepsdj/
Latimer's Kitchen & Catering	Catering		Colorado Springs	Colorado	Colorado Springs, Monument, Woodland Park, Manitou Springs and Fountain	Colorado Springs caterer with over 15 years of wedding work, known for barbecue, seafood and its own dessert line, with full service.	info@latskitchen.com	(719) 339-6400	https://latskitchen.com	https://www.instagram.com/lats_kitchen/
The Catering Collective	Catering	1701 S 8th Street	Colorado Springs	Colorado	Colorado Springs and the Front Range	Family of catering brands including Picnic Basket and Buffalo Gals, serving weddings in Colorado Springs since 1989.	info@pbcatering.com	(719) 635-0200	https://www.pbcatering.com	
El Chapin Food Truck	Catering	1228 E Fillmore St	Colorado Springs	Colorado	Colorado Springs and surrounding neighbourhoods	Colorado Springs taco and burger truck with a fixed Fillmore Street location, booked for events and late-night wedding snacks.		(719) 209-0996	https://www.elchapinfoodtruck.com	
THE DAY Hair & Makeup	Hair & Makeup	3404 W Colorado Avenue	Colorado Springs	Colorado	Colorado Springs, Denver and surrounding regions	Team of licensed hairstylists and makeup artists in Colorado Springs, travelling on location to wedding parties along the Front Range.	info@thedaycolorado.com	719-433-5530	https://www.thedaycolorado.com	https://www.instagram.com/the_day_colorado/
Ally's Beauty Bar	Hair & Makeup		Colorado Springs	Colorado	Colorado Springs, with travel available	Boho-leaning bridal hair and makeup team led by licensed cosmetologist Allyssa LeFevre, offering looks from natural to full glam.	allysbeautybar7@gmail.com		https://www.allysbeautybar.com	https://www.instagram.com/allysbeautybar7/
Brook Mae Hairstyling	Hair & Makeup		Colorado Springs	Colorado	Colorado Springs, Monument and Castle Rock	On-location bridal hairstylist known for soft, undone, romantic styles, also teaching business skills to other stylists.			https://brookmaehairstyling.com	
Peak Cake Co	Cake		Colorado Springs	Colorado	Colorado Springs, Monument, Falcon, Black Forest, Fountain and Manitou Springs	Veteran-owned bakery making European buttercream wedding cakes in a clean, modern style with scratch-made fillings.	orders@peakcakeco.com	(719) 900-1007	https://peakcakeco.com	
Mountain Bliss Cakery	Cake	4801 Eddleman Ct	Colorado Springs	Colorado	Colorado Springs and surrounding areas	Veteran-owned custom cake bakery seeing clients by appointment, making wedding cakes with handcrafted sugar flowers and metallic details.	mountainblisscakery@gmail.com	(719) 960-6795	https://mountainblisscakery.com	https://www.instagram.com/mountain_bliss_cakery/
The Sugarplum Cake Shoppe	Cake	412 S 8th St	Colorado Springs	Colorado	Colorado Springs area	Downtown Colorado Springs bakery making custom wedding cakes, cupcakes and dessert tables, with a retail counter open Tuesday to Saturday.		(719) 930-3343	https://www.sugarplumcakeshoppe.com	https://www.instagram.com/thesugarplumcakeshoppe/
J Angel Visuals	Videography		Colorado Springs	Colorado	Colorado, including Colorado Springs, Denver, Vail, Aspen and Breckenridge	Wedding filmmaker Jordan Angel, shooting cinematic films on cinema cameras with highlight and full-length options, based in Colorado Springs.		(719) 360-3945	https://www.jangelvisuals.com	https://www.instagram.com/jangelvisuals/
Films About Love	Videography		Colorado Springs	Colorado	Colorado Springs, Denver, Boulder, Vail, Aspen and Telluride	Colorado Springs wedding videographers making story-led films for mountain weddings, with social cuts for couples as well.	michael@filmsaboutlove.com	(719) 237-5159	https://www.filmsaboutlove.com	https://www.instagram.com/filmsaboutlove/
Matt Cress Media	Videography		Colorado Springs	Colorado	Colorado Springs area and limited Denver coverage	Colorado Springs photographer and videographer offering calm, documentary-style wedding coverage with 4K highlight films.	MattcressMEDIA@gmail.com	(719) 663-2930	https://www.mattcressmedia.com	https://www.instagram.com/mattcressmedia1/
`,
  },
  {
    name: "Vail and Aspen: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Amanda Berube Photography	Photography		Vail	Colorado	Vail, Aspen, Breckenridge and destination weddings	Fine art wedding photographer based in Vail, creating light, timeless images of luxury mountain weddings across Colorado and further afield.			https://amandaberube.com/	https://www.instagram.com/amandaberuebphoto/
Aspen Sage Photo	Photography		Glenwood Springs	Colorado	Aspen, Glenwood Springs, Carbondale, Snowmass and all of Colorado	Wedding and elopement photographer working from Glenwood Springs, with a classic, documentary approach that favours natural light and candid moments.			https://www.aspensagephoto.com/	https://www.instagram.com/aspensagephoto/
Michael Rawlings Photography	Photography		Vail	Colorado	Vail and Beaver Creek	Long-standing Vail photographer covering weddings and engagements in photojournalistic, classic, contemporary and fine art styles around Vail and Beaver Creek.	michael@vailphotography.com	970-390-9233	https://vailphotography.com/	
Danielle DeFiore Photography	Photography		Aspen	Colorado	Aspen, Snowmass, Basalt, Vail, Beaver Creek, Telluride and Steamboat	Aspen photographer for weddings and family portraits, with an unscripted, story-led style across Colorado's mountain towns.			https://danielledefiore.com/	https://www.instagram.com/danielle_defiore/
Jacie Marguerite	Photography		Aspen	Colorado	Aspen, wider Colorado and destination weddings	Aspen wedding photographer shooting editorial, emotive images for elegant celebrations, luxury wedding weekends and destination events.			https://jaciemarguerite.com/	https://www.instagram.com/jaciemarguerite/
Two Elk Studios	Photography	210 Edwards Village Blvd D206	Edwards	Colorado	Vail, Beaver Creek, Eagle, Edwards, Breckenridge, Keystone and Aspen	Edwards studio offering wedding, couples and family photography that blends reportage with careful posing and lighting for Vail Valley celebrations.	hi@twoelkstudios.com	970-325-2258	https://www.twoelkstudios.com/	https://www.instagram.com/twoelkstudios/
Kellie McKenzie Photography	Photography		Vail	Colorado	Vail, Avon, Edwards and Eagle	Full-time Vail photographer who covers weddings, engagements and elopements, plus family and senior sessions, across the Vail Valley.	kelliemckenziephotography@gmail.com		https://www.kelliemckenziephotography.com/	https://www.instagram.com/kelliemckenziephotography/
Hickory Grove Pictures	Photography		Aspen	Colorado	Aspen, Snowmass Village, Woody Creek, Basalt, Carbondale and the Roaring Fork Valley	Cinematic wedding film and photography team taking a limited number of Aspen weddings each season, with drone footage offered where permitted.	west@hickorygrovepictures.com		https://www.hickorygrovepictures.com/aspen	https://www.instagram.com/hickorygrovepictures/
Gregg & Cath Photographers	Photography		Aspen	Colorado	Aspen, Snowmass Village, Basalt, Carbondale and Glenwood Springs	Roaring Fork Valley photographers covering weddings, elopements and engagements against mountain backdrops, alongside family and corporate work.			https://www.greggandcathphotographers.com/	https://www.instagram.com/greggcathphoto/
Stargazed Weddings and Events	Planning		Aspen	Colorado	Aspen, Snowmass, Vail, Beaver Creek, Crested Butte and Steamboat Springs	Full-service planning and design studio for mountain weddings, led by its owner, Jenny, and covering Aspen, Snowmass and the Vail area.			https://stargazedweddings.com/	https://www.instagram.com/stargazed_weddings_and_events/
J.Lemons Events	Planning		Aspen	Colorado	Aspen and surrounding areas	High-touch, full-service Aspen wedding planner offering tasteful guidance from first ideas through to the wedding day.	janie@jlemonsevents.com	970.379.8072	https://www.jlemonsevents.com/	https://www.instagram.com/j.lemonsevents/
Aspen Eventworks	Planning	325B Summerset Way	Basalt	Colorado	Aspen area	Basalt event company producing both corporate and social events, from mountain-top weddings to large galas around Aspen.		970.618.5750	https://www.aspeneventworks.com/	https://www.instagram.com/aspeneventworks/
Veils of Vail	Planning		Vail	Colorado	Vail, Beaver Creek, Aspen and Breckenridge	Wedding planner for destination couples, with full, partial and weekend coordination packages, run by Becca Gould in the Rocky Mountains.	Becca@veilsofvail.com	512-809-6262	https://www.veilsofvail.com/	https://www.instagram.com/veilsofvail/
Kira Barczy Events	Planning		Vail	Colorado	Vail, Aspen and Beaver Creek	Vail wedding planner and designer with over a decade of experience, working at venues such as Four Seasons Vail and Camp Hale.	kira@kirabarczyevents.com	808-298-7704	https://kirabarczyevents.com/	https://www.instagram.com/kirabarczyevents/
Rose Petals	Florals		Vail	Colorado	Vail, Beaver Creek and the wider Vail Valley	Wedding florist offering bespoke bouquets, ceremony and reception designs, plus lighting, draping and furniture hire for mountain celebrations.	flowers@rosepetalsvail.com	(970) 687-1723	https://rosepetalsvail.com	
Two Roots Farm	Florals	100 Sopris Creek Road	Basalt	Colorado	Basalt, Aspen and the Roaring Fork Valley	Organic farm growing its own chemical-free flowers, with full-service and a la carte wedding floral design for couples across the valley.	farmers@tworootsfarm.com	(970) 376-6039	https://www.tworootsfarm.com	https://www.instagram.com/tworootsfarm/
Sweet Pea Designs	Florals	210 Edwards Village Blvd Suite 119	Edwards	Colorado	Vail to Edwards, with daily delivery in the valley	Edwards flower shop making custom bouquets and arrangements for mountain weddings, alongside plants, gifts and permanent botanical pieces.		(970) 949-6617	https://www.sweetpeadesignsvail.com	
Flower Franch	Florals		Basalt	Colorado	Basalt, Aspen and the Roaring Fork Valley	Basalt florist designing custom wedding flowers, from timeless classics to avant-garde pieces, with consultations and a portfolio of past weddings.		(970) 279-5267	https://www.flowerfranch.com	https://www.instagram.com/flowerfranch/
Botanicals Floral Art	Florals		Glenwood Springs	Colorado	Glenwood Springs, Carbondale, Aspen, Snowmass, Basalt, New Castle and Rifle	Florist in business since 2012 offering wedding packages, arch decor hire and valley-wide delivery for couples across the Roaring Fork Valley.	info@botanicalscolorado.com	(970) 379-4870	https://www.botanicalscolorado.com	https://www.instagram.com/botanicalsfloral/
Aspen DJ Company	Music		Aspen	Colorado	Aspen, Snowmass, Roaring Fork Valley, Vail and Beaver Creek, plus destination weddings	Wedding DJ team covering ceremony, cocktail hour and after-party, with sound, uplighting and wireless microphones included in tailored packages.		(970) 404-9319	https://www.aspendjcompany.com	https://www.instagram.com/aspendjcompany/
Kickin' Aspen Entertainment	Music		Aspen	Colorado	Aspen and surrounding areas, with a focus on destination weddings	Aspen DJ duo who can add live musicians for ceremony and cocktails, and plan remotely with couples marrying from afar.	KickinAspen@yahoo.com	(423) 352-7736	https://kickinaspen.com	
The Farmer and Chef	Catering		Carbondale	Colorado	Aspen, Snowmass, Carbondale and Basalt	Scratch-kitchen caterer serving weddings and celebrations with farm-to-table menus built on local, seasonal ingredients across the valley.	info@thefarmerandchef.com	(970) 279-3272	https://www.thefarmerandchef.com	https://www.instagram.com/thefarmerandchef/
Vail Catering Concepts	Catering		Vail	Colorado	Vail and surrounding venues	Chef-owned caterer with a dedicated wedding menu, cooking with natural meats and fresh produce for plated dinners and receptions, staffed to match.		970-376-5263	https://www.vailcateringconcepts.com	
Vail Chef	Catering		Vail	Colorado	Eagle-Vail Valley	Chef-run catering and private dining company for groups from four to over four hundred, delivering customised menus for weddings and events.		970-331-2334	https://www.vailchef.com	https://www.instagram.com/vail_chef/
Full Circle Aspen	Hair & Makeup		Aspen	Colorado	Aspen, Snowmass and the Roaring Fork Valley	Mobile beauty team bringing bridal hair and makeup to homes, hotels and rental properties around Aspen, alongside wider wellness services.		(970) 923-3302	https://www.fullcircleaspen.com	https://www.instagram.com/fullcircleaspen/
SweetCheeks Vail	Hair & Makeup	30 West Benchmark Rd. Unit G1	Avon	Colorado	Vail, Beaver Creek and surrounding Eagle County	Hair and makeup studio offering bridal styling in the salon or on location, with hourly pricing and travel fees applied for on-site work.	sweetcheeksmakeup@mail.com	(970) 331-1429	https://sweetcheeksvail.com	https://www.instagram.com/sweetcheeksvailco/
Bhava Beauty and Wellness	Hair & Makeup	47 E Beaver Creek Blvd #C19	Avon	Colorado	Vail, Beaver Creek, Aspen and other Colorado resort towns	Organic spa and salon in Avon that styles wedding hair and makeup in-house or on location, with a relaxed natural mountain-bride look.	info@bhavabeautyandwellness.com	970-368-2404	https://bhavabeautyandwellness.com	https://www.instagram.com/bhavabeautyandwellness/
Sunshine Beauty & Bridal	Hair & Makeup		Vail	Colorado	Vail, with travel available on request	Vail-based bridal artist providing makeup, hair and spray tans for brides, with consultations, touch-up kits and extension and veil advice included.	ana@sunshinebeautyandbridal.com		https://www.sunshinebeautybridal.com	https://www.instagram.com/sunshine_beauty_bridal/
Rocky Mountain Hair Co.	Hair & Makeup	210 Offerson Rd	Beaver Creek	Colorado	Beaver Creek Village and surrounding areas	Beaver Creek Village salon that styles hair and makeup for weddings and elopements, with outcall visits available for bridal parties.	information@rockymountainhairco.com		https://www.rockymountainhairco.com	https://www.instagram.com/rockymountainhairco/
Mountain Flour	Cake	824 Chambers Ave #A4	Eagle	Colorado	Vail Valley	Eagle bakery making custom wedding cakes and groom's cakes, as well as birthday cakes and other specialty desserts for the Vail region.	info@mountainflour.com	(970) 328-0312	https://www.mountainflour.com	
Afternoon Delight Bakery	Cake		Glenwood Springs	Colorado	Aspen, Snowmass, Vail and the Colorado mountains	Owner-run bakery making original-design wedding cakes from scratch, with tastings offered in person or shipped, serving the mountain region.	afternoondelightbakery.ashley@gmail.com	970.984.6306	https://www.afternoondelightbakery.com	https://www.instagram.com/afternoon.delight.bakery/
Coppelia Cake Design	Cake		Carbondale	Colorado	Aspen, Glenwood Springs and the Rocky Mountains of Colorado	Carbondale cake studio designing custom wedding cakes, with a gallery of past work, flavour options and pricing guidance for couples.			https://www.coppeliacakedesign.com	https://www.instagram.com/coppeliacakes/
Summit Photo & Film	Videography		Aspen	Colorado	Aspen, the Roaring Fork Valley and destination weddings	Husband-and-wife team in Aspen filming natural, unposed mountain weddings alongside photography, with coverage across the valley and further afield.	dale@summitphotoandfilm.com	970-710-9647	https://summitphotoandfilm.com	https://www.instagram.com/summitphotoandfilm/
Larisa Graham Video + Photo	Videography		Eagle	Colorado	Vail, Beaver Creek, Aspen, Steamboat Springs and Telluride	Eagle-based wedding videographer taking a documentary, unobtrusive approach to filming, with eight-hour coverage and highlight films.		970-471-4145	https://larisagraham.com	
Majestik Films	Videography		Aspen	Colorado	Aspen, Vail, Beaver Creek, Breckenridge, Keystone and Denver	Story-led wedding filmmakers who have worked with over 400 couples across Colorado, offering combined photo and video packages.			https://www.majestikfilms.com	https://www.instagram.com/majestikweddings/
`,
  },
  {
    name: "Fort Collins: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Lara Photography	Photography		Fort Collins	Colorado	Colorado	Sean Lara photographs weddings and elopements on digital and film from Fort Collins, and also offers albums and wedding video.	info@seanlara.com		https://seanlara.com/	https://www.instagram.com/seanlaraphotography/
Girard Photo & Film	Photography		Loveland	Colorado	Colorado and destination weddings	A husband-and-wife team in Loveland who photograph and film weddings of every size, from intimate ceremonies to full weekends.	info@girardphotoandfilm.com		https://girardphotoandfilm.com/	https://www.instagram.com/girardphotoandfilms/
Love Letter Film Co.	Videography		Fort Collins	Colorado	Colorado and worldwide	A Fort Collins wedding film studio making cinematic, story-led films of Colorado weddings and destination celebrations abroad.	hello@loveletterfilmco.com		https://www.loveletterfilmco.com/	https://www.instagram.com/loveletterfilmco/
All Digital Photo and Video	Videography		Greeley	Colorado	Denver, Estes Park, Fort Collins, Loveland and Windsor	A Greeley photo and video company filming weddings since 1999, able to send both a photographer and a videographer for the day.	info@alldigitalphotoandvideo.com	866-243-8749	https://alldigitalphotoandvideo.com/	https://www.instagram.com/alldigitalphotoandvideo/
Amoré DJ Entertainment	Music		Fort Collins	Colorado	Estes Park, Fort Collins, Boulder, Denver, Vail and Colorado Springs	An award-winning Colorado wedding DJ and MC company led by its owner, adding event lighting, decor and photo booths on request.		970-215-2690	https://amoredjentertainment.com/	
Howe Eventful	Music	201 E 4th St	Loveland	Colorado		A Loveland entertainment company offering mobile DJs, live musicians and silent disco for wedding ceremonies and receptions.	info@howeeventful.com		https://www.howeeventful.com/	https://www.instagram.com/howeeventful/
Rutabaga Catering	Catering		Longmont	Colorado	Within 65 miles of Longmont, including Boulder, Denver, Estes Park and Fort Collins	A Longmont kitchen serving restaurant-style plated dinners, buffets and drop-off menus at weddings along the Front Range.	hello@rutabagacatering.com	970-670-8440	https://rutabagacatering.com/	https://www.instagram.com/rutabagacatering/
Fresh Plate Catering	Catering		Loveland	Colorado	Northern Colorado and Denver	A Loveland caterer with over 20 years in Northern Colorado, cooking with fresh seasonal ingredients for weddings from Estes Park to the plains.	tracie@freshplatecatering.com	970-460-6091	https://freshplatecatering.com/	https://www.instagram.com/fresh.plate.catering/
The Cakery	Cake	2842 Council Tree Ave #141	Fort Collins	Colorado	Northern Colorado	A Fort Collins bakery known for its cupcakes, making wedding cakes and cupcake displays for couples across Northern Colorado.		970-391-5070	https://www.thecakeryco.com/	https://www.instagram.com/thecakerynoco/
Kupcake Konnoisseur	Cake		Loveland	Colorado	Northern Colorado	A Loveland cupcake bakery supplying wedding cupcakes and dessert displays to couples and venues throughout Northern Colorado.	KupcakeKonnoisseur@gmail.com	970-310-1176	https://www.kupcakekonnoisseur.com/	https://www.instagram.com/kupcake_konnoisseur/
Ardent Rose Floral	Florals		Loveland	Colorado	Northern Colorado	Kelsey's Loveland floral studio designs textured, botanical wedding flowers, from full-service installs to elopement bouquets.	ardentrosefloraldesign@gmail.com		https://www.ardentrosefloraldesign.com/	https://www.instagram.com/ardentrosefloral/
Reale Events	Florals	22322 Schultz Ln	Berthoud	Colorado		A Berthoud floral and decor studio that also rents out a large event inventory, so flowers and furnishings can come from one place.	info@Reale-Events.com		https://www.reale-events.com/	https://www.instagram.com/reale_events/
Mountainside Events	Planning		Fort Collins	Colorado	Colorado	A Fort Collins wedding planning company offering full and partial planning, design and month-of coordination across Colorado.	taylor@mountainsideevents.com	970-215-4258	https://www.mountainsideevents.com/	https://www.instagram.com/mountainsideevents/
Sweetie Pie Weddings	Planning		Fort Collins	Colorado		A Fort Collins planning and design studio that stays with couples through every stage, from the first budget to the wedding day.	sweetiepieweddings@gmail.com	970-449-2301	https://www.sweetiepieweddings.com/	
Carver Coordination	Planning	387 Buffalo Dr, Unit C	Windsor	Colorado	Colorado and Wyoming	Stacie Carver's Windsor planning firm handles budgets, design and day-of running so couples and families can be guests at their own wedding.	carvercoordination@gmail.com	719-510-5917	https://www.carvercoordination.com/	https://www.instagram.com/carvercoordination/
Orchidée Salon & Spa	Hair & Makeup	1015 W Horsetooth Rd	Fort Collins	Colorado		A Fort Collins salon and spa doing bridal party hair and makeup in the salon or on site, plus pre-wedding spa days.		970-488-2733	https://orchideesalonandspa.com/	https://www.instagram.com/orchideesalonandspa/
Rotella Beauty	Hair & Makeup	588 N Lincoln Ave	Loveland	Colorado	Fort Collins, Loveland, Estes Park, Boulder and Northern Colorado	Danielle Rotella's Loveland studio does natural, skin-focused bridal hair and makeup, travelling to venues across Northern Colorado.			https://www.rotellabeauty.com/	
The Bridal Goddess	Hair & Makeup		Longmont	Colorado	Boulder, Longmont, Estes Park, Lyons, Denver and Fort Collins	A Longmont bridal hair and makeup team working since 2011, specialising in medium and large wedding parties on the Front Range.		720-927-9944	https://www.thebridalgoddess.com/	https://www.instagram.com/thebridalgoddess/
`,
  },
  {
    name: "Boulder: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Nina Reed Photography	Photography		Boulder	Colorado	Boulder, Front Range, Colorado mountains (about two hours' drive)	Boulder-based wedding and elopement photographer whose recent work spans Boulder receptions, Aspen, Estes Park, Leadville and micro weddings in the foothills.			https://ninareed.com/	
June Moon Photography	Photography		Boulder	Colorado	Boulder, Front Range	Boulder-born photographer offering documentary-style elopement and micro wedding coverage for couples marrying in Boulder or along the Front Range.			https://junemoonphotography.com/	
Ivory Events	Planning		Boulder	Colorado	Boulder, Denver, Colorado mountain towns	Boulder wedding planning firm offering full-service, partial planning and day-of coordination for weddings from the Front Range to Vail and Aspen.		720-771-2488	https://ivoryeventscolorado.com/	https://www.instagram.com/ivoryeventsco/
Colorado Celebrations	Planning		Boulder	Colorado	Boulder, Longmont, Denver, Front Range, Estes Park	Boutique Boulder County planning team handling wedding timelines, vendor communication and day-of logistics, plus showers and other social events.	hello@colorado-celebrations.com		https://colorado-celebrations.com/	https://www.instagram.com/coloradocelebrations/
Cherry Bomb Events	Planning		Boulder	Colorado	Boulder, Denver, Estes Park, Vail, Telluride	Boulder wedding planner offering planning packages, day-of and month-of coordination, and an in-house floral studio for couples who want one team.	shayna@cherry-bombevents.com	303-877-2640	https://www.cherrybombweddings.com/	https://www.instagram.com/cherry_bomb_events/
Root and Gather Events	Planning		Boulder	Colorado	Boulder, Colorado	Boulder wedding planning and design company with a sustainability focus, helping couples choose venues and vendors and shape tablescapes and details.	alaina@rootandgatherevents.com		https://rootandgatherevents.com/	https://www.instagram.com/rootandgatherevents/
Marigold Events	Planning		Boulder	Colorado	Boulder, Denver, Colorado mountains (Aspen, Vail, Beaver Creek)	Boulder-based planning and event design studio offering full-service wedding planning across the Front Range and the Colorado mountain resorts.	hello@marigold-events.com		https://www.marigold-events.com/	https://www.instagram.com/marigoldeventsco/
Boulder Blooms	Florals	2935 Baseline Rd. Ste 103	Boulder	Colorado	Boulder and Front Range	Boulder flower studio with full-service wedding florals and an à la carte menu with no minimum, suited to elopements and smaller celebrations.	info@boulderblooms.com	(303) 494-5678	https://boulderblooms.com/	https://www.instagram.com/boulderblooms/
Painted Primrose Co.	Florals		Boulder	Colorado	Boulder, Colorado	Boulder floral designer creating one-of-a-kind wedding flowers for couples who want something personal and a little unconventional.	sabia@paintedprimrose.co		https://paintedprimrose.co/	https://www.instagram.com/paintedprimrose/
A Florae	Florals		Longmont	Colorado	Longmont, Boulder County, Denver	Longmont florist offering full-service wedding design, delivery and setup, plus à la carte bouquets and arch rentals for couples on a smaller budget.	Rachel@aflorae.com	720-680-0046	https://www.aflorae.com/	https://www.instagram.com/a_florae/
Belle Terre Floral	Florals	7960 Niwot Rd	Niwot	Colorado	Boulder, Niwot, Front Range	Niwot floral studio that serves as resident florist at a Boulder wedding venue and designs bouquets, bar florals and backdrops for celebrations nearby.	sarah@belleterrefloral.com	(303) 652-0419	https://belleterrefloral.com/	https://www.instagram.com/belleterrefloral/
Tier Two Live	Music		Lafayette	Colorado	Boulder County, Boulder, Denver, Front Range	Lafayette DJ and MC service that also arranges live music, sound and lighting for weddings across Boulder County and the Front Range.	TierTwoLive@gmail.com	303-710-5201	https://www.tiertwolive.com/	https://www.instagram.com/tiertwolive/
The Fever	Music		Boulder	Colorado	Colorado, travels widely	Boulder live band, flexible from solo to nine-piece, playing jazz, funk, rock, pop and bluegrass, with emceeing and event timeline help for weddings.			https://www.thefeverlive.com/	https://www.instagram.com/thefeverlive/
M3DIUM Productions	Music		Boulder	Colorado	Boulder, Louisville, Lafayette, Longmont, Lyons, Front Range	Boulder wedding DJ team supplying ceremony sound, PA, lighting and an MC with packages quoted within a day, and also offers video.	hello@m3diumproductions.com	720-893-1933	https://m3diumproductions.com/	https://www.instagram.com/m3dium_dj/
Three Leaf Catering	Catering	808 Main St	Louisville	Colorado	Boulder area, Louisville, Chautauqua	Louisville caterer from a Boulder-area restaurant group, serving weddings on and off site with a dedicated weddings page and gallery.	info@threeleafcatering.com	303-862-8584	https://www.threeleafcatering.com/	
A Spice of Life Catering	Catering	2108 55th St., Suite 115	Boulder	Colorado	Boulder, Denver, Lyons, Estes Park, Front Range	Boulder caterer handling weddings and corporate events, with a wedding page covering mountain venues in Lyons and Estes Park.		(303) 443-4049	https://www.aspiceoflife.com/	https://www.instagram.com/aspiceoflifecatering/
Savory Catering	Catering	5741 Arapahoe Ave #1A	Boulder	Colorado	Boulder, Denver, Broomfield, Longmont, Louisville, Golden	Boulder caterer offering wedding menus across American, Italian and Mexican styles, with zero-waste options and dietary accommodations.		(303) 440-1016	https://www.savorycatering.com/	
Shear Abby	Hair & Makeup	2338 Broadway Street Unit C	Boulder	Colorado	Boulder, on location, travels	Downtown Boulder salon offering bridal hair, makeup and extensions for the whole wedding party, in the salon or on location.		303-807-6042	https://www.shearabby.com/	
WedLocks Bridal Hair & Makeup	Hair & Makeup		Boulder	Colorado	Boulder, Colorado	Boulder bridal beauty team providing wedding hair and makeup for brides and their parties, working with all skin tones and hair textures.	info@wedlocksbridalhair.com	(720) 292-3177	https://www.wedlocksbridalhair.com/	https://www.instagram.com/wedlocks/
Ember Salon & Spa	Hair & Makeup	1215 Spruce Street, Unit 100B	Boulder	Colorado	Boulder, Denver, mountain destinations	Downtown Boulder salon whose on-location team styles bridal hair and makeup at hotels, homes and rentals; bookings go through a wedding coordinator.		720-665-5111	https://embersalonboulder.com/	https://www.instagram.com/embersalon_boulder/
Petal & Thyme	Cake		Longmont	Colorado	Longmont, Boulder County, Colorado	Longmont bakery making custom wedding cakes and mini desserts, with travel and delivery to venues and booking handled online.	hello@petalandthyme.com	(970) 670-8440	https://petalandthyme.com/	https://www.instagram.com/petalthymebakery/
`,
  },
  {
    name: "Estes Park: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Pyle Photography	Photography		Estes Park	Colorado	Estes Park, Rocky Mountain National Park and nearby mountain venues	Estes Park photography team shooting weddings, elopements and engagement sessions at local lodges and in Rocky Mountain National Park.			https://www.joepylephotography.com/	https://www.instagram.com/joepylephotography/
Story Maker Photo	Photography		Estes Park	Colorado	Estes Park and Colorado mountain weddings	Estes Park wedding photographer with over 300 weddings behind her, focused on intimate celebrations, elopements and micro weddings.	amber@storymakerphoto.com		https://storymakerphoto.com/	https://www.instagram.com/storymakerphoto/
Fanciful	Planning		Estes Park	Colorado	Estes Park, Crested Butte and the Western Slope	Estes Park planner offering base, partial and complete planning plus à la carte help for mountain and destination weddings, with floral design too.	fancifulfdwp@gmail.com	970-567-8387	https://fancifulweddings.com/	
Floral Design of Europe	Florals		Estes Park	Colorado	Estes Park	Estes Park florist making bridal and party bouquets, ceremony decor, centrepieces and cake flowers, led by a designer with over 35 years of experience.	fdofeurope@gmail.com	(970) 577-9999	http://fdofeurope.com/	https://www.instagram.com/floraldesignofeurope/
Lilac and Sage Studio	Florals		Loveland	Colorado	Loveland	Loveland wedding and event florist creating arrangements for couples, run by florist Kelly James.	lilacandsagestudio@gmail.com		https://www.lilacandsagestudio.com/	https://www.instagram.com/lilacandsagestudio/
Pure Sounds Productions	Music		Loveland	Colorado	Northern Colorado, Denver, Boulder and mountain towns including Estes Park	Long-running wedding DJ company that plays weddings across northern Colorado and the mountains, working from each couple's own wishes.		303.678.1966	http://www.pspdj.com/	https://www.instagram.com/pspdj/
Jubilations Catering	Catering		Estes Park	Colorado	Estes Park, Lyons, Loveland and northern Colorado	Estes Park caterer with in-house chefs building custom wedding menus, from plated dinners to street tacos.	info@jubilationscatering.com	(303) 440-1315	https://jubilationscatering.com/	https://www.instagram.com/jubilationscatering/
Mountain Berry Bakery	Cake	400 B E Elkhorn Ave	Estes Park	Colorado	Estes Park	Riverwalk bakery in Estes Park making custom wedding cakes, with an online request form for orders.		(563) 581-2303	https://mountainberrybakery.com/	
Bridal Glow Wedding Services	Hair & Makeup		Estes Park	Colorado	Estes Park	Mobile team styling brides, grooms, bridal parties and families with hair, makeup and airbrush spray tans on location.		970.391.0929	https://www.bridalglowweddingservices.com/	https://www.instagram.com/bridalglowweddings/
Glacier Lily Beauty	Hair & Makeup	513 Big Thompson Ave, Unit 102	Estes Park	Colorado	Estes Park	Estes Park salon and boutique in Lower Stanley Village that also provides on-site wedding hair and makeup.		(970) 599-0301	https://www.glacierlilybeauty.com/	https://www.instagram.com/glacierlilybeauty_ep/
Something Borrowed	Hair & Makeup		Estes Park	Colorado	Estes Park	Mobile bridal hair and makeup service offering styling for brides and wedding parties, with a sister photo booth business.	Info@somethingborrowedep.com	(970) 443-1137	https://www.somethingborrowedep.com/	
Jake Beyer	Videography		Estes Park	Colorado	Estes Park, Rocky Mountain National Park and Colorado	Estes Park filmmaker making cinematic wedding and engagement films, who also photographs elopements and weddings in the mountains.			https://www.jakebeyer.com/	https://www.instagram.com/jake_beyer/
`,
  },
  {
    name: "Fort Collins: photography, florals, music, catering and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hillary Shedd Photography	Photography		Fort Collins	Colorado	Fort Collins, Estes Park, Vail, Summit County and Denver	Fort Collins photographer with a documentary, candid style for weddings, from city celebrations to intimate mountain ceremonies.			https://www.hillarysheddphotography.com/	https://www.instagram.com/hillarysheddphotography/
The Joyful Poppy	Florals	5748 S College Ave, Unit C	Fort Collins	Colorado	Northern Colorado	Fort Collins florist designing bridal and reception flowers, with consultations in person or by phone and flower preservation available.		970-443-8053	https://thejoyfulpoppy.com/	https://www.instagram.com/thejoyfulpoppy/
Ron Michaels Weddings	Music		Fort Collins	Colorado	Fort Collins and Estes Park	Fort Collins DJ and master of ceremonies who also officiates, with song resources for couples and a booking call before the day.	Ron@RonMichaelsWeddings.com	970-225-3900	http://www.ronmichaelsweddings.com/	
Ginger and Baker	Catering	359 Linden Street	Fort Collins	Colorado	Fort Collins, Loveland, Windsor, Timnath, Severance and Wellington	Fort Collins caterer and bakery offering buffet, family-style and plated meals, dessert catering, rehearsal dinners and morning-after brunches.		970-223-7437	https://gingerandbaker.com/	https://www.instagram.com/gingerandbaker/
`,
  },
  {
    name: "Vail and Aspen: music, catering, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
DJ Jay One	Music		Vail	Colorado	Vail Valley, including Vail and Beaver Creek	Vail DJ mixing open-format sets live for weddings, who also plays private parties and fundraisers.	jarrettquint@hotmail.com		https://djjayone.com/	https://www.instagram.com/d.j.jayone/
All Occasions Music	Music		Vail	Colorado	Vail, Beaver Creek, Aspen, Telluride and across Colorado	Vail live band company covering ceremony, cocktails and reception for one price, with line-ups from four players to an orchestra.		(970) 331-6111	https://www.alloccasionsmusic.net/	https://www.instagram.com/jmoband/
Roaring Fork Event Company	Music		Glenwood Springs	Colorado	Roaring Fork Valley, Aspen, Snowmass, Vail and Beaver Creek	Valley sound and lighting company supplying wedding DJs, MCs, uplighting, dance floors and LED video walls.	roaringforkeventcompany@gmail.com	612.508.3871	https://www.roaringforkeventcompany.com/	https://www.instagram.com/roaringforkeventcompany/
Big Delicious Catering	Catering	503 S Frontage Rd E	Vail	Colorado	Vail Valley, Beaver Creek, Aspen and Denver	Vail-based caterer with a dedicated weddings service, working across Vail Valley and further afield.	hunter@bigdeliciouscatering.com	(970) 896-6855	https://bigdeliciouscatering.com/	https://www.instagram.com/bigdeliciousvailco/
Aspen Chef	Catering	50 Sunset Drive #5	Basalt	Colorado	Aspen, Snowmass and the Roaring Fork Valley	Basalt private chef and catering company offering wedding catering with custom menus across the Roaring Fork Valley.	alan@aspenchef.com	(970) 279-5274	https://www.aspenchef.com/	
Cornerstone Chocolates & Confections	Cake	32137 US Hwy 6	Edwards	Colorado	Vail, Beaver Creek, Aspen and greater Colorado	Edwards chocolatier and cake maker creating custom wedding cakes made to order and delivered to Vail, Beaver Creek and Aspen.		970.291.1343	https://cornerstonechocolates.com/	https://www.instagram.com/cornerschocolat/
`,
  },
  {
    name: "Colorado Springs: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mikayla Renee Photo	Photography		Colorado Springs	Colorado	Colorado Springs, Denver, Telluride, Crested Butte, Aspen and other Colorado destinations	Colorado Springs wedding and elopement photographer who shoots romantic, vibrant coverage for celebrations of up to 200 guests.		414-659-6454	https://mikaylareneephoto.com/	https://www.instagram.com/mikaylareneephoto/
Wed with Erika	Planning		Colorado Springs	Colorado	Throughout Colorado	Downtown Colorado Springs planner offering month-of coordination from $2,950 and full planning from $6,500, with a free consultation for full-service couples.	erika@wedwitherika.com	720-329-7692	https://www.wedwitherika.com/	https://www.instagram.com/wed_with_erika/
Dream Catcher Weddings	Planning		Colorado Springs	Colorado	Colorado, including destination wedding weekends	Colorado Springs planning business offering full-service, partial and month-of support, with pricing and deliverables set out up front for couples.	howdy@dreamcatcherwed.com	719-204-3904	https://www.dreamcatcherwed.com/	https://www.instagram.com/dreamcatcherweddingsco/
Cosette's Creations	Florals		Colorado Springs	Colorado	Pikes Peak region including Manitou Springs, Monument, Black Forest and Larkspur	Woman-owned Colorado Springs florist designing sustainable, locally sourced wedding flowers, from ceremony arches to bouquets, for a limited number of weddings.			https://www.cosettes.com/	https://www.instagram.com/cosettes_creations/
Amber Mustain Floral Design	Florals		Colorado Springs	Colorado	Colorado Springs and Rocky Mountain wedding venues	Colorado Springs studio florist creating custom wedding and event flowers by pre-order, with past work at the Garden of the Gods Resort.	hello@ambermustain.com	719-469-4267	https://www.ambermustain.com/	https://www.instagram.com/ambermustain_floraldesign/
Rise DJs	Music		Colorado Springs	Colorado	Colorado Springs and across Colorado	Colorado Springs wedding DJ and MC company with flat-rate packages from $995 to $2,495 covering ceremony, cocktail hour and reception.	info@risedjs.com	970-404-2400	https://risedjs.com/	https://www.instagram.com/risedjscolorado/
MC Events Co.	Music		Colorado Springs	Colorado	Colorado Springs, the Front Range, Denver, Pueblo and Fort Collins	Colorado Springs DJ and MC service with wedding packages from $900 for four hours, plus photo booth, lighting and video options.	mceventsco@gmail.com	719-301-3239	https://mceventsco.com/	https://www.instagram.com/mceventsco/
A Piece of Cake Catering	Catering		Colorado Springs	Colorado	Colorado Springs and the Front Range	Colorado Springs caterer offering tiered wedding buffets, food stations and a Western barbecue option, with wedding cakes available from the same kitchen.	APieceOfCakeCaterings@hotmail.com	719-310-7683	https://www.apieceofcakecatering.com/	
Kim Clay Artistry	Hair & Makeup	770 Wooten Rd #101	Colorado Springs	Colorado	Colorado Springs and surrounding area	Colorado Springs makeup artist working from a studio on Wooten Road, with bridal makeup listed among her specialities.	contact@kimclaymua.com	719-306-7616	https://coloradospringsmakeup.com/	https://www.instagram.com/kimclayartistry/
Emerson Rae Styling	Hair & Makeup		Colorado Springs	Colorado	Colorado Springs and brides across Colorado	Colorado Springs stylist providing a calm, tailored bridal beauty experience with trials, available to travel for weddings elsewhere in Colorado.			https://emersonraestyling.com/	https://www.instagram.com/emersonraestyling/
Bella Cakes by Thena	Cake		Colorado Springs	Colorado	Colorado Springs	Colorado Springs bakery with a large wedding cake gallery, plus cookies and cupcakes, taking tasting appointments for larger tiered cakes.			https://www.bellacakesbythena.net/	
Promise Pine	Videography		Colorado Springs	Colorado	Colorado Springs and across Colorado	Colorado Springs filmmaker making quiet, intentional wedding films that favour unposed moments over staged shots, with elopement coverage too.	matthew@promisepine.com	719-332-1001	https://promisepine.com/	https://www.instagram.com/promisepine/
Lizzie Studios	Videography		Colorado Springs	Colorado	Denver, Boulder, Fort Collins, Aspen, Buena Vista, mountain towns and destinations	Colorado Springs videographer filming documentary-style weddings and elopements full of candid details and laughter, with destination work available.			https://www.lizziestudios.com/	https://www.instagram.com/sarahstruttmann/
`,
  },
  {
    name: "Denver: photography, planning, florals, music, catering, hair and makeup, cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Berg Berg Photography	Photography		Golden	Colorado	Golden, Denver, Estes Park, Winter Park, Evergreen, Littleton and across Colorado	Golden wedding photography duo covering Colorado venues, with experience in Indian, Hindu, LGBTQ and film weddings.	bergbergphotography@gmail.com		https://www.bergbergphotography.com/	https://www.instagram.com/bergbergphotography/
Kimberly Crist Photography	Photography		Denver	Colorado	Statewide in Colorado	Denver photographer focused on scenic Colorado elopements and intimate weddings, favouring locations a short walk from parking.	hello@kimberlycrist.com		https://www.kimberlycrist.com/	https://www.instagram.com/kimberlycrist/
Brooke Silverman Photography	Photography		Denver	Colorado	Denver and surrounding areas, with travel across the US and abroad	Denver photographer offering photojournalistic wedding, elopement, engagement and proposal coverage, with travel across the US.	info@brookesilvermanphotography.com	410.350.5399	https://www.brookesilvermanphotography.com/	https://www.instagram.com/brookesilvermanphoto/
Mado Photo	Photography		Denver	Colorado	Denver and the Colorado area, available for travel	Inclusive Denver photographer shooting weddings, couples and elopements on digital and film, with over a decade of experience.	Info@mado-photo.com	(303) 946-1780	https://www.mado-photo.com/	https://www.instagram.com/mado.photo/
Erika Sandoval Events	Planning		Denver	Colorado	Denver, Vail, Aspen, Boulder and Colorado mountain destinations	Boutique Denver planning and design studio founded in 2013, taking on a limited number of weddings each year in the city and mountains.			https://erikasandovalevents.com/	https://www.instagram.com/erikasandovalevents/
Tie the Knot Bridal Creations	Planning	10050 Ralston Rd Suite #5	Arvada	Colorado	Denver, Lakewood, Littleton, Boulder, Golden, Estes Park, Breckenridge and surrounding areas	Arvada wedding boutique offering planning, coordination, officiant services and rental decor for couples across the Denver area.	tietheknotbridalcreations@gmail.com	(303) 495-0926	https://www.tietheknotbridalcreations.com/	https://www.instagram.com/tietheknotbridalcreationsllc/
Lumiere Aisle Collective	Planning		Denver	Colorado	Denver and across Colorado, including destination weddings	Boutique Denver planning collective offering day-of coordination and full planning for city, mountain and intimate weddings.			https://www.lumiereaislecollective.com/	
Plum Social Events & Flowers	Florals	4360 E. Evans Ave.	Denver	Colorado	Colorado and beyond	Denver studio combining wedding florals with full event design, from candles and lighting to place cards, for celebrations across Colorado.	hello@plumsocial.com	(720) 328-2190	https://plumsocial.com/	https://www.instagram.com/plumsocialdenver/
KaraKara Blooms	Florals	472 N Broadway	Denver	Colorado		Denver floral studio founded in 2022 creating experiential flowers for weddings and elopements, run by a second-generation florist.			https://www.karakarablooms.com/	
Hovey Entertainment	Music		Littleton	Colorado	Throughout Colorado, including Denver, Boulder and mountain resort towns	Littleton DJ service handling the music, timeline and key moments for weddings, with lighting, photo booths and karaoke add-ons.	eric@hoveyentertainment.com	(303) 253-2747	https://www.hoveyentertainment.com/	https://www.instagram.com/hoveyentertainment/
Soul X Band	Music		Denver	Colorado	Colorado, other parts of the US and international	Denver variety band of eight to thirteen players covering Motown, funk, country and current pop for high-energy wedding receptions.	thesoulxband@gmail.com	720-231-5951	https://www.soulxband.com/	https://www.instagram.com/soulxband/
Deja Blu Variety Dance Band	Music		Denver	Colorado	Denver, Aspen, Vail and across Colorado	Seven-piece Denver dance band where every member sings, with smaller ensemble options for more intimate wedding celebrations.	band@dejabluband.com	(303) 517-9852	https://www.dejabluband.com/	https://www.instagram.com/dejabludanceband/
DJ Jen G	Music		Denver	Colorado		Denver wedding DJ who builds custom playlists around each couple and works closely with officiants and venues on the day.	book@djjeng.com	303-916-7730	https://www.djjeng.com/	https://www.instagram.com/dj.jeng/
Denver Lighting and DJ Services	Music		Denver	Colorado		Wedding DJ and MC service offering lighting design and event production for celebrations around Denver and mountain venues.	denverlightinganddj@gmail.com	(720) 788-9389	https://www.denverlightinganddj.com/	
Hippie Chicks Catering	Catering	225 Mariposa St	Denver	Colorado		Scratch-kitchen caterer making seasonal, locally sourced menus for weddings, from drop-off trays to fully staffed service.	info@hippiechickscatering.com	720-645-4536	https://hippiechickscatering.com	https://www.instagram.com/hippiechickscatering/
Three Tomatoes Catering	Catering	255 Yuma St	Denver	Colorado	Denver metro including Cherry Creek, LoDo, RiNo, Highlands, Lakewood, Littleton and Aurora	All-inclusive wedding caterer offering buffets, plated dinners and cocktail receptions, with menus and pricing you can build online.	info@threetomatoes.com	303-433-3332	https://www.threetomatoes.com	https://www.instagram.com/threetomatoescatering/
Modern Catering	Catering	490 Decatur St	Denver	Colorado	Denver, Boulder, Northern Colorado and the Front Range	Full-service Denver caterer building custom plated, buffet and station menus around regional ingredients, plus bartending and rentals.		(720) 299-7638	https://moderncatering.com	https://www.instagram.com/moderncateringco/
The Next Course	Catering		Denver	Colorado	Within about two hours of the Denver metro, including many mountain venues	Chef-owned caterer bringing restaurant-style wedding menus, from signature buffets and plated dinners to food trucks and brunch.	info@thenextcourseco.com	720-508-9881	https://www.thenextcourseco.com	https://www.instagram.com/thenextcourseco/
AURA Salon	Hair & Makeup	12664 W Indore Pl	Littleton	Colorado	Ken Caryl, Roxborough, Littleton, Morrison, Highlands Ranch, Evergreen, Bailey and Arvada	Littleton salon styling hair and makeup for brides and their parties, in the salon or on location, with timeless looks to suit each bride.	info@theaurasalon.com	303-933-2872	https://www.theaurasalon.com	https://www.instagram.com/theaurasalon/
Kim J Beauty	Hair & Makeup		Denver	Colorado	Colorado	Denver team travelling to weddings for natural, timeless bridal makeup and romantic, classic hairstyles.	kim@kimjbeauty.com	720-261-8274	https://www.kimjbeauty.com	https://www.instagram.com/kimjbeauty/
Candelaria Beauty	Hair & Makeup	2421 28th Ave	Denver	Colorado	Boulder, Denver, Estes Park, Vail and greater Colorado	Wedding beauty team offering calm, refined bridal hair and makeup that looks effortless, plus photoshoot glam and makeup lessons.	hello@candelariabeauty.com	(970) 430-8048	https://www.candelariabeauty.com	https://www.instagram.com/candelariabeautyco/
Divine Beauty Artists	Hair & Makeup		Denver	Colorado	Denver, Boulder, Colorado Springs, Breckenridge, Vail, Aspen and surrounding areas	Travelling bridal hair and makeup team, from classic princess styles to bold glam, with experience across cultural traditions and skin tones.			https://www.divinebeautyartists.com	https://www.instagram.com/divinebeautyartists/
The Cake Bar	Cake	214 E 13th Ave	Denver	Colorado		Plant-based Denver bakery making wedding cakes with no eggs or dairy butter, and a mobile cake bar service for events.	team@thecakebardenver.com	303-568-9752	https://thecakebardenver.com	https://www.instagram.com/thecakebardenver/
Flick of the Whisk Cakes	Cake		Denver	Colorado		Colorado wedding cake baker creating sleek, minimalist cakes with a timeless look, a subtle edge and refined flavours.	flickofthewhiskcakes@gmail.com		https://www.flickofthewhiskcakes.com	https://www.instagram.com/flickofthewhiskcakes/
CAK	Cake		Denver	Colorado	Colorado	Boutique Denver cake design studio making modern sculpted wedding cakes, donut walls and dessert displays for any guest count.			https://www.cakthebakery.com	
Clasica Films	Videography	11111 E Mississippi Ave, Suite 211	Aurora	Colorado	Denver and across Colorado	Aurora studio filming weddings and quinceaneras with an emotional, cinematic style, paired with photography and handcrafted albums.			https://www.clasicafilms.com	https://www.instagram.com/clasicafilms/
Wedding Films Co	Videography		Denver	Colorado	Denver and destination weddings	Denver videographer making cinematic, personalised wedding films, with trained second shooters and professional editing gear.			https://weddingfilmsco.com	https://www.instagram.com/weddingfilmsco/
Boxcar Photography	Videography		Denver	Colorado	Denver, Vail, Estes Park, Colorado Springs and the mountains	Denver photo and video team shooting candid, documentary-style wedding films with true-to-life colour and natural audio.			https://boxcarphotography.com	https://www.instagram.com/boxcarphotography/
Wolff Paw Video	Videography		Denver	Colorado	Denver area and beyond	Budget-friendly wedding videographer offering raw in-camera footage or edited films, with guest interviews and no overtime fees.	wolffpawvideo@gmail.com	303-744-8968	https://wolffpawvideo.com	
`,
  },
  {
    name: "Estes Park: photography, planning, florals, music, catering, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mark Creery Photography	Photography		Fort Collins	Colorado	Estes Park, Fort Collins, Denver, Boulder, Vail, Aspen, Colorado Springs and more	Fort Collins wedding and portrait photographer with over two decades behind the camera, known for candid moments and big Colorado scenery.	photos@markcreery.com	(970) 402-0618	https://www.markcreeryphotography.com/	
Annie Grace Events	Planning		Estes Park	Colorado	Estes Park, Colorado, and beyond	Estes Park coordinator offering planning and day-of coordination, vendor liaison, timeline management and calm problem-solving on the wedding day.			https://www.anniegraceevents.com/	https://www.instagram.com/anniegraceevents/
Wild Blossoms Studio	Florals		Fort Collins	Colorado	Estes Park, Denver and Boulder wedding venues	Fort Collins floral studio creating wedding flowers for Estes Park and Front Range venues, plus pressed-flower bouquet preservation and workshops.			https://wildblossomsstudio.com/	https://www.instagram.com/wildblossomsstudio/
Ampersand Family	Videography		Littleton	Colorado	Denver, Vail, Aspen, Colorado Springs, Breckenridge and Estes Park	Colorado videography team making cinematic wedding films for couples marrying in the mountains and along the Front Range.	hello@ampersandfamily.com		https://www.ampersandfamily.com/	https://www.instagram.com/ampersandfamily/
`,
  },
  {
    name: "Boulder: photography, cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
J. La Plante Photo	Photography		Boulder	Colorado	Colorado, plus destination weddings across the US and abroad	Boulder wedding photographers offering creative, non-traditional coverage of weddings, elopements and engagement sessions, including destination work.	mail@jlaplante.com	303.652.7346	https://www.jlaplante.com/	https://www.instagram.com/j.laplante.photo/
16:3 Cake Studio	Cake		Louisville	Colorado	Louisville and surrounding Colorado cities	Louisville cake studio specialising in custom buttercream wedding cakes and gourmet desserts, with delivery across the surrounding area.	info@163cakestudio.com	(720) 593-1570	https://www.163cakestudio.com/	https://www.instagram.com/16.3cakestudio/
Sugar High Cakes	Cake		Firestone	Colorado	Longmont, Firestone, Frederick, Dacono, Erie, Mead and nearby	Firestone baker handcrafting custom wedding cakes, cutting cakes and dessert spreads for couples in Longmont and the surrounding towns.	amber@sugarhighcakes.com	720-727-5555	https://sugarhighcakes.com/	https://www.instagram.com/sugarhighcakesllc/
Alchemy Creative	Videography		Boulder	Colorado	Boulder County, Colorado	Boulder County studio filming weddings and elopements alongside photography, for couples wanting stills and video from one creative team.			https://alchemycreative.net/	https://www.instagram.com/alchemy_creative/
Francis Sylvest	Videography		Boulder	Colorado	Colorado, including Aspen, Vail, Denver, Boulder and Colorado Springs	Boulder-based filmmaker and photographer shooting candid, documentary-style wedding day videography on both film and digital.	hello@francissylvest.com	+1.985.515.8671	https://francissylvest.com/	https://www.instagram.com/afsylvest/
`,
  },
  {
    name: "Fort Collins: cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Blackbird Baking Company	Cake		Fort Collins	Colorado	Fort Collins and Northern Colorado	Fort Collins bakery designing handcrafted wedding cakes from scratch, with artistic buttercream finishes and handmade sugar flowers.			https://loveblackbirdbaking.com/	https://www.instagram.com/loveblackbirdbaking/
Complete Weddings + Events Northern Colorado	Videography		Fort Collins	Colorado	Fort Collins, Loveland, Greeley, Windsor, Estes Park and Northern Colorado	Fort Collins team pairing couples with videographers who produce cinematic or documentary highlight films, with backup coverage on standby.		970.707.3024	https://www.completewedo.com/northern-colorado/	https://www.instagram.com/completenortherncolorado/
`,
  },
  {
    name: "Colorado Springs: photography, catering, cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Captured with Grace	Photography		Larkspur	Colorado	Manitou Springs, Colorado Springs, El Paso County, the Front Range and Denver	Larkspur-based photographer and videographer covering weddings, engagements and events in Manitou Springs and across the Pikes Peak region.		720-413-1046	https://capturedwithgrace.co/	
Little London Cake Shoppe	Cake		Colorado Springs	Colorado	Colorado Springs and surrounding area	Family-run Colorado Springs bakery open since 1985, making handcrafted custom cakes, including wedding cakes, to order.		719-475-2340	https://littlelondoncs.com/	
`,
  },
  {
    name: "Vail and Aspen: cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Gold Heart Weddings	Videography		Vail	Colorado	Vail, Aspen, Denver, Buena Vista, Breckenridge and beyond	Vail wedding filmmakers producing story-led films for mountain couples, and willing to travel across Colorado.	goldheartweddings@gmail.com		https://www.goldheartweddings.com/	https://www.instagram.com/goldheartweddingfilms/
`,
  },
];

export default batches;
