import type { VendorBatch } from "@/lib/vendor-batches";

// Colorado vendor batches. Every row's State is "Colorado". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Denver: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
From the Hip Photo	Photography	8842 E 47th Ave	Denver	Colorado	All of Colorado and beyond	A five-person photography team in Denver's Central Park neighbourhood with 17 years of weddings, covering Front Range and mountain venues alike.	chat@fromthehipphoto.com	720-390-5995	https://fromthehipphoto.com/	https://www.instagram.com/fromthehipphoto/
Be Boulder Photography	Photography		Boulder	Colorado	Boulder and Colorado	Eleanor Williamson's Boulder studio for weddings and elopements, mixing posed portraits with candid storytelling and openly welcoming every couple.			https://beboulderphotography.com/	https://www.instagram.com/beboulderphotography/
DGASS Photography	Photography		Denver	Colorado	Denver, Omaha and destination weddings	A Denver photo and film team of five with one editor for a consistent look, known for multi-day Indian weddings as well as elopements.			https://dgassphotography.com/	https://www.instagram.com/dgass_photography/
Molly Margaret Photography	Photography		Denver	Colorado	Colorado and worldwide	Molly shoots weddings and elopements on both film and digital, and offers video too, with a candid, documentary approach to the day.	hello@mollymargaretphotography.com		https://www.mollymargaretphotography.com/	https://www.instagram.com/mollymargaretphotos/
Sapphire Celebrations	Planning		Denver	Colorado	Denver, Aspen, Vail, Colorado Springs and throughout Colorado	A family-led planning firm working across Colorado for over 20 years, handling full planning and destination weddings in the city and the mountains.		303-617-3984	https://www.sapphirecelebrations.com/	https://www.instagram.com/sapphirecelebrations/
Pink Champagne Events	Planning		Denver	Colorado	Denver and the Colorado mountains	A Denver planning and design boutique focused on full-service destination wedding weekends in mountain towns such as Vail, Keystone and Steamboat.	events@pinkchampagneevents.com	720-872-1642	https://www.pinkchampagneevents.com/	
Cloud 9 Weddings & Papers	Planning	821 Santa Fe Dr	Denver	Colorado	Colorado	A Denver planner since 2002 with over 400 weddings behind it, offering full planning and design alongside its own custom invitation studio.	brittany@cloud9bliss.com	720-570-1168	https://cloud9bliss.com/	https://www.instagram.com/cloud9denver/
The Nouveau Romantics	Planning		Denver	Colorado	Colorado and worldwide	Elizabeth McKellar's Denver studio plans destination weddings with an architect's eye for layout and flow, taking a small number of couples.			https://thenouveauromantics.com/	https://www.instagram.com/thenouveauromantics/
Sanctuary	Florals	3138 N Milwaukee St	Denver	Colorado	Denver metro	A Denver florist with a theatre and design background, building wedding flowers around colour, movement and texture rather than set formulas.	sanctuaryflorals@gmail.com	303-435-7992	https://sanctuaryflorals.com/	https://www.instagram.com/sanctuaryfloraldenver/
Landfall Floral Co.	Florals	5505 W 20th Ave	Edgewater	Colorado	Lakewood and west Denver	A florist at Edgewater Public Market making airy, garden-style wedding flowers, with full-service, intimate and a la carte options.		720-409-3265	https://landfallfloral.com/	https://www.instagram.com/landfallfloralco/
Petals Colorado	Florals		Denver	Colorado	Denver metro and all of Colorado	A Denver wedding florist led by Lora and Courtney, designing original arrangements with couples from a free first consultation through to the day.	petalscolorado@gmail.com	720-636-4857	https://www.petalscolorado.com/	https://www.instagram.com/petalscolorado/
DJ Guy	Music		Denver	Colorado	Denver metro	A family-run Denver DJ company with decades of weddings behind it, offering DJs, MC work and online quotes for receptions across the metro.	yourdj@djguy.com	303-754-0004	https://djguy.com/	https://www.instagram.com/djguy_denver/
A Music Plus Entertainment	Music	6870 Broadway	Denver	Colorado	Throughout Colorado	A Denver entertainment agency of 30-plus years that trains its own DJs and can also book live bands, string quartets and other acts.	events@amusicplus.com	303-426-9990	https://amusicplus.com/	
Funkiphino	Music		Boulder	Colorado	Colorado and nationwide	A 13-piece Boulder funk band with a full horn section and Hammond organ, playing weddings and private events as well as public shows.			https://funkiphino.com/	
Footers Catering	Catering	6543 Wadsworth Blvd	Arvada	Colorado	Denver metro and Colorado	An Arvada caterer founded in 1981 that cooks on site at weddings and provides full event coordination for large and small receptions.		303-762-1410	https://footerscatering.com/	https://www.instagram.com/footerscatering/
Biscuits & Berries	Catering	14818 W 6th Ave	Golden	Colorado	Denver metro	A Golden caterer cooking from scratch on site at weddings, from intimate dinners to receptions of 300 or more guests.	info@biscuitsandberries.com	303-277-9677	https://www.biscuitsandberries.com/	https://www.instagram.com/biscuitsandberries/
Mountain Crust	Catering	3880 S Lowell Blvd	Denver	Colorado	Denver and beyond	Wood-fired pizza wedding catering served from a fleet of vintage trucks, with salads, seasonal starters and beer on tap; also runs its own venue.	party@mountaincrust.com	720-515-0917	https://www.mountaincrust.com/	https://www.instagram.com/mountaincrusteventvenue/
GLAM5280	Hair & Makeup		Denver	Colorado	On location throughout Colorado	A Denver on-location bridal hair and makeup team that scales to large wedding parties and favours natural, modern looks.	Hello@glam5280.com	720-341-9626	https://www.glam5280.com/	https://www.instagram.com/glam5280/
Jaded Beauty	Hair & Makeup	277 Broadway	Denver	Colorado	Colorado	A Denver salon and wedding team doing on-site bridal hair and makeup for whole wedding parties, including hair extensions.	info@jadedbeauty.com	720-295-0441	https://jadedbeauty.com/	https://www.instagram.com/jadedbeauty__/
Amy DaCosta & Co.	Hair & Makeup		Denver	Colorado	Denver and all of Colorado	A Denver collective of bridal hair and makeup artists, each trained by Amy DaCosta, working weddings from mountain lodges to city hotels.	hello@amydacosta.com		https://www.amydacosta.com/	https://www.instagram.com/amydacostaandco/
Cate Hair Makeup	Hair & Makeup		Denver	Colorado	Denver and worldwide	A Denver bridal artist with over 750 weddings who takes one booking a day and stays through the morning for veils and touch-ups.			https://catehairmakeup.com/	https://www.instagram.com/catehairmakeup/
Das Meyer Fine Pastry Chalet	Cake	13251 W 64th Ave	Arvada	Colorado		A family-run Arvada bakery since 1981, baking everything from scratch on site, with wedding cakes from traditional to modern and Saturday tastings.		303-425-5616	https://www.dasmeyerpastry.com/	https://www.instagram.com/dasmeyerpastry/
Gingerly Baked	Cake		Denver	Colorado	Colorado	A Denver wedding cake baker making everything from scratch, with careful stacking and piping, published menus and a tasting process.			https://www.gingerlybaked.com/	https://www.instagram.com/gingerly_baked/
Snarky Sweet Cake Chick	Cake		Arvada	Colorado		Nicole's Arvada cake business makes custom wedding cakes and treats, using edible image printing for detailed textures and personal designs.	cakechick@snarkysweetcakechick.com		https://www.snarkysweetcakechick.com/	https://www.instagram.com/snarkysweetcakechick/
14er Films	Videography		Denver	Colorado	Denver, Colorado Springs, Boulder and Vail	A Colorado wedding film company making cinematic films of Rocky Mountain weddings in Denver, Boulder, Colorado Springs and Vail.	14erfilms@gmail.com		https://www.14erfilms.com/	https://www.instagram.com/14erfilms/
Birch and Blush	Videography		Denver	Colorado	Denver metro and within two hours, including Fort Collins and Colorado Springs	A Denver team of wedding videographers filming unscripted, documentary-style stories set against Colorado's mountain scenery.			https://birchandblush.com/	https://www.instagram.com/birchandblush/
Veiled Rose Films	Videography		Denver	Colorado	Denver, Boulder, Estes Park and throughout Colorado	Brian Alan's Denver studio makes boutique cinematic wedding films and guarantees delivery within 12 weeks, with drone coverage available.	info@veiledrosefilms.com	720-840-5541	https://www.veiledrosefilms.com/	https://www.instagram.com/veiledrosefilms/
`,
  },
  {
    name: "Colorado Springs: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Michelle Betz Photography	Photography		Colorado Springs	Colorado	Colorado Springs, Denver, Boulder, Breckenridge and across Colorado	Wedding and elopement photographer based in Colorado Springs, with an emphasis on elegant, true-to-life images and tight timelines.		719.310.0837	https://michellebetzphotography.com	https://www.instagram.com/michellebetzphotography/
Bobak Radbin Photography	Photography		Colorado Springs	Colorado	Colorado Springs and all of Colorado	Elopement and intimate-wedding photographer who helps couples choose mountain locations and sort out permits across Colorado.			https://www.bobakradbin.com	https://www.instagram.com/bobakradbin/
Whitney Marshall Photo	Photography		Colorado Springs	Colorado	Colorado	Colorado Springs wedding photographer working in natural light with relaxed posing, also offering engagement and family sessions.			https://whitneymphoto.com	
The Paper Ring Collective	Planning		Colorado Springs	Colorado	Colorado Springs and surrounding areas	Wedding planning and day-of coordination studio in Colorado Springs, led by Tomi Erfe, focused on intimate, story-led weddings.	hello@thepaperringcollective.com		https://www.thepaperringcollective.com	https://www.instagram.com/thepaperringcollective/
Wakefield Event Co	Planning		Colorado Springs	Colorado	Colorado Springs and greater Colorado	Colorado Springs planner offering full-service, partial planning and day-of coordination, plus party planning for other celebrations.	paige.wakefieldeventco@gmail.com		https://www.wakefieldeventco.com	https://www.instagram.com/wakefieldeventco/
Flourish Event Co	Planning		Colorado Springs	Colorado	Colorado and Southern California	Colorado Springs event company coordinating weddings, from vendor introductions and timelines through to day-of management.	hello@flourisheventco.com	719-217-0992	https://flourisheventcompany.com	https://www.instagram.com/flourisheventcompany/
Kind Floral	Florals		Colorado Springs	Colorado	Colorado Springs and Colorado	Wedding florist led by designer Kristin Hay, making wild, romantic arrangements with local blooms for ceremonies and receptions.	info@kindfloral.com		https://www.kindfloral.com	https://www.instagram.com/kind_floral/
Layers of Lovely	Florals		Colorado Springs	Colorado	Colorado Springs and surrounding areas	Floral arts studio in Colorado Springs designing wedding flowers, with work at venues such as The Broadmoor and Garden of the Gods Resort.		702.281.9145	https://www.layersoflovely.com	https://www.instagram.com/layersoflovely/
Yes Dear Florals	Florals	180 Highway 67, Suite G	Woodland Park	Colorado	Woodland Park, Teller County and the Front Range	Woodland Park florist with a shop and studio doing wedding and elopement flowers as well as event design across the Front Range.		719-374-6370	https://yesdearflorals.com	https://www.instagram.com/yesdearflorals/
Springs Sounds Entertainment	Music		Colorado Springs	Colorado		Colorado Springs DJ and entertainment team with professional sound and lighting, playing across many genres at weddings.		(719) 232-6038	https://www.springssounds.com	https://www.instagram.com/springssounds/
Warren Entertainment	Music		Colorado Springs	Colorado	Colorado Springs and Monument	Family-run DJ company in Colorado Springs offering disc jockey, lighting and photo booth services for weddings and celebrations.			https://www.coloradospringsdj.com	
HEPS DJ & Photo Booth	Music		Colorado Springs	Colorado	Colorado Springs, Denver, Fort Collins, Pueblo, Estes Park and Silverthorne	DJ service led by Brian Hepperle since 2011, adding photo booth hire, lighting and audio guestbooks to wedding receptions.			https://www.hepsdj.com	https://www.instagram.com/hepsdj/
Latimer's Kitchen & Catering	Catering		Colorado Springs	Colorado	Colorado Springs, Monument, Woodland Park, Manitou Springs and Fountain	Colorado Springs caterer with over 15 years of wedding work, known for barbecue, seafood and its own dessert line, with full service.	info@latskitchen.com	(719) 339-6400	https://latskitchen.com	https://www.instagram.com/lats_kitchen/
The Catering Collective	Catering	1701 S 8th Street	Colorado Springs	Colorado	Colorado Springs and the Front Range	Family of catering brands including Picnic Basket and Buffalo Gals, serving weddings in Colorado Springs since 1989.	info@pbcatering.com	(719) 635-0200	https://www.pbcatering.com	
El Chapin Food Truck	Catering	1228 E Fillmore St	Colorado Springs	Colorado	Colorado Springs and surrounding neighbourhoods	Colorado Springs taco and burger truck with a fixed Fillmore Street location, booked for events and late-night wedding snacks.		(719) 209-0996	https://www.elchapinfoodtruck.com	
THE DAY Hair & Makeup	Hair & Makeup	3404 W Colorado Avenue	Colorado Springs	Colorado	Colorado Springs, Denver and surrounding regions	Team of licensed hairstylists and makeup artists in Colorado Springs, travelling on location to wedding parties along the Front Range.	info@thedaycolorado.com	719-433-5530	https://www.thedaycolorado.com	https://www.instagram.com/the_day_colorado/
Ally's Beauty Bar	Hair & Makeup		Colorado Springs	Colorado	Colorado Springs, with travel available	Boho-leaning bridal hair and makeup team led by licensed cosmetologist Allyssa LeFevre, offering looks from natural to full glam.	allysbeautybar7@gmail.com		https://www.allysbeautybar.com	https://www.instagram.com/allysbeautybar7/
Brook Mae Hairstyling	Hair & Makeup		Colorado Springs	Colorado	Colorado Springs, Monument and Castle Rock	On-location bridal hairstylist known for soft, undone, romantic styles, also teaching business skills to other stylists.			https://brookmaehairstyling.com	
Peak Cake Co	Cake		Colorado Springs	Colorado	Colorado Springs, Monument, Falcon, Black Forest, Fountain and Manitou Springs	Veteran-owned bakery making European buttercream wedding cakes in a clean, modern style with scratch-made fillings.	orders@peakcakeco.com	(719) 900-1007	https://peakcakeco.com	
Mountain Bliss Cakery	Cake	4801 Eddleman Ct	Colorado Springs	Colorado	Colorado Springs and surrounding areas	Veteran-owned custom cake bakery seeing clients by appointment, making wedding cakes with handcrafted sugar flowers and metallic details.	mountainblisscakery@gmail.com	(719) 960-6795	https://mountainblisscakery.com	https://www.instagram.com/mountain_bliss_cakery/
The Sugarplum Cake Shoppe	Cake	412 S 8th St	Colorado Springs	Colorado	Colorado Springs area	Downtown Colorado Springs bakery making custom wedding cakes, cupcakes and dessert tables, with a retail counter open Tuesday to Saturday.		(719) 930-3343	https://www.sugarplumcakeshoppe.com	https://www.instagram.com/thesugarplumcakeshoppe/
J Angel Visuals	Videography		Colorado Springs	Colorado	Colorado, including Colorado Springs, Denver, Vail, Aspen and Breckenridge	Wedding filmmaker Jordan Angel, shooting cinematic films on cinema cameras with highlight and full-length options, based in Colorado Springs.		(719) 360-3945	https://www.jangelvisuals.com	https://www.instagram.com/jangelvisuals/
Films About Love	Videography		Colorado Springs	Colorado	Colorado Springs, Denver, Boulder, Vail, Aspen and Telluride	Colorado Springs wedding videographers making story-led films for mountain weddings, with social cuts for couples as well.	michael@filmsaboutlove.com	(719) 237-5159	https://www.filmsaboutlove.com	https://www.instagram.com/filmsaboutlove/
Matt Cress Media	Videography		Colorado Springs	Colorado	Colorado Springs area and limited Denver coverage	Colorado Springs photographer and videographer offering calm, documentary-style wedding coverage with 4K highlight films.	MattcressMEDIA@gmail.com	(719) 663-2930	https://www.mattcressmedia.com	https://www.instagram.com/mattcressmedia1/
`,
  },
];

export default batches;
