import type { VendorBatch } from "@/lib/vendor-batches";

// Colorado vendor batches. Every row's State is "Colorado". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Denver: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
From the Hip Photo	Photography	8842 E 47th Ave	Denver	Colorado	All of Colorado and beyond	A five-person photography team in Denver's Central Park neighbourhood with 17 years of weddings, covering Front Range and mountain venues alike.	chat@fromthehipphoto.com	720-390-5995	https://fromthehipphoto.com/	https://www.instagram.com/fromthehipphoto/
Be Boulder Photography	Photography		Boulder	Colorado	Boulder and Colorado	Eleanor Williamson's Boulder studio for weddings and elopements, mixing posed portraits with candid storytelling and openly welcoming every couple.			https://beboulderphotography.com/	https://www.instagram.com/beboulderphotography/
DGASS Photography	Photography		Denver	Colorado	Denver, Omaha and destination weddings	A Denver photo and film team of five with one editor for a consistent look, known for multi-day Indian weddings as well as elopements.			https://dgassphotography.com/	https://www.instagram.com/dgass_photography/
Molly Margaret Photography	Photography		Denver	Colorado	Colorado and worldwide	Molly shoots weddings and elopements on both film and digital, and offers video too, with a candid, documentary approach to the day.	hello@mollymargaretphotography.com		https://www.mollymargaretphotography.com/	https://www.instagram.com/mollymargaretphotos/
Sapphire Celebrations	Planning		Denver	Colorado	Denver, Aspen, Vail, Colorado Springs and throughout Colorado	A family-led planning firm working across Colorado for over 20 years, handling full planning and destination weddings in the city and the mountains.		303-617-3984	https://www.sapphirecelebrations.com/	https://www.instagram.com/sapphirecelebrations/
Pink Champagne Events	Planning		Denver	Colorado	Denver and the Colorado mountains	A Denver planning and design boutique focused on full-service destination wedding weekends in mountain towns such as Vail, Keystone and Steamboat.	events@pinkchampagneevents.com	720-872-1642	https://www.pinkchampagneevents.com/	
Cloud 9 Weddings & Papers	Planning	821 Santa Fe Dr	Denver	Colorado	Colorado	A Denver planner since 2002 with over 400 weddings behind it, offering full planning and design alongside its own custom invitation studio.	brittany@cloud9bliss.com	720-570-1168	https://cloud9bliss.com/	https://www.instagram.com/cloud9denver/
The Nouveau Romantics	Planning		Denver	Colorado	Colorado and worldwide	Elizabeth McKellar's Denver studio plans destination weddings with an architect's eye for layout and flow, taking a small number of couples.			https://thenouveauromantics.com/	https://www.instagram.com/thenouveauromantics/
Sanctuary	Florals	3138 N Milwaukee St	Denver	Colorado	Denver metro	A Denver florist with a theatre and design background, building wedding flowers around colour, movement and texture rather than set formulas.	sanctuaryflorals@gmail.com	303-435-7992	https://sanctuaryflorals.com/	https://www.instagram.com/sanctuaryfloraldenver/
Landfall Floral Co.	Florals	5505 W 20th Ave	Edgewater	Colorado	Lakewood and west Denver	A florist at Edgewater Public Market making airy, garden-style wedding flowers, with full-service, intimate and a la carte options.		720-409-3265	https://landfallfloral.com/	https://www.instagram.com/landfallfloralco/
Petals Colorado	Florals		Denver	Colorado	Denver metro and all of Colorado	A Denver wedding florist led by Lora and Courtney, designing original arrangements with couples from a free first consultation through to the day.	petalscolorado@gmail.com	720-636-4857	https://www.petalscolorado.com/	https://www.instagram.com/petalscolorado/
DJ Guy	Music		Denver	Colorado	Denver metro	A family-run Denver DJ company with decades of weddings behind it, offering DJs, MC work and online quotes for receptions across the metro.	yourdj@djguy.com	303-754-0004	https://djguy.com/	https://www.instagram.com/djguy_denver/
A Music Plus Entertainment	Music	6870 Broadway	Denver	Colorado	Throughout Colorado	A Denver entertainment agency of 30-plus years that trains its own DJs and can also book live bands, string quartets and other acts.	events@amusicplus.com	303-426-9990	https://amusicplus.com/	
Funkiphino	Music		Boulder	Colorado	Colorado and nationwide	A 13-piece Boulder funk band with a full horn section and Hammond organ, playing weddings and private events as well as public shows.			https://funkiphino.com/	
Footers Catering	Catering	6543 Wadsworth Blvd	Arvada	Colorado	Denver metro and Colorado	An Arvada caterer founded in 1981 that cooks on site at weddings and provides full event coordination for large and small receptions.		303-762-1410	https://footerscatering.com/	https://www.instagram.com/footerscatering/
Biscuits & Berries	Catering	14818 W 6th Ave	Golden	Colorado	Denver metro	A Golden caterer cooking from scratch on site at weddings, from intimate dinners to receptions of 300 or more guests.	info@biscuitsandberries.com	303-277-9677	https://www.biscuitsandberries.com/	https://www.instagram.com/biscuitsandberries/
Mountain Crust	Catering	3880 S Lowell Blvd	Denver	Colorado	Denver and beyond	Wood-fired pizza wedding catering served from a fleet of vintage trucks, with salads, seasonal starters and beer on tap; also runs its own venue.	party@mountaincrust.com	720-515-0917	https://www.mountaincrust.com/	https://www.instagram.com/mountaincrusteventvenue/
GLAM5280	Hair & Makeup		Denver	Colorado	On location throughout Colorado	A Denver on-location bridal hair and makeup team that scales to large wedding parties and favours natural, modern looks.	Hello@glam5280.com	720-341-9626	https://www.glam5280.com/	https://www.instagram.com/glam5280/
Jaded Beauty	Hair & Makeup	277 Broadway	Denver	Colorado	Colorado	A Denver salon and wedding team doing on-site bridal hair and makeup for whole wedding parties, including hair extensions.	info@jadedbeauty.com	720-295-0441	https://jadedbeauty.com/	https://www.instagram.com/jadedbeauty__/
Amy DaCosta & Co.	Hair & Makeup		Denver	Colorado	Denver and all of Colorado	A Denver collective of bridal hair and makeup artists, each trained by Amy DaCosta, working weddings from mountain lodges to city hotels.	hello@amydacosta.com		https://www.amydacosta.com/	https://www.instagram.com/amydacostaandco/
Cate Hair Makeup	Hair & Makeup		Denver	Colorado	Denver and worldwide	A Denver bridal artist with over 750 weddings who takes one booking a day and stays through the morning for veils and touch-ups.			https://catehairmakeup.com/	https://www.instagram.com/catehairmakeup/
Das Meyer Fine Pastry Chalet	Cake	13251 W 64th Ave	Arvada	Colorado		A family-run Arvada bakery since 1981, baking everything from scratch on site, with wedding cakes from traditional to modern and Saturday tastings.		303-425-5616	https://www.dasmeyerpastry.com/	https://www.instagram.com/dasmeyerpastry/
Gingerly Baked	Cake		Denver	Colorado	Colorado	A Denver wedding cake baker making everything from scratch, with careful stacking and piping, published menus and a tasting process.			https://www.gingerlybaked.com/	https://www.instagram.com/gingerly_baked/
Snarky Sweet Cake Chick	Cake		Arvada	Colorado		Nicole's Arvada cake business makes custom wedding cakes and treats, using edible image printing for detailed textures and personal designs.	cakechick@snarkysweetcakechick.com		https://www.snarkysweetcakechick.com/	https://www.instagram.com/snarkysweetcakechick/
14er Films	Videography		Denver	Colorado	Denver, Colorado Springs, Boulder and Vail	A Colorado wedding film company making cinematic films of Rocky Mountain weddings in Denver, Boulder, Colorado Springs and Vail.	14erfilms@gmail.com		https://www.14erfilms.com/	https://www.instagram.com/14erfilms/
Birch and Blush	Videography		Denver	Colorado	Denver metro and within two hours, including Fort Collins and Colorado Springs	A Denver team of wedding videographers filming unscripted, documentary-style stories set against Colorado's mountain scenery.			https://birchandblush.com/	https://www.instagram.com/birchandblush/
Veiled Rose Films	Videography		Denver	Colorado	Denver, Boulder, Estes Park and throughout Colorado	Brian Alan's Denver studio makes boutique cinematic wedding films and guarantees delivery within 12 weeks, with drone coverage available.	info@veiledrosefilms.com	720-840-5541	https://www.veiledrosefilms.com/	https://www.instagram.com/veiledrosefilms/
`,
  },
];

export default batches;
