import type { VendorBatch } from "@/lib/vendor-batches";

// Delaware vendor batches. Every row's State is "Delaware". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Wilmington: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Stone Weddings	Photography		Wilmington	Delaware	Travels wherever the story takes them	Husband-and-wife duo Kseni and Geoff shooting documentary-style weddings that favour candid, unposed moments over directed set-ups.		240-484-0052	https://www.stoneweddings.com/	https://www.instagram.com/stoneweddings/
Creative Image Weddings & Portraits	Photography		Wilmington	Delaware	Open to travelling anywhere	Katie's Wilmington studio photographs weddings, engagements and portraits in a bold, colourful and artistic style.	katie@cibphoto.com	302-354-7903	https://creativeimageweddings.com/	https://www.instagram.com/creativeimageweddings/
Becca Mathias Photography	Photography		Wilmington	Delaware		Documentary-style wedding photographer who lets the day unfold naturally, stepping in only for family portraits and gentle posing tips.			https://www.beccamathiasphoto.com/	https://www.instagram.com/beccamathiasphoto/
The Koordinator	Planning	254 Chapman Road	Newark	Delaware	Delaware and the tri-state area	Jasmine Walker's Newark firm offering full planning, coordination-only and consultation packages for couples across the tri-state area.		267-539-9616	https://thekoordinator.com/	
The Lovely Veil Events	Planning		Newark	Delaware	DE, MD, PA & destination	Licensed Newark planner offering full planning and styling, partial planning and month-of coordination for DE, MD and PA weddings.	hello@lovelyveilevents.com	302-803-4942	https://lovelyveilevents.com/	https://www.instagram.com/lovelyveilevents/
Heaven Sent Wedding Consultants	Planning		Newark	Delaware	Tri-state area and destination weddings	Long-running planner and travel agency handling local and destination weddings, with its own floral division and honeymoon booking.	info@heavensentweddings.com	267-334-0301	https://heavensentweddings.com/	https://www.instagram.com/heavensentweddings/
The Wilmington Florist	Florals		Wilmington	Delaware	Wilmington, Delaware and the Philadelphia region	Woman-owned North Wilmington studio designing modern garden-style wedding flowers, from courthouse elopements to large weddings.	thewilmingtonflorist@gmail.com	302-584-1365	https://www.thewilmingtonflorist.com/	https://www.instagram.com/thewilmingtonflorist/
Belak Flowers	Florals	832 Philadelphia Pike	Wilmington	Delaware	New Castle County, from Claymont to Townsend	Independent Brandywine florist since 1954, supplying bouquets, ceremony pieces and reception centrepieces with delivery and set-up.	wecare@belak-flowers.com	302-762-5000	https://www.belak-flowers.com/wedding	https://www.instagram.com/belakflowers.wilmington/
Bernette's Designs	Florals	2406 N Market Street	Wilmington	Delaware	Wilmington and surrounding areas	North Market Street flower shop offering wedding consultations, bridal party bouquets, corsages, ceremony décor and reception arrangements.		302-377-0168	https://www.bernettesdesigns.com/wedding-flowers	
Bagay Nef Weddings & Events	Music		Wilmington	Delaware	DE, PA, NJ, NY, MD, DC and surrounding regions	Multicultural DJ and MC outfit led by John Beaucejour, adding photo booths, cold sparklers and dancing-on-the-clouds effects.		302-722-5318	https://www.bagaynefweddings.com/	https://www.instagram.com/bagaynefweddingsevents/
Wired Up Entertainment	Music		Wilmington	Delaware	Delaware and beyond	Family-run Wilmington DJ collective known for packed dance floors, with photo booths, lighting and AV hire available alongside.		302-563-9092	https://www.justgetwired.com/	https://www.instagram.com/wired_up_entertainment/
Sightline Events	Music		Wilmington	Delaware	Delaware	DJ Steven Lewis builds personalised playlists for receptions and offers photo booth hire as part of combined wedding packages.	Steve@SightlineEvents.com	302-256-8277	https://sightlineevents.com/	https://www.instagram.com/sightlineevents/
Jamestown Catering Co.	Catering	2510 W 5th St	Wilmington	Delaware	Delaware, Maryland, Pennsylvania and New Jersey	Off-site caterer designing seasonal menus for weddings at unusual venues and private homes, with full-service, pickup or drop-off options.		302-510-8071	https://www.jamestowncatering.com/	https://www.instagram.com/jamestowncateringco/
Sherm's Catering	Catering	913 Brandywine Blvd	Wilmington	Delaware	New Castle County, Delaware	Catering New Castle County weddings since 2008 with homemade American food, custom or set menus and an eye on keeping costs affordable.	Sales@ShermsCatering.com	302-607-7200	https://shermscatering.com/	https://www.instagram.com/shermscatering/
Toscana Catering at Piccolina Toscana	Catering	1412 N Dupont St	Wilmington	Delaware	Delaware	Catering arm of a Wilmington Italian restaurant, serving weddings for over 30 years and a regular caterer at Hagley and the Delaware Art Museum.		302-654-8877	https://piccolinatoscana.com/catering	
JNP Beauty	Hair & Makeup		Wilmington	Delaware	Based in Delaware, travels worldwide	Jesie leads a Wilmington bridal hair and makeup team known for light, long-wearing glam that never feels heavy on the skin.			https://www.jnpbeauty.com/	https://www.instagram.com/jnpbeauty/
LOKA Beauty Studio	Hair & Makeup	3222 Avenue North Boulevard	Wilmington	Delaware	Wilmington, Delaware	Avenue North salon and spa with a 25-strong team covering bridal hair, makeup, lashes and skin, including trials and on-site wedding mornings.	book-now@lc.lokabeautystudio.com	302-600-1538	https://lokabeautystudio.com/services-overview/beauty-services/wedding-services/	https://www.instagram.com/lokabeautystudio/
Styled By Jaide	Hair & Makeup	93 Clinton St	Delaware City	Delaware	Northern Delaware, Elkton MD and Chester County PA	Bilingual makeup and hair artist working from Honey Salon, bringing bridal and quinceañera looks to venues and hotels, trials included.	info@styledbyjaide.com	302-499-3729	https://styledbyjaide.com/	https://www.instagram.com/styled_by_jaide/
Desserts by Dana	Cake	1212 Capitol Trail	Newark	Delaware	Newark and New Castle, with delivery	Two-shop Delaware bakery offering wedding cake tastings, a wide choice of custom designs, and delivery and set-up at the venue.	cakes@dessertsbydana.com	302-721-5798	https://dessertsbydana.com/	https://www.instagram.com/dessertsbydana/
Sweet Melissa Bakery	Cake	5407 Peterson Road	Middletown	Delaware		Middletown bakery and coffee shop making buttercream and fondant wedding cakes, voted Best Wedding Cakes upstate in Best of Delaware 2026.	melissa@sweetmelissade.com		https://sweetmelissade.com/custom-cakes/	https://www.instagram.com/sweetmelissade/
CupKate's Bakery	Cake	4001 Kennett Pike, Suite 134	Greenville	Delaware		Greenville cake shop baking one-off, personalised wedding cakes from scratch, alongside cupcakes, cookies and macarons for dessert tables.		302-256-0819	https://www.cupkatescakes.com/	https://www.instagram.com/cupkatescakebakery/
DoMore Digital	Videography		Wilmington	Delaware	DE, PA, MD and NJ	Wilmington videographer blending cinematic trailer-style edits with documentary coverage of real vows, with photo-and-video bundles too.			https://www.domore.digital/wedding-videos	https://www.instagram.com/domore.digital/
Dukes Films	Videography		Seaford	Delaware	Tri-state area and destination weddings	Husband-and-wife cinematography team from southern Delaware filming weddings from the morning preparations through to the last dance.	hello@dukesfilms.com	302-569-8855	https://www.dukesfilms.com/	https://www.instagram.com/tjdukesfilms/
Video In Progress	Videography		Seaford	Delaware		Seaford studio filming story-led wedding films since 2012, from 60-second social highlights to full documentary coverage of the day.	Sales@VideoInProgress.com	888-511-4595	https://www.videoinprogress.com/weddings	`,
  },
  {
    name: "Rehoboth Beach: photography, florals, music, catering, hair & makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jordan Fern Photo	Photography		Rehoboth Beach	Delaware	Rehoboth Beach and coastal Delaware	Rehoboth Beach photographer for weddings and elopements, known for a warm, playful approach that keeps couples relaxed and laughing.			https://jordanfernphoto.com/	https://www.instagram.com/jordanfernphoto/
Josh Feeney Photography	Photography		Lewes	Delaware	Coastal Delaware and the Delmarva Peninsula	Coastal Delaware photographer covering weddings and engagements with a focus on timeless, feeling-led images, plus family portraits.			https://www.joshfeeneyphotography.com/	https://www.instagram.com/josh_feeney_photography/
DSmithImages Photography	Photography		Rehoboth Beach	Delaware	Rehoboth Beach and Maryland's Eastern Shore	Rehoboth Beach photographer specialising in micro-weddings and elopements since 2010, with a cinematic, alternative eye.	dsmithimages@gmail.com		https://www.dsiphotography.com/rehoboth-beach-wedding-photography	https://www.instagram.com/dsmithimagesphotography/
Floral Inspirations	Florals	524 E Savannah Rd	Lewes	Delaware	Lewes, Rehoboth Beach, Milton and nearby	Lewes florist since 2015 with an AIFD-certified designer, making wedding flowers and hand-delivering arrangements across the beaches.	wecare@lewesflowers.com	302-703-1009	https://www.lewesflowers.com/	https://www.instagram.com/floral.inspirations/
Cowger Entertainment Group	Music		Rehoboth Beach	Delaware	Delaware, Maryland and Virginia	Rehoboth Beach DJ company licensed in three states, offering wedding DJ and MC services with event lighting and photo booths.		443-783-9175	https://cowgerentertainment.com/	https://www.instagram.com/cowgerentertainment/
Jimmy's Grille Catering	Catering	113 Dickinson Ave	Dewey Beach	Delaware	Delaware and nearby Maryland communities	Dewey Beach caterer doing buffet-style wedding menus for 50 to 5,000 guests, with hors d'oeuvres and drinks in an all-inclusive package.	ron@jimmysgrillecatering.com	302-337-8868	https://www.jimmysgrillecatering.com/	
Beach House Pantry	Catering		Lewes	Delaware	Lewes, Rehoboth, Dewey, Bethany and Fenwick Island	Personal chef and caterer for the Delaware beaches, offering seafood bakes, grazing boards and event planning for weddings and parties.	heather@beachhousepantry.com	302-841-5253	https://www.beachhousepantry.com/	
The Art of Beauty	Hair & Makeup		Milford	Delaware	Delaware, Pennsylvania, Maryland, New Jersey, DC and Virginia	Milford bridal hair and makeup team travelling to weddings, with a luxury, soft-glam approach built for every skin tone and hair texture.			https://theartofbeauty.net/	https://www.instagram.com/theartofbeautyyyy/
Carolina Sugar Fairy	Cake		Rehoboth Beach	Delaware	Lewes, Rehoboth Beach, Dewey Beach, Bethany Beach, Milton and Millsboro	Southern Delaware baker making custom wedding and large-event cakes, dessert tables and decorated cookies from quality ingredients.			http://www.carolinasugarfairy.com/	
Crumb One Crumb All	Cake		Lewes	Delaware	Lewes and Sussex County	Lewes bakery making gluten-free and traditional custom cakes, cupcakes and pastries to order, with care taken to avoid cross-contamination.	CrumbOneCrumbAllBakery@Gmail.com	302-542-5445	https://crumbonecrumball.com/	`,
  },
];

export default batches;
