import type { VendorBatch } from "@/lib/vendor-batches";

// Georgia vendor batches. Every row's State is "Georgia". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Atlanta: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Audrey Grace Photography	Photography		Atlanta	Georgia		Fine art wedding and portrait photographer with 14 years behind the camera, aiming for timeless, joyful images over passing trends.			https://audreygracephoto.com/	https://www.instagram.com/audreygracephoto/
Amanda Summerlin Photography	Photography		Atlanta	Georgia	Atlanta, the Southeast and travel across the US	LGBTQ+-owned studio photographing creative, documentary-style weddings since 2009, including more than 100 queer weddings.			https://amandasummerlin.com/	
Sarah Folsom Photography	Photography		Atlanta	Georgia		Wedding photographer blending polished portraits with candid moments, covering everything from the small details to the dance floor.			https://sarahfolsomphotography.com/	https://www.instagram.com/sarahfolsomphoto/
Pop + Fizz	Planning		Atlanta	Georgia	Atlanta, across the US and destination weddings	Team of four planners offering full planning, design and coordination for style-led weddings in Atlanta and further afield.			https://popandfizz.com/	
Tinted Events	Planning		Atlanta	Georgia	Atlanta and destination weddings nationwide	Latina-owned planning and design studio led by Jax, creating bespoke full-service weddings in Atlanta and beyond.			https://tintedevents.com/	https://www.instagram.com/tintedevents/
Red & Gold Events	Planning		Atlanta	Georgia	Metro Atlanta, the Southeast and international destinations	Planning team specialising in Indian, Pakistani, South Asian and fusion weddings, from vendor contracts to multi-day timelines.	info@redandgold-events.com	(404) 445-4498	https://www.redandgold-events.com/	https://www.instagram.com/redandgoldevents/
Wedded Details	Planning		Atlanta	Georgia	Fulton, Gwinnett, Cobb, DeKalb, Cherokee and Forsyth counties	Flat-fee day-of and month-of coordination for metro Atlanta weddings, led by a planner with more than 15 years of experience.			https://www.weddedetails.com/	https://www.instagram.com/weddedetails/
Faith Flowers	Florals	1183 Virginia Ave NE	Atlanta	Georgia		Appointment-only Virginia-Highland studio designing wedding flowers and décor, which also runs flower classes and floral tours abroad.		(404) 922-8298	https://faithflowers.com/	https://www.instagram.com/faithflowersatl/
Le Jardin Français	Florals	1465 Howell Mill Rd NW, Suite 100C	Atlanta	Georgia		French-inspired floral and garden design firm with a Westside atelier and boutique, creating flowers for weddings and events.	info@lejardinfrancais.com	(404) 792-1680	https://lejardinfrancais.com/	
Each Day Florals	Florals		Atlanta	Georgia	Atlanta and the Southeast	Upper Westside studio led by designer Amy, making organic, elevated arrangements for weddings at venues across Georgia.	eachdayflorals@gmail.com	(216) 402-6826	https://eachdayflorals.com/	https://www.instagram.com/eachdayflorals/
D Street Entertainment	Music		Marietta	Georgia	Marietta, Atlanta and Kennesaw	DJ company pairing a DJ with a separate MC for an interactive two-person show, with more than 1,000 events played since 2001.	info@dstreetent.com	(404) 578-2655	https://www.dstreetentertainment.com/	https://www.instagram.com/dstreetent/
Lumina String Ensemble	Music		Atlanta	Georgia	Greater metro Atlanta and throughout Georgia	Violinist-led duo, trio and quartet for ceremonies and cocktail hours, drawing on a 235-song repertoire and custom arrangements.	luminastringensemble@gmail.com	(470) 588-2839	https://www.luminastringensemble.com/	https://www.instagram.com/luminastringensemble/
Elite Strings	Music		Atlanta	Georgia	Atlanta and surrounding areas	String duos, trios and quartets founded by a cellist and a violinist, with amplification packages for receptions as well as ceremonies.	info@elite-strings.com		https://elitestrings.com/	https://www.instagram.com/elitestringsatlanta/
Figs & Honey Catering	Catering	2911 Pharr Ct South NW	Atlanta	Georgia	Metro Atlanta	Scratch-made, chef-prepared catering for weddings and private events, offering drop-off menus as well as fully staffed service.	info@figsandhoneycatering.com	(404) 745-9561	https://www.figsandhoneycatering.com/	
Talk of the Town Catering	Catering	2469 Canton Rd	Marietta	Georgia	Metro Atlanta and North Georgia	Cobb County caterer led by executive chef Andrew Brackner, providing gourmet menus and full service staff for weddings.	andrew@tottatl.com	(404) 334-4935	https://talkofthetownatlanta.com/	
Dogwood Catering Company	Catering	4961 Lower Roswell Rd	Marietta	Georgia	Marietta and greater Atlanta	Upscale Southern catering for full-service weddings, corporate events and film and TV productions across metro Atlanta.	info@dogwoodcatering.com	(404) 914-6770	https://dogwoodcatering.com/	https://www.instagram.com/dogwoodcatering/
Eva Christine's Sweets	Cake		Atlanta	Georgia		Luxury wedding cake studio making bespoke, sculptural cakes with layered flavours, plus custom desserts for celebrations.	sweets@evachristinessweets.com	(404) 692-7075	https://www.evachristinessweets.com/	https://www.instagram.com/evachristinessweets/
Frosted Pumpkin Wedding Cakes	Cake		Atlanta	Georgia	Atlanta area	Handcrafted wedding cakes for metro Atlanta couples, designed through personal consultations on style and flavour.			https://frostedpumpkin.com/	https://www.instagram.com/frostedpumpkincakes/
Platinum Cake Designs	Cake		Decatur	Georgia	Atlanta metro area	Private Decatur cake studio run by chef Nevia Giles, creating original custom wedding cakes rather than copied designs.	info@platinumcakedesigns.com	(678) 487-9797	https://www.platinumcakedesigns.com/	https://www.instagram.com/_platinumcakedesigns/
Virginia Marie Cake Boutique	Cake	5160 Erin Rd	Atlanta	Georgia	Georgia, Alabama, Tennessee, Mississippi and Florida	Appointment-only cake boutique offering custom wedding cakes with tastings, delivering across Georgia and neighbouring states.	info@virginiamarie.com	(404) 996-2617	https://www.virginiamarie.com/	https://www.instagram.com/virginiamariecakes/
Vigilante Makeup + Hair Artistry	Hair & Makeup	4463 Cherokee St, Suite 100	Acworth	Georgia	Atlanta and Chattanooga areas	On-location and destination bridal hair and makeup team founded by Erica Ages in 2014, working from a studio in Acworth.	info@vigilantecosmetics.com	(404) 402-0486	https://vigilantecosmetics.com/	https://www.instagram.com/vigilantecosmetics/
Brushworx	Hair & Makeup	9165 Martin Rd	Roswell	Georgia	Georgia, the Carolinas, Tennessee and Alabama	On-location bridal hair and makeup team founded in 2006, with studios in Roswell and Snellville and grooming for grooms.			https://www.brushworx.net/	
B For Beaute	Hair & Makeup		Atlanta	Georgia	Atlanta, DC and beyond	Bridal makeup artist specialising in women of colour, with hair from a partner stylist for combined hair and makeup packages.	info@bforbeaute.co		https://bforbeaute.co/	https://www.instagram.com/bforbeaute.co/
Claudia Goodwin Films	Videography		Atlanta	Georgia	Atlanta and destination weddings worldwide	Wedding filmmaker since 2019 making emotional, timeless films across Georgia and at destinations from Venice to New York.	claudiagoodwinfilms@gmail.com	(404) 405-0661	https://claudiagoodwinfilms.com/	https://www.instagram.com/claudiagoodwinfilms/
Vitor Lindo	Videography		Atlanta	Georgia	Atlanta, Georgia and travel nationwide	Wedding videographer and photographer with more than 450 weddings filmed, experienced in Indian and multi-day celebrations.			https://vitor-lindo.com/	https://www.instagram.com/vitorlindophotovideo/
KJB Studios	Videography		Atlanta	Georgia	Atlanta and worldwide	Photo and video studio led by Kendrick, filming weddings as unstaged storytelling with an editorial, art-led eye.	kjbstudios.info@gmail.com		https://kjbstudios.com/	https://www.instagram.com/k.j.bstudios/
`,
  },
  {
    name: "Savannah: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
State of Grace Studios	Photography		Savannah	Georgia		Husband-and-wife team photographing and filming weddings, engagements and elopements, with drone coverage on offer for aerial views.	stateofgracestudios@gmail.com	(912) 429-4778	https://stateofgracestudios.com/	https://www.instagram.com/stateofgracestudios/
Jeff & Mollie	Photography		Savannah	Georgia		Documentary husband-and-wife duo shooting weddings together since 2009, covering both photography and video from a single team.		(912) 224-7717	https://www.jeffandmollie.com/	https://www.instagram.com/jeffandmollie/
Meredith Ryncarz	Photography		Savannah	Georgia	Savannah and destination weddings worldwide	Classic, heirloom-minded wedding photography from a Savannah photographer who also travels for destination weddings, backed by a small team.	info@meredithryncarz.com	(912) 910-1040	https://meredithryncarz.com/	https://www.instagram.com/meredithryncarz/
Coastal Chic Studios	Photography		Savannah	Georgia	Savannah and the Southeast	Husband-and-wife photographers Todd and Angela, specialising in fine-art wedding and couples portraits, plus proposal shoots for visitors.			https://coastalchicstudios.com/	https://www.instagram.com/coastalchicstudios/
Tara Skinner Events	Planning		Savannah	Georgia	Savannah, the coast and destination weddings	Destination wedding planning and design firm offering full-service planning for timeless luxury weddings in Savannah and further afield.			https://taraskinnerevents.com/	https://www.instagram.com/taraskinnerevents/
Elegant Savannah Weddings	Planning		Savannah	Georgia		Planning team offering full planning, coordination and design packages for Savannah weddings, with a clear step-by-step process for couples.	info@elegantsavannahweddings.com	(912) 531-0993	https://www.elegantsavannahweddings.com/	https://www.instagram.com/elegantsavannahweddings/
Sincerely Yours Events	Planning		Savannah	Georgia	Savannah, the Lowcountry and beyond	Wedding planning company helping couples shape and carry out their vision across Savannah and the Lowcountry, from first ideas to the day itself.	hello@sincerelyyoursevents.com		https://www.sincerelyyoursevents.com/	https://www.instagram.com/sincerely.yours.events/
A to Zinnias	Florals	217 East Broad Street	Savannah	Georgia	Savannah and the Lowcountry	Downtown florist working since 1999, with weddings at its roots and thousands designed across the Lowcountry's historic venues and landscapes.	info@atozinnias.com	(912) 234-3400	https://www.atozinnias.com/	https://www.instagram.com/atozinnias/
Kato Floral Designs	Florals	127 Abercorn Street, Suite 207	Savannah	Georgia	Savannah, Hilton Head and the Golden Isles	Award-winning wedding and event florist with a studio on Oglethorpe Square, designing custom florals for intimate and destination celebrations.	hello@katoweddings.com	(912) 508-1166	https://katoweddings.com/	https://www.instagram.com/katofloraldesigns/
Urban Poppy	Florals	3125 Bull Street	Savannah	Georgia		Ardsley Park flower shop and studio running an à la carte luxury wedding floral programme, alongside a flower bar, workshops and gifts.	margaret.urbanpoppy@gmail.com	(912) 482-1713	https://urbanpoppy.com/	https://www.instagram.com/urbanpoppyshop/
Sweetfield Flowers	Florals		Savannah	Georgia		A fifth-generation Savannahian's studio creating lush, layered wedding florals from local farm stems, each piece designed rather than repeated.	sweetfieldflowers@gmail.com		https://www.sweetfieldflowers.com/	https://www.instagram.com/sweetfieldflowers/
Versamix Music	Music		Savannah	Georgia	Savannah, Hilton Head and the Coastal Empire	Luxury wedding DJ service led by Savannah DJ César Almodóvar, pairing curated sets with lighting and sound for weddings and galas.	versamixmusic@yahoo.com		https://www.versamixmusic.com/	https://www.instagram.com/versamix_music/
All About You Entertainment	Music	404 East Oglethorpe Ave	Savannah	Georgia		Savannah DJ company providing wedding DJs and MCs, with uplighting, photo booths and silent disco kit available to add on.		(912) 897-0518	https://allaboutyoudjs.com/	https://www.instagram.com/allaboutyouentertainment/
J&M Sound Productions	Music		Richmond Hill	Georgia	Savannah, Hilton Head, Jekyll Island, Statesboro and surrounding areas	Locally owned DJ company founded in 2001 by DJ Johnny C, bringing over 20 years of wedding experience and its own sound equipment.		(912) 308-0751	https://www.jmsoundproductions.com/	
Logan Thomas Music	Music		Savannah	Georgia		Singing guitarist, DJ and MC in one, offering live acoustic music and DJ sets for weddings and upscale events around Savannah.	logan@loganthomasmusic.com		https://www.loganthomasmusic.com/	https://www.instagram.com/loganthomasmusic/
Thrive Catering	Catering	2700 Gregory St, Suite 200	Savannah	Georgia		Award-winning Savannah caterer handling weddings, social events and corporate functions, with rentals and a list of favourite venues.	thrivecatering@gmail.com	(912) 508-6068	https://cateringbythrive.com/	https://www.instagram.com/thrivecateringsav/
B Local Catering	Catering	1000 Eisenhower Drive, Suite E	Savannah	Georgia		Wedding caterer that designs menus around each couple's vision and budget, from pasta bars to full receptions and rehearsal dinners.		(912) 247-8839	https://www.blocalcateringsav.com/	https://www.instagram.com/blocalcateringsav/
Magnolia Grill Catering	Catering	3881 Hwy 17	Richmond Hill	Georgia	Savannah area	Wife-and-husband team catering since 1999, serving buffets, plated, family-style and stations, plus bar service and Lowcountry boils.	sales@magnoliagrillcatering.com	(912) 756-3663	https://magnoliagrillcatering.com/	
Savannah Event Catering	Catering	1109 South Rogers Street	Pooler	Georgia	Savannah and the Lowcountry	Chef-led caterer serving Savannah and the Lowcountry since 2008, building custom wedding menus around each couple's tastes and traditions.	events@savannaheventcatering.com	(912) 660-7533	https://savannaheventcatering.com/	https://www.instagram.com/savannaheventcatering_/
Wonderland Beauty Bar	Hair & Makeup	7370 Hodgson Memorial Dr	Savannah	Georgia	Savannah and beyond (travel fee outside Savannah)	Mobile bridal hair and makeup team led by licensed stylist and cosmetology instructor Wanda, travelling to venues around Savannah and beyond.	wanda@wonderlandbeautybar.com	(912) 323-9282	https://wonderlandbeautybar.com/	https://www.instagram.com/wonderlandbeauty_bar/
LANÉ Makeup Artistry	Hair & Makeup		Savannah	Georgia		Brandi Lane's Savannah makeup service specialising in soft-glam bridal and elopement looks, drawing on a background in television makeup.	lanemakeupartistry@gmail.com		https://lanemakeupartistry.com/	https://www.instagram.com/lane_makeupartistry/
Beyond Beautiful by Heather	Hair & Makeup		Savannah	Georgia		Licensed on-location makeup and hair artist Heather Ferguson, styling brides, bridal parties and elopements around Savannah.	heatherjferguson@hotmail.com	(912) 713-7039	https://www.beyondbeautifulbyheather.com/	https://www.instagram.com/beyondbeautifulbyheather/
Wicked Cakes of Savannah	Cake	466 Montgomery Street	Savannah	Georgia		Downtown bakery making wedding and groom's cakes to order for pick-up or delivery, alongside custom cakes and cake-decorating classes.	wickedcakesofsavannah@gmail.com	(912) 298-0040	https://www.wickedcakesofsavannah.com/	https://www.instagram.com/wickedcakesofsavannah/
Baker's Pride Bakery	Cake	840 E. DeRenne Ave	Savannah	Georgia		Family bakery serving Savannah since 1982, making wedding and groom's cakes alongside cakes, cheesecakes and pies for every occasion.		(912) 355-1155	https://www.savannahbakery.com/	https://www.instagram.com/bakers_pride_bakery/
Coastal Confections	Cake		Richmond Hill	Georgia	Richmond Hill, Savannah, Tybee Island, St Simons Island and surrounding areas	Appointment-only custom cake shop opened in 2013 by a certified chef, making wedding and groom's cakes as well as sugar and chocolate art.	coastalconfections2013@gmail.com		https://www.coastalconfections.net/	
Flirt With Dessert	Cake		Wilmington Island	Georgia	Savannah and surrounding areas	Mother-daughter boutique bakery making custom wedding cakes, with gluten-free, eggless, dairy-free and vegan options on request.	ashley@flirtwithdessert.com	(912) 661-2662	https://flirtwithdessert.com/	https://www.instagram.com/flirtwithdessertbakery/
Ardsley Park Productions	Videography		Savannah	Georgia	Savannah and travelling everywhere	Cinematic wedding films from a Savannah studio that travels anywhere, with full-length films from venues such as Hotel Bardo and Forsyth Park.	ardsleyparkproductions@gmail.com		https://www.ardsleyparkproductions.com/	https://www.instagram.com/ardsleyparkproductions/
Square City Productions	Videography		Savannah	Georgia		Savannah video team making wedding films on 4K cinema cameras, with drone footage in highlight films and delivery in a digital album.			https://squarecityproductions.com/	https://www.instagram.com/squarecityproductions/
`,
  },
  {
    name: "Savannah: videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Savannah Wedding Films	Videography		Savannah	Georgia	Savannah, Charleston, Hilton Head and beyond	Savannah studio led by filmmaker Trevor Jenkins, making handcrafted wedding videos and photos for Lowcountry and coastal Georgia couples.	savannahweddingfilms@gmail.com		https://www.savannahweddingfilms.com/	https://www.instagram.com/savannahweddingfilms/
`,
  },
  {
    name: "Athens: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Claire Diana Photography	Photography		Athens	Georgia	Athens, Atlanta and beyond	Full-time Athens photographer, formerly shooting UGA football for the local paper, who covers weddings alongside senior and boudoir portraits.			https://clairedianaphotography.com/	https://www.instagram.com/claire_diana/
Blane Marable Photography	Photography		Athens	Georgia	Athens and Atlanta	Long-running Athens wedding photographer covering engagements, bridal portraits and the wedding day itself across Athens and Atlanta.			https://www.blanemarable.com/	
Jackson & June Events	Planning		Athens	Georgia	Athens and Atlanta	Planning studio offering full, partial and month-of coordination, with a soft spot for walkable downtown Athens wedding weekends.			https://jacksonandjune.com/athens-weddings	https://www.instagram.com/jacksonandjuneevents/
Brett Glenn Floral Design	Florals	1054 S Lumpkin St	Athens	Georgia	Athens and Oconee County	Full-service florist on South Lumpkin Street designing flowers for weddings, corporate events and social gatherings around Athens.		706-227-9937	https://www.brettglenn.com/	
Flowerland	Florals	823 Prince Ave	Athens	Georgia		Prince Avenue flower shop making bridal bouquets, centrepieces, head-table garlands and floral arches in styles from cascading to modern.	flowerlandathens@gmail.com	(706) 549-1884	https://www.flowerlandathensga.com/wedding-flowers	
Classic City Confections	Cake		Athens	Georgia	Athens and Northeast Georgia	Athens wedding cake maker offering buttercream and fondant tiers priced per serving, plus a range of dessert-table sweets by consultation.	classiccityconfections@gmail.com		https://classiccityconfections.com/	
Sound Insight	Music		Athens	Georgia	Athens and Atlanta	DJ company for Athens and Atlanta weddings that also handles ceremony sound, with wireless mics for officiants and readers.	events@soundinsightdj.com	706-927-5261	https://www.soundinsightdj.com/weddings	https://www.instagram.com/soundinsightpro/
Nightbird	Music		Athens	Georgia	Atlanta, Athens and North Georgia	DJ and photo booth crew, formerly Athens DJ Service, that assigns your DJ 90 days out and joins two planning calls before the day.	info@nightbirdent.com	(706) 715-3371	https://www.nightbirdent.com/	https://www.instagram.com/nightbirdent/
Bombshell Creations	Hair & Makeup	688 S Milledge Avenue	Athens	Georgia	Athens, Atlanta, Savannah and the Southeast	On-site hair and makeup team based in Athens, styling brides, bridal parties and grooms at venues across Georgia and the Carolinas.		(706) 714-1907	https://bombshellcreations.com/	https://www.instagram.com/bombshellcreationsga/
CraigFilm	Videography		Athens	Georgia		Athens video and photo studio filming wedding days, with 360 VR coverage and live streaming for guests who can't attend in person.	info@craigfilm.com		https://craigfilm.com/	https://www.instagram.com/craigcarmean/
Trumps Catering	Catering	2026 South Milledge Avenue, Suite B	Athens	Georgia	Athens and surrounding counties	Athens caterer since 1986, grown from a neighbourhood bistro, handling receptions, rehearsal dinners and bridal luncheons.	sales@trumpscatering.com	(706) 546-1320	https://www.trumpscatering.com/	https://www.instagram.com/trumpscatering/
Epting Events	Catering	1430 N Chase St	Athens	Georgia	Athens, Atlanta and beyond	Athens-headquartered catering and event design company with decades of experience, also catering weddings in Atlanta.	info@eptingevents.com	706.353.1913	https://www.eptingevents.com/	https://www.instagram.com/eptingevents/
`,
  },
  {
    name: "North Georgia Mountains: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
River Underwood Photography	Photography		Blue Ridge	Georgia	Blue Ridge, Blairsville, Ellijay and the North Georgia mountains	Blue Ridge photographer covering weddings and events as well as family portraits and real estate around the mountain towns.	sales@riverunderwoodphotography.com	706-455-6736	https://www.riverunderwoodphotography.com/	https://www.instagram.com/riverunderwoodphotography/
Appalachian Wedding Photography	Photography		Blue Ridge	Georgia	Blue Ridge and travel	Blue Ridge wedding and elopement photographer Emilie Gates, documenting mountain weddings with a Leave No Trace approach to outdoor shoots.	info@appalachianweddingphotography.com		https://appalachianweddingphotography.com/	https://www.instagram.com/appalachianweddingphotography/
Unique Events	Planning		Blairsville	Georgia	Blue Ridge, Blairsville and the North Georgia mountains	Blairsville planning and design firm led by Andrea, coordinating mountain weddings and connecting couples with trusted local vendors.	andrea.uniqueevents@gmail.com	706.851.9106	https://www.uniqueevents.org/	https://www.instagram.com/uniqueeventsbyandrea/
Ever Weddings	Planning		Talking Rock	Georgia	North Georgia, from Dahlonega to Chattanooga	Day-of coordinator Michelle, based in Talking Rock, running wedding timelines and vendors for couples marrying across the North Georgia mountains.			https://everweddings.com/	https://www.instagram.com/everweddings/
North Georgia Weddings & Events	Music		Commerce	Georgia	North Georgia and Atlanta	DJ and MC company covering Blue Ridge, Dahlonega and other mountain venues, with lighting and photo booth hire alongside the music.	info@northgeorgiaweddingsandevents.com	(706) 383-9883	https://www.northgeorgiaweddingsandevents.com/	https://www.instagram.com/northgeorgiaweddingsandevents/
Smith House Catering	Catering	84 South Chestatee St	Dahlonega	Georgia	Dahlonega and nearby venues	Off-site catering from Dahlonega's long-running Smith House restaurant, whose staff deliver Southern dishes and set up the buffet on site.	info@smithhouse.com	706.725.8330	https://smithhouse.com/cater-to-location/	
Styles by Sydney	Hair & Makeup		Dawsonville	Georgia	All of Georgia and destination weddings	Dawsonville-based stylist offering on-site bridal hair and makeup for weddings in North Georgia, Atlanta and further afield.	info@stylesbysydney.com	512-738-7097	https://stylesbysydney.com/	
Jamie Bakes	Cake		Dahlonega	Georgia	North Georgia wedding venues	Boutique cakery in Dahlonega making wedding cakes, and a preferred vendor at a number of North Georgia mountain venues.	jamiebakes706@gmail.com		https://www.jamiebakes.net/	https://www.instagram.com/jamiebakes706/
Sherry's Sweets-n-Eats	Cake		Dahlonega	Georgia		Licensed cottage bakery in Dahlonega making custom celebration and wedding cakes to order for North Georgia couples.			https://www.sherryssweetsneats.com/	https://www.instagram.com/sherrys.sweetsn.eats/
Grant Media	Videography		Dahlonega	Georgia		Dahlonega video production company with more than 15 years behind the camera, filming weddings and events as well as corporate work.	ben@grantmediaga.com	(404) 376-9408	https://www.grantmediaga.com/	https://www.instagram.com/grantmediaga/
`,
  },
  {
    name: "North Georgia Mountains: photography, planning, florals, music, catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mountain Woman Weddings	Planning		Dahlonega	Georgia	Dahlonega and surrounding North Georgia	Dahlonega planner and certified coordinator offering full planning, partial planning and day-of coordination for mountain weddings.		678.294.8663	https://www.mountainwomanweddings.com/	https://www.instagram.com/mountainwomanweddings/
Flowers By Patsy	Florals	162 Lumpkin County Parkway, Unit 1	Dahlonega	Georgia	Dahlonega and surrounding delivery area	Dahlonega flower shop making bridal bouquets, arches, centrepieces and cake-table flowers, with custom keepsake handle details.		(706) 326-3106	https://www.flowersbypatsy.com/wedding-flowers	
Stowers Flowers	Florals	135 Howser Mill Place	Dawsonville	Georgia	Dawsonville and a 20-mile radius, including Dahlonega and Big Canoe	Dawsonville florist doing wedding florals alongside everyday and event arrangements, delivering across the north Georgia foothills.	info@stowersflowers.com	404-405-6199	https://www.stowersflowers.com/	https://www.instagram.com/stowersflowers/
Floral Creations	Florals	270 Summit St	Blue Ridge	Georgia	Blue Ridge and surrounding North Georgia communities	Family-run Blue Ridge florist since 1977, delivering wedding flowers to mountain venues including Summit Farm and The Falls at Blue Ridge.	floralcreationsbr@yahoo.com	(706) 632-5006	https://floralcreationsblueridge.com/	
Blue Ridge Flowers	Florals	3586 E 1st St, Suite 304	Blue Ridge	Georgia	Blue Ridge, Ellijay, McCaysville and Cherry Log	Blue Ridge florist with a wedding room of linens, ceremony arches and cake stands for hire, plus custom wedding flower packages.	wecare@blueridgeflowers.net	(706) 258-3913	https://www.blueridgeflowers.net/	
Ellijay's Hometown Florist	Florals		Ellijay	Georgia	Greater Ellijay area	Ellijay florist making hand-tied bridal bouquets, centrepieces and boutonnieres, and delivering ceremony and reception flowers to local venues.			https://hometownfloristellijay.com/collections/wedding	
Backwoodz Boyz Entertainment	Music		Dahlonega	Georgia	Georgia and the wider Southeast	Dahlonega DJ company that also hires out photo booths, playing wedding receptions around North Georgia and neighbouring states.	djaycheek@gmail.com	(770) 655-2281	https://www.backwoodzboyzentertainment.com/	https://www.instagram.com/backwoodzboyzentertainment/
NDL Entertainment	Music		Dawsonville	Georgia	Dawsonville, Dahlonega and North Georgia	Owner-run mobile DJ for North Georgia weddings, with dance-floor lighting included and room uplighting available as an extra.			https://www.looneydjservices.com/	
Romaine On The Go	Catering		Dahlonega	Georgia	Dahlonega, Blue Ridge, Chattanooga and Knoxville	Personal chef and caterer based in Dahlonega, serving wedding buffets and interactive food stations across the mountains and into Tennessee.		423-504-9999	https://romaineotg.com/catering/dahlonega-ga/	
Catering by Cindy	Catering		Mineral Bluff	Georgia	North Georgia mountains	Mineral Bluff caterer for weddings, commitment ceremonies and retreats, cooking homemade menus planned around each couple.	cateringbycindy@gmail.com	770-894-9256	https://cateringbycindy.com/	
Horn Photography and Design	Photography		Dahlonega	Georgia	North Georgia	Husband-and-wife Dahlonega team shooting photo and film for a limited number of weddings a year, including Catholic ceremonies.			https://hornphotographyanddesign.com/	https://www.instagram.com/hornpd/
`,
  },
  {
    name: "Athens: photography, planning, florals, hair and makeup, cake, videography and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Elizabeth Hill Photography	Photography		Athens	Georgia	Athens and the Southeast	Athens wedding photographer for faith-minded couples, with calm direction and timeless, heirloom-style gallery images.	hello@elizabethhillphotography.com		https://www.elizabethhillphotography.com/	https://www.instagram.com/elizabethhillphotography/
Tara Wilburn Photography	Photography		Athens	Georgia	North Georgia and destination	Athens photographer with over sixteen years of experience shooting natural-light, emotion-led weddings for couples who want real moments.		706-338-6208	https://tarawilburn.com/	https://www.instagram.com/tarawilburn_photo/
Michele Houston Photography	Photography		Athens	Georgia	Georgia and the East Coast	Athens-based wedding photographer mixing classic portraits with room for candid moments, booking Georgia and East Coast weddings.			https://michelehoustonphotography.com/	https://www.instagram.com/michelehoustonphotography/
Candace McClain Weddings	Planning		Athens	Georgia	Athens and Atlanta	Day-of coordinator who also helps with pre-planning and rehearsals, and can host the reception, for weddings in Athens and Atlanta.	candacemcclainweddings@gmail.com	706-340-0317	https://www.candacemcclainweddings.com/	
Bloom & Ivy Events	Planning	1211 Washington St	Jefferson	Georgia		Jefferson floral design and planning team offering full-service, partial and month-of wedding coordination alongside decor and flowers.	info@bloomandivyevents.com	762-402-3636	https://www.bloomandivyevents.com/	https://www.instagram.com/bloomandivyweddings/
Ivy & Sterling Florals	Florals	225 Carruth Road	Jefferson	Georgia	Jefferson, Athens, Braselton, Commerce and Gainesville	Jefferson flower shop designing wedding bouquets and arrangements for couples across Athens and north Georgia.		(770) 797-8918	https://ivyandsterlingflorals.com/	https://www.instagram.com/ivyandsterlingflorals/
Kayla Walters Beauty Collective	Hair & Makeup		Madison	Georgia	Athens, Atlanta, Augusta, Madison and North Georgia	On-location bridal hair and makeup team creating soft, elevated looks for brides in Athens, Madison, Atlanta and across Georgia.	Kayla@kaylawaltershair.com	404-788-5302	https://kaylawaltershair.com/	https://www.instagram.com/kayla.walters.hair/
Sweetie Pie by Savie	Cake	150 E Whitehall Rd	Athens	Georgia	Athens	Athens bakery making wedding cakes and desserts, with tasting boxes, published pricing and delivery within town.	sweetiepiebysavie@gmail.com	(706) 850-9255	https://www.sweetiepiebysavie.com/	https://www.instagram.com/sweetiepiebysavie/
Cecilia's Cake Shop	Cake	610 North Milledge Avenue	Athens	Georgia	Athens	Small-batch Athens bakery taking orders for wedding cakes, groom's cakes, cupcakes and custom designs.		(706) 543-3308	https://ceciliascakeshop.com/	https://www.instagram.com/ceciliascakeshop/
CareAway Cakes & Gifts	Cake		Athens	Georgia	Athens	Athens bakery that makes custom-designed cakes for weddings and other occasions, with local delivery in the Athens area.			https://careawaycakes.com/	
Russ Feltman Films	Videography		Athens	Georgia	Athens, Macon, Augusta, Atlanta and Winder	Athens videographer with over thirty years filming weddings, from rehearsal dinner to grand exit, with drone footage available.			https://www.russfeltman.com/	https://www.instagram.com/russfeltman/
Hallie Jane's Catering	Catering		Madison	Georgia	Within 150 miles, including Athens, Atlanta and Augusta	Full-service Madison caterer for weddings and rehearsal dinners, with sample menus, bar service and a 150-mile travel radius covering Athens.	info@halliejanes.com	706-342-2837	https://halliejanes.com/	https://www.instagram.com/halliejanescatering/
`,
  },
];

export default batches;
