import type { VendorBatch } from "@/lib/vendor-batches";

// Georgia vendor batches. Every row's State is "Georgia". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Atlanta: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Audrey Grace Photography	Photography		Atlanta	Georgia		Fine art wedding and portrait photographer with 14 years behind the camera, aiming for timeless, joyful images over passing trends.			https://audreygracephoto.com/	https://www.instagram.com/audreygracephoto/
Amanda Summerlin Photography	Photography		Atlanta	Georgia	Atlanta, the Southeast and travel across the US	LGBTQ+-owned studio photographing creative, documentary-style weddings since 2009, including more than 100 queer weddings.			https://amandasummerlin.com/	
Sarah Folsom Photography	Photography		Atlanta	Georgia		Wedding photographer blending polished portraits with candid moments, covering everything from the small details to the dance floor.			https://sarahfolsomphotography.com/	https://www.instagram.com/sarahfolsomphoto/
Pop + Fizz	Planning		Atlanta	Georgia	Atlanta, across the US and destination weddings	Team of four planners offering full planning, design and coordination for style-led weddings in Atlanta and further afield.			https://popandfizz.com/	
Tinted Events	Planning		Atlanta	Georgia	Atlanta and destination weddings nationwide	Latina-owned planning and design studio led by Jax, creating bespoke full-service weddings in Atlanta and beyond.			https://tintedevents.com/	https://www.instagram.com/tintedevents/
Red & Gold Events	Planning		Atlanta	Georgia	Metro Atlanta, the Southeast and international destinations	Planning team specialising in Indian, Pakistani, South Asian and fusion weddings, from vendor contracts to multi-day timelines.	info@redandgold-events.com	(404) 445-4498	https://www.redandgold-events.com/	https://www.instagram.com/redandgoldevents/
Wedded Details	Planning		Atlanta	Georgia	Fulton, Gwinnett, Cobb, DeKalb, Cherokee and Forsyth counties	Flat-fee day-of and month-of coordination for metro Atlanta weddings, led by a planner with more than 15 years of experience.			https://www.weddedetails.com/	https://www.instagram.com/weddedetails/
Faith Flowers	Florals	1183 Virginia Ave NE	Atlanta	Georgia		Appointment-only Virginia-Highland studio designing wedding flowers and décor, which also runs flower classes and floral tours abroad.		(404) 922-8298	https://faithflowers.com/	https://www.instagram.com/faithflowersatl/
Le Jardin Français	Florals	1465 Howell Mill Rd NW, Suite 100C	Atlanta	Georgia		French-inspired floral and garden design firm with a Westside atelier and boutique, creating flowers for weddings and events.	info@lejardinfrancais.com	(404) 792-1680	https://lejardinfrancais.com/	
Each Day Florals	Florals		Atlanta	Georgia	Atlanta and the Southeast	Upper Westside studio led by designer Amy, making organic, elevated arrangements for weddings at venues across Georgia.	eachdayflorals@gmail.com	(216) 402-6826	https://eachdayflorals.com/	https://www.instagram.com/eachdayflorals/
D Street Entertainment	Music		Marietta	Georgia	Marietta, Atlanta and Kennesaw	DJ company pairing a DJ with a separate MC for an interactive two-person show, with more than 1,000 events played since 2001.	info@dstreetent.com	(404) 578-2655	https://www.dstreetentertainment.com/	https://www.instagram.com/dstreetent/
Lumina String Ensemble	Music		Atlanta	Georgia	Greater metro Atlanta and throughout Georgia	Violinist-led duo, trio and quartet for ceremonies and cocktail hours, drawing on a 235-song repertoire and custom arrangements.	luminastringensemble@gmail.com	(470) 588-2839	https://www.luminastringensemble.com/	https://www.instagram.com/luminastringensemble/
Elite Strings	Music		Atlanta	Georgia	Atlanta and surrounding areas	String duos, trios and quartets founded by a cellist and a violinist, with amplification packages for receptions as well as ceremonies.	info@elite-strings.com		https://elitestrings.com/	https://www.instagram.com/elitestringsatlanta/
Figs & Honey Catering	Catering	2911 Pharr Ct South NW	Atlanta	Georgia	Metro Atlanta	Scratch-made, chef-prepared catering for weddings and private events, offering drop-off menus as well as fully staffed service.	info@figsandhoneycatering.com	(404) 745-9561	https://www.figsandhoneycatering.com/	
Talk of the Town Catering	Catering	2469 Canton Rd	Marietta	Georgia	Metro Atlanta and North Georgia	Cobb County caterer led by executive chef Andrew Brackner, providing gourmet menus and full service staff for weddings.	andrew@tottatl.com	(404) 334-4935	https://talkofthetownatlanta.com/	
Dogwood Catering Company	Catering	4961 Lower Roswell Rd	Marietta	Georgia	Marietta and greater Atlanta	Upscale Southern catering for full-service weddings, corporate events and film and TV productions across metro Atlanta.	info@dogwoodcatering.com	(404) 914-6770	https://dogwoodcatering.com/	https://www.instagram.com/dogwoodcatering/
Eva Christine's Sweets	Cake		Atlanta	Georgia		Luxury wedding cake studio making bespoke, sculptural cakes with layered flavours, plus custom desserts for celebrations.	sweets@evachristinessweets.com	(404) 692-7075	https://www.evachristinessweets.com/	https://www.instagram.com/evachristinessweets/
Frosted Pumpkin Wedding Cakes	Cake		Atlanta	Georgia	Atlanta area	Handcrafted wedding cakes for metro Atlanta couples, designed through personal consultations on style and flavour.			https://frostedpumpkin.com/	https://www.instagram.com/frostedpumpkincakes/
Platinum Cake Designs	Cake		Decatur	Georgia	Atlanta metro area	Private Decatur cake studio run by chef Nevia Giles, creating original custom wedding cakes rather than copied designs.	info@platinumcakedesigns.com	(678) 487-9797	https://www.platinumcakedesigns.com/	https://www.instagram.com/_platinumcakedesigns/
Virginia Marie Cake Boutique	Cake	5160 Erin Rd	Atlanta	Georgia	Georgia, Alabama, Tennessee, Mississippi and Florida	Appointment-only cake boutique offering custom wedding cakes with tastings, delivering across Georgia and neighbouring states.	info@virginiamarie.com	(404) 996-2617	https://www.virginiamarie.com/	https://www.instagram.com/virginiamariecakes/
Vigilante Makeup + Hair Artistry	Hair & Makeup	4463 Cherokee St, Suite 100	Acworth	Georgia	Atlanta and Chattanooga areas	On-location and destination bridal hair and makeup team founded by Erica Ages in 2014, working from a studio in Acworth.	info@vigilantecosmetics.com	(404) 402-0486	https://vigilantecosmetics.com/	https://www.instagram.com/vigilantecosmetics/
Brushworx	Hair & Makeup	9165 Martin Rd	Roswell	Georgia	Georgia, the Carolinas, Tennessee and Alabama	On-location bridal hair and makeup team founded in 2006, with studios in Roswell and Snellville and grooming for grooms.			https://www.brushworx.net/	
B For Beaute	Hair & Makeup		Atlanta	Georgia	Atlanta, DC and beyond	Bridal makeup artist specialising in women of colour, with hair from a partner stylist for combined hair and makeup packages.	info@bforbeaute.co		https://bforbeaute.co/	https://www.instagram.com/bforbeaute.co/
Claudia Goodwin Films	Videography		Atlanta	Georgia	Atlanta and destination weddings worldwide	Wedding filmmaker since 2019 making emotional, timeless films across Georgia and at destinations from Venice to New York.	claudiagoodwinfilms@gmail.com	(404) 405-0661	https://claudiagoodwinfilms.com/	https://www.instagram.com/claudiagoodwinfilms/
Vitor Lindo	Videography		Atlanta	Georgia	Atlanta, Georgia and travel nationwide	Wedding videographer and photographer with more than 450 weddings filmed, experienced in Indian and multi-day celebrations.			https://vitor-lindo.com/	https://www.instagram.com/vitorlindophotovideo/
KJB Studios	Videography		Atlanta	Georgia	Atlanta and worldwide	Photo and video studio led by Kendrick, filming weddings as unstaged storytelling with an editorial, art-led eye.	kjbstudios.info@gmail.com		https://kjbstudios.com/	https://www.instagram.com/k.j.bstudios/
`,
  },
  {
    name: "Savannah: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
State of Grace Studios	Photography		Savannah	Georgia		Husband-and-wife team photographing and filming weddings, engagements and elopements, with drone coverage on offer for aerial views.	stateofgracestudios@gmail.com	(912) 429-4778	https://stateofgracestudios.com/	https://www.instagram.com/stateofgracestudios/
Jeff & Mollie	Photography		Savannah	Georgia		Documentary husband-and-wife duo shooting weddings together since 2009, covering both photography and video from a single team.		(912) 224-7717	https://www.jeffandmollie.com/	https://www.instagram.com/jeffandmollie/
Meredith Ryncarz	Photography		Savannah	Georgia	Savannah and destination weddings worldwide	Classic, heirloom-minded wedding photography from a Savannah photographer who also travels for destination weddings, backed by a small team.	info@meredithryncarz.com	(912) 910-1040	https://meredithryncarz.com/	https://www.instagram.com/meredithryncarz/
Coastal Chic Studios	Photography		Savannah	Georgia	Savannah and the Southeast	Husband-and-wife photographers Todd and Angela, specialising in fine-art wedding and couples portraits, plus proposal shoots for visitors.			https://coastalchicstudios.com/	https://www.instagram.com/coastalchicstudios/
Tara Skinner Events	Planning		Savannah	Georgia	Savannah, the coast and destination weddings	Destination wedding planning and design firm offering full-service planning for timeless luxury weddings in Savannah and further afield.			https://taraskinnerevents.com/	https://www.instagram.com/taraskinnerevents/
Elegant Savannah Weddings	Planning		Savannah	Georgia		Planning team offering full planning, coordination and design packages for Savannah weddings, with a clear step-by-step process for couples.	info@elegantsavannahweddings.com	(912) 531-0993	https://www.elegantsavannahweddings.com/	https://www.instagram.com/elegantsavannahweddings/
Sincerely Yours Events	Planning		Savannah	Georgia	Savannah, the Lowcountry and beyond	Wedding planning company helping couples shape and carry out their vision across Savannah and the Lowcountry, from first ideas to the day itself.	hello@sincerelyyoursevents.com		https://www.sincerelyyoursevents.com/	https://www.instagram.com/sincerely.yours.events/
A to Zinnias	Florals	217 East Broad Street	Savannah	Georgia	Savannah and the Lowcountry	Downtown florist working since 1999, with weddings at its roots and thousands designed across the Lowcountry's historic venues and landscapes.	info@atozinnias.com	(912) 234-3400	https://www.atozinnias.com/	https://www.instagram.com/atozinnias/
Kato Floral Designs	Florals	127 Abercorn Street, Suite 207	Savannah	Georgia	Savannah, Hilton Head and the Golden Isles	Award-winning wedding and event florist with a studio on Oglethorpe Square, designing custom florals for intimate and destination celebrations.	hello@katoweddings.com	(912) 508-1166	https://katoweddings.com/	https://www.instagram.com/katofloraldesigns/
Urban Poppy	Florals	3125 Bull Street	Savannah	Georgia		Ardsley Park flower shop and studio running an à la carte luxury wedding floral programme, alongside a flower bar, workshops and gifts.	margaret.urbanpoppy@gmail.com	(912) 482-1713	https://urbanpoppy.com/	https://www.instagram.com/urbanpoppyshop/
Sweetfield Flowers	Florals		Savannah	Georgia		A fifth-generation Savannahian's studio creating lush, layered wedding florals from local farm stems, each piece designed rather than repeated.	sweetfieldflowers@gmail.com		https://www.sweetfieldflowers.com/	https://www.instagram.com/sweetfieldflowers/
Versamix Music	Music		Savannah	Georgia	Savannah, Hilton Head and the Coastal Empire	Luxury wedding DJ service led by Savannah DJ César Almodóvar, pairing curated sets with lighting and sound for weddings and galas.	versamixmusic@yahoo.com		https://www.versamixmusic.com/	https://www.instagram.com/versamix_music/
All About You Entertainment	Music	404 East Oglethorpe Ave	Savannah	Georgia		Savannah DJ company providing wedding DJs and MCs, with uplighting, photo booths and silent disco kit available to add on.		(912) 897-0518	https://allaboutyoudjs.com/	https://www.instagram.com/allaboutyouentertainment/
J&M Sound Productions	Music		Richmond Hill	Georgia	Savannah, Hilton Head, Jekyll Island, Statesboro and surrounding areas	Locally owned DJ company founded in 2001 by DJ Johnny C, bringing over 20 years of wedding experience and its own sound equipment.		(912) 308-0751	https://www.jmsoundproductions.com/	
Logan Thomas Music	Music		Savannah	Georgia		Singing guitarist, DJ and MC in one, offering live acoustic music and DJ sets for weddings and upscale events around Savannah.	logan@loganthomasmusic.com		https://www.loganthomasmusic.com/	https://www.instagram.com/loganthomasmusic/
Thrive Catering	Catering	2700 Gregory St, Suite 200	Savannah	Georgia		Award-winning Savannah caterer handling weddings, social events and corporate functions, with rentals and a list of favourite venues.	thrivecatering@gmail.com	(912) 508-6068	https://cateringbythrive.com/	https://www.instagram.com/thrivecateringsav/
B Local Catering	Catering	1000 Eisenhower Drive, Suite E	Savannah	Georgia		Wedding caterer that designs menus around each couple's vision and budget, from pasta bars to full receptions and rehearsal dinners.		(912) 247-8839	https://www.blocalcateringsav.com/	https://www.instagram.com/blocalcateringsav/
Magnolia Grill Catering	Catering	3881 Hwy 17	Richmond Hill	Georgia	Savannah area	Wife-and-husband team catering since 1999, serving buffets, plated, family-style and stations, plus bar service and Lowcountry boils.	sales@magnoliagrillcatering.com	(912) 756-3663	https://magnoliagrillcatering.com/	
Savannah Event Catering	Catering	1109 South Rogers Street	Pooler	Georgia	Savannah and the Lowcountry	Chef-led caterer serving Savannah and the Lowcountry since 2008, building custom wedding menus around each couple's tastes and traditions.	events@savannaheventcatering.com	(912) 660-7533	https://savannaheventcatering.com/	https://www.instagram.com/savannaheventcatering_/
Wonderland Beauty Bar	Hair & Makeup	7370 Hodgson Memorial Dr	Savannah	Georgia	Savannah and beyond (travel fee outside Savannah)	Mobile bridal hair and makeup team led by licensed stylist and cosmetology instructor Wanda, travelling to venues around Savannah and beyond.	wanda@wonderlandbeautybar.com	(912) 323-9282	https://wonderlandbeautybar.com/	https://www.instagram.com/wonderlandbeauty_bar/
LANÉ Makeup Artistry	Hair & Makeup		Savannah	Georgia		Brandi Lane's Savannah makeup service specialising in soft-glam bridal and elopement looks, drawing on a background in television makeup.	lanemakeupartistry@gmail.com		https://lanemakeupartistry.com/	https://www.instagram.com/lane_makeupartistry/
Beyond Beautiful by Heather	Hair & Makeup		Savannah	Georgia		Licensed on-location makeup and hair artist Heather Ferguson, styling brides, bridal parties and elopements around Savannah.	heatherjferguson@hotmail.com	(912) 713-7039	https://www.beyondbeautifulbyheather.com/	https://www.instagram.com/beyondbeautifulbyheather/
Wicked Cakes of Savannah	Cake	466 Montgomery Street	Savannah	Georgia		Downtown bakery making wedding and groom's cakes to order for pick-up or delivery, alongside custom cakes and cake-decorating classes.	wickedcakesofsavannah@gmail.com	(912) 298-0040	https://www.wickedcakesofsavannah.com/	https://www.instagram.com/wickedcakesofsavannah/
Baker's Pride Bakery	Cake	840 E. DeRenne Ave	Savannah	Georgia		Family bakery serving Savannah since 1982, making wedding and groom's cakes alongside cakes, cheesecakes and pies for every occasion.		(912) 355-1155	https://www.savannahbakery.com/	https://www.instagram.com/bakers_pride_bakery/
Coastal Confections	Cake		Richmond Hill	Georgia	Richmond Hill, Savannah, Tybee Island, St Simons Island and surrounding areas	Appointment-only custom cake shop opened in 2013 by a certified chef, making wedding and groom's cakes as well as sugar and chocolate art.	coastalconfections2013@gmail.com		https://www.coastalconfections.net/	
Flirt With Dessert	Cake		Wilmington Island	Georgia	Savannah and surrounding areas	Mother-daughter boutique bakery making custom wedding cakes, with gluten-free, eggless, dairy-free and vegan options on request.	ashley@flirtwithdessert.com	(912) 661-2662	https://flirtwithdessert.com/	https://www.instagram.com/flirtwithdessertbakery/
Ardsley Park Productions	Videography		Savannah	Georgia	Savannah and travelling everywhere	Cinematic wedding films from a Savannah studio that travels anywhere, with full-length films from venues such as Hotel Bardo and Forsyth Park.	ardsleyparkproductions@gmail.com		https://www.ardsleyparkproductions.com/	https://www.instagram.com/ardsleyparkproductions/
Square City Productions	Videography		Savannah	Georgia		Savannah video team making wedding films on 4K cinema cameras, with drone footage in highlight films and delivery in a digital album.			https://squarecityproductions.com/	https://www.instagram.com/squarecityproductions/
`,
  },
  {
    name: "Savannah: videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Savannah Wedding Films	Videography		Savannah	Georgia	Savannah, Charleston, Hilton Head and beyond	Savannah studio led by filmmaker Trevor Jenkins, making handcrafted wedding videos and photos for Lowcountry and coastal Georgia couples.	savannahweddingfilms@gmail.com		https://www.savannahweddingfilms.com/	https://www.instagram.com/savannahweddingfilms/
`,
  },
  {
    name: "Athens: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Claire Diana Photography	Photography		Athens	Georgia	Athens, Atlanta and beyond	Full-time Athens photographer, formerly shooting UGA football for the local paper, who covers weddings alongside senior and boudoir portraits.			https://clairedianaphotography.com/	https://www.instagram.com/claire_diana/
Blane Marable Photography	Photography		Athens	Georgia	Athens and Atlanta	Long-running Athens wedding photographer covering engagements, bridal portraits and the wedding day itself across Athens and Atlanta.			https://www.blanemarable.com/	
Jackson & June Events	Planning		Athens	Georgia	Athens and Atlanta	Planning studio offering full, partial and month-of coordination, with a soft spot for walkable downtown Athens wedding weekends.			https://jacksonandjune.com/athens-weddings	https://www.instagram.com/jacksonandjuneevents/
Brett Glenn Floral Design	Florals	1054 S Lumpkin St	Athens	Georgia	Athens and Oconee County	Full-service florist on South Lumpkin Street designing flowers for weddings, corporate events and social gatherings around Athens.		706-227-9937	https://www.brettglenn.com/	
Flowerland	Florals	823 Prince Ave	Athens	Georgia		Prince Avenue flower shop making bridal bouquets, centrepieces, head-table garlands and floral arches in styles from cascading to modern.	flowerlandathens@gmail.com	(706) 549-1884	https://www.flowerlandathensga.com/wedding-flowers	
Classic City Confections	Cake		Athens	Georgia	Athens and Northeast Georgia	Athens wedding cake maker offering buttercream and fondant tiers priced per serving, plus a range of dessert-table sweets by consultation.	classiccityconfections@gmail.com		https://classiccityconfections.com/	
Sound Insight	Music		Athens	Georgia	Athens and Atlanta	DJ company for Athens and Atlanta weddings that also handles ceremony sound, with wireless mics for officiants and readers.	events@soundinsightdj.com	706-927-5261	https://www.soundinsightdj.com/weddings	https://www.instagram.com/soundinsightpro/
Nightbird	Music		Athens	Georgia	Atlanta, Athens and North Georgia	DJ and photo booth crew, formerly Athens DJ Service, that assigns your DJ 90 days out and joins two planning calls before the day.	info@nightbirdent.com	(706) 715-3371	https://www.nightbirdent.com/	https://www.instagram.com/nightbirdent/
Bombshell Creations	Hair & Makeup	688 S Milledge Avenue	Athens	Georgia	Athens, Atlanta, Savannah and the Southeast	On-site hair and makeup team based in Athens, styling brides, bridal parties and grooms at venues across Georgia and the Carolinas.		(706) 714-1907	https://bombshellcreations.com/	https://www.instagram.com/bombshellcreationsga/
CraigFilm	Videography		Athens	Georgia		Athens video and photo studio filming wedding days, with 360 VR coverage and live streaming for guests who can't attend in person.	info@craigfilm.com		https://craigfilm.com/	https://www.instagram.com/craigcarmean/
Trumps Catering	Catering	2026 South Milledge Avenue, Suite B	Athens	Georgia	Athens and surrounding counties	Athens caterer since 1986, grown from a neighbourhood bistro, handling receptions, rehearsal dinners and bridal luncheons.	sales@trumpscatering.com	(706) 546-1320	https://www.trumpscatering.com/	https://www.instagram.com/trumpscatering/
Epting Events	Catering	1430 N Chase St	Athens	Georgia	Athens, Atlanta and beyond	Athens-headquartered catering and event design company with decades of experience, also catering weddings in Atlanta.	info@eptingevents.com	706.353.1913	https://www.eptingevents.com/	https://www.instagram.com/eptingevents/
`,
  },
  {
    name: "North Georgia Mountains: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
River Underwood Photography	Photography		Blue Ridge	Georgia	Blue Ridge, Blairsville, Ellijay and the North Georgia mountains	Blue Ridge photographer covering weddings and events as well as family portraits and real estate around the mountain towns.	sales@riverunderwoodphotography.com	706-455-6736	https://www.riverunderwoodphotography.com/	https://www.instagram.com/riverunderwoodphotography/
Appalachian Wedding Photography	Photography		Blue Ridge	Georgia	Blue Ridge and travel	Blue Ridge wedding and elopement photographer Emilie Gates, documenting mountain weddings with a Leave No Trace approach to outdoor shoots.	info@appalachianweddingphotography.com		https://appalachianweddingphotography.com/	https://www.instagram.com/appalachianweddingphotography/
Unique Events	Planning		Blairsville	Georgia	Blue Ridge, Blairsville and the North Georgia mountains	Blairsville planning and design firm led by Andrea, coordinating mountain weddings and connecting couples with trusted local vendors.	andrea.uniqueevents@gmail.com	706.851.9106	https://www.uniqueevents.org/	https://www.instagram.com/uniqueeventsbyandrea/
Ever Weddings	Planning		Talking Rock	Georgia	North Georgia, from Dahlonega to Chattanooga	Day-of coordinator Michelle, based in Talking Rock, running wedding timelines and vendors for couples marrying across the North Georgia mountains.			https://everweddings.com/	https://www.instagram.com/everweddings/
North Georgia Weddings & Events	Music		Commerce	Georgia	North Georgia and Atlanta	DJ and MC company covering Blue Ridge, Dahlonega and other mountain venues, with lighting and photo booth hire alongside the music.	info@northgeorgiaweddingsandevents.com	(706) 383-9883	https://www.northgeorgiaweddingsandevents.com/	https://www.instagram.com/northgeorgiaweddingsandevents/
Smith House Catering	Catering	84 South Chestatee St	Dahlonega	Georgia	Dahlonega and nearby venues	Off-site catering from Dahlonega's long-running Smith House restaurant, whose staff deliver Southern dishes and set up the buffet on site.	info@smithhouse.com	706.725.8330	https://smithhouse.com/cater-to-location/	
Styles by Sydney	Hair & Makeup		Dawsonville	Georgia	All of Georgia and destination weddings	Dawsonville-based stylist offering on-site bridal hair and makeup for weddings in North Georgia, Atlanta and further afield.	info@stylesbysydney.com	512-738-7097	https://stylesbysydney.com/	
Jamie Bakes	Cake		Dahlonega	Georgia	North Georgia wedding venues	Boutique cakery in Dahlonega making wedding cakes, and a preferred vendor at a number of North Georgia mountain venues.	jamiebakes706@gmail.com		https://www.jamiebakes.net/	https://www.instagram.com/jamiebakes706/
Sherry's Sweets-n-Eats	Cake		Dahlonega	Georgia		Licensed cottage bakery in Dahlonega making custom celebration and wedding cakes to order for North Georgia couples.			https://www.sherryssweetsneats.com/	https://www.instagram.com/sherrys.sweetsn.eats/
Grant Media	Videography		Dahlonega	Georgia		Dahlonega video production company with more than 15 years behind the camera, filming weddings and events as well as corporate work.	ben@grantmediaga.com	(404) 376-9408	https://www.grantmediaga.com/	https://www.instagram.com/grantmediaga/
`,
  },
  {
    name: "North Georgia Mountains: photography, planning, florals, music, catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mountain Woman Weddings	Planning		Dahlonega	Georgia	Dahlonega and surrounding North Georgia	Dahlonega planner and certified coordinator offering full planning, partial planning and day-of coordination for mountain weddings.		678.294.8663	https://www.mountainwomanweddings.com/	https://www.instagram.com/mountainwomanweddings/
Flowers By Patsy	Florals	162 Lumpkin County Parkway, Unit 1	Dahlonega	Georgia	Dahlonega and surrounding delivery area	Dahlonega flower shop making bridal bouquets, arches, centrepieces and cake-table flowers, with custom keepsake handle details.		(706) 326-3106	https://www.flowersbypatsy.com/wedding-flowers	
Stowers Flowers	Florals	135 Howser Mill Place	Dawsonville	Georgia	Dawsonville and a 20-mile radius, including Dahlonega and Big Canoe	Dawsonville florist doing wedding florals alongside everyday and event arrangements, delivering across the north Georgia foothills.	info@stowersflowers.com	404-405-6199	https://www.stowersflowers.com/	https://www.instagram.com/stowersflowers/
Floral Creations	Florals	270 Summit St	Blue Ridge	Georgia	Blue Ridge and surrounding North Georgia communities	Family-run Blue Ridge florist since 1977, delivering wedding flowers to mountain venues including Summit Farm and The Falls at Blue Ridge.	floralcreationsbr@yahoo.com	(706) 632-5006	https://floralcreationsblueridge.com/	
Blue Ridge Flowers	Florals	3586 E 1st St, Suite 304	Blue Ridge	Georgia	Blue Ridge, Ellijay, McCaysville and Cherry Log	Blue Ridge florist with a wedding room of linens, ceremony arches and cake stands for hire, plus custom wedding flower packages.	wecare@blueridgeflowers.net	(706) 258-3913	https://www.blueridgeflowers.net/	
Ellijay's Hometown Florist	Florals		Ellijay	Georgia	Greater Ellijay area	Ellijay florist making hand-tied bridal bouquets, centrepieces and boutonnieres, and delivering ceremony and reception flowers to local venues.			https://hometownfloristellijay.com/collections/wedding	
Backwoodz Boyz Entertainment	Music		Dahlonega	Georgia	Georgia and the wider Southeast	Dahlonega DJ company that also hires out photo booths, playing wedding receptions around North Georgia and neighbouring states.	djaycheek@gmail.com	(770) 655-2281	https://www.backwoodzboyzentertainment.com/	https://www.instagram.com/backwoodzboyzentertainment/
NDL Entertainment	Music		Dawsonville	Georgia	Dawsonville, Dahlonega and North Georgia	Owner-run mobile DJ for North Georgia weddings, with dance-floor lighting included and room uplighting available as an extra.			https://www.looneydjservices.com/	
Romaine On The Go	Catering		Dahlonega	Georgia	Dahlonega, Blue Ridge, Chattanooga and Knoxville	Personal chef and caterer based in Dahlonega, serving wedding buffets and interactive food stations across the mountains and into Tennessee.		423-504-9999	https://romaineotg.com/catering/dahlonega-ga/	
Catering by Cindy	Catering		Mineral Bluff	Georgia	North Georgia mountains	Mineral Bluff caterer for weddings, commitment ceremonies and retreats, cooking homemade menus planned around each couple.	cateringbycindy@gmail.com	770-894-9256	https://cateringbycindy.com/	
Horn Photography and Design	Photography		Dahlonega	Georgia	North Georgia	Husband-and-wife Dahlonega team shooting photo and film for a limited number of weddings a year, including Catholic ceremonies.			https://hornphotographyanddesign.com/	https://www.instagram.com/hornpd/
`,
  },
  {
    name: "Athens: photography, planning, florals, hair and makeup, cake, videography and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Elizabeth Hill Photography	Photography		Athens	Georgia	Athens and the Southeast	Athens wedding photographer for faith-minded couples, with calm direction and timeless, heirloom-style gallery images.	hello@elizabethhillphotography.com		https://www.elizabethhillphotography.com/	https://www.instagram.com/elizabethhillphotography/
Tara Wilburn Photography	Photography		Athens	Georgia	North Georgia and destination	Athens photographer with over sixteen years of experience shooting natural-light, emotion-led weddings for couples who want real moments.		706-338-6208	https://tarawilburn.com/	https://www.instagram.com/tarawilburn_photo/
Michele Houston Photography	Photography		Athens	Georgia	Georgia and the East Coast	Athens-based wedding photographer mixing classic portraits with room for candid moments, booking Georgia and East Coast weddings.			https://michelehoustonphotography.com/	https://www.instagram.com/michelehoustonphotography/
Candace McClain Weddings	Planning		Athens	Georgia	Athens and Atlanta	Day-of coordinator who also helps with pre-planning and rehearsals, and can host the reception, for weddings in Athens and Atlanta.	candacemcclainweddings@gmail.com	706-340-0317	https://www.candacemcclainweddings.com/	
Bloom & Ivy Events	Planning	1211 Washington St	Jefferson	Georgia		Jefferson floral design and planning team offering full-service, partial and month-of wedding coordination alongside decor and flowers.	info@bloomandivyevents.com	762-402-3636	https://www.bloomandivyevents.com/	https://www.instagram.com/bloomandivyweddings/
Ivy & Sterling Florals	Florals	225 Carruth Road	Jefferson	Georgia	Jefferson, Athens, Braselton, Commerce and Gainesville	Jefferson flower shop designing wedding bouquets and arrangements for couples across Athens and north Georgia.		(770) 797-8918	https://ivyandsterlingflorals.com/	https://www.instagram.com/ivyandsterlingflorals/
Kayla Walters Beauty Collective	Hair & Makeup		Madison	Georgia	Athens, Atlanta, Augusta, Madison and North Georgia	On-location bridal hair and makeup team creating soft, elevated looks for brides in Athens, Madison, Atlanta and across Georgia.	Kayla@kaylawaltershair.com	404-788-5302	https://kaylawaltershair.com/	https://www.instagram.com/kayla.walters.hair/
Sweetie Pie by Savie	Cake	150 E Whitehall Rd	Athens	Georgia	Athens	Athens bakery making wedding cakes and desserts, with tasting boxes, published pricing and delivery within town.	sweetiepiebysavie@gmail.com	(706) 850-9255	https://www.sweetiepiebysavie.com/	https://www.instagram.com/sweetiepiebysavie/
Cecilia's Cake Shop	Cake	610 North Milledge Avenue	Athens	Georgia	Athens	Small-batch Athens bakery taking orders for wedding cakes, groom's cakes, cupcakes and custom designs.		(706) 543-3308	https://ceciliascakeshop.com/	https://www.instagram.com/ceciliascakeshop/
CareAway Cakes & Gifts	Cake		Athens	Georgia	Athens	Athens bakery that makes custom-designed cakes for weddings and other occasions, with local delivery in the Athens area.			https://careawaycakes.com/	
Russ Feltman Films	Videography		Athens	Georgia	Athens, Macon, Augusta, Atlanta and Winder	Athens videographer with over thirty years filming weddings, from rehearsal dinner to grand exit, with drone footage available.			https://www.russfeltman.com/	https://www.instagram.com/russfeltman/
Hallie Jane's Catering	Catering		Madison	Georgia	Within 150 miles, including Athens, Atlanta and Augusta	Full-service Madison caterer for weddings and rehearsal dinners, with sample menus, bar service and a 150-mile travel radius covering Athens.	info@halliejanes.com	706-342-2837	https://halliejanes.com/	https://www.instagram.com/halliejanescatering/
`,
  },
  {
    name: "Atlanta: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Saturday Sun	Photography		Atlanta	Georgia	Atlanta and the North Georgia mountains	Atlanta wedding photography studio covering weddings, elopements and engagements with an unposed, real-moments approach.			https://saturdaysunphoto.com/	https://www.instagram.com/saturdaysunphoto/
Joey Wallace Photography	Photography		Atlanta	Georgia	Atlanta	Atlanta photography and video team covering weddings, including multi-day Indian and South Asian celebrations.			https://joeywallacephotography.com/	https://www.instagram.com/joeywallacephotography/
ALTMIX Photography	Photography		Atlanta	Georgia	Atlanta	Atlanta wedding photography team that also offers a photo booth and engagement sessions alongside full wedding coverage.	info@altmixphotography.com	404.432.1442	https://altmixphotography.com/	https://www.instagram.com/altmix/
Russell K Photo	Photography		Atlanta	Georgia		Atlanta wedding and family photographer who focuses on candid, relaxed moments of the day, with packages listed on the site.			https://russellkphoto.com/	https://www.instagram.com/russellkphotography/
Elicia Bryan Photography	Photography		Atlanta	Georgia	Atlanta and worldwide	Atlanta-based photographer shooting documentary-style weddings and elopements, and happy to travel for destination celebrations.	elicia@eliciabryan.com	(404) 827-8139	https://eliciabryanweddings.com/	https://www.instagram.com/eliciabryan/
Aurora Photography	Photography		Atlanta	Georgia	Atlanta, Georgia and destination weddings	Atlanta wedding photographer with more than 300 weddings photographed across Georgia and further afield over eleven years.	auroraphotoatl@gmail.com		https://www.auroraatl.com/	https://www.instagram.com/auroraphotoatl/
Gorgeous By Design Events	Planning		Atlanta	Georgia	Metro Atlanta	Atlanta planner and designer for large-budget weddings, with design packages that carry minimum spends from $30,000.	consult@gorgeousbydesignevents.com		https://www.gorgeousbydesignevents.com/	https://www.instagram.com/gorgeousbydesignevents/
Pollyanna Richter Weddings	Planning		Atlanta	Georgia	Buckhead, Alpharetta and across Georgia	Atlanta full-service wedding planning and design that also supplies sustainable floral work for the weddings it plans.	weddings@pollyannarichter.com	470-545-2584	https://www.pollyannarichter.com/	https://www.instagram.com/pollyannarichterweddings/
Fête & Figs	Planning		Atlanta	Georgia	Atlanta, North Georgia and surrounding areas	Atlanta wedding planning and event design studio offering full-service planning from first ideas through to the day itself.			https://www.feteandfigs.com/	https://www.instagram.com/feteandfigs/
Bello Events	Planning		Alpharetta	Georgia		Alpharetta event planning and management company that handles weddings alongside corporate and private events, from decor to performers.	info@belloevents.com	(678) 314-6960	https://belloevents.com/	https://www.instagram.com/belloevents.llc/
Becca Brooks Events & Design	Planning		Atlanta	Georgia	Georgia and the Southeast	Full-service Atlanta wedding planner who plans weddings at Georgia venues as well as across the wider Southeast.			https://www.beccabrooksevents.com/	https://www.instagram.com/beccabrooksevents/
Faith Flowers	Florals	1183 Virginia Ave NE	Atlanta	Georgia	Atlanta	Atlanta flower studio designing wedding and event florals, with a flower school and floral tours alongside its design work.		404-922-8298	https://faithflowers.com/	https://www.instagram.com/faithflowersatl/
JJ's Flower Shop	Florals	4511 Olde Perimeter Way	Atlanta	Georgia	Atlanta and surrounding areas	Atlanta flower shop offering wedding bouquets and event flowers as well as same-day delivery across the city.	hello@jjsflowershop.com		https://jjsflowershop.com/	https://www.instagram.com/jjsflowershop/
Flux Floral Design	Florals		Atlanta	Georgia	Atlanta and surrounding areas	Atlanta wedding and event florist with a full-service design option, a budget calculator and a la carte bouquets.	info@fluxfloral.com	(470) 467-6230	https://www.fluxfloral.com/	https://www.instagram.com/fluxfloral/
Millbrook Farm Flowers	Florals		Marietta	Georgia	Atlanta	Garden-inspired wedding and event florist based in Marietta and designing for celebrations across Atlanta.		404-906-4809	https://millbrookfarmflowers.com/	https://www.instagram.com/millbrookfarmflowers/
The Flower Shop Atlanta	Florals	4610 Memorial Drive	Decatur	Georgia	Metro Atlanta	Decatur florist with a dedicated wedding service as well as same-day flower delivery across metro Atlanta.	sales@theflowershopatl.com	404-292-0907	https://theflowershopatl.com/pages/weddings	https://www.instagram.com/theflowershop_atl/
Revel Entertainment	Music		Atlanta	Georgia	Atlanta and worldwide	Atlanta DJ, MC and lighting company built around South Asian and Indian weddings, from baraat to reception.	info@revel-ent.com	706-341-1510	https://www.revel-ent.com/	https://www.instagram.com/revelentertainment/
Atlanta Music Pros	Music		Atlanta	Georgia	Atlanta and Alpharetta	Atlanta entertainment company supplying DJs, MCs, live musicians, lighting and photo booths for weddings.	info@atlantamusicpros.com	(404) 919-0970	https://atlantamusicpros.com/	https://www.instagram.com/atlantamusicpros/
The Atlanta Wedding Band	Music		Brookhaven	Georgia	Atlanta	Live wedding band based in Brookhaven, with separate ceremony music and a published song list and cost guide.	cocrogan@gmail.com	770-653-7841	https://atlantaweddingband.com/	https://www.instagram.com/atlantaweddingband/
Flavor Band ATL	Music		Atlanta	Georgia	Atlanta	Atlanta live band for wedding receptions, with ensembles from six players up and an MC to run the evening.	flavorbandatl@gmail.com	678-422-1058	https://flavorbandatl.com/	https://www.instagram.com/flavorbandatl/
Tasteful Tea Band	Music		Atlanta	Georgia	Atlanta	Atlanta wedding reception band playing high-energy sets for couples in the city and further afield.	contact@tastefulteaband.com	470-684-4049	https://www.tastefulteaband.com/	https://www.instagram.com/tastefulteaband/
The American Flyers	Music		Atlanta	Georgia	Atlanta	Atlanta show band playing classic rock, country, pop and R&B for weddings, corporate events and parties.		(404) 545-5656	https://theamericanflyers.com/	
Step By Step Catering	Catering	1303 Columbia Dr	Decatur	Georgia	Decatur and surrounding areas	Decatur caterer offering wedding packages with heavy hors d'oeuvres, dessert stations and rehearsal dinner menus.	info@stepbystepcatering.com	(404) 286-0094	https://stepbystepcatering.com/	
AV Gourmet	Catering	627 E College Ave Suite D1	Decatur	Georgia	Metro Atlanta	Decatur caterer with wedding menus and a mixology service, which also works on film and corporate events.	info@avgourmet.com	(678) 203-4203	https://avgourmet.com/	
Artistic Soul Catering	Catering	3996 Pleasantdale Rd. #203	Atlanta	Georgia	Metro Atlanta	Metro Atlanta caterer serving soulful, globally inspired menus with Southern, Cajun and Caribbean influences for weddings.	eat@artisticsoulcatering.com	404-983-0210	https://artisticsoulcatering.com/	https://www.instagram.com/artisticsoulcatering/
Sabrosa Catering	Catering	3781 Presidential Pkwy Suite FP-303	Atlanta	Georgia	Atlanta	Atlanta caterer run by a chef and a pastry chef, offering full-service food and event production with a dessert menu.	events@sabrosaatl.com		https://sabrosaatl.com/	https://www.instagram.com/sabrosacateringatl/
Exquisite Delites Catering Company	Catering	4391 Glenwood Rd	Decatur	Georgia	Atlanta	Decatur caterer with a dedicated weddings offering and chef-led menu tastings built around each couple's preferences.	info@exqdelites.com	470-664-2930	https://www.exqdelites.com/	https://www.instagram.com/exquisite_delites_/
Formal Faces	Hair & Makeup		Atlanta	Georgia	Atlanta area	On-location bridal hair and makeup team serving the Atlanta area since 1998, with practice sessions and bridal party services.	jennifer@formalfaces.com	770-682-7627	https://formalfaces.com/	https://www.instagram.com/formalfaces/
One10 Beauty	Hair & Makeup		Atlanta	Georgia	Atlanta	On-location bridal hair and makeup team across Atlanta that matches artists to each bride and works with all hair textures.	booking@one10beauty.com		https://one10beauty.com/bridal-atl	https://www.instagram.com/one10beauty/
Lemoine Looks	Hair & Makeup		Atlanta	Georgia	Atlanta	Atlanta makeup artist María Lemoine, Venezuelan-born, who does bridal makeup and travels for destination weddings.			https://lemoinelooks.com/	
BridesbySAJ	Hair & Makeup		Atlanta	Georgia	Atlanta and surrounding areas	Atlanta bridal makeup artist and hairstylist offering natural or airbrush looks, with the same artist at trial and on the day.			https://www.bridesbysaj.com/	https://www.instagram.com/bridesbysaj/
Shannon Turner Cakes	Cake		Acworth	Georgia	Georgia	Acworth wedding cake designer with signature cake packages, elopement cakes and a blog of planning tips.	hello@shannonturnercakes.com	404-902-3457	https://shannonturnercakes.com/	https://www.instagram.com/shannonturnercakes/
Frosted Pumpkin Wedding Cakes	Cake		Atlanta	Georgia	Atlanta	Atlanta custom wedding and groom's cake maker, with dummy cakes available and flavours and pricing listed online.			https://frostedpumpkin.com/	https://www.instagram.com/frostedpumpkincakes/
Platinum Cake Designs	Cake		Decatur	Georgia	Atlanta metro area	Pastry-chef-led private cake studio in Decatur making custom wedding cakes for the Atlanta area, with eco-conscious practices.	info@platinumcakedesigns.com	678-487-9797	https://www.platinumcakedesigns.com/	https://www.instagram.com/_platinumcakedesigns/
Cakes by Darcy	Cake		Roswell	Georgia	Atlanta area	Roswell bespoke wedding cake boutique run by a mother and daughter since 2004, working from a licensed cottage kitchen.	cakesbydarcy@gmail.com	770-993-2253	https://www.cakesbydarcy.com/	https://www.instagram.com/cakesbydarcy/
Custom Cakes by Liud	Cake	10518 Alpharetta Hwy	Roswell	Georgia	Roswell	Roswell Cuban bakery making custom wedding, groom's and quinceañera cakes, with Spanish spoken.		770-998-1731	https://www.customcakesbyliud.com/	
Atlanta Wedding Productions	Videography		Atlanta	Georgia	Atlanta and the Southeast	Atlanta wedding film studio producing cinematic wedding films since 2002 for couples across the Southeast.			https://atlwed.com/	https://www.instagram.com/atlwed/
Sarah Clawson Films	Videography		Atlanta	Georgia	Atlanta	Atlanta-based wedding videographer making refined, story-led films rather than trend-driven highlight reels.			https://sarahclawsonfilms.com/	https://www.instagram.com/sarahclawsonfilms/
Felix Wedding Films	Videography		Atlanta	Georgia	Atlanta and the Southeast	Atlanta documentary-style wedding videographers who combine candid footage with cinematic editing.	info@felixweddingfilms.com		https://www.felixweddingfilms.com/	https://www.instagram.com/felix_weddingfilms/
Catherine Vargas Films	Videography		Atlanta	Georgia	Atlanta	Atlanta wedding videographer specialising in Indian, South Asian and Muslim weddings and fine-art style film.	info@catherinevargas.com	404.539.5873	https://www.catherinevargas.com/	https://www.instagram.com/catherinevargasfilms/
Paul Patrick Films	Videography		Atlanta	Georgia	Atlanta	Atlanta videography and photography studio making wedding and engagement films, with separate wedding and event quote forms.	info@paulpatrickfilms.com	470-905-6784	https://www.paulpatrickfilms.com/	https://www.instagram.com/paulpatrickweddings/
247 Digital Media	Videography		Acworth	Georgia	Atlanta, Marietta, Alpharetta and Roswell	Acworth photo and video studio filming cinematic weddings across Atlanta, Marietta, Alpharetta, Roswell and Cobb County.	info@247digitalmedia.net	(678) 404-2479	https://247digitalmedia.net/	https://www.instagram.com/247digitalmediafilms/
`,
  },
  {
    name: "Augusta: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Stacey Brenner Photography	Photography		Augusta	Georgia	Augusta, Evans, Grovetown, Martinez, North Augusta and Aiken	Home-studio photographer covering weddings, elopements and newborns around Augusta, with set wedding pricing published on her site.			https://www.staceybrennerphotography.com/	https://www.instagram.com/staceybrennerphotography/
Elisa Rose Photo	Photography		Augusta	Georgia	Georgia, including Waynesboro, Hephzibah and Savannah	Augusta photographer shooting candid, emotion-led weddings and elopements, with six to ten hours of coverage and a published starting price.			https://elisarosephoto.com/	https://www.instagram.com/elisarosephoto/
Katie Jewell Co.	Photography		Augusta	Georgia	Nationwide	Augusta wedding photographer with over 120 weddings behind her, offering a luxury, personality-led approach and travelling nationwide.			https://katiejewellco.com/	https://www.instagram.com/katiejewellco/
Greg Boulus Events	Planning	449 Highland Ave	Augusta	Georgia	Georgia, South Carolina and destination weddings	Augusta planner and designer for weddings, social and corporate events, with invitations and paper goods alongside planning.		(706) 738-6298	https://www.gregboulusevents.com/	https://www.instagram.com/gregboulusevents/
Flowers on Broad	Florals	1030 Greene St	Augusta	Georgia	Augusta	Locally run Augusta flower shop with a wedding gallery and custom arrangements alongside same-day delivery.	sales@flowersonbroad.com	(706) 261-8555	https://flowersonbroad.com/	https://www.instagram.com/flowersonbroad1018/
Honeycomb Florals	Florals	1202 Town Park Lane, Suite 109	Evans	Georgia		Evans florist offering full-service or à la carte wedding design, from bouquets to wedding meadows, arbors and hanging installations.	honeycombflorals@gmail.com	(706) 901-2204	https://www.honeycombflorals.com/	https://www.instagram.com/honeycombflorals/
Ebony's Flowers & Gifts	Florals	2725 Milledgeville Rd	Augusta	Georgia	Augusta	Independent Augusta florist, open since 2016, offering custom wedding florals with consultations by phone or in person.	wecare@augustasflorist.com	(706) 481-1723	https://www.augustasflorist.com/	
Z Entertainment	Music		Augusta	Georgia	Augusta and the CSRA	Wedding DJ service mixing live for ceremonies, cocktail hours and receptions, with dance-floor music planned around each couple.			https://zentertainmentdj.com/	https://www.instagram.com/z_entertainment_dj/
Life of the Party	Music		Augusta	Georgia		Wedding-focused DJ with over twenty years' experience, adding custom lighting, photo booths and a 360 video booth.	AugustaWeddingDJ@gmail.com	(706) 399-4209	https://augustaweddingdj.com/	https://www.instagram.com/augustaweddingdj/
Roux's Catering	Catering	1244 Jones St	Augusta	Georgia	Augusta and the CSRA	Augusta caterer building custom plated or buffet wedding menus to a budget, including weddings at The Foundry and The Marbury Center.	robert@rouxscatering.com	(706) 724-2218	https://rouxscatering.com/	https://www.instagram.com/rouxscatering/
Tastefully Yours	Catering	2204 Ellis St	Augusta	Georgia	Augusta and the CSRA	Locally owned caterer offering wedding menus from hors d'oeuvres to full-course dinners, with sample small plates and late-night snacks.		(706) 481-0038	https://tastefullyyourscatering.net/	https://www.instagram.com/tastefullyyourscateringaugusta/
Berry's Catering + Events	Catering		Augusta	Georgia	The CSRA	Full-service caterer for weddings, corporate events and private parties, guiding couples through planning with floral-led presentation.			https://www.berryscatering.net/	https://www.instagram.com/berrys.catering/
GG Beauty Artistry	Hair & Makeup		Augusta	Georgia	Augusta, Georgia and South Carolina	Licensed cosmetologist offering on-site bridal hair and makeup for brides, wedding parties and rehearsal dinners.			https://www.ggbeautyartistry.com/	https://www.instagram.com/ggbeautyartistry/
Lindsay Taylor Bridal Hair and Makeup	Hair & Makeup		Evans	Georgia	Augusta area	Evans hairstylist and airbrush makeup artist who travels to the wedding, offering bridal upstyles and a morning-of timeline.			https://www.lindsaytaylor.us/	
Madelyn's Specialty Cakes	Cake		Evans	Georgia	Evans, Augusta, North Augusta and the CSRA	Evans home bakery making scratch-baked custom wedding cakes, with tastings and design consultations for couples.	madelyns.specialtycakes@gmail.com	(757) 773-8438	https://www.madelynspecialtycakes.com/	https://www.instagram.com/madelynspecialtycakes/
Hey Honey! Cakery	Cake	229 Fury's Ferry Rd, Suite 129	Augusta	Georgia	Augusta	Augusta bakery making scratch-baked wedding cakes, cupcakes and desserts, with delivery and setup for weddings.	heyhoneycakery@gmail.com	(706) 496-3971	https://www.heyhoneycakery.com/	https://www.instagram.com/heyhoneycakery/
10:31 Productions, LLC	Videography		Augusta	Georgia	The CSRA	Veteran-owned Augusta video company producing wedding videos of five to ten minutes alongside its commercial work.	Gerald@1031prod.com	(706) 834-9575	https://1031prod.com/	https://www.instagram.com/1031_productions_llc/
Joshua Mekhi	Videography		Augusta	Georgia	Augusta, the CSRA and the Southeast	Augusta photographer and videographer offering wedding film and photo coverage across the CSRA and wider Southeast.			https://www.joshuamekhi.com/wedding	https://www.instagram.com/followjoshuamekhi/
`,
  },
  {
    name: "Macon: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
ee photography	Photography		Macon	Georgia	Macon, Warner Robins, Perry, Monroe, Eatonton, Athens, Atlanta and Savannah	Travelling wedding and elopement photographer based in Macon, welcoming to LGBTQ+ and BIPOC couples.			https://eephotog.com/	https://www.instagram.com/ee_photog/
Kari Bendig Photography	Photography		Warner Robins	Georgia	Georgia, South Carolina and North Carolina	Warner Robins fine-art wedding photographer taking a limited number of weddings a year with a relaxed, personal approach.			https://www.karibendig.com/	
LLC Events	Planning		Macon	Georgia	Georgia and the Southeast coast	Macon planning team creating upscale weddings and events, from coastal tented celebrations to ballroom galas, since 2014.			https://llcevents.com/	https://www.instagram.com/llcevents/
Cherished Memories Florist and Events	Florals	5540 Thomaston Rd, Suite B	Macon	Georgia	Macon	Macon florist with a wedding and events line, local delivery, and custom arrangements alongside everyday bouquets.	cherishedmemoriesinc@hotmail.com	(478) 259-3243	https://cherishedmemoriesfloral.com/	
The Gift Garden	Florals		Macon	Georgia	Greater Macon	Macon florist offering ceremony and reception flowers, bouquets and centrepieces, with direct delivery to churches and venues.			https://thegiftgardenflorist.com/	
478 Events	Music		Macon	Georgia		Macon DJ company focused on weddings, including destination weddings, with custom lighting, audio setups and photo booths.	kevin@478events.com	(478) 957-6491	https://www.macondj.com/	https://www.instagram.com/478events/
Rockmaster "D" Productions	Music		Warner Robins	Georgia	Middle Georgia, including Warner Robins, Macon and Perry	Warner Robins wedding DJ with a published package covering emceeing, dance-floor lighting, wireless mics and an optional ceremony sound add-on.	rockmasterd@gmail.com	(478) 954-0899	https://rockmasterd.com/	https://www.instagram.com/rockmasterd/
Kobi Catering Co.	Catering		Macon	Georgia	Georgia	Family-owned Macon caterer specialising in formal event dining, with a wedding menu of salmon, chicken and steak plus classic sides.		(478) 422-0709	https://kobicatering.com/	https://www.instagram.com/kobicatering/
Cast Iron Catering	Catering		Macon	Georgia	Macon	Macon caterer with a dedicated weddings page, offering custom menus for wedding celebrations.			https://www.castironcateringmacon.com/	https://www.instagram.com/castironcateringmacon/
The Blush Macon	Hair & Makeup		Macon	Georgia	Macon, travelling anywhere	On-location event hair and makeup led by a Macon native with over 25 years' experience, including bridal looks.		(478) 262-8723	https://theblushmacon.com/	
Brooke Smith Beauty	Hair & Makeup		Warner Robins	Georgia	Middle Georgia and the Southeast	Bridal hair and makeup packages with trial run-throughs, bridesmaid services and an artist-for-the-day touch-up option.	makeupbybw@yahoo.com	(478) 952-9400	https://www.brookesmithbeauty.com/	https://www.instagram.com/brookewoodsmith/
LisaMae Cakes	Cake	213 Clinton St	Macon	Georgia	Macon	Appointment-only Mill Hill bakery making custom wedding and celebration cakes, with gluten-free options available.		(478) 654-6161	https://www.lisamaecakes.com/	https://www.instagram.com/lisamaecakes/
Mary Virginia Cakes	Cake		Macon	Georgia		Macon micro bakery making custom wedding and groom's cakes alongside petit fours, macarons and truffles.	mv@maryvirginiacakes.com	(478) 845-1372	https://www.maryvirginiacakes.com/	https://www.instagram.com/maryvirginiacakes/
Berserk Desserts	Cake		Macon	Georgia		Licensed cottage bakery in north Macon that takes wedding cake enquiries through a dedicated form.	ashleebump@berserkdesserts.com		https://www.berserkdesserts.com/	
Radiant Sky Films	Videography		Milledgeville	Georgia	Macon, Warner Robins, Athens and Atlanta	Milledgeville production company with over a decade filming weddings, live events and short films.	RadiantSkyFilms@gmail.com	(478) 239-3073	https://radiantskyfilms.com/	https://www.instagram.com/radiantskyfilms/
`,
  },
  {
    name: "Savannah: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Karen Norian Photography	Photography		Savannah	Georgia	Savannah, Tybee Island and beyond	Savannah photographer who shoots editorial-style weddings and elopements, with separate pages for intimate weddings and engagements.			https://www.karennorian.com/	https://www.instagram.com/karennorianphoto/
Swanson Signature Events	Planning		Savannah	Georgia	Savannah, the Lowcountry and Georgia	Savannah wedding planning and event design company offering full planning and day-of coordination, and pairing couples with a matched vendor team.	jennifer@swansonsignatureevents.com		https://swansonsignatureevents.com/	https://www.instagram.com/swansonsignatureevents/
Enchanted Alice Events	Planning		Savannah	Georgia	Savannah and destination weddings	Savannah planner known for themed and storybook weddings, offering full-service planning as well as month-of and day-of management.	Allie@EnchantedAlice.com	912-695-2104	https://enchantedalice.com/	https://www.instagram.com/enchantedaliceevents/
Port Town Collective	Planning		Savannah	Georgia	Savannah	Savannah planning and decor team that designs weddings around the city's historic venues, alongside private soirees and corporate events.			https://www.porttowncollective.com/	https://www.instagram.com/porttowncollective/
Lollygag Floral	Florals		Savannah	Georgia	Savannah, with travel	Savannah urban flower farm designing seasonal, locally grown wedding flowers, from bouquets to ceremony and table arrangements.	bre@lollygagfloral.com	912-844-4541	https://www.lollygagfloral.com/	https://www.instagram.com/lollygagfloral/
Cater Crew Savannah	Catering		Savannah	Georgia	Savannah	Savannah caterer for weddings and receptions alongside private parties and corporate events, with a menu and mobile bartending on offer.	CaterCrewSavannah@gmail.com	(978) 967-5925	https://www.catercrewsavannah.com/	https://www.instagram.com/catercrewsavannah/
IK Studio by Inga Krasileviciute	Hair & Makeup		Savannah	Georgia	Savannah, Hilton Head, Bluffton and Beaufort	Savannah bridal hair and makeup artist working on location or at her studio, with free travel to Hilton Head, Bluffton and Beaufort.	Info@ikmakeupartist.com	(912) 318-7513	https://www.ikmakeupartist.com/	https://www.instagram.com/inga_iamlit/
Kelsey Kent Makeup Artistry	Hair & Makeup		Savannah	Georgia	Savannah and surrounding areas	Savannah makeup artist focused on bridal and wedding-party makeup, with paid trial sessions and lashes included in her packages.	kelseykmakeup@gmail.com		https://www.kkmua.com/	https://www.instagram.com/kelseykmakeup/
Tierah Shaane Beauty	Hair & Makeup		Savannah	Georgia	Savannah, Charlotte and destination weddings	Bridal makeup artist split between Savannah and Charlotte, taking bridal inquiries online and travelling for destination weddings.	tshaanebeauty@gmail.com	704-309-3219	https://www.tierahshaanebeauty.com/	https://www.instagram.com/tierahshaanebeauty/
Savannah Rum Runners Bakery & Cafe	Cake	324 West Bolton Street	Savannah	Georgia	Savannah	Savannah bakery in the Victorian District making wedding and groom's cakes by consultation, with rum cakes and specialty cakes on the side.	info@savannahrumrunnersbakery.com	912-355-4177	https://savannahrumrunners.com/	
Shane Sebuck Films	Videography		Savannah	Georgia	Savannah, Charleston and worldwide	Wedding videographer split between Savannah and West Michigan, making highlight films and travelling to Charleston and further afield.			https://www.shanesebuckfilms.com/	https://www.instagram.com/shanesebuckfilms/
Manchester Productions	Videography		Savannah	Georgia	Savannah, Tybee Island and Hilton Head	Savannah photo and video team with wedding packages for photography, videography or both, including Tybee Island elopements.	jason@manchesterproductions.com	(704) 340-1500	https://manchesterproductions.com/	
`,
  },
  {
    name: "North Georgia Mountains: hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jolie Day Spa	Hair & Makeup	10 South Chestatee Street, Suite B	Dahlonega	Georgia	Dahlonega and North Georgia	Dahlonega Square spa offering bridal hair, makeup and pre-wedding treatments, with a bridal book and estimates by consultation.	Relax@joliedayspa.com	706-864-2772	https://www.joliedayspa.com/	https://www.instagram.com/joliedayspa/
Amberly at Structure Hair Studio	Hair & Makeup	1808 South Chestatee Street, Suite 206	Dahlonega	Georgia	Dahlonega and North Georgia	Dahlonega stylist who does hair and makeup for weddings from a salon suite, with a portfolio and list of endorsed vendors.	info@amberlyatshs.com	(678) 617-8796	https://acbridal.com/	https://www.instagram.com/amberly_structurehs/
Zell's Cottage Bakery	Cake	3294 Thompson Bridge Road	Gainesville	Georgia	Gainesville and North Georgia	Gainesville retail bakery making luxury wedding cakes with kitchen cakes for extra servings, and delivery for a mileage-based fee.	info@zellscottagebakery.com	470-729-2253	https://www.zellscottagebakery.com/	https://www.instagram.com/zellscottagebakery/
Artful Cakery by Julie	Cake		Flowery Branch	Georgia	North Georgia and Metro Atlanta	Family-run Flowery Branch cottage bakery making custom wedding and groom's cakes, delivered and set up at the venue.	artfulcakerybyjulie@gmail.com	770-315-1555	https://www.artfulcakery.com/	https://www.instagram.com/artfulcakerybyjulie/
Sugartopia Bakery	Cake	188 N. Main St.	Cornelia	Georgia	Cornelia and Northeast Georgia	Cornelia bakery with a wedding cake line alongside cupcakes, decorated cakes and a signature cake bar for dessert tables.		(706) 968-7777	https://www.sugartopiabakery.com/	https://www.instagram.com/sugartopiabakery/
Grasetin Productions	Videography		Chatsworth	Georgia	North Georgia	Chatsworth crew shooting wedding video and photography, with separate photo and video galleries on its site.	grasetinp@gmail.com	706-618-0109	https://grasetinproductions.com/	https://www.instagram.com/grasetin_productions/
`,
  },
  {
    name: "Athens: hair and makeup and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Cam Watson Beauty	Hair & Makeup		Athens	Georgia	Athens and surrounding counties	Licensed makeup artist with a studio outside Athens who does bridal and wedding-party makeup and travels across Georgia.	camwatsonbeauty@gmail.com	706-870-5815	https://www.camwatsonbeauty.me/	
B & B Videography	Videography		Athens	Georgia	Athens and North Georgia	Athens-based wedding videographer offering teaser, highlight and cinematic films plus rehearsal dinner coverage.	bailey.brettvideo@gmail.com		https://www.bandbvideography.com/	
`,
  },
];

export default batches;
