import type { VendorBatch } from "@/lib/vendor-batches";

// Hawaii vendor batches. Every row's State is "Hawaii". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Honolulu: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Megan Moura Photography	Photography	928 Nuuanu Ave, Suite 403	Honolulu	Hawaii	Oahu and beyond	Honolulu photographer with a Chinatown studio, capturing timeless, natural wedding coverage at beaches and venues across Oahu.		(808) 285-8770	https://meganmoura.com	https://www.instagram.com/megan_moura/
Shannon Sasaki Photography	Photography		Honolulu	Hawaii	Oahu, with travel to outer islands and the mainland	Oahu-born photographer whose vibrant, colourful style plays up Hawaii's blue water and green mountains for weddings and engagements.	shannonsasakiphoto@gmail.com	(808) 224-7974	https://www.shannonsasakiphotography.com	https://www.instagram.com/shannon_sasaki/
Michelle Chan Photography	Photography		Honolulu	Hawaii	Hawaii and beyond	Honolulu-based photographer specialising in intimate weddings and elopements around Oahu, plus proposals and engagement sessions.			https://www.michellechanphotography.com	https://www.instagram.com/michellechanphoto/
Aloha Bridal Connections	Planning		Honolulu	Hawaii	Oahu	Honolulu planning team offering day-of, hybrid and full-service packages for destination couples, with long-standing local vendor contacts.		(808) 371-8363	https://www.alohabridalconnections.com	https://www.instagram.com/abcweddings/
Perfection – An International Event Company	Planning		Honolulu	Hawaii	Hawaiian Islands, California and international	Woman-owned Honolulu firm founded in 2014 handling full planning, partial planning and day-of coordination for destination weddings and elopements.	gina@perfectioninternational.com	(808) 779-9910	https://perfectioninternational.com	https://www.instagram.com/perfection_international/
Love Letter Weddings	Planning		Honolulu	Hawaii	Oahu	Oahu planning and floral design studio for colourful destination weddings, with full planning, guided planning or florals on their own.	hello@loveletterweddings.com	(808) 342-5137	https://loveletterweddings.com	https://www.instagram.com/love_letter_weddings/
Watanabe Floral	Florals	1618 N Nimitz Hwy	Honolulu	Hawaii	Oahu	Family florist operating for around eight decades, with a dedicated lei department, micro-wedding packages and full ceremony and reception flowers.	info@watanabefloral.com	(808) 832-9360	https://www.watanabefloral.com	https://www.instagram.com/watanabefloral/
Sweet Blossoms Hawaii	Florals	1014 Kapahulu Ave	Honolulu	Hawaii	Honolulu, from the airport to Sandy Beach	Kapahulu flower shop making wedding bouquets, hair pieces and custom lei, including traditional pakalana and crown flower designs.	irene@sweetblossomshawaii.com	(808) 732-7668	https://sweetblossomshawaii.com	https://www.instagram.com/sweetblossomshawaii/
Aloha Florals 808	Florals		Waipahu	Hawaii	Oahu	Central Oahu wedding florist using locally grown tropical blooms for arches, bouquets, lei po'o and guest lei, with published starting packages.	brandi@alohaflorals808.com		https://alohaflorals808.com	https://www.instagram.com/alohaflorals808/
Kaululani Florals	Florals		Honolulu	Hawaii	Oahu	Woman-owned Kaimuki studio creating Hawaiian-inspired wedding florals and lei po'o with cultural intention, plus floral workshops.	kaululaniflorals@gmail.com	(808) 445-1281	https://kaululaniflorals.com	https://www.instagram.com/kaululaniflorals/
Frobaby Productions	Music		Haleiwa	Hawaii	Oahu, with select events on Maui, Kauai and Hawaii Island	North Shore DJ and MC team mixing receptions live, with ceremony sound, an online music-planning app and experience of multicultural weddings.	events@frobabyproductions.com	(808) 427-8080	https://frobabyproductions.com	https://www.instagram.com/frobabyproductions/
Kani Events	Music		Kapolei	Hawaii	Hawaii	Native Hawaiian-owned, LGBTQ-friendly company offering wedding DJ and MC work, a kahu officiant, silent disco and live sound.	info@kanievents.com	(808) 780-1894	https://www.kanievents.com	https://www.instagram.com/kanievents/
Ono Kine Entertainment	Music		Mililani	Hawaii	Hawaii	Mililani outfit pairing live ukulele and Hawaiian music for ceremonies with DJ and MC service for receptions, plus hula dancers on request.	onokineentertainment@yahoo.com	(808) 387-4477	https://onokineentertainment.com	
Mana Music Hawaii	Music		Honolulu	Hawaii	Oahu, Hawaii Island, Maui, Lanai and Kauai	Classical strings led by a Hawaii Symphony Orchestra cellist, offering solo cello, duos and string quartets for ceremonies and receptions.	Josh@manamusichawaii.com		https://manamusichawaii.com	https://www.instagram.com/manamusichawaii/
Marin Pang	Hair & Makeup	449 Kapahulu Ave, Suite 204	Honolulu	Hawaii	Oahu	Licensed cosmetologist working from a Waikiki studio or on location, with humidity-resistant bridal hair and makeup for beach and resort weddings.	marinmorin@gmail.com	(808) 729-2216	https://marinpang.com	
Ke Nui Kitchen	Catering	59-864 Kamehameha Hwy	Haleiwa	Hawaii		North Shore caterer based in Waimea Valley, cooking local, farm-to-table Hawaiian menus for luaus and weddings, plus dessert bars and cocktails.	info@kenuikitchen.com	(808) 638-5000	https://kenuikitchen.com	https://www.instagram.com/kenuikitchen/
Cake Works HI	Cake	2820 S King Street	Honolulu	Hawaii		Moiliili bakery making tiered wedding cakes in buttercream, whipped cream or fondant, with mailed tasting boxes and design consultations.	custom@cakeworkshi.com	(808) 946-4333	https://cakeworkshi.com/honolulu-cake-works-hi-weddings	https://www.instagram.com/cakeworks_hi/
Pua Cake Studio	Cake	71 S Kamehameha Hwy	Wahiawa	Hawaii		Central Oahu studio known for hand-piped buttercream flower cakes, with published wedding packages pairing tiered cakes and cupcakes.		(808) 206-3349	https://puacakestudiohawaii.com	https://www.instagram.com/puacakestudiohawaii/
A Cake Life	Cake	2320 S King St	Honolulu	Hawaii	Oahu	Custom cake shop running since 2009, designing one-off wedding cakes to each couple's brief, with local flavours such as passion fruit and guava.	info@acakelife.com	(808) 542-0131	https://acakelife.com	https://www.instagram.com/acakelife/
Aloha Life Media	Videography		Mililani	Hawaii	Oahu	Husband-and-wife film team founded in 2022, shooting candid, cinematic wedding videos with drone coverage and social clips.			https://alohalifemedia.com	https://www.instagram.com/alohalifemedia/
Face Art Beauty	Hair & Makeup	1436 Young St, Suite 306	Honolulu	Hawaii	Oahu	Honolulu bridal hair and makeup team with a calm, collaborative approach, styling destination weddings and elopements across Oahu.	info@faceartbeauty.com	(808) 636-4761	https://www.faceartbeauty.com	https://www.instagram.com/faceartbeauty/
Makeup by Kayla Scheffler	Hair & Makeup		Kailua	Hawaii	Oahu	Kailua-based mobile artist doing on-location bridal makeup and hair, with trials, bridal party and groom grooming on published price lists.	kaylaschef@gmail.com		https://www.makeupbykaylascheffler.com	https://www.instagram.com/makeupbykaylascheffler/
Memoirs Hawaii	Catering	55 Merchant St, Suite 20	Honolulu	Hawaii	Oahu	Downtown Honolulu caterer with more than 17 years on Oahu, providing full-service menus, bar and staffing for large weddings; sister company of 1311 Events.	sales@memoirshawaii.com	(808) 744-1885	https://memoirshawaii.com	https://www.instagram.com/memoirshawaii/
Nomadic Wedding Films	Videography		Honolulu	Hawaii	Hawaii and worldwide	Honolulu filmmaker making unscripted, documentary-style wedding films, with multi-day coverage as standard for destination couples.	chris@nomadicweddingfilms.com		https://nomadicweddingfilms.com	
Small Hour Films	Videography		Honolulu	Hawaii	Oahu	Oahu video studio with a narrative and documentary film background, covering elopements, engagements and full wedding days with customisable packages.	info@smallhourfilms.com		https://www.smallhourfilms.com	https://www.instagram.com/smallhourfilmsllc/
Chef Elmer's Island Cuisine	Catering	95-1840 Meheula Pkwy #5	Mililani	Hawaii		Catering arm of chef Elmer Guzman, cooking local favourites with a twist alongside fine-dining and sustainable menus for weddings and events since 2012.	info@chefelmer.com		https://www.chefelmersislandcuisine.com	https://www.instagram.com/chefelmersislandcuisine/`,
  },
];

export default batches;
