import type { VendorBatch } from "@/lib/vendor-batches";

// Hawaii vendor batches. Every row's State is "Hawaii". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Honolulu: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Megan Moura Photography	Photography	928 Nuuanu Ave, Suite 403	Honolulu	Hawaii	Oahu and beyond	Honolulu photographer with a Chinatown studio, capturing timeless, natural wedding coverage at beaches and venues across Oahu.		(808) 285-8770	https://meganmoura.com	https://www.instagram.com/megan_moura/
Shannon Sasaki Photography	Photography		Honolulu	Hawaii	Oahu, with travel to outer islands and the mainland	Oahu-born photographer whose vibrant, colourful style plays up Hawaii's blue water and green mountains for weddings and engagements.	shannonsasakiphoto@gmail.com	(808) 224-7974	https://www.shannonsasakiphotography.com	https://www.instagram.com/shannon_sasaki/
Michelle Chan Photography	Photography		Honolulu	Hawaii	Hawaii and beyond	Honolulu-based photographer specialising in intimate weddings and elopements around Oahu, plus proposals and engagement sessions.			https://www.michellechanphotography.com	https://www.instagram.com/michellechanphoto/
Aloha Bridal Connections	Planning		Honolulu	Hawaii	Oahu	Honolulu planning team offering day-of, hybrid and full-service packages for destination couples, with long-standing local vendor contacts.		(808) 371-8363	https://www.alohabridalconnections.com	https://www.instagram.com/abcweddings/
Perfection – An International Event Company	Planning		Honolulu	Hawaii	Hawaiian Islands, California and international	Woman-owned Honolulu firm founded in 2014 handling full planning, partial planning and day-of coordination for destination weddings and elopements.	gina@perfectioninternational.com	(808) 779-9910	https://perfectioninternational.com	https://www.instagram.com/perfection_international/
Love Letter Weddings	Planning		Honolulu	Hawaii	Oahu	Oahu planning and floral design studio for colourful destination weddings, with full planning, guided planning or florals on their own.	hello@loveletterweddings.com	(808) 342-5137	https://loveletterweddings.com	https://www.instagram.com/love_letter_weddings/
Watanabe Floral	Florals	1618 N Nimitz Hwy	Honolulu	Hawaii	Oahu	Family florist operating for around eight decades, with a dedicated lei department, micro-wedding packages and full ceremony and reception flowers.	info@watanabefloral.com	(808) 832-9360	https://www.watanabefloral.com	https://www.instagram.com/watanabefloral/
Sweet Blossoms Hawaii	Florals	1014 Kapahulu Ave	Honolulu	Hawaii	Honolulu, from the airport to Sandy Beach	Kapahulu flower shop making wedding bouquets, hair pieces and custom lei, including traditional pakalana and crown flower designs.	irene@sweetblossomshawaii.com	(808) 732-7668	https://sweetblossomshawaii.com	https://www.instagram.com/sweetblossomshawaii/
Aloha Florals 808	Florals		Waipahu	Hawaii	Oahu	Central Oahu wedding florist using locally grown tropical blooms for arches, bouquets, lei po'o and guest lei, with published starting packages.	brandi@alohaflorals808.com		https://alohaflorals808.com	https://www.instagram.com/alohaflorals808/
Kaululani Florals	Florals		Honolulu	Hawaii	Oahu	Woman-owned Kaimuki studio creating Hawaiian-inspired wedding florals and lei po'o with cultural intention, plus floral workshops.	kaululaniflorals@gmail.com	(808) 445-1281	https://kaululaniflorals.com	https://www.instagram.com/kaululaniflorals/
Frobaby Productions	Music		Haleiwa	Hawaii	Oahu, with select events on Maui, Kauai and Hawaii Island	North Shore DJ and MC team mixing receptions live, with ceremony sound, an online music-planning app and experience of multicultural weddings.	events@frobabyproductions.com	(808) 427-8080	https://frobabyproductions.com	https://www.instagram.com/frobabyproductions/
Kani Events	Music		Kapolei	Hawaii	Hawaii	Native Hawaiian-owned, LGBTQ-friendly company offering wedding DJ and MC work, a kahu officiant, silent disco and live sound.	info@kanievents.com	(808) 780-1894	https://www.kanievents.com	https://www.instagram.com/kanievents/
Ono Kine Entertainment	Music		Mililani	Hawaii	Hawaii	Mililani outfit pairing live ukulele and Hawaiian music for ceremonies with DJ and MC service for receptions, plus hula dancers on request.	onokineentertainment@yahoo.com	(808) 387-4477	https://onokineentertainment.com	
Mana Music Hawaii	Music		Honolulu	Hawaii	Oahu, Hawaii Island, Maui, Lanai and Kauai	Classical strings led by a Hawaii Symphony Orchestra cellist, offering solo cello, duos and string quartets for ceremonies and receptions.	Josh@manamusichawaii.com		https://manamusichawaii.com	https://www.instagram.com/manamusichawaii/
Marin Pang	Hair & Makeup	449 Kapahulu Ave, Suite 204	Honolulu	Hawaii	Oahu	Licensed cosmetologist working from a Waikiki studio or on location, with humidity-resistant bridal hair and makeup for beach and resort weddings.	marinmorin@gmail.com	(808) 729-2216	https://marinpang.com	
Ke Nui Kitchen	Catering	59-864 Kamehameha Hwy	Haleiwa	Hawaii		North Shore caterer based in Waimea Valley, cooking local, farm-to-table Hawaiian menus for luaus and weddings, plus dessert bars and cocktails.	info@kenuikitchen.com	(808) 638-5000	https://kenuikitchen.com	https://www.instagram.com/kenuikitchen/
Cake Works HI	Cake	2820 S King Street	Honolulu	Hawaii		Moiliili bakery making tiered wedding cakes in buttercream, whipped cream or fondant, with mailed tasting boxes and design consultations.	custom@cakeworkshi.com	(808) 946-4333	https://cakeworkshi.com/honolulu-cake-works-hi-weddings	https://www.instagram.com/cakeworks_hi/
Pua Cake Studio	Cake	71 S Kamehameha Hwy	Wahiawa	Hawaii		Central Oahu studio known for hand-piped buttercream flower cakes, with published wedding packages pairing tiered cakes and cupcakes.			https://puacakestudiohawaii.com	https://www.instagram.com/puacakestudiohawaii/
A Cake Life	Cake	2320 S King St	Honolulu	Hawaii	Oahu	Custom cake shop running since 2009, designing one-off wedding cakes to each couple's brief, with local flavours such as passion fruit and guava.	info@acakelife.com	(808) 542-0131	https://acakelife.com	https://www.instagram.com/acakelife/
Aloha Life Media	Videography		Mililani	Hawaii	Oahu	Husband-and-wife film team founded in 2022, shooting candid, cinematic wedding videos with drone coverage and social clips.			https://alohalifemedia.com	https://www.instagram.com/alohalifemedia/
Face Art Beauty	Hair & Makeup	1436 Young St, Suite 306	Honolulu	Hawaii	Oahu	Honolulu bridal hair and makeup team with a calm, collaborative approach, styling destination weddings and elopements across Oahu.	info@faceartbeauty.com	(808) 636-4761	https://www.faceartbeauty.com	https://www.instagram.com/faceartbeauty/
Makeup by Kayla Scheffler	Hair & Makeup		Kailua	Hawaii	Oahu	Kailua-based mobile artist doing on-location bridal makeup and hair, with trials, bridal party and groom grooming on published price lists.	kaylaschef@gmail.com		https://www.makeupbykaylascheffler.com	https://www.instagram.com/makeupbykaylascheffler/
Memoirs Hawaii	Catering	55 Merchant St, Suite 20	Honolulu	Hawaii	Oahu	Downtown Honolulu caterer with more than 17 years on Oahu, providing full-service menus, bar and staffing for large weddings; sister company of 1311 Events.	sales@memoirshawaii.com	(808) 744-1885	https://memoirshawaii.com	https://www.instagram.com/memoirshawaii/
Nomadic Wedding Films	Videography		Honolulu	Hawaii	Hawaii and worldwide	Honolulu filmmaker making unscripted, documentary-style wedding films, with multi-day coverage as standard for destination couples.	chris@nomadicweddingfilms.com		https://nomadicweddingfilms.com	
Small Hour Films	Videography		Honolulu	Hawaii	Oahu	Oahu video studio with a narrative and documentary film background, covering elopements, engagements and full wedding days with customisable packages.	info@smallhourfilms.com		https://www.smallhourfilms.com	https://www.instagram.com/smallhourfilmsllc/
Chef Elmer's Island Cuisine	Catering	95-1840 Meheula Pkwy #5	Mililani	Hawaii		Catering arm of chef Elmer Guzman, cooking local favourites with a twist alongside fine-dining and sustainable menus for weddings and events since 2012.	info@chefelmer.com		https://www.chefelmersislandcuisine.com	https://www.instagram.com/chefelmersislandcuisine/`,
  },
  {
    name: "Maui: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hitched in Maui	Photography		Kihei	Hawaii	Maui	Lexi McGhee photographs romantic, natural weddings and elopements on Maui, drawing on time spent as a planner and officiant.			https://hitchedinmaui.com	https://www.instagram.com/hitchedinmaui/
Lesley Castle Photo	Photography		Kihei	Hawaii	Maui, the neighbouring Hawaiian islands and destinations	Kihei-based photographer offering artistic wedding, elopement and couples sessions on Maui, plus brand work and travel to the other islands.	lesleycastle@gmail.com	808-631-2011	https://www.lesleycastlephoto.com	https://www.instagram.com/lesleycastlephoto/
Tad Craig Photography	Photography		Paia	Hawaii	Maui	Paia photographer covering Maui weddings, elopements and surprise proposals, with experience at resorts such as the Four Seasons.	tad@tadcraigphotography.com	808-283-0617	https://tadcraigphotography.com	https://www.instagram.com/tadcraigphotography/
Happily Maui'd	Planning		Lahaina	Hawaii	Maui	Boutique planner running all-inclusive Maui elopements and destination weddings, with traditional Hawaiian ceremony options and day-of coordination.	contact@happilymauid.com		https://happilymauid.com	https://www.instagram.com/happilymauid/
Kolowi Events	Planning		Kihei	Hawaii	Maui	All-inclusive Maui elopement and small-wedding packages covering permits, officiants, lei, live music and hotel transport (formerly A Paradise Dream Wedding).	info@kolowievents.com	(808) 800-4733	https://www.kolowievents.com	https://www.instagram.com/mauiweddings/
Maui Aloha Weddings	Planning		Kihei	Hawaii	Maui	Family-run Kihei planner offering named beach and venue wedding packages, including LGBTQ, adventure and vow-renewal options.		808-344-8805	https://mauialohaweddings.com	https://www.instagram.com/mauialohaweddings/
Kahului Florist	Florals	201 Dairy Rd	Kahului	Hawaii	Maui	Long-running Kahului flower shop making wedding collections and wearable florals, including traditional maile and haku lei.	kahului@mauiflowerco.com	(808) 877-3951	https://kahuluiflorist.com	https://www.instagram.com/kahuluiflorist/
Asa Flowers	Florals		Wailuku	Hawaii	Maui	Wailuku floral studio, trading since 1982, designing wedding, private-event and resort florals exclusively for celebrations on Maui.	will@asaflowers.com	808-249-8845	https://www.asaflowers.com	https://www.instagram.com/asaflowers/
Marvin Tevaga Music	Music		Lahaina	Hawaii	Maui	Maui-born singer and ukulele player performing island and Hawaiian songs at wedding ceremonies and receptions, and also available as officiant.	marvintevagamusic@gmail.com		https://www.marvintevagamusic.com	https://www.instagram.com/marvint_music/
Maui DJ Services	Music		Kihei	Hawaii	Maui and Oahu	Kihei DJ and MC company for weddings, adding uplighting, cold-spark fountains, an open-air photo booth and ceremony sound systems.	info@mauidjservices.com	808-419-0445	https://www.mauidjservices.com	https://www.instagram.com/mauidjservices/
DJ Boomshot	Music		Wailuku	Hawaii	Maui	Maui mobile DJ and MC for wedding receptions, also booking live acts such as The Lamonts and Island Grooves.		(808) 281-0292	https://djboomshot.com	
Cafe O'Lei Catering	Catering	2439 South Kihei Rd	Kihei	Hawaii	Maui	Catering arm of a family-owned Maui restaurant group, cooking plated and buffet wedding menus on-site or at its own Waikapu and Kihei spaces.	cherub@cafeoleirestaurants.com	808-442-7742	https://www.cafeoleirestaurants.com/cafe-olei-catering	https://www.instagram.com/cafeolei_maui/
Maui Catering Services	Catering		Paia	Hawaii	Maui	Paia caterer led by chef Tiffany Ward, known from Food Network's Extreme Chef, serving gourmet wedding menus with her own service team.	mauicateringservices@gmail.com	808-344-0058	https://www.mauicateringservices.com	
Honu Cuisine	Catering		Haiku	Hawaii	Maui	Private chef Hiram Peri cooks farm-to-table menus for Maui weddings and intimate dinners, drawing on over 30 years in kitchens.	hiramgperi@gmail.com	808-633-6533	https://www.honucuisine.com	https://www.instagram.com/chef_hiram/
Love and Beauty Maui	Hair & Makeup	2439 S Kihei Rd, Suite 208 B	Kihei	Hawaii	All of Maui, Lanai and the other Hawaiian islands	Kihei salon team doing mobile bridal hair and airbrush makeup for brides and wedding parties across Maui, plus trials and spray tans.		(808) 344-4453	https://loveandbeautymaui.com	https://www.instagram.com/loveandbeautymaui/
Simply Beauty Maui	Hair & Makeup		Kula	Hawaii	Maui	Upcountry-based team offering on-location bridal hair and makeup for Maui weddings, elopements and shoots, with styles built to last in the humidity.	hello@simplybeautymaui.com	808-264-6360	https://simplybeautymaui.com	https://www.instagram.com/simplybeautymaui/
Maui Wedding Cakes	Cake		Kihei	Hawaii	Maui	Kihei bakery run by pastry chef Casey Logsdon and designer Cheryl Logsdon, making custom wedding cakes and also offering dove releases.	weddingcake@hawaii.rr.com	(808) 283-7068	https://mauiweddingcakes.com	https://www.instagram.com/mauiweddingcakes/
Cymz Sweet Kre8tionz	Cake	153 Maa Street	Kahului	Hawaii	Maui	Kahului bakery making custom wedding cakes and dessert spreads for Maui celebrations, with nationwide shipping of some treats.	cymzsweetkre8tionz@gmail.com	(808) 757-6603	https://www.cymzsweetkre8tionz.com	https://www.instagram.com/cymz_sweet_kre8tionz_llc/
No Ka 'Oi Films	Videography		Lahaina	Hawaii	Maui, the other Hawaiian islands and destinations	Caleb films natural, joyful wedding and elopement videos on Maui and every Hawaiian island, with an analogue film option.	caleb@nokaoifilms.com	(503) 881-5201	https://www.nokaoifilms.com	https://www.instagram.com/nokaoimedia/
Stephan Boeker Films	Videography		Makawao	Hawaii	Maui, Hawaii Island and destinations	Emmy-winning Makawao filmmaker making documentary-style wedding films at Maui resorts and beyond, with photography and live webcasts too.	stephan@stephanboekerfilms.com		https://stephanboekerfilms.com	https://www.instagram.com/stephanboekerfilms/
Gaucho Visual	Videography		Wailuku	Hawaii	Maui	Two Argentinian cinematographers filming Maui weddings and elopements in an unobtrusive, fly-on-the-wall style.			https://www.gauchovisual.com	https://www.instagram.com/gauchovisual/
Hi Focused	Videography		Wailuku	Hawaii	Maui	Maui-born Jordan Nagasako's studio has filmed weddings for 15 years, adding licensed drone footage and now photography.	jordan@hifocused.com	808-281-1530	https://hifocused.com	https://www.instagram.com/hifocused/`,
  },
  {
    name: "Maui: florals, hair and makeup, and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Bella Bloom Maui	Florals	161 Wailea Ike Pl, #D101	Wailea	Hawaii	Maui	Wailea Town Center flower boutique designing wedding bouquets, ceremony arches, centrepieces and installations, set up on the day by its own team.	bellabloommaui@gmail.com	808.875.1919	https://bellabloommaui.com	https://www.instagram.com/bellabloommaui/
Fernhouse	Florals		Haiku	Hawaii	Maui, the neighbour islands and the West Coast	Woman-owned Maui floral studio growing its own flowers, designing bespoke wedding florals with full install and breakdown across the islands.			https://fernhousemaui.com	https://www.instagram.com/fernhouseflowers/
Bridal by Jen	Hair & Makeup		Wailuku	Hawaii	Maui	Wailuku-based artist doing bridal hair and makeup for Maui elopements and weddings, with experience at weddings from Montauk to Maui.	jencmakeupartist@gmail.com	714-350-7853	https://bridalbyjen.com	https://www.instagram.com/bridal.by.jen/
Makeup and Talent Hawaii	Hair & Makeup		Kihei	Hawaii		Kihei team led by makeup artist and cosmetics designer Kymberly Marr, offering bridal makeup and hair alongside editorial and fashion work.		(808) 283-2779	https://makeupandtalenthawaii.com	https://www.instagram.com/makeupandtalenthawaii/
Cake Fanatics	Cake		Lahaina	Hawaii	Maui	Maui custom cake studio led by artist EmmaLee, making wedding cakes and dessert buffets for over 14 years, with tastings by appointment.	emmscakes@gmail.com	(808) 214-7767	https://cakefanaticsmaui.com	https://www.instagram.com/cakefanatics/`,
  },
  {
    name: "Kauai: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Photography by Keri Cooper	Photography		Lihue	Hawaii	Kauai, Maui and Oahu	Kauai wedding and engagement photographer with an adventurous, story-led style, often taking couples off the beaten path around the island.	hello@kericooper.com	808-652-4207	https://kericooper.com/	https://www.instagram.com/weddingphotographerkauai/
Ikaika Photography	Photography		Princeville	Hawaii	Kauai	North Shore photographer Ikaika Pidot, covering weddings and elopements across Kauai, with combined photo and video packages on offer.	ikaika.pidot@gmail.com	808-429-1911	https://www.ikaika.photo/	https://www.instagram.com/ikaikaphotography/
Legacy Events Kauai	Planning		Lihue	Hawaii	Kauai	Full-service wedding and event planning company based on Kauai, specialising in destination weddings for couples planning from afar.			https://legacyeventskauai.com/	https://www.instagram.com/legacyeventskauai/
Alohana Kauai Weddings	Planning		Kapaa	Hawaii	Hanalei, Princeville, Kapaa, Poipu and the rest of Kauai	Island-based planner handling full planning, coordination and elopement packages at beaches, gardens and private estates around Kauai.	diana@alohanakauaiweddings.com	808-823-0077	https://alohanakauaiweddings.com/	https://www.instagram.com/kauaiweddingplanners/
Kealoha Flowers	Florals		Lihue	Hawaii	Kauai	Kauai florist making wedding bouquets, leis and ceremony flowers for couples marrying at beaches and venues around the island.	kealohaflowerskauai@gmail.com	808-755-5946	https://www.kealohaflowers.com/	
Ho'omohala Floral and Design	Florals		Koloa	Hawaii	Kauai and the neighbour islands	Boutique South Shore florist creating wedding flowers and décor from intimate dinners to large affairs, with coordination help too.	hoomohalainfo@gmail.com	808-652-4423	https://hoomohalaflorals.com/	
Strings of Hawaii	Music		Lihue	Hawaii	Kauai and the other Hawaiian islands	Classical violinist Kaycee Parker's ensemble, playing ceremony and cocktail-hour music at weddings across Kauai since 2007.	stringsofhawaii@gmail.com	808-482-0686	https://www.stringsofhawaii.com/	https://www.instagram.com/stringsofhawaii/
Soul Fire Productions	Music		Lihue	Hawaii	Kauai	Kauai entertainment company supplying wedding DJs and live music, plus fire dancers and Polynesian performers for receptions.	Kaia@SoulFireProductions.com	808-651-8228	https://www.soulfireproductions.com/	https://www.instagram.com/soulfireproductions/
Kickshaws	Catering	4556 Awawa Rd	Hanapepe	Hawaii	Kauai	Hanapepe food truck whose chef caters weddings anywhere on Kauai with custom menus at relaxed, budget-friendly prices.	kickshaws808@gmail.com	808-651-6750	https://www.kickshaws808.com/	https://www.instagram.com/kickshaws808/
Bridal Kauai	Hair & Makeup		Lihue	Hawaii	Kauai	Bridal hair stylist travelling to venues around Kauai for wedding-day styling, sunrise elopements and special-occasion looks.	hello@bridalkauai.com		https://www.bridalkauai.com/	https://www.instagram.com/bridalkauai/
Echelon Beauty Kauai	Hair & Makeup		Lihue	Hawaii	Kauai	Bridal hair and makeup team on Kauai focused on long-wearing looks that hold up through outdoor heat, humidity and sea breeze.			https://www.echelonbeautykauai.com/	
Ko Bakery + Coffee	Cake	1611 Haleukana St, #3	Lihue	Hawaii	Kauai	Lihue bakery making wedding cakes, cheesecakes and tarts that are certified Kauai made, using island ingredients and flavours.	aloha@kobakery.com	808-212-9437	https://kobakery.com/	https://www.instagram.com/kobakery/
Orly Patisserie Kauai	Cake	4454 Nuhou St	Lihue	Hawaii	Kauai	Lihue patisserie baking custom wedding cakes with published prices, known for island flavours such as ube and lilikoi.	orders@orlypatisseriekauai.com	808-378-4343	https://orlypatisseriekauai.com/	
10th Letter Media	Videography		Lihue	Hawaii	Kauai	Kauai-based wedding videographer producing cinematic highlight films of ceremonies and receptions around the island.	info@10thlettermedia.com		https://10thlettermedia.com/	https://www.instagram.com/10thlettermedia/`,
  },
  {
    name: "Big Island: photography, planning, florals, music, catering, hair and makeup and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Laura Pittman Photography	Photography		Kailua-Kona	Hawaii	The Big Island and the other Hawaiian islands	Kona photographer shooting joyful, natural wedding and couples coverage on the Big Island, with in-water sessions as a speciality.	laura@laurapittmanphotography.com		https://laurapittmanphotography.com/	https://www.instagram.com/laurapittmanphotography/
Fletch Photography	Photography		Kailua-Kona	Hawaii	Kona Coast	Kona Coast photography company covering weddings at Big Island resorts and beaches, alongside engagement and portrait work.			https://www.fletchhawaii.com/	https://www.instagram.com/fletchphotography/
Tetiana Me Photography	Photography		Kailua-Kona	Hawaii	The Big Island	Kailua-Kona photographer offering relaxed elopement, wedding and couples sessions, helping visitors pick the beach and light.			https://www.tetianamephotography.com/	https://www.instagram.com/tetiana__me_photography/
Naupaka Events & Weddings	Planning		Kamuela	Hawaii	The Big Island	Waimea-based coordination firm planning Big Island weddings and events, and the booking agent for Anna Ranch weddings.	Dayna@NaupakaEvents.com	808-430-4362	https://www.naupakaevents.com/	https://www.instagram.com/naupakaevents/
Simple Kona Weddings	Planning		Kailua-Kona	Hawaii	The Big Island	Kona officiant-led service arranging simple beach weddings, elopements and vow renewals with Hawaiian elements, LGBTQ+ welcome.	hawaiianweddings808@gmail.com	808-896-7955	https://www.simplekonaweddings.com/	
Grace Flowers Hawaii	Florals	45-502 Rickard Pl	Honokaa	Hawaii	The Big Island	Honokaa flower shop designing wedding flowers for Kohala Coast resorts and Big Island venues, from bouquets to arches.	events@graceflowershawaii.com	808-443-3999	https://www.graceflowershawaii.com/	https://www.instagram.com/graceflowershawaii/
Lalamilo Flower Girl	Florals		Kamuela	Hawaii	The Big Island	Waimea florist designing sustainable wedding arrangements from her family's flower farm, sourcing locally wherever possible.	lalamiloflowergirl@gmail.com		https://lalamiloflowergirl.com/	https://www.instagram.com/lalamiloflowergirl/
Hawaii Sound & Vision	Music		Kailua-Kona	Hawaii	The Big Island	Big Island DJ and audio-visual company handling wedding music, ceremony sound, dance floors and lighting, plus band support.	aloha@hawaiisav.com	808-982-8330	https://www.hawaiisav.com/	
Papa Kona Events & Catering	Catering	75-5770 Alii Dr	Kailua-Kona	Hawaii	The Big Island	Kailua-Kona caterer and oceanside event space on Alii Drive, cooking custom menus for weddings on site or anywhere on the island.	aloha@papakona.com	808-300-0044	https://www.papakonaevents.com/	https://www.instagram.com/papakonaevents/
Indigo Grace Artistry	Hair & Makeup		Kailua-Kona	Hawaii	The Big Island	Kona-based hair and makeup team working with destination brides and wedding parties at resorts across the Big Island.	indigograceartistry@gmail.com	808-217-4998	https://www.indigograceartistry.com/	https://www.instagram.com/indigograceartistry/
Kassi Bissman Beauty	Hair & Makeup		Kailua-Kona	Hawaii		Kona makeup artist and licensed hairstylist with over a decade of experience, styling brides and bridal parties on the Big Island.	kassi@bigislandbeautyandbridal.com	808-756-7280	https://www.kassibissmanbeauty.com/	https://www.instagram.com/kassi.bissman.beauty/
240 Media	Videography		Kailua-Kona	Hawaii	The Big Island	Kailua-Kona production company, founded in 2015, filming wedding highlight reels and features, with photo, DJ and photo booth add-ons.	info@240media.com	808-238-2558	https://www.240media.com/	https://www.instagram.com/240media/
Shelly Lynn	Videography		Kailua-Kona	Hawaii	Waikoloa, Kailua-Kona, Hilo and beyond	Hawaii Island photography and videography team filming weddings and elopements with gentle direction and a documentary feel.	shellylynnphotograph@gmail.com		https://shellylynnphotography.com/	https://www.instagram.com/shellylynnphotos/`,
  },
];

export default batches;
