import type { VendorBatch } from "@/lib/vendor-batches";

// Illinois vendor batches. Every row's State is "Illinois". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Chicago: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
J. Brown Photography	Photography		Chicago	Illinois	Chicago and destinations afar	Award-winning photojournalist capturing unposed, colourful moments, with experience at Indian and same-sex weddings.	jason@jbrownphotography.com	773-255-5404	https://www.jbrownphotography.com/	https://www.instagram.com/j_brown_photo/
Shan Photography	Photography	444 N Michigan Ave, Suite 1200	Chicago	Illinois	Chicago and nationwide	Photo and film studio with over 20 years at Indian and multicultural weddings, from Sangeet and Mehndi to the first dance.	info@shanphotography.com	630-624-7426	https://www.shanphotography.com/	https://www.instagram.com/shanphotographyinc/
Joe Nowak Photography	Photography		St. Charles	Illinois	Chicago, St. Charles and surrounding suburbs	Wedding-only photographer with 20 years and 500+ weddings, taking a handful a year in a calm, natural-light documentary style.	joenowakphotography@gmail.com	312-860-4576	https://www.joenowakphotography.com/	https://www.instagram.com/joenowakphotography/
John Foley Photography	Photography		Chicago	Illinois	Chicago and surrounding suburbs, with global travel	Fine-art photographer blending documentary moments with artistic frames, offering hybrid photo and film coverage for a few weddings a year.	john@johnfoleyphotography.com		https://johnfoleyphotography.com/	https://www.instagram.com/johnfoleyphoto/
Honey Bee Weddings & Events	Planning	125 N Green St	Chicago	Illinois	Chicago, with travel available	Planning firm specialising in sustainable weddings, with experience in Indian, South Asian, Korean, Filipino and Nigerian celebrations.	misse@honeybeeweddings.com	773-789-9233	https://honeybeeweddings.com/	https://www.instagram.com/honeybeeweddings/
ForUrEvents	Planning	6326 N Cicero Ave, Unit 107	Chicago	Illinois	Chicagoland	Indian wedding planners handling Hindu, Sikh and South Indian ceremonies, with in-house décor, DJ, photo and catering options.	info@forurevents.com	847-224-3427	https://www.forurevents.com/	https://www.instagram.com/forurevents/
JoKay Events	Planning		Chicago	Illinois		Planner focused on multicultural and fusion weddings, including South Asian and Christian ceremonies, with budget and day-of support.	admin@jokayevents.com	630-210-1382	https://jokayevents.com/	https://www.instagram.com/jokayevents/
Afterglow Weddings & Events	Planning		Chicago	Illinois		Boutique planning team offering full planning, partial planning and coordination, with a personalised, detail-led approach.			https://www.afterglowweddingsandevents.com/	https://www.instagram.com/afterglowweddingsandevents/
Flowerchild	Florals	328 N Albany Ave	Chicago	Illinois	Chicago	Floral and event design studio with a separate Andersonville flower shop, creating lush wedding installations and bouquets.	info@flowerchildchicago.com	773-614-4032	https://www.flowerchildchicago.com/	https://www.instagram.com/flowerchild_floraldesign/
Studio Poppy	Florals	2643 W Chicago Ave	Chicago	Illinois		Woman-owned boutique florist designing natural, garden-inspired wedding flowers, using locally grown stems where it can.	natalie@studiopoppyflora.com		https://www.studiopoppyflora.com/	https://www.instagram.com/studio__poppy/
Flowers Just For You	Florals		Lemont	Illinois	Chicagoland	Wedding and event florist from Lemont creating custom designs across Chicagoland, with published price ranges for its floral work.	flowersjustforyouinc@gmail.com	630-597-6006	https://www.flowersjustforyou.studio/	https://www.instagram.com/flowers_just_for_you/
Thistle + Plume	Florals	1431 W Hubbard St, Suite 103	Chicago	Illinois		Boutique wedding florist working seasonally, known for loose, textured garden-style bouquets with plenty of colour and movement.	grace@thistleandplume.com	646-279-2729	https://www.thistleandplume.com/	
Toast & Jam	Music	2054 N California Ave, Suite 1	Chicago	Illinois		Woman-led DJ company since 2005 where the DJ you meet is the one who plays your wedding, with lighting and photo booths too.		773-687-8833	https://toastandjamdjs.com/	https://www.instagram.com/toastandjamdjs/
Groove Is In The Heart DJs	Music		Chicago	Illinois	Chicago area	Female-owned, inclusive DJ boutique matching couples with hand-picked DJs who build sets around each couple's own taste.	info@grooveisintheheartdjs.com		https://www.grooveisintheheartdjs.com/	https://www.instagram.com/grooveisintheheartdjs/
Cagen Music	Music		Chicago	Illinois	Chicago and destination weddings nationwide	Entertainment agency with several branded bands and DJs, including a Greek wedding band and Hindu ceremony musicians.		847-559-0900	https://cagenmusic.com/	
Blue Plate Catering	Catering	1362 W Fulton St	Chicago	Illinois	Chicago	Long-running caterer, Chicago's first green-certified, and a preferred partner at more than 85 venues across the city.			https://blueplatechicago.com/	https://www.instagram.com/blueplatechicago/
Food For Thought	Catering	7001 N Ridgeway Ave	Lincolnwood	Illinois	Chicagoland	Woman-owned, MBE-certified caterer offering chef-driven wedding menus and event planning under a sustainability framework.	info@ffthospitality.com	847-982-2608	https://www.ffthospitality.com/	https://www.instagram.com/fftchicago/
Cocina Fusion	Catering	1900 N Austin Ave	Chicago	Illinois		Family-owned caterer serving Latin fusion and traditional Mexican menus, with stations, bar service and late-night food.	juliana@cocinafusionchicago.com	773-430-4328	https://www.weddingcateringchicago.net/	https://www.instagram.com/cocinafusioncatering/
Limelight Catering	Catering	2400 S Michigan Ave	Chicago	Illinois		Seasonal caterer sourcing from Illinois and Indiana farms, offering passed bites, stations and plated wedding dinners.			https://www.limelightcatering.com/	https://www.instagram.com/limelightcatering/
Rare Bird Beauties	Hair & Makeup	2248 W Grand Ave	Chicago	Illinois		Bridal hair and makeup studio known for custom wedding-day hair extensions, with lessons and in-studio lash and brow services.	booking@rarebirdbeauties.com		https://rarebirdbeauties.com/	https://www.instagram.com/rarebirdbeauties/
Fine Makeup Art & Associates	Hair & Makeup		Chicago	Illinois	Chicago, North Shore, northwest suburbs and Lake Geneva	Makeup team bringing 15+ years of television experience to a refined, editorial bridal look for Chicago weddings.	traci@finemakeupart.com		https://finemakeupart.com/	https://www.instagram.com/finemakeupart312/
Windy City Glam	Hair & Makeup		Chicago	Illinois	Chicago and surrounding area	Award-winning bridal hair and makeup team for weddings, rehearsals and engagement shoots, aiming for a natural 'more of you' look.			https://windycityglam.com/	https://www.instagram.com/windycityglam/
Studio Standard Beauty	Hair & Makeup		Chicago	Illinois		Appointment-only beauty studio with a film and television background, offering bridal packages built to last in photos.			https://studiostandardbeauty.com/	
Alliance Bakery	Cake	1837 W Grand Ave	Chicago	Illinois		French-inspired bakery with two West Town shops, designing custom wedding cakes with tastings and iced-cookie favours.	info@alliancebakery.com	773-278-0366	https://alliancebakery.com/	https://www.instagram.com/alliancebakery/
Bittersweet Pastry Shop	Cake	1114 W Belmont Ave	Chicago	Illinois		Pastry shop with Lakeview, Pilsen and West Loop locations, handcrafting wedding cakes alongside its everyday pastries.	info@bittersweetpastry.com		https://bittersweetpastry.com/	
Creative Cakes Bakery	Cake	16649 Oak Park Ave, Suite F	Tinley Park	Illinois		Southwest-suburban bakery designing custom wedding cakes and dessert tables since 1989, with consultations by appointment.	info@creativecakesbakery.com	708-614-9755	https://www.creativecakesbakery.com/	https://www.instagram.com/cr8cakes/
West Town Bakery	Cake	1916 W Chicago Ave	Chicago	Illinois		Bakery and diner mixing street-art style with custom cakes and its well-known cakeballs, with several city and suburban shops.			https://www.westtownbakery.com/	https://www.instagram.com/westtownbakery/
Munaco Pictures	Videography	5740 N Milwaukee Ave	Chicago	Illinois	Chicago and surrounding suburbs, plus destination weddings	Wedding film studio with 500+ weddings over 15 years, offering cinematic story-led films, next-day highlights and raw footage.	tom@munacopictures.com	708-435-9773	https://www.munacopictures.com/	https://www.instagram.com/munacopictures/
Old North Film Company	Videography		Chicago	Illinois	Chicago and the Midwest, plus Texas, Massachusetts and California	Wedding film and photo team working across several Midwest cities, with a backup team member on hand for every booking.	hello@oldnorthfilmcompany.com	872-240-4310	https://www.oldnorthfilmcompany.com/	https://www.instagram.com/oldnorthfilmco/
Ellyce Wedding Films	Videography		Chicago	Illinois		Wedding videographer focused on emotional storytelling and intimate moments, filming couples in Chicago and around the US.	fernando@ellyceweddingfilms.com	773-870-4502	https://www.ellyceweddingfilms.com/	https://www.instagram.com/ellyce_wedding_films/
Forever Hello Films	Videography		Chicago	Illinois	Chicago and destinations	Wedding filmmaker shooting on Super 8 and 16mm film for a nostalgic, grainy look, and an openly LGBTQ+ friendly team.			https://www.foreverhellofilms.com/	https://www.instagram.com/foreverhellofilms/`,
  },
  {
    name: "Springfield: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Peach Moon Floral	Florals		Springfield	Illinois	Springfield and central Illinois	Bespoke floral studio led by certified florist Hannah Malone, creating romantic wedding flowers and one-of-a-kind floral fashion pieces.			https://www.peachmoonfloral.com/	https://www.instagram.com/peachmoonflorals/
Shawfield Events & Design	Planning		Springfield	Illinois	Central Illinois and beyond	Full-service planning and design duo, Meghan and Corinne, shaping distinctive, styled weddings of any size and budget across central Illinois.	shawfieldevents@gmail.com		https://www.shawfieldevents.com/	https://www.instagram.com/shawfieldevents/
Incredibly Delicious	Cake	925 S 7th St	Springfield	Illinois		French bakery and café in the historic Weber House, baking custom wedding cakes in Springfield for over three decades.		217-528-8548	https://www.incrediblydelicious.com/	https://www.instagram.com/incdelcakes/
Chris Withers Photography & Film	Photography	2160 S 6th St	Springfield	Illinois	Springfield, central Illinois and select destinations	Husband-and-wife team with 300+ weddings behind them, pairing timeless photography with cinematic film and a limited yearly calendar.		217-638-7579	https://chriswithersphotography.com/weddings	
Caitlin & Luke Photography	Photography		Springfield	Illinois	Central Illinois	Photographing Springfield weddings since 2011, with full-day coverage, a large gallery of images and an engagement session in every collection.			https://caitlinandluke.com/wedding-photographers-in-springfield-il	https://www.instagram.com/caitlinandlukephoto/
Lauren Westrich Photography	Photography		Springfield	Illinois	Central Illinois, St. Louis and beyond	Natural-light wedding photographer favouring cheerful, unposed images, travelling from Springfield across central Illinois and to St. Louis.	laurenwestrichphotography@gmail.com		https://laurenwestrichphotography.com/	https://www.instagram.com/laurenwestrichphotography/
Kristi Mitchell Photography	Photography	106 W Illinois	New Berlin	Illinois		Small-town studio photographer west of Springfield covering weddings and engagements alongside seniors, families and headshots.			https://www.kristimitchellphotography.com/	https://www.instagram.com/_kristimitchellphotography_/
CJ Waters Films	Videography		Springfield	Illinois	Springfield, central Illinois, Chicago, St. Louis and worldwide	Cinematic wedding films from Springfield, covering everything from small elopements to large celebrations across Illinois and beyond.	cicel@cjwatersfilms.com	217-553-0979	https://www.cjwatersfilms.com/	https://www.instagram.com/cjwatersfilms/
Lydia Stuemke Films	Videography		Springfield	Illinois	Central Illinois and beyond	Springfield videographer taking around a dozen weddings a year, so each couple gets an unhurried, personal film of the day.	lydia@lydiastuemke.com		https://lydiastuemke.com/	https://www.instagram.com/lydiastuemkeweddings/
Steve Weber Films	Videography		Jacksonville	Illinois	Central Illinois	Story-driven wedding videos from a Jacksonville filmmaker, with drone footage included in every package as standard.	steveweber@steveweberfilms.com	217-248-1580	https://www.steveweberfilms.com/	https://www.instagram.com/steveweberfilms/
Simply Detailed Wedding & Event Planning	Planning		Springfield	Illinois	Central Illinois, from Champaign and Peoria to Quincy and Litchfield	Two-planner team, Lyn and Marsha, offering full planning or day-of coordination, with more than 100 central Illinois weddings managed.		217-415-9700	https://simplydetailedevents.com/	https://www.instagram.com/simplydetailedevents/
Flourish Flower Company	Florals	2413 Denver Dr	Springfield	Illinois		Local flower shop building bridal packages from bouquets and boutonnieres to arches and centrepieces, in classic or contemporary styles.		217-679-1700	https://www.flourishflowercompany.net/wedding-flowers	https://www.instagram.com/flourishflowercompany/
The Flower Connection	Florals	1027 W Jefferson St	Springfield	Illinois		Locally owned Springfield florist of over 35 years, led by designer Paula Fricke, with wedding consultations by appointment.		217-787-5777	https://flowerconnection217.com/	
Music Source Professional Disc Jockey Service	Music	901 S Grand Ave W	Springfield	Illinois	Central Illinois	Long-running Springfield mobile DJ company, founded in 1982, playing around 100 events a year with wedding receptions at its core.	jr@musicsourcedj.com	217-787-8600	https://musicsourcedj.net/	
Nelson's Catering	Catering	3005 Great Northern Ave	Springfield	Illinois	Springfield, Decatur, Peoria, Bloomington-Normal, Champaign and beyond	Full-service caterer with over 25 years across central Illinois, handling weddings from menu planning through service on the day.		217-787-9443	https://nelsonscatering.com/	https://www.instagram.com/nelsonscateringil/
Arlington's Catering	Catering	210 Broadway	Springfield	Illinois	Springfield and central Illinois	Downtown Springfield caterer and historic venue, now cooking with family-run Cured Catering for weddings on site or off-premise.		217-679-6235	https://arlingtonsspi.com/catering/	https://www.instagram.com/arlingtons/
BJ Grand Salon & Spa	Hair & Makeup	3300 Robbins Rd	Springfield	Illinois	Within 40 miles of Springfield	Springfield salon dressing brides since 1975, offering hair, makeup and pampering for the whole party in-salon or on site.		217-787-7770	https://bjgrandsalon.com/bridal-services/	https://www.instagram.com/bjgrandsalon/
Violet & Lavender	Hair & Makeup	901 Clocktower Dr #18	Springfield	Illinois	Springfield and central Illinois, Chicago and St. Louis	Licensed cosmetologist Rowela French offering inclusive on-site or in-suite wedding hair and makeup, with transparent, tip-free pricing.		217-303-4500	https://www.violetandlavender.com/	https://www.instagram.com/violet_and_lavender/
Missy's Sweet Shoppe	Cake	113 S Sangamon St	Lincoln	Illinois	Central Illinois	Lincoln bake shop run by Missy Gaither since 2007, making custom wedding cakes, cupcakes and cookies from its downtown storefront.		309-825-5291	https://missyssweetshoppe.com/	
Crumble Creations	Cake		Springfield	Illinois	Springfield and surrounding areas	Made-to-order Springfield baker of custom wedding cakes, offering couples a multi-flavour tasting before they settle on a design.	laresacrumb@gmail.com	217-284-2397	https://crumblecreationsllc.com/services/wedding-cakes/	`,
  },
  {
    name: "Springfield: music and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Conn's Catering & Events	Catering	835 S Second St	Springfield	Illinois		Family-owned Springfield caterer since 1948, offering full-service wedding menus with setup and teardown and vegan or gluten-free options.	info@connshg.com	217-523-4466	https://www.connshg.com/conns-catering/	
Bloom Hospitality & Catering	Catering		Springfield	Illinois		Majority female-owned off-site caterer in Springfield serving modern American menus for weddings, from starters and stations to entrées.	info@bloomcaters.com	217-825-0836	https://bloomcaters.com/	https://www.instagram.com/bloom.caters/
BCA Weddings + Events	Music		Springfield	Illinois	Within 80 miles of Springfield, with travel beyond	Springfield wedding DJ and MC company that also brings photo booths, uplighting and ceremony sound, and names your DJ before you sign.	brandon.austin214@gmail.com		https://bcaweddingsandevents.com/	https://www.instagram.com/bcaweddingsandevents/
Radio Pro DJs	Music		Springfield	Illinois	Springfield region	Springfield DJ company staffed by local radio personalities, offering wedding DJs with uplighting, monograms, cold sparks and dancing-on-a-cloud effects.	lynchrpdjs@gmail.com	217-717-9192	https://www.radioprodjs.com/	https://www.instagram.com/radioprodjs/`,
  },
];

export default batches;
