import type { VendorBatch } from "@/lib/vendor-batches";

// Indiana vendor batches. Every row's State is "Indiana". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Indianapolis: photography, planning, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alison Mae Photography	Photography		Indianapolis	Indiana	Midwest and nationwide	Husband-and-wife team photographing garden and estate weddings with calm direction and natural, light-filled images.			https://www.alisonmaephotography.com/	https://www.instagram.com/alisonmaephotography/
Stacy Able Photography	Photography		Indianapolis	Indiana	Indianapolis, Central Indiana, Chicago, Cincinnati, Louisville and destinations	Documentary and editorial wedding photographer with true-to-life colour, photographing over 500 couples since 2008.			https://www.stacyable.com/	https://www.instagram.com/stacyablephotography/
Duet Floral Studio	Florals	1604 Deloss St	Indianapolis	Indiana	Midwest and beyond	Soft, romantic wedding floral design with digital mock-ups and a curated rental inventory to pair with arches and installations.	hello@duetfloral.com	812-785-6407	https://www.duetfloral.com/	https://www.instagram.com/duetfloral/
The Flower Boys	Florals	702 Lexington Ave	Indianapolis	Indiana		Fletcher Place flower shop known for Workshop Weddings where couples build their own bouquets, alongside full designer and DIY bulk options.	info@flowerboysindy.com	317-734-9356	https://www.flowerboysindy.com/	https://www.instagram.com/flowerboysindy/
LCB Weddings	Planning		Indianapolis	Indiana	Indianapolis, Bloomington, Chicago and beyond	Owner-led team offering full and partial planning, day-of coordination and décor rentals, and happy to plan around couples' dogs.			https://www.lcbweddings.com/	https://www.instagram.com/lcb.weddings/
Plum & Poppy Weddings	Planning		Zionsville	Indiana	Indianapolis and beyond	Zionsville planning and design firm with over 400 weddings behind it, many for out-of-state couples marrying in Indiana.	sarah@plumandpoppy.com	317-732-1998	https://www.plumandpoppy.com/	https://www.instagram.com/plumandpoppy/
DJ Indiana	Music		Indianapolis	Indiana	Central Indiana, Cincinnati, Louisville and Chicago	Wedding DJ team whose online client portal lets couples manage music choices and timelines in one place ahead of the day.	dj@djindiana.com	317-965-0792	https://djindiana.com/	
Living Proof	Music		Indianapolis	Indiana	Indianapolis and the Midwest	Award-winning cover band playing for over 20 years, with multiple lead singers, emcee duties and a set list from Motown to current pop.			https://www.livingproofmusic.com/	
Endless Summer Band	Music		Indianapolis	Indiana		Six-piece party band with several vocalists and an optional horn section, playing high-energy sets tailored to each reception.			https://www.esbband.com/	https://www.instagram.com/esbband/
Indy Fresh Catering	Catering	3047 Lafayette Rd	Indianapolis	Indiana	Central Indiana, from Lafayette and Kokomo to Bloomington and Terre Haute	Scratch-made wedding catering with tiered event packages and a large local team, catering across Central Indiana since 2013.	info@indyfreshcatering.com	317-605-1200	https://indyfreshcatering.com/	
Nameless Catering Company	Catering		Noblesville	Indiana	Indiana	High-volume wedding caterer with relaxed menus from Mexican bars and barbecue to pasta, plus more elevated Pier and Prairie spreads.		317-344-8449	https://namelesscatering.com/	https://www.instagram.com/nameless.caters/
Sweet Escape Cake Company	Cake	7745 S Meridian St	Indianapolis	Indiana		Family-run South Side bakery designing every wedding cake from scratch, with a private tasting room and 19 flavours at base price.	info@indycakes.com	317-840-1562	https://www.sweetescapecakecompany.com/	https://www.instagram.com/sweetescapecakeco/
Classic Cakes	Cake	1752 E 116th St	Carmel	Indiana		Carmel wedding bakery making custom tiered cakes since 1995, starting each order with a complimentary tasting consultation.	cake@classiccakes.com	317-844-6901	https://www.classiccakes.com/	https://www.instagram.com/classiccakescarmel/
Grafton Peek	Catering	410 E Main St	Greenwood	Indiana	Central Indiana, including Indianapolis, Carmel, Fishers, Bloomington and Anderson	Greenwood caterer working since 1999 on custom wedding menus for 50 to 3,000 guests, with bar service and dietary accommodations.	Jason@GraftonPeek.com	317-557-8377	https://graftonpeek.com/	
The Cake Bake Shop	Cake	6515 Carrollton Ave	Indianapolis	Indiana		Broad Ripple cake shop and restaurant founded by Gwendolyn Rogers, with a dedicated concierge team handling wedding cake orders.			https://thecakebakeshop.com/pages/weddings	https://www.instagram.com/thecakebakeshop/
Tangled Up Bridal	Hair & Makeup		Indianapolis	Indiana	Greater Indianapolis	On-site bridal hair and makeup team run as a sister business to an established salon, with clear pricing and stylist-matched scheduling.	Tangledupbridal@gmail.com	317-439-8131	https://www.tangledupbridal.com/	https://www.instagram.com/tangledupbridal/
Something Blue Stylists	Hair & Makeup		Indianapolis	Indiana	Indiana and west Michigan	On-location bridal hair and makeup team led by a stylist working since 2007, with airbrush makeup at no extra charge and touch-up kits included.			https://somethingbluestylists.com/	https://www.instagram.com/somethingbluestylists/`,
  },
  {
    name: "Indianapolis: videography, photography, planning, florals and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
6th Day Films	Videography		Indianapolis	Indiana	Indianapolis, the Midwest and destinations	Husband-and-wife film team crafting relaxed, story-led wedding films shaped by a pre-wedding consultation with each couple.	jared@6thdayfilms.com	317-342-1138	https://www.6thdayfilms.com/	https://www.instagram.com/6thdayfilms/
Time Walk Wedding Video	Videography		Indianapolis	Indiana	All of Indiana	Husband-and-wife videographers filming unobtrusively, with packages that can add drone footage, guest messages and couple interviews.	TimeWalkVideo@gmail.com	765-414-6076	https://www.timewalkvideo.com/	https://www.instagram.com/timewalkvideo/
Orange Float Weddings	Videography		Bloomington	Indiana	Indiana, the Midwest and destinations	Bloomington team filming and photographing weddings in-house, with no outsourcing, for couples across Indiana and beyond.			https://www.orangefloatweddings.com/	https://www.instagram.com/orangefloatweddings/
Sheema Q Makeup Artistry	Hair & Makeup		Indianapolis	Indiana	Indianapolis, Bloomington, Carmel, Fishers, Greenwood, Chicago and surrounding areas	Bridal makeup artist specialising in South Asian bridal glam for Indian, Pakistani and fusion weddings, alongside classic soft looks.	sheema@sheemaqmakeupartistry.com	317-762-4443	https://sheemaqmakeupartistry.com/	https://www.instagram.com/sheemaqmakeupartistry/
Thoughtfully Designed Co.	Planning		Indianapolis	Indiana	Indianapolis and surrounding areas	Full planning, design and day-of coordination firm with its own in-house florist and design team handling décor and set-up.			https://www.thoughtfullydesignedco.com/	https://www.instagram.com/thoughtfullydesignedco/
Satin & Stems	Florals		Indianapolis	Indiana	Indiana and destination weddings across the US	Owner-led studio pairing bespoke wedding florals with full-service planning, designing each celebration around the couple's personalities.	elizabeth@satinandstems.com		https://satinandstems.com/	https://www.instagram.com/elizabeth_satinandstems/
The Moments Between Us	Photography		Indianapolis	Indiana	Indianapolis, Chicago and the Midwest	Black woman-owned studio shooting dreamy, romantic and editorial wedding images, welcoming diverse and LGBTQ+ couples across the Midwest.			https://themomentsbetweenus.com/	
Curious Courtney's Photography	Photography		Indianapolis	Indiana	Indianapolis and nationwide	Husband-and-wife photographers blending documentary and fine-art styles, with a focus on intimate weddings and elopements.	curiouscourtneysphotography@gmail.com		https://curiouscourtneysphotography.com/	https://www.instagram.com/curiouscourtneysphotography/`,
  },
  {
    name: "Fort Wayne: photography, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kasey Wallace Photo	Photography		Fort Wayne	Indiana	Fort Wayne and travel	Wedding and portrait photographer with an art-degree background, favouring atmospheric light and unposed emotion over formula.			https://kaseywallacephoto.com/	
Dustin & Corynn	Photography		Fort Wayne	Indiana	Fort Wayne, Indianapolis, Indiana and destinations	Husband-and-wife photography team with studios in Fort Wayne and Indianapolis, covering weddings, engagements and elopements.	dustinandcorynn@gmail.com	260.241.6631	https://dustinandcorynn.com/	https://www.instagram.com/dustinandcorynn/
Jasmine Rose Photography	Photography		Fort Wayne	Indiana	Fort Wayne and travelling nationally	Fort Wayne photographer since 2017 capturing candid in-between moments at weddings and elopements, now booking into 2027.			https://jasminerose.photography/	https://www.instagram.com/jasminerosephotography/
Paige Danielle Photography	Photography		Fort Wayne	Indiana	Fort Wayne, Indianapolis, Cincinnati and beyond	Unobtrusive documentary-style wedding photographer focused on belly laughs, quiet moments and packed dance floors.	paige@paigedaniellephotography.com		https://paigedaniellephotography.com/	https://www.instagram.com/paigedaniellephoto/
Rose's Bouquets	Florals		Fort Wayne	Indiana	Fort Wayne area and beyond	Weddings-only florist that has designed contemporary bouquets, ceremony pieces and centrepieces for over 1,400 local couples.	tristarose@rb-weddings.com	260-602-7311	https://www.rb-weddings.com/	https://www.instagram.com/rosesbouquets/
Floracultured	Florals		Fort Wayne	Indiana	Fort Wayne, Leo-Cedarville, Grabill, and the Midwest including Indianapolis, South Bend and Chicago	Husband-and-wife floral studio creating modern, seasonal wedding designs, using blooms from local flower farms where they can.	hello@floracultured.com	260.348.4603	https://www.floracultured.com/	https://www.instagram.com/floracultured/
Cottage Flowers	Florals	236 E Wayne St	Fort Wayne	Indiana		Downtown Fort Wayne flower shop open since 1946, designing wedding florals from single pieces to full packages after a consultation.		(260) 426-3405	https://www.cottageflowersinc.net/page/weddings	https://www.instagram.com/cottageflowersinc/
Broadview Florist & Greenhouses	Florals	5409 Winchester Rd	Fort Wayne	Indiana	Fort Wayne and surrounding areas	Family-run florist and greenhouse of over 50 years on Fort Wayne's south side, offering wedding flowers by consultation.	eamninc@gmail.com	(260) 747-3146	https://broadviewflorist.net/consultation/	https://www.instagram.com/broadview_florist_greenhouse/
Get Up to Get Down Elite Entertainment	Music		Fort Wayne	Indiana	Fort Wayne and Northeast Indiana	Wedding DJ and MC team that sends two DJs to each wedding to run the timeline, with lighting and photo booth add-ons.	chris@getuptogetdown.com	260-715-2858	https://www.getuptogetdown.com/	https://www.instagram.com/getup2getdowndjs/
312 Muzik Entertainment	Music		Fort Wayne	Indiana	Fort Wayne, Indiana, and Illinois, Michigan and Ohio on request	Bilingual English-Spanish DJ and emcee with 20+ years of open-format sets, experienced with multicultural weddings.	312muzik@gmail.com	260-242-1143	https://312muzik.com/	https://www.instagram.com/312muzik/
PureVibe DJs	Music	6317 CR 327	Garrett	Indiana	Fort Wayne and Northeast Indiana	Christian-run DJ company with 30+ years and 3,000+ events, playing clean edits of popular music for family-friendly receptions.		260.553.6547	https://www.purevibedjs.com/	
Goeglein's Catering	Catering	7311 Maysville Rd	Fort Wayne	Indiana	Greater Fort Wayne and Northeast Indiana	Family caterer since 1951 cooking from family recipes, with its own banquet hall plus off-site catering, bar service and decorating.	catering@goegleins.com	260-749-5192	https://www.goegleins.com/	
Ceruti's Catering	Catering		Fort Wayne	Indiana	Within 100 miles of Fort Wayne	Family-owned full-service caterer since the early 1950s, handling wedding menus, bar service, planning and decor up to 100 miles out.		(260) 207-2000	https://www.cerutis.com/content/catering-overview	https://www.instagram.com/cerutis_catering/
SRG Catering	Catering		Fort Wayne	Indiana	Fort Wayne, Allen County and Northeast Indiana	Catering arm of a local restaurant group, drawing on Italian, Mexican, steak and seafood kitchens for plated or buffet receptions.	srgcateringfw@gmail.com	(260) 437-0369	https://srgcatering.com/	
Sassie Cakes	Cake	1014 Broadway	Fort Wayne	Indiana		Family-owned Broadway bakery specialising in buttercream wedding cakes, and able to design the wider dessert table too.	sassiecakes@me.com	260-478-8973	https://www.sassiecakes.com/	
Courtney's Bakery	Cake	7773 Coldwater Road	Fort Wayne	Indiana		North-side Fort Wayne bakery making custom wedding cakes, with consultations booked through the shop and online ordering.	info@courtneysbakery.com	260 338-2688	https://www.courtneysbakery.com/	
Caking at Midnight	Cake	1202 W Main St	Fort Wayne	Indiana		West Main Street cake shop quoting custom wedding cakes per serving, with fresh flower, macaron and fondant detail options.	cakingatmidnight@gmail.com	(260) 403-6998	https://www.cakingatmidnight.com/	https://www.instagram.com/caking_at_midnight/
The Red Stiletto	Hair & Makeup	6171 Stoney Creek Dr	Fort Wayne	Indiana	Fort Wayne, regional Midwest cities and destination weddings nationwide	Fort Wayne salon and spa with a dedicated on-location bridal team, travelling to Detroit, Cincinnati, Indianapolis and beyond.	info@redstilettoartistry.com	(260) 471-6033	https://redstilettoartistry.com/	https://www.instagram.com/redstilettoartistry/
The Beauty Atelier	Hair & Makeup		Fort Wayne	Indiana	Fort Wayne, Indianapolis and Midwest travel	Bridal makeup artist with 17 years of experience specialising in soft-glam and airbrush looks applied on site.	thebeautyatelierfw@gmail.com		https://www.thebeautyatelierfw.com/	https://www.instagram.com/thebeautyatelier.fw/
Beautiful Memories	Hair & Makeup		Fort Wayne	Indiana	Indiana and destinations worldwide	On-location team of stylists offering bridal hair, airbrush or traditional makeup and nails at your home or venue.	hayleyfiche@gmail.com		https://www.beautifulmemories.us/	https://www.instagram.com/beautifulmemories.inc/
Erin Nay Makeup Artistry	Hair & Makeup		Fort Wayne	Indiana	Fort Wayne and surrounding areas	On-site bridal makeup artist for brides and wedding parties, offering a free 15-minute phone consult before booking.	erin@erinnay.com		https://www.erinnay.com/	https://www.instagram.com/erinnaymakeupartistry/`,
  },
  {
    name: "Fort Wayne: planning and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Four-Thirty Events	Planning		Fort Wayne	Indiana	Fort Wayne and the Midwest	Planner founded in 2020 by Kelly, whose team offers full, partial and wedding-day management and also runs The Fairfield venue.	kelly@fourthirtyevents.com		https://www.fourthirtyevents.com/	https://www.instagram.com/four_thirty_events/
bella&fern event planning	Planning		Fort Wayne	Indiana	Fort Wayne and destinations worldwide	Fort Wayne planning firm offering full custom planning, partial planning and day-of services, each with an associate on the day.			https://www.bella-fern.com/	https://www.instagram.com/bella_fern_events/
Day 1 Wedding Coordinating	Planning		Fort Wayne	Indiana	Fort Wayne, Indianapolis and Northwest Indiana	Mother-daughter-founded team of 20 coordinators specialising in day-of coordination and partial planning for couples who plan their own.	day1wc@gmail.com		https://www.day1wc.com/	https://www.instagram.com/day1wc/
Kingdom Film Co.	Videography		Fort Wayne	Indiana	Fort Wayne and surrounding area	Fort Wayne filmmaker with a visual communications degree making true-to-life cinematic wedding films in 4K with drone footage.	evan@kingdomfilmco.com	(260) 415-3287	https://www.kingdomfilmco.com/	https://www.instagram.com/kingdomfilmco/
Daze Filmography	Videography		Fort Wayne	Indiana		Downtown Fort Wayne film and photo duo offering wedding and engagement film packages, with a background in music and audio work.			https://www.dazefilmography.com/	https://www.instagram.com/dazefilmography/
Logan Hoffman Film & Photo	Videography		Fort Wayne	Indiana	The Midwest and beyond	Fort Wayne videographer making wedding films that catch the small personal moments alongside the big ones, plus photo work.			https://www.lhfilmphoto.com/	https://www.instagram.com/loganhoffmanfilmphoto/
Film By Abbie	Videography		Fort Wayne	Indiana	Fort Wayne and travel	Fort Wayne photographer and videographer making candid, emotion-led wedding films, with photo and film packages available together.	filmbyabbie@gmail.com		https://www.abbieschumm.com/	https://www.instagram.com/filmbyabbie_/`,
  },
];

export default batches;
