import type { VendorBatch } from "@/lib/vendor-batches";

// Indiana vendor batches. Every row's State is "Indiana". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Indianapolis: photography, planning, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alison Mae Photography	Photography		Indianapolis	Indiana	Midwest and nationwide	Husband-and-wife team photographing garden and estate weddings with calm direction and natural, light-filled images.			https://www.alisonmaephotography.com/	https://www.instagram.com/alisonmaephotography/
Stacy Able Photography	Photography		Indianapolis	Indiana	Indianapolis, Central Indiana, Chicago, Cincinnati, Louisville and destinations	Documentary and editorial wedding photographer with true-to-life colour, photographing over 500 couples since 2008.			https://www.stacyable.com/	https://www.instagram.com/stacyablephotography/
Duet Floral Studio	Florals	1604 Deloss St	Indianapolis	Indiana	Midwest and beyond	Soft, romantic wedding floral design with digital mock-ups and a curated rental inventory to pair with arches and installations.	hello@duetfloral.com	812-785-6407	https://www.duetfloral.com/	https://www.instagram.com/duetfloral/
The Flower Boys	Florals	702 Lexington Ave	Indianapolis	Indiana		Fletcher Place flower shop known for Workshop Weddings where couples build their own bouquets, alongside full designer and DIY bulk options.	info@flowerboysindy.com	317-734-9356	https://www.flowerboysindy.com/	https://www.instagram.com/flowerboysindy/
LCB Weddings	Planning		Indianapolis	Indiana	Indianapolis, Bloomington, Chicago and beyond	Owner-led team offering full and partial planning, day-of coordination and décor rentals, and happy to plan around couples' dogs.			https://www.lcbweddings.com/	https://www.instagram.com/lcb.weddings/
Plum & Poppy Weddings	Planning		Zionsville	Indiana	Indianapolis and beyond	Zionsville planning and design firm with over 400 weddings behind it, many for out-of-state couples marrying in Indiana.	sarah@plumandpoppy.com	317-732-1998	https://www.plumandpoppy.com/	https://www.instagram.com/plumandpoppy/
DJ Indiana	Music		Indianapolis	Indiana	Central Indiana, Cincinnati, Louisville and Chicago	Wedding DJ team whose online client portal lets couples manage music choices and timelines in one place ahead of the day.	dj@djindiana.com	317-965-0792	https://djindiana.com/	
Living Proof	Music		Indianapolis	Indiana	Indianapolis and the Midwest	Award-winning cover band playing for over 20 years, with multiple lead singers, emcee duties and a set list from Motown to current pop.			https://www.livingproofmusic.com/	
Endless Summer Band	Music		Indianapolis	Indiana		Six-piece party band with several vocalists and an optional horn section, playing high-energy sets tailored to each reception.			https://www.esbband.com/	https://www.instagram.com/esbband/
Indy Fresh Catering	Catering	3047 Lafayette Rd	Indianapolis	Indiana	Central Indiana, from Lafayette and Kokomo to Bloomington and Terre Haute	Scratch-made wedding catering with tiered event packages and a large local team, catering across Central Indiana since 2013.	info@indyfreshcatering.com	317-605-1200	https://indyfreshcatering.com/	
Nameless Catering Company	Catering		Noblesville	Indiana	Indiana	High-volume wedding caterer with relaxed menus from Mexican bars and barbecue to pasta, plus more elevated Pier and Prairie spreads.		317-344-8449	https://namelesscatering.com/	https://www.instagram.com/nameless.caters/
Sweet Escape Cake Company	Cake	7745 S Meridian St	Indianapolis	Indiana		Family-run South Side bakery designing every wedding cake from scratch, with a private tasting room and 19 flavours at base price.	info@indycakes.com	317-840-1562	https://www.sweetescapecakecompany.com/	https://www.instagram.com/sweetescapecakeco/
Classic Cakes	Cake	1752 E 116th St	Carmel	Indiana		Carmel wedding bakery making custom tiered cakes since 1995, starting each order with a complimentary tasting consultation.	cake@classiccakes.com	317-844-6901	https://www.classiccakes.com/	https://www.instagram.com/classiccakescarmel/
Grafton Peek	Catering	410 E Main St	Greenwood	Indiana	Central Indiana, including Indianapolis, Carmel, Fishers, Bloomington and Anderson	Greenwood caterer working since 1999 on custom wedding menus for 50 to 3,000 guests, with bar service and dietary accommodations.	Jason@GraftonPeek.com	317-557-8377	https://graftonpeek.com/	
The Cake Bake Shop	Cake	6515 Carrollton Ave	Indianapolis	Indiana		Broad Ripple cake shop and restaurant founded by Gwendolyn Rogers, with a dedicated concierge team handling wedding cake orders.			https://thecakebakeshop.com/pages/weddings	https://www.instagram.com/thecakebakeshop/
Tangled Up Bridal	Hair & Makeup		Indianapolis	Indiana	Greater Indianapolis	On-site bridal hair and makeup team run as a sister business to an established salon, with clear pricing and stylist-matched scheduling.	Tangledupbridal@gmail.com	317-439-8131	https://www.tangledupbridal.com/	https://www.instagram.com/tangledupbridal/
Something Blue Stylists	Hair & Makeup		Indianapolis	Indiana	Indiana and west Michigan	On-location bridal hair and makeup team led by a stylist working since 2007, with airbrush makeup at no extra charge and touch-up kits included.			https://somethingbluestylists.com/	https://www.instagram.com/somethingbluestylists/`,
  },
  {
    name: "Indianapolis: videography, photography, planning, florals and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
6th Day Films	Videography		Indianapolis	Indiana	Indianapolis, the Midwest and destinations	Husband-and-wife film team crafting relaxed, story-led wedding films shaped by a pre-wedding consultation with each couple.	jared@6thdayfilms.com	317-342-1138	https://www.6thdayfilms.com/	https://www.instagram.com/6thdayfilms/
Time Walk Wedding Video	Videography		Indianapolis	Indiana	All of Indiana	Husband-and-wife videographers filming unobtrusively, with packages that can add drone footage, guest messages and couple interviews.	TimeWalkVideo@gmail.com	765-414-6076	https://www.timewalkvideo.com/	https://www.instagram.com/timewalkvideo/
Orange Float Weddings	Videography		Bloomington	Indiana	Indiana, the Midwest and destinations	Bloomington team filming and photographing weddings in-house, with no outsourcing, for couples across Indiana and beyond.			https://www.orangefloatweddings.com/	https://www.instagram.com/orangefloatweddings/
Sheema Q Makeup Artistry	Hair & Makeup		Indianapolis	Indiana	Indianapolis, Bloomington, Carmel, Fishers, Greenwood, Chicago and surrounding areas	Bridal makeup artist specialising in South Asian bridal glam for Indian, Pakistani and fusion weddings, alongside classic soft looks.	sheema@sheemaqmakeupartistry.com	317-762-4443	https://sheemaqmakeupartistry.com/	https://www.instagram.com/sheemaqmakeupartistry/
Thoughtfully Designed Co.	Planning		Indianapolis	Indiana	Indianapolis and surrounding areas	Full planning, design and day-of coordination firm with its own in-house florist and design team handling décor and set-up.			https://www.thoughtfullydesignedco.com/	https://www.instagram.com/thoughtfullydesignedco/
Satin & Stems	Florals		Indianapolis	Indiana	Indiana and destination weddings across the US	Owner-led studio pairing bespoke wedding florals with full-service planning, designing each celebration around the couple's personalities.	elizabeth@satinandstems.com		https://satinandstems.com/	https://www.instagram.com/elizabeth_satinandstems/
The Moments Between Us	Photography		Indianapolis	Indiana	Indianapolis, Chicago and the Midwest	Black woman-owned studio shooting dreamy, romantic and editorial wedding images, welcoming diverse and LGBTQ+ couples across the Midwest.			https://themomentsbetweenus.com/	
Curious Courtney's Photography	Photography		Indianapolis	Indiana	Indianapolis and nationwide	Husband-and-wife photographers blending documentary and fine-art styles, with a focus on intimate weddings and elopements.	curiouscourtneysphotography@gmail.com		https://curiouscourtneysphotography.com/	https://www.instagram.com/curiouscourtneysphotography/`,
  },
  {
    name: "Fort Wayne: photography, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kasey Wallace Photo	Photography		Fort Wayne	Indiana	Fort Wayne and travel	Wedding and portrait photographer with an art-degree background, favouring atmospheric light and unposed emotion over formula.			https://kaseywallacephoto.com/	
Dustin & Corynn	Photography		Fort Wayne	Indiana	Fort Wayne, Indianapolis, Indiana and destinations	Husband-and-wife photography team with studios in Fort Wayne and Indianapolis, covering weddings, engagements and elopements.	dustinandcorynn@gmail.com	260.241.6631	https://dustinandcorynn.com/	https://www.instagram.com/dustinandcorynn/
Jasmine Rose Photography	Photography		Fort Wayne	Indiana	Fort Wayne and travelling nationally	Fort Wayne photographer since 2017 capturing candid in-between moments at weddings and elopements, now booking into 2027.			https://jasminerose.photography/	https://www.instagram.com/jasminerosephotography/
Paige Danielle Photography	Photography		Fort Wayne	Indiana	Fort Wayne, Indianapolis, Cincinnati and beyond	Unobtrusive documentary-style wedding photographer focused on belly laughs, quiet moments and packed dance floors.	paige@paigedaniellephotography.com		https://paigedaniellephotography.com/	https://www.instagram.com/paigedaniellephoto/
Rose's Bouquets	Florals		Fort Wayne	Indiana	Fort Wayne area and beyond	Weddings-only florist that has designed contemporary bouquets, ceremony pieces and centrepieces for over 1,400 local couples.	tristarose@rb-weddings.com	260-602-7311	https://www.rb-weddings.com/	https://www.instagram.com/rosesbouquets/
Floracultured	Florals		Fort Wayne	Indiana	Fort Wayne, Leo-Cedarville, Grabill, and the Midwest including Indianapolis, South Bend and Chicago	Husband-and-wife floral studio creating modern, seasonal wedding designs, using blooms from local flower farms where they can.	hello@floracultured.com	260.348.4603	https://www.floracultured.com/	https://www.instagram.com/floracultured/
Cottage Flowers	Florals	236 E Wayne St	Fort Wayne	Indiana		Downtown Fort Wayne flower shop open since 1946, designing wedding florals from single pieces to full packages after a consultation.		(260) 426-3405	https://www.cottageflowersinc.net/page/weddings	https://www.instagram.com/cottageflowersinc/
Broadview Florist & Greenhouses	Florals	5409 Winchester Rd	Fort Wayne	Indiana	Fort Wayne and surrounding areas	Family-run florist and greenhouse of over 50 years on Fort Wayne's south side, offering wedding flowers by consultation.	eamninc@gmail.com	(260) 747-3146	https://broadviewflorist.net/consultation/	https://www.instagram.com/broadview_florist_greenhouse/
Get Up to Get Down Elite Entertainment	Music		Fort Wayne	Indiana	Fort Wayne and Northeast Indiana	Wedding DJ and MC team that sends two DJs to each wedding to run the timeline, with lighting and photo booth add-ons.	chris@getuptogetdown.com	260-715-2858	https://www.getuptogetdown.com/	https://www.instagram.com/getup2getdowndjs/
312 Muzik Entertainment	Music		Fort Wayne	Indiana	Fort Wayne, Indiana, and Illinois, Michigan and Ohio on request	Bilingual English-Spanish DJ and emcee with 20+ years of open-format sets, experienced with multicultural weddings.	312muzik@gmail.com	260-242-1143	https://312muzik.com/	https://www.instagram.com/312muzik/
PureVibe DJs	Music	6317 CR 327	Garrett	Indiana	Fort Wayne and Northeast Indiana	Christian-run DJ company with 30+ years and 3,000+ events, playing clean edits of popular music for family-friendly receptions.		260.553.6547	https://www.purevibedjs.com/	
Goeglein's Catering	Catering	7311 Maysville Rd	Fort Wayne	Indiana	Greater Fort Wayne and Northeast Indiana	Family caterer since 1951 cooking from family recipes, with its own banquet hall plus off-site catering, bar service and decorating.	catering@goegleins.com	260-749-5192	https://www.goegleins.com/	
Ceruti's Catering	Catering		Fort Wayne	Indiana	Within 100 miles of Fort Wayne	Family-owned full-service caterer since the early 1950s, handling wedding menus, bar service, planning and decor up to 100 miles out.		(260) 207-2000	https://www.cerutis.com/content/catering-overview	https://www.instagram.com/cerutis_catering/
SRG Catering	Catering		Fort Wayne	Indiana	Fort Wayne, Allen County and Northeast Indiana	Catering arm of a local restaurant group, drawing on Italian, Mexican, steak and seafood kitchens for plated or buffet receptions.	srgcateringfw@gmail.com	(260) 437-0369	https://srgcatering.com/	
Sassie Cakes	Cake	1014 Broadway	Fort Wayne	Indiana		Family-owned Broadway bakery specialising in buttercream wedding cakes, and able to design the wider dessert table too.	sassiecakes@me.com	260-478-8973	https://www.sassiecakes.com/	
Courtney's Bakery	Cake	7773 Coldwater Road	Fort Wayne	Indiana		North-side Fort Wayne bakery making custom wedding cakes, with consultations booked through the shop and online ordering.	info@courtneysbakery.com	260 338-2688	https://www.courtneysbakery.com/	
Caking at Midnight	Cake	1202 W Main St	Fort Wayne	Indiana		West Main Street cake shop quoting custom wedding cakes per serving, with fresh flower, macaron and fondant detail options.	cakingatmidnight@gmail.com	(260) 403-6998	https://www.cakingatmidnight.com/	https://www.instagram.com/caking_at_midnight/
The Red Stiletto	Hair & Makeup	6171 Stoney Creek Dr	Fort Wayne	Indiana	Fort Wayne, regional Midwest cities and destination weddings nationwide	Fort Wayne salon and spa with a dedicated on-location bridal team, travelling to Detroit, Cincinnati, Indianapolis and beyond.	info@redstilettoartistry.com	(260) 471-6033	https://redstilettoartistry.com/	https://www.instagram.com/redstilettoartistry/
The Beauty Atelier	Hair & Makeup		Fort Wayne	Indiana	Fort Wayne, Indianapolis and Midwest travel	Bridal makeup artist with 17 years of experience specialising in soft-glam and airbrush looks applied on site.	thebeautyatelierfw@gmail.com		https://www.thebeautyatelierfw.com/	https://www.instagram.com/thebeautyatelier.fw/
Beautiful Memories	Hair & Makeup		Fort Wayne	Indiana	Indiana and destinations worldwide	On-location team of stylists offering bridal hair, airbrush or traditional makeup and nails at your home or venue.	hayleyfiche@gmail.com		https://www.beautifulmemories.us/	https://www.instagram.com/beautifulmemories.inc/
Erin Nay Makeup Artistry	Hair & Makeup		Fort Wayne	Indiana	Fort Wayne and surrounding areas	On-site bridal makeup artist for brides and wedding parties, offering a free 15-minute phone consult before booking.	erin@erinnay.com		https://www.erinnay.com/	https://www.instagram.com/erinnaymakeupartistry/`,
  },
  {
    name: "Fort Wayne: planning and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Four-Thirty Events	Planning		Fort Wayne	Indiana	Fort Wayne and the Midwest	Planner founded in 2020 by Kelly, whose team offers full, partial and wedding-day management and also runs The Fairfield venue.	kelly@fourthirtyevents.com		https://www.fourthirtyevents.com/	https://www.instagram.com/four_thirty_events/
bella&fern event planning	Planning		Fort Wayne	Indiana	Fort Wayne and destinations worldwide	Fort Wayne planning firm offering full custom planning, partial planning and day-of services, each with an associate on the day.			https://www.bella-fern.com/	https://www.instagram.com/bella_fern_events/
Day 1 Wedding Coordinating	Planning		Fort Wayne	Indiana	Fort Wayne, Indianapolis and Northwest Indiana	Mother-daughter-founded team of 20 coordinators specialising in day-of coordination and partial planning for couples who plan their own.	day1wc@gmail.com		https://www.day1wc.com/	https://www.instagram.com/day1wc/
Kingdom Film Co.	Videography		Fort Wayne	Indiana	Fort Wayne and surrounding area	Fort Wayne filmmaker with a visual communications degree making true-to-life cinematic wedding films in 4K with drone footage.	evan@kingdomfilmco.com	(260) 415-3287	https://www.kingdomfilmco.com/	https://www.instagram.com/kingdomfilmco/
Daze Filmography	Videography		Fort Wayne	Indiana		Downtown Fort Wayne film and photo duo offering wedding and engagement film packages, with a background in music and audio work.			https://www.dazefilmography.com/	https://www.instagram.com/dazefilmography/
Logan Hoffman Film & Photo	Videography		Fort Wayne	Indiana	The Midwest and beyond	Fort Wayne videographer making wedding films that catch the small personal moments alongside the big ones, plus photo work.			https://www.lhfilmphoto.com/	https://www.instagram.com/loganhoffmanfilmphoto/
Film By Abbie	Videography		Fort Wayne	Indiana	Fort Wayne and travel	Fort Wayne photographer and videographer making candid, emotion-led wedding films, with photo and film packages available together.	filmbyabbie@gmail.com		https://www.abbieschumm.com/	https://www.instagram.com/filmbyabbie_/`,
  },
  {
    name: "Bloomington: photography, videography, planning, florals, music, catering and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
James Brosher Photography	Photography		Bloomington	Indiana	Bloomington and south-central Indiana, with travel	Bloomington photojournalist shooting candid, story-driven wedding coverage, with formal portraits and editorial work offered alongside.	james@brosher.com	(765) 744-0865	https://www.brosher.com/	https://www.instagram.com/jamesbrosher/
Garrett Ann Walters Photography	Photography		Bloomington	Indiana	Southern Indiana	Bloomington photographer blending film and digital for casual, timeless wedding and portrait images that favour candid moments.	garrettannwalters@gmail.com		https://www.garrettannwalters.com/	https://www.instagram.com/garrettannwaltersphotography/
Mika LH Photography	Photography		Bloomington	Indiana	Bloomington and destinations nationwide	Bloomington wedding and portrait photographer focused on unscripted moments and real emotion, travelling for couples across the country.	mikalhphotography@gmail.com		https://mikalh.com/	https://www.instagram.com/mikalhphoto/
Courtney Sinclair Photography	Photography		Bloomington	Indiana	Indiana, Chicago and beyond	Husband-and-wife team shooting film and digital weddings with a journalistic eye, based in Bloomington and working around Indiana and Chicago.	hello@courtneysinclair.com		https://courtneysinclair.com/	https://www.instagram.com/courtneysinclairphoto/
Gold Iris Weddings	Videography		Bloomington	Indiana	South-central Indiana	Bloomington wedding media company combining photography, highlight films and audio-visual support for ceremonies and receptions.	info@goldirisweddings.com		https://www.goldirisweddings.com/	https://www.instagram.com/goldirisweddings/
Green Hat Media	Videography	2599 W Fountain Dr, Suite 3	Bloomington	Indiana	South-central Indiana	Bloomington photo and video studio covering weddings as well as headshots, events and promotional video, with a dedicated wedding line.		(812) 340-4451	https://greenhatmediallc.com/	https://www.instagram.com/greenhatmedia/
Elite Weddings & Events	Planning		Bloomington	Indiana	Bloomington and surrounding Indiana	Bloomington planning and décor company offering wedding planning packages, setup and teardown, and décor and entertainment rentals.	hello@elite-we.com		https://elite-we.com/	https://www.instagram.com/elitewebych/
Blessinger Entertainment	Music		Indianapolis	Indiana	Indianapolis, Bloomington, Columbus, Fort Wayne and across Indiana	Wedding DJ, hosting and lighting team that travels around the state, with Bloomington and Brown County among its listed service areas.			https://blessingerentertainment.com/	https://www.instagram.com/blessingerentertainment/
One World Catering	Catering		Bloomington	Indiana	Bloomington and surrounding venues	Made-from-scratch Bloomington caterer with customisable wedding menus, event planning help and full-service staffing at area venues.		(812) 334-3663	https://oneworldcaters.com/	https://www.instagram.com/owcatering/
Hair International Day Spa	Hair & Makeup	608 W Kirkwood Ave	Bloomington	Indiana	Bloomington	Kirkwood Avenue day spa offering hair design, makeup, skincare, nails, waxing and lash services for bridal parties.	info@hairint.com	(812) 339-5222	https://hairint.com/	https://www.instagram.com/hair_international_dayspa/
Bloomin' Tons	Florals	2642 E 10th St	Bloomington	Indiana	Bloomington and south-central Indiana	Bloomington florist making custom bridal bouquets and on-site ceremony and reception décor, from traditional to contemporary looks.		(812) 336-7201	https://www.bloomintons.net/wedding-flowers	https://www.instagram.com/bloomintonsfloral/
Three Blondes Floral Co.	Florals	217 W 6th St	Bloomington	Indiana	Bloomington	Downtown Bloomington boutique florist offering wedding and event design, seasonal workshops and daily arrangements.			https://www.threeblondesfloralco.com/	https://www.instagram.com/threeblondesfloralco/`,
  },
  {
    name: "Bloomington: planning, florals, music, hair and makeup, cake and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Ashley Weddings & Events	Planning		Bloomington	Indiana	Bloomington and Indianapolis	Wedding and event planner with a design-led approach, with a blog of real Bloomington and Indiana University venue weddings.			https://ashleyweddingsandevents.com/	https://www.instagram.com/ashleyweddings/
Sincerely Yours Weddings & Premier Events	Planning		Bloomington	Indiana	Bloomington, Evansville and southern Indiana	Wedding coordination packages covering timelines, vendor management and rehearsal and wedding-day logistics across southern Indiana.	hello@sywpevents.com	812.212.0871	https://www.sywpevents.com/	
Cathy Teeters Beautiful Weddings	Florals		Bloomington	Indiana	Bloomington	Bloomington florist and bridal consultant with over 40 years' experience, offering wedding flowers, advice and day-of coordination.	cateeters@yahoo.com	(812) 327-9794	https://www.cathyteetersbeautifulweddings.com/	https://www.instagram.com/cathyteetersbeautifulweddings/
DJ Clay Lewis	Music		Bloomington	Indiana	Bloomington, Martinsville, Bedford, Nashville, Spencer and southern Indiana	Bloomington DJ and MC offering customised music and hosting for weddings and events across southern Indiana.	clay@djclaylewis.com	812-727-0330	https://djclaylewis.com/	https://www.instagram.com/djclaylewis/
Hoosier DJ Services	Music		Bloomington	Indiana	Indiana	Premium wedding DJ and master of ceremonies working from Bloomington, with packages built around each couple's timeline.			https://www.hoosierdj.com/	
The Mane Bridal	Hair & Makeup	114 South College Avenue	Bloomington	Indiana	Bloomington and southern Indiana	On-location bridal hair and makeup team in Bloomington, from romantic updos to modern glam, booked by appointment.			https://www.themanebloomington.com/for-brides	https://www.instagram.com/themanebloomington/
Two Sticks Bakery	Cake	415 S Washington St	Bloomington	Indiana	Bloomington	Women-owned from-scratch bakery making custom wedding cakes, with pick-up tastings and delivery for larger tiered cakes.	twosticksbakery@gmail.com	(812) 668-2125	https://www.twosticksbakery.com/	https://www.instagram.com/twosticksbakery/
Bake Me A Cake Etc	Cake		Bloomington	Indiana	Bloomington, Ellettsville and Spencer	Home-based Bloomington baker making custom wedding cakes and cupcakes, with delivery to Bloomington, Ellettsville and Spencer.			https://www.bakemeacakeetc.com/	
Cardinal Spirits Catering	Catering	922 S Morton St	Bloomington	Indiana	Bloomington and surrounding areas	Craft distillery's catering arm, working with The Cabin restaurant to cater a limited number of weddings and events each year.	hello@cardinalspirits.com	812-202-6789	https://www.cardinalspirits.com/catering	https://www.instagram.com/cardinalspirits/`,
  },
  {
    name: "South Bend: photography, videography, planning, florals, music, catering, cake and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Weeping Willow Photography	Photography		South Bend	Indiana	South Bend, Michiana and Northern Indiana	Wedding photographer in South Bend offering timed coverage packages, elopements and destination weddings across Michiana.	kayla@weepingwillowphoto.com	574-806-4653	https://www.weepingwillowphoto.com/weddings-and-events	https://www.instagram.com/weepingwillowphotography/
Leah Rife Photo	Photography		South Bend	Indiana		South Bend photographer covering weddings alongside lifestyle and portrait sessions, with a relaxed, personal approach to the day.	leahrifephoto@gmail.com		https://leahrifephoto.com/	https://www.instagram.com/leahrife/
Casey Patrick Photography	Photography		South Bend	Indiana	Notre Dame and South Bend area	South Bend photographer shooting weddings around Notre Dame and northern Indiana, alongside family and senior portraits.	Caseypatrickphotography@gmail.com	574-821-5336	https://www.caseypatrickphotography.com/	https://www.instagram.com/caseypatrickphotography/
Cat Alkire Photography	Photography		South Bend	Indiana	South Bend, Chicago, Indianapolis and the Midwest	Fine art wedding photographer in South Bend with Catholic and traditional ceremony experience and Notre Dame campus weddings.	hello@catalkire.com		https://catalkire.com/	https://www.instagram.com/catalkirephoto/
Nico Studios	Photography		South Bend	Indiana	South Bend, the Midwest and beyond	South Bend photo and video studio covering weddings, with testimonials from couples about their wedding-day photographs.	chris@nico-studios.com		https://nico-studios.com/	https://www.instagram.com/nicostudiossb/
Robin Crystal Photography	Photography		Goshen	Indiana	Indiana	Goshen photographer covering weddings as well as children's portraits, serving couples around Elkhart County and northern Indiana.			https://robincrystalphotography.com/	https://www.instagram.com/robincrystalphotography/
Lighthouse Productions	Videography	1100 Chicago Ave, Suite 2C	Goshen	Indiana		Goshen studio in the Old Bag Factory offering wedding photography and video, with separate wedding photo and film pages.	lighthousevideo@gmail.com	574-533-1400	https://www.lighthousephotoandvideo.com/	
Vibrant Video Productions	Videography		South Bend	Indiana	Michiana and Indianapolis	South Bend wedding videographer producing short films and full edits, with recent wedding films published on its site.			https://vibevideoproductions.com/	https://www.instagram.com/VibrantVideoProductions/
Story Light Films	Videography		South Bend	Indiana	Michiana, south west Michigan and northern Indiana	Michiana wedding videographer based in South Bend, filming wedding days across northern Indiana and south west Michigan.	storylightfilms.1@gmail.com		https://www.storylightfilms.com/	https://www.instagram.com/story_light_films/
Belle Behind the Ball	Planning		South Bend	Indiana	Michiana	Wedding planner offering full planning, partial planning, day-of coordination and destination and honeymoon planning for Michiana couples.		574-274-9383	https://bellebehindtheball.com/	
One Fine Day Special Events and Wedding Planning	Planning		Osceola	Indiana		Osceola planner offering full, partial and day-of wedding coordination, plus set-up and break-down, welcome bags and travel planning.	planneronefineday@gmail.com	574-303-5581	https://onefinedayspecialevents.com/	https://www.instagram.com/onefinedayspecialevents/
LB Floristry	Florals		South Bend	Indiana	Northern Indiana, Southwest Michigan and Chicago	Studio florist in South Bend focused solely on weddings, with a fine art, organic style and featured real weddings on its site.			https://lbfloristry.com/	https://www.instagram.com/lbfloristry/
Always N Bloom Weddings	Florals		Notre Dame	Indiana	Notre Dame, Granger, South Bend and the Michiana region	Wedding flower studio near Notre Dame designing custom florals for Michiana weddings, with a portfolio and photo gallery.		574-876-1916	https://alwaysnbloomweddings.com/	https://www.instagram.com/alwaysnbloom/
Blossom Floral Design	Florals	615 N Michigan St	South Bend	Indiana	South Bend, Elkhart, Mishawaka, Goshen and Niles	South Bend flower shop that also does wedding flowers and delivers to local venues across Indiana and nearby Michigan towns.	alwaysblossomflowers@gmail.com	574-647-8506	https://blossomfloraldesignalways.com/	https://www.instagram.com/blossom_floral_design_/
Cherry Road Florals	Florals		Granger	Indiana	Northern Indiana and Southern Michigan	Granger wedding florist creating custom ceremony and reception designs, using locally grown flowers when they are in season.			https://cherryroadflorals.com/	https://www.instagram.com/cherryroadflorals/
Sincerely Good Music	Music		South Bend	Indiana	Northern Indiana and southern Michigan, including South Bend and Mishawaka	Wedding DJ service with a dedicated weddings section, covering South Bend, Mishawaka, Goshen and a wide stretch of northern Indiana.	dmp.sgm@gmail.com	260-615-5977	https://sincerelygoodmusic.com/south-bend-indiana-dj/	
Party Tyme DJ	Music	3218 York St	Mishawaka	Indiana	Northern Indiana and Southwest Michigan	Mishawaka DJ company playing wedding ceremonies and receptions across South Bend, Elkhart and into southwest Michigan.		574-220-1409	https://partytymedjsb.com/	https://www.instagram.com/partytymedjsb/
Mishawaka DJ	Music		Mishawaka	Indiana	Mishawaka and South Bend	Mishawaka DJ with a dedicated weddings page, providing sound and music for receptions around Mishawaka and the wider Michiana area.	djmishawaka@gmail.com	574-307-9935	https://www.djmishawaka.com/	
R&S Entertainment The Wedding Event Co.	Music		Mishawaka	Indiana		Mishawaka DJ and event company that bundles DJ, photography, video, photo booth and lighting into custom wedding packages.		574-238-7382	https://www.randsentertainment.com/	https://www.instagram.com/weddingeventcompany/
Silver Strings Quartet	Music		South Bend	Indiana	Northern Indiana and southern Michigan	South Bend string quartet playing prelude and ceremony music for weddings and events, with over 70 years of combined experience.			https://www.thesilverstrings.com/	
The Landing Catering	Catering	2801 S Michigan St	South Bend	Indiana	South Bend and Michiana	South Bend caterer with over 25 years of wedding experience, offering plated or buffet menus, bar service and staffing at its own and partner venues.		574-299-9126	https://www.landingcatering.com/	
Navarre Catering and Events	Catering	727 S Eddy St	South Bend	Indiana		South Bend caterer run by Navarre Hospitality Group, serving weddings with stations, passed hors d'oeuvres, bar service and tastings.	info@navarrecatering.com	574-217-8359	https://www.navarrecatering.com/	https://www.instagram.com/navarrecateringandevents/
South Bend Catering	Catering		South Bend	Indiana	South Bend and Elkhart	South Bend caterer listing wedding catering among its services, with delivery and service around South Bend and Elkhart.		574-475-6980	https://www.southbendcatering.com/	
C'est La Vie Cakes	Cake	2917 E Mishawaka Ave	South Bend	Indiana	South Bend, Notre Dame and Southwest Michigan	South Bend bakery founded in 2010 making wedding cakes, cupcakes and dessert bars, and handling over 200 weddings a year.	courtneyehopkins@gmail.com	574-220-6438	https://southbendweddingcakes.com/	
Glorious Sugar Creations	Cake		South Bend	Indiana		South Bend studio making custom wedding cakes, cupcakes and cookies for couples.			https://www.glorioussugarcreations.com/	https://www.instagram.com/glorioussugarcreations/
Mini Delights Bake Shoppe	Cake	217 S Main St	Elkhart	Indiana		Elkhart bake shop making custom cakes, cupcakes and cookies, with a wedding category on its site and tastings for larger events.		574-286-9902	https://elkhartbakery.com/	https://www.instagram.com/minidelightsbakeshoppe/
Salon Nouveau	Hair & Makeup	7220 Heritage Square, Suite 530	Granger	Indiana	South Bend and Granger	Salon with Granger and downtown South Bend locations offering bridal updos, trial runs and styling for the wedding party.	lacie@salonnouveau.com	574-272-6767	https://www.salonnouveau.com/for-the-bride.php	`,
  },
  {
    name: "Evansville: photography, videography, planning, florals, music, catering, cake and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Phoenix Down Photography	Photography		Evansville	Indiana	Indiana, Kentucky, Tennessee and destination weddings	Husband-and-wife team in Evansville shooting candid weddings and elopements, with wedding films also on offer.			https://www.phoenixdownphotography.com/	https://www.instagram.com/phoenix_down_photography/
Aurie Janae Photography	Photography		Evansville	Indiana	Evansville, Indiana, and Washington State; travels	Evansville photographer for intimate weddings, elopements and engagement sessions, with a blog of recent real weddings.			https://auriejanaephoto.com/	https://www.instagram.com/auriejanaephotography/
Eleanor Elaine Photography	Photography		Evansville	Indiana	Midwest and beyond	Evansville photographer, established 2019, covering weddings, elopements and couples sessions across the Midwest.	hello@eleanorelainephoto.com		https://www.eleanorelainephoto.com/	https://www.instagram.com/eleanorelainephoto/
Brittney Moseby Photo & Video	Photography		Evansville	Indiana	Indiana and the Midwest	Evansville team shooting wedding photography and engagements, with highlight films and full toast clips as video options.			https://brittneymoseby.com/	https://www.instagram.com/brittneymoseby/
Kalli June Photography	Photography		Jasper	Indiana	Southern Indiana	Jasper photographer whose blog shows many Southern Indiana weddings, from event barns to outdoor ceremonies.	hello@kallijune.com		https://www.kallijune.com/	https://www.instagram.com/kalli.june.photo/
Meghan Premuda Photo	Photography		Jasper	Indiana	Midwest and destination weddings	Jasper wedding photographer working since 2010, taking Midwest and destination weddings and booking into 2027.			https://meghanpremuda.com/	https://www.instagram.com/meghanpremuda/
Planning Forever Events	Planning		Newburgh	Indiana	Indiana and Kentucky, including Evansville and Owensboro	Newburgh planning studio, established 2003, offering full-service planning and month-of coordination for local weddings.	saundra@planningforever.com	812-518-0094	https://planningforever.com/	https://www.instagram.com/planningforever/
Daylily Events	Planning		Evansville	Indiana	Available to travel	Evansville planner offering full-service wedding planning and a coaching option for couples who want guidance as they plan.			https://www.daylilyevents.com/	https://www.instagram.com/daylilyevents/
Zeidler's Flowers	Florals	2011 North Fulton Ave	Evansville	Indiana	Evansville and Newburgh	Evansville florist whose wedding designers book appointments for bouquets, boutonnieres, altar flowers and reception centrepieces.		812-402-1234	https://www.zeidlers.com/wedding-flowers/	https://www.instagram.com/zeidlersflowers/
Emerald Design	Florals	427 Main Street	Evansville	Indiana	Evansville and the Tri-State area	Downtown Evansville flower shop treating weddings as a specialty, with pew and aisle decor, backdrops and locally grown stems in season.	emeraldevv@gmail.com	812-568-4460	https://emeraldevv.com/	https://www.instagram.com/emeraldevv/
It Can Be Arranged	Florals	12500 US Highway 41 N, Suite 2	Evansville	Indiana	Evansville, McCutchanville, Newburgh, Henderson and Princeton	North-side Evansville flower shop that designs for weddings and events, with a wide online selection of fresh blooms.	itcanbearrangedin@gmail.com	812-402-5555	https://itcanbearrangedin.com/	
Jesse Jeanne's Flowers	Florals		Newburgh	Indiana		Newburgh flower shop designing custom fresh arrangements for weddings, with flower preservation and classes as extras.		812-853-6622	https://jessejeannesflowers.com/	
All About You DJ	Music	4600 Washington Ave, Suite 103	Evansville	Indiana		Evansville DJ company focused on weddings, with ceremony, cocktail hour and reception music, MC work, uplighting and photo booths.	info@allaboutyoudj.com	812-402-0610	https://www.allaboutyoudj.com/	
sonusdj	Music		Evansville	Indiana	Evansville, Newburgh, Boonville, Rockport, Vincennes, Owensboro and Henderson	DJ service for Evansville and Newburgh weddings, offering ceremony music, lighting, a photo booth and a 360 video booth.			https://sonusdj.com/evansville-indiana-newburgh-indiana-wedding-dj-photo-booth-ceremony-music-lighting-360-video-booth/	
Miller's Catering	Catering		Evansville	Indiana	Evansville and surrounding Indiana, Kentucky and Illinois	Evansville barbecue caterer with wedding packages in plated or buffet style, plus a mobile smokehouse for off-site events.		812-454-2744	https://millersbarbecue.com/	https://www.instagram.com/millersbarbecue/
Julie Catering	Catering	708 W Louisiana St	Evansville	Indiana	Evansville and the tri-state area	Evansville caterer specialising in slow-smoked barbecue, with custom wedding menus, rehearsal dinner packages and setup and breakdown.	julie@juliecatering.com	914-494-3224	https://www.juliecatering.com/	
Pappa Bear's Catering	Catering	122 N Weinbach Ave	Evansville	Indiana		Owner-run Evansville caterer that lists wedding catering among its services, with the owner involved from cooking through to serving.		812-568-8890	https://pappabearscatering.com/	
Marx Barbecue & Catering	Catering		Evansville	Indiana		Evansville barbecue caterer building personalised wedding menus, known for whole hog catering as a showpiece for receptions.	marxbbq@yahoo.com	812-425-1616	https://marxbbq.com/catering	
Salon One	Hair & Makeup	951 S Hebron Ave	Evansville	Indiana		Evansville salon with several hundred weddings behind it, offering bridal hair and makeup, trials and wedding party services.		812-473-2574	https://www.salononeevv.com/	https://www.instagram.com/salon.one/
Fusion Spa & Salon	Hair & Makeup	7144 E Virginia St, Suite D	Evansville	Indiana		Evansville spa and salon offering bridal updos, curls and makeup, at the salon or on location on the wedding day.		812-402-6004	https://www.fusionspaevansville.com/salon-services/wedding-hair-and-makeup/	https://www.instagram.com/fusionspaevv/
Impulse Salon & Spa	Hair & Makeup	428 W Jennings St	Newburgh	Indiana		Family-owned Newburgh salon with customisable bridal services covering hair, skin, nails and makeup, and free consultations.	ptap4adam@gmail.com	812-210-5040	https://www.impulsehair.com/bridal-services	https://www.instagram.com/impulsehair/
Piece of Cake Bakery	Cake	210 Main Street	Evansville	Indiana	Evansville	Downtown Evansville bakery making classic and custom wedding cakes and cupcakes, with a flavour sampler for couples to try.		812-424-2253	https://www.pieceofcakebakery.com/wedding-cakes/	https://www.instagram.com/pieceofcake_bakery/
Bea Sweet Treats	Cake	4111 Merchant Dr	Newburgh	Indiana		Mother-daughter bakery in Newburgh making cakes, cupcakes, cookies and macarons, with a wedding page and custom orders.		812-454-7728	https://www.beasweettreats.com/	https://www.instagram.com/beasweettreats/
Avalon Studios	Videography		Evansville	Indiana		Evansville wedding film studio with two videographers and five selectable film styles, from vintage to black tie.			https://www.theavalonstudios.com/	https://www.instagram.com/theavalonstudios/
Ivory Lace Photo & Film	Videography		Evansville	Indiana	Indiana, Kentucky, Illinois, Missouri, Ohio, Michigan and Tennessee	Husband-and-wife photo and film team, John and Jen Richard, covering weddings across the Midwest and Tennessee.	ivorylacephotofilm@gmail.com	812-431-5996	https://www.ivorylacephotoandfilm.com/	https://www.instagram.com/ivorylacephotoandfilm/`,
  },
  {
    name: "Indianapolis: photography, videography, planning, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Imagery by Lindley	Photography		Indianapolis	Indiana		Indianapolis photographer covering weddings, engagements and lifestyle sessions, with a classic, polished approach to couples' portraits.	imagerybylindley@gmail.com		https://imagerybylindley.com/	https://www.instagram.com/imagerybylindley/
Vallosio Photo + Film	Photography		Indianapolis	Indiana		Husband-and-wife photo and video team for calm, nature-centred weddings and elopements, with outdoor ceremonies a speciality.	vallosiophotoandfilm@gmail.com		https://vallosiophotoandfilm.com/	https://www.instagram.com/vallosiophoto.film/
Kevin Riley Films	Videography		Indianapolis	Indiana		Indianapolis videographer making personalised wedding films alongside commercial work, with a focus on telling each couple's own story.			https://kevinrileyfilms.com/	https://www.instagram.com/kevin_riley_films/
Handheld Weddings	Videography		Indianapolis	Indiana		Documentary wedding films shot as the day unfolds, with a full-day film and a short story film for every couple.		(317) 847-0038	https://handheldweddings.com/	
Arbor & Bloom Events	Planning		Indianapolis	Indiana		Indianapolis planner offering full planning, partial planning and day-of coordination packages, plus design and one-off consultations.	megan@arborandbloomevents.com	303.949.9205	https://arborandbloomevents.com/	https://www.instagram.com/arborandbloomevents/
Woven Blooms	Florals		Indianapolis	Indiana		Boutique florist for weddings and events, designing around the natural character of each stem with seasonal, locally grown blooms.	wovenblooms@gmail.com		https://wovenblooms.com/	https://www.instagram.com/wovenblooms/
Solstice Floral Design	Florals		Indianapolis	Indiana		Indianapolis floral studio creating nature-inspired arrangements for weddings and special occasions, led by owner and designer Angela Stoffregen.	angela@solsticefloral.com		https://solsticefloral.com/	https://www.instagram.com/solsticefloral/
Higher Love Entertainment and Events	Music		Indianapolis	Indiana		Wedding DJs and MCs with custom playlists, plus dance floors, photo booths and special-effects lighting for receptions.	info@higherloveentertainmentandevents.com	317-560-7912	https://www.higherloveentertainmentandevents.com/	https://www.instagram.com/higherloveentertainment/
Complete Weddings + Events Indianapolis	Music	4770 S. Emerson Ave, Suite H	Indianapolis	Indiana		DJ company that also supplies photographers, videographers, photo booths and coordinators, with discounts when couples bundle services.		317.771.4829	https://www.completeindy.com/	https://www.instagram.com/completeindy/
Kahn's Catering	Catering	8580 Allison Pointe Blvd	Indianapolis	Indiana		Indianapolis caterer for weddings in its own historic venues, with Indian wedding menus and a stated welcome for LGBTQ+ couples.	info@kahnscatering.com	(317) 577-3663	https://www.kahnscatering.com/	https://www.instagram.com/kahnscatering/
Sahm's Catering	Catering	2502 East 52nd Street	Indianapolis	Indiana	Indianapolis and central Indiana	Family-owned caterer serving central Indiana since 1986, with bread and coffee cake baked in the family bakery.	catering@sahms.com	(317) 536-1305	https://www.sahmscatering.com/	https://www.instagram.com/sahmscateringandevents/
Laura Snyder Hair	Hair & Makeup		Indianapolis	Indiana	Hamilton County and Indianapolis	Licensed on-location bridal hairstylist, working since 2008, known for classic updos, half-ups and natural curl styles.	laura@laurasnyderhair.com		https://laurasnyderhair.com/	https://www.instagram.com/laurasnyderhair/
Beauty Haven Indy	Hair & Makeup		Indianapolis	Indiana		Indianapolis makeup team for brides who want soft, natural glam, offering consultations and calm wedding-morning support.			https://www.beautyhavenindy.com/	https://www.instagram.com/beautyhavenindy/
Jacke Wray Beauty	Hair & Makeup		Indianapolis	Indiana		Indianapolis bridal makeup artist offering airbrush, lash application, trials and group bookings, on location or at a salon.			https://www.jackewray.com/	https://www.instagram.com/jackewraybeauty/
Confectioneiress Cupcakes & Sweets	Cake	80 Brendon Way	Zionsville	Indiana	Zionsville and Indianapolis	Bakery making wedding cakes, cupcakes, macarons and dessert bars, with shops in Zionsville and on Mass Ave in Indianapolis.	info@confectioneiress.com	(317) 873-0880	https://confectioneiress.com/	https://www.instagram.com/confectioneiress/`,
  },
  {
    name: "Bloomington: catering and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Chef's Table Catering	Catering		Bloomington	Indiana	Bloomington	Chef-owned Bloomington caterer for weddings, corporate lunches and celebrations, with menus built from appetisers through dessert.	chefstablecater@gmail.com	(812) 287-8016	https://chefstablecateringbloomington.com/	https://www.instagram.com/chefs_table.catering/
Cake Scraps	Cake		Bloomington	Indiana		Bloomington baker of custom wedding cakes, cupcakes and cookies, with quotes built from couples' photos and colour palettes.	cakescrapsus@gmail.com		https://cakescraps.squarespace.com/	https://www.instagram.com/cakescraps_us/`,
  },
];

export default batches;
