import type { VendorBatch } from "@/lib/vendor-batches";

// Iowa vendor batches. Every row's State is "Iowa". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Des Moines: photography, planning, florals, music, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jason Thomas Crocker Photography	Photography	833 42nd St	Des Moines	Iowa	Des Moines, Iowa and the wider Midwest	Des Moines photographer with more than 800 weddings behind him, shooting unobtrusive, natural-looking images without heavy filters.	jason@jasonthomascrocker.com	515-216-0650	https://www.jasonthomascrocker.com/	https://www.instagram.com/jasontcrocker/
The Wedding Format	Photography		Des Moines	Iowa	Des Moines, with travel to Minneapolis, Kansas City, Chicago and Omaha	Husband-and-wife duo mixing digital and film photography with a candid, relaxed style, and offering Super 8mm wedding films.	booking@theweddingformat.com		https://theweddingformat.com/	https://www.instagram.com/theweddingformat/
Corah B Photography	Photography		Des Moines	Iowa	Des Moines and nearby areas including Ames, Omaha and Dubuque	Des Moines wedding photographer focused on small, everyday moments of the day, who also offers bridal boudoir sessions.			https://corahbphotography.com/	https://www.instagram.com/corah.b.photography/
Uniqu Co. Events & Planning	Planning		Des Moines	Iowa	Des Moines area	Down-to-earth Des Moines planner offering day-of coordination and partial planning, with setup and breakdown crews available.			https://uniqucoevents.com/	https://www.instagram.com/uniqucoevents/
Stuart Alexander Productions	Planning	100 Indiana Ave	Des Moines	Iowa		Des Moines event company that plans, coordinates and styles weddings, with rentals, lighting and Indian wedding experience in-house.		515-953-2500	https://www.stuartalexanderproductions.com/	https://www.instagram.com/stuartalexanderproductions/
Everlasting Events	Planning		Des Moines	Iowa	Des Moines and Iowa	Sister-run Des Moines planning company offering full, partial and final-months coordination aimed at budget-conscious couples.			https://www.everlastingeventsdsm.com/	
CamBam Custom Floral	Florals	10536 Justin Dr	Urbandale	Iowa	Des Moines area	Woman-owned studio designing custom wedding bouquets, ceremony installations and reception styling, with rental decor and a la carte options.	cambamcustomfloral@gmail.com	515-468-9600	https://www.cambamcustomfloral.com/	https://www.instagram.com/cambamfloral_llc/
Something Chic Floral	Florals	1905 E.P. True Park Way, Suite 209	West Des Moines	Iowa	Des Moines area	West Des Moines studio focused only on wedding and event flowers, with clean-lined designs and showroom consultations by appointment.	danielle@somethingchicfloral.com	515-556-0835	https://somethingchicfloral.com/	
Bella Flora	Florals	3100 Justin Dr, Suite A	Urbandale	Iowa	Des Moines area	Urbandale floral and event design studio, working since 2004 with an in-house team across a range of styles and budgets.		515-554-6964	https://bellafloraeventdesign.com/	https://www.instagram.com/bellafloradsm/
Marquee Events	Music		Des Moines	Iowa	Des Moines and central Iowa	Des Moines DJ company pairing MCs with lighting design and optional live musicians, and a regular at the city's hotel and downtown venues.	info@marqueeeventsiowa.com	515-957-7770	https://www.marqueeeventsdjs.com/	https://www.instagram.com/marqueeeventsdjs/
DSM Dance Party DJs	Music		Des Moines	Iowa	Iowa	Des Moines wedding DJs who add dance floors, lighting and effects to keep the reception busy from the first song.	booking@dsmdancepartydjs.com	515-512-2003	https://www.dsmdancepartydjs.com/	https://www.instagram.com/dsmdancepartydjs.co/
Yeti House Entertainment	Music		Ankeny	Iowa	Central Iowa	Ankeny DJ and emcee service for weddings, school dances and private parties, also running weekly trivia nights across the metro.	djyetihouse@gmail.com	515-729-3096	https://www.yetihouseentertainment.com/	https://www.instagram.com/djyetihouse/
Christiani's VIP Catering Service	Catering	1150 E Diehl Ave	Des Moines	Iowa	Des Moines area	Family-run Des Moines caterer with more than 40 years behind it, supplying linens, china, uniformed staff and a banquet captain.	christianiscatering1@gmail.com	515-287-3169	https://www.christianiscatering.com/	
Gateway Market	Catering	2002 Woodland Ave	Des Moines	Iowa	Des Moines	Independent Des Moines specialty grocer and cafe, with a bakery and chef-led kitchen that also caters weddings and events off-site.	info@gatewaymarket.com	515-243-1754	https://www.gatewaymarket.com/	https://www.instagram.com/gatewaymarket/
Tangerine Food Co	Catering	900 Keosauqua Way, Suite 131	Des Moines	Iowa	Des Moines	Downtown Des Moines caterer that also hosts events in its own studio-building space, serving fresh, locally sourced menus.	info@tangerinefoodco.com	515-720-7510	https://www.tangerinefoodco.com/	
DSM Salon	Hair & Makeup	849 42nd St	Des Moines	Iowa	Des Moines	Des Moines salon with a dedicated bridal team trained across hair and skin types, matching each bride to a stylist through a short survey.			https://dsmsalon.com/	https://www.instagram.com/dsmsalonia/
Salon Au	Hair & Makeup	1325 SW Oralabor Rd, Suite 216	Ankeny	Iowa	Ankeny and Des Moines, in-salon or on location	Ankeny salon with a bridal team offering wedding hair and makeup in the salon or on location, led by stylist Michelle Golden.	info@salonau.com	833-244-9360	https://www.salonau.com/	https://www.instagram.com/salonauiowa/
Sweet Cactus Bakery	Cake		Pleasant Hill	Iowa	Des Moines area	Pleasant Hill bakery run by Erin Leutscher making custom wedding cakes and cupcakes from the couple's own design ideas and reference photos.	sweetcactusbakery19@gmail.com	515-321-9174	https://www.sweetcactusbakery.com/	https://www.instagram.com/sweetcactusbakery/
Parinda Cupcakes	Cake		Des Moines	Iowa	Des Moines	Home-based Des Moines baker making designer wedding cakes with hand-piped buttercream flowers, plus simpler pre-designed cakes for tighter budgets.	may@parindacupcakes.com	515-771-3342	https://www.parindacupcakes.com/	https://www.instagram.com/parindacupcakes/
Bake Sale Customs	Cake		Des Moines	Iowa	Des Moines area	Des Moines custom cake and dessert bakery that makes wedding cakes, known for star and heart-shaped designs and quality ingredients.			https://www.bakesalecustoms.com/	https://www.instagram.com/bakesalecustoms/
Reed Shepherd Films	Videography		Des Moines	Iowa	Iowa, and travels widely	Des Moines wedding filmmaker making upbeat, personality-led films with teaser, feature and aerial options, and happy to travel.			https://reedshepherdfilms.com/	https://www.instagram.com/reedshepherdfilms/
5 Point Visuals	Videography		Des Moines	Iowa	Iowa	Des Moines filmmaker-photographer who keeps wedding days low-key and unposed, also offering photo booth rental.			https://5pointvisuals.com/	https://www.instagram.com/kyle_starcevich/
`,
  },
  {
    name: "Des Moines: hair and makeup and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jene Beauty	Hair & Makeup	815 Office Park Rd, Suite 9	West Des Moines	Iowa	Des Moines metro	West Des Moines esthetician and makeup artist offering bridal makeup, lash services and lessons from a studio suite, with on-site work for wedding parties.		515-867-3430	https://www.jenebeauty.com/	https://www.instagram.com/jenebeauty__/
Feilmeier Films	Videography		Des Moines	Iowa	Des Moines, the Midwest and beyond	Des Moines filmmaker covering weddings alongside lifestyle, travel and commercial work, shooting around Iowa, the wider Midwest and farther afield.			https://www.feilmeierfilms.com/weddings	https://www.instagram.com/feilmeierfilms/
`,
  },
  {
    name: "Cedar Rapids: photography, planning, florals, music, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Rock Tai Photography	Photography		Cedar Rapids	Iowa	Cedar Rapids and Iowa City	A Cedar Rapids photographer and videographer covering weddings, engagements and wedding films, travelling beyond 20 miles for a fee.	rocktaiphotography@gmail.com		https://rocktaiphotography.com/	https://www.instagram.com/rocktaiphoto/
Unhinged Floral Co.	Florals		Cedar Rapids	Iowa	Cedar Rapids and beyond	A boutique Cedar Rapids wedding florist making whimsical, artistic pieces from unexpected textures and colour combinations.	unhingedfloral@gmail.com		https://www.unhingedfloral.com/	https://www.instagram.com/unhingedfloralco/
Ella Floral Design	Florals		Cedar Rapids	Iowa	Cedar Rapids, Iowa City, Marion, Galena and Eastern Iowa	A family-run boutique floral studio in Cedar Rapids designing lush, timeless wedding flowers across Eastern Iowa.	hello@ellabankblossoms.com		https://www.ellafloraldesign.com/	https://www.instagram.com/ellabankblossoms/
Zest Catering Company	Catering	5977 Mt. Vernon Rd SE	Cedar Rapids	Iowa	Cedar Rapids, Hiawatha, Marion, Iowa City, Coralville, West Branch and Anamosa	A Cedar Rapids caterer offering custom wedding menus from plated and family-style dinners to action stations and charcuterie.		319-261-1032	https://www.zestcateringco.com/	https://www.instagram.com/zestcateringco/
Peppercorn Food Company	Catering	101 3rd Ave SW	Cedar Rapids	Iowa	Eastern Iowa and western Illinois	A scratch-kitchen caterer with a downtown Cedar Rapids base and a second kitchen in Dubuque, serving weddings from simple to grand.	jude@peppercornfoodcompany.com	319-654-6044	https://www.peppercornfoodcompany.com/	https://www.instagram.com/peppercornfoodco/
Goldfinch Tap + Eatery	Catering		Marion	Iowa	Marion area	A Marion restaurant that offers drop-off and full-service catering and a private banquet space for wedding receptions.	hello@goldfinchtap.com	319-246-3238	https://www.goldfinchtap.com/	https://www.instagram.com/goldfinchmarion/
Madisen Timp Weddings	Photography		Cedar Rapids	Iowa	Iowa, with travel across the US	A husband-and-wife Cedar Rapids team shooting weddings as photo and video in digital, film and Super 8, with a documentary approach.	madisentimpweddings@gmail.com		https://madisentimpweddings.com/	
Whitepeak Films	Videography		Cedar Rapids	Iowa		A Cedar Rapids videography company making personal, cinematic wedding films alongside nonprofit documentaries and commercial video.	richie@whitepeakfilms.com	319-640-7663	https://whitepeakfilms.com/	https://www.instagram.com/whitepeakfilms/
Pretty Little Vows	Planning		Cedar Rapids	Iowa	Throughout Iowa	A Cedar Rapids wedding planning and coordination business offering full planning and day-of support to couples across Iowa.	support@prettylittlevows.com		https://www.prettylittlevows.com/	
Sugar Flower Cake Design	Cake		Cedar Rapids	Iowa		A Cedar Rapids cake studio making luxury wedding cakes and groom's cakes, known for hand-made sugar flowers.		319-491-1938	https://www.sugarflowercakedesign.com/	https://www.instagram.com/sugarflowercake101/
Take the Cake Desserts	Cake		Marion	Iowa	Eastern Iowa	A Marion dessert company making wedding cakes and dessert tables by appointment, with consultations by phone or in person.	ttcbusiness2020@gmail.com	319-382-2936	https://www.takethecakedesserts.com/	https://www.instagram.com/takethecakedesserts/
Classic Cakes By Design	Cake		Cedar Rapids	Iowa	Cedar Rapids and Marion	A Cedar Rapids cake bakery with around thirty years' experience making custom wedding cakes, cupcakes, sugar cookies and dessert bars.			https://classiccakesbydesign.com/	
Hydrangea Bloom	Florals		Tiffin	Iowa	Iowa City, Coralville, Cedar Rapids, Des Moines, Davenport and Dubuque	A Tiffin floral design studio, open since 2016, with the owner designing every wedding arrangement personally across the Iowa City corridor.	info@hydrangeabloom.com		https://www.hydrangeabloom.com/	https://www.instagram.com/hydrangeabloomia/
Bellefleur Productions	Videography		Iowa City	Iowa	Iowa City and the Midwest	A two-brother Iowa City team filming cinematic wedding films, combining film-making and event experience.	info@bellefleurproductions.com		https://www.bellefleurproductions.com/	https://www.instagram.com/bellefleurproductions/
Erin Allsup Photography	Photography		Cedar Rapids	Iowa	Cedar Rapids, Eastern Iowa and the Midwest	A Cedar Rapids wedding photographer capturing honest, romantic, film-inspired moments for couples across Eastern Iowa and beyond.			https://erinallsupphotography.com/	https://www.instagram.com/erinallsupphotography/
Iowa Party Starters	Music		Cedar Rapids	Iowa	Iowa	A Cedar Rapids DJ company offering affordable wedding music with event lighting, a photo booth and special effects.	iowapartystarters@gmail.com	319-487-4482	https://www.iowapartystarters.com/	https://www.instagram.com/iowaweddingdj/
Lindsey Michelle MUA	Hair & Makeup		Cedar Rapids	Iowa	Cedar Rapids, mainly on location	A freelance Cedar Rapids makeup artist who works mostly on location for weddings, offering natural but enhanced looks and trials.	lindsey.michelle.mua@gmail.com	319-775-0610	https://lindseymichellemua.com/	https://www.instagram.com/lindseymichellemua/
Vibrations DJ	Music		Cedar Rapids	Iowa	Cedar Rapids, Iowa City, Waterloo, Dubuque and Des Moines	A Cedar Rapids DJ service providing wedding and corporate entertainment across Eastern Iowa, built on repeat business and client referrals.	tony@vibrationsdj.com	319-721-9956	https://vibrationsdj.com/	
DJ Davin Titus	Music		Iowa City	Iowa	Iowa City and destination events	An Iowa City wedding DJ offering sound, dance-floor and uplighting, live mixing and emceeing, who began DJing at the University of Iowa.			https://www.davintitus.com/	https://www.instagram.com/dj_davin_titus/
Beauty Op by S. Mueller	Hair & Makeup	595 Ashley Ct	North Liberty	Iowa	Eastern Iowa and the Midwest	A North Liberty bridal beauty studio with a team of hair and makeup artists, serving Eastern Iowa and the wider Midwest.	beautyop@gmail.com		https://www.beautyopbysm.com/	https://www.instagram.com/beautyopbys.mueller/
Blackbird Events	Planning		Cedar Rapids	Iowa		A Cedar Rapids wedding and event planning business that also offers day-of coordination for couples wanting a stress-free day.	maggie@blackbird-events.com	319-521-0695	https://blackbirdevents.net/	https://www.instagram.com/blkbrdevents/
`,
  },
  {
    name: "Iowa City: florals, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Studio Bloom Iowa	Florals		Ely	Iowa	Cedar Rapids, Iowa City and East Central Iowa	Boutique wedding florist making garden-style bouquets, ceremony arches and centrepieces with specialty and local blooms, working since 2013.	tiffany@studiobloomiowa.com	319-423-9464	https://studiobloomiowa.com	https://www.instagram.com/studiobloomiowa/
Main Event Catering	Catering	1220 1st Avenue	Coralville	Iowa	Coralville, Iowa City, Cedar Rapids, Amana, Tiffin, West Branch, West Liberty, Solon and within about an hour	Full-service Coralville caterer offering plated entrees, buffets, barbecue and appetisers, with servers, set-up and teardown for weddings.		319-351-0645	https://www.maineventcatering.com/coralville-catering	
Amos Deans Catering	Catering	1829 Mehaffey Bridge Road NE	Solon	Iowa	Eastern Iowa	Scratch-kitchen caterer and food truck in Solon that cooks wedding banquets and plated dinners, and also runs The Exchange on Vine venue.	amosdeans@amosdeans.com	(319) 321-7779	https://www.amosdeans.com	https://www.instagram.com/amosdeansiowa/
Plated Table	Catering	625 S Dubuque St	Iowa City	Iowa	Iowa City area	Iowa City wine shop and event space that caters from-scratch seasonal menus and hosts wedding receptions at its South Dubuque Street home.	platedtable@gmail.com	319-200-3663	https://platedtablecatering.com	https://www.instagram.com/plated.table/
Bread Garden Market	Catering	225 S Linn Street	Iowa City	Iowa	Venues up to about 35 minutes from downtown Iowa City	Downtown Iowa City grocery and bakery whose kitchen team caters weddings, arriving at venues to set up and serve guests.	breadgardenmarketic@gmail.com	319-351-9119	https://breadgardenmarket.com	https://www.instagram.com/breadgardenmarket/
Catered By Charlotte	Catering	580 Hwy 1 West	Iowa City	Iowa	Iowa City, Coralville and surrounding areas	Iowa City caterer operating since 2000 that handles weddings and large events of any size, using fresh ingredients and a full service team.	info@cateredbycharlotte.com	319-321-1577	https://www.cateredbycharlotte.com	https://www.instagram.com/cateredbycharlotte/
Tru Salon	Hair & Makeup	2201 E Grantview Dr, Suite 100	Coralville	Iowa	Coralville, in salon or on location at the wedding	Coralville salon offering bridal hair and makeup in the salon or on location, with a dedicated wedding coordinator and tiered party experiences.	oakdale@tru-salon.com	319-354-2833	https://tru-salon.com	https://www.instagram.com/trusalonia/
Bespoke Beauty LLC	Hair & Makeup		Brooklyn	Iowa	Central and Eastern Iowa, including Cedar Rapids, Iowa City and Des Moines	Brooklyn-based bridal hairstylist who travels to venues across Iowa, known for frizz-free waves and modern buns.	bespokebeauty24@gmail.com		https://www.bespokebeautyllc.com	https://www.instagram.com/bespoke_beauty_llc/
Salon Voche	Hair & Makeup	5940 Rockwell Drive NE	Cedar Rapids	Iowa	Cedar Rapids, Coralville, Iowa City and Marion	Cedar Rapids salon that styles brides and their parties, with consultations and practice appointments before the wedding day.	info@salonvoche.com	(319) 554-9576	https://www.salonvoche.com	https://www.instagram.com/salonvoche/
Thompson & Co. Salon Parlor	Hair & Makeup		Iowa City	Iowa	Iowa City, Coralville and the Corridor	Iowa City salon offering wedding hair and bridal trials, with bridal parties limited to current or past salon guests and their families.		(319) 499-1041	https://thompsoncosalon.com	https://www.instagram.com/tcosalon/
Baked with Grace	Cake		Anamosa	Iowa	Cedar Rapids, Iowa City, the Corridor and the Quad Cities	Anamosa baker making buttercream-only floral wedding cakes, cupcake towers and dessert tables, with delivery available around eastern Iowa.	bakedwithgraceia@gmail.com	(319) 491-3533	https://bakedwithgrace-ia.com	https://www.instagram.com/bakedwithgrace.ia/
Iced Bakery	Cake	361 7th Ave	Marion	Iowa	Marion, Cedar Rapids, Hiawatha, Iowa City and surrounding areas	Made-to-order Marion bakery creating custom-designed cakes plus cookies, cupcakes and pies for weddings and other celebrations.		(319) 389-1328	https://www.icedbakeryllc.com	https://www.instagram.com/icedbakeryllc/
Tip Top Cakes	Cake		Iowa City	Iowa	Eastern Iowa	Iowa City baker creating custom wedding cakes and desserts for couples across eastern Iowa.			https://www.tiptopcakes.com	
Arbor + Light	Videography		Iowa City	Iowa	Weddings anywhere in Iowa and beyond, with travel fees past 60 miles	Husband-and-wife team in Iowa City filming cinematic wedding highlight films, with photography bundles and a lead filmmaker on every wedding.			https://www.arborandlight.com	https://www.instagram.com/arborandlight/
Diamond Label Films	Videography		Iowa City	Iowa	Iowa	Iowa City filmmaker making cinematic wedding films with an authentic storytelling approach, alongside engagement and wedding photography.	diamondlabelfilms@gmail.com		https://www.diamondlabelfilms.com	https://www.instagram.com/iowaweddingvideographer/
`,
  },
];

export default batches;
