import type { VendorBatch } from "@/lib/vendor-batches";

// Kentucky vendor batches. Every row's State is "Kentucky". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Louisville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Sarah Katherine Davis Photography	Photography		Louisville	Kentucky	Louisville and Kentucky	Documentary-leaning wedding and elopement photographer blending candid moments with fine-art portraits, with a strong welcome for LGBTQ+ couples.	info@sarahkatherinedavis.com		https://www.sarahkatherinedavis.com/	https://www.instagram.com/sarahkatherinedavisphotography/
Jeff & Michele Wedding Photographers	Photography		Louisville	Kentucky	Louisville, Lexington and destinations	Husband-and-wife photojournalist team shooting relaxed, natural-light coverage of weddings across Kentucky and abroad since 2015.	contact@jeffandmichelephoto.com	502-551-5799	https://jeffandmichelephoto.com/	https://www.instagram.com/jeffandmichelephoto/
Rach Loves Troy	Photography		Louisville	Kentucky	Weddings around the country	Married photographer and filmmaker duo offering documentary-style wedding photos and films, so one team can cover both stills and video.			https://rachlovestroy.com/	https://www.instagram.com/rachlovestroy/
MM Photo Co.	Photography		Louisville	Kentucky	No travel fee within 90 miles of Louisville	Solo photographer mixing candid documentary coverage with directed portraits, edited in a classic, true-to-colour style.	madison@mmphotoco.com		https://mmphotoco.org/	https://www.instagram.com/mm_photoco/
Heleringer Events	Planning		Louisville	Kentucky	Louisville and beyond	Design-led planning firm offering full, partial and day-of coordination, taking a limited number of couples so no two weddings repeat.	hello@heleringerevents.com	502-653-2321	https://www.heleringerevents.com/	https://www.instagram.com/heleringerevents/
Simply Sara O	Planning	10000 Shelbyville Rd Suite 205	Louisville	Kentucky		Owner-led event studio handling design, fabrication, planning and day-of management for weddings, taking ideas from concept to completion.	sarao@simplysarao.com	502-599-8586	https://www.simplysarao.com/	https://www.instagram.com/simplysarao/
Bliss Events & Co	Planning		Louisville	Kentucky	Louisville, Kentucky, Southern Indiana and beyond	Planning team offering full, partial and month-of packages plus à la carte help, with venue set-up, tear-down and an audio guest book option.	blisseventsandcompany@gmail.com		https://www.blisseventsandco.com/	https://www.instagram.com/blisseventsandco/
Evently	Planning		Louisville	Kentucky	Louisville, Lexington, Southern Indiana and surrounding areas	Wedding planning and design house covering full service to day-of coordination, with its own décor rentals and set-up included in some packages.			https://www.evently.events/	https://www.instagram.com/evently.events/
Zachary Brady Designs	Florals	1000 E Kentucky St	Louisville	Kentucky	Louisville and Lexington	Appointment-only floral studio designing timeless wedding and event flowers, adapting from lush and organic to clean, monochrome looks.	info@zacharybradydesigns.com		https://www.zacharybradydesigns.com/	https://www.instagram.com/zacharybradydesigns/
Bloomed Roots	Florals	746 E Market St	Louisville	Kentucky	Louisville area	Seasonal floral studio and Bloom Bar on East Market Street using mostly local stems for wedding and event work, plus dried everlasting pieces.	bloomedroots@gmail.com	502-612-1271	https://bloomedroots.co/	https://www.instagram.com/bloomedroots/
Petite Refine Floral Studio	Florals	2842 Frankfort Ave	Louisville	Kentucky	Louisville	Frankfort Avenue floral studio designing custom wedding flowers without preset menus or event minimums, alongside daily delivery work.			https://petiterefine.com/	
Rose & Honey Floral	Florals		Louisville	Kentucky		Boutique full-service floral studio run by a couple, specialising in garden-inspired, organic wedding designs built around seasonal blooms.	roseandhoneyfloral@gmail.com		https://roseandhoneyfloral.com/	https://www.instagram.com/roseandhoneyfloral/
Masters of Music	Music	3221 Ruckriegel Pkwy Suite D	Louisville	Kentucky	Louisville and Kentuckiana	Long-running DJ and MC company that pairs reception music with uplighting, monogram lights, photo booths and interactive games.		502-266-5351	https://mastersofmusicdj.com/	https://www.instagram.com/masters_of_music_events/
KUDMANI	Music		Louisville	Kentucky		Live wedding band whose package covers ceremony music, emcee and DJ sets, sound and lighting alongside a high-energy dance set.			https://kudmani.com/	https://www.instagram.com/kudmani_louisvilleweddingband/
64West	Music		Louisville	Kentucky	Louisville and Lexington	Variety dance band with degree-trained musicians playing everything from 60s classics to current radio hits, with an all-inclusive gear package.	booking@64westband.com	502-609-7133	https://www.64westband.com/	https://www.instagram.com/64west/
Wax Factory	Music		Louisville	Kentucky	Louisville area	Party and dance band covering rock, pop, country and soul from the 1950s onward, bringing its own lighting and audio production.	waxfactoryrocks@gmail.com	502-435-7884	https://www.waxfactoryband.com/	https://www.instagram.com/waxfactoryband/
Victoria's Catering	Catering	5410 Valley Station Rd #102	Louisville	Kentucky	Within 60 miles of Louisville	Southern-style caterer serving hot buffets, appetisers, bartending and drink stations, with free wedding tasting consultations.		502-933-2393	https://victoriascatering.com/	
Marigold Catering Company	Catering	498 N English Station Rd #104	Louisville	Kentucky		Chef-driven caterer offering multi-course plated dinners, stations and dessert bars with French, Spanish, Mexican and Asian influences.		502-830-3063	https://www.marigoldcateringco.com/wedding-menus	https://www.instagram.com/marigoldcateringco/
Kingsley Meats & Catering	Catering	2701 Taylorsville Rd	Louisville	Kentucky	Louisville area	Butcher shop and caterer serving fresh-cut meat buffets with wait staff, linens and tableware included, plus free tastings for couples.		502-459-7585	https://kingsleymeatsandcatering.com/wedding-formal-buffet	https://www.instagram.com/kingsleycaters/
True North Catering Co.	Catering		Louisville	Kentucky	Louisville and Kentuckiana	Chef-founded caterer building bespoke menus of elevated comfort food from locally sourced ingredients for weddings and private events.			https://www.truenorthcateringco.com/	https://www.instagram.com/truenorthcatering/
Makeup by Brooke Duvall & Co.	Hair & Makeup	414 Baxter Ave Suite 106	Louisville	Kentucky	Louisville and Southern Indiana; travels	Team of six licensed artists offering airbrush or traditional bridal makeup and hair, on location or in a studio with a bridal suite.			https://www.makeupbybrookeduvall.com/	https://www.instagram.com/makeupbybrookeduvall/
Bridal Bar	Hair & Makeup	11524 Shelbyville Rd	Louisville	Kentucky		Shelbyville Road bridal hair and makeup studio styling brides and wedding parties in looks from soft and natural to bold glam.	bridalbarlouisville@gmail.com	502-536-8850	https://www.bridalbarlouisville.com/	https://www.instagram.com/bridalbarlouisville/
Beauty Lou	Hair & Makeup		Louisville	Kentucky		Rachel Edwards' hair and makeup team works on location or in its own 1,200 sq ft bridal suite where the wedding party can get ready.			https://www.racheledwardsmua.com/	https://www.instagram.com/beautylouky/
Southern Bridal Styles	Hair & Makeup	1515 Bardstown Rd	Louisville	Kentucky		Bardstown Road hair and makeup team styling brides and their wedding parties, with a focus on making each client look and feel unique.	southernbridalstyles@gmail.com	502-919-2842	https://www.southernbridalstyles.com/	https://www.instagram.com/southernbridalstyles/
Sweets by Millie	Cake	223 S Hancock St	Louisville	Kentucky		Hancock Street boutique bakery making custom wedding cakes and decorated cookies, designed to order for each couple.	sweetsbymillie@gmail.com	502-488-8312	https://www.sweetsbymillie.com/	https://www.instagram.com/sweetsbymillie/
The Mixing Bar	Cake		Louisville	Kentucky		Custom bakery making wedding cakes since 2021, known for vintage piping and to-go tasting boxes couples can sample at home.	themixingbar@gmail.com		https://www.themixingbar.com/	https://www.instagram.com/themixingbar/
Mert's Cakes	Cake	11511 Shelbyville Rd	Louisville	Kentucky		Shelbyville Road bakery offering one-of-a-kind wedding cakes alongside its signature praline cakes, brownies and Louie's Derby Cake.		502-244-6200	https://www.mertscakes.com/	https://www.instagram.com/mertscakes/
Reventure Media	Videography		Louisville	Kentucky	Based in Kentucky, travelling worldwide	Boutique studio making cinematic, story-driven wedding films that lean on real audio and unscripted moments, now booking 2027 and 2028.	hello@reventuremedia.com	502-291-2493	https://reventuremedia.com/	https://www.instagram.com/reventuremedia/
Slye Films	Videography		Louisville	Kentucky	Louisville, Lexington, Indianapolis, Cincinnati, Chicago and beyond	Husband-and-wife film team creating unposed, documentary-style wedding films for couples across the Midwest and further afield.	hello@slyefilms.com	812-250-9876	https://slyefilms.com/	https://www.instagram.com/slyefilms/
Jack Brown Videography	Videography		Louisville	Kentucky	Louisville and surrounding areas	Storytelling wedding videographer offering 8-10 hour packages with a preview and highlight film, plus The Louisville Wedding Podcast.			https://www.jackbrownvideography.com/	https://www.instagram.com/jackbrownvideography/
Burn Bright Productions	Videography		Louisville	Kentucky		Film-school-trained videographer Hannah Bright Will shooting authentic, cinematic wedding films, with music video work on the side.	burnbrightproductions@gmail.com		https://www.burnbrightproductions.com/	https://www.instagram.com/burnbrightproductions/`,
  },
  {
    name: "Lexington: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Greg Thomas Photography	Photography		Lexington	Kentucky	Lexington and Central Kentucky	Documentary wedding photographer drawing on two decades as a military photojournalist, favouring candid storytelling over posed shots.			https://www.gregthomasphotography.com/weddings	https://www.instagram.com/gregthomasphoto/
Keely Nichole Photography	Photography		Lexington	Kentucky	Lexington, Nashville and beyond	Elegant, emotive wedding photography with planning guides and timeline help included, working across Kentucky, Nashville and further afield.	keelynicholephotography@gmail.com		https://keelynicholephotography.com/weddings	https://www.instagram.com/keelynicholephotography/
Rachel D. Photography	Photography		Lexington	Kentucky	Central Kentucky	Light and airy wedding and engagement photographer blending editorial polish with true-to-life colour across the Bluegrass.	hello@racheldphotography.com		https://racheldphotography.com/	https://www.instagram.com/racheldphoto_/
Emily Faith Photography	Photography		Lexington	Kentucky		Documentary-led wedding photographer with over 400 couples behind her, quietly catching candid moments with downloadable galleries included.	emily@emilyfaithphotography.com	(859) 494-2444	https://emilyfaithphotography.com/	https://www.instagram.com/emilyfaithphotography/
Planned to Perfection of the Bluegrass	Planning		Lexington	Kentucky	Central Kentucky	Boutique planning firm running since 2008, offering full planning, design and day-of coordination plus intimate weddings and elopements.	ptopofthebluegrass@gmail.com	(859) 699-4979	https://www.plannedtoperfectionbluegrass.com/	
Remington Event Co.	Planning		Lexington	Kentucky	Lexington and Central Kentucky	Lexington-based wedding planners offering full-service planning and coordination for couples marrying across Central Kentucky.	hello@remingtoneventco.com		https://www.remingtoneventco.com/	https://www.instagram.com/remingtoneventco/
Bourbon City Events	Planning		Lexington	Kentucky		Lexington planning team offering full, partial and consulting packages, from venue scouting through to day-of coordination.			https://www.bourboncityevents.com/	https://www.instagram.com/bourboncityevents/
Heart of Lex Events	Planning		Lexington	Kentucky		Lexington planner and stylist offering day-of coordination, partial or full planning, and decor styling for Kentucky weddings.	nayeliz@heartoflexevents.com		https://www.heartoflexevents.com/	https://www.instagram.com/heartoflexevents/
Flowers by Marnie and Jenny	Florals	400 Old Vine St, Suite 120	Lexington	Kentucky	Kentucky and the Bluegrass, plus out-of-state events	Two-designer studio near downtown Lexington with an earthy, farm-connected style, also running seasonal floral design workshops.	marnie@flowersbymarnieandjenny.com	(859) 619-4718	https://www.flowersbymarnieandjenny.com/	https://www.instagram.com/flowersbymarnieandjenny/
Roséalia	Florals		Lexington	Kentucky	Lexington and surrounding areas	Woman-owned, full-service floral studio known for romantic, artisan wedding work and turning each couple's own vision into flowers.	rosealiaflorals@gmail.com	(859) 533-4219	https://www.rosealiaflorals.com/	https://www.instagram.com/rosealiaflorals/
Drury Floral	Florals		Lexington	Kentucky	Lexington and Central Kentucky	Private downtown design studio since 2017 creating natural, artistic, one-of-a-kind wedding florals with an emphasis on local blooms.	druryfloral@gmail.com	(502) 370-8378	https://www.druryfloral.com/	https://www.instagram.com/druryfloral/
Ephemeral Florals	Florals		Lexington	Kentucky	Kentucky	Non-traditional, sustainable florist sourcing most specialty stems from Kentucky flower farms for bespoke weddings and events.	ephemeralfloralsky@gmail.com		https://www.ephemeralfloralsky.com/weddings	
Encore of Lexington	Music		Lexington	Kentucky	Kentucky	Live party band together for over a decade, playing current hits, Motown and old-school funk to keep wedding dance floors full.	encoreoflex2013@gmail.com	(859) 509-6415	https://encoreoflex.com/	
Addie and Cole	Music		Lexington	Kentucky	Lexington, Louisville, Cincinnati and surrounding regions	Piano and violin duo covering ceremony, cocktail hour and reception, from classical pieces to instrumental pop, country and film themes.	addieandcolemusic@gmail.com		https://www.addieandcole.com/private-events	https://www.instagram.com/addieandcolemusic/
2Ten Entertainment	Music		Lexington	Kentucky	Lexington	Wedding DJ and MC service that can add live acoustic guitar and violin plus wireless LED uplighting to a reception.	mike@2tenentertainment.com	(859) 433-4113	https://www.2tenentertainment.com/	https://www.instagram.com/2tenentertainment/
A To Z Productions	Music	306 W Main St, Suite 408	Frankfort	Kentucky	Central Kentucky	Frankfort-based wedding DJ team offering ceremony and reception sound, MC work, monograms, uplighting and officiant services.	kerryazbill@atozprodj.com	(502) 517-1020	https://www.atozprodj.com/	
Dupree Catering + Events	Catering	201 E Main St	Lexington	Kentucky	Central Kentucky	Long-running Lexington caterer since 1987 cooking scratch-made, locally sourced menus for weddings of 20 to 2,500 guests.		(859) 765-0133	https://www.dupreecatering.com/	https://www.instagram.com/dupree_catering/
Type A Catering and Events	Catering	105 MacArthur Ct, Unit E	Nicholasville	Kentucky	Lexington, Nicholasville, Georgetown, Frankfort and Richmond	Boutique off-site caterer since 2003 that also handles rentals, floor plans and timelines alongside custom wedding menus.		(859) 619-3198	https://www.typeacateringandevents.com/	https://www.instagram.com/typeacatering/
Selma's Catering Co.	Catering	720 Henry Clay Blvd	Lexington	Kentucky	Lexington and surrounding area	Lexington caterer and cafe team offering full wedding catering with warm, hands-on service and flavourful, crowd-pleasing menus.	contactus@selmascatering.com	(859) 971-2763	https://www.selmascatering.com/	https://www.instagram.com/selmascatering/
River Stone Catering	Catering		Lexington	Kentucky	Lexington and Central Kentucky	Full-service wedding caterer building custom menus with setup, service and breakdown included, across Lexington and nearby towns.			https://riverstonecatering.com/	
Beheld Beauty Collective	Hair & Makeup		Lexington	Kentucky	Lexington, Louisville, Cincinnati and surrounding areas	On-location bridal hair and makeup team handling whole wedding parties, with editorial and special-occasion styling too.	hello@beheldbeauty.co		https://beheldbeauty.co/	
Radiant Skin & Brows	Hair & Makeup	185 Pasadena Dr, Suite 230	Lexington	Kentucky	Lexington, with travel available	Lexington makeup artist offering bridal makeup with a trial and touch-up kit, wedding party add-ons and on-site lash application.	radiantskinandbrows@gmail.com	(859) 309-6262	https://www.radiantskinandbrows.com/makeup	https://www.instagram.com/radiantskinandbrows_/
Wildflower Salon Studio	Hair & Makeup	444 Lewis Hargett Cir, Suite 170	Lexington	Kentucky	Lexington, Georgetown, Versailles, Nicholasville, Richmond, Danville and nearby	Lexington salon styling whole bridal parties in the studio or on location, covering wedding hair and bridal makeup.			https://wildflowersalonstudio.framer.website/	
GLObal Brides USA	Hair & Makeup		Lexington	Kentucky		Licensed hair and makeup duo with over fifteen years in weddings, styling bridal parties locally and travelling for destination weddings.			https://globalbridesusa.com/	https://www.instagram.com/globalbridesusa/
Caramanda's	Cake	2220 Nicholasville Rd	Lexington	Kentucky		Family-run Lexington bake shop since 2006 making custom wedding cakes and dessert bars, with free wedding consultations.		(859) 278-7172	https://www.caramandas.com/	https://www.instagram.com/caramandas/
Martine's Pastries	Cake	400 E Third St	Lexington	Kentucky		Downtown Lexington pastry shop and cafe known for French tarts and buttercream-finished wedding cakes in a range of flavours.	martines@qx.net	(859) 231-9110	https://www.martinespastries.com/	https://www.instagram.com/martinespastries/
Mondelli's Bake Shop	Cake	3120 Pimlico Pkwy, Suite 162	Lexington	Kentucky		Lexington bake shop making wedding and custom cakes, cupcakes and mini desserts, plus favours for showers and rehearsal dinners.		(859) 955-8216	https://www.bakerylexington.com/	
Jackson Visuals	Videography		Lexington	Kentucky	Kentucky and beyond	Husband-and-wife team Tyler and Tiffany Jackson making documentary-style wedding films with a nostalgic, candid feel.			https://www.visualsbyjackson.com/	https://www.instagram.com/visuals.jackson/
Franzetti Photography	Videography		Lexington	Kentucky	Kentucky	Lexington studio run by Nick and Michelle Franzetti, filming weddings across Kentucky and pairing film with photography coverage.			https://franzettiphotography.com/videography	https://www.instagram.com/m_franzetti/
Maddox Made Weddings	Videography		Berea	Kentucky	Central Kentucky and beyond, including Lexington, Richmond, Danville and Winchester	Berea film and photo pairing, with Drew filming and Ariana Jordan photographing, so couples can book both from one small team.	hello@maddoxmade.com	(859) 248-9657	https://www.maddoxmadeweddings.com/	https://www.instagram.com/maddoxmadefilm/
KellieJoy Films	Videography		Lexington	Kentucky	Worldwide destination events	Lexington cinematographer with a soft, true-to-colour approach to wedding films, travelling for destination celebrations.	info@kelliejoyfilms.com		https://kelliejoyfilms.com/	https://www.instagram.com/kelliejoyfilms/`,
  },
  {
    name: "Bowling Green: planning, florals, photography, music and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Events by Allie	Planning		Bowling Green	Kentucky	Bowling Green, Nashville and Kentucky	Bowling Green wedding planning and coordination, with day-of support for couples marrying around south central Kentucky and Nashville.	eventsbyalliecoode@gmail.com	(270) 202-1736	http://www.eventsbyalliecoode.com/	https://www.instagram.com/eventsbyallie_coode/
Simply Sharp Events	Planning		Bowling Green	Kentucky	Kentucky and Tennessee	Full, partial and day-of wedding planning led by Emily, with a promise to help couples get hitched without a headache.			https://simplysharpevents.com/	https://www.instagram.com/simplysharpevents/
Belle Lane Events	Planning		Bowling Green	Kentucky		Wedding consulting, month-of and day-of coordination, layout design and full planning packages from a Black- and woman-owned team.	breona@bellelaneevents.com		https://www.bellelaneevents.com/	https://www.instagram.com/bellelaneevents/
Fete By Arnela	Planning		Bowling Green	Kentucky		Bowling Green event production company offering planning, coordination and rentals for weddings and other celebrations.	info@fetebyarnela.com	(270) 996-8014	https://www.fetebyarnela.com/	https://www.instagram.com/fetebyarnela/
Jules With The Flowers	Florals		Bowling Green	Kentucky	Bowling Green, Browning, Allen Springs, Blue Level, Petros and Cavehill	Bowling Green florist designing wedding flowers alongside daily deliveries, sympathy work and flower subscriptions, with consultations offered.	juleswiththeflowers@gmail.com	(502) 303-4050	https://juleswiththeflowers.com/	https://www.instagram.com/juleswiththeflowers/
Julie Hall Photography	Photography		Bowling Green	Kentucky	Bowling Green, Owensboro, Russellville and Nashville	Bowling Green photographer covering weddings, engagements and bridal sessions, and travelling for destination celebrations.			https://juliehallphotography.com/	
Violet Skies Photography	Photography		Bowling Green	Kentucky	Bowling Green and Nashville	Woman-owned studio led by Olivia Violet, shooting editorial-style weddings and engagements alongside family and portrait sessions.	oliviaviolet@violetskiesphotography.com	(916) 540-6432	https://www.violetskiesphotography.com/	https://www.instagram.com/violetskiesphotograph/
Five-Carat Entertainment	Music		Bowling Green	Kentucky	Bowling Green and the surrounding region	DJ and MC service for Bowling Green weddings and private celebrations, with bookings open for the 2026 and 2027 seasons.	info@fivecaratent.com	(270) 303-2824	https://fivecaratent.com/	https://www.instagram.com/fivecaratdj/
Heritage DJs	Music		Bowling Green	Kentucky	Kentucky, Tennessee and Alabama	Wedding DJ company handling ceremony sound, reception music, lighting and hosting for couples across Kentucky and Tennessee.	jim@heritagedjs.com	810-965-0590	https://heritagedjs.com/	
Regina Webb Salon & Spa	Hair & Makeup		Bowling Green	Kentucky		Full-service Bowling Green salon open since 1999, with a bridal studio for wedding hairstyles, colour and spa treatments.			https://www.reginawebbsalon.com/	https://www.instagram.com/reginawebbsalonandspa/`,
  },
];

export default batches;
