import type { VendorBatch } from "@/lib/vendor-batches";

// Louisiana vendor batches. Every row's State is "Louisiana". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "New Orleans: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Anthony LaMothe Photography	Photography		New Orleans	Louisiana	New Orleans and destination weddings	New Orleans photographer with an artistic, detail-led eye for emotion, covering weddings, engagements and proposals at home and further afield.	anthony@anthonylamothe.com	(504) 881-9600	https://anthonylamothe.com	https://www.instagram.com/anthonylamothephotography/
Elope to NOLA by Ibay Photography	Photography		Kenner	Louisiana	New Orleans and Biloxi	All-inclusive elopement and intimate wedding packages led by photographer Marcia Ibay, bundling photos, officiant and flowers in French Quarter settings.	info@elopetonola.com	(504) 292-4856	https://elopetonola.com	https://www.instagram.com/ibayphotography/
Michael Caswell Photography	Photography		Slidell	Louisiana	New Orleans, Slidell, Baton Rouge and the Mississippi Gulf Coast	Slidell-based wedding photographer with more than 800 weddings behind him, working unobtrusively across south Louisiana and the Gulf Coast.	info@michaelcaswell.com	(504) 453-8029	https://michaelcaswell.com	https://www.instagram.com/michael.caswell/
Elyse Jennings Weddings	Planning		New Orleans	Louisiana	New Orleans and destination weddings	Planning and design studio running New Orleans weddings since 2011, handling both the creative look and the logistics for local and destination couples.	elyse@elysejenningsweddings.com	(504) 261-0484	https://elysejenningsweddings.com	https://www.instagram.com/elysejenningsweddings/
Uncommon Camellia	Planning		New Orleans	Louisiana	New Orleans, Baton Rouge, Covington, Hammond and Slidell	Large planning firm offering wedding management, partial and full planning, with a set process that organises every stage of the run-up to the day.	info@uncommoncamellia.com	(504) 224-9895	https://uncommoncamellia.com	https://www.instagram.com/ucneworleans/
Lux Event Solutions	Planning		New Orleans	Louisiana	New Orleans and destination weddings	Boutique New Orleans planner covering full-service planning, design and day-of management for weddings and proposals, with in-house candle rentals.			https://www.luxeeventsolutions.com	https://www.instagram.com/luxeventplanninganddesign/
Leaf + Petal NOLA	Florals	5228 Tchoupitoulas St	New Orleans	Louisiana	New Orleans and the Gulf South	Garden-style wedding florist working with seasonal blooms and layered textures, from intimate dinners to large ceremony installations.	info@leafandpetalnola.com	(504) 343-6964	https://www.leafandpetalnola.com	https://www.instagram.com/leafandpetalnola/
Dunn and Sonnier	Florals	3433 Magazine St	New Orleans	Louisiana		Florist and antiques shop in an 1830s Creole cottage on Magazine Street, designing flowers for weddings, private homes and special events.		(504) 524-3235	https://dunnandsonnier.com	
NOLA Flora	Florals	4536 Magazine St	New Orleans	Louisiana		Magazine Street florist making bridal bouquets, ceremony installations and reception flowers alongside everyday made-to-order arrangements.	flowerninjas@nolaflora.com	(504) 891-3333	https://www.nolaflora.com	https://www.instagram.com/nola__flora/
Mitch's Flowers	Florals	4843 Magazine St	New Orleans	Louisiana		Uptown Magazine Street florist run by Monique Chauvin, offering full-service wedding and event flowers alongside orchids and everyday arrangements.	mitchsflowers@gmail.com		https://mitchsflowersnola.com	https://www.instagram.com/mitchsflowersnola/
Big Fun Entertainment & Brass Band	Music		New Orleans	Louisiana		Horn-driven New Orleans cover band and brass band collective playing receptions, second lines and parades, with DJ sets available too.	booking@bigfunbrassband.com		https://bigfunbrassband.com	https://www.instagram.com/bigfunentertainment/
Bucktown All-Stars	Music		New Orleans	Louisiana	Greater New Orleans	Party band formed in 1992 mixing 1960s R&B and soul, 70s funk and New Orleans standards, a regular choice for weddings and Mardi Gras balls.	thebucktownallstars@gmail.com		https://www.bucktownallstars.com	https://www.instagram.com/bucktownallstars/
Big Easy Entertainment	Music		New Orleans	Louisiana		Local live-music company booking its own bands, brass bands and musicians for weddings, second lines and private celebrations.	events@bigeasyentertainment.com	(504) 229-2247	https://bigeasyentertainment.com	https://www.instagram.com/bigeasyentertainmentnola/
Groovy 7	Music		New Orleans	Louisiana		New Orleans party band playing dance hits for weddings, conventions and private events, having opened for national touring acts.	groovy7info@gmail.com	(504) 343-2311	https://groovy7.com	https://www.instagram.com/groovy7nola/
Messina's Catering & Events	Catering	916 Dakin St	Jefferson	Louisiana		Family-run caterer now in its third generation, creating custom wedding menus and running its own venues, including Messina's at the Terminal.		(504) 469-7373	https://messinascatering.com	https://www.instagram.com/messinascateringandevents/
Ralph Brennan Catering and Events	Catering		New Orleans	Louisiana		Catering arm of the Ralph Brennan Restaurant Group, pairing locally sourced seasonal menus and craft cocktails with its own service staff.			https://www.ralphbrennancatering.com	https://www.instagram.com/ralphbrennancatering/
Faces of Virtue	Hair & Makeup		New Orleans	Louisiana	New Orleans and destination weddings	Bridal beauty studio founded in 2006 by Dee Rouzan, specialising in multicultural hair and makeup with a team of up to six artists.	dee@facesofvirtue.com		https://facesofvirtue.com	https://www.instagram.com/facesofvirtue/
Petal Salon	Hair & Makeup	1340 Magazine St	New Orleans	Louisiana		Lower Garden District salon with a dedicated bridal hair and makeup team for wedding-day looks, plus everyday cuts and colour.	info@petalsalon.com	(504) 354-1477	https://www.petalsalon.com	https://www.instagram.com/petalsalon/
Jessica Jackson Hair	Hair & Makeup		Marrero	Louisiana		On-location bridal hairstylist offering updos, glam waves and sleek ponytails for brides and their parties, with trials in her Marrero studio.	jessicajacksonhair@gmail.com	(504) 982-1544	https://www.jessicajacksonhair.com	https://www.instagram.com/jessicajacksonhair/
Haydel's Bakery	Cake	4037 Jefferson Hwy	New Orleans	Louisiana		Family bakery with over 60 years of New Orleans wedding cakes, offering a large design portfolio and traditional silver cake-pull charms.		(504) 837-0190	https://haydelsbakery.com/wedding-cakes/	https://www.instagram.com/haydelsbakery/
Joe Gambino's Bakery	Cake	4821 Veterans Memorial Blvd	Metairie	Louisiana		Long-standing Metairie bakery making wedding, groom's and shower cakes to order, with further shops in Baton Rouge and Lafayette.		(504) 885-7500	https://gambinos.com/pages/wedding-cakes	https://www.instagram.com/gambinosbakery/
Jenny's Cake Creations	Cake	6601 Veterans Memorial Blvd, Suite 2	Metairie	Louisiana	Greater New Orleans and south-east Louisiana	Licensed Metairie cake studio making tiered wedding cakes and custom celebration cakes by order only, with no walk-in sales.	jennys.cakecreations.llc@gmail.com		https://www.jennyscakecreations.com/neworleansweddingcakes	https://www.instagram.com/jennyscakecreations/
La Louisiane Bakery	Cake	5616 Heebe St	Harahan	Louisiana		Locally owned bakery known for wedding and custom cakes, quoting each design individually alongside pastries and desserts for celebrations.	laloubakery@gmail.com	(504) 734-9188	https://www.lalouisianebakery.com	https://www.instagram.com/laloubakery/
Numa Films	Videography		New Orleans	Louisiana	New Orleans, Lafayette, Louisiana and Oregon	Documentary-style wedding films by Elizabeth Trahan and Olivia Breaux, with a same-week teaser and a full-length film for each couple.			https://numafilms.com	https://www.instagram.com/numa.films.weddings/
Rue Royale Media	Videography		New Orleans	Louisiana		New Orleans wedding film studio mixing documentary storytelling with stylised shots, with packages that can be added to after the day.			https://www.rueroyalemedia.com	https://www.instagram.com/rueroyalemedia/
WeddingLens	Videography	5208 Magazine St, Suite 125	New Orleans	Louisiana	New Orleans, south Louisiana and Houston	Uptown studio offering combined photo and video packages from one team, with backup shooters and raw photos delivered within a week.	info@weddinglens.studio	(504) 662-9020	https://weddinglens.studio	https://www.instagram.com/weddinglensphoto/
Nathan Willis Wedding Films	Videography		New Orleans	Louisiana	New Orleans and destination weddings	Wedding films led by an Emmy-winning documentary filmmaker, shot in a low-profile way that favours real moments over staged ones.	nathanwillisweddingfilms@gmail.com		https://www.nathanwillisweddingfilms.com	https://www.instagram.com/nathanwillisweddingfilms/
Two Bites Events & Catering	Catering		New Orleans	Louisiana	Greater New Orleans	Chef-led caterer blending Mediterranean and New Orleans flavours, designing custom wedding menus for anything from elopement dinners to 300 guests.	hello@twobitesnola.com	(504) 264-2328	https://www.twobitesnola.com/weddings	https://www.instagram.com/twobitesnola/
Elysian Events Catering	Catering		New Orleans	Louisiana	New Orleans area	Off-premise caterer serving New Orleans cuisine with Louisiana oyster raw bars and full bar service, started by a couple who catered their own wedding.	hello@elysianeventscatering.com	(504) 541-0091	https://elysianeventscatering.com/	https://www.instagram.com/elysianeventscatering/
`,
  },
  {
    name: "Baton Rouge: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Taylor Hubbs Photography	Photography		Baton Rouge	Louisiana		Baton Rouge photographer for weddings, engagements and bridal portraits with a warm, emotive style focused on heirloom images over trends.			https://www.taylorhubbs.com/	https://www.instagram.com/taylorhubbsphotography/
Arielle N. Photography	Photography		Baton Rouge	Louisiana	Baton Rouge, New Orleans, the Northshore, Lafayette and surrounding areas	Natural, lightly edited wedding and elopement photography by a former model who can also officiate and coordinate small weddings.	ariellenphotography@gmail.com		https://www.ariellenphotography.com/	https://www.instagram.com/arielle.n.photography/
David Williams Photography	Photography		Baton Rouge	Louisiana	Baton Rouge, New Orleans and south Louisiana	Documentary-led wedding and engagement photographer working across Baton Rouge and New Orleans, focused on candid, unscripted moments.			https://dlwilliamsphotography.com/	https://www.instagram.com/david_williams_photography/
Lovely Occasions Weddings + Events	Planning		Baton Rouge	Louisiana	South Louisiana, including Baton Rouge and New Orleans	Baton Rouge planning team offering full planning, partial planning and day-of coordination packages for weddings across south Louisiana.	amanda@lovelyoccasionsla.com	(225) 615-6247	https://www.lovelyoccasionsla.com/	https://www.instagram.com/lovelyoccasions.la/
Magnolia Ceremonies	Planning		Baton Rouge	Louisiana	Greater Baton Rouge, New Orleans, the Northshore and south Louisiana	Day-of coordination and partial planning paired with officiant services, with two coordinators on site and inclusive LGBTQ+ ceremonies.	rhonda@magnoliaceremonies.com	(225) 252-4844	https://www.magnoliaceremonies.com/	https://www.instagram.com/magnolia_ceremonies/
AlesiaKim and Co	Planning		Baton Rouge	Louisiana	Baton Rouge and beyond	Baton Rouge studio offering full, partial, month-of and day-of wedding planning, with in-house photography and videography if wanted.	alesiakim2017@gmail.com	(225) 503-0633	https://www.alesiakimandco.com/wedding-planner-baton-rouge/	
Billy Heroman's Weddings & Events	Florals	10812 N Harrells Ferry Rd	Baton Rouge	Louisiana		Long-established Baton Rouge florist with a dedicated events team handling wedding flowers, décor, plant and prop rentals.		(225) 250-1115	https://www.billyheromansweddings.com/	https://www.instagram.com/billyheromans/
Hummingbird Floral Studio	Florals		Baton Rouge	Louisiana	Baton Rouge and New Orleans	Bespoke wedding and event florist based in Baton Rouge, designing custom florals for celebrations in Baton Rouge, New Orleans and beyond.	hello@hummingbirdfloralstudio.com		https://www.hummingbirdfloralstudio.com/	https://www.instagram.com/hummingbirdfloralstudio/
Luna Rose Florals	Florals		Prairieville	Louisiana		Prairieville florist creating custom bridal bouquets, bridal party flowers and event arrangements colour-matched to the venue.	lunaroseflorals@gmail.com	(225) 921-9124	https://www.lunaroseflorals.com/	https://www.instagram.com/lunaroseflorals/
The Floral Cottage	Florals	38480 LA-42	Prairieville	Louisiana		Prairieville flower shop with whimsical custom wedding florals, lower-cost pre-designed collections and silk bouquet rentals.	thefloralcottageflorist@gmail.com	(225) 677-2600	https://thefloralcottageflorist.com/weddings	https://www.instagram.com/thefloralcottageflorist/
Geaux BIG Entertainment	Music		Prairieville	Louisiana	Baton Rouge, Lafayette, New Orleans and the Northshore	Live-mixing wedding DJs from Prairieville, with add-ons such as photo booths, uplighting, cold sparks and LED walls.			https://geauxbig.com/	https://www.instagram.com/geauxbigentertainment/
Premier Sound Services	Music		Baton Rouge	Louisiana	Baton Rouge area	Baton Rouge DJ company for weddings and events, offering online music requests, photo booths, uplighting and monogram projection.			https://pssdj.com/	
Downbeat Louisiana	Music		Baton Rouge	Louisiana	Louisiana, Texas and Mississippi	Baton Rouge wedding and party band playing in eight- to twelve-piece line-ups, covering dance hits for receptions across the Gulf South.	info@downbeatlouisiana.com		https://downbeatlouisiana.com/	https://www.instagram.com/downbeatlouisiana/
Culinary Productions	Catering	3004 North Blvd	Baton Rouge	Louisiana	Baton Rouge, New Orleans and south Louisiana	Baton Rouge caterer since 2001 building custom south Louisiana wedding menus from scratch, with bar service and rentals available.	william@culinaryproductionsbr.com	(225) 346-4008	https://www.culinaryproductionsbr.com/wedding-catering/	https://www.instagram.com/culinary_productions/
Unique Cuisine Catering	Catering	3838 W Lakeshore Dr	Baton Rouge	Louisiana	Greater Baton Rouge	Full-service Baton Rouge caterer since 1984, known for Creole and Louisiana dishes, custom menus and craft cocktail bar service.	events@uniquecuisine.com	(225) 383-3663	https://uniquecuisine.com/	https://www.instagram.com/uniquecuisinecatering/
Bacon & Fig Events	Catering	10550 Airline Hwy	Baton Rouge	Louisiana	Baton Rouge and surrounding areas	Baton Rouge caterer offering carving and action stations, full bar service and wedding and groom's cakes, on site or off site.	info@baconandfigevents.com	(225) 366-6594	https://www.baconandfigevents.com/services	https://www.instagram.com/baconandfig/
Verde Beauty	Hair & Makeup		Baton Rouge	Louisiana	Baton Rouge and New Orleans, with travel for destination weddings	On-location wedding hair and makeup team working across Baton Rouge and New Orleans, experienced with diverse skin tones and hair types.	tina@verdebeautystudio.com		https://www.verdebeautystudio.com/	https://www.instagram.com/tina_verdebeauty/
Salon Raybon	Hair & Makeup	12602 Coursey Blvd	Baton Rouge	Louisiana		Baton Rouge salon offering bridal hair, makeup for the bride, bridal party and mothers, plus spray tans, in salon or on site.		(225) 756-1201	https://www.salonraybon.com/event-wedding-glam	https://www.instagram.com/salonraybon/
The Ambrosia Bakery	Cake	8546 Siegen Ln	Baton Rouge	Louisiana		Baton Rouge bakery open since 1993, making tiered custom wedding cakes and famed for its fresh strawberry cake.		(225) 763-6489	https://ambrosiabakery.com/	https://www.instagram.com/ambrosiabakery/
Les Amis Bake Shoppe	Cake	400 Convention St, Suite 111	Baton Rouge	Louisiana		Downtown Baton Rouge bake shop making wedding and custom cakes alongside cupcakes, cheesecakes and seasonal bakes.	info@lesamisbakeshoppe.com	(225) 293-8115	https://www.lesamisbakeshoppe.com/	https://www.instagram.com/lesamisbakeshoppe/
Sweet Stirrings	Cake	4342 High St	Zachary	Louisiana	Baton Rouge and Zachary	Zachary cake shop creating custom and semi-custom wedding cakes in smooth buttercream or fondant, plus desserts and baking classes.	sweetstirringscakes@gmail.com		https://www.sweetstirrings.com/	https://www.instagram.com/sweet_stirrings/
Kee's Treasured Delights	Cake		Gonzales	Louisiana	Gonzales, Baton Rouge, Ascension Parish and Denham Springs	Gonzales home bakery making wedding and groom's cakes, sculpted 3D cakes, cupcakes and cookies for Ascension Parish and Baton Rouge.	info@keestreasureddelights.com	(225) 380-3701	https://www.keestreasureddelights.com/	https://www.instagram.com/_keestreasureddelightsllc/
Eye Wander Photo	Videography	7964 Goodwood Blvd	Baton Rouge	Louisiana	New Orleans, Baton Rouge and destination weddings	Baton Rouge studio filming and photographing weddings, often at historic south Louisiana estates, with both services in-house.	hello@eyewanderphoto.com	(225) 366-4567	https://www.eyewanderphoto.com/	https://www.instagram.com/eyewanderphoto/
SB James Photography	Videography		Baton Rouge	Louisiana	Baton Rouge, New Orleans, Lafayette and the southern Gulf states	Baton Rouge wedding videographer and photographer Suzette James, with film packages from six hours and a highlight reel, plus photo booths.	sbjamesphotography@gmail.com	(225) 588-5591	https://www.sbjamesphotography.com/videography	https://www.instagram.com/sbjamesphotography/
`,
  },
  {
    name: "Baton Rouge: hair and makeup and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Faces by Leah	Hair & Makeup	16285-A Highland Rd, Room 104	Baton Rouge	Louisiana		Baton Rouge makeup studio run by a 20-year beauty educator, offering on-location bridal hair and makeup alongside microblading and brow work.	leah@facesbyleah.com	(225) 218-7474	https://facesbyleah.com/	https://www.instagram.com/facesbyleah/
Elysium Trail	Videography		Baton Rouge	Louisiana		Baton Rouge wedding filmmaker who trained as a wedding planner too, offering story-led films with toasts, interviews and drone footage.	nick@elysiumtrail.com		https://elysiumtrail.com/	https://www.instagram.com/nsavides/
`,
  },
];

export default batches;
