import type { VendorBatch } from "@/lib/vendor-batches";

// Maine vendor batches. Every row's State is "Maine". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Portland: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
James Hardman Photography	Photography	386 Fore St	Portland	Maine	Maine	Documentary wedding photographer shooting film and digital from an Old Port studio, with over a decade of Maine weddings behind him.	james@jameshardmanphotography.com	(508) 237-0776	https://www.jameshardmanphotography.com	https://www.instagram.com/jameshardmanphotography/
Emily Leonard Photography	Photography		Portland	Maine	New England and New York	Documentary-style film and digital wedding photography focused on warm, unposed moments and an inclusive approach to every couple.			https://emilyleonardphotography.com	https://www.instagram.com/emilyleonardphotography/
Whitney J. Fox Weddings	Photography		Portland	Maine	Maine, New England and beyond	Creative documentary wedding photographer telling the story of the day, who also photographs engagements, families and adoptions.	whitney@whitneyjfox.com		https://www.whitneyjfoxweddings.com	
Olive and Co.	Planning		Portland	Maine	Maine	Planning team working since 2015, offering partial and comprehensive planning plus event management with or without rental selection.	hello@oliveandcoevents.com	207.468.6040	https://oliveandcoevents.com	https://www.instagram.com/oliveandcoevents/
Dirigo Event Co.	Planning		South Portland	Maine	Maine and beyond	Founder-led planning firm offering full and partial wedding planning with a calm, structured and friendly approach to the process.	hello@dirigoeventco.com		https://www.dirigoeventco.com	https://www.instagram.com/dirigoeventco/
Petal & Pine Planning	Planning		Portland	Maine	Maine	Planner offering full and partial planning, day-of coordination and one-hour Planning Power Hour consults, including for out-of-state couples.	petalandpine.eventsllc@gmail.com	(207) 450-5509	https://www.petalandpineplanning.com	https://www.instagram.com/petal.and.pine.planning/
fern & flair	Planning		Portland	Maine	Maine and New England; travels nationally	Portland-area planner offering full-service planning through wedding management, with packages tailored to each couple.	lydia@fernandflair.com		https://www.fernandflair.com	https://www.instagram.com/fernandflair/
Plant Office	Florals	17 Marion St	Portland	Maine	Maine, with travel projects	Munjoy Hill floral studio and plant shop using locally sourced seasonal flowers, with no minimum for wedding orders.			https://plantoffice.net/pages/weddings	https://www.instagram.com/plant.office/
Field Floral Studio	Florals		Portland	Maine	Statewide for full-service weddings	Studio florist with 500+ weddings since 2013, designing loose, seasonal arrangements from Maine-grown flowers, plus a la carte orders.			https://www.fieldfloralstudio.com	https://www.instagram.com/fieldfloralstudio/
Petalage Floral Studio	Florals		Yarmouth	Maine		Small studio taking about ten full-service weddings a year, with romantic, old-world designs built around Maine-grown blooms.	MichelleG@petalageflorals.com	207-613-3162	https://www.petalageflorals.com	https://www.instagram.com/petalageflorals/
The Dapper Gents	Music		Portland	Maine	New England and beyond	Folk-rock band with a cellist, playing hits and deeper cuts as a duo, quartet or DJ, with 300+ weddings played since 2013.	jake@thedappergentsband.com	207-991-2300	https://www.thedappergentsband.com	https://www.instagram.com/dapgents/
The Music Man DJ Service	Music		Portland	Maine	Southern Maine coast, Portland to York	DJ and MC team specialising in coastal Maine weddings, also offering uplighting, monograms and photo booth hire.	info@themusicmandjservice.com	(207) 468-7904	https://themusicmandjservice.com/portland-me-wedding-djs/	https://www.instagram.com/servicemusicmandj/
DJ-BrianC	Music		Lewiston	Maine	Greater Portland, central, midcoast and coastal Maine	DJ and MC working since 1992 who reads the room rather than a fixed playlist, with backup equipment and LGBTQ+ friendly service.		(207) 212-6560	https://djbrianc.us/portland-maine-wedding-dj/	https://www.instagram.com/djbrianc207/
Fire & Co.	Catering	1035 Ocean Ave	Portland	Maine	Portland and surrounding Maine	Wood-fired and smoked menus cooked over open fire, with grazing stations and local beer from Maine brewery partners.			https://www.fireandcompany.com	https://www.instagram.com/fireandco/
58 Culinary	Catering	110 Thames St	Portland	Maine	Maine, including Casco Bay islands	Catering arm of five Portland restaurants, offering seasonal menus, lobster bakes, farm dinners and island weddings.	sales@prenticehospitality.com	207-910-7300	https://www.58culinary.com	https://www.instagram.com/58culinary/
Churchill Events	Catering	1037 Forest Avenue	Portland	Maine	Southern Maine, coast and islands	Full-service caterer and event planner handling barn, oceanfront and island weddings with its own chefs, bartenders and servers.	justin@churchillevents.com	207.878.2277	https://churchillevents.com	
Barn & Table	Catering		Gray	Maine	Southern Maine	Farm-to-table caterer cooking custom menus grown to order at Caswell Farm, served as stations or family style.	BarnAndTable@gmail.com	207.650.0481	https://www.barnandtable.me	https://www.instagram.com/barnandtablecatering/
Salon Lavender	Hair & Makeup	63 Washington Avenue	Portland	Maine	Greater Portland	East End salon offering bridal hair and makeup in the salon or on site, with trial and lashes included in the bridal package.		207.747.4431	https://www.salonlavender.com/weddings	https://www.instagram.com/lavenderportlandme/
Erika St. Pierre	Hair & Makeup	90 Bridge St	Westbrook	Maine	Greater Portland and beyond	Wedding hair and makeup artist working on site or from a Westbrook studio, booking bridal parties across southern Maine.	hello@erikastpierre.com	207.441.6280	https://www.erikastpierre.com/weddings	
Lindsey L. Green	Hair & Makeup	209 Western Ave	South Portland	Maine	Maine and New Hampshire	Hair and makeup artist offering on-location or in-salon styling by appointment, from a single bride to a full wedding party.	lindsey@lindseylgreen.com	207-730-3531	https://lindseylgreen.com	https://www.instagram.com/lindseylgreen/
Cakes Extraordinaire	Cake		Portland	Maine	Greater Portland	Wedding cake bakery working since 1984, building custom designs from couples' photos and ideas and delivering across greater Portland.	orders@cakesextraordinaire.com		https://www.cakesextraordinaire.com	
Prairie Baking Co.	Cake	44 Romasco Lane	Portland	Maine	Southern and coastal Maine	Cake and pastry bakery making tiered buttercream cakes dressed with fresh flowers, with seasonal flavours rooted in European pastry.			https://www.prairiebaking.com	https://www.instagram.com/prairiebakingco/
Hanami Cake Design	Cake		Biddeford	Maine	Maine, New England and beyond	Couture cake studio known for hand-painted designs and sugar work, with gluten-free, vegan and refined-sugar-free options.	hanamicakedesign@gmail.com		https://www.hanamicakedesign.com	https://www.instagram.com/hanamicakedesign/
Let Them Eat Cake	Cake		Kennebunk	Maine	Southern Maine, Kennebunkport to Falmouth	Boutique cake shop with over 30 years of wedding cakes, making both classical and whimsical custom designs across southern Maine.		207-967-4145	https://www.letthemeatcakemaine.com	
Mars and the Moon Films	Videography		Portland	Maine	New England and beyond	Husband-and-wife team filming and photographing weddings, with 250+ weddings covered and Super 8 and 35mm film options.	Bonnie@MarsAndTheMoonFilms.com	(207) 929-0241	https://www.marsandthemoonfilms.com	https://www.instagram.com/marsmoonfilms/
Ledge Light Films	Videography		Portland	Maine	Maine	Solo filmmaker blending documentary coverage with a cinematic edit, drawn to natural light and the textures of the Maine coast.	hello@ledgelightfilms.com	(207) 408-1735	https://ledgelightfilms.com	https://www.instagram.com/ledgelightfilms/
Fox and Sparrow Films	Videography		Portland	Maine	New England and beyond	Queer-owned wife duo making heartfelt Super 8 and digital wedding films that follow the day's unscripted moments.			https://www.foxandsparrowfilms.com	https://www.instagram.com/foxandsparrowfilms/`,
  },
  {
    name: "Midcoast and Bar Harbor: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Siri Jones Photography	Photography		Camden	Maine	Camden, Rockland and the wider Midcoast, with no travel fee within 75 miles	Camden photographer documenting intimate weddings and elopements, as well as family sessions, with a relaxed and joyful approach.	hi@sirijonesphotography.com		https://www.sirijonesphotography.com/	https://www.instagram.com/sirijonesphotography/
Fidelio Photography	Photography		Washington	Maine	Camden, Rockport, Boothbay Harbor, Bar Harbor and Portland	Husband-and-wife documentary team, working since 2007, shooting weddings, elopements and engagements on digital and film from their Washington base.	info@fideliophotography.com		https://www.fideliophotography.com/	https://www.instagram.com/fideliophoto/
Nicole Daacke Photography	Photography		Bar Harbor	Maine	Bar Harbor, Acadia National Park and Mount Desert Island	Bar Harbor photographer with ten-plus years of experience in Acadia, covering adventure elopements and small weddings among the park's landscapes.			https://www.nicoledaackephotography.com/	https://www.instagram.com/nicoledaackephoto/
Breezy Photography	Photography		Bar Harbor	Maine	Bar Harbor and Acadia National Park	Local Bar Harbor photographer covering elopements, weddings, engagements and proposals, and familiar with park permits and quiet coves.		207-270-3225	https://www.breezy-photography.com/	https://www.instagram.com/breezyphotome/
Emily Brianne Photography	Photography		Bar Harbor	Maine	Bar Harbor, coastal Maine and destinations further afield	Wedding and elopement photographer split between Bar Harbor and Arizona, blending a luxurious feel with adventurous locations, plus heirloom albums.	emilybriannephotography@gmail.com		https://emilybriannephotography.com/	https://www.instagram.com/emilybriannephotography/
Dragonfly Services	Planning		Boothbay Harbor	Maine	Boothbay Harbor and the surrounding Midcoast	Boothbay Harbor coordinator offering day-of coordination, micro-wedding packages and extended planning, plus rehearsal dinner and brunch support.	Wendy@dragonflyweddingcoordinator.com	207-350-0778	https://www.dragonflyweddingcoordinator.com/	https://www.instagram.com/dragonflyservices/
R.L. Sisson Events	Planning		Bar Harbor	Maine	Bar Harbor, Mount Desert Island and destination couples	Full-service wedding planning and event design from a Bar Harbor team with two decades of hospitality experience, founded in 2012.			https://www.rlsissonevents.com/	https://www.instagram.com/rlsissonevents/
MDI Weddings	Planning		Bar Harbor	Maine	Bar Harbor, Mount Desert Island and Acadia National Park	Bar Harbor wedding planning and officiating for couples marrying on Mount Desert Island, starting from an online request form.	adam.babbitt.mainenp@gmail.com		https://www.mdiweddings.com/	
Midcoast Blooms	Florals		Damariscotta	Maine	Brunswick to Belfast, including Bath and Camden	Damariscotta floral studio designing wedding and event flowers, with wearables, accessory rentals and repurposing of arrangements after the day.	Laura@midcoastblooms.com	207-682-0103	https://www.midcoastblooms.com/	https://www.instagram.com/midcoastblooms/
Willow Rose Flower Shoppe	Florals	521 Main St, Unit 2 C	Damariscotta	Maine	Damariscotta and nearby Midcoast towns	Damariscotta flower shop with vintage-inspired, locally sourced designs that also takes on wedding and event florals.		207-563-6537	https://www.willowroseflowershoppe.net/	https://www.instagram.com/willow_rose_flower_shoppe/
Cottage Flowers	Florals	162 Otter Creek Drive	Bar Harbor	Maine	Bar Harbor and Acadia National Park area	Bar Harbor flower grower making bridal bouquets, boutonnieres and ceremony and reception arrangements from blooms cut at the foot of Cadillac Mountain.	info@cottageflowersmaine.com	207-288-2509	https://cottageflowersmaine.com/	
Butera the Florist	Florals		Sedgwick	Maine	Bar Harbor, Blue Hill, Ellsworth, Castine, Southwest Harbor, Belfast and Downeast Maine	Wedding-only florist near Blue Hill, working since 1980, taking one wedding per day and growing its own flowers on a small farm.	hello@buteratheflorist.com	207-359-5020	https://buteratheflorist.com/	
Leafsong Family Farm	Florals	507 Back Belmont Rd	Belmont	Maine	Belfast, Camden and the wider Midcoast	Organic flower farm and floral studio near Belfast offering wedding flowers, farm-grown stems, arrangements and garden design.	leafsongfamilyfarm@gmail.com	207-342-2613	https://www.leafsongfamilyfarm.com/	https://www.instagram.com/leafsongfamilyfarm/
Bouchard Entertainment	Music		Bar Harbor	Maine	Bar Harbor, Mount Desert Island and Downeast Maine	Bar Harbor DJ service for weddings, with event uplighting, dance-floor lighting and photo booth hire available alongside the music.	office@bouchardentertainment.com	207-501-2289	https://bouchardentertainment.com/	https://www.instagram.com/bouchardentertainment/
Bar Harbor Catering Company	Catering	367 State Highway 3	Bar Harbor	Maine	Maine	Full-service caterer on Mount Desert Island offering seasonal menus, bar service, rentals, staffing and day-of coordination for weddings.	office@bhcaterco.com	207-801-9382	https://www.bhcaterco.com/	https://www.instagram.com/bhcaterco/
Stone Cove Catering	Catering		Bristol	Maine	Midcoast of Maine	Midcoast caterer offering tailored wedding menus, from canapes and plated dinners to pig roasts and barbecues, finished with desserts.	info@stonecovecatering.com	207.563.7008	https://stonecovecatering.com/	https://www.instagram.com/stonecovecatering/
Megunticook Market	Catering	2 Gould Street	Camden	Maine	Camden, Rockland, Rockport, Belfast and nearby	Camden market whose catering team prepares platters and custom menus for weddings and celebrations around Camden, Rockland, Rockport and Belfast.	catering@megunticookmarket.com	207-236-3537	https://megunticookmarket.com/	https://www.instagram.com/megunticookmarket/
Trillium Caterers	Catering		Belfast	Maine	Throughout Maine	Belfast caterer providing wedding food, bartending and rental coordination, built around quality ingredients and polished menus.	hello@trilliumcaterers.com	207.338.5080	https://www.trilliumcaterers.com/	https://www.instagram.com/trilliumcaterers/
Salty Waves Salon	Hair & Makeup	770 Commercial Street	Rockport	Maine	Rockport, with on-site weddings up to 100+ miles (travel fees apply)	Rockport salon offering bridal hair and makeup with trials included, either in the salon or on location, with travel fees further afield.		(207) 466-9036	https://saltywavessalon.net/	https://www.instagram.com/saltywavessalon/
Bar Harbor Beauty	Hair & Makeup		Bar Harbor	Maine		Bar Harbor makeup artist focused on bridal looks that stay natural and photograph well, who also teaches makeup classes.	info@barharborbeauty.com		https://barharborbeauty.com/	https://www.instagram.com/barharborbeauty/
Atlantic Baking Co.	Cake	351 Main Street	Rockland	Maine		Rockland bakery whose pastry chefs make wedding cakes to order, alongside its everyday bread and baking.		207.596.0505	https://atlanticbakingco.com/	https://www.instagram.com/atlantic_baking_co/
Cakes by Design	Cake		Brunswick	Maine	Brunswick area	Brunswick cake shop making custom wedding cakes with clean lines and careful detail, now taking online pre-orders and scheduled pick-ups only.			https://www.mainecakesbydesign.com/	https://www.instagram.com/mainecakesbydesign/
Tailwind Media	Videography		Rockport	Maine	Midcoast Maine	Rockport video production company offering wedding films with one or two cinematographers, highlight edits, optional drone and teaser clips.	collaborate@tailwindmedia.com		https://tailwindmedia.com/	`,
  },
];

export default batches;
