import type { VendorBatch } from "@/lib/vendor-batches";

// Maine vendor batches. Every row's State is "Maine". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Portland: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
James Hardman Photography	Photography	386 Fore St	Portland	Maine	Maine	Documentary wedding photographer shooting film and digital from an Old Port studio, with over a decade of Maine weddings behind him.	james@jameshardmanphotography.com	(508) 237-0776	https://www.jameshardmanphotography.com	https://www.instagram.com/jameshardmanphotography/
Emily Leonard Photography	Photography		Portland	Maine	New England and New York	Documentary-style film and digital wedding photography focused on warm, unposed moments and an inclusive approach to every couple.			https://emilyleonardphotography.com	https://www.instagram.com/emilyleonardphotography/
Whitney J. Fox Weddings	Photography		Portland	Maine	Maine, New England and beyond	Creative documentary wedding photographer telling the story of the day, who also photographs engagements, families and adoptions.	whitney@whitneyjfox.com		https://www.whitneyjfoxweddings.com	
Olive and Co.	Planning		Portland	Maine	Maine	Planning team working since 2015, offering partial and comprehensive planning plus event management with or without rental selection.	hello@oliveandcoevents.com	207.468.6040	https://oliveandcoevents.com	https://www.instagram.com/oliveandcoevents/
Dirigo Event Co.	Planning		South Portland	Maine	Maine and beyond	Founder-led planning firm offering full and partial wedding planning with a calm, structured and friendly approach to the process.	hello@dirigoeventco.com		https://www.dirigoeventco.com	https://www.instagram.com/dirigoeventco/
Petal & Pine Planning	Planning		Portland	Maine	Maine	Planner offering full and partial planning, day-of coordination and one-hour Planning Power Hour consults, including for out-of-state couples.	petalandpine.eventsllc@gmail.com	(207) 450-5509	https://www.petalandpineplanning.com	https://www.instagram.com/petal.and.pine.planning/
fern & flair	Planning		Portland	Maine	Maine and New England; travels nationally	Portland-area planner offering full-service planning through wedding management, with packages tailored to each couple.	lydia@fernandflair.com		https://www.fernandflair.com	https://www.instagram.com/fernandflair/
Plant Office	Florals	17 Marion St	Portland	Maine	Maine, with travel projects	Munjoy Hill floral studio and plant shop using locally sourced seasonal flowers, with no minimum for wedding orders.			https://plantoffice.net/pages/weddings	https://www.instagram.com/plant.office/
Field Floral Studio	Florals		Portland	Maine	Statewide for full-service weddings	Studio florist with 500+ weddings since 2013, designing loose, seasonal arrangements from Maine-grown flowers, plus a la carte orders.			https://www.fieldfloralstudio.com	https://www.instagram.com/fieldfloralstudio/
Petalage Floral Studio	Florals		Yarmouth	Maine		Small studio taking about ten full-service weddings a year, with romantic, old-world designs built around Maine-grown blooms.	MichelleG@petalageflorals.com	207-613-3162	https://www.petalageflorals.com	https://www.instagram.com/petalageflorals/
The Dapper Gents	Music		Portland	Maine	New England and beyond	Folk-rock band with a cellist, playing hits and deeper cuts as a duo, quartet or DJ, with 300+ weddings played since 2013.	jake@thedappergentsband.com	207-991-2300	https://www.thedappergentsband.com	https://www.instagram.com/dapgents/
The Music Man DJ Service	Music		Portland	Maine	Southern Maine coast, Portland to York	DJ and MC team specialising in coastal Maine weddings, also offering uplighting, monograms and photo booth hire.	info@themusicmandjservice.com	(207) 468-7904	https://themusicmandjservice.com/portland-me-wedding-djs/	https://www.instagram.com/servicemusicmandj/
DJ-BrianC	Music		Lewiston	Maine	Greater Portland, central, midcoast and coastal Maine	DJ and MC working since 1992 who reads the room rather than a fixed playlist, with backup equipment and LGBTQ+ friendly service.		(207) 212-6560	https://djbrianc.us/portland-maine-wedding-dj/	https://www.instagram.com/djbrianc207/
Fire & Co.	Catering	1035 Ocean Ave	Portland	Maine	Portland and surrounding Maine	Wood-fired and smoked menus cooked over open fire, with grazing stations and local beer from Maine brewery partners.			https://www.fireandcompany.com	https://www.instagram.com/fireandco/
58 Culinary	Catering	110 Thames St	Portland	Maine	Maine, including Casco Bay islands	Catering arm of five Portland restaurants, offering seasonal menus, lobster bakes, farm dinners and island weddings.	sales@prenticehospitality.com	207-910-7300	https://www.58culinary.com	https://www.instagram.com/58culinary/
Churchill Events	Catering	1037 Forest Avenue	Portland	Maine	Southern Maine, coast and islands	Full-service caterer and event planner handling barn, oceanfront and island weddings with its own chefs, bartenders and servers.	justin@churchillevents.com	207.878.2277	https://churchillevents.com	
Barn & Table	Catering		Gray	Maine	Southern Maine	Farm-to-table caterer cooking custom menus grown to order at Caswell Farm, served as stations or family style.	BarnAndTable@gmail.com	207.650.0481	https://www.barnandtable.me	https://www.instagram.com/barnandtablecatering/
Salon Lavender	Hair & Makeup	63 Washington Avenue	Portland	Maine	Greater Portland	East End salon offering bridal hair and makeup in the salon or on site, with trial and lashes included in the bridal package.		207.747.4431	https://www.salonlavender.com/weddings	https://www.instagram.com/lavenderportlandme/
Erika St. Pierre	Hair & Makeup	90 Bridge St	Westbrook	Maine	Greater Portland and beyond	Wedding hair and makeup artist working on site or from a Westbrook studio, booking bridal parties across southern Maine.	hello@erikastpierre.com	207.441.6280	https://www.erikastpierre.com/weddings	
Lindsey L. Green	Hair & Makeup	209 Western Ave	South Portland	Maine	Maine and New Hampshire	Hair and makeup artist offering on-location or in-salon styling by appointment, from a single bride to a full wedding party.	lindsey@lindseylgreen.com	207-730-3531	https://lindseylgreen.com	https://www.instagram.com/lindseylgreen/
Cakes Extraordinaire	Cake		Portland	Maine	Greater Portland	Wedding cake bakery working since 1984, building custom designs from couples' photos and ideas and delivering across greater Portland.	orders@cakesextraordinaire.com		https://www.cakesextraordinaire.com	
Prairie Baking Co.	Cake	44 Romasco Lane	Portland	Maine	Southern and coastal Maine	Cake and pastry bakery making tiered buttercream cakes dressed with fresh flowers, with seasonal flavours rooted in European pastry.			https://www.prairiebaking.com	https://www.instagram.com/prairiebakingco/
Hanami Cake Design	Cake		Biddeford	Maine	Maine, New England and beyond	Couture cake studio known for hand-painted designs and sugar work, with gluten-free, vegan and refined-sugar-free options.	hanamicakedesign@gmail.com		https://www.hanamicakedesign.com	https://www.instagram.com/hanamicakedesign/
Let Them Eat Cake	Cake		Kennebunk	Maine	Southern Maine, Kennebunkport to Falmouth	Boutique cake shop with over 30 years of wedding cakes, making both classical and whimsical custom designs across southern Maine.		207-967-4145	https://www.letthemeatcakemaine.com	
Mars and the Moon Films	Videography		Portland	Maine	New England and beyond	Husband-and-wife team filming and photographing weddings, with 250+ weddings covered and Super 8 and 35mm film options.	Bonnie@MarsAndTheMoonFilms.com	(207) 929-0241	https://www.marsandthemoonfilms.com	https://www.instagram.com/marsmoonfilms/
Ledge Light Films	Videography		Portland	Maine	Maine	Solo filmmaker blending documentary coverage with a cinematic edit, drawn to natural light and the textures of the Maine coast.	hello@ledgelightfilms.com	(207) 408-1735	https://ledgelightfilms.com	https://www.instagram.com/ledgelightfilms/
Fox and Sparrow Films	Videography		Portland	Maine	New England and beyond	Queer-owned wife duo making heartfelt Super 8 and digital wedding films that follow the day's unscripted moments.			https://www.foxandsparrowfilms.com	https://www.instagram.com/foxandsparrowfilms/`,
  },
];

export default batches;
