import type { VendorBatch } from "@/lib/vendor-batches";

// Maryland vendor batches. Every row's State is "Maryland". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Baltimore: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alicia Wiley Photography	Photography	3500 Parkdale Ave	Baltimore	Maryland	Baltimore, Philadelphia and beyond	Candid, colourful wedding photography mixing documentary and editorial, from a Baltimore studio that also offers albums and photo booths.	hello@aliciawiley.com		https://www.aliciawileyphotography.com/	https://www.instagram.com/aliciawileyphotography/
Haley Day Photography	Photography		Baltimore	Maryland	Baltimore, DC and the East Coast	Editorial wedding portraits and candid moments shot on both film and digital, for stylish modern celebrations around Baltimore.	haley@haleyday.com		https://haleyday.com/	https://www.instagram.com/haleydayphotography/
Megapixels Media	Photography		Baltimore	Maryland	Baltimore, Washington DC and beyond	Black husband-and-wife team photographing real, diverse couples with candid yet magazine-style coverage; video is offered too.	Hello@MegapixelsMedia.com		https://megapixelsmedia.com/	https://www.instagram.com/megapixelsmedia/
Crimson & Clover Floral Design	Florals	733 Deepdene Rd	Baltimore	Maryland	Baltimore, Towson, Timonium, Pikesville, Lutherville	North Baltimore flower shop with two decades of wedding work, known for stylised centrepieces and custom installations alongside everyday florals.		410-534-5459	https://crimsonandcloverdesigns.com/	
Violet Floral Designs	Florals	4708 Harford Rd, Ste. 1B	Baltimore	Maryland	Baltimore	Woman-founded Baltimore studio making abundant, whimsical floral designs led by the season, often with locally grown flowers.	VIOLETFLORALDESIGNS@GMAIL.COM		https://www.violetfloraldesigns.com/	https://www.instagram.com/violet_florals/
Petals by Alex	Florals		Baltimore	Maryland	Baltimore, Annapolis, DC and surrounding areas	Organic, garden-style wedding flowers with bold texture and movement, mixing local and imported blooms for couples wanting something personal.	alex@petalsbyalex.com		https://www.petalsbyalex.com/	https://www.instagram.com/petalsbyalex/
Bay Deejays	Music		Baltimore	Maryland		Wedding-only DJ firm in Baltimore with upfront published pricing, an online planning portal and a focus on keeping the dance floor full.		(410) 302-9177	https://www.baydeejays.com/	
Baltimore Sound Entertainment	Music		Baltimore	Maryland	Maryland, Washington DC and Virginia	DJ and event-production company adding photo booths, silent discos, dance-floor and staging hire to its wedding DJ packages.	baltimoresound@gmail.com	(443) 405-2378	https://www.baltimoresound.net/	https://www.instagram.com/baltimoresoundentertainment/
RCC Weddings & Events	Planning		Baltimore	Maryland	Baltimore, Frederick, Annapolis and surrounding areas	Certified planner Renee leads full planning and coordination for Maryland weddings, taking on vendor and timeline details so couples can relax.	info@rccweddingsandevents.com	(443) 873-0903	https://rccweddingsandevents.com/	
Moore & Co. Event Stylists	Planning	24 South Main St.	Bel Air	Maryland	Baltimore, Maryland and DC	Bel Air planning and styling studio offering full, partial and month-of wedding packages, with a strong eye for design and décor.	info@mooreandcoevents.com	410-838-4802	https://www.mooreandcoevents.com/	https://www.instagram.com/mooreandcoevents/
Charm City Cakes	Cake	2936 Remington Ave	Baltimore	Maryland		Remington bakery famed for sculpted, imaginative custom cakes, also offering a wedding collection for celebrations large and small.	info@charmcitycakes.com	410.235.9229	https://www.charmcitycakes.com/	https://www.instagram.com/charmcitycakes/
Plant Baked by Sarah	Cake		Baltimore	Maryland	Greater Baltimore and DC metro	Appointment-only vegan bakery making custom plant-based buttercream wedding cakes, with gluten-free and nut-free versions on request.	sarah@plantbakedbysarah.com	484-553-4507	https://www.plantbakedbysarah.com/	https://www.instagram.com/plantbakedbysarah/
Cedars Cakes	Cake	6421 Frederick Rd	Catonsville	Maryland	Catonsville and greater Baltimore	Catonsville cake shop baking made-to-order wedding cakes and cupcakes, with wedding consultations and tastings to settle on flavours and design.	orders@cedarscakes.com	(443) 830-7697	https://cedarscakes.com/	https://www.instagram.com/cedarscakes/
Zeffert & Gold Catering	Catering	6601 Whitestone Road, Suite E	Baltimore	Maryland	Baltimore–Washington region	Caterer and event planner with over 30 years of Baltimore weddings, handling menus, service and reception planning across the region.	info@zeffertandgold.com	410-999-0271	https://zeffertandgold.com/catering-weddings-receptions/	https://www.instagram.com/zeffertandgold/
ROUGE Fine Catering	Catering	11110 Pepper Road, Suite F	Hunt Valley	Maryland	Maryland, Washington DC and Virginia	Hunt Valley caterer cooking on site from a mobile kitchen, with plated, buffet, family-style and cocktail menus built around the couple.		410-527-0007	https://www.rougecatering.com/weddings/	https://www.instagram.com/rougecatering/
Chef's Expressions	Catering	9526 Deereco Road	Timonium	Maryland	Baltimore, Maryland and Washington DC	Timonium caterer with over 3,000 celebrations behind it, pairing custom wedding menus with event design consultants and tastings.	Cheers@ChefsExpressions.com	(410) 561-2433	https://www.chefsexpressions.com/catered-events/weddings	
Unveiled Bridal Beauty Co	Hair & Makeup		Baltimore	Maryland		On-location bridal hair and makeup team from Baltimore that handles trials, scheduling and timelines for the whole wedding party.	unveiledbeauty24@gmail.com	443-678-2435	https://www.unveiledbridalbeautyco.com/	https://www.instagram.com/unveiledbridalbeautyco/
#NoFilter Glam	Hair & Makeup	11222 York Rd. #4	Cockeysville	Maryland	Maryland, DC, Virginia and destination weddings	Baltimore County hair and makeup company focused on natural-looking bridal glam, also offering spray tanning and artist education.	hello@nofilterglam.com	443.800.3384	https://www.nofilterglam.com/	https://www.instagram.com/nofilterglam/
The Brushing Bride	Hair & Makeup	1927 A York Road	Lutherville-Timonium	Maryland	Baltimore, coastal and destination weddings	On-site bridal hair and makeup team working out of Brush. Salon, known for soft glam for elopements through to large celebrations.	thebrushingbride@gmail.com		https://www.thebrushingbride.net/	
Documented Video Productions	Videography		Baltimore	Maryland	Baltimore and surrounding areas	Owner-led Baltimore studio filming and editing in house, blending documentary footage of unplanned moments with cinematic shots.		443-845-5554	https://www.documentedvideo.com/weddings.html	https://www.instagram.com/documentedvideo/
K&A Photo and Video	Videography		Baltimore	Maryland	Maryland, Pennsylvania, Virginia, Delaware and the East Coast	Baltimore photo and video team, founded in 2019, making cinematic highlight films with full-day coverage and professional audio.	kandaphotoandvideo@gmail.com	443-813-8266	https://www.kandaphotoandvideo.com/baltimore-wedding-videographer	https://www.instagram.com/kandaphotoandvideo/
In Motion Video	Videography	1014 Regester Ave	Baltimore	Maryland	Maryland, DC, Northern Virginia, Delaware and southern Pennsylvania	Documentary-style wedding films shot in 4K with wireless audio, from a Baltimore studio filming weddings for over two decades; drone add-ons too.	gene@inmotionvideo.com	(410) 929-5170	https://www.bestbaltimoreweddingvideography.com/	
Hill Chamber Music	Music		Baltimore	Maryland	Maryland, DC, Virginia and beyond	Baltimore string quartets and trios playing classical, pop and jazz arrangements for ceremony prelude, processional and recessional music.	hillchambermusic@gmail.com	443-857-4205	https://www.hillchambermusic.com/	`,
  },
  {
    name: "Annapolis: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kate Fine Art Photography	Photography		Annapolis	Maryland	Annapolis, Baltimore, Washington DC and across Maryland	Fine-art wedding photography with two decades of experience, mixing honest documentary coverage with an artistic eye.	kate@katefineart.com	(410) 212-8887	https://katefineart.com/	https://www.instagram.com/katefineart/
Madeline Serio Photography	Photography		Annapolis	Maryland	Washington DC, Maryland, Virginia and New York	Painterly, natural wedding photography from an Annapolis-based artist blending guided portraits with relaxed documentary moments.			https://www.madelineserio.com/	https://www.instagram.com/madelineseriophotography/
Christa Rae Photography	Photography		Annapolis	Maryland	Maryland and Washington DC	Timeless, true-to-colour wedding photography from an Annapolis photographer with more than 450 weddings across the DMV.			https://www.christaraephotography.com/	https://www.instagram.com/christaraephotography/
Harbor & Veil	Planning		Annapolis	Maryland	Annapolis and the Chesapeake Bay region	Woman-owned day-of coordination for Annapolis weddings, covering the month-before prep, rehearsal and full event-day running.	harborandveil@gmail.com		https://www.harborandveil.com/	https://www.instagram.com/harborandveil/
Island Creek Events	Planning		Oxford	Maryland	DMV area and beyond, focused on the Eastern Shore	Eastern Shore planner offering full planning, partial planning and day-of coordination for bay and waterfront weddings across the DMV.	info@islandcreekevents.com	(410) 231-3272	https://www.islandcreekevents.com/	https://www.instagram.com/islandcreekevents/
Trivien Events	Planning		Annapolis	Maryland	East Coast and beyond	Annapolis firm (formerly Adriana Marie Events) handling complete planning and design for organic, elegant weddings.		(410) 533-8414	https://trivienevents.com/	https://www.instagram.com/trivienevents/
Scentered Stem Florals	Florals		Annapolis	Maryland	Annapolis, Baltimore, the Chesapeake Bay and the Eastern Shore	Sustainable wedding florals using local blooms, foam-free mechanics and reusable vessels, from a designer with 20 years of experience.			https://scenteredstem.com/	
Bloom Luxury Box	Florals	62 Maryland Ave	Annapolis	Maryland	Annapolis, Baltimore, Washington DC and Northern Virginia	Downtown Annapolis flower shop offering consultations and custom ceremony and reception florals alongside its luxury boxed arrangements.	bloomluxurybox@gmail.com	(443) 336-3705	https://bloomluxurybox.com/	https://www.instagram.com/bloomluxurybox/
Floret & Vine	Florals		Annapolis	Maryland		Boutique Annapolis studio pairing modern composition with lush installations, with more than 300 weddings and events behind it.			https://floretandvine.com/	https://www.instagram.com/floretandvine/
Palate Pleasers	Catering		Annapolis	Maryland	Potomac, Chevy Chase, Washington DC, Baltimore, Annapolis and the Eastern Shore	Long-running Annapolis caterer for receptions of five to 700 guests, with an in-house bakery making custom wedding cakes.	info@palatepleasers.com	(410) 263-6941	https://www.palatepleasers.com/	https://www.instagram.com/palatepleasers/
April's Table	Catering	541-C Baltimore Annapolis Blvd	Severna Park	Maryland		Severna Park caterer and cafe offering full-service wedding catering and private events at its own space, Arbor & Fig.	eat@aprilstable.com	(410) 544-2660	https://www.aprilstable.com/	https://www.instagram.com/aprils.table/
Bayside Bull	Catering	108 Central Ave	Edgewater	Maryland	Maryland	Edgewater open-pit barbecue kitchen with a dedicated weddings team, suited to relaxed Chesapeake receptions and casual buffets.	sales@baysidebull.com	(410) 956-6009	https://www.baysidebull.com/	https://www.instagram.com/baysidebullbbq/
Infinity Artistry	Hair & Makeup	48 Maryland Ave #103	Annapolis	Maryland	Maryland and destination weddings	Downtown Annapolis studio whose team of stylists provides bridal hair and makeup locally and for destination weddings.	sara@infinityartistry.com	(410) 456-6831	https://infinityartistry.com/	https://www.instagram.com/infinityartistry/
WeddingsBySage	Hair & Makeup		Edgewater	Maryland	Annapolis, Davidsonville and the Chesapeake Bay area	Edgewater-based team bringing on-site bridal hair and makeup to weddings across Anne Arundel County and the Chesapeake Bay.	weddingsbysage@gmail.com		https://www.weddingsbysage.com/	https://www.instagram.com/weddingsbysage/
Blue Crab Cupcakes	Cake	1580 Whitehall Rd	Annapolis	Maryland		Annapolis bakery specialising in wedding and special-occasion cakes, cupcakes and cake pops from its Whitehall Road shop.	carrie@bluecrabcupcakes.com	(443) 221-7246	https://www.bluecrabcupcakes.com/	https://www.instagram.com/bluecrabcupcakes/
Sweet Eden Bakeshop	Cake	2604-A Annapolis Rd	Severn	Maryland	Severn, Odenton, Glen Burnie, Annapolis, Columbia and Baltimore	Anne Arundel County bakeshop with a dedicated wedding cake service and wide flavour menu, booked online.		(443) 795-4550	https://www.sweetedenbakeshop.com/	https://www.instagram.com/sweetedenbakeshop/
Sweeter Side Bakeshop	Cake	107 Mountain Rd, Suite E	Pasadena	Maryland		Pasadena bakeshop on Mountain Road offering custom tiered wedding cakes alongside its everyday cakes and pastries.			https://www.sweetersidebakeshop.com/weddings	https://www.instagram.com/sweetersidebakeshopmd/
Rivion Wedding Films	Videography		Crofton	Maryland	Maryland, Washington DC and Virginia	Crofton-based wedding film studio focused on affordable packages that still capture the sights, sounds and feel of the day.		(443) 429-1028	https://rivionweddings.com/	https://www.instagram.com/rivionweddingfilms/
Mixing Maryland	Music		Annapolis	Maryland	Maryland, Washington DC and Northern Virginia	Full-time wedding DJs known for live mixing and packed dance floors, with dozens of Annapolis and Eastern Shore venues on their books.		(443) 603-9150	https://www.mixingmaryland.com/	https://www.instagram.com/mixingmarylanddjs/`,
  },
  {
    name: "Baltimore: planning",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jennifer Rose Events & Weddings	Planning		Baltimore	Maryland	DMV area; travels to other states and abroad	Baltimore planning studio founded in 2016 offering full, partial and month-of planning, with a 3-D floor-plan tool for seating layouts.		(443) 878-6633	https://www.jenniferroseevents.com/	https://www.instagram.com/jenniferroseeventsandweddings/`,
  },
  {
    name: "Annapolis: hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Limin' Hair Studio	Hair & Makeup		Annapolis	Maryland	Within 20 miles of the Annapolis studio without travel fee	Annapolis hair studio open since 2014, styling brides and wedding parties on location, with trial runs held at the studio.	info@liminhairstudio.com		https://www.liminhairstudio.com/	https://www.instagram.com/liminhairstudio/`,
  },
  {
    name: "Frederick: photography, planning, florals, music, catering, hair & makeup, cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Barbara Badstibner Photography	Photography		Frederick	Maryland	Frederick, Baltimore and Northern Virginia	Frederick wedding and portrait photographer focused on candid, unposed moments for couples across the Mid-Atlantic.	hello@barbarabadstibner.com	240-446-1264	https://www.barbarabadstibner.com/	https://www.instagram.com/barbarabadstibnerphotography/
Jenna Davis Photography	Photography		Frederick	Maryland	Frederick County and the DMV	Frederick studio shooting romantic, candid wedding days, deliberately limited to about fifteen couples a year.			https://jennadavisphoto.com/home-frederick	https://www.instagram.com/jennadavisphotographymd/
Mary Sarah Photography	Photography		Frederick	Maryland	Northern Virginia, Loudoun County and the greater DMV; destinations	Frederick wedding and portrait photographer who works in natural light and leans toward estate and vineyard venues.			http://marysarah.photography/	https://www.instagram.com/marysarahphotography/
Sleeping Bee Designs	Planning		Frederick	Maryland	Frederick	Frederick coordinator specialising in month-of and day-of wedding coordination, with design styling and rentals on the side.	sleepingbeedesigns@gmail.com		https://www.sleepingbeedesigns.com/	https://www.instagram.com/sleepingbeedesigns/
Nevermore Weddings and Events	Planning		Frederick	Maryland	Maryland and the surrounding DMV	Women-owned, inclusive Frederick planner offering coordination, bartending, staffing, rentals and ceremony officiation.	info@nevermoreevents.com		https://www.nevermoreweddingsandevents.com/	https://www.instagram.com/nevermoreweddingsandevents/
Once Upon A Time Events	Planning		Frederick	Maryland	Maryland, Pennsylvania, Virginia, Washington DC and West Virginia	Frederick planning and decor company covering weddings and quinceañeras, with design, florals and day-of coordination.		(240) 440-9134	https://onceuponatime.events/wedding-planner-frederick-md/	https://www.instagram.com/onceuponatime.events/
Frederick Flower Farm	Florals	7102 Linganore Rd	Frederick	Maryland	Frederick and the DMV, with delivery and setup up to 1.5 hours away	Working flower farm outside Frederick supplying wedding florals grown on site, which also runs seasonal U-pick days.	frederickflowerfarm@gmail.com	240-439-0428	https://www.frederickflowerfarm.com/	https://www.instagram.com/frederickflowerfarm/
Sweet Blossoms LLC	Florals		Frederick	Maryland	Maryland, Washington DC and Northern Virginia	Frederick floral designer making custom wedding and event flowers since 2011, with a focus on sustainable practices.	blair@sweetblossomsllc.com		https://sweetblossomsllc.com/	https://www.instagram.com/thesweetblossoms/
Maryland Florals	Florals	3340 Galena Dr, Suite 104	Frederick	Maryland	Frederick	Frederick flower shop that designs bridal bouquets, ceremony arrangements and reception flowers, with consultations by appointment.		(240) 812-2713	https://www.marylandflorals.net/wedding-flowers	https://www.instagram.com/marylandflorals/
Dan McGuire Group	Music		Frederick	Maryland	Maryland, Washington DC and Virginia	Frederick live-music company supplying wedding bands, DJs, lighting and photo booths, so one team can cover ceremony and dance floor.	info@danmcguiregroup.com	(240) 292-9482	https://www.danmcguiregroup.com/	https://www.instagram.com/danmcguiregroup/
District Event Co	Music		Frederick	Maryland	Washington DC, Maryland and Northern Virginia; travels further	Frederick entertainment and production company offering DJs, MCs, live musicians, lighting and AV for weddings across the DMV.	contact@districtdj.com	(240) 292-9482	https://www.districtdj.com/	https://www.instagram.com/districteventco/
Frederick DJs	Music		Frederick	Maryland	Frederick	Frederick DJ service for weddings and private parties, with event production support and bookings open into 2027.			https://frederickdjs.com/	https://www.instagram.com/FrederickDJsMD/
Celebrations Catering	Catering	425 N Church St	Thurmont	Maryland	Frederick and Thurmont	Long-running Thurmont caterer handling wedding menus, staffing and day-of service for Frederick County receptions.		(301) 271-2220	https://www.celebrationsfrederick.com/weddings/	https://www.instagram.com/celebrationsfrederick/
Canapés Catering	Catering	1 Frederick Health Way, Suite 210	Frederick	Maryland	Maryland, Pennsylvania, Northern Virginia and Washington DC	Frederick caterer since 1989 serving weddings and corporate events, with an on-site cafe and bakery that also makes custom cakes.	info@canapescatering.com	301-663-8220	https://www.canapescatering.com/	
P.I.G.S. BBQ Catering	Catering	2401 Whittier Dr, Suite E	Frederick	Maryland	Mid-Maryland	Frederick barbecue restaurant with an events arm, catering smoked meats, house sauces and sides for relaxed wedding receptions.		301-620-7447	https://www.porkisgoodstuff.com/	https://www.instagram.com/pigsbbq/
Renaissance Chef Catering	Catering	244 S Jefferson St, Unit C	Frederick	Maryland		Full-service Frederick caterer since 2005 handling weddings, cocktail parties and barbecue-style events.	info@renaissancechef.com	301-228-2433	https://www.renaissancechef.com/	https://www.instagram.com/renchefcatering/
Lauren Abagale Bridal	Hair & Makeup	3556 Worthington Blvd, Unit 201	Frederick	Maryland		Frederick bridal hair and makeup artist working from a studio suite, also offering lash enhancements for the wedding day.	Bridal@LaurenAbagale.com	240-675-0615	https://laurenabagale.com/	https://www.instagram.com/laurenabagalebridal/
MBM Beauty	Hair & Makeup	3556 Worthington Blvd, Unit 201	Frederick	Maryland	Frederick and Urbana, serving the DMV	Frederick beauty team covering bridal hair, makeup and airbrush spray tans for brides and their wedding parties.	mbmbeautydmv@gmail.com	240-422-8272	https://www.mbmbeauty.us/	https://www.instagram.com/mbmbeauty_dmv/
JnetBeauty Artist	Hair & Makeup		Frederick	Maryland	Frederick, Washington DC, Loudoun County, Baltimore and nearby	Mobile Frederick makeup artist who travels to the bride for wedding mornings, events and everyday glam.			https://jnetbeautyartist.com/frederick-makeup-artist/	https://www.instagram.com/jnetbeautyartist/
The Golden Rose Cakery	Cake		Frederick	Maryland	Frederick area, within about 30 miles	Small-batch Frederick home bakery making custom wedding cakes, cupcakes and cookies, with a gallery of past weddings.	thegoldenrosecakery@gmail.com	301-668-2959	https://www.thegoldenroseonline.net/	
Natty Cakes Bakery	Cake		Frederick	Maryland	Frederick	Frederick custom dessert bakery making bold, richly flavoured cakes for weddings as well as smaller parties.			https://nattycakesbakeryllc.com/	https://www.instagram.com/nattycakesbakerymd/
Fine Art Wedding Film	Videography		Frederick	Maryland	DC, Maryland and Virginia; travels worldwide	Husband-and-wife Frederick team making cinematic, story-led wedding films for couples around the Mid-Atlantic.	fineartweddingfilm@gmail.com	240-439-5962	https://www.fineartweddingfilm.com/	https://www.instagram.com/afineartweddingfilm/
Rockridge Productions	Videography		Frederick	Maryland	Frederick, Washington DC, Baltimore and Northern Virginia	Frederick video production company since 2007 that includes cinematic wedding films alongside commercial and brand work.		227-800-3611	https://www.rockridgeproductions.com/	
Stories by Olivia	Videography		Frederick	Maryland		Full-time Frederick wedding videographer focused on candid, personal films that tell each couple's story.	Livvy@StoriesByOlivia.com	907-738-1867	https://www.storiesbyolivia.com/about	`,
  },
];

export default batches;
