import type { VendorBatch } from "@/lib/vendor-batches";

// Massachusetts vendor batches. Every row's State is "Massachusetts". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Boston: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
CityLux Studios	Photography		Boston	Massachusetts	Boston, Newport, the New Hampshire Seacoast, Cape Cod and beyond	Husband-and-wife studio blending editorial and documentary wedding photography, with an engagement session included in every package.		978-595-1581	https://citylux.studio/	https://www.instagram.com/cityluxstudios/
Nicole Chan Photo & Video	Photography	177 Tremont Street	Boston	Massachusetts	Greater Boston, Massachusetts and destination weddings	Boston photo and video team with deep experience of Chinese, Indian and multicultural weddings, shot in a photojournalistic style.	nicole@nicolechanphotography.com		https://www.nicolechanphotography.com/	https://www.instagram.com/nicolechanphotography/
Fern & Feather Studio	Photography		Boston	Massachusetts	Boston and New England	Photo and film studio known for South Asian weddings, from sangeet to ceremony, captured in a warm documentary and editorial style.	info@fernfeatherstudio.com	(508) 686-1159	https://www.fernfeatherstudio.com/	https://www.instagram.com/fernfeatherstudio/
Gina Brocker Photography	Photography		Boston	Massachusetts	Boston and surrounding areas	Documentary wedding photographer who focuses on candid, emotional moments rather than posed set-ups, from city venues to historic houses.			https://ginabrocker.com/	https://www.instagram.com/ginabrocker/
Soraya Events	Planning	868 Worcester St	Wellesley	Massachusetts		Wellesley planning studio focused on multicultural and South Asian weddings, with its own in-house catering and bar service.	info@sorayaevents.com	508-203-7848	https://sorayaevents.com/	https://www.instagram.com/soraya_events/
Lia Bancroft Events	Planning		Boston	Massachusetts	Cape Cod, Newport, the New Hampshire and Maine coasts, the Hamptons, Charleston and Palm Beach	Full-service planner taking a small number of couples each year, specialising in coastal wedding weekends with heirloom detail.			https://liabancroftevents.com/	https://www.instagram.com/liabancroftevents/
Allure Affair	Planning		Boston	Massachusetts	New England	New England planning company offering day-of coordination, partial or full planning, so couples choose how much help they need.	weddings@allureaffair.com	860-978-6645	https://www.allureaffair.com/	https://www.instagram.com/theallureaffairr/
Kate Murtaugh Events & Design	Planning		Duxbury	Massachusetts	New England and beyond	Luxury planning and design studio with offices in Boston, Duxbury and Westerly, known for tented events and private estate weddings.			https://katemurtaughevents.com/	https://www.instagram.com/katemurtaugh/
Floristika Studio	Florals	435 Newtonville Ave	Newton	Massachusetts	Boston and New England	European-style floral and wedding design studio in Newton, creating custom arrangements for weddings and events of every size.	info@floristikastudio.com	(617) 514-0903	https://www.floristikastudio.com/	https://www.instagram.com/floristika_studio/
Artistic Blossoms	Florals		Boston	Massachusetts	Boston metro, Cape Cod, New England, New York City and destinations	Event-only floral studio led by founder Kelly Dolloff for over 40 years, with eclectic designs and no retail shop to split attention.			https://www.artisticblossoms.com/	https://www.instagram.com/artisticblossoms/
Ephemirus	Florals		Boston	Massachusetts	New England and beyond	Floral design studio working with local and foraged flowers to create sculptural, romantic and seasonal wedding arrangements.	ephemirus@gmail.com		https://www.ephemirus.com/	https://www.instagram.com/ephemirus/
Althea Floral Design	Florals		Stoneham	Massachusetts	Within 100 miles of Greater Boston	Stoneham florist making bold, colourful and playful wedding florals and installations, with full weddings from 6,500 dollars.			https://www.altheafloraldesign.com/	https://www.instagram.com/althea.floral.boston/
Wilson Stevens	Music		Boston	Massachusetts	New England, including Cape Cod and Newport	Second-generation family band agency founded in 1987, run by musicians, with a roster of 15 bands for multi-generational dance floors.		978-256-0360	https://wilsonstevens.com/	https://www.instagram.com/wilsonstevensbands/
617 Weddings	Music	400 West Cummings Park	Woburn	Massachusetts	Boston and New England	Woburn wedding DJ and lighting company that also offers photography and video, so couples can book one team for the day.	info@617weddings.com	617-207-0003	https://617weddings.com/	
Boston Sound and Light Company	Music		Cambridge	Massachusetts	New England	Indian wedding DJ and production company handling baraats, sangeet nights, uplighting, LED dance floors and photo booths.	DJYogz@Gmail.com	978-360-4273	https://www.bostonsoundandlight.com/	
Johnny Burke Catering	Catering	170 Spring St	Boston	Massachusetts	Greater Boston	Full-service caterer cooking with local organic produce and meat from sustainable ranches, and a preferred caterer at over 25 venues.	catering@johnnyburkecatering.com	617-312-1408	https://johnnyburkecatering.com/	https://www.instagram.com/johnnyburkecatering/
Catering by Andrew	Catering	3867 Washington Street	Roslindale	Massachusetts		Kosher caterer under KVH supervision, handling weddings and other celebrations from its kitchen in Roslindale.	office@cateringbyandrew.com	(617) 731-6585	https://www.cateringbyandrew.com/	https://www.instagram.com/catering_by_andrew/
Boston Indian Catering	Catering	500 Harvard Street	Brookline	Massachusetts		Brookline Indian caterer with wedding and event menus spanning meat, seafood and a wide vegetarian range, plus breads and desserts.		(617) 734-9000	https://www.bostonindiancatering.com/	
Tova's Catering	Catering	253 Mansfield Ave	Norton	Massachusetts	Greater Boston and New England	Glatt kosher, Vaad-certified caterer started by Tova Yarmush in 1990, catering weddings, bar and bat mitzvahs and community events.	planner@tovascatering.com	508-286-2242	https://www.tovascatering.com/	https://www.instagram.com/tovascateringinc/
Lyndsay Simon Beauty	Hair & Makeup		Boston	Massachusetts	Greater Boston, Cape Cod, Rhode Island, Maine, New Hampshire and beyond	On-location bridal hair and makeup team known for soft glam, travelling to your home, hotel or wedding venue.	lyndsay@lyndsaysimonbeauty.com	617-249-3029	https://lyndsaysimonbeauty.com/	https://www.instagram.com/lyndsaysimonbeauty/
ZenaRose	Hair & Makeup	49 River Street	Boston	Massachusetts	Boston	Beacon Hill studio doing bridal hair, airbrush makeup and lashes, in the salon for small parties or on location for larger ones.	hello@zenarose.com	857-991-1680	https://www.zenarose.com/bridalsuite	https://www.instagram.com/zrboston/
Edra Couture Bridal	Hair & Makeup	5 Post Office Square, Suite 2	Sharon	Massachusetts	Boston, New England and Punta Cana	Bridal hair and makeup team offering South Asian, Hollywood glam and whimsical looks, with trials included in signature packages.	info@edracouturebridal.com	(847) 420-5078	https://edracouturebridal.com/	https://www.instagram.com/edra_couture_bridal/
GlamByHitesha	Hair & Makeup		Boston	Massachusetts		Boston makeup and hair artist specialising in Indian bridal looks for wedding and reception changes, now booking 2026 and 2027.	shah.hitesha@gmail.com		https://hiteshashah.com/	https://www.instagram.com/glambyhitesha/
Konditor Meister	Cake	32 Wood Road	Braintree	Massachusetts	Greater Boston and beyond	European-style bakery making cakes and pastries for over 40 years, with custom wedding cakes and tastings by appointment.		(781) 849-1970	https://konditormeister.com/	https://www.instagram.com/konditormeister/
Topsfield Bakeshop	Cake	42 Main Street	Topsfield	Massachusetts	Boston's North Shore	North Shore bakeshop open since 1997, making specialty wedding cakes and cupcakes alongside its everyday pastries.	info@topsfieldbakeshop.com	(978) 887-0795	https://www.topsfieldbakeshop.com/	https://www.instagram.com/topsfieldbakeshop/
Montilio's Bakery	Cake	285 Columbia Road	Hanover	Massachusetts		Family-owned South Shore bakery with six shops, offering wedding cake consultations, flavour tastings and wedding favours.		(781) 887-2253	https://montilios.com/	
S.H. Videography	Videography	162 Newbury Street	Boston	Massachusetts		Family film studio founded over 30 years ago by Kathy and Steve and now in its second generation, making story-led wedding films.	Info@shvideography.com	(617) 840-4119	https://www.shvideography.com/	https://www.instagram.com/shvideography/
Brighter Lights	Videography		Boston	Massachusetts	New England, including Cape Cod, Nantucket, Martha's Vineyard and Newport	Cinematic wedding films shot in 4K with drone footage, in packages from a short highlight to a full feature edit.	julian@brighterlightsmedia.com	888-929-2427	https://www.brighterlightsmedia.com/	https://www.instagram.com/brighterlightsmedia/
The Ewings	Videography		Bolton	Massachusetts	New England	Erica and Ben's photo and video team based outside Boston, with plenty of experience filming Chinese tea ceremonies and city weddings.	erica@the-ewings.com		https://the-ewings.com/	https://www.instagram.com/theewingsstudio/`,
  },
  {
    name: "Cape Cod: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alex Gordias Photography	Photography		Mashpee	Massachusetts	Cape Cod, Boston, Newport and New England, plus destination weddings	Mashpee photographer mixing candid documentary coverage with polished fine-art portraits, at home at Cape resorts and island estates alike.	gordeev.photo@gmail.com	774.232.7141	https://www.alexgordias.com/	https://www.instagram.com/alexgordiasphotography/
Jolie Flower Shop	Florals	115 Old Town House Rd	South Yarmouth	Massachusetts	Cape Cod, from Falmouth to Provincetown	South Yarmouth flower shop designing bouquets, centrepieces and arches for Cape weddings, and avoiding floral foam in its work.	info@jolieflowershop.com	(774) 368-0508	https://www.jolieflowershop.com/	https://www.instagram.com/jolieflowershopcapecod/
Sea & Soil Botanical Design	Florals		Wellfleet	Massachusetts	Outer Cape Cod	Wellfleet flower farm and design studio growing its own seasonal blooms, with wedding packages from full service to a la carte.			https://seaandsoilwellfleet.com/	https://www.instagram.com/seaandsoildesign/
Fire Cat Farm	Florals		West Tisbury	Massachusetts	Martha's Vineyard	West Tisbury flower farm doing full-service wedding florals from its own fields, or buckets of fresh stems for couples who arrange themselves.	firecatfarmmv@gmail.com		https://www.firecatfarmmv.com/wedding-flowers	https://www.instagram.com/fire.cat.farm/
Delicious Desserts	Cake	44 Candace Way	East Falmouth	Massachusetts	Cape Cod, Boston and Newport	East Falmouth cake studio making custom wedding cakes and full dessert tables, with design given as much weight as flavour.	lisa@deliciousdesserts.net	508-540-3352	https://deliciousdesserts.net/	https://www.instagram.com/deliciousdessertscapecod/
The Nantucket Bake Shop	Cake	17 1/2 Old South Road	Nantucket	Massachusetts	Nantucket	Island bakery of over 45 years baking tiered wedding cakes in a few classic flavours, with icing, decoration, delivery and set-up included.		508.228.2797	https://nantucketbakeshop.com/pages/cakes	https://www.instagram.com/nantucketbakeshop/
Confections by the Sea	Cake		Chatham	Massachusetts	Cape Cod	Chatham home cake studio taking a few weddings a year, known for hand-made sugar flowers and cakes and fillings made from scratch.	bakers@confectionsbythesea.com		https://confectionsbythesea.com/	https://www.instagram.com/confectionsbythesea/
White's Catering	Catering		Brewster	Massachusetts	Cape Cod	Off-premise caterer on the Cape for over 20 years with family roots in Boston catering since the 1940s, handling set-up, service and clean-up.		508-776-8331	https://capecaterers.com/	https://www.instagram.com/capecaterers/
Cape Cod Chef on Call	Catering		West Chatham	Massachusetts	All of Cape Cod, from Bourne and Falmouth to Provincetown	Chef-led caterer cooking on site since 1999 for weddings up to 150 guests, from plated dinners and family-style feasts to clambakes.		508-896-1400	https://www.capecodchefoncall.com/	https://www.instagram.com/capecodchefoncall/
Nantucket Catering Company	Catering		Nantucket	Massachusetts	Nantucket	Island caterer running since 2001, covering wedding receptions, lobster bakes and morning-after brunches across Nantucket.			https://nantucketcateringcompany.com/nantucket-weddings/	https://www.instagram.com/nantucketcateringcompany/
KG Events & Design	Planning		Edgartown	Massachusetts	Martha's Vineyard, Nantucket and destinations	Edgartown planning and design firm founded in 2013 by Kristen Gosselin, used to the ferry, tenting and remote-site logistics of island weddings.	office@kgeventsdesign.com		https://www.kgeventsdesign.com/	https://www.instagram.com/kgeventsdesign/
Jessica Hennessey Weddings	Planning		Marshfield	Massachusetts	Cape Cod, Boston, Newport and the Northeast	Marshfield planner and designer offering full planning or day-of coordination, with recent weddings from Cape Cod clubs to Boston hotels.	jessicahennesseyweddings@gmail.com	(603) 320-0201	https://www.jessicahennesseyweddings.com/	https://www.instagram.com/jessicahennesseyweddings/
Magnolia Affairs	Planning		Nantucket	Massachusetts	Nantucket	Nantucket-based planner Karina designs and runs full wedding weekends on the island, and also offers hourly consulting for couples who plan themselves.	Karina@MagnoliaAffairs.com	843.415.2313	https://www.magnoliaaffairs.com/	https://www.instagram.com/magnoliaaffairs/
Shoreshotz Photography	Photography		Mashpee	Massachusetts	Cape Cod, Boston, Newport, New England and Caribbean destinations	Mashpee photographer working since 2009 in a bright, natural-light style, at home at coastal and waterfront weddings across the Cape.		508.488.7868	https://shoreshotz.com/	https://www.instagram.com/shoreshotzcapecod/
Artworx Beauty	Hair & Makeup	30 North St	Mashpee	Massachusetts	Cape Cod and New England	Mashpee Commons makeup studio, part of the Cape bridal scene for nearly 40 years, offering on-location bridal makeup and custom wedding quotes.	kristin@artworxbeauty.com	508.292.4981	https://www.artworxbeauty.com/	https://www.instagram.com/artworxbeautycc/
Mia Patrick Photography	Photography		Sandwich	Massachusetts	Cape Cod and coastal New England	Sandwich photographer blending fine-art and photojournalistic coverage, with a Cape engagement session and second shooter in full-day packages.			https://www.miapatrickphotography.com/	https://www.instagram.com/miapatrickphotography/
Mike Benjamin & The Keepers	Music		Edgartown	Massachusetts	Martha's Vineyard, Nantucket, Cape Cod and Boston	Edgartown live band playing Vineyard weddings for over 15 years, covering ceremony, cocktail hour, rehearsal dinner and reception sets.	mike@mikebenjaminmusic.com	508-642-0439	https://mikebenjaminmusic.com/	https://www.instagram.com/mikebenjaminandthekeepersmv/
Cape Symphony Presents	Music	2235 Iyannough Road	West Barnstable	Massachusetts	Cape Cod	Booking arm of the Cape Symphony supplying string quartets, trios, piano, guitar and jazz groups for ceremonies, cocktail hours and receptions.		774.470.2282	https://capesymphony.org/cape-symphony-presents/live-music-bookings	https://www.instagram.com/cape_symphony/
Salt Spray Films	Videography		West Yarmouth	Massachusetts	Cape Cod and Atlanta	West Yarmouth studio making cinematic wedding films, with photography too, so couples can book both from one team; packages from about 3,000 dollars.	saltsprayfilms@gmail.com		https://www.saltsprayfilms.com/	https://www.instagram.com/saltsprayfilms/
Tolay Productions	Videography		Edgartown	Massachusetts	Martha's Vineyard and New England	Edgartown filmmaker Borja Tolay making cinematic, story-led wedding films on Martha's Vineyard, alongside commercial and event work.	Borja@Tolayproductions.com	(339)-364-5237	https://www.tolayproductions.com/	https://www.instagram.com/borja_tolay/
Paolina Beauty	Hair & Makeup		Nantucket	Massachusetts	Nantucket	Nantucket makeup artist bringing bridal makeup to the bride on the island, for timeless looks on the wedding morning without leaving home.	makeupbypaolina@gmail.com	508.901.3606	https://www.paolinabeauty.com/	https://www.instagram.com/_paolina_beauty_/
Bellezza Salon Medspa	Hair & Makeup	221 Main Street	Falmouth	Massachusetts	Upper Cape, including Falmouth, Woods Hole, Mashpee and Bourne	Falmouth salon and medspa doing bridal hair and makeup in the salon or on location, with styling meant to hold up in coastal humidity.	info@spabellezza.com	(508) 299-8300	https://spabellezza.com/bridal-events/	https://www.instagram.com/bellezzasalonmedspa/`,
  },
];

export default batches;
