import type { VendorBatch } from "@/lib/vendor-batches";

// Massachusetts vendor batches. Every row's State is "Massachusetts". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Boston: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
CityLux Studios	Photography		Boston	Massachusetts	Boston, Newport, the New Hampshire Seacoast, Cape Cod and beyond	Husband-and-wife studio blending editorial and documentary wedding photography, with an engagement session included in every package.		978-595-1581	https://citylux.studio/	https://www.instagram.com/cityluxstudios/
Nicole Chan Photo & Video	Photography	177 Tremont Street	Boston	Massachusetts	Greater Boston, Massachusetts and destination weddings	Boston photo and video team with deep experience of Chinese, Indian and multicultural weddings, shot in a photojournalistic style.	nicole@nicolechanphotography.com		https://www.nicolechanphotography.com/	https://www.instagram.com/nicolechanphotography/
Fern & Feather Studio	Photography		Boston	Massachusetts	Boston and New England	Photo and film studio known for South Asian weddings, from sangeet to ceremony, captured in a warm documentary and editorial style.	info@fernfeatherstudio.com	(508) 686-1159	https://www.fernfeatherstudio.com/	https://www.instagram.com/fernfeatherstudio/
Gina Brocker Photography	Photography		Boston	Massachusetts	Boston and surrounding areas	Documentary wedding photographer who focuses on candid, emotional moments rather than posed set-ups, from city venues to historic houses.			https://ginabrocker.com/	https://www.instagram.com/ginabrocker/
Soraya Events	Planning	868 Worcester St	Wellesley	Massachusetts		Wellesley planning studio focused on multicultural and South Asian weddings, with its own in-house catering and bar service.	info@sorayaevents.com	508-203-7848	https://sorayaevents.com/	https://www.instagram.com/soraya_events/
Lia Bancroft Events	Planning		Boston	Massachusetts	Cape Cod, Newport, the New Hampshire and Maine coasts, the Hamptons, Charleston and Palm Beach	Full-service planner taking a small number of couples each year, specialising in coastal wedding weekends with heirloom detail.			https://liabancroftevents.com/	https://www.instagram.com/liabancroftevents/
Allure Affair	Planning		Boston	Massachusetts	New England	New England planning company offering day-of coordination, partial or full planning, so couples choose how much help they need.	weddings@allureaffair.com	860-978-6645	https://www.allureaffair.com/	https://www.instagram.com/theallureaffairr/
Kate Murtaugh Events & Design	Planning		Duxbury	Massachusetts	New England and beyond	Luxury planning and design studio with offices in Boston, Duxbury and Westerly, known for tented events and private estate weddings.			https://katemurtaughevents.com/	https://www.instagram.com/katemurtaugh/
Floristika Studio	Florals	435 Newtonville Ave	Newton	Massachusetts	Boston and New England	European-style floral and wedding design studio in Newton, creating custom arrangements for weddings and events of every size.	info@floristikastudio.com	(617) 514-0903	https://www.floristikastudio.com/	https://www.instagram.com/floristika_studio/
Artistic Blossoms	Florals		Boston	Massachusetts	Boston metro, Cape Cod, New England, New York City and destinations	Event-only floral studio led by founder Kelly Dolloff for over 40 years, with eclectic designs and no retail shop to split attention.			https://www.artisticblossoms.com/	https://www.instagram.com/artisticblossoms/
Ephemirus	Florals		Boston	Massachusetts	New England and beyond	Floral design studio working with local and foraged flowers to create sculptural, romantic and seasonal wedding arrangements.	ephemirus@gmail.com		https://www.ephemirus.com/	https://www.instagram.com/ephemirus/
Althea Floral Design	Florals		Stoneham	Massachusetts	Within 100 miles of Greater Boston	Stoneham florist making bold, colourful and playful wedding florals and installations, with full weddings from 6,500 dollars.			https://www.altheafloraldesign.com/	https://www.instagram.com/althea.floral.boston/
Wilson Stevens	Music		Boston	Massachusetts	New England, including Cape Cod and Newport	Second-generation family band agency founded in 1987, run by musicians, with a roster of 15 bands for multi-generational dance floors.		978-256-0360	https://wilsonstevens.com/	https://www.instagram.com/wilsonstevensbands/
617 Weddings	Music	400 West Cummings Park	Woburn	Massachusetts	Boston and New England	Woburn wedding DJ and lighting company that also offers photography and video, so couples can book one team for the day.	info@617weddings.com	617-207-0003	https://617weddings.com/	
Boston Sound and Light Company	Music		Cambridge	Massachusetts	New England	Indian wedding DJ and production company handling baraats, sangeet nights, uplighting, LED dance floors and photo booths.	DJYogz@Gmail.com	978-360-4273	https://www.bostonsoundandlight.com/	
Johnny Burke Catering	Catering	170 Spring St	Boston	Massachusetts	Greater Boston	Full-service caterer cooking with local organic produce and meat from sustainable ranches, and a preferred caterer at over 25 venues.	catering@johnnyburkecatering.com	617-312-1408	https://johnnyburkecatering.com/	https://www.instagram.com/johnnyburkecatering/
Catering by Andrew	Catering	3867 Washington Street	Roslindale	Massachusetts		Kosher caterer under KVH supervision, handling weddings and other celebrations from its kitchen in Roslindale.	office@cateringbyandrew.com	(617) 731-6585	https://www.cateringbyandrew.com/	https://www.instagram.com/catering_by_andrew/
Boston Indian Catering	Catering	500 Harvard Street	Brookline	Massachusetts		Brookline Indian caterer with wedding and event menus spanning meat, seafood and a wide vegetarian range, plus breads and desserts.		(617) 734-9000	https://www.bostonindiancatering.com/	
Tova's Catering	Catering	253 Mansfield Ave	Norton	Massachusetts	Greater Boston and New England	Glatt kosher, Vaad-certified caterer started by Tova Yarmush in 1990, catering weddings, bar and bat mitzvahs and community events.		508-286-2242	https://www.tovascatering.com/	https://www.instagram.com/tovascateringinc/
Lyndsay Simon Beauty	Hair & Makeup		Boston	Massachusetts	Greater Boston, Cape Cod, Rhode Island, Maine, New Hampshire and beyond	On-location bridal hair and makeup team known for soft glam, travelling to your home, hotel or wedding venue.	lyndsay@lyndsaysimonbeauty.com	617-249-3029	https://lyndsaysimonbeauty.com/	https://www.instagram.com/lyndsaysimonbeauty/
ZenaRose	Hair & Makeup	49 River Street	Boston	Massachusetts	Boston	Beacon Hill studio doing bridal hair, airbrush makeup and lashes, in the salon for small parties or on location for larger ones.	hello@zenarose.com	857-991-1680	https://www.zenarose.com/bridalsuite	https://www.instagram.com/zrboston/
Edra Couture Bridal	Hair & Makeup	5 Post Office Square, Suite 2	Sharon	Massachusetts	Boston, New England and Punta Cana	Bridal hair and makeup team offering South Asian, Hollywood glam and whimsical looks, with trials included in signature packages.	info@edracouturebridal.com	(847) 420-5078	https://edracouturebridal.com/	https://www.instagram.com/edra_couture_bridal/
GlamByHitesha	Hair & Makeup		Boston	Massachusetts		Boston makeup and hair artist specialising in Indian bridal looks for wedding and reception changes, now booking 2026 and 2027.	shah.hitesha@gmail.com		https://hiteshashah.com/	https://www.instagram.com/glambyhitesha/
Konditor Meister	Cake	32 Wood Road	Braintree	Massachusetts	Greater Boston and beyond	European-style bakery making cakes and pastries for over 40 years, with custom wedding cakes and tastings by appointment.		(781) 849-1970	https://konditormeister.com/	https://www.instagram.com/konditormeister/
Topsfield Bakeshop	Cake	42 Main Street	Topsfield	Massachusetts	Boston's North Shore	North Shore bakeshop open since 1997, making specialty wedding cakes and cupcakes alongside its everyday pastries.	info@topsfieldbakeshop.com	(978) 887-0795	https://www.topsfieldbakeshop.com/	https://www.instagram.com/topsfieldbakeshop/
Montilio's Bakery	Cake	285 Columbia Road	Hanover	Massachusetts		Family-owned South Shore bakery with six shops, offering wedding cake consultations, flavour tastings and wedding favours.		(781) 887-2253	https://montilios.com/	
S.H. Videography	Videography	162 Newbury Street	Boston	Massachusetts		Family film studio founded over 30 years ago by Kathy and Steve and now in its second generation, making story-led wedding films.	Info@shvideography.com	(617) 840-4119	https://www.shvideography.com/	https://www.instagram.com/shvideography/
Brighter Lights	Videography		Boston	Massachusetts	New England, including Cape Cod, Nantucket, Martha's Vineyard and Newport	Cinematic wedding films shot in 4K with drone footage, in packages from a short highlight to a full feature edit.	julian@brighterlightsmedia.com	888-929-2427	https://www.brighterlightsmedia.com/	https://www.instagram.com/brighterlightsmedia/
The Ewings	Videography		Bolton	Massachusetts	New England	Erica and Ben's photo and video team based outside Boston, with plenty of experience filming Chinese tea ceremonies and city weddings.	erica@the-ewings.com		https://the-ewings.com/	https://www.instagram.com/theewingsstudio/`,
  },
  {
    name: "Cape Cod: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alex Gordias Photography	Photography		Mashpee	Massachusetts	Cape Cod, Boston, Newport and New England, plus destination weddings	Mashpee photographer mixing candid documentary coverage with polished fine-art portraits, at home at Cape resorts and island estates alike.	gordeev.photo@gmail.com	774.232.7141	https://www.alexgordias.com/	https://www.instagram.com/alexgordiasphotography/
Jolie Flower Shop	Florals	115 Old Town House Rd	South Yarmouth	Massachusetts	Cape Cod, from Falmouth to Provincetown	South Yarmouth flower shop designing bouquets, centrepieces and arches for Cape weddings, and avoiding floral foam in its work.	info@jolieflowershop.com	(774) 368-0508	https://www.jolieflowershop.com/	https://www.instagram.com/jolieflowershopcapecod/
Sea & Soil Botanical Design	Florals		Wellfleet	Massachusetts	Outer Cape Cod	Wellfleet flower farm and design studio growing its own seasonal blooms, with wedding packages from full service to a la carte.			https://seaandsoilwellfleet.com/	https://www.instagram.com/seaandsoildesign/
Fire Cat Farm	Florals		West Tisbury	Massachusetts	Martha's Vineyard	West Tisbury flower farm doing full-service wedding florals from its own fields, or buckets of fresh stems for couples who arrange themselves.	firecatfarmmv@gmail.com		https://www.firecatfarmmv.com/wedding-flowers	https://www.instagram.com/fire.cat.farm/
Delicious Desserts	Cake	44 Candace Way	East Falmouth	Massachusetts	Cape Cod, Boston and Newport	East Falmouth cake studio making custom wedding cakes and full dessert tables, with design given as much weight as flavour.	lisa@deliciousdesserts.net	508-540-3352	https://deliciousdesserts.net/	https://www.instagram.com/deliciousdessertscapecod/
The Nantucket Bake Shop	Cake	17 1/2 Old South Road	Nantucket	Massachusetts	Nantucket	Island bakery of over 45 years baking tiered wedding cakes in a few classic flavours, with icing, decoration, delivery and set-up included.		508.228.2797	https://nantucketbakeshop.com/pages/cakes	https://www.instagram.com/nantucketbakeshop/
Confections by the Sea	Cake		Chatham	Massachusetts	Cape Cod	Chatham home cake studio taking a few weddings a year, known for hand-made sugar flowers and cakes and fillings made from scratch.	bakers@confectionsbythesea.com		https://confectionsbythesea.com/	https://www.instagram.com/confectionsbythesea/
White's Catering	Catering		Brewster	Massachusetts	Cape Cod	Off-premise caterer on the Cape for over 20 years with family roots in Boston catering since the 1940s, handling set-up, service and clean-up.		508-776-8331	https://capecaterers.com/	https://www.instagram.com/capecaterers/
Cape Cod Chef on Call	Catering		West Chatham	Massachusetts	All of Cape Cod, from Bourne and Falmouth to Provincetown	Chef-led caterer cooking on site since 1999 for weddings up to 150 guests, from plated dinners and family-style feasts to clambakes.		508-896-1400	https://www.capecodchefoncall.com/	https://www.instagram.com/capecodchefoncall/
Nantucket Catering Company	Catering		Nantucket	Massachusetts	Nantucket	Island caterer running since 2001, covering wedding receptions, lobster bakes and morning-after brunches across Nantucket.			https://nantucketcateringcompany.com/nantucket-weddings/	https://www.instagram.com/nantucketcateringcompany/
KG Events & Design	Planning		Edgartown	Massachusetts	Martha's Vineyard, Nantucket and destinations	Edgartown planning and design firm founded in 2013 by Kristen Gosselin, used to the ferry, tenting and remote-site logistics of island weddings.	office@kgeventsdesign.com		https://www.kgeventsdesign.com/	https://www.instagram.com/kgeventsdesign/
Jessica Hennessey Weddings	Planning		Marshfield	Massachusetts	Cape Cod, Boston, Newport and the Northeast	Marshfield planner and designer offering full planning or day-of coordination, with recent weddings from Cape Cod clubs to Boston hotels.	jessicahennesseyweddings@gmail.com	(603) 320-0201	https://www.jessicahennesseyweddings.com/	https://www.instagram.com/jessicahennesseyweddings/
Magnolia Affairs	Planning		Nantucket	Massachusetts	Nantucket	Nantucket-based planner Karina designs and runs full wedding weekends on the island, and also offers hourly consulting for couples who plan themselves.	Karina@MagnoliaAffairs.com	843.415.2313	https://www.magnoliaaffairs.com/	https://www.instagram.com/magnoliaaffairs/
Shoreshotz Photography	Photography		Mashpee	Massachusetts	Cape Cod, Boston, Newport, New England and Caribbean destinations	Mashpee photographer working since 2009 in a bright, natural-light style, at home at coastal and waterfront weddings across the Cape.		508.488.7868	https://shoreshotz.com/	https://www.instagram.com/shoreshotzcapecod/
Artworx Beauty	Hair & Makeup	30 North St	Mashpee	Massachusetts	Cape Cod and New England	Mashpee Commons makeup studio, part of the Cape bridal scene for nearly 40 years, offering on-location bridal makeup and custom wedding quotes.	kristin@artworxbeauty.com	508.292.4981	https://www.artworxbeauty.com/	https://www.instagram.com/artworxbeautycc/
Mia Patrick Photography	Photography		Sandwich	Massachusetts	Cape Cod and coastal New England	Sandwich photographer blending fine-art and photojournalistic coverage, with a Cape engagement session and second shooter in full-day packages.			https://www.miapatrickphotography.com/	https://www.instagram.com/miapatrickphotography/
Mike Benjamin & The Keepers	Music		Edgartown	Massachusetts	Martha's Vineyard, Nantucket, Cape Cod and Boston	Edgartown live band playing Vineyard weddings for over 15 years, covering ceremony, cocktail hour, rehearsal dinner and reception sets.	mike@mikebenjaminmusic.com	508-642-0439	https://mikebenjaminmusic.com/	https://www.instagram.com/mikebenjaminandthekeepersmv/
Cape Symphony Presents	Music	2235 Iyannough Road	West Barnstable	Massachusetts	Cape Cod	Booking arm of the Cape Symphony supplying string quartets, trios, piano, guitar and jazz groups for ceremonies, cocktail hours and receptions.		774.470.2282	https://capesymphony.org/cape-symphony-presents/live-music-bookings	https://www.instagram.com/cape_symphony/
Salt Spray Films	Videography		West Yarmouth	Massachusetts	Cape Cod and Atlanta	West Yarmouth studio making cinematic wedding films, with photography too, so couples can book both from one team; packages from about 3,000 dollars.	saltsprayfilms@gmail.com		https://www.saltsprayfilms.com/	https://www.instagram.com/saltsprayfilms/
Tolay Productions	Videography		Edgartown	Massachusetts	Martha's Vineyard and New England	Edgartown filmmaker Borja Tolay making cinematic, story-led wedding films on Martha's Vineyard, alongside commercial and event work.	Borja@Tolayproductions.com	(339)-364-5237	https://www.tolayproductions.com/	https://www.instagram.com/borja_tolay/
Paolina Beauty	Hair & Makeup		Nantucket	Massachusetts	Nantucket	Nantucket makeup artist bringing bridal makeup to the bride on the island, for timeless looks on the wedding morning without leaving home.	makeupbypaolina@gmail.com	508.901.3606	https://www.paolinabeauty.com/	https://www.instagram.com/_paolina_beauty_/
Bellezza Salon Medspa	Hair & Makeup	221 Main Street	Falmouth	Massachusetts	Upper Cape, including Falmouth, Woods Hole, Mashpee and Bourne	Falmouth salon and medspa doing bridal hair and makeup in the salon or on location, with styling meant to hold up in coastal humidity.	info@spabellezza.com	(508) 299-8300	https://spabellezza.com/bridal-events/	https://www.instagram.com/bellezzasalonmedspa/`,
  },
  {
    name: "Cape Cod: music and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Digital Imaging of Cape Cod	Videography		West Barnstable	Massachusetts	Cape Cod	West Barnstable video studio filming Cape Cod weddings since 1995, with FAA-certified drone pilots for aerial and time-lapse footage.	capecodvideo@gmail.com	508-420-9090	https://www.capecodvideo.com/	
The Dukes	Music		Vineyard Haven	Massachusetts	Martha's Vineyard, Nantucket, Cape Cod, Boston and beyond	Vineyard Haven band covering island and Cape weddings, from a jazz quartet or acoustic guitarist at cocktails to a horn trio for the ceremony.	info@dukesband.com	316-737-4203	https://dukesband.com/weddings/	https://www.instagram.com/thedukesmv/`,
  },
  {
    name: "Berkshires: photography, planning, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Tricia McCormack Photography	Photography	17 Main Street #2	Lee	Massachusetts	Berkshires	Lee studio with a four-person team photographing Berkshires weddings in a joyful, classic style, with engagements and photo booths too.	tricia@triciamccormack.com	413-358-4351	https://triciamccormack.com/	https://www.instagram.com/triciamccormackphotography/
Nene's Deco	Planning	89 Tanner Street	Pittsfield	Massachusetts		Pittsfield planning and decor studio offering day-of coordination, partial or full planning, and design packages with linens and centrepieces.	nenesdeco@nenesdeco.com		https://www.nenesdeco.com/	
Avela Floral Design	Florals		Williamstown	Massachusetts	Berkshire County, the Hudson Valley, NYC and Boston	Williamstown floral studio run by a Berkshires-raised couple, making sustainably crafted, seasonal designs for in-season weddings.	avelafloraldesign@gmail.com		https://avelafloraldesign.com/	https://www.instagram.com/avela.floral/
Berkshire Catering Co.	Catering	508 State Road	North Adams	Massachusetts	The Berkshires	North Adams caterer of 35 years with a wood-fired pizza oven and charcoal grill, plus servers, bar staff, rentals and allergy-aware menus.		413-228-3737	https://berkshirecateringco.com/	
Marketplace Catering	Catering	240 Stockbridge Road	Great Barrington	Massachusetts		Great Barrington caterer cooking globally inspired, locally made menus for weddings from casual to formal, with specialty cakes and desserts too.		(413) 248-5040	https://marketplacekitchen.com/catering/	https://www.instagram.com/marketplacecatering/
MusiChris DJ & Lighting Service	Music		Pittsfield	Massachusetts	The Berkshires and Western Massachusetts	Pittsfield DJ Chris Plankey runs ceremonies and receptions as DJ and MC, with uplighting, string lights and drapery to dress the room.	chris@djchrisplankey.com	413.442.9854	https://www.djchrisplankey.com/	
Bob Heck Entertainment	Music		Pittsfield	Massachusetts	Berkshire County, Albany and the Springfield area	Pittsfield DJ company pairing wedding DJ sets with event lighting, photo booths and a 360 video booth, booked singly or bundled.	bob@bobheckentertainment.com	(413) 358-4976	https://www.bobheckentertainment.com/	
Sweet Confections by Kelsey	Cake		Pittsfield	Massachusetts	Berkshire County, Western Massachusetts, the Capital Region, Hudson Valley, Southern Vermont and Northwest Connecticut	Pittsfield home bakery making wedding cakes, cupcake towers and dessert bars from scratch, including a build-your-own cake bar for guests.	sctreatsshop@gmail.com	(413) 358-8556	https://sctreatsbakery.com/	https://www.instagram.com/sctreatsbakery/
Patisserie Lenox	Cake	30A Church Street	Lenox	Massachusetts		Family-run French pastry shop in Lenox making wedding cakes to order, plus dessert bars of mini pastries, macarons and cookies.	info@patisserielenox.com	(413) 551-9050	https://www.patisserielenox.com/special-orders	
Sabrina Marie Makeup Artistry	Hair & Makeup	60 Roberts Drive, Suite 315	North Adams	Massachusetts		North Adams makeup artist doing wedding makeup from her studio, alongside brow microblading, lash lifts and tints.	sabrinamariemakeup@gmail.com	413-441-9737	https://www.sabrinamariemakeup.com/	https://www.instagram.com/sabrinamariemakeupartistry/
Makeup Artistry by Liz	Hair & Makeup		Holyoke	Massachusetts	The Pioneer Valley, Berkshires, Northern CT and Southern VT	Western Massachusetts airbrush makeup artist who travels to Berkshires weddings and refers trusted hair stylists for the bridal party.	liz@bridalbyliz.com	413.539.8035	https://www.bridalbyliz.com/	https://www.instagram.com/bridalbyliz/`,
  },
  {
    name: "Worcester: florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
JAM Event DJs	Music	104 Maple St.	West Boylston	Massachusetts	Boston, Portsmouth, Hartford, Newport, Providence and Worcester	West Boylston DJ company playing modern wedding sets from first dance to last song, covering Worcester, Boston and much of New England.	info@jameventdjs.com	(508) 667-8895	https://www.jameventdjs.com/	https://www.instagram.com/jameventdjs/
Sparkle on Park	Florals	263 Park Ave	Worcester	Massachusetts		Worcester florist doing bouquets, buttonholes and arch arrangements, delivering and setting up on the day and working to the couple's budget.	hello@sparkleonpark.com	(508) 762-9270	https://www.sparkleonpark.com/	https://www.instagram.com/sparkleonpark/
Peppers Artful Events	Catering	43 Hudson Street	Northborough	Massachusetts	New England	Northborough caterer and event designer handling food, bar, cake and flowers, and caterer for venues such as Fruitlands and the Bradley Estate.	EventInquiry@peppersartfulevents.com	508.393.6844	https://www.peppersartfulevents.com/	https://www.instagram.com/peppersartfulevents/
Bean Counter Bakery	Cake	270 Grove Street	Worcester	Massachusetts		Worcester bakery with two shops making wedding cakes in textured, gold-banded and vintage styles, plus mini cupcakes for dessert tables.			https://www.beancounterbakery.com/	https://www.instagram.com/beancounterbakery/
On the Rise Baking	Cake	1120 Pleasant Street	Worcester	Massachusetts		Worcester bakery with over 30 years of custom wedding cakes, made with fresh, organic and local ingredients wherever possible.	info@ontherisebaking.com	508-752-3809	https://www.ontherisebaking.com/	https://www.instagram.com/ontherisebaking/
Erin Moynihan Films	Videography		Worcester	Massachusetts		Worcester videographer making documentary wedding films of real, unposed moments rather than staged scenes, and travelling well beyond New England.			https://erinmoynihanfilms.com/	https://www.instagram.com/erinmoynihanfilms/
BrightEyes Beauty Bar	Hair & Makeup	69 Milk St., Suite 208	Westborough	Massachusetts		Westborough beauty bar known for lash extensions, also doing event hair and makeup for brides and their wedding parties.	tiffany@brighteyesbeautybar.com	727-637-8824	https://www.brighteyesbeautybar.com/	https://www.instagram.com/brighteyes_beauty_bar/`,
  },
  {
    name: "Berkshires: photography, planning, florals, music, hair and makeup, catering and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Avida Love Photography	Photography		Great Barrington	Massachusetts	Massachusetts, Connecticut and New York	Berkshire-raised photographer Amy Whalan documents weddings and engagements with a calm presence and a fine-art eye.	amy@avidalove.com	(413) 238-6143	https://www.avidalove.com	https://www.instagram.com/avidalovephotography/
Sadie Elizabeth Photography	Photography		Williamstown	Massachusetts	Berkshire County	Documentary-inspired wedding and family photographer in Williamstown, focused on unscripted, honest moments.	sadie@sadieelizabethphotography.com		https://sadieelizabethphotography.com	
Christina Michelle Photo	Photography		Lenox	Massachusetts	The Berkshires	Candid, true-to-colour wedding and family photographer based in Lenox, working at venues around the Berkshires.			https://www.christinamichellephoto.com	https://www.instagram.com/christinamichellephoto/
Jillian J Events	Planning		Great Barrington	Massachusetts	Berkshires, New York and New England	Full-service wedding and event planner in Great Barrington, also working in the Hudson Valley and across New England.	jillian@jillianjevents.com	914-552-3811	https://jillianjevents.com	
Birdhouse Event Planning and Consulting	Planning	1130 East Rd	Richmond	Massachusetts	The Berkshires	Planner who acts as liaison and scheduler for weddings, elopements and venue consulting, drawing on local vendor contacts.	birdhouseeventsberkshires@gmail.com		https://www.birdhouseeventsberkshires.com	https://www.instagram.com/birdhouseevents/
Only In My Dreams Events	Planning		South Egremont	Massachusetts	The Berkshires	Event planning and staffing company serving weddings and other celebrations around the Berkshires from South Egremont.	info@onlyinmydreamsevents.com	(413) 528-0285	https://onlyinmydreamsevents.com	https://www.instagram.com/onlyinmydreamsevents/
Township Four Floristry & Home	Florals	30 Main Street	Stockbridge	Massachusetts	Berkshires	Floristry and home shop inside the Red Lion Inn creating bespoke wedding flowers from locally grown blooms.	flowers@townshipfour.com	(413) 347-3244	https://townshipfour.com	https://www.instagram.com/townshipfour/
Ruby Farm Florals	Florals	159 Alum Hill Road	Ashley Falls	Massachusetts	Berkshire County	Husband-and-wife flower farm and design team offering full-service wedding florals, with complimentary consultations, from a workshop in the Berkshire hills.	rubyfarmflorals@gmail.com	413-429-7214	https://www.rubyfarmflorals.com	https://www.instagram.com/rubyfarmflorals/
Lance Entertainment DJ Services	Music		Pittsfield	Massachusetts	Berkshire County	Pittsfield DJ and karaoke service offering music, MC services, and optional lighting or photo booths for weddings across Berkshire County since 2013.	info@lance-entertainment.com	413-441-1381	https://lance-entertainment.com	https://www.instagram.com/lanceentertainmentdj/
Daniela Pignatelli	Hair & Makeup	25 Maple St	Lenox	Massachusetts	Lenox studio	Private beauty studio offering bridal makeup, hair styling, updos and balayage colour, with consultations available in English and Spanish.	danielapignatelli.cos@gmail.com	+1 (617) 483-3539	https://danielapignatelli.com	https://www.instagram.com/danipignatellicos/
SoMa Catering	Catering	4 Albany Rd	West Stockbridge	Massachusetts	Berkshires, Connecticut, upstate New York	Farm-to-table wedding catering with seasonal custom menus, run from a West Stockbridge kitchen and serving the southern Berkshires.	Loretta@somacatering.com	413-232-0007	https://somacatering.com	https://www.instagram.com/somacatering/
KJ Nosh Catering	Catering	339 Tyler St	Pittsfield	Massachusetts	Berkshire County	Full-service Pittsfield caterer handling weddings, rehearsal dinners and bridal showers across Berkshire County.			https://kjnosh.com	https://www.instagram.com/kjnosh/
Berkshire Culinary Group	Catering		Dalton	Massachusetts	Berkshire County, 45-minute radius	Chef-led team offering buffets, plated multi-course dinners and raw bars for weddings, working from a Dalton kitchen.	berkshireculinarygroup@gmail.com	413-446-7319	https://berkshireculinarygroup.com	
Bounti-Fare Restaurant & Catering	Catering	200 Howland Ave	Adams	Massachusetts	Northern Berkshires	Adams restaurant that caters weddings on or off site, with packages that include a wedding coordinator and no cake-cutting fee.		413-743-0193	https://bountifare.com	`,
  },
  {
    name: "Worcester: photography, planning, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jenna Rose Photography	Photography	110 Elm St, Second Floor	Millbury	Massachusetts	Central Massachusetts, 60 miles of travel included	Millbury studio photographer telling wedding days as stories, with sixty miles of travel built into the wedding coverage price.	info@jennarosesarosi.com		https://jennarosesarosi.com	https://www.instagram.com/jennarosesarosi/
Caroline the Photographer	Photography		West Boylston	Massachusetts	Central Massachusetts and Cape Cod	West Boylston photographer with a classic, joyful style, shooting weddings, families and newborns across central Massachusetts since 2014.	hello@carolinethephotographer.co		https://carolinethephotographer.co	https://www.instagram.com/carolinethephotographer/
Heather Fuller Photography	Photography		Sturbridge	Massachusetts	New England, the East Coast and worldwide	Documentary-style wedding and engagement photographer based near Sturbridge, focused on candid, joyful moments rather than posed portraits.			https://www.heatherfullerphotography.com	https://www.instagram.com/heatherfullerphotography/
Weddings by TMW Productions	Planning		Worcester	Massachusetts	Worcester, Providence, Newport, Boston, Cape Cod and Hartford	Wedding planning from full service to day-of coordination, with elopement planning and rehearsal dinner coordination also on offer.	zacharyw@tmwproductions.biz	401-484-3291	https://weddingsbytmw.com	https://www.instagram.com/weddings.tmw/
Perro's Flowers	Florals	284 Grafton St	Worcester	Massachusetts	Worcester, Holden, Shrewsbury, Grafton, Millbury and nearby towns	Family-run Worcester florist, open since 1948, designing wedding and event flowers from hand-picked blooms and delivering locally.		(508) 755-7744	https://www.perrosflowers.com	https://www.instagram.com/perrosflowers/
Custom Sound DJ	Music	330 Water St	Fitchburg	Massachusetts	Central Massachusetts, Greater Boston, southern New Hampshire and Rhode Island	Fitchburg wedding DJ team with 25-plus years of experience, adding photo booths, uplighting and full event production.		855-599-7064	https://customsounddjs.com	
Firehouse Entertainment	Music		Worcester	Massachusetts	Worcester and surrounding area	Worcester DJ service for weddings and private parties, with customisable music packages and over twenty years of combined experience.	Jim@firehouse-Entertainment.net	508-479-8327	https://www.firehouse-entertainment.net	
Cordials Catering and Beverages	Catering	360 West Boylston St, #106	West Boylston	Massachusetts	Greater Worcester	Full-service caterer with bar service for weddings and other celebrations, working from a West Boylston base across greater Worcester.		+1 (508) 203-1969	https://cordialscaterandbevs.com	https://www.instagram.com/cordials106/
Creedon and Co.	Catering	39 Jolma Rd	Worcester	Massachusetts	Within an hour of Worcester, including Boston, Providence, Nashua and Springfield	Worcester caterer and rental company supplying wedding menus plus tents, tables, chairs and linens from a single team.		(508) 792-3100	https://www.creedonandco.com	
MCL Custom Caterers	Catering		Holden	Massachusetts	Worcester area, including Holden and Shrewsbury	Holden caterer building customised menus for weddings, corporate events and private celebrations in the Worcester area.			https://www.mclcustomcaterers.com	
Made by Mack	Hair & Makeup		Worcester	Massachusetts	New England	Mobile hair and makeup artist styling brides and wedding parties on location, from Worcester across New England.		(508) 656-0363	https://www.madebymackhmua.com	https://www.instagram.com/madebymackhmua/
Jade Silvestri Studio	Hair & Makeup	6 Brussels St, Suite 303	Worcester	Massachusetts	Massachusetts, Rhode Island and northeastern Connecticut	Worcester studio team travelling to bridal parties for formal updos and waterproof airbrush makeup across southern New England.	jadesilvestristudio@gmail.com	774-420-2228	http://www.jadesilvestristudio.com	https://www.instagram.com/jadesilvestristudio_bridal/
Christy & Co.	Hair & Makeup		Sturbridge	Massachusetts	Massachusetts, Connecticut and Rhode Island	Sturbridge bridal beauty team offering airbrush makeup and wedding hair design on location since 1997.			https://www.makeup-artistry.com	https://www.instagram.com/christyandcobridalbeauty/
Taste Great Cakes	Cake	98 Hamilton St	Worcester	Massachusetts		Family-run Worcester bakery making handcrafted custom cakes for weddings and celebrations, with a shop open by appointment.		508-579-1955	https://www.tastegreatcakes.com	https://www.instagram.com/tastegreatcakes/
`,
  },
  {
    name: "Boston: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Silver + Salt Photography	Photography		Boston	Massachusetts	Massachusetts and New England	Candid, photojournalistic wedding coverage shot on Leica cameras, designed to stay out of the way so guests can enjoy the day.	silverandsaltphoto@gmail.com	(617) 513-1634	https://www.silverandsaltphoto.com/	https://www.instagram.com/silverandsaltphoto/
Rebecca Cee Photography	Photography		Boston	Massachusetts	New England and beyond	Documentary and editorial wedding photographer working on both film and digital, with an intimate, cinematic feel to city and destination weddings.			https://rebeccacee.com/	https://www.instagram.com/rebeccaceephoto/
Nicki Bursae Photography	Photography		Boston	Massachusetts	Massachusetts, New England and worldwide	Documentary wedding and elopement photography with a cinematic edge, covering Boston celebrations as well as castle and beach destinations.	nicole.bursae@gmail.com	(843) 540-4057	https://www.nickibursaephotography.com/	https://www.instagram.com/nickibursae_photography/
Kayla Rice Photography	Photography		Boston	Massachusetts	Greater Boston, Massachusetts, New York and Vermont	Boston wedding photojournalist with an unposed, heartfelt approach, shooting full weddings across Massachusetts and neighbouring states.	kaylaricephoto@gmail.com	(802) 451-9071	https://kaylaricephotography.com/	https://www.instagram.com/kaylaricephoto/
Raise A Glass Weddings & Events	Planning		Danvers	Massachusetts	Boston's North Shore, Salem and Gloucester	Certified North Shore planner offering full planning and day-of management, including local oversight for couples organising from out of state.	rhonda@raiseaglassweddings.com	(351) 201-0481	https://raiseaglassweddings.com/	https://www.instagram.com/raiseaglassweddings/
Whim Events	Planning	24 Roland Street	Boston	Massachusetts	Boston, New England, the Hudson Valley and destinations	Planning, design and floral studio for down-to-earth couples who want a warm, nature-inspired celebration rooted in connection.	natalie@whimevents.com	(617) 413-9735	https://www.whimevents.com	https://www.instagram.com/whimevents/
Heather Dawn Events	Planning		Boston	Massachusetts	New England	Boutique full-service planning and design company building a cohesive look for timeless, modern weddings from first concept through to the day.			https://heatherdawnevents.com/	https://www.instagram.com/heatherdawnevents/
Elle Weddings & Events	Planning		Boston	Massachusetts	Massachusetts and New England	Planner offering full-service, partial and day-of coordination for modern, elegant weddings, with a collaborative and organised process.	info@elleweddingsandevents.com	(617) 233-4067	https://www.elleweddingsandevents.com/	https://www.instagram.com/elleweddingsandevents_/
Laura Jean Floral Design	Florals	270 Concord Avenue	Cambridge	Massachusetts	Boston, New England and beyond	Full-service floral studio known for modern-organic designs from local farms, with a focus on sustainability and donating flowers after events.	studio@ljfloral.com	617.299.0092	https://www.ljfloral.com/	https://www.instagram.com/laurajean_floral/
Table & Tulip	Florals	461 Shawmut Ave	Boston	Massachusetts	Greater Boston	Female-owned South End studio creating full wedding floral environments, plus an a la carte bridal menu of bouquets and centrepieces.	hello@tableandtulip.com		https://tableandtulip.com/	https://www.instagram.com/tableandtulip/
Hingham Greenery	Florals	39 South Street	Hingham	Massachusetts	Hingham, Cohasset, Hull, Norwell, Scituate and the South Shore	Long-running South Shore flower shop providing wedding and event flowers and delivering to local venues from Quincy to Marshfield.	hinghamgreenery@comcast.net	(781) 749-7363	https://hinghamgreenery.com/	
The SweetBeats	Music		Boston	Massachusetts	Massachusetts, New England and New York	Seven-piece party band with male and female vocalists and a live strings option, with MC duties included and one event booked per day.	thesweetbeatsband@gmail.com	617-838-3718	https://thesweetbeatsband.com/	https://www.instagram.com/thesweetbeatsband/
Kahootz Entertainment	Music		Boston	Massachusetts	Greater Boston and surrounding towns	Boston-based roster of six- to nine-piece bands and DJs, with ceremony music, lighting and photo booths available alongside the live acts.		(617) 297-8854	https://www.bostonsbestband.com/kahootz-2/	https://www.instagram.com/kahootzentertainment/
Fine Tune Entertainment	Music		Boston	Massachusetts	Greater Boston and Cape Cod	Wedding DJ and MC service covering ceremony, cocktails and reception, with wireless uplighting, monograms, photo booths and silent disco options.	finetunedj@gmail.com	(857) 244-0707	https://www.finetunedj.com/	https://www.instagram.com/finetunedj/
Nandee's Catering	Catering	990 Shirley Street	Winthrop	Massachusetts	Greater Boston and the North Shore	Family caterer where the owner-chef attends every event, supplying linens, china and waitstaff with homemade, generously portioned menus.	peter@nandeescatering.com	617-480-7020	https://nandees.com/	
Kate's Table	Catering	105 South Street	Hingham	Massachusetts	Hingham, Cohasset, Duxbury and Boston	Female-founded Hingham caterer creating bespoke menus for weddings and private events, cooking from its own commercial kitchen and composting scraps.	kelly@katestable.com	781-740-4111	https://www.katestable.com/	https://www.instagram.com/katestable/
Pauline's Catering and Staffing	Catering	40 Pond Street	Natick	Massachusetts	MetroWest	Natick caterer of more than twenty years handling weddings, with full bar service, staffing and menus adapted to any cuisine or diet.	Pauline@cateringandstaffing.com	1-508-320-0506	https://paulinesstaffingandcatering.com/	
Glamour Cosmetics	Hair & Makeup	1844B Mass Ave	Lexington	Massachusetts	Boston, Cape Cod, Newport	Bridal makeup team led by Garineh Ashjian that pairs each client with a matched artist for a soft, glowy look.			https://glamourcosmeticsofficial.com/	https://www.instagram.com/glamourcosmeticsofficial/
Blush	Hair & Makeup	29 Main Street	Hingham	Massachusetts		On-site bridal and event makeup team in Hingham that travels to the venue and aims to bring out each bride's natural features.		(781) 740-2228	https://blushweddingday.com/	
Katrina Hess Makeup Studio	Hair & Makeup		Boston	Massachusetts		Back Bay makeup studio on Newbury Street offering bridal makeup and brow shaping, with the artist travelling to wedding-day venues.	katrina@katrinahess.com	781-710-6865	https://katrinahess.com/	https://www.instagram.com/katrinahessmakeup/
Jenny Luu Hair + Makeup	Hair & Makeup		Milton	Massachusetts	Boston, Cape Cod, Rhode Island	Soft-glam bridal hair and makeup from a single artist with 18 years behind the brush, plus editorial and branding work.	jenny@jcluu.com		https://jcluu.com/	https://www.instagram.com/_jennyluu/
The Icing on the Cake	Cake	230 Adams Street	Newton	Massachusetts		Newton bakery making custom wedding and celebration cakes and cupcakes in a range of sizes, designs and price points for over 40 years.	cake@tiotc.net	617-969-1830	https://www.theicingonthecake.com/	https://www.instagram.com/tiotcma/
Silver Whisk Bake Shop	Cake	248 Moody St	Waltham	Massachusetts		Waltham bake shop and chocolatier making designer wedding cakes and cupcakes alongside a retail counter and handmade chocolates.	hello@silverwhiskbakeshop.com		https://silverwhiskbakeshop.com/	https://www.instagram.com/silverwhiskbakeshop/
Cake Monstah	Cake		Weymouth	Massachusetts		Weymouth cake studio creating hand-crafted modern luxury wedding cakes and sculpted custom designs by a Johnson & Wales-trained baker.			https://www.cakemonstah.com/	https://www.instagram.com/cake.monstah/
Pirates Lane Video	Videography		Gloucester	Massachusetts	New England	Gloucester wedding videographers blending documentary and cinematic styles, filming in 4K since 2010 across New England.	jim@pirateslane.com		https://pirateslanevideo.com/	https://www.instagram.com/PiratesLaneVideo/
Lovely Valentine	Videography	343 Medford St	Somerville	Massachusetts	Boston, Newport and destinations	Somerville studio filming cinematic weddings alongside photography under one creative direction, with all editing done in-house.	info@lovelyvalentine.com	617-575-9693	https://lovelyvalentine.com/	https://www.instagram.com/lovelyvalentine/
Nedd Media	Videography		Cambridge	Massachusetts		Cambridge boutique filmmaker shooting cinematic wedding films on 4K cinema cameras with a storytelling approach and one-on-one service.			https://neddmedia.com/	https://www.instagram.com/neddmedia/
`,
  },
  {
    name: "Worcester: planning and florals",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
City Cut Flowers	Florals		Worcester	Massachusetts		Worcester florist and floral design studio offering wedding packages and arrangements, now booking the 2026 and 2027 seasons.	citycutflowers@gmail.com	774-312-5258	https://citycutflowers.com/	https://www.instagram.com/citycutflowers/
`,
  },
  {
    name: "Cape Cod: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Cape Cod Wedding Planning	Planning		Brewster	Massachusetts	Cape Cod and beyond	Local planner offering full, partial and day-of coordination, with close ties to Cape venues and a knack for guiding out-of-town couples.	alexavictoria@capecodweddingplanning.com		https://capecodweddingplanning.com/	https://www.instagram.com/capecodweddingplanning/
Garden Party Cape Cod	Florals		South Yarmouth	Massachusetts	Harwich, Dennis, Chatham, Brewster, Orleans and the wider Cape	Boutique floral studio taking one wedding per weekend, favouring bold, locally grown seasonal blooms over the usual coastal palette.	info@gardenpartycapecod.com		https://www.gardenpartycapecod.com/	https://www.instagram.com/gardenpartycapecod/
American Stems	Florals		Harwich Port	Massachusetts	Cape Cod, Nantucket, Boston and Newport	Wedding floral design studio known for artful, playful arrangements, working across the Cape and out to Nantucket and Newport.	kelsey@americanstemsfd.com		https://americanstems.com/	https://www.instagram.com/americanstems/
Cape Cod String Quartet	Music		Barnstable	Massachusetts	Cape Cod, Martha's Vineyard, Nantucket, Greater Boston and Rhode Island	Chamber ensemble playing ceremony and cocktail-hour music for weddings, with a repertoire running from classical to modern arrangements.	capecodstringquartet@gmail.com	774-413-0079	https://www.capecodstringquartet.com/	https://www.instagram.com/capecodstringquartet/
Cape Cod Private Dinners	Catering		Orleans	Massachusetts	Cape Cod	Boutique caterer and private chef service making scratch-cooked menus from mostly local ingredients for small, intimate Cape weddings.		508-246-4967	https://capecodprivatedinners.com/	https://www.instagram.com/capecodprivatedinners/
Harborview Studios	Videography		Centerville	Massachusetts	Cape Cod, Nantucket, Martha's Vineyard and New England	Husband-and-wife filmmakers making quiet, cinematic wedding films with a natural storytelling approach across the Cape and Islands.			https://www.harborviewstudios.com/	https://www.instagram.com/harborviewstudios/
`,
  },
  {
    name: "Martha's Vineyard and Nantucket: photography, planning, florals and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Zofia & Co. Photography	Photography		Nantucket	Massachusetts	Nantucket	Island studio photographing Nantucket weddings and portraits since 2005, with an emotive, documentary feel and deep knowledge of local venues.	zofia@zofiaphoto.com		https://zofiaphoto.com/	https://www.instagram.com/zofiaphoto/
Mila Lowe Photography	Photography		West Tisbury	Massachusetts	Martha's Vineyard	Island photographer covering weddings, elopements, engagements and proposals on Martha's Vineyard with a relaxed, natural approach.	info@milalowe.com	508-560-6312	https://www.milalowe.com/	https://www.instagram.com/mila.lowe/
David Welch Photography	Photography		Vineyard Haven	Massachusetts	Martha's Vineyard, New England and beyond	Vineyard Haven studio photographing weddings, elopements and family portraits, with drone photography and video also on offer.		508-939-3438	https://www.davidwelchphotography.com/	https://www.instagram.com/dwpmv/
Plan It Martha's Vineyard + Nantucket	Planning		Edgartown	Massachusetts	Martha's Vineyard and Nantucket	Edgartown planning and design firm for destination weddings on both islands, from full planning to month-of coordination.	events@planitmv.com	774-549-9406	https://planitmv.com/	https://www.instagram.com/planitmarthasvineyard/
Immaculate Reception ACK	Planning		Nantucket	Massachusetts	Nantucket	Nantucket coordinator who has planned island weddings and events since 1994, with long-standing relationships among local venues and suppliers.	jimjak@comcast.net	508-221-2239	https://immaculatereceptionack.com/	
Donaroma's	Florals		Edgartown	Massachusetts	Martha's Vineyard	Family-run nursery, landscape and floral business offering wedding bouquets, ceremony pieces and event flowers across the island.		508-627-3036	https://donaromas.com/	https://www.instagram.com/donaromasmv/
Morrice Florist	Florals	149 State Rd	Vineyard Haven	Massachusetts	Martha's Vineyard	Island florist creating simple, classic wedding flowers with a loose, wildflower feel, from bouquets to ceremony and reception pieces.	studio@morriceflorist.com	508-693-0392	https://morriceflorist.com/	https://www.instagram.com/morriceflorist/
PPX Events	Catering	7 South Water Street	Nantucket	Massachusetts	Nantucket	Boutique Nantucket planning and catering studio with an in-house patisserie, offering seasonal menus and delivery for weddings and events.		508-332-8054	https://ppxevents.com/	https://www.instagram.com/ppxevents/
`,
  },
  {
    name: "Boston: music, florals, planning, videography, cake and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Brick Park	Music		Boston	Massachusetts		Boston wedding band offering customisable, all-inclusive packages built around a dedicated lineup, with video and audio samples to preview.	contact@brickpark.com		https://www.brickparkent.com/	https://www.instagram.com/brickparkband/
Epic Entertainment Boston	Music	20 Blackman Rd	Canton	Massachusetts	Greater Boston	Wedding DJ company offering full or a la carte packages, with photo booths, uplighting and event lighting available alongside the music.	info@epicentertainmentboston.com	781-267-3443	https://epicentertainmentboston.com/	https://www.instagram.com/epicentboston/
Amuse Floral Co.	Florals		Milford	Massachusetts	New England	Private floral studio designing wedding, elopement and event florals, with full-service packages including rentals and on-site setup, by appointment.			https://www.amusefloralco.com/	https://www.instagram.com/amusefloralco/
Stone Event Planning	Planning		Boston	Massachusetts	Boston, New England and beyond	Boston planning and creative-direction firm with around twenty years of luxury wedding and event experience, working in partnership with couples.	gabriellestone@stoneeventplanning.com	617-470-1946	https://www.stoneeventplanning.com/	https://www.instagram.com/stoneeventplanning/
Shiang Studios	Videography		Boston	Massachusetts	Boston and Newport	Boston videographer making unhurried, story-led wedding films with a sense of pacing drawn from his classical music background.	hello@shiangstudios.com	857.293.0985	https://www.shiangstudios.com/	https://www.instagram.com/shiangstudios/
Bright Spot Films	Videography		Boston	Massachusetts	Greater Boston, Cape Cod and across New England	Cinematic, story-driven wedding films that weave vows and toasts into the finished edit, shot across Greater Boston, the Cape and New England.	Brightspotfilm@gmail.com	508-733-4076	https://www.brightspotfilms.com/	https://www.instagram.com/brightspotfilms/
Path Wedding Films	Videography		Boston	Massachusetts	Boston, New England and Cape Cod	Documentary-minded wedding videographers who film real, unposed moments for couples across Boston, New England and Cape Cod.	pat@pathweddings.com	617.829.3887	https://www.pathweddings.com/	https://www.instagram.com/pathweddings/
Sound Choice Events	Music		Natick	Massachusetts	Greater Boston and New England	Natick DJ company offering wedding DJs, lighting, photo booths and video, also covering Bar and Bat Mitzvahs and other events.	Info@soundchoiceevents.com	617-909-4700	https://www.soundchoiceevents.com/	
Boston Latin DJs	Music		Boston	Massachusetts	Boston, Cambridge, Worcester and wider New England	Bilingual English and Spanish DJs and MCs for Latin American weddings and quinceañeras, mixing salsa, bachata, merengue and reggaeton.	contact@bostonlatindjs.biz	617.905.4515	https://bostonlatindjs.biz/	https://www.instagram.com/bostonlatindjs/
DJ KYD & Co.	Music		Boston	Massachusetts	Boston and New England	Bilingual DJ and MC team for multicultural weddings, blending Latin, Afrobeats, soca and open-format sets into one tailored night.	info@djkyd.com	617-800-9573	https://www.djkyd.com/	https://www.instagram.com/djkyd617/
Cake Dolls	Cake		Framingham	Massachusetts	Massachusetts, Rhode Island, New Hampshire, Connecticut and Maine	Framingham cake studio, open by appointment, creating custom wedding cakes, dessert tables and sweet favours for weddings across New England.	info@cakedolls.com	(617) 802 9091	https://www.cakedolls.com/	https://www.instagram.com/bycakedolls/
Min-Ah Campos Makeup + Hair	Hair & Makeup		Boston	Massachusetts	Boston, Rhode Island and New England	Korean-trained Boston bridal makeup and hair artist with two decades of experience, working on location for weddings across New England.	minisha50@icloud.com	508-617-7122	https://www.minahcampos.com/	https://www.instagram.com/makeup_by_minah/
Fei Xu Beauty Studio	Hair & Makeup		Boston	Massachusetts	Boston	Boston bridal hair and makeup studio founded to serve Asian and multicultural brides, with a team of artists for wedding parties.			https://www.fei-xu.com/	
`,
  },
  {
    name: "Worcester: hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Leti Silva Beauty	Hair & Makeup		Westborough	Massachusetts	Boston, Worcester, Central Massachusetts and New England	Westborough bridal makeup artist and licensed esthetician who travels on location, with brow and lash services at her studio.			https://letisilvabeauty.com/	https://www.instagram.com/letisilvabeauty/
`,
  },
  {
    name: "Cape Cod: photography, planning, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Falcon Visuals	Videography		Cape Cod	Massachusetts	Cape Cod and the Islands, including Chatham, Falmouth and Truro	Cape-based videographers offering tiered wedding film packages, from ceremony-only coverage to two-camera days with highlight reels and documentary edits.			https://falconvis.com/	https://www.instagram.com/falconvis/
Accent	Music		Cape Cod	Massachusetts	Cape Cod	Full-time Cape Cod party band that also offers a DJ option, playing wedding receptions and events across the Cape.			https://www.musiccapecod.com/	
Salon 700 & Day Spa	Hair & Makeup	700 Main Street	Hyannis	Massachusetts	Cape Cod, with travel to the islands by arrangement	Hyannis salon and spa with bridal packages, in-salon previews and a private bridal suite, plus on-location artists for Cape and island weddings.	info@salon700.com	(508) 957-2509	https://www.salon700.com/	
Wingate's Cake Design	Cake	434 American Legion Highway	Westport	Massachusetts	South Coast, Cape Cod to Providence, with delivery to Nantucket and Martha's Vineyard	Boutique Westport studio making custom wedding cakes, large-event desserts and French macarons, delivered and set up at the venue.	wingatescakes@gmail.com	774 309 3223	https://www.wingatescakes.com/	https://www.instagram.com/wingatescakedesign/
Brenda's Cakes For All Occasions	Cake		Harwich	Massachusetts	Cape Cod	Harwich kitchen baking wedding cakes in styles from fresh-flower and beach themes to cupcake and groom's cakes, plus favours and dessert buffets.	brendascakesforalloccasions@gmail.com	774-209-9095	https://www.brendascakesforalloccasions.com/	https://www.instagram.com/brendascakesforalloccasions/
The Chocolate Rose	Cake	628 Main St, Suite A	Mashpee	Massachusetts	Cape Cod	Boutique Mashpee bakery offering tiered wedding cakes, signature dessert tables and petite pastries, with tastings for larger custom orders.	info@chocolaterosecakes.com	774.238.7020	https://www.chocolaterosecakes.com/	https://www.instagram.com/chocolaterosecakes/
Aundria's Kitchen	Cake		Falmouth	Massachusetts	Cape Cod and the Islands	Falmouth cottage bakery making custom wedding cakes and dessert-table treats by appointment for couples across the Cape and islands.		774-521-4134	https://www.aundriaskitchen.com/	
Treats Catering	Catering	25 Scarsdale Road	Dennis	Massachusetts	Provincetown to Woods Hole	Dennis caterer with a long Cape Cod track record, serving wedding receptions and working as a preferred caterer for several local venues.	Celebrate@treatscatering.com	(508) 385-6571	https://www.treats-catering.com/	
Deering Events	Planning		South Yarmouth	Massachusetts	Cape Cod; Boston; North Carolina	Planner offering partial planning and day-of coordination for Cape Cod weddings, with additional offices in Boston and North Carolina.	jyl@deeringevents.com	774-243-2940	https://deeringevents.com/	https://www.instagram.com/jyldeering/
Alex Paul Photography	Photography		Harwich	Massachusetts	Cape Cod; also Boston and Rhode Island	Harwich photographer shooting weddings year-round at Cape Cod venues and private estates, with some Boston and Newport commissions.	alexpaulphoto@gmail.com	508 723 50 38	https://www.alexpaulphotography.com/	https://www.instagram.com/alexpaulphotography/
Meghan Lynch Photography	Photography		Cape Cod	Massachusetts	New England and New York, with Cape Cod weddings featured	Wedding photographer whose Cape Cod galleries cover Pelham House Resort, Chatham Bars Inn and Wequassett, working across New England.			https://meghanlynchphotography.com/	https://www.instagram.com/meghanlynchphotography/
`,
  },
  {
    name: "Martha's Vineyard and Nantucket: music, videography, hair and makeup, cake, catering, florals and planning",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Yellow Productions	Videography		Nantucket	Massachusetts	Nantucket	Nantucket-based filmmakers producing cinematic wedding films for island couples, with a team that lives and works on the island year-round.	info@yellowproductions.com		https://www.yellowproductions.com/	https://www.instagram.com/yellowproductions/
Luke DiOrio	Videography		Martha's Vineyard	Massachusetts	West Tisbury, Edgartown, Chilmark, Aquinnah, Menemsha and nearby coastal towns	Island filmmaker and photographer offering documentary-style wedding films, elopements and intimate celebrations across Martha's Vineyard's up-island and coastal venues.			https://www.lukediorio.com/	https://www.instagram.com/luke_diorio_photography/
DJ Smooth B	Music		Vineyard Haven	Massachusetts	Martha's Vineyard and beyond	Year-round island DJ with over two decades of experience, playing weddings and private events on Martha's Vineyard and further afield.	sterlingbishop75@gmail.com	(617) 828-9075	https://djsmoothbmv.com/	
Vineyard Spin	Music		Martha's Vineyard	Massachusetts	Martha's Vineyard	Island wedding DJ playing since 2017 at venues such as Atria, Lambert's Cove Inn and the Beach Plum Inn, as well as private residences.			https://www.vineyardspin.com/	https://www.instagram.com/dj_dern/
The Vine Shakers	Music		Martha's Vineyard	Massachusetts	Martha's Vineyard	Island-based live band performing for wedding receptions and parties, with testimonials from couples who danced the night away on the Vineyard.			https://thevineshakers.com/	https://www.instagram.com/thevineshakers/
Nantucket DJ Productions	Music		Nantucket	Massachusetts	Nantucket	Island DJ service that specialises in weddings and offers entertainment and event support for couples marrying on Nantucket.	nantucketdj@hotmail.com	413.531.9637	https://www.nantucketdjproductions.com/	
Sea Spa Salon	Hair & Makeup		Edgartown	Massachusetts	Martha's Vineyard (on-location across the island)	Edgartown salon whose team travels to island venues to style hair and apply makeup for the whole wedding party on the day.		(508) 627-8953	https://www.seaspasalonmv.com/	https://www.instagram.com/seaspasalon/
RJ Miller Salon & Spa	Hair & Makeup	6 Amelia Drive	Nantucket	Massachusetts	Nantucket	Long-running Nantucket salon offering bridal hair and makeup trials and wedding-day styling for brides, attendants and flower girls.	rjmillersalon@gmail.com	508.228.3446	https://rjmillersalons.com/	
Sweet Bites	Cake	32 Beach Street	Vineyard Haven	Massachusetts	Martha's Vineyard	Brazilian bakery and café in Vineyard Haven that makes cakes for island weddings and events alongside its everyday pastries.			https://sweetbitesmv.com/	https://www.instagram.com/sweetbitesmv/
Bill Smith's Martha's Vineyard Clambake Co.	Catering	10 North Line Road, Unit 3	Edgartown	Massachusetts	Martha's Vineyard	Edgartown clambake caterer offering a full-service wedding option for parties of 30 up to 3,000 guests anywhere on the island.		508-627-8809	https://www.mvclambake.com/	
Morning Glory Farm	Florals	120 Meshacket Rd.	Edgartown	Massachusetts	Martha's Vineyard	Family farm in Edgartown offering full-service wedding floral design with centrepieces and bouquets, or seasonal blooms for couples to arrange themselves.		(508) 627-9003	https://www.morninggloryfarm.com/	https://www.instagram.com/morninggloryfarmmv/
`,
  },
  {
    name: "Boston: Catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Calla Catering and Events	Catering	179 W. Central St, Suite 2	Natick	Massachusetts	Massachusetts and southern New Hampshire	Full-service wedding caterer run by a chef and a wedding planner, with private tastings of the real menu and clear pricing.	melanie@callacatering.com	(781) 774-9735	https://www.callacatering.com	https://www.instagram.com/calla.catering/
MAX Ultimate Food	Catering	65 East Cottage Street	Dorchester	Massachusetts	Rhode Island to Maine	Dorchester caterer for weddings of any style, from small dinners to large celebrations, handling planning details alongside the menu.	info@maxultimatefood.com	(617) 427-9799	https://www.maxultimatefood.com	https://www.instagram.com/maxultimatefood/
`,
  },
  {
    name: "Martha's Vineyard and Nantucket: Hair & Makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Vineyard Makeup Artist	Hair & Makeup		Edgartown	Massachusetts	Martha's Vineyard	Edgartown makeup artist who travels to your chosen island location to do the bride, bridal party and family.	bufteanicoleta@yahoo.com	508-627-0548	https://www.vineyardmakeupartist.com/weddings	
`,
  },
  {
    name: "Worcester: Videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
New England Wedding Film	Videography		Worcester	Massachusetts	Massachusetts and New England	Worcester studio making cinematic wedding films and photography across New England, from the Berkshires to Cape Cod and Newport.	info@newenglandweddingfilm.com	(774) 385-0793	https://www.newenglandweddingfilm.com/	https://www.instagram.com/newenglandweddingfilm/
`,
  },
];

export default batches;
