import type { VendorBatch } from "@/lib/vendor-batches";

// Michigan vendor batches. Every row's State is "Michigan". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Detroit: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kari Dawson + Co	Photography		Detroit	Michigan	Detroit, Metro Detroit, Ann Arbor, Grand Rapids and Northern Michigan	Mother-daughter photography duo capturing light-filled, emotionally driven wedding images across Michigan and beyond.	kari@karidawson.com		https://karidawson.com/	https://www.instagram.com/karidawsonphoto/
MyPic Photography	Photography		Lake Orion	Michigan	Metro Detroit and Southeast Michigan	Family-run Lake Orion studio photographing Metro Detroit weddings since 2008, sending two photographers to each wedding.			https://mypicphotography.com/	https://www.instagram.com/mypicphotography1/
Rosy & Shaun Wedding Photography	Photography	440 Burroughs St	Detroit	Michigan	Metro Detroit, Ann Arbor, Northern Michigan, Florida and destination weddings	Husband-and-wife team who both shoot every wedding, with a candid style and experience photographing South Asian weddings.	hello@rosyandshaun.com		https://rosyandshaun.com/	https://www.instagram.com/rosyandshaun/
Derek Cookson Photography	Photography		Detroit	Michigan	Detroit based, serving USA, Canada and worldwide	Detroit photographer and filmmaker covering weddings, engagements and portraits with a relaxed, personality-led approach.			https://www.dcooksonphoto.com/	https://www.instagram.com/thederek23/
You're The Bride	Planning		Farmington	Michigan	Metro Detroit, including Oakland, Wayne, Macomb and Washtenaw Counties	Certified planner offering full planning through day-of management, experienced with cultural and multi-family weddings.		(248) 408-4602	https://yourethebride.com/	https://www.instagram.com/yourethebride/
J.Britt & Company Events and Designs	Planning		Detroit	Michigan	Michigan and beyond	Detroit planning studio offering full planning and day-of coordination plus its own décor and balloon design for weddings.	info@jbrittandco.com	586-872-5632	https://www.jbrittandco.com/	https://www.instagram.com/jbrittandco/
Christian Lei Events	Planning		Detroit	Michigan	Birmingham, Royal Oak, Ferndale, Bloomfield Hills, Rochester and Troy	Detroit planner led by a certified wedding designer, offering full planning, day-of coordination and destination weddings.	Events@ChristianLeiEvents.com		https://www.christianleievents.com/	https://www.instagram.com/christianleievents/
All Grand Events + Floral	Planning	2233 W Grand River Ave	Okemos	Michigan	Traverse City to Grand Rapids to Metro Detroit	Okemos studio pairing full-service wedding planning with in-house floral and event design for couples across Michigan.			https://allgrandevents.com/	https://www.instagram.com/allgrandeventsfloral/
Betsy & Bobbie	Florals		Detroit	Michigan	Metro Detroit, Michigan and beyond	Woman-owned, eco-conscious floral studio designing bespoke wedding flowers inspired by art, interiors, fashion and travel.	hello@betsyandbobbie.com		https://www.betsyandbobbie.com/	https://www.instagram.com/betsyandbobbie/
Blumz by JRDesigns	Florals	522 E. Nine Mile Rd	Ferndale	Michigan		Ferndale florist with a second shop in Holly, offering wedding flowers alongside specialty linens, rentals and invitations.		(248) 398-5130	https://blumz.com/weddings	https://www.instagram.com/blumzbyjrdesigns/
Emerald City Designs	Florals	24590 N. Industrial Drive	Farmington Hills	Michigan		Farmington Hills studio combining wedding florals with planning, stationery and a 16,000 sq ft rental inventory.		248-474-7077	https://emeraldcitydesigns.com/	https://www.instagram.com/emeraldcitydesigns/
The Flower Kitten	Florals		Clinton Township	Michigan	Metro Detroit, Southwest Michigan, Lower Michigan	Clinton Township florist creating natural, abundant wedding designs that favour Michigan-grown flowers and foliage in summer.			https://www.theflowerkitten.com/	https://www.instagram.com/theflowerkitten/
Rondo String Quartet	Music		Detroit	Michigan	Southeast Michigan and the Detroit Metro Area	Settled four-player string quartet for ceremonies and receptions, playing classical, rock, jazz standards and Bollywood.	rondostrings@hotmail.com	248-650-0325	https://www.rondostringquartet.com/	https://www.instagram.com/RondoStringQuartet/
Sugar Events & Entertainment	Music		Detroit	Michigan	Detroit-based, worldwide	Detroit entertainment company specialising in South Asian weddings, with DJs, MCs and lighting for sangeet, baraat and reception.	info@sugareventsent.com	248-679-2443	https://www.sugareventsent.com/	https://www.instagram.com/sugareventsent/
Elite Wedding Co.	Music	14061 13 Mile Road #4	Warren	Michigan		Warren company with a showroom, providing wedding DJs alongside photography, videography, photo booths and accent lighting.	YourTeam@EliteWeddingCo.com	586-415-4800	https://www.weddingsbyelite.com/	https://www.instagram.com/eliteweddingco/
Brooks & Landry Fine Catering	Catering	4936 Allen Rd	Allen Park	Michigan	Detroit, Ann Arbor, Novi, Troy, Grosse Pointe, Port Huron, Flint, Toledo and nearby communities	Chef-owned Allen Park caterer cooking from scratch with local ingredients for weddings at Detroit-area venues.	events@brooksandlandry.com	248-761-1844	https://www.brooksandlandry.com/	https://www.instagram.com/brooksandlandrycatering/
Forte Belanger	Catering	700 Stephenson Highway	Troy	Michigan		Troy caterer and event producer with three decades of weddings behind it and a CATIE award for event production.		248-602-4500	https://www.fortebelanger.com/	https://www.instagram.com/fortebelanger/
Skosh Catering	Catering	126 Ferland St	Walled Lake	Michigan	Oakland, Wayne, Livingston, Washtenaw, Macomb and St. Clair counties	Husband-and-wife boutique off-site caterer in Walled Lake, building personalised wedding menus around each couple.	info@skoshcatering.com	248-313-9245	https://www.skoshcatering.com/	https://www.instagram.com/skoshcatering/
Detroit Catering Company	Catering		Detroit	Michigan	Metro Detroit	Detroit caterer preparing customised wedding menus with local partners, with care taken over dietary needs and requests.	Info@DetroitCateringCompany.com	734-730-7570	https://detroitcateringcompany.com/	https://www.instagram.com/DetroitCateringCompany/
Kathleen Berg Beauty	Hair & Makeup		Detroit	Michigan	Metro Detroit and beyond	All-women team providing on-location bridal soft glam makeup and timeless hairstyles, with virtual or in-person previews.		313-462-9386	https://kathleenbergbeauty.com/	https://www.instagram.com/kathleenbergbeauty/
Gals & Ghouls	Hair & Makeup	2633 South Lapeer Road	Lake Orion	Michigan	All of Michigan and beyond	LGBTQ+ friendly on-location wedding hair and makeup team in Lake Orion, also skilled in special effects and film makeup.	galsandghouls@gmail.com	248-602-3346	https://www.galsandghouls.com/	https://www.instagram.com/galsandghouls/
Tiffany Elie Makeup Artistry and Associates	Hair & Makeup		Huntington Woods	Michigan	Metro Detroit	Huntington Woods makeup artist with over 20 years' experience and a team of associates, using long-wearing waterproof HD makeup.			https://tiffanyeliemakeup.com/	https://www.instagram.com/tiffanyelie_makeupartistry/
Sorellas Cake Studio & Bakery	Cake	31236 Five Mile Road	Livonia	Michigan		Livonia bakery run by sisters Bertha and Monica, making wedding cakes with buttercream and fillings made from scratch.	hello@cakesistersdetroit.com	734-525-5544	https://sorellascakestudio.com/	https://www.instagram.com/sorellascakestudio/
The Home Bakery	Cake	300 South Main Street	Rochester	Michigan		Downtown Rochester bakery known for modern wedding cakes in buttercream and homemade fondant, with mock-up consultations.		(248) 651-4830	https://thehomebakery.com/pages/weddings	https://www.instagram.com/homebakeryroch/
Sweet Heather Anne Cake Studio	Cake	2449 West Stadium Boulevard	Ann Arbor	Michigan	Ann Arbor, Michigan and beyond	Ann Arbor cake studio founded by an art graduate, creating artistic wedding cakes from local, high-quality ingredients.	info@sweetheatheranne.com	734-361-1682	https://www.sweetheatheranne.com/	https://www.instagram.com/sweetheatheranne/
Petite Sweets Detroit	Cake		Detroit	Michigan		Dessert caterer and micro bakery led by a former hotel pastry chef, baking wedding cakes and dessert tables to order.	info@petitesweetsdetroit.com	248-797-5782	https://www.petitesweetsdetroit.com/	https://www.instagram.com/petitesweetsdetroit/
New Signature Films	Videography	2820 W Maple Rd, Ste 234	Troy	Michigan	Michigan and beyond	Troy-based team of filmmakers making cinematic wedding films built on intentional storytelling and real emotion.	info@newsignaturefilms.com	248-416-7700	https://newsignaturefilms.com/	https://www.instagram.com/newsignaturefilms/
Mike Staff Productions	Videography	55 E. Long Lake Rd., Ste. 306	Troy	Michigan	Metro Detroit	Troy wedding company running since 1996, pairing videography with DJ and photography and letting couples choose crew by name.		248-689-0777	https://mikestaff.com/services/wedding-videographer/	https://www.instagram.com/mikestaffproductions/
Jaymes Media	Videography		Plymouth	Michigan	All of Michigan, plus Chicago, Orlando and destination weddings	Plymouth studio making documentary-style wedding films with professional colour grading, drone footage and custom sound design.	hello@jaymesmedia.com	734-719-8883	https://jaymesmedia.com/	https://www.instagram.com/jaymesmedia/`,
  },
  {
    name: "Grand Rapids: photography, planning and florals",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Studio Grand Rapids	Photography		Grand Rapids	Michigan	Chicago, Detroit Metro, Grand Rapids, South Bend and Traverse City	LGBTQIA+ and BIPOC-inclusive wedding photographer working in true-colour, loosely editorial images shot in honest natural light.	studiograndrapids@gmail.com	616-466-0993	https://www.studiograndrapids.com/	https://www.instagram.com/studiograndrapids/
Taylor J. Photography	Photography		Grand Rapids	Michigan	West Michigan, Petoskey, Traverse City, Detroit and Ludington	Grand Rapids photographer capturing weddings and families in a natural, documentary style with vibrant, true-to-life colour.	hello@taylorjphotography.co		https://www.taylorjphotography.co/	https://www.instagram.com/taylorjphotog/
Kelly Sweet Photography	Photography		Grand Rapids	Michigan	Grand Rapids, Detroit, Northern Michigan and destinations worldwide	Film and film-inspired digital wedding photography with a soft, airy, true-to-colour look, drawing on over 20 years behind the camera.	kelly@kellysweet.com		https://www.kellysweet.com/	https://www.instagram.com/kellysweetphoto/
Liv Lyszyk Photography	Photography		Grand Rapids	Michigan	Grand Rapids and beyond	LGBTQ+ focused wedding and portrait photographer with an earthy, romantic style built around genuine moments and inclusive values.	livlyszykphoto@gmail.com		https://livlyszyk.com/	https://www.instagram.com/livlyszykphotography/
In the Details Weddings	Planning		Grand Rapids	Michigan	Michigan and destinations nationwide	Grand Rapids team offering full wedding planning and day-of coordination, focused on detail work that keeps couples present on the day.	inthedetailsweddingplanning@gmail.com	248-880-0880	https://inthedetailsweddings.com/	https://www.instagram.com/inthedetailsweddings/
The Best Day Details	Planning	77 Monroe Center St NW Suite 600	Grand Rapids	Michigan	Grand Rapids, Detroit, Holland, Traverse City and Southwest Michigan	Day-of wedding coordination company with a large team of lead coordinators, plus management and set-up-only packages across Michigan.	info@thebestdaydetails.com	616-558-9144	https://thebestdaydetails.com/	https://www.instagram.com/thebestdaydetails/
Dearly Beloved Wedding Planning	Planning		Grand Rapids	Michigan	Michigan, including Detroit, Traverse City, Holland and South Haven, and Chicago	Grand Rapids planner offering full-weekend, full, partial and day-of planning for weddings across Michigan and in Chicago.	dearlybelovedweddingplanning@gmail.com		https://dearlybelovedweddingplanning.com/	https://www.instagram.com/dearlybelovedweddingplanning/
Forever & Always Event Planning	Planning		Grand Rapids	Michigan	Grand Rapids, Kalamazoo and surrounding areas in Southwest Michigan	Wedding management and coordination that starts 90 days out, with a client portal, custom timeline and decor rentals.			https://foreverandalwaysplan.com/	https://www.instagram.com/foreverandalwayseventplanning/
Ball Park Floral & Gifts	Florals	8 Valley Ave NW	Grand Rapids	Michigan		Family-owned West Side flower shop designing since 1904, offering wedding consultations, bouquets, ceremony pieces and on-site set-up.		616-459-3409	https://www.ballparkfloral.com/	https://www.instagram.com/ballparkfloral/
She Is GR Co.	Florals		Grand Rapids	Michigan	West Michigan	Small West Michigan floral studio growing its own seasonal blooms, known for interactive flower bars alongside full wedding florals.	info@sheisgr.com	616-405-7286	https://www.sheisgr.com/	https://www.instagram.com/sheisgrco/
Modern Day Events and Floral	Florals	555 76th St Suite B	Byron Center	Michigan	West Michigan and destinations nationwide	Twenty-year-old studio combining wedding florals with planning, design, rentals and custom invitations under one roof.	events@moderndayfloral.com		https://events.moderndaycollective.com/	https://www.instagram.com/moderndaycollective/
Pinna Co Floral Design	Florals		Ada	Michigan	Grand Rapids, Ada, Holland, Kalamazoo, Lansing, Detroit, Traverse City and destinations throughout Michigan	Garden-inspired wedding florist in Ada offering full-service designs or a lower-cost studio pickup collection for smaller budgets.	info@pinna-co.com	616-217-9881	https://pinna-co.com/	https://www.instagram.com/pinnacoflowers/`,
  },
];

export default batches;
