import type { VendorBatch } from "@/lib/vendor-batches";

// Mississippi vendor batches. Every row's State is "Mississippi". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Jackson: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Shelby Mullins Photography	Photography		Jackson	Mississippi	Jackson, MS and destination weddings	Jackson wedding and portrait photographer with a classic, timeless style, photographing couples across Mississippi and at destinations abroad.	info@shelbymullinsphotography.com		https://shelbymullinsphotography.com/	https://www.instagram.com/shelbymullinsphotography/
Ashley Upchurch Photography	Photography		Jackson	Mississippi	Southeast US and destination weddings	Artful, romantic wedding photography from a Jackson-area photographer covering the Southeast and destination weddings, with coverage from $6,600.	ashleyupchurchphoto@gmail.com	(601) 955-8399	https://ashleyupchurchphotography.com/	https://www.instagram.com/ashleyupchurchphoto/
Ashley Schurch Photography	Photography		Jackson	Mississippi	Jackson, MS and destination weddings	Joyful, light-filled wedding photography from a Jackson-based photographer who also books weddings in Charleston, the DC area and further afield.			https://ashleyschurch.com/	https://www.instagram.com/ashleyschurchphotography/
Michelle Whitley Photography	Photography		Jackson	Mississippi	Jackson, Mississippi and Washington DC	Modern, emotive wedding and portrait photography split between Jackson and Washington DC, suited to couples with ties to both places.			https://michellewhitley.com/	https://www.instagram.com/michellewhitley/
Gavin Snyder Events	Planning		Jackson	Mississippi	Across the Southeast	Full-service wedding planning and design studio in Jackson with its own floral arm, handling budgets, vendors and on-the-day production.			https://www.gavinsnyderevents.com/	
Jennifer Mullen Events & Designs	Planning		Jackson	Mississippi	Jackson, Mississippi and beyond	Jackson planner offering everything from full wedding-weekend planning to wedding management only, with original event design for each couple.		(601) 345-1640	https://jmeventsanddesigns.com/	https://www.instagram.com/jmeventsanddesigns/
Signature Occasions	Planning	140 Township Avenue, Suite 110	Ridgeland	Mississippi		Ridgeland wedding and event planning firm led by a Master Wedding Planner with more than 25 years of experience organising Mississippi celebrations.	info@signatureoccasions.com	(601) 952-1960	https://www.signatureoccasions.com/	https://www.instagram.com/signatureoccasionsms/
Green Oak Florist	Florals	5009 Old Canton Road	Jackson	Mississippi		Family-run Jackson florist and garden centre since 1960, offering full wedding packages with delivery, setup and takedown, plus a Ridgeland shop.		(601) 956-5017	https://greenoakms.com/weddings/	https://www.instagram.com/greenoakms/
Kellye Christian Floral + Event Design	Florals	2741 Old Brandon Road	Pearl	Mississippi	All of Mississippi plus parts of Louisiana, Tennessee, Alabama and Texas	Full-service floral and event design firm in Pearl creating large-scale wedding décor and arrangements across Mississippi and neighbouring states.	design@kellyechristian.com	(601) 454-5410	https://kellyechristian.com/	https://www.instagram.com/kcfloraldesigns/
Florals by Brittany	Florals		Madison	Mississippi	Madison and throughout Mississippi	Madison wedding florist specialising in romantic, garden-style designs layered with colour and texture for celebrations across Mississippi.	info@floralsbybrittany.com	(601) 920-9782	https://www.floralsbybrittany.com/	https://www.instagram.com/floralsbybrittany/
Solid Steele Sounds Entertainment	Music		Jackson	Mississippi	Statewide across Mississippi	Jackson wedding DJ with 30+ years behind the decks, who teams up with a husband-and-wife photography partner for couples wanting both.	david.steele@solidsteelesounds.com	(601) 985-8195	https://www.solidsteelesounds.com/	
Crowd Pleasers Entertainment	Music		Madison	Mississippi		Madison wedding DJ company offering MC services, uplighting, gobo monograms and photo booths, with an online event planning sheet for couples.	rob@crowdpleasersdj.com	(601) 573-6162	https://www.crowdpleasersdj.com/	https://www.instagram.com/crowdpleasersdj/
String Music for Mississippi Weddings	Music		Jackson	Mississippi	Central Mississippi, including Madison, Clinton and Vicksburg	String quartets, trios, duos and solo violin for central Mississippi ceremonies since 2007, happy to arrange modern songs alongside classical pieces.	StringMusicforMSWeddings@gmail.com	(601) 323-2312	https://www.stringmusicformississippiweddings.com/	
Catering by George's	Catering	140 Madison Landing Circle	Ridgeland	Mississippi	Central Mississippi	Long-running Ridgeland caterer offering off-site wedding catering, bars and food stations, plus its own reservoir-view banquet hall.	cathy@cbgrez.com	(601) 898-1934	https://www.cateringbygeorges.com/	
Mangia Bene Catering	Catering		Jackson	Mississippi		Jackson caterer drawing menus from BRAVO!, Broad Street and Sal & Mookie's, with staffing and licensed bar service for weddings of any size.	avenw@broadstbakery.com	(601) 362-2900	https://www.mangiabene-catering.com/	https://www.instagram.com/mangiabenecatering/
My Mama & Me Catering	Catering		Jackson	Mississippi	Jackson and surrounding areas	Jackson caterer building tailored wedding menus, from plated dinners to elegant buffets, for intimate gatherings through to large receptions.		(601) 750-7017	https://www.mymamaandmecatering.com/	https://www.instagram.com/mymamaandmecatering_40/
Canvas Salon	Hair & Makeup	102 Dees Drive, Suite J	Madison	Mississippi		Madison salon whose Canvas Bridal team offers on-location hair and makeup for brides and wedding parties, with artists at several price points.	canvasthehairsalon@gmail.com	(601) 974-0555	https://www.canvasthehairsalon.com/bridal	https://www.instagram.com/canvas.bridal/
NGM Artistry & Co.	Hair & Makeup	108 S Maple St	Ridgeland	Mississippi	Jackson and surrounding areas	Makeup studio in Ridgeland providing luxury on-location bridal makeup, including a preview trial and optional wedding-day touch-up service.	makeupbynatalie09@yahoo.com	(601) 376-5253	https://makeupbyngm.com/	https://www.instagram.com/makeupbyngm/
Chelsey Jones	Hair & Makeup		Jackson	Mississippi	Mississippi and the Southeast	Jackson bridal makeup artist creating elevated makeup and hair looks for weddings across Mississippi and the Southeast, with lessons on offer too.			https://chelseyjones.co/	https://www.instagram.com/makeupbychels/
Mama J Bakes	Cake		Jackson	Mississippi	Metro Jackson	Home bakery in metro Jackson making custom wedding cakes, with a phone design consultation followed by a tasting before the final design.		(601) 345-1651	https://www.mamajbakes.com/weddings	https://www.instagram.com/mamaj_bakes/
AuRe's Cakes	Cake		Ridgeland	Mississippi		Ridgeland cake studio making homemade Southern-style custom and wedding cakes, with daily cakes available for same-day pickup.		(769) 226-6687	https://www.aurescakes.com/	https://www.instagram.com/aurescakes/
The Kakery Bakery	Cake		Madison	Mississippi		Family-run Madison cake shop baking made-from-scratch wedding and bridal shower cakes, plus cupcakes and cookies, since 2013.		(601) 316-3773	https://www.thekakerybakery.com/	
Line Studios	Videography		Jackson	Mississippi	Jackson, MS and beyond	Jackson wedding videographer making cinematic, story-led films, with highlight, full-length and stand-alone ceremony coverage options.	video@linestudios.org		https://www.linestudios.org/	https://www.instagram.com/linestudios/
McClenty Digital Media	Videography		Jackson	Mississippi		Jackson media company filming weddings across Mississippi with published package pricing, alongside photography and design work.	info@mcclentydigital.com	(601) 941-1337	https://www.mcclentydigital.com/weddings	
Samuel Long Productions	Videography		Madison	Mississippi	Jackson metro and north Mississippi	Wedding filmmaker working between Madison and Oxford, making cinematic films for couples across the Jackson metro and north Mississippi since 2019.	samuel@samuellongproductions.com		https://www.samuellongproductions.com/	https://www.instagram.com/samuellongproductions/
`,
  },
];

export default batches;
