import type { VendorBatch } from "@/lib/vendor-batches";

// Mississippi vendor batches. Every row's State is "Mississippi". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Jackson: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Shelby Mullins Photography	Photography		Jackson	Mississippi	Jackson, MS and destination weddings	Jackson wedding and portrait photographer with a classic, timeless style, photographing couples across Mississippi and at destinations abroad.	info@shelbymullinsphotography.com		https://shelbymullinsphotography.com/	https://www.instagram.com/shelbymullinsphotography/
Ashley Upchurch Photography	Photography		Jackson	Mississippi	Southeast US and destination weddings	Artful, romantic wedding photography from a Jackson-area photographer covering the Southeast and destination weddings, with coverage from $6,600.	ashleyupchurchphoto@gmail.com	(601) 955-8399	https://ashleyupchurchphotography.com/	https://www.instagram.com/ashleyupchurchphoto/
Ashley Schurch Photography	Photography		Jackson	Mississippi	Jackson, MS and destination weddings	Joyful, light-filled wedding photography from a Jackson-based photographer who also books weddings in Charleston, the DC area and further afield.			https://ashleyschurch.com/	https://www.instagram.com/ashleyschurchphotography/
Michelle Whitley Photography	Photography		Jackson	Mississippi	Jackson, Mississippi and Washington DC	Modern, emotive wedding and portrait photography split between Jackson and Washington DC, suited to couples with ties to both places.			https://michellewhitley.com/	https://www.instagram.com/michellewhitley/
Gavin Snyder Events	Planning		Jackson	Mississippi	Across the Southeast	Full-service wedding planning and design studio in Jackson with its own floral arm, handling budgets, vendors and on-the-day production.			https://www.gavinsnyderevents.com/	
Jennifer Mullen Events & Designs	Planning		Jackson	Mississippi	Jackson, Mississippi and beyond	Jackson planner offering everything from full wedding-weekend planning to wedding management only, with original event design for each couple.		(601) 345-1640	https://jmeventsanddesigns.com/	https://www.instagram.com/jmeventsanddesigns/
Signature Occasions	Planning	140 Township Avenue, Suite 110	Ridgeland	Mississippi		Ridgeland wedding and event planning firm led by a Master Wedding Planner with more than 25 years of experience organising Mississippi celebrations.	info@signatureoccasions.com	(601) 952-1960	https://www.signatureoccasions.com/	https://www.instagram.com/signatureoccasionsms/
Green Oak Florist	Florals	5009 Old Canton Road	Jackson	Mississippi		Family-run Jackson florist and garden centre since 1960, offering full wedding packages with delivery, setup and takedown, plus a Ridgeland shop.		(601) 956-5017	https://greenoakms.com/weddings/	https://www.instagram.com/greenoakms/
Kellye Christian Floral + Event Design	Florals	2741 Old Brandon Road	Pearl	Mississippi	All of Mississippi plus parts of Louisiana, Tennessee, Alabama and Texas	Full-service floral and event design firm in Pearl creating large-scale wedding décor and arrangements across Mississippi and neighbouring states.	design@kellyechristian.com	(601) 454-5410	https://kellyechristian.com/	https://www.instagram.com/kcfloraldesigns/
Florals by Brittany	Florals		Madison	Mississippi	Madison and throughout Mississippi	Madison wedding florist specialising in romantic, garden-style designs layered with colour and texture for celebrations across Mississippi.	info@floralsbybrittany.com	(601) 920-9782	https://www.floralsbybrittany.com/	https://www.instagram.com/floralsbybrittany/
Solid Steele Sounds Entertainment	Music		Jackson	Mississippi	Statewide across Mississippi	Jackson wedding DJ with 30+ years behind the decks, who teams up with a husband-and-wife photography partner for couples wanting both.	david.steele@solidsteelesounds.com	(601) 985-8195	https://www.solidsteelesounds.com/	
Crowd Pleasers Entertainment	Music		Madison	Mississippi		Madison wedding DJ company offering MC services, uplighting, gobo monograms and photo booths, with an online event planning sheet for couples.	rob@crowdpleasersdj.com	(601) 573-6162	https://www.crowdpleasersdj.com/	https://www.instagram.com/crowdpleasersdj/
String Music for Mississippi Weddings	Music		Jackson	Mississippi	Central Mississippi, including Madison, Clinton and Vicksburg	String quartets, trios, duos and solo violin for central Mississippi ceremonies since 2007, happy to arrange modern songs alongside classical pieces.			https://www.stringmusicformississippiweddings.com/	
Catering by George's	Catering	140 Madison Landing Circle	Ridgeland	Mississippi	Central Mississippi	Long-running Ridgeland caterer offering off-site wedding catering, bars and food stations, plus its own reservoir-view banquet hall.	cathy@cbgrez.com	(601) 898-1934	https://www.cateringbygeorges.com/	
Mangia Bene Catering	Catering		Jackson	Mississippi		Jackson caterer drawing menus from BRAVO!, Broad Street and Sal & Mookie's, with staffing and licensed bar service for weddings of any size.	avenw@broadstbakery.com	(601) 362-2900	https://www.mangiabene-catering.com/	https://www.instagram.com/mangiabenecatering/
My Mama & Me Catering	Catering		Jackson	Mississippi	Jackson and surrounding areas	Jackson caterer building tailored wedding menus, from plated dinners to elegant buffets, for intimate gatherings through to large receptions.		(601) 750-7017	https://www.mymamaandmecatering.com/	https://www.instagram.com/mymamaandmecatering_40/
Canvas Salon	Hair & Makeup	102 Dees Drive, Suite J	Madison	Mississippi		Madison salon whose Canvas Bridal team offers on-location hair and makeup for brides and wedding parties, with artists at several price points.	canvasthehairsalon@gmail.com	(601) 974-0555	https://www.canvasthehairsalon.com/bridal	https://www.instagram.com/canvas.bridal/
NGM Artistry & Co.	Hair & Makeup	108 S Maple St	Ridgeland	Mississippi	Jackson and surrounding areas	Makeup studio in Ridgeland providing luxury on-location bridal makeup, including a preview trial and optional wedding-day touch-up service.	makeupbynatalie09@yahoo.com	(601) 376-5253	https://makeupbyngm.com/	https://www.instagram.com/makeupbyngm/
Chelsey Jones	Hair & Makeup		Jackson	Mississippi	Mississippi and the Southeast	Jackson bridal makeup artist creating elevated makeup and hair looks for weddings across Mississippi and the Southeast, with lessons on offer too.			https://chelseyjones.co/	https://www.instagram.com/makeupbychels/
Mama J Bakes	Cake		Jackson	Mississippi	Metro Jackson	Home bakery in metro Jackson making custom wedding cakes, with a phone design consultation followed by a tasting before the final design.		(601) 345-1651	https://www.mamajbakes.com/weddings	https://www.instagram.com/mamaj_bakes/
AuRe's Cakes	Cake		Ridgeland	Mississippi		Ridgeland cake studio making homemade Southern-style custom and wedding cakes, with daily cakes available for same-day pickup.		(769) 226-6687	https://www.aurescakes.com/	https://www.instagram.com/aurescakes/
The Kakery Bakery	Cake		Madison	Mississippi		Family-run Madison cake shop baking made-from-scratch wedding and bridal shower cakes, plus cupcakes and cookies, since 2013.		(601) 316-3773	https://www.thekakerybakery.com/	
Line Studios	Videography		Jackson	Mississippi	Jackson, MS and beyond	Jackson wedding videographer making cinematic, story-led films, with highlight, full-length and stand-alone ceremony coverage options.	video@linestudios.org		https://www.linestudios.org/	https://www.instagram.com/linestudios/
McClenty Digital Media	Videography		Jackson	Mississippi		Jackson media company filming weddings across Mississippi with published package pricing, alongside photography and design work.	info@mcclentydigital.com	(601) 941-1337	https://www.mcclentydigital.com/weddings	
Samuel Long Productions	Videography		Madison	Mississippi	Jackson metro and north Mississippi	Wedding filmmaker working between Madison and Oxford, making cinematic films for couples across the Jackson metro and north Mississippi since 2019.	samuel@samuellongproductions.com		https://www.samuellongproductions.com/	https://www.instagram.com/samuellongproductions/
`,
  },
  {
    name: "Gulf Coast: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kayce Stork Photography	Photography		Biloxi	Mississippi	Biloxi, New Orleans and the Mississippi and Alabama Gulf Coast	Biloxi wedding photography team covering coastal venues from the Mississippi Sound to New Orleans, with a blog full of recent local weddings.			https://www.kaycestorkweddings.com/	https://www.instagram.com/kaycestorkphotography/
Anna Cirlot Photography	Photography		Gautier	Mississippi	Mississippi and Alabama Gulf Coast	Gautier photographer shooting weddings, engagements and beach sessions along the Mississippi and Alabama coast, with a relaxed, natural style.	hello@annacirlotphotography.com	(228) 202-2009	https://annacirlotphotography.com/	https://www.instagram.com/annacirlotphotography/
DP Photography	Photography	895 Vee St	Biloxi	Mississippi	Across the Gulf Coast	Biloxi studio photographer focusing on smaller weddings of 100 guests or fewer, with elopement coverage and an option for live photo delivery on the day.	dpphotographyllc@gmail.com	(228) 910-3307	https://dpphotographyllc.com/	
The Wedding Collection	Planning	107 US Hwy 90	Bay St. Louis	Mississippi	Mississippi Gulf Coast	Bay St. Louis studio offering full planning, month-of coordination, styling and in-house floral design for weddings from Bay St. Louis to Ocean Springs.	info@theweddingcollection.com		https://www.theweddingcollection.com/	https://www.instagram.com/the.wedding.collection/
Tenesha & Company	Planning	4341 Gautier-Vancleave Rd, Suite 8	Gautier	Mississippi		Gautier event planning and design company that coordinates venues, catering, DJs and décor for weddings, and keeps its own rental inventory.	tenandcoevents@gmail.com	(228) 327-6844	https://www.teneshaandcompany.com/	
Coastal Wedding Services	Planning	2408 14th St	Gulfport	Mississippi		Gulfport ceremony specialists offering officiant-only packages up to fully staged beach ceremonies with seating, music, arches and flowers.	coastalweddingservices@gmail.com	(228) 256-3113	https://coastalweddingservices.net/	
The French Potager	Florals	213 Main Street	Bay St. Louis	Mississippi		Flower shop and event designer on Main Street in Old Town Bay St. Louis, creating wedding and event florals alongside everyday orders and classes.	shop@thefrenchpotager.com	(228) 364-3091	https://www.thefrenchpotager.com/	https://www.instagram.com/thefrenchpotager/
Beth Cranford Floral Designs	Florals		Bay St. Louis	Mississippi		Bay St. Louis floral designer working on the coast since 2016, taking couples through a step-by-step wedding process that starts with a questionnaire.		(228) 342-5944	https://www.bethcranfordfloral.com/	https://www.instagram.com/bethcranfordfloral/
Flowers By Karen	Florals	3074 Government St	Ocean Springs	Mississippi		Ocean Springs florist with dedicated wedding collections for the ceremony and reception, and wedding consultations booked through its site.		(228) 875-0703	https://flowersbykareninc.com/pages/wedding-page	
Nightshift Sounds Entertainment	Music		Ocean Springs	Mississippi	New Orleans to the Florida panhandle	Ocean Springs DJ and lighting company with a long run of wedding industry awards, playing receptions from New Orleans to the Florida panhandle.	info@nightshiftsounds.net	(228) 219-0695	https://www.nightshiftsounds.net/	https://www.instagram.com/nightshiftsoundsentertainment/
DJ George Chuck	Music		Gulfport	Mississippi	Mississippi Gulf Coast, coastal Alabama, the Northshore and south and central Mississippi	Gulfport wedding DJ and MC with 25-plus years and 700-plus weddings, adding ceremony audio, uplighting, monogram lighting and livestreams.	george.chuck@me.com	(601) 622-3173	https://www.georgechuck.com/	https://www.instagram.com/georgechuck/
Jim Horn Entertainment	Music		Gautier	Mississippi	Mississippi Gulf Coast, Hattiesburg, Mobile and Slidell	Gautier wedding DJ and MC with more than three decades of receptions on the coast, bringing his own sound and lighting and a tailored playlist.	jim@jimhornentertainment.com	(228) 623-1383	https://www.jimhornentertainment.com/	https://www.instagram.com/djjim/
Scranton's Catering	Catering	623 Delmas Ave	Pascagoula	Mississippi		Pascagoula restaurant's full-service off-site catering, with a production crew handling setup, bar service and clean-up for weddings of 100-plus guests.	service@scrantons.com	(228) 218-5102	https://www.scrantons.com/catering	https://www.instagram.com/scrantons/
Eat Drink Love	Catering	701 Bienville Blvd	Ocean Springs	Mississippi		Ocean Springs restaurant and bar running a separate catering arm for off-site weddings, showers and cocktail parties and corporate dinners.	eatdrinkloveos@gmail.com	(228) 217-7160	https://eatdrinklove701.com/ocean-springs-eat-drink-love-catering-catering	https://www.instagram.com/eatdrinklovecatering/
Salute Italian Restaurant	Catering	1712 15th Street	Gulfport	Mississippi		Gulfport Italian and Gulf seafood restaurant catering weddings and rehearsal dinners, either in its own rooms or off-site at your venue.	hollielarkins@gmail.com	(228) 864-2500	https://www.saluteitalian.com/catering-company-gulfport	
Simply Seafood and Catering	Catering		Biloxi	Mississippi	Mississippi Gulf Coast	Biloxi caterer specialising in seafood-led wedding menus in tiered packages, with Cajun, Italian and vegetarian options and tastings offered.	ssoldo21@gmail.com	(228) 990-7161	https://www.simplyseafoodandcatering.com/	
Poppy Rose Beauty	Hair & Makeup		Ocean Springs	Mississippi	Gulf Coast from south Alabama to New Orleans and up to Hattiesburg	Ocean Springs bridal makeup artist and esthetician who travels to weddings across the coast, with looks ranging from natural to red-carpet glam.	poppyroseesthetics@gmail.com	(916) 316-7329	https://www.poppyrosebeauty.com/	
Tracy Perry Hair Salon	Hair & Makeup	14355 Dedeaux Rd	Gulfport	Mississippi	Within 60 miles of Gulfport	Gulfport salon offering bridal updos and airbrush makeup, with stylists able to travel to weddings within about 60 miles of the salon.		(228) 832-2240	https://www.perryshairsalon.com/	
Polished Salon & Spa	Hair & Makeup	1308 College St	Gulfport	Mississippi		Full-service Gulfport salon and spa that specialises in bridal and event hair and makeup, alongside lash extensions, waxing and massage.	pssgulfport@hotmail.com	(228) 206-5465	https://polishedsalonandspallc.com/	
Dolce Bakeshop	Cake	200 Jeff Davis Ave, Suite 2	Long Beach	Mississippi		Long Beach bakeshop designing custom wedding cakes at its cake studio, plus groom's cakes, shower cakes and dessert-table sweets.		(228) 265-8790	https://www.dolcebakes.net/weddings	https://www.instagram.com/dolcebakeshopms/
Custom Cakes by Jennifer Noble	Cake		Biloxi	Mississippi	Mississippi Gulf Coast and surrounding areas	Biloxi cake artist, formerly of Cheeky Monkey Cake Company, now designing bespoke wedding cakes from a private studio by consultation.	jennifer@jnoblecakes.com	(228) 220-4985	https://www.jnoblecakes.com/	https://www.instagram.com/jnoblecakes/
Jen & Chuck Photography	Videography		Ocean Springs	Mississippi	Mississippi, Alabama, Louisiana, Florida and beyond	Husband-and-wife team from Ocean Springs filming and photographing weddings, so couples can book video and stills from one crew.	Jenandchuckphotography@gmail.com	(228) 235-0242	https://jenandchuck.com/	https://www.instagram.com/jenandchuckphotography/
`,
  },
  {
    name: "Gulf Coast: videography, cake, photography, planning and music",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
itsGMB Studios	Videography		Long Beach	Mississippi	Mississippi, Louisiana, Alabama, Florida, Georgia and Tennessee	One team handling wedding photography, cinematic films and DJ and MC duties in a single booking, rooted in studio production since 2004.			https://itsgmb.com/	https://www.instagram.com/itsgmb/
Savvy Snapshots Photo + Films	Photography	178 Main St, Suite #302	Biloxi	Mississippi	Mississippi Gulf Coast, Alabama, Louisiana and Florida	Editorial-style wedding, elopement and portrait photography with film and drone coverage, run from a Biloxi studio since 2018.	savvysnapshotsphotography@gmail.com	228-861-2495	https://savvysnapshots.com/	https://www.instagram.com/savvysnapshots/
Bamari Event Planning	Planning		Gautier	Mississippi	Mississippi, with select areas of Louisiana, Alabama and West Florida	Full-service wedding planning, coordination and decor from a Gautier team led by Abbi Adkins, with table and chair rentals on offer.			https://www.bamarieventplanning.com/	https://www.instagram.com/bamarieventplanning/
Say Yes Weddings and Events	Planning		Biloxi	Mississippi	Mississippi Gulf Coast	Wedding planning, day-of coordination and floral design led by founder Brie Lybrand Garza, with a Southern feel and an invitation specialist on the team.	sayyesweddingsevents@gmail.com		https://www.sayyesweddingsevents.com/	https://www.instagram.com/sayyesweddingsandevents/
LaceyCakes	Cake	2321 Government St. STE B	Ocean Springs	Mississippi	Ocean Springs and surrounding areas	By-appointment baker creating custom buttercream wedding and celebration cakes, plus cake carts, from a downtown Ocean Springs shop.	laceycakesms@gmail.com	(228) 860-0104	https://www.laceycakesms.com/	https://www.instagram.com/laceycakesms/
Melissa's Bakery	Cake	15335 Dedeaux Road, Suite B	Gulfport	Mississippi		Boutique Gulfport bakery designing custom wedding cakes, cupcakes and macarons, with cake consultations booked through its website.		228-563-5111	https://www.melissasgulfport.com/	
Susan's Sassy Sweets	Cake	315 HWY 90	Waveland	Mississippi		Family-owned Waveland bakery making scratch-baked custom cakes, cupcakes and cake pops, with a dedicated page for wedding cakes.		228-265-4343	https://susanssassysweets.net/	
Secret Coast DJ	Music		Ocean Springs	Mississippi	Mississippi Gulf Coast	Clean, high-energy wedding DJ service covering ceremony and reception, with photo booth, lighting and cold spark extras available.		(601) 724-2030	https://secretcoastdj.com/	https://www.instagram.com/secretcoastdj/
`,
  },
  {
    name: "Oxford: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Chloe Cole Photography	Photography		Oxford	Mississippi		Oxford photographer offering documentary-style wedding, boudoir and portrait sessions, with a focus on genuine moments and emotion.	chloe@chloecolephotography.com		http://www.chloecolephotography.com/	https://www.instagram.com/chloecolephotography/
Helena Kaye Photography	Photography		Oxford	Mississippi	Oxford, Mississippi and worldwide	Wedding and engagement photographer working from Oxford, sharing real weddings and elopements through an online journal and investment guide.			https://www.helenakaye.com/	
b.flint photography	Photography		Oxford	Mississippi		Fine art wedding photographer in Oxford, Brian Flint documents couples across Mississippi with a photojournalistic eye and a journal of recent weddings.			https://www.bflint.com/	https://www.instagram.com/bflint/
Keli Lindsey Photography and Film	Videography		Oxford	Mississippi	North Mississippi	Mother and daughter team filming full wedding and engagement videos in North Mississippi alongside wedding and senior photography.	kelilindseyphotos@gmail.com	662-473-8448	https://kelilindseyphotography.com/	https://www.instagram.com/kelilindseyphotos/
Taylored Well Events	Planning		Oxford	Mississippi	Oxford, Tupelo and destinations	Wedding and event design firm rooted in Oxford and Tupelo, handling layered tablescapes, timelines, contracts and rain plans for couples.			https://www.tayloredwellevents.com/	https://www.instagram.com/tayloredwellevents/
Ellen Thomas Event Design	Planning	1104 Van Buren Ave, Suite B	Oxford	Mississippi		Oxford planning and design studio offering full event design or month-of coordination, led by a University of Mississippi hospitality graduate.	info@ellenthomaseventdesign.com	662-307-4404	https://ellenthomaseventdesign.com/	https://www.instagram.com/ellenthomaseventdesign/
Oxford Floral	Florals	1103 Jefferson Ave	Oxford	Mississippi		Family-owned Oxford florist since 1924, designing wedding bouquets, ceremony pieces and centrepieces alongside gifts and a bridal registry.		662-234-2515	https://www.oxfordfloral.com/	
Farmstead Florals	Florals		Oxford	Mississippi	North Mississippi, Memphis and Birmingham	Cut flower farm outside Oxford growing seasonal blooms for weddings and events, as well as wholesale bunches, classes and a self-serve stand.	katherine@farmsteadwr.com		https://www.farmsteadflorals.com/	https://www.instagram.com/farmsteadflorals/
University Florist	Florals	1912 University Ave	Oxford	Mississippi		Oxford flower shop with a dedicated weddings section for bouquets, corsages, boutonnieres and centrepieces, plus same-day local delivery.		662-234-6044	https://www.universityfloristms.com/	
TSR Events	Music		Oxford	Mississippi		Oxford DJ service offering tiered wedding packages with MC duties, uplighting and optional photo booths, plus coordination at the top tier.		662-832-0338	https://www.tsreventsoxford.com/	https://www.instagram.com/tsreventsoxford/
Taylor Grocery Special Events Catering	Catering		Oxford	Mississippi	Oxford and North Mississippi	Southern wedding caterer using local ingredients for receptions and rehearsal dinners, built on three decades of events around Oxford.		662-801-9140	https://taylorgrocerycatering.com/	https://www.instagram.com/taylorgrocater/
Elizabeth Heiskell Catering	Catering		Oxford	Mississippi	Across the South	Mississippi caterer with nearly three decades behind it, designing plated and family-style wedding menus as well as galas and gatherings.			https://elizabethheiskell.com/	
My Michelle's	Catering		Oxford	Mississippi		Oxford caterer and takeaway kitchen providing food for weddings of any size, plus game-day and corporate orders around the Grove.		662-236-1512	https://www.mymichellesoxford.com/	https://www.instagram.com/mymichelles/
The Studio Oxford	Hair & Makeup	1417 University Avenue	Oxford	Mississippi		Full-service Oxford salon and spa with a dedicated bridal page for wedding hair, extensions and bridal party styling.	thestudiooxfordms@gmail.com	662-371-1229	https://www.thestudiooxfordms.com/	https://www.instagram.com/thestudiooxfordms/
Element Hair Studio	Hair & Makeup	404 South 11th Street	Oxford	Mississippi		Downtown Oxford hair salon offering bridal updos and blowouts for the bride, bridesmaids, mothers and little ones.	reception@element-hairstudio.com	662-301-9540	https://www.elementhairstudio.com/	https://www.instagram.com/element.hair.oxford/
Flight Aesthetics and Salon	Hair & Makeup	2154 S Lamar Blvd	Oxford	Mississippi		Oxford salon and medspa offering bridal hair and makeup, updos, makeup lessons and game day styling from its South Lamar studio.	info@flightmedspa.com	662-380-5277	https://www.flightmedspa.com/	https://www.instagram.com/flightaesthetics/
Bremma's Cakery and Confections	Cake	1944 University Avenue	Oxford	Mississippi		Oxford bakery from two bakers making scratch-made wedding cakes and groom's cakes, with consultations and delivery setup priced per slice.	info@bremmasbakery.com	662-202-6466	https://www.bremmasbakery.com/	https://www.instagram.com/bremmasbakery/
JustCakeIt!	Cake	2580 Jackson Ave West, Suite 34	Oxford	Mississippi		Oxford bakery making custom celebration cakes and desserts for weddings and university events, with a quote request form.		662-237-2253	https://justcakeit.net/	https://www.instagram.com/justcakeit_662/
`,
  },
];

export default batches;
