import type { VendorBatch } from "@/lib/vendor-batches";

// Nebraska vendor batches. Every row's State is "Nebraska". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Omaha: photography, planning, florals, music, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Lathrop Wedding Company	Photography		Omaha	Nebraska	Omaha and the Midwest	Husband-and-wife style team shooting candid, documentary wedding photography and video from one booking.	hello@lathropweddingco.com	712-525-0416	https://lathropweddingco.com/	https://www.instagram.com/lathropweddingco/
Andrea Bibeault	Photography		Omaha	Nebraska	Omaha, Nebraska	Wedding photojournalist who focuses on candids, details and the small moments of the day rather than staged poses.		402-657-3923	https://andreabibeault.com/	https://www.instagram.com/andreabibeault/
Caitlin & Camera	Photography		Omaha	Nebraska	Nebraska and beyond	Omaha photographer shooting natural, documentary-style weddings, plus engagement and family portrait sessions.	caitlinmanley12@gmail.com		https://caitlinandcamera.com/	https://www.instagram.com/caitlinandcamera/
Walnut Studio Events	Planning		Omaha	Nebraska	Nebraska and the Midwest	Boutique Omaha planning studio offering full planning, partial planning and day-of coordination for weddings across the Midwest.	cara@walnutstudioevents.com	719-337-1707	https://walnutstudioevents.com/	
Kimmy Ann Events	Planning		Omaha	Nebraska	Omaha, Nebraska	Omaha planner offering wedding coordination and full-service planning built on a step-by-step approach to the logistics of the day.	kimmy@kimmyannevents.com	417-343-3983	https://www.kimmyannevents.com/	https://www.instagram.com/kimmyannevents/
Elle Seals Events	Planning		Omaha	Nebraska	Omaha, Nebraska	Omaha event designer and coordinator who builds a custom design and plan for each wedding.	elle@elleseals.com	402-980-7347	https://elleseals.com/	https://www.instagram.com/elle.seals.events/
Bouquet	Florals	725 N 98th St	Omaha	Nebraska	Omaha and beyond	Floral design studio in west Omaha known for high-end weddings, large-scale installations and floral workshops.	details@bouquetomaha.com	402-905-0589	https://www.bouquetomaha.com/	https://www.instagram.com/bouquetomaha/
Ethereal Floral Studio	Florals		Omaha	Nebraska	Omaha metro and surrounding areas	Floral studio producing wedding florals in the Omaha metro, from bespoke installations to colourful whimsical tablescapes.			https://etherealfloralstudio.com/	https://www.instagram.com/etherealfloralstudio/
Janousek Florist	Florals	4901 Charles St	Omaha	Nebraska	Omaha, Nebraska	Family-owned Omaha flower shop open since 1913, doing wedding flowers alongside same-day delivery.		402-556-5652	https://janousekflorist.com/	
Ackerman Events	Music		Omaha	Nebraska	Omaha, Lincoln and Council Bluffs	DJ and MC service for weddings, with ceremony audio, reception DJ and dance floor lighting available.	Zach@ackermanevents.com	402-704-4187	https://www.ackermanevents.com/	https://www.instagram.com/ackermanevents/
Mitchell Wedding Services	Music		Elkhorn	Nebraska	Omaha area	Wedding and event DJ service with a professional MC, six-speaker sound system and dance floor lighting.	MitchellWeddingServices@gmail.com	402-917-8216	https://www.mitchellweddingservices.com/	https://www.instagram.com/mitchellweddingservices/
Image Entertainment	Music		Omaha	Nebraska	Omaha, Nebraska	Omaha DJ company covering both intimate gatherings and wedding receptions with hundreds of guests.	imageentertainment402@gmail.com	402-515-3569	https://www.imageentertainmentomaha.com/	
Abraham Catering	Catering		Omaha	Nebraska	Omaha and Lincoln	Four-generation family caterer, in business since 1951, with plated, buffet and station menus for weddings.			https://www.abrahamcatering.com/	https://www.instagram.com/abrahamcatering/
Attitude On Food	Catering	7758 Cass St	Omaha	Nebraska	Omaha and the Midwest	Full-service wedding and event caterer in Omaha since 2002, with fine-dining style menus at approachable prices.		402-341-3663	https://attitudeonfood.com/	https://www.instagram.com/attitudeonfood/
Patricia Catering & Cocktails	Catering		Omaha	Nebraska	Omaha, Bellevue, Papillion, La Vista, Gretna, Elkhorn, Council Bluffs and Lincoln	Omaha caterer since 1986 offering wedding menus plus a cocktail service across the metro and into Lincoln.	info@patriciacatering.com	402-733-6733	https://patriciacatering.com/	https://www.instagram.com/patriciacateringandcocktails/
Hannah Kuhary Makeup	Hair & Makeup		Omaha	Nebraska	Omaha, Nebraska	Omaha makeup artist who works onsite on wedding mornings and favours a modern, natural finish.	hannah.kuhary@gmail.com	952-807-2160	https://www.hannahkuhary.com/	https://www.instagram.com/hkmakeupartist/
Makeup by Madison	Hair & Makeup		Omaha	Nebraska	Omaha, Nebraska	Omaha bridal, event and commercial makeup artist who also helps wedding mornings run smoothly.	madison.schreffler@gmail.com		https://www.makeupxmadison.com/	https://www.instagram.com/makeupxmadisonne/
Model Perfect Airbrush	Hair & Makeup		Omaha	Nebraska	Omaha, with travel to wedding venues	Airbrush makeup and hair company that works at its Omaha location or travels to weddings for an added fee.	modelperfectairbrush@gmail.com		https://www.mpairbrush.com/	https://www.instagram.com/modelperfectairbrush/
Crum Cakes Bakery	Cake	763 N 114th St	Omaha	Nebraska	Omaha, Nebraska	Local Omaha bakery making custom cakes, cupcakes and treats designed around the couple's style.	crumcakesbakery@yahoo.com	402-850-5941	https://crumcakesbakery.com/	
Love More Sweets	Cake		Omaha	Nebraska	Omaha and across Nebraska	Pastry chef Kelsey Ryder makes bespoke wedding cakes with hand-sculpted sugar flowers and private tastings.	kelsey@lovemoresweetsomaha.com		https://lovemoresweetsomaha.com/	https://www.instagram.com/lovemoresweets/
Sweet Magnolias Bake Shop	Cake	813 N 40th St	Omaha	Nebraska	Omaha, Nebraska	Boutique bakery in the Joslyn Castle neighbourhood with a dedicated wedding cake order form and tastings.	sweetmagnoliasbakeshop@gmail.com	402-934-6427	https://www.sweetmagnoliasbakeshop.com/	https://www.instagram.com/sweetmagnoliasbakeshop/
Bobby Jay Films	Videography		Omaha	Nebraska	Omaha and Des Moines	Wedding videographer in Omaha making custom films that reflect each couple's own day, also travelling to Des Moines.	bobbyjayfilms@gmail.com		https://bobbyjayfilms.com/	https://www.instagram.com/bobbyjayfilms/
Heart & Light Co.	Videography		Omaha	Nebraska	Omaha and the Midwest	Documentary-style wedding films with an artful storytelling approach, aimed at luxury weddings in Omaha and beyond.	tess@heartandlightcompany.com		https://www.heartandlightcompany.com/	https://www.instagram.com/heartandlightcompany/
Vogel Films	Videography		Papillion	Nebraska	Omaha metro	Omaha-area wedding video company making custom films of the wedding day and other life's special moments.			https://www.vogelfilms.com/	
`,
  },
  {
    name: "Lincoln: photography, planning, florals, music, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Allison Garrett Johnson	Photography		Lincoln	Nebraska	Lincoln and within 70 miles, with travel across the Midwest	Lincoln wedding photographer working full-time for seventeen years, with collections from two hours to a full day and travel beyond 70 miles.	allison@allisongarrett.com	402-641-1728	https://www.allisongarrett.com/lincoln-nebraska-wedding-photographer/	https://www.instagram.com/allisongarrettjohnson/
Vance Doeden Photography	Photography		Lincoln	Nebraska	Lincoln, Omaha and travel across the Midwest	Lincoln wedding and elopement photographer who documents real, unposed moments, originally from Wichita and based in Lincoln since 2024.			https://www.vancedoeden.com/	https://www.instagram.com/vancedoeden/
Laura Elizabeth Photography	Photography		Lincoln	Nebraska	Nebraska, with travel anywhere	Husband-and-wife Lincoln team who shoot both photo and video at each wedding, in a light, timeless style, with travel anywhere.	hello@lauraelizabethphotography.org	402-413-1862	https://www.lauraelizabethphotography.org/nebraskaweddingphotographer	https://www.instagram.com/lauraelizabethphotos/
Sage Events by Camryn	Planning		Lincoln	Nebraska	Lincoln and surrounding areas	Lincoln month-of wedding coordinator who runs the day so the couple can be guests, now booking 2027 and 2028 dates; does not offer full planning.	sageeventsne@gmail.com	(402) 413-8870	https://www.sageeventsne.com/	https://www.instagram.com/sageeventsne/
Event Design	Planning		Lincoln	Nebraska	Lincoln and surrounding areas, with travel	Lincoln planner and coordinator, licensed since 2011, handling budget, timeline and vendors plus setup and teardown, with staff for bartending and childcare.	shelly@eventdesignit.com	(402) 440-8913	https://www.eventdesignit.com/	
Of The Earth Floral Design	Florals	8320 Glynoaks Dr, Ste 120	Lincoln	Nebraska	Lincoln and surrounding areas	Lincoln floral studio with a café and rentable event space, offering full-service and a la carte wedding flowers in garden-inspired styles.	hello@oftheearthflorals.com	(402) 480-6220	https://www.oftheearthflorals.com/full-service	
Stem Gallery	Florals	5630 P St	Lincoln	Nebraska	Lincoln	Lincoln flower shop on P Street offering wedding bouquets, ceremony, reception and wedding-party flowers alongside its everyday arrangements and gifts.		(402) 489-1700	https://www.thestemgallery.com/wedding-flowers	https://www.instagram.com/thestemgallery/
Oak Creek Plants & Flowers	Florals	3435 S 13th St	Lincoln	Nebraska	Lincoln	Lincoln florist and plant shop on South 13th Street with collections for wedding bouquets, ceremony and reception flowers and wedding-party pieces.		(402) 421-2999	https://www.oakcreekflowers.com/wedding-flowers	https://www.instagram.com/oakcreekplantsandflowers/
Crown DJs	Music	4211 S 33rd St	Lincoln	Nebraska	Lincoln	Lincoln wedding DJ and MC with a digital photo booth and dance floor lighting, working from a new south Lincoln office and taking 2026 and 2027 dates.	info@crowndjs.com	(402) 610-4275	https://www.crowndjslincoln.com/	https://www.instagram.com/crowndjslincoln/
Downtown Collective Band	Music		Lincoln	Nebraska	Nebraska and the Midwest	Lincoln live band of nine to eleven musicians, with a hybrid band and DJ option, playing high-energy sets for wedding receptions across the Midwest.	downtowncollectivelincoln@gmail.com	(402) 405-7375	https://www.downtowncollectiveband.com/packages/weddings	https://www.instagram.com/tdco.ent/
5 Star Entertainment	Music		Lincoln	Nebraska	Lincoln	Lincoln mobile DJ service that books weddings, receptions and parties, with a calendar for checking open dates.	info@5starent.net	402-805-1523	https://www.5starent.net/	
Doorstep Diner Catering	Catering	5550 S 59th St	Lincoln	Nebraska	Lincoln and southeast Nebraska	Lincoln caterer making from-scratch food for weddings, with staffed food stations, grazing tables and charcuterie boards plus boxed and corporate lunches.	catering@doorstepdiner.com	531-510-8385	https://www.doorstepdiner.com/	
Chez Hay	Catering		Lincoln	Nebraska	Lincoln	Lincoln caterer of more than twenty years serving bridal showers, rehearsal dinners and wedding receptions with personalised menus.		402.489.7445	https://chezhay.com/	
Premier Catering	Catering	2621 S 70th St, Suite B	Lincoln	Nebraska	Omaha and Lincoln venues	Lincoln caterer with buffet and a la carte menus for events of 50 to 5,000 guests, including weddings, and a published list of venues in Omaha and Lincoln.	service@premiercatering.net	(402) 323-8420	https://www.premiercatering.net/	
Salon Frankie	Hair & Makeup	133 S 9th St	Lincoln	Nebraska	Lincoln, with travel by arrangement	Downtown Lincoln salon whose owner, with over twenty years of experience, does bridal hair and makeup in the salon or at your location, trial included.		402.429.6992	https://www.salonfrankie.com/wedding-hair	https://www.instagram.com/hsousek/
House of Holloway	Hair & Makeup	5740 Old Cheney Rd, #7	Lincoln	Nebraska	Lincoln	Lincoln salon off Old Cheney Road that lists bridal styling, updos, braiding and makeup application alongside its regular cuts and colour services.	houseofholloway@yahoo.com	(402) 423-3616	https://www.houseofholloway.com/services	https://www.instagram.com/houseofhollowaysalon/
Alicia's Makeup Artistry	Hair & Makeup		Lincoln	Nebraska	Lincoln and Nebraska, with travel for larger parties	Lincoln makeup artist trained in Vancouver, doing airbrush and traditional bridal makeup on location, with a bridal preview included.	alicias.makeup@yahoo.com		https://www.aliciasmakeupartistry.com/	https://www.instagram.com/aliciasmakeupartistryllc/
Butterfly Bakery	Cake	4209 S 33rd St	Lincoln	Nebraska	Lincoln	Locally owned Lincoln cake and pastry shop with designer and custom wedding cakes, cupcakes, tablescape cakes and graze tables.	customerservice@butterflybakeryne.com	402-499-0620	https://butterflybakeryne.com/	https://www.instagram.com/butterflygaykery/
Goldenrod Pastries	Cake	3947 S 48th St	Lincoln	Nebraska	Lincoln	Lincoln pastry shop with a wedding menu of six cake designs, each available gluten-free, dairy-free, vegan or traditional.	orders@goldenrodpastries.com	402-486-4103	https://www.goldenrodpastries.com/weddings	https://www.instagram.com/goldenrodpastries/
Cupcakes & More	Cake	5700 Old Cheney Rd	Lincoln	Nebraska	Lincoln	Lincoln bakery on Old Cheney Road making cupcakes, custom cakes and wedding cakes, with a wedding cake consultation and gluten-free or dairy-free options.	cupcakesandmorelincoln@gmail.com	402-261-6214	https://www.cupcakesandmorelincoln.com/wedding	
Van Hoosen Video	Videography	926 N 39th St	Lincoln	Nebraska	Southeast and Central Nebraska	Lincoln video company making wedding films since 2000, with half-day to full-day and cinematic packages and a photo booth option.		(402) 540-6951	https://vanhoosenvideo.com/	
Bill Griepenstroh	Videography		Lincoln	Nebraska	Lincoln, Omaha and destination weddings	Lincoln commercial director who also films weddings in a documentary, story-first style, with travel fees beyond a 100-mile radius of Lincoln.			https://www.billgriepenstroh.com/weddings	https://www.instagram.com/billgrip/
NVAR Studios	Videography	1200 N St, Suite 524	Lincoln	Nebraska	Lincoln	Lincoln video and photo studio filming documentary-style weddings with a highlight film plus a longer feature, handled by the same team that shoots the photos.		(402) 610-4480	https://www.nvarstudios.com/lincoln-wedding-videographer	https://www.instagram.com/nvarstudios/
`,
  },
  {
    name: "Lincoln: planning",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Only Once Co.	Planning		Lincoln	Nebraska	Lincoln, with travel outside Lincoln available	Lincoln planner with a conference and vendor-side background, offering full, partial and month-of coordination at published package prices.	shianne@onlyonceco.com	(307) 921-0822	https://www.onlyonceco.com/	https://www.instagram.com/OnlyOnceCo.Events/
`,
  },
];

export default batches;
