import type { VendorBatch } from "@/lib/vendor-batches";

// Nevada vendor batches. Every row's State is "Nevada". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Las Vegas: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
SOTE	Photography		Las Vegas	Nevada	Las Vegas and destination weddings	Editorial and documentary wedding photographer led personally by Kim Willoughby, drawing on a film and fashion background.	kim@photosbysote.com	+1 702 701 4380	https://www.photosbysote.com	https://www.instagram.com/photosbysote/
Studio N Photography	Photography		Las Vegas	Nevada	Las Vegas and destination weddings	Husband-and-wife photography studio offering romantic wedding coverage, engagement sessions and bridal makeup artistry.		(702) 750-1060	https://www.thestudion.com	https://www.instagram.com/studio_n_photography/
Kristen Marie Weddings + Portraits	Photography		Las Vegas	Nevada	Las Vegas and destinations	Las Vegas photographer with a timeless, relaxed style, also shooting engagements, family portraits and headshots.			https://kristenmarieweddings.com	https://www.instagram.com/kristenmarieweddings/
The Vegas Planners	Planning		Las Vegas	Nevada	Las Vegas and destination weddings	Wedding and event planning company that guides couples through a five-step process, from foundations to day-of execution.	info@thevegasplanners.com	702.683.7288	https://thevegasplanners.com	https://www.instagram.com/thevegasplanner/
Simply Weddings Las Vegas	Planning		Las Vegas	Nevada	Las Vegas	Wedding planning and design firm combining personalised celebration design with hands-on logistics, with a second office in the Pacific Northwest.	hello@simplyweddingslv.com	702-592-3982	https://www.simplyweddingslv.com	https://www.instagram.com/simplyweddings/
Blanc Events	Planning		Las Vegas	Nevada	Las Vegas and surrounding region	Wedding and event planner founded by a former Cirque du Soleil producer, focused on guest experience and refined design.	inquire@blanc-events.com		https://blanc-events.com	https://www.instagram.com/blanceventslv/
Sara Lunn Floral Studio	Florals		Las Vegas	Nevada	Las Vegas, Arizona and Southern California	Floral design studio for weddings and events, working in Strip hotels and private estates with over ten years of experience.			https://saralunn.com	https://www.instagram.com/saralunnfloral/
City Blossoms	Florals		Las Vegas	Nevada	Las Vegas area	Floral studio known for romantic, lush, organic arrangements, offering full-service wedding florals and rental pieces.			https://www.cityblossomslv.com	https://www.instagram.com/cityblossomslv/
Floral Lab	Florals		Las Vegas	Nevada	Las Vegas Valley, Henderson and Boulder City	Boutique florist where the owner checks each arrangement, taking on custom wedding florals, installations and flower bars.	mail@floral-lab.com	702-771-1770	https://www.floral-lab.com	https://www.instagram.com/florallab_vegas/
Live Music Society	Music		Las Vegas	Nevada	Las Vegas, nationally and internationally	Wedding and corporate band agency building lineups from solo acts to 15-piece showbands, with sound and backline included.	info@lmsentertainmentlv.com	702-858-2682	https://www.livemusicsocietylv.com	https://www.instagram.com/livemusicsocietylv/
DJ Mo Blvd	Music		Las Vegas	Nevada	Las Vegas, travels anywhere	Wedding DJ and MC offering ceremony audio, wireless mics, uplighting and an online portal for timelines and playlists.			https://djmoblvd.com	https://www.instagram.com/djmoblvd/
Divine Events	Catering	6630 W Arby Ave Suite 107	Las Vegas	Nevada	Las Vegas and surrounding areas	Chef-led caterer with a dedicated event planner on each booking, handling around 750 events a year including weddings.	info@divineeventslv.com	702.253.1400	https://www.divineeventslv.com	https://www.instagram.com/divineeventslasvegas/
Art of Cooking	Catering	8420 W Desert Inn Rd #1	Las Vegas	Nevada	Las Vegas and surrounding Nevada	Woman-owned, chef-driven caterer using all-natural ingredients, with bespoke wedding menus and full-service or drop-off options.	request@aoclasvegas.com	702.426.3193	https://www.aoclasvegas.com	https://www.instagram.com/artofcookinglv/
All About Catering Las Vegas	Catering	8100 W Charleston Blvd #104	Las Vegas	Nevada	Las Vegas Valley	Full-service caterer since 2011 with seasonal wedding packages, brunch menus, an in-house pastry chef and interactive food bars.	contact@cateringlv.com	(702) 300-7102	https://allaboutcateringlv.com	https://www.instagram.com/allaboutcateringlv/
Amelia C & Co	Hair & Makeup		Las Vegas	Nevada	Las Vegas hotels and venues, worldwide	Bridal hair and makeup team that styles on location for groups from elopements to large parties, in soft or full glam.			https://www.amelia-c.com	https://www.instagram.com/ameliacandco/
Rouge Hair and Makeup	Hair & Makeup	7155 S Rainbow Blvd Suite 210	Las Vegas	Nevada	Throughout Las Vegas (mobile)	Mobile bridal and corporate beauty team offering bridal packages, trials and event styling, in business for over ten years.	info@rougevegas.com	702-885-0970	https://www.rougevegas.com	https://www.instagram.com/rougevegas/
Luxury Brides Las Vegas	Hair & Makeup		Las Vegas	Nevada	Las Vegas Strip and surrounding areas	Mobile bridal hair and makeup service that comes to Strip hotels, with group packages and WhatsApp support for international couples.	Luxurybrideslv@gmail.com	702-490-9229	https://luxurybrideslv.com	https://www.instagram.com/luxury.brides.lasvegas/
Las Vegas Custom Cakes	Cake	5243 W Charleston Blvd Ste 7	Las Vegas	Nevada	Las Vegas Valley	Bespoke wedding cake bakery with a cake planner tool, gluten-free and vegan options on request, and Spanish-language service.	info@LasVegasCustomCakes.com	(702) 233-2253	https://lasvegascustomcakes.com	https://www.instagram.com/lasvegascustomcakes/
Pastry Palace Las Vegas	Cake	4523 W Sahara Ave	Las Vegas	Nevada	Las Vegas and Henderson	Custom cake bakery making tiered wedding cakes with floral detailing, with same-day delivery across the valley.	info@pastrypalacelv.com	(702) 251-1555	https://pastrypalacelv.com	https://www.instagram.com/pastrypalacelv/
Cake Designs Las Vegas	Cake	6985 W Sahara Ave #111	Las Vegas	Nevada	Las Vegas	Sisters baking custom wedding cakes daily with over two decades of experience, with a 14-business-day minimum for orders.		(702) 251-7001	https://www.cakedesignslv.com	https://www.instagram.com/lasvegascakedesigns/
Pure Light Creative	Videography		Las Vegas	Nevada	Las Vegas, Red Rock, Valley of Fire and Mount Charleston	Documentary-style wedding filmmakers since 2012, shooting unobtrusively across Strip hotels, private clubs and desert locations.	purelightcreative@gmail.com		https://www.purelightcreative.com	https://www.instagram.com/purelightcreative/
Gateway Visuals	Videography		Las Vegas	Nevada	Las Vegas, California and destination weddings	Wedding filmmakers producing documentary-style films with confessional interviews and candid dialogue in place of highlight reels.			https://www.gatewayvisuals.com	https://www.instagram.com/gateway_visuals/
Lomax Studios	Videography		Las Vegas	Nevada	Las Vegas and beyond	Studio combining wedding film and photography under one creative director, with a coordinated team and cinematic, natural direction.			https://lomaxstudios.com	https://www.instagram.com/lomax_wedding_films/
`,
  },
];

export default batches;
