import type { VendorBatch } from "@/lib/vendor-batches";

// New York vendor batches. Every row's State is "New York". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "New York City: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Christian Oth Studio	Photography		New York	New York	New York, Miami and destinations	Editorial and fine art wedding photography from a studio with decades in fashion and advertising, working in NYC, Miami and abroad.		212-634-7949	https://www.christianothstudio.com/	https://www.instagram.com/christianothstudio/
Brian Dorsey Studios	Photography	291 7th Avenue	New York	New York	New York City and destination weddings worldwide	Manhattan studio offering wedding photography and film, plus engagement portraits and mitzvah coverage, with a team of photographers.	info@briandorseystudios.com	212-227-6772	https://briandorseystudios.com/	https://www.instagram.com/briandorseystudios/
Humza Studio	Photography	777 West Merrick Rd	Valley Stream	New York	NYC, Long Island, Westchester, Hudson Valley, NJ and CT	Documentary-style photography and multi-camera wedding films, specialising in South Asian and multicultural celebrations across the five boroughs.		917-721-9814	https://www.humzastudio.com/	
Jove Meyer	Planning		New York	New York	New York City and worldwide	NYC planner and designer known for modern, LGBTQIA+ inclusive weddings for couples who want something personal and out of the ordinary.	hello@jovemeyer.com		https://jovemeyer.com/	https://www.instagram.com/jovemeyer/
Sonal J. Shah Event Consultants	Planning		New York	New York	New York, Miami and worldwide	Full-service planning and production for large-scale luxury South Asian and cross-cultural weddings, with over 20 years of multi-day events.			https://sjsevents.com/	https://www.instagram.com/sjsevents/
Just Say Yes NY	Planning		Brooklyn	New York	Brooklyn and the NYC area	Brooklyn planners offering full planning, partial planning and day-of coordination for NYC couples, including multi-day and non-traditional weddings.			https://www.justsayyesny.com/	https://www.instagram.com/justsayyesny/
Lewis Miller Design	Florals	251 West 39th St	New York	New York	New York City and Palm Beach	Garment District studio producing large-scale wedding florals plus full event design, from lighting and linens to custom dance floors.	FlowersPB@lewismillerdesign.com	212-614-2734	https://www.lewismillerdesign.com/	https://www.instagram.com/lewismillerdesign/
Rachel Cho Floral Design	Florals	33-20 48th Avenue	Long Island City	New York	New York City	Queens studio creating clean, architectural modern arrangements for weddings and events, with a local delivery shop alongside.	hello@rachelchoflowers.com	212-877-2877	https://www.rachelchoflowers.com/	https://www.instagram.com/rachelchofloral/
Stolen Magnolia	Florals	818 Wyckoff Avenue	Brooklyn	New York		Bushwick floral studio focused on custom weddings and events, with seasonal, artful designs and by-appointment pick-up.			https://www.stolenmagnolia.com/	https://www.instagram.com/stolenmagnolia/
Hank Lane Music and Productions	Music	155 E. 55th Street	New York	New York	NYC, Long Island, New Jersey, Philadelphia and South Florida	Midtown entertainment agency with over 40 years of live wedding bands, DJs and ceremony ensembles, plus staging, lighting and video production.	info@hanklane.com	212-767-0600	https://www.hanklane.com/	https://www.instagram.com/hanklanemusic/
The Shuk Music Group	Music		New York	New York	New York City and worldwide	Israeli musicians and singers playing Jewish weddings, from chuppah melodies and the hora to funk, Mizrahi and pop, in 4 to 14 pieces.	yoni@the-shuk.com	347-860-8764	https://www.the-shuk.com/	https://www.instagram.com/theshukmusicgroup/
Dhoom Events	Music		New York	New York	New York City, nationwide and destination weddings	NYC Indian wedding DJ company with over 20 years of sangeets and receptions, supplying sound, lighting and special effects too.	info@dhoomevents.com	917-444-0580	https://www.dhoomevents.com/	https://www.instagram.com/dhoomevents/
Abigail Kirsch	Catering		New York	New York	New York City, Westchester and Connecticut	Chef-led caterer with seasonal, globally inspired menus, cooking off-premise and at its own venues, Tappan Hill Mansion and The Skylark.			https://www.abigailkirsch.com/	https://www.instagram.com/abigailkirschculinary/
Great Performances	Catering	2417 3rd Avenue	Bronx	New York	New York City	Bronx-based wedding caterer whose kitchens draw on its own 60-acre organic Katchkie Farm in the Hudson Valley for seasonal produce.	celebratefood@greatperformances.com	212-727-2424	https://www.greatperformances.com/	https://www.instagram.com/gpfood/
Ginger Man Catering	Catering	445 Park Ave	New York	New York	NYC, Long Island, the Hamptons, New Jersey and Connecticut	Glatt kosher caterer cooking custom wedding menus at homes and venues across the city, Long Island, the Hamptons, NJ and CT.	info@gingermancatering.com	347-634-6227	https://www.gingermancatering.com/	https://www.instagram.com/ginger_man_kosher_catering/
[salon] 718	Hair & Makeup		Brooklyn	New York	Brooklyn neighbourhoods incl. Bay Ridge, Carroll Gardens, Dumbo and Fort Greene	Brooklyn bridal salon styling hair and makeup in the chair or on location, with boutique salon packages for the whole bridal party.			https://www.salon718.com/	
Yunimakeup	Hair & Makeup		New York	New York	New York City	Korean-American makeup artist doing on-location bridal makeup for Asian and Korean brides, from natural looks to airbrush and tattoo cover.			https://www.yunimakeup.com/	https://www.instagram.com/unis_makeup/
Ron Ben-Israel Cakes	Cake	247 West 38th St	New York	New York	East Coast, consultations nationwide	Garment District studio known for couture wedding cakes with lifelike sugar flowers, with gluten-free and vegan options.	office@weddingcakes.com	212-625-3369	https://www.ronbenisrael.com/	https://www.instagram.com/rbicakes/
By the Way Bakery	Cake	2440 Broadway	New York	New York	Manhattan, Westchester and Greenwich	Gluten-free, dairy-free bakery with kosher-certified products, making wedding cakes from its Upper West Side, Upper East Side and Hastings shops.		212-877-0806	https://www.btwbakery.com/	https://www.instagram.com/bythewaybakery/
City Cakes NY	Cake		New York	New York	New York City	Manhattan cake studio making custom wedding cakes, including sculpted and architectural designs, plus cupcakes, cookies and classes.			https://www.citycakes.com/	https://www.instagram.com/citycakes/
JS Visions Photography and Cinematography	Videography	647 Franklin Avenue	Garden City	New York	Long Island, NYC, Westchester, Hudson Valley, the Hamptons and North Fork	Garden City studio filming documentary-style weddings for over 25 years, editing in-house, with English and Spanish spoken.	info@jsvisionsphotoandvideo.com	516-280-3600	https://jsvisionsphotoandvideo.com/cinematography/	https://www.instagram.com/jsvisionsphoto/
SV Curls	Hair & Makeup	116 Elizabeth St	New York	New York	NYC and surrounding areas	Nolita salon specialising in curly hair, offering bridal styling tailored to each curl pattern, from romantic updos to loose defined curls.	sofveig08@gmail.com	646-241-5978	https://www.svcurls.com/pages/services/new-york-city-deep-bridal-hairstyles-for-curly-hair	https://www.instagram.com/svcurls/
NY Bridal Beauty	Hair & Makeup		New York	New York	New York City	Amanda Shackleton's NYC bridal hair and makeup business, styling brides and their wedding parties for the big day.	nybbnyc@gmail.com	917-334-6155	https://www.nybridalbeauty.com/	https://www.instagram.com/ashackletonnyc/
Dulcigno Wedding Films	Videography	140 Church St	New York	New York	New York, New Jersey, Florida, Hawaii and destination weddings	Lower Manhattan studio making cinematic wedding films for NYC couples and destination weddings, from Florida to Hawaii.	dulcignoweddingfilms@gmail.com		https://dulcignoweddingfilms.com/	https://www.instagram.com/dulcignoweddingfilms/
First Day Films	Videography		New York	New York	New York City and surrounding areas	NYC wedding film company with nearly two decades of experience, focusing on the moments, relationships and small details of each day.	info@firstdayfilms.com	917-568-4266	https://www.firstdayfilms.com/	https://www.instagram.com/firstdayfilms/`,
  },
  {
    name: "Hudson Valley: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Joshua Brown Photography	Photography		Newburgh	New York	Hudson Valley and Catskills	Documentary wedding photographer shooting since 1999, focused on candid moments with guests and family rather than posed set-pieces.		845-335-8688	https://joshuabrownphotography.com/	https://www.instagram.com/joshuabrownphotography/
Megan & Kenneth	Videography	333 Fishkill Ave	Beacon	New York	Hudson Valley, Catskills and Westchester	Married photo and video team filming relaxed, documentary-style wedding films alongside stills, with an openly LGBTQ+ welcoming approach.	hello@meganandkenneth.com	347-721-6862	https://meganandkenneth.com/	https://www.instagram.com/meganandkenneth/
Kimberly Coccagnia	Photography		Beacon	New York	Hudson Valley, New York City, the Hamptons and New England	Documentary wedding photographer working since 2006, published in The New York Times and Brides, who also makes heirloom photo books.			https://www.kimberlycoccagnia.com/	https://www.instagram.com/kimberlycoccagniaweddings/
Flora Good Times	Florals	197 Main St	Beacon	New York	Hudson Valley	Woman-owned Main Street flower shop and studio making playful, garden-style wedding florals with unconventional blooms and houseplants.	hello@floragoodtimes.com	845-219-5434	https://www.floragoodtimes.com/	https://www.instagram.com/floragoodtimes/
Main Course Catering + Events	Catering	175 Main St	New Paltz	New York		New Paltz restaurant and market whose catering arm handles weddings and events with seasonal menus drawn from Hudson Valley produce.		845-255-2600	https://www.maincoursecatering.com/	https://www.instagram.com/maincourse_catering/
Christofora Events	Planning	721 Broadway, Suite 245	Kingston	New York	Hudson Valley, New England and destinations	Kingston planning and design studio that scouts and styles weddings at non-traditional venues, from barns and estates to destination weekends.	angela@christoforaevents.com	845-430-6394	https://christoforaevents.com/	https://www.instagram.com/christoforaevents/
Calculated Confections	Cake		Walden	New York	Hudson Valley and tri-state area	Walden cake shop making wedding cakes, macaron towers, edible favours and full dessert tables, with complimentary tastings for couples.			https://www.calculatedconfections.com/	https://www.instagram.com/calculatedconfections/
The Blushery	Hair & Makeup	528 Main Street	Beacon	New York	Hudson Valley	Beacon makeup studio led by Stephanie Jones, offering bridal makeup in the studio or on location at Hudson Valley venues.	stephanie@theblushery.com		https://www.theblushery.com/	https://www.instagram.com/theblushery/
Marion Salon Spa	Hair & Makeup	2510 Route 44	Salt Point	New York	Salt Point, Rhinebeck, Millbrook, Pleasant Valley and Poughkeepsie	Dutchess County salon and spa sending bridal hair, airbrush makeup and trial teams on site, with a bridal retreat package in the spa.		845-635-1626	https://marionsalonspa.com/salon/bridal/	https://www.instagram.com/marionsalonspany/
MSV Entertainment	Music	396 Main St	Beacon	New York	Hudson Valley	Beacon DJ company running wedding DJ packages alongside photo booths and wedding films, from a Main Street office and event space.	Events@musicspeaksvolumes.com	845-264-0800	https://www.musicspeaksvolumes.com/	https://www.instagram.com/msv_dj_events/
Dancing Tulip Floral Boutique	Florals	114 Partition Street	Saugerties	New York	Saugerties and surrounding Hudson Valley towns	Village flower shop in Saugerties known for unusual blooms, designing custom wedding and event florals with local venues and planners.	dancingtulipfloral@gmail.com	845-247-3164	https://dancingtulipfloral.com/	https://www.instagram.com/dancingtulipfloral/
Local Lore Floral	Florals	141 Slate Quarry Rd	Rhinebeck	New York	Hudson Valley	Rhinebeck floral studio working with locally grown, seasonal flowers for natural, artistic wedding designs; now booking 2027 dates.	sonja@locallorefloral.com	845-453-8385	https://www.locallorefloral.com/	https://www.instagram.com/locallorefloral/
Common Table	Catering		Kingston	New York	Hudson Valley and New York City	Kingston boutique caterer cooking relaxed, seasonal food for weddings and gatherings, with an openly queer-friendly approach to celebrations.	hello@commontableny.com		https://www.commontableny.com/boutique-catering	https://www.instagram.com/commontableny/
Stilwell Photography and Films	Videography	15 James P. Kelly Way	Middletown	New York	Hudson Valley, Greater NYC, northern New Jersey and Connecticut	Middletown studio filming weddings and love-story films alongside photography, covering venues from Rhinebeck to Tarrytown.		845-273-3853	https://www.alisastilwell.com/	https://www.instagram.com/alisastilwell/
Beautiful Images Hair Salon	Hair & Makeup	123 Boices Lane	Kingston	New York	Ulster County and the Hudson Valley	Kingston hair salon offering wedding makeup and trials in the salon or on location, at modest per-person rates for bridal parties.	stylists@beautifulimageshairsalon.com	845-383-1852	https://www.beautifulimageshairsalon.com/makeup/	
Deising's Bakery	Cake	111 North Front St.	Kingston	New York	About 40 miles around Kingston	Kingston bakery and restaurant offering custom wedding cakes, groom's cakes and dessert tables, with design consultations and free tastings.	Deisingspics@gmail.com	845-338-7505	https://www.deisings.com/weddings/	https://www.instagram.com/deisingsbakery/
Hudson River Photographer	Photography		Rhinebeck	New York	Hudson Valley, Catskills, New York City, Litchfield and Fairfield counties and the Berkshires	LGBTQ-owned Rhinebeck studio of Diane Stredicke, who has photographed more than 350 weddings and elopements across the Hudson Valley.			https://www.hudsonriverphotographer.com/	https://www.instagram.com/hudsonriverphotographer/
DJ Lou Paris	Music	299 Main Street	Kingston	New York	Hudson Valley, Catskills, New York City and beyond	Kingston boutique wedding DJ offering ceremony audio, lighting design and custom printed details as part of an elevated reception package.		845-605-2738	https://djlouparis.com/	https://www.instagram.com/djlouparis/
DJ Sounds Unlimited	Music		Stanfordville	New York	Dutchess, Putnam, Westchester and Rockland counties plus Connecticut	Dutchess County wedding DJ service with personalised playlists, MC work and photo booth rentals, insured and running for over two decades.	DjDieter@djsoundsunlimited.com	845-278-7475	https://www.djsoundsunlimited.com/	
Nightoff Productions	Videography		Beacon	New York	Dutchess, Putnam and Ulster counties	Beacon video production company filming weddings and private events, with packages from small events to full-day coverage.	nightoffproductions@gmail.com		https://nightoffproductions.com/pages/videographer-beacon-ny	https://www.instagram.com/_nightoff_/
Silver Spoon Catering	Catering	200 E. Main Street	Mount Kisco	New York	Westchester	Chef-owned Mount Kisco caterer cooking fresh, inventive menus for Westchester weddings and private events.	Craig@SilverSpoonCateringNY.com	914-241-0955	https://silverspooncateringny.com/	
Baked by Susan	Cake	379 S. Riverside Ave.	Croton on Hudson	New York	Westchester	Croton-on-Hudson bakery making custom wedding cakes from scratch each day with all-natural and local ingredients.		914-862-0874	https://bakedbysusan.com/wedding-cakes/	https://www.instagram.com/bakedbysusan/`,
  },
  {
    name: "Buffalo: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Lovely Day Photo	Photography		Buffalo	New York	Buffalo area	Buffalo wedding and family photographer Melissa Parrish, with over twenty years behind the camera, catching both the wide view and the small details.		716.861.3459	https://www.lovelydayphoto.com/	https://www.instagram.com/lovelydayphoto/
Colin Gordon Photography	Photography		Buffalo	New York	Western New York and beyond	LGBTQ+-owned documentary wedding photographer who skips stiff posing in favour of real moments, from backyard tents to City Hall elopements.			https://colingordonphotography.com/	https://www.instagram.com/colin_patrick/
Jaimie Ellis Photography	Photography		Buffalo	New York	Buffalo, available worldwide	Woman-owned, LGBTQ+-affirming photographer specialising in elopements and intimate weddings, drawing on more than thirty years with a camera.	hello@jaimieellisphotography.com	716-361-6507	https://www.jamellisphoto.com/	https://www.instagram.com/jamellisphoto/
JH Studio Co.	Planning		Buffalo	New York	Western and Central New York	Buffalo coordinator offering day-of and month-of coordination plus custom planning, handling vendor logistics and timelines behind the scenes.	jordan@jhstudioco.com		https://www.jhstudioco.com/	https://www.instagram.com/jhstudioco/
North Park Florist	Florals	1514 Hertel Ave	Buffalo	New York	Erie and Niagara counties	Hertel Avenue flower shop that designs wedding flowers alongside its everyday arrangements and delivery across Erie and Niagara counties.		(716) 838-1123	https://www.northparkflorist.com/	https://www.instagram.com/northparkflorist/
Flowers By Nature	Florals	572 Main Street	East Aurora	New York		Main Street florist in East Aurora with a sister gift shop, Second Nature, designing wedding and event flowers as well as walk-in arrangements.	flowersbynature@gmail.com	(716) 655-4484	https://www.flowersbynature.com/your-wedding/	https://www.instagram.com/flowersbynature/
Sonic Rue	Music		Buffalo	New York		Wedding DJ and emcee led by a jazz saxophonist and band director, adding live sax, piano or band sets for ceremonies and cocktail hours.	booking@sonicrue.com	716-430-6970	https://www.sonicrue.com/	
Beloved Entertainment	Music	323 Central Ave	Lancaster	New York	Buffalo and Western New York	Lancaster DJ and audio-visual production company playing weddings across Buffalo and Western New York, with lighting and full AV.	Djbeloved@beloved-entertainment.com	716-563-6698	https://beloved-entertainment.com/	https://www.instagram.com/beloved_entertainment/
Energy Entertainment	Music		Buffalo	New York	Buffalo and Western New York	DJ and photo booth company founded in Buffalo in 2007, pairing wedding DJs with an open-air booth and custom-themed prints.	info@energyentertainmentwny.com	716-428-3472	https://www.energyentertainmentwny.com/	https://www.instagram.com/energyentertainmentwny/
The Scarlett Agency	Planning		Buffalo	New York	New York and destination events	Boutique Buffalo agency led by Kellyann Scarlett, with over seventeen years of planning and a deliberately small roster of weddings each year.	kellyscarlett@msn.com	716-228-4141	https://www.scarlettagency.com/	https://www.instagram.com/the.scarlett.agency/
Social Maven Event Co.	Planning		Buffalo	New York		Buffalo planning and design studio offering full planning, guided planning, wedding management from four months out, and design-only packages.			https://www.socialmavenbuffalo.com/	https://www.instagram.com/socialmaveneventco/
Rosalind's Catering	Catering	281 Tacoma Ave	Buffalo	New York		Buffalo caterer pitched at couples on a budget, with buffet packages that cover cake cutting, a coffee bar, linens and vegetarian entrees.	michael.cervino8@icloud.com	(716) 818-8888	https://www.rosalindscatering.com/wedding_catering	
The Grange Community Kitchen	Catering	22 Main Street	Hamburg	New York	Buffalo, Hamburg, East Aurora, Ellicottville and Cattaraugus County	Hamburg restaurant group catering weddings at partner venues across Western New York, with dinner-style service, a full bar and desserts.	info@grangecommunitykitchen.com	716-648-0022	https://www.grangecommunitykitchen.com/events	https://www.instagram.com/thegrangecommunitykitchen/
Oliver's	Catering	2095 Delaware Ave	Buffalo	New York		Delaware Avenue fine-dining restaurant dating from 1936 whose catering team handles weddings with creative, varied menus and private dining.	catering@oliverscuisine.com	716.877.9662	https://oliverscuisine.com/weddings/	https://www.instagram.com/olivers_cuisine/
Heirloom Soul Florals	Florals		Lockport	New York	Buffalo region	Lockport flower farm growing over 100 varieties regeneratively, offering loose garden-style wedding design or bulk buckets for DIY couples.	heirloomsoulflorals@gmail.com		https://www.heirloomsoul.com/	https://www.instagram.com/heirloomsoulflorals/
Blush Makeup and Hair	Hair & Makeup	184 Sweeney St	North Tonawanda	New York	Western New York, from Buffalo and Niagara Falls to Rochester and Ellicottville	North Tonawanda salon team specialising in airbrush makeup and on-location bridal styling, with extra artists so large parties avoid early starts.		(716) 873-1740	https://www.blushmakeupandhair.com/wedding-services	https://www.instagram.com/blushsalon716/
Laura Amaya Beauty	Hair & Makeup	1345 Hertel Avenue	Buffalo	New York	Buffalo and beyond	Licensed esthetician and bridal makeup artist with fifteen-plus years' experience, favouring refined, skin-first looks plus prep guidance.	info@lauraamaya.com	716-909-7404	https://www.lauraamaya.com/	https://www.instagram.com/lauraamayabeauty/
Golden Hour Hair + Beauty Salon	Hair & Makeup	818 Elmwood Avenue	Buffalo	New York		Elmwood Avenue salon of independent stylists with a dedicated bridal team, offering wedding hair and makeup in the salon or on site.		716-480-0672	https://www.goldenhourbuffalo.com/	https://www.instagram.com/goldenhourbuffalo/
Buffalo Cake Pops	Cake	27 Chandler Street	Buffalo	New York		Chandler Street bake shop known for custom cake pops, also making layered wedding cakes, cookies and full dessert tables, with free consultations.	buffalocakepops@gmail.com	(716) 240-9238	https://buffalocakepops.com/weddings/	https://www.instagram.com/BuffaloCakePops/
Ohlson's Bakery & Cafe	Cake	8500 Sheridan Drive	Buffalo	New York		Family bakery established in 1988, taking wedding consultations for two-tier cakes, cupcakes and dessert trays alongside its cafe.	ohlsonsbakery8500@gmail.com	716-626-7783	https://www.ohlsonsbakery.com/wedding-cakes	https://www.instagram.com/ohlsonsbakery/
The Village Bake Shoppe	Cake	417 Center St	Lewiston	New York		From-scratch bakery in Lewiston village making wedding cakes, simple cutting cakes with cupcake tables, and dessert-display extras like mousse cups.	calista@villagebakeshoppe.com	(716) 754-2300	https://www.villagebakeshoppe.com/	https://www.instagram.com/villagebakeshoppe/
547 Media	Videography		Buffalo	New York	Buffalo and destination weddings	Buffalo videographer making cinematic wedding films at city venues such as the Admiral Room and Avanti Mansion, delivered in eight to twelve weeks.			https://www.547media.com/	https://www.instagram.com/547media/
Black Horse Videography	Videography		Buffalo	New York	Western New York and beyond	Buffalo wedding film team run by Alyssa and Alex, with drone footage offered in most packages and travel across Western New York.			https://blackhorsevideography.com/	https://www.instagram.com/blackhorsevideography/
Nightfox Films	Videography		Jamestown	New York	Buffalo, Chautauqua Lake, Ellicottville, Erie PA and beyond	Jamestown duo filming weddings on Super 8, vintage camcorders and 4K, alone or blended into mixed-media films, with 100 travel miles included.	hello@nightfoxfilms.com		https://nightfoxfilms.com/	https://www.instagram.com/nightfox.films/`,
  },
  {
    name: "Hudson Valley: planning",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Idyllwild Event Design	Planning		Red Hook	New York	Hudson Valley, Catskills and Western Berkshires	Art-forward wedding planning, design and floral studio based in Red Hook and the Catskills, known for painterly, design-led celebrations.	HelloThere@IdyllwildEventDesign.com		https://idyllwildeventdesign.com/	https://www.instagram.com/idyllwild.events/`,
  },
];

export default batches;
