import type { VendorBatch } from "@/lib/vendor-batches";

// New Mexico vendor batches. Every row's State is "New Mexico". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Albuquerque: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alicia Lucia Collective	Photography	4619 Greene Ave NW STE A	Albuquerque	New Mexico	Southwest and destination weddings	Albuquerque and Santa Fe studio photographing weddings and elopements since 2012, with video and engagement sessions also offered.	hello@alicialucia.com		https://www.alicialucia.com/	https://www.instagram.com/alicialuciaphotos/
Photonuel	Photography		Albuquerque	New Mexico	Albuquerque and New Mexico	Emmanuel Morales shoots bold, colour-rich wedding photography across New Mexico, with galleries delivered in about three weeks.	emmanuelphotography@icloud.com	(505) 319-1691	https://photonuel.com/weddings	https://www.instagram.com/photonuel/
Guillermo Quijano Photography	Photography		Albuquerque	New Mexico	Albuquerque, Santa Fe and Northern New Mexico	Guillermo Quijano has photographed weddings across Albuquerque, Santa Fe and northern New Mexico since 2006, with packages from $2,250.	GQ@albuquerqueweddingphotographer.com	505-397-4334	https://www.albuquerqueweddingphotographer.com/	https://www.instagram.com/albuquerquephotographer/
Carissa & Ben Photography	Photography		Albuquerque	New Mexico	Albuquerque and beyond	Albuquerque husband-and-wife photographers covering weddings and LGBTQ+ celebrations with a relaxed, inclusive approach to portraits.	info@carissaandben.com		https://carissaandben.com/	
Just Lovely Wedding & Event Planning	Planning		Albuquerque	New Mexico		Lauren Waller's Albuquerque planning firm, running since 2014, offering partial planning and month-of coordination for New Mexico weddings.			https://www.justlovelyweddings.com/	https://www.instagram.com/justlovelyweddings/
Champagne Events	Planning		Albuquerque	New Mexico	New Mexico and surrounding states	Mariah Encinias's mobile Albuquerque planning team offering day-of coordination through to full planning, with vendor selection support.	champagneeventsnm@gmail.com	505-585-2303	https://www.champagneeventsnm.com/	https://www.instagram.com/champagne_eventsnm/
Danielle Marisa Weddings & Events	Planning		Albuquerque	New Mexico	Albuquerque, Santa Fe and Taos	Owner-led planning for weddings, elopements and micro weddings in Albuquerque, Santa Fe and Taos, from full planning to day-of coordination.	hello@daniellemarisa.com	505.715.2953	https://www.daniellemarisa.com/	https://www.instagram.com/daniellemarisaevents/
Flowers from Kara	Florals		Albuquerque	New Mexico	Albuquerque and surrounding areas	Eco-minded Albuquerque florist designing wedding and elopement flowers with locally sourced stems, from intimate events to large celebrations.			https://www.flowersfromkara.com/	https://www.instagram.com/flowersfromkara/
Florecita Flowers	Florals	3600 Osuna Rd NE Suite 313	Albuquerque	New Mexico		Albuquerque studio selling wedding flowers a la carte in curated colour palettes, suited to elopements, showers and budget-minded weddings.	hola@florecitaflowers.com	(505) 595-7044	https://www.florecitaflowers.com/	https://www.instagram.com/florecitaflowers_nm/
Albuquerque Florist	Florals	3121 San Mateo Blvd NE	Albuquerque	New Mexico		Long-running Albuquerque flower shop with two locations, designing wedding and event arrangements in house alongside same-day local delivery.		(505) 881-3336	https://www.albuquerqueflorist.com/	
Floriography	Florals		Santa Fe	New Mexico	Santa Fe, Albuquerque and greater New Mexico	Farmer-florist studio using its own and locally grown blooms, desert botanicals and native plants for weddings across New Mexico.	hello@floriographyflowers.com	505-819-3865	https://www.floriographyflowers.com/	https://www.instagram.com/floriography_flowers/
Cutmaster Music	Music	2430 Midtown Place NE Ste C	Albuquerque	New Mexico	Albuquerque and Santa Fe	Independent Albuquerque DJ company with a team of DJs who plan the reception with the couple and MC the night from first dance to send-off.	info@cutmastermusic.com	(505) 508-3489	https://www.cutmastermusic.com/	https://www.instagram.com/cutmastermusic/
Sound Productions DJ and MC Service	Music		Rio Rancho	New Mexico	Rio Rancho and Albuquerque	Rio Rancho DJ and MC service whose DJs work fluently in English and Spanish, suited to bilingual and Hispanic wedding receptions.		(505) 352-0609	https://thedjmatt.com/	https://www.instagram.com/soundproductionsdj/
Styles DJ Services	Music		Albuquerque	New Mexico	Albuquerque and Rio Rancho	Mobile DJ and MC service for Albuquerque and Rio Rancho weddings, with photo booth and uplighting available as add-ons.	stylesdjservices@gmail.com	505.304.0590	https://www.stylesdjservices.com/	
Red Sapphire DJ Services	Music		Albuquerque	New Mexico	Albuquerque, Santa Fe and towns across New Mexico	Albuquerque DJ service playing weddings, school dances and company events across New Mexico, bookable by call or text.		505-614-5627	https://www.dj-albuquerquered.com/	
M'Tucci's Catering	Catering		Albuquerque	New Mexico	Albuquerque and Rio Rancho	Catering arm of the local M'Tucci's Italian restaurants, offering full-service menus and event management for Albuquerque and Rio Rancho weddings.	catering@mtuccis.com	(505) 350-0019	https://www.mtuccis.com/catering/	https://www.instagram.com/mtuccis_catering/
Slate Street Cafe Catering	Catering	515 Slate Ave NW	Albuquerque	New Mexico		Downtown Albuquerque cafe providing full-service catering for wedding receptions, and on the caterer lists of several local venues.	dine@slatestreetcafe.com	(505) 243-2210	https://www.slatestreetcafe.com/catering	https://www.instagram.com/slatestreetcafe/
Garcia's Kitchen Catering	Catering		Albuquerque	New Mexico		Albuquerque New Mexican restaurant family catering weddings with red and green chile dishes, from drop-off to fully staffed set-up and clean-up.		(505) 242-1199	https://www.garciaskitchen.com/catering	https://www.instagram.com/garciaskitchen/
ABC Cake Shop & Bakery	Cake	1830 San Pedro Dr NE	Albuquerque	New Mexico	Albuquerque metro and statewide delivery	Albuquerque bakery making custom wedding cakes with tastings and consultations, plus biscochitos, cupcakes and pastries for dessert tables.	info@abccakeshop.com	(505) 255-5080	https://www.abccakeshop.com/	https://www.instagram.com/abccakeshop/
The Cake Boutique	Cake	3250 Coors Blvd NW Suite F	Albuquerque	New Mexico		Locally owned Westside Albuquerque bakery focused on wedding and custom cakes, with cookies, cupcakes and mini desserts, by appointment.	admin@thecakeboutiqueabq.com	505-833-1170	https://www.thecakeboutiqueabq.com/	
Sierra Sunrise Goods	Cake	318 Isleta Blvd SW Ste 311	Albuquerque	New Mexico	Albuquerque and Rio Rancho	Allergy-friendly Albuquerque bakery making gluten-free, plant-based custom cakes and dessert catering for weddings and events.	sierrasunrisegoods@gmail.com	505-218-1274	https://www.sierrasunrisegoods.com/	https://www.instagram.com/sierrasunrisegoods/
Betty Rose by Alanna	Hair & Makeup		Albuquerque	New Mexico		Albuquerque bridal hair and makeup team offering in-studio trials and on-site wedding-day styling, plus spray tans and blow-outs.	alanna@bettyrose.com	505.315.6410	https://bettyrose.com/	https://www.instagram.com/bettyrosebyalanna/
Kata Baron	Hair & Makeup		Albuquerque	New Mexico		Makeup artist splitting time between Albuquerque and Los Angeles, bringing film and editorial experience to bridal and wedding makeup.	hello@katabaron.com	(505) 203-3565	https://www.katabaron.com/	https://www.instagram.com/katamakeup/
Brandon Handy Weddings	Videography		Albuquerque	New Mexico	New Mexico, Texas, Colorado and neighbouring states	Albuquerque wedding videographers making story-driven films, with more than 100 weddings filmed across New Mexico and nearby states.	BrandonHandyMedia@gmail.com		https://www.brandonhandyweddings.com/new-mexico	https://www.instagram.com/brandonhandyweddings/
Luminance Wedding Films	Videography		Albuquerque	New Mexico	Albuquerque, Santa Fe and destination weddings	Husband-and-wife film team based in New Mexico since 2006, making cinematic wedding films locally and at destination weddings.		505.301.1668	https://www.luminanceweddingfilms.com/	https://www.instagram.com/luminanceweddingfilms/
CinemaBooth	Videography		Albuquerque	New Mexico	Albuquerque and Santa Fe	Albuquerque studio filming cinematic wedding and event videos, with photography also available, across Albuquerque and Santa Fe.			https://www.cinemabooth.llc/	https://www.instagram.com/cinemaboothllc/
`,
  },
  {
    name: "Santa Fe: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Suroeste Studios	Photography		Santa Fe	New Mexico	Santa Fe and the American West	Photography and video team based out of Santa Fe, shooting wedding love stories and editorial work across the American West.			https://www.suroestestudios.com/	https://www.instagram.com/suroestebyfrankiegomez/
Weckmann Photography	Photography		Santa Fe	New Mexico	Santa Fe and northern New Mexico	Santa Fe photographer shooting weddings, couples, families and portraits, with finished galleries delivered a few weeks after the day.	weckmannphotography@gmail.com	(505) 948-0093	https://www.weckmannphotography.com/	https://www.instagram.com/weckmannphotography/
Maura Jane Photography	Photography		Santa Fe	New Mexico	Santa Fe, Albuquerque and destination weddings	Santa Fe wedding photographer, also working in Albuquerque and at destination weddings, with a romantic, timeless and whimsical style.			https://maurajanephotography.com/	https://www.instagram.com/maurajanesphoto/
La Luz Weddings & Events	Planning		Albuquerque	New Mexico	Albuquerque, Santa Fe, the Southwest and destinations	Albuquerque planning company founded in 2010, planning New Mexico, Santa Fe, Southwest and destination weddings with a relaxed, fun approach.	hello@laluzevents.com	505.226.2224	https://www.laluzevents.com/	https://www.instagram.com/laluzweddingsandevents/
Shelby Your Day Events	Planning		Santa Fe	New Mexico	Albuquerque, Santa Fe, Taos and southern Colorado	Santa Fe wedding planner Shelby Spoonhoward, offering planning and coordination in northern New Mexico and for destination weddings worldwide.			https://www.shelbyyourday.com/	https://www.instagram.com/shelbyyourdayevents/
Verdeaux & Co	Planning		Santa Fe	New Mexico	Santa Fe, New Mexico and destination weddings	Santa Fe wedding planner and designer curating meaningful destination weddings for couples from across the US and abroad.	hello@verdeauxandco.com	(505) 393-3634	https://verdeauxandco.com/	https://www.instagram.com/verdeauxandco/
Artichokes & Pomegranates	Florals	418 Cerrillos Road Ste 1-C	Santa Fe	New Mexico	Santa Fe and surrounding area	Santa Fe floral design studio making custom flowers for weddings and events since 1995, with daily flower delivery across the area.	info@artichokesandpomegranates.com	505.820.0044	https://artichokesandpomegranates.com/	https://www.instagram.com/artichokes.and.pomegranates/
Renegade Floral	Florals		Santa Fe	New Mexico	Santa Fe and northern New Mexico	Event florist Melissa Paquin creates colour- and texture-led floral designs for Santa Fe weddings and special occasions.	hello@renegadefloral.com	505.930.9495	https://www.renegadefloral.com/	https://www.instagram.com/renegadefloral/
All The Pretty Flowers	Florals	313 Camino Alire Studio 107	Santa Fe	New Mexico	Santa Fe	Locally owned Santa Fe floral boutique at Dragonstone Studios, doing wedding and event flowers with local stems where possible and composting its waste.		505.204.3643	https://alltheprettyflowers.com/	https://www.instagram.com/alltheprettyflowersinsantafe/
Mariachi Albuquerque	Music		Albuquerque	New Mexico	Santa Fe, Las Cruces, Rio Rancho and statewide	Albuquerque mariachi ensemble in charro dress, playing weddings and quinceañeras across New Mexico in full-band or trio formats, in English and Spanish.	mariachialbuquerque@gmail.com	505-715-8367	https://mariachialbuquerque.com/	https://www.instagram.com/mariachi.albuquerque/
Deja Blu Band	Music		Santa Fe	New Mexico	Santa Fe and Albuquerque	Dance and party band with trio, quartet and full-band ensembles for wedding ceremonies and receptions, having played the Inn of Loretto and Hyatt Tamaya.	band@dejabluband.com	(303) 517-9852	https://dejabluband.com/santa-fe-albuquerque-wedding-dance-bands/	https://www.instagram.com/dejabludanceband/
Tomasita's	Catering	500 S Guadalupe St	Santa Fe	New Mexico	Santa Fe and Albuquerque	Santa Fe New Mexican restaurant offering full-service wedding catering with buffet set-up, service and clean-up, plus family-style red and green chile trays.		505-983-5721	https://tomasitas.com/catering/	
Net Zero Ranch	Catering		Sapello	New Mexico	Santa Fe, Taos and northern New Mexico	Wood-fired wedding caterer sourcing from regenerative New Mexico ranches, with charro buffet and live-fire asado menus and a no-trace approach.			https://netzeroranch.com/	https://www.instagram.com/netzeroranch/
Walter Burke Catering	Catering	1209 Calle de Commercio	Santa Fe	New Mexico	Santa Fe and northern New Mexico	Full-service Santa Fe caterer doing seasonal contemporary menus for weddings and events, from formal galas to backyard barbecues.		(505) 473-9600	https://walterburkecatering.com/	https://www.instagram.com/walterburkecatering/
A Cake Odyssey	Cake	1430 2nd Street	Santa Fe	New Mexico	Santa Fe	Family-run Santa Fe bakery making custom wedding cakes with a Southwestern flair, plus cupcakes, pies and cookies, with tastings by appointment.	hello@acakeodyssey.com	(505) 982-2253	https://www.acakeodyssey.com/	
Crumb Girl Sweets	Cake		Santa Fe	New Mexico	Santa Fe and Albuquerque area	Santa Fe bakery making custom wedding cakes, with birthday cakes, baked goods and dessert catering also available.			https://www.crumbgirlsweets.com/	
Madeline McCue Makeup	Hair & Makeup		Santa Fe	New Mexico	Santa Fe, Albuquerque and Taos	Santa Fe makeup artist with film and commercial credits who also offers bridal hair and makeup for New Mexico weddings.	madelinemccuemakeup@gmail.com	646-354-9755	https://www.madelinemccuemakeup.com/	https://www.instagram.com/madelinemccue.makeup/
Viva Grace Makeup	Hair & Makeup		Taos	New Mexico	Taos, northern New Mexico and destination	Taos makeup artist Juliette Peralta offering bridal and wedding makeup that enhances natural features, with travel available for destination weddings.	juliette@vivagracemakeup.com	575-779-9994	https://vivagracemakeup.com/	https://www.instagram.com/vivagracemakeup/
The Beauty Collective	Hair & Makeup	501 Franklin Avenue	Santa Fe	New Mexico	Santa Fe and New Mexico	Santa Fe salon with a team of stylists offering bridal hair and makeup, plus spa services, for weddings.	thebeautycollectivesantafe@gmail.com	505-428-9522	https://www.thebeautycollectivesantafe.com/	https://www.instagram.com/thebeautycollectivesantafe/
LJM Films	Videography		Santa Fe	New Mexico	Santa Fe and destination weddings	Santa Fe videographer Luke McDonald, making cinematic wedding films for local and destination couples and based between Santa Fe and Aspen.	luke.ljmfilms@gmail.com	(505) 554-0560	https://ljmfilms.com/	https://www.instagram.com/ljm_films/
Southwest Wedding Films	Videography		Rio Rancho	New Mexico	New Mexico, Santa Fe, Colorado, Arizona and Texas	Rio Rancho wedding videographers making cinematic films, with Santa Fe weddings and elopements in their portfolio and travel across the Southwest.			https://southwestweddingfilms.com/	https://www.instagram.com/southwestweddingfilms/
Weird Bird Music	Music		El Prado	New Mexico	Taos and northern New Mexico	Taos-area live music company supplying bands, musicians, DJs and silent discos for weddings, with set wedding packages and an intake form.	weirdbirdmusic@gmail.com		https://weirdbirdmusic.com/	
Jessica Ash + Co.	Videography		Albuquerque	New Mexico	New Mexico including Santa Fe and Taos, plus destinations	Wedding and elopement photography company that also films weddings, working across New Mexico venues from Santa Fe to Ruidoso and at destinations.			https://jessash.com/albuquerque-wedding-videography	https://www.instagram.com/jessashphotos/
That Cake Lady of Santa Fe	Cake		Santa Fe	New Mexico	Santa Fe	Santa Fe home baker making custom wedding cakes from $100, with consultation sessions that include flavour tastings and a design walk-through.	thatcakeladysf@gmail.com	505-303-0686	https://5e966e35924e4.site123.me/	https://www.instagram.com/thatcakeladysantafe/
`,
  },
  {
    name: "Albuquerque: hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mayra's Hairstyles	Hair & Makeup		Albuquerque	New Mexico	Albuquerque	On-location Albuquerque bridal hairstylist for glamorous and romantic wedding styles, who also does makeup and quinceañera hair.			https://mayrashairstyles.com/	https://www.instagram.com/mayrashairstyles/
`,
  },
];

export default batches;
