import type { VendorBatch } from "@/lib/vendor-batches";

// New Hampshire vendor batches. Every row's State is "New Hampshire". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Portsmouth: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Flower Kiosk	Florals	61 Market Street	Portsmouth	New Hampshire	NH seacoast	Woman-owned florist in downtown Portsmouth since 1986, designing natural, seasonal wedding flowers with free consultations.	info@flowerkiosk.com	603-436-1234	https://www.flowerkiosk.com/weddings	https://www.instagram.com/flowerkiosk/
Jardiniere Flowers	Florals	28 Deer Street, Suite 101	Portsmouth	New Hampshire	Seacoast of Maine and New Hampshire	Family-owned Portsmouth florist founded in 1993, doing bouquets, arches and centrepieces for weddings along the seacoast.		603-427-5560	https://www.jardiniereflowers.com/	https://www.instagram.com/jardiniereflowers/
Brass Tacks Photography	Photography	401 The Hill	Portsmouth	New Hampshire	New Hampshire, Boston and Maine	Portsmouth studio photographing weddings and engagements in a creative, candid style across New Hampshire, Maine and Boston.		978-886-1148	https://www.brasstacksphotography.com/	https://www.instagram.com/brasstacksphotography/
Lauren Wilson Events	Planning		Stratham	New Hampshire	New Hampshire Seacoast, coastal Maine and Massachusetts North Shore	Full-service wedding planning and design from Stratham, from venue sourcing to month-of coordination on the seacoast.	lauren@laurenwilsonevents.com	978-228-1152	https://www.laurenwilsonevents.com/	https://www.instagram.com/laurenwilsonevents/
Great Circle Catering	Catering	282 Corporate Dr, Unit 4	Portsmouth	New Hampshire	Southern Maine, northern Massachusetts and west to Concord NH	Portsmouth caterer with a decade of events, cooking menus from Mediterranean and Indian to seafood, with vegan and gluten-free options.	info@greatcirclecatering.com	603-422-5502	https://www.greatcirclecatering.com/	https://www.instagram.com/greatcirclecatering/
Vibe Wedding Films	Videography		Portsmouth	New Hampshire	New Hampshire, Maine, Rhode Island and beyond	Portsmouth film team making cinematic wedding films that weave the day's audio and small moments into a lasting story.			https://www.vibeweddingfilms.com/	https://www.instagram.com/vibeweddingfilms/
Solstice Planning Studio	Planning		Dover	New Hampshire	New Hampshire, Maine, Massachusetts and Vermont	Dover planner offering full, partial and wedding-management packages, with a hospitality-first approach shaped by years in service.	danielle@solsticeplanningstudio.com		https://www.solsticeplanningstudio.com/	
Bold Hearts Studio	Hair & Makeup	3 Front Street, 400B	Rollinsford	New Hampshire		Rollinsford hair studio doing colour, extensions and wedding hair, booked through a small, personal salon near Dover.	boldheartsstudio@gmail.com	603-845-9259	https://www.boldheartsstudio.com/	https://www.instagram.com/boldheartsstudio/
Anser Luna Strings	Music		Stratham	New Hampshire	Seacoast New Hampshire, Massachusetts, Maine and greater New England	Seacoast cello duo playing classical, traditional and pop for ceremonies and cocktail hours, with custom arrangements on request.	anserlunastrings@gmail.com	603-205-3844	https://anserluna.com/	https://www.instagram.com/anserlunastrings/
BTE Entertainment	Music		Wakefield	New Hampshire	New England, including Massachusetts, New Hampshire, Maine and Vermont	New Hampshire DJ and MC company with over 25 years of weddings, adding lighting, laser shows and video dance parties.	event@btedjs.com	603-427-0174	https://btedjs.com/	
Silver Street Flower Farm	Florals		Dover	New Hampshire		One-acre urban flower farm and design studio in Dover, growing its own blooms for foam-free, low-waste wedding flowers.			https://www.silverstreetflowerfarm.com/weddings	https://www.instagram.com/silverstreetflowerfarm/
Lockwood Photo + Film	Videography		Portsmouth	New Hampshire	New Hampshire Seacoast, coastal Maine and beyond	Portsmouth team filming and photographing weddings in a natural, warm style, focused on the unposed moments between the big ones.			https://www.lockwoodphotoandfilm.com/	https://www.instagram.com/lockwoodphotoandfilm/
Three Sisters Cake Shop	Cake	One Washington St., Suite 3142	Dover	New Hampshire		Dover cake shop run by three sisters, baking custom-order wedding cakes, cupcakes and cookies with tastings by appointment.	info@threesisterscakeshop.com	603-834-9978	https://www.threesisterscakeshop.com/	https://www.instagram.com/threesisterscakeshop/
My Friend's Bakery	Cake	96A Hayes Rd.	Madbury	New Hampshire		Madbury cake studio founded in 2008 by a Johnson & Wales-trained pastry chef, making scratch wedding cakes and dessert tables.	info@myfriendsbakery.com	603-509-2260	https://www.myfriendsbakery.com/	https://www.instagram.com/myfriendsbakerynh/
Sweetened Memories	Cake	13 Jenkins Ct. Ste 120	Durham	New Hampshire		Small-batch Durham bakery making tiered wedding cakes, custom designs and cupcake displays, with gluten-free options.	alaina@sweetenedmemories.com	603-868-7253	https://sweetenedmemories.com/	https://www.instagram.com/sweetenedmemoriesnh/
Chill Catering	Catering	580 US-1 BYP	Portsmouth	New Hampshire	Portsmouth NH and New England	Portsmouth caterer covering plated wedding dinners as well as lobster bakes, barbecues and pig roasts for relaxed receptions.		877-244-5575	https://www.chillcatering.com/	https://www.instagram.com/chillcatering/
The White Apron	Catering	1 Washington Place, Suite 1124	Dover	New Hampshire	NH seacoast	Dover caterer since 2004 writing bespoke fine-dining wedding menus around seasonal and foraged ingredients, with wine pairing.	info@thewhiteapron.com	603-617-3555	https://www.thewhiteapron.com/	https://www.instagram.com/thewhiteapron/
Making Faces Weddings	Hair & Makeup		Portsmouth	New Hampshire	Seacoast of New Hampshire, Maine, Vermont and Massachusetts	Portsmouth makeup artist doing on-location bridal makeup at venues and getting-ready suites across the seacoast and New England.	makingfacesweddings@gmail.com		https://www.makingfacesweddings.com/	https://www.instagram.com/makingfacesweddings/
Mike Sears Photography	Photography		Exeter	New Hampshire	New Hampshire, Maine, Vermont and Massachusetts	Exeter photographer with over 400 weddings behind him, shooting honest, unobtrusive documentary coverage with a film-inspired feel.			https://mikesearsphotography.com/	https://www.instagram.com/mikesearsphotography/
Dragonfly Photography	Photography	36 Maplewood Ave	Portsmouth	New Hampshire	Seacoast from Portsmouth to Kittery, York, Ogunquit and Kennebunkport	Downtown Portsmouth studio photographing weddings and families in a relaxed, natural documentary style along the NH and Maine coast.		978-857-2088	https://www.dragonflyshots.com/	https://www.instagram.com/dragonflyshots/
Vanity Hair Studio	Hair & Makeup	44 Dover Point Road, Unit H	Dover	New Hampshire	NH seacoast, with travel beyond 30 miles for a mileage fee	Dover salon doing bridal hair and airbrush makeup in studio or on location, with trials and a getting-ready space for the party.	weddings.vanityhairstudio@gmail.com	603-430-8689	https://vanityhairstudionh.com/pages/wedding	https://www.instagram.com/vanity.hairstudio.nh/
Seacoast DJ	Music		Hampton	New Hampshire	New Hampshire and Massachusetts Seacoast, and across New England	Hampton DJ and MC with 200-plus weddings, mixing live on turntables to read the room rather than running a fixed playlist.		603-608-8790	https://seacoastdj.com/	https://www.instagram.com/seacoastdj/
Robert Ortiz Photography	Videography		Portsmouth	New Hampshire	New England and destination weddings	Portsmouth studio with 20 years in weddings, pairing documentary black-and-white and colour photography with a wedding video team.	robcam@ttlc.net		https://www.robertortizphotography.com/	https://www.instagram.com/robertortizweddingphotography/
Cameron & Co. Events	Planning		Newmarket	New Hampshire	New Hampshire seacoast and southern Maine	Seacoast planning studio offering full planning, coordination and design, aiming for weddings that feel natural rather than overproduced.			https://cameronandcoevents.com/	`,
  },
];

export default batches;
