import type { VendorBatch } from "@/lib/vendor-batches";

// North Carolina vendor batches. Every row's State is "North Carolina". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Charlotte: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Bhowmik Dave Films & Photography	Photography	101 N Tryon St Suite 6000	Charlotte	North Carolina	Charlotte, NC and worldwide	Charlotte photo and film studio specialising in South Asian weddings, with colourful multi-day coverage, pre-wedding shoots and albums.	contact@bdfilms.photography	(980) 446-9449	https://bdfilms.photography	https://www.instagram.com/bhowmikdavefilms.photo/
Casey Hendrickson Photography	Photography		Charlotte	North Carolina	East Coast and beyond	Fine-art, documentary-leaning wedding photographer working since 2011, known for classic, true-to-colour images and heirloom albums.			https://www.caseyhphotos.com	https://www.instagram.com/caseyhphotos/
Kevyn Dixon Photography	Photography		Charlotte	North Carolina	Charlotte area	Warm, relaxed Charlotte wedding photographer with a decade of experience, often at uptown hotels, country clubs and Lake Norman estates.	hello@kevyndixonphoto.com		https://kevyndixonphoto.com	https://www.instagram.com/kevyndixonphoto/
Jenkins & Co. Weddings	Planning		Charlotte	North Carolina	Charlotte and throughout the US	Full-service planning and design firm for multi-day wedding weekends, handling stationery, guest hospitality, welcome parties and farewell events.	Sacoya@jenkinsandcoweddings.com	(704) 281-1589	https://www.jenkinsandcoweddings.com	https://www.instagram.com/jenkinsandcoweddings/
J'adore Jay Weddings	Planning		Charlotte	North Carolina	Charlotte and the Southeast	Charlotte planner offering full-service planning and wedding-day management for couples after a personal, detail-led celebration.	info@jadorejay.com		https://jadorejay.com	https://www.instagram.com/jadorejayweddings/
Proper Flower	Florals		Charlotte	North Carolina		Charlotte floral studio with a sustainability focus, designing weddings of every size alongside event florals, interiors and hands-on workshops.	hello@properflower.com		https://www.properflower.com	https://www.instagram.com/properflower/
IRIS Blossom	Florals		Charlotte	North Carolina	Charlotte, South Florida and destinations	Charlotte florist known for bespoke, colour-led luxury arrangements, handling wedding design, setup and teardown with locally and internationally sourced stems.	info@irisblossomclt.com	(704) 593-6669	https://www.irisblossomclt.com/events	https://www.instagram.com/irisblossomclt/
Carey Roberts Design Co.	Florals	34 E. Woodrow Ave.	Belmont	North Carolina		Appointment-only boutique studio west of Charlotte creating classic wedding and event florals, from intimate dinners to large receptions.	carey@careyrobertsdesign.com	(704) 718-6987	https://www.careyrobertsdesign.com	https://www.instagram.com/careyrobertsdesign/
Carolina Royal Strings	Music		Charlotte	North Carolina	North and South Carolina	Charlotte string ensemble playing since 2010, offering solo to quartet line-ups with classical pieces, pop covers and Broadway for ceremonies.			https://www.carolinaroyalstrings.com	https://www.instagram.com/carolina_royal_strings/
Bunn DJ Company	Music	1026 Jay St B238	Charlotte	North Carolina	Western North Carolina incl. Charlotte, Asheville, Boone and Mooresville	Locally owned DJ and MC team with a Charlotte office, known for mixing that keeps dance floors full and for detailed timeline planning.		(704) 494-7333	https://bunndjcompany.com/charlotte-wedding-djs	https://www.instagram.com/bunndjclt/
Melonbelly Music	Music		Charlotte	North Carolina	Within about 4 hours of Charlotte (NC, SC, GA, TN, VA)	Charlotte acoustic guitar duo with vocal harmonies, playing bluegrass, beach, Motown and classic rock for ceremonies, with DJ and MC services included.			https://www.melonbellymusic.com	https://www.instagram.com/melonbellymusic/
Something Classic	Catering	1860 Lindbergh St.	Charlotte	North Carolina	Charlotte and surrounding areas	Woman-owned Charlotte caterer of 30-plus years with farm-to-table menus, plated or buffet service, plus staffing, rentals and event coordination.	jill@somethingclassic.com	(704) 377-4202	https://www.somethingclassic.com	https://www.instagram.com/somethingclassiccharlotte/
Sonaa Weddings + Events	Planning		Charlotte	North Carolina		Charlotte planning team founded in 2017, specialising in South Asian and Hindu weddings, from venue and vendor selection to multi-day event execution.			https://www.sonaaevents.com	https://www.instagram.com/sonaaevents/
Plate Perfect Catering	Catering	601 S Kings Dr. Suite AA	Charlotte	North Carolina	The Carolinas	Charlotte caterer since 1992 serving menus from its sister restaurants, including Midwood Smokehouse barbecue, Calle Sol Cuban and Mama Ricotta’s Italian.		(704) 343-0155	https://plateperfectcatering.com	https://www.instagram.com/plateperfectcatering/
Cali Stott Artistry	Hair & Makeup		Stallings	North Carolina	Greater Charlotte, on location	Hair and makeup team working since 2010 with artists of varied backgrounds, offering bridal trials, airbrush, lashes and on-location wedding-party styling.	hello@calistottartistry.com	(801) 882-5429	https://www.calistottartistry.com	https://www.instagram.com/calistottartistry/
Beauty Asylum	Hair & Makeup		Charlotte	North Carolina	Charlotte, Atlanta, Charleston and destinations	Large on-site wedding beauty team with 16-plus years and over a thousand weddings, ranging from soft, natural looks to full glam with airbrush.			https://www.beautyintervention.com	https://www.instagram.com/beautyasylum/
Renaissance Patisserie	Cake	6401 Carnegie Blvd #4A	Charlotte	North Carolina		SouthPark French patisserie founded in 2013, baking traditional French pastries and custom wedding cakes and dessert spreads to order.	renaissancepatisserie@gmail.com	(980) 819-8771	https://www.renaissancepatisserie.com	https://www.instagram.com/renaissancepatisserie/
August June Desserts	Cake		Charlotte	North Carolina	Charlotte and surrounding areas	Boutique Charlotte cake studio since 2010 making scratch-baked wedding cakes and gourmet cupcakes, known for minimalist designs and unusual flavours.	info@augustjunedesserts.com	(704) 594-5283	https://www.augustjunedesserts.com	https://www.instagram.com/augustjunedesserts/
Suárez Bakery	Cake	4245 Park Rd	Charlotte	North Carolina		Family scratch bakery in Park Road Shopping Center since 1992; no tiered cakes, but couples pre-order a spread of single-tier cakes, including tres leches.	hello@suarezbakery.com	(704) 525-0145	https://www.suarezbakery.com/made-to-order-cakes	https://www.instagram.com/suarezbakery/
Victor Films	Videography		Charlotte	North Carolina	Charlotte and destinations	Charlotte luxury wedding film team using two cinematographers and mic’d vows and speeches to build unscripted, story-led films.	hello@victorfilms.co		https://www.victorfilms.co	https://www.instagram.com/victorfilms.co/
Blacksmith Media Group	Videography		Charlotte	North Carolina	North Carolina, South Carolina and Tampa, FL	Couple-owned Charlotte video studio filming weddings at accessible prices, with cinematic highlight films alongside real estate and commercial work.	info@blacksmithmediagroup.com		https://www.blacksmithmediagroup.com	https://www.instagram.com/bsmithmedia/
Handiwork Media	Videography		Charlotte	North Carolina	Charlotte, NC and beyond	Charlotte production studio since 2017 making cinematic, unobtrusive wedding films in three collection tiers, alongside brand and documentary work.	hello@handiworkmedia.com	(980) 213-8884	https://handiworkmedia.com/charlotte-wedding-videographer/	
Laura R. Artistry	Hair & Makeup		Charlotte	North Carolina		Charlotte makeup artist with film and commercial experience, offering natural, personalised bridal makeup in studio or on location.			https://makeupincharlotte.com	https://www.instagram.com/laurarartistry/`,
  },
  {
    name: "Raleigh–Durham: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Joe Payne Photography	Photography	509 W North St	Raleigh	North Carolina	Raleigh, Durham, Chapel Hill and across North Carolina	British-born photographer blending documentary coverage with artistic portraits, shooting Triangle weddings since 2008 with a second shooter included.	info@joesphoto.com	919-397-4889	https://joepayneweddingphotography.com	https://www.instagram.com/joepaynephoto/
Slauer Events & Design	Planning		Raleigh	North Carolina	Raleigh, Durham and Chapel Hill	Woman-owned Triangle planning team led by Rachel Slauer, offering full planning, custom packages and event-management coordination.	rachel@slauerevents.com	770-715-1096	https://slauerevents.com	https://www.instagram.com/slauerevents/
Vow & Verve	Planning		Raleigh	North Carolina	Raleigh and destination weddings	Raleigh planning and design studio offering high-touch full planning, vendor curation and day-of coordination, with 100+ weddings behind it.			https://vowandverve.com	https://www.instagram.com/vowandverve/
Uthsaav	Planning		Cary	North Carolina	Cary and nationwide	Cary planners specialising in Indian, South Asian and multicultural weddings, handling design, vendor management and full multi-day execution.	uthsaav@gmail.com	919-694-3748	https://uthsaav.com	https://www.instagram.com/uthsaav/
Carolina Elite Events	Videography		Cary	North Carolina	The Carolinas and beyond	Cary production company filming South Asian and fusion weddings, pairing cinematography with photography, DJ, lighting and live streaming.			https://carolinaeliteevents.com/weddings	https://www.instagram.com/carolinaeliteevents/
Jesse Adair Photography	Photography		Raleigh	North Carolina	Raleigh, North Carolina and destination weddings	Raleigh photographer taking a limited number of weddings each year, focused on relaxed documentary coverage and gently guided portraits.	jesseadairphotos@gmail.com		https://jesseadairphotography.com	https://www.instagram.com/jesseadairphotography/
Amy Ellis Photography	Photography		Raleigh	North Carolina	Raleigh, Durham, Chapel Hill, Charlotte and the East Coast	Raleigh documentary photographer who tells the story of the day through candid moments, from house-rental weddings to grand hotel receptions.			https://amyellisphotography.com	https://www.instagram.com/amyellisphoto/
Fresh Affairs	Florals	4724-116 Hargrove Rd	Raleigh	North Carolina	Raleigh, Durham, Chapel Hill and the Triangle	Long-standing Raleigh floral and event design studio creating bouquets, ceremony aisles, altar pieces and reception centrepieces.	info@freshaffairs.com	919-954-0808	https://freshaffairs.com	https://www.instagram.com/freshaffairs/
The Skinny Vase	Florals		Raleigh	North Carolina	Raleigh and regional weddings	Raleigh floral studio run by Jaclyn Pline, designing wearable florals, aisle pieces and table centrepieces for luxury weddings.	theskinnyvase@gmail.com	(410) 458-6993	https://theskinnyvase.com	
Xela Florals	Florals		Durham	North Carolina		Durham floral designer offering full-service wedding flowers plus an a la carte menu suited to micro-weddings, elopements and DIY couples.			https://www.xelaflorals.com	https://www.instagram.com/xelaflorals/
DJ Stephen Downing	Music		Hillsborough	North Carolina	Raleigh, Durham, Chapel Hill, the Triangle and Triad	Hillsborough wedding DJ and MC who mixes live to read the room, with ceremony sound, uplighting and photo booth add-ons.			https://www.djstephendowning.com	https://www.instagram.com/djstephendowning/
Magnolia String Quartet	Music		Raleigh	North Carolina	All of North Carolina and beyond	Raleigh string group playing as a solo, duo, trio or quartet, mixing classical repertoire with pop arrangements for ceremonies and cocktails.	info@magnoliastringquartet.com		https://www.magnoliastringquartet.com	https://www.instagram.com/magnolia.string.quartet/
Save the Date Music	Music		Raleigh	North Carolina	Raleigh, Durham, Chapel Hill, Cary and across North Carolina	Family-run Raleigh music company with decades of weddings, offering solo strings or sax, duos to quartets, a DJ and full band options.		919-538-4190	https://www.savethedatemusic.com	
Neomonde Mediterranean	Catering	3817 Beryl Rd	Raleigh	North Carolina	Raleigh, Durham and Morrisville	Lebanese family bakery and kitchen founded in 1977, catering weddings with Mediterranean buffets, reception platters and plenty of vegan dishes.	caterraleigh@neomonde.com	919-695-2434	https://neomonde.com/catering	https://www.instagram.com/neomondemediterranean/
Clyde Cooper's Barbecue	Catering	1326 E Millbrook Rd	Raleigh	North Carolina		Raleigh barbecue joint cooking Eastern North Carolina pork since 1938, offering wedding catering, private parties and buffet pickup.	clydecoopersbbq.1938@gmail.com	919-832-7614	https://clydecoopersbbq.com/catering	https://www.instagram.com/clydecoopersbbqraleigh/
Christine's Plates	Catering		Raleigh	North Carolina	Research Triangle, within 50-60 miles of Raleigh	Triangle caterer and private chef cooking rustic, farm-inspired food from family recipes, with charcuterie and day-of coordination help.	christinesplates@gmail.com		https://www.christinesplates.com	https://www.instagram.com/christinesplates/
Mena Garcia Beauty	Hair & Makeup		Raleigh	North Carolina	Raleigh area and beyond	Raleigh bridal hair and makeup team working with every hair texture, known for a radiant, glam-but-natural look, with trials and on-site styling.	mena@menagarciabeauty.com		https://www.menagarciabeauty.com	https://www.instagram.com/menagarciabeauty/
Wink Hair & Makeup	Hair & Makeup	1039 Dresser Ct	Raleigh	North Carolina		Raleigh hair and makeup team working from The Wink Suite, styling brides and full bridal parties for weddings and special occasions.	info@winkhairandmakeup.com		https://www.winkhairandmakeup.com	https://www.instagram.com/winkhairandmakeup/
Starlit Beauty Co.	Hair & Makeup		Raleigh	North Carolina	Raleigh, Durham, Chapel Hill and surrounding areas	Raleigh makeup artist and licensed esthetician Alaina Arntsen, known for soft-glam bridal makeup with skin prep, plus bridal hairstyling.		(919) 520-4931	https://www.starlitbeautyco.com	https://www.instagram.com/starlitbeautyco/
Edible Art Bakery & Dessert Cafe	Cake	4351 The Circle at North Hills, Suite 115	Raleigh	North Carolina		North Hills bakery making scratch-made Southern cakes since 1982, with tiered wedding cakes, cupcake bars, groom's cakes and macarons.	info@edibleartnc.com	919-856-0604	https://edibleartbakery.com/weddings	https://www.instagram.com/edibleartbakeryraleigh/
Once in a Blue Moon Bakery	Cake	115-G W Chatham St	Cary	North Carolina	The Triangle	Downtown Cary bakery and cafe that has spent 25 years baking for the Triangle, with a dedicated wedding cake service alongside its weekly menu.	onceinabluemoonbakery@gmail.com	(919) 319-6554	https://bluemoonbakery.com/wedding-cakes/	https://www.instagram.com/onceinabluemoonbakery/
The Mad Hatter's Cafe & Bakeshop	Cake	1802 W Main St	Durham	North Carolina	Durham, Chapel Hill, Raleigh and the Triangle	Durham cafe and bakeshop on West Main Street making custom buttercream and fondant wedding cakes, delivered to venues across the Triangle.		919-286-1987	https://www.madhatterbakeshop.com/menus/bake-shop/wedding-cakes/	https://www.instagram.com/madhatterdurham/
Sixteen 9 Films	Videography		Raleigh	North Carolina	North Carolina and destination weddings	Raleigh filmmaker Andy makes storytelling wedding films that take in family and community as well as the couple, getting to know clients first.	andy@sixteen9films.com	601-291-7935	https://www.sixteen9films.com	https://www.instagram.com/sixteen9films/
Single Story Film	Videography		Raleigh	North Carolina	Most of the East Coast, plus national and international travel	Husband-and-wife film team Wil and Elisa, based in Raleigh, making emotional, story-led wedding films shot on 6K and 4K cinema cameras.	singlestoryfilm@gmail.com		https://www.singlestoryfilm.com	https://www.instagram.com/singlestoryfilm/`,
  },
  {
    name: "Asheville: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mozingo Photography	Photography		Asheville	North Carolina	Western North Carolina	Husband-and-wife team photographing weddings, engagements and proposals around Asheville, with more than 400 weddings behind them.	Meriah@MozingoPhotography.com	828-734-3063	https://mozingophotography.com/	https://www.instagram.com/mozingo_photography/
Anorda Photography	Photography		Asheville	North Carolina	Western North Carolina, the Southeast and destinations	Married duo Sam and Nick Straub offering documentary-style wedding photography and film, with an inclusive approach to every couple.	hello@anordaphotography.com	704-916-9468	https://anordaphotography.com/	
Meghan Rose Photography	Photography		Asheville	North Carolina	The Carolinas and the South	Hybrid film and digital wedding photographer in Asheville, known for warm, romantic images with a timeless film feel.			https://meghanrosephotography.com/	https://www.instagram.com/meghanrose_photography/
Silver Fern Events	Planning		Asheville	North Carolina		Asheville planning studio offering full planning, partial planning, day-of coordination and floral design for weddings large and small.		917-327-8734	https://www.silverfernevents.com/	https://www.instagram.com/silverfernevents/
KnightCo Events	Planning		Asheville	North Carolina	Western North Carolina and destinations	Planner Chynna leads bespoke wedding planning and design in Asheville, focused on personal details and intentional, modern-romantic days.	hello@knightcoevents.com		https://knightcoevents.com/	https://www.instagram.com/knightcoevents/
TW Events & Productions	Planning	34 Wall St	Asheville	North Carolina	Worldwide	Terran Ward's downtown Asheville studio plans and creatively directs luxury weddings with a chic, design-led take on mountain celebrations.	info@terran-ward.com		https://terran-ward.com/	https://www.instagram.com/terran_ward_events/
Flower Gallery of Asheville	Florals	800 Fairview Road Suite A4	Asheville	North Carolina		Family-owned floral studio in east Asheville creating custom wedding and event flowers, with consultations held at its Fairview Road shop.	flowers@flowergalleryasheville.com	828-505-1577	https://flowergalleryasheville.com/	https://www.instagram.com/flowergalleryofasheville/
Bask Floral Studio	Florals		Asheville	North Carolina	Asheville and beyond	Asheville florist designing artful, romantic wedding flowers and installations, with both full-service and à la carte options.	nicole@baskfloralstudio.com		https://www.baskfloralstudio.com/	https://www.instagram.com/baskfloralstudio/
Blazing Star Flowers	Florals		Asheville	North Carolina	Around Asheville	Small Asheville flower farm growing organically and designing wedding florals from its own seasonal blooms, plus DIY flower buckets.	blazingstarflowers@gmail.com		https://www.blazingstarflowers.com/weddings-events	https://www.instagram.com/blazingstarflowers/
Remix Weddings	Music		Arden	North Carolina	Asheville, the Blue Ridge Mountains, Charlotte, Greenville SC and Johnson City	Asheville-area DJ and MC company with over 15 years of wedding receptions across the Blue Ridge Mountains.	mitch@remixweddings.com	828-774-7119	https://remixweddings.com/	https://www.instagram.com/remixweddings/
A Touch Of Rose Music	Music		Asheville	North Carolina		Violinist Karen Rose leads solo, duo, trio and quartet strings, plus violin and harp pairings, for Asheville ceremonies and elopements.	karenfrose@aol.com	828-335-9827	https://www.classicalviolin.com/	
Phoenix DJ and Sound	Music		Hendersonville	North Carolina	Hendersonville and Asheville area	Owner-DJ Curtis provides DJ and sound for weddings and parties around Hendersonville and Asheville, tailoring music to each crowd.	curtis@phoenixdjandsound.com	828-702-0927	https://phoenixdjandsound.com/	
Catering by Corey	Catering	12 Old Charlotte Highway, Ste 7	Asheville	North Carolina		Full-service Asheville caterer serving upscale Southern menus for weddings, with tastings, bar service and rentals available.	events@cateringbycorey.org	828-484-9556	https://www.cateringbycorey.org/	https://www.instagram.com/cateringbycorey/
67 Biltmore Eatery & Catering	Catering	67 Biltmore Ave	Asheville	North Carolina		Downtown Asheville eatery and full-service caterer offering wedding menus, casual catering and a Gathering Room for small events.		828-252-1500	https://67biltmore.com/catering/	https://www.instagram.com/67biltmore/
Dining Innovations	Catering	46 Haywood Street, Suite 334	Asheville	North Carolina		Asheville caterer building custom wedding and rehearsal-dinner menus, with servers and bartenders drawn from hotel and fine-dining work.	catering.dininginnovationsavl@gmail.com	828-782-3184	https://dininginnovationsavl.com/	https://www.instagram.com/dininginnovationscatering/
Pop of Color Asheville	Hair & Makeup		Asheville	North Carolina		Owner Melissa's Asheville team sends hair and makeup artists to weddings every weekend, with more than a decade in bridal beauty.	info@popofcolorasheville.com	828-230-9557	https://popofcolorasheville.com/	https://www.instagram.com/popofcolorasheville/
Jeanne's Hair & Makeup	Hair & Makeup		Asheville	North Carolina	Western North Carolina	Wedding hair and makeup from a private Asheville salon cottage or on location, including grooming services for grooms.		828-275-4952	https://jeanneshair.com/	https://www.instagram.com/jeanneshair/
Pure Beauty Asheville	Hair & Makeup		Asheville	North Carolina	On location, worldwide	Asheville makeup and hair artist known for skin-forward natural and soft-glam bridal looks, travelling to weddings on location.	purebeautyasheville@gmail.com		https://www.purebeautyasheville.com/	https://www.instagram.com/purebeautyasheville/
Layered	Cake	171 New Haw Creek Road	Asheville	North Carolina		Custom wedding and elopement cakes baked and decorated in east Asheville from locally sourced ingredients, by appointment.	info@layeredbylex.com	828-674-2137	https://layeredbylex.com/	https://www.instagram.com/layeredbylex/
Filo Pastries & Post 70 Indulgence Bar	Cake	1155 Tunnel Road	Asheville	North Carolina		East Asheville pastry shop and dessert bar that has baked custom wedding and anniversary cakes for more than ten years.	info@filopost70.com	828-298-9777	https://filopost70.com/asheville-filo-pastries-and-post-70-indulgence-bar-custom-cakes	https://www.instagram.com/filopastries/
Whisk Avl	Cake	801 Smokey Park Highway	Candler	North Carolina		Drive-through bakery west of Asheville making wedding cakes from rustic chic to elegant, alongside its cinnamon rolls and pastries.		828-633-0622	https://whiskavl.com/	https://www.instagram.com/whisk.avl/
Candeo Films	Videography		Asheville	North Carolina	Asheville, Houston and beyond	Story-driven wedding films shot in Asheville and beyond, built around each couple's own humour and personality rather than templates.	hello@candeofilms.com		https://www.candeofilms.com/	https://www.instagram.com/candeofilms/
Katherine Denise Films	Videography		Asheville	North Carolina	Asheville, Highlands, Charleston and 30A	Asheville filmmaker crafting bespoke, artistic wedding films for mountain and Southeast coast celebrations, with a decade of experience.	hello@katherinedenisefilms.com		https://www.katherinedenisefilms.com/	https://www.instagram.com/katherinedenisefilms/
Brian Kennedy Productions	Videography	56 South Lexington Avenue	Asheville	North Carolina	Western North Carolina, the Carolinas, Virginia and East Tennessee	Asheville wedding videographer Brian Kennedy films relaxed, cinematic highlight videos for mountain weddings across the Southeast.	brian@briankennedyproductions.com	828-713-1224	https://briankennedyproductions.com/	https://www.instagram.com/briankennedyproductions/`,
  },
  {
    name: "Charlotte: catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Best Impressions Caterers	Catering	2600 Youngblood Street	Charlotte	North Carolina		Charlotte caterer in business since 1989, offering plated courses, buffets and chef stations with event directors handling the planning.		(704) 333-9779	https://www.bestimpressionscaterers.com/wedding-receptions	https://www.instagram.com/bestimpressionscaterers/`,
  },
];

export default batches;
