import type { VendorBatch } from "@/lib/vendor-batches";

// North Dakota vendor batches. Every row's State is "North Dakota". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Fargo: photography, planning, florals, music, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Abby Anderson Photography	Photography		Fargo	North Dakota	Fargo, ND and Moorhead, MN	Fargo wedding and portrait photographer with a classic, light-led style aimed at couples who want timeless rather than trendy images.			https://abbyanderson.com/	https://www.instagram.com/abbyanders/
Chelsea Joy Photography	Photography		Fargo	North Dakota		Fargo wedding photographer who works with couples who want a personal day rather than a standard wedding template, in a bright, colour-true style.	chelseajoyphoto@gmail.com		https://chelseajoyphoto.com/	https://www.instagram.com/chelseajoyphotography/
Willow + Rose Photo	Photography		Fargo	North Dakota	North Dakota and Minnesota	Fargo photographer covering weddings alongside portraits, families and milestones, with a storytelling approach to the day.			https://willowandrosephoto.com/	https://www.instagram.com/willowandrose.photo/
Gather Event Planning	Planning		Fargo	North Dakota		Fargo planner offering full-service, partial planning and day-of coordination so couples can be guests at their own wedding.			https://www.plantogather.com/	https://www.instagram.com/plantogather/
Breathe and Relax Events	Planning		Fargo	North Dakota		Fargo wedding planner, designer and day-of coordinator, taking on anything from a single day of coordination to full planning.			https://breatheandrelaxevents.com/	https://www.instagram.com/breatheandrelaxevents/
Say Less Events Co.	Planning		Fargo	North Dakota		Two Fargo coordinators who step in to settle final details and run the wedding day itself, for couples who have planned the rest.	saylesseventsco@gmail.com		https://www.saylesseventsco.com/	https://www.instagram.com/saylesseventsco/
Love Always Floral	Florals	1120 Northern Pacific Ave	Fargo	North Dakota	Fargo and beyond	Fargo studio founded in 2016 making airy, garden-style wedding flowers and installations, working by appointment.	fargo@lovealwaysfloral.com	(701) 205-8710	https://lovealwaysfloral.com/pages/weddings	https://www.instagram.com/lovealwaysfloral/
Shotwell Floral & Greenhouse	Florals	4000 40th St S	Fargo	North Dakota	Fargo, Moorhead, Dilworth, Horace, Oxbow, Hickson and West Fargo	Long-running Fargo florist and greenhouse that also designs wedding and event flowers alongside its everyday deliveries.		(701) 356-9377	https://www.shotwellflorist.com/services/weddings/	https://www.instagram.com/shotwell_floral/
Classic Floral	Florals	29 Sheyenne St	West Fargo	North Dakota	Fargo, West Fargo, Horace, Harwood and Moorhead	West Fargo flower shop offering customisable wedding packages with bouquets and centrepieces made by hand.		701-281-0767	https://westfargoflowers.com/pages/wedding-page	https://www.instagram.com/classicfloralwf/
Powerplay DJ	Music	4151 38th St S Ste C	Fargo	North Dakota	Fargo-Moorhead, Bismarck and across North Dakota, South Dakota and Minnesota	Fargo DJ company with a second base in Bismarck, also supplying karaoke, photo booths and casino nights for wedding receptions.			https://www.powerplaydj.com/	https://www.instagram.com/powerplaydj/
Midnight Express DJs	Music		Fargo	North Dakota	North Dakota, western Minnesota and into Montana	Family-run wedding DJ service going since 1980, quoting plain pricing with no hidden fees and covering Fargo-Moorhead.	tylerexpressdj@gmail.com	(701) 773-6805	https://mexpressdjs.com/	https://www.instagram.com/midnightexpressdj/
GO DJ Eventz	Music		Fargo	North Dakota	North Dakota, South Dakota and Minnesota	Fargo DJ with more than fifteen years behind the decks, supplying sound systems for weddings, corporate events and private parties.	godjeventz@gmail.com	701-999-2098	https://www.godjeventz.com/	
Brew Catering & Events	Catering	635 2nd Ave N	Fargo	North Dakota	Fargo, Moorhead, Wahpeton and surrounding area	Chef-led Fargo caterer with custom menus, specialty buffets and event planning help for weddings among its event types.	events@brewcatering.com	701-369-0333	https://www.brewcatering.com/	https://www.instagram.com/brewcatering/
Savory Catering	Catering	3803 13th Ave S	Fargo	North Dakota	Fargo-Moorhead and beyond	Catering arm of a Fargo hotel, making familiar dishes with extra depth of flavour and custom menus for weddings and other events.	sales@savoryfargo.com	701-277-7353	https://www.savorycateringfargo.com/	https://www.instagram.com/savorycateringfargo/
Artistry Fargo	Hair & Makeup	705 13th Ave E	West Fargo	North Dakota		West Fargo bridal hair and airbrush makeup team that sends two or more stylists at no extra charge, in salon or on location.		701-353-8073	https://artistryfargo.com/weddings	https://www.instagram.com/artistryfargo/
Artistry by Kimberly	Hair & Makeup		Fargo	North Dakota	Fargo-Moorhead, travelling through the Midwest and beyond	Fargo makeup artist for brides who want refined, editorial looks that photograph naturally and last through a long wedding day.			https://www.artistrybykimberly.com/	https://www.instagram.com/artistrybykimberly/
Cassandra L. Hair Studio	Hair & Makeup		West Fargo	North Dakota		West Fargo master cosmetologist doing bridal and special-event hair and makeup, either in the studio or on location.			https://cassandralhairstudio.com/bridal-hair-and-makeup/	https://www.instagram.com/hairbycassl/
Nichole's Fine Pastry & Café	Cake	13 8th St S	Fargo	North Dakota	Fargo-Moorhead, with limited out-of-town delivery	Downtown Fargo bakery and restaurant of over twenty years making custom wedding cakes with European baking traditions.		(701) 232-6430	https://nicholesfinepastry.com/bakery/wedding-events/	https://www.instagram.com/nicholesfinepastry/
Tartan Rose Bakery	Cake		Fargo	North Dakota		Fargo bakery, formerly Love in the Oven, baking custom wedding cakes and desserts from scratch in small batches since 2010.	hello@tartanrosebakery.com		https://www.tartanrosebakery.com/	
Meadowlark Films	Videography		Fargo	North Dakota	Fargo, Minnesota and destination weddings	Fargo wedding film team, founded in 2019, making documentary-style heirloom films built around candid, emotional moments.			https://www.meadowlarkfilms.com/	
Karied Away Video	Videography		Fargo	North Dakota	North Dakota, Minnesota and South Dakota	Fargo wedding videographer offering storytelling films with attention to small details, from highlight reels to full ceremonies.	hello@kariedawayvideo.com		https://kariedawayvideo.com/	https://www.instagram.com/kariedawayvideo/
Eclipse Multimedia & Video	Videography		Fargo	North Dakota		Fargo video company with years of wedding experience, offering tiered ceremony packages with multiple cameras, plus reception coverage.	amy@eclipsemulti.com	(701) 200-9552	https://www.eclipsemulti.com/	
`,
  },
  {
    name: "Fargo: catering and cakes",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
457 Cake	Cake		Fargo	North Dakota	Fargo-Moorhead and surrounding area	Fargo cake decorator making custom cakes, cupcakes and treats for weddings and other events, with delivery around Fargo-Moorhead.	jamie@457cake.com	(701) 552-2469	https://457cake.com/	https://www.instagram.com/457cake/
Spitfire Bar & Grill	Catering	1660 13th Ave E	West Fargo	North Dakota	Fargo-Moorhead	West Fargo wood-fired and smoked BBQ restaurant whose catering team also serves weddings and rehearsal dinners around Fargo-Moorhead.		701-478-8667	https://spitfirebarandgrill.com/catering/west-fargo-catering/	
`,
  },
  {
    name: "Bismarck: planning, florals, photography, videography, hair and makeup and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Behind the Scenes Events	Planning		Bismarck	North Dakota	Bismarck, Fargo and destination weddings	Bismarck wedding planning and month-of coordination team, who also plan honeymoons and destination weddings for North Dakota couples.		701.401.2218	https://behindthescenesevents.net/	https://www.instagram.com/behind.the.scenes.events/
Enticed Bismarck	Planning		Bismarck	North Dakota	Bismarck and Mandan	Full-service wedding and event coordinator handling vendors, budgets, decor set-up and tear-down, with DJ and venue options in Mandan.	enticed.bismarck@gmail.com	701-220-7548	https://www.enticedbismarck.com/	
Mini Blooms by Emil	Florals		Bismarck	North Dakota	Bismarck and beyond	Bismarck florist designing garden-inspired, colourful wedding bouquets, ceremony installations and centrepieces with a touch of whimsy.		701-226-5312	https://minibloomsbyemil.shop/	https://www.instagram.com/minibloomsbyemil/
BWeis Media Weddings	Videography		Bismarck	North Dakota	North Dakota and beyond	Bismarck wedding videographer making story-driven films, limiting bookings to a small number of weddings each year.	bweisbeck@bweismedia.com		https://bweismediaweddings.com/	https://www.instagram.com/bweismedia/
TraceLynn Films	Videography		Bismarck	North Dakota	North Dakota, South Dakota, Minnesota and Montana	Bismarck videographer creating personalised, creative wedding films for couples across the northern plains states.	tracelynnfilms@gmail.com		https://www.tracelynnfilms.com/	https://www.instagram.com/tracelynnfilms/
Great Plains Sound and Media	Videography		Bismarck	North Dakota	Bismarck and North Dakota	Bismarck production collective, established 2023, offering wedding videography with drone footage alongside DJs, live audio and photography.			https://greatplainssound.com/	https://www.instagram.com/greatplainssound/
Paper Hands Media	Photography		Bismarck	North Dakota	Bismarck and North Dakota	Bismarck photographer and videographer documenting weddings with a warm, emotional and personality-led style.	quinnlyn.nelson@gmail.com		http://paperhandsmedia.com/	
Jessica Heller Photography	Photography		Bismarck	North Dakota	Bismarck and North Dakota	Bismarck photographer with 15 years behind the camera, shooting weddings, seniors and families with a relaxed, fun approach to bridal parties.	JessicaHellerPhotography@gmail.com		https://jessicahellerphotography.com/	https://www.instagram.com/jessicahellerphotography/
ily Studios	Photography		Bismarck	North Dakota	Bismarck and North Dakota	Bismarck photographer specialising in weddings, couples and boudoir sessions, with a photobooth available for receptions.			https://www.ilystudios.co/	https://www.instagram.com/ily.studios/
Leyla Alleyne	Photography		Bismarck	North Dakota	Bismarck and Mandan	Bismarck-Mandan wedding, boudoir and portrait photographer who publishes her wedding investment pricing online.			https://www.leylaalleyne.com/	https://www.instagram.com/leyladwellephotography/
Desirae's Makeup & Beauty Lounge	Hair & Makeup		Bismarck	North Dakota	Bismarck	Bismarck makeup studio and beauty shop offering professional makeup applications and dedicated bridal makeup for wedding days.		(701) 751-2312	https://www.desiraesbeautylounge.com/	https://www.instagram.com/desiraesbeautylounge/
Evolve Salon and Spa	Hair & Makeup	1001 West Interstate Avenue, Suite 100	Bismarck	North Dakota	Bismarck	Bismarck salon acting as bridal headquarters, with makeup application and updos for the bride and wedding party.	evolvebismarck@hotmail.com	701-751-7990	https://www.evolvesalonbismarck.com/	https://www.instagram.com/evolvebismarck/
Eden's Edge Salon	Hair & Makeup		Bismarck	North Dakota	Bismarck	Independent Bismarck hairstylist and makeup artist offering colour, cuts and wedding-day hair and makeup.			https://www.edensedgesalon.com/	https://www.instagram.com/edensedgesalon/
Mabel's All Day	Catering		Bismarck	North Dakota	Bismarck	Bismarck food truck serving classic American staples, with mobile catering for weddings, rehearsal dinners and community gatherings.	hello@mabelsallday.com		https://www.mabelsallday.com/	https://www.instagram.com/mabelsallday/
`,
  },
];

export default batches;
