import type { VendorBatch } from "@/lib/vendor-batches";

// Ohio vendor batches. Every row's State is "Ohio". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Columbus: photography, planning, florals, music and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kismet Visuals & Co	Photography		Columbus	Ohio	Columbus, the Midwest and destinations worldwide	Documentary-minded wedding photographer working since 2010, focused on honest, unposed moments and timeless images, with destination coverage on offer.			https://www.kismetvisuals.com/	https://www.instagram.com/kismetvisuals/
Asteria Photography	Photography		Columbus	Ohio	Ohio, with travel across the US and to Europe	Storytelling wedding photography centred on candid emotion and the feel of the day, with complete packages and regular travel beyond Ohio.	asteriaphoto@gmail.com	614-648-3967	https://www.asteriaphotography.com/	https://www.instagram.com/asteriaphoto/
Brad Gillespie Photography	Photography		Columbus	Ohio	Throughout Ohio	Columbus wedding and engagement photographer since 2020 creating warm, romantic, timeless images that reflect each couple's personalities.			https://www.bradgillespiephotography.com/	https://www.instagram.com/bradgillespiephotography/
Zolana Weddings	Planning		Columbus	Ohio	Columbus, Philadelphia, New Jersey and Delaware	Full and partial planning, wedding management and multi-day events, specialising in multicultural weddings that blend more than one family tradition.			https://www.zolanaweddings.com/	https://www.instagram.com/zolana.weddings/
Aisle & Co	Planning		Columbus	Ohio	Ohio, the Raleigh-Durham area and destinations including Italy	Planning and design firm offering full planning, styling and month-of coordination for couples marrying locally or at destinations abroad.	hello@aisleandcompany.com		https://aisleandcompany.com/	https://www.instagram.com/aisleandco/
Adoration Weddings & Events	Planning		Columbus	Ohio	Columbus and destination weddings nationwide	Latina- and woman-owned planning studio offering full-service planning and design, wedding management from three months out, and hourly consultations.			https://www.adorationweddings.com/	https://www.instagram.com/adorationweddings/
Camela Lynn Weddings & Events	Planning		Dublin	Ohio	Dublin and the surrounding Columbus area, travel available	Dublin-based planner offering full, partial, month-of and hourly wedding planning, along with dessert table design for receptions.	events@camelalynnweddingsandevents.com		https://www.camelalynnweddingsandevents.com/	
Flocal Co Floral Studio	Florals	1464 W 5th Ave	Columbus	Ohio	Columbus, including Grandview, Upper Arlington, Dublin, Worthington and Bexley	Woman-owned Grandview-area floral studio building lush, garden-style wedding flowers and installations, with full-service and pick-up options.		(614) 408-3985	https://www.flocalcompany.com/	https://www.instagram.com/flocalcofloralstudio/
Prema Designs	Florals		Columbus	Ohio	Columbus and destination weddings	Wedding design firm working since 2010 on abundant florals and large-scale installations, with an a la carte flower collection for smaller events.			https://www.prema-designs.com/	https://www.instagram.com/prema_designs/
Madison House Designs	Florals	19817 Raymond Rd	Marysville	Ohio	Weddings throughout Columbus and select destinations	Wedding and event florist near Marysville designing refined, naturally placed arrangements scaled to each venue across the Columbus area.	lynette@madisonhousedesigns.com	614-561-0135	https://www.madisonhousedesigns.com/	https://www.instagram.com/madisonhouseflowers/
Femme Floral	Florals		Columbus	Ohio	Columbus and travel for events	Art-forward floral studio combining sculptural flower design with ceiling and wall draping to shape the whole look of a wedding space.	designsbyfemme@gmail.com		https://www.femme-floral.com/	https://www.instagram.com/femmefloraldesigns/
Arch City Lights	Music		Columbus	Ohio	Columbus and neighbouring areas	Columbus party band playing soul, Motown, funk and current R&B, with acoustic, string and DJ options for the ceremony and cocktail hour.	archcitylights@gmail.com		https://www.archcitylights.com/	https://www.instagram.com/archcitylights/
Columbus Musicians	Music		Columbus	Ohio	Columbus area	Live wedding music agency supplying string quartets, harp, piano, brass, jazz ensembles and reception bands from guest arrival to last dance.	columbusmusicians@gmail.com	419-944-8965	https://www.columbusmusicians.com/	
LogieBear Sound & Lighting	Music		Columbus	Ohio	Central Ohio including Dublin, New Albany, Westerville and Downtown Columbus	Wedding DJ and MC mixing live with uplighting included, plus add-ons such as live saxophone, photo booth and an audio guestbook.	Logan@LogieBearSNL.com	(614) 917-3787	https://www.logiebearsnl.com/	https://www.instagram.com/logiebear.snl/
Platinum Music Productions	Music		Columbus	Ohio	Columbus and Central Ohio	Wedding DJ company running since 2005, offering ceremony audio, dance-floor lighting, custom monograms, cold-spark effects and a mirror photo booth.			https://platinummusicdj.com/	https://www.instagram.com/platinummusicdj/
Cameron Mitchell Premier Events	Catering	7619 Huntington Park Dr.	Columbus	Ohio	Columbus and the surrounding region	Full-service caterer and event team that also plans and designs weddings and runs three Columbus event spaces, including The Stack.		(614) 848-4700	https://cameronmitchellpremierevents.com/	https://www.instagram.com/cmpe_columbus/
Bosc + Brie	Catering	7625 North High Street	Columbus	Ohio		North Columbus caterer with in-house planners, linens and cake cutting included, and a bring-your-own-alcohol option that helps trim bar costs.		614.985.2215	https://www.boscandbrie.com/	https://www.instagram.com/bosc_and_brie/
Fire & Knife	Catering		Columbus	Ohio	Homes, workplaces and venues across Ohio	Columbus caterer specialising in weddings with refined global menus served as a buffet or plated dinner, with a dedicated catering sales contact.	info@fireandknife.com	614.758.3659	https://www.fireandknife.com/	`,
  },
  {
    name: "Columbus: hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hertty's Bakeshop	Cake	100 E Campus View Blvd Suite #250	Columbus	Ohio	Columbus, with delivery required for wedding cakes	Family-run cake design studio in north Columbus making custom tiered wedding cakes by consultation appointment, with sugar flowers and fine detailing.	info@herttysbakeshop.com	614-373-7699	https://www.herttysbakeshop.com/	
Lavender and Honey Wedding Cakes	Cake		Columbus	Ohio	Columbus	Boutique Columbus bakery making scratch-baked custom wedding cakes and desserts, with tasting boxes couples can sample at home.	info@lavenderandhoneyweddingcakes.com	(614) 547-9851	https://www.lavenderandhoneyweddingcakes.com/	
Our CupCakery	Cake	54 S. High St.	Dublin	Ohio		Family-owned bakery in Historic Dublin offering classic tiered wedding cakes alongside cupcake displays, with a dedicated wedding request process.	Laura@ourcupcakery.com	614-659-1555	https://www.ourcupcakery.com/	
Sweet & Shiny	Cake		Columbus	Ohio		Columbus custom cake maker producing wedding cakes and decorative display cakes, with a wedding gallery and an online bakery shop.	elaine@sweetandshiny.com	614-680-9195	https://www.sweetandshiny.com/	https://www.instagram.com/sweetandshiny_columbus/
Columbus Wedding Videos	Videography		Columbus	Ohio	Central Ohio	Long-running Central Ohio video team filming since 2008, offering unobtrusive full-length documentary edits alongside shorter cinematic films.	info@columbusweddingvideos.com	614.725.0169	https://columbusweddingvideos.com/	https://www.instagram.com/columbusweddingvideos/
Hey Films	Videography		Columbus	Ohio	Columbus, Dublin, Westerville, New Albany and Central Ohio	Columbus wedding film studio with hourly packages from a short three-hour shoot to two-videographer full days, and two-week delivery.			https://heyfilms.com/	https://www.instagram.com/heyfilmsweddings/
Cinemachine Studios	Videography		Columbus	Ohio	Columbus area	Columbus video team making cinematic wedding films that lean on deliberate camera movement, angles and lighting to tell each couple's day.	info@cinemachinestudios.com		https://www.cinemachinestudios.com/	
The Lovely Artistry Collective	Hair & Makeup		Columbus	Ohio	Ohio and nationwide, travelling worldwide	Bridal hair and makeup team founded in 2011 for classic, timeless looks, with more than 3,000 brides styled and travel for destination weddings.			https://thelovelyartistrycollective.com/	https://www.instagram.com/thelovelyartistrycollective/
Lauren Wolff Hair Design	Hair & Makeup	1500 West 3rd Ave	Columbus	Ohio	Columbus area	Licensed cosmetologist creating long-lasting bridal hairstyles from a Grandview-area studio, alongside editorial styling and hair education.	hello@laurenwolffhairdesign.com		https://www.laurenwolffhairdesign.com/	https://www.instagram.com/lo.wolff_hairdesign/
Makeup with Anna K	Hair & Makeup		Columbus	Ohio	Columbus and destination weddings	Bridal makeup artist using luxury brands, with bridal party packages and a VIP option that pairs a two-hour facial with wedding makeup.	makeupwithannak@gmail.com		https://www.makeupwithannak.com/	https://www.instagram.com/makeup.with.annak/
Carly Jo Makeup	Hair & Makeup		Columbus	Ohio	Central Ohio	Bridal makeup artist focused on intimate weddings and elopements, aiming for a polished look that still feels like the bride herself.			https://www.carlyjomakeup.com/	https://www.instagram.com/carlyjomakeup/`,
  },
  {
    name: "Cincinnati: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Bird and Rose Photography	Photography	529 Main Street, Suite 204	Loveland	Ohio	Cincinnati and beyond, with travel	Husband-and-wife team with 25 years of combined experience telling wedding stories from their Loveland studio and travelling to couples elsewhere.	hello@birdandrosephoto.com		https://www.birdandrosephoto.com/	https://www.instagram.com/wearebirdandrose/
Très Belle Cakes	Cake	8921 Reading Road	Cincinnati	Ohio	Greater Cincinnati	Woman-owned bakery making award-winning custom wedding cakes and desserts since 2003, designed around each couple's tastes and story.	tresbellecakes@gmail.com	513-241-2253	https://www.tresbellecakes.com/	https://www.instagram.com/tresbellecakes/
The BonBonerie	Cake	2030 Madison Road	Cincinnati	Ohio	Cincinnati and surrounding areas	Bakery and café open since 1983, baking wedding cakes, cupcakes and dessert bars from European recipes, with tastings and cake stands.		513-321-3399	https://www.bonbonerie.com/	https://www.instagram.com/bonboneriecincy/
Light Parade Films	Videography		Cincinnati	Ohio	Cincinnati and destination weddings worldwide	Woman-owned cinematography studio making unobtrusive, story-driven wedding films with careful editing and sound design, aimed at lasting rather than trendy.	info@lightparadefilms.com	859-957-7587	https://www.lightparadefilms.com/	https://www.instagram.com/lightparade_films/
A Spoon Fulla Sugar	Cake	11916 Montgomery Rd	Cincinnati	Ohio	Cincinnati region	Montgomery Road bakery making custom wedding cakes plus cupcakes, cookies, dessert bars and its dotted Spoonie cakes, by appointment midweek.	info@aspoonfullasugar.com	513-683-0444	https://www.aspoonfullasugar.com/	https://www.instagram.com/aspoonfullasugar/
BRIDEface	Hair & Makeup		Cincinnati	Ohio		On-location bridal hair and makeup team founded in 2005, offering both airbrush and traditional makeup alongside updos, with studio appointments too.			https://www.brideface.com/	https://www.instagram.com/bridefaceotr/
Elegant Fare	Catering	2575 Commerce Blvd.	Cincinnati	Ohio	Greater Cincinnati and Northern Kentucky	Full-service caterer running since 1982, pairing each couple with a dedicated event consultant and offering menus at several price levels.	events@elegantfare.com	513-552-1340	https://www.elegantfare.com/	https://www.instagram.com/elegantfare/
Cincinnati Catering	Catering	1320 Ethan Avenue	Cincinnati	Ohio	Greater Cincinnati and Northern Kentucky	Long-running local caterer of around 90 years handling weddings and social events, with menus that stretch to grill-outs and Gold Star Chili.		513-541-2626	https://www.cincinnaticatering.com/	https://www.instagram.com/cincinnaticatering/
KMC Weddings and Events	Planning		Cincinnati	Ohio	Ohio and destination weddings	Cincinnati-based planning and design team of sixteen with over 18 years behind it, handling full planning, custom builds and destination weddings.			https://www.kmcweddings.com/	https://www.instagram.com/kmcweddings/
Sutle Productions	Music		Cincinnati	Ohio	Greater Cincinnati	DJ company with a roster of DJs matched to each couple's style, covering weddings and parties, with online date checking and booking.			https://www.sutleproductions.com/	https://www.instagram.com/shaunissutle/
Everlasting Sounds	Music	121 W Benson St	Reading	Ohio		Full-service DJ company bringing sound, lighting and event coordination to weddings, with an Ohio office in Reading and a second in Florida.	ohio@everlastingsounds.com	513-260-2780	https://www.everlastingsounds.com/	
Brittany Bays Photography	Photography		Cincinnati	Ohio	Cincinnati, the Midwest and destinations worldwide	Editorial, fine-art wedding photographer shooting on both film and digital, with over 15 years of experience and a calm, unobtrusive approach.			https://brittanybays.com/	https://www.instagram.com/brittanybaysphotography/
Images by Daniel Michael	Photography	110 W. Benson St.	Cincinnati	Ohio		Studio with 25+ years and 3,000+ weddings behind it, also photographing bar and bat mitzvahs, blending documentary, editorial and traditional styles.	imagesbydanielmichael@gmail.com	513-262-4830	https://www.danielmichael.com/	https://www.instagram.com/danielmichael_photo/
Cate Ronan	Photography		Cincinnati	Ohio	Ohio, the East Coast, New England, Nashville and Europe	Documentary-led wedding photographer working since 2016, focused on candid, emotive images and especially suited to intimate weddings of 100 or fewer.			https://cateronan.com/	https://www.instagram.com/thecateronan/
Eve Floral Co.	Florals	3706 Eastern Ave	Cincinnati	Ohio	Cincinnati and beyond	Woman-led flower shop and studio in Columbia-Tusculum creating seasonally inspired wedding florals, with consultations by appointment.			https://evefloralco.com/	https://www.instagram.com/evefloralco/
Floré	Florals		Cincinnati	Ohio	The Midwest and beyond	Appointment-only boutique studio for weddings and events, using colour, movement and form to build personal, intentional floral designs.	zoe.inflore@gmail.com	513-401-5677	https://florecincy.com/	https://www.instagram.com/flore.floralstudio/
Westcraft Floral	Florals		Cincinnati	Ohio	Greater Cincinnati, Northern Kentucky and the Midwest	Bespoke wedding and event floral studio led by designer Nola, focused on seasonal, locally sourced flowers and considered colour and composition.			https://westcraftfloral.com/weddings-and-events	https://www.instagram.com/westcraftfloral/
Still & Story Films	Videography		Cincinnati	Ohio	Cincinnati and worldwide	Husband-and-wife film team, formerly Dave Woodland Films, making cinematic, documentary-inspired wedding films after 400+ weddings around the world.			https://stillandstoryfilms.com/	https://www.instagram.com/stillandstoryfilms/
Maxwell Faust Productions	Videography		Cincinnati	Ohio	Cincinnati and nationwide	Cinematic wedding filmmaker with 100+ weddings across 60+ venues, aiming to capture how the day felt as much as what happened.	max@maxwellfaust.com	513-509-8885	https://maxwellfaust.com/	https://www.instagram.com/maxwellfaustproductions/
Athena's Eyes Productions	Videography		Cincinnati	Ohio	Cincinnati, Northern Kentucky, Dayton and eastern Indiana	Affordable documentary-style videographer filming unobtrusively with several cameras, delivering highlight reels in one to two weeks.	AthenasEyesProductions@gmail.com	513-280-7707	https://athenaseyes.com/	
Elegant Productions	Videography		Cincinnati	Ohio	Cincinnati, Columbus, Indianapolis, Lexington, Louisville and West Virginia	Film and photo company since 2007 with 250+ weddings, whose packages include a full edit of the ceremony and reception formalities as standard.	julie@elegantproductions.com	513-767-1510	https://elegantproductions.com/	
Blush & Bowtie	Planning		Cincinnati	Ohio	Cincinnati, Dayton and beyond	Planning and design team with published packages from event-only coordination to full planning, plus sister firms for vintage rentals and entertainment.			https://blushandbowtieweddings.com/	https://www.instagram.com/blushandbowtieweddings/
Every Last Detail	Planning		Cincinnati	Ohio	Cincinnati region and surrounding areas	Owner-led planning and design studio that grew out of a decor rental collection, handling coordination and vendor management alongside its rentals.	EveryLastDetailOhio@gmail.com		https://www.everylastdetailohio.com/	https://www.instagram.com/everylastdetailohio/
Ivory Couture	Planning		Cincinnati	Ohio	Cincinnati and destinations	Planner offering full and partial planning with design, or wedding management alone, built around strategy and logistics as much as styling.			https://ivorycouture.co/	https://www.instagram.com/ivorycouture.co/
Chenese Bean Makeup Artistry	Hair & Makeup	1821 Summit Rd., Suite 300B	Cincinnati	Ohio	Cincinnati, Northern Kentucky, Dayton and destination weddings	Bridal makeup artist with over 25 years' experience, skilled across all skin tones and in airbrush, with a hand-picked team of artists and hairstylists.			https://chenesebean.com/cincinnati-bridal-makeup-artist	https://www.instagram.com/chenesebean.mua/
AV Beauty Bar	Hair & Makeup	1408 Elm Street	Cincinnati	Ohio		Over-the-Rhine salon whose stylists offer bridal hair and makeup in the chair or as on-location glam for the wedding party.	info@avbeautybar.com		https://www.avbeautybar.com/	https://www.instagram.com/avbeautybar/
Jack Garrett Band	Music		Cincinnati	Ohio	Cincinnati, Columbus, Dayton, Louisville, Lexington, Indianapolis and beyond	Live wedding band with 25 years behind it, playing as a 7-piece or a 12-piece with a six-piece horn section, plus small groups for ceremonies.		513-508-7450	https://www.jackgarrettband.com/	
DelightMore	Catering	1761 Tennessee Ave	Cincinnati	Ohio	Greater Cincinnati	Caterer and event producer, formerly Funky's Catering, serving plated, buffet or station menus and running five of its own Cincinnati venues.		513-841-9999	https://delightmore.com/	https://www.instagram.com/delightmoreevents/
Midnight Rose Trio	Music		Cincinnati	Ohio	Cincinnati	Ceremony and cocktail-hour trio with 15+ years of events, playing contemporary, classical and Celtic music in custom arrangements.	midnightrosetrio@gmail.com	513-259-3110	https://www.midnightrosetrio.com/	https://www.instagram.com/midnightrosetrio/
Carly Messmer Floral Design	Florals		Cincinnati	Ohio	Cincinnati and Northern Kentucky	Bespoke wedding florist creating lush, garden-inspired designs that pair classic focal flowers with unexpected textures, starting from mood boards.	carly@carlymessmer.com	513-551-9783	https://www.carlymessmer.com/	https://www.instagram.com/carlymessmerfloral/
Village Pantry Catering	Catering	453 Wards Corner Road	Loveland	Ohio	Greater Cincinnati and the Tri-State	Family-owned caterer running since 1978, cooking for weddings and social events with gluten-free and vegan dishes on request.		513-965-0511	https://villagepantrycatering.com/	
Maribelle Cakery	Cake	3704 Cheviot Avenue	Cincinnati	Ohio		Appointment-only cake studio of over 40 years, whose owner trained with Ron Ben-Israel, using organic fillings, fresh berries and Belgian chocolate.		513-631-8333	https://maribellecakery.com/	https://www.instagram.com/maribellecakery/`,
  },
  {
    name: "Cleveland: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jenna Therese Photography	Photography		Cleveland	Ohio	Cleveland, Northeast Ohio and destination weddings worldwide	Romantic, light and joy-filled wedding photography with a focus on details and candid moments, based in Cleveland since 2016.	hello@jennatheresephotography.com	440-864-3599	https://jennatheresephotography.com/	https://www.instagram.com/jennatheresephotography/
David Blakeslee Photography	Photography		Cleveland	Ohio	Cleveland and Akron	Natural-light wedding photography with a moody, bolder look built on shadow and colour, favouring candid moments over stiff posing.	ddblakeslee@gmail.com	216-272-1492	https://davidblakesleephotography.com/	
Eileen Potts Photography	Photography		Cleveland	Ohio	Northeast Ohio and beyond	Editorial, film-inspired wedding photography with true-to-colour editing and a calm, unhurried presence on the day.			https://eileenpottsphotography.com/	
The Cannons Photography	Photography		Cleveland	Ohio	Cleveland, Columbus, Chicago, Detroit and destination weddings	Husband-and-wife team offering classic, candid wedding coverage with gentle posing guidance and a close eye for detail.	courtney@thecannonsphotography.com		https://thecannonsphotography.com/	https://www.instagram.com/thecannonsphotography/
Molly Taylor & Co.	Florals	8420 Lake Ave	Cleveland	Ohio	Northeast Ohio and beyond	Floral studio running since 2010 with five design styles from classic and romantic to bright and whimsical, plus large ceremony installations.	hello@mollytaylorandco.com	216-400-7488	https://mollytaylorandco.com/	https://www.instagram.com/mollytaylorandco/
Wild Vine Floristry	Florals		Avon Lake	Ohio	Cleveland and the greater Cleveland area, with travel available	Owner-led wedding floristry with a sustainability focus, mixing imported blooms with flowers from local Ohio growers.	hello@wildvinefloristry.com		https://wildvinefloristry.com/	https://www.instagram.com/wild_vine_floristry/
Blossom Flower Bar	Florals	14526 Detroit Ave	Lakewood	Ohio	Cleveland and Columbus areas	Lakewood flower shop with a build-your-own bouquet bar that also designs full-service wedding florals and rents a flower cart.		216-512-0700	https://www.blossomflowerbar.com/	https://www.instagram.com/blossomflowerbar/
Dew Drop Flower Shoppe	Florals		Seville	Ohio	Northeast Ohio, with travel available	Locally owned wedding and event florist with free consultations and designs ranging from classic and romantic to fun and funky.	hello@dewdropflowershoppe.com	330-485-3153	https://dewdropflowershoppe.com/	https://www.instagram.com/dewdropflowershoppe/
A Charming Fête	Planning	2035 Crocker Rd #102	Westlake	Ohio	Cleveland and destination weddings worldwide	Wedding planning, design and production firm founded in 2011, handling both Cleveland celebrations and destination weddings abroad.	lisa@acharmingfete.com		https://acharmingfete.com/	https://www.instagram.com/acharmingfete/
Emily Berg Weddings & Events	Planning		Cleveland	Ohio	Northeast Ohio and beyond	Full planning, design and day-of coordination since 2017 for non-traditional couples, donating 5% of each contract to a charity the couple picks.	hello@emilyjuneberg.com	330-353-8152	https://emilyjuneberg.com/	https://www.instagram.com/emilybergweddings/
Engaged With Nora	Planning	8001 Sweet Valley Dr, Suite 7	Valley View	Ohio	Ohio and destination weddings	Planning firm offering full-weekend, full-service and coordination packages, known for creative design and close vendor management.	nora@engagedwithnora.com	440-829-4832	https://engagedwithnora.com/	https://www.instagram.com/engagedwithnora/
Oak + Honey Event Planning Co.	Planning		Cleveland	Ohio	Northeast Ohio, including Akron, Canton, Sandusky and Youngstown, plus destinations	Cleveland planning and design team with over a decade of experience, known for collaborative planning and out-of-the-box styling.			https://oakandhoneyevents.com/	https://www.instagram.com/oakandhoneyevents/
Selective Sound Events	Music	26601 Richmond Rd	Bedford Heights	Ohio	Cleveland and the surrounding region	DJ and MC company with over 30 years in the trade, also offering ceremony audio, uplighting, photo booths and special effects.	info@selectivesound.com	440-516-0020	https://selectivesound.com/	https://www.instagram.com/selectivesoundevents/
Synapse Entertainment	Music		Cleveland	Ohio	Cleveland and Northeast Ohio	DJ Ivan Moore leads this DJ and emcee outfit with lighting packages and backup gear, at ease with LGBTQ+ and interfaith weddings.	dj@synapseentertainment.com	216-710-6100	https://synapseentertainment.com/	https://www.instagram.com/synapse_ent/
Cleveland Keys	Music		Cleveland	Ohio	Cleveland, Columbus, Cincinnati, Toledo and Pittsburgh	All-request dueling pianos taking live guest song requests, with DJ, MC and ceremony music available and extra players on hand.			https://clekeys.com/	https://www.instagram.com/clekeys/
Duo Post Prelude	Music		Cleveland	Ohio	Cleveland, with travel anywhere	Acoustic guitar duo with over 35 years of combined playing, arranging songs across genres for ceremonies and cocktail hours.	duopostprelude@gmail.com		https://duopostprelude.com/	https://www.instagram.com/postprelude/
Spice Catering Co.	Catering	5601 Tillman Ave	Cleveland	Ohio	Ohio and the wider region	Chef Ben Bebenroth's scratch-made seasonal catering since 2004, supplied partly by the company's own farm in Cuyahoga Valley National Park.	Info@SpiceHeadquarters.com	216-432-9090	https://spicecaters.com/	https://www.instagram.com/spicecateringandevents/
Marigold Catering + Events	Catering	3901 Lakeside Ave, Suite 100	Cleveland	Ohio	Northeast Ohio	Full-service wedding caterer with kitchens in Cleveland and Cuyahoga Falls, offering personalised menus, staffing and venue partnerships.	inquiries@marigoldcatering.com	216-566-5400	https://marigoldcatering.com/	https://www.instagram.com/marigoldcateringevents/
Sausalito CLE	Catering	1360 E 9th St, Suite 125	Cleveland	Ohio	Cleveland and surrounding areas	Family-owned caterer with two decades of off-site weddings at museums, parks, historic halls and backyards, using locally sourced food.	babu@sausalitocle.com	216-696-2233	https://www.sausalitocle.com/	https://www.instagram.com/sausalitocle/
Culinary Expressions Catering	Catering		Cleveland	Ohio		Woman-owned Cleveland caterer led by Chef Antonia Eddie, known for charcuterie displays, grazing stations and Ohio-sourced seasonal menus.	sales@culinaryexpressionscle.com	216-307-3398	https://culinaryexpressionscle.com/	https://www.instagram.com/culinaryexpressions216/
Hair and Makeup Cleveland	Hair & Makeup	755 Starkweather Ave	Cleveland	Ohio	All of Northeast Ohio, with travel across the US on request	Stylist and educator Alyssa Dotson leads an on-location team of about ten artists doing bridal hair and makeup across the region.	hairandmakeupbyalyssa@yahoo.com		https://www.hairandmakeupcleveland.com/	https://www.instagram.com/hairandmakeupcleveland/
The Studio Salon Downtown	Hair & Makeup	1300 W 9th St #200	Cleveland	Ohio	Cleveland	Downtown Paul Mitchell Focus salon offering bridal and groom styling, makeup and spa services seven days a week, with trials available.	neoido.wedding@gmail.com	216-685-1400	https://www.thestudiosalondowntown.com/wedding-services	https://www.instagram.com/thestudiosalondowntown/
Makeup by Ahshia	Hair & Makeup		Cleveland	Ohio	Cleveland, Columbus, Akron and destination weddings	Ahshia Cavin and team bring over 12 years of bridal makeup and hairstyling experience, with a signature soft-glam look.	ahshia@makeupbyahshia.com	216-200-6049	https://makeupbyahshia.com/	https://www.instagram.com/makeupbyahshia/
Facet Salon & Day Spa	Hair & Makeup	1 Memory Ln	Garrettsville	Ohio	Garrettsville and surrounding Portage County communities	Full-service salon and day spa offering wedding hair and makeup seven days a week, alongside facials, nails and massage.		330-527-4347	https://facetsalonandspa.com/	https://www.instagram.com/facetsalonandspa/
Luna Bakery & Cafe	Cake	2482 Fairmount Blvd	Cleveland Heights	Ohio		Scratch bakery with three Cleveland-area shops making hand-designed wedding cakes in Swiss meringue buttercream, with take-home tasting boxes.	weddingcakes@lunabakerycafe.com	216-231-8585	https://www.lunabakerycafe.com/cakes	https://www.instagram.com/lunabakerycafe/
Cake Drama	Cake	5409 Detroit Ave	Cleveland	Ohio		Gordon Square custom cake studio building tiered wedding cakes with a different flavour per tier, plus tasting boxes and virtual consultations.	cakedramabakery@gmail.com	216-762-9966	https://www.cake-drama.com/	https://www.instagram.com/cake.drama.cle/
Wild Flour Bakery	Cake	20111 Lake Rd	Rocky River	Ohio		Rocky River bakery making custom wedding cakes since 1994, with consultations, sample boxes, cake stand rentals and dessert tables.		440-331-2950	https://wildflourbakery.com/	https://www.instagram.com/wildflourbakeryoh/
Gourmet Girl Custom Cakes	Cake		Cleveland	Ohio		Self-taught cake artist Adenike Harper brings over 20 years to sculptural, story-led wedding cakes and posts tasting boxes to couples.			https://www.gourmetgirlcustomcakes.com/	https://www.instagram.com/gourmetgirlcustomcakes/
Blitz Studios	Videography		Cleveland	Ohio	Cleveland and Northeast Ohio	Cleveland video production company that also films cinematic wedding highlight films, with a polished, commercial-grade edit.	matthewh@blitzstudios.video	330-715-5344	https://www.blitzstudios.video/wedding-films	https://www.instagram.com/theblitzstudios/
Making the Moment	Videography	1650 Crossings Pkwy, Suite D	Westlake	Ohio	Cleveland and the wider Ohio region	In-house photo and film team making story-driven custom wedding films, with all editing done by its own staff rather than outsourced.	Hello@MakingTheMoment.com	440-835-5000	https://www.makingthemoment.com/cleveland-wedding-films	https://www.instagram.com/makingthemoment/
Mystic Image Photography & Cinematography	Videography	8448 Victoria Dr	Broadview Heights	Ohio	Greater Cleveland and Northeast Ohio, including Akron, Canton, Youngstown and Sandusky	Hybrid photo and film studio with over 1,500 weddings behind it, pairing drone footage and cinematic editing with fashion-style portraits.		440-457-2280	https://mystic-image.com/	
Catchlight Film + Photo Co	Videography		Cleveland	Ohio	Ohio and destination weddings	Former TV news reporter Jordan brings journalistic storytelling to wedding films and photos, travelling to national parks and beyond.			https://catchlightfilmphoto.com/	https://www.instagram.com/jordantvnews/`,
  },
  {
    name: "Dayton: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kevin Lush Photography	Photography		Dayton	Ohio	Dayton, Cincinnati, Columbus, Southwest and Central Ohio	Dayton photographer and videographer who has shot weddings since 2007 and added wedding video in 2022, with engagement sessions too.	kevin@kevinlushphotography.com	(937) 321-5752	https://kevinlushphotography.com/	https://www.instagram.com/kevinlushphotography/
Chelsea Hall Photography	Photography	204 South Ludlow Street, Suite 301	Dayton	Ohio	Dayton, Cincinnati, Columbus and surrounding Ohio communities	Studio-based Dayton wedding and portrait photographer working with a small team and offering heirloom-quality prints and products.	info@chelsea-hall.com		https://www.chelsea-hall.com/	https://www.instagram.com/chelseahallphoto/
William Floyd Photography	Photography		Beavercreek	Ohio	Dayton, Columbus and Cincinnati	Beavercreek wedding photographer blending candid photojournalism with classic portraits, and offering engagement sessions and custom albums.			https://wfphotography.net/	
Echo by Design	Photography		Beavercreek	Ohio	Dayton, Cincinnati and Columbus, with worldwide travel	Beavercreek photographer covering weddings, elopements and engagements in a polished style, with printed heirloom pieces for keepsakes.	echo@echobydesign.com	419.217.0714	https://www.echobydesign.com/	https://www.instagram.com/echobydesign/
Austin Carter Photos	Photography		Dayton	Ohio	Dayton suburbs, Southwest Ohio, Northern Kentucky and Indiana	Dayton wedding and engagement photographer who mixes candid and lightly posed images across the Miami Valley and surrounding suburbs.	austincarterphotos@gmail.com	+1-937-503-7037	https://www.austincarterphotos.com/	https://www.instagram.com/austincarterphotos/
Maxim Photo Studio	Photography		Springboro	Ohio	Ohio and Tennessee	Springboro wedding photography studio that sends two photographers to each wedding and also shoots engagement sessions and business headshots.	Max@MaximPhotoStudio.com	937.475.7373	https://maximphotostudio.com/	
Kate Legters Photography	Photography		Dayton	Ohio	Greater Dayton, Cincinnati, Columbus and Lexington	Dayton wedding photographer who documents candid moments alongside formal portraits and includes engagement sessions and timeline planning.	hello@katelegtersphotography.com		https://katelegtersphotography.com/	https://www.instagram.com/katelegtersphotography/
Studio 22 Photography	Photography		Dayton	Ohio	Dayton, Cincinnati, Columbus and destination weddings	Dayton wedding photographer with a bold, playful approach to couples' portraits, also booking destination weddings abroad.		(715) 559-1077	https://www.choosestudio22.com/	https://www.instagram.com/studio22photography/
Studio 213 Films	Videography		Dayton	Ohio	Dayton, Cincinnati, Columbus, Cleveland and destination weddings	Dayton wedding videographer who films couples' stories across Ohio and travels for elopements and destination weddings.	david@studio213films.com	937-241-7834	https://www.studio213films.com/	https://www.instagram.com/studio213films/
WIZ Photo and Video	Videography		Springboro	Ohio	Dayton and Cincinnati	Springboro videography and photography business making cinematic or documentary-style wedding highlight films and love-story videos.	wiz@wizphotoandvideo.com	(937) 689-1868	https://wizphotoandvideo.com/	
Kodjoarts	Videography		Dayton	Ohio	Greater Dayton including Kettering, Centerville, Beavercreek and Springboro	Dayton filmmaker producing story-led wedding films and editorial-style photos, with licensed drone footage where venues permit.			https://www.kodjoarts.com/	
Knights Media Productions	Videography		Springboro	Ohio	Springboro, Centerville, Miamisburg, Beavercreek, Xenia, Troy and wider Miami Valley	Springboro video company offering wedding, corporate and aerial filming for couples across the Dayton and Cincinnati areas.	steve.clark@knightsmedia.com	(937) 889-9444	https://www.knightsmedia.com/	
Sturgis Events	Planning		Dayton	Ohio	Montgomery County and surrounding counties	Solo Dayton coordinator offering day-of wedding coordination and multi-month planning packages, plus event rentals.	eventsbysturgis@gmail.com	937-418-3853	https://www.eventsbysturgis.com/	https://www.instagram.com/sturgisevents/
Pink with Envy Events	Planning		Dayton	Ohio	Dayton and surrounding regions	Dayton planner handling full-service wedding planning and day-of coordination, alongside social and corporate events.	info@pinkwithenvyevents.com		https://www.pinkwithenvyevents.com/	https://www.instagram.com/pinkwithenvyevents/
Pearls & Poppy	Planning		Fairborn	Ohio	Dayton, Cincinnati and greater Ohio	Fairborn team offering wedding planning, month-of and day-of coordination, design, and decor setup and teardown.	pearlsandpoppy@gmail.com	937-750-6795	https://www.pearlsandpoppy.com/	https://www.instagram.com/pearlsandpoppy/
TEC Event Services	Planning		Dayton	Ohio	Dayton, Cincinnati and surrounding areas	Dayton company coordinating wedding days with ceremony and day-of support, all-inclusive receptions and limo service.	TECEventServices@gmail.com	937-254-6930	https://www.teceventservices.com/	https://www.instagram.com/teceventservices/
Floral V Designs	Florals	24 S Main St	Bellbrook	Ohio	Cincinnati/Dayton region and destination	Bellbrook floral studio creating bridal bouquets, table arrangements and larger installations for weddings and events.	hello@floralvdesigns.com	(937) 709-9117	https://floralvdesigns.com/	https://www.instagram.com/floralvdesigns/
Wood Floral Studio	Florals	444 E 3rd St	Dayton	Ohio	Dayton area and destination events	Dayton studio making nature-inspired bouquets, centrepieces and installations for weddings and events.	info@woodfloralstudio.com		https://www.woodfloralstudio.com/	https://www.instagram.com/woodfloralstudio/
Cindy Trick Floral Design	Florals		Beavercreek	Ohio	Dayton and surrounding areas	Beavercreek designer doing wedding and reception flowers, plus rehearsal dinner and other special occasion arrangements.	cindy@cindytrickfloraldesign.com	937-903-6935	https://cindytrickfloraldesign.com/	
Far Hills Florist	Florals		Kettering	Ohio	Greater Dayton including Beavercreek, Springboro, Miamisburg and Xenia	Kettering florist that offers wedding consultations and delivers across the greater Dayton region.	farhillsflorist@gmail.com	(937) 439-0314	https://farhillsflorist.com/	https://www.instagram.com/farhillsflorist/
Oberer's Flowers	Florals		Dayton	Ohio	Miami Valley	Long-established Miami Valley florist offering wedding flower packages for a range of venues and budgets.		(937) 223-1253	https://www.oberers.com/	
Ashley's Pastry Shop	Cake	21 Park Ave	Dayton	Ohio	Greater Dayton	Dayton bakery making custom wedding cakes by appointment, with cupcakes, dessert bars and donut walls as alternatives.	theresa@ashleyspastries.com	(937) 293-1719	https://ashleyspastries.com/	https://www.instagram.com/ashleyspastries/
Purely Sweet Bakery	Cake	3375 Dayton-Xenia Rd	Beavercreek	Ohio	Greater Dayton	Beavercreek bakery taking orders for custom wedding cakes and other celebration bakes, with a retail shop on site.		937-705-6605	https://www.purelysweetbakery.com/	https://www.instagram.com/purelysweetbakery/
Kathy's Cakery & Treats	Cake	115 E. National Rd	Vandalia	Ohio		Vandalia bakery where cake artist Katherine Hanson designs custom wedding cakes with each couple.	kathyscakery@yahoo.com	937-479-2509	https://kathyscakeryandtreats.com/	
Dayton Mobile DJ	Music		Dayton	Ohio	Dayton, Cincinnati, Columbus and select destinations	Wedding DJ and host offering uplighting, a photo booth and cold sparks, working across the Dayton area and further afield.	mitch@DaytonMobileDJ.com	(937) 477-2502	https://www.daytonmobiledj.com/	https://www.instagram.com/daytonmobiledj/
Ohio's Greatest Music	Music		Farmersville	Ohio	Dayton area and across Ohio	Full-service DJ and MC company for wedding receptions, as well as parties, school events and corporate gatherings around Dayton.		(937) 838-5373	https://ohiosgreatestmusic.com/	https://www.instagram.com/ohiosgreatestmusic/
Viva La Strings	Music		Dayton	Ohio	Dayton, Cincinnati, Columbus, Cleveland and Nashville	String quartets, trios and duos playing wedding ceremonies, cocktail hours and dinners, with jazz and guitar options too.	dayton@vivalastrings.com	937-304-0010	https://www.vivalastrings.com/	https://www.instagram.com/vivalastrings/
Catalyst Event Co.	Music		Dayton	Ohio	Dayton, Cincinnati and Columbus	Owner-run wedding DJ and emcee service with sound, dance floor lighting and packages sized by guest count.	hello@catalysteventco.com		https://www.catalysteventco.com/	
Amplified Digital Entertainment	Music		Dayton	Ohio	Dayton, Cincinnati, Columbus and nearby cities	Wedding DJ and emcee company that also supplies lighting and a photo booth for receptions in the Dayton area.		937-813-1312	https://www.amplifieddigitalentertainment.com/	
Possum Creek Ramblers	Music		Dayton	Ohio		Five-piece bluegrass band with banjo, dobro, mandolin and fiddle, available to play weddings in the Dayton area.	possumcreekramblers@gmail.com		https://possumcreekramblers.com/	https://www.instagram.com/possumcreekramblers/
Elite Catering & Events	Catering	2700 E River Rd	Moraine	Ohio	Dayton area	Wedding and event caterer working with a number of Dayton venues, from its base in Moraine.		(937) 559-4590	https://elitecatering.com/	https://www.instagram.com/elitecateringandevents/
LMR Catering	Catering	2700 East River Road	Moraine	Ohio	Dayton area and Southwest Ohio	Full-service caterer running The Mandalay Event Center, with menus from formal plated dinners to backyard barbecues.		(937) 848-2464	https://www.lmrcatering.com/	https://www.instagram.com/lmr_catering_the_mandalay/
Mrs. B's Catering	Catering	101 N. Main St.	Pleasant Hill	Ohio	Miami Valley	Family-run off-premise caterer making food from scratch, with hors d'oeuvres, stations, buffets, plated dinners and barbecue.	info@mrsbscatering.com	937-676-2883	https://mrsbscatering.com/	https://www.instagram.com/mrs_bs_catering/
Brock Masterson's Catering & Events	Catering	101 East Alex Bell Road	Centerville	Ohio	Dayton, Centerville, Kettering, Oakwood, Springboro and Beavercreek	Woman- and family-owned caterer offering wedding menus, desserts and a chocolate fountain, with a small room to hire.		(937) 288-3410	https://www.brockmastersonscatering.com/	https://www.instagram.com/brockmastersonscatering/
Belmont Catering	Catering	730 Watervliet Ave	Dayton	Ohio	Greater Dayton including Kettering, Beavercreek, Centerville, Miamisburg and Xenia	Long-running Dayton caterer providing wedding and formal event menus with staffed service, plus delivery and pickup.		937-253-2197	https://www.belmontcatering.com/	
Kohler Catering & Presidential Banquet Center	Catering	4572 Presidential Way	Dayton	Ohio	Dayton area	Caterer open since 1968 that runs two banquet venues and also serves weddings at other preferred venues.		(937) 291-3600	https://kohlercatering.com/	
Salon Noir Hair Lounge	Hair & Makeup	855 E Franklin Street	Centerville	Ohio		Hair salon offering bridal hair and makeup services for wedding parties from its Centerville base.	salonnoircenterville@gmail.com	(937) 716-1694	https://www.salonnoirdayton.com/	https://www.instagram.com/salonnoirdayton/
Let's Do Makeup and Hair	Hair & Makeup		Dayton	Ohio	Dayton, Cincinnati and Columbus	Travelling hair and makeup team that brings salon-style bridal styling, trials and airbrush makeup to the wedding venue.		(937) 999-1295	https://www.letsdomakeupandhair.com/	https://www.instagram.com/letsdomakeupandhair/
Shear Hotness	Hair & Makeup		Dayton	Ohio	Dayton, Cincinnati, Columbus, Indianapolis and Louisville	Airbrush makeup and hairstyling for brides and wedding parties, led by a stylist trained at Paul Mitchell in Cincinnati.		937.210.7815	https://shearhotness.com/	https://www.instagram.com/shearhotness/
Simply Makeup by Jessica	Hair & Makeup		Dayton	Ohio	Greater Dayton	Bridal and special-event makeup artist offering wedding hair and makeup, lessons and online booking.	simplymakeupbyjessica@gmail.com	937-701-7731	https://www.simplymakeupbyjessica.com/	https://www.instagram.com/simplymakeupbyjessica/
REFeyeANCE Makeup & Hair	Hair & Makeup		Dayton	Ohio	Dayton area, no travel fee	Bridal beauty agency matching couples with licensed hair stylists and makeup artists, with airbrush foundation and lashes.		1-937-550-3034	https://www.bestweddinghairandmakeup.com/	https://www.instagram.com/refeyeance/`,
  },
  {
    name: "Toledo: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Sokol & Co Photo	Photography		Toledo	Ohio	Greater Toledo and Metro Detroit, travelling for weddings elsewhere	Candid, documentary-style wedding and elopement photography from a Toledo studio that limits its yearly bookings and works with a second shooter.	savannahleighphotog@gmail.com		https://sokolco.com/	https://www.instagram.com/sokolcophoto/
Kristen Negrin Photography	Photography		Toledo	Ohio	Toledo, Ohio and beyond	Artistic, candid wedding photography that avoids stiff posing, led by a photographer who grew up in her father's fashion studio.	kristen@kristennicolephotography.com	419-349-4215	http://kristennicolephotography.com/	https://www.instagram.com/kristennicolephoto/
Swatch Studios	Photography	2237 Brothan Dr.	Toledo	Ohio		Relaxed, hands-on wedding photography for couples who dislike posing, with engagement sessions and custom heirloom albums.		(419) 807-1690	https://swatchstudios.com/	https://www.instagram.com/swatchstudios/
Adore Wedding Photography	Photography		Toledo	Ohio	Toledo and Ann Arbor, travelling further for weddings	Husband-and-wife team shooting candid, documentary-style weddings since 2012, with timeline help, engagement sessions and heirloom album options.	Mail@AdorePhotograph.com	(419) 205-0889	https://adoreweddingphotography.com/	https://www.instagram.com/adoreweddingphotography/
Selah Photo Co.	Photography		Toledo	Ohio	Northwest Ohio, travelling for weddings	Timeless, relaxed wedding and elopement photography from a Toledo photographer who also covers engagements, families and seniors.	hello@selahphotoco.com		https://selahphotoco.com/	https://www.instagram.com/selahphotoco/
With Love Photography	Photography		Toledo	Ohio		Romantic, emotive wedding and engagement photography with black and white and true-to-colour galleries, plus planning support on the day.		(419) 908-3402	https://withlovephotographyllc.com/	https://www.instagram.com/withlovephotographyllc/
Ann Neely Events, LLC	Planning		Toledo	Ohio	Toledo, Perrysburg, Columbus, Cleveland, Detroit and beyond	Wedding, corporate and social event planning and design, built around each couple's own vision rather than a standard template.			https://www.annneelyevents.com/	https://www.instagram.com/annneelyevents/
Bee for the Day	Planning		Toledo	Ohio		Wedding consulting and event planning that takes the day's details off the couple's hands so they can enjoy the celebration.		567-277-8301	http://www.beefortheday.com	https://www.instagram.com/beefortheday/
Pineapples & Parties Ltd.	Planning		Perrysburg	Ohio		Event coordination and decorating with close attention to detail, run by a hospitality-trained owner who offers day-of and fuller wedding help.	pineapplesandparties@gmail.com	(419) 246-7685	https://www.pineapplesandpartiesltd.com	https://www.instagram.com/pineapplesandparties/
The Flower Mercantile	Florals	27 Broadway Street	Toledo	Ohio		Wedding and event floral design from a small Toledo studio in the Oliver House, with appointments only and workshops on offer.			https://www.theflowermercantile.com/	https://www.instagram.com/theflowermercantile/
GardenView Flowers	Florals	11160 South River Road	Grand Rapids	Ohio	Northwest Ohio and the Toledo area, with weddings up to 300 miles away	Family flower farm growing its own blooms for full-service wedding design, with flower crowns, installations and resin flower preservation.	ellie@GARDENVIEWFLOWERS.com	(419) 982-8774	https://www.gardenviewweddings.com/	https://www.instagram.com/gardenview_flowers/
Hafner Florist	Florals	5139 Main Street	Sylvania	Ohio		Sylvania florist with a weddings and events team offering seasonal, artful design alongside everyday arrangements and delivery.	hello@hafnerflorist.com	419-885-7033	https://www.hafnerflorist.com	https://www.instagram.com/hafnerflorist/
Bartz Viviano	Florals	4505 Secor Road	Toledo	Ohio	Up to about 1.5 hours from Toledo	Long-established florist with three Toledo-area shops, no wedding minimum, budget-led design and rentals of vases, candles and decor.	flowers@bviviano.com	419-474-1600	https://www.bartzviviano.com/	https://www.instagram.com/bartzviviano/
DJ Diamond Lee	Music		Bowling Green	Ohio		Wedding-focused mobile DJ near Bowling Green offering emcee work, ceremony sound, personalised playlists and optional uplighting since 1999.	djdiamondlee@gmail.com	419-806-5218	https://www.djdiamondlee.com/	https://www.instagram.com/djdiamondlee/
Jason Kent Sound & Lighting	Music		Toledo	Ohio	Toledo, Perrysburg, Maumee and Northwest Ohio	Wedding DJ team with published package pricing, ceremony music, uplighting and photobooth, plus a micro wedding package for under 50 guests.		(419) 619-2291	https://jasonkentdj.com/locations/toledo-ohio-wedding-dj-service/	https://www.instagram.com/dj_jason_kent/
Tree City Catering	Catering	5960 Angola Rd. Ste. 5	Toledo	Ohio	Toledo and Northwest Ohio	Full-service caterer using locally grown ingredients, with buffet, plated and family-style menus, trained serving staff and rentals.	scott@treecitycatering.com	(419) 206-1142	https://www.treecitycatering.com/	https://www.instagram.com/treecitycatering/
Ida's Catering	Catering		Toledo	Ohio	Northwest Ohio	Family-run caterer and event planner of nearly 40 years, known for affordable wedding menus from black tie dinners to backyard barbecue.	info@idascatering.com	419-478-3103	https://www.idascatering.com/	
Sidelines Restaurant Group Catering & Events	Catering		Toledo	Ohio	Northwest Ohio and Southeast Michigan	Restaurant-group caterer offering a mix-and-match wedding menu across Italian, American and barbecue brands, plus its own event venues.	sidelinescatering100@gmail.com	419-574-5516	https://www.sidelinescatering.com	
Beauty by Payton Keller	Hair & Makeup	4604 Woodville Rd	Northwood	Ohio		Independent stylist offering bridal hair and makeup, extensions and dimensional blonding, with a separate wedding site and online booking.	beautybypkeller@gmail.com	(567) 318-2611	https://www.beautybypaytonkeller.com/	https://www.instagram.com/beautybypkeller/
Jeanne Hooven Makeup Artist	Hair & Makeup		Toledo	Ohio		On-site makeup artist for Toledo brides, focused on bridal looks built to last through the day, alongside commercial work.	jeannehoovenmua@gmail.com	419-509-2764	https://www.jeannehoovenmua.com/	
Hanah Jade Beauty	Hair & Makeup		Toledo	Ohio		Travelling bridal hair and makeup artist known for glowy soft glam, doing 60 to 70 weddings a year with bridesmaid packages.			https://www.hanahjadebeauty.com	https://www.instagram.com/thehanahjade/
Glamour by Taylor	Hair & Makeup	3150 Chappel Dr	Perrysburg	Ohio		Bridal makeup artist who also offers clean-skincare facials before the wedding, with kits stocked for the whole party.	glamourbytaylor.mua@gmail.com	(419) 464-7526	https://www.glamourbytaylor.com	
Eston's Bakery	Cake	5433 Monroe Street	Toledo	Ohio	Greater Toledo area	Toledo bakery of nearly four decades making dessert-style tiered wedding cakes, with ten signature flavours and a free anniversary cake.		(419) 885-9442	https://estonsbakery.com/	
McKiddy Cakes	Cake		Sylvania	Ohio		Family-run Sylvania cake shop making custom wedding cakes and dessert bars, with a wide flavour menu and tastings by arrangement.		(419) 250-0788	https://mckiddycakes.com/	https://www.instagram.com/mckiddycakesltd/
7 Little Cupcakes	Cake	122 West South Boundary	Perrysburg	Ohio	Northwest Ohio and Southeast Michigan	Women-owned Perrysburg cake studio since 2015, with over 700 wedding cakes behind it and custom cupcake and dessert tables.	hello@7littlecupcakes.com	419-252-0858	https://www.7littlecupcakes.com/	https://www.instagram.com/7.little.cupcakes/
7th Floor Wedding Films	Videography		Toledo	Ohio	Based in Toledo and available worldwide	Cinematic wedding films focused on real moments and emotion, sold as four collections from short essentials to a complete day.	Steve@7floormedia.com		https://www.7floormedia.com/	https://www.instagram.com/7thfloormedia/
tcfilmstudios	Videography		Sylvania	Ohio		Two-filmmaker team shooting wedding films on two cameras, with ceremony, full-day and premium packages and full footage delivered.	tcfilmstudios@gmail.com		https://www.tcfilmstudios.com/	https://www.instagram.com/tcfilmstudios/
M Label Media	Videography		Findlay	Ohio	No travel fee for Ohio, Michigan, Indiana, Illinois, Pennsylvania and Kentucky	Wedding filmmaker and photographer working between Findlay and Michigan in an editorial, photojournalistic style, taking limited bookings.	inquire@mlabelmedia.com		https://www.mlabelmedia.com/	https://www.instagram.com/mlabelmedia/`,
  },
  {
    name: "Akron and Canton: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
David Corey Photography	Photography	3101 Vermont Pl.	Akron	Ohio	Akron, Canton, Cleveland and Northeast Ohio	Akron studio photographing weddings and portraits in a timeless style, with print rights to every image and custom albums.	info@davidcoreyphotography.com	330-858-8838	https://www.davidcoreyphotography.com/	https://www.instagram.com/davidcoreyphoto/
Justin Gamble Photography	Photography		Cuyahoga Falls	Ohio	Cleveland, Akron, Canton and Youngstown, plus travel	Cuyahoga Falls studio offering guided wedding and engagement coverage, with premium heirloom artwork made from the finished images.	justin@justingamblephotography.com	330-283-3666	https://www.justingamblephotography.com/	https://www.instagram.com/whatsupimjustin/
K Photography	Photography		Canton	Ohio	Akron, Canton, Cleveland, Medina, Stow, Kent, Hudson, Massillon and across Northeast Ohio	Faith-driven wedding photographer with over a decade of experience who also helps couples shape their timeline and family photos.			https://www.kphotographystudio.com/	https://www.instagram.com/kphotography_weddings/
Guy's Party Center	Planning	500 E Waterloo Rd	Akron	Ohio	Stark County and Summit County	Family-run Akron party centre offering wedding planning and day-of coordination with an on-site coordinator, plus its own ballrooms.		330-403-9091	https://www.guyspartycenter.com/	https://www.instagram.com/guyspartycenter/
Bellar Events	Planning		Medina	Ohio	All of Northeast Ohio	Medina team of certified event professionals handling wedding-day coordination and officiant services across Northeast Ohio.	info@bellarevents.com	330-388-8190	https://www.bellarevents.com/	
Savoir-Faire Event Planning	Florals	2291 West Market St	Akron	Ohio	Greater Akron	Single-artist Akron studio designing bespoke wedding bouquets, ceremony installations and tablescapes, each hand-tied in house.		330-835-9055	https://savoirfaireflorist.com/	https://www.instagram.com/savoirfaire_akron/
C R Blooms Floral	Florals	1494 E. Smithville Western Rd.	Wooster	Ohio	Wooster and surrounding areas	Wooster florist providing ceremony and reception flowers, bouquets and wedding party pieces alongside everyday same-day delivery.		330-345-1503	https://www.crblooms.com/	
The Budding Tree	Florals	403 N Main St	Munroe Falls	Ohio	Munroe Falls and Akron and Cleveland-area venues	Munroe Falls floral studio that grew from wedding and event design, offering seasonal bouquets and consultations by appointment.	thebuddingtree@gmail.com	330-338-5508	https://www.thebuddingtree.com/	https://www.instagram.com/thebuddingtree/
Evening Star Entertainment	Music		Waynesburg	Ohio	Akron, Canton, Cleveland, Medina, Massillon and Northeast Ohio	Waynesburg DJ and MC service with uplighting, ceremony music and an online planning portal, offering unlimited-hours packages.		330-353-9401	https://eveningstarent.com/	
The Crew	Music		Akron	Ohio	Akron, Cleveland and Northeast Ohio	Akron team combining wedding DJ and MC, photo booth, photography and videography under one roof, with uplighting available.	info@thedjcrew.com	330-869-5665	https://crewweddings.com/	https://www.instagram.com/thecrewohio/
Drop The Mic Entertainment	Music		Akron	Ohio	Cleveland, Canton and Akron	Wedding DJ company offering music-selection help and professional emceeing of key moments, as well as private and corporate sets.		330-631-6469	https://www.dropthemicentertainment.com/	
Natalie's Catering	Catering		Akron	Ohio	Akron, with off-site catering	Akron caterer since 1993 offering off-site wedding menus for a range of budgets, plus custom wedding cakes and dessert bars.	NParksEvents@gmail.com	330-860-7795	https://www.nataliecatering.com/	https://www.instagram.com/nataliesakron/
Eclectic Edibles Catering	Catering	1300 W Waterloo Rd	Akron	Ohio	Greater Akron	Woman-owned Akron caterer cooking from scratch, with custom menus, allergy handling and experience from small gatherings to 350 guests.		330-608-5707	https://www.eclecticediblescatering.com/	https://www.instagram.com/eclecticediblescatering/
Village Catering Company	Catering	637 E Main St.	Smithville	Ohio	Canton, Stark County, North Canton, Massillon, Akron and Wooster	Smithville caterer offering plated, buffet and family-style wedding service, with tastings and venue coordination through the timeline.		330-669-9151	https://villagecateringcompany.com/	https://www.instagram.com/villagecateringcompany/
Love Beautiful Skin	Hair & Makeup	8433 Cleveland Ave NW	North Canton	Ohio	North Canton, Akron, Canton, Cleveland and Columbus, with on-location travel	North Canton spa offering mineral-based wedding makeup, hairstyling and lessons, with on-location service for bridal parties.		330-323-7049	https://lovebeautifulskin.com/	https://www.instagram.com/lovebeautifulskin/
VIVO Beauty Bar	Hair & Makeup		Cuyahoga Falls	Ohio	On location or in salon, including Akron and Fairlawn	Cuyahoga Falls salon with a dedicated bridal coordinator, offering hair and makeup for brides and guests on location or in the salon.		234-303-6780	https://www.vivobeautybar.com/	https://www.instagram.com/vivobeautybar/
Tiffany's Bakery	Cake	620 Ridgewood Crossing	Akron	Ohio	Akron area	Family bakery serving Akron for fifty years, making custom wedding and birthday cakes alongside everyday baking and ice cream.	tiffanysbakeryakron@gmail.com	330-668-2253	https://tiffanysbakeryakron.com/	https://www.instagram.com/tiffanysbakeryakron/
Stacked Akron	Cake	1185 Canton Road	Akron	Ohio		Akron bakery making custom cookies, cupcakes and wedding cakes, with tastings and consultations arranged by phone.	stackedakron@gmail.com	330-604-1781	https://www.stackedakron.com/	
Omalicha Custom Cakes & Confectionery	Cake		Akron	Ohio	Summit County	Licensed Akron home bakery making wedding cakes in minimalist, detailed and luxe styles, with vegan options and macarons.	info@omalichacakes.com	216-767-6115	https://omalichacakes.com/	https://www.instagram.com/omalichacustomcakes/
Work Shed Weddings	Videography		Akron	Ohio	Northeast Ohio and Western Pennsylvania	Akron film team blending documentary storytelling with cinematic visuals, making teasers, highlight films and short films of the day.	weddings@workshedpictures.com	330-790-1797	https://workshedweddings.com/	https://www.instagram.com/workshedweddings/
Canton Wedding Videos	Videography		Canton	Ohio	Canton, Akron, Youngstown, Cleveland and Massillon	Canton videographer producing highlight reels, social-ready clips and behind-the-scenes footage from getting ready through the vows.			https://cantonweddingvideos.com/	`,
  },
  {
    name: "Columbus: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Brookmade Photography	Photography		Columbus	Ohio		Editorial wedding photographer in Columbus shooting polished, fashion-minded wedding days, plus elopements and events for modern couples.	hello@brookmade.com		https://brookmadephotography.com/	https://www.instagram.com/brookmadephotography/
Robb McCormick Photography	Photography		Columbus	Ohio	Central Ohio	Columbus photographer with more than 700 weddings behind him, known for dramatic light and unposed moments, who also covers corporate and portrait work.	info@robbmccormick.com		https://robbmccormick.com/	https://www.instagram.com/robbmccormickphotography/
Kovyphoto	Photography		Columbus	Ohio	Columbus and Central Ohio	Husband-and-wife duo with two photographers at every session, documenting proposals, micro weddings and full weddings in a cinematic, emotional style.			https://kovyphoto.com/	https://www.instagram.com/kovy.photo/
Vivere Visuals	Videography		Columbus	Ohio	Ohio and destination weddings	Husband-and-wife team making wedding films alongside photography, with a guided, emotion-led approach and willingness to travel for destination weddings.			https://viverevisuals.com/	https://www.instagram.com/viverevisuals/
Milo's Catering	Catering	980 West Broad Street	Columbus	Ohio		Columbus caterer with more than 25 years' experience, handling weddings alongside drop-off and full-service events at accessible prices.	info@cateringbymilos.com	(614) 224-0272	https://cateringbymilos.com/	https://www.instagram.com/miloscatering/
Catering By Scott	Catering		Columbus	Ohio	Central Ohio	Family-owned caterer with over 37 years behind it, building custom wedding and corporate menus with gluten-free options and delivery across Central Ohio.		(380) 285-6767	https://cateringbyscott.com/	https://www.instagram.com/cateringbyscott/
Carfagna's Catering	Catering	1440 Gemini Place	Columbus	Ohio	Central Ohio	Italian-leaning caterer attached to a family market, offering wedding packages that include an Italian dinner option and a complimentary menu tasting.	catering@carfagnas.com	(614) 846-6340	https://carfagnascatering.com/	
The Planning Bee	Planning		Columbus	Ohio		Full-service wedding and event planning studio stressing clear communication and careful logistics, which also runs its own downtown venue, Genesis.	hello@theplanningbee.com		https://theplanningbee.com/	https://www.instagram.com/theplanningbeeplans/
Lēf Floral & Botanical	Florals	243 N. 5th St	Columbus	Ohio		Locally owned downtown florist creating garden-inspired wedding flowers, with a complimentary consultation and a studio shop on North 5th Street.	contact@leffloral.com	(614) 254-6280	https://leffloral.com/	https://www.instagram.com/leffloral/
Events By Maryam	Florals	555 Buttles Ave	Columbus	Ohio	Ohio	Design studio for Pakistani, Somali, Indian, Nepali and Habesha weddings, building stages, florals and venue décor with its own installation crew.	bookings.eventsbymaryam@gmail.com	(614) 927-9772	https://eventsbymaryam.com/	https://www.instagram.com/decor_eventsbymaryam/
The Big Badd	Music		Columbus	Ohio		Wedding and event band with horns, rhythm section and singers, offering optional ceremony and cocktail music, DJ-plus services and a photo booth.	booking@thebigbadd.com	(614) 352-0306	https://thebigbadd.com/	https://www.instagram.com/thebigbaddband/
Goode Beauty LLC	Hair & Makeup		Dublin	Ohio	Central Ohio	Dublin-based travelling team doing bridal hair and makeup at the venue, bridal suite or home for weddings across Central Ohio.	Shannon@GoodeBeauty.com	(614) 578-6941	https://goodebeautyhairandmakeup.com/	
614 Beauty	Hair & Makeup	7140 N. High St., Suite 210 & 220	Worthington	Ohio		Worthington makeup studio and med spa offering wedding hair and makeup alongside lessons, facials and on-set work.	info@614beauty.com	(614) 400-9604	https://614beauty.com/	https://www.instagram.com/614.beauty/
Fate Cakes	Cake	1360 Cherry Bottom Road	Gahanna	Ohio		Gahanna cake shop making custom wedding cakes and desserts, with bookable tasting boxes and local delivery.	info@fate-cakes.com	(614) 219-9429	https://fate-cakes.com/	https://www.instagram.com/fatecakescolumbus/
Sauer Cakes LLC	Cake		Gahanna	Ohio	Columbus and Central Ohio	Gahanna cake maker designing custom wedding cakes for the Columbus area, with a published flavour and filling list and delivery with set-up.	michelle@sauercakes.com	(614) 428-9741	https://sauercakes.com/	https://www.instagram.com/sauercakes/`,
  },
  {
    name: "Cleveland: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mariya Bee Photo	Photography		Cleveland	Ohio	Northeast Ohio	Cleveland photographer shooting weddings and engagements in warm, colour-rich tones, with published packages and videography as an add-on.	contact@mariyabeephoto.com		https://mariyabeephoto.com/	https://www.instagram.com/mariyabeephoto/
Eva Mea Event Design	Planning		Cleveland	Ohio	Cleveland and beyond	Cleveland planning and design firm taking weddings from vendor matching and budgeting through day-of execution, plus corporate and nonprofit events.	info@evamea.com		https://evamea.com/	https://www.instagram.com/evameaeventdesign/
HeatherLily	Planning	3050 Lakeside Avenue	Cleveland	Ohio	Northeast Ohio	Cleveland wedding planner that also runs a floral studio, taking a limited number of floral commissions each season and urging early booking.	info@heatherlily.com	(216) 862-2864	https://heatherlily.com/	https://www.instagram.com/heatherlily/
T. Florals	Florals		Cleveland Heights	Ohio	Cleveland and greater Cleveland	Cleveland Heights florist focused on weddings, making garden-style bouquets and ceremony installations from locally sourced blooms.	tonya@tflorals.com	(216) 410-1384	https://tflorals.com/	https://www.instagram.com/tflorals/
Coyne Catering	Catering	22909 Center Ridge Rd	Rocky River	Ohio	Avon Lake, Broadview Heights, Brunswick, Elyria, Lorain, Medina, North Olmsted, Parma, Strongsville	Rocky River caterer with decades of Cleveland wedding experience, working at its own venue and at off-site locations across the western suburbs.	coynecateringcleveland@gmail.com	(216) 695-1160	https://coynecatering.com/	https://www.instagram.com/coynecatering/
Cleveland Beauty Collective	Hair & Makeup	1127 Rowley Ave	Cleveland	Ohio	Northeast Ohio	Agency matching couples with vetted hair and makeup artists for bridal parties, handling booking from start to finish, with makeup lessons too.	hello@clevelandbeautycollective.com	(216) 618-7484	https://clevelandmakeupartistry.com/	https://www.instagram.com/clevelandbeautycollective/
Chrissy Hart Makeup Artistry	Hair & Makeup		Cleveland	Ohio		Solo Cleveland makeup artist offering traditional or airbrush bridal makeup on location, with basic hairstyling and tattoo coverage available.	chrssyhrt@gmail.com		https://chrssyhrt.com/	https://www.instagram.com/chrissyhart/
Top Tier Cakes Cleveland	Cake	25971 Detroit Road	Westlake	Ohio		Westlake bakery and cake studio led by pastry chef Ashley Zinicola-Joslin, making wedding and celebration cakes with a walk-in counter.	toptiercle@gmail.com	(440) 688-1899	https://toptiercakescleveland.com/	https://www.instagram.com/toptiercakescleveland/
K2 Custom Cakes & Treats	Cake		Cleveland	Ohio		Cleveland cake maker offering round, tiered and seasonal gourmet wedding cakes, vintage heart cakes and treats by the dozen.			https://k2cakes.com/	https://www.instagram.com/k2cakescle/
The Image In Motion	Videography		Cleveland	Ohio		Husband-and-wife Cleveland filmmakers making cinematic wedding films, with a strong run of couple testimonials on their site.	vince@theimageinmotion.com	(440) 975-6792	https://theimageinmotion.com/	https://www.instagram.com/theimageinmotion/
P47 Productions	Videography		North Royalton	Ohio	Cleveland and Northeast Ohio	North Royalton production company filming weddings in cinematic or documentary styles, alongside commercial, live-event and tape-to-digital work.		(330) 510-2115	https://p47productions.com/	https://www.instagram.com/p47productions/`,
  },
  {
    name: "Cincinnati: photography, planning, florals, music, catering, hair and makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alex Marie Photos	Photography		Cincinnati	Ohio	Ohio and Kentucky	Cincinnati fine-art wedding photographer documenting genuine, romantic moments across Ohio and Kentucky, with family sessions on offer too.	hello@alexmariephotos.com		https://alexmariephotos.com/	https://www.instagram.com/alexmariephotos/
Fortheloved Photography	Photography		Cincinnati	Ohio	Cincinnati and destination weddings	Cincinnati wedding and elopement photographer with a tender, documentary approach who also offers mentorships to other photographers.			https://forthelovedphotography.com/	https://www.instagram.com/forthelovedphotography/
I Thee Wed	Planning		Cincinnati	Ohio	Cincinnati tri-state area	Small woman-owned planning business offering full and partial planning, plus coordination for couples who have organised most of it themselves.	itheewedplanning@gmail.com	(513) 315-3122	https://itheewedconsulting.com/	https://www.instagram.com/itheewedplanning/
Glass and Grace Events	Planning		Cincinnati	Ohio	Dayton and Cincinnati	Planning and design studio serving Dayton and Cincinnati, focused on luxury styling, tidy timelines and stress-free coordination.			https://glassandgraceevents.com/	https://www.instagram.com/glassandgraceevents/
Floral in Bloom	Florals		Cincinnati	Ohio	Ohio	Cincinnati floral studio for weddings and celebrations, offering full-service design as well as smaller packages for elopements and intimate weddings.	floristinbloom8@gmail.com		https://floral-in-bloom.com/	https://www.instagram.com/florist.in.bloom/
Aurous Floral Design Studio	Florals		Cincinnati	Ohio		Boutique Cincinnati studio designing bouquets and arrangements for weddings, elopements and small events, plus flower subscriptions and flower-bar workshops.	Pamela@AurousFloralDesign.com	(513) 570-4308	https://aurousfloraldesign.com/	https://www.instagram.com/aurousfloraldesign/
Queen City Quartet	Music		Cincinnati	Ohio		Cincinnati string duo, trio or quartet playing ceremonies, cocktail hours and dinner parties, with a Bridgerton-style repertoire.			https://queencityquartet.wixsite.com/queencity	https://www.instagram.com/queencityquartet/
CookUp Catering	Catering	1719 Elm Street	Cincinnati	Ohio		Cincinnati caterer with affordable wedding menus, from plated courses to buffets and food stations, using locally sourced ingredients.		(513) 889-8198	https://cookupcatering513.com/	https://www.instagram.com/cookupcatering513/
Blend Artistry	Hair & Makeup	316 Main Street, Suite C	Hamilton	Ohio	Cincinnati area	Hair and makeup team based in Hamilton that travels to weddings across the Cincinnati area, with salon appointments available as well.		(513) 827-2220	https://blendartistryohio.com/	https://www.instagram.com/salonblendohio/
Tanya's Image & Wellness Salon	Hair & Makeup	2716 Erie Ave.	Cincinnati	Ohio		Hyde Park Square salon that sends on-site hair and makeup artists to weddings, with trial sessions and clear per-service pricing.	tanya@tanyasimage.com	(513) 533-9400	https://tanyasimage.com/	https://www.instagram.com/tanyas_image/
Happy Chicks Bakery	Cake	4035 Hamilton Avenue	Cincinnati	Ohio		Independent Northside bakery making artistic wedding cakes in a dedicated egg- and dairy-free space.	happychicksbakery@gmail.com	(513) 386-7990	https://happychicksbakery.com/	https://www.instagram.com/happychicksbakery/`,
  },
  {
    name: "Columbus: videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Columbus Wedding Videos	Videography	5568 Cloverdale Dr	Galena	Ohio	Columbus and central Ohio	Galena-based studio making cinematic highlight films and full-length documentary-style wedding videos for central Ohio couples.	info@columbusweddingvideos.com	614.725.0169	https://columbusweddingvideos.com/	https://www.instagram.com/columbusweddingvideos/`,
  },
  {
    name: "Cleveland: music",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Selective Sound Events	Music	26601 Richmond Rd	Bedford Heights	Ohio	Cleveland and surrounding areas	Cleveland DJ, MC and live party band company that also supplies ceremony audio, lighting and photo booths for weddings.	info@selectivesound.com	(440) 516-0020	https://www.selectivesound.com/	https://www.instagram.com/selectivesoundevents/`,
  },
  {
    name: "Toledo: music",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Sounds of Music DJs	Music		Toledo	Ohio	North-west Ohio and south-east Michigan	Toledo DJ and MC service for weddings and parties, which also produces two local bridal shows each year.			https://www.soundsofmusicdjs.com/	`,
  },
  {
    name: "Akron and Canton: planning, hair and makeup and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Always Eventful	Planning		Akron	Ohio	Akron, Canton and Cleveland	Event planner who organises weddings and company celebrations for couples across Akron, Canton and Cleveland.	triciadever91@gmail.com	(330) 354-7133	https://alwayseventful.com/	https://www.instagram.com/triciadeverevents/
MAVON Beauty	Hair & Makeup	2830 Copley Rd Suite D	Copley	Ohio	Akron, Canton, Cleveland and Columbus	Studio offering on-location bridal hair and makeup, including styling for Indian and South Asian multi-day weddings.		330.730.9711	https://www.mavonbeauty.com/	
Work Shed Weddings	Videography		Akron	Ohio	Akron, Cleveland, Canton, Youngstown and Pittsburgh	Akron wedding film studio blending documentary storytelling with cinematic visuals across north-east Ohio and western Pennsylvania.	weddings@workshedpictures.com	330.790.1797	https://workshedweddings.com/	https://www.instagram.com/workshedweddings/`,
  },
];

export default batches;
