import type { VendorBatch } from "@/lib/vendor-batches";

// Ohio vendor batches. Every row's State is "Ohio". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Columbus: photography, planning, florals, music and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kismet Visuals & Co	Photography		Columbus	Ohio	Columbus, the Midwest and destinations worldwide	Documentary-minded wedding photographer working since 2010, focused on honest, unposed moments and timeless images, with destination coverage on offer.			https://www.kismetvisuals.com/	https://www.instagram.com/kismetvisuals/
Asteria Photography	Photography		Columbus	Ohio	Ohio, with travel across the US and to Europe	Storytelling wedding photography centred on candid emotion and the feel of the day, with complete packages and regular travel beyond Ohio.	asteriaphoto@gmail.com	614-648-3967	https://www.asteriaphotography.com/	https://www.instagram.com/asteriaphoto/
Brad Gillespie Photography	Photography		Columbus	Ohio	Throughout Ohio	Columbus wedding and engagement photographer since 2020 creating warm, romantic, timeless images that reflect each couple's personalities.			https://www.bradgillespiephotography.com/	https://www.instagram.com/bradgillespiephotography/
Zolana Weddings	Planning		Columbus	Ohio	Columbus, Philadelphia, New Jersey and Delaware	Full and partial planning, wedding management and multi-day events, specialising in multicultural weddings that blend more than one family tradition.			https://www.zolanaweddings.com/	https://www.instagram.com/zolana.weddings/
Aisle & Co	Planning		Columbus	Ohio	Ohio, the Raleigh-Durham area and destinations including Italy	Planning and design firm offering full planning, styling and month-of coordination for couples marrying locally or at destinations abroad.	hello@aisleandcompany.com		https://aisleandcompany.com/	https://www.instagram.com/aisleandco/
Adoration Weddings & Events	Planning		Columbus	Ohio	Columbus and destination weddings nationwide	Latina- and woman-owned planning studio offering full-service planning and design, wedding management from three months out, and hourly consultations.			https://www.adorationweddings.com/	https://www.instagram.com/adorationweddings/
Camela Lynn Weddings & Events	Planning		Dublin	Ohio	Dublin and the surrounding Columbus area, travel available	Dublin-based planner offering full, partial, month-of and hourly wedding planning, along with dessert table design for receptions.	events@camelalynnweddingsandevents.com		https://www.camelalynnweddingsandevents.com/	
Flocal Co Floral Studio	Florals	1464 W 5th Ave	Columbus	Ohio	Columbus, including Grandview, Upper Arlington, Dublin, Worthington and Bexley	Woman-owned Grandview-area floral studio building lush, garden-style wedding flowers and installations, with full-service and pick-up options.		(614) 408-3985	https://www.flocalcompany.com/	https://www.instagram.com/flocalcofloralstudio/
Prema Designs	Florals		Columbus	Ohio	Columbus and destination weddings	Wedding design firm working since 2010 on abundant florals and large-scale installations, with an a la carte flower collection for smaller events.			https://www.prema-designs.com/	https://www.instagram.com/prema_designs/
Madison House Designs	Florals	19817 Raymond Rd	Marysville	Ohio	Weddings throughout Columbus and select destinations	Wedding and event florist near Marysville designing refined, naturally placed arrangements scaled to each venue across the Columbus area.	lynette@madisonhousedesigns.com	614-561-0135	https://www.madisonhousedesigns.com/	https://www.instagram.com/madisonhouseflowers/
Femme Floral	Florals		Columbus	Ohio	Columbus and travel for events	Art-forward floral studio combining sculptural flower design with ceiling and wall draping to shape the whole look of a wedding space.	designsbyfemme@gmail.com		https://www.femme-floral.com/	https://www.instagram.com/femmefloraldesigns/
Arch City Lights	Music		Columbus	Ohio	Columbus and neighbouring areas	Columbus party band playing soul, Motown, funk and current R&B, with acoustic, string and DJ options for the ceremony and cocktail hour.	archcitylights@gmail.com		https://www.archcitylights.com/	https://www.instagram.com/archcitylights/
Columbus Musicians	Music		Columbus	Ohio	Columbus area	Live wedding music agency supplying string quartets, harp, piano, brass, jazz ensembles and reception bands from guest arrival to last dance.	columbusmusicians@gmail.com	419-944-8965	https://www.columbusmusicians.com/	
LogieBear Sound & Lighting	Music		Columbus	Ohio	Central Ohio including Dublin, New Albany, Westerville and Downtown Columbus	Wedding DJ and MC mixing live with uplighting included, plus add-ons such as live saxophone, photo booth and an audio guestbook.	Logan@LogieBearSNL.com	(614) 917-3787	https://www.logiebearsnl.com/	https://www.instagram.com/logiebear.snl/
Platinum Music Productions	Music		Columbus	Ohio	Columbus and Central Ohio	Wedding DJ company running since 2005, offering ceremony audio, dance-floor lighting, custom monograms, cold-spark effects and a mirror photo booth.		614-407-6935	https://platinummusicdj.com/	https://www.instagram.com/platinummusicdj/
Cameron Mitchell Premier Events	Catering	7619 Huntington Park Dr.	Columbus	Ohio	Columbus and the surrounding region	Full-service caterer and event team that also plans and designs weddings and runs three Columbus event spaces, including The Stack.		(614) 848-4700	https://cameronmitchellpremierevents.com/	https://www.instagram.com/cmpe_columbus/
Bosc + Brie	Catering	7625 North High Street	Columbus	Ohio		North Columbus caterer with in-house planners, linens and cake cutting included, and a bring-your-own-alcohol option that helps trim bar costs.		614.985.2215	https://www.boscandbrie.com/	https://www.instagram.com/bosc_and_brie/
Fire & Knife	Catering		Columbus	Ohio	Homes, workplaces and venues across Ohio	Columbus caterer specialising in weddings with refined global menus served as a buffet or plated dinner, with a dedicated catering sales contact.	info@fireandknife.com	614.758.3659	https://www.fireandknife.com/	`,
  },
  {
    name: "Columbus: hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hertty's Bakeshop	Cake	100 E Campus View Blvd Suite #250	Columbus	Ohio	Columbus, with delivery required for wedding cakes	Family-run cake design studio in north Columbus making custom tiered wedding cakes by consultation appointment, with sugar flowers and fine detailing.	info@herttysbakeshop.com	614-373-7699	https://www.herttysbakeshop.com/	
Lavender and Honey Wedding Cakes	Cake		Columbus	Ohio	Columbus	Boutique Columbus bakery making scratch-baked custom wedding cakes and desserts, with tasting boxes couples can sample at home.	info@lavenderandhoneyweddingcakes.com	(614) 547-9851	https://www.lavenderandhoneyweddingcakes.com/	
Our CupCakery	Cake	54 S. High St.	Dublin	Ohio		Family-owned bakery in Historic Dublin offering classic tiered wedding cakes alongside cupcake displays, with a dedicated wedding request process.	Laura@ourcupcakery.com	614-659-1555	https://www.ourcupcakery.com/	
Sweet & Shiny	Cake		Columbus	Ohio		Columbus custom cake maker producing wedding cakes and decorative display cakes, with a wedding gallery and an online bakery shop.	elaine@sweetandshiny.com	614-680-9195	https://www.sweetandshiny.com/	https://www.instagram.com/sweetandshiny_columbus/
Columbus Wedding Videos	Videography		Columbus	Ohio	Central Ohio	Long-running Central Ohio video team filming since 2008, offering unobtrusive full-length documentary edits alongside shorter cinematic films.	info@columbusweddingvideos.com	614.725.0169	https://columbusweddingvideos.com/	https://www.instagram.com/columbusweddingvideos/
Hey Films	Videography		Columbus	Ohio	Columbus, Dublin, Westerville, New Albany and Central Ohio	Columbus wedding film studio with hourly packages from a short three-hour shoot to two-videographer full days, and two-week delivery.			https://heyfilms.com/	https://www.instagram.com/heyfilmsweddings/
Cinemachine Studios	Videography		Columbus	Ohio	Columbus area	Columbus video team making cinematic wedding films that lean on deliberate camera movement, angles and lighting to tell each couple's day.	info@cinemachinestudios.com		https://www.cinemachinestudios.com/	
The Lovely Artistry Collective	Hair & Makeup		Columbus	Ohio	Ohio and nationwide, travelling worldwide	Bridal hair and makeup team founded in 2011 for classic, timeless looks, with more than 3,000 brides styled and travel for destination weddings.			https://thelovelyartistrycollective.com/	https://www.instagram.com/thelovelyartistrycollective/
Lauren Wolff Hair Design	Hair & Makeup	1500 West 3rd Ave	Columbus	Ohio	Columbus area	Licensed cosmetologist creating long-lasting bridal hairstyles from a Grandview-area studio, alongside editorial styling and hair education.	hello@laurenwolffhairdesign.com		https://www.laurenwolffhairdesign.com/	https://www.instagram.com/lo.wolff_hairdesign/
Makeup with Anna K	Hair & Makeup		Columbus	Ohio	Columbus and destination weddings	Bridal makeup artist using luxury brands, with bridal party packages and a VIP option that pairs a two-hour facial with wedding makeup.	makeupwithannak@gmail.com		https://www.makeupwithannak.com/	https://www.instagram.com/makeup.with.annak/
Carly Jo Makeup	Hair & Makeup		Columbus	Ohio	Central Ohio	Bridal makeup artist focused on intimate weddings and elopements, aiming for a polished look that still feels like the bride herself.			https://www.carlyjomakeup.com/	https://www.instagram.com/carlyjomakeup/`,
  },
];

export default batches;
