import type { VendorBatch } from "@/lib/vendor-batches";

// Ohio vendor batches. Every row's State is "Ohio". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Columbus: photography, planning, florals, music and catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kismet Visuals & Co	Photography		Columbus	Ohio	Columbus, the Midwest and destinations worldwide	Documentary-minded wedding photographer working since 2010, focused on honest, unposed moments and timeless images, with destination coverage on offer.			https://www.kismetvisuals.com/	https://www.instagram.com/kismetvisuals/
Asteria Photography	Photography		Columbus	Ohio	Ohio, with travel across the US and to Europe	Storytelling wedding photography centred on candid emotion and the feel of the day, with complete packages and regular travel beyond Ohio.	asteriaphoto@gmail.com	614-648-3967	https://www.asteriaphotography.com/	https://www.instagram.com/asteriaphoto/
Brad Gillespie Photography	Photography		Columbus	Ohio	Throughout Ohio	Columbus wedding and engagement photographer since 2020 creating warm, romantic, timeless images that reflect each couple's personalities.			https://www.bradgillespiephotography.com/	https://www.instagram.com/bradgillespiephotography/
Zolana Weddings	Planning		Columbus	Ohio	Columbus, Philadelphia, New Jersey and Delaware	Full and partial planning, wedding management and multi-day events, specialising in multicultural weddings that blend more than one family tradition.			https://www.zolanaweddings.com/	https://www.instagram.com/zolana.weddings/
Aisle & Co	Planning		Columbus	Ohio	Ohio, the Raleigh-Durham area and destinations including Italy	Planning and design firm offering full planning, styling and month-of coordination for couples marrying locally or at destinations abroad.	hello@aisleandcompany.com		https://aisleandcompany.com/	https://www.instagram.com/aisleandco/
Adoration Weddings & Events	Planning		Columbus	Ohio	Columbus and destination weddings nationwide	Latina- and woman-owned planning studio offering full-service planning and design, wedding management from three months out, and hourly consultations.			https://www.adorationweddings.com/	https://www.instagram.com/adorationweddings/
Camela Lynn Weddings & Events	Planning		Dublin	Ohio	Dublin and the surrounding Columbus area, travel available	Dublin-based planner offering full, partial, month-of and hourly wedding planning, along with dessert table design for receptions.	events@camelalynnweddingsandevents.com		https://www.camelalynnweddingsandevents.com/	
Flocal Co Floral Studio	Florals	1464 W 5th Ave	Columbus	Ohio	Columbus, including Grandview, Upper Arlington, Dublin, Worthington and Bexley	Woman-owned Grandview-area floral studio building lush, garden-style wedding flowers and installations, with full-service and pick-up options.		(614) 408-3985	https://www.flocalcompany.com/	https://www.instagram.com/flocalcofloralstudio/
Prema Designs	Florals		Columbus	Ohio	Columbus and destination weddings	Wedding design firm working since 2010 on abundant florals and large-scale installations, with an a la carte flower collection for smaller events.			https://www.prema-designs.com/	https://www.instagram.com/prema_designs/
Madison House Designs	Florals	19817 Raymond Rd	Marysville	Ohio	Weddings throughout Columbus and select destinations	Wedding and event florist near Marysville designing refined, naturally placed arrangements scaled to each venue across the Columbus area.	lynette@madisonhousedesigns.com	614-561-0135	https://www.madisonhousedesigns.com/	https://www.instagram.com/madisonhouseflowers/
Femme Floral	Florals		Columbus	Ohio	Columbus and travel for events	Art-forward floral studio combining sculptural flower design with ceiling and wall draping to shape the whole look of a wedding space.	designsbyfemme@gmail.com		https://www.femme-floral.com/	https://www.instagram.com/femmefloraldesigns/
Arch City Lights	Music		Columbus	Ohio	Columbus and neighbouring areas	Columbus party band playing soul, Motown, funk and current R&B, with acoustic, string and DJ options for the ceremony and cocktail hour.	archcitylights@gmail.com		https://www.archcitylights.com/	https://www.instagram.com/archcitylights/
Columbus Musicians	Music		Columbus	Ohio	Columbus area	Live wedding music agency supplying string quartets, harp, piano, brass, jazz ensembles and reception bands from guest arrival to last dance.	columbusmusicians@gmail.com	419-944-8965	https://www.columbusmusicians.com/	
LogieBear Sound & Lighting	Music		Columbus	Ohio	Central Ohio including Dublin, New Albany, Westerville and Downtown Columbus	Wedding DJ and MC mixing live with uplighting included, plus add-ons such as live saxophone, photo booth and an audio guestbook.	Logan@LogieBearSNL.com	(614) 917-3787	https://www.logiebearsnl.com/	https://www.instagram.com/logiebear.snl/
Platinum Music Productions	Music		Columbus	Ohio	Columbus and Central Ohio	Wedding DJ company running since 2005, offering ceremony audio, dance-floor lighting, custom monograms, cold-spark effects and a mirror photo booth.		614-407-6935	https://platinummusicdj.com/	https://www.instagram.com/platinummusicdj/
Cameron Mitchell Premier Events	Catering	7619 Huntington Park Dr.	Columbus	Ohio	Columbus and the surrounding region	Full-service caterer and event team that also plans and designs weddings and runs three Columbus event spaces, including The Stack.		(614) 848-4700	https://cameronmitchellpremierevents.com/	https://www.instagram.com/cmpe_columbus/
Bosc + Brie	Catering	7625 North High Street	Columbus	Ohio		North Columbus caterer with in-house planners, linens and cake cutting included, and a bring-your-own-alcohol option that helps trim bar costs.		614.985.2215	https://www.boscandbrie.com/	https://www.instagram.com/bosc_and_brie/
Fire & Knife	Catering		Columbus	Ohio	Homes, workplaces and venues across Ohio	Columbus caterer specialising in weddings with refined global menus served as a buffet or plated dinner, with a dedicated catering sales contact.	info@fireandknife.com	614.758.3659	https://www.fireandknife.com/	`,
  },
  {
    name: "Columbus: hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hertty's Bakeshop	Cake	100 E Campus View Blvd Suite #250	Columbus	Ohio	Columbus, with delivery required for wedding cakes	Family-run cake design studio in north Columbus making custom tiered wedding cakes by consultation appointment, with sugar flowers and fine detailing.	info@herttysbakeshop.com	614-373-7699	https://www.herttysbakeshop.com/	
Lavender and Honey Wedding Cakes	Cake		Columbus	Ohio	Columbus	Boutique Columbus bakery making scratch-baked custom wedding cakes and desserts, with tasting boxes couples can sample at home.	info@lavenderandhoneyweddingcakes.com	(614) 547-9851	https://www.lavenderandhoneyweddingcakes.com/	
Our CupCakery	Cake	54 S. High St.	Dublin	Ohio		Family-owned bakery in Historic Dublin offering classic tiered wedding cakes alongside cupcake displays, with a dedicated wedding request process.	Laura@ourcupcakery.com	614-659-1555	https://www.ourcupcakery.com/	
Sweet & Shiny	Cake		Columbus	Ohio		Columbus custom cake maker producing wedding cakes and decorative display cakes, with a wedding gallery and an online bakery shop.	elaine@sweetandshiny.com	614-680-9195	https://www.sweetandshiny.com/	https://www.instagram.com/sweetandshiny_columbus/
Columbus Wedding Videos	Videography		Columbus	Ohio	Central Ohio	Long-running Central Ohio video team filming since 2008, offering unobtrusive full-length documentary edits alongside shorter cinematic films.	info@columbusweddingvideos.com	614.725.0169	https://columbusweddingvideos.com/	https://www.instagram.com/columbusweddingvideos/
Hey Films	Videography		Columbus	Ohio	Columbus, Dublin, Westerville, New Albany and Central Ohio	Columbus wedding film studio with hourly packages from a short three-hour shoot to two-videographer full days, and two-week delivery.			https://heyfilms.com/	https://www.instagram.com/heyfilmsweddings/
Cinemachine Studios	Videography		Columbus	Ohio	Columbus area	Columbus video team making cinematic wedding films that lean on deliberate camera movement, angles and lighting to tell each couple's day.	info@cinemachinestudios.com		https://www.cinemachinestudios.com/	
The Lovely Artistry Collective	Hair & Makeup		Columbus	Ohio	Ohio and nationwide, travelling worldwide	Bridal hair and makeup team founded in 2011 for classic, timeless looks, with more than 3,000 brides styled and travel for destination weddings.			https://thelovelyartistrycollective.com/	https://www.instagram.com/thelovelyartistrycollective/
Lauren Wolff Hair Design	Hair & Makeup	1500 West 3rd Ave	Columbus	Ohio	Columbus area	Licensed cosmetologist creating long-lasting bridal hairstyles from a Grandview-area studio, alongside editorial styling and hair education.	hello@laurenwolffhairdesign.com		https://www.laurenwolffhairdesign.com/	https://www.instagram.com/lo.wolff_hairdesign/
Makeup with Anna K	Hair & Makeup		Columbus	Ohio	Columbus and destination weddings	Bridal makeup artist using luxury brands, with bridal party packages and a VIP option that pairs a two-hour facial with wedding makeup.	makeupwithannak@gmail.com		https://www.makeupwithannak.com/	https://www.instagram.com/makeup.with.annak/
Carly Jo Makeup	Hair & Makeup		Columbus	Ohio	Central Ohio	Bridal makeup artist focused on intimate weddings and elopements, aiming for a polished look that still feels like the bride herself.			https://www.carlyjomakeup.com/	https://www.instagram.com/carlyjomakeup/`,
  },
  {
    name: "Cincinnati: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Bird and Rose Photography	Photography	529 Main Street, Suite 204	Loveland	Ohio	Cincinnati and beyond, with travel	Husband-and-wife team with 25 years of combined experience telling wedding stories from their Loveland studio and travelling to couples elsewhere.	hello@birdandrosephoto.com		https://www.birdandrosephoto.com/	https://www.instagram.com/wearebirdandrose/
Très Belle Cakes	Cake	8921 Reading Road	Cincinnati	Ohio	Greater Cincinnati	Woman-owned bakery making award-winning custom wedding cakes and desserts since 2003, designed around each couple's tastes and story.	tresbellecakes@gmail.com	513-241-2253	https://www.tresbellecakes.com/	https://www.instagram.com/tresbellecakes/
The BonBonerie	Cake	2030 Madison Road	Cincinnati	Ohio	Cincinnati and surrounding areas	Bakery and café open since 1983, baking wedding cakes, cupcakes and dessert bars from European recipes, with tastings and cake stands.		513-321-3399	https://www.bonbonerie.com/	https://www.instagram.com/bonboneriecincy/
Light Parade Films	Videography		Cincinnati	Ohio	Cincinnati and destination weddings worldwide	Woman-owned cinematography studio making unobtrusive, story-driven wedding films with careful editing and sound design, aimed at lasting rather than trendy.	info@lightparadefilms.com	859-957-7587	https://www.lightparadefilms.com/	https://www.instagram.com/lightparade_films/
A Spoon Fulla Sugar	Cake	11916 Montgomery Rd	Cincinnati	Ohio	Cincinnati region	Montgomery Road bakery making custom wedding cakes plus cupcakes, cookies, dessert bars and its dotted Spoonie cakes, by appointment midweek.	info@aspoonfullasugar.com	513-683-0444	https://www.aspoonfullasugar.com/	https://www.instagram.com/aspoonfullasugar/
BRIDEface	Hair & Makeup		Cincinnati	Ohio		On-location bridal hair and makeup team founded in 2005, offering both airbrush and traditional makeup alongside updos, with studio appointments too.			https://www.brideface.com/	https://www.instagram.com/bridefaceotr/
Elegant Fare	Catering	2575 Commerce Blvd.	Cincinnati	Ohio	Greater Cincinnati and Northern Kentucky	Full-service caterer running since 1982, pairing each couple with a dedicated event consultant and offering menus at several price levels.	events@elegantfare.com	513-552-1340	https://www.elegantfare.com/	https://www.instagram.com/elegantfare/
Cincinnati Catering	Catering	1320 Ethan Avenue	Cincinnati	Ohio	Greater Cincinnati and Northern Kentucky	Long-running local caterer of around 90 years handling weddings and social events, with menus that stretch to grill-outs and Gold Star Chili.		513-541-2626	https://www.cincinnaticatering.com/	https://www.instagram.com/cincinnaticatering/
KMC Weddings and Events	Planning		Cincinnati	Ohio	Ohio and destination weddings	Cincinnati-based planning and design team of sixteen with over 18 years behind it, handling full planning, custom builds and destination weddings.			https://www.kmcweddings.com/	https://www.instagram.com/kmcweddings/
Sutle Productions	Music		Cincinnati	Ohio	Greater Cincinnati	DJ company with a roster of DJs matched to each couple's style, covering weddings and parties, with online date checking and booking.			https://www.sutleproductions.com/	https://www.instagram.com/shaunissutle/
Everlasting Sounds	Music	121 W Benson St	Reading	Ohio		Full-service DJ company bringing sound, lighting and event coordination to weddings, with an Ohio office in Reading and a second in Florida.	ohio@everlastingsounds.com	513-260-2780	https://www.everlastingsounds.com/	
Brittany Bays Photography	Photography		Cincinnati	Ohio	Cincinnati, the Midwest and destinations worldwide	Editorial, fine-art wedding photographer shooting on both film and digital, with over 15 years of experience and a calm, unobtrusive approach.			https://brittanybays.com/	https://www.instagram.com/brittanybaysphotography/
Images by Daniel Michael	Photography	110 W. Benson St.	Cincinnati	Ohio		Studio with 25+ years and 3,000+ weddings behind it, also photographing bar and bat mitzvahs, blending documentary, editorial and traditional styles.	imagesbydanielmichael@gmail.com	513-262-4830	https://www.danielmichael.com/	https://www.instagram.com/danielmichael_photo/
Cate Ronan	Photography		Cincinnati	Ohio	Ohio, the East Coast, New England, Nashville and Europe	Documentary-led wedding photographer working since 2016, focused on candid, emotive images and especially suited to intimate weddings of 100 or fewer.			https://cateronan.com/	https://www.instagram.com/thecateronan/
Eve Floral Co.	Florals	3706 Eastern Ave	Cincinnati	Ohio	Cincinnati and beyond	Woman-led flower shop and studio in Columbia-Tusculum creating seasonally inspired wedding florals, with consultations by appointment.			https://evefloralco.com/	https://www.instagram.com/evefloralco/
Floré	Florals		Cincinnati	Ohio	The Midwest and beyond	Appointment-only boutique studio for weddings and events, using colour, movement and form to build personal, intentional floral designs.	zoe.inflore@gmail.com	513-401-5677	https://florecincy.com/	https://www.instagram.com/flore.floralstudio/
Westcraft Floral	Florals		Cincinnati	Ohio	Greater Cincinnati, Northern Kentucky and the Midwest	Bespoke wedding and event floral studio led by designer Nola, focused on seasonal, locally sourced flowers and considered colour and composition.			https://westcraftfloral.com/weddings-and-events	https://www.instagram.com/westcraftfloral/
Still & Story Films	Videography		Cincinnati	Ohio	Cincinnati and worldwide	Husband-and-wife film team, formerly Dave Woodland Films, making cinematic, documentary-inspired wedding films after 400+ weddings around the world.			https://stillandstoryfilms.com/	https://www.instagram.com/stillandstoryfilms/
Maxwell Faust Productions	Videography		Cincinnati	Ohio	Cincinnati and nationwide	Cinematic wedding filmmaker with 100+ weddings across 60+ venues, aiming to capture how the day felt as much as what happened.	max@maxwellfaust.com	513-509-8885	https://maxwellfaust.com/	https://www.instagram.com/maxwellfaustproductions/
Athena's Eyes Productions	Videography		Cincinnati	Ohio	Cincinnati, Northern Kentucky, Dayton and eastern Indiana	Affordable documentary-style videographer filming unobtrusively with several cameras, delivering highlight reels in one to two weeks.	AthenasEyesProductions@gmail.com	513-280-7707	https://athenaseyes.com/	
Elegant Productions	Videography		Cincinnati	Ohio	Cincinnati, Columbus, Indianapolis, Lexington, Louisville and West Virginia	Film and photo company since 2007 with 250+ weddings, whose packages include a full edit of the ceremony and reception formalities as standard.	julie@elegantproductions.com	513-767-1510	https://elegantproductions.com/	
Blush & Bowtie	Planning		Cincinnati	Ohio	Cincinnati, Dayton and beyond	Planning and design team with published packages from event-only coordination to full planning, plus sister firms for vintage rentals and entertainment.			https://blushandbowtieweddings.com/	https://www.instagram.com/blushandbowtieweddings/
Every Last Detail	Planning		Cincinnati	Ohio	Cincinnati region and surrounding areas	Owner-led planning and design studio that grew out of a decor rental collection, handling coordination and vendor management alongside its rentals.	EveryLastDetailOhio@gmail.com		https://www.everylastdetailohio.com/	https://www.instagram.com/everylastdetailohio/
Ivory Couture	Planning		Cincinnati	Ohio	Cincinnati and destinations	Planner offering full and partial planning with design, or wedding management alone, built around strategy and logistics as much as styling.			https://ivorycouture.co/	https://www.instagram.com/ivorycouture.co/
Chenese Bean Makeup Artistry	Hair & Makeup	1821 Summit Rd., Suite 300B	Cincinnati	Ohio	Cincinnati, Northern Kentucky, Dayton and destination weddings	Bridal makeup artist with over 25 years' experience, skilled across all skin tones and in airbrush, with a hand-picked team of artists and hairstylists.			https://chenesebean.com/cincinnati-bridal-makeup-artist	https://www.instagram.com/chenesebean.mua/
AV Beauty Bar	Hair & Makeup	1408 Elm Street	Cincinnati	Ohio		Over-the-Rhine salon whose stylists offer bridal hair and makeup in the chair or as on-location glam for the wedding party.	info@avbeautybar.com		https://www.avbeautybar.com/	https://www.instagram.com/avbeautybar/
Jack Garrett Band	Music		Cincinnati	Ohio	Cincinnati, Columbus, Dayton, Louisville, Lexington, Indianapolis and beyond	Live wedding band with 25 years behind it, playing as a 7-piece or a 12-piece with a six-piece horn section, plus small groups for ceremonies.		513-508-7450	https://www.jackgarrettband.com/	
DelightMore	Catering	1761 Tennessee Ave	Cincinnati	Ohio	Greater Cincinnati	Caterer and event producer, formerly Funky's Catering, serving plated, buffet or station menus and running five of its own Cincinnati venues.		513-841-9999	https://delightmore.com/	https://www.instagram.com/delightmoreevents/
Midnight Rose Trio	Music		Cincinnati	Ohio	Cincinnati	Ceremony and cocktail-hour trio with 15+ years of events, playing contemporary, classical and Celtic music in custom arrangements.	midnightrosetrio@gmail.com	513-259-3110	https://www.midnightrosetrio.com/	https://www.instagram.com/midnightrosetrio/
Carly Messmer Floral Design	Florals		Cincinnati	Ohio	Cincinnati and Northern Kentucky	Bespoke wedding florist creating lush, garden-inspired designs that pair classic focal flowers with unexpected textures, starting from mood boards.	carly@carlymessmer.com	513-551-9783	https://www.carlymessmer.com/	https://www.instagram.com/carlymessmerfloral/
Village Pantry Catering	Catering	453 Wards Corner Road	Loveland	Ohio	Greater Cincinnati and the Tri-State	Family-owned caterer running since 1978, cooking for weddings and social events with gluten-free and vegan dishes on request.		513-965-0511	https://villagepantrycatering.com/	
Maribelle Cakery	Cake	3704 Cheviot Avenue	Cincinnati	Ohio		Appointment-only cake studio of over 40 years, whose owner trained with Ron Ben-Israel, using organic fillings, fresh berries and Belgian chocolate.		513-631-8333	https://maribellecakery.com/	https://www.instagram.com/maribellecakery/`,
  },
];

export default batches;
