import type { VendorBatch } from "@/lib/vendor-batches";

// Oregon vendor batches. Every row's State is "Oregon". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Portland: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
FritzPhoto	Photography		Portland	Oregon	Greater Portland, Beaverton, Lake Oswego and Tigard	Long-running Portland portrait and wedding studio of 25-plus years, pairing candid storytelling with polished, relaxed portraits of the couple.		(503) 421-8663	https://www.fritzphoto.com	https://www.instagram.com/fritzphoto.pdx/
Studio 623 Photography	Photography	38872 SE Proctor Blvd Suite 2E	Sandy	Oregon	Portland metro, Mt. Hood, Central Oregon and the Oregon Coast	Women-owned studio near Mt. Hood, photographing weddings and elopements since 2006, with wedding videography also available.	studio623photo@gmail.com	(503) 810-2958	https://www.studio623photography.com	https://www.instagram.com/studio623photography/
Define Motion	Photography		Portland	Oregon	Portland, the Columbia River Gorge, Mt. Hood, Bend, the Oregon Coast and destinations	Husband-and-wife team offering wedding photography and film together, mixing documentary moments with gentle posing and a five-week turnaround.	hello@definemotion.com		https://www.definemotion.com/wedding-photography-videography	https://www.instagram.com/definemotion/
Catalina Jean Photography	Photography		Portland	Oregon	Portland, with travel nationally and abroad	Documentary wedding photographer with editorial portraits and true-to-colour editing, focusing on unscripted moments throughout the day.	hello@catalinajean.com	(971) 533-9081	https://catalinajean.com/	https://www.instagram.com/catalinajean/
Bridal Bliss	Planning	402 N State St	Lake Oswego	Oregon	Portland, Seattle and Bend, plus destination weddings	Planning firm running weddings since 2002, offering full, partial and day-of planning plus design packages from offices across the Northwest.	nora@bridalbliss.com	(503) 804-4901	https://bridalbliss.com	https://www.instagram.com/bridalblissnw/
Mattera Events	Planning		Portland	Oregon	Portland, the Oregon Coast, the Pacific Northwest and Seattle	Planner with 25-plus years in events and CMP certification, offering full planning, consultation and coordination focused on guest comfort.	lisa@matteraevents.com	(503) 799-1795	https://www.matteraevents.com	https://www.instagram.com/lisamattera.events/
Rose & Fern Events	Planning		Portland	Oregon	Portland and the Pacific Northwest	Day-of coordinator for hands-on couples, bringing a project-management background and a people-first approach to running the wedding day.	kaila@roseandfernevents.com		https://www.roseandfernevents.com	https://www.instagram.com/roseandfernevents/
Atomic Wild Floral Design	Florals		Portland	Oregon	Pacific Northwest	Woman-owned studio designing foam-free wedding florals and installations with locally grown blooms, blending lush organic shapes with an edgier look.	atomicwildinfo@gmail.com		https://www.atomicwildfloral.com	https://www.instagram.com/atomic_wild/
Brier & Ivy	Florals		Portland	Oregon		Portland floral studio founded in 2016, designing bouquets, ceremony arches and tablescapes with a modern yet timeless, slightly wild style.	hello@brierandivy.com		https://www.brierandivy.com	https://www.instagram.com/brierandivy/
SELVA Design House	Florals		Portland	Oregon	Portland, Bend, Hood River, the Willamette Valley, Seattle and beyond	Sculptural, abundant wedding florals from a woman-owned studio that grows on its own organic farm, works foam-free and composts green waste.	hello@selvafloral.com		https://selvafloral.com/wedding-florist-oregon	https://www.instagram.com/selvadesignhouse/
Portmanteau Flower Company	Florals	3450 N Williams Ave Suite 15	Portland	Oregon	Portland, the Columbia River Gorge, Mount Hood and the Willamette Valley	North Williams flower shop run by two self-taught designers, creating sculptural, modern and garden-style wedding florals from seasonal stems.	jonathan@portmanteauflowerco.com	(503) 702-4838	https://www.portmanteauflowerco.com	https://www.instagram.com/portmanteauflowerco/
Paradox Productions	Music		Portland	Oregon	Portland, Bend and the Pacific Northwest, plus destination weddings	Veteran-owned DJ and MC company working from Portland and Bend, reading the room live and offering uplighting and photo booths as add-ons.	info@djpdx.com	(971) 247-9878	https://djpdx.com/	https://www.instagram.com/paradox_productions/
Rose City DJs	Music		Portland	Oregon	Portland metropolitan area	DJ and MC company serving Portland since 2000, with ceremony and rehearsal coordination and a planning process built around each couple.		(503) 422-1331	https://www.rosecitydjs.com/	
Stumptown DJs	Music		Portland	Oregon	Portland, Vancouver, the Columbia River Gorge and the Tri-Cities	Portland DJ roster matching couples with the right DJ-MC, covering ceremony music, entrances, toasts and a full dance floor.	info.stumptowndjs@gmail.com	(503) 877-3357	https://www.stumptowndjs.com	
Art of Catering	Catering	1019 NW Everett St	Portland	Oregon		Full-service Pearl District caterer with around 25 years behind it, designing custom wedding menus, specialty cocktails and event-day service.		(503) 231-8185	https://www.artofcatering.net/	https://www.instagram.com/artofcateringpdx/
Mundo Catering	Catering		Portland	Oregon	Portland area	Family-owned caterer with globally inspired, customisable menus built on Oregon ingredients, plus tent, table and linen rentals.		(971) 302-5041	https://mundocateringco.com/weddings/	https://www.instagram.com/mundocatering/
Premiere Catering	Catering	2432 SE Umatilla St	Portland	Oregon	Greater Portland, Gresham and Salem	Portland caterer operating since 1985, specialising in full-service receptions with on-site cooking and menus fitted to the budget.	premierecatering@comcast.net	(503) 235-0274	https://www.premierecatering.biz/	
Helen Bernhard Bakery	Cake	1717 NE Broadway	Portland	Oregon		Family bakery on NE Broadway dating to 1924, baking custom wedding cakes alongside its everyday pastries and with published pricing.	contact@helenbernhardbakery.com	(503) 287-1251	https://www.helenbernhardbakery.com	https://www.instagram.com/helenbernhardbakery/
Next Dimension Bakery	Cake	13283 NW Main St	Banks	Oregon	Oregon and Southwest Washington	Appointment-only cake studio known for no-fondant wedding cakes finished in a rolled chocolate blend, with posted tasting boxes for couples.	nextdimensionbakery2@gmail.com	(971) 238-9616	https://www.nextdimensionbakery.com/wedding-cake-bakery-portland-oregon	https://www.instagram.com/nextdimensionbakery/
Little Banana Bakery	Cake		Portland	Oregon	Portland and beyond	Bespoke cake studio making sculptural wedding cakes, handmade sugar flowers and dessert tables, with delivery and on-site set-up included.	littlebananabakery@gmail.com		https://www.littlebananabakery.com	https://www.instagram.com/littlebananabakery/
Goddess Glamour	Hair & Makeup		Portland	Oregon	Portland, Beaverton, Salem, Hood River and Southwest Washington	On-location bridal hair and makeup agency working since 2003, with a team of long-serving artists for brides and wedding parties.	info@goddess-glamour.com	(360) 607-0454	https://goddess-glamour.com/	https://www.instagram.com/goddessglamour_pnw/
Style Me PDX	Hair & Makeup	21935 NE Halsey St Ste 700	Fairview	Oregon	Portland area	Salon-based team led by Ashley Berglund, specialising in wedding hair and makeup for brides and bridal parties in the Portland area.	stylemepdx@gmail.com	(503) 893-8522	https://www.stylemepdx.com	https://www.instagram.com/style_me_pdx/
Marina Haynes Artistry + Esthetics	Hair & Makeup	10490 SW Eastridge St #110G	Portland	Oregon	Greater Portland	Licensed esthetician and stylist doing bridal hair and makeup in studio or on site, known for natural glam and a touch-up kit with every booking.	letschat@marinahaynes.com		https://www.marinahaynes.com/bridalhmua	https://www.instagram.com/marinahaynes_artistry/
Candy Glass Productions	Videography	2552 NW Vaughn St Unit E	Portland	Oregon	Portland and the Pacific Northwest	Northwest Portland film studio making cinematic, documentary-style wedding films shot discreetly, each cut to suit the couple.	info@candyglassproductions.com	(971) 258-6400	https://www.candyglassproductions.com/	https://www.instagram.com/candyglassproductions/
Mac Wedding Films	Videography		Portland	Oregon	Portland and surrounding areas	Documentary-style wedding films by Cody McDonald with no hourly cap on coverage and drone footage included where it is safe and legal.	hello@macweddingfilms.com	(503) 568-1199	https://www.macweddingfilms.com	https://www.instagram.com/macweddingfilms/
Portland Event Films	Videography		Portland	Oregon	Portland and the Pacific Northwest	Team of four cinematographers filming multi-camera wedding highlights and full documentaries, with live streaming and Indian wedding coverage.	info@portlandeventfilms.com		https://www.portlandeventfilms.com/	https://www.instagram.com/portlandeventfilms/`,
  },
  {
    name: "Bend: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Ponderosa Planning	Planning		Bend	Oregon	Central Oregon	Sustainable wedding planning and design for outdoorsy couples, running full weekends with local suppliers and an Aisle Planner portal for each couple.	emily@ponderosaplanning.com	(541) 728-3819	https://ponderosaplanning.com	https://www.instagram.com/ponderosaplanning/
Mae & June Flowers	Florals		Bend	Oregon		Sister-run floral studio founded in 2022, buying from Central Oregon farms and their own garden, with playful touches such as fresh-flower bow ties.	maeandjuneflowers@gmail.com	541-241-6997	https://www.maeandjuneflowers.com	https://www.instagram.com/mae.and.june.flowers/
Flip Flop Sounds	Music	20664 Carmen Loop Suite #1	Bend	Oregon	Bend, Redmond, Sunriver, Powell Butte and Central Oregon	Wedding DJ and event production company working across Central Oregon since 2009, with a separate lighting and AV division for larger events.	info@flipflopsounds.com	541-410-7291	https://flipflopsounds.com	
Bleu Bite Catering	Catering	63016 NE 18th St	Bend	Oregon	Central Oregon	Catering company feeding Central Oregon weddings since 2000, with an owner-led tasting, rustic custom menus and its own staff and rentals.	info@bleubitecatering.com	541-388-1104	https://bleubitecatering.com/weddings/	https://www.instagram.com/bleubitecatering/
Foxtail Bakeshop	Cake		Bend	Oregon		European-style wedding cakes and dessert bars made from scratch by a pastry chef known for gum paste flowers; now booking from spring 2027.	foxtailbakeshop@gmail.com		https://foxtailbakeshop.com/weddings	
Nick Raz Photography	Photography		Bend	Oregon	Central Oregon, the Pacific Northwest and destination weddings	Documentary wedding photographer mixing digital with 35mm film, favouring smaller and micro weddings and offering Super 8 highlight films.			https://www.nickrazphotography.com	https://www.instagram.com/nickrazphotography/
Edge Hair & Makeup	Hair & Makeup		Bend	Oregon	Bend and Central Oregon, with travel nationwide on request	Bridal hair and makeup studio led by Lori, styling couples and wedding parties in its Bend studio or on location at cabins and venues.	lori@edgehairmakeup.com	(541) 410-4384	https://edgehairmakeup.com	https://www.instagram.com/edgehairmakeup/
Bend Event Sound	Music		Bend	Oregon	Central Oregon	DJ and MC team with hundreds of Central Oregon weddings behind it, offering three set packages with travel and online music planning included.		(541) 316-5558	https://bendeventsound.com	https://www.instagram.com/bendeventsound/
Crumb Cakery	Cake		Bend	Oregon	Central Oregon and surrounding areas	Small-batch, from-scratch wedding cake and dessert studio working by appointment only since 2017, using real butter, vanilla and local produce.			https://crumbcentraloregon.com	https://www.instagram.com/crumb_cakery/
Benjamin Edwards Photography	Photography		Bend	Oregon	Central Oregon and destination weddings worldwide	Bend-based team photographing weddings since 2005, from resort celebrations at Brasada Ranch to sunrise elopements at Smith Rock, with video on offer too.	info@benjaminedwardsphotography.com	(541) 390-2276	https://benjaminedwardsphotography.com	https://www.instagram.com/benjaminedwards/
Noble Beginnings Wedding Company	Planning		Bend	Oregon	Central Oregon and the Pacific Northwest	Bend planner running custom full-planning packages and lighter wedding-management coordination for couples who plan themselves, active since 2022.	noblebeginningsweddingco@gmail.com		https://noblebeginningsweddingco.com	https://www.instagram.com/noblebeginningsweddingco/
Ida's Cupcake Cafe	Cake	1155 SW Division St	Bend	Oregon	Bend and Redmond	Cupcake bakery with shops in Bend and Redmond supplying wedding cupcakes and dessert bars, including dedicated gluten-free and vegan options.		(541) 678-5057	https://www.idascupcakecafe.com	https://www.instagram.com/idascupcakecafe/
Wild Poppy Florist	Florals		Sunriver	Oregon	Bend, Sunriver, Three Rivers and La Pine	Nature-inspired florist with a retail shop in Sunriver, designing bouquets and reception flowers for weddings across Bend and the southern Deschutes area.	events@wildpoppyflorist.com	(541) 593-2027	https://wildpoppyflorist.com	https://www.instagram.com/wildpoppyflorists/
Kayla Cindy Photo	Photography		Bend	Oregon	Bend and Portland	Documentary-style wedding photographer shooting on digital and film, focusing on candid in-between moments with light direction rather than staged posing.			https://kaylacindyphoto.com	
AlpenGlow Adventure Catering	Catering		Bend	Oregon	Central Oregon	Outdoor-focused caterer cooking chef-led, farm-to-table menus over fire and coals for backyard, lakeside and campsite weddings around Bend and Sisters.	alpenglowadventurecatering@gmail.com	425-269-0751	https://www.alpenglowadventurecatering.com	https://www.instagram.com/alpenglowadventurecatering/
The Indigo Bride	Planning		Bend	Oregon	Central Oregon and destination weddings	Bend team running full wedding planning and design since 2017, from Central Oregon resort weddings to destination celebrations further afield.	hello@theindigobride.com	(541) 362-4967	https://theindigobride.com	https://www.instagram.com/theindigobride/
Tyler Valzania Creative	Videography		Bend	Oregon		Bend videographer and former commercial ad producer filming weddings in an unobtrusive, documentary style, with photography available alongside.	tylervalzaniacreative@gmail.com		https://tylervalzaniacreative.com/weddings	https://www.instagram.com/tyvalz9/
High Desert Florals	Florals	249 NW 6th St Suite 2	Redmond	Oregon	Redmond, Bend and Central Oregon	Downtown Redmond flower shop with a dedicated weddings and events team designing modern bouquets and reception florals, delivering to Bend and beyond.		(541) 923-3977	https://highdesertflorals.com	https://www.instagram.com/highdesertflorals/
Kate Hana Artistry	Hair & Makeup		Bend	Oregon	Bend, Central Oregon and destination weddings	Bend makeup artist and licensed aesthetician with 16 years' experience, offering skin-focused, camera-ready bridal glam on location.			https://www.katehanaartistry.com	https://www.instagram.com/kate_hana_artistry/
Katy Nevinsky Photo & Films	Videography		Bend	Oregon	Bend, Oregon and Washington, with travel across the US	Bend wedding filmmaker making cinematic films on digital and Super 8, with photography alongside and full-length documentary edits on request.	hello@katynevinsky.com	541-241-6031	https://www.katynevinsky.com/videographer-bend-oregon/	https://www.instagram.com/katynevinsky/
Mike Hiatt Media	Videography		Bend	Oregon		Bend wedding videographer filming in a natural, documentary way without over-directing, with photography and elopement coverage also offered.	mike@mikehiattmedia.com	(541) 848-8569	https://mikehiattmedia.com	https://www.instagram.com/mikehiattmedia/
Craft Kitchen and Brewery	Catering	62988 Layton Ave #103	Bend	Oregon	Bend, Redmond, Sisters, Sunriver, Prineville and surrounding areas	Bend brewery kitchen catering weddings with orchard-wood smoked barbecue and scratch-made sides, from rehearsal dinners to next-day brunch.	info@craftoregon.com	541-668-1766	https://craftoregon.com/catering/	
Mom's Kitchen Catering Co.	Catering		Redmond	Oregon		Redmond caterer and gathering space run by chef Mariah, also offering florals, rentals and coordination, plus a private lakefront venue in Sisters.	momskitchen541@gmail.com	541-213-9696	https://www.momskitchencateringco.com	
NovusElle Salon	Hair & Makeup	133 SW Century Dr #104	Bend	Oregon		Bend westside salon offering bridal hair and makeup with trials, styling wedding parties in the salon or on location for a travel fee.	hello@novusellesalon.com	541-213-6493	https://www.novusellesalon.com/weddings-bridal	https://www.instagram.com/novusellesalonbend/
Precious Byrd	Music		Bend	Oregon	Bend, Central Oregon and the wider Pacific Northwest	Bend dance and rock band playing high-energy wedding receptions across the Northwest, fronted by Corey Parnell with saxophonist Andy Warr.	booking@preciousbyrd.com		https://www.preciousbyrd.com	https://www.instagram.com/preciousbyrdband/`,
  },
  {
    name: "Willamette Valley: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Photos By Orion	Photography	2416 13th St SE Suite A	Salem	Oregon	Oregon	Husband-and-wife Salem studio covering weddings, elopements and portraits, with video, drone and album options so one team can handle the whole day.	contact@photosbyorion.com	(503) 385-1435	https://www.photosbyorion.com/	
Photography by Lynn Marie	Photography	4172 Scottdale St.	Eugene	Oregon	Eugene, Bend, Sunriver, Oregon Coast and the Pacific Northwest	Full-time Eugene wedding and elopement photographer with a relaxed, personable approach, also shooting in Bend, Sunriver and along the coast.		541-913-7100	https://www.photosbylynnmarie.com/	https://www.instagram.com/photographybylynnmarie/
Heidi Rakas Photography	Photography	4967 Hyde Lane	Eugene	Oregon	Eugene, Springfield, Salem, Corvallis and across Oregon	Eugene photographer focused on intimate weddings, elopements and engagements, documenting genuine emotion in a natural, unobtrusive way.	hello@heidirakas.com	541-844-8215	https://heidirakas.com/	https://www.instagram.com/heidirakasphotography/
Katie Carodine Photography	Photography		Salem	Oregon	Salem, Keizer, Jefferson, Woodburn, Eugene and surrounding areas	Salem photographer offering creative themed weddings and elopements, from steampunk and pirate to fairy and Halloween looks.		971.315.3002	https://www.katiecarodinephotography.com/	https://www.instagram.com/katiecarodinephotography/
Joshua Rainey Photography	Photography		Eugene	Oregon	Eugene, Oregon and surrounding areas	Eugene photographer blending fine art and photojournalism for weddings, delivering 700 to 1,100 images with printing rights included.		541.505.2781	https://joshuaraineyphotography.com/	https://www.instagram.com/joshuaraineyphotography/
Salem Smith Photography	Photography		Salem	Oregon	Salem, Keizer, Silverton, Dallas, Albany, Corvallis, Portland and the Willamette Valley	Salem photographer shooting documentary-style weddings and couple portraits that favour relaxed, authentic moments over posed shots.			https://salemsmithphotography.com/	https://www.instagram.com/salemsmithphoto/
Events by Erin	Planning		Eugene	Oregon	Eugene, Springfield, all of Oregon and destination weddings	Eugene planner offering full-service planning and day-of coordination with a calm, organised approach for relaxed, down-to-earth couples.	erinrice@eventsbyerin.com	541-285-1154	https://www.eventsbyerinoregon.com/	https://www.instagram.com/eventsbyerinoregon/
AMOR Events	Planning		Albany	Oregon	Willamette Valley, greater Portland, Central and Southern Oregon, SW Washington	Albany planner with over 15 years of wedding and event experience, offering customised planning and coordination across the Willamette Valley.		541-840-5345	https://www.willamettevalleyeventplanner.com/	https://www.instagram.com/amor.events.or/
Finesse Weddings & Events	Planning		Salem	Oregon		Salem wedding and event planning business offering customised planning and coordination built around each couple's own vision.	finesseweddingsandevents@gmail.com		https://www.finesseweddingsandevents.biz/	https://www.instagram.com/finessseevents/
Rachel Rose Event Planning	Planning		Salem	Oregon	Oregon	Salem planner handling vendor selection, ceremony logistics and day-of management to take the stress out of wedding planning.	rreventsoregon@gmail.com	503-884-4193	https://www.rreventsoregon.com/	https://www.instagram.com/rreventsoregon/
Branch & Bramble	Florals		Eugene	Oregon	Eugene	Eugene florist creating bespoke wedding and event florals from local, seasonal blooms for ceremonies and celebrations.	kara@branchandbramblefloral.com	(925)922-0255	https://branchandbramblefloral.com/	https://www.instagram.com/branchandbramblefloralco/
Garden Girl Flowers	Florals		Eugene	Oregon	Eugene and Springfield	Home-based Eugene studio designing luxurious wedding and event florals from premium seasonal blooms with a sustainable focus.	gardengirlflowers@icloud.com	541-870-0960	https://www.gardengirlflowers.com/	https://www.instagram.com/gardengirlflowerseugene/
wild child flower co.	Florals		Eugene	Oregon		Woman-owned Eugene floral studio growing flowers on site and designing custom wedding pieces that blend fresh and dried botanicals.			https://wildchildflowerco.com/	https://www.instagram.com/wildchildflowerco/
Wrong Number Floral	Florals		Eugene	Oregon	Oregon and Washington	Eugene florist making sculptural, colourful wedding designs, sourcing most of each wedding's flowers from local growers in peak season.			https://wrongnumberfloral.com/	https://www.instagram.com/wrongnumberfloral/
Flowers & Thyme	Florals		Springfield	Oregon	Eugene, Springfield and beyond	Springfield florist offering full-service wedding and celebration design, led by owner DelJean Benton's personal, heartfelt approach.	deljean@flowersandthyme.net	(541) 579-1160	https://flowersandthyme.net/	https://www.instagram.com/flowersandthyme/
Apogee Event Productions LLC	Music	220 S 8th St	Aumsville	Oregon	Salem, Keizer and all of Oregon	Aumsville team bundling wedding DJs, photo booths, photography, video and planning under one contract and invoice.	team@weareapogee.com	971-374-7047	https://weareapogee.com/	https://www.instagram.com/apogeeisawesome/
Caught In The Act Entertainment	Music	860 28th St	Springfield	Oregon	Eugene, Springfield, Salem, Florence, Newport, Lincoln City, Roseburg and nearby	Springfield DJ and MC service with sound, lighting and microphones included in its packages and a pre-event consultation for each couple.	jared@citaent.com	(541) 915-9957	https://www.citaent.com/	https://www.instagram.com/caughtintheactent/
TrueLove Sound	Music		Eugene	Oregon	Eugene, Portland, Salem, Corvallis, Albany, Roseburg, Medford, Florence, Newport, Lincoln City	Eugene wedding DJ with over 20 years of experience, offering personalised entertainment for ceremonies, receptions and anniversaries.	Truelovesounddj@gmail.com	541-515-5115	https://www.truelovesound.com/	
Generations Wedding and Event Bands LLC	Music		Eugene	Oregon	Pacific Northwest	Eugene collective of musicians offering solo piano, jazz combos, string and brass ensembles or a full cover band for weddings.			https://www.hiregenerations.com/	https://www.instagram.com/gen_bands/
Willabys Catering	Catering	765 Liberty St SE	Salem	Oregon		Scratch-kitchen caterer working since 1993, building each wedding menu from regional produce and suppliers rather than set packages.	events@willabyscatering.com	503-371-7815	https://www.willabyscatering.com	
Sheild Catering	Catering	225 Madison Street	Eugene	Oregon	Eugene/Springfield	Bistro and catering kitchen offering tasting sessions and menus built on local farm ingredients, for weddings from 50 to over 300 guests.		541-968-2403	https://sheildcatering.com	https://www.instagram.com/sheildcatering/
Ginkgo Catering	Catering	1203 Willamette St #160	Eugene	Oregon	Eugene, Springfield and Lane County	Farm-to-table caterer using seasonal Pacific Northwest produce and local suppliers, with menus adapted for vegan, vegetarian and gluten-free guests.	info@ginkgocatering.com	(541) 517-6448	https://ginkgocatering.com	https://www.instagram.com/ginkgogardencatering/
Mac's Custom Catering	Catering	1626 Willamette St	Eugene	Oregon	Eugene and surrounding areas	Eugene caterer with 35+ years behind it, offering fully custom menus plus ready-made Italian, Hawaiian, Northwest and Southwest wedding themes.		541-344-8600	https://macseugenecatering.com	
Chef Becky	Catering		Eugene	Oregon	Eugene and surrounding areas	Eugene chef catering weddings since 2001 with seasonal, locally sourced menus, passed appetisers, plated dinners and optional wine pairing.	becky@chefbecky.com	541-510-0326	https://chefbecky.com	https://www.instagram.com/chefbeckym/
Kico's Barbecue	Catering		Eugene	Oregon	Eugene and surrounding communities	Oak-pit Santa Maria style barbecue caterer cooking entirely on site at the venue, with buffet service or a food truck option for weddings.		(541) 668-1155	https://kicosbbq.com	https://www.instagram.com/kicosbbq/
Bell Sol Beauty & Esthetics	Hair & Makeup	1845 Fairgrounds Rd. NE, Suite 1A	Salem	Oregon	Salem	Licensed esthetician and makeup artist offering bridal makeup alongside skincare, lash and brow work from a studio inside The Lotus Lounge.		503-510-7399	https://www.bellsolbeauty.com	https://www.instagram.com/bellsolbeauty/
Adore Salon	Hair & Makeup	300 SW Madison Ave	Corvallis	Oregon	Corvallis and surrounding regions, with travel	Corvallis salon offering bridal hair and makeup packages with trial runs, in the salon or on location, plus travel for wedding parties.	hello@adoresaloncorvallis.com	(541) 250-2306	https://adoresaloncorvallis.com	https://www.instagram.com/adoresaloncorvallis/
La Muse Beauty Salon	Hair & Makeup	308 E First St., Suite B	Newberg	Oregon	Newberg	Newberg stylist Desiree Neel offers bridal hair and makeup alongside everyday cuts and colour, and won a WeddingWire Couples' Choice award in 2022.		971-373-1407	https://lamusebeautysalon.com	https://www.instagram.com/lamusebeautysalon/
McKenzie Mingo Creations	Hair & Makeup	440 West 6th Avenue	Eugene	Oregon	Eugene, with in-home bridal party service	Eugene hair and makeup studio with bridal party packages in the chair or on location, backed by colour and blow-dry training.	mckenzie@mingocreations.com	(541) 232-5598	https://mingocreations.com	
Devour Cakes and More	Cake		Eugene	Oregon	Eugene and surrounding areas	Eugene bakery making scratch-baked custom wedding and celebration cakes with locally sourced ingredients, each designed to the couple's brief.	andrea@devourcakesandmore.com		https://devourcakesandmore.com	https://www.instagram.com/devourcakesandmore/
Soft Peaks Cakery	Cake		Eugene	Oregon	Eugene, Springfield and greater Lane County	Custom cake studio working by request only, capping weekly orders so the owner can design each wedding cake personally with the couple.	hello@softpeakscakery.com		https://www.softpeakscakery.com	https://www.instagram.com/softpeakscakery/
Custom Cakes NW	Cake		Newberg	Oregon	Willamette Valley wine country, with delivery across the Northwest	Newberg baker with 30+ years of sugar-art experience making scratch wedding cakes to order, with tastings and pickups by appointment.		(503) 538-0530	https://www.customcakesnw.com	
Blair's Custom Cakes LLC	Cake		McMinnville	Oregon		McMinnville cake designer working by appointment, using local and homegrown ingredients where possible and also running decorating classes.	cakegalbakin@gmail.com	503-583-2227	https://www.blairscustomcakes.com	https://www.instagram.com/blairscustomcakes/
Kayke Custom Cakes	Cake		Corvallis	Oregon	Corvallis	Corvallis artisan baker with an art background making one-of-a-kind wedding and celebration cakes, designed from a conversation with the couple.	orders@customkayke.com	(307) 461-1590	https://customkayke.com	
Transitions In Time Photography	Videography	804A NW Buchanan, Suite 40	Corvallis	Oregon	Benton and Linn counties, Albany, Salem, Eugene, Oregon Coast	Corvallis photography studio that also films weddings, pairing video with in-house archival printing and album design.		541-360-7400	https://transitionsintime.com	
Carter Cunningham Films	Videography		Eugene	Oregon	Oregon and the Pacific Northwest	Eugene filmmaker making story-led wedding and elopement films tailored to each couple rather than following trends.			https://cartercunninghamfilms.com	https://www.instagram.com/cartercfilms/
Ashley Renee Studios	Videography		Salem	Oregon	Salem, available to travel	Husband-and-wife Salem team filming documentary-style weddings since 2018, aiming for films that feel like a favourite movie.	hello@ashleyreneestudios.com		https://ashleyreneestudios.com	https://www.instagram.com/ashleyreneestudios/`,
  },
];

export default batches;
