import type { VendorBatch } from "@/lib/vendor-batches";

// Pennsylvania vendor batches. Every row's State is "Pennsylvania". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Philadelphia: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hoffer Photography	Photography		Downingtown	Pennsylvania		Husband-and-wife Chester County team photographing Philadelphia weddings in an authentic, elevated style mixing candids and portraits.	info@hofferphotography.com	484-693-0055	https://hofferphotography.com/	https://www.instagram.com/hofferphotography/
Asya Photography	Photography		Philadelphia	Pennsylvania		Philadelphia photographer with a romantic, documentary approach, shooting weddings at places like the Barnes Foundation.	asya@asyaphotography.com		https://asyaphotography.com/	https://www.instagram.com/asya_photography_philly/
Love Me Do Photography	Photography	2220 E Susquehanna Ave	Philadelphia	Pennsylvania		Fishtown-based team of photographers and videographers covering weddings, with several lead shooters to choose from.	carina@lovemedophotography.com		https://www.lovemedophotography.com/	https://www.instagram.com/lovemedophoto/
Porch & Pearls	Planning		Philadelphia	Pennsylvania	Philadelphia and destination weddings	Full planning firm led by an attorney-turned-planner, focused on vendor management, timelines and calm execution on the day.		267-258-4292	https://www.porchandpearls.com/	https://www.instagram.com/porchandpearls/
Olive Street Events	Planning		Philadelphia	Pennsylvania		Wedding planning and design company whose team brings experience from both planning weddings and running venues.	hello@olivestreetevents.com		https://www.olivestreetevents.com/	https://www.instagram.com/olivestreetevents/
Elegant Events Planning + Design	Planning		Philadelphia	Pennsylvania	Philadelphia and its suburbs, Delaware, New Jersey, Maryland and destinations	Long-running planning and design firm specialising in Indian, multicultural, interfaith and fusion weddings, with offices in Philadelphia and Delaware.		888-549-7526	https://elegant-events.net/	https://www.instagram.com/eleganteventsphilly/
Caroline Florals	Florals		Philadelphia	Pennsylvania	Philadelphia and beyond	Whimsical, flower-forward wedding florist known for playful colour palettes, natural movement and seasonal blooms.	hello@carolineflorals.com		https://carolineflorals.com/	https://www.instagram.com/caroline.florals/
Myrtle & Magnolia	Florals	2222 Frankford Ave	Philadelphia	Pennsylvania		Woman-owned Fishtown flower shop and studio designing artistic, bespoke florals for weddings and events.	hello@myrtleandmagnolia.com	215-914-3805	https://www.myrtleandmagnolia.com/	https://www.instagram.com/myrtlemagnolia/
Gardena Floral	Florals		Fort Washington	Pennsylvania	Philadelphia, Bucks County and beyond	Boutique florist and micro flower farm growing many of its own blooms for romantic, garden-inspired wedding work.	hello@gardenafloral.com		https://gardenafloral.com/	https://www.instagram.com/floralsbyadena/
BVTLive!	Music	114 Commons Court	Chadds Ford	Pennsylvania	Philadelphia region	Agency behind a roster of exclusive wedding and dance bands, plus DJs and specialty acts for weddings around Philadelphia.	info@bvtlive.com	610-358-9010	https://www.bvtlive.com/	https://www.instagram.com/bvtlive/
CTO Music Artists	Music		Bala Cynwyd	Pennsylvania	Philadelphia, the Main Line, Bucks, Montgomery, Delaware and Chester counties	Entertainment agency booking live party bands, DJs and ceremony ensembles for Philadelphia-area weddings since 1997.	info@cto.art	215-220-9928	https://www.ctomusicartists.com/	https://www.instagram.com/ctomusicartists/
Z4 Events	Music		Philadelphia	Pennsylvania	Philadelphia, New Jersey and Delaware	DJ and lighting company specialising in Indian and cultural weddings, with Bollywood sets, uplighting and LED video walls.	z4eventsusa@gmail.com	267-444-7148	https://z4events.com/	https://www.instagram.com/z4events/
Peachtree & Co.	Catering	175 King of Prussia Road	Radnor	Pennsylvania	Main Line, Philadelphia and beyond	Family-run caterer since 1985 serving off-premise weddings and its own venues, including Pomme, Parque, Portico and The Willows.	sales@peachtreeandco.com	484-580-8260	https://www.peachtreeweddings.com/	https://www.instagram.com/peachtreeweds/
Eatible Delights Catering	Catering	1540 Wadsworth Avenue	Philadelphia	Pennsylvania		Chef David Simms' Philadelphia caterer, established in 1996, cooking classic familiar favourites with a modern flair.		215-236-3900	https://eatibledelightscatering.com/	
LemonCo Catering	Catering		Philadelphia	Pennsylvania	Philadelphia, the Main Line, Bucks and Montgomery counties	Boutique full-service caterer offering custom menus, BYOB bar service with signature cocktails, rentals and decor.		609-464-1313	https://www.lemoncocatering.com/	https://www.instagram.com/lemoncocatering/
Aleksandra Ambrozy Makeup and Hair	Hair & Makeup	1118 Pine Street	Philadelphia	Pennsylvania	Philadelphia, the Main Line, South Jersey, NYC and Delaware	Center City team bringing refined on-location bridal hair and makeup that enhances natural features and photographs well.	info@aleksandraambrozy.com		https://aleksandraambrozy.com/	https://www.instagram.com/aleksandraambrozy/
The Philly Hair & Makeup Co.	Hair & Makeup	2619 Aramingo Ave	Philadelphia	Pennsylvania	Philadelphia, Bucks and Montgomery counties, the Main Line and South Jersey	On-location bridal hair and makeup team with a Fishtown studio, bringing a full salon set-up to wedding mornings.	phillyhairgirl@gmail.com	267-687-7936	https://www.phillyhairandmakeup.com/	https://www.instagram.com/phillyhair/
Beauty & Bridal Philly	Hair & Makeup	28 S 8th Street	Quakertown	Pennsylvania	Philadelphia area, New Jersey, NYC and Delaware	Bridal hair and makeup studio led by an artist with over 18 years' experience, travelling to weddings across the region.	beautyandbridalphilly@gmail.com	607-368-7808	https://beautyandbridalphilly.com/	https://www.instagram.com/beautyandbridalphilly/
Isgro Pastries	Cake	1009 Christian Street	Philadelphia	Pennsylvania		Italian Market bakery, family owned since 1904, making traditional Italian pastries alongside custom wedding cakes.	isgropastries1904@gmail.com	215-923-3092	https://isgropastries.com/	https://www.instagram.com/isgropastries/
The Frosted Fox Cake Shop	Cake	6511 Germantown Ave	Philadelphia	Pennsylvania		Mt Airy bakery baking from scratch daily, making custom wedding cakes and treats for over a decade.	frostedfoxcakeshop@gmail.com	267-900-5453	https://www.frostedfoxcakeshop.com/	https://www.instagram.com/frostedfoxcakeshop/
The Novel Baker	Cake	4945 W Swamp Rd	Doylestown	Pennsylvania		Bucks County boutique cake studio known for airy buttercream wedding cakes, with tasting experiences available.		215-280-5926	https://www.thenovelbaker.com/	https://www.instagram.com/thenovelbaker/
Solidity Films	Videography		Philadelphia	Pennsylvania	Philadelphia region and beyond	Philadelphia videographers making story-led wedding films that go beyond a chronological recap of the day.	info@solidityfilms.com		https://solidityfilms.com/	https://www.instagram.com/solidityfilms/
New Pace Weddings	Videography		Philadelphia	Pennsylvania	Philadelphia and beyond	Studio working since 2007 that offers wedding videography and photography together, plus social media reels.	info@newpaceweddings.com	484-453-8419	https://newpaceweddings.com/	https://www.instagram.com/newpaceweddings/
Noise Soul Cinema	Videography		Philadelphia	Pennsylvania	Philadelphia and the Tri-State	Philadelphia video company led by Joshua Mallory, filming weddings alongside nonprofit and brand work, with a three-payment plan.		267-225-8285	https://noisesoulcinema.com/	https://www.instagram.com/noisesoulcinema/`,
  },
  {
    name: "Pittsburgh: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Novasoul Photography	Photography		Pittsburgh	Pennsylvania	Pittsburgh, Western Pennsylvania and surrounding areas	Documentary-style wedding photographer with a relaxed, journalistic approach, often shooting at Pittsburgh restaurants and hotels.			https://www.novasoulphotography.com/	https://www.instagram.com/novasoulphotography/
Sarah McCloskey Photography	Photography		Pittsburgh	Pennsylvania		Pittsburgh-based photographer and small team focused on natural, detail-rich wedding coverage, travelling for destination weddings.			https://sarahmccloskey.com/	https://www.instagram.com/sarahmccloskeyphoto/
Ashley Sara Photography	Photography		Pittsburgh	Pennsylvania	Pennsylvania, the East Coast and destinations worldwide	Editorial, artful wedding photography from Pittsburgh, with venue guides covering local mansions and county parks.	hello@ashleysaraphotography.com		https://ashleysaraphotography.com/	https://www.instagram.com/ashleysaraphoto/
Stark White Weddings	Planning		Pittsburgh	Pennsylvania	Pittsburgh and worldwide	Pittsburgh team of wedding managers and planners founded in 2023, offering full planning, partial planning and day-of management.	hello@starkwhiteweddings.com		https://starkwhiteweddings.com/	https://www.instagram.com/starkwhiteweddings/
Tiffany and Design	Planning		Pittsburgh	Pennsylvania		Pittsburgh planner whose background in graphic and interior design shapes both coordination and the look of the day.	info@tiffanyanddesign.com		https://tiffanyanddesign.com/	https://www.instagram.com/tiffanyanddesign/
Wanderlust Weddings and Events	Planning		Pittsburgh	Pennsylvania	Pittsburgh and destinations worldwide	Pittsburgh-based planning firm working since 2015 on local and destination weddings, with an inclusive approach to every couple.	services@wanderlustweddingsandevents.com		https://www.wanderlustweddingsandevents.com/	https://www.instagram.com/wanderlustweddingsandevents/
Hearts and Flowers Floral Design	Florals		Pittsburgh	Pennsylvania		Pittsburgh wedding and event florist designing custom arrangements through an inquiry and design-process approach.	brigette@heartsandflowersfloral.com		https://www.heartsandflowersfloral.com/	https://www.instagram.com/heartsandflowersfloraldesign/
Flowers by Gerard	Florals	20555 Rte 19	Cranberry Township	Pennsylvania		Cranberry Township flower shop on Route 19 offering wedding flowers alongside same-day designed and hand-delivered arrangements.	wecare@flowersbygerard.com	(724) 779-3900	https://www.flowersbygerard.com/wedding	https://www.instagram.com/flowersbygerard/
Sugar Flowers and Leaves	Florals		Sewickley	Pennsylvania	Pittsburgh-area events	Appointment-only Sewickley florist offering custom wedding work and lower-cost pre-designed colour collections, delivery only.	designer@sugarflowersandleaves.com	(412) 915-3069	https://www.sugarflowersandleaves.com/weddings	https://www.instagram.com/sugarflowersandleaves/
Bethel Bakery	Cake	5200 Brightwood Road	Bethel Park	Pennsylvania		Family-owned South Hills bakery known for its French buttercream, offering wedding cake consultations, tastings and custom designs.		412-835-6658	https://www.bethelbakery.com/	https://www.instagram.com/bethelbakery/
Prantl's Bakery	Cake	612 Grove Street	Greensburg	Pennsylvania		Westmoreland County bakery famous for its burnt almond torte, with shops around Pittsburgh and a wedding cake service.		724-837-3706	https://www.prantlsbakery.com/weddings	https://www.instagram.com/prantlsbakery/
Remo's Catering	Catering		Pittsburgh	Pennsylvania	Pittsburgh-area venues	Family wedding caterer with five generations of experience, offering custom menus, bar service, mobile BBQ and free tastings.		412-822-7844	https://www.remoscatering.com/	https://www.instagram.com/remoscatering/
Post Script Films	Videography	618 Beaver Street	Sewickley	Pennsylvania	Pittsburgh and beyond	Sewickley wedding film studio with a full-time team and 16 years in business, making cinematic films with customisable packages.	weddings@postscriptfilms.com		https://www.postscriptfilms.com/	https://www.instagram.com/postscript_weddingfilms/
Fireside Events	Music		Allison Park	Pennsylvania	Pittsburgh and Western Pennsylvania	Family-run DJ and AV production company working since 2015, combining DJ and MC work with lighting, sound and day-of coordination.			https://fireside-events.com/	https://www.instagram.com/fireside.events/
Loyalty Weddings & Events	Music		Pittsburgh	Pennsylvania		Pittsburgh entertainment company founded in 2015 by Loyal and Nicole Martinez, offering wedding DJs alongside live music.	info@loyaltyevents.com	(412) 607-3693	https://www.loyaltyevents.com/	https://www.instagram.com/loyaltyentertains/
Aaron Woods Productions	Videography		Pittsburgh	Pennsylvania		Pittsburgh videographer shooting in 4K with drone coverage, delivering cinematic highlight films and full-length features.		412 260-5242	https://aaronwoodsproductions.com/	https://www.instagram.com/aaronwoods.productions/
Glam To Go	Hair & Makeup		Pittsburgh	Pennsylvania	Pittsburgh and worldwide travel	Mobile bridal hair and makeup team based in Pittsburgh, coming to the wedding-morning location and now booking into 2027.	info@glamtogo.com		https://glamtogo.com/	https://www.instagram.com/_glamtogo_/
The Fluted Mushroom	Catering	109 S. 12th St.	Pittsburgh	Pennsylvania	Pittsburgh area	South Side caterer working for nearly 50 years, building custom wedding menus with vegan and vegetarian options and a venue guide.	catering@flutedmushroom.com	412.381.1899	https://flutedmushroom.com/	https://www.instagram.com/theflutedmushroom/
Oakmont Bakery	Cake	One Sweet Street	Oakmont	Pennsylvania		Large family-founded retail bakery in Oakmont, open since 1988, with cake designers for wedding and groom's cakes plus cookies and minis.		412-826-1606	https://oakmontbakery.com/weddings/	https://www.instagram.com/oakmontbakery/
Hot Metal Strings	Music		Pittsburgh	Pennsylvania		All-female, classically trained Pittsburgh string ensemble playing ceremonies and receptions as a solo, duet, trio or quartet.			https://hotmetalstrings.com/	https://www.instagram.com/hotmetalstrings/
Carnation Films	Videography		Pittsburgh	Pennsylvania	Pennsylvania, Ohio and destinations	Husband-and-wife film team in Pittsburgh shooting weddings on both digital and Super 8, with raw footage included alongside the edit.			https://carnation-films.com/	https://www.instagram.com/carnationfilms/
Simply Captivating Salon	Hair & Makeup		Pittsburgh	Pennsylvania	Pennsylvania, Ohio and West Virginia	On-location bridal hair team that sets up a mini salon at the getting-ready venue, specialising in updos and bridal party styling.		412-448-8989	https://simplycaptivatingsalon.com/	https://www.instagram.com/simply.captivating.pgh_hair/
All in Good Taste Productions	Catering	1520 Monterey St.	Pittsburgh	Pennsylvania	Pittsburgh and the surrounding areas	North Side caterer and event producer with over 35 years in business, handling weddings from engagement party through farewell brunch.	info@allingoodtasteproductions.com	412-321-6869	https://allingoodtasteproductions.com/	
JL Makeup Studio and Beauty Boutique	Hair & Makeup		Pittsburgh	Pennsylvania	Pittsburgh, free within 30 miles	Pittsburgh bridal makeup and hair studio offering in-studio or on-site wedding teams, with published packages running to 2028.	jlstudiopgh@gmail.com		https://www.jlstudiopgh.com/bridal-services	https://www.instagram.com/jlstudio_hairandmakeup/`,
  },
  {
    name: "Lancaster: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kirsten Hartzell Photography	Photography		Lancaster	Pennsylvania	Lancaster, Philadelphia, Maryland, New York, Washington DC and destinations	Docu-editorial wedding photographer pairing unscripted documentary coverage with polished, intentional portraits for couples who want to stay present.	kirstenhartzellphotography@gmail.com		https://www.kirstenhartzellphotography.com/	https://www.instagram.com/kirstenhartzellphotography/
Alisa Marie Co.	Planning		Lancaster	Pennsylvania		Lancaster planner offering day-of coordination, partial and full planning, quietly handling problems on the day so couples can simply enjoy it.			https://www.alisamarie.co/	https://www.instagram.com/alisamarie.co/
Hannah Elizabeth Events	Planning		Lancaster	Pennsylvania	Lancaster, Philadelphia and worldwide	Full-service design and management firm led by Hannah Umberger, working on detailed, design-led weddings with a focus on Philadelphia.			https://hannahelizabethevents.com/	https://www.instagram.com/hannahelizabethevents/
Splints & Daisies Floral Design	Florals		Lancaster	Pennsylvania	Lancaster, Central Pennsylvania, Philadelphia, the Mid-Atlantic and the Finger Lakes	Vibrant, whimsical wedding florals built from locally sourced and sustainably grown blooms, with an emphasis on low-waste design.	tara@splintsanddaisies.com	717-379-6087	https://www.splintsanddaisies.com/	https://www.instagram.com/splintsanddaisies/
Custom Florals	Florals	2610 River Road	Conestoga	Pennsylvania	Lancaster and South Central PA	Countryside studio with over 30 years of wedding work, designing bouquets, arches and garlands in styles from vintage to contemporary on most budgets.	mycustomflorals@gmail.com	717-468-5465	https://www.customflorals.com/	https://www.instagram.com/customflorals/
Downtown Sound	Music		Lancaster	Pennsylvania	Central Pennsylvania	Large live party band covering 60s soul to current hits, known for mash-ups and singers who move out onto the dance floor.	lucy@robin-banksentertainment.com	717-609-1154	https://downtown-sound.com/	https://www.instagram.com/d_townsoundband/
DJ Mast Productions	Music		Lancaster	Pennsylvania	Lancaster, Harrisburg, Hershey, York, Philadelphia, Baltimore and destinations	Wedding DJ and MC company with over a decade of event work, adding uplighting, photo booths and backup equipment with no setup fees.	contact@djmast.com	717-951-5221	https://www.djmast.com/	https://www.instagram.com/djmastproductions/
C&J Catering and Events	Catering	903 Spring Garden Drive	Middletown	Pennsylvania	Hershey, Harrisburg, Lancaster, York, Lebanon and Carlisle	Full-service caterer with buffets, plated dinners and carving stations, plus its own bakery for wedding cakes and an in-house floral team.		717-576-1610	https://www.candjcatering.com/	https://www.instagram.com/c_and_j_catering/
Envy Studio	Hair & Makeup	24 W King St	Lancaster	Pennsylvania	Lancaster and on location	Downtown Lancaster salon with a private bridal suite for 16, airbrush makeup and on-site styling for brides, bridesmaids and flower girls.	bridesbyenvy@gmail.com	717-435-9343	https://envystudiolancasterpa.com/services/bridal/	https://www.instagram.com/_envy_studio_/
Abloom Bridal Artistry	Hair & Makeup		Lancaster	Pennsylvania	Lancaster, York and Harrisburg	On-site bridal hair and makeup by Katie Childers, specialising in soft glam, boho braids and romantic updos that hold up all day.	abloombridalartistry@gmail.com		https://www.abloombridalartistry.com/	https://www.instagram.com/abloombridalartistry/
Olive Bridal Hair	Hair & Makeup		Lancaster	Pennsylvania	Lancaster area and beyond	Hair-only bridal team led by Crystal Haynick, offering tiered on-site packages and preview trials, focused only on the wedding party that day.	olivebrideshair@gmail.com		https://www.olivebridalhair.com/	https://www.instagram.com/olivebridalhair/
Bird-in-Hand Bakery & Cafe	Cake	2715 Old Philadelphia Pike	Bird-in-Hand	Pennsylvania	Within 20 miles of the bakery	Family-run Lancaster County bakery making scratch wedding cakes in classic flavours, with fondant flowers and local delivery and setup.		717-768-1501	https://bird-in-hand.com/bakery-cafe/specialty-cakes/	
Wayfinder Films	Videography		Lancaster	Pennsylvania	PA, NJ, MD, NY, NC and nationwide destinations	Wedding film team focused on raw, documentary storytelling that captures how the day felt rather than a staged sequence of events.			https://wayfinderfilms.co/	https://www.instagram.com/wayfinderfilmsco/
Strata Wedding Films	Videography		Lancaster	Pennsylvania	Central PA, Philadelphia, Lehigh Valley, Pittsburgh, New Jersey and worldwide	Owner-led wedding films with cinematic framing, true colour and story-driven dialogue; Tyler films every wedding and caps bookings each year.			https://www.strataweddingfilms.com/	https://www.instagram.com/strataweddingfilms/
Taylor Ann Photography	Photography		Lancaster	Pennsylvania	Pennsylvania and destinations abroad	Film and digital wedding photographer Taylor Mihaljevic, telling queer, nontraditional and adventurous love stories with a candid, joyful eye.			https://taylorannphotography.com/	https://www.instagram.com/taylorannphotography/
3 West Productions	Music	272 Granite Run Drive	Lancaster	Pennsylvania	PA, NJ, NYC, MD, DE and beyond	Entertainment company of touring musicians and DJs, offering wedding DJs, live bands and a band-plus-DJ hybrid shaped around each couple.	info@3westproductions.com	717-368-8305	https://www.3westproductions.com/	https://www.instagram.com/3west_productions/
The Clay House	Catering	1380 Furnace Hill Road	Stevens	Pennsylvania	Lancaster, York and Lebanon counties	Family-owned caterer since 2018 serving handmade buffet dinners, taco bowls, brunch spreads and a coffee bar, with care for dietary needs.	clayhousebnb@gmail.com	717-428-7238	https://www.theclayhousebnb.com/wedding-catering-lancaster-pa	https://www.instagram.com/theclayhousebnb/
Beats and Focus	Photography		Lancaster	Pennsylvania	Lancaster, Philadelphia, Pittsburgh, DC, Baltimore, Delaware, New Jersey and New York	Lancaster wedding team pairing photography with DJ and MC work, videography and a photo booth, so one crew covers several parts of the day.		717-538-0823	https://beatsandfocus.com/	https://www.instagram.com/beatsandfocus/
Burke & Poppy	Planning		Lancaster	Pennsylvania	Pennsylvania	Planning and floral design studio offering partial and full planning, taking a limited number of weddings a year with in-house flowers and rentals.	hello@burkeandpoppy.com		https://burkeandpoppy.com/	https://www.instagram.com/burkeandpoppy/
Meadowbrook Floral Design	Florals		Lancaster	Pennsylvania	Lancaster, York, Harrisburg and beyond in Pennsylvania and Maryland	Garden-inspired wedding florals from owner Laura and her team, using locally grown blooms in whimsical, garden or classic styles.	meadowbrookfloral@gmail.com		https://meadowbrookfloral.com/	https://www.instagram.com/meadowbrookfloral/
Luongo Barbecue	Catering	101 E Main St	Middletown	Pennsylvania	Central Pennsylvania	Family-run Texas pit barbecue, smoked low and slow, catering weddings with brisket, ribs and sides, with tastings at its Middletown restaurant.	luongobbq@gmail.com	717-202-2277	https://luongobbq.com/	https://www.instagram.com/luongobbq/
Oregon Dairy Bake Shoppe	Cake	2900 Oregon Pike	Lititz	Pennsylvania		Farm-market bakery designing custom wedding cakes in many flavours and fillings, now adding gluten-free cakes and mini dessert trays.		717-656-2856	https://www.oregondairy.com/the-bake-shoppe/wedding-cakes	https://www.instagram.com/oregondairy/
Lancaster Cupcake	Cake	260 Granite Run Dr	Lancaster	Pennsylvania		Gourmet cupcake bakery offering wedding cupcakes with a small cutting cake, a bridal sampling four-pack and a cupcake truck for the reception.		717-553-5287	https://www.lancastercupcake.com/weddings	
Rosenberry Media	Videography		Lancaster	Pennsylvania	Central Pennsylvania including Lancaster, Harrisburg, Hershey and Reading	Cinematic, story-led wedding films shot unobtrusively around natural moments, with photography also available from the same team.		717-229-7006	https://www.rosenberrymedia.com/weddingvideography	https://www.instagram.com/rosenberrymedia/`,
  },
  {
    name: "Poconos: photography, videography, music, florals, cake, catering, hair and makeup, bar, rentals and more",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Ever After Studio	Photography	1023 Dancing Ridge Rd	East Stroudsburg	Pennsylvania	Pocono Mountains, Lehigh Valley, Scranton, New Jersey and New York	East Stroudsburg wedding photographer and cinematographer covering Pocono venues, with a trusted team on hand for extra coverage when needed.	info@ever-afterstudio.com	(908) 892-2184	https://www.ever-afterstudio.com/	https://www.instagram.com/everafterstudio/
Renée Dee Photography	Photography	43 North 7th Street	Stroudsburg	Pennsylvania	Stroudsburg and the wider Pocono Mountains	Stroudsburg photographer with a studio, offering relaxed documentary-style coverage for microweddings, elopements, couples and families.	reneedeephotography@gmail.com	(570) 730-5583	https://www.reneedeephotography.com/	https://www.instagram.com/reneedeephotography/
Rob Lettieri Photography	Photography	1610 Wyoming Avenue	Scranton	Pennsylvania	Scranton, Poconos and Wilkes-Barre area	Scranton wedding photographer and filmmaker whose recent work includes weddings at Skytop Lodge, Stroudsmoor Inn and the Scranton Cultural Center.	rob@lettieriphoto.com	570.498.3686	https://www.lettieriphoto.com/	https://www.instagram.com/roblettieriphotography/
Frankie Carll Productions	Music	407 Davis Street	Clarks Summit	Pennsylvania	Poconos, Scranton, Wilkes-Barre, Hazleton, Lehigh Valley, Stroudsburg, Jim Thorpe, Hawley and Honesdale	Clarks Summit firm, established in 1984, offering wedding DJs alongside photography, videography, photo booths and uplighting across northeast Pennsylvania.	fcprod@frankiecarll.com	(570) 587-2740	https://www.frankiecarll.com/	https://www.instagram.com/frankiecarll/
Lucid Lens Films	Videography		Stroudsburg	Pennsylvania	Pocono Mountains, Lehigh Valley, Northeast Pennsylvania and New Jersey	Stroudsburg wedding filmmaker offering unobtrusive, candid films shot in 4K, with drone footage included in every package.	info@lucidlensfilms.com	(570) 580-0744	https://lucidlensfilms.com/	https://www.instagram.com/lucidlensfilms/
That's Groovy Photo Booth	Photo Booth		East Stroudsburg	Pennsylvania	Within about 60 miles of East Stroudsburg, including the Poconos, Scranton, Easton and Allentown	East Stroudsburg booth hire for weddings, with open-air, magic mirror and 360 options plus props and backdrops.	info.tg.photobooth@gmail.com	(570) 844-0111	https://thatsgroovyphotobooth.com/	https://www.instagram.com/thatsgroovyphotobooth/
Lois Heckman - Celebrant	Officiant		Saylorsburg	Pennsylvania	Pocono Mountain resorts and the Harmony Gardens ceremony site	Humanist celebrant who writes personal secular, spiritual or interfaith wedding and elopement ceremonies in the Poconos.		570-350-9514	http://www.loisheckman.com/	
Karla's Garden Studio	Florals	337 Poplar Valley Rd W	Stroudsburg	Pennsylvania	Stroudsburg, surrounding communities and the Slate Belt	Full-service floral studio in Stroudsburg designing wedding and event flowers, with delivery across the town and the Slate Belt.	karlasgardenstudio@gmail.com	570-234-3353	https://www.karlasgardenstudio.com	https://www.instagram.com/karlasgardenstudio/
Imaginations Florals & More by Ally	Florals	272 Learn Rd	Tannersville	Pennsylvania		Tannersville flower shop creating wedding flowers alongside everyday arrangements, gifts and plants for the local area.		(570) 620-2680	https://www.imaginationsfloralsnmore.com	https://www.instagram.com/imaginationsfloralsnmore_ally/
Gorgeous Floral	Florals		Hawley	Pennsylvania		Hawley florist offering wedding floral packages as well as flower subscriptions, houseplants and celebration arrangements.			https://www.gorgeous-floral.com	https://www.instagram.com/gorgeousfloralpa/
Sonia's Sweet Inspirations	Cake	110 N 9th Street	Stroudsburg	Pennsylvania		Stroudsburg bakery making custom wedding cakes, tiered designs and 3D novelty cakes, with a shop open Tuesday to Saturday.		(570) 664-6686	https://www.soniassweetinspirations.com	
Just Like Magic Bakery	Cake	727 Main Street	Stroudsburg	Pennsylvania		Stroudsburg bakery making custom wedding cakes, alongside cupcakes, cookies, macarons and dessert bars for weddings and special events.		(570) 872-0132	https://www.justlikemagicbakery.com	https://www.instagram.com/justlikemagicbakery_/
The Willowtree Inn	Catering	601 Ann St	Stroudsburg	Pennsylvania		Stroudsburg restaurant providing on- and off-site catering for wedding receptions, showers and other private celebrations.		570-476-0211	https://thewillowtreeinn.net	https://www.instagram.com/willowtreeinnrestaurant/
Latin Kitchen Catering	Catering		Tobyhanna	Pennsylvania	Within 30 minutes of Mount Pocono, extending to New York and New Jersey	Wedding caterer offering restaurant-style table service and flexible menus spanning Latin, Italian, Southern and American dishes.	Latinkitchencateringpa@gmail.com	570-580-9493	https://latinkitchencatering.com	https://www.instagram.com/latin_kitchen_catering/
Barley Creek Catering	Catering	1774 Sullivan Trail	Tannersville	Pennsylvania	Poconos region and beyond	Brewery-based caterer offering full-service catering at its venues or mobile kitchen catering, plus an Airstream mobile bar.		570-629-9399	https://www.barleycreek.com	https://www.instagram.com/barleycreekbrewing/
Fairview Catering	Catering	2016 Lehigh Ave	Whitehall	Pennsylvania	Lehigh Valley and Poconos	Caterer using mobile food units to cook fresh on site for weddings and banquets across the Lehigh Valley and Poconos.	twistedsistersscheduling@gmail.com	(484) 522-8307	https://fairviewcatering.com	
On The Rocks Mobile Bar	Bar		Milanville	Pennsylvania	Within 50 miles of zip code 18443	Dry-hire mobile bar with insured, RAMP-certified bartenders for weddings and private events, priced by package length.			https://mobilebarontherocks.com	https://www.instagram.com/mobilebar_ontherocks/
Hausbar	Bar		Bethlehem	Pennsylvania	Lehigh Valley, Poconos, Philadelphia and surrounding areas	Cocktail bar service with RAMP-certified bartenders and a portable bar, for hosts who supply their own alcohol at weddings.	info@hausbar.us	+1-484-809-6109	https://www.hausbar.us	https://www.instagram.com/hausbar.us/
SOUNDBAR Entertainment	Music		Saylorsburg	Pennsylvania	Poconos, Scranton, Lehigh Valley, NEPA	Wedding DJ based in Saylorsburg who takes one event per day, covering ceremony sound and receptions across the Poconos, Scranton and Lehigh Valley.	info@soundbardjs.com	(570) 520-2050	https://soundbardjs.com	https://www.instagram.com/soundbardjs/
DJ Johnny Johnson	Music		Sciota	Pennsylvania	Poconos, Lehigh Valley, Scranton, NEPA, northern and central New Jersey	Sciota-based wedding DJ offering four to six hour packages with custom playlists, MC duties and optional photo booth and uplighting add-ons.		570-402-1133	https://djjohnnyjohnson.com	
Penn Strings	Music		East Stroudsburg	Pennsylvania	Poconos and northeastern Pennsylvania	East Stroudsburg string ensemble playing classical and pop arrangements for weddings and events, with musicians and repertoire tailored to each couple.	pennstrings@gmail.com	(570) 604-5226	https://www.pennstrings.com	https://www.instagram.com/pennstringsrocks/
Oath Hair Studio & Spa	Hair & Makeup	96 South Courtland Street	East Stroudsburg	Pennsylvania	East Stroudsburg and the Poconos	East Stroudsburg salon and spa offering cuts, colour, extensions and spa treatments, plus bridal hair including trials ahead of the wedding.		(570) 534-0088	https://oathhairstudio.com	https://www.instagram.com/oathhairstudio/
La'Ren Hair Studio	Hair & Makeup	239 Fox Run Lane, Suite 3	East Stroudsburg	Pennsylvania	East Stroudsburg and the Poconos	East Stroudsburg hair studio known for colour and extensions, also styling updos and bridal hair with trial runs before the wedding.		(570) 630-0659	https://larenhairstudio.com	https://www.instagram.com/larenhairstudio/
11:11 Event Rentals	Rentals	118 Highland Avenue	Clarks Summit	Pennsylvania	Poconos incl. Tannersville, White Haven, Gouldsboro, Cresco; Scranton area	Family-run rental company delivering tents, tables, chairs, dance floors and decor to Poconos weddings, with setup included and no hidden labour fees.		(272) 228-0720	https://eleveneventrentals.com	https://www.instagram.com/1111_eventrentals/
Metz Amusements and Concessions	Rentals	6428 Sullivan Trail	Wind Gap	Pennsylvania	Stroudsburg, East Stroudsburg and northeast Pennsylvania	Wind Gap rental firm supplying tents up to 80 by 300 feet, tables, chairs and lighting for weddings in Stroudsburg, East Stroudsburg and nearby.	info@metzamusements.com	610-863-4914	https://metzamusements.com	
Elite Rides Limo Service	Transportation		Stroudsburg	Pennsylvania	Stroudsburg, Poconos and Lehigh Valley	Owner-operated Stroudsburg limousine service focused on weddings, with a 2024 Sprinter van and more than 25 years of experience.		570-817-7070	https://www.goeliterides.com	https://www.instagram.com/goeliterides/
Luxury Limousine Service	Transportation	8 Apollo Dr.	West Wyoming	Pennsylvania	Northeast Pennsylvania and Poconos incl. Monroe County	Independent West Wyoming operator since 1989, providing wedding limousines and party buses for events across northeast Pennsylvania and the Poconos.	info@luxurylimo.com	(570) 823-5233	https://luxurylimo.com	https://www.instagram.com/luxurylimo/
POSH Life Floral	Decor & Lighting	401 Jefferson Avenue	Scranton	Pennsylvania	Scranton and northeast Pennsylvania	Scranton floral and event design team offering installations, custom decor pieces and lighting such as uplighting and pin spotting for weddings.			https://poshscranton.com	
Elegant Bridal Boutique	Bridal & Formalwear	106 Plaza 611 Lane	Stroudsburg	Pennsylvania	Stroudsburg, Tannersville and the Poconos	Stroudsburg bridal shop open since 1990, selling wedding, bridesmaid and mother-of-the-bride gowns with spacious fitting rooms and styling help.	elegantbridalboutique@yahoo.com	(570) 688-9594	https://www.elegantbridalboutique.net	`,
  },
  {
    name: "Philadelphia: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Abhi Sarkar Photography	Photography		Philadelphia	Pennsylvania	Philadelphia, New Jersey, NYC and destination weddings	Candid, emotional wedding coverage paired with high-fashion portraits, with an engagement session and print credits in every package.	namaste@abhisarkar.com	856-857-8147	https://www.abhisarkar.com/	https://www.instagram.com/asarkarphotos/
The Styled Stem	Planning		Philadelphia	Pennsylvania	Philadelphia, New York, New Jersey, Delaware and the DMV	Full-service wedding management that starts six to nine months out, taking over vendor coordination and running the day itself.	info@thestyledstem.com	347-385-6979	https://www.thestyledstem.com/	https://www.instagram.com/the_styled_stem/
Designs by Daisy Events	Planning	1306 Pottstown Pike	West Chester	Pennsylvania	West Chester, Philadelphia and the Main Line	West Chester planner offering full planning through day management, with a detail-focused approach to luxury celebrations.	daisy@designsbydaisyevents.com	(484) 319-7216	https://designsbydaisyevents.com/	https://www.instagram.com/designsbydaisyevents/
Walter Pine Floral Studio	Florals	729 South 4th Street	Philadelphia	Pennsylvania	Greater Philadelphia	Queen Village flower shop and studio with a wedding portfolio and FAQs, alongside same-day delivery across Philadelphia.	hello@walterpine.com	267-519-0120	https://www.walterpine.com/	https://www.instagram.com/walterpinestudio/
Accents by Michele Flower Studio	Florals	3829 West Chester Pike	Newtown Square	Pennsylvania	Delaware, Chester, Montgomery and Philadelphia counties	Newtown Square florist at Ellis Preserve with wedding galleries, colour collections and pages for nearby ballroom venues.	accentsbymichele@verizon.net	(610) 356-5683	https://www.accentsbymichele.com/	https://www.instagram.com/accentsbymichele/
Schaffer Sound Disc Jockeys	Music	843 N. Providence Road	Media	Pennsylvania	Philadelphia, South Jersey, Jersey Shore, Delaware, Delaware County, Chester County, Montgomery County and Lancaster County	Media-based wedding DJ company that tailors each booking to the couple and works with modern audio equipment.	comments@schaffersound.com	(610) 627-5900	https://sspdj.com/	https://www.instagram.com/schaffersounddjs/
Bonita Sound	Music		Philadelphia	Pennsylvania	Philadelphia, NYC, the Jersey Shore and nearby eastern PA, NJ and NY	DJs paired with live musicians for culturally rich soundtracks, including Jewish weddings and hora sets, founded by DJ Royale.	bookings@bonitasound.com	276-212-1226	https://www.bonitasound.com/	https://www.instagram.com/bonitasound/
Catering by Jessica Lee	Catering	925 Street Rd	Southampton	Pennsylvania	Philadelphia, the Main Line, King of Prussia, Montgomery County, Doylestown and Bucks County	Southampton caterer offering all-inclusive wedding packages built on personal service and close attention to detail.	info@cateringbyjessicalee.com	(215) 343-4186	https://cateringbyjessicalee.com/	
AAC Event Catering	Catering	2135 Bustard Rd. Suite #8	Lansdale	Pennsylvania	Montgomery County, plus private residences, farms and other venues	Montgomery County caterer for weddings from barn receptions to outdoor dinners, with fresh menus and full service.		(610) 584-6212	https://www.aaceventcatering.com/	https://www.instagram.com/aaceventcatering/
Christina San Clemente Beauty	Hair & Makeup		Philadelphia	Pennsylvania	Philadelphia, the Main Line, South Jersey and Bucks County	On-location bridal makeup and hair team aiming for a natural, elevated look that still feels like the client.	christina@christinasanclemente.com	(609) 220-4370	https://phillybeauty.com/	https://www.instagram.com/christinasanclementebeauty/
Isla Studio + Hair Co.	Hair & Makeup	3614 Chapel Road	Newtown Square	Pennsylvania	Newtown Square, West Chester, Wayne, Villanova, Bryn Mawr, Havertown, Broomall, Media, Malvern and Berwyn	Salon-based bridal hair and makeup in Newtown Square and West Chester, with full bridal party styling and pre-wedding spray tans.	islahairco@gmail.com	(610) 862-2131	https://www.islastudiobeautybar.com/	https://www.instagram.com/islabeautybar/
The Master's Baker	Cake	319 West Gay Street	West Chester	Pennsylvania	West Chester and Greater Philadelphia	West Chester bakery with more than 55 years of custom cakes, taking wedding cake consultations by booking.	info@themastersbaker.com	610-436-9888	https://themastersbaker.com/	https://instagram.com/themastersbaker/
Chocolate Therapy	Cake		West Chester	Pennsylvania		Custom cakes blending European, Indian and American flavours, such as rasmalai tres leches, designed from a couple's theme.		(267) 541-8620	https://chocolatetherapy.us/	https://www.instagram.com/chocolate.therapy.by.nupur/
Alenka Films	Videography		Philadelphia	Pennsylvania	Pennsylvania, New Jersey and Delaware	Solo female-owned studio making documentary-style wedding films with multiple camera angles.	alenkafilms@gmail.com		https://www.alenkafilms.com/	https://www.instagram.com/alenkafilms/`,
  },
  {
    name: "Pittsburgh: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Steven Dray Photography	Photography		Pittsburgh	Pennsylvania	Western PA	Pittsburgh wedding photographer taking an unobtrusive, fly-on-the-wall approach to classic, emotive coverage across western Pennsylvania.	steven@stevendrayphotography.com		https://stevendrayphotography.com/	https://www.instagram.com/stevendrayphoto/
Day One Wedding Co.	Planning		Pittsburgh	Pennsylvania		Pittsburgh planner offering holistic wedding planning, design and day-of coordination for couples who want the day to start their marriage well.	hello@dayoneweddingco.com		https://www.dayoneweddingco.com/	https://www.instagram.com/dayone.weddingco/
The Blue Daisy Floral Designs	Florals	109 East Spring Street	Zelienople	Pennsylvania	Pittsburgh and Zelienople	Boutique florist with shops in Zelienople and Pittsburgh designing wedding flowers, plus gifts, workshops and local delivery.		724-473-0802	https://thebluedaisyfloral.com/	https://www.instagram.com/thebluedaisyfloral/
Steven Vance Entertainment	Music		Pittsburgh	Pennsylvania	Pittsburgh, Cleveland and DC	Electric violin, string ensemble and DJ packages for weddings, with photo booths and uplighting available to bundle.	stevenvance@stevenvance.com	724-799-0277	https://stevenvance.com/	https://www.instagram.com/stevenvanceentertainment/
The Chef and I Catering	Catering	902 Brackenridge Ave	Brackenridge	Pennsylvania	Pittsburgh area	Full-service caterer near Pittsburgh with custom menus, offering full-service and casual wedding options and a published list of preferred venues.		(724) 295-2400	https://chefandicatering.com/	https://www.instagram.com/chefandicatering/
Just in Thyme Catering & Events	Catering	5316 William Flinn Hwy #203	Gibsonia	Pennsylvania	Pittsburgh area	Gibsonia caterer with its own event space, offering catering and wedding hosting across the Pittsburgh region.	events@jitcatering.com	(412) 969-4807	https://www.jitcatering.com/	https://www.instagram.com/jitcatering/
Finch Beauty & Bridal	Hair & Makeup	608 California Ave	Pittsburgh	Pennsylvania		Pittsburgh hair salon and bridal studio taking dated bridal bookings, with a hair and makeup team, extensions and bridal coaching.	office@finchbeauty.com	412-935-8416	https://www.finchbeauty.com/	https://www.instagram.com/finchbeautypgh/
Artistry by Emily	Hair & Makeup		Pittsburgh	Pennsylvania		Pittsburgh makeup artist working with brides, with a portfolio of past looks and a list of local vendors she recommends.	artistrybyemilypgh@gmail.com	412-452-2308	https://www.artistrybyemily.com/	https://www.instagram.com/emily_artistry/
Alex Robba Cake	Cake		Pittsburgh	Pennsylvania	East Coast	Pittsburgh cake designer creating refined wedding cakes, with a tasting offering and clients throughout the East Coast.	info@alexrobbacake.com		https://www.alexrobbacake.com/	https://www.instagram.com/alexrobbacake/
Alyssa Michelle Videography	Videography		Pittsburgh	Pennsylvania		Pittsburgh videographer filming emotional wedding films, with photo and video duo packages for couples who want one team.	alyssamvideo@gmail.com		http://www.alyssamichellevideography.com/	https://www.instagram.com/alyssamichellevideographyllc/
Penderville Wedding Films	Videography		Pittsburgh	Pennsylvania		Pittsburgh videographer making fun, cinematic wedding films, openly welcoming couples of every background and LGBTQ+ weddings.	jt@pendervilleweddingfilms.com		https://www.pendervilleweddingfilms.com/	https://www.instagram.com/pendervilleweddingfilms/`,
  },
  {
    name: "Lehigh Valley: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
John Wirick Photography	Photography	3738 Northwood Avenue	Easton	Pennsylvania	Easton, Bethlehem, Allentown and beyond	Easton photographer blending photojournalistic wedding coverage with lightly guided portraits, offering timeline help, full-day coverage and custom albums.	john@johnwirickphotography.com	610-991-7501	https://www.johnwirickphotography.com/	https://www.instagram.com/johnwirickphotography/
Gangi Photography	Photography	821 North New Street	Bethlehem	Pennsylvania	Lehigh Valley, Allentown, Bethlehem, Kutztown	Bethlehem studio shooting romantic, photojournalistic weddings and elopements, mixing candid and posed frames with close attention to small details.	gangiphotography@gmail.com	609-577-5532	https://gangiphotography.com/	https://www.instagram.com/gangi_photography/
Mosaic & Co.	Planning	1096 Milton Street	Catasauqua	Pennsylvania	Lehigh Valley, Allentown, Bethlehem, Easton and Philadelphia	Full-service wedding planner offering a free consultation and acting solely for the couple rather than for a venue, with liability insurance provided.	hello@mosaicandcompany.com	610-657-5703	https://mosaicandcompany.com/planning	https://www.instagram.com/mosaicandcompany/
Rich Mar Florist	Florals	1708 Tilghman Street	Allentown	Pennsylvania	Lehigh Valley and beyond	Four-generation family florist with a bridal showroom of bouquet, ceremony and centrepiece samples and a free 90-minute consultation.	richmarflorist@aol.com	610-437-5588	https://richmarflorist.com/weddings/	https://www.instagram.com/richmarflorist/
Cathy's Creative Catering & Café	Catering	752 Front St	Catasauqua	Pennsylvania	Lehigh Valley	Catasauqua caterer with over thirty years' experience, also offering wedding cakes and licensed event planning and coordination.	cathyscreativecatering@yahoo.com	610-443-0670	https://www.cathyscreativecatering.com/	https://www.instagram.com/cathyscreativecatering/
Makeup by Roxy	Hair & Makeup	301 Front St	Catasauqua	Pennsylvania	Lehigh Valley, on location near and far	Catasauqua studio with a mobile team doing bridal hair and makeup on location, taking bridal enquiries by email to manage limited dates.	info@makeupbyroxy.com	484-820-0202	https://www.makeupbyroxy.com/	https://www.instagram.com/makeupbyroxy/
Piece 'a Cake	Cake	165 E Main St	Macungie	Pennsylvania		Macungie bakery making scratch-baked wedding cakes from hand-drawn sketches and delivering large ones in its own refrigerated truck.		610-421-8482	https://www.pieceacakellc.com/	https://www.instagram.com/pieceacakellc/
LBJ Media	Videography	931 Hamilton St, Floor 3	Allentown	Pennsylvania	Lehigh Valley and beyond	Allentown studio filming full-day weddings with two videographers, clear vow and speech audio and a cinematic highlight edit, with Spanish-speaking staff.			https://www.lbjmedia.com/wedding-videography.html	https://www.instagram.com/lbjmediallc/`,
  },
  {
    name: "Harrisburg and Hershey: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Elaine Gates Photography	Photography		Mechanicsburg	Pennsylvania	Harrisburg, Mechanicsburg, Camp Hill, Lemoyne, Hershey and beyond	Mechanicsburg photographer with sixteen years of weddings, building the timeline with couples and keeping the day relaxed, including for children.	elaine@elainegates.com	717-805-4953	https://elainegates.com/	https://www.instagram.com/elainegatesphoto/
That's It! Wedding Concepts	Planning		Mechanicsburg	Pennsylvania	Eastern and south central Pennsylvania, northern Maryland, Washington DC and destinations	Mechanicsburg planner known for merit-based vendor referrals and wedding-day execution, with venues ranging from city parks to the State Capitol.	thatsitweddingconcepts@gmail.com	717-645-5700	https://www.thatsitweddingconcepts.com/	https://www.instagram.com/thatsitweddingconcepts/
Plenty of Petals	Florals		Harrisburg	Pennsylvania	Harrisburg, Hershey, Mechanicsburg, Camp Hill, Carlisle, Middletown, Hummelstown and Elizabethtown	Harrisburg studio that includes delivery and full venue setup with every wedding, from arches to aisle pieces and centrepieces.		717-608-1401	https://plentyofpetalspa.com/	
Klock Entertainment	Music	2200A Woodview Dr	Harrisburg	Pennsylvania	Dauphin, Lancaster, Cumberland and York counties, including Camp Hill, Carlisle, Mechanicsburg and Hershey	Harrisburg DJ company of about twenty years, combining wedding DJs, lighting, audio-visual and photo booths under one roof.		717-836-7366	https://klockentertainment.com/	https://www.instagram.com/klockentertainment/
Mountain Laurel Catering & Events	Catering	3424 N 6th St	Harrisburg	Pennsylvania	Central PA, including Lancaster, Carlisle and Mechanicsburg	Harrisburg caterer cooking from scratch with seasonal, fully customisable menus and a focus on sustainable products.	Info@mountainlaurelcatering.com	717-364-0782	https://www.mountainlaurelcatering.com/	https://www.instagram.com/mountain_laurel_catering/
Strictly Catering	Catering	17 S. 35th Street	Camp Hill	Pennsylvania	Within 60 miles of its Camp Hill kitchen, including Harrisburg, Mechanicsburg, Carlisle, New Cumberland, Dillsburg, Lancaster and York	Camp Hill caterer of thirty-plus years with a weddings page, instant online quoting and dietary options built into its menus.	Info@strictlycatering.com	223-895-7411	https://strictlycatering.com/	https://www.instagram.com/strictlycatering/
Carmina Cristina	Hair & Makeup	2209 Market Street	Camp Hill	Pennsylvania	Harrisburg, Lancaster, Hershey, York and Central PA	Camp Hill makeup boutique with bridal packages and portfolio, led by an artist trained in the US, Canada and Romania.	Carmina@CarminaCristina.com	717-343-2805	https://carminacristina.com/	https://www.instagram.com/carminacristinamua/
Sweet Confections Cakes	Cake	4702 Fritchey Street	Harrisburg	Pennsylvania	Camp Hill, Carlisle, Enola, Dauphin, Harrisburg, Halifax, Hershey, Lebanon, Lancaster, Mechanicsburg, York and surrounding communities	Harrisburg bakery with an in-store display room, making custom wedding cakes and wedding cheesecakes designed around couples' inspiration photos.	info@sweetconfectionscakes.com	717-671-7111	https://www.sweetconfectionscakes.com/	
Zimmerman Videography	Videography		Mifflintown	Pennsylvania	Central PA, including York, Lancaster and Harrisburg	Family-run studio making documentary-style wedding films with music licensing included, so they can be shared on social media without being muted.	zimmermanvideography@gmail.com		https://www.zimmermanvideography.com/	https://www.instagram.com/zimmvideo/`,
  },
  {
    name: "Erie: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Smyklo Photo	Photography		Erie	Pennsylvania		Erie photographer with twenty years behind the camera, shooting candid, artistic wedding coverage across north-west Pennsylvania.	eric@smyklophoto.com	814.218.3232	https://smyklophoto.com/	
Morgan Pelinsky Photography	Photography		Erie	Pennsylvania		Queer-owned Erie wedding and boudoir photographer shooting raw, relaxed coverage, and happy to travel for destination weddings.			https://morganpelinskyphotography.com/	https://www.instagram.com/morganpelinskyphotography/
WE Weddings and Events	Planning		Erie	Pennsylvania	North-western PA, eastern Ohio and western NY	Erie planner for weddings, showers and corporate events, working with couples across north-west Pennsylvania, eastern Ohio and western New York.			https://weweddingsevents.com/	https://www.instagram.com/weweddingsevents/
Bella's Blooms Flower Co.	Florals		Erie	Pennsylvania	Erie, PA	Erie flower farm and florist growing seasonal specialty cut flowers locally and designing bespoke bouquets and arrangements for weddings.	info@bellasblooms.com		https://www.bellasblooms.com/weddings	https://www.instagram.com/bellasbloomspa/
Mary Mae Gardens	Florals	2564 W 8th Street	Erie	Pennsylvania	Erie, PA and surrounding areas	Erie flower farm and florist with a Colony Plaza shop, supplying locally grown seasonal flowers for weddings, galas and backyard parties.	flowers@marymaegardens.com	(814) 790-2757	https://www.marymaegardens.com/events	https://www.instagram.com/marymaegardens/
John Gallagher Wedding & Special Event Entertainment	Music		Erie	Pennsylvania	Erie, western PA, north-east Ohio and western NY	Erie DJ and photo booth company covering weddings across north-west Pennsylvania, north-east Ohio and western New York.		814.838.2490	https://www.johngallagher.com/	https://www.instagram.com/johngallagherdj/
Sabella's Catering	Catering	1508 West 32nd Street	Erie	Pennsylvania	Erie, PA	Erie caterer handling weddings, rehearsal dinners and showers, with a published list of venues it works in and a focus on plated presentation.		(814) 868-3463	https://www.sabellascatering.com/	
Formosa Hair Studio	Hair & Makeup	7165 Peach St, Studio 27	Erie	Pennsylvania	Erie, PA	Private boutique studio in Erie offering bridal trials, updos, soft waves and makeup for wedding mornings.	formosahair27@gmail.com	(814) 873-9434	https://formosa.hair/bridal-hair-erie-pa/	https://www.instagram.com/formosa_hair_by_katie/
JustineMade	Cake		Erie	Pennsylvania	Erie, PA	Home-based Erie baker making custom wedding cakes from scratch, known for hand-piped realistic buttercream flowers.	justinemadellc@gmail.com	(814) 580-5292	https://www.justinemade.com/	https://www.instagram.com/justinemade.llc/
Variety Video	Videography		Erie	Pennsylvania	Erie, PA area	Erie videographer who films the key moments of the day and edits them into a single wedding video, with a set package and sample reels.	varietyvideoerie@gmail.com		https://varietyvideoerie.com/	`,
  },
];

export default batches;
