import type { VendorBatch } from "@/lib/vendor-batches";

// Pennsylvania vendor batches. Every row's State is "Pennsylvania". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Philadelphia: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hoffer Photography	Photography		Downingtown	Pennsylvania		Husband-and-wife Chester County team photographing Philadelphia weddings in an authentic, elevated style mixing candids and portraits.	info@hofferphotography.com	484-693-0055	https://hofferphotography.com/	https://www.instagram.com/hofferphotography/
Asya Photography	Photography		Philadelphia	Pennsylvania		Philadelphia photographer with a romantic, documentary approach, shooting weddings at places like the Barnes Foundation.	asya@asyaphotography.com		https://asyaphotography.com/	https://www.instagram.com/asya_photography_philly/
Love Me Do Photography	Photography	2220 E Susquehanna Ave	Philadelphia	Pennsylvania		Fishtown-based team of photographers and videographers covering weddings, with several lead shooters to choose from.	carina@lovemedophotography.com		https://www.lovemedophotography.com/	https://www.instagram.com/lovemedophoto/
Porch & Pearls	Planning		Philadelphia	Pennsylvania	Philadelphia and destination weddings	Full planning firm led by an attorney-turned-planner, focused on vendor management, timelines and calm execution on the day.		267-258-4292	https://www.porchandpearls.com/	https://www.instagram.com/porchandpearls/
Olive Street Events	Planning		Philadelphia	Pennsylvania		Wedding planning and design company whose team brings experience from both planning weddings and running venues.	hello@olivestreetevents.com		https://www.olivestreetevents.com/	https://www.instagram.com/olivestreetevents/
Elegant Events Planning + Design	Planning		Philadelphia	Pennsylvania	Philadelphia and its suburbs, Delaware, New Jersey, Maryland and destinations	Long-running planning and design firm specialising in Indian, multicultural, interfaith and fusion weddings, with offices in Philadelphia and Delaware.		888-549-7526	https://elegant-events.net/	https://www.instagram.com/eleganteventsphilly/
Caroline Florals	Florals		Philadelphia	Pennsylvania	Philadelphia and beyond	Whimsical, flower-forward wedding florist known for playful colour palettes, natural movement and seasonal blooms.	hello@carolineflorals.com		https://carolineflorals.com/	https://www.instagram.com/caroline.florals/
Myrtle & Magnolia	Florals	2222 Frankford Ave	Philadelphia	Pennsylvania		Woman-owned Fishtown flower shop and studio designing artistic, bespoke florals for weddings and events.	hello@myrtleandmagnolia.com	215-914-3805	https://www.myrtleandmagnolia.com/	https://www.instagram.com/myrtlemagnolia/
Gardena Floral	Florals		Fort Washington	Pennsylvania	Philadelphia, Bucks County and beyond	Boutique florist and micro flower farm growing many of its own blooms for romantic, garden-inspired wedding work.	hello@gardenafloral.com		https://gardenafloral.com/	https://www.instagram.com/floralsbyadena/
BVTLive!	Music	114 Commons Court	Chadds Ford	Pennsylvania	Philadelphia region	Agency behind a roster of exclusive wedding and dance bands, plus DJs and specialty acts for weddings around Philadelphia.	info@bvtlive.com	610-358-9010	https://www.bvtlive.com/	https://www.instagram.com/bvtlive/
CTO Music Artists	Music		Bala Cynwyd	Pennsylvania	Philadelphia, the Main Line, Bucks, Montgomery, Delaware and Chester counties	Entertainment agency booking live party bands, DJs and ceremony ensembles for Philadelphia-area weddings since 1997.	info@cto.art	215-220-9928	https://www.ctomusicartists.com/	https://www.instagram.com/ctomusicartists/
Z4 Events	Music		Philadelphia	Pennsylvania	Philadelphia, New Jersey and Delaware	DJ and lighting company specialising in Indian and cultural weddings, with Bollywood sets, uplighting and LED video walls.	z4eventsusa@gmail.com	267-444-7148	https://z4events.com/	https://www.instagram.com/z4events/
Peachtree & Co.	Catering	175 King of Prussia Road	Radnor	Pennsylvania	Main Line, Philadelphia and beyond	Family-run caterer since 1985 serving off-premise weddings and its own venues, including Pomme, Parque, Portico and The Willows.	sales@peachtreeandco.com	484-580-8260	https://www.peachtreeweddings.com/	https://www.instagram.com/peachtreeweds/
Eatible Delights Catering	Catering	1540 Wadsworth Avenue	Philadelphia	Pennsylvania		Chef David Simms' Philadelphia caterer, established in 1996, cooking classic familiar favourites with a modern flair.		215-236-3900	https://eatibledelightscatering.com/	
LemonCo Catering	Catering		Philadelphia	Pennsylvania	Philadelphia, the Main Line, Bucks and Montgomery counties	Boutique full-service caterer offering custom menus, BYOB bar service with signature cocktails, rentals and decor.		609-464-1313	https://www.lemoncocatering.com/	https://www.instagram.com/lemoncocatering/
Aleksandra Ambrozy Makeup and Hair	Hair & Makeup	1118 Pine Street	Philadelphia	Pennsylvania	Philadelphia, the Main Line, South Jersey, NYC and Delaware	Center City team bringing refined on-location bridal hair and makeup that enhances natural features and photographs well.	info@aleksandraambrozy.com		https://aleksandraambrozy.com/	https://www.instagram.com/aleksandraambrozy/
The Philly Hair & Makeup Co.	Hair & Makeup	2619 Aramingo Ave	Philadelphia	Pennsylvania	Philadelphia, Bucks and Montgomery counties, the Main Line and South Jersey	On-location bridal hair and makeup team with a Fishtown studio, bringing a full salon set-up to wedding mornings.	phillyhairgirl@gmail.com	267-687-7936	https://www.phillyhairandmakeup.com/	https://www.instagram.com/phillyhair/
Beauty & Bridal Philly	Hair & Makeup	28 S 8th Street	Quakertown	Pennsylvania	Philadelphia area, New Jersey, NYC and Delaware	Bridal hair and makeup studio led by an artist with over 18 years' experience, travelling to weddings across the region.	beautyandbridalphilly@gmail.com	607-368-7808	https://beautyandbridalphilly.com/	https://www.instagram.com/beautyandbridalphilly/
Isgro Pastries	Cake	1009 Christian Street	Philadelphia	Pennsylvania		Italian Market bakery, family owned since 1904, making traditional Italian pastries alongside custom wedding cakes.	isgropastries1904@gmail.com	215-923-3092	https://isgropastries.com/	https://www.instagram.com/isgropastries/
The Frosted Fox Cake Shop	Cake	6511 Germantown Ave	Philadelphia	Pennsylvania		Mt Airy bakery baking from scratch daily, making custom wedding cakes and treats for over a decade.	frostedfoxcakeshop@gmail.com	267-900-5453	https://www.frostedfoxcakeshop.com/	https://www.instagram.com/frostedfoxcakeshop/
The Novel Baker	Cake	4945 W Swamp Rd	Doylestown	Pennsylvania		Bucks County boutique cake studio known for airy buttercream wedding cakes, with tasting experiences available.		215-280-5926	https://www.thenovelbaker.com/	https://www.instagram.com/thenovelbaker/
Solidity Films	Videography		Philadelphia	Pennsylvania	Philadelphia region and beyond	Philadelphia videographers making story-led wedding films that go beyond a chronological recap of the day.	info@solidityfilms.com		https://solidityfilms.com/	https://www.instagram.com/solidityfilms/
New Pace Weddings	Videography		Philadelphia	Pennsylvania	Philadelphia and beyond	Studio working since 2007 that offers wedding videography and photography together, plus social media reels.	info@newpaceweddings.com	484-453-8419	https://newpaceweddings.com/	https://www.instagram.com/newpaceweddings/
Noise Soul Cinema	Videography		Philadelphia	Pennsylvania	Philadelphia and the Tri-State	Philadelphia video company led by Joshua Mallory, filming weddings alongside nonprofit and brand work, with a three-payment plan.		267-225-8285	https://noisesoulcinema.com/	https://www.instagram.com/noisesoulcinema/`,
  },
  {
    name: "Pittsburgh: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Novasoul Photography	Photography		Pittsburgh	Pennsylvania	Pittsburgh, Western Pennsylvania and surrounding areas	Documentary-style wedding photographer with a relaxed, journalistic approach, often shooting at Pittsburgh restaurants and hotels.			https://www.novasoulphotography.com/	https://www.instagram.com/novasoulphotography/
Sarah McCloskey Photography	Photography		Pittsburgh	Pennsylvania		Pittsburgh-based photographer and small team focused on natural, detail-rich wedding coverage, travelling for destination weddings.			https://sarahmccloskey.com/	https://www.instagram.com/sarahmccloskeyphoto/
Ashley Sara Photography	Photography		Pittsburgh	Pennsylvania	Pennsylvania, the East Coast and destinations worldwide	Editorial, artful wedding photography from Pittsburgh, with venue guides covering local mansions and county parks.	hello@ashleysaraphotography.com		https://ashleysaraphotography.com/	https://www.instagram.com/ashleysaraphoto/
Stark White Weddings	Planning		Pittsburgh	Pennsylvania	Pittsburgh and worldwide	Pittsburgh team of wedding managers and planners founded in 2023, offering full planning, partial planning and day-of management.	hello@starkwhiteweddings.com		https://starkwhiteweddings.com/	https://www.instagram.com/starkwhiteweddings/
Tiffany and Design	Planning		Pittsburgh	Pennsylvania		Pittsburgh planner whose background in graphic and interior design shapes both coordination and the look of the day.	info@tiffanyanddesign.com		https://tiffanyanddesign.com/	https://www.instagram.com/tiffanyanddesign/
Wanderlust Weddings and Events	Planning		Pittsburgh	Pennsylvania	Pittsburgh and destinations worldwide	Pittsburgh-based planning firm working since 2015 on local and destination weddings, with an inclusive approach to every couple.	services@wanderlustweddingsandevents.com		https://www.wanderlustweddingsandevents.com/	https://www.instagram.com/wanderlustweddingsandevents/
Hearts and Flowers Floral Design	Florals		Pittsburgh	Pennsylvania		Pittsburgh wedding and event florist designing custom arrangements through an inquiry and design-process approach.	brigette@heartsandflowersfloral.com		https://www.heartsandflowersfloral.com/	https://www.instagram.com/heartsandflowersfloraldesign/
Flowers by Gerard	Florals	20555 Rte 19	Cranberry Township	Pennsylvania		Cranberry Township flower shop on Route 19 offering wedding flowers alongside same-day designed and hand-delivered arrangements.	wecare@flowersbygerard.com	(724) 779-3900	https://www.flowersbygerard.com/wedding	https://www.instagram.com/flowersbygerard/
Sugar Flowers and Leaves	Florals		Sewickley	Pennsylvania	Pittsburgh-area events	Appointment-only Sewickley florist offering custom wedding work and lower-cost pre-designed colour collections, delivery only.	designer@sugarflowersandleaves.com	(412) 915-3069	https://www.sugarflowersandleaves.com/weddings	https://www.instagram.com/sugarflowersandleaves/
Bethel Bakery	Cake	5200 Brightwood Road	Bethel Park	Pennsylvania		Family-owned South Hills bakery known for its French buttercream, offering wedding cake consultations, tastings and custom designs.		412-835-6658	https://www.bethelbakery.com/	https://www.instagram.com/bethelbakery/
Prantl's Bakery	Cake	612 Grove Street	Greensburg	Pennsylvania		Westmoreland County bakery famous for its burnt almond torte, with shops around Pittsburgh and a wedding cake service.		724-837-3706	https://www.prantlsbakery.com/weddings	https://www.instagram.com/prantlsbakery/
Remo's Catering	Catering		Pittsburgh	Pennsylvania	Pittsburgh-area venues	Family wedding caterer with five generations of experience, offering custom menus, bar service, mobile BBQ and free tastings.		412-822-7844	https://www.remoscatering.com/	https://www.instagram.com/remoscatering/
Post Script Films	Videography	618 Beaver Street	Sewickley	Pennsylvania	Pittsburgh and beyond	Sewickley wedding film studio with a full-time team and 16 years in business, making cinematic films with customisable packages.	weddings@postscriptfilms.com		https://www.postscriptfilms.com/	https://www.instagram.com/postscript_weddingfilms/
Fireside Events	Music		Allison Park	Pennsylvania	Pittsburgh and Western Pennsylvania	Family-run DJ and AV production company working since 2015, combining DJ and MC work with lighting, sound and day-of coordination.			https://fireside-events.com/	https://www.instagram.com/fireside.events/
Loyalty Weddings & Events	Music		Pittsburgh	Pennsylvania		Pittsburgh entertainment company founded in 2015 by Loyal and Nicole Martinez, offering wedding DJs alongside live music.	info@loyaltyevents.com	(412) 607-3693	https://www.loyaltyevents.com/	https://www.instagram.com/loyaltyentertains/
Aaron Woods Productions	Videography		Pittsburgh	Pennsylvania		Pittsburgh videographer shooting in 4K with drone coverage, delivering cinematic highlight films and full-length features.		412 260-5242	https://aaronwoodsproductions.com/	https://www.instagram.com/aaronwoods.productions/
Glam To Go	Hair & Makeup		Pittsburgh	Pennsylvania	Pittsburgh and worldwide travel	Mobile bridal hair and makeup team based in Pittsburgh, coming to the wedding-morning location and now booking into 2027.	info@glamtogo.com		https://glamtogo.com/	https://www.instagram.com/_glamtogo_/
The Fluted Mushroom	Catering	109 S. 12th St.	Pittsburgh	Pennsylvania	Pittsburgh area	South Side caterer working for nearly 50 years, building custom wedding menus with vegan and vegetarian options and a venue guide.	catering@flutedmushroom.com	412.381.1899	https://flutedmushroom.com/	https://www.instagram.com/theflutedmushroom/
Oakmont Bakery	Cake	One Sweet Street	Oakmont	Pennsylvania		Large family-founded retail bakery in Oakmont, open since 1988, with cake designers for wedding and groom's cakes plus cookies and minis.		412-826-1606	https://oakmontbakery.com/weddings/	https://www.instagram.com/oakmontbakery/
Hot Metal Strings	Music		Pittsburgh	Pennsylvania		All-female, classically trained Pittsburgh string ensemble playing ceremonies and receptions as a solo, duet, trio or quartet.			https://hotmetalstrings.com/	https://www.instagram.com/hotmetalstrings/
Carnation Films	Videography		Pittsburgh	Pennsylvania	Pennsylvania, Ohio and destinations	Husband-and-wife film team in Pittsburgh shooting weddings on both digital and Super 8, with raw footage included alongside the edit.			https://carnation-films.com/	https://www.instagram.com/carnationfilms/
Simply Captivating Salon	Hair & Makeup		Pittsburgh	Pennsylvania	Pennsylvania, Ohio and West Virginia	On-location bridal hair team that sets up a mini salon at the getting-ready venue, specialising in updos and bridal party styling.		412-448-8989	https://simplycaptivatingsalon.com/	https://www.instagram.com/simply.captivating.pgh_hair/
All in Good Taste Productions	Catering	1520 Monterey St.	Pittsburgh	Pennsylvania	Pittsburgh and the surrounding areas	North Side caterer and event producer with over 35 years in business, handling weddings from engagement party through farewell brunch.	info@allingoodtasteproductions.com	412-321-6869	https://allingoodtasteproductions.com/	
JL Makeup Studio and Beauty Boutique	Hair & Makeup		Pittsburgh	Pennsylvania	Pittsburgh, free within 30 miles	Pittsburgh bridal makeup and hair studio offering in-studio or on-site wedding teams, with published packages running to 2028.	jlstudiopgh@gmail.com		https://www.jlstudiopgh.com/bridal-services	https://www.instagram.com/jlstudio_hairandmakeup/`,
  },
  {
    name: "Lancaster: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kirsten Hartzell Photography	Photography		Lancaster	Pennsylvania	Lancaster, Philadelphia, Maryland, New York, Washington DC and destinations	Docu-editorial wedding photographer pairing unscripted documentary coverage with polished, intentional portraits for couples who want to stay present.	kirstenhartzellphotography@gmail.com		https://www.kirstenhartzellphotography.com/	https://www.instagram.com/kirstenhartzellphotography/
Alisa Marie Co.	Planning		Lancaster	Pennsylvania		Lancaster planner offering day-of coordination, partial and full planning, quietly handling problems on the day so couples can simply enjoy it.			https://www.alisamarie.co/	https://www.instagram.com/alisamarie.co/
Hannah Elizabeth Events	Planning		Lancaster	Pennsylvania	Lancaster, Philadelphia and worldwide	Full-service design and management firm led by Hannah Umberger, working on detailed, design-led weddings with a focus on Philadelphia.			https://hannahelizabethevents.com/	https://www.instagram.com/hannahelizabethevents/
Splints & Daisies Floral Design	Florals		Lancaster	Pennsylvania	Lancaster, Central Pennsylvania, Philadelphia, the Mid-Atlantic and the Finger Lakes	Vibrant, whimsical wedding florals built from locally sourced and sustainably grown blooms, with an emphasis on low-waste design.	tara@splintsanddaisies.com	717-379-6087	https://www.splintsanddaisies.com/	https://www.instagram.com/splintsanddaisies/
Custom Florals	Florals	2610 River Road	Conestoga	Pennsylvania	Lancaster and South Central PA	Countryside studio with over 30 years of wedding work, designing bouquets, arches and garlands in styles from vintage to contemporary on most budgets.	mycustomflorals@gmail.com	717-468-5465	https://www.customflorals.com/	https://www.instagram.com/customflorals/
Downtown Sound	Music		Lancaster	Pennsylvania	Central Pennsylvania	Large live party band covering 60s soul to current hits, known for mash-ups and singers who move out onto the dance floor.	lucy@robin-banksentertainment.com	717-609-1154	https://downtown-sound.com/	https://www.instagram.com/d_townsoundband/
DJ Mast Productions	Music		Lancaster	Pennsylvania	Lancaster, Harrisburg, Hershey, York, Philadelphia, Baltimore and destinations	Wedding DJ and MC company with over a decade of event work, adding uplighting, photo booths and backup equipment with no setup fees.	contact@djmast.com	717-951-5221	https://www.djmast.com/	https://www.instagram.com/djmastproductions/
C&J Catering and Events	Catering	903 Spring Garden Drive	Middletown	Pennsylvania	Hershey, Harrisburg, Lancaster, York, Lebanon and Carlisle	Full-service caterer with buffets, plated dinners and carving stations, plus its own bakery for wedding cakes and an in-house floral team.		717-576-1610	https://www.candjcatering.com/	https://www.instagram.com/c_and_j_catering/
Envy Studio	Hair & Makeup	24 W King St	Lancaster	Pennsylvania	Lancaster and on location	Downtown Lancaster salon with a private bridal suite for 16, airbrush makeup and on-site styling for brides, bridesmaids and flower girls.	bridesbyenvy@gmail.com	717-435-9343	https://envystudiolancasterpa.com/services/bridal/	https://www.instagram.com/_envy_studio_/
Abloom Bridal Artistry	Hair & Makeup		Lancaster	Pennsylvania	Lancaster, York and Harrisburg	On-site bridal hair and makeup by Katie Childers, specialising in soft glam, boho braids and romantic updos that hold up all day.	abloombridalartistry@gmail.com		https://www.abloombridalartistry.com/	https://www.instagram.com/abloombridalartistry/
Olive Bridal Hair	Hair & Makeup		Lancaster	Pennsylvania	Lancaster area and beyond	Hair-only bridal team led by Crystal Haynick, offering tiered on-site packages and preview trials, focused only on the wedding party that day.	olivebrideshair@gmail.com		https://www.olivebridalhair.com/	https://www.instagram.com/olivebridalhair/
Bird-in-Hand Bakery & Cafe	Cake	2715 Old Philadelphia Pike	Bird-in-Hand	Pennsylvania	Within 20 miles of the bakery	Family-run Lancaster County bakery making scratch wedding cakes in classic flavours, with fondant flowers and local delivery and setup.		717-768-1501	https://bird-in-hand.com/bakery-cafe/specialty-cakes/	
Wayfinder Films	Videography		Lancaster	Pennsylvania	PA, NJ, MD, NY, NC and nationwide destinations	Wedding film team focused on raw, documentary storytelling that captures how the day felt rather than a staged sequence of events.			https://wayfinderfilms.co/	https://www.instagram.com/wayfinderfilmsco/
Strata Wedding Films	Videography		Lancaster	Pennsylvania	Central PA, Philadelphia, Lehigh Valley, Pittsburgh, New Jersey and worldwide	Owner-led wedding films with cinematic framing, true colour and story-driven dialogue; Tyler films every wedding and caps bookings each year.			https://www.strataweddingfilms.com/	https://www.instagram.com/strataweddingfilms/
Taylor Ann Photography	Photography		Lancaster	Pennsylvania	Pennsylvania and destinations abroad	Film and digital wedding photographer Taylor Mihaljevic, telling queer, nontraditional and adventurous love stories with a candid, joyful eye.			https://taylorannphotography.com/	https://www.instagram.com/taylorannphotography/
3 West Productions	Music	272 Granite Run Drive	Lancaster	Pennsylvania	PA, NJ, NYC, MD, DE and beyond	Entertainment company of touring musicians and DJs, offering wedding DJs, live bands and a band-plus-DJ hybrid shaped around each couple.	info@3westproductions.com	717-368-8305	https://www.3westproductions.com/	https://www.instagram.com/3west_productions/
The Clay House	Catering	1380 Furnace Hill Road	Stevens	Pennsylvania	Lancaster, York and Lebanon counties	Family-owned caterer since 2018 serving handmade buffet dinners, taco bowls, brunch spreads and a coffee bar, with care for dietary needs.	clayhousebnb@gmail.com	717-428-7238	https://www.theclayhousebnb.com/wedding-catering-lancaster-pa	https://www.instagram.com/theclayhousebnb/
Beats and Focus	Photography		Lancaster	Pennsylvania	Lancaster, Philadelphia, Pittsburgh, DC, Baltimore, Delaware, New Jersey and New York	Lancaster wedding team pairing photography with DJ and MC work, videography and a photo booth, so one crew covers several parts of the day.		717-538-0823	https://beatsandfocus.com/	https://www.instagram.com/beatsandfocus/
Burke & Poppy	Planning		Lancaster	Pennsylvania	Pennsylvania	Planning and floral design studio offering partial and full planning, taking a limited number of weddings a year with in-house flowers and rentals.	hello@burkeandpoppy.com		https://burkeandpoppy.com/	https://www.instagram.com/burkeandpoppy/
Meadowbrook Floral Design	Florals		Lancaster	Pennsylvania	Lancaster, York, Harrisburg and beyond in Pennsylvania and Maryland	Garden-inspired wedding florals from owner Laura and her team, using locally grown blooms in whimsical, garden or classic styles.	meadowbrookfloral@gmail.com		https://meadowbrookfloral.com/	https://www.instagram.com/meadowbrookfloral/
Luongo Barbecue	Catering	101 E Main St	Middletown	Pennsylvania	Central Pennsylvania	Family-run Texas pit barbecue, smoked low and slow, catering weddings with brisket, ribs and sides, with tastings at its Middletown restaurant.	luongobbq@gmail.com	717-202-2277	https://luongobbq.com/	https://www.instagram.com/luongobbq/
Oregon Dairy Bake Shoppe	Cake	2900 Oregon Pike	Lititz	Pennsylvania		Farm-market bakery designing custom wedding cakes in many flavours and fillings, now adding gluten-free cakes and mini dessert trays.		717-656-2856	https://www.oregondairy.com/the-bake-shoppe/wedding-cakes	https://www.instagram.com/oregondairy/
Lancaster Cupcake	Cake	260 Granite Run Dr	Lancaster	Pennsylvania		Gourmet cupcake bakery offering wedding cupcakes with a small cutting cake, a bridal sampling four-pack and a cupcake truck for the reception.		717-553-5287	https://www.lancastercupcake.com/weddings	
Rosenberry Media	Videography		Lancaster	Pennsylvania	Central Pennsylvania including Lancaster, Harrisburg, Hershey and Reading	Cinematic, story-led wedding films shot unobtrusively around natural moments, with photography also available from the same team.		717-229-7006	https://www.rosenberrymedia.com/weddingvideography	https://www.instagram.com/rosenberrymedia/`,
  },
  {
    name: "Poconos: photography, videography, music, florals, cake, catering, hair and makeup, bar, rentals and more",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Ever After Studio	Photography	1023 Dancing Ridge Rd	East Stroudsburg	Pennsylvania	Pocono Mountains, Lehigh Valley, Scranton, New Jersey and New York	East Stroudsburg wedding photographer and cinematographer covering Pocono venues, with a trusted team on hand for extra coverage when needed.	info@ever-afterstudio.com	(908) 892-2184	https://www.ever-afterstudio.com/	https://www.instagram.com/everafterstudio/
Renée Dee Photography	Photography	43 North 7th Street	Stroudsburg	Pennsylvania	Stroudsburg and the wider Pocono Mountains	Stroudsburg photographer with a studio, offering relaxed documentary-style coverage for microweddings, elopements, couples and families.	reneedeephotography@gmail.com	(570) 730-5583	https://www.reneedeephotography.com/	https://www.instagram.com/reneedeephotography/
Rob Lettieri Photography	Photography	1610 Wyoming Avenue	Scranton	Pennsylvania	Scranton, Poconos and Wilkes-Barre area	Scranton wedding photographer and filmmaker whose recent work includes weddings at Skytop Lodge, Stroudsmoor Inn and the Scranton Cultural Center.	rob@lettieriphoto.com	570.498.3686	https://www.lettieriphoto.com/	https://www.instagram.com/roblettieriphotography/
Frankie Carll Productions	Music	407 Davis Street	Clarks Summit	Pennsylvania	Poconos, Scranton, Wilkes-Barre, Hazleton, Lehigh Valley, Stroudsburg, Jim Thorpe, Hawley and Honesdale	Clarks Summit firm, established in 1984, offering wedding DJs alongside photography, videography, photo booths and uplighting across northeast Pennsylvania.	fcprod@frankiecarll.com	(570) 587-2740	https://www.frankiecarll.com/	https://www.instagram.com/frankiecarll/
Lucid Lens Films	Videography		Stroudsburg	Pennsylvania	Pocono Mountains, Lehigh Valley, Northeast Pennsylvania and New Jersey	Stroudsburg wedding filmmaker offering unobtrusive, candid films shot in 4K, with drone footage included in every package.	info@lucidlensfilms.com	(570) 580-0744	https://lucidlensfilms.com/	https://www.instagram.com/lucidlensfilms/
That's Groovy Photo Booth	Photo Booth		East Stroudsburg	Pennsylvania	Within about 60 miles of East Stroudsburg, including the Poconos, Scranton, Easton and Allentown	East Stroudsburg booth hire for weddings, with open-air, magic mirror and 360 options plus props and backdrops.	info.tg.photobooth@gmail.com	(570) 844-0111	https://thatsgroovyphotobooth.com/	https://www.instagram.com/thatsgroovyphotobooth/
Lois Heckman - Celebrant	Officiant		Saylorsburg	Pennsylvania	Pocono Mountain resorts and the Harmony Gardens ceremony site	Humanist celebrant who writes personal secular, spiritual or interfaith wedding and elopement ceremonies in the Poconos.		570-350-9514	http://www.loisheckman.com/	
Karla's Garden Studio	Florals	337 Poplar Valley Rd W	Stroudsburg	Pennsylvania	Stroudsburg, surrounding communities and the Slate Belt	Full-service floral studio in Stroudsburg designing wedding and event flowers, with delivery across the town and the Slate Belt.	karlasgardenstudio@gmail.com	570-234-3353	https://www.karlasgardenstudio.com	https://www.instagram.com/karlasgardenstudio/
Imaginations Florals & More by Ally	Florals	272 Learn Rd	Tannersville	Pennsylvania		Tannersville flower shop creating wedding flowers alongside everyday arrangements, gifts and plants for the local area.		(570) 620-2680	https://www.imaginationsfloralsnmore.com	https://www.instagram.com/imaginationsfloralsnmore_ally/
Gorgeous Floral	Florals		Hawley	Pennsylvania		Hawley florist offering wedding floral packages as well as flower subscriptions, houseplants and celebration arrangements.			https://www.gorgeous-floral.com	https://www.instagram.com/gorgeousfloralpa/
Sonia's Sweet Inspirations	Cake	110 N 9th Street	Stroudsburg	Pennsylvania		Stroudsburg bakery making custom wedding cakes, tiered designs and 3D novelty cakes, with a shop open Tuesday to Saturday.		(570) 664-6686	https://www.soniassweetinspirations.com	
Just Like Magic Bakery	Cake	727 Main Street	Stroudsburg	Pennsylvania		Stroudsburg bakery making custom wedding cakes, alongside cupcakes, cookies, macarons and dessert bars for weddings and special events.		(570) 872-0132	https://www.justlikemagicbakery.com	https://www.instagram.com/justlikemagicbakery_/
The Willowtree Inn	Catering	601 Ann St	Stroudsburg	Pennsylvania		Stroudsburg restaurant providing on- and off-site catering for wedding receptions, showers and other private celebrations.		570-476-0211	https://thewillowtreeinn.net	https://www.instagram.com/willowtreeinnrestaurant/
Latin Kitchen Catering	Catering		Tobyhanna	Pennsylvania	Within 30 minutes of Mount Pocono, extending to New York and New Jersey	Wedding caterer offering restaurant-style table service and flexible menus spanning Latin, Italian, Southern and American dishes.	Latinkitchencateringpa@gmail.com	570-580-9493	https://latinkitchencatering.com	https://www.instagram.com/latin_kitchen_catering/
Barley Creek Catering	Catering	1774 Sullivan Trail	Tannersville	Pennsylvania	Poconos region and beyond	Brewery-based caterer offering full-service catering at its venues or mobile kitchen catering, plus an Airstream mobile bar.		570-629-9399	https://www.barleycreek.com	https://www.instagram.com/barleycreekbrewing/
Fairview Catering	Catering	2016 Lehigh Ave	Whitehall	Pennsylvania	Lehigh Valley and Poconos	Caterer using mobile food units to cook fresh on site for weddings and banquets across the Lehigh Valley and Poconos.	twistedsistersscheduling@gmail.com	(484) 522-8307	https://fairviewcatering.com	
On The Rocks Mobile Bar	Bar		Milanville	Pennsylvania	Within 50 miles of zip code 18443	Dry-hire mobile bar with insured, RAMP-certified bartenders for weddings and private events, priced by package length.			https://mobilebarontherocks.com	https://www.instagram.com/mobilebar_ontherocks/
Hausbar	Bar		Bethlehem	Pennsylvania	Lehigh Valley, Poconos, Philadelphia and surrounding areas	Cocktail bar service with RAMP-certified bartenders and a portable bar, for hosts who supply their own alcohol at weddings.	info@hausbar.us	+1-484-809-6109	https://www.hausbar.us	https://www.instagram.com/hausbar.us/
SOUNDBAR Entertainment	Music		Saylorsburg	Pennsylvania	Poconos, Scranton, Lehigh Valley, NEPA	Wedding DJ based in Saylorsburg who takes one event per day, covering ceremony sound and receptions across the Poconos, Scranton and Lehigh Valley.	info@soundbardjs.com	(570) 520-2050	https://soundbardjs.com	https://www.instagram.com/soundbardjs/
DJ Johnny Johnson	Music		Sciota	Pennsylvania	Poconos, Lehigh Valley, Scranton, NEPA, northern and central New Jersey	Sciota-based wedding DJ offering four to six hour packages with custom playlists, MC duties and optional photo booth and uplighting add-ons.		570-402-1133	https://djjohnnyjohnson.com	
Penn Strings	Music		East Stroudsburg	Pennsylvania	Poconos and northeastern Pennsylvania	East Stroudsburg string ensemble playing classical and pop arrangements for weddings and events, with musicians and repertoire tailored to each couple.	pennstrings@gmail.com	(570) 604-5226	https://www.pennstrings.com	https://www.instagram.com/pennstringsrocks/
Oath Hair Studio & Spa	Hair & Makeup	96 South Courtland Street	East Stroudsburg	Pennsylvania	East Stroudsburg and the Poconos	East Stroudsburg salon and spa offering cuts, colour, extensions and spa treatments, plus bridal hair including trials ahead of the wedding.		(570) 534-0088	https://oathhairstudio.com	https://www.instagram.com/oathhairstudio/
La'Ren Hair Studio	Hair & Makeup	239 Fox Run Lane, Suite 3	East Stroudsburg	Pennsylvania	East Stroudsburg and the Poconos	East Stroudsburg hair studio known for colour and extensions, also styling updos and bridal hair with trial runs before the wedding.		(570) 630-0659	https://larenhairstudio.com	https://www.instagram.com/larenhairstudio/
11:11 Event Rentals	Rentals	118 Highland Avenue	Clarks Summit	Pennsylvania	Poconos incl. Tannersville, White Haven, Gouldsboro, Cresco; Scranton area	Family-run rental company delivering tents, tables, chairs, dance floors and decor to Poconos weddings, with setup included and no hidden labour fees.		(272) 228-0720	https://eleveneventrentals.com	https://www.instagram.com/1111_eventrentals/
Metz Amusements and Concessions	Rentals	6428 Sullivan Trail	Wind Gap	Pennsylvania	Stroudsburg, East Stroudsburg and northeast Pennsylvania	Wind Gap rental firm supplying tents up to 80 by 300 feet, tables, chairs and lighting for weddings in Stroudsburg, East Stroudsburg and nearby.	info@metzamusements.com	610-863-4914	https://metzamusements.com	
Elite Rides Limo Service	Transportation		Stroudsburg	Pennsylvania	Stroudsburg, Poconos and Lehigh Valley	Owner-operated Stroudsburg limousine service focused on weddings, with a 2024 Sprinter van and more than 25 years of experience.		570-817-7070	https://www.goeliterides.com	https://www.instagram.com/goeliterides/
Luxury Limousine Service	Transportation	8 Apollo Dr.	West Wyoming	Pennsylvania	Northeast Pennsylvania and Poconos incl. Monroe County	Independent West Wyoming operator since 1989, providing wedding limousines and party buses for events across northeast Pennsylvania and the Poconos.	info@luxurylimo.com	(570) 823-5233	https://luxurylimo.com	https://www.instagram.com/luxurylimo/
POSH Life Floral	Decor & Lighting	401 Jefferson Avenue	Scranton	Pennsylvania	Scranton and northeast Pennsylvania	Scranton floral and event design team offering installations, custom decor pieces and lighting such as uplighting and pin spotting for weddings.			https://poshscranton.com	
Elegant Bridal Boutique	Bridal & Formalwear	106 Plaza 611 Lane	Stroudsburg	Pennsylvania	Stroudsburg, Tannersville and the Poconos	Stroudsburg bridal shop open since 1990, selling wedding, bridesmaid and mother-of-the-bride gowns with spacious fitting rooms and styling help.	elegantbridalboutique@yahoo.com	(570) 688-9594	https://www.elegantbridalboutique.net	
  },
];

export default batches;
