import type { VendorBatch } from "@/lib/vendor-batches";

// Rhode Island vendor batches. Every row's State is "Rhode Island". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Providence and Newport: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Hilary Block Photography	Photography		Newport	Rhode Island	New England, Block Island and worldwide	Fine-art wedding photographer in Newport since 2009, blending analogue film with digital in a natural, emotive style.	info@hilarybphotography.com	401-667-7897	https://hilarybphotography.com	https://www.instagram.com/hilarybphotography/
Move Mountains Co.	Photography	28 Wolcott St	Providence	Rhode Island	New England and the East Coast	Providence photo and film studio offering several curated photo styles, Super 8 film, live streaming and a photo booth under one roof.	info@movemountains.co	401-373-4500	https://movemountains.co	https://www.instagram.com/movemountainsco/
Mark B. Carrier Photography	Photography		Smithfield	Rhode Island		Candid Smithfield wedding photographer focused on honest, unposed moments, stepping in with direction only when couples need it.	hello@markbcarrier.photography	(401) 405-1768	https://www.markbcarrier.photography	https://www.instagram.com/mbcarrier_photography/
Sweet Deets Events	Planning		Newport	Rhode Island	Newport and New England	Newport planning and design studio offering full planning, coordination and design services, now booking 2027 weddings.			https://www.sweetdeetsevents.com	https://www.instagram.com/sweetdeetsevents/
Dana Marie Weddings & Events	Planning		Newport	Rhode Island	Newport, Block Island, Cape Cod and New England	Newport planner with an event management degree, offering full and partial planning, day-of coordination and micro-weddings.	hello@danamarieweddings.com	203.824.0393	https://www.danamarieweddings.com	https://www.instagram.com/danamarie_weddings/
AMC Weddings	Planning	62 Thames St	Newport	Rhode Island	Newport and destination weddings	Full-service planning and design firm with a Thames Street office in Newport, handling local and destination weddings start to finish.	hello@amcweddings.com	(401) 374-9518	https://www.amcweddings.com	https://www.instagram.com/amc.weddings/
Greenlion Design	Florals		Newport	Rhode Island	Rhode Island and beyond	Newport floral studio run by a two-person team, working foam-free, composting afterwards and creating art-led installations.			https://www.greenliondesign.com	https://www.instagram.com/greenlionri/
Stoneblossom	Florals	79 Joyce St	Warren	Rhode Island	East Coast destinations	By-appointment floral and event design house in Warren creating individually tailored arrangements for destination weddings.		401.884.3220	https://www.stoneblossomflorals.com	https://www.instagram.com/stoneblossom/
Sayles Livingston Design	Florals	3855 Main Rd	Tiverton	Rhode Island	Nationwide and international	Tiverton floral and event design firm that also handles linens, lighting and props, sources unusual stems and donates flowers after events.		401-635-9500	https://sayleslivingstondesign.com	https://www.instagram.com/sayleslivingstondesign/
DownCity Band	Music		Providence	Rhode Island	Rhode Island and Newport County	Eight-piece Providence party band covering blues, country, Motown, pop and hip-hop, learning requested songs and handling MC duties.		401-268-7385	https://www.downcityband.com	
Dee Jays Etc	Music		Warwick	Rhode Island	Rhode Island, Connecticut and southern New England	Warwick DJ Sidney has played weddings since 1998, takes one wedding a day and keeps microphone chatter low-key.		(401) 859-5072	https://www.deejaysetc.com	https://www.instagram.com/deejaysetc/
Rhythm Express Disc Jockey Service	Music		Bristol	Rhode Island	Rhode Island, Massachusetts and Cape Cod	Bristol DJ and MC service of over 25 years, pairing wedding sets with custom uplighting packages and a seasonal Cape Cod base.		401-254-1519	https://www.rhythmexpressdj.net	https://www.instagram.com/rhythmexpressdj/
Blackstone Caterers	Catering	224 John Clarke Rd	Middletown	Rhode Island	Newport and Rhode Island	Middletown caterer focused on Newport's mansions and larger venues, writing seasonal menus around quality regional ingredients.	info@blackstonecaterers.com	401-848-2030	https://www.blackstonecaterers.com	https://www.instagram.com/blackstoneri/
McGrath Clambakes & Catering	Catering	64 Halsey St	Newport	Rhode Island	Southern New England	Newport caterer of over 50 years serving traditional New England clambakes alongside full, customised wedding menus.	info@riclambake.com	401.847.7743	https://www.riclambake.com	https://www.instagram.com/mcgrathclambakes/
401 Gourmet	Catering	560 Mineral Spring Ave	Pawtucket	Rhode Island		Licensed Pawtucket wedding and event caterer with customisable menus, voted RI Monthly's best caterer in 2022 and 2025.	info@401gourmet.com	401-429-3946	https://www.401gourmet.com	https://www.instagram.com/401gourmet/
BellaBeauty Bridal	Hair & Makeup	42 Spring St	Newport	Rhode Island	New England, including Newport and Cape Cod	Newport bridal hair and makeup team with over 30 years' experience, working in its Spring Street studio or on site.			https://www.bellabeautybridal.com	https://www.instagram.com/bellabeautybridal/
Curl Up and Dye	Hair & Makeup	2 Pond Ave	Newport	Rhode Island	Newport	Inclusive Newport salon open since 2005, with a dedicated bridal team offering wedding hair and makeup packages.	curlupanddyenewport@gmail.com	401-619-1955	https://www.curlupanddyenewport.com	https://www.instagram.com/curlupanddyeweddingsri/
Ali Lomazzo Beauty	Hair & Makeup	289 Bullocks Point Ave	Riverside	Rhode Island		Riverside bridal hair and makeup studio founded in 2013, known for timeless, long-wearing looks that last through the night.			https://www.alilomazzobeauty.com	https://www.instagram.com/ali_lomazzo_beauty/
Silver Spoon Bakery	Cake	58 Main St	East Greenwich	Rhode Island	Rhode Island	East Greenwich bakery making wedding cakes, cupcakes, macarons and favours, delivered and set up on its own stands.	contact@silverspoonbakery.com	(401) 384-0078	https://www.silverspoonbakery.com/weddings	https://www.instagram.com/silverspoonbakery/
Wright's Dairy Farm & Bakery	Cake	200 Woonsocket Hill Rd	North Smithfield	Rhode Island	Within an hour of North Smithfield	Family dairy farm bakery working since 1914, baking tiered wedding cakes and delivering within an hour's drive.	info@wrightsdairyfarm.com	401-767-3014	https://www.wrightsri.com/weddings-and-events	https://www.instagram.com/wrightsbakeryri/
Mike Picard Motion Pictures	Videography	3650 Diamond Hill Rd	Cumberland	Rhode Island	Rhode Island, Massachusetts, Connecticut and New England	Cumberland studio making cinematic wedding films that aim to capture how the day felt, not just how it looked.	mike@mikepicard.com	401.827.8056	https://www.mikepicard.com	https://www.instagram.com/mpmotionpictures/
Artistic Wedding Films	Videography	174 Bellevue Ave, Suite 220	Newport	Rhode Island	The Northeast and destination weddings	Newport cinematography studio on Bellevue Avenue producing highlight, feature and same-day-edit films with aerial footage.	info@artisticweddingfilms.com	877-819-0923	https://www.artisticweddingfilms.com	https://www.instagram.com/artisticweddingfilms/
Steve Levin Cinematography	Videography		South Kingstown	Rhode Island	Rhode Island, Massachusetts and Connecticut	Documentary-style South Kingstown filmmaker shooting 4K and drone footage, drawing on years as a film camera assistant.		1-401-474-8061	https://www.stevelevincinematography.com	https://www.instagram.com/stevelevincinematography/
Sin Desserts	Cake	1413 Westminster St	Providence	Rhode Island	Rhode Island and nearby areas	Providence custom cake studio with artistic wedding designs and dedicated gluten-free and vegan tasting flights.	info@eatwicked.com	(401) 369-8427	https://www.eatwicked.com/wedding-cakes/	https://www.instagram.com/sindesserts/`,
  },
];

export default batches;
