import type { VendorBatch } from "@/lib/vendor-batches";

// South Carolina vendor batches. Every row's State is "South Carolina". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Charleston: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Chrisman Studios	Photography	2681 Spruill Ave	North Charleston	South Carolina	Charleston metro and destination weddings	Husband-and-wife photography team working since 2005 from a high-ceilinged studio in a former Navy building.	info@chrismanstudios.com	843-410-3076	https://www.chrismanstudios.com/	https://www.instagram.com/chrismanstudios/
Jolie Connor Photography	Photography		Charleston	South Carolina	Charleston and surrounding areas; travels nationally	Bright, editorial-leaning wedding photography with coached romantic portraits, drawing on more than 300 weddings shot so far.			https://www.jolieconnorphotography.com/	https://www.instagram.com/jolieconnorphotography/
Dana Cubbage Weddings	Photography	354 Huger St	Charleston	South Carolina	Charleston, the Lowcountry and destination weddings	Colourful, classic wedding photography from a Charleston studio, with a second lead shooter as standard and film options on request.	info@danacubbageweddings.com	(843) 410-3236	https://www.danacubbageweddings.com/	https://www.instagram.com/danacubbageweddings/
The Coordination Company	Planning		Charleston	South Carolina	Charleston and the Lowcountry	Design-minded planning team offering full planning, partial planning and wedding management for couples wanting a personal celebration.	kate@thecoordinationcompany.com		https://www.thecoordinationcompany.com/	https://www.instagram.com/thecoordinationcompany/
Peper Events	Planning		Charleston	South Carolina		Coordination and partial planning for practical couples, run by a team of lead planners who start from day-of management upwards.	erica@peperevents.com	(843) 847-1607	https://www.peperevents.com/	https://www.instagram.com/peper.events/
Charleston Elopement Packages	Planning		Charleston	South Carolina	Charleston and surrounding locations	Local elopement planners bundling officiant, photography and hair and makeup into themed packages for up to a dozen guests.	charlestonelopements@gmail.com		https://www.charlestonelopementpackages.com/	https://www.instagram.com/charlestonelopepackages/
Tiger Lily Weddings	Florals	1614 Camp Rd	Charleston	South Carolina	Charleston and the Lowcountry	Long-running Charleston florist with a James Island design studio, known for coastal palettes from classic blue-and-white to bright pinks.	contact@tigerlilyflorist.com	843.723.2808	https://www.tigerlilyweddings.com/	https://www.instagram.com/tigerlilyweds/
Branch Flower Shop	Florals	1113 Bowman Rd Suite 101	Mount Pleasant	South Carolina	Charleston and Mount Pleasant	Mount Pleasant flower shop and design studio creating garden-style wedding and event florals alongside everyday arrangements.	info@branchflowershop.com	843-847-7996	https://www.branchflowershop.com/	https://www.instagram.com/branchflowershop/
CC Bloom Florals & Events	Florals		Mount Pleasant	South Carolina	Charleston area	Locally owned florist building garden-style wedding work with roses, ranunculus and hydrangea, from small gatherings to large parties.	events@ccbloomflorals.com		https://www.ccbloomflorals.com/	
Lowcountry Entertainment	Music		Charleston	South Carolina		Charleston wedding DJ and MC company that can also handle lighting, café lights and draping for the reception space.	hello@lowcountryentertainment.com	(843) 343-9515	https://www.lowcountryentertainment.com/	https://www.instagram.com/lowcountryentertainment/
Lowcountry Strings	Music		Charleston	South Carolina	Charleston area including Kiawah Island	Ceremony strings run by guitarist Bob Williams, offering solo, duo, trio and jazz line-ups with Charleston Symphony players and officiant mics.	bob@lowcountrystrings.com	843-557-6360	https://www.lowcountrystrings.com/	https://www.instagram.com/bobwilliamsguitar/
The Vistas Band	Music		Charleston	South Carolina	Charleston; travels across the Southeast	Charleston reception band built around vocals, piano and saxophone, playing a mix of classic dance-floor songs and current hits.	TheVistas@live.com	843-200-0772	https://www.thevistasband.com/	https://www.instagram.com/thevistasband/
Hamby Catering & Events	Catering	909 St Andrews Blvd	Charleston	South Carolina	Charleston and the Lowcountry	Family-run caterer since 1979 cooking Lowcountry menus, with bar service, décor help and its own Rutledge Room event space.		843-571-3103	https://www.hambycatering.com/	https://www.instagram.com/hambycatering/
Carolima's Lowcountry Cuisine	Catering	2408 Ashley River Rd, Suite C	Charleston	South Carolina	Charleston and surrounding areas	Sister-run Gullah Geechee caterer serving okra soup, red rice, garlic crabs and other heritage dishes, full-service or drop-off.	carolimasc@gmail.com	843-900-4467	https://www.carolimas.com/	https://www.instagram.com/carolimasc/
Cru Catering	Catering	1784 Harmon St	Charleston	South Carolina		Long-standing Charleston caterer cooking customised menus fresh on site for weddings and private parties, backed by a full service team.	info@crucatering.com	843.534.2433	https://www.crucatering.com/	https://www.instagram.com/crucatering/
Charleston I Do	Hair & Makeup		Charleston	South Carolina	Greater Charleston and the Lowcountry	On-location bridal styling team favouring fresh, natural looks, with airbrush makeup, lashes and veil placement in the bridal package.	charlestonido@gmail.com		https://www.charlestonido.com/	https://www.instagram.com/charlestonido/
Silhouette On Site	Hair & Makeup		Charleston	South Carolina	Charleston	On-site hair, airbrush makeup and lash team that matches each bride to an artist, with a getting-ready suite at Faber House.			https://silhouetteonsite.com/	https://www.instagram.com/silhouetteonsite/
Vanity Salon & Blowout Bar	Hair & Makeup	1903 N Highway 17, Suite 100	Mount Pleasant	South Carolina		Mount Pleasant salon whose hair and makeup artists style brides and wedding parties, with blowouts and makeup offered in the studio.		843.216.7181	https://www.vanitysalonsc.com/	https://www.instagram.com/vanitysalonsc/
Spilled Milk Cake Boutique	Cake		Charleston	South Carolina	Charleston and surrounding areas	Wedding cake studio run by baker Alex Kowaleski, known for clean shapes, soft colours and refined piping on modern romantic designs.	alex@spilledmilkcake.com		https://www.spilledmilkcakeboutique.com/	https://www.instagram.com/spilledmilkcake/
Gala Cafe & Bakery	Cake	123 Pitt St	Mount Pleasant	South Carolina		European-style café and bakery in an old Mount Pleasant house, making custom wedding and event cakes in a range of flavours.	galadesserts@gmail.com	(854) 227-5723	https://www.galadesserts.com/	https://www.instagram.com/galadesserts/
Ashley Bakery	Cake	1662 Savannah Highway, Suite 200	Charleston	South Carolina		West Ashley bakery decorating wedding cakes since 1988, from classic piped designs to modern looks, with six-flavour tasting boxes.	info@ashleybakery.com	843-763-4125	https://www.ashleybakery.com/	https://www.instagram.com/ashleybakery/
Dock House Digital	Videography		Charleston	South Carolina		Cinematic wedding films from filmmaker Drew, a Global Wedding Film Awards nominee, offering long-day coverage and extra shooters.	drew@dockhousedigital.com	(843) 743-3555	https://www.dockhousedigital.com/	https://www.instagram.com/dockhousedigital/
Palmetto Wedding Films	Videography		Charleston	South Carolina	Charleston	Charleston filmmaker Jessie Smith blends documentary honesty with cinematic technique, keeping true-to-colour tones and filming discreetly.			https://www.palmettoweddingfilms.com/	https://www.instagram.com/palmettoweddingfilms/
Five25Films	Videography		Charleston	South Carolina	Charleston, the Carolinas and destinations	Charleston wedding film studio cutting emotive, music-led films with slow motion and natural light, from coastal islands to Carolina manors.			https://www.five25films.com/	https://www.instagram.com/five25films/`,
  },
];

export default batches;
