import type { VendorBatch } from "@/lib/vendor-batches";

// South Carolina vendor batches. Every row's State is "South Carolina". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Charleston: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Chrisman Studios	Photography	2681 Spruill Ave	North Charleston	South Carolina	Charleston metro and destination weddings	Husband-and-wife photography team working since 2005 from a high-ceilinged studio in a former Navy building.	info@chrismanstudios.com	843-410-3076	https://www.chrismanstudios.com/	https://www.instagram.com/chrismanstudios/
Jolie Connor Photography	Photography		Charleston	South Carolina	Charleston and surrounding areas; travels nationally	Bright, editorial-leaning wedding photography with coached romantic portraits, drawing on more than 300 weddings shot so far.			https://www.jolieconnorphotography.com/	https://www.instagram.com/jolieconnorphotography/
Dana Cubbage Weddings	Photography	354 Huger St	Charleston	South Carolina	Charleston, the Lowcountry and destination weddings	Colourful, classic wedding photography from a Charleston studio, with a second lead shooter as standard and film options on request.	info@danacubbageweddings.com	(843) 410-3236	https://www.danacubbageweddings.com/	https://www.instagram.com/danacubbageweddings/
The Coordination Company	Planning		Charleston	South Carolina	Charleston and the Lowcountry	Design-minded planning team offering full planning, partial planning and wedding management for couples wanting a personal celebration.	kate@thecoordinationcompany.com		https://www.thecoordinationcompany.com/	https://www.instagram.com/thecoordinationcompany/
Peper Events	Planning		Charleston	South Carolina		Coordination and partial planning for practical couples, run by a team of lead planners who start from day-of management upwards.	erica@peperevents.com	(843) 847-1607	https://www.peperevents.com/	https://www.instagram.com/peper.events/
Charleston Elopement Packages	Planning		Charleston	South Carolina	Charleston and surrounding locations	Local elopement planners bundling officiant, photography and hair and makeup into themed packages for up to a dozen guests.	charlestonelopements@gmail.com		https://www.charlestonelopementpackages.com/	https://www.instagram.com/charlestonelopepackages/
Tiger Lily Weddings	Florals	1614 Camp Rd	Charleston	South Carolina	Charleston and the Lowcountry	Long-running Charleston florist with a James Island design studio, known for coastal palettes from classic blue-and-white to bright pinks.	contact@tigerlilyflorist.com	843.723.2808	https://www.tigerlilyweddings.com/	https://www.instagram.com/tigerlilyweds/
Branch Flower Shop	Florals	1113 Bowman Rd Suite 101	Mount Pleasant	South Carolina	Charleston and Mount Pleasant	Mount Pleasant flower shop and design studio creating garden-style wedding and event florals alongside everyday arrangements.	info@branchflowershop.com	843-847-7996	https://www.branchflowershop.com/	https://www.instagram.com/branchflowershop/
CC Bloom Florals & Events	Florals		Mount Pleasant	South Carolina	Charleston area	Locally owned florist building garden-style wedding work with roses, ranunculus and hydrangea, from small gatherings to large parties.	events@ccbloomflorals.com		https://www.ccbloomflorals.com/	
Lowcountry Entertainment	Music		Charleston	South Carolina		Charleston wedding DJ and MC company that can also handle lighting, café lights and draping for the reception space.	hello@lowcountryentertainment.com	(843) 343-9515	https://www.lowcountryentertainment.com/	https://www.instagram.com/lowcountryentertainment/
Lowcountry Strings	Music		Charleston	South Carolina	Charleston area including Kiawah Island	Ceremony strings run by guitarist Bob Williams, offering solo, duo, trio and jazz line-ups with Charleston Symphony players and officiant mics.	bob@lowcountrystrings.com	843-557-6360	https://www.lowcountrystrings.com/	https://www.instagram.com/bobwilliamsguitar/
The Vistas Band	Music		Charleston	South Carolina	Charleston; travels across the Southeast	Charleston reception band built around vocals, piano and saxophone, playing a mix of classic dance-floor songs and current hits.	TheVistas@live.com	843-200-0772	https://www.thevistasband.com/	https://www.instagram.com/thevistasband/
Hamby Catering & Events	Catering	909 St Andrews Blvd	Charleston	South Carolina	Charleston and the Lowcountry	Family-run caterer since 1979 cooking Lowcountry menus, with bar service, décor help and its own Rutledge Room event space.		843-571-3103	https://www.hambycatering.com/	https://www.instagram.com/hambycatering/
Carolima's Lowcountry Cuisine	Catering	2408 Ashley River Rd, Suite C	Charleston	South Carolina	Charleston and surrounding areas	Sister-run Gullah Geechee caterer serving okra soup, red rice, garlic crabs and other heritage dishes, full-service or drop-off.	carolimasc@gmail.com	843-900-4467	https://www.carolimas.com/	https://www.instagram.com/carolimasc/
Cru Catering	Catering	1784 Harmon St	Charleston	South Carolina		Long-standing Charleston caterer cooking customised menus fresh on site for weddings and private parties, backed by a full service team.	info@crucatering.com	843.534.2433	https://www.crucatering.com/	https://www.instagram.com/crucatering/
Charleston I Do	Hair & Makeup		Charleston	South Carolina	Greater Charleston and the Lowcountry	On-location bridal styling team favouring fresh, natural looks, with airbrush makeup, lashes and veil placement in the bridal package.	charlestonido@gmail.com		https://www.charlestonido.com/	https://www.instagram.com/charlestonido/
Silhouette On Site	Hair & Makeup		Charleston	South Carolina	Charleston	On-site hair, airbrush makeup and lash team that matches each bride to an artist, with a getting-ready suite at Faber House.			https://silhouetteonsite.com/	https://www.instagram.com/silhouetteonsite/
Vanity Salon & Blowout Bar	Hair & Makeup	1903 N Highway 17, Suite 100	Mount Pleasant	South Carolina		Mount Pleasant salon whose hair and makeup artists style brides and wedding parties, with blowouts and makeup offered in the studio.		843.216.7181	https://www.vanitysalonsc.com/	https://www.instagram.com/vanitysalonsc/
Spilled Milk Cake Boutique	Cake		Charleston	South Carolina	Charleston and surrounding areas	Wedding cake studio run by baker Alex Kowaleski, known for clean shapes, soft colours and refined piping on modern romantic designs.	alex@spilledmilkcake.com		https://www.spilledmilkcakeboutique.com/	https://www.instagram.com/spilledmilkcake/
Gala Cafe & Bakery	Cake	123 Pitt St	Mount Pleasant	South Carolina		European-style café and bakery in an old Mount Pleasant house, making custom wedding and event cakes in a range of flavours.	galadesserts@gmail.com	(854) 227-5723	https://www.galadesserts.com/	https://www.instagram.com/galadesserts/
Ashley Bakery	Cake	1662 Savannah Highway, Suite 200	Charleston	South Carolina		West Ashley bakery decorating wedding cakes since 1988, from classic piped designs to modern looks, with six-flavour tasting boxes.	info@ashleybakery.com	843-763-4125	https://www.ashleybakery.com/	https://www.instagram.com/ashleybakery/
Dock House Digital	Videography		Charleston	South Carolina		Cinematic wedding films from filmmaker Drew, a Global Wedding Film Awards nominee, offering long-day coverage and extra shooters.	drew@dockhousedigital.com	(843) 743-3555	https://www.dockhousedigital.com/	https://www.instagram.com/dockhousedigital/
Palmetto Wedding Films	Videography		Charleston	South Carolina	Charleston	Charleston filmmaker Jessie Smith blends documentary honesty with cinematic technique, keeping true-to-colour tones and filming discreetly.			https://www.palmettoweddingfilms.com/	https://www.instagram.com/palmettoweddingfilms/
Five25Films	Videography		Charleston	South Carolina	Charleston, the Carolinas and destinations	Charleston wedding film studio cutting emotive, music-led films with slow motion and natural light, from coastal islands to Carolina manors.			https://www.five25films.com/	https://www.instagram.com/five25films/`,
  },
  {
    name: "Greenville: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Davey Morgan Photography	Photography		Greenville	South Carolina	Greenville area; travels nationally and internationally	Husband-and-wife photography team with 300+ weddings behind them, known for bright, vivid colour and relaxed, joyful candids.	info@daveymorgan.com	864-378-2248	https://daveymorgan.com	https://www.instagram.com/daveymorgan/
Markie Walden Photography	Photography		Greenville	South Carolina	Southeast; domestic and international travel	Luxury wedding and portrait photographer working between Greenville and Charleston, with a soft, editorial style suited to destination days.			https://www.markiewalden.com	https://www.instagram.com/markiewaldenphoto/
Simple Stems	Florals		Greenville	South Carolina	Upstate South Carolina	Artist-run flower studio founded by two art-school friends over 20 years ago, designing garden-style wedding and event florals across the Upstate.	simplestemsflorist@gmail.com	864.979.2602	https://simplestems.com	https://www.instagram.com/simplestems/
Social Events & Design	Planning		Greenville	South Carolina	Greenville	Greenville planning and design studio led by Jessica Innes, who brings a decade of festival and corporate event work to weddings.	jessica@socialeventsanddesign.com	864.735.7125	https://socialeventsanddesign.com	https://www.instagram.com/social.events.design/
Twigs	Florals		Greenville	South Carolina	Greenville	Family-owned Greenville florist and home shop since 1988, offering wedding consultations and designs from stems sourced direct from farms.			https://www.twigs.net/pages/wedding-consult	https://www.instagram.com/twigsgreenville/
B&R Events	Planning		Greenville	South Carolina	Greenville region	Greenville planning and design firm led by Samantha Benamati Moss, offering full planning, design and wedding-day coordination.	coordinator@bandreventssc.com	864-420-1398	https://bandreventssc.com	https://www.instagram.com/breventssc/
Bo Stegall The Salon	Hair & Makeup	703 Wade Hampton Boulevard	Greenville	South Carolina	Greenville; travel available	Wade Hampton Boulevard salon whose team styles bridal hair and makeup on location or in-salon, from soft glam to full glam for whole parties.	Bo@BoStegall.com	864-232-4446	https://bostegall.com/bridal	https://www.instagram.com/bostegallthesalon/
Premiere Party Entertainment	Music	1200 Woodruff Road, Suite F5	Greenville	South Carolina	Greenville, Charleston, Columbia and Asheville	Woodruff Road DJ and MC company also offering photo booths, live musicians and effects such as cold-spark fountains for receptions.	hello@ppedjs.com	(864) 884-3419	https://www.ppedjs.com	https://www.instagram.com/ppedjs/
Southern Couture Makeup	Hair & Makeup		Greenville	South Carolina	On-site and in-salon	Greenville hair and makeup artists working on site or in their salon since 2015, creating looks for brides of every cultural background.	southerncouturemakeup@gmail.com	864-559-0460	https://southerncouturemakeup.com	https://www.instagram.com/southerncouturemakeup/
Laurenda's Family Restaurant & Catering	Catering	300 South Line Street	Greer	South Carolina	Greer, Greenville, Spartanburg, Lyman, Duncan, Easley and Anderson	Family restaurant in Greer cooking scratch-made Southern food since 1993, catering wedding receptions with complimentary tastings.		(864) 848-3012	https://laurendascatering.com	https://www.instagram.com/laurendascatering/
Table 301 Catering	Catering	68 Global Drive	Greenville	South Carolina	Greenville	Catering arm of the Table 301 restaurant group, cooking custom wedding menus in Greenville for over 20 years, plus a food truck.	catering@table301.com	864.271.8431	https://table301catering.com	
White Wine & Butter	Catering	2299 E Gap Creek Rd	Greer	South Carolina	Greenville, Greer and upstate South Carolina	Louisiana-inspired Greer restaurant whose chef caters weddings of 20 to 500 with plated dinners, action stations and graze tables.	booking@whitewineandbutter.com	(864) 417-4106	https://whitewineandbutter.com/weddings	https://www.instagram.com/whitewine_butter/
SoundChoice DJ	Music	1200 Woodruff Rd, Ste A-18	Greenville	South Carolina	Upstate SC, Asheville, Hendersonville and Columbia	Greenville DJ and MC team with published packages, ceremony sound, LED uplighting and a planner for each part of the reception.		(864) 209-1030	https://soundchoicedjs.com	https://www.instagram.com/soundchoicedj/
Couture Cakes of Greenville	Cake	1325 Miller Road, Suite H	Greenville	South Carolina	Greenville and beyond	Miller Road cake shop founded over 20 years ago, designing fully custom wedding and groom's cakes after one-to-one consultations.	hello@couturecakesofgreenville.com	(864) 288-6610	https://couturecakesofgreenville.com	https://www.instagram.com/couturecakesofgreenville/
Southern Luxury Cakes	Cake		Greenville	South Carolina		Greenville bakery making custom wedding cakes, groom's cakes, dessert bars and faux tiers, with buttercream cakes for 100 from $850.	southernluxurycakes@gmail.com	(864) 386-6610	https://southernluxurycakes.com	https://www.instagram.com/southernluxurycakes/
Butter Bunny Bakery	Cake		Greenville	South Carolina		Bespoke wedding cakes from a former interior designer turned sugar artist, drawing on her grandmothers' recipes, plus dessert tables.	hello@butterbunnybakery.com	(864) 832-2253	https://butterbunnybakery.com	https://www.instagram.com/butterbunnygreenville/
Weaver Films and Photography	Videography		Greenville	South Carolina	South Carolina and international destinations	Women-owned Greenville studio run by filmmakers Jen and Kayla, offering wedding films and photography separately or as a pair.	hello@weaverfilmsandphotography.com	864-625-0498	https://weaverfilmsandphotography.com	https://www.instagram.com/weaverfilmsandphoto/
Smithalee Weddings	Videography	1875 Hayne Street	Spartanburg	South Carolina	Spartanburg, Greenville, Charlotte, Atlanta; travels worldwide	Spartanburg studio founded by Smitha Lee whose team of creators films and photographs weddings, at home in the Upstate or abroad.	info@smithalee.com	864-208-6020	https://smithaleeweddings.com	https://www.instagram.com/smithalee/
Molly Madeira Photography	Photography		Greenville	South Carolina	Greenville, Asheville, Charleston and beyond	Luxury wedding-weekend photographer who takes a limited roster each year and pairs digital galleries with handcrafted heirloom albums.	hello@mollymadeira.com		https://mollymadeira.com	https://www.instagram.com/mollymadeira/
askem8 Films	Videography		Taylors	South Carolina	Greenville, Charleston, the Southeast and beyond	Analogue wedding filmmakers shooting real Super 8, 16mm and 35mm film for a nostalgic, grainy keepsake, with vintage camera rentals too.	bookings@askemstudios.com	864-990-2155	https://www.palmetto8films.com	https://www.instagram.com/askem8weddingfilms/
Two Worlds Weddings by Ale	Planning		Greenville	South Carolina	Upstate South Carolina and beyond	Bilingual planner Alejandra Neal specialising in multicultural weddings that blend two families' traditions, from full planning to day-of help.	2worldweddings@gmail.com	(864) 385-9786	https://twoworldsweddings.com	https://www.instagram.com/twwbyale/
Laurel Creek Florals	Florals		Greenville	South Carolina	Greenville and surrounding areas	Eco-minded wedding florist growing specialty crops and buying from local farms, designing sculptural arrangements without flower foam.	bookings@laurelcreekflorals.com		https://laurelcreekflorals.com	https://www.instagram.com/laurelcreekflorals/
Soulution	Music		Greenville	South Carolina	Southeast United States	Greenville party band playing Motown to current pop, from small ensembles up to a full line-up with saxophone, vocalists and an MC.	booking@soulutionband.com	(855) 718-6050	https://www.weddingsoulution.com	https://www.instagram.com/soulution_sc/
Collective Beauty	Hair & Makeup		Greenville	South Carolina	Greenville; artists travel to you	Team of a dozen licensed hairstylists and makeup artists based in Greenville, working by appointment or travelling to the wedding.	info@collectivebeautysc.com	864.901.3281	https://collectivebeautysc.com	https://www.instagram.com/collectivebeautyhmu/`,
  },
];

export default batches;
