import type { VendorBatch } from "@/lib/vendor-batches";

// Tennessee vendor batches. Every row's State is "Tennessee". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Nashville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Krista Lee Photography	Photography		Nashville	Tennessee	Nashville and Middle Tennessee	Modern, polished wedding photography from a studio that has photographed Nashville-area couples and families for more than 15 years.	krista@kristaleephotography.com		https://kristaleephotography.com/	https://www.instagram.com/kristaleephoto/
Kristyn Hogan Photography	Photography		Nashville	Tennessee	Nashville and destinations worldwide	Bright, fresh and timeless wedding photography with a fashion-and-travel eye, shooting Nashville weddings and destination celebrations.	kristyn@kristynhogan.com	(615) 962-3449	https://www.kristynhoganblog.com/	https://www.instagram.com/kristynhogan/
Harp & Olive Photography	Photography		Nashville	Tennessee	Nashville, Tennessee and destinations beyond	Elegant, emotive wedding photography for a limited number of couples each year, with custom collections rather than preset packages.	harpandolive@gmail.com		https://harpandolive.com/	https://www.instagram.com/harpandolive/
Nashville Photography Group	Photography		Nashville	Tennessee	Nashville and destination weddings	Award-winning wedding studio led by Jeb Wilson, known for creative, inventive imagery at both grand and pared-back weddings.	info@nashvillephotogroup.com		https://www.nashvillephotogroup.com/	
Emma Martin Events	Planning		Nashville	Tennessee	Nashville, the Southeast and beyond	Full-service planning and design studio led by Emma Rolader Martin, with floral design and stationery available in-house.			https://www.emmamartinevents.com/	https://www.instagram.com/emmamartinevents/
Siena & Co. Events	Planning		Nashville	Tennessee	Nashville, Italy, the Caribbean and beyond	Boutique planner taking on a small number of full-service weddings a year, with a dedicated offshoot for Italian destination weddings.			https://sienacoevents.com/	https://www.instagram.com/sienaco_events/
Magnolia Wedding Co.	Planning		Nashville	Tennessee	Nashville area	Wedding studio founded in 2014 that keeps planning, design, rentals, florals and photography under one roof to simplify the process.			https://magnoliaweddingcompany.com/	https://www.instagram.com/magnoliaweddingcompany/
Olive & Ivy Events	Planning		Nashville	Tennessee	Nashville	Planner Lauren Wallstedt offers month-of coordination through to full planning and design, with hands-on help on setup and teardown.	lauren@oliveandivyevents.com		https://oliveandivyevents.com/	https://www.instagram.com/oliveandivyevents/
Lillian's Floral Studio	Florals	2807 Bransford Avenue, Suite A	Nashville	Tennessee	Nashville and beyond	Boutique Nashville flower shop and design studio creating wedding florals with an emphasis on sustainable design and sourcing.		(629) 203-7160	https://lilliansfloralstudio.com/	https://www.instagram.com/lilliansfloralstudio/
Frances & Jane	Florals		Franklin	Tennessee	Nashville and Williamson County	Sister-run studio designing organic, garden-inspired wedding flowers shaped around each venue's architecture, light and palette.			https://francesandjane.com/	https://www.instagram.com/frances_and_jane/
Mason & Loretta Floral Design	Florals		Nashville	Tennessee	Nashville and surrounding areas	Bespoke garden-style wedding florals from a Nashville-native designer who puts inclusivity and a relaxed process at the heart of her work.	chelsea@masonandloretta.com		https://www.masonandloretta.com/	https://www.instagram.com/masonandloretta/
Petal Barn	Florals		Nashville	Tennessee	Middle Tennessee	Family-run florist established in 2015, specialising in luxury custom florals for weddings and events across Middle Tennessee.	petalbarn@gmail.com	(615) 630-3098	https://petalbarn.com/	https://www.instagram.com/petal.barn/
DJ DanCo.	Music		Nashville	Tennessee	Nashville and Middle Tennessee	DJ and MC service with more than 25 years in Middle Tennessee, handling custom playlists, announcements and timeline coordination.	info@djdanco.com	(615) 457-1956	https://www.djdanco.com/	https://www.instagram.com/djdanco/
Dynamic Excitement	Music		Nashville	Tennessee	Nashville, Charlotte, Atlanta, Tampa and St. Louis	Wedding DJ and production company adding uplighting, photo booths, cold sparklers and cultural wedding experience to the dance floor.	info@dynamicexcitement.com	(615) 403-8545	https://www.dynamicexcitement.com/	https://www.instagram.com/dynamicexcitement/
The Nashville Band	Music		Nashville	Tennessee	Nashville and worldwide	High-energy live wedding band with party, country and small-ensemble line-ups, whose musicians have shared stages with major touring acts.	info@thenashvilleband.com	(615) 492-3006	https://www.thenashvilleband.com/	https://www.instagram.com/thenashvilleband/
The Music City DJs	Music		Nashville	Tennessee	Nashville and beyond	Full-service mobile DJ company pairing wedding music and MC work with sound and lighting production, karaoke and a 360 photo booth.			https://www.themusiccitydjs.com/	
Actual Food	Catering	3914 Gallatin Pike	Nashville	Tennessee	Nashville	Full-service Nashville caterer offering custom, locally inspired menus with polished bar and front-of-house service.	hello@actualfoodnashville.com	(615) 490-6139	https://www.actualfoodnashville.com/	https://www.instagram.com/actualfoodnash/
dailyDish Events & Catering	Catering	2205 Hillsboro Road	Franklin	Tennessee	Franklin, Brentwood and Nashville	Caterer serving Middle Tennessee since 1990, known for homestyle American menus, buffets and budget-friendly wedding options.		(615) 293-1128	https://dailydishcatering.com/	
Suzette Catering & Events	Catering	104 Carr Ave, Suite 7	Franklin	Tennessee	Franklin and Middle Tennessee	Chef-driven caterer building custom menus around each couple's heritage, and handling flowers, linens and décor for up to 500 guests.			https://www.cateringbysuzette.com/	https://www.instagram.com/cateringbysuzette/
CRAVE Full Service Events	Catering	324 Gallatin Pike South	Madison	Tennessee	Nashville and Middle Tennessee	Nashville-founded caterer offering plated dinners and buffets, with event planning and florals from its sister studio Prim and Poppy.	info@bycrave.com	(615) 974-0306	https://bycrave.com/	https://www.instagram.com/cravecateringevents/
One10 Beauty	Hair & Makeup	703 Craighead Street	Nashville	Tennessee	Nashville and within 30 miles	Berry Hill salon sending artists on location for bridal hair and makeup, matched to the bride and skilled across hair textures and skin tones.	booking@one10beauty.com	(615) 970-0726	https://one10beauty.com/bridal	https://www.instagram.com/one10beauty/
Indigo Beauty Collective	Hair & Makeup	3511 Gallatin Pike, Suite 302	Nashville	Tennessee	Nashville	On-location bridal hair and makeup team led by Katie-Laine Thornton, with a focus on conscious, low-tox products and natural looks.	klt@katielainethornton.com	(615) 601-2796	https://www.indigobeautycollective.com/	https://www.instagram.com/indigobeautycollective/
Black Tie and Blush	Hair & Makeup		Nashville	Tennessee	Nashville, Knoxville and East Tennessee; travels worldwide	Mobile bridal hair and makeup led by Sarah Crews, known for soft, quiet glam and a calm, unhurried morning-of experience.	sarah@blacktieandblush.com	(615) 589-5055	https://blacktieandblush.com/	https://www.instagram.com/blacktieandblush/
Elite Collective	Hair & Makeup	4000 Longpoint Way, Suite 420	Franklin	Tennessee	Franklin, Brentwood and Nashville	Franklin salon for bridal hair, airbrush makeup and lashes, offering in-salon styling or artists who travel to the venue.		(615) 708-8226	https://www.elitecollective.co/bridal	https://www.instagram.com/elitecollectivesalon/
Baked in Nashville	Cake	2616 Eugenia Avenue	Nashville	Tennessee	Nashville	By-appointment bakery founded in 2015 by a pastry-trained baker, making custom wedding cakes, decorated cookies and French macarons.	hello@bakedinnashville.com	(615) 760-5101	https://www.bakedinnashville.com/	https://www.instagram.com/bakedinnashville/
Baked on 8th	Cake	1512 8th Avenue South	Nashville	Tennessee	Nashville	Neighbourhood bakery on 8th Avenue South baking custom wedding and celebration cakes fresh to order, alongside cookies and pies.	info@bakedon8th.com	(615) 933-1100	https://www.bakedon8th.com/	https://www.instagram.com/bakedon8th/
Kailey Cakes	Cake		Franklin	Tennessee	Nashville, Franklin, Brentwood and Middle Tennessee	Family-run, order-only wedding cake bakery that also brings its Sugar + Slice cake cart and dessert tables to receptions.			https://www.kaileycakes.com/	https://www.instagram.com/kaileycakesnashville/
Wild Fern Weddings	Videography		Nashville	Tennessee	Nashville	Christian McGee films calm, candid, hands-off wedding films that capture real moments rather than staged ones.			https://www.wildfernweddings.com/	https://www.instagram.com/wildfernweddings/
Hodges Media	Videography		Nashville	Tennessee	Nashville, Franklin, Mt. Juliet and Middle Tennessee	Wade Hodges makes cinematic wedding films that blend documentary storytelling with a feel for each couple's Nashville day.		(615) 852-9350	https://hodges-media.com/	
Details Nashville	Videography	401 Center Street	Old Hickory	Tennessee	Nashville	Photo and video studio filming weddings and corporate events, with photography and photo booth hire available from one team.	info@detailsnashville.com	(615) 567-3850	https://www.detailsnashville.com/	https://www.instagram.com/detailsnashville/
`,
  },
  {
    name: "Knoxville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Winx Photo	Photography		Knoxville	Tennessee	Knoxville, Nashville, the Great Smoky Mountains and beyond	Knoxville photography studio run by husband-and-wife duo Jesse and Quinn, documenting weddings, elopements and couples across East Tennessee.	winxphoto@gmail.com		https://winxphoto.com/	https://www.instagram.com/winxphotoweddings/
Erin Morrison Photography	Photography		Knoxville	Tennessee	Knoxville and the Great Smoky Mountains National Park	Knoxville wedding and elopement photographer with a relaxed, candid style, LGBTQ+ inclusive, and regular work in the Smokies.	erinmorrisonphotography@gmail.com	(865) 214-7826	https://erinmorrisonphotography.com/	https://www.instagram.com/erinm_photography/
Amy-Cole Photography	Photography		Knoxville	Tennessee	Tennessee, Georgia and Alabama	Knoxville wedding and family photographer Amy, covering engagements and wedding days across Tennessee, Georgia and Alabama.	amysullins@yahoo.com	(256) 613-6728	https://www.amy-colephotography.com/	https://www.instagram.com/amycolephotography/
Hayley Howard Photography	Photography		Knoxville	Tennessee	Knoxville and the Smokies	Knoxville-based wedding and elopement photographer with an unhurried, present approach, often shooting in the Smoky Mountains.			https://hayleyhoward.co/	
Elope to Gatlinburg	Photography		Gatlinburg	Tennessee	Gatlinburg, Pigeon Forge and the Smoky Mountains	Gatlinburg elopement company bundling officiant and photography into simple mountain-overlook and creekside ceremony packages.		(865) 365-5025	https://elopetogatlinburg.com/	https://www.instagram.com/elopetogatlinburg/
Sewell Celebrations	Planning		Knoxville	Tennessee	Knoxville, Athens, Maryville, Sevierville and all of East Tennessee	Knoxville coordination team specialising in day-of coordination and last-minute planning help for couples across East Tennessee.	sewellcelebrations@gmail.com		https://sewellcelebrations.com/	
A Touch of Whimsi Weddings & Events	Planning		Knoxville	Tennessee	East Tennessee, Chattanooga and the Smoky Mountains	Certified Knoxville planner offering full and partial planning and design for elegant, romantic weddings, including destination events.		(865) 455-5671	https://atouchofwhimsiweddings.com/	https://www.instagram.com/atouchofwhimsiweddings/
Wild Sage Weddings	Planning		Knoxville	Tennessee		Knoxville wedding planner providing full-service planning and coordination, with a warm, personal approach to each couple's day.		(865) 324-5699	https://wildsageweddings.com/	https://www.instagram.com/wildsage_weddings/
The Pink Butler Events & Rentals	Planning		Knoxville	Tennessee		Knoxville event planner pairing day-of and full planning with its own party rental collection, so decor and coordination come from one team.	kelly@thepinkbutlerevents.com	(865) 603-3343	https://thepinkbutlerevents.com/	
Echelon Florist	Florals	1260 Rocky Hill Rd	Knoxville	Tennessee	Knoxville area	Family-owned Knoxville florist in the Rocky Hill Shopping Center, serving the area since 1995 with custom wedding and event flowers.	flowers@echelonflorist.com	(865) 690-7427	https://echelonflorist.com/	https://www.instagram.com/echelonflorist/
Rose Moss Designs	Florals		Knoxville	Tennessee		Knoxville floral design company focused on wedding flowers and large events, from bridal bouquets to full ceremony installations.	anna.rosemoss@gmail.com		https://rosemossdesigns.com/	https://www.instagram.com/rosemossdesigns/
Wither and Bloom Designs	Florals		Knoxville	Tennessee	Destination and local events in the Eastern United States and beyond	Knoxville-studio wedding florist creating natural, textural arrangements for local Smoky Mountain weddings and destination events.			https://witherandbloomdesigns.com/	https://www.instagram.com/witherandbloomdesigns/
Gabby Rose Flora	Florals	713 Winona Street	Knoxville	Tennessee		Knoxville floral design studio offering full-service wedding flowers and decor, plus floral workshops at its Parkridge studio.	gabbyroseflora@gmail.com	(865) 640-3033	https://gabbyroseflora.com/	https://www.instagram.com/gabbyroseflora/
LB Floral	Florals		Knoxville	Tennessee		Knoxville luxury florist specialising in weddings, with detail-focused bouquets, centrepieces and ceremony flowers in every style.	lesley@lbfloral.com	(865) 313-3404	https://lbfloral.com/	https://www.instagram.com/lbfloral/
J3 Entertainment	Music		Knoxville	Tennessee	Knoxville and East Tennessee	Knoxville DJ company with over 20 years of experience, offering wedding DJ and MC packages with uplighting and photo booths.	bookings@j3entertainment.com	(865) 257-0527	https://www.j3entertainment.com/weddings	https://www.instagram.com/j3entertainment/
Midas Entertainment	Music		Lenoir City	Tennessee	Knoxville, Maryville, Farragut, Sevier County and East Tennessee	Lenoir City DJ Rob Kermidas runs wedding receptions with tailored uplighting colour, with travel within two hours included.	events@midaswelldance.com	(607) 743-1217	https://midaswelldance.com/	https://www.instagram.com/midaswelldance/
Marble City String Quartet	Music		Knoxville	Tennessee	Greater Knoxville	Knoxville string quartet playing ceremonies and receptions since 2015, with a library of over 700 classical, film and pop arrangements.	wesley@marblecityquartet.com	(865) 415-0664	https://marblecityquartet.com/	
City Catering	Catering	922 N Central St	Knoxville	Tennessee	Knoxville and surrounding areas	Knoxville caterer from the family behind Kefi and The Square Room, offering elevated wedding menus plus craft mixology service.	info@spacesinthecity.com	(865) 544-4199	https://citycateringknox.com/	https://www.instagram.com/citycatering_knoxville/
Dead End BBQ	Catering	3621 Sutherland Ave	Knoxville	Tennessee		Award-winning Knoxville barbecue restaurant with a dedicated wedding catering menu for relaxed, smoked-meat receptions.		(865) 212-5655	https://deadendbbq.com/catering	https://www.instagram.com/deadendbbqetn/
First Fruits Kitchen	Catering		Maryville	Tennessee	Knoxville, Maryville, Sevierville and East Tennessee	Maryville chef-led caterer offering full-service and drop-off wedding catering, with its own bakery producing wedding cakes too.	tmcclanahan1@gmail.com	(865) 233-2395	https://firstfruitskitchen.com/wedding-catering/	https://www.instagram.com/first_fruits_kitchen/
Bangs and Blush	Hair & Makeup	106 Hotel Road, Suite 100	Knoxville	Tennessee	Knoxville based, available worldwide	Knoxville beauty agency bringing bridal hair and makeup teams on location, with an in-studio option for trials and smaller parties.	hello@bangsandblush.com	(865) 456-0006	https://bangsandblush.com/	https://www.instagram.com/bangsandblush_/
Wanderlust Salon and Spa	Hair & Makeup		Sevierville	Tennessee	Sevierville, Gatlinburg and the Smoky Mountains	Downtown Sevierville salon offering in-salon bridal packages and travelling hair and makeup for Smoky Mountain weddings.	reservations@wanderlustsalonspa.com	(865) 366-3100	https://wanderlustsalonspa.com/bridal	https://www.instagram.com/wanderlustsalonspa/
Magpies Bakery	Cake	846 N Central St	Knoxville	Tennessee	Knoxville, with delivery to Nashville, Asheville, Chattanooga and Atlanta	North Knoxville bakery making scratch wedding and groom's cakes, from standard designs to fully custom tiers, plus cupcakes.	weddings@magpiescakes.com	(865) 673-0471	https://magpiescakes.com/weddings	https://www.instagram.com/magpiescakes/
Art of Cakes Bakery	Cake	1909 Sevierville Rd	Maryville	Tennessee		Maryville bakery known for classic and contemporary wedding cakes, groom's cakes and sculpted 3D designs, all baked from scratch.		(865) 306-2919	https://artofcakesmaryville.com/	
Artisan Cakery of Knoxville	Cake	5803 Kingston Pike	Knoxville	Tennessee		Bearden cafe and bakery for European-style desserts, offering wedding cakes alongside layered honey cakes, macarons and tarts.	theartisancakery@gmail.com	(865) 851-8093	https://theartisancakery.com/	https://www.instagram.com/artisan.cakery/
Sweets Cake Studio	Cake		Sevierville	Tennessee	Pigeon Forge, Sevierville and Gatlinburg	Licensed Sevierville home bakery creating custom wedding cakes, cupcakes and dessert tables for Smoky Mountain weddings.	sweetscakestudio@gmail.com		https://sweetscakestudio.com/	https://www.instagram.com/sweets_cake_studio/
Rellek Films	Videography		Knoxville	Tennessee	Knoxville and beyond	Husband-and-wife team Tommy and Nicole, long-time Knoxville locals, making unscripted documentary-style wedding films.	rellekfilms@gmail.com		https://rellekfilms.com/	https://www.instagram.com/rellekfilms/
SK Videography	Videography		Knoxville	Tennessee	All of East Tennessee	Knoxville husband-and-wife team Steve and Kat filming cinematic wedding films, from ceremony-only coverage to full-day packages.			https://www.skvideography.com/	https://www.instagram.com/s.k.videography/
`,
  },
  {
    name: "Memphis: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Rob+Deanna	Photography		Memphis	Tennessee		Husband-and-wife wedding photography team covering Memphis weddings and engagements, from Dixon Gallery ceremonies to Annesdale Mansion.	info@robanddeanna.com		https://robanddeanna.com/	
Michelle Evans Art	Photography		Memphis	Tennessee		Memphis wedding photographer with a relaxed, intimate style who gets to know each couple well before the day itself.	hello@michelleevansart.com		https://www.michelleevansart.com/	https://www.instagram.com/michelleevansart/
Sarai Lange Photography	Photography		Memphis	Tennessee	Memphis and the Mid-South	Wedding photographer focused on the connections between a couple and their guests, with a calm, unhurried approach on the day.			https://www.sarailangephotography.com/	https://www.instagram.com/sarailangephotography/
Elizabeth Hoard Photography	Photography		Memphis	Tennessee	Couples throughout the United States and destinations worldwide	Memphis-based wedding photographer working since 2013, pairing classic portraits with candid, light-hearted moments.			https://www.elizabethhoardphotography.com/	https://www.instagram.com/elizabethhoardphotography/
Incredibly Wee Photography	Photography		Memphis	Tennessee		Memphis photographer Esmee Kyles shoots weddings, portraits and events in a bold, vivid style that lets couples be themselves.	hello@incrediblywee.com	(901) 483-6141	https://www.incrediblywee.com/	https://www.instagram.com/incrediblywee/
Infinity Events	Planning		Memphis	Tennessee	Memphis, Chicago, Austin and worldwide	Certified planners offering full, partial and month-of wedding planning, with more than a decade of events across Memphis and beyond.	emma@infinityeventsmemphis.com	(901) 412-7451	https://www.infinityeventsmemphis.com/	https://www.instagram.com/infinityeventsmemphis/
Purple Door Planning	Planning		Memphis	Tennessee	Tennessee, Mississippi and Arkansas	Master-certified wedding planning firm with 300-plus events behind it, experienced in multicultural celebrations from Nigerian to Korean.	info@purpledoorplanning.com	(901) 497-9011	https://www.purpledoorplanning.com/	
Dani Cymone Events	Planning		Memphis	Tennessee	Tennessee, Arkansas and Mississippi, plus destination weddings	Memphis wedding planner and designer who also rents décor and organises destination weddings in the Caribbean and Mexico.	hello@danicymoneevents.com	(901) 492-1091	https://www.danicymoneevents.com/	https://www.instagram.com/dani_cymone_events/
Tailored For You Weddings & Events	Planning		Bartlett	Tennessee	Memphis, Jackson, Nashville, Oxford MS and surrounding areas	Planning firm led by a master-certified planner, with collections from full planning to virtual coaching, micro-weddings and elopements.	info@tailoredforyouplanning.com	(901) 738-0466	https://tailoredforyouplanning.com/	https://www.instagram.com/tailoredforyouplanning/
Lynn Doyle Flowers & Events	Florals	6225 Old Poplar Pike	Memphis	Tennessee		Family florist founded in 1937 and now five generations on, designing wedding and event flowers from its East Memphis shop.		(901) 323-4521	https://www.lynndoyleflowersandevents.com/	https://www.instagram.com/lynndoyleflowers/
Pugh's Wedding Flowers	Florals		Memphis	Tennessee		Wedding and events team of a family-owned Memphis florist of over 40 years, designing in styles from garden to moody and artistic.		(901) 363-6744	https://www.pughsweddingflowers.com/	https://www.instagram.com/pughsweddingsandevents/
Premier Flowers	Florals		Memphis	Tennessee	Memphis, Germantown, Cordova, West Memphis and surrounding areas	Memphis studio florist with no walk-ins, making bridal bouquets and centrepieces, with work seen on local TV and NBC's Bluff City Law.	premierflowers901@gmail.com	(901) 618-2661	https://premierflowerstn.com/	https://www.instagram.com/premierflowersmemphis/
M10 DJ Company	Music		Memphis	Tennessee	Memphis and the Mid-South	Memphis wedding DJ company that reads the room rather than playing preset lists, with 500-plus weddings and events to date.	info@m10djcompany.com	(901) 410-2020	https://www.m10djcompany.com/	
Cooper Union Band	Music	408 South Front Street	Memphis	Tennessee		LGBTQ-owned party band of up to ten musicians, also offering jazz and cocktail sets and string ensembles for ceremonies.	info@cooperunionband.com	(270) 635-1921	https://www.cooperunionband.com/	https://www.instagram.com/cooperunionband/
Groove Factor Live	Music		Memphis	Tennessee	Alabama, Mississippi, Arkansas, Texas, Louisiana, Georgia and Oklahoma	Memphis party band playing everything from Motown to current dance hits, now offering DJ sets alongside the live show.		(404) 423-1607	https://groovefactorlive.com/	https://www.instagram.com/groovefactorlive/
Simply Southern Catering Co.	Catering	2886 Walnut Grove Road	Memphis	Tennessee	Memphis metropolitan area and surrounding areas	Memphis caterer for weddings and celebrations, known for Southern menus and elaborate food displays such as gourmet bread service.	info@eatsimplysouthern.com	(901) 440-0089	https://www.eatsimplysouthern.com/	
A Moveable Feast Catering	Catering	1291 Tully St	Memphis	Tennessee	Greater Memphis and the Mid-South	Memphis caterer running two styles: upscale menus as A Moveable Feast and casual barbecue as Hog Wild, both available for weddings.	info@amoveablefeastcatering.com	(901) 522-9453	https://amoveablefeastcatering.com/	https://www.instagram.com/hogwild_amf/
Draper's Catering	Catering	6116 Macon Rd	Memphis	Tennessee	Memphis and the Mid-South	Off-site caterer offering plated tastings, waiting staff, bartending and clean-up for weddings across the Memphis area.	info@draperscatering.com	(901) 385-7788	https://draperscatering.com/	https://www.instagram.com/draperscatering/
Donelson's Catering	Catering	8225 Dexter Rd, Ste 107	Cordova	Tennessee	Mid-South	Minority-owned Cordova caterer run by Wendell and Kim for nearly two decades, catering wedding receptions and corporate events.	events@donelsonscatering.com	(901) 757-4300	https://www.donelsonscatering.com/	https://www.instagram.com/donelsonscatering/
Kimberly Yasmine Makeup	Hair & Makeup	841 S Cooper Street	Memphis	Tennessee		Memphis bridal makeup studio specialising in soft glam, with more than 1,200 brides done and hair and makeup for the bridal party.			https://kimberlyyasmine.com/	
Mandie J Pro	Hair & Makeup	5007 Black Rd, Suite 230	Memphis	Tennessee		Travelling makeup artist and hairstylist with TV and film experience, offering bridal looks built to last through the day.	info@mandiej.com	(901) 229-1387	https://www.mandiej.com/	https://www.instagram.com/mandiejpro/
Memphis Makeup Artists	Hair & Makeup	2962 North Stage Plaza	Bartlett	Tennessee	Memphis and surrounding areas	Team of licensed cosmetologists and makeup artists, working since 2018, who do on-site bridal party hair and makeup at hotels or venues.		(901) 730-6517	https://memphismakeup.com/	https://www.instagram.com/memphismakeupdotcom/
MyMoniCakes	Cake		Memphis	Tennessee	Memphis metro and the Tennessee, Arkansas and Mississippi tri-state area	Family-owned Memphis boutique cake studio baking everything from scratch, making custom wedding cakes to each couple's design.	monica@mymonicakes.com	(901) 605-7065	https://mymonicakes.com/	https://www.instagram.com/mymonicakes/
Frost Bake Shop	Cake	1016 W Poplar Ave, Suite 107	Collierville	Tennessee		Family-owned scratch bakery since 2004 with shops in East Memphis, Collierville and Lakeland, offering wedding cake tastings.	cakes@frostbakeshop.com	(901) 232-7555	https://www.frostbakeshop.com/	
Muddy's Bake Shop	Cake	2497 Broad Ave	Memphis	Tennessee		Broad Avenue bake shop open since 2008, taking custom layer and tiered cake orders for weddings alongside its pies and other bakes.			https://www.muddysbakeshop.com/	https://www.instagram.com/muddysbakeshop/
FJ Originals	Videography		Memphis	Tennessee	Memphis and the Southeast	Husband-and-wife team Felipe and Jess making documentary wedding films that favour candid moments over polished spectacle.	hello@fjoriginals.com		https://www.fjoriginals.com/	https://www.instagram.com/fjoriginals/
Dreams Film Company	Videography		Memphis	Tennessee		Family-run Memphis film company making cinematic wedding videos, with packages that combine videography and photography.	dkgdream@gmail.com	(901) 215-8364	https://www.dreamsfilmcompany.com/	
Matt Phoenix	Videography		Memphis	Tennessee	Memphis and destinations worldwide	Memphis-based wedding photographer and videographer offering cinematic highlight films alongside photo coverage.			https://www.mattpphoto.com/	https://www.instagram.com/mattpphoto1/
`,
  },
  {
    name: "Chattanooga: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Anh Bao	Photography		Chattanooga	Tennessee	Chattanooga and beyond	Chattanooga photographer shooting weddings, engagements and family portraits, with fine art prints offered alongside her session work.	anhbao@anhbao.com	(423) 521-5138	https://www.anhbao.com/	https://www.instagram.com/anhbao.photography/
Cinderella Wedding Co	Photography	1806 Madison St	Chattanooga	Tennessee	Chattanooga and beyond	Photography and videography company with a Madison Street studio, shooting weddings and elopements in a modern, candid style.			https://cinderellawedding.co/	https://www.instagram.com/cinderellawedding.co/
Daisy Moffatt Photography	Photography		Chattanooga	Tennessee	Chattanooga and destinations	Chattanooga wedding photographers who also shoot engagements and family sessions, and travel for destination weddings.	daisy@daisymphotography.com	(423) 386-5324	https://daisymphotography.com/	
Emily Lester Photography	Photography		Chattanooga	Tennessee		Wedding and elopement photographer who works in natural light and favours adventurous, outdoor settings.	emily@emilylesterphotography.com		https://www.emilylesterphotography.com/	https://www.instagram.com/emilylesterphotography/
Before the Vows	Planning		Chattanooga	Tennessee	Chattanooga and the Southeast	Wedding planning and coordination from proposal through reception, with packages for the whole run of events.	infobeforethevows@gmail.com	(423) 250-3963	https://www.beforethevowsllc.com/	https://www.instagram.com/beforethevows_/
Catilyn Devone Weddings	Planning		Chattanooga	Tennessee	Chattanooga and beyond	Chattanooga wedding planner and day-of coordinator who is happy to travel to the couple's venue.			http://www.catilyndevoneweddings.com/	https://www.instagram.com/catilyndevone_weddings/
Loga Weddings	Planning	7000 Lee Highway, Suite 600	Chattanooga	Tennessee	Chattanooga	Chattanooga company offering full wedding planning and day-of coordination.		(423) 693-9906	https://www.logaweddings.com/	
The Best Day Weddings	Planning		Chattanooga	Tennessee	Chattanooga and East Tennessee	Solo wedding coordinator and event planner offering full planning, partial planning and day-of coordination in East Tennessee.			https://www.thebestdayweddings.com/	https://www.instagram.com/thebestdayweddingcoordinating/
With Class Weddings	Music		Chattanooga	Tennessee	Tennessee, Georgia and Alabama	Chattanooga coordination company whose lead DJ Mark runs ceremony sound, emcee duties and the dance floor.		(423) 314-3094	https://www.withclassllc.com/	https://www.instagram.com/withclassllc/
Complete Weddings + Events Chattanooga	Music		Chattanooga	Tennessee	Chattanooga and nearby	Bundled wedding services in Chattanooga, from DJs and emcees to photo, video, photo booth and day-of coordination.		(678) 398-7868	https://completewedo.com/chattanooga/	https://www.instagram.com/completechattanooga/
Golden Gate Entertainment	Music		Chattanooga	Tennessee	Chattanooga	Chattanooga DJ, host and MC service for weddings and parties, with photo booths and lighting effects available.	kyle.goldengateentertainment@gmail.com	(423) 315-2990	https://www.goldengate-entertainment.com/	https://www.instagram.com/goldengateent/
Scenic Event Solutions	Music		Chattanooga	Tennessee	Chattanooga and Northeast Georgia	Chattanooga DJ service for weddings, adding photo booth and event lighting across Chattanooga and Northeast Georgia.	info@sceniceventsolutions.com	(423) 645-1565	https://sceniceventsolutions.com/	https://www.instagram.com/sceniceventsolutions/
May Flowers	Florals	800 N Market St	Chattanooga	Tennessee	Chattanooga	North Shore floral design studio led by florist Christy Staven, focused on wedding and event flowers.		(423) 486-5320	https://www.mayflowerscha.com/	https://www.instagram.com/mayflowerscha/
Petal Pushers	Florals	8827 Standifer Gap Road	Chattanooga	Tennessee	Chattanooga	Chattanooga florist making custom wedding flowers alongside funeral work, subscription florals and daily bouquets.	hello@petalpusherschatt.com	(423) 424-4321	https://www.petalpusherschatt.com/	
Summerfield Studio Floral Design	Florals	1209 Taft Highway	Signal Mountain	Tennessee	Chattanooga and beyond	Boutique floral design studio on Signal Mountain creating curated wedding and event florals around Chattanooga.		(423) 394-9346	https://www.summerfieldstudiofloral.com/	https://www.instagram.com/summerfieldstudiofloral/
Petaline Floral	Florals		Chattanooga	Tennessee	Chattanooga and the Southeast	Fine-art wedding florist designing custom, organic arrangements for couples in Chattanooga and across the Southeast.			https://www.petaline.co/	https://www.instagram.com/petalinefloral/
GRAFE Studio	Florals	4009 Tennessee Ave	Chattanooga	Tennessee	Chattanooga	Chattanooga floral studio with its own events team, offering wedding flowers from a Tennessee Avenue shop.	grafestudio.events@epbfi.com		https://www.grafestudiofloralartists.com/	https://www.instagram.com/grafestudio/
Flowers by Tami	Florals		Chattanooga	Tennessee	Chattanooga and surrounding areas	Wedding florist Tami McAllister, making bouquets and arrangements for Chattanooga-area brides.	tami@flowersbytamichatt.com	(423) 402-1228	http://www.flowersbytamichatt.com/	https://www.instagram.com/flowersbytami/
Good Company Catering	Catering	5110 Hixson Pike, Suite D	Chattanooga	Tennessee	Chattanooga	Wedding and event caterer serving Southern food with global touches, with a tasting room at the Dwell Hotel.	megan@goodcompanycatering.com	(423) 785-7959	https://www.goodcompanycatering.com/	https://www.instagram.com/good.co.catering/
Catering by Alan	Catering		Chattanooga	Tennessee	Chattanooga	Chattanooga caterer in business since 1995, handling weddings, corporate events and parties.	cateringbyalan@gmail.com	(423) 593-8686	https://cateringbyalan.com/	
Silverware Affair Catering	Catering		Chattanooga	Tennessee	East Tennessee and North Georgia	Wedding and event caterer that also supplies bartending and equipment rentals across East Tennessee and North Georgia.			https://silverwareaffair.com/	https://www.instagram.com/asilverwareaffair/
Catering Cart	Catering		Chattanooga	Tennessee	Chattanooga	Chattanooga caterer offering wedding menus of appetisers, charcuterie and grazing boards and buffets, with bartending and staffing.		(423) 280-5432	https://catering-cart.com/	https://www.instagram.com/cateringcart/
Chattanooga Catering	Catering		Chattanooga	Tennessee	Chattanooga and Cleveland, TN	Caterer serving wedding receptions at Chattanooga venues and in Cleveland, from drop-off meals to formal full-service events.			https://chattanoogacatering.com/	https://www.instagram.com/chattanoogacatering/
Main Street Meats	Catering	217 East Main Street	Chattanooga	Tennessee	Chattanooga	Butcher shop and restaurant on Main Street that caters everything from a grazing table to a full wedding feast.		(423) 602-9568	https://www.mainstreetmeatschatt.com/catering-chattanooga-tn	https://www.instagram.com/mainstreetmeats/
Luxe + Lumi	Hair & Makeup		Chattanooga	Tennessee	Tennessee and Georgia	On-site bridal beauty team of makeup artists and hair stylists, travelling to weddings across Tennessee and Georgia.	luxeandlumico@gmail.com		https://luxeandlumico.com/	https://www.instagram.com/luxeandlumico/
Natural Beauty Nook	Hair & Makeup		Chattanooga	Tennessee	Chattanooga	Chattanooga salon offering bridal hair and makeup trials and on-site wedding-day services alongside everyday beauty work.		(423) 596-2725	https://www.naturalbeautynook.com/bridal-makeup-artist/	https://www.instagram.com/naturalbeautynook/
Sweet Angel Cakes	Cake	6331 E Brainerd Rd	Chattanooga	Tennessee	Chattanooga	Brainerd Road bakery making custom wedding cakes, plus special-occasion cakes, with a modest-priced starting point.	sweetangelcakes@yahoo.com	(423) 485-3473	https://www.mysweetangelcakes.com/	https://www.instagram.com/sweet_angel_cakes/
Six Little Teacups Bakery	Cake		Chattanooga	Tennessee	Chattanooga	Chattanooga bakery taking custom wedding and birthday cake orders alongside cake-decorating classes and tea parties.			https://www.sixlittleteacups.com/	https://www.instagram.com/sixlittleteacupsbakery/
Chattanooga Custom Cakes	Cake		Chattanooga	Tennessee	Chattanooga	Chattanooga custom cake maker taking orders for wedding and special-occasion cakes.		(423) 595-2250	https://www.chattanoogacustomcakes.com/	
B's Sweets	Cake	440 Timberlinks Dr	Signal Mountain	Tennessee	Chattanooga	Signal Mountain bakery whose wedding cakes range from tiny elopement cakes to detailed tiered designs.	cakeorders@bssweets.com	(423) 521-0311	https://www.bssweets.com/	https://www.instagram.com/bssweets/
Erin Mary Films	Videography		Chattanooga	Tennessee	Chattanooga, North Georgia and beyond	Chattanooga wedding videographer making cinematic, story-led films for local and destination couples.	chelsea@erinmaryfilms.com		https://erinmaryfilms.com/	https://www.instagram.com/erinmaryfilms/
Stewart Films	Videography		Chattanooga	Tennessee	Chattanooga, Nashville and Knoxville	Husband-and-wife film team based in Chattanooga making cinematic wedding films for couples around Tennessee.			https://stewartfilms.co/	
Wild Heart Wedding Films	Videography		Chattanooga	Tennessee	Chattanooga	Chattanooga videography company specialising in adventurous weddings and elopements.	wildheartweddingfilm@gmail.com		https://www.wildheartweddingfilms.com/	https://www.instagram.com/wildheart_weddingfilms/
VE Videography	Videography		Chattanooga	Tennessee	Chattanooga and destinations	Documentary-style wedding filmmaker offering highlight films, full-length films, elopements and engagement films.	info@vevideography.com	(423) 486-2214	https://www.vevideography.com/	https://www.instagram.com/vevideography/
`,
  },
];

export default batches;
