import type { VendorBatch } from "@/lib/vendor-batches";

// Tennessee vendor batches. Every row's State is "Tennessee". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Nashville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Krista Lee Photography	Photography		Nashville	Tennessee	Nashville and Middle Tennessee	Modern, polished wedding photography from a studio that has photographed Nashville-area couples and families for more than 15 years.	krista@kristaleephotography.com		https://kristaleephotography.com/	https://www.instagram.com/kristaleephoto/
Kristyn Hogan Photography	Photography		Nashville	Tennessee	Nashville and destinations worldwide	Bright, fresh and timeless wedding photography with a fashion-and-travel eye, shooting Nashville weddings and destination celebrations.	kristyn@kristynhogan.com	(615) 962-3449	https://www.kristynhoganblog.com/	https://www.instagram.com/kristynhogan/
Harp & Olive Photography	Photography		Nashville	Tennessee	Nashville, Tennessee and destinations beyond	Elegant, emotive wedding photography for a limited number of couples each year, with custom collections rather than preset packages.	harpandolive@gmail.com		https://harpandolive.com/	https://www.instagram.com/harpandolive/
Nashville Photography Group	Photography		Nashville	Tennessee	Nashville and destination weddings	Award-winning wedding studio led by Jeb Wilson, known for creative, inventive imagery at both grand and pared-back weddings.	info@nashvillephotogroup.com		https://www.nashvillephotogroup.com/	
Emma Martin Events	Planning		Nashville	Tennessee	Nashville, the Southeast and beyond	Full-service planning and design studio led by Emma Rolader Martin, with floral design and stationery available in-house.			https://www.emmamartinevents.com/	https://www.instagram.com/emmamartinevents/
Siena & Co. Events	Planning		Nashville	Tennessee	Nashville, Italy, the Caribbean and beyond	Boutique planner taking on a small number of full-service weddings a year, with a dedicated offshoot for Italian destination weddings.			https://sienacoevents.com/	https://www.instagram.com/sienaco_events/
Magnolia Wedding Co.	Planning		Nashville	Tennessee	Nashville area	Wedding studio founded in 2014 that keeps planning, design, rentals, florals and photography under one roof to simplify the process.			https://magnoliaweddingcompany.com/	https://www.instagram.com/magnoliaweddingcompany/
Olive & Ivy Events	Planning		Nashville	Tennessee	Nashville	Planner Lauren Wallstedt offers month-of coordination through to full planning and design, with hands-on help on setup and teardown.	lauren@oliveandivyevents.com		https://oliveandivyevents.com/	https://www.instagram.com/oliveandivyevents/
Lillian's Floral Studio	Florals	2807 Bransford Avenue, Suite A	Nashville	Tennessee	Nashville and beyond	Boutique Nashville flower shop and design studio creating wedding florals with an emphasis on sustainable design and sourcing.		(629) 203-7160	https://lilliansfloralstudio.com/	https://www.instagram.com/lilliansfloralstudio/
Frances & Jane	Florals		Franklin	Tennessee	Nashville and Williamson County	Sister-run studio designing organic, garden-inspired wedding flowers shaped around each venue's architecture, light and palette.			https://francesandjane.com/	https://www.instagram.com/frances_and_jane/
Mason & Loretta Floral Design	Florals		Nashville	Tennessee	Nashville and surrounding areas	Bespoke garden-style wedding florals from a Nashville-native designer who puts inclusivity and a relaxed process at the heart of her work.	chelsea@masonandloretta.com		https://www.masonandloretta.com/	https://www.instagram.com/masonandloretta/
Petal Barn	Florals		Nashville	Tennessee	Middle Tennessee	Family-run florist established in 2015, specialising in luxury custom florals for weddings and events across Middle Tennessee.	petalbarn@gmail.com	(615) 630-3098	https://petalbarn.com/	https://www.instagram.com/petal.barn/
DJ DanCo.	Music		Nashville	Tennessee	Nashville and Middle Tennessee	DJ and MC service with more than 25 years in Middle Tennessee, handling custom playlists, announcements and timeline coordination.	info@djdanco.com	(615) 457-1956	https://www.djdanco.com/	https://www.instagram.com/djdanco/
Dynamic Excitement	Music		Nashville	Tennessee	Nashville, Charlotte, Atlanta, Tampa and St. Louis	Wedding DJ and production company adding uplighting, photo booths, cold sparklers and cultural wedding experience to the dance floor.	info@dynamicexcitement.com	(615) 403-8545	https://www.dynamicexcitement.com/	https://www.instagram.com/dynamicexcitement/
The Nashville Band	Music		Nashville	Tennessee	Nashville and worldwide	High-energy live wedding band with party, country and small-ensemble line-ups, whose musicians have shared stages with major touring acts.	info@thenashvilleband.com	(615) 492-3006	https://www.thenashvilleband.com/	https://www.instagram.com/thenashvilleband/
The Music City DJs	Music		Nashville	Tennessee	Nashville and beyond	Full-service mobile DJ company pairing wedding music and MC work with sound and lighting production, karaoke and a 360 photo booth.			https://www.themusiccitydjs.com/	
Actual Food	Catering	3914 Gallatin Pike	Nashville	Tennessee	Nashville	Full-service Nashville caterer offering custom, locally inspired menus with polished bar and front-of-house service.	hello@actualfoodnashville.com	(615) 490-6139	https://www.actualfoodnashville.com/	https://www.instagram.com/actualfoodnash/
dailyDish Events & Catering	Catering	2205 Hillsboro Road	Franklin	Tennessee	Franklin, Brentwood and Nashville	Caterer serving Middle Tennessee since 1990, known for homestyle American menus, buffets and budget-friendly wedding options.		(615) 293-1128	https://dailydishcatering.com/	
Suzette Catering & Events	Catering	104 Carr Ave, Suite 7	Franklin	Tennessee	Franklin and Middle Tennessee	Chef-driven caterer building custom menus around each couple's heritage, and handling flowers, linens and décor for up to 500 guests.			https://www.cateringbysuzette.com/	https://www.instagram.com/cateringbysuzette/
CRAVE Full Service Events	Catering	324 Gallatin Pike South	Madison	Tennessee	Nashville and Middle Tennessee	Nashville-founded caterer offering plated dinners and buffets, with event planning and florals from its sister studio Prim and Poppy.	info@bycrave.com	(615) 974-0306	https://bycrave.com/	https://www.instagram.com/cravecateringevents/
One10 Beauty	Hair & Makeup	703 Craighead Street	Nashville	Tennessee	Nashville and within 30 miles	Berry Hill salon sending artists on location for bridal hair and makeup, matched to the bride and skilled across hair textures and skin tones.	booking@one10beauty.com	(615) 970-0726	https://one10beauty.com/bridal	https://www.instagram.com/one10beauty/
Indigo Beauty Collective	Hair & Makeup	3511 Gallatin Pike, Suite 302	Nashville	Tennessee	Nashville	On-location bridal hair and makeup team led by Katie-Laine Thornton, with a focus on conscious, low-tox products and natural looks.	klt@katielainethornton.com	(615) 601-2796	https://www.indigobeautycollective.com/	https://www.instagram.com/indigobeautycollective/
Black Tie and Blush	Hair & Makeup		Nashville	Tennessee	Nashville, Knoxville and East Tennessee; travels worldwide	Mobile bridal hair and makeup led by Sarah Crews, known for soft, quiet glam and a calm, unhurried morning-of experience.	sarah@blacktieandblush.com	(615) 589-5055	https://blacktieandblush.com/	https://www.instagram.com/blacktieandblush/
Elite Collective	Hair & Makeup	4000 Longpoint Way, Suite 420	Franklin	Tennessee	Franklin, Brentwood and Nashville	Franklin salon for bridal hair, airbrush makeup and lashes, offering in-salon styling or artists who travel to the venue.		(615) 708-8226	https://www.elitecollective.co/bridal	https://www.instagram.com/elitecollectivesalon/
Baked in Nashville	Cake	2616 Eugenia Avenue	Nashville	Tennessee	Nashville	By-appointment bakery founded in 2015 by a pastry-trained baker, making custom wedding cakes, decorated cookies and French macarons.	hello@bakedinnashville.com	(615) 760-5101	https://www.bakedinnashville.com/	https://www.instagram.com/bakedinnashville/
Baked on 8th	Cake	1512 8th Avenue South	Nashville	Tennessee	Nashville	Neighbourhood bakery on 8th Avenue South baking custom wedding and celebration cakes fresh to order, alongside cookies and pies.	info@bakedon8th.com	(615) 933-1100	https://www.bakedon8th.com/	https://www.instagram.com/bakedon8th/
Kailey Cakes	Cake		Franklin	Tennessee	Nashville, Franklin, Brentwood and Middle Tennessee	Family-run, order-only wedding cake bakery that also brings its Sugar + Slice cake cart and dessert tables to receptions.			https://www.kaileycakes.com/	https://www.instagram.com/kaileycakesnashville/
Wild Fern Weddings	Videography		Nashville	Tennessee	Nashville	Christian McGee films calm, candid, hands-off wedding films that capture real moments rather than staged ones.			https://www.wildfernweddings.com/	https://www.instagram.com/wildfernweddings/
Hodges Media	Videography		Nashville	Tennessee	Nashville, Franklin, Mt. Juliet and Middle Tennessee	Wade Hodges makes cinematic wedding films that blend documentary storytelling with a feel for each couple's Nashville day.		(615) 852-9350	https://hodges-media.com/	
Details Nashville	Videography	401 Center Street	Old Hickory	Tennessee	Nashville	Photo and video studio filming weddings and corporate events, with photography and photo booth hire available from one team.	info@detailsnashville.com	(615) 567-3850	https://www.detailsnashville.com/	https://www.instagram.com/detailsnashville/
`,
  },
  {
    name: "Knoxville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Winx Photo	Photography		Knoxville	Tennessee	Knoxville, Nashville, the Great Smoky Mountains and beyond	Knoxville photography studio run by husband-and-wife duo Jesse and Quinn, documenting weddings, elopements and couples across East Tennessee.	winxphoto@gmail.com		https://winxphoto.com/	https://www.instagram.com/winxphotoweddings/
Erin Morrison Photography	Photography		Knoxville	Tennessee	Knoxville and the Great Smoky Mountains National Park	Knoxville wedding and elopement photographer with a relaxed, candid style, LGBTQ+ inclusive, and regular work in the Smokies.	erinmorrisonphotography@gmail.com	(865) 214-7826	https://erinmorrisonphotography.com/	https://www.instagram.com/erinm_photography/
Amy-Cole Photography	Photography		Knoxville	Tennessee	Tennessee, Georgia and Alabama	Knoxville wedding and family photographer Amy, covering engagements and wedding days across Tennessee, Georgia and Alabama.	amysullins@yahoo.com	(256) 613-6728	https://www.amy-colephotography.com/	https://www.instagram.com/amycolephotography/
Hayley Howard Photography	Photography		Knoxville	Tennessee	Knoxville and the Smokies	Knoxville-based wedding and elopement photographer with an unhurried, present approach, often shooting in the Smoky Mountains.			https://hayleyhoward.co/	
Elope to Gatlinburg	Photography		Gatlinburg	Tennessee	Gatlinburg, Pigeon Forge and the Smoky Mountains	Gatlinburg elopement company bundling officiant and photography into simple mountain-overlook and creekside ceremony packages.		(865) 365-5025	https://elopetogatlinburg.com/	https://www.instagram.com/elopetogatlinburg/
Sewell Celebrations	Planning		Knoxville	Tennessee	Knoxville, Athens, Maryville, Sevierville and all of East Tennessee	Knoxville coordination team specialising in day-of coordination and last-minute planning help for couples across East Tennessee.	sewellcelebrations@gmail.com		https://sewellcelebrations.com/	
A Touch of Whimsi Weddings & Events	Planning		Knoxville	Tennessee	East Tennessee, Chattanooga and the Smoky Mountains	Certified Knoxville planner offering full and partial planning and design for elegant, romantic weddings, including destination events.		(865) 455-5671	https://atouchofwhimsiweddings.com/	https://www.instagram.com/atouchofwhimsiweddings/
Wild Sage Weddings	Planning		Knoxville	Tennessee		Knoxville wedding planner providing full-service planning and coordination, with a warm, personal approach to each couple's day.		(865) 324-5699	https://wildsageweddings.com/	https://www.instagram.com/wildsage_weddings/
The Pink Butler Events & Rentals	Planning		Knoxville	Tennessee		Knoxville event planner pairing day-of and full planning with its own party rental collection, so decor and coordination come from one team.	kelly@thepinkbutlerevents.com	(865) 603-3343	https://thepinkbutlerevents.com/	
Echelon Florist	Florals	1260 Rocky Hill Rd	Knoxville	Tennessee	Knoxville area	Family-owned Knoxville florist in the Rocky Hill Shopping Center, serving the area since 1995 with custom wedding and event flowers.	flowers@echelonflorist.com	(865) 690-7427	https://echelonflorist.com/	https://www.instagram.com/echelonflorist/
Rose Moss Designs	Florals		Knoxville	Tennessee		Knoxville floral design company focused on wedding flowers and large events, from bridal bouquets to full ceremony installations.	anna.rosemoss@gmail.com		https://rosemossdesigns.com/	https://www.instagram.com/rosemossdesigns/
Wither and Bloom Designs	Florals		Knoxville	Tennessee	Destination and local events in the Eastern United States and beyond	Knoxville-studio wedding florist creating natural, textural arrangements for local Smoky Mountain weddings and destination events.			https://witherandbloomdesigns.com/	https://www.instagram.com/witherandbloomdesigns/
Gabby Rose Flora	Florals	713 Winona Street	Knoxville	Tennessee		Knoxville floral design studio offering full-service wedding flowers and decor, plus floral workshops at its Parkridge studio.	gabbyroseflora@gmail.com	(865) 640-3033	https://gabbyroseflora.com/	https://www.instagram.com/gabbyroseflora/
LB Floral	Florals		Knoxville	Tennessee		Knoxville luxury florist specialising in weddings, with detail-focused bouquets, centrepieces and ceremony flowers in every style.	lesley@lbfloral.com	(865) 313-3404	https://lbfloral.com/	https://www.instagram.com/lbfloral/
J3 Entertainment	Music		Knoxville	Tennessee	Knoxville and East Tennessee	Knoxville DJ company with over 20 years of experience, offering wedding DJ and MC packages with uplighting and photo booths.	bookings@j3entertainment.com	(865) 257-0527	https://www.j3entertainment.com/weddings	https://www.instagram.com/j3entertainment/
Midas Entertainment	Music		Lenoir City	Tennessee	Knoxville, Maryville, Farragut, Sevier County and East Tennessee	Lenoir City DJ Rob Kermidas runs wedding receptions with tailored uplighting colour, with travel within two hours included.	events@midaswelldance.com	(607) 743-1217	https://midaswelldance.com/	https://www.instagram.com/midaswelldance/
Marble City String Quartet	Music		Knoxville	Tennessee	Greater Knoxville	Knoxville string quartet playing ceremonies and receptions since 2015, with a library of over 700 classical, film and pop arrangements.	wesley@marblecityquartet.com	(865) 415-0664	https://marblecityquartet.com/	
City Catering	Catering	922 N Central St	Knoxville	Tennessee	Knoxville and surrounding areas	Knoxville caterer from the family behind Kefi and The Square Room, offering elevated wedding menus plus craft mixology service.	info@spacesinthecity.com	(865) 544-4199	https://citycateringknox.com/	https://www.instagram.com/citycatering_knoxville/
Dead End BBQ	Catering	3621 Sutherland Ave	Knoxville	Tennessee		Award-winning Knoxville barbecue restaurant with a dedicated wedding catering menu for relaxed, smoked-meat receptions.		(865) 212-5655	https://deadendbbq.com/catering	https://www.instagram.com/deadendbbqetn/
First Fruits Kitchen	Catering		Maryville	Tennessee	Knoxville, Maryville, Sevierville and East Tennessee	Maryville chef-led caterer offering full-service and drop-off wedding catering, with its own bakery producing wedding cakes too.	tmcclanahan1@gmail.com	(865) 233-2395	https://firstfruitskitchen.com/wedding-catering/	https://www.instagram.com/first_fruits_kitchen/
Bangs and Blush	Hair & Makeup	106 Hotel Road, Suite 100	Knoxville	Tennessee	Knoxville based, available worldwide	Knoxville beauty agency bringing bridal hair and makeup teams on location, with an in-studio option for trials and smaller parties.	hello@bangsandblush.com	(865) 456-0006	https://bangsandblush.com/	https://www.instagram.com/bangsandblush_/
Wanderlust Salon and Spa	Hair & Makeup		Sevierville	Tennessee	Sevierville, Gatlinburg and the Smoky Mountains	Downtown Sevierville salon offering in-salon bridal packages and travelling hair and makeup for Smoky Mountain weddings.	reservations@wanderlustsalonspa.com	(865) 366-3100	https://wanderlustsalonspa.com/bridal	https://www.instagram.com/wanderlustsalonspa/
Magpies Bakery	Cake	846 N Central St	Knoxville	Tennessee	Knoxville, with delivery to Nashville, Asheville, Chattanooga and Atlanta	North Knoxville bakery making scratch wedding and groom's cakes, from standard designs to fully custom tiers, plus cupcakes.	weddings@magpiescakes.com	(865) 673-0471	https://magpiescakes.com/weddings	https://www.instagram.com/magpiescakes/
Art of Cakes Bakery	Cake	1909 Sevierville Rd	Maryville	Tennessee		Maryville bakery known for classic and contemporary wedding cakes, groom's cakes and sculpted 3D designs, all baked from scratch.		(865) 306-2919	https://artofcakesmaryville.com/	
Artisan Cakery of Knoxville	Cake	5803 Kingston Pike	Knoxville	Tennessee		Bearden cafe and bakery for European-style desserts, offering wedding cakes alongside layered honey cakes, macarons and tarts.	theartisancakery@gmail.com	(865) 851-8093	https://theartisancakery.com/	https://www.instagram.com/artisan.cakery/
Sweets Cake Studio	Cake		Sevierville	Tennessee	Pigeon Forge, Sevierville and Gatlinburg	Licensed Sevierville home bakery creating custom wedding cakes, cupcakes and dessert tables for Smoky Mountain weddings.	sweetscakestudio@gmail.com		https://sweetscakestudio.com/	https://www.instagram.com/sweets_cake_studio/
Rellek Films	Videography		Knoxville	Tennessee	Knoxville and beyond	Husband-and-wife team Tommy and Nicole, long-time Knoxville locals, making unscripted documentary-style wedding films.	rellekfilms@gmail.com		https://rellekfilms.com/	https://www.instagram.com/rellekfilms/
SK Videography	Videography		Knoxville	Tennessee	All of East Tennessee	Knoxville husband-and-wife team Steve and Kat filming cinematic wedding films, from ceremony-only coverage to full-day packages.			https://www.skvideography.com/	https://www.instagram.com/s.k.videography/
`,
  },
  {
    name: "Memphis: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Rob+Deanna	Photography		Memphis	Tennessee		Husband-and-wife wedding photography team covering Memphis weddings and engagements, from Dixon Gallery ceremonies to Annesdale Mansion.	info@robanddeanna.com		https://robanddeanna.com/	
Michelle Evans Art	Photography		Memphis	Tennessee		Memphis wedding photographer with a relaxed, intimate style who gets to know each couple well before the day itself.	hello@michelleevansart.com		https://www.michelleevansart.com/	https://www.instagram.com/michelleevansart/
Sarai Lange Photography	Photography		Memphis	Tennessee	Memphis and the Mid-South	Wedding photographer focused on the connections between a couple and their guests, with a calm, unhurried approach on the day.			https://www.sarailangephotography.com/	https://www.instagram.com/sarailangephotography/
Elizabeth Hoard Photography	Photography		Memphis	Tennessee	Couples throughout the United States and destinations worldwide	Memphis-based wedding photographer working since 2013, pairing classic portraits with candid, light-hearted moments.			https://www.elizabethhoardphotography.com/	https://www.instagram.com/elizabethhoardphotography/
Incredibly Wee Photography	Photography		Memphis	Tennessee		Memphis photographer Esmee Kyles shoots weddings, portraits and events in a bold, vivid style that lets couples be themselves.	hello@incrediblywee.com	(901) 483-6141	https://www.incrediblywee.com/	https://www.instagram.com/incrediblywee/
Infinity Events	Planning		Memphis	Tennessee	Memphis, Chicago, Austin and worldwide	Certified planners offering full, partial and month-of wedding planning, with more than a decade of events across Memphis and beyond.	emma@infinityeventsmemphis.com	(901) 412-7451	https://www.infinityeventsmemphis.com/	https://www.instagram.com/infinityeventsmemphis/
Purple Door Planning	Planning		Memphis	Tennessee	Tennessee, Mississippi and Arkansas	Master-certified wedding planning firm with 300-plus events behind it, experienced in multicultural celebrations from Nigerian to Korean.	info@purpledoorplanning.com	(901) 497-9011	https://www.purpledoorplanning.com/	
Dani Cymone Events	Planning		Memphis	Tennessee	Tennessee, Arkansas and Mississippi, plus destination weddings	Memphis wedding planner and designer who also rents décor and organises destination weddings in the Caribbean and Mexico.	hello@danicymoneevents.com	(901) 492-1091	https://www.danicymoneevents.com/	https://www.instagram.com/dani_cymone_events/
Tailored For You Weddings & Events	Planning		Bartlett	Tennessee	Memphis, Jackson, Nashville, Oxford MS and surrounding areas	Planning firm led by a master-certified planner, with collections from full planning to virtual coaching, micro-weddings and elopements.	info@tailoredforyouplanning.com	(901) 738-0466	https://tailoredforyouplanning.com/	https://www.instagram.com/tailoredforyouplanning/
Lynn Doyle Flowers & Events	Florals	6225 Old Poplar Pike	Memphis	Tennessee		Family florist founded in 1937 and now five generations on, designing wedding and event flowers from its East Memphis shop.		(901) 323-4521	https://www.lynndoyleflowersandevents.com/	https://www.instagram.com/lynndoyleflowers/
Pugh's Wedding Flowers	Florals		Memphis	Tennessee		Wedding and events team of a family-owned Memphis florist of over 40 years, designing in styles from garden to moody and artistic.		(901) 363-6744	https://www.pughsweddingflowers.com/	https://www.instagram.com/pughsweddingsandevents/
Premier Flowers	Florals		Memphis	Tennessee	Memphis, Germantown, Cordova, West Memphis and surrounding areas	Memphis studio florist with no walk-ins, making bridal bouquets and centrepieces, with work seen on local TV and NBC's Bluff City Law.	premierflowers901@gmail.com	(901) 618-2661	https://premierflowerstn.com/	https://www.instagram.com/premierflowersmemphis/
M10 DJ Company	Music		Memphis	Tennessee	Memphis and the Mid-South	Memphis wedding DJ company that reads the room rather than playing preset lists, with 500-plus weddings and events to date.	info@m10djcompany.com	(901) 410-2020	https://www.m10djcompany.com/	
Cooper Union Band	Music	408 South Front Street	Memphis	Tennessee		LGBTQ-owned party band of up to ten musicians, also offering jazz and cocktail sets and string ensembles for ceremonies.	info@cooperunionband.com	(270) 635-1921	https://www.cooperunionband.com/	https://www.instagram.com/cooperunionband/
Groove Factor Live	Music		Memphis	Tennessee	Alabama, Mississippi, Arkansas, Texas, Louisiana, Georgia and Oklahoma	Memphis party band playing everything from Motown to current dance hits, now offering DJ sets alongside the live show.		(404) 423-1607	https://groovefactorlive.com/	https://www.instagram.com/groovefactorlive/
Simply Southern Catering Co.	Catering	2886 Walnut Grove Road	Memphis	Tennessee	Memphis metropolitan area and surrounding areas	Memphis caterer for weddings and celebrations, known for Southern menus and elaborate food displays such as gourmet bread service.	info@eatsimplysouthern.com	(901) 440-0089	https://www.eatsimplysouthern.com/	
A Moveable Feast Catering	Catering	1291 Tully St	Memphis	Tennessee	Greater Memphis and the Mid-South	Memphis caterer running two styles: upscale menus as A Moveable Feast and casual barbecue as Hog Wild, both available for weddings.	info@amoveablefeastcatering.com	(901) 522-9453	https://amoveablefeastcatering.com/	https://www.instagram.com/hogwild_amf/
Draper's Catering	Catering	6116 Macon Rd	Memphis	Tennessee	Memphis and the Mid-South	Off-site caterer offering plated tastings, waiting staff, bartending and clean-up for weddings across the Memphis area.	info@draperscatering.com	(901) 385-7788	https://draperscatering.com/	https://www.instagram.com/draperscatering/
Donelson's Catering	Catering	8225 Dexter Rd, Ste 107	Cordova	Tennessee	Mid-South	Minority-owned Cordova caterer run by Wendell and Kim for nearly two decades, catering wedding receptions and corporate events.	events@donelsonscatering.com	(901) 757-4300	https://www.donelsonscatering.com/	https://www.instagram.com/donelsonscatering/
Kimberly Yasmine Makeup	Hair & Makeup	841 S Cooper Street	Memphis	Tennessee		Memphis bridal makeup studio specialising in soft glam, with more than 1,200 brides done and hair and makeup for the bridal party.			https://kimberlyyasmine.com/	
Mandie J Pro	Hair & Makeup	5007 Black Rd, Suite 230	Memphis	Tennessee		Travelling makeup artist and hairstylist with TV and film experience, offering bridal looks built to last through the day.	info@mandiej.com	(901) 229-1387	https://www.mandiej.com/	https://www.instagram.com/mandiejpro/
Memphis Makeup Artists	Hair & Makeup	2962 North Stage Plaza	Bartlett	Tennessee	Memphis and surrounding areas	Team of licensed cosmetologists and makeup artists, working since 2018, who do on-site bridal party hair and makeup at hotels or venues.		(901) 730-6517	https://memphismakeup.com/	https://www.instagram.com/memphismakeupdotcom/
MyMoniCakes	Cake		Memphis	Tennessee	Memphis metro and the Tennessee, Arkansas and Mississippi tri-state area	Family-owned Memphis boutique cake studio baking everything from scratch, making custom wedding cakes to each couple's design.	monica@mymonicakes.com	(901) 605-7065	https://mymonicakes.com/	https://www.instagram.com/mymonicakes/
Frost Bake Shop	Cake	1016 W Poplar Ave, Suite 107	Collierville	Tennessee		Family-owned scratch bakery since 2004 with shops in East Memphis, Collierville and Lakeland, offering wedding cake tastings.	cakes@frostbakeshop.com	(901) 232-7555	https://www.frostbakeshop.com/	
Muddy's Bake Shop	Cake	2497 Broad Ave	Memphis	Tennessee		Broad Avenue bake shop open since 2008, taking custom layer and tiered cake orders for weddings alongside its pies and other bakes.			https://www.muddysbakeshop.com/	https://www.instagram.com/muddysbakeshop/
FJ Originals	Videography		Memphis	Tennessee	Memphis and the Southeast	Husband-and-wife team Felipe and Jess making documentary wedding films that favour candid moments over polished spectacle.	hello@fjoriginals.com		https://www.fjoriginals.com/	https://www.instagram.com/fjoriginals/
Dreams Film Company	Videography		Memphis	Tennessee		Family-run Memphis film company making cinematic wedding videos, with packages that combine videography and photography.	dkgdream@gmail.com	(901) 215-8364	https://www.dreamsfilmcompany.com/	
Matt Phoenix	Videography		Memphis	Tennessee	Memphis and destinations worldwide	Memphis-based wedding photographer and videographer offering cinematic highlight films alongside photo coverage.			https://www.mattpphoto.com/	https://www.instagram.com/mattpphoto1/
`,
  },
  {
    name: "Chattanooga: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Anh Bao	Photography		Chattanooga	Tennessee	Chattanooga and beyond	Chattanooga photographer shooting weddings, engagements and family portraits, with fine art prints offered alongside her session work.	anhbao@anhbao.com	(423) 521-5138	https://www.anhbao.com/	https://www.instagram.com/anhbao.photography/
Cinderella Wedding Co	Photography	1806 Madison St	Chattanooga	Tennessee	Chattanooga and beyond	Photography and videography company with a Madison Street studio, shooting weddings and elopements in a modern, candid style.			https://cinderellawedding.co/	https://www.instagram.com/cinderellawedding.co/
Daisy Moffatt Photography	Photography		Chattanooga	Tennessee	Chattanooga and destinations	Chattanooga wedding photographers who also shoot engagements and family sessions, and travel for destination weddings.	daisy@daisymphotography.com	(423) 386-5324	https://daisymphotography.com/	
Emily Lester Photography	Photography		Chattanooga	Tennessee		Wedding and elopement photographer who works in natural light and favours adventurous, outdoor settings.	emily@emilylesterphotography.com		https://www.emilylesterphotography.com/	https://www.instagram.com/emilylesterphotography/
Before the Vows	Planning		Chattanooga	Tennessee	Chattanooga and the Southeast	Wedding planning and coordination from proposal through reception, with packages for the whole run of events.	infobeforethevows@gmail.com	(423) 250-3963	https://www.beforethevowsllc.com/	https://www.instagram.com/beforethevows_/
Catilyn Devone Weddings	Planning		Chattanooga	Tennessee	Chattanooga and beyond	Chattanooga wedding planner and day-of coordinator who is happy to travel to the couple's venue.			http://www.catilyndevoneweddings.com/	https://www.instagram.com/catilyndevone_weddings/
Loga Weddings	Planning	7000 Lee Highway, Suite 600	Chattanooga	Tennessee	Chattanooga	Chattanooga company offering full wedding planning and day-of coordination.		(423) 693-9906	https://www.logaweddings.com/	
The Best Day Weddings	Planning		Chattanooga	Tennessee	Chattanooga and East Tennessee	Solo wedding coordinator and event planner offering full planning, partial planning and day-of coordination in East Tennessee.			https://www.thebestdayweddings.com/	https://www.instagram.com/thebestdayweddingcoordinating/
With Class Weddings	Music		Chattanooga	Tennessee	Tennessee, Georgia and Alabama	Chattanooga coordination company whose lead DJ Mark runs ceremony sound, emcee duties and the dance floor.		(423) 314-3094	https://www.withclassllc.com/	https://www.instagram.com/withclassllc/
Complete Weddings + Events Chattanooga	Music		Chattanooga	Tennessee	Chattanooga and nearby	Bundled wedding services in Chattanooga, from DJs and emcees to photo, video, photo booth and day-of coordination.		(678) 398-7868	https://completewedo.com/chattanooga/	https://www.instagram.com/completechattanooga/
Golden Gate Entertainment	Music		Chattanooga	Tennessee	Chattanooga	Chattanooga DJ, host and MC service for weddings and parties, with photo booths and lighting effects available.	kyle.goldengateentertainment@gmail.com	(423) 315-2990	https://www.goldengate-entertainment.com/	https://www.instagram.com/goldengateent/
Scenic Event Solutions	Music		Chattanooga	Tennessee	Chattanooga and Northeast Georgia	Chattanooga DJ service for weddings, adding photo booth and event lighting across Chattanooga and Northeast Georgia.	info@sceniceventsolutions.com	(423) 645-1565	https://sceniceventsolutions.com/	https://www.instagram.com/sceniceventsolutions/
May Flowers	Florals	800 N Market St	Chattanooga	Tennessee	Chattanooga	North Shore floral design studio led by florist Christy Staven, focused on wedding and event flowers.		(423) 486-5320	https://www.mayflowerscha.com/	https://www.instagram.com/mayflowerscha/
Petal Pushers	Florals	8827 Standifer Gap Road	Chattanooga	Tennessee	Chattanooga	Chattanooga florist making custom wedding flowers alongside funeral work, subscription florals and daily bouquets.	hello@petalpusherschatt.com	(423) 424-4321	https://www.petalpusherschatt.com/	
Summerfield Studio Floral Design	Florals	1209 Taft Highway	Signal Mountain	Tennessee	Chattanooga and beyond	Boutique floral design studio on Signal Mountain creating curated wedding and event florals around Chattanooga.		(423) 394-9346	https://www.summerfieldstudiofloral.com/	https://www.instagram.com/summerfieldstudiofloral/
Petaline Floral	Florals		Chattanooga	Tennessee	Chattanooga and the Southeast	Fine-art wedding florist designing custom, organic arrangements for couples in Chattanooga and across the Southeast.			https://www.petaline.co/	https://www.instagram.com/petalinefloral/
GRAFE Studio	Florals	4009 Tennessee Ave	Chattanooga	Tennessee	Chattanooga	Chattanooga floral studio with its own events team, offering wedding flowers from a Tennessee Avenue shop.	grafestudio.events@epbfi.com		https://www.grafestudiofloralartists.com/	https://www.instagram.com/grafestudio/
Flowers by Tami	Florals		Chattanooga	Tennessee	Chattanooga and surrounding areas	Wedding florist Tami McAllister, making bouquets and arrangements for Chattanooga-area brides.	tami@flowersbytamichatt.com	(423) 402-1228	http://www.flowersbytamichatt.com/	https://www.instagram.com/flowersbytami/
Good Company Catering	Catering	5110 Hixson Pike, Suite D	Chattanooga	Tennessee	Chattanooga	Wedding and event caterer serving Southern food with global touches, with a tasting room at the Dwell Hotel.	megan@goodcompanycatering.com	(423) 785-7959	https://www.goodcompanycatering.com/	https://www.instagram.com/good.co.catering/
Catering by Alan	Catering		Chattanooga	Tennessee	Chattanooga	Chattanooga caterer in business since 1995, handling weddings, corporate events and parties.	cateringbyalan@gmail.com	(423) 593-8686	https://cateringbyalan.com/	
Silverware Affair Catering	Catering		Chattanooga	Tennessee	East Tennessee and North Georgia	Wedding and event caterer that also supplies bartending and equipment rentals across East Tennessee and North Georgia.			https://silverwareaffair.com/	https://www.instagram.com/asilverwareaffair/
Catering Cart	Catering		Chattanooga	Tennessee	Chattanooga	Chattanooga caterer offering wedding menus of appetisers, charcuterie and grazing boards and buffets, with bartending and staffing.		(423) 280-5432	https://catering-cart.com/	https://www.instagram.com/cateringcart/
Chattanooga Catering	Catering		Chattanooga	Tennessee	Chattanooga and Cleveland, TN	Caterer serving wedding receptions at Chattanooga venues and in Cleveland, from drop-off meals to formal full-service events.			https://chattanoogacatering.com/	https://www.instagram.com/chattanoogacatering/
Main Street Meats	Catering	217 East Main Street	Chattanooga	Tennessee	Chattanooga	Butcher shop and restaurant on Main Street that caters everything from a grazing table to a full wedding feast.		(423) 602-9568	https://www.mainstreetmeatschatt.com/catering-chattanooga-tn	https://www.instagram.com/mainstreetmeats/
Luxe + Lumi	Hair & Makeup		Chattanooga	Tennessee	Tennessee and Georgia	On-site bridal beauty team of makeup artists and hair stylists, travelling to weddings across Tennessee and Georgia.	luxeandlumico@gmail.com		https://luxeandlumico.com/	https://www.instagram.com/luxeandlumico/
Natural Beauty Nook	Hair & Makeup		Chattanooga	Tennessee	Chattanooga	Chattanooga salon offering bridal hair and makeup trials and on-site wedding-day services alongside everyday beauty work.		(423) 596-2725	https://www.naturalbeautynook.com/bridal-makeup-artist/	https://www.instagram.com/naturalbeautynook/
Sweet Angel Cakes	Cake	6331 E Brainerd Rd	Chattanooga	Tennessee	Chattanooga	Brainerd Road bakery making custom wedding cakes, plus special-occasion cakes, with a modest-priced starting point.	sweetangelcakes@yahoo.com	(423) 485-3473	https://www.mysweetangelcakes.com/	https://www.instagram.com/sweet_angel_cakes/
Six Little Teacups Bakery	Cake		Chattanooga	Tennessee	Chattanooga	Chattanooga bakery taking custom wedding and birthday cake orders alongside cake-decorating classes and tea parties.			https://www.sixlittleteacups.com/	https://www.instagram.com/sixlittleteacupsbakery/
Chattanooga Custom Cakes	Cake		Chattanooga	Tennessee	Chattanooga	Chattanooga custom cake maker taking orders for wedding and special-occasion cakes.		(423) 595-2250	https://www.chattanoogacustomcakes.com/	
B's Sweets	Cake	440 Timberlinks Dr	Signal Mountain	Tennessee	Chattanooga	Signal Mountain bakery whose wedding cakes range from tiny elopement cakes to detailed tiered designs.	cakeorders@bssweets.com	(423) 521-0311	https://www.bssweets.com/	https://www.instagram.com/bssweets/
Erin Mary Films	Videography		Chattanooga	Tennessee	Chattanooga, North Georgia and beyond	Chattanooga wedding videographer making cinematic, story-led films for local and destination couples.	chelsea@erinmaryfilms.com		https://erinmaryfilms.com/	https://www.instagram.com/erinmaryfilms/
Stewart Films	Videography		Chattanooga	Tennessee	Chattanooga, Nashville and Knoxville	Husband-and-wife film team based in Chattanooga making cinematic wedding films for couples around Tennessee.			https://stewartfilms.co/	
Wild Heart Wedding Films	Videography		Chattanooga	Tennessee	Chattanooga	Chattanooga videography company specialising in adventurous weddings and elopements.	wildheartweddingfilm@gmail.com		https://www.wildheartweddingfilms.com/	https://www.instagram.com/wildheart_weddingfilms/
VE Videography	Videography		Chattanooga	Tennessee	Chattanooga and destinations	Documentary-style wedding filmmaker offering highlight films, full-length films, elopements and engagement films.	info@vevideography.com	(423) 486-2214	https://www.vevideography.com/	https://www.instagram.com/vevideography/
`,
  },
  {
    name: "Nashville: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Rebecca Musayev Photography	Photography		Nashville	Tennessee	Nashville and destination weddings	Nashville wedding photographer whose site features real weddings and names Style Me Pretty, Wed Society and Southern Bride among her publications.			https://www.rebeccamusayev.com/	
Laura K. Allen Photography	Photography		Nashville	Tennessee	Nashville, Franklin, Mt. Juliet, Lebanon, Bellevue, Brentwood, Hendersonville	Nashville photographer with a wedding and engagement portfolio and more than 300 weddings behind her, covering most of the towns around the city.			https://nashvilletnweddingphotographers.com/	https://www.instagram.com/laurakallenphoto/
Kathy Thomas Photography	Photography		Nashville	Tennessee	Tennessee, Wyoming, Montana, Florida and worldwide	Nashville and Orlando wedding photographers whose portfolio includes celebrations at Trinity View Farm in Franklin, alongside destination work.	kathythomasphotography@gmail.com		https://www.kathythomasphotography.com/	https://www.instagram.com/kathythomasphoto/
Lizzy Oakley Photography	Photography		Nashville	Tennessee	Franklin and Williamson County, Nashville and Davidson County, Brentwood, Murfreesboro and Rutherford County	Nashville photographer with wedding, elopement and engagement galleries and dedicated pages for Franklin and Murfreesboro couples.			https://lizzyoakley.com/	https://www.instagram.com/lizzyoakleyphotography/
CM Event Design	Planning		Nashville	Tennessee	Nashville and Middle Tennessee	Nashville studio founded in 2019 offering custom full-service planning or a 90-day management option, with Franklin estates among its usual venues.	info@cmeventdesign.com	(615) 268-2918	https://cmeventdesign.com/nashville-wedding-planner/	https://www.instagram.com/cm.event.design/
Weddings & Events by Raina	Planning	112 South Maple Street	Murfreesboro	Tennessee	Nashville, Murfreesboro, Franklin, Brentwood, Smyrna, Gallatin and Greater Middle Tennessee	Murfreesboro planner and licensed officiant handling full, month-of and day-of planning, including Hindu, Sikh, Jewish and multicultural weddings.	weddingsbyraina@gmail.com	(615) 956-1313	https://eventsbyraina.com/	https://www.instagram.com/weddingsandeventsbyraina/
EBJ & Company	Planning		Nashville	Tennessee		Nashville wedding planners offering full-service planning and design as well as coordination and event management, with client testimonials on the site.	casey@ebjandcompany.com		https://ebjandcompany.com/	https://www.instagram.com/ebjandcompany/
Beautiful Things Floral & Design	Florals		Nashville	Tennessee		Nashville wedding florist whose site shows bridal bouquets, centrepieces and ceremony flowers, with real-wedding examples on its blog.	info@beautifulthingsfloralanddesign.com		https://www.beautifulthingsfloralanddesign.com/	https://www.instagram.com/beautifulthingsfloralanddesign/
The Bloom House	Florals		Nashville	Tennessee		Nashville wedding florist with photo galleries of real couples' flowers, reachable by phone or through the contact form on its site.		615-624-0506	https://thebloomhousetn.com/	https://www.instagram.com/thebloomhouse.tn/
Harmony Fields	Florals		Nashville	Tennessee	Middle Tennessee and beyond, with pages for Brentwood and Franklin	East Nashville wedding florist that designs for any destination and shares brides' stories alongside a large gallery of its floral work.		(513) 256-4689	https://harmonyfieldsnashville.com/	https://www.instagram.com/harmonyfieldsnashville/
Bloom & Bounty	Florals		Nashville	Tennessee		Nashville flower studio with wedding bouquets and arrangements, linked portfolios from two photographers and a downloadable wedding story guide.	weddings@bloomandbounty.com		https://bloomandbounty.com/weddings	https://www.instagram.com/bloom_bounty/
Top Tier	Music		Nashville	Tennessee		Nashville wedding and corporate band that can be booked in several sizes with horns, plus DJ services, with photo and video pages on its site.		(615) 319-6318	https://toptierband.com/	https://www.instagram.com/toptierbandofficial/
Burning Las Vegas	Music		Nashville	Tennessee		Nashville live band for wedding receptions, with performance videos, guest reviews and a Couples' Choice Award displayed on its site.			https://www.burninglasvegas.com/	https://www.instagram.com/burninglasvegas/
Party Down Live Entertainment	Music		Mount Juliet	Tennessee		Mount Juliet live band for weddings and corporate events, with a wedding section and a package that pairs the band with a DJ.	partydownlive@gmail.com	615-823-0085	https://www.partydownlive.com/	https://www.instagram.com/partydownlive/
Choice DJs	Music		Nashville	Tennessee	All of Middle Tennessee, including Williamson and Rutherford counties	Nashville DJ company handling ceremony sound, emceeing, uplighting and photo booths, with wedding client reviews on its site.	info@choicedjs.com	615 243 8570	https://choicedjs.com/	https://www.instagram.com/choicedjs/
The Alley on Main	Catering	223 W Main St.	Murfreesboro	Tennessee	Murfreesboro, Nashville, Franklin, Brentwood, Hendersonville, Lebanon, Mt. Juliet and across Middle Tennessee	Murfreesboro restaurant that caters weddings and other events, with its own wedding catering page and delivery across Middle Tennessee.		(615) 203-3498	https://alleyonmain.com/catering/	https://www.instagram.com/alleyonmain/
Sandra's Catering	Catering		Nashville	Tennessee	Nashville and Middle Tennessee, generally within one hour, including Franklin, Brentwood, Murfreesboro and Dickson	Nashville caterer that provides wedding meals and wedding cakes, travelling to towns within about an hour of the city.	info@sandrascatering.com	615-662-1909	https://sandrascatering.com/wedding-catering-nashville-tn	https://www.instagram.com/sandrascatering215/
Two Fat Men Catering	Catering	1331 West Main St.	Lebanon	Tennessee	Lebanon, Mt. Juliet, Murfreesboro, Nashville, and Davidson, Williamson, Smith and Wilson counties	Lebanon caterer that says it has handled hundreds of weddings, serving Wilson County and the wider Nashville area.	info@twofatmencatering.com	615.443.4007	https://twofatmencatering.com/	https://www.instagram.com/twofatmencatering/
Claire Mints Makeup Artistry	Hair & Makeup		Nashville	Tennessee	Within 30 miles of Nashville with free travel, plus destination weddings	Nashville bridal makeup artist who also styles hair, with soft-glam and classic looks, free travel inside 30 miles and a bridal portfolio.	hello@clairemints.com	806-679-7232	https://www.clairemints.com/bridal	https://www.instagram.com/clairemints_mua/
Willow Beauty Collective	Hair & Makeup	1648 Westgate Circle, Suite 234	Brentwood	Tennessee	Middle Tennessee, including Nashville, Brentwood and Franklin	Brentwood studio of artist Morgan Ebright, offering wedding hair and makeup, with a real wedding at The Loveless Barn on its feature list.			https://willowbeautycollective.com/	https://www.instagram.com/morganebright/
Nashville Wedding Stylist by Berry Hill Beauty	Hair & Makeup		Nashville	Tennessee	Middle Tennessee and Southern Kentucky	Nashville bridal hair and makeup team operating since 2015, with bride testimonials and press features displayed on its site.	hello@berryhillbeauty.com	615-212-9660	https://www.nashvilleweddingstylist.com/	https://www.instagram.com/nashvilleweddingstylist/
Braids and Blush	Hair & Makeup		Nashville	Tennessee		Nashville hair and makeup artist licensed in Tennessee who says she has styled over a thousand brides, with a portfolio page.			https://braidsandblush.com/	https://www.instagram.com/braidsandblushTN/
Classic Cakes by Leslie	Cake		Brentwood	Tennessee	Nashville, Brentwood and Franklin	Brentwood cake designer making custom wedding cakes since 1983, with a flavours and prices page and a booking process.	weddingcake@comcast.net	(615) 260-4099	https://www.classiccakes.net/	https://www.instagram.com/classiccakesbyleslie/
La Crème Wedding Cakes	Cake		Murfreesboro	Tennessee	Greater Nashville and surrounding areas	Murfreesboro wedding-cake designer working by appointment, serving Middle Tennessee couples and the Nashville area.	weddingcakes@lacremecakes.net	615-530-7850	https://lacremecakes.net/about-us/	https://www.instagram.com/la_creme_wedding_cakes/
Julia's Homestyle Bakery	Cake	1911 Medical Center Parkway, Ste B	Murfreesboro	Tennessee		Murfreesboro bakery that also offers designer wedding cakes alongside cookies, cupcakes and pies, with a dedicated wedding page.		615.890.2253	https://www.myjulias.com/	https://www.instagram.com/juliashomestylebakery/
Katelin Hayes Desserts	Cake		Nashville	Tennessee		Nashville dessert maker that lists wedding cakes among its work, reachable by phone or email through the site.		731-446-2050	https://www.katelinhayes.com/	https://www.instagram.com/katelinhayesdesserts/
Annie Mae's Bakery	Cake		Nashville	Tennessee	Throughout the Nashville area	Nashville custom cake bakery whose site shows wedding cakes alongside birthday and special-occasion cakes.			https://www.ambcakes.com/	https://www.instagram.com/anniemaesbakery/
Big Hill Productions	Videography		Gallatin	Tennessee		Gallatin team with over 15 years of wedding film and photography experience, filming Nashville and Tennessee weddings.	bighillpro@bighillproductions.com		https://bighillproductions.com/	https://www.instagram.com/bighillproductions/
Colling Films	Videography		Nashville	Tennessee		Wedding videographers who describe a cinematic, modern style with highlight films, based out of Nashville.	phillip@collingfilms.com	815-922-2016	https://www.collingfilms.com/	https://www.instagram.com/collingfilms/
Exposure Essence	Videography		Murfreesboro	Tennessee	Middle Tennessee, including Nashville, Franklin, Brentwood, Smyrna and Clarksville	Murfreesboro videographers whose wedding films cover venues from Nashville and Brentwood to Lebanon and Bell Buckle.		(615) 603-8216	https://exposureessence.com/wedding-videographer-murfreesboro-tn	https://www.instagram.com/exposure_essence_photography/
Peerless Films	Videography		Nashville	Tennessee	Nashville and beyond	Nashville wedding videographer with over ten years' experience, offering teaser, highlight and full-length films with a portfolio page.	info@peerlessfilms.com	615-439-2028	https://peerlessfilms.com/	https://www.instagram.com/peerlessfilms/
`,
  },
  {
    name: "Knoxville: planning, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Wed Knoxville	Planning	5404 Swallowtail Lane	Knoxville	Tennessee	East Tennessee, also travels for destination and out-of-state weddings	Planning team offering full and partial wedding planning and day-of coordination, with decor and floral services too.	misty@wedknoxville.com	865.410.2096	https://www.wedknoxville.com/	https://www.instagram.com/wed_knoxville/
Lindsey Mae Events & Designs	Planning		Knoxville	Tennessee	Knoxville and East Tennessee	Wedding and event planning firm covering full planning, day-of coordination, decor design and florals, operating since 2015.			https://lindseymaeeventsanddesigns.com/	https://www.instagram.com/lindseymaedesigns/
Ogle Entertainment	Music		Knoxville	Tennessee	Knoxville and surrounding areas	Knoxville mobile DJ and lighting company providing music and enhanced lighting for weddings, proms, birthdays and corporate events.		865-970-3429	https://ogleentertainment.com/	https://www.instagram.com/godjogle/
Sequoyah Entertainment	Music		Knoxville	Tennessee		Mobile DJ and lighting design company providing wedding and event entertainment with an emphasis on personal service.		865-335-5722	https://www.sequoyahentertainment.com/	https://www.instagram.com/sequoyahentertainment/
Music in Motion DJ & Lighting	Music		Knoxville	Tennessee	Knoxville	DJ and lighting company for weddings, parties, school dances and corporate events, with personalised planning for each client.	info@musicinmotionprodj.com	(865) 237-9814	https://musicinmotionprodj.com/	https://www.instagram.com/coreyozair/
Rothchild Catering	Catering	8807 Kingston Pike	Knoxville	Tennessee	Knoxville, Oak Ridge, Morristown, Sevierville, Pigeon Forge, Gatlinburg, Crossville and surrounding East Tennessee	Knoxville caterer and event centre, in business since 1984, offering full-service catering and venue hosting for weddings and other events.		865-690-0103	https://www.rothchildcatering.com/	https://www.instagram.com/rothchildcatering/
Classy Caterer	Catering		Knoxville	Tennessee	Knoxville and East Tennessee	Caterer founded in 2018 offering full-service, drop-off and custom catering for wedding and corporate events, known for handmade cheesecakes.		(865) 406-5477	https://www.classycaterer.com/	https://www.instagram.com/classycatererknoxville/
Bissel Catering	Catering		Powell	Tennessee	Knoxville and surrounding East Tennessee	Family-owned caterer handling weddings, corporate events and private parties, with an emphasis on fresh ingredients and personal service.		(865) 696-2447	https://bisselcatering.com/	
Rvl'd Beauty	Hair & Makeup		Knoxville	Tennessee	East Tennessee and destination weddings; travel fees may apply	Clean-beauty wedding hair and makeup studio offering skin-focused looks, bridal prep guidance, lash services and in-studio appointments.			https://www.rvldbeauty.com/	
Effortless Beauty	Hair & Makeup	1304 Atlantic Ave.	Knoxville	Tennessee	Knoxville, with on-site services at the client's venue	Wedding hair and makeup studio offering in-studio and on-site appointments, with certified stylists and a dedicated coordinator.			https://www.theeffortlessbeautyco.com/	https://www.instagram.com/theeffortlessbeauty/
grow	Hair & Makeup	5344 Kingston Pike	Knoxville	Tennessee		Knoxville salon offering bridal hair and makeup with trials and on-location services, using L'ANZA and Glo Skin Beauty products.		865-450-5490	https://growknoxville.com/bridal/	https://www.instagram.com/weddingsatgrow/
Belleza Bridal and Special Events	Hair & Makeup		Knoxville	Tennessee		Knoxville hair and makeup service for weddings, proms and special events, with date enquiries made through its website.			https://www.bellezabridal.com/	
Heidi's Bakery	Cake	4505 Greenway Drive	Knoxville	Tennessee	Knoxville and about 36 East Tennessee towns, including Maryville, Oak Ridge, Sevierville and Gatlinburg	Knoxville bakery, operating since 2017, making custom wedding cakes, cupcake towers and dessert tables with tastings and delivery.		(865) 249-6573	https://heidishomecooking.com/	https://www.instagram.com/heidishomecooking/
Foraged Films	Videography		Knoxville	Tennessee	Tennessee and beyond, including Nashville and Asheville	Husband-and-wife team making wedding films intended as keepsakes, with a focus on discretion and intention on the day.	hello@foragedfilms.com	(850) 559-5086	https://www.foragedfilms.com/	https://www.instagram.com/foragedfilms/
Jake Shick Productions	Videography		Knoxville	Tennessee	East Tennessee, the Smoky Mountains and beyond	Knoxville wedding videography team making cinematic films, with wedding-weekend coverage and other video production on offer.			https://jakeshickproductions.com/	https://www.instagram.com/jakeshickproductions/
Hawkins Film Co.	Videography		Knoxville	Tennessee	East Tennessee and the Smoky Mountains, including Gatlinburg, Sevierville, Pigeon Forge and Chattanooga	Husband-and-wife team offering wedding videography and photography, plus portrait, family and newborn sessions.	hawkinsproductionco@gmail.com		https://hawkinsfilmco.com/	https://www.instagram.com/hawkinsfilmco/
Golightly Studios	Videography		Knoxville	Tennessee	Knoxville, Farragut, Lenoir City, Oak Ridge, Maryville, Townsend, Gatlinburg, Pigeon Forge, Sevierville and further afield	Knoxville wedding videography company producing cinematic films of the whole day, including the candid moments in between.			https://www.golightlystudios.com/portfolio/weddings/knoxville-wedding-videography	
Studio Motion Films	Videography		Knoxville	Tennessee	Regularly films in Knoxville, Maryville, Pigeon Forge and Gatlinburg; travels across Tennessee and for destination weddings	Documentary-style wedding filmmakers preserving how the day felt, with drone footage offered when conditions allow.			https://studiomotionfilms.com/	https://www.instagram.com/studiomotionfilms/
`,
  },
  {
    name: "Memphis: planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
The Hardin House	Planning		Memphis	Tennessee		Memphis wedding planning firm offering full planning and design for weddings and other major celebrations.			https://www.thehardinhouse.com/	https://www.instagram.com/thehardinhouse/
Everbloom Design	Florals		Memphis	Tennessee		Boutique Memphis floral studio offering full-service wedding design and smaller intimate-event work with custom pieces.	kristin@everbloomdesign.com		https://www.everbloomdesign.com/pages/weddings	https://www.instagram.com/everbloomdesignmemphis/
Piano's Flowers & Gifts	Florals	4532 Elvis Presley	Memphis	Tennessee	Memphis, with delivery further afield	Family-owned Memphis florist, open since 1982, taking orders for custom wedding and event flowers by consultation.		(901) 345-7670	https://www.pianosflowers.com/	
Mark Anderson's Disc Jockey Attractions	Music		Memphis	Tennessee	Memphis, Collierville, Germantown, Lakeland, Arlington, Bartlett, Eads and Millington	Memphis-area DJ and karaoke service with over 30 years of experience at weddings, corporate events and other celebrations.		901-338-4328	https://www.discjockeyattractions.com/	
DeepBlu Entertainment	Music		Memphis	Tennessee		Memphis wedding DJ and MC service hosting ceremonies and receptions, with help on pre-wedding planning.			https://www.deepblu.net/	https://www.instagram.com/deepbluweddings/
Sanders Catering	Catering	7195 Highway 64	Memphis	Tennessee	Memphis, Collierville, Germantown, Cordova, Bartlett, Arlington, Lakeland, Millington and surrounding areas	Memphis caterer, operating since 1988, serving weddings, corporate events and church functions with Southern-style food.	info@sanderscatering.com	(901) 372-2631	https://www.sanderscatering.com/memphis-caterer	
Simply Done Catering and Events	Catering		Collierville	Tennessee		Collierville full-service caterer designing custom menus for weddings, corporate events and showers, from stations to seated dinners.		901-457-7781	http://www.greatfoodsimplydone.com/	
Janice Allen Salon	Hair & Makeup	2123 West Street, Suite 122	Germantown	Tennessee		Germantown master hairstylist and colourist known for bridal updos, who has styled bridal magazine shoots for over a decade.		901-489-1555	https://www.janiceallen.net/	
Sweet LaLa's Bakery	Cake	6150 Poplar Avenue #118	Memphis	Tennessee	Memphis-area venues for delivery; collection from the bakery	Memphis bakery designing custom wedding and groom's cakes, plus favours and gift boxes.		(901) 654-3646	https://sweetlalas.com/	https://www.instagram.com/sweetlalasbakery/
The Flour Garden	Cake		Memphis	Tennessee		Artisan Memphis cake bakery making wedding cakes and cakes for other celebrations, with a dedicated weddings section on its site.	hello@theflourgardenmemphis.com	(901) 417-7600	https://theflourgardenmemphis.com/	https://www.instagram.com/the_flour_garden/
Something Blue Wedding Films	Videography		Memphis	Tennessee	Destination weddings worldwide	Memphis studio making cinematic, handcrafted wedding films, from backyard ceremonies to luxury destination weddings.			https://www.somethingblueweddingfilms.com/	https://www.instagram.com/michaelallen/
STCVISUALS	Videography		Memphis	Tennessee	TN, AR, MS, TX, NC, KY and beyond	Memphis studio producing cinematic wedding films and photographs, taking on a limited number of weddings each season.			https://stcvisuals.com/	https://www.instagram.com/stc.visuals/
Lynn Productions	Videography		Memphis	Tennessee	Memphis and surrounding areas; has filmed across the Mid-South and beyond	Wedding videography company producing highlight films for couples across the Mid-South and further afield.			https://lynnproductions.net/	
`,
  },
  {
    name: "Gatlinburg and the Smokies: photography, planning, florals, music, catering and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Mountain Escape Photography	Photography		Gatlinburg	Tennessee	Gatlinburg, Pigeon Forge, Townsend and Wears Valley	Photographer covering weddings, elopements and couple or family sessions around Gatlinburg, Pigeon Forge, Townsend and Wears Valley.	info@mountainescapephotography.com	(865) 293-0199	https://mountainescapephotography.com/	https://www.instagram.com/mountainescape/
Ashley Leffew Photography	Photography		Gatlinburg	Tennessee	Great Smoky Mountains National Park and beyond	Gatlinburg photographer documenting weddings, adventurous elopements and family sessions in and around the Great Smoky Mountains National Park.	ashleyleffewphotography@gmail.com		https://ashleyleffewphotography.com/	https://www.instagram.com/ashleyleffewphotography/
New Beginnings Photography	Photography		Gatlinburg	Tennessee	Gatlinburg and the Smoky Mountains	Gatlinburg wedding and elopement photographer, run by Eric Gebhart since 2004, offering simple packages at Smokies locations such as Cades Cove.	info@perfectweddingpics.com	865-484-6243	https://www.perfectweddingpics.com/	
Don Fields Photography	Photography		Sevierville	Tennessee	Gatlinburg, Pigeon Forge and Sevierville	Family-run Sevierville studio shooting on-location weddings, elopements and family portraits, with wedding film coverage also offered.	don@donfieldsphotography.com	865-774-7610	https://www.donfieldsphotography.com/	
ST Photography	Photography		Sevierville	Tennessee	Great Smoky Mountains	Husband-and-wife team in Sevierville photographing adventure-style weddings, elopements and family sessions in the Smoky Mountains.	stphotogallery@gmail.com	(865) 321-5341	http://stphotogallery.net/	https://www.instagram.com/stphotogallery/
Effortless Elopements	Planning		Gatlinburg	Tennessee	Gatlinburg and the Great Smoky Mountains	Gatlinburg elopement planner and photographer who handles the officiant, permits and locations for all-inclusive Smoky Mountain ceremonies.		(865) 268-3661	https://www.gatlinburgelopements.com/	https://www.instagram.com/effortlesselopementsgatlinburg/
Great Smoky Mountain Elopements	Planning		Gatlinburg	Tennessee	Great Smoky Mountains	Elopement planning for the Gatlinburg area with photography, film, ceremony coordination and permit guidance at Smokies locations.	info@greatsmokymountainelopements.com	865-248-9577	https://www.greatsmokymountainelopements.com/	https://www.instagram.com/greatsmokymountainelopements/
Appalachian Wedding Company	Planning		Gatlinburg	Tennessee	Gatlinburg and the Smoky Mountains	Gatlinburg company offering planning and coordination for simple, lower-cost weddings and elopements, including chapel and riverside options.		865-674-5683	https://appalachianweddingcompany.com/	https://www.instagram.com/appalachianweddingco/
The White Pheasant	Planning		Sevierville	Tennessee	Smoky Mountain region of East Tennessee	Sevierville wedding and special-event design and planning business that also hires out modern vintage rentals.	jamey@thewhitepheasant.net	865.246.9933	https://thewhitepheasant.net/	https://www.instagram.com/the_white_pheasant/
Smokey Mountain Sounds	Music		Gatlinburg	Tennessee	Gatlinburg, Pigeon Forge, Sevierville and surrounding areas	Wedding DJ and officiant service for Gatlinburg, Pigeon Forge and Sevierville, with photo booths, lighting and karaoke options.		865.712.1854	https://smokeymountainsounds.com/	https://www.instagram.com/smokeymtnsounds/
Hale Entertainment	Music		Gatlinburg	Tennessee	Great Smoky Mountains region	Gatlinburg DJ and photography company offering ceremony sound, officiant services, photo booths and karaoke for weddings and parties.		865-606-0260	https://gatlinburgentertainment.net/	https://www.instagram.com/hale_entertainment_photography/
DJ Traxx	Music		Pigeon Forge	Tennessee	Pigeon Forge, Gatlinburg, Knoxville and the Great Smoky Mountains	Pigeon Forge DJ providing music for wedding receptions, corporate events and parties across Sevier County and the wider Smokies.	DJTRAXXintheSmokies@gmail.com	865-440-7637	http://pigeonforgedj.com/	
Bloom & Style	Hair & Makeup		Gatlinburg	Tennessee	Gatlinburg, Pigeon Forge and Sevierville, on location	On-location bridal hair and make-up artist travelling to cabins, hotels and venues across Gatlinburg, Pigeon Forge and Sevierville.		(865) 424-0126	https://www.gatlinburgweddinghair.com/	https://www.instagram.com/katerina.makehair/
Sevier Blumen	Florals		Sevierville	Tennessee	Knoxville, Pigeon Forge and Gatlinburg area	Sevierville flower farm supplying wedding flowers, from loose stems for DIY arranging to bespoke bouquets and ceremony designs.			https://sevierblumen.com/	
Gatlinburg Gourmet	Catering		Gatlinburg	Tennessee	Sevier County and the Smoky Mountains	Caterer serving Sevier County weddings, rehearsal dinners and cabin stays, building a custom menu for each couple.	hello@gatlinburggourmet.com	865-438-0779	https://gatlinburggourmet.com/	https://www.instagram.com/gatlinburggourmet/
`,
  },
];

export default batches;
