import type { VendorBatch } from "@/lib/vendor-batches";

// Texas vendor batches. Every row's State is "Texas". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Hill Country: music, videography, cake, planning, florals, hair and makeup, bar, rentals, transport, bridal, photo booths and more",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Midnight Flyer Band	Music		Dripping Springs	Texas	Texas Hill Country	Dripping Springs band playing Tex-Mix covers and originals for wedding receptions, private parties and corporate events.			https://midnightflyerband.com/	
Dynamic Celebrations	Music		Austin	Texas	Dripping Springs, Wimberley, Marble Falls and the wider Texas Hill Country	Austin-based wedding DJ, MC and photo booth company working regularly at Hill Country venues, with officiants also available.	info@dynamiccelebrations.com	512-628-4656	https://dynamiccelebrations.com/	https://www.instagram.com/dynamiccelebrations/
A. Ward Weddings and Events	Music		Austin	Texas	Central Texas, San Antonio and the Hill Country	Austin DJ and MC service offering sound, uplighting and photo booth hire for weddings across Central Texas, operating since 2006.			https://www.atxdjaaron.com/	https://www.instagram.com/atxdjaaron/
Boogie Down DJs	Music		San Antonio	Texas	San Antonio, Boerne and surrounding areas	San Antonio wedding DJ company that also plays proms, quinceañeras and corporate events, and serves Boerne.		210-473-3012	https://boogiedowndjs.us/	
Gold Leader Films	Videography		Fredericksburg	Texas	Fredericksburg, Kerrville, Boerne, San Antonio and Austin	Documentary-style wedding films for couples around the Hill Country, alongside commercial and social media video work.	info@goldleaderfilms.com	830-708-3518	https://goldleaderfilms.com/	https://www.instagram.com/goldleader_films/
Hill Country Video	Videography		Austin	Texas	Fredericksburg, Wimberley, Dripping Springs, Bandera, Kerrville and Johnson City	Austin studio filming weddings, elopements and ranch events across the Hill Country, with drone coverage standard and no travel fee at most venues.			https://hillcountryvideo.com/	
Wildflower Cinema	Videography		New Braunfels	Texas	Texas Hill Country	New Braunfels wedding cinematography business making story-led films for Hill Country couples, with photography also available.	ashley@wildflowercinema.com		https://wildflowercinema.com/	https://www.instagram.com/wildflowercinema/
Hill Country Bakehouse	Cake	200 Main Street	Marble Falls	Texas	Marble Falls and the Highland Lakes	Marble Falls bakery making custom wedding cakes, cupcakes and cookies, with consultations and design collaboration for each couple.	order@hillcountrybakehouse.com	830-572-5007	https://hillcountrybakehouse.com/	https://www.instagram.com/hillcountrybakehouse/
Cake Llama	Cake		Wimberley	Texas	Central Texas	Wimberley dessert caterer making wedding cakes, cake pops and sweet tables for weddings and other events.	Makeitsweet@cakellama.com	210-792-4566	https://www.cakellama.com/	https://www.instagram.com/cake_llama/
Heaven-Pathways-Earth (Rev. Dr. Sheryl T. Martin)	Officiant		Wimberley	Texas	Within 50 miles of Wimberley	Interfaith minister in Wimberley officiating weddings and vow renewals, with optional premarital counselling and ceremony add-ons.		559-779-5510	https://www.heavenpathwaysearth.com/	
Hill Country Selfies	Photo Booth		Fredericksburg	Texas	Fredericksburg and the surrounding Hill Country	Fredericksburg photo booth hire with HD camera, lighting, props and instant digital sharing for weddings and parties.		830-446-3201	https://hillcountryselfies.com/	
Boerne Photo Booth Co.	Photo Booth		Boerne	Texas	Boerne, Fair Oaks Ranch, Bulverde, Comfort and Helotes	Boerne photo booth hire with open-air, 360 video, audio guest book and magic mirror options, staffed by an attendant for weddings.	hello@boernephotoboothco.com	210-722-3512	https://boernephotoboothco.com/	
Hitch & Click	Photo Booth		Johnson City	Texas	Fredericksburg, Dripping Springs, Blanco, Marble Falls, Wimberley and Central Texas	Family-run Johnson City business hiring out a vintage 1950s-style photo booth trailer, with attendant, props and printed strips.			https://www.hitchandclick.com/	
Snaps To Remember	Photo Booth		Spring Branch	Texas	San Antonio, Boerne, Kerrville, Marble Falls and the Texas Hill Country	Spring Branch photo booth company offering mirror, print, glam and digital booths for weddings, corporate events and parties.			https://snapstoremember.com/	https://www.instagram.com/snapstoremembertx/
Weddings by Wendi	Planning		San Marcos	Texas	Austin, Dripping Springs, San Marcos, New Braunfels, Fredericksburg, Wimberley and the Hill Country	Wedding planning and day-of coordination for couples marrying in Austin and the Texas Hill Country, drawing on more than 300 weddings.	concierge@weddingsbywendi.com	512-766-9776	https://weddingsbywendi.com/	
Grant Your Wish Weddings	Planning		Austin	Texas	Dripping Springs, Wimberley, Fredericksburg, Marble Falls, Blanco, Johnson City, New Braunfels	Austin-based coordinator offering day-of and month-of wedding coordination, with a focus on outdoor and ranch weddings across the Hill Country.	hello@grantyourwishweddings.com		https://grantyourwishweddings.com/	https://www.instagram.com/grantyourwishweddings/
House Call Bar Services	Bar		Fredericksburg	Texas	Fredericksburg and the Texas Hill Country	Fredericksburg mobile bar offering craft cocktail service for weddings and other events, including dedicated wedding bartending packages.	housecallbarservices@gmail.com		https://housecallbarservices.com/	https://www.instagram.com/housecallbarservices/
Bartenders4You	Bar		San Antonio	Texas	San Antonio, New Braunfels, Boerne, Austin, Fredericksburg	San Antonio mobile bar company providing wedding bartenders and handcrafted cocktails, travelling to Boerne, Fredericksburg and New Braunfels.			https://bartenders4you.com/	https://www.instagram.com/bartenders4you/
Hill Country Event Rentals	Rentals		New Braunfels	Texas	Austin, New Braunfels, San Antonio and the Texas Hill Country	New Braunfels rental company supplying tents, tables, chairs, linens, bars, dance floors and lighting for events across the Hill Country.	events@rentalshc.com	512-255-0646	https://hillcountryeventrentals.com/	https://www.instagram.com/hceventrentals/
Five Star Party & Event Rentals	Rentals	1492 Medina Hwy	Kerrville	Texas	Texas Hill Country	Kerrville rental and design company supplying furniture, linens, lighting, tents, dance floors and stages for Hill Country weddings and events.	fsraccounting@yahoo.com	830-896-0282	https://fivestarpartyrental.com/	https://www.instagram.com/fivestarpartyevents/
290 Wine Shuttle	Transportation	308 S Washington St	Fredericksburg	Texas	Fredericksburg and the 290 Wine Trail	Fredericksburg shuttle company running wine-trail tours and offering private wedding and event transportation around the Hill Country.	wineshuttle290@yahoo.com	210-724-7217	https://290wineshuttle.com/	https://www.instagram.com/290wineshuttle/
Hill Country Limousine Service	Transportation		Kerrville	Texas	Kerrville, Boerne, Comfort, Fredericksburg, Ingram, Junction and the Hill Country	Family-run Kerrville chauffeur service operating since 1985, offering wedding transport, airport runs and wine tours across the Hill Country.		830-896-1429	https://hillcountrylimos.com/	
Fiancée Bridal Boutique (Boerne)	Bridal & Formalwear	116 S Main St	Boerne	Texas	Kendall County and north San Antonio	Boerne bridal boutique with made-to-order and off-the-rack gowns, plus plus-size styles, dress cleaning and preservation.	boerne@fianceebridalboutique.com	830-431-8687	https://fianceebridalboutique.com/	https://www.instagram.com/fianceebridalboutique/
LD Bridal	Bridal & Formalwear	412 River Road, Suite 104	Boerne	Texas		Boerne boutique offering private, by-appointment gown fittings alongside mother-of-the-bride dresses and bridal accessories.		830-331-9232	https://www.ldbridalboutique.com/	https://www.instagram.com/ld_bridal/
Sacrament Bridal	Bridal & Formalwear	401 E Auguste Street	Fredericksburg	Texas		Appointment-only Fredericksburg boutique selling designer wedding gowns alongside men's formal wear.		830-733-2135	https://www.sacramentbridal.com/	https://www.instagram.com/sacrament.bridal/
Dragonfly Designs	Stationery & Invitations		Austin	Texas	Austin area, the Hill Country and nationwide	Austin stationery studio designing custom wedding invitations, save-the-dates and day-of paper for couples in the Hill Country and beyond.			https://invitationsbydragonflydesigns.com/	https://www.instagram.com/dragonflydes/
Belle Vita Blooms	Florals		Fredericksburg	Texas	Fredericksburg and surrounding areas	Fredericksburg event florist focused on weddings, creating bridal party flowers and venue florals with 15 years of experience.	bellevitablooms@gmail.com	281-782-3656	https://www.bellevitablooms.com/	https://www.instagram.com/bellevitablooms/
Glashaus Floral Design	Florals	606 N Llano Street	Fredericksburg	Texas	Texas Hill Country	Fredericksburg flower shop designing seasonal, whimsical arrangements for weddings and everyday occasions, with gifts and local delivery.	info@glashausfloral.com	830-998-1247	https://www.glashausfloral.com/	https://www.instagram.com/glashausfloral/
Front St. Floral	Florals	419 Front St	Comfort	Texas	Comfort and surrounding areas	Family-owned Comfort florist making bridal bouquets, ceremony arrangements and reception flowers for Hill Country weddings.	laurie@frontstfloral.com	210-386-6776	https://www.frontstfloral.net/	https://www.instagram.com/frontstfloral/
Jolie Belle Beauty Bar	Hair & Makeup	664 S. Walnut Avenue	New Braunfels	Texas	New Braunfels, San Antonio, Austin and the Texas Hill Country	New Braunfels hair and makeup team for brides and bridal parties, working across the Hill Country, San Antonio and Austin.	joliebelle.beautybar@gmail.com		https://www.joliebellebeautybar.com/	https://www.instagram.com/joliebelle.beautybar/
Anastasia MUA	Hair & Makeup		Austin	Texas	Austin, Dripping Springs, Kyle, Driftwood, Wimberley	Onsite wedding hair and makeup team based in Austin, travelling to Dripping Springs, Wimberley and Driftwood weddings.	info@anastasiamua.com		https://www.anastasiamua.com/	https://www.instagram.com/anastasiamuatx/
On Location Hair and Makeup	Hair & Makeup		San Antonio	Texas	San Antonio, Boerne, New Braunfels, Fredericksburg, Kerrville, Dripping Springs	San Antonio hair and makeup artist offering airbrush bridal makeup and styling, travelling to weddings in Boerne, Fredericksburg and Kerrville.	cgreen89@aol.com	210-722-6979	https://www.onlocationtx.com/	https://www.instagram.com/reneegreen89/
Makeup by Adrienn & Team	Hair & Makeup		Austin	Texas	Austin and Dripping Springs	Austin bridal hair and makeup team that also works at Dripping Springs and Driftwood wedding venues.	beautybyadrienn@gmail.com	949-272-6092	https://makeupbyadrienn.com/	https://www.instagram.com/makeupbyadriennandteam/
`,
  },
  {
    name: "Killeen, Harker Heights, Temple and Salado: planning, florals, cake, catering and music",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Milestone Memories & Events	Planning	2501 South W.S. Young Drive, Suite 209	Killeen	Texas		Killeen planner and showroom offering hourly consulting, day-of coordination or full wedding planning, with rentals and a venue to hire.		(254) 630-1008	https://www.milestonememoriesandevents.com/	
Botanical Jane	Florals		Temple	Texas	Temple, Waco and Austin	Floral design studio creating custom wedding flowers, with a portfolio drawn from Austin-area venues and a base in Temple.	info@botanicaljane.com		https://botanicaljane.com/	https://www.instagram.com/botanicaljane/
Wonderland Flowers	Florals		Temple	Texas	Temple, Killeen, Belton, Harker Heights, Salado and Central Texas	Temple studio florist making hand-crafted floral designs for weddings and events, with delivery across Bell County and nearby towns.	wonderlandflowers81@gmail.com	(682) 808-2973	https://www.wonderlandflowers.com/	https://www.instagram.com/wonderlandflowers/
Morgan Pearl Bakery	Cake	2415 N Main Street	Belton	Texas		Belton bakery making custom wedding cakes, late-night bites and interactive dessert stations, with tastings by appointment when the shop is closed.	info@morganpearlcakes.com	254-314-6304	https://morganpearlcakes.com/	https://www.instagram.com/morganpearlcakes/
Texas Bites Bakery	Cake		Killeen	Texas		Self-taught home baker in Killeen making custom wedding cakes and cupcakes, with a quote form, a published flavour list and wedding pricing.	texasbitesbakery@gmail.com	254-249-4934	https://www.texasbitesbakery.com/	https://www.instagram.com/texasbitesbakery/
Arboniche's Fine Catering	Catering	4013 Chaparral Rd	Killeen	Texas		Killeen caterer run since 2004 by a chef and his wife, serving buffets for 50 to 1,000-plus guests, with custom menus and china and table rentals.		254-519-4300	https://www.arbonichesfinecatering.com/	
Let Us Do The Cooking	Catering	111 S Main Street	Nolanville	Texas		Full-service caterer founded in 2006 near Killeen, handling plated dinners and buffets for weddings, military balls and corporate events.	admin@letusdothecooking.com	(254) 554-2665	https://www.letusdothecooking.com/	
DJ JayJacq Entertainment	Music		Killeen	Texas	Killeen, Harker Heights, Copperas Cove, Belton, Temple and Central Texas	Killeen mobile DJ playing weddings, reunions and parties, with R&B, jazz, reggae and disco in the mix, plus karaoke and a photo booth rental.	dj.jayjacq@gmail.com	254.462.7183	https://gjjacquot.wixsite.com/djjayjacq	https://www.instagram.com/dj.jayjacq/`,
  },
  {
    name: "El Paso: planning and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
El Paso's Bakery	Cake	3300 Fort Blvd	El Paso	Texas		Mexican bakery making pastries, cakes and breads from scratch, with specialty cakes and catering for weddings and quinceañeras.		(915) 300-6909	https://elpasosbakery.com	https://www.instagram.com/elpasosbakery/
Greggerson's Cake Cottage	Cake	2050 Trawood Dr #9	El Paso	Texas		Neighbourhood bakery known for its almond buttercream, selling ready-made and custom cakes and cupcakes for special occasions.		(915) 591-5690	https://www.greggersonscakecottage.com	https://www.instagram.com/greggersonselpaso/
Imagine Events	Planning	7365 Remcon Circle, Suite C-301	El Paso	Texas	El Paso	Event coordination and design firm with 18 years' experience, offering full planning or day-of support for weddings, plus rentals and vendor coordination.	veronica@imagineeventplanners.com	(915) 833-2300	https://www.imagineeventplanners.com	
I Do Weddings & Events	Planning	11233 Rojas Drive	El Paso	Texas	El Paso and across the United States	Full-service wedding planning and event design company with over 22 years' experience, also offering decoration, catering and equipment rentals.	cody@idoweddingsevents.net	915-771-7788	https://www.idoeventsep.com	https://www.instagram.com/idoweddingseventsep/
That One Chica Event Planner	Planning		El Paso	Texas	El Paso and surrounding areas, plus destination events	Planner Paola offers full wedding planning, day-of coordination, tent draping and event design, with 8-plus years in the industry.	pq.eventdesigner@gmail.com	(915) 600-3381	https://thatonechicaeventdesigner.com	https://www.instagram.com/urpartyplanner_pao/
Jocabed Cajiga Event Design	Planning		El Paso	Texas	El Paso and Ciudad Juárez	Bilingual wedding planner and event designer working since 2015, covering full planning and design for couples in El Paso and Juárez.	info@jocabedcajiga.com		https://www.jocabedcajiga.com	https://www.instagram.com/jocabed.planner/`,
  },
];

export default batches;
