import type { VendorBatch } from "@/lib/vendor-batches";

// Utah vendor batches. Every row's State is "Utah". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Salt Lake City: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Branson Maxwell Photo & Video	Photography		Salt Lake City	Utah		Salt Lake City photo and video team that covers weddings at Utah ranch, lodge and estate venues and has shot over 400 weddings.			https://bransonmaxwell.com	https://www.instagram.com/bransonmaxwell.photo/
Caili Chung Photography	Photography		Salt Lake City	Utah	Salt Lake City and Park City	Wedding and portrait photographer working across Salt Lake City, Park City and the Wasatch mountains.		801-913-6162	https://cailichung.com	
Jordan Varela Photography	Photography		Salt Lake City	Utah		Salt Lake City photographer for weddings, elopements and engagements, with a second shooter and an openly welcoming approach.			https://www.jordanvarela.com	https://www.instagram.com/JordanVarelaPhotography/
West Coast Creatives SLC	Planning		Salt Lake City	Utah		Latina-owned planning and design studio offering full planning, partial planning and wedding-day management since 2022.	westcoastcreativesslc@gmail.com		https://www.westcoastcreativesslc.com	https://www.instagram.com/westcoastcreativesslc/
Ryann Kristena Events	Planning		Salt Lake City	Utah	Salt Lake City and Park City	Planner for non-traditional weddings with a moody, modern or fashion-led look, offering full design and day-of management.	hello@ryannkristenaevents.com		https://www.ryannkristenaevents.com	https://www.instagram.com/ryannkristenaevents/
Heirloom Weddings & Events	Planning		Salt Lake City	Utah	Salt Lake City, Park City, Sundance and Utah Valley	Boutique planning and design firm focused on mountain weddings and private estates, with full, guided and coordination packages.	hello@heirloomweddingsutah.com		https://heirloomweddingsutah.com	
Flower Imagination	Florals	481 East South Temple	Salt Lake City	Utah	Salt Lake Valley and surrounding areas	Downtown Salt Lake City flower shop and design studio that does custom wedding flowers and event styling.	contact@flowerimagination.com	(801) 347-8846	https://www.flowerimagination.com	https://www.instagram.com/flowerimagination/
Native Flower Company	Florals	430 East 900 South Suite 102	Salt Lake City	Utah	Salt Lake City and Park City	Salt Lake City florist using seasonal blooms for complete wedding flower packages, with delivery in the city and Park City.		(801) 364-4606	https://www.nativeflowercompany.com	https://www.instagram.com/nativeflowercompany/
Floral Rhapsody	Florals	834 North 100 East Suite B	Lehi	Utah	Utah	Luxury wedding floral studio in Lehi led by designer Jill Savage, covering bouquets, ceremony pieces and reception decor.			https://www.floralrhapsody.com	https://www.instagram.com/floralrhapsody/
DJ Pauly Weddings and Events	Music		Murray	Utah	Salt Lake City, Park City, Heber, Ogden, Provo and the Wasatch Front	Murray-based wedding DJ and MC with over 20 years of experience, supplying sound and lighting for ceremonies and receptions.	paul@djpauly.com	801-554-8647	https://djpaulyweddings.com	https://www.instagram.com/djpaulyslc/
DJ Hector Vibes	Music		Salt Lake City	Utah	Salt Lake City area	Salt Lake City wedding DJ with bilingual MC services, monogram gobo projection and LED uplighting; also plays quinceaneras.	djhectorvibes@gmail.com	801.210.9621	https://djhectorvibes.com	https://www.instagram.com/_hectorvibes_/
Electric Audio	Music		Layton	Utah	Northern and Southern Utah, including Salt Lake City	Wedding DJ and MC service run by Jason Tesch, covering ceremony music, reception sets and cued special moments.		(801) 941-0686	https://www.electricaudiodjs.com	https://www.instagram.com/electricaudiodjs/
Catering by Bryce	Catering	653 West 10600 South	South Jordan	Utah	Ogden to Provo, including Salt Lake City and Park City	Family caterer serving Utah since 1984 with self-serve buffet menus for receptions of up to about 300 guests.		(801) 856-6998	https://cateringbybryce.com	https://www.instagram.com/cateringbybryce4/
Market Catering	Catering	1578 South 300 West	Salt Lake City	Utah		Salt Lake City caterer offering plated dinners, buffets, small bites and food stations for weddings.		801.895.2388	https://www.marketcatering.com	
Have Party Will Travel	Catering	466 West Lawndale Drive	Salt Lake City	Utah	Wasatch Front	Full-service caterer and event company founded in 1995, handling menus, staffing, rentals and logistics.		+1-801-269-8400	https://havepartywilltravel.com	https://www.instagram.com/havepartywilltravel/
Maggie's Hair & Bridal	Hair & Makeup	1033 East 2100 South	Salt Lake City	Utah	Salt Lake City, Park City and across Utah	Sugar House studio and on-location bridal hair and makeup artist with over 14 years of styling experience.	maggielangdonstylist@gmail.com		https://www.maggieshairandbridal.com	https://www.instagram.com/maggieshairnbridal/
Blush + Rose Artistry	Hair & Makeup		Salt Lake City	Utah	Salt Lake City and surrounding areas	On-location bridal hair and makeup team that also offers halo hair extensions and editorial styling.	info@blushrosebeauty.com	801-845-3985	https://www.blushroseartistry.com	https://www.instagram.com/blushroseartistry/
Haven Makeup Studios	Hair & Makeup	9066 South 1510 West #13	West Jordan	Utah	Salt Lake City, Park City, Draper and Snowbird	By-appointment studio in West Jordan providing bridal trials plus on-location wedding hair and makeup.	havenmakeupstudios@gmail.com	801-425-1661	https://www.havenmakeupstudios.com	https://www.instagram.com/havenmakeupstudios/
Granite Bakery & Bridal Showcase	Cake	902 East 2700 South	Salt Lake City	Utah	Salt Lake City area	Family-owned retail bakery open since 1983 that makes custom wedding cakes, with free tastings and design consultations.	sweettreats@granitebakery.com	(801) 467-7291	https://www.granitebakery.com	
City Cakes Cafe	Cake		Salt Lake City	Utah		Vegan bakery whose wedding cakes can also be made gluten-free, with tiers serving 39 to 203 guests and decorator consultations.	citycakesslc@citycakescafe.com	(801) 359-2239	https://www.citycakescafe.com/wedding-cakes/	https://www.instagram.com/citycakesslc/
Salt Cake City	Cake		South Jordan	Utah	Salt Lake Valley and surrounding areas	By-appointment custom cakery operating since 2008, offering over 70 flavours and handmade marshmallow fondant detail.	SaltCakeCity@gmail.com	310-874-7300	https://saltcakecity.com	
Tanner Castro Films	Videography		Salt Lake City	Utah	Utah and destination weddings	Documentary-style wedding films with full-day coverage, elopements and optional Super 8 footage.	hello@tannercastrofilms.com	801-334-9964	https://www.tannercastrofilms.com	https://www.instagram.com/tannercastrofilms/
Ryan Hinman Films	Videography		Salt Lake City	Utah	Deer Valley, Park City, Jackson Hole, Montana, Colorado and destination	Salt Lake City wedding filmmaker with 15 years of experience, making clean, story-led films at Park City resort venues.			https://ryanhinmanfilms.com	https://www.instagram.com/ryanhinmanfilms/
Danny G Video	Videography		Salt Lake City	Utah	Utah County	Wedding videographer with over 200 weddings filmed, offering tiered coverage packages and short highlight videos.		(385) 439-7772	https://www.dannygvids.com	https://www.instagram.com/dannygvids/
`,
  },
  {
    name: "Provo: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Katinov Photography & Videography	Photography		Provo	Utah	Utah, including Salt Lake City, Park City, Provo, Orem, Draper and Spanish Fork	Provo-based photo and video team of four that has documented over 350 weddings and works in English, Spanish and Portuguese.	katinovphotography@gmail.com	435-313-9319	https://katinov.com	https://www.instagram.com/katinovphotography/
Justin Hackworth Photography	Photography		Provo	Utah	Utah County, Salt Lake area and Park City	Provo photographer with over twenty years behind the camera, shooting candid documentary-style weddings and engagements.			https://justinhackworth.com	https://www.instagram.com/justinhackworth/
James Erick Photography	Photography		American Fork	Utah	Utah County, Salt Lake City, Park City, Ogden and across Utah	American Fork wedding photographer who also films in 4K, covers temple weddings, and charges no travel within 80 miles.		801-678-6240	https://www.jameserickphotographyutah.com	https://www.instagram.com/jameserickphotographyutah/
Kaushay & Co. Events	Planning		Lehi	Utah	Salt Lake City, Park City, Utah County and destination	Lehi wedding planning and design team known for colourful, personality-led weddings, with a background in broadcast journalism and theatre.		385-374-0789	https://kaushay.co	https://www.instagram.com/kaushay.co/
Queen Hollidae	Planning	154 West Main St	American Fork	Utah	Utah and Salt Lake Counties	American Fork event planner offering day-of coordination to full planning, with catering, decor rentals and a small gift shop under one roof.		801-380-6459	https://queenhollidae.com	https://www.instagram.com/queenhollidae1/
Everson Events	Planning		Orem	Utah	Utah, willing to travel	Utah planning and design studio offering full planning, day-of coordination and design consultation, welcoming to all couples and budgets.	eversondesignstudio@gmail.com		https://eversonevents.com	https://www.instagram.com/eversonevents/
Bronte's Florals	Florals		Lehi	Utah	Salt Lake City to Provo and south to St. George	Lehi wedding florist with a horticulture degree and over 15 years of experience, making bouquets, arches and centrepieces.	info@brontesflorals.com	385-215-9566	https://brontesflorals.com	https://www.instagram.com/brontesflorals/
Blossoms & Twine	Florals		American Fork	Utah	Utah County and beyond	American Fork mother-and-daughter florist making lush, garden-style wedding flowers, with owner training from the Utah School of Floral Design.	info@blossomsandtwine.com	801-759-4024	https://www.blossomsandtwine.com	https://www.instagram.com/blossomsandtwine/
Kunz Floral Co	Florals		Springville	Utah		Springville luxury wedding florist led by Mackenzy Kunz, known for lush, romantic designs that reflect each couple.			https://www.kunzfloralco.com/	https://www.instagram.com/kunzfloralco/
Moment Entertainment	Music		Mapleton	Utah	Utah County, Salt Lake City and Park City	Mapleton wedding DJ and bilingual English-Spanish MC with 20 years of mixing, adding lighting design, fog effects and a Glambot.	Info@GetMomentEntertainment.com	801-788-4595	https://www.getmomententertainment.com	https://www.instagram.com/dj.teardrop/
Greenhollow Catering	Catering	1400 W 400 N	Orem	Utah	Greater Utah County	Family-run Orem caterer serving Utah County for three generations, with wedding dinners, receptions and cocktail hours.		801-691-4435	https://www.greenhollowcatering.com	https://www.instagram.com/greenhollowcatering/
Utah Celebrations	Catering	1086 N 450 W Ste 120	Springville	Utah	Utah	Springville catering, event planning and rental company offering wedding menus plus linens, china and decor from the same team.	Info@UtahCelebrations.com	801-836-3508	https://utahcelebrations.com	https://www.instagram.com/utcelebrations/
Brown Brothers Catering	Catering	1620 S State St	Orem	Utah	Provo, Orem, Salt Lake City and greater Utah	Orem caterer with over 1,000 events behind it, offering plated, buffet, family-style and chef-action-station wedding service.		801-607-1891	https://www.brownbrotherscatering.com	
Yulia Wilcox Hair & Makeup	Hair & Makeup		Provo	Utah	Utah County, Provo and Park City	Provo bridal hair and makeup artist working since 2012 in a soft, timeless style, with all-inclusive packages and lashes included.	yulia.wilcox.mua@gmail.com	385-277-0534	https://www.yuliawilcox.com	https://www.instagram.com/yulia_wilcox_pro/
Ottalaus Salon	Hair & Makeup	3300 N Running Creek Way Suite A2	Lehi	Utah	Greater Utah	Full-service Lehi hair and nail salon that offers bridal hair and makeup in the salon or on location, matched to your stylist.		833-385-1523	https://www.ottalaus.com/bridal-hair-and-makeup	https://www.instagram.com/ottalaussalon/
MVP by Ellie Nicole	Hair & Makeup		Orem	Utah		Orem airbrush makeup artist who also films and photographs, so couples can book bridal makeup and wedding coverage with one person.			https://mvpbyellienicole.com	https://www.instagram.com/ellienicole.mvp/
Grapefruit & Thyme	Cake	145 S Pleasant Grove Blvd	Pleasant Grove	Utah	Pleasant Grove and Salt Lake City	Pleasant Grove bakery, formerly Ami Cakes, making wedding cakes and pies, with a second shop in Salt Lake City's Sugar House.	info@grapefruitandthyme.com		https://grapefruitandthyme.com	https://www.instagram.com/grapefruitandthyme/
Bucko Bakery	Cake		Orem	Utah	Orem and surrounding areas	Woman-owned Orem home bakery making custom wedding cakes from tested recipes, with consultations by appointment and delivery for tiered cakes.		845-260-0309	https://buckobakery.com	
Sweet & Dulce Bakery	Cake		Spanish Fork	Utah	Spanish Fork, Provo, Orem and Utah County	Spanish Fork bakery making custom wedding cakes with Latin flavours such as tres leches.			https://sweetanddulcebakery.com	https://www.instagram.com/sweetanddulcebakery/
Skylark Media Weddings	Videography		Lehi	Utah	Utah	Lehi wedding videography and photo studio with five-hour coverage, six to eight minute highlight films and ceremony live streaming.			https://www.skylarkmediaweddings.com	https://www.instagram.com/skylarkmedia_weddings/
Emily Brand Films	Videography		Lehi	Utah	Utah	Lehi filmmaker making wedding films alongside corporate and documentary work, with packages from partial to full-day coverage.			https://emilybrandfilms.com	https://www.instagram.com/emilybrandfilms/
Chad Coleman Films	Videography		Orem	Utah	Utah and worldwide	Orem wedding videographer making natural, cinematic films that favour real moments over staged ones, with seven years of weddings.			https://chadcolemanfilms.com	https://www.instagram.com/chadcolemanfilms/
OHLR	Music	275 North Main Street Unit 1101	Centerville	Utah	All of Utah, including Provo, Orem, Pleasant Grove and Spanish Fork	Centerville DJ and MC team handling ceremony audio, uplighting, monograms and stage effects, run by a team of music producers.		801-699-3759	https://ohlr.co/home	https://www.instagram.com/ohlrmusic/
Artiva Strings	Music		Salt Lake City	Utah	Salt Lake County, Utah County (Provo, Orem, Lehi) and Park City	String quartet formed in 2020 playing weddings, with a 300-song library, custom arrangements and a Live Jukebox for guest requests.	info@artivastrings.com		https://artivastrings.com	https://www.instagram.com/artivastrings/
`,
  },
];

export default batches;
