import type { VendorBatch } from "@/lib/vendor-batches";

// Vermont vendor batches. Every row's State is "Vermont". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Burlington: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Oak & Bee Florals	Florals		Burlington	Vermont	Vermont and beyond	Burlington studio creating garden-inspired wedding flowers that draw on Vermont's landscape, with bouquet preservation and flower classes too.	oakandbeeflorals@gmail.com		https://www.oakandbeeflorals.com	https://www.instagram.com/oakandbeeflorals/
June Farm	Florals	200 Higbee Road	Charlotte	Vermont		Charlotte flower farm growing naturally raised specialty cut flowers and turning its own fresh, local stems into wedding and event arrangements.	flowers@junefarmvt.com		https://www.junefarmvt.com	
That Cake Stand	Cake		Burlington	Vermont	Burlington area, with delivery	Custom cake maker working from a downtown Burlington kitchen, designing tiered wedding cakes one-to-one with couples and offering tasting boxes.	Erinn@thatcakestand.com		https://www.thatcakestand.com/weddings	https://www.instagram.com/thatcakestand/
Wedding DJ VT	Music		Burlington	Vermont	Chittenden County, Stowe, Killington, southern Vermont, the Northeast Kingdom, New York and New England	Burlington team of wedding DJs led by Evan LeCompte, covering ceremony sound through the last dance with professional gear and years of club experience.	evan@weddingdjvt.com	802-338-2726	https://www.weddingdjvt.com	https://www.instagram.com/weddingdjvt/
Supersounds Entertainment	Music		Underhill	Vermont	Burlington, Stowe and across Vermont	Vermont DJ company working since 1978, with a video of each DJ so couples can pick the person who will actually play their wedding.	events@supersounds.com	802-343-2677	https://supersounds.com	https://www.instagram.com/vermontweddingdj/
Fin Catering	Catering	210 Shelburne Road	Burlington	Vermont	Northern Vermont and beyond	Small full-time Burlington catering team offering Vermont cheese boards, detailed hors d'oeuvres, family-style dinners and a full local bar.			https://www.fincatering.com	https://www.instagram.com/fincateringvt/
Adventure Dinner	Catering	70 Roosevelt Highway	Colchester	Vermont	Vermont	Colchester caterer known for themed dinners, bringing the same focus on Vermont farms and small producers to wedding and private event menus.			https://www.adventuredinner.com	https://www.instagram.com/adventuredinner/
Susanna's Catering	Catering	120 Pleasant Street	Morrisville	Vermont	Vermont and beyond	Morrisville caterer cooking since 2003, pairing produce from local farms with global spices for wedding menus across the state.	susannascatering@gmail.com		https://susannascatering.com	https://www.instagram.com/susannastogo/
I Dews Design & Events	Planning		Burlington	Vermont	New England and beyond	Burlington planner Meghan Dews designs and runs wedding days, with a queer-owned practice centred on celebrating every kind of couple.	meg@idewsdesign.com	(207) 475-5955	https://www.idewsdesign.com	https://www.instagram.com/idewsdesign/
Kelsey Regan Photography	Photography		Burlington	Vermont	Vermont, New England, New York and beyond	Wedding photographer near Burlington shooting in both digital and film, with an editorial eye, a calm presence and a fondness for logistics.	kelsey@kelseyreganphotography.com		https://kelseyreganphotography.com	https://www.instagram.com/kelseyreganphoto/
Daniel Schechner Photography	Photography		Burlington	Vermont		Burlington photographer working as A Life in the Boonies, covering weddings alongside portrait and lifestyle work with an outdoorsy, rural feel.	hello@danielschechner.com		https://www.danielschechner.com	https://www.instagram.com/lifeintheboonies/
Flora Vita	Florals		St. Albans	Vermont	Throughout Vermont, near Stowe and Burlington	Florist and flower farm in St. Albans growing many of its own blooms for seasonal, full-service wedding designs with itemised pricing.	floravitavt@gmail.com	802.370.3075	https://www.floravitavt.com/vt-wedding-floral-services	https://www.instagram.com/floravitavt/
Sticks and Stones Band	Music		Burlington	Vermont	Vermont	Burlington live band playing weddings, private parties and community events around Vermont, with live sets built for the dance floor.	emailsticksandstones@gmail.com	802-343-0050	https://www.sticksandstonesbandvt.com	
Vermont Sweet Tooth	Cake		Stowe	Vermont	Vermont and beyond	Stowe special-order bakery known for hand-painted sugar-paste flowers and custom toppers that can be kept long after the wedding.		802.249.2601	https://vermontsweettooth.com	https://www.instagram.com/vermontsweettooth/
Blue House Bakeshop	Cake		Shelburne	Vermont	All over Vermont and beyond	Shelburne bakery making buttercream-only tiered wedding cakes in ten sizes, plus mini desserts for dessert bars, with no fondant used.	bluehousebakeshopvt@gmail.com	(802) 318-6589	https://www.bluehousebakeshop.com/weddings	https://www.instagram.com/bluehousebakeshop/
Salon Salon	Hair & Makeup	232 Mountain Road	Stowe	Vermont		Aveda concept salon on Stowe's Mountain Road offering wedding-party hair and beauty services alongside skincare and nails.	salonsalon@stowe.nu	802-253-7378	https://www.salonsalonvt.com	https://www.instagram.com/salonsalonvt/
k.rossini stylist	Hair & Makeup	3 Main Street	Burlington	Vermont	Vermont	Independent Burlington stylist Kelsey Rossini does bridal trials and travels off-site to style whole wedding parties, updos to extensions.	krossinistylist@gmail.com	(617) 872-8706	https://www.krossinistylist.com/weddings	https://www.instagram.com/krossinistylist/
Pure Beauty	Hair & Makeup	39 Kilburn Street	Burlington	Vermont		South End skincare lounge whose esthetician Kirstin has done bridal makeup since 2010, travelling on site for parties of four or more.	info@purebeautyvt.com	802-318-7259	https://purebeautyvt.com	https://www.instagram.com/purebeautyvt/
Forever Lucky Films	Videography		Burlington	Vermont	New England, New York, New Jersey and Pennsylvania	Burlington wedding filmmaker making warm, cinematic films with an unobtrusive approach that catches the small moments in between.			https://www.foreverluckyfilms.com	https://www.instagram.com/foreverluckyfilms/
Zack Griswold Photography	Photography		Burlington	Vermont	Vermont and New England	Burlington wedding and event photographer with over a decade of experience, covering weddings and elopements around Vermont and New England.	zack@zackgriswold.com	(802) 355-0222	https://zackgriswold.com	https://www.instagram.com/zgriswold/
Inna Chirko Photography	Photography		Burlington	Vermont	Burlington, Shelburne, Vermont and New England	Burlington wedding and family photographer working from Stowe to Lake Champlain, with a relaxed, elegant style built around natural moments.			https://www.photobyinna.com	https://www.instagram.com/innachirkophotography/
Jaclyn Watson Events	Planning		Hyde Park	Vermont	Vermont, Cape Cod, Newport and beyond	Hyde Park planning and design studio with seventeen years behind it, taking on a select number of Vermont and New England weddings each year.		802-324-1433	https://jaclynwatsonevents.com	https://www.instagram.com/jaclynwatsonevents/
Katie Hopkins Events	Planning		Montpelier	Vermont	New England and beyond	Montpelier wedding planner offering full-scale planning and coordination, working from a home studio and travelling across New England.	Katie@katiehopkinsevents.com		https://katiehopkinsevents.com	https://www.instagram.com/katiehopkinsevents/
Todd Stoilov / Still & Motion	Videography		Burlington	Vermont	New England and across the US	Burlington filmmaker and photographer offering combined photo and video coverage, working unobtrusively rather than directing the day.	todd@stoilovstudio.com	802-318-5513	https://toddstoilov.net	https://www.instagram.com/toddstoilov/
Amelia Marie Photography	Videography		Burlington	Vermont	New England and the Southwest	Burlington elopement and wedding videographer making five-to-seven-minute highlight films with short social teasers, alongside her photography.	amelia@ameliamariephoto.com		https://ameliamariephoto.com/wedding-and-elopement-videography	https://www.instagram.com/ameliamariephoto/`,
  },
  {
    name: "Stowe: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Savannah Brown Photography	Photography		Stowe	Vermont	Vermont and worldwide	Stowe wedding and family photographer, working since 2016, known for candid, emotional images and local knowledge of Vermont's mountain venues.	hello@savannahbrown.com		https://savannahbrown.com/	https://www.instagram.com/imsavannahbrown/
LuvLens Photo	Photography		Stowe	Vermont	Vermont, especially the Stowe area, and beyond	Stowe-area wedding photographer documenting the big moments and the quiet in-between ones, with a natural, unforced approach to couples' days.	luvlensphoto@gmail.com		https://www.luvlens.com/	https://www.instagram.com/luvlens/
NJOY Weddings & Events	Planning		Stowe	Vermont	Vermont, including destination weddings	Stowe planning and design company offering full planning, month-of coordination, elopements and micro-weddings, with a hospitality-first, upscale style.	nancy@njoyevent.com	802-229-8665	https://www.njoyevent.com/	https://www.instagram.com/n_joyevent/
Bramble + Bloom	Florals	559 Harrel Street, Unit B4-D	Morrisville	Vermont	Stowe and across Vermont	Florist near Stowe designing wedding flowers, ceremony installations and reception tablescapes, with event design and day-of coordination available too.	brambleandbloom@gmail.com	802-760-6785	https://www.brambleandbloomdesigns.com/	https://www.instagram.com/bramblebloom/
Peak Entertainment	Music		Stowe	Vermont	Vermont and New Hampshire	Stowe boutique DJ service known for discreet, unobtrusive wedding DJs and personalised playlists, travelling across Vermont and the White Mountains.		802-888-6978	https://peakdj.com/	https://www.instagram.com/peakdjs/
Sweet & Savory	Catering		Stowe	Vermont	Stowe, Morrisville and central Vermont	Chef-run caterer in Stowe and Morrisville cooking wedding and event menus around seasonal Vermont meats, poultry and produce, with dietary needs handled.	sweetsavorypc@gmail.com	802-730-2792	https://www.sweetsavorystowe.com/	
Warren's Kitchen & Catering	Catering	100 Cottage Club Road	Stowe	Vermont	Stowe, Morrisville, Waterbury and central Vermont	Stowe food truck and caterer serving Caribbean-influenced jerk dishes, comfort-food twists and farm-fresh ingredients at events across central Vermont.	info@warrenskitchenvt.com	603-393-9439	https://warrenskitchenvt.com/	https://www.instagram.com/warrens__kitchen/
The Roving Feast	Catering		Cambridge	Vermont	Northern Vermont	Cambridge caterer offering wedding menus with hors d'oeuvres, barbecue and brunch, plus bar packages from beer and wine only to a full open bar.	info@therovingfeast.com	802-310-5196	https://www.therovingfeast.com/	https://www.instagram.com/therovingfeast/
SALT + GROVE	Hair & Makeup	2038 Mountain Road	Stowe	Vermont		Stowe wellness studio offering bridal makeup with a trial, plus a prep package of custom glow facials, a massage and skin consultation before the day.	hello@saltstowe.com	802-760-6591	https://saltstowe.com/	https://www.instagram.com/saltandgrovewellness/
Vermont Wedding Hair & Makeup by Brittany	Hair & Makeup	One Stowe Street	Waterbury	Vermont	Vermont	Waterbury stylist doing mobile bridal hair and makeup, from updos to down styles, with an on-site trial run and wedding-day service.		802-343-5164	https://vermontweddinghair.weebly.com/	https://www.instagram.com/vermontweddinghair/
Stowe Bee Bakery & Cafe	Cake	1056 Mountain Road	Stowe	Vermont		Stowe bakery making handmade layer cakes with mousse fillings and Italian buttercream, plus cheesecakes and vegan or flourless options with notice.	info@stowebeebakery.com	802-760-6728	https://www.stowebeebakery.com/	https://www.instagram.com/stowebeebakery/
Red Poppy Cakery	Cake	1 Elm Street, Suite #1	Waterbury	Vermont	Vermont	Waterbury bakery making custom tiered wedding cakes, cupcakes and dessert tables, with vegan and allergy-friendly options and tastings.	janina@redpoppycakery.net	203-400-0700	https://www.redpoppycakery.net/	https://www.instagram.com/redpoppycakeryvt/
Mountain Brothers Media	Videography		Stowe	Vermont	Vermont and New England	Stowe video and photo team filming weddings with unlimited coverage rather than hourly caps, and meeting couples at their venue before the day.			https://www.mountainbrothersmedia.com/	`,
  },
  {
    name: "Stowe: florals, photography, planning, videography and hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Uncle George's Flowers	Florals	638 S Main St, Suite 7	Stowe	Vermont	Stowe	Full-service Stowe florist with a German-trained owner and 25-plus years designing wedding bouquets, arrangements and event flowers.		802-253-9900	https://www.unclegeorgesflowersvt.com/	
Sprig	Florals		Stowe	Vermont	Stowe and Vermont	Stowe cut-flower farm growing its own blooms, foliage and woody stems for wedding bouquets, ceremony pieces and reception florals.	sprigflowerfarmvt@outlook.com	802-793-6574	https://www.sprigvt.com/	https://www.instagram.com/sprigflowerfarmvt/
Bagel Flowers	Florals		Stowe	Vermont	Stowe, Waterbury and Chittenden, Lamoille and part of Washington County	Stowe florist offering bespoke wedding and event design, from bouquets to ceremony and reception arrangements.	bagelflowers@gmail.com	802-207-4985	https://bagelflowers.com/pages/weddings-events	https://www.instagram.com/bagel_flowers/
Peck's Flower Shop	Florals	64 Portland St	Morrisville	Vermont	Morrisville, Stowe and surrounding towns	Morrisville flower shop with more than 50 years serving the area, designing wedding bouquets, centrepieces and ceremony flowers.		802-888-2332	https://www.pecksflowershopvt.com/	https://www.instagram.com/pecksflowershopvt/
Wildly Vowed	Photography		Stowe	Vermont	Vermont and worldwide	Stowe-based photographers focused on adventure elopements and small weddings for couples who prefer wild places to big guest lists.			https://wildlyvowed.com/	https://www.instagram.com/wildlyvowed/
Elisabeth Viilu Photography	Photography		Stowe	Vermont	Vermont	Stowe photographer capturing natural, emotional photos of weddings, proposals and family sessions at venues across Vermont.			https://www.elisabethviiluphotography.com/	https://www.instagram.com/elisabeth_viilu_photography/
Randi Nonni Events	Planning		Burlington	Vermont	Vermont, including Stowe resort weddings	Burlington planner, formerly Silver Toad, offering full-service planning and takes on no more than ten clients a season.	rskn@randinonnievents.com	802-598-3885	https://randinonnievents.com/	https://www.instagram.com/randinonnievents/
Carmen George Weddings	Planning		Burlington	Vermont	Vermont	Burlington planner and officiant offering full planning, week-of and day-of coordination and hourly consulting for Vermont weddings.	carmengeorgevt@gmail.com	802-829-8111	https://www.officiantvermont.com/vermontdayofcoordinator	
Align Film	Videography		Waterbury Center	Vermont	Vermont	Waterbury Center team making cinematic wedding films, alongside family and commercial video.	inquire@align.film	802-662-2012	https://www.align.film/	
Hillary Fay Studios	Hair & Makeup	12 Pearl Street	Essex Junction	Vermont	Vermont	Essex Junction studio offering on-location bridal makeup and hair styling for Vermont weddings and small elopements.		802-373-3149	https://www.hillaryfaystudios.com/	https://www.instagram.com/hillaryfaystudios/`,
  },
];

export default batches;
