import type { VendorBatch } from "@/lib/vendor-batches";

// Vermont vendor batches. Every row's State is "Vermont". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Burlington: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Oak & Bee Florals	Florals		Burlington	Vermont	Vermont and beyond	Burlington studio creating garden-inspired wedding flowers that draw on Vermont's landscape, with bouquet preservation and flower classes too.	oakandbeeflorals@gmail.com		https://www.oakandbeeflorals.com	https://www.instagram.com/oakandbeeflorals/
June Farm	Florals	200 Higbee Road	Charlotte	Vermont		Charlotte flower farm growing naturally raised specialty cut flowers and turning its own fresh, local stems into wedding and event arrangements.	flowers@junefarmvt.com		https://www.junefarmvt.com	
That Cake Stand	Cake		Burlington	Vermont	Burlington area, with delivery	Custom cake maker working from a downtown Burlington kitchen, designing tiered wedding cakes one-to-one with couples and offering tasting boxes.	Erinn@thatcakestand.com		https://www.thatcakestand.com/weddings	https://www.instagram.com/thatcakestand/
Wedding DJ VT	Music		Burlington	Vermont	Chittenden County, Stowe, Killington, southern Vermont, the Northeast Kingdom, New York and New England	Burlington team of wedding DJs led by Evan LeCompte, covering ceremony sound through the last dance with professional gear and years of club experience.	evan@weddingdjvt.com	802-338-2726	https://www.weddingdjvt.com	https://www.instagram.com/weddingdjvt/
Supersounds Entertainment	Music		Underhill	Vermont	Burlington, Stowe and across Vermont	Vermont DJ company working since 1978, with a video of each DJ so couples can pick the person who will actually play their wedding.	events@supersounds.com	802-343-2677	https://supersounds.com	https://www.instagram.com/vermontweddingdj/
Fin Catering	Catering	210 Shelburne Road	Burlington	Vermont	Northern Vermont and beyond	Small full-time Burlington catering team offering Vermont cheese boards, detailed hors d'oeuvres, family-style dinners and a full local bar.			https://www.fincatering.com	https://www.instagram.com/fincateringvt/
Adventure Dinner	Catering	70 Roosevelt Highway	Colchester	Vermont	Vermont	Colchester caterer known for themed dinners, bringing the same focus on Vermont farms and small producers to wedding and private event menus.			https://www.adventuredinner.com	https://www.instagram.com/adventuredinner/
Susanna's Catering	Catering	120 Pleasant Street	Morrisville	Vermont	Vermont and beyond	Morrisville caterer cooking since 2003, pairing produce from local farms with global spices for wedding menus across the state.	susannascatering@gmail.com		https://susannascatering.com	https://www.instagram.com/susannastogo/
I Dews Design & Events	Planning		Burlington	Vermont	New England and beyond	Burlington planner Meghan Dews designs and runs wedding days, with a queer-owned practice centred on celebrating every kind of couple.	meg@idewsdesign.com	(207) 475-5955	https://www.idewsdesign.com	https://www.instagram.com/idewsdesign/
Kelsey Regan Photography	Photography		Burlington	Vermont	Vermont, New England, New York and beyond	Wedding photographer near Burlington shooting in both digital and film, with an editorial eye, a calm presence and a fondness for logistics.	kelsey@kelseyreganphotography.com		https://kelseyreganphotography.com	https://www.instagram.com/kelseyreganphoto/
Daniel Schechner Photography	Photography		Burlington	Vermont		Burlington photographer working as A Life in the Boonies, covering weddings alongside portrait and lifestyle work with an outdoorsy, rural feel.	hello@danielschechner.com		https://www.danielschechner.com	https://www.instagram.com/lifeintheboonies/
Flora Vita	Florals		St. Albans	Vermont	Throughout Vermont, near Stowe and Burlington	Florist and flower farm in St. Albans growing many of its own blooms for seasonal, full-service wedding designs with itemised pricing.	floravitavt@gmail.com	802.370.3075	https://www.floravitavt.com/vt-wedding-floral-services	https://www.instagram.com/floravitavt/
Sticks and Stones Band	Music		Burlington	Vermont	Vermont	Burlington live band playing weddings, private parties and community events around Vermont, with live sets built for the dance floor.	emailsticksandstones@gmail.com	802-343-0050	https://www.sticksandstonesbandvt.com	
Vermont Sweet Tooth	Cake		Stowe	Vermont	Vermont and beyond	Stowe special-order bakery known for hand-painted sugar-paste flowers and custom toppers that can be kept long after the wedding.		802.249.2601	https://vermontsweettooth.com	https://www.instagram.com/vermontsweettooth/
Blue House Bakeshop	Cake		Shelburne	Vermont	All over Vermont and beyond	Shelburne bakery making buttercream-only tiered wedding cakes in ten sizes, plus mini desserts for dessert bars, with no fondant used.	bluehousebakeshopvt@gmail.com	(802) 318-6589	https://www.bluehousebakeshop.com/weddings	https://www.instagram.com/bluehousebakeshop/
Salon Salon	Hair & Makeup	232 Mountain Road	Stowe	Vermont		Aveda concept salon on Stowe's Mountain Road offering wedding-party hair and beauty services alongside skincare and nails.	salonsalon@stowe.nu	802-253-7378	https://www.salonsalonvt.com	https://www.instagram.com/salonsalonvt/
k.rossini stylist	Hair & Makeup	3 Main Street	Burlington	Vermont	Vermont	Independent Burlington stylist Kelsey Rossini does bridal trials and travels off-site to style whole wedding parties, updos to extensions.	krossinistylist@gmail.com	(617) 872-8706	https://www.krossinistylist.com/weddings	https://www.instagram.com/krossinistylist/
Pure Beauty	Hair & Makeup	39 Kilburn Street	Burlington	Vermont		South End skincare lounge whose esthetician Kirstin has done bridal makeup since 2010, travelling on site for parties of four or more.	info@purebeautyvt.com	802-318-7259	https://purebeautyvt.com	https://www.instagram.com/purebeautyvt/
Forever Lucky Films	Videography		Burlington	Vermont	New England, New York, New Jersey and Pennsylvania	Burlington wedding filmmaker making warm, cinematic films with an unobtrusive approach that catches the small moments in between.			https://www.foreverluckyfilms.com	https://www.instagram.com/foreverluckyfilms/
Zack Griswold Photography	Photography		Burlington	Vermont	Vermont and New England	Burlington wedding and event photographer with over a decade of experience, covering weddings and elopements around Vermont and New England.	zack@zackgriswold.com	(802) 355-0222	https://zackgriswold.com	https://www.instagram.com/zgriswold/
Inna Chirko Photography	Photography		Burlington	Vermont	Burlington, Shelburne, Vermont and New England	Burlington wedding and family photographer working from Stowe to Lake Champlain, with a relaxed, elegant style built around natural moments.			https://www.photobyinna.com	https://www.instagram.com/innachirkophotography/
Jaclyn Watson Events	Planning		Hyde Park	Vermont	Vermont, Cape Cod, Newport and beyond	Hyde Park planning and design studio with seventeen years behind it, taking on a select number of Vermont and New England weddings each year.	jackie@jaclynwatsonevents.com	802-324-1433	https://jaclynwatsonevents.com	https://www.instagram.com/jaclynwatsonevents/
Katie Hopkins Events	Planning		Montpelier	Vermont	New England and beyond	Montpelier wedding planner offering full-scale planning and coordination, working from a home studio and travelling across New England.	Katie@katiehopkinsevents.com		https://katiehopkinsevents.com	https://www.instagram.com/katiehopkinsevents/
Todd Stoilov / Still & Motion	Videography		Burlington	Vermont	New England and across the US	Burlington filmmaker and photographer offering combined photo and video coverage, working unobtrusively rather than directing the day.	todd@stoilovstudio.com	802-318-5513	https://toddstoilov.net	https://www.instagram.com/toddstoilov/
Amelia Marie Photography	Videography		Burlington	Vermont	New England and the Southwest	Burlington elopement and wedding videographer making five-to-seven-minute highlight films with short social teasers, alongside her photography.	amelia@ameliamariephoto.com		https://ameliamariephoto.com/wedding-and-elopement-videography	https://www.instagram.com/ameliamariephoto/`,
  },
];

export default batches;
