import type { VendorBatch } from "@/lib/vendor-batches";

// Virginia vendor batches. Every row's State is "Virginia". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Northern Virginia: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Danielle Towle Photography	Photography		Leesburg	Virginia	Northern Virginia, Washington DC and beyond	Warm, romantic wedding photography mixing lifestyle and traditional coverage, with a decade and 200-plus weddings behind it.	danielle@danielletowlephotography.com		https://danielletowlephotography.com/	https://www.instagram.com/danielletowlephotography/
By Asa Photography	Photography		Alexandria	Virginia	Alexandria, Arlington and the DMV	Documentary-style wedding, elopement and micro-wedding photography from Alexandria, using portable off-camera lighting for polished portraits.		(202) 596-2051	https://byasaphotography.com/	https://www.instagram.com/byasaphotography/
Imagery by Erin	Photography		Alexandria	Virginia	Virginia, Maryland and Washington DC	Bright, joyful wedding and engagement photography from an Alexandria photographer, often shooting around Old Town and the wider DMV.			https://imagerybyerin.com/	https://www.instagram.com/imagery.by.erin/
The Finer Points Event Planning and Design	Planning	10 South King Street	Leesburg	Virginia	Loudoun County, Virginia	Two-planner Leesburg firm with over twenty years of wedding design and coordination, meeting couples at a studio in historic downtown.	lynn@thefinerpointsllc.com	(703) 431-9494	https://thefinerpointsllc.com/	https://www.instagram.com/thefinerpointseventplanning/
V&V Wedding Planning	Planning		Warrenton	Virginia	Northern Virginia and the greater Washington DC area	Bilingual English-Spanish planner, Venezuelan-born, offering full planning and day-of coordination for weddings across Northern Virginia since 2014.	hola@vvweddingplanning.com	(703) 347-3013	https://vvweddingplanning.com/	https://www.instagram.com/vvweddingplanning/
JAXA Event Designer	Planning	14170 Minniville Rd, Suite A	Dale City	Virginia	Northern Virginia, Washington DC and Maryland	Dale City studio handling wedding planning and décor, with florals, party rentals and bridal and quinceañera gowns under one roof.	jaxaeventdesigner@gmail.com	(703) 586-7029	https://jaxaeventdesigner.com/	https://www.instagram.com/jaxa_eventdesigner/
Catherine Lee Florals	Florals	2225 Casemont Drive	Falls Church	Virginia	Northern Virginia, Washington DC and Maryland	Family-run Falls Church florist specialising in garden-inspired wedding flowers, working from an appointment-only studio.	support@catherineleeflorals.com	(202) 670-5686	https://www.catherineleeflorals.com/	https://www.instagram.com/catherine.lee.florals/
J. Morris Flowers	Florals	120 East Market Street, Suite B	Leesburg	Virginia	Northern Virginia and Washington DC	Downtown Leesburg floral studio with two decades of wedding work, offering set wedding collections with delivery and on-site styling.	studio@jmorrisflowers.com	(703) 779-3530	https://www.jmorrisflowers.com/	https://www.instagram.com/jmorrisflowers/
Bridal Castle Events Decoration	Florals	45714 Oakbrook Court, Suite 170	Sterling	Virginia	Northern Virginia; travels nationwide	Sterling décor studio known for mandap, sangeet and South Asian wedding styling, with floral centrepieces, bouquets and rentals.	info@bridalcastledecorations.com	(571) 999-2590	https://bridalcastledecorations.com/	https://www.instagram.com/bridalcastleevents/
Dynasty AV & Entertainment	Music		Chantilly	Virginia	Nationwide	Chantilly DJ and AV company focused on South Asian weddings, supplying desi DJs, MCs, live dhol for the baraat, lighting and staging.		(202) 468-9496	https://dynastyave.com/	https://www.instagram.com/dynasty_ave/
Hercules Entertainment	Music	14887 Farm Creek Drive	Woodbridge	Virginia	Northern Virginia and greater Washington DC	Woodbridge DJ company offering bilingual Spanish-English DJs and MCs for weddings and quinceañeras, plus lighting and photo booths.		(888) 435-4372	https://herculesentertainment.com/	https://www.instagram.com/herculesent.torrchez/
Trio Encantador	Music		Fairfax	Virginia	Virginia	Self-contained trio playing traditional Mexican boleros with guitars and harmonies for wedding ceremonies, cocktail hours and anniversaries.	contact@trioencantador.com	(540) 439-8353	https://www.trioencantador.com/	
Celebration by Rupa Vira	Catering	44260 Ice Rink Plaza #120	Ashburn	Virginia	Virginia, Maryland and Washington DC	Ashburn Indian restaurant catering weddings with regional menus spanning Punjabi, Gujarati, South Indian, Indo-Chinese and Bombay dishes.		(571) 281-2233	https://celebrationva.com/catering/	
To Your Taste Catering	Catering	5701 General Washington Dr, Suite F	Alexandria	Virginia	Virginia, Maryland and Washington DC	Owner-run Alexandria caterer with nearly two decades of full-service wedding, social and corporate catering across the DMV.	sales@toyourtastecatering.com	(703) 539-8646	https://www.toyourtastecatering.com/	https://www.instagram.com/toyourtastecatering/
Silver Spoon Caterers	Catering	348 Victory Drive	Herndon	Virginia	Northern Virginia and the DC metro	Family-run Herndon caterer, woman- and minority-owned since 1997, serving plated dinners, buffets and late-night bites in American and global styles.		(703) 968-2950	https://www.silverspooncaterers.com/	https://www.instagram.com/silverspooncaterersva/
Shruti's Beauty	Hair & Makeup		Aldie	Virginia	Northern Virginia and the DC metro	Aldie Indian bridal salon with 20-plus years of South Asian bridal makeup, hair, henna and help with sari draping and dupatta setting.		(571) 218-5826	https://shruti-salon.com/	https://www.instagram.com/makeupbyshruti_salon/
Tamar C Makeup	Hair & Makeup		Vienna	Virginia	DMV area	Vienna-based bridal hair and makeup team offering polished, long-wearing looks for brides and wedding parties across the DMV.			https://www.tamarcmakeup.com/	https://www.instagram.com/tamarcmakeup/
Glam by Duaa	Hair & Makeup		Stafford	Virginia	Virginia, Maryland, Washington DC and beyond	Bridal hair and makeup artist with a decade of soft and full glam, specialising in Pakistani and Indian bridal looks for every skin tone.	duaasayed20@gmail.com	(571) 499-7191	https://glambyduaa.net/	
Breeze Bakery Cafe	Cake	4125 Hummer Road	Annandale	Virginia		Family-owned Korean bakery cafe in Annandale since 2010, baking natural-yeast breads and custom celebration and wedding cakes.	breezebakery@gmail.com	(703) 462-9093	https://www.breezebakery.com/	
Buzz Bakeshop	Cake	901 Slaters Lane	Alexandria	Virginia	Alexandria, Arlington, DC and Fairfax County delivery	Alexandria bakeshop making buttercream wedding cakes of up to two tiers, plus cupcakes, cake pops and cookie tables for receptions.	buzz@buzzbakeshop.com	(703) 600-2899	https://www.buzzbakeshop.com/weddingcakes	
Cakebee	Cake		Warrenton	Virginia	Metro DC area and Virginia	Boutique wedding cake studio run by a French Culinary Institute-trained baker, known for painted buttercream and sugar flowers.	cakebeecakes@gmail.com	(571) 308-3233	https://www.cakebee.com/	https://www.instagram.com/thecakebee/
Catch Motion Studio	Videography		Ashburn	Virginia	Virginia, Maryland, DC and destinations	Ashburn photo and film studio covering Hindu, Sikh and South Indian weddings since 2013, with more than 500 South Asian celebrations filmed.	info@catchmotion.com	(571) 446-0004	https://catchmotion.com/	https://www.instagram.com/catchmotionstudio/
Kevin Socola Films	Videography		Fairfax	Virginia	DMV region and destinations	Fairfax team filming cinematic, editorial wedding videos and photos, bilingual in English and Vietnamese, with 24-48 hour teasers.	info@kevinsocolafilms.com		https://kevinsocolafilms.com/	
Bakerture Photo & Video	Videography		Leesburg	Virginia	Virginia, Maryland, Washington DC and beyond	Studio run from a farm outside Leesburg, making cinematic, story-led wedding films and photographs across Virginia since 2014.			https://bakerture.com/videography	https://www.instagram.com/bakerture/`,
  },
  {
    name: "Richmond: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Stephanie Jenkins Photo	Photography		Richmond	Virginia	Richmond, Midlothian, Powhatan, Glen Allen, Mechanicsville, Ashland and destination	Richmond studio photographing weddings and elopements in an upbeat, candid style, with combined photo and video collections available.			https://stephaniejenkinsphoto.com/	https://www.instagram.com/stephaniejenkinsphoto/
Shelby Lynn Events	Planning		Richmond	Virginia	Richmond, Charlottesville and throughout Virginia	Richmond planning studio offering full wedding planning with design guidance, or event management for couples who have done the planning themselves.	info@shelbylynnevents.com	804-658-6659	https://shelbylynnevents.com/	https://www.instagram.com/shelbylynnevents/
Fred Vaughan Music	Music		Richmond	Virginia		Richmond saxophonist and DJ who plays soul, funk and jazz standards live over his own DJ sets, or solo sax for ceremonies and dinners.	Fredvaughanmusic@gmail.com	804-469-8260	https://fredvaughanmusic.com/	https://www.instagram.com/fredvaughanmusic/
Sabrina Boykin Photography	Photography		Richmond	Virginia	Richmond and surrounding areas	Richmond wedding and family photographer with a relaxed, candid approach that puts couples at ease and favours natural, joyful moments.			https://sabrinaboykin.com/	https://www.instagram.com/sabrinaboykinphotography/
Jesslyn McCartney	Photography		Richmond	Virginia	Virginia, North Carolina, Georgia and the East Coast	Richmond photographer shooting weddings on a mix of film and digital, known for nostalgic colour and classic black-and-white frames.			https://www.jesslynmccartney.com/	https://www.instagram.com/jesslynmccartney/
Nicki Metcalf Photography	Photography		Richmond	Virginia	Richmond and Charlottesville	Richmond wedding photographer with over a decade of experience, favouring an organic, film-inspired look for weddings and engagements.			https://nickimetcalf.com/	https://www.instagram.com/nickimetcalfphotography/
Fleuressence	Florals	9614 Newbys Bridge Road	Chesterfield	Virginia	Richmond and Charlottesville	Chesterfield floral boutique designing seasonal, garden-style wedding flowers, from soft spring palettes to classic neutrals and autumn tones.	hello@fleuressencefloraldesign.com	804-806-4373	https://www.fleuressencefloraldesign.com/	https://www.instagram.com/fleuressencefloraldesign/
Olivera Floral Design	Florals		Richmond	Virginia	Richmond, Charlottesville, Hampton Roads, Northern Virginia	Richmond wedding florist, formerly The Proper Petal, covering bouquets, ceremony arbours, reception centrepieces and larger installations.	hello@oliverafloraldesign.com		https://oliverafloraldesign.com/	https://www.instagram.com/oliverafloraldesign/
VC's Flowers	Florals		Richmond	Virginia	Richmond, Charlottesville and Virginia Beach	Richmond-area studio creating custom wedding and event flowers, quoting from each couple's inspiration boards and venue details.	vcsflowers@gmail.com		https://www.vcsflowers.com/	https://www.instagram.com/vcsflowers/
Elle Loren & Co.	Planning		Richmond	Virginia	Virginia and beyond	Richmond boutique planning and design firm, founded in 2015, handling full-service weddings including large and multicultural celebrations.	hello@ellelorenandco.com		https://ellelorenandco.com/	https://www.instagram.com/ellelorenandco/
The Hive Wedding Collective	Planning		Richmond	Virginia	Richmond, Charlottesville, DC and beyond	Richmond team of planners running full planning and day-of coordination since 2011, with a strong record in modern and multicultural weddings.	christine@thehiveweddingco.com		https://thehiveweddingco.com/	https://www.instagram.com/thehiveweddingco/
Rhythm of Love	Music		Richmond	Virginia	Richmond and surrounding areas	Richmond wedding DJ team providing low-key MC work, ceremony-to-reception music, uplighting and help shaping the day's timeline.	seth@rolweddings.com	804-314-2769	https://www.rolweddings.com/	https://www.instagram.com/rolweddings/
SHO DJ	Music		Richmond	Virginia	Richmond and surrounding areas	Richmond DJ company with tiered wedding packages, dance-floor lighting and add-ons such as photo booths, a 360 booth and live streaming.	info@shodj.net	804-922-6647	https://www.shodj.net/	https://www.instagram.com/_shodj/
Everyday Gourmet	Catering	6010 North Crestwood Ave Suite B	Richmond	Virginia	Richmond area	Richmond caterer with standard and custom wedding menus, from backyard buffets to plated dinners, supplying staff and bar service.	info@egourmetrva.com	804-651-7281	https://www.egourmetrva.com/weddings	https://www.instagram.com/egourmetrva/
Deep Run Roadhouse	Catering	12379 Gayton Road	Henrico	Virginia	Richmond and Central Virginia	Henrico roadhouse catering weddings with barbecue, Southern comfort dishes and Tex-Mex, from rehearsal dinners to sit-down receptions.	catering@deeprunroadhouse.com	804-740-6301	https://deeprunroadhouse.com/weddings/	https://www.instagram.com/deeprunroadhouse/
Groovin' Gourmets	Catering	8501 Sanford Drive	Richmond	Virginia	Richmond and Hampton Roads	Full-service Richmond caterer working since 1999, building chef-led wedding menus around fresh, locally sourced ingredients.			https://www.trolleyhouseva.com/groovin-gourmets	
PRISM HAIR	Hair & Makeup	505 Hull St	Richmond	Virginia	Richmond, Henrico, Glen Allen and surrounding areas	Richmond salon whose bridal team styles hair and makeup in-salon or on location, experienced with every hair type and texture.		804-319-7825	https://www.prismhairrva.com/weddings-events/	https://www.instagram.com/prismbride/
Lou Stevens	Hair & Makeup		Richmond	Virginia	Virginia, nearby states and destination weddings	Richmond makeup artist and hairstylist with over three decades of bridal work, leading an on-location team focused on natural looks.	loustevensinquiries@gmail.com	804-658-9749	https://loustevens.com/	https://www.instagram.com/_loustevens_/
Avenue 42 Salon	Hair & Makeup	5803 Patterson Avenue	Richmond	Virginia		Richmond salon with Patterson Avenue and Short Pump locations offering bridal hair and makeup alongside its everyday salon services.		804-625-4242	https://www.ave42.com/	https://www.instagram.com/ave42salon/
Fat Rabbit Bakery	Cake	2025 Venable Street	Richmond	Virginia		Union Hill bakery and coffee shop in Richmond making custom wedding cakes in rotating, seasonal flavours from quality ingredients.	info@fat-rabbit.com	804-344-3730	https://www.fat-rabbit.com/	https://www.instagram.com/fatrabbitcakes/
Lana's Cakes	Cake		Moseley	Virginia	Greater Richmond	Moseley cake studio creating artistic buttercream wedding cakes for couples across greater Richmond, designed as the reception centrepiece.		804-305-4347	https://www.lanascakesrva.com/	https://www.instagram.com/lanascakesrva/
Corazón Cake Company	Cake		Richmond	Virginia		Fully gluten-free Richmond home bakery making tiered wedding cakes with palette-knife painted florals, plus cupcakes and tasting flights.			https://www.corazoncakeco.com/	
RVA Productions	Videography		Richmond	Virginia	Richmond metro	Richmond videographer with a background in sports and documentary work, offering flat-rate multi-camera wedding films with payment plans.	info@rvaproductions.com	804-482-0773	https://www.rvaproductions.com/weddings	https://www.instagram.com/rva_productions/
Wild Bridge Films	Videography		Richmond	Virginia	East Coast and beyond	Richmond film-makers shooting weddings on vintage Super 8 cameras, delivering short, nostalgic vignettes with vows, toasts and first dances.	contact@wildbridgefilms.com	804-779-5193	https://wildbridgeweddings.com/	https://www.instagram.com/wildbridgefilms/
Cat McCarthy Creative	Videography		Richmond	Virginia	Richmond, Charlottesville, Virginia Beach and the DMV	Richmond documentary-style wedding videographers who film unobtrusively, with two-shooter coverage, drone footage and optional photography.	hello@catmccarthycreative.com		https://www.catmccarthycreative.com/wedding-loved-ones/wedding-videography	https://www.instagram.com/catmccarthycreative/`,
  },
  {
    name: "Charlottesville: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Aaron Watson Photography	Photography		Charlottesville	Virginia	Charlottesville, Washington DC and worldwide	Long-running Charlottesville studio with a photojournalistic approach to weddings, plus in-house printing and framing.	info@aaronwatsonphoto.com	434-202-8031	https://www.aaronwatsonphoto.com/	https://www.instagram.com/aaronwatsonphotography/
Eilish Bailey Photography	Photography		Charlottesville	Virginia	Charlottesville and central Virginia	Documentary wedding photographer shooting largely on film, favouring candid, light-led images over posed portraits.			https://eilishbailey.com/	https://www.instagram.com/eilishbaileyphoto/
Cecilia Photography Co	Photography		Charlottesville	Virginia		Charlottesville photographer blending film and digital, pairing documentary honesty with an editorial eye for weddings.	info@ceciliaphotographyco.com		https://www.ceciliaphotographyco.com/	https://www.instagram.com/ceciliaphotographyco/
Little Acorn Events	Planning		Charlottesville	Virginia	Central Virginia	Charlottesville firm handling full wedding planning, design and production, with a calm, hospitality-trained lead planner.			https://littleacornevents.com/	https://www.instagram.com/littleacornevents/
The One Moment Events Co.	Planning		Charlottesville	Virginia	Charlottesville, DC and destinations worldwide	Charlottesville planning and design studio creating story-led, highly customised weddings at home and abroad.			https://theonemomentevents.com/	https://www.instagram.com/theonemomentevents/
Mary Elizabeth Events	Planning		Charlottesville	Virginia	Charlottesville and destination weddings	Charlottesville planning and design team offering flexible service levels, with experience running destination weddings.			https://maryelizabethevents.com/	https://www.instagram.com/maryelizabethevents/
Hedge Fine Blooms	Florals	115 4th St NE	Charlottesville	Virginia	Charlottesville, Afton, Crozet, Keswick, Free Union and nearby	Downtown Charlottesville flower shop running since 2001, offering wedding consultations and custom event designs.	hedgefineblooms@gmail.com	(434) 293-8825	https://hedgefineblooms.com/	https://www.instagram.com/hedge.fineblooms/
Fiori Floral Studio	Florals	1311 Wertland Street	Charlottesville	Virginia	Charlottesville, Crozet, Ivy, Keswick and UVA	Charlottesville studio near UVA designing custom wedding florals, with a seasonal leaning towards garden blooms such as dahlias.		434-233-4464	https://www.fiorifloralstudio.com/	https://www.instagram.com/fiorifloralstudio/
Horse & Hen	Florals	1260 Crozet Avenue, Unit B	Crozet	Virginia	Crozet, Afton and Charlottesville	Crozet florist working with locally grown, seasonal flowers in natural, textural wedding designs.	horseandhencrozet@gmail.com	(434) 531-0258	https://www.horseandhencrozet.com/	https://www.instagram.com/horseandhen.crozet/
20 South Productions	Music		Charlottesville	Virginia	Central Virginia	Family-run Charlottesville agency booking live bands across many genres and DJs for ceremonies, receptions and rehearsal dinners.	chris@20south.net	(434) 296-1600	https://www.20south.net/	
Big Ray and the Kool Kats	Music		Charlottesville	Virginia	Virginia, DC, Maryland and beyond	Charlottesville party band playing entirely live from ceremony to last dance, with the bandleader also acting as MC.	bigrayandthekoolkats@gmail.com	434-202-1769	https://bigrayandthekoolkats.com/	https://www.instagram.com/bigrayandthekoolkats/
Sam Hill Entertainment	Music		Charlottesville	Virginia	Nationwide and destination weddings	Charlottesville band agency founded in 1995, matching couples with soul, Motown, jazz, bluegrass and Top 40 acts.		434-977-6665	https://www.samhillbands.com/	https://www.instagram.com/samhillentertainment/
L'etoile Catering	Catering		Charlottesville	Virginia	Central Virginia	Charlottesville caterer since 1993 cooking French- and Virginia-inspired menus, served seated, buffet or family style.	inquiry@letoileva.com	434-823-1435	https://letoilecatering.com/	https://www.instagram.com/letoilecatering/
The Local Catering	Catering	824 Hinton Avenue	Charlottesville	Virginia		Catering arm of a Belmont neighbourhood restaurant, building wedding menus around produce from small local farms.	catering@thelocal-cville.com		https://catering.thelocal-cville.com/	https://www.instagram.com/thelocalcatering/
On Location Bridal	Hair & Makeup		Charlottesville	Virginia	Central Virginia and destination weddings	Charlottesville artist Judy Hayward travelling to venues for bridal and wedding-party hair and makeup, with lashes included.	judyhayward@ymail.com	434-825-3151	https://www.onlocationbridal.com/	https://www.instagram.com/onlocationbridal/
Maliha Cakery	Cake		Charlottesville	Virginia	Central Virginia	Boutique cake studio run by Anita Gupta since 2006, known for sugar flowers, wafer paper and custom-flavoured tiers.	anita@malihacakery.com	434-973-3183	https://www.malihacakery.com/	https://www.instagram.com/malihacakery/
Commonwealth Cake Company	Cake		Charlottesville	Virginia	Charlottesville, Washington DC and destinations	Fine-art wedding cake studio taking a limited number of commissions each year, with in-studio or delivered tastings.	info@commonwealthcakecompany.com		https://commonwealthcakecompany.com/	https://www.instagram.com/commonwealthcakeco/
Cake Bloom	Cake	120 10th St. NW	Charlottesville	Virginia	Charlottesville pick-up and delivery	Sister-run Charlottesville bakery making small, made-to-order wedding cakes finished with fresh and pressed flowers.	hello@cakebloom.com	(434) 328-8130	https://cakebloom.com/	https://www.instagram.com/cakebloom/
Iron & Ivy Films	Videography		Charlottesville	Virginia	Virginia, East Coast and destinations	Charlottesville filmmaker Brandi Hall crafting story-led, heirloom wedding films, with an inclusive, affirming approach.			https://ironandivyfilms.com/	https://www.instagram.com/ironandivyfilms/
Film & Flourish	Videography		Charlottesville	Virginia	Virginia, DC, North Carolina and beyond	Charlottesville videographer Andrew Gilford filming weddings, elopements and adventure sessions since 2017.			https://filmandflourish.com/	https://www.instagram.com/filmandflourish/
Sydney Koerber Films	Videography		Charlottesville	Virginia	Worldwide	Husband-and-wife film team from Charlottesville taking a subtle, collaborative approach to refined weddings.			https://www.sydneykoerberfilms.com/	https://www.instagram.com/sydneykoerberfilms/`,
  },
  {
    name: "Charlottesville: hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
A More Beautiful You	Hair & Makeup		Charlottesville	Virginia	Central Virginia	Charlottesville team bringing on-location bridal hair and airbrush makeup to wedding parties across central Virginia for over a decade.	ambyservices@gmail.com	(434) 326-2705	https://www.amorebeautifulyouva.com/	https://www.instagram.com/amorebeautifulyouva/`,
  },
  {
    name: "Virginia Beach: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Keith Cephus Photography	Photography		Virginia Beach	Virginia	Virginia and destination weddings	Virginia Beach photographer with 25 years behind the lens, known for Indian and other multicultural and destination weddings.			https://keithcephus.com/	
Meridith Bright Photography	Photography		Virginia Beach	Virginia	Virginia and beyond	Classic, romantic wedding photography from a Virginia Beach photographer who keeps colours true and the day stress-free.	meridithbrightphoto@gmail.com		https://meridithbrightphotography.com/	https://www.instagram.com/meridithbrightphoto/
Melissa Bliss Photography	Photography		Virginia Beach	Virginia	Virginia Beach, Norfolk, Chesapeake, Portsmouth, Sandbridge and Williamsburg	Lifestyle-led wedding, family and maternity photography across Hampton Roads and the Sandbridge shore.	melissablissphotography@gmail.com	(757) 646-7408	https://www.melissablissphotography.com/	https://www.instagram.com/melissablissphotography/
Audrey Rose Photography	Photography		Norfolk	Virginia	Hampton Roads, Williamsburg, Richmond and Charlottesville	Norfolk wedding photographer making joyful, romantic light-and-airy images for classic Southern weddings.			https://audreyrosephoto.com/	https://www.instagram.com/audreyrosephoto/
Belle Events	Planning		Virginia Beach	Virginia	Hampton Roads	Virginia Beach planning studio offering month-of coordination through full planning, run by a certified planner who also officiates.	weddings@belle-events.com	(757) 818-0796	https://belle-events.com/	https://www.instagram.com/belleevents_hr/
By Love Events & Design	Planning		Virginia Beach	Virginia	Virginia Beach, Richmond, Charlottesville, Washington DC and destinations	Full-service wedding planning and design shaped around each couple's own vision rather than a house template, since 2017.	hello@byloveevents.com		https://www.byloveevents.com/	https://www.instagram.com/byloveevents/
Michelle Amarillo Event Planning	Planning		Virginia Beach	Virginia	Coastal Virginia and destinations	Wedding design and planning for coastal Virginia, from full planning to help for couples organising from far away.	michelle@michelleamarillo.com		https://www.michelleamarillo.com/	https://www.instagram.com/michelleamarilloeventplanning/
Alluring Affairs	Planning		Chesapeake	Virginia	Chesapeake, Virginia Beach, Norfolk and Portsmouth	Event planner coordinating weddings, bachelorette parties, anniversaries and reunions across southeastern Virginia.		(757) 822-8633	https://alluringaffairs757.com/	https://www.instagram.com/alluringaffairs_eventplanning/
Virginia Floral Design & Events	Florals	4940 Rutherford Road, Suite 100	Virginia Beach	Virginia	Hampton Roads	Virginia Beach florist working one-to-one with couples on wedding and event flowers from a Rutherford Road studio.	tina@vbeventstudio.com		https://virginiafloraldesign.com/	https://www.instagram.com/virginiafloraldesign/
Lotus Vows	Florals		Virginia Beach	Virginia	Virginia Beach and Hampton Roads	Romantic wedding florist making bouquets, ceremony arches, arbors and centrepieces, with full bridal-party flowers.	info@lotusvows.com	(239) 286-4943	https://lotusvows.com/	https://www.instagram.com/lotusvows11/
Vika Sokanoff Design	Florals		Virginia Beach	Virginia	Virginia, Maryland and Washington DC	Wedding florist and event draping studio creating editorial, dramatic designs for classic-minded couples.			https://vikasokanoff.com/	https://www.instagram.com/vikasokanoffdesign/
Gather Floral Design	Florals		Virginia Beach	Virginia	Virginia Beach and across Virginia	Virginia Beach floral studio making wedding and special-event flowers and installations, travelling across the state.			https://www.gatherfloral.com/	https://www.instagram.com/gather.floral/
Vinyl Headlights	Music		Virginia Beach	Virginia	Virginia Beach and beyond	Three-piece Virginia Beach wedding band that also DJs between sets and handles MC announcements.	vinylheadlights@verizon.net	(757) 589-4118	https://vinylheadlights.com/	
196 Events	Music		Suffolk	Virginia	Hampton Roads, Richmond and Central Virginia	Wedding DJ team offering planning support, ceremony sound, personalised music and professional MCing.	info@196events.com	(757) 287-4985	https://196events.com/	https://www.instagram.com/196events/
The DJ Company of Virginia	Music		Virginia Beach	Virginia	Virginia Beach, Chesapeake, Norfolk, Portsmouth, Hampton and Newport News	Affordable Virginia Beach-based DJs playing weddings and parties across Chesapeake, Norfolk, Portsmouth and Hampton Roads.			https://thedjcompany.co/	https://www.instagram.com/thedjcompanyofva/
Astro Event Company	Music	2384 Princess Anne Rd	Virginia Beach	Virginia	Virginia Beach and Hampton Roads	Long-running Virginia Beach wedding DJs that also supply rentals, event lighting, photo booths and planning.	Sales@Astroeventco.com	(757) 460-2224	https://www.astroeventcompany.com/	https://www.instagram.com/astroeventcompany/
Mermaid Catering	Catering		Virginia Beach	Virginia	Hampton Roads	Full-service Virginia Beach wedding caterer, led by a chef-owner and repeatedly voted a local favourite.		(757) 358-7904	https://mermaidcatering.com/	
Catering Concepts	Catering		Virginia Beach	Virginia	Hampton Roads	Off-premise caterer serving Hampton Roads since 1993, with custom menus, buffets, kosher options and event design.		(757) 425-5682	https://www.cateringconcepts.net/	https://www.instagram.com/cateringconceptsinc/
TASTE Catering & Events	Catering		Virginia Beach	Virginia	Coastal Virginia	Employee-owned Coastal Virginia caterer, cafe and market with experienced event managers and chefs building custom menus.			https://www.tasteunlimited.com/	https://www.instagram.com/tasteunlimited/
Blushtones	Hair & Makeup		Virginia Beach	Virginia	Hampton Roads and travel	Large Virginia Beach team of makeup artists working in their studio or on location for brides and bridal parties.			https://blushtones.com/	https://www.instagram.com/blushtones/
Adorn Artistry Studio	Hair & Makeup		Virginia Beach	Virginia	Hampton Roads, Richmond and the Outer Banks	On-location bridal hairstylist offering custom wedding styles and extensions, with makeup partnered in.	info@adornbridalhair.com	(757) 362-1561	https://www.adornbridalhair.com/	https://www.instagram.com/adorn.artistry.studio/
Unveiled On-Site Beauty	Hair & Makeup		Virginia Beach	Virginia	Hampton Roads	Virginia Beach wedding hair and makeup team that travels to your getting-ready location.	unveiledonsitebeauty@gmail.com	(757) 702-0210	https://unveiledonsitebeauty.com/	
Sugar Plum Bakery	Cake	1353 Laskin Rd	Virginia Beach	Virginia	Hampton Roads	Non-profit Virginia Beach bakery making wedding cakes since 1987, with delivery and set-up at reception venues.		(757) 422-3913	https://www.sugarplumbakery.org/	https://www.instagram.com/sugarplumbakery/
AbbyCakes	Cake	5660 Indian River Road, Suite 125	Virginia Beach	Virginia	Hampton Roads	Virginia Beach bakery making wedding and celebration cakes, cupcakes and cookie trays since 2000.		(757) 962-0990	https://www.abbycakes757.com/	https://www.instagram.com/abbycakes757/
Crystal Marie Cake Creations	Cake		Virginia Beach	Virginia	Hampton Roads	Custom decorated cakes and hand-crafted desserts made with local ingredients for weddings and other occasions.			https://www.crystalmariecakes.com/	https://www.instagram.com/crystal.marie.cakes/
Brandon Mitchell Films	Videography		Virginia Beach	Virginia	Virginia and beyond	Virginia Beach wedding videographer filming with drones and a full kit to capture the day from every angle.	brandon@brandonmitchellfilms.com		https://brandonmitchellfilms.com/	https://www.instagram.com/brandonmitchellfilms/
Delta Studio Productions	Videography		Virginia Beach	Virginia	Hampton Roads	Virginia Beach videography and photography studio with over fifteen years of wedding and event experience.	delta@dstudiopro.com	(757) 214-4344	https://dstudiopro.com/	https://www.instagram.com/dstudiopro/
Norfolk Wedding Videography	Videography		Norfolk	Virginia	Norfolk, Virginia Beach and Chesapeake	Cinematic wedding films from Norfolk, with drone coverage by FAA-licensed operators at Hampton Roads venues.		(757) 996-4889	https://norfolkweddingvideography.com/	`,
  },
  {
    name: "Roanoke: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Anna Bowser Photography	Photography		Roanoke	Virginia	Virginia, the Carolinas and destinations	Roanoke photographer shooting candid, classic wedding and elopement coverage, with a love of mountain, national park and adventure ceremonies.	hello@annabowserphoto.com	540-798-0568	https://www.annabowserphoto.com/	https://www.instagram.com/annabowserphotography/
Lighthaven Photography	Photography		Roanoke	Virginia	Roanoke, Smith Mountain Lake, Blacksburg, Lynchburg and across Virginia	Roanoke photographer shooting soft, joyful and timeless wedding portraits and couple sessions for brides and grooms across Virginia.	lighthavenphoto@gmail.com		https://www.lighthavenphotography.com/	https://www.instagram.com/lighthavenphotography/
Hoprich Photography	Photography		Roanoke	Virginia		Roanoke photo studio covering weddings, boudoir sessions and events for couples and families around the Roanoke Valley.	HoprichPhotography@gmail.com		https://www.hoprichphotography.com/	https://www.instagram.com/hoprichphotography/
La Bella Vita Event Planners	Planning		Roanoke	Virginia	Roanoke and beyond	Roanoke planning firm offering full, partial and month-of wedding coordination, and happy to travel beyond the valley for the right couple.	labellavitaeventplanner@gmail.com		https://www.labellavitaevents.com/	https://www.instagram.com/labellavitaeventplanners_/
Cypress and Sage Event & Design	Planning		Roanoke	Virginia	Roanoke and Virginia	Boutique Roanoke planning and design studio offering organised, thoughtful wedding planning from full service down to month-of coordination.	info@cypressandsagedesign.com	540-404-2510	https://cypressandsagedesign.com/	https://www.instagram.com/cypressandsagedesign/
The Planning Bee	Planning		Roanoke	Virginia	Roanoke	Roanoke wedding planner offering full-service planning and day-of coordination for couples who want a calm, organised run-up to the wedding.	lauren@planning-bee.com		https://www.planning-bee.com/	https://www.instagram.com/theplanningbeeva/
Gloriosa	Florals	1515 W Ruritan Rd	Roanoke	Virginia		Roanoke florist designing wedding bouquets, centrepieces and event decor from a studio on West Ruritan Road, with a unique-design focus.	maryjo@flowersbygloriosa.com	540-529-6472	https://flowersbygloriosa.com/	https://www.instagram.com/flowersbygloriosa/
Foraged & Cut	Florals		Lynchburg	Virginia		Lynchburg florist offering wedding and event flowers, from bouquets and centrepieces to ceremony decor, with a foraged, locally grown look.	foragedandcut@gmail.com	434-544-1811	https://www.foragedandcut.com/	https://www.instagram.com/foragedandcut/
Blossom & Bliss	Florals		Roanoke	Virginia	Virginia	Floral design studio creating artful, romantic flowers for weddings and events, from intimate celebrations to full wedding weekends.	blossomandblissinfo@gmail.com	540-855-1058	https://www.blossomandbliss.co/	https://www.instagram.com/blossomandblissflowers/
Quest Entertainment	Music		Roanoke	Virginia	Southwest Virginia	Family-owned Roanoke entertainment company providing wedding DJs, open-air photo booths, LED uplighting and a silent disco option.	djquestent@gmail.com	540-588-1113	https://quest-ent.com/	
A Party's Favorite Entertainment	Music		Roanoke	Virginia	Roanoke, Charlottesville, Richmond and across Virginia	Wedding and event DJ company based in Roanoke, adding mobile bar service and interactive entertainment to its reception music.	info@apfent.com	540-249-1234	https://www.apfent.com/	https://www.instagram.com/apartysfav/
Liz's Studio	Music		Lynchburg	Virginia		Lynchburg DJ and MC who weaves live flute into electronic sets for wedding ceremonies and receptions, and also runs karaoke nights.	lizs.studio@yahoo.com	434-209-2478	https://djliz.biz/	https://www.instagram.com/lizs.studio/
Blue Ridge Catering	Catering	522 Salem Ave	Roanoke	Virginia	Western Virginia	Roanoke off-site caterer building original, personalised wedding menus for receptions, rehearsal dinners and celebration brunches.		540-982-7700	https://blueridgecatering.net/	https://www.instagram.com/blueridgecatering/
Pumpernickel Pickle Catering Co	Catering		Salem	Virginia	Roanoke, Salem, Blacksburg, Lynchburg and Charlottesville	Wedding-focused caterer serving the Roanoke and Salem area, with a long gallery of real receptions of every size.	pumpernickelpicklecatering@gmail.com	540-797-6550	https://www.pumpernickelpicklecatering.com/	
Center Stage Catering	Catering	17 Claiborne Ave	Rocky Mount	Virginia		Rocky Mount caterer offering creative menus for weddings and events, alongside family meals, pop-ups and entertainment catering.	events@centerstagefood.com	540-489-7827	https://centerstagefood.com/weddings/	https://www.instagram.com/center.stage.event.tures/
The Refinery Hair & Makeup Studio	Hair & Makeup	3746 Colonial Ave	Roanoke	Virginia	Roanoke	Roanoke hair and makeup studio offering bridal services, with a dedicated bridal phone line and a salon on Colonial Avenue.		540-355-8817	https://therefineryhairstudio.com/	https://www.instagram.com/therefineryhairstudio.roava/
Morgie Makes It Up	Hair & Makeup	1948 Franklin Rd SW, Suite 204	Roanoke	Virginia	Southwest Virginia	Roanoke makeup artist and esthetician serving Southwest Virginia, working from a studio suite with room for bridal parties.	morgieashrn@gmail.com	540-460-9492	https://www.morgiemakesitup.com/	https://www.instagram.com/morgiemakesitup/
K. Renee Beauty	Hair & Makeup		Lynchburg	Virginia	Lynchburg, Roanoke and central Virginia	Lynchburg bridal makeup artist creating customised soft-glam looks for brides and bridesmaids, with travel to your venue available.			https://www.kreneebeautyva.com/	https://www.instagram.com/k_renee_beauty/
Takes the Cake Roanoke	Cake		Salem	Virginia	Roanoke Valley	Salem home bakery making modern buttercream wedding cakes and dessert bars with carefully chosen ingredients for Roanoke Valley couples.			https://www.takesthecakeroanoke.com/	https://www.instagram.com/takesthecakeroanoke/
Sugar Blush Bakery	Cake		Lynchburg	Virginia	Lynchburg and surrounding area	Lynchburg boutique bakery making custom wedding cakes and desserts, with set-up and delivery around the city.			https://www.sugarblushbakery.com/	https://www.instagram.com/sugarblushbaker/
Uncommon Cakes	Cake		Amherst	Virginia	Charlottesville, Lynchburg, Lexington and central Virginia	Central Virginia baker making wedding cakes and cupcakes from scratch in inventive flavours such as crème brûlée and cardamom strawberry.	uncommoncakes.mail@gmail.com	434-882-3894	https://uncommoncakes.wordpress.com/	https://www.instagram.com/uncommoncakesva/
MNF Productions	Videography		Roanoke	Virginia	Roanoke and worldwide	Roanoke video production company that films weddings alongside commercial projects, with licensed drone pilots for aerial footage.	mneilfox@gmail.com	540-355-0019	https://www.mnfproductions.com/	https://www.instagram.com/mnf_productions/
Star City Creations	Videography		Roanoke	Virginia	Roanoke Valley and beyond	Roanoke documentary-style wedding videographer using several cameras and clean audio, with packages from ceremony-only to a full day.			https://www.starcitycreations.com/wedding-videography/	
Elegance Created	Videography		Lynchburg	Virginia	Central Virginia and the East Coast	Central Virginia photographer and videographer making relaxed, cinematic wedding films for couples at Virginia venues and beyond.			https://elegancecreated.com/	https://www.instagram.com/sabin213/`,
  },
  {
    name: "Shenandoah Valley: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Luna Photography	Photography		Harrisonburg	Virginia	The Shenandoah Valley and Charlottesville	Harrisonburg photographer for weddings and family sessions, with set wedding coverage packages and galleries for Valley couples.			https://nancylunaphoto.com/	
Rachel Dodson Photography	Photography		Harrisonburg	Virginia	Harrisonburg and the Shenandoah Valley	Harrisonburg wedding and portrait photographer with a classic, clean style, covering farm weddings and church receptions for Valley couples.	racheldodsonphotos@gmail.com	540-222-7851	https://www.racheldodsonphotos.com/	
Jennifer Nolan Photography	Photography		Berryville	Virginia	The Shenandoah Valley, including Front Royal and Luray, and Northern Virginia	Berryville-based wedding photographers who shoot Valley weddings, from barn and inn celebrations to resort venues, around Front Royal and Luray.	info@jennifernolanphoto.com		https://jennifernolanphoto.com/shenandoah-valley-wedding	https://www.instagram.com/jennifernolanphotography/
Seasoned Events	Planning		Front Royal	Virginia	Winchester, Front Royal, Luray, Harrisonburg and the Piedmont	Wedding planner offering full planning and design as well as month-of coordination for couples in the northern Shenandoah Valley and beyond.	aseasonedevent@gmail.com	331-454-9959	https://www.seasonedevent.com/	https://www.instagram.com/seasonedeventsva/
Rosemary and Lavender Events	Planning		Harrisonburg	Virginia	Harrisonburg and the Shenandoah Valley	Day-of wedding coordinator for small, intimate weddings, taking over a couple's finished plans so they can enjoy the day in the Harrisonburg area.			https://www.rosemaryandlavenderevents.com/	https://www.instagram.com/rosemaryandlavenderevents/
Brooke Shehan Events	Planning		Lexington	Virginia	Lexington, Charlottesville and across Virginia	Lexington wedding planner focused on classic celebrations, offering full planning and design with a limited number of weddings taken each year.			https://brookeshehan.com/	https://www.instagram.com/brookeshehan/
Sparrow's Floral Design	Florals	91 North Main Street	Harrisonburg	Virginia	Harrisonburg, with delivery up to 15 miles	Harrisonburg flower shop making custom wedding bouquets and event flowers, with full-service and a la carte options for couples.	sparrowsflowers@gmail.com	540-209-8074	https://sparrowsfloraldesign.com/	https://www.instagram.com/sparrows_flowers/
One Last Avocado Floral Design	Florals		Timberville	Virginia	Staunton, Charlottesville, Northern Virginia and beyond	Timberville florist designing natural, garden-style wedding flowers, from tented-reception arrangements to candlelit winter weddings.	onelastavocado@gmail.com		https://onelastavocado.com/	https://www.instagram.com/onelastavocadofloraldesign/
Forest & Field Flower Co.	Florals		Front Royal	Virginia	The Shenandoah Valley and Northern Virginia	Front Royal florist creating wedding and event flowers for couples across the Shenandoah Valley and Northern Virginia, with a lookbook to browse.	forestandfieldflowerco@gmail.com	540-622-7441	https://www.forestandfieldflowerco.com/	https://www.instagram.com/forestandfieldflowerco/
Epic Sounds Entertainment	Music		Faber	Virginia	Charlottesville, Harrisonburg, Staunton, Waynesboro and Culpeper	DJ company from Faber with over 25 years of experience, playing hundreds of weddings around Staunton, Harrisonburg and Charlottesville.	lance@epicsoundsentertainment.com	434-989-0219	https://epicsoundsentertainment.com/	
CDJ Weddings and Events	Music		Stephens City	Virginia	Northern Shenandoah Valley, Washington DC metro and Central Virginia	Stephens City wedding DJ service serving the northern Valley around Winchester, with couple testimonials from recent weddings on its site.	cdjweddingsandevents@gmail.com	703-598-5365	https://www.cdjweddingsandevents.com/	
SoundMaster DJs	Music		Harrisonburg	Virginia	Harrisonburg, Staunton, Luray, Waynesboro, Charlottesville and nearby	Wedding DJ team working Harrisonburg and Staunton celebrations, with equipment included and a music planning app for choosing songs.			https://www.soundmasterdjs.com/	https://www.instagram.com/soundmasterdjs/
Hank's Grille & Catering	Catering	49 Bloomer Springs Road	McGaheysville	Virginia		McGaheysville restaurant and caterer with a wedding catering menu, ABC-certified bartenders, and a second kitchen in Dayton.		540-289-7667	https://www.hanksgrilleandcatering.com/	https://www.instagram.com/hanksgrilleandcatering/
Dayton Catering Co.	Catering	400 N Main St	Bridgewater	Virginia	The Shenandoah Valley	Bridgewater caterer serving weddings and other events across the Shenandoah Valley, with its own wedding catering category.		540-908-0029	https://www.daytoncateringco.com/	
Early Katering	Catering	2061F Evelyn Byrd Ave	Harrisonburg	Virginia	Harrisonburg, Lexington, Luray, Charlottesville and Shenandoah County	Harrisonburg caterer with 25 years of weddings behind it, offering menus from country picnic to black-tie served buffet, plated or family style.		540-801-8139	https://earlykatering.com/	
The Studio Hair Salon and Day Spa	Hair & Makeup	353 Neff Avenue	Harrisonburg	Virginia	Luray, Winchester, Charlottesville, Staunton and nearby Valley towns	Harrisonburg salon whose stylists do bridal hair and makeup for the bride and party, either at the salon or on site at the venue.	thestudio@thestudiohairsalon.com	540-434-8188	https://www.thestudiohairsalon.com/bridal	https://www.instagram.com/thestudiohairsalon/
Lydia J. Designs Hair and Makeup	Hair & Makeup	1007 Harper Valley Road	Luray	Virginia	The Shenandoah Valley and beyond	Luray stylist providing wedding hair and makeup on site at the venue or wherever the bride is getting ready.	valjmu2003@gmail.com	540-742-4604	https://www.lydiajdesigns.com/	https://instagram.com/lydiaj.designs_hairandmakeup/
Dazzled by Des LLC	Hair & Makeup	1550 Commerce Rd Suite 200	Staunton	Virginia		Staunton hair and makeup artist offering bridal and bridal party services, with veils and volume styling for the wedding day.	destinyvinson22@gmail.com	757-818-1405	https://www.dazzledbydesllc.com/	https://www.instagram.com/dazzled_bydes/
Claire's Cake Co.	Cake	107 W. Main Street	Monterey	Virginia	Staunton, Harrisonburg, Highland and Bath Counties	Highland County bakery making wedding cakes and offering wedding catering, with tastings for couples around Staunton and Harrisonburg.	clairescakeco@gmail.com	540-468-1800	https://www.clairescakeco.com/weddings	https://www.instagram.com/clairescakeco/
El Paisano Bakery	Cake	56 E Wolfe St	Harrisonburg	Virginia		Family-owned Mexican bakery in Harrisonburg that builds custom wedding cakes, including multi-platform designs and cupcake pairings.		540-209-8892	https://www.elpaisanobakery.com/wedding-cakes	https://www.instagram.com/elpaisanobakery/
Sweet Tooth Bakery	Cake	3034 Valley Ave., Suite 110	Winchester	Virginia	Within an hour's drive of Winchester	Winchester bakery with a tiered cake gallery, making wedding cakes and offering delivery and set-up within an hour's drive.	sweettoothbakerywin@gmail.com	540-667-6155	https://sweettoothbakeryva.com/weddings/	https://www.instagram.com/sweettoothbakeryva/
Studio Mac Films	Videography		Staunton	Virginia	Staunton, Harrisonburg, Charlottesville, Winchester and Richmond	Staunton video studio filming weddings since 2008, with highlight reels and multi-camera full ceremony coverage in three collections.	amacdanel@gmail.com	540-476-0653	https://www.studiomac.info/	https://www.instagram.com/studiomacfilms/
Reel Deal Films	Videography		Harrisonburg	Virginia	The Shenandoah Valley	Harrisonburg videographer making wedding films for Valley couples, with examples from Luray, Stanley and Stanardsville weddings.	ben@reeldealfilms.net		https://www.reeldealfilms.net/	https://www.instagram.com/reeldealfilm/
Ethan Film and Photo	Videography		Front Royal	Virginia	Virginia, Washington DC, Maryland and West Virginia	Front Royal photo and video team near Shenandoah National Park, offering wedding and elopement collections.		703-655-0995	https://ethanfilmandphoto.com/	https://www.instagram.com/ethanfilmandphoto/`,
  },
  {
    name: "Richmond: photography, planning, florals, music, catering, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Sandy Swagger Jones	Photography		Richmond	Virginia	Richmond (RVA)	Richmond portrait and wedding photographer blending documentary candids with directed portraits, with smaller packages for intimate gatherings.	hello@sandyswaggerjones.com		https://www.sandyswaggerjones.com/	https://www.instagram.com/sandyswaggerphoto/
CCS Events	Planning		Richmond	Virginia	Richmond	Richmond event planning firm that handles weddings from design and set-up through day-of logistics.	colleen@ccsevents.com		https://ccsevents.com/	https://www.instagram.com/ccsevents.co/
The Blissful Elite Weddings and Events	Planning		Louisa	Virginia	Richmond, Charlottesville and Fredericksburg	Louisa-based planner offering full and partial planning, day-of coordination and micro-wedding support for couples around Richmond.	theblissfulelite@gmail.com	540-656-3589	https://theblissfulelite.com/	https://www.instagram.com/the_blissful_elite/
FIELD	Florals	311 W. Broad St	Richmond	Virginia	Richmond	Contemporary floral design studio on West Broad Street in Richmond, taking on weddings alongside everyday flowers and gifts.	hello@fieldfloraldesign.com	804-362-8062	https://fieldfloraldesign.com/	https://www.instagram.com/fieldfloral/
Lasting Florals	Florals	3541 Clintwood Road	Midlothian	Virginia	Midlothian	Midlothian flower shop designing custom wedding flowers for each couple, with consultations arranged by phone.		804-839-1047	https://www.midlothianvaflorist.com/wedding-flowers	https://www.instagram.com/debbielastingflorals/
Bunn DJ Company	Music	508 E Franklin St	Richmond	Virginia	Central Virginia, focused on Richmond and Charlottesville	Richmond DJ and MC team providing ceremony audio, dance-floor sound and uplighting, with extras such as audio guest books and photo booths.		804-304-2449	https://bunndjcompany.com/richmond-wedding-djs/	https://www.instagram.com/bunndjrva/
The Party Favors	Music		Richmond	Virginia	Richmond and Central Virginia	Richmond live band playing weddings and corporate events on a flat-rate base package with optional add-ons.	thepartyfavorsband@gmail.com		https://thepartyfavorsband.com/	https://www.instagram.com/thepartyfavorsband/
Autumn's Custom Catering	Catering		Richmond	Virginia	Richmond	Richmond caterer serving upscale comfort food as buffet, family-style or plated meals, with tastings and a mobile kitchen.	autumnscc@gmail.com	804-591-6191	https://autumnscustomcatering.com/	https://www.instagram.com/autumnscaferva
Goodrich Gourmet Catering	Catering		Richmond	Virginia	Richmond, Henrico, Chesterfield and surrounding areas	Full-service caterer based in Richmond for weddings, corporate functions and celebrations, delivering within roughly an hour of the city.	info@goodrichgourmet.com	804-750-1400	https://www.goodrichgourmet.com/	https://www.instagram.com/therealgoodrichgourmet/
Society 11:11	Hair & Makeup		Richmond	Virginia	Richmond, Charlottesville, Hampton Roads and Washington DC	Mobile bridal hair and makeup team in Richmond offering previews, on-site wedding-day styling and travel for destination weddings.	contact@society1111.com	804-808-1541	https://society1111.com/	https://www.instagram.com/_society1111/
Live Fancy Makeup	Hair & Makeup		Richmond	Virginia	Richmond and surrounding areas	Richmond makeup artist specialising in soft glam for brides and wedding parties, who also teaches makeup classes.			https://livefancymakeup.com/	https://www.instagram.com/shannonj.mua/
Bradby Lane Bakery	Cake		Midlothian	Virginia		Midlothian bakery making cakes to order, including wedding cakes, cupcakes and dessert shooters, with tastings available.	BradbyLaneBakery@gmail.com	804-631-5772	https://bradbylanebakery.com/	
Moonlit Pantry Bakery & Cafe	Cake		Richmond	Virginia	Richmond and surrounding cities	Richmond pre-order bakery and cafe making custom cakes and dessert catering for weddings, parties and special events.	Alliyahl@moonlitpantry.com		https://moonlitpantry.com/	https://www.instagram.com/moonlitpantry/
CY Wedding Films	Videography		Richmond	Virginia	Richmond	Richmond videographer making cinematic wedding films from unscripted moments, filmed unobtrusively so couples stay present.	chrisyeattsfilms@gmail.com	804-874-8701	https://www.cyweddingfilms.com/	https://www.instagram.com/cy_weddingfilms/
Little Fox Films	Videography		Richmond	Virginia	Richmond and Central Virginia	Richmond wedding videographer telling intimate, story-led films for young couples across Central Virginia.			https://littlefoxfilms.com/	https://www.instagram.com/littlefoxfilms/`,
  },
  {
    name: "Charlottesville: catering and hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
DaH Catering	Catering	194 Zan Rd	Charlottesville	Virginia		Husband-and-wife Charlottesville caterer for weddings and rehearsal dinners, with bar service under its own alcohol licence.	east.carter@gmail.com	434-242-5498	https://dahcatering.com/	https://www.instagram.com/dahcatering/
Captivating Complexion	Hair & Makeup		Charlottesville	Virginia	Charlottesville and across Virginia	Charlottesville team of independent makeup artists providing on-site wedding makeup, plus in-studio appointments and lessons.	meg@captivatingcomplexion.com		https://www.captivatingcomplexion.com/	https://www.instagram.com/captivatingcomplexion/`,
  },
  {
    name: "Northern Virginia: photography, videography, planning, florals, music, catering, hair & makeup and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Jessica Smith Photography	Photography		Leesburg	Virginia	Leesburg, Ashburn and Northern Virginia	Leesburg photographer with nearly twenty years behind the camera, shooting natural, unfussy wedding and family portraits across Loudoun.	jessicasmithphotography@gmail.com		https://jessicasmithphotography.com/	https://www.instagram.com/jessiesmith220/
Genevieve Leiper Photography	Photography	10 S King Street	Leesburg	Virginia		Leesburg photographer with twenty years of experience, known for clean wedding coverage and end-of-night star portraits.	gleiper@genevieveleiper.com	703-200-0428	https://genevieveleiper.com/	https://www.instagram.com/genevieveleiperphotography/
Darcy Troutman Photography	Photography		Northern Virginia	Virginia	Northern Virginia, Washington DC, Arlington, Alexandria and Maryland	Documentary-style wedding and family photographer who favours relaxed, joyful moments over stiff posing, with lower-cost weekday elopements.	hello@darcytroutmanphotography.com		https://www.darcytroutmanphotography.com/	https://www.instagram.com/darcytroutman_weddings/
Regeti's	Photography		Northern Virginia	Virginia	Washington DC area and Northern Virginia	Husband-and-wife team focused on South Asian, Hindu, Sikh and multicultural weddings, covering multi-day events from mehndi to reception.	info@regetis.com	703-314-7861	https://www.regetis.com/	https://www.instagram.com/theregetis/
Class & Style Productions	Photography		Alexandria	Virginia	Alexandria, Manassas and surrounding Northern Virginia	Women- and veteran-owned photo and film duo in the Alexandria area, shooting weddings, elopements and portraits.			https://classandstyleproductions.com/	https://www.instagram.com/class_style_productions/
JP Collection	Videography		Fairfax	Virginia	Northern Virginia, Washington DC and Maryland	Fairfax-based photographer and filmmaker making documentary-leaning wedding films, with photography and engagement sessions available alongside.			https://www.thejpcollection.com/	https://www.instagram.com/the.jpcollection/
Bakerture	Videography		Leesburg	Virginia	Leesburg, Virginia and Washington DC	Leesburg studio pairing a photo and film team, shooting weddings in a documentary style with an editorial finish since 2014.	hello@bakerture.com		https://www.bakerture.com/	https://www.instagram.com/bakerture/
Moments Mirror	Videography		Northern Virginia	Virginia	Arlington, Alexandria, Fairfax, McLean, Falls Church, Reston, Washington DC and Maryland	Photography and video team covering weddings across Northern Virginia, including South Asian and other multicultural celebrations.	momentsmirror@yahoo.com		https://momentsmirror.com/	https://www.instagram.com/momentsmirror/
Wedding Stories By Tania	Videography		Northern Virginia	Virginia	Northern Virginia, DC Metro	Photojournalistic photo and video team that stays unobtrusive on the day, offering matching film and photo coverage for Northern Virginia weddings.	tania@weddingstoriesbytania.com	703-489-5999	https://weddingstoriesbytania.com/	https://www.instagram.com/weddingstoriesbytania/
Photrixwink	Videography		Northern Virginia	Virginia	DMV area and nationwide	Photo and video studio covering weddings and cultural ceremonies in the DMV, with a photo booth add-on.	Photrixwink@gmail.com	571-251-1638	https://photrixwink.com/	https://www.instagram.com/photrixwink/
Best Wishes Weddings	Planning		Leesburg	Virginia	Loudoun County and Northern Virginia	Loudoun-based coordinators offering day-of coordination and fuller planning, matching each couple with a planner suited to their style.			https://bestwishesweddings.com/	https://www.instagram.com/bestwishesloudoun/
An Exceptional Event	Planning		Loudoun County	Virginia	Loudoun County and Northern Virginia	Loudoun planner handling day-of coordination, partial planning and full weddings, keeping timelines and vendors in hand so couples can relax.	info@anexceptionalevent.com	703-505-3677	https://www.anexceptionalevent.com/	https://www.instagram.com/anexceptionalevent/
Dusk to Dawn Events	Planning		Northern Virginia	Virginia	Northern Virginia, Washington DC and Maryland	Wedding and corporate event planner serving Northern Virginia venues, from Leesburg and Manassas to Gainesville, Haymarket and Warrenton.	info@dusktodawnevents.com		https://www.northernvirginiaweddingplanner.com/	https://www.instagram.com/events.dusktodawn/
The Event Group International	Planning		Reston	Virginia	Northern Virginia, Washington DC and beyond	Reston-based planning, design and management firm for weddings and corporate events, with certified wedding professionals assigned to each client.			https://www.teginternational.com/	
Petal's Edge Floral Design	Florals	1105 Oronoco St	Alexandria	Virginia	Greater Washington DC area	Old Town Alexandria florist designing custom wedding and event flowers, with daily flower delivery from its shop.	info@petalsedge.com	703-518-8488	https://www.petalsedge.com/	https://www.instagram.com/petalsedgeDC/
Wisteria Florals	Florals		Alexandria	Virginia	Alexandria	Alexandria florist with over twenty years of experience building custom wedding flowers around each couple's tastes.		(703) 360-0278	http://www.wisteriaflorals.com/	https://www.instagram.com/wisteriastudio/
Ultimate Floral Designs	Florals	9912-B Georgetown Pike Unit 104	Great Falls	Virginia	Great Falls, McLean, Arlington, Reston, Vienna, Falls Church, Herndon and Washington DC	Great Falls studio founded in 2005 making custom wedding and event flowers, using premium Dutch-grown stems.	ultimatefloraldesigns@verizon.net	(703) 759-5001	http://www.ultimatefloraldesigns.com/	https://www.instagram.com/weddingbyflora/
Azi Flowers	Florals	3045 Columbia Pike	Arlington	Virginia	Arlington, Alexandria, Fairfax, Vienna, Falls Church, McLean, Reston, Herndon and Springfield	Arlington flower shop designing bridal bouquets, ceremony installations and reception centrepieces, with delivery and setup.	wecare@aziflower.com	(703) 618-2152	https://www.aziflower.com/	https://www.instagram.com/azi.flowers/
Tulip Decorations	Florals		Fairfax	Virginia		Fairfax florist creating custom wedding flowers and decor, mixing fresh and high-quality artificial blooms.	Manal@tulipdecorations.us	515-829-2580	https://www.tulipdecorations.us/	https://www.instagram.com/tulip.decorations.us/
String Quartet of Northern Virginia	Music		Alexandria	Virginia	Alexandria and the DC metro area	Woman-owned group of professional DC-area classical musicians playing wedding ceremonies, cocktail hours and receptions.	stringquartetnova@gmail.com	(703) 473-8986	http://northernvirginiastringquartet.com/	https://www.instagram.com/stringquartetnova/
Pulse Entertainment	Music		Fairfax	Virginia	Northern Virginia, Southern Maryland and Washington DC	Fairfax wedding DJ and lighting company with full-time staff and backup cover for every event.	Contact@PulseWeddings.com	(703) 520-9898	https://pulseweddings.com/	
Dominion Wedding Entertainment	Music		Northern Virginia	Virginia	Northern Virginia, Washington DC and Maryland including Manassas, Haymarket, Leesburg and Fairfax	DJ and emcee for weddings, with monogram lighting and photo booth hire, covering Prince William, Loudoun and Fauquier.	bob@dominionwed.com	703-989-1874	https://www.dominionweddingentertainment.com/	https://www.instagram.com/dominionweddingentertainment/
NDavis Music	Music		Leesburg	Virginia		Leesburg-based musician and DJ offering live music, sound and lighting, with a focus on weddings in the DC area.			https://ndavismusic.com/	https://www.instagram.com/ndavismusic/
DJ's of Virginia	Music		Northern Virginia	Virginia	Northern Virginia, Washington DC and Maryland including Leesburg, Middleburg and Warrenton	Wedding DJ company with tiered packages and multicultural MC services, plus photo booth and lighting add-ons.	info@djvirginia.com	(703) 832-6670	https://djvirginia.com/	https://www.instagram.com/djvirginiapro/
RSVP Catering	Catering	2930 Prosperity Avenue	Fairfax	Virginia	Washington DC metro area	Fairfax caterer providing food and event service for weddings, social events and corporate functions.	info@rsvpcatering.com	703-573-8700	https://www.rsvpcatering.com/	https://www.instagram.com/rsvpcateringdc/
Rosendale Events NOVA	Catering		Leesburg	Virginia	Northern Virginia	Leesburg caterer led by Certified Master Chef Rich Rosendale, offering upscale menus for weddings and private events.	Info@rosendalenova.com	(703) 967-8301	https://www.rosendaleeventsnova.com/	https://www.instagram.com/rosendaleevents.nova/
Design Cuisine	Catering	2659 South Shirlington Rd	Arlington	Virginia	Washington DC, Virginia and Maryland	Arlington special-event caterer serving the DC region, with wedding work shown on its site.	inquiry@designcuisine.com	703-979-9400	https://designcuisine.com/	https://www.instagram.com/designcuisine/
Helga's Caterers	Catering	8466-E Tyco Road	Vienna	Virginia	Northern Virginia, Washington DC and Maryland	Family-run Vienna caterer, founded in 1981, handling food, drinks and event planning for weddings and galas.		703-556-0780	http://www.helgascatering.com/	
Windows Catering	Catering	5724 General Washington Drive	Alexandria	Virginia	Washington DC, Virginia and Maryland	Alexandria caterer with around forty years in business, offering detailed food and service for weddings and galas.		703-519-3500	http://www.catering.com/	https://www.instagram.com/windowscatering/
Dana's Cake Shoppe	Cake	1604 Village Market Blvd SE #125	Leesburg	Virginia	Leesburg and Northern Virginia	A Leesburg bakery that designs custom wedding cakes and dessert tables, with tastings arranged through a form on its website.	order@danascakeshoppe.com	703-675-4222	https://www.danascakeshoppe.com/	https://www.instagram.com/danascakeshoppe/
Heidelberg Pastry Shoppe	Cake	2150 N. Culpeper Street	Arlington	Virginia	Arlington and Northern Virginia	An Arlington pastry shop that bakes wedding cakes and groom's cakes, publishing galleries, options and price sheets for couples to browse.		703-527-8394	https://heidelbergbakery.com/	
Edibles Incredible Desserts	Cake	22735 Executive Drive Suite 190	Sterling	Virginia	Washington D.C. metropolitan area	A Sterling bakery whose pastry chefs and decorators make wedding cakes for couples across the Washington D.C. area.	weddingconsultant@ediblesincredible.com	703-437-3008	https://www.ediblesincredible.com/	https://www.instagram.com/ediblesincredible/
Liberty Baking Co.	Cake	10782 Fairfax Blvd Suite D	Fairfax	Virginia	Fairfax and Northern Virginia	A Fairfax bakery run by two pastry chefs, offering wedding cakes through an enquiry form and tastings in its shop.	hello@libertybaking.com	703-662-1072	https://libertybaking.com/	https://www.instagram.com/libertyandjisoo/
Dunn From Scratch	Cake	13493 Arcadian Dr.	Leesburg	Virginia	Leesburg, Loudoun and Northern Virginia	A boutique Leesburg studio making wedding cakes and dessert displays, with a wedding portfolio and tasting enquiries online.	hello@dunnfromscratch.com	703-200-2540	https://dunnfromscratch.com/	https://www.instagram.com/dunnfromscratch/
Cakes by Steph	Cake		Leesburg	Virginia	Northern Virginia, the Shenandoah Valley and Washington DC	A Leesburg cake maker, baking from scratch and delivering by hand within roughly 45 miles for weddings and other celebrations.		240-471-5637	https://cakesbystephva.com/	https://www.instagram.com/_cakes_bysteph_llc/
Taylor Bailey Makeup Artistry	Hair & Makeup		Lorton	Virginia	Northern Virginia and Washington DC	A licensed cosmetologist offering skin-focused soft-glam makeup for weddings, working on location or in her Lorton studio.	taylor@taylorbaileymakeupartist.com	703-568-3864	https://taylorbaileymakeupartist.com/	https://www.instagram.com/taylorbailey.mua/
Carla Reis Beauty	Hair & Makeup		Alexandria	Virginia	Alexandria and Northern Virginia	An Alexandria artist doing soft-glam bridal makeup and polished hairstyles, with a calm approach on the wedding morning.		571-438-3303	https://www.carlareisbeauty.com/	
Alina Mills Makeup	Hair & Makeup		Falls Church	Virginia	Falls Church, Leesburg and the wider DMV	A bridal hair and makeup artist based in Falls Church with a Leesburg studio, travelling within 20 miles of it without a fee.	makeup.alinamills@gmail.com	256-458-0742	https://www.alinamills-makeup.com/	https://www.instagram.com/dc.dmv_makeup/
Salon SBS	Hair & Makeup		Aldie	Virginia	Aldie, Loudoun and Northern Virginia	An Aldie salon with certified makeup artists and stylists who offer bridal hair and makeup, booked through an enquiry form.	info@salonsbs.com	571-373-0100	https://www.salonsbs.com/	https://www.instagram.com/stylesbyswati_salonsbs/
Reston Wedding Hair and Makeup	Hair & Makeup		Reston	Virginia	Reston and Northern Virginia	A mobile team of bridal hair stylists and makeup artists serving Reston and nearby Northern Virginia towns for weddings.		703-782-9694	https://restonweddinghairandmakeup.com/	https://www.instagram.com/makeoverbykyung/`,
  },
];

export default batches;
