import type { VendorBatch } from "@/lib/vendor-batches";

// Washington vendor batches. Every row's State is "Washington". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Seattle: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Stephanie Cristalli Photography	Photography		Seattle	Washington	Mostly Washington, travel considered	Timeless, polished wedding photography from a photographer with 600-plus Washington weddings who caps her calendar at 20 a year.	stephanie@stephaniecristalli.com	206.783.8985	https://www.stephaniecristalli.com/seattle-wedding-photography	https://www.instagram.com/stephaniecristalliphotography/
Tom Ellis Photography	Photography	600 7th Ave, Suite 301	Seattle	Washington	Seattle and Washington State, plus destination weddings	Storytelling wedding photographer with 30-plus years behind the lens, offering film or digital and experienced with Indian, Japanese and Chinese weddings.	tom@tomellisphoto.com	425-646-2790	https://www.tomellisphoto.com/	https://www.instagram.com/tom_ellis_photography/
Adrien Craven Photography	Photography		Seattle	Washington	Puget Sound, Olympic and Kitsap Peninsulas, San Juan Islands and worldwide	Documentary-style wedding and elopement photographer with 15-plus years of experience, often working on the islands and peninsulas of the Sound.			https://adriencraven.com/	https://www.instagram.com/adriencraven/
Doug Hall	Photography		Seattle	Washington		Wedding and elopement photographer shooting on 35mm and medium-format film alongside digital, with a lean towards mountain and backcountry days.			https://douglasrhall.com/	https://www.instagram.com/douglasrhall/
Willow & Ivy Events	Planning		Seattle	Washington	Seattle and worldwide	Boutique planning and design studio taking a limited number of weddings each year, with a playful fine-art style and a focus on guest experience.	alex@willowandivyevents.com		https://willowandivyevents.com/	https://www.instagram.com/willowandivyevents/
Little Wedding Blush	Planning		Seattle	Washington	Seattle, Chicago and worldwide	Certified planner specialising in Indian, South Asian and fusion weddings, from coordination and virtual planning up to complete design.	hello@littleweddingblush.com	(206) 495-8724	https://littleweddingblush.com/	https://www.instagram.com/littleweddingblush/
Sweet and Soul Design	Planning		Seattle	Washington	Seattle and worldwide	Fine-art wedding planning team offering day-of coordination through full planning and design, plus elopement and destination packages.	info@sweetandsouldesign.com	425.766.7791	https://sweetandsouldesign.com/	https://www.instagram.com/sweetandsouldesign/
Honey Water Flowers	Florals		Seattle	Washington		Husband-and-wife floral studio that grows much of its own wedding flowers in a seaside garden plot, giving a loose, just-picked look.	hello@honeywaterflowers.com		https://honeywaterflowers.com/	https://www.instagram.com/honeywaterflowers/
Butterfly's Rest	Florals	800 5th Avenue, Ste L160	Seattle	Washington	Seattle, the Eastside and the Pacific Northwest	Designer-led downtown floral studio making seasonal, foam-free wedding flowers shaped around the venue, with a retail shop and workshops too.	info@butterflysrest.com	(425) 298-3780	https://butterflysrest.com/	https://www.instagram.com/butterflysrest/
Nadira Design	Florals		Seattle	Washington		Seattle floral studio sourcing seasonally and locally, known for blending cultural traditions such as Indian weddings with Pacific Northwest style.	amanda@nadiradesign.com		https://nadiradesign.com/	https://www.instagram.com/nadira_design/
Emerald City Sound	Music		Seattle	Washington	Greater Puget Sound	Owner-run DJ and MC outfit with over a decade of weddings, offering custom playlists, timeline management, uplighting and dance lighting.	emeraldcitysound@gmail.com	206.498.9072	https://emeraldcitysound.com/	https://www.instagram.com/emeraldcitysound/
Limitless Events	Music	901 5th Ave	Seattle	Washington	Western Washington, from Olympia to Bellingham	Family-run DJ and MC team covering ceremony sound, receptions, uplighting and photo booth hire for weddings across Western Washington.		206.807.3058	https://limitlesseventdjs.com/	https://www.instagram.com/limitlesseventdjs/
Puget Sound Strings	Music		Seattle	Washington	Seattle, Bellevue and Tacoma	String ensemble founded in 2010 offering duo to quintet line-ups, custom arrangements and add-on harp, flute, trumpet or piano for ceremonies.	bookings@pugetsoundstrings.com		https://pugetsoundstrings.com/	https://www.instagram.com/thepugetsoundstrings/
Herban Feast	Catering	570 Roy St	Seattle	Washington	Greater Seattle and partner venues across Washington	Farm-to-table caterer using herbs and vegetables from a partner farm, serving buffets, family-style and plated menus at many Seattle venues.	info@landmarkeventco.com	206-285-7846	https://landmarkeventco.com/herban-feast-catering/	https://www.instagram.com/herbanfeast/
Seasoned in Seattle	Catering	5619 MLK Jr. Way South	Seattle	Washington		Farm-to-table caterer in south Seattle building seasonal wedding menus and handling the table settings and finer event details.	events@seasonedinseattle.com	(206) 723-5596	https://www.seasonedinseattle.com/	https://www.instagram.com/seasonedinseattle/
The Tall Chef	Catering	426 South Massachusetts Street	Seattle	Washington	Greater Seattle	Chef-driven caterer using Washington seafood and foraged produce, with menus from Pacific Northwest to paella and bespoke wedding cocktails.	kate@thetallchef.com	206.250.3722	https://thetallchef.com/	https://www.instagram.com/thetallchef/
Old Ballard Catering Co.	Catering	1505 NE 65th St	Seattle	Washington		Brother-and-sister catering company offering custom wedding packages, from barbecue and buffets to custom menus, with bartenders and servers.	joann@oldballardcc.com	206-379-7129	https://oldballardcateringco.com/	https://www.instagram.com/oldballardcateringco/
Bridal Beauty Agency	Hair & Makeup	55 S Atlantic St, Ste 210	Seattle	Washington		Curated team of bridal hair and makeup artists with an editorial eye, managing booking, scheduling and the wedding-morning timeline.	bridalbeautyagency@gmail.com		https://bridalbeautyagency.com/	https://www.instagram.com/bridalbeautyagency/
GLAM by Sassy	Hair & Makeup		Renton	Washington	Seattle area, the Pacific Northwest and beyond	On-site bridal hair and makeup team working with all skin tones since 2009, adding skin prep and wellness treatments to wedding packages.	glambysassy@gmail.com	(206) 973-3764	https://glambysassy.com/	https://www.instagram.com/glambysassy/
Velvet & Venus	Hair & Makeup		Seattle	Washington	Seattle area	On-location bridal hair and makeup artist with film and editorial experience, offering airbrush makeup, updos and a consultation for each bride.	velvetandvenusbeauty@gmail.com	206.635.0980	https://velvetandvenus.com/	https://www.instagram.com/velvetandvenusbeauty/
Pacific Artistry	Hair & Makeup	5335 Northeast 4th Street #2	Renton	Washington	Seattle, Bellevue, Issaquah and the Pacific Northwest	Renton salon with a team of nine-plus artists who travel to venues for bridal party hair and makeup, with in-salon trials beforehand.	info@pacificartistry.com	(425) 786-7976	https://pacificartistry.com/	
Byen Bakeri	Cake	15 Nickerson St, Suite D	Seattle	Washington		Seattle Scandinavian bakery making bespoke wedding cakes, including the traditional ring-tiered kransekake and hand-piped flower cakes.		206-218-1000	https://www.byenbakeri.com/wedding-cakes	https://www.instagram.com/byen_bakeri/
Artful Layerz	Cake		Seattle	Washington	Seattle	Georgetown cake studio where a pastry chef with 20-plus years makes classic to avant-garde wedding cakes, with vegan and gluten-free options.	info@artfullayerz.com	(206) 297-9634	https://artfullayerz.com/	https://www.instagram.com/artfullayerz/
Flour Lane Bake Shop	Cake		Seattle	Washington		Woman-owned Seattle bake shop making modern custom wedding cakes along with cupcakes, brownies and other desserts for celebrations.	flourlanebakeshop@gmail.com		https://flourlanebakeshop.com/	https://www.instagram.com/flourlanebakeshop/
Rebecca Lynn Films	Videography		Seattle	Washington	Seattle and the Pacific Northwest, plus travel across the West	Documentary wedding videographer capturing unscripted toasts, bloopers and reactions, and openly celebrating LGBTQ+ couples.			https://rebeccalynnfilms.com/	
Diana Gas	Videography		Seattle	Washington	Seattle, the Pacific Northwest and worldwide	Cinematic, story-driven wedding and elopement films that focus on genuine emotion, for Seattle-area and destination celebrations.	hi@dianagas.com		https://www.dianagas.com/	https://www.instagram.com/_dianagas/
Pixeldust Weddings	Videography		Seattle	Washington	Pacific Northwest	Wedding film studio working since 2012 with an unobtrusive, cinematic approach, filming couples of all cultures and traditions.		206.462.5490	https://seattle-wedding-videographer.com/	https://www.instagram.com/pixeldust_weddings/`,
  },
  {
    name: "Spokane: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Shanoah Bri Photography	Photography		Spokane	Washington	Spokane	Candid, documentary-leaning wedding photographer capturing the in-between moments, with elopement packages and an engagement session included.			https://shanoahbriphotography.com/	https://www.instagram.com/shanoahbriphotography/
Jacie Van B Photography	Photography		Spokane	Washington	Pacific Northwest	Wedding and lifestyle photographer favouring honest, unposed moments and a relaxed, friend-like approach on the day.			https://jacievanbphoto.com/	https://www.instagram.com/jacievanb/
Arch & Elm Photography	Photography		Spokane	Washington	Spokane, Seattle, North Idaho and Montana	Documentary wedding photographer with light-touch posing and a warm, true-to-colour, film-inspired look, offering tiered full-day collections.	archandelmphoto@gmail.com		https://archandelm.com/weddings	https://www.instagram.com/archandelmphotography/
Crystal Madsen Photography	Photography		Spokane	Washington	Spokane County	Candid, emotive wedding photography with gentle creative direction, from short weekday elopement coverage to full nine-hour days.			https://crystalmadsen.com/pricing/spokane-weddings/	https://www.instagram.com/crystalmadsenphotography/
The Good Karen Events	Planning		Spokane	Washington	Spokane, Coeur d'Alene, Sandpoint and surrounding areas	Wedding planner offering full planning, partial planning and day-of coordination, acting as the couple's advocate from start to finish.	karen@thegoodkarenevents.com		https://www.thegoodkarenevents.com/	https://www.instagram.com/the.good.karen.events/
Beck & Co. Events	Planning		Spokane	Washington		Spokane wedding planning studio offering full, partial and month-of planning plus a la carte help for couples who need just a few pieces.	mariah@beckandcoevents.com	(509) 368-1730	https://www.beckandcoevents.com/	
Crescent Moon Events	Planning		Spokane	Washington	Spokane and North Idaho	Wedding and event coordinators offering everything from virtual and day-of coordination to partial and full planning across the region.	kristen@crescentmoonevents.com	(509) 903-5788	https://crescentmoonevents.com/	https://www.instagram.com/crescentmoonevents1/
Every Moment Events	Planning		Spokane	Washington	Greater Spokane and North Idaho	Planning team offering full-service planning or day-of coordination, with its own rental stock of arbors, signage, linens and decor.	Carrie@EveryMomentEvents.com	(509) 557-0339	https://www.everymomentevents.com/	https://www.instagram.com/everymomenteventspnw/
All In The Details Floral Design	Florals		Spokane	Washington	Spokane and Northern Idaho	Wedding-focused floral design studio led by Kira, working with in-season, locally sourced blooms tailored to each venue.	info@allinthedetailsflowers.com	(509) 474-0877	https://www.allinthedetailsflowers.com/	https://www.instagram.com/allinthedetailsflowers/
Christina Rose Florals	Florals		Elk	Washington		Rural floral studio north of Spokane creating organic, garden-style wedding arrangements and installations from mostly locally grown flowers.	christinaroseflorals@gmail.com	(509) 951-8841	https://www.christinaroseflorals.com/	https://www.instagram.com/christinarosefloralsanddesign/
Daisies in May Flower Farm & Florist	Florals		Spokane	Washington	Spokane, Liberty Lake, Colbert and North Idaho	Flower farm and florist growing its own peonies, dahlias and ranunculus for seasonal, garden-style wedding florals, full service or a la carte.	loreen@daisiesinmayflowerfarm.com	(509) 808-4992	https://daisiesinmayflowerfarm.com/	https://www.instagram.com/daisies.in.may/
Big Show Mobile Entertainment	Music		Spokane	Washington		Wedding DJ and master of ceremonies Lance Morris, pairing hosting and music with venue lighting design for receptions.	Lance@bigshowmobile.com	(509) 990-0445	https://bigshowmobile.com/	
New Beginnings DJ's	Music		Spokane	Washington	Spokane, Coeur d'Alene and surrounding areas	Wedding DJ and MC company operating since 1998, with all-inclusive pricing and an online planning tool for couples.	info@newbeginningsdjs.com	(509) 216-8776	https://www.newbeginningsdjs.com/	
The Ivory Table	Catering	1822 E Sprague Ave	Spokane	Washington	Spokane and Coeur d'Alene	Full-service caterer known for custom menus, polished presentation and professional service staff for weddings across the Inland Northwest.	catering@ivorytable.com	(509) 999-2703	https://ivorytable.com/	https://www.instagram.com/ivorytable/
Nectar Catering and Events	Catering		Spokane	Washington		Caterer of nearly 15 years offering creative custom menus and bar service off-site or at its historic downtown venue.	catering@nectarcateringandevents.com	(509) 951-2096	https://nectarcateringandevents.com/	https://www.instagram.com/nectarcateringevents/
A Catered Affair	Catering		Spokane	Washington	Greater Spokane and Coeur d'Alene	Locally owned full-service caterer of 25-plus years, with menus adaptable for gluten-free, vegan and other dietary needs.	ChelseaD@ACateredAffair.org	(509) 230-1596	https://acateredaffair.org/	
Alexi Sage	Hair & Makeup		Spokane	Washington	Spokane and the Pacific Northwest	Travelling hair and makeup artist with editorial, film and television experience, offering bridal packages and a la carte services.		(509) 939-3178	https://www.alexisage.com/	https://www.instagram.com/alexi.sage/
Kiss and Makeup	Hair & Makeup	1403 W Garland Ave, Suite A	Spokane	Washington		Inclusive Garland District salon specialising in bridal hair and makeup, with trials included and on-site styling for wedding parties.			https://www.kissandmakeupspokane.com/	https://www.instagram.com/kissandmakeup114/
Anna Rose Artistry	Hair & Makeup		Spokane	Washington	Spokane, Coeur d'Alene and the Pacific Northwest	Bridal makeup artist offering a concierge-style experience with all-inclusive packages, all-day touch-ups and personal assisting.	annamumau@gmail.com	(509) 690-6949	https://www.annaroseartistry.com/	https://www.instagram.com/anna_mumau_makeup/
Sweet Evie's Bakery	Cake		Spokane	Washington	Greater Spokane area	Custom, made-to-order bakery designing bespoke wedding cakes and dessert platters, with a guided cake design process.	sweeteviesbakeshop@gmail.com	(509) 903-8103	https://www.sweeteviesbakery.com/	https://www.instagram.com/sweeteviesbakeshop/
Sweet Frostings Blissful Bakeshop	Cake	15 S Washington St	Spokane	Washington		Spokane bakeshop with two locations crafting bespoke wedding cakes and dessert spreads, with gluten-free and vegan flavours available.	info@sweetfrostingsbakeshop.com	(509) 242-3845	https://sweetfrostingsbakeshop.com/	
Sweet World Cakes	Cake	1104 W Wellesley Ave	Spokane	Washington		North Spokane scratch bakery making wedding cakes customised to the couple's theme, colours and flavours, plus desserts and cupcakes.	sweetworldcakesbakery@gmail.com	(509) 467-0083	https://sweetworldcakes.com/	https://www.instagram.com/sweetworldcakesspokane/
Grace Media Films	Videography		Spokane	Washington	Spokane, Coeur d'Alene, Seattle and nationwide	Wedding film company with over a decade of cinematic wedding films and trailers across the Inland Northwest and beyond.	contact@gracemedia.info	(509) 251-5152	https://www.gracemedia.info/	https://www.instagram.com/gracemediafilms/
Noah K. Film & Photo	Videography		Spokane	Washington	Spokane, Coeur d'Alene, Sandpoint, Chelan and the Inland Northwest	Wedding videographer and photographer with more than 100 weddings captured, offering film and photo coverage from one studio.		(509) 339-4620	https://www.noahkfilms.com/	https://www.instagram.com/noahk.filmandphoto/
JoVan Films	Videography		Spokane	Washington	Spokane, Seattle and Coeur d'Alene	Spokane-native videographer making cinematic, adventurous wedding films and limiting bookings to a select few couples each year.			https://www.jovanfilms.com/	https://www.instagram.com/jovan_films_/`,
  },
  {
    name: "Tacoma: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Sage and Soul Photography	Photography	202 St Helens Ave	Tacoma	Washington	Seattle-Tacoma, the wider Pacific Northwest and abroad	Tacoma studio shooting weddings, events, portraits and commercial work, with video offered alongside the photography.	hello@sageandsoulphotography.com	253-224-0300	https://www.sageandsoulphotography.com/	https://www.instagram.com/sageandsoulphotography/
Anchor & Lace	Photography		Tacoma	Washington	Pacific Northwest and worldwide	Tacoma husband-and-wife team photographing weddings and elopements in an artistic, romantic and timeless style.			https://anchorandlace.com/	https://www.instagram.com/anchorandlacephoto/
Kelli Hodges Photography	Photography		Gig Harbor	Washington	Gig Harbor, Tacoma and the wider Pacific Northwest	Gig Harbor photographer with a decade of wedding work, known for timeless, natural-light images that mix candid and posed moments.	kelli@kellihodgesphotography.com	253.224.8040	https://www.kellihodgesphotography.com/	https://www.instagram.com/kellihodgesphotography/
Lauren Bentley Photography	Photography		Federal Way	Washington	Snohomish, Seattle, Tacoma, Olympia and destinations	Federal Way photographer with 15 years behind the camera covering weddings, engagements and proposals, with set packages published openly.	lbentleyphoto@gmail.com		https://lbentley.com/tacoma-wedding-photography	https://www.instagram.com/lbentleyphoto/
Cascade Light Photography	Photography		Seattle	Washington	Seattle, Tacoma and the Pacific Northwest	Seattle studio offering documentary, fine-art wedding coverage plus engagement sessions and elopements, regularly working in the Tacoma area.			https://www.seattletacomaweddingphotographer.com/	
Megan Montalvo Photography	Photography		Seattle	Washington	Seattle, Olympia, Tacoma, Mount Rainier and destinations	Adventure-minded photographer for elopements and intimate weddings, planning locations with couples and often shooting around Point Defiance and Rainier.			https://meganmontalvophotography.com/	https://www.instagram.com/meganmontalvophoto/
Jenna Bechtholt Photography	Photography		Seattle	Washington	Pacific Northwest and worldwide	Natural-light, photojournalistic wedding photographer with over a decade of experience, working across Puget Sound including Tacoma.			https://www.jennabechtholt.com/tacoma-wedding-photographer/	https://www.instagram.com/jennabechtholt/
Solaire Visual Studio	Videography		Tacoma	Washington	Seattle and Tacoma	Tacoma film studio making relaxed, cinematic wedding films, with 4 to 8 hour coverage options, highlight reels, raw footage and engagement sessions.	Solairevisualstudio@gmail.com		https://www.solairevisualstudio.com/wedding	https://www.instagram.com/solairevisualstudio/
RcMEDIA Photography	Videography	8415 54th St NW	Gig Harbor	Washington	Gig Harbor, Tacoma and greater Seattle	Gig Harbor husband-and-wife team producing cinematic wedding films for couples around Tacoma and Puget Sound, working from a local studio.	info@RcMEDIAphotography.com	253 225 2497	https://rcmediaphotography.com/wedding-films/	https://www.instagram.com/rcmedia_photography/
Pixeldust Weddings	Videography		Seattle	Washington	Tacoma and southern Washington	Wedding videographer delivering a feature film plus a sneak peek or highlight edit, with Tacoma waterfront and nautical venues a regular backdrop.		206.462.5490	https://seattle-wedding-videographer.com/tacoma-wedding-videographer	https://www.instagram.com/pixeldust_weddings/
Upward Films	Videography		Olympia	Washington	Seattle, Tacoma, Olympia and across Washington, plus destinations	Olympia filmmaker making personal, story-led wedding films and travelling regularly to Tacoma, Seattle and central Washington venues.		360.485.0123	https://upwardfilms.com/	https://www.instagram.com/upwardfilms/
Moments and Mountains Photo and Film	Videography		Olympia	Washington	Olympia, Tacoma, Lacey, Chehalis and nearby	Olympia photo and film team covering weddings as one integrated crew, so couples avoid hiring separate photographer and videographer.			https://momentsandmountains.com/s-j-tacoma-wedding-moments-and-mountains-photo-and-film/	https://www.instagram.com/momentsandmountainsphoto/
Minic Media	Videography		Seattle	Washington	Tacoma, Puyallup, Gig Harbor, Federal Way, Seattle and wider Northwest	Cinematic video studio that also films weddings, including at Point Defiance and Thornewood Castle, travelling across the region.	Info@MinicMedia.com	509-593-3073	https://minicmedia.com/locations/tacoma	https://www.instagram.com/minicmedia/
Emerald Engagements	Planning		Tacoma	Washington	Washington State	Tacoma planner offering day-of coordination, design-led help turning Pinterest boards into plans, and full planning, with free initial consultations.	carly@emeraldengagements.com	(425) 490-5528	https://emeraldengagements.com/wedding-planner-tacoma/	https://www.instagram.com/emeraldengagements/
Elegant Affairs	Planning	10116 36th Ave Ct SW, Suite 12	Lakewood	Washington	Seattle, Tacoma, the wider Pacific Northwest and international	Planning firm working since 2005 with over 300 couples, offering full-service planning and day-of coordination for refined, detailed weddings.	info@elegantaffairswa.com	253-279-6485	https://www.elegantaffairswa.com/	https://www.instagram.com/elegantaffairswa/
Colleen's Coordinating	Planning		Bonney Lake	Washington	Within 30 miles of Bonney Lake, including Tacoma	Day-of and partial planning coordinator whose packages all include 12 hours of on-site coordination, with a decade of experience behind them.	events@colleenscoordinating.com	(253) 785-3727	https://www.colleenscoordinating.com	https://www.instagram.com/colleenscoordinating/
Birdsong & Blossom Events	Planning		Tacoma	Washington	Seattle and the Puget Sound	Tacoma coordinator covering elopements, day-of coordination and partial planning for couples across the Puget Sound.			https://www.birdsongandblossomevents.com/	https://www.instagram.com/birdsongandblossomevents/
Anna Rose Weddings	Planning		Tacoma	Washington	Washington	Tacoma day-of coordinator whose packages include venue consultation, vendor communication, timelines, rehearsal direction and up to 12 hours on site.			https://www.annaroseweddings.com/	
KaDeana Prévu Events & Venue Consulting	Planning		Tacoma	Washington	Tacoma, Seattle and surrounding regions	Boutique consultancy offering full planning, day-of coordination and venue consulting, with a mobile bar service available for receptions.		(253) 439-0303	https://www.weddingplannerprevuevents.com/	
Uniquely Unified	Planning		Chehalis	Washington	Seattle, Tacoma, Spokane, Olympia, Skagit and Snohomish	Planner for culturally diverse, interfaith and interracial weddings, with day-of coordination from $1,800, design services and virtual planning.	lizzie@uniquelyunified.com	360-269-1502	https://www.uniquelyunified.com/tacoma-wedding-planner	https://www.instagram.com/uniquely.unified/
Loveleigh Blooms	Florals		Tacoma	Washington	Tacoma, Seattle and the Pacific Northwest	Boutique wedding florist making bridal bouquets and ceremony installations, with a personal, friend-like approach and seasonal blooms.	leigh@loveleighblooms.com		https://loveleighblooms.com	https://www.instagram.com/loveleighblooms/
You Are My Sunshine Flowers	Florals	11454 12th Ave S	Tacoma	Washington	Tacoma and surrounding delivery areas	Tacoma flower shop doing bridal and attendant bouquets, ceremony decor and reception pieces, with custom bouquet handles and wedding rentals.		(253) 444-8644	https://www.youaremysunshineflowers.com/wedding-flowers	
Beloved Blooms Co.	Florals		Puyallup	Washington	Pierce County, Tacoma and the Pacific Northwest	Floral design for small weddings and elopements, with officiants and a garden venue for celebrations of up to 25 guests alongside the flowers.	belovedbloomsco@gmail.com	360-460-7830	https://www.belovedbloomsco.com/	https://www.instagram.com/belovedbloomsco/
Anthera Floral	Florals		Seattle	Washington	Seattle, Tacoma, Whidbey Island, Woodinville, Bellingham and across the Pacific Northwest	Full-service wedding florist with a decade of experience, handling colour consultation, installations, delivery, setup and takedown, with elopement budgets too.	antherafloral@gmail.com		https://antherafloral.com/weddings	https://www.instagram.com/antherafloral/
Karrie Michelle Floral Design	Florals		Gig Harbor	Washington	Gig Harbor and the South Sound	Gig Harbor studio creating timeless, romantic florals with packages tailored to each couple, after a personal consultation about their vision.		253-298-0909	https://www.karriemichelle.com/	https://www.instagram.com/karriemichellefloraldesign/
William's Flowers & Gift	Florals	1620 6th Ave	Tacoma	Washington	King, Pierce and Kitsap counties and the Portland area	Second-generation family florist with several shops, offering bridal bouquets, boutonnieres and reception flowers, plus free consultations for couples.		(800) 458-7430	https://www.williamsflowers.com/flowers/weddings/	
Gallucci's Catering	Catering	47 St. Helens Ave	Tacoma	Washington	Tacoma, Puyallup, Seattle and the wider Puget Sound	Long-running caterer with 35-plus years of weddings and corporate events behind it, building customised menus from a Tacoma tasting office.		253.826.1799	https://www.galluccis.com/	
Jònz Catering	Catering		Tacoma	Washington	Tacoma, Pierce County, Gig Harbor, Puyallup, Lakewood and DuPont	Pierce County caterer since 2007 offering buffets, finger foods and bar service for wedding groups from 50 up to around 1,000 guests.		(253) 274-0443	https://www.jonzcatering.com/	https://www.instagram.com/jonz.catering/
Georgio's Catering	Catering	3812 Wright Ave	Tacoma	Washington	Tacoma area	Full-service Tacoma caterer covering barbecue through to evening wedding menus, with decor and bar service available alongside the food.	info@georgioscatering.com	(253) 232-3615	https://www.georgioscatering.com/	https://www.instagram.com/georgioscatering/
Mama Stortini's	Catering	3207 East Main Ave	Puyallup	Washington	Puyallup, Kent and Federal Way locations	Locally owned Italian restaurant group that also caters and hosts weddings, offering a homestyle, family-table approach to the menu.		253.845.7569	https://www.mamastortinis.com/	https://www.instagram.com/mamastortinis/
Table Catering Co.	Catering		Seattle	Washington	Greater Seattle area, including Tacoma	Pacific Northwest-ingredient caterer offering plated dinners, cocktail receptions, food stations and charcuterie boards for weddings.		(206) 963-5114	https://tablecateringco.com/	https://www.instagram.com/tablecateringco/
Subtle Approach Catering	Catering	10836 E Marginal Wy S	Tukwila	Washington	Washington state	Chef-owned caterer with seasonal, locally sourced menus for weddings and off-site events, drawing on over 40 years of combined kitchen experience.	info@subtleapproachcatering.com	253-318-1018	https://www.subtleapproachcatering.com/	https://www.instagram.com/subtleapproachcatering/
Lux Salon & Spa	Hair & Makeup	1614 S Mildred St, Suite 9	Tacoma	Washington	Tacoma	Tacoma salon with bridal hair and makeup packages, including trials for the bride, with stylists at several experience levels to suit different budgets.		(253) 474-1899	https://luxsalontacoma.com/bridal-services/	
I.M. Artistry	Hair & Makeup		Tacoma	Washington	Seattle, Tacoma, Kirkland and on-site locations	Bridal beauty team led by a makeup artist with 21-plus years of experience, offering on-site makeup, hair and skin services for wedding parties.	booking@makeupbyimartistry.com	(206) 773-5593	https://www.makeupbyimartistry.com/	https://www.instagram.com/imartistry_/
Styled by Maria Lynn	Hair & Makeup	11803 101st Ave E, Suite 103	Puyallup	Washington	Washington state	Hairstylist known for romantic bridal styling and invisible bead extensions, working from a Puyallup studio with online booking.			https://www.styledbymarialynn.com/	https://www.instagram.com/styledbymarialynn/
Pacific NW Beauty Bar	Hair & Makeup	2325 Tacoma Ave S	Tacoma	Washington	Tacoma, with travel beyond 40 minutes charged extra	Licensed esthetician offering bridal makeup and lash extensions after a pre-wedding consultation, working from a Tacoma studio.	pacificnwbeautybarinc@gmail.com	253-221-6823	https://www.pacificnwbeautybar.com/	https://www.instagram.com/pacificnwbeautybar/
Celebrity Cake Studio	Cake	314 E 26th St	Tacoma	Washington	Tacoma and the surrounding region	Women-owned Tacoma cake boutique operating since 1999, offering wedding consultations and tastings plus petit fours, cupcakes and groom's cakes.	info@celebritycakestudio.com	(253) 627-4773	https://celebritycakestudio.com/	https://www.instagram.com/celebritycakestudio/
Corina Bakery	Cake	602 Fawcett Ave	Tacoma	Washington	Tacoma	Downtown Tacoma bakery making wedding and groom's cakes from scratch, with vegan and gluten-free options and paid tastings by appointment.	customerservice@corinabakery.com	(253) 627-5070	https://www.corinabakery.com/	https://www.instagram.com/corinabakery/
Cakery Atelier	Cake	2220 N Proctor St	Tacoma	Washington	Tacoma	Licensed Proctor pastry atelier focused on artisanal single-tier wedding cakes with optional fresh flowers, alongside French pastries.			https://www.cakeryatelier.com/	https://www.instagram.com/cakeryatelier/
Love By The Slice	Cake		Tacoma	Washington	Tacoma	Social-impact bakery making custom wedding cakes, cupcakes and cookies while employing young adults who have experienced homelessness.	info@lovebytheslice.net	253-588-2253	https://www.lovebytheslice.com/	https://www.instagram.com/lovebytheslice/
Pinewood Baking	Cake		SeaTac	Washington	Seattle and Tacoma areas	Licensed, insured home bakery making custom wedding cakes, cupcakes, cake pops, donuts and cookies for weddings across the Seattle and Tacoma regions.	pinewoodbaking@gmail.com	(253) 336-4394	https://www.pinewoodbaking.com/	https://www.instagram.com/pinewoodbaking/
The Cake Lady Gig Harbor	Cake	7927 Warren Dr NW	Gig Harbor	Washington	Gig Harbor	Custom cake and dessert baker with 15-plus years of experience, handling weddings of over 300 guests and gluten-free or vegan requests.	The-Cake-Lady@comcast.net	(253) 219-9580	https://thecakeladygigharbor.com/	`,
  },
  {
    name: "Seattle: photography, planning, florals, music, catering, videography, cake, hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Entwined Portraits	Photography		Woodinville	Washington	Seattle, Snohomish, Woodinville and venues across Washington	Woodinville photographer covering elopements and full wedding days, with an engagement session included in full-day packages.	christine@entwinedportraits.com	(425) 247-3295	https://www.entwinedportraits.com/	https://www.instagram.com/entwinedportraits/
B. Jones Photography	Photography		Snohomish	Washington	Greater Seattle, Snohomish, King and Whatcom counties, plus travel	Snohomish wedding photographer with a light and airy style, shooting since 2012 across Seattle, Woodinville and Bellingham, including waterfront weddings.	becca@bjonesphotos.com	(360) 770-9190	https://www.bjonesphotos.com/	https://www.instagram.com/bjonesphotos/
Luma Weddings	Photography		Edmonds	Washington	Seattle, Snohomish, Woodinville, Whidbey and San Juan Islands, destination	Edmonds-based wedding and elopement photographers working around Puget Sound and the islands, with destination weddings by custom proposal.			https://lumaweddings.com/	
Artistry Images Photography	Photography		Mukilteo	Washington	Seattle, Bellevue, Everett, Redmond, Woodinville, Snohomish, Kirkland and nearby	Mukilteo photographer offering wedding coverage with published pricing, working from Everett and Snohomish down to Seattle, Bellevue and Redmond.		425-330-4980	https://www.artistryimages.com/	
Luxe Productions	Planning		Seattle	Washington	Seattle, Portland and the wider Pacific Northwest	Wedding planning and design for estate, outdoor and warehouse venues, with experience in South Asian wedding traditions and published planning tiers.			https://luxenw.com/	https://www.instagram.com/luxeproductions/
Perfectly Posh Events	Planning		Seattle	Washington	Greater Seattle, San Juan Islands and destination weddings	Seattle planning, coordination and event design firm taking weddings from first design ideas through to final day-of coordination.	holly@perfectlyposhevents.com		https://perfectlyposhevents.com/	https://www.instagram.com/perfectlyposhevents/
Amethyst Events	Planning		Seattle	Washington	Seattle and the Pacific Northwest	Seattle planning firm offering full-service planning, partial planning, day-of coordination and design, led by a founder with long hospitality experience.		(480) 232-5454	https://amethysteventsllc.com/	https://www.instagram.com/amethystevents_wa/
Elevated Events by Tosha	Planning		Seattle	Washington		Seattle planner focused on intimate, non-traditional weddings and elopements, with full planning or design and coordination options.			https://www.elevatedeventsbytosha.com/	https://www.instagram.com/elevatedeventsbytosha/
Bridal Bliss	Planning		Seattle	Washington	Seattle, Portland, Bend and destination	Planning company offering full-service, partial and day-of wedding coordination for Seattle couples, with events run since 2002 by its own team.	nora@bridalbliss.com	503.804.4901	https://www.bridalbliss.com/	https://www.instagram.com/bridalblissnw/
Moonflower Design Co.	Florals		Seattle	Washington	Greater Seattle and the Pacific Northwest	Seattle floral studio designing modern, luxe wedding flowers with a playful streak, and sharing real weddings and styled shoots in an online journal.			https://www.moonflower.design/	https://www.instagram.com/moonflowerdesignco/
Twisted Bramble	Florals		Seattle	Washington	Greater Seattle	Seattle studio led by Meghan, creating full-service wedding florals from locally grown seasonal blooms using foam-free mechanics.			https://www.twistedbramble.com/	
Diadem Flower Co.	Florals		Seattle	Washington	Seattle, Bellingham and the greater Pacific Northwest	Floral studio making seasonal wedding flowers for celebrations of all sizes, with a focus on sustainability and clear pricing.	colleen@diademflowers.com		https://www.diademflowers.com/	
Gather Design Company	Florals		Seattle	Washington	Seattle and beyond	Seattle florist and event design studio building custom floral packages, buying from local farmers where possible and favouring sustainably grown stems.	amy@gatherdesigncompany.com	206-310-9600	https://www.gatherdesigncompany.com/	https://www.instagram.com/gatherdesigncompany/
Seablush Floral	Florals		Shoreline	Washington	Shoreline, with delivery within 25 miles	Shoreline florist working with seasonal Northwest flowers, offering wedding bouquets alongside floral earrings and tattoo-style corsages.			https://seablushfloral.com/	https://www.instagram.com/seablushfloral/
Precious Byrd	Music		Bellevue	Washington	The Eastside, greater Seattle, Oregon and Washington	Bellevue live dance party band playing covers and originals for weddings, corporate events and private parties, with sample playlists on request.	booking@preciousbyrd.com		https://preciousbyrd.com/	https://www.instagram.com/preciousbyrdband/
Soulfunktion Seattle	Music		Seattle	Washington	Seattle, Tacoma, Bellevue and the Pacific Northwest	Seven-piece live band playing funk, soul, R&B and disco for weddings and parties, bringing its own PA, lighting and sound engineering.	bookings.soulfunktion@outlook.com	(253) 693-8389	https://soulfunktionseattle.com/	https://www.instagram.com/soulfunktion_seattle/
Orion Entertainment	Music		Everett	Washington	Seattle metro area	Everett DJ company tailoring wedding music to each couple, with MC work, photo booths, event lighting and AV support available.	information@orion-ent.com	(206) 529-7780	https://orion-ent.com/	https://www.instagram.com/orion_ent/
Seattle DJ Pro	Music		Seattle	Washington	Seattle, King County, Bellevue, Kirkland, Redmond, Everett and Tacoma	Wedding DJ and MC service covering ceremony and reception sound, dance-floor lighting and planning with venues, with photo booths and uplighting as options.			https://www.seattledjpro.com/	https://www.instagram.com/seattledjpro/
Puget Sounds Featuring DJ Kelli	Music		Seattle	Washington	Seattle	Seattle wedding DJ and MC service founded in 2007, focused on personalised music and keeping the day running smoothly.	info@yourpugetsounds.com	(425) 802-4555	https://www.yourpugetsounds.com/	
Kaspars Catering & Events	Catering	3656 34th Ave W	Seattle	Washington	Seattle and Bellevue	Seattle caterer with a wedding service for plated and styled celebrations, working from a kitchen in the Magnolia area.	catering@kasparsseattlecatering.com	206.298.0123	https://kasparsseattlecatering.com/	https://www.instagram.com/kasparscaters/
Chef Dane Catering and Delivery	Catering	19515 44th Ave W, Suite A	Lynnwood	Washington	Seattle and Bellevue	Lynnwood caterer serving Seattle and Bellevue, with a dedicated wedding catering page and sample wedding menu.	info@chefdane.com	206.794.0812	https://www.chefdane.com/	https://www.instagram.com/chefdanecatering/
Nourish Catering	Catering		Bellevue	Washington	Seattle and surrounding areas	Caterer designing each event menu from scratch rather than from set packages, including weddings with on-site food preparation.	events@nourishcatering.com		https://nourishcatering.com/	
Arista Catering	Catering	1502 Queen Anne Ave N, Suite B	Seattle	Washington	Greater Seattle area including Bellevue	Queen Anne caterer serving weddings, corporate events and private parties around Seattle and the Eastside, with menus browsable online.	brett@aristacatering.com	206-250-5143	https://cateringseattle.com/	https://www.instagram.com/aristacateringseattle/
It's All Good Catering	Catering		Seattle	Washington	Greater Seattle, Bellevue and Renton	Seattle caterer offering wedding menus for grand or intimate receptions, with a 2026 wedding menu published on its site.		(206) 339-0089	https://www.itsallgoodcatering.net/	
Bogle Productions	Videography		Seattle	Washington		Seattle videography team filming weddings since 1992, with multi-camera coverage and a documentary-style approach to the day.	info@bogleproductions.com	(206) 799-5967	https://www.bogleproductions.com/	https://www.instagram.com/bogleproductions/
Emerald Media	Videography		Seattle	Washington		Seattle-based studio making cinematic wedding and elopement films that blend candid documentary footage with a polished highlight edit.			https://www.seattlewedding-videography.com/	https://www.instagram.com/emerald_media_videography/
Seattle Wedding Films	Videography		Seattle	Washington	Puget Sound region including Bellevue, Tacoma, Kirkland, Redmond and Everett	Seattle wedding videographers offering tiered packages from a single-camera highlight to a documentary-style feature film, with a portfolio of couples' films.			https://seattleweddingfilms.com/	https://www.instagram.com/seattleweddingfilms/
Pearl Films	Videography		Seattle	Washington		Seattle wedding videographer making cinematic films with full-day coverage and storytelling edits, offering both highlight reels and longer documentary cuts.	alfred@pearlfilms.net	425-469-8429	https://www.pearlfilms.net/	https://www.instagram.com/thepearlfilms/
Best Made Videos	Videography		Seattle	Washington	Seattle, the Pacific Northwest and destination weddings	West Seattle videography company offering custom wedding films and destination wedding coverage, with finished videos shared online for guests and family.	bestmadevideos@gmail.com	(425) 785-0718	https://bestmadeweddingvideos.com/	
morfey's cake	Cake	2914 1st Avenue	Seattle	Washington		Long-running Belltown cake shop making custom wedding cakes in buttercream or fondant, with tastings and consultations booked by appointment.	morfeyscake@gmail.com	206.283.8557	https://morfeyscake.com/	https://www.instagram.com/morfeyscake/
Rosie Bakery	Cake		Seattle	Washington		Home-style bakery creating tiered wedding cakes with floral, gold and pearl finishes, made in a Seattle kitchen with Bellevue pickup available.	marjan@rosiebakery.com	425-900-3202	https://www.rosiebakery.com/	https://www.instagram.com/rosiebakemake
Seatown Sweets	Cake	6830 NE Bothell Way, Suite A	Kenmore	Washington	Bellevue, Kirkland, Redmond, Bothell, Woodinville, Seattle, Lynnwood, Snohomish, Sammamish, Issaquah, Mercer Island and Mill Creek	Kenmore bakery making custom wedding cakes, including buttercream cutting cakes, with delivery across the Eastside and north Seattle.	info@seatownsweets.com	425-605-9537	https://www.seatownsweets.com/	https://www.instagram.com/seatownsweets/
Mithaas Bakery	Cake	19600 144th Ave NE	Woodinville	Washington	Seattle Eastside	Woodinville bakery offering multi-tiered and minimalist wedding cakes, delivered across the Eastside, alongside its custom cake range.	info@mithaasbakery.com	(425) 773-8355	https://mithaasbakery.com/	https://www.instagram.com/mithaas_bakery_/
Hoffman's Fine Cakes and Pastries	Cake	16175 Cleveland Street, Suite 107	Redmond	Washington		Redmond bakery and cafe, open since 1984, that turns couples' ideas into custom wedding cakes and sells pastries and a cake of the month.	contact@hoffmansfinecakes.com	425-828-0926	https://hoffmansfinecakes.com/	
Tracy Saunders Makeup	Hair & Makeup		Seattle	Washington	Seattle and worldwide travel, free travel within Seattle	Seattle bridal makeup artist offering on-location wedding services, with same-day quotes and travel for destination weddings.	tracy@tracysaundersmakeup.com	206-429-5309	https://www.tracysaundersmakeup.com/	https://www.instagram.com/tracysaundersmakeup/
Michelle Wight Makeup Artistry	Hair & Makeup		Seattle	Washington	Seattle, with destination work anywhere a carry-on can go	Seattle team providing on-site bridal hair and makeup at venues across the region, and travelling for destination weddings.	michelle@michellewight.com		https://michellewight.com/	https://www.instagram.com/michellewight.hmu/
Beauty Studio Inc.	Hair & Makeup		Seattle	Washington	Seattle neighbourhoods, Bellevue, Kirkland, Redmond and wider King County	Seattle hair and makeup agency sending stylists to the venue for brides and bridal parties, with a gallery of local wedding looks.	contact@beautystudioinc.com	1-800-243-2240	https://www.beautystudioinc.com/	https://www.instagram.com/beautystudioinc
Valentine Collective	Hair & Makeup	1400 N. 80th St. #103	Seattle	Washington	Weddings throughout Washington State	Salon team with Seattle and Woodinville locations offering bridal hair and makeup for the bride and her party, with tiered artist pricing.		(206) 708-1357	https://valentinecollectivesalon.com/	https://www.instagram.com/valentinecobridal
Integral DJs	Music		Seattle	Washington		Seattle wedding and event DJs offering music for ceremonies and receptions, with a team of DJs and MCs.	marc@integraldjs.com	206-850-5840	https://www.integraldjs.com/	https://www.instagram.com/integraldjs
`,
  },
  {
    name: "Tacoma: music",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Monica Schley	Music		Seattle	Washington	Greater Seattle and Tacoma	Seattle harpist playing weddings solo or paired with flute, violin, voice, bass or cello for ceremonies and cocktail hours.	harp@monicaschley.com		https://monicaschley.com/	https://www.instagram.com/monicaschley_harp
Best Tacoma DJ	Music		Puyallup	Washington	Puget Sound region	Puyallup-based DJ serving Tacoma and the wider Puget Sound area for weddings and other celebrations.	Besttacomadj@gmail.com	(253) 677-5293	https://besttacomadj.com/	https://www.instagram.com/besttacomadj
Tony Schwartz: Wedding MC & DJ	Music		Puyallup	Washington		Puyallup wedding MC and DJ covering ceremony and reception music, lighting and atmosphere, travelling to couples near and far.			https://tonyschwartzmcdj.com/	https://www.instagram.com/TonySchwartzMCDJ
`,
  },
  {
    name: "Spokane: music",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
DJA1	Music		Spokane	Washington	Eastern Washington including Spokane, Spokane Valley, Cheney and Deer Park, plus travel	Spokane wedding DJ and emcee with a dedicated weddings page, working across Eastern Washington and travelling further on request.	DJA1MIX@YAHOO.COM	509-342-4241	https://www.dja1mix.com/	https://www.instagram.com/dja1mix
`,
  },
  {
    name: "Bellingham and the San Juan Islands: photography, planning, florals, music, catering, hair & makeup, cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Wild Coast Photography	Photography		Bellingham	Washington		Documentary-style wedding and adventure elopement photography from a Bellingham photographer, with Mount Baker and Skagit Valley sessions.	hello@wildcoastphoto.com		https://www.wildcoastphoto.com/	https://www.instagram.com/wildcoastphoto/
Jagger Photography	Photography		Bellingham	Washington		Bellingham wedding and elopement photographer whose recent work includes small ceremonies on Lummi Island and around Whatcom County.			https://jaggerphotography.com/	https://www.instagram.com/jagger.photography/
Ashley Peek Photo	Photography		Bellingham	Washington		Bellingham photographer and videographer who photographs weddings and maternity sessions with a candid approach and earthy tones.			https://www.ashleypeekphoto.com/	https://www.instagram.com/ashleypeekphoto/
Exposure Leak Photography	Photography		Bellingham	Washington	Whatcom County, Mt. Baker and beyond	Bellingham photographer covering lifestyle and documentary-style weddings, elopements and engagements across Whatcom County and Mount Baker.			https://www.exposureleak.com/	https://www.instagram.com/exposureleak/
La Vie Photography	Photography		Friday Harbor	Washington	San Juan Island	Friday Harbor husband-and-wife team, Kim and Adam Bamberg, photographing weddings, portraits and proposals on San Juan Island.	contact@laviephoto.com	206-910-5687	https://laviephoto.com/	https://www.instagram.com/laviephoto/
Satya Curcio Photography	Photography		Orcas Island	Washington	Orcas Island and the San Juan Islands	Fine-art wedding, elopement and family photography by an Orcas Island photographer who works throughout the San Juan Islands.	satya@satyaphotography.com		https://satyaphotography.com/	https://www.instagram.com/satyaphotography/
Chase Anderson Documentary Photography	Photography		Friday Harbor	Washington		Documentary photographer living on San Juan Island in Friday Harbor, covering weddings, portraits and local events.			https://www.chaseanderson.com/	
Islands Weddings and Events	Planning		Orcas Island	Washington	Orcas Island, San Juan Island and Lopez Island	Wedding planning, day-of coordination and officiating for Orcas Island, San Juan Island and Lopez Island ceremonies and elopements.		360-298-0362	https://islandsweddingsandevents.com/	
Love Is Love Wedding Co.	Planning		Bellingham	Washington	Bellingham, Mount Vernon, Whatcom and Skagit counties	Inclusive wedding planning and day-of coordination for couples in Bellingham, Mount Vernon and the wider Whatcom and Skagit County area.			https://www.loveisloveweddingco.com/	
Apotheca Design	Florals	992 Argyle Ave	Friday Harbor	Washington	San Juan Island	Boutique floral studio in Friday Harbor creating wedding and event flowers for ceremonies across San Juan Island.	apothecadesign@gmail.com		https://www.apothecadesign.com/	https://www.instagram.com/apothecadesign/
Camas Designs	Florals		Friday Harbor	Washington	San Juan Islands	San Juan Islands florist specialising in weddings and events, with experience at nearly every venue in the islands, often for destination couples.	erin@camasdesigns.com	206-437-4993	https://www.camasdesigns.com/	https://www.instagram.com/camasdesigns/
Nest Flowers	Florals		Orcas Island	Washington		Orcas Island studio florist Cindy Morgan designs wedding flowers using blooms grown on the island and sourced from farms worldwide.			https://www.nestflowers.com/	https://www.instagram.com/nestonorcas/
Bloom San Juan	Florals		Friday Harbor	Washington	San Juan Island	San Juan Island wedding flower producer that also hosts small retreats and dinners at its oceanside property.	bloomsanjuan@gmail.com		https://bloomsanjuan.com/	https://www.instagram.com/bloomsanjuan/
Whatcom Sound	Music		Bellingham	Washington		Bellingham sound and DJ company offering wedding packages with a pro sound system, wireless microphones and dance floor lighting.			http://www.whatcomsound.com/	
Lynden DJ	Music		Lynden	Washington	Whatcom County	Lynden DJ provides music, sound and lighting for wedding ceremonies, receptions and special events in Whatcom County and beyond.			https://lyndendj.com/	
Avenue Catering Enterprises	Catering	676 S. Spruce St	Burlington	Washington	Skagit County and greater western Washington	Burlington caterer for weddings and events across Skagit County and western Washington, from Bellingham to Seattle, with its own menus and facility.		360-755-5880	https://www.cateringbyavenue.com/	
Salmonberry Catering	Catering		Friday Harbor	Washington	San Juan Islands	Farm-to-table caterer serving San Juan Islands weddings, using ingredients from San Juan Island and Skagit Valley farms.	juels@salmonberrycatering.com	808-652-1511	https://www.salmonberrycatering.com/	https://www.instagram.com/salmonberry_catering/
Paella San Juan	Catering		Friday Harbor	Washington	San Juan Islands	Spanish paella caterer that began at the Friday Harbor farmers market and now offers wedding packages across the islands.	info@paellassanjuan.com	360-830-8652	https://www.paellassanjuan.com/	https://www.instagram.com/paellassanjuan/
Coho Restaurant	Catering	120 Nichols Street	Friday Harbor	Washington	San Juan Island	Friday Harbor farm-to-table restaurant that also caters weddings and events on San Juan Island, in its dining room or off site.		360-378-6330	https://cohorestaurant.com/	https://www.instagram.com/cohorestaurant/
Jade Madison Artistry	Hair & Makeup		Bellingham	Washington	Bellingham and Whatcom County	Bellingham bridal makeup artist offering elevated, natural looks with on-site service on the wedding morning.		360-483-8380	https://www.jademadisonartistry.com/	https://www.instagram.com/jademadisonartistry/
Salon Bellissima	Hair & Makeup		Bellingham	Washington		Eco-friendly Fairhaven salon in Bellingham with bridal hair and makeup, trials and on-site wedding party styling.		360-715-1052	https://www.salonbellissimabellingham.com/	https://www.instagram.com/salonbellissima/
Symmetrie Bridal	Hair & Makeup		Bellingham	Washington	Bellingham, Lynden and Mt. Baker	Bridal hair and airbrush makeup team serving weddings in Bellingham, Lynden and Mount Baker with trials for each bridal party.			https://www.symmetriebridal.com/	https://www.instagram.com/symmetriebridal/
Trista Evans MUA	Hair & Makeup		Bellingham	Washington		Bellingham makeup artist offering bridal makeup and previews for weddings in Bellingham and beyond.			https://tristaevansmua.wixsite.com/makeupartist	https://www.instagram.com/tristaevansmua/
Island Roots Salon	Hair & Makeup		Friday Harbor	Washington		Friday Harbor salon on San Juan Island offering cut, colour and styling including bridal up-dos since 2012.			https://islandrootssalon.com/	
Saltadena Bakery & Cake Shop	Cake		Bellingham	Washington	Bellingham and Seattle areas	Downtown Bellingham bakery making modern custom and signature cakes and desserts for weddings and events.		360-393-3111	https://www.saltadena.com/	https://www.instagram.com/saltadena/
It's The Sweet Things	Cake		Bellingham	Washington		Downtown Bellingham bakery and cafe making artisan cupcakes and handcrafted desserts for weddings, with consultations by appointment.	itsthesweetthingsbakery@gmail.com	360-255-9998	https://www.itsthesweetthings.com/	https://www.instagram.com/its_the_sweet_things/
Pure Bliss Desserts	Cake	1424 Cornwall Avenue	Bellingham	Washington		Bellingham dessert shop baking wedding cakes and desserts in its own kitchen, with local delivery available.	info@pureblissdesserts.com	360-739-1612	https://www.pureblissdesserts.com/	https://www.instagram.com/pureblissdesserts/
Digital Tide Productions	Videography		Bellingham	Washington		Bellingham videographer and photographer producing wedding films, including drone footage and multi-location coverage.		360-774-6204	https://www.digitaltideproductions.com/	
Orcas Video	Videography		Orcas Island	Washington	Orcas Island, Roche Harbor and the San Juan Islands	Orcas Island wedding videography and photography studio covering ceremonies across Orcas and the wider San Juan Islands.			https://www.orcasvideo.com/	https://www.instagram.com/orcas_video/
`,
  },
  {
    name: "Leavenworth and Chelan: photography, planning, florals, music, catering, hair & makeup, cake, videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Alder Photography	Photography		Leavenworth	Washington	Leavenworth and the Pacific Northwest	Natural-light wedding and elopement photography from a photographer who moved from Seattle and now lives in Leavenworth.	hello@alder.photography		https://www.alder.photography/	https://www.instagram.com/alder.photography/
Brandt Photo Co.	Photography		Wenatchee	Washington	Central Washington including Lake Chelan, Leavenworth and Cashmere	Husband-and-wife Wenatchee team photographing weddings and portraits for couples across Central Washington.	info@brandtphoto.co		https://brandtphoto.co/	
Kendra Wittwer Photography	Photography		Wenatchee	Washington		Wenatchee-based wedding and elopement photographer with timeless, emotive images, shooting in Chelan and across the Pacific Northwest.	hello@kendrawittwer.com	907-957-6852	https://www.kendrawittwer.com/	https://www.instagram.com/kendrawittwerphotography/
Sherrard Studios	Photography		Chelan	Washington	Lake Chelan, Wenatchee and the Pacific Northwest	Lake Chelan wedding photography team shooting natural, story-driven weddings and portraits around Chelan, Wenatchee and Leavenworth.			https://sherrardstudios.com/	https://www.instagram.com/sherrardstudios/
Emily Moller Photography	Photography		Chelan	Washington		Chelan fine-art wedding, family and brand photographer who has been shooting weddings around Lake Chelan since 2010.			https://emilymollerphotography.com/	https://www.instagram.com/emilymollerphotography/
Karisa Anna Photography	Photography		Chelan	Washington	Cascade Mountains and San Juan Islands	Chelan wedding photographer covering celebrations, proposals and couples across the Cascades and the San Juan Islands.			https://karisaanna.com/	https://www.instagram.com/karisaannaphotography/
The Local Event Co.	Planning		Leavenworth	Washington		Leavenworth planning company offering day-of coordination, elopements and micro-weddings, plus rentals and venue management.	venues@thelocaleventco.com		https://www.thelocaleventco.com/	https://www.instagram.com/thelocaleventco/
Chelan Shindigs	Planning		Chelan	Washington	North Central Washington	Chelan boutique planner offering wedding and day-of coordination alongside floral design and balloon installations.	chelanshindigs@gmail.com	425-788-8344	https://www.chelanshindigs.com/	https://www.instagram.com/chelanshindigs/
J9Bing Floral & Event Planning	Planning		Chelan	Washington	Lake Chelan, Wenatchee, Leavenworth, Puyallup and Tacoma	Wedding planning, day-of coordination and destination wedding packages for couples at Lake Chelan, Wenatchee and Leavenworth.			https://j9bing.com/	https://www.instagram.com/chelanweddingplanner/
Elope in Leavenworth	Planning		Leavenworth	Washington		Elopement package planner that lets couples choose a Cascade Mountain venue, customise their package and see pricing up front.	cheers@elopeinleavenworth.com		https://elopeinleavenworth.com/	
Leavenworth Flowers	Florals		Leavenworth	Washington	Leavenworth and surrounding areas	Husband-and-wife flower farm in Peshastin growing sustainable seasonal blooms for weddings, elopements and events around Leavenworth.	leavenworthflowers@gmail.com		https://www.leavenworthflowers.com/	
Chelan Floral	Florals		Manson	Washington	Chelan Valley	Floral design company in Manson, established in 2015, creating luxury wedding and event flowers suited to Lake Chelan venues.		509-818-3335	https://www.chelanfloral.com/	https://www.instagram.com/chelan_floral/
JMG Entertainment	Music		Wenatchee	Washington	Wenatchee, Chelan and Leavenworth	Wenatchee mobile DJ and photo booth company serving weddings in Wenatchee, Chelan and Leavenworth and further afield.	jedgossman@gmail.com	509-668-1169	https://www.jmgmusicdj.com/	https://www.instagram.com/jed_jmg/
Showbiz Northwest	Music		Wenatchee	Washington	Wenatchee Valley and North Central Washington	DJ and MC company with nearly 20 years of experience at weddings and events throughout the Wenatchee Valley and surrounding areas.		509-293-4704	https://showbiznw.com/	
DJRT	Music		Wenatchee	Washington	Wenatchee, Chelan and Leavenworth	Wedding DJ Ryan Tilton advertises wedding DJ services for Seattle, Wenatchee, Chelan and Leavenworth couples.			https://djrt.com/	
Inna's Cuisine	Catering		Wenatchee	Washington	Wenatchee, Leavenworth, Cashmere and Lake Chelan	Downtown Wenatchee European restaurant that caters weddings and parties in Wenatchee, Leavenworth, Cashmere and Lake Chelan.	innascuisine@nwi.net	509-888-4662	https://www.innas-cuisine.com/	https://www.instagram.com/innascuisine/
Ring-A-Bell's Catering	Catering		East Wenatchee	Washington		East Wenatchee caterer making food to order for weddings and other events, with set delivery charges across the Wenatchee Valley.	barb@ringabellscatering.com	509-670-7656	https://ringabellscatering.com/	
Bridal Hair by Lucy	Hair & Makeup		Leavenworth	Washington		Leavenworth hair designer offering bridal half-up, curl and up-do styles, with travel available for weddings.	bridalhairbylucy@gmail.com	509-670-8962	https://www.bridalhairbylucy.com/	https://www.instagram.com/bridalhairbylucy/
ChelanGlam	Hair & Makeup		Chelan	Washington		Lake Chelan hair and makeup team focused on on-site bridal beauty for weddings, elopements and special events.			https://www.chelanglam.com/	
Chelan Beauty Collective	Hair & Makeup		Chelan	Washington	Lake Chelan and surrounding communities	On-site bridal and event hair and makeup in Lake Chelan, from intimate elopements to larger weddings.	hannah@chelanbeautycollective.com		https://chelanbeautycollective.com/	https://www.instagram.com/chelanbrideandglam/
Yeyo's Bakery	Cake	802 S. Wenatchee Ave	Wenatchee	Washington		Family-owned downtown Wenatchee panaderia known for custom cakes for weddings, birthdays and quinceaneras.		509-888-1044	https://www.yeyosbakery.com/	https://www.instagram.com/yeyo.bakery/
Cupcake Blues	Cake	17 Orondo Ave	Wenatchee	Washington		Downtown Wenatchee cupcake shop that also makes cakes, including for weddings, with special-order cupcakes for larger events.		509-888-1966	https://www.cupcakeblues.com/	https://www.instagram.com/cupcakesblues/
Ben Holten Films	Videography		Wenatchee	Washington	Chelan, Leavenworth and Wenatchee	Wenatchee videographer specialising in wedding films in Chelan, Leavenworth and Wenatchee, with highlight films and trailers.			https://www.benholtenfilms.com/	https://www.instagram.com/benholtenfilms/
New Diamond Productions	Videography		Yakima	Washington	Washington, Oregon and Idaho, including Chelan, Wenatchee and Leavenworth	Yakima cinematic videography studio filming weddings since 2008 and regularly covering Chelan, Wenatchee and Leavenworth.		509-831-1085	https://www.ndproductions.media/	https://www.instagram.com/ndpfilms/
`,
  },
];

export default batches;
