import type { VendorBatch } from "@/lib/vendor-batches";

// West Virginia vendor batches. Every row's State is "West Virginia". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Charleston: photography, planning, florals, music, catering, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
The Oberports	Photography		Charleston	West Virginia	Charleston, Fayetteville, New River Gorge, Huntington, Morgantown and beyond	Married photography duo documenting weddings and elopements across West Virginia with a thoughtful, artful style.	hello@theoberports.com		https://theoberports.com/	https://www.instagram.com/theoberports/
Emily Ferguson Photography	Photography		Charleston	West Virginia	Charleston, Huntington, Beckley, Parkersburg, Wheeling, Fayetteville, Lewisburg, Morgantown	Husband-and-wife team from the Charleston area offering creative yet timeless wedding and elopement photography statewide.		(304) 205-9647	https://www.efergusonphotography.com/	https://www.instagram.com/emily_ferguson_photography/
Lauren Love Photography	Photography		Charleston	West Virginia	West Virginia and Kentucky; destination weddings	Wedding and engagement photographer covering Charleston, Huntington and resort venues such as Snowshoe, with travel further afield.			https://laurenlovephotography.com/	https://www.instagram.com/laurenlovephotography/
The Breiters	Videography		Charleston	West Virginia	East Coast, Pacific Northwest and destinations abroad	Appalachian photographer and videographer duo making honest, unpolished wedding and elopement films alongside stills.	hello@thebreiters.com		https://thebreiters.com/	https://www.instagram.com/thebreiters/
Charleston Cut Flower Company	Florals	1900 5th Ave	Charleston	West Virginia		Long-running, family-owned Charleston flower shop designing ceremony and reception flowers, bouquets and centrepieces, with consultations.		(304) 343-5116	https://charlestoncutflower.com/pages/wedding-page	
G&S Celebrations	Music		Charleston	West Virginia		Husband-and-wife DJ and MC team covering ceremony, cocktail hour and reception, with dance-floor lighting and a planned timeline.	gscelebrations@gmail.com		https://www.gscelebrations.com/weddings	
Allianz Music Ensembles	Music		Charleston	West Virginia		Musician-run agency booking auditioned string quartets and other ensembles for ceremonies, with custom arrangements and song requests.	ian@allianzmusicensembles.com	(304) 550-3078	https://allianzmusicensembles.com/	https://www.instagram.com/allianzmusicensembles/
DJ Tibbs	Music		Charleston	West Virginia		One-woman wedding DJ blending EDM, disco, funk, Afro-fusion and country into personalised sets for receptions and intimate parties.	brooke.thibodaux@gmail.com	(636) 577-4911	https://www.djtibbs.com/	
Loma Cakes and Catering	Catering		Charleston	West Virginia	West Virginia and Ohio	Woman-owned caterer cooking homestyle buffet and plated wedding menus, with over 35 cake flavours and desserts made in-house.	loma@lomacakes.com		https://www.lomacakes.com/	https://www.instagram.com/lomacakesandcatering/
Spring Hill Pastry Shop	Cake	600 Chestnut St	South Charleston	West Virginia	Kanawha Valley	Neighbourhood pastry shop baking Kanawha Valley wedding cakes for about 70 years, from lace overlays to naked and ombré tiers.		(304) 768-7397	https://www.springhillpastry.com/wedding-cakes	
Sugar Pie Bakery	Cake	94 RHL Blvd	South Charleston	West Virginia		Scratch bakery making hand-decorated wedding cakes, cupcakes and cookies, with an allergy information page and online ordering.	info@sugarpiebakerywv.com	(304) 205-7753	https://www.sugarpiebakerywv.com/	
Rock City Cake Co.	Cake		Charleston	West Virginia		Charleston cake company now working by order only, making wedding cakes alongside cake pops, push pops and event desserts.		(681) 265-9154	https://www.rockcitycakeco.com/	https://www.instagram.com/rockcitycakeco/
Oak + Arrow Films	Videography		Charleston	West Virginia	West Virginia and Kentucky	Husband-and-wife team of Lindsey and Caleb Tackett filming story-led wedding films, with photography offered alongside.			https://oakandarrowfilms.com/	https://www.instagram.com/oakandarrowfilms/
Eye Lens Visuals	Videography		Dunbar	West Virginia	West Virginia, Kentucky, Ohio, Pennsylvania, North Carolina	Family-run Kanawha Valley team offering cinematic wedding films with drone footage, plus photo and DJ bundles under one booking.		(304) 881-7363	https://www.eyelensvisuals.com/	
Coordinated Chaos Co	Planning		Charleston	West Virginia		Planning team led by Taylor Kiser offering day-of coordination for already-planned weddings and full planning with design guidance.	team@coordinatedchaosco.com	(681) 234-4845	https://www.coordinatedchaosco.com/	https://www.instagram.com/coordinatedchaosco_/
Simple Moments Event Designs	Planning		Charleston	West Virginia	West Virginia and destination weddings	Charleston planning duo Stephanie and David offering custom coordination packages, from a few details to full planning and venue décor.	simplemomentswv@gmail.com	(304) 419-4757	https://simplemomentswv.com/	https://www.instagram.com/simplemomentswv/`,
  },
  {
    name: "Charleston: florals, catering and hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Good Sun Florals	Florals		Charleston	West Virginia	Charleston area; travels for events	Charleston-area floral studio led by a West Virginia artist, creating sustainable wedding flowers and running classes and subscriptions.			https://goodsunflorals.com/	
Styles Salon	Hair & Makeup	519 C Street	South Charleston	West Virginia		South Charleston salon doing bridal hair and wedding-party styling, with colour, extensions and blowouts for the rest of the year.		(304) 746-4650	https://stylessalonwv.com/	
Shuckers Catering Services	Catering	70 Olde Main Plaza	St. Albans	West Virginia	St. Albans, Charleston, South Charleston, Nitro, Winfield, Hurricane and beyond	St. Albans seafood and Italian restaurant catering wedding receptions with fresh seafood, comfort classics and custom menus.		(304) 722-1500	https://eatatshuckers.com/shuckers-catering-services/	https://www.instagram.com/eatatshuckers/
L & R Custom Catering	Catering	3380 Teays Valley Road	Hurricane	West Virginia	Putnam, Cabell and Kanawha Counties	Teays Valley barbecue kitchen catering wedding receptions and family celebrations with smoked meats and custom menus.	landrbbq@gmail.com	(304) 757-0707	https://lrcustomcatering.com/	
Art's Flower and Gift Shop	Florals	1227 Ohio Ave.	Dunbar	West Virginia	Dunbar, Charleston, Kanawha City, South Charleston, Nitro, St. Albans, Cross Lanes, Hurricane, Scott Depot	Third-generation Dunbar flower shop open since 1963, arranging wedding and event flowers alongside everyday bouquets and gifts.		(304) 768-1237	https://artsflowershop.com/dunbar-florist-flower-delivery/wedding-flowers/	`,
  },
  {
    name: "Charleston: planning and hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Spa Bliss	Hair & Makeup	1210 Smith Street	Charleston	West Virginia		Downtown Aveda salon and spa doing HD airbrush bridal makeup and special-occasion updos, with service at your location available.	info@spabliss.com	(304) 720-1005	https://spabliss.com/services/makeup-application/	https://www.instagram.com/spablisswv/
Enchanted Events	Planning		Hurricane	West Virginia	Based in Hurricane; travels for weddings	Hurricane planning team led by a certified planner, offering tiered packages from day-of coordination to full planning, with an online couple portal.	get.started@enchantedevents.info	(304) 483-8235	https://www.enchantedevents.info/	https://www.instagram.com/enchantedeventswv/`,
  },
  {
    name: "Morgantown: photography, planning, florals, music, catering, cake, videography and hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Amberlee Christey Photography	Photography		Morgantown	West Virginia	Morgantown and destination weddings worldwide	Award-winning Morgantown wedding and engagement photographer with fourteen years in business who also travels for destination weddings.		(304) 216-5903	https://www.amberleechristeyphotography.com/	https://www.instagram.com/amberleechristeyphotography/
Buonamici Exposures	Photography		Morgantown	West Virginia		Morgantown-based wedding and portrait photographer taking bookings for weddings, engagements and sessions around West Virginia.	buonamiciexposures@gmail.com		https://buonamiciexposures.com/	https://www.instagram.com/buonamiciexposures/
Lunar Media	Videography		Morgantown	West Virginia	Morgantown to Pittsburgh	Two friends offering wedding photography, video and DJ service as one booking, working from Morgantown to Pittsburgh and beyond.	lunar.media.company@gmail.com		https://lunarmediaweddings.com/	https://www.instagram.com/lunarmediaco/
Kathryn Rose Event Company	Planning		Morgantown	West Virginia	West Virginia, greater Pittsburgh and Asheville, North Carolina	Morgantown planners designing adventurous mountaintop and brewery weddings across West Virginia, the Pittsburgh area and Asheville.			https://kreventco.com/	https://www.instagram.com/kathrynroseeventco/
Dream Creations Event Planning	Planning		Morgantown	West Virginia	Morgantown, Deep Creek and Oakland MD, southwestern PA	Planning and coordination for weddings and parties in Morgantown, Deep Creek Lake and southwestern Pennsylvania, with set packages.			https://dreamcreationseventplanning.com/	https://www.instagram.com/dream_creations_event_planning/
Brittany Anne's	Planning		Morgantown	West Virginia		Morgantown rental and planning company offering wedding coordination with two team members on site, plus arches, backdrops and flower walls.	brittanyannesevents@gmail.com	(304) 415-2723	https://brittanyannesevents.com/wedding-coordination	https://www.instagram.com/brittanyannesevents/
Love and Lavender Moments	Planning		Morgantown	West Virginia		Husband-and-wife Morgantown team offering wedding and event coordination, services and rentals, with value packages priced on the site.			https://www.loveandlavendermoments.com/home	
Zaccagnini Morgantown Florist	Florals	735 Chestnut Ridge Rd, Suite E	Morgantown	West Virginia	Morgantown and surrounding areas	Florist formed from two long-running Morgantown shops, making bridal bouquets, ceremony flowers and reception arrangements.		(304) 599-2996	https://www.morgantownflorist.com/shop/weddings	
Bella Fiore Floral	Florals	967 Canyon Road	Morgantown	West Virginia	Morgantown and surrounding areas	Morgantown florist founded by designer Jason Savage, doing wedding bouquets, personal flowers and event arrangements alongside everyday orders.	jasonbellafiore@gmail.com	(304) 777-2472	https://morgantownflowerswv.com/	
Dynamic Entertainment & Lighting Productions	Music		Morgantown	West Virginia	North Central West Virginia	Husband-and-wife DJ and lighting team with 20-plus years between them, offering reception coordination, uplighting and dance-floor effects.	dynamicdj0777@gmail.com	(304) 669-8442	https://dynamicdjwv.com/	
Musicshow Sound	Music		Morgantown	West Virginia		Morgantown production company providing wedding DJ and MC service, sound for live bands, dance-floor and up-lighting, and confetti or CO2 effects.	kevin@musicshowsound.com	(304) 288-3057	https://musicshowsound.com/weddings	
DJ Dave Event Services	Music		Morgantown	West Virginia		Morgantown wedding DJ and MC company that also rents photo booths and offers event planning through a planner on its team.			https://djdeventservices.wixsite.com/home	https://www.instagram.com/djdaverishell/
Madeleine Marie's Catering & Carryout	Catering	260 Green St	Morgantown	West Virginia		Full-service Morgantown caterer with over 25 years of event experience, offering set packages or custom menus plus everyday carryout.	info@madeleinemaries.com		https://www.madeleinemaries.com/events	https://www.instagram.com/madmariescatering/
Mario's Full Bowl Catering	Catering	3117 University Avenue	Morgantown	West Virginia		Morgantown restaurant caterer doing buffet, plated, family-style or boxed menus on site or off site, with custom menus to suit a budget.		(304) 599-4309	https://www.mariosfishbowl.com/catering	https://www.instagram.com/mariosfishbowl/
Lake House Catering	Catering	165 Sunset Beach Road	Morgantown	West Virginia		Lake House restaurant's catering arm, taking orders for parties and celebrations from the Sunset Beach Road kitchen near Morgantown.		(304) 594-0088	https://www.lakehousewv.com/catering/	
Honeycomb Baking	Cake		Morgantown	West Virginia	West Virginia, Pennsylvania and Maryland	Boutique Morgantown bakery making artistic, timeless wedding cakes and cookies, with each design tailored to the couple.		(304) 578-1781	http://www.honeycombbaking.com/	https://www.instagram.com/honeycombbaking/
Megan's Custom Creations	Cake		Morgantown	West Virginia		Morgantown home baker making artistic wedding cakes, cupcakes, macarons and sugar cookies, with $50 tastings credited toward the final order.	meganscookiesandcakes@gmail.com		https://www.meganscustomcreations.com/wedding-cakes	
Honey Bridal Collective	Hair & Makeup		Morgantown	West Virginia	Morgantown and surrounding areas	Salon collective of bridal beauty artists doing hair and makeup on site, with an optional Bridal Preview in its private salon suite.	honeybridalwv@gmail.com	(304) 266-2535	https://www.honeywv.com/bridal	https://www.instagram.com/honeywv_/
Amanda Vicinelly	Hair & Makeup		Morgantown	West Virginia	Morgantown, Uniontown and Pittsburgh	Travelling bridal makeup artist focused on skin-forward looks and colour harmony, taking wedding bookings for 2027.	amandavicinelly@gmail.com	(412) 848-4247	https://www.amandavicinelly.com/	https://www.instagram.com/amandavicinellypromakeupartist/`,
  },
  {
    name: "New River Gorge: photography, videography, florals, music, catering and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Chris Jackson Photography	Photography		Fayetteville	West Virginia	Statewide West Virginia including the New River Gorge, Charleston, Lewisburg and Morgantown	Documentary and fine art wedding photographer in Fayetteville, covering the New River Gorge and elopements across West Virginia and beyond.	chrisphoto304@gmail.com	304.553.3785	https://chrisjacksonphoto.com/	https://www.instagram.com/chrisjacksonphoto/
Sheena Pendley Design + Photography	Photography		Lewisburg	West Virginia	West Virginia, Virginia and Maryland	Husband-and-wife photo and video team in downtown Lewisburg, covering weddings, elopements and engagements across southern West Virginia and Virginia.	hello@sheenapendleydp.com	304.646.9452	https://www.sheenapendleydp.com/	https://www.instagram.com/sheenapendley/
Greenbrier Images	Photography		Lewisburg	West Virginia	Lewisburg and surrounding areas including Beckley, Snowshoe and Virginia	Lewisburg photographer offering wedding photography and films, with portfolio weddings through 2026 and coverage around Beckley and Snowshoe.	info@greenbrierimages.com	304 237 5170	https://www.greenbrierimages.com/	
Lady Mountain Films	Videography		Fayetteville	West Virginia		Fayetteville filmmaker making wedding films and photos, with a focus on adventure elopements and non-traditional weddings since 2017.			https://www.ladymountainfilms.com/	https://www.instagram.com/ladymountainfilms/
Aronfield Weddings	Videography		Beckley	West Virginia	Central and southern West Virginia, over 16 counties	Wedding videography across central and southern West Virginia, with three coverage packages running from two to ten hours.			https://aronfieldweddings.com/	
Xandar Blankenship Photo & Film	Photography		Meadow Bridge	West Virginia	Meadow Bridge, Fayetteville, Oak Hill, Beckley, Mount Hope, Hinton, Lewisburg and Princeton	Meadow Bridge photographer and videographer covering weddings and engagements around Fayetteville, Oak Hill, Beckley and Lewisburg.		(304) 396-6983	https://photographermeadowbridge.com/	https://www.instagram.com/xandarblankenship/
Kelli Carrico Photography	Photography		Beckley	West Virginia		Beckley wedding photographer with over 300 weddings photographed, including work at The Greenbrier Resort, and photography education for others.	kellicarricophotography@hotmail.com		https://www.kellicarricophotography.com/	https://www.instagram.com/kellicarricophotography/
Jaki Good Miller Photography	Photography		Summersville	West Virginia	Summersville and the surrounding region	Summersville photographer offering wedding, senior and family portraits, and a Certified Professional Photographer with a PPA master's degree.	jaki@jakigoodmiller.com	304-940-5254	https://www.jakigoodmiller.com/	
Savannah Confections	Cake		Beckley	West Virginia		Beckley cake and dessert studio making bespoke, from-scratch wedding cakes and confections, with 2026 and 2027 wedding dates open for booking.			https://www.savannahconfections.com/	https://www.instagram.com/savannahconfections/
Designs By Barb & James Inc.	Florals	305 Main Street West	Oak Hill	West Virginia	Oak Hill and surrounding areas	Oak Hill flower shop offering wedding bouquets, ceremony flowers and reception flowers alongside everyday seasonal arrangements.		(304) 469-6006	https://www.designsbybarbandjamesinc.com/	
Greenbrier Cut Flowers & Gifts	Florals	246 Maplewood Avenue	Lewisburg	West Virginia	Lewisburg and surrounding regions	Lewisburg florist with more than twenty years' experience designing wedding packages, from bridal bouquets and ceremony pieces to reception tables.		(304) 645-6694	https://www.greenbriercutflowers.com/	
Glade Creek Floral	Florals	8430 Webster Rd.	Summersville	West Virginia	Summersville and surrounding areas	Family-run Summersville florist making custom arrangements for weddings and other occasions, with delivery across the local area.		(304) 872-3105	https://www.gladecreekfloral.com/	
SunTan Swine BBQ	Catering		Glen Fork	West Virginia	Oceana, Gilbert, Pineville, Glen Daniel, Beckley, Brenton and Mullens	Family-run mobile barbecue caterer from Glen Fork serving weddings with slow-smoked pulled pork, brisket, ribs and wings from a food truck.	SunTanSwineBBQ@Yahoo.com	304-237-1353	https://www.suntanswinebbq.com/	https://www.instagram.com/suntan.swine.bbq/
Hungry Bear Catering	Catering		Fayetteville	West Virginia		Fayetteville caterer offering smoked meats and smokehouse sides for weddings, plus tables, chairs and tents for full-service events.	phgfoodservice@gmail.com	304-719-9153	https://www.hungrybearwv.com/	
Kellen's Kitchen	Catering		Lewisburg	West Virginia	Lewisburg, White Sulphur Springs, Ronceverte, Fairlea, Alderson, Rainelle and Greenbrier County	Lewisburg caterer running since 2004, serving pit-smoked barbecue and offering drop-off catering for Greenbrier County weddings.	kellen@pigsflybbq.com	(304) 249-8124	https://kellenskitchenwv.com/	
Blackwell's Catering	Catering	830 Jefferson Street South	Lewisburg	West Virginia	Lewisburg area, delivery available	Lewisburg chef-owned caterer providing custom menus for plated weddings and fundraisers, with pickup, delivery and event space hire.		304-645-6159	https://www.blackwellscatering.com/	https://www.instagram.com/blackwellsgbc/
Maple Hill Entertainment	Music		Ronceverte	West Virginia	Greenbrier Valley	Ronceverte DJ and announcing service covering weddings, proms, school dances and parties across the Greenbrier Valley.	maplehillentertainment@yahoo.com	304-647-4231	https://www.maplehillentertainment.com/	`,
  },
  {
    name: "Charleston: hair & makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Oasis Spa	Hair & Makeup	33 RHL Blvd	South Charleston	West Virginia		South Charleston day spa and salon offering bridal styling and a bride-to-be package alongside lashes, brows, nails and facials.	oasisspawv@gmail.com	304-747-6116	https://oasisspacharleston.com/	https://www.instagram.com/oasis.spa.wv/`,
  },
  {
    name: "Morgantown: photography, florals, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kristin Hurley Photography	Photography		Morgantown	West Virginia		Morgantown fine art wedding photographer known for natural, emotional coverage of weddings across West Virginia and nearby Pennsylvania.			https://www.kristinhurleyphotography.com/	
Beverly Hills Florist	Florals	1269 Fairmont Rd	Morgantown	West Virginia		Morgantown flower shop on Fairmont Road that handles wedding flowers by consultation, alongside everyday arrangements and local delivery.	morgantownflowershop@gmail.com	304-983-2899	https://www.morgantownflowershop.com/	
Tuscan Sun Spa and Salon	Hair & Makeup	401 Boyers Ave	Morgantown	West Virginia		Spa and salon on Boyers Avenue with bridal updos, bridal party styling and spa packages for the wedding party before the big day.		304-296-1325	https://tuscanspaandsalon.com/salon/bridal/	https://www.instagram.com/tuscansunspa/
The Cupcakerie	Cake	3200 Collins Ferry Road	Morgantown	West Virginia		Morgantown cupcake café and bakery off Collins Ferry Road that also caters weddings and private events with made-to-order menus.	orders@thecupcakerie.com	304-212-5464	https://thecupcakerie.com/	
Image Studios & Entertainment	Videography		Morgantown	West Virginia		Morgantown studio offering wedding videography packages alongside photography and DJ services, travelling further for a mileage fee.	ljlenhart@imagestudiosllc.com	304-216-2064	https://imagestudiosandentertainment.com/	
GeeCee Media	Videography		Morgantown	West Virginia		Morgantown wedding film company producing cinematic wedding videos and photography, and travelling beyond West Virginia for couples.		304-644-2848	https://www.geeceemedia.com/	`,
  },
  {
    name: "New River Gorge: planning, music, hair & makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Gillespie's	Planning	377 Main Street West	White Sulphur Springs	West Virginia		Greenbrier Valley event company offering personalised event planning, sailcloth tents, décor rentals and wedding florals.	sales@gillespies.events		https://gillespies.events/	
West Virginia Elopement Collective	Planning		Fayetteville	West Virginia	New River Gorge, Dolly Sods, Spruce Knob and Blackwater Falls	Weekday elopement planners running all-inclusive days at the New River Gorge and other WV spots, with photo, film and an officiant.			https://westvirginiaelopements.com/	https://www.instagram.com/wvelopementcollective/
Weddings By Leah	Planning		Oak Hill	West Virginia		Oak Hill planner who takes on wedding and event planning by appointment for couples around Fayette County and the New River Gorge.		304-640-0224	https://weddingsbyleah.wixsite.com/leahcoats	
Purpose Entertainment	Music		Beckley	West Virginia	Beckley, Fayetteville, Oak Hill, Lewisburg, Summersville and southern West Virginia	Beckley DJ and MC company covering weddings across southern West Virginia, with lighting and a planning-led approach to the reception.	naybz@purposedjs.com	304-894-4003	https://purposedjs.com/	
Branded Beauty Salon	Hair & Makeup	921 Court St N	Lewisburg	West Virginia		Lewisburg salon with bridal and special-event hair and makeup services alongside colour, extensions, nails and everyday styling.			https://josiepatterson.glossgenius.com/	https://www.instagram.com/brandedbyjosie/
The Studio	Hair & Makeup	348 Webster Street	Lewisburg	West Virginia		Full-service Lewisburg hair and nail salon offering bridal consultations and special-occasion makeup through online booking.			https://square.site/book/SBY34FD55GACG/the-studio-lewisburg-wv	
Fruits of Labor	Cake	161 Main Street	Rainelle	West Virginia		Rainelle café, bakery and culinary training centre making custom wedding cakes for couples who book its full wedding catering.	jordan@fruitsoflaborinc.com	304-438-7425	https://www.fruitsoflaborinc.com/	
Kenzie's Kakes & Coffee	Cake		Beaver	West Virginia		Raleigh County bakery and coffee shop making custom cakes, including wedding and bridal shower cakes, plus cupcakes and cheesecake.			https://www.kenzieskakes.com/	
White Heaven Co	Videography		Nitro	West Virginia	New River Gorge, Fayetteville and the East Coast	Nitro-based photo and film team that regularly shoots New River Gorge weddings, delivering 4K and 6K cinematic wedding films.	booking@whiteheaven.co		https://whiteheaven.co/productions/weddings/locations/fayetteville-wv	`,
  },
];

export default batches;
