import type { VendorBatch } from "@/lib/vendor-batches";

// Wisconsin vendor batches. Every row's State is "Wisconsin". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Milwaukee: planning, florals, music, and hair and makeup",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Leigh Rice Design & Flower Co	Florals		Milwaukee	Wisconsin	Milwaukee and destinations	Full-service floral design studio and shop making sustainable, contemporary arrangements for weddings and intimate celebrations.	hello@leighricedesign.com		https://leighricedesign.com	https://www.instagram.com/leighricedesign/
Studio 24 Floral	Florals		Milwaukee	Wisconsin	Greater Milwaukee, Chicagoland and the Minneapolis metro	Owner-run Milwaukee florist making wedding flowers and event arrangements, with workshops on the side for hands-on floral fans.			https://studio24floral.com	https://www.instagram.com/studio24floral/
Eucalyptus and Company	Florals	800 E Chambers St	Milwaukee	Wisconsin	Milwaukee, Madison and Chicago areas	Milwaukee floral and art studio making natural, seasonal wedding flowers from locally grown blooms alongside ceramics and stained glass classes.	eucalyptus.co4424@gmail.com		https://eucalyptusandcompany.com	https://www.instagram.com/eucalyptus__co/
Sound Love	Music		Milwaukee	Wisconsin	Milwaukee and throughout Wisconsin	Wedding DJ team led by founder Collin Bischoff, designing each reception around the couple's tastes and acting as emcee, with 600-plus weddings since 2012.		(414) 522-1718	https://soundloveaudio.com	https://www.instagram.com/soundloveaudio_dj/
SoundWave DJs MKE	Music		Milwaukee	Wisconsin	Milwaukee, Wisconsin and Chicago	Milwaukee wedding DJ service with set wedding packages and a photo booth, also covering school dances and private parties.		(414) 368-0506	https://soundwavedjsmke.com	https://www.instagram.com/soundwave_djs_mke/
ACA Music & Entertainment	Music	1025 S Moorland Rd	Brookfield	Wisconsin	Milwaukee area and the Midwest	Entertainment agency booking live bands, ceremony string ensembles, jazz groups and DJs for weddings across the Milwaukee area.		262-790-0060	https://acaentertainment.com	
Dare to Dream Weddings	Planning		Milwaukee	Wisconsin	Milwaukee and surrounding areas	Boutique Milwaukee planning company founded in 2011 that takes on a limited number of couples each year, with full-service and six-week coordination options.		414-232-4391	https://daretodreamweddingswi.com	https://www.instagram.com/dtdweddingsmke/
Mitch & Jenna Weddings	Planning		Milwaukee	Wisconsin	Milwaukee area	Milwaukee-based team offering wedding planning, officiating and marriage coaching, with month-of coordination for couples who want to prioritise the ceremony.	jenna@mitchandjenna.com		https://mitchandjenna.com	https://www.instagram.com/mitchandjenna/
Events to a T	Planning		Milwaukee	Wisconsin	Milwaukee area	Planning and production company offering two wedding packages, handling layouts, lighting, timelines and sound with an in-house team.			https://eventstoatmke.com	https://www.instagram.com/eventstoat/
bobby.pin.beauty	Hair & Makeup		Milwaukee	Wisconsin	Greater Milwaukee Area	Onsite wedding hair and makeup collective of freelance artists, each with five or more years of experience, offering bridal trials and packages.	shenna.bpb@gmail.com		https://bobbypinbeauty.com	https://www.instagram.com/bobby.pin.beauty/
Lexi Lee Hair	Hair & Makeup	1921 Silvernail Rd	Pewaukee	Wisconsin	Greater Milwaukee area	Pewaukee salon with a dedicated team of on-site bridal hairstylists who travel to the wedding morning, with a five-service minimum.	hello@lexileehair.com		https://lexileehair.com	https://www.instagram.com/lexileehair/
Wide Eyed Bride	Hair & Makeup		Milwaukee	Wisconsin	Milwaukee and Chicago areas	Agency of on-location hair and makeup artists, most based in Milwaukee, with backgrounds in fashion and commercial work.			https://wideeyedbride.com	https://www.instagram.com/wideeyedbrides/
`,
  },
  {
    name: "Milwaukee: photography, catering, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Bailey Bryn Photography	Photography		Milwaukee	Wisconsin	Southeast Wisconsin, Lake Geneva, Madison and Chicago	Milwaukee photographer with a calm, candid style and warm editing, delivering a preview gallery within 48 hours of the wedding.	hello@baileybrynphotography.com		https://baileybrynphotography.com/	https://www.instagram.com/baileybrynphotography/
Ari Rosenthal Photography	Photography		Milwaukee	Wisconsin	Milwaukee, southeastern Wisconsin and Chicago	Milwaukee studio with a team of photographers and a long record of wedding awards, also offering videography and album design.		414-967-0540	https://arirosenthalphotography.com/	https://www.instagram.com/arirosenthalphotography/
One Shot Scott Photography	Photography		Milwaukee	Wisconsin	Milwaukee, Chicago and Lake Geneva, plus destination weddings	Milwaukee photographer who aims for laughing, relaxed couples over stiff poses, covering weddings, elopements and family sessions.			https://oneshotscottphotography.com/	https://www.instagram.com/oneshotscottphotography/
Hello Darling Films	Videography		Milwaukee	Wisconsin	Milwaukee, Chicago, Madison, Green Bay and Door County	Wedding film team creating cinematic, natural-feeling films, covering Wisconsin and Chicago as well as destination weddings.			https://www.hellodarlingfilms.com/	https://www.instagram.com/hellodarlingfilms/
Wilk Media	Videography		Milwaukee	Wisconsin	Milwaukee, Chicagoland and New York City	Milwaukee-area wedding videographer working across the city, Chicagoland and New York, with a portfolio of full wedding films from a range of venues.	jack@wilkmedia.com		https://wilkmedia.com/	https://www.instagram.com/wilk.films/
Ruach Collective	Videography		Milwaukee	Wisconsin	Milwaukee and beyond	Milwaukee filmmaker and photographer DJ Olson, making story-driven wedding films alongside work for brands and churches.	djo@ruachcollective.com		https://www.ruachcollective.com/	https://www.instagram.com/ruach_collective/
Emerald City Catering	Catering	3555 S 13th St	Milwaukee	Wisconsin	Milwaukee area	Family-owned Milwaukee caterer for weddings and events of any size, with menus shaped around the couple's style and budget.	info@emeraldcitycatering.com	414-672-3434	https://emeraldcitycatering.com/	
Antigua Catering & Events	Catering	6207 W National Ave	West Allis	Wisconsin	Milwaukee area	West Allis caterer from the Antigua Latin Inspired Kitchen team, building wedding menus around Latin and Caribbean dishes such as ceviche and paella.	catering@antiguamilwaukee.com	414-321-5775	https://www.antiguacatering.com/	
Slo' Motion BBQ	Catering	N64W22648 Main St	Sussex	Wisconsin	Southeast Wisconsin	Sussex barbecue caterer slow-smoking meats and making sides from scratch for weddings, corporate events and private parties.	orders@slomotionbbq.com	262-822-1402	https://slomotionbbq.com/	https://www.instagram.com/slomotionbbq/
Aggie's Bakery & Cake Shop	Cake	7328 W Greenfield Ave	West Allis	Wisconsin	Milwaukee and Waukesha counties	Family bakery open since 1977, making tiered wedding cakes with its own buttercream recipe and delivering across metro Milwaukee.		414-482-1288	https://www.aggiesbakery.com/	
Simma's Bakery	Cake	817 N 68th St	Wauwatosa	Wisconsin	Milwaukee area	Wauwatosa bakery open since 1982, offering wedding cakes from understated to elaborate and known for its award-winning cheesecake.	info@simmasbakery.com	414-257-0998	https://simmasbakery.com/	https://www.instagram.com/simmas_bakery/
Greige Patisserie	Cake	408 W Florida St, Suite 104	Milwaukee	Wisconsin	Milwaukee	French-style patisserie and cafe in Walker's Point whose pastry chef Jessica Reinhardtsen also makes wedding cakes and custom desserts.	info@greigemke.com		https://www.greigemke.com/	https://www.instagram.com/greigemke/
`,
  },
  {
    name: "Madison: photography, planning, florals, music, catering, hair and makeup, cakes and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kuffel Photography	Photography		Madison	Wisconsin		A Madison husband-and-wife photography duo shooting laid-back, luxury-feeling weddings with a natural, documentary look.	kuffelphoto@gmail.com		https://kuffelphotography.com/	https://www.instagram.com/kuffelphoto/
Katie Ricard Photography	Photography		Madison	Wisconsin	Wisconsin and beyond	A Madison wedding photographer shooting natural, authentic love stories across Wisconsin and further afield.	katie@katiericard.com		https://katiericard.com/	https://www.instagram.com/katiericard/
Brianna Kraft Photography	Photography		Madison	Wisconsin	Wisconsin and worldwide	A Madison photographer covering traditional weddings and adventure elopements on both digital and 35mm film.	briannakraftphotography@gmail.com	815-541-7404	https://www.briannakraftphotography.com/	https://www.instagram.com/briannakraftphotography/
Madison Vow Co	Planning		Madison	Wisconsin	Madison and beyond	A Madison planning firm run by two sisters, guiding couples through a structured planning method from vendor shortlist to wedding day.	Heather@madisonvowco.com		https://www.madisonvowco.com/	https://www.instagram.com/madisonvowco/
Relax Event Planning	Planning		Madison	Wisconsin	Madison and beyond	A full-service Madison wedding and event planning company led by one planner, Amy Murphy, who handles planning and coordination.	amy@relaxeventplanning.com		https://www.relaxeventplanning.com/	https://www.instagram.com/relaxeventplanning/
Luminous Sound Company	Music		Madison	Wisconsin	Wisconsin	A small Madison team providing luxury DJ, lighting and sound for weddings, private celebrations and upscale gatherings.	luminoussoundcompany@gmail.com		https://www.luminoussoundcompany.com/	
Dance Floor Heroes	Music		Madison	Wisconsin	Greater Madison	A Madison mobile DJ who has played the city's biggest dance clubs, now running wedding receptions and events around town.	michael@dancefloorheroes.com		https://www.dancefloorheroes.com/	
Juke Box Bandstand	Music		Madison	Wisconsin	Wisconsin	A Madison mobile DJ service running since 1978, specialising in wedding receptions and corporate events across Wisconsin.		608-249-2900	https://www.jukeboxbandstand.com/	https://www.instagram.com/jukeboxbandstand/
Lily Forest Designs	Florals	1252 Williamson St	Madison	Wisconsin	Madison and the greater Midwest	A Madison wedding and event florist with an organic, artistic style that favours domestically grown flowers where possible.	lily@lilyforestdesigns.com	608-556-8400	https://www.lilyforestdesigns.com/	https://www.instagram.com/lilyforestdesigns/
Blue Plate Catering	Catering		Madison	Wisconsin		A locally owned Madison caterer since 1992 offering full-service wedding catering and event design, with its own event venue.	contact@blueplatecatering.com	608-827-7200	https://blueplatecatering.com/	
Twisted Radish Catering	Catering		Madison	Wisconsin	Madison	A Madison caterer building bespoke menus for weddings, private celebrations and corporate events around each host's story.	twistedradishcatering@gmail.com		https://twistedradish.com/	https://www.instagram.com/TwistedRadish/
Pollen & Platter	Catering		Madison	Wisconsin	Madison and southern Wisconsin	A Madison caterer of buffets, grazing tables, food bars and small bites for work events, weddings and celebrations.		608-571-5005	https://pollenandplatter.com/	https://www.instagram.com/pollenandplatter/
Food & Cake Films and Photos	Videography		Madison	Wisconsin	Wisconsin and worldwide	A Madison husband-and-wife team making wedding films and photos for non-traditional, fun-loving couples in Wisconsin and beyond.			https://foodandcakeweddingfilms.com/	
Ella Bella Productions	Videography		Madison	Wisconsin	Wisconsin, Rockford and Chicagoland	A Madison videography and photography studio making cinematic wedding films and editorial photos across Wisconsin and Chicagoland.			https://ellabellaproductions.com/	
AB On Site Beauty	Hair & Makeup	7475 Mineral Point Rd	Madison	Wisconsin	Madison area and Wisconsin	A Madison on-site hair and makeup team that specialises in large wedding parties and comes to the venue on the day.	abonsitebeauty@gmail.com	608-574-5411	https://www.abonsitebeauty.com/	
Alice Ezrow Creative	Hair & Makeup		Madison	Wisconsin	Madison	An independent Madison stylist in a small organic salon offering bridal hair and makeup alongside sustainable hair care.		608-230-6556	https://www.aliceezrow.com/	https://www.instagram.com/aliceezrowcreative/
Be Inspired Salon	Hair & Makeup		Madison	Wisconsin	Madison	An award-winning Madison hair salon with two locations and a curly-hair speciality that also offers bridal hairstyling.		608-271-2771	https://beinspiredsalon.com/	https://www.instagram.com/be_inspired_salon/
Craig's Cake Shop	Cake	604 West Verona Ave	Verona	Wisconsin	Madison area	A Verona storefront bakery offering wedding cakes with tastings by appointment, plus grab-and-go desserts.	info@craigscakeshop.com	608-848-6331	https://craigscakeshop.com/	https://www.instagram.com/craigscakeshop/
Batch Bakehouse	Cake	1402 Willy Street	Madison	Wisconsin	Madison	A Madison neighbourhood bakery, open since 2009, that takes special orders of pies, cakes, cupcakes and cookies for weddings.	special.orders@batchbakehouse.com	608-257-1652	https://www.batchbakehouse.com/	https://www.instagram.com/batch_bakehouse/
Rolling Pin Bake Shop	Cake	2935 S Fish Hatchery Rd	Fitchburg	Wisconsin	Madison area	A Fitchburg bakeshop making gourmet desserts, pastries and cookies from scratch, including extravagant wedding cakes.		608-270-9611	https://www.rollingpinbakeshop.com/	https://www.instagram.com/rollingpinbakeshop/
KP Designs	Florals		Madison	Wisconsin	Madison and beyond	A Madison florist making custom-tailored flowers for weddings, photo shoots and private events, led by floral designer Kirstie Pence.	kirstie@kpdesignsmadison.com	608-469-6628	https://www.kpdesignsmadison.com/	https://www.instagram.com/kpdesignsmadison/
Jahr Wedding Films	Videography		Madison	Wisconsin	Madison, Milwaukee, Chicago and destination weddings	A Madison cinematography company making custom, documentary-style wedding films for couples in Wisconsin and Chicago.	hello@jahrweddingfilms.com		https://www.jahrweddingfilms.com/	https://www.instagram.com/jahrweddingfilms/
Piece of Cake Consulting	Planning		Madison	Wisconsin	Greater Madison and Lake Geneva	A full-service wedding and event planning company serving the greater Madison area as far as Lake Geneva.	pieceofcakeconsultingllc@gmail.com	608-347-6545	https://pieceofcakeconsultingllc.com/	https://www.instagram.com/pieceofcakeconsultingllc/
Leaf & Bloom	Florals	114 E Main St	Waunakee	Wisconsin	Waunakee and the greater Madison area	A Waunakee flower shop designing seasonal arrangements and wedding florals, delivering across the greater Madison area.			https://www.leafandbloomwaunakee.com/	https://www.instagram.com/leafandbloomwaunakee/
`,
  },
  {
    name: "Door County: photography, planning, florals, catering, videography, hair and makeup, and cake",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Heidi Hodges Photography	Photography		Sturgeon Bay	Wisconsin	Door County, Milwaukee and Madison	Former photojournalist photographing Door County weddings in a vibrant documentary style, with honest emotion, natural light and relaxed, modern posing.	heidi@heidihodges.com	(920) 495-0629	https://heidihodges.com/	
Sondersweet Photography	Photography	143 N 4 Ave	Sturgeon Bay	Wisconsin		Sturgeon Bay studio photographing weddings, portraits, seniors and milestone celebrations with a relaxed, sincere eye for small everyday moments.	cass@sondersweetphotography.com	920 256 1653	https://sondersweetphotography.com/	https://www.instagram.com/sondersweet_photography/
Tandem Photography of Door County	Photography		Sturgeon Bay	Wisconsin	Door County	Husband-and-wife-led team shooting relaxed, candid weddings, portraits and proposals across Door County, with video available alongside photography.	hello@tandemphotographyofdoorcounty.com	(920) 493-1622	https://www.tandemphotographyofdoorcounty.com/	https://www.instagram.com/tandemphotographyofdc/
Chris Miller Photography	Photography		Sister Bay	Wisconsin	Door County	Northern Door County photographer with over fifteen years of natural, candid wedding, elopement, engagement and family work around the peninsula.	chris@chrismillerphotography.com	(920) 883-9581	https://www.chrismillerphotography.com/	
Roost & Harbor	Photography		Washington Island	Wisconsin	Door County and beyond	Washington Island photographer capturing unposed, storytelling wedding, couple and family sessions in natural tones, serving Door County and further afield.	hannah@roostandharbor.com		https://roostandharbor.com/	https://www.instagram.com/roostandharborphoto/
Chapter One Films	Videography		Green Bay	Wisconsin	Green Bay, Door County, Milwaukee and Madison	Husband-and-wife Green Bay videography duo with a decade of experience making timeless, elegant wedding films for Door County and Wisconsin couples.			https://www.chapteronefilmswi.com/	https://www.instagram.com/chapter.one.films/
Door County Event Planners	Planning		Sister Bay	Wisconsin	Door County	Planning team led by Carrie Baldwin-Smith, with 27 years of experience offering full-service wedding planning, day-of coordination and limited-service options.	carrie@doorcountyevents.com		https://www.doorcountyweddings.com/	https://www.instagram.com/doorcountyeventplanners/
One•Eighty Petals	Florals	8999 S. Highland Road	Fish Creek	Wisconsin	Northern Door County	Flower farm and studio near Fish Creek offering field-to-event floral design for Door County weddings, plus a cut-your-own flower field.		(920) 724-1180	https://www.oneeightypetals.com/	https://www.instagram.com/oneeightypetals/
Thyme Catering	Catering		Sister Bay	Wisconsin	Door County and Northeast Wisconsin	Farm-to-table caterer creating custom menus from local ingredients, with staff to set up, serve and clear away at Door County weddings.	contact@thymecateringdoorcounty.com	920-421-5112	https://www.thymecateringdoorcounty.com/	https://www.instagram.com/thymecuisinedoorcounty/
Serves You Right Catering	Catering		Sturgeon Bay	Wisconsin	Door County	Sturgeon Bay caterer with some twenty years of experience, offering custom menus, cocktail parties and event staffing across Door County.	moragmh@gmail.com	920-743-0969	https://www.doorcountyservesyourightcatering.com/	
Blush Bridal Team	Hair & Makeup	2521 S Bay Shore Dr	Sister Bay	Wisconsin	Door County	Bridal hair and airbrush makeup team working from a Sister Bay salon with a rentable bridal suite, travelling to venues across Door County.	blushbridalteamDC@gmail.com		https://www.blushbridalteam.com/	
Brown Butter Bakeshop	Cake	10592 Country Walk Dr UNIT 19	Sister Bay	Wisconsin	Door County	From-scratch Sister Bay bakery taking orders for wedding and custom cakes alongside pastries, and offering event catering.		920-363-2560	https://brownbutterbakeshop.com/	https://www.instagram.com/Brown.Butter.Bakeshop/
FlourGirl Patissier	Cake		Jacksonport	Wisconsin	Door County	Jacksonport studio kitchen baking tiered wedding cakes, cupcakes and desserts from scratch, with weekly pickup for custom orders.	sarah@flourgirlpatissier.com	920.421.0649	https://www.flourgirlpatissier.com/	https://www.instagram.com/flourgirlpatissier/
Pink Bakery	Cake		Egg Harbor	Wisconsin	Door County	Downtown Egg Harbor bakery making custom wedding cakes and desserts alongside everyday pastries, with event catering also offered.	yuri@mojorestaurantgroup.com	920-868-3355	https://pinkbakery-doorcounty.com/	https://www.instagram.com/pinkbakerydoorcounty/
`,
  },
  {
    name: "Green Bay: Photography, Planning, Florals, Music, Catering, Hair & Makeup, Cake, Videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Kristin Reuter Photography	Photography		Green Bay	Wisconsin	Green Bay, Appleton, Oshkosh and destination weddings	Green Bay photographer covering weddings, engagements and proposals in a warm, unposed style, with senior portraits alongside.	hello@kristinreuterphotography.com	920-309-6669	https://www.kristinreuterphotography.com/	https://www.instagram.com/kristinreuterphotography/
Molly Thomas Photography	Photography		Green Bay	Wisconsin	Green Bay, Door County and Northeast Wisconsin	Green Bay wedding photographer with a light, joyful approach who also shoots family sessions around Door County and the wider northeast.	hello@mollythomasphotography.com		https://mollythomasphotography.com/	https://www.instagram.com/mollythomasphotography/
Adam Shea Photography	Photography	124 West Wisconsin Avenue STE 240E	Neenah	Wisconsin	Neenah, Menasha, Appleton, Oshkosh, Fox Valley and Green Bay	Neenah photographer shooting weddings, seniors, families and headshots in a crisp, colourful style across the Fox Valley and Green Bay.	contact@adamsheaphoto.com	(920) 215-1164	https://www.adamsheaphoto.com/	https://www.instagram.com/adamsheaphoto/
Kaytlyn Roze	Planning		Appleton	Wisconsin	Green Bay, Appleton, Oshkosh, Door County and across Wisconsin	Appleton wedding planner offering full planning, partial planning and day-of management, with venue consulting and design for polished celebrations.	hello@kaytlynroze.com		https://www.kaytlynroze.com/	https://www.instagram.com/kaytlynroze/
Alliey & Co	Planning		Green Bay	Wisconsin	Statewide across Wisconsin	Green Bay planning company that coordinates weddings and other events, with help on invitations and stationery as well as the wedding day itself.	alliey@alliey.co	920-606-3197	https://alliey.co/	https://www.instagram.com/alliey_co/
buds 'n bloom	Florals	1876 Dickinson Rd	De Pere	Wisconsin	Northeast Wisconsin	Full-service De Pere floral studio making bouquets, ceremony flowers and reception decor, with a consultation process and years of wedding work.	info@budsnbloom.com	(920) 338-0505	https://budsnbloom.wedding/	
Artful Rose	Florals		Green Bay	Wisconsin	Green Bay area	Green Bay florist run by a trained floral designer, making wedding bouquets and centrepieces with free consultations and funeral work on the side.	rose@artfulrose.com	920-819-5195	https://www.artfulrose.com/	
Roots on 9th	Florals	1369 9th St	Green Bay	Wisconsin	Green Bay	Green Bay flower shop and greenhouse with bridal packages, wedding enquiries and a showroom of rentals, as well as everyday arrangements and delivery.	info@rootsgb.com	920-634-2788	https://www.rootsgb.com/	https://www.instagram.com/roots_on_9th/
SoundFire DJ	Music	801 Heritage Rd STE E7	De Pere	Wisconsin	Door County, Green Bay, Appleton and the Fox Valley	Green Bay-based wedding DJ and MC service with set packages, lighting and entertainment, travelling across Door County and the Fox Valley.	inquiries@soundfiredj.com	920-383-3231	https://soundfiredj.com/	https://www.instagram.com/soundfiredj/
Over The Top Entertainment	Music		Appleton	Wisconsin	Appleton and the Fox Valley, no travel fee within 60 miles	Appleton wedding DJ duo working since 2003, offering high-energy music, lighting and an availability checker for couples across the Fox Valley.	overthetop@wi-net.com	(715) 570-7364	https://overthetopentertainment.com/	
Gold Medal Sound	Music		Neenah	Wisconsin	Appleton, Oshkosh and the Fox Valley	Neenah mobile DJ service for weddings, with song lists, planning worksheets and optional uplighting for receptions across the Fox Valley.	info@goldmedalsound.com	(920) 209-7890	https://www.goldmedalsound.com/	https://www.instagram.com/goldmedalsound/
Biebel's Catering & Rental	Catering	1234 Bellevue St	Green Bay	Wisconsin	Green Bay, Fox Valley and Door County	Green Bay caterer offering wedding buffets, bartending and tasting events, plus tables, chairs, linens and tent rentals under one roof.		920-468-6828	https://www.biebelscatering.com/	
Van Abel's of Hollandtown	Catering	8108 County Trunk Hwy D	Kaukauna	Wisconsin	Green Bay, the Fox Cities and nearby communities	Family-run Kaukauna supper club dating from 1848 that caters weddings on site and off site, with a customised quote for each event.	info@vanabels.com	920-766-2291	https://www.vanabels.com/	https://www.instagram.com/vanabelsofhollandtown/
Valley Catering Co.	Catering	1280 S Van Dyke Rd, Suite 1	Appleton	Wisconsin	Venues from Green Bay to Fond du Lac	Small Appleton caterer focused on hors d'oeuvres, cocktail events and wedding menus for groups of 30 to 250, seen by appointment.	valleycaterco@gmail.com		https://www.valleycaterco.com/	
Salon Fifty Four	Hair & Makeup	154 N Broadway	Green Bay	Wisconsin	Green Bay, in salon or on location	Downtown Green Bay salon taking bridal hair and makeup bookings, with separate in-salon and on-site contracts and an online enquiry form.		920-432-0601	https://www.salonfiftyfour.com/	https://www.instagram.com/salonfiftyfourgb/
Salon Cti	Hair & Makeup	330 North Mall Drive	Appleton	Wisconsin	Appleton	Appleton salon offering bridal hair and makeup with trials and wedding-day styling for the whole party, in the salon or on location.	info@saloncti.com	(920) 731-9396	https://www.saloncti.com/	https://www.instagram.com/saloncti/
715 Beautify	Hair & Makeup		Appleton	Wisconsin	Appleton and Wisconsin	Appleton wedding makeup artist who is also a licensed esthetician, offering a personal, polished bridal look with trials beforehand.			https://www.715beautify.com/	https://www.instagram.com/715beautify/
Whisk & Arrow	Cake	1915 N Richmond Street	Appleton	Wisconsin	Appleton and greater Northeast Wisconsin	Appleton bakery making buttercream wedding cakes in one to three tiers, with a wedding enquiry service and a minimum of 100 servings.	weddings@whiskandarrow.com	(920) 815-3645	https://www.whiskandarrow.com/	https://www.instagram.com/whiskandarrow/
Monzù Bakery & Custom Cakes	Cake	620 Gray St	Green Bay	Wisconsin	Green Bay	Licensed Green Bay bakery with over fifteen years of experience, making custom wedding cakes and asking couples to book well ahead.	info@monzubakery.com	920-639-9869	https://monzubakery.com/	
The Cupcake Couture	Cake	310 Main Ave	De Pere	Wisconsin	De Pere	De Pere bakery baking wedding cupcakes and desserts from scratch on the morning of the wedding, plus a small cutting cake on request.	Orders@thecupcakecouture.com	920-632-7247	https://www.thecupcakecouture.com/	https://www.instagram.com/thecupcakecouturedp/
Frassetto Films	Videography		Oshkosh	Wisconsin	Fox Valley, Green Bay, Madison and across Wisconsin	Oshkosh wedding videographer making cinematic films from a one-person studio, with packages and a photography add-on.			https://www.frassettofilms.com/	https://www.instagram.com/frassetto_films/
Sierra Studios	Videography		Green Bay	Wisconsin	Green Bay and beyond, available worldwide	Green Bay husband-and-wife studio filming and photographing weddings in a documentary, natural-light style with interview-style footage.			https://www.sierrastudiosofficial.com/	https://www.instagram.com/sierrastudiosofficial/
Next Gen Captures	Videography		Green Bay	Wisconsin	Green Bay and across Wisconsin	Green Bay studio offering wedding and engagement videography alongside photography, with hybrid packages for couples wanting both.	info@nextgencaptures.com	920-660-4522	https://www.nextgencaptures.com/	https://www.instagram.com/next_gen_captures/
`,
  },
  {
    name: "Lake Geneva: Photography, Planning, Florals, Music, Catering, Hair & Makeup, Cake, Videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Matt Mason Photography	Photography		Lake Geneva	Wisconsin	Lake Geneva, Milwaukee, Madison and Chicagoland	Lake Geneva studio shooting weddings, engagements and commercial work, with more than 100 weddings and events photographed each year.	matt@mattmasonphotography.com		https://mattmasonphotography.com/	
Katie Mallett Photography	Photography		Lake Geneva	Wisconsin	Southeast Wisconsin, including Mukwonago	Lake Geneva wedding and engagement photographer with over 150 weddings behind her, who also offers phone calls to help shape the day's timeline.	Katiemallettphotography@gmail.com	262-812-9213	https://www.katiemallettphotography.com/	
C.Mae Photography	Photography		Lake Geneva	Wisconsin	Lake Geneva, Chicago and worldwide	Team-led luxury wedding studio in Lake Geneva covering local, destination and multi-day weddings, with limited bookings each season.	contact@cmaephoto.com	312-772-3688	https://cmaephoto.com/	https://www.instagram.com/cmaephoto/
Elyse Bullard Photography	Photography		Lake Geneva	Wisconsin	Fontana, Walworth, Williams Bay, Lake Geneva, SE Wisconsin and northern Illinois	Lake Geneva photographer for weddings, engagements and portraits, with a background in wedding coordination and a relaxed approach to the day.	info@elysebullardphotography.com		https://www.elysebullardphotography.com/	https://www.instagram.com/elysebullardphotography/
Lakeside Bride	Planning		Lake Geneva	Wisconsin	Southeastern Wisconsin, mainly the Lake Geneva area	Lake Geneva planning team offering wedding packages and private party planning, with a portfolio of past events and a directory of local vendors.	Jenna@lakesidebride.com	262-949-2183	https://www.lakesidebride.com/	https://www.instagram.com/lakeside.bride/
Something Blue Wedding Planning	Planning		Lake Geneva	Wisconsin	Lake Geneva and surrounding areas	Partial, full-service and day-of wedding planning for the Lake Geneva area, run by a small team that knows the local resort venues well.	info@somethingbluelakegeneva.com	262-745-1677	https://www.somethingbluelakegeneva.com/	https://www.instagram.com/somethingbluelg/
Graceful Events Planning + Design	Planning		Lake Geneva	Wisconsin	Lake Geneva area, southern Wisconsin and northern Illinois	Lake Geneva planner and designer for weddings and private events, with a trusted-venues list and one-hour planning consultations bookable online.	gracefuleventswi@gmail.com	262-215-8835	https://www.gracefulevents.net/	https://www.instagram.com/graceful_events_weddings/
Lilypots	Florals		Lake Geneva	Wisconsin	Lake Geneva area, including Williams Bay, Twin Lakes, Delavan, Elkhorn and Whitewater	Lake Geneva flower studio led by Cassandra Duda, designing weddings and events since 2014 and delivering to venues across Walworth County.	cassandra@lilypotsevents.com	262-332-4200	https://lilypots.com/	https://www.instagram.com/lilypotsevents/
Forget Me Not Flower Market	Florals	111 S. 5th Ave.	Walworth	Wisconsin	Walworth County	Walworth flower shop run by two florists with 20 years in the county, offering custom wedding designs in a simple, rustic style with fresh local stems.	forgetmenotflowermarket@gmail.com	262-275-0796	https://www.forgetmenotflowermarket.com/	https://www.instagram.com/forgetmenotflowermarket/
Trellis Wedding Flowers	Florals		Lake Geneva	Wisconsin	Wisconsin and Illinois	Floral design studio in Lake Geneva that focuses on weddings and shows a gallery of past work, couple testimonials and press features.			https://www.flowersbytrellis.com/	
BB's Best DJ Service	Music		Burlington	Wisconsin	Burlington area, southeast Wisconsin	Owner-run Burlington DJ specialising in weddings, with standard, ceremony and uplighting packages and an online availability calendar.	dj@bbsbest.com	262-534-6527	https://bbsbest.com/	https://www.instagram.com/bbsbestdjservice/
The Classic Harpist	Music		Lake Geneva	Wisconsin	Lake Geneva, Elkhorn, Williams Bay, Delavan, Burlington and southern Wisconsin	Lake Geneva harpist playing ceremony, cocktail and dinner music solo or paired with violin, cello, flute or a string quartet.	devon@theclassicharpist.com	574-344-9401	https://theclassicharpist.com/	https://www.instagram.com/devonharpist/
Midwest DJ Productions	Music		Kenosha	Wisconsin	Kenosha and southeast Wisconsin	Kenosha wedding DJ offering reception and ceremony setups, with packages and a quote request form on its website.		262-220-4590	https://www.midwestdjproductions.com/	
Lake Life Catering	Catering	1 Liechty Dr.	Williams Bay	Wisconsin	Williams Bay and Lake Geneva	In-house caterer for the PIER 290 lakefront venue in Williams Bay, serving on-site and off-site weddings and private events.		262-245-2101	https://lakelifecatering.com/	https://www.instagram.com/lakelifecatering/
Geneva Lakes Catering	Catering		Lake Geneva	Wisconsin	Lake Geneva, Wisconsin	Lake Geneva caterer making wedding menus from scratch with local ingredients, each couple assigned an event coordinator, and weddings hosted at the Ridge Hotel.		262-249-3800	https://www.genevalakescatering.com/	
Celebration on Wells	Catering	422 S. Wells St.	Lake Geneva	Wisconsin	Lake Geneva	Full-service Lake Geneva caterer and mid-century venue since 1990, offering wedding packages, tastings, a bar, planning and coordination.		262-248-2555	https://www.celebrationonwells.com/	https://www.instagram.com/celebrationonwells/
Jordan Lynn Bridal	Hair & Makeup		Lake Geneva	Wisconsin	Lake Geneva, travelling across Wisconsin and Chicago	Lake Geneva bridal makeup artist offering bridal and bridal-party hair and makeup, with trials booked through a consultation form.	jordanlynnbridal@gmail.com		https://www.jordanlynnbridal.com/	https://www.instagram.com/jordanlynnartistry/
LUXE On Site Hair & Makeup	Hair & Makeup		Lake Geneva	Wisconsin	Lake Geneva, travelling to the client	Travelling hair and makeup team based in Lake Geneva that comes to the getting-ready location for weddings, with a portfolio and pricing page online.	luxelg@yahoo.com	630-853-8313	https://www.luxelg.com/	https://www.instagram.com/luxe_lg/
MAIE House	Hair & Makeup		Lake Geneva	Wisconsin	Lake Geneva, Fontana, Williams Bay, Delavan, Walworth, Elkhorn and surrounds	On-location bridal hair and makeup in Lake Geneva, styling brides, bridesmaids and mothers at resorts, rental homes and venues.			https://www.maiehouse.com/lakegeneva-bridal-hair-and-makeup	https://www.instagram.com/maie.house/
Julie Michelle Cakes	Cake	117 Kenosha St.	Walworth	Wisconsin	Lake Geneva, Walworth and northwest Chicago suburbs	Walworth cake studio making custom celebration and wedding cakes, with macarons, cookies and a travelling cotton candy cart as extras.	info@juliemichellecakes.com	312-800-3101	https://www.juliemichellecakes.com/	https://www.instagram.com/juliemichellecakes/
Pastries by Chad	Cake	29 N. Wisconsin St.	Elkhorn	Wisconsin	Elkhorn and Walworth County	Elkhorn bakery run by a baker who competed on Next Level Baker, making cakes and cupcakes and listing a dedicated weddings page.	pastriesbychad@gmail.com	262-379-1187	https://pastriesbychad.com/	https://www.instagram.com/pastriesbychad/
Lorelei Bittner's Bakery	Cake	495 Interchange N.	Lake Geneva	Wisconsin	Lake Geneva	Lake Geneva bakery making custom wedding cakes and desserts, with tastings and consultations usually held four to seven months ahead.	info@loreleibittnersbakery.com	262-248-2330	https://www.loreleibittnersbakery.com/	https://www.instagram.com/loreleibittnerbakery/
Memento Video & Design	Videography		Lake Geneva	Wisconsin	Wisconsin and northern Illinois	Lake Geneva videographer producing cinematic wedding films, with packages, a video gallery and free consultations booked online.	mementovideoanddesign@gmail.com	262-902-1209	http://www.mementovideoanddesign.com/	
Matthew Thomas Media	Videography		Lake Geneva	Wisconsin	Lake Geneva area	Lake Geneva studio making cinematic wedding films, with all editing and production done in-house rather than contracted out.	info@matthewthomasmedia.com	262-358-2326	https://www.matthewthomasmedia.com/	
`,
  },
  {
    name: "Milwaukee: Photography, Planning, Florals, Music, Catering, Hair & Makeup, Cake, Videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
Caroline Cavalcante Photography	Photography		Milwaukee	Wisconsin	Milwaukee, and travels anywhere	Milwaukee-based wedding and portrait photographer who is also available to travel for couples marrying beyond the city.	Contact@carolinecavalcanteph.com		https://www.carolinecavalcanteph.com	https://www.instagram.com/carolinecavalcante.ph/
Reminisce Photography	Photography		Milwaukee	Wisconsin	Milwaukee, throughout Wisconsin and northeastern Illinois	Candid, artistic wedding and portrait photography from a Milwaukee studio that mixes documentary storytelling with gentle direction.		(414) 405-6693	https://reminiscephotographymilwaukee.com	https://www.instagram.com/reminiscephotomke/
Veronica Rose Wedding Planning	Planning		Milwaukee	Wisconsin	Milwaukee, Wisconsin area	Milwaukee wedding planner offering customisable packages for couples who want help with the details and the people around them.	veronica@veronicaroseplanning.com		https://veronicaroseplanning.com	https://www.instagram.com/veronicaroseplanning/
Unique by Monique Weddings	Planning		Milwaukee	Wisconsin	Milwaukee	Milwaukee wedding coordinator who handles the logistics from the first meeting to the last song so couples can enjoy the day.	hello@itsuniquemonique.com		https://www.itsuniquemonique.com	https://www.instagram.com/its.unique.monique/
North Gate Floral	Florals		Milwaukee	Wisconsin	Greater Milwaukee metro area	Full-service wedding and event florist in Milwaukee, designing flowers and decor around each couple's vision, venue and budget.	hello@northgatefloral.com		https://northgatefloral.com	https://www.instagram.com/northgatefloral/
Avenue Bloom	Florals		Milwaukee	Wisconsin	Milwaukee	Modern wedding and elopement florist with three packages, from bouquets and buttonholes only to full ceremony and reception design.			https://www.avenuebloom.com	https://www.instagram.com/avenue_bloom/
SoundBlessed	Music		Milwaukee	Wisconsin	Milwaukee and across Wisconsin	Milwaukee DJ service providing wedding and event entertainment for couples in the city, the suburbs and further afield in Wisconsin.	Dan@soundblessed.com	(262) 563-2005	https://www.soundblessed.com	https://www.instagram.com/soundblesseddjco/
Milwaukee String Quartet	Music		Milwaukee	Wisconsin	Milwaukee and Southeastern Wisconsin	String quartet for wedding ceremonies and receptions that also plays as a trio, duo or solo and can add a vocalist.			https://milwaukeestringquartet.com	
Chef Jack's Catering	Catering		Waukesha	Wisconsin	Metro Milwaukee area, at your venue or theirs	Waukesha caterer operating since 1986, serving plated, station and family-style wedding receptions with tray-passed appetisers.		(262) 549-5558	https://www.chefjacks.com	https://www.instagram.com/chefjackscatering/
Nadi Plates	Catering		Milwaukee	Wisconsin	Milwaukee	Woman-owned Italian caterer and food truck cooking scratch-made recipes for wedding dinners and rehearsal dinners.	contact@nadiplates.com		https://nadiplates.com	https://www.instagram.com/nadiplatesmke/
Ms Lauryn Marie	Hair & Makeup		Brookfield	Wisconsin	Brookfield and Milwaukee area, travelling to the client	Bridal makeup artist based in Brookfield who travels to the client's chosen location for weddings and special occasions.	hello@mslaurynmarie.com		https://mslaurynmarie.com	https://www.instagram.com/mslaurynmarie/
Melissa Ann Artistry + Co	Hair & Makeup	N27 W23960 Paul Road, Suite 203	Pewaukee	Wisconsin	Milwaukee, Waukesha, Brookfield and further afield	Pewaukee bridal hair and makeup team that works on location or in the studio to keep the wedding morning calm.	hello@melissaannartistry.com		https://www.melissaannartistry.com	https://www.instagram.com/melissaannartistryco/
C. Adam's Bakery	Cake	400 N. Water St.	Milwaukee	Wisconsin	Milwaukee	From-scratch bakery in the Milwaukee Public Market selling tiered wedding cakes, cutting cakes and dessert-table treats.	orders@cadamsbakery.com	(414) 271-1871	https://www.cadamsbakery.com	https://www.instagram.com/c.adamsbakery/
The Cake Lady	Cake	3561 S. Kinnickinnic Ave.	St. Francis	Wisconsin	Milwaukee area	Custom wedding cakes made from scratch with Swiss buttercream, finished with fondant and gum paste flowers for Milwaukee-area couples.	cakeladydesigns@yahoo.com	(414) 294-4220	https://cakeladydesigns.com	https://www.instagram.com/cakeladydesigns/
J.C. Designs	Videography		Waukesha	Wisconsin	Waukesha, Milwaukee, Madison, Brookfield and across Wisconsin	Waukesha studio producing cinematic and documentary wedding videos, with wedding photography offered as well.	info@jcdesignswi.com	(414) 507-2192	https://www.jcdesignswi.com	https://www.instagram.com/jcdesignswi/
Flyin' Iris	Videography		Cedarburg	Wisconsin	Milwaukee area, free travel within 120 miles of Milwaukee	Husband-and-wife wedding videographers in Cedarburg making cinematic films, including Door County and Lake Geneva weddings.		(262) 384-5079	https://www.flyiniris.com	https://www.instagram.com/flyin.iris/
`,
  },
  {
    name: "Madison: Photography, Planning, Florals, Music, Catering, Hair & Makeup, Cake, Videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
AJ Photo Company	Photography		Sun Prairie	Wisconsin	Madison area and across Wisconsin	Sun Prairie documentary wedding and portrait photographer with a relaxed approach and complimentary travel within Wisconsin.	alison@ajphotocompany.com		https://www.ajphotocompany.com	https://www.instagram.com/ajphotoco/
Azena Photography	Photography	2820 Walton Commons W, Suite 131	Madison	Wisconsin	Madison	Madison wedding photographer mixing documentary coverage with magazine-style portraits, plus engagement, headshot and boudoir sessions.	hillary@azenaphoto.com		https://www.azenaphoto.com	https://www.instagram.com/azenaphotography/
Danielle Oler Wedding Coordination	Planning		Madison	Wisconsin	Greater Madison area	Madison day-of coordinator who also steps in for the final week, running the details so family and friends can relax.	danielleolerweddings@gmail.com	(608) 843-2357	https://www.danielleolerweddings.com	
Copper Feather Events	Planning		Deerfield	Wisconsin	Deerfield, Wisconsin	Boutique wedding planning company in Deerfield focused on stylish, fun celebrations that reflect each couple's story.			https://www.copperfeatherevents.com	
daffodil*parker	Florals	544 W. Washington Ave.	Madison	Wisconsin	Madison and surrounding area	Madison floral studio with a large wedding portfolio, which also runs classes, a floral CSA and subscriptions.	info@daffodilparker.com	(608) 663-2100	https://www.daffodilparker.com	https://www.instagram.com/daffodilparker/
Klein's Floral & Greenhouses	Florals	3758 E. Washington Ave.	Madison	Wisconsin	Madison, Middleton, Verona, Sun Prairie and Fitchburg	Madison florist and greenhouse on the east side with a dedicated wedding flowers service for the wider Madison area.		(608) 244-5661	https://kleinsfloral.com	https://www.instagram.com/kleinfloralgreenhouses/
Camerata String Quartet	Music		Verona	Wisconsin	Madison area, Wisconsin	Professional string quartet playing classical, folk, pop and jazz for wedding ceremonies and other elegant events.	cameratastringquartet@gmail.com		https://www.cameratastrings.com	https://www.instagram.com/cameratastringquartet/
Celebrations Entertainment	Music	3013 Perry St.	Madison	Wisconsin	Madison and across Wisconsin	Madison DJ and entertainment company providing music and hosting for weddings and other celebrations.		(608) 233-5822	https://www.celebrationsentertainment.com	https://www.instagram.com/celebrationsmadison/
Beef Butter BBQ	Catering	3001 N. Sherman Ave.	Madison	Wisconsin	Madison	Texas-style barbecue caterer in Madison offering smoked meats for weddings and other events.	patrickriha@beefbutterbbq.com	(608) 640-5000	https://beefbutterbbq.com	https://www.instagram.com/beefbutterbbq/
Buck & Honey's	Catering	804 Liberty Blvd.	Sun Prairie	Wisconsin	Madison area: Sun Prairie, Monona, Waunakee and Mount Horeb	Local restaurant group with four Madison-area locations that also offers wedding catering from its Sun Prairie base.	info@buckandhoneys.com		https://www.buckandhoneys.com	https://www.instagram.com/buckandhoneys/
Katie May Makeup	Hair & Makeup		Madison	Wisconsin	Dane County, with per-mile travel elsewhere in Wisconsin	Madison bridal makeup artist who travels to the venue, with a five-service minimum and bridal previews available.	katiemayface@gmail.com		https://www.katiemaymakeup.com	https://www.instagram.com/katiemaymakeup/
Beaming Beauty Studio	Hair & Makeup	5201 Old Middleton Rd.	Madison	Wisconsin	Madison area	Makeup studio inside Golden Hour Salon on Madison's west side offering bridal and special-event makeup with a consultation.	hello@beamingbeautystudio.com	(608) 413-2326	https://www.beamingbeautystudio.com	https://www.instagram.com/beamingbeautystudio_/
Creative Confections	Cake		Madison	Wisconsin	Madison area	Licensed home bake shop making wedding cakes for Madison-area couples, trained in piping and fondant techniques.	Alicia@CreativeConfections.net	(608) 455-1448	https://www.creativeconfections.net	
Fletcher Media	Videography		Madison	Wisconsin	Wisconsin	Madison wedding videographers offering full wedding-day films, highlight reels and livestreaming for the ceremony.			https://www.fletchermediawi.com	https://www.instagram.com/fletcher.media/
Thrive Photography & Films	Videography		Madison	Wisconsin	Madison and across Wisconsin	Madison team shooting both photography and cinematic films, so couples can book their wedding stills and video together.	info@thrivingimage.com	(608) 438-5170	https://www.thrivingimage.com	https://www.instagram.com/thrivephotographyfilms/
`,
  },
  {
    name: "Door County: Florals, Catering",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
The Artroom Flowers	Florals		Fish Creek	Wisconsin	Door County, with delivery in the county	Fish Creek florist using locally sourced seasonal flowers for weddings and everyday arrangements, delivering around Door County.	tmielcarekmelger@gmail.com		https://www.theartroomflowers.net	https://www.instagram.com/theartroomflowers/
Sonny's Italian Kitchen & Pizzeria	Catering	129 N. Madison Ave.	Sturgeon Bay	Wisconsin	Sturgeon Bay and Door County	Sturgeon Bay Italian restaurant with a catering menu for weddings and other events, plus an outdoor event space.		(920) 743-2300	https://sonnyspizzeria.com	https://www.instagram.com/sonnyspizzeriadoorcounty/
`,
  },
];

export default batches;
