import type { VendorBatch } from "@/lib/vendor-batches";

// Wyoming vendor batches. Every row's State is "Wyoming". Add new batches at the end.
const batches: VendorBatch[] = [
  {
    name: "Jackson Hole: photography, planning, florals, music, catering, hair and makeup, cake and videography",
    tsv: `Name	Category	Address	City	State	Service area	Description	Email	Phone	Website	Instagram
JCM Photography	Photography		Jackson	Wyoming	Jackson Hole and Grand Teton area; travels for destination weddings	Husband-and-wife team shooting weddings, elopements and engagements around Jackson Hole and the Tetons, and travelling for destination work.	info@jacksonholephotographers.com	307-231-0091	https://www.jacksonholephotographers.com/	https://www.instagram.com/jcmphotographyjacksonhole/
Kinsey Skye Photography	Photography		Jackson	Wyoming	Jackson Hole; travels worldwide	Documentary and cinematic wedding and elopement photographer based in Jackson Hole who also travels for destination weddings.	kinsey@kinseyskye.com	(307) 699-1467	https://kinseyskye.com/	https://www.instagram.com/kinseyskye/
Grayson Swingle Photography	Photography		Jackson	Wyoming	Jackson Hole, Teton Valley and Grand Teton National Park	Wedding, elopement, engagement and proposal photographer working in the mountain settings of Jackson Hole and the Teton region.	grayson@graysonswinglephotography.com		https://www.graysonswinglephotography.com/	https://www.instagram.com/gswinglephoto/
Wild Rose JH	Planning		Jackson	Wyoming	Jackson Hole and surrounding areas	Earth-conscious wedding and event planner offering full planning, partial coordination and elopement planning in Jackson Hole.	hello@wildrosejh.com	(307) 699-4901	https://wildrosejh.com/	https://www.instagram.com/wildrosejh/
Event Planners of Jackson Hole	Planning		Jackson	Wyoming	Jackson Hole and surrounding region	Team of planners and coordinators offering full planning and month-of coordination for weddings, with an in-house wedding officiant.		307-699-5253	https://eventplannersofjacksonhole.com/	
Forever West Weddings & Events	Planning		Jackson	Wyoming	Jackson Hole, Bozeman and Sun Valley	Wedding planning and event design that blends classical styling with the look of the American West, with Jackson Hole as a main location.	foreverwestwed@gmail.com		https://www.foreverwestweddings.com/	https://www.instagram.com/foreverwestweddings_events/
Briar Rose Flowers	Florals	495 E Hansen St	Jackson	Wyoming	Jackson, Wilson, Teton Village and Moose	Jackson florist doing custom wedding bouquets, centrepieces and arrangements, and delivering across the valley.	briarrose@onewest.net	(307) 732-1222	https://www.briarroseflowers.com/	
Fleur de V	Florals		Jackson	Wyoming	Jackson Hole	Floral designer Vanessa Flory creates flowers and event styling for weddings and parties in Jackson Hole.	vanessa@fleurdevevents.com	307.690.8440	https://www.fleurdevevents.com/	https://www.instagram.com/fleurdevjacksonhole/
Flowers by Chloe	Florals		Jackson	Wyoming		Custom floral design for weddings, events and the home, run as a small florist based in Jackson Hole.			https://www.flowersbychloejh.com/	https://www.instagram.com/flowersbychloejh/
Teton Tone	Music		Jackson	Wyoming	Destination weddings worldwide	Jackson Hole wedding band playing high-energy receptions, with ceremony sound, cocktail hour sets and an MC.	hello@tetontone.com		https://www.tetontone.com	https://www.instagram.com/tetontone/
Jackson Hole DJ	Music		Jackson	Wyoming	Jackson Hole and surrounding venues	DJ and live music team doing ceremony sound, reception DJing and guitar for cocktail hour, focused on Jackson Hole weddings since 2005.			https://www.jacksonholedj.com	https://www.instagram.com/jacksonholedj/
Snake River Strings	Music		Wilson	Wyoming	Jackson Hole and Teton County	String ensemble from solo to quartet for ceremonies and cocktail hours, playing together for over 20 years.	michelle@jhmusicacademy.com	307-690-0974	https://snakeriverstringsjh.com/	
Maho Catering	Catering		Jackson	Wyoming	Jackson Hole area	New American wedding catering led by Executive Chef Maho Hakoshima, covering rehearsal dinners and full wedding meals.	info@mcateringjh.com	307.734.9698	https://mcateringjh.com/	https://www.instagram.com/mahocatering/
Cafe Genevieve Catering	Catering	135 E Broadway	Jackson	Wyoming	Jackson Hole and surrounding communities	Catering arm of a Jackson restaurant that serves weddings and events of any size at the venue of the couple's choice.		307.732.1910	https://genevievejh.com/catering-events	https://www.instagram.com/cafegenevieve/
MileHighCook	Catering		Jackson	Wyoming	Jackson Hole and Teton County, plus Colorado, Arizona and Utah	Chef-owned caterer doing all-inclusive custom menus for multi-day destination weddings at Jackson ranches and resorts.	steve@milehighcook.net	(720) 730-7194	https://milehighcook.net/wedding-catering-in-jackson-hole-wyoming	https://www.instagram.com/milehighcook/
Hair & Makeup by Tanya	Hair & Makeup		Jackson	Wyoming	Jackson Hole, Park City, Big Sky and the Mountain West	On-location bridal hair and makeup team for weddings and elopements, with bridal packages starting at $650.		(720) 238-7969	https://tanyacrocker.com/services/bridal-services/	https://www.instagram.com/hmubytanya/
Hair by Mollie O	Hair & Makeup		Jackson	Wyoming	House calls in Teton Valley, Jackson Hole, Park City and Big Sky	Colourist, hairstylist and makeup artist offering bridal styling by appointment with house calls across the region.	molliewetzel@gmail.com	307.699.0461	https://www.molliewetzel.com/	https://www.instagram.com/mollieo_hairstylist/
Athena Beauty Artistry	Hair & Makeup		Jackson	Wyoming	Jackson Hole and surrounding area	On-site bridal hair and makeup artist with 12 years of commercial, editorial, wedding and salon experience.	athena@athenabeautyartistry.com	(406) 396-1012	https://www.athenabeautyartistry.com/	https://www.instagram.com/athenabeautyartistry/
Windy Woman Cakes	Cake		Jackson	Wyoming	Jackson, Pinedale, Star Valley and Teton Valley	Made-to-order bakery in Jackson making wedding and celebration cakes with simple, rustic, elegant finishes.			https://www.windywomancakes.com/	https://www.instagram.com/windywomancakes/
Simply Elegant Cakes	Cake		Jackson	Wyoming	Jackson Hole	Professionally trained pastry chef making custom wedding cakes and desserts for the Jackson Hole area.	simplyelegantcakesjh@gmail.com	307-264-5005	https://simplyelegantcakesjh.com/	
Foxy Cakes	Cake		Jackson	Wyoming	Greater Jackson Hole Valley	Custom wedding cakes, cupcakes and cookies in Jackson, with wedding cakes from $18 per serving and tasting consultations.			https://foxycakesjh.com/weddings	
Tower 3 Productions	Videography	2112 Hidden Ranch Ln	Jackson	Wyoming	Jackson Hole and beyond	Jackson video production company making wedding highlight films with aerial drone footage from FAA-licensed pilots.	info@tower3productions.com	307-699-1618	https://tower3productions.com/wedding-videography/	https://www.instagram.com/tower3productions/
Morales Photo & Film	Videography		Cody	Wyoming	Jackson Hole, Cody, Afton, Thayne, Alpine and Powell, plus Yellowstone and Grand Teton	Photographer and videographer shooting wedding films across northwest Wyoming, also offering a wildflower photo booth.			https://www.moralesphotoandfilm.com/	https://www.instagram.com/moralesphotoandfilm/
Diana Edlinger Studios	Videography		Jackson	Wyoming	Jackson Hole and worldwide destinations	Jackson Hole wedding photographer and filmmaker shooting digital, drone, Super 8 and 16mm film.			https://dianaedlinger.com/	
`,
  },
];

export default batches;
