import type { VenueBatch } from "@/lib/venue-batches";

// Alabama venue batches. Every row's State is "Alabama". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Birmingham and Huntsville",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Florentine Building	2101 2nd Avenue North	Birmingham	Alabama			Historic / Estate	Indoor	300		Downtown building whose upstairs ballroom began in 1926 as the Club Florentine dance hall, with a street-level café for smaller gatherings and in-house catering.	events@florentinebuilding.com	(205) 503-4470	https://florentinebuilding.com/ballroom/
Sloss Furnaces	20 32nd Street North	Birmingham	Alabama			Historic / Estate	Indoor & Outdoor			National Historic Landmark ironworks on a 32-acre site, with a modern visitor centre hall and outdoor spaces beside the old blast furnaces.	events@slossfurnaces.org	(205) 254-2025	https://www.slossfurnaces.org/events
Events at Haven	2515 6th Ave S	Birmingham	Alabama			Historic / Estate	Indoor			Restored 1924 Mack Truck building in the Lakeview District, with 20,000 sq ft of brick-walled space, a stage, a permanent bar and a bridal suite.	info@eventsathaven.com	(205) 536-7233	https://eventsathaven.com/
Cahaba Brewing Co.	4500 5th Ave South, Building C	Birmingham	Alabama			Restaurant / Vineyard	Indoor & Outdoor	120		Brewery in the historic Continental Gin building in Avondale/Woodlawn, renting its Barrel Room, taproom and covered patio.		(205) 578-2616	https://cahababrewing.com/rent-the-space/
Windwood Equestrian	4848 Highway 11	Birmingham	Alabama			Barn / Rustic	Indoor & Outdoor			Equestrian estate of more than 200 acres south of Birmingham, with European-style stables, courtyards, an arena and riverside ceremony spots.	events@windwoodequestrian.com	(205) 901-9737	https://www.windwoodequestrian.com/weddings-and-events-venue/alabama
Park Crest Event Facility	2030 Little Valley Rd	Hoover	Alabama			Garden / Outdoor	Indoor & Outdoor	260		Three spaces in Hoover: a garden with a pavilion, a two-level carriage house with chandeliers and a long double-sided fireplace, and a coach house with a large bar.	info@parkcrestevents.com	(205) 822-7275	https://www.parkcrestevents.com/
Oris & Oak	613 Sanders Road	Hoover	Alabama			Barn / Rustic	Indoor & Outdoor			Part of the old Smith Farm in Bluff Park, with an air-conditioned barn, a large pavilion and a guest house for getting ready.		(205) 866-8891	https://www.orisandoak.com/
Renaissance Birmingham Ross Bridge Golf Resort & Spa	4000 Grand Ave	Hoover	Alabama			Ballroom / Hotel	Indoor & Outdoor			Golf and spa resort on the Robert Trent Jones Golf Trail, with a ballroom, a terrace and guest rooms on site.		(205) 916-7677	https://www.marriott.com/en-us/hotels/bhmhv-renaissance-birmingham-ross-bridge-golf-resort-and-spa/events/
Rosewood Hall	2850 19th Street South	Homewood	Alabama			Ballroom / Hotel	Indoor	500		Event hall on the ground floor of Homewood City Hall at SoHo Square, with three rooms and a terrazzo foyer that open into one space.			https://rosewoodhall.com/
The Sonnet House	1487 Montevallo Road SW	Leeds	Alabama			Historic / Estate	Indoor & Outdoor			1918 farmhouse on 18 acres beside the Little Cahaba River, with in-house catering, flowers and planning.	TheSonnetHouse@gmail.com	(205) 699-7490	https://www.thesonnethouse.com/
The Ledges	32 Castle Down Drive	Huntsville	Alabama			Ballroom / Hotel	Indoor & Outdoor	270		Mountaintop golf clubhouse in stone and slate with a ballroom, a veranda and views across southeast Huntsville; non-members can book weddings.	azanlunghi@theledges.com		https://theledges.com/SpecialEvents/Weddings_and_Special_Events
106 Jefferson	106 Jefferson Street South	Huntsville	Alabama			Ballroom / Hotel	Indoor & Outdoor			Downtown lifestyle hotel with a ground-floor ballroom, a private dining room and patio, and a rooftop for daytime ceremonies.	experience@106jefferson.com	(256) 288-0128	https://www.106jefferson.com/weddings
U.S. Space & Rocket Center	One Tranquility Base	Huntsville	Alabama			Historic / Estate	Indoor			Space museum whose Davidson Center hall holds receptions beneath a Saturn V rocket, with in-house catering.	spevents@spacecamp.com	(256) 721-7173	https://rocketcenter.com/hostanevent/
Weeden House Museum	300 Gates Avenue	Huntsville	Alabama			Historic / Estate	Indoor & Outdoor	175	Simple	1819 house museum in the Twickenham historic district, renting its ground floor, porch and garden for weddings.		(256) 536-7718	https://weedenhousemuseum.com/events
A.M. Booth's Lumberyard	108 Cleveland Ave NW	Huntsville	Alabama			Restaurant / Vineyard	Indoor & Outdoor			Old lumberyard site near downtown turned into a restaurant and music venue, with a banquet hall, courtyard and a 1924 dining rail car.		(256) 651-5437	https://www.amboothslumberyard.com/weddings
Monte Sano State Park Event Lodge	5105 Nolen Ave	Huntsville	Alabama			Garden / Outdoor	Indoor & Outdoor			State park lodge on top of Monte Sano with a hearth-lined main hall and a terrace over the bluff.	monte.sanostpk@dcnr.alabama.gov	(256) 534-3757	https://www.alapark.com/parks/monte-sano-state-park/event-lodge
New Gooch Place	500 Gooch Lane	Madison	Alabama			Ballroom / Hotel	Indoor	275		Event centre near Huntsville airport with a large hall and stage, a smaller hall and a kitchen for caterers.		(256) 951-2575	https://newgoochplace.com/
The Magnolia Room	216 Moulton St E	Decatur	Alabama			Historic / Estate	Indoor	160		3,000 sq ft hall in Decatur's downtown historic district with high ceilings, original hardwood floors and a bridal suite.	Info@TMRDecatur.com	(256) 580-6160	https://themagnoliaroomdecatur.com/weddings
Heritage Corner Farm	687 Kinnard Mill Rd	Hazel Green	Alabama			Barn / Rustic	Indoor & Outdoor			Family Christmas tree farm with a modern barn beside a seven-acre lake and pier.	Spencer@ChristmasAtTheCorner.com	(256) 804-5855	https://heritagecornerfarm.com/
`,
  },
  {
    name: "Gulf Shores, Mobile and Fairhope",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Venue Fairhope	105 South Section Street	Fairhope	Alabama			Ballroom / Hotel	Indoor & Outdoor			Downtown Fairhope event space with more than 8,000 square feet inside and out.	info@venuefairhope.com	(251) 510-8444	https://venuefairhope.com/
Oak Hollow Farm	14210 Greeno Road	Fairhope	Alabama			Barn / Rustic		300		Barn venue on more than 300 acres of pasture and oaks, known for its lit tunnel of trees.		(251) 928-4840	https://oakhollowfarm.net/
Grand Hotel Golf Resort & Spa	17855 Scenic Hwy 98	Fairhope	Alabama			Ballroom / Hotel	Indoor & Outdoor			Bayside resort that hosts ceremonies and receptions in several venues around the property, with pricing by request.		(251) 928-9201	https://www.grand1847.com/
Loblolly Farm	9930 Stone Road	Semmes	Alabama			Barn / Rustic				Country-and-luxury event farm in Semmes offering event spaces and photography locations.		251-301-3850	https://loblollyfarm.com/
Crown Hall	653 St. Louis Street	Mobile	Alabama			Historic / Estate				Restored historic building downtown with a grand ballroom, the Azalea Room and the Crooked Crown, served by an in-house catering partner.	info@crownhall.events	(251) 450-9051	https://www.crownhall.events/
Rock Creek Golf Club	140 Clubhouse Dr	Fairhope	Alabama			Ballroom / Hotel	Indoor & Outdoor			Golf clubhouse that rents indoor and outdoor spaces for weddings with its own bar, catering and an event coordinator.	ashli.pridgen@rockcreekgolf.com	(251) 928-4223	https://rockcreekgolf.com/rock-creek-venue/
Eastern Shore Art Center	401 Oak Street	Fairhope	Alabama			Historic / Estate	Indoor			Downtown Fairhope art center whose three galleries can be rented singly or as a whole for receptions, with a catering kitchen and sound system.	info@esartcenter.org	(251) 928-2228	https://esartcenter.org/facility-rental/
Belforest Pointe	26503 State Highway 181	Daphne	Alabama			Garden / Outdoor	Indoor & Outdoor			Ten wooded acres with an indoor reception hall, a covered patio and open lawns.		(251) 621-1233	https://www.belforestpointe.com/
Historic Malbis Nursery	10145 US-90	Daphne	Alabama			Garden / Outdoor				Former nursery grounds with two arbors, an upstairs gathering room and a serving kitchen, rented by the hour or by the day.	Events@HistoricMalbisNursery.com		https://www.historicmalbisnursery.com/weddings
Waters' Edge	24120 Fountain St.	Robertsdale	Alabama			Barn / Rustic				Rustic wedding and event venue in central Baldwin County.	watersedge24120@gmail.com	(251) 284-0722	https://watersedgecountry.com/
Izenstone	9311 D'Olive Road	Spanish Fort	Alabama			Garden / Outdoor	Indoor & Outdoor			Venue with a climate-controlled reception room and ceremony spots such as the Secret Garden, courtyard and front lawn.	hello@izenstone.com	(251) 249-8649	https://www.izenstone.com/
Venue Thirty One	34025 US-31	Spanish Fort	Alabama			Garden / Outdoor	Outdoor			Event venue under sweeping trees in Spanish Fort with curated rentals and hands-on service.			https://www.venuethirtyone.com/
The Orchard at Hayes Farm	9854 Lancaster Road	Theodore	Alabama			Barn / Rustic	Indoor & Outdoor	200		Barn built in 2018 at the edge of a satsuma orchard, with bridal and groom suites, a covered patio and a waterfront spot for ceremonies.	hayesfarm31@gmail.com		https://www.theorchardathayesfarm.com/
Saraland Event Center	727 Saraland Blvd S.	Saraland	Alabama			Ballroom / Hotel	Indoor			Event space of over 25,000 square feet in three rooms, inside the city's municipal complex.	info@saralandeventcenter.com	251-243-1741	https://saralandeventcenter.com/
The Battle House Renaissance Mobile Hotel & Spa	26 North Royal Street	Mobile	Alabama			Ballroom / Hotel	Indoor			Downtown hotel with 16 event rooms and certified wedding planners; the Moonlight Ballroom is its largest.		251-338-2000	https://www.marriott.com/en-us/hotels/mobbr-the-battle-house-renaissance-mobile-hotel-and-spa/events/
Perdido Beach Resort	27200 Perdido Beach Blvd	Orange Beach	Alabama			Ballroom / Hotel	Indoor & Outdoor			Gulf-front resort that hosts beach ceremonies with an arch and altar and receptions on its terrace and in its event spaces.		251-981-9811	https://www.perdidobeachresort.com/weddings
The Port at Zeke's	26619 Perdido Beach Blvd	Orange Beach	Alabama			Beach / Waterfront	Indoor & Outdoor	350		Marina-side event venue with flexible indoor and outdoor space and in-house catering from Zeke's Restaurant.		(251) 341-2867	https://theportatzekes.com
Festiva on Canal	26831 Canal Rd	Orange Beach	Alabama			Ballroom / Hotel	Indoor	135		Renovated wedding hall near the beach with a bar area, dance floor, changing suite and exclusive catering.	Patti@FestivaOrangeBeach.com	1 (855) 933-7733	http://www.FestivaOrangeBeach.com
Coastal Arts Center of Orange Beach	26389 Canal Rd	Orange Beach	Alabama			Beach / Waterfront	Indoor & Outdoor			City-run arts campus with a 5,000 sq ft hall, catering kitchen and dressing areas, plus waterfront grounds with a stage facing Wolf Bay.	cacevents@orangebeachal.gov	251-981-2787	https://www.orangebeachal.gov/403/Weddings-Events-Space
Heron Pointe at The Wharf	23101 Canal Rd	Orange Beach	Alabama			Beach / Waterfront				A 10,580 sq ft event space overlooking the Intracoastal Waterway at The Wharf.		251.224.1000	https://alwharf.com/directory/heron-pointe
The Lodge at Gulf State Park	21196 East Beach Blvd	Gulf Shores	Alabama			Ballroom / Hotel	Indoor & Outdoor			Beachfront hotel with a roughly 12,000 sq ft ballroom, outdoor terraces and beach ceremony options; weddings are quoted per couple.	sales@lodgegsp.com	251-923-2918	https://lodgeatgulfstatepark.com/meetings-events/
The Beach Club Resort & Spa	925 Beach Club Trail	Gulf Shores	Alabama			Ballroom / Hotel	Indoor & Outdoor			Beachfront resort with an outdoor Veranda (up to 80 guests), an indoor Island Room (up to 125) and Coast Restaurant (up to 130) for receptions.		866-229-7350	https://thebeachclub.spectrumresorts.com/dreamy-beach-wedding-venues-at-the-beach-club-in-gulf-shores/
Gulf Place Penthouse Event Terrace	200 East Beach Blvd	Gulf Shores	Alabama			Ballroom / Hotel	Indoor & Outdoor			Rooftop penthouse venue with a 3,685 sq ft terrace, Gulf views, catering kitchen and lodging in the same building.		(251) 284-5387	https://www.luckybirdvacations.com/gulf-place-penthouse-terrace/
Legacy Oaks Venue	27300 Schoen Rd	Elberta	Alabama			Garden / Outdoor	Indoor & Outdoor		Simple	Venue under century-old oaks with a Carriage House ballroom and an outdoor ceremony site; packages run $3,900 to $5,900 and include 125 guests.	LegacyOaksVenue@gmail.com	(251) 200-2979	https://legacyoaksvenue.com/
The Veranda at the Preserve	28341 Preserve Trail	Elberta	Alabama			Garden / Outdoor				Event venue on a roughly 200-acre championship golf course that hosts destination weddings, retreats and concerts.	blake.veranda@gmail.com	251-986-8633	https://www.verandaatthepreserve.com/
Glory Farms	13780 Norris Ln	Foley	Alabama			Barn / Rustic				Family-owned wedding and event venue set among oak trees.	rachel@gloryfarms.org	251-228-2462	https://www.glory-farms.com/
The Hotel Magnolia	119 N McKenzie St	Foley	Alabama			Historic / Estate	Indoor			Downtown Foley hotel with two ballrooms that the site says hold more than 200 guests.	themagnoliahotel@gmail.com	251.952.5005	https://thehotelmagnolia.com/
The Southerly Warehouse	1007 Avenue B	Opelika	Alabama			Historic / Estate	Indoor	250		A downtown Opelika event venue in the historic district with natural light, original brick walls, wooden beam ceilings and stained concrete floors.	southerlywarehouse@gmail.com	334-610-1250	https://www.thesoutherlywarehouse.com
Auburn Oaks Farm	230 County Road 57	Notasulga	Alabama			Barn / Rustic	Indoor & Outdoor	300		A 600-acre private farm near Auburn with a pond-side ceremony lawn, a 10,000 sq ft indoor clubhouse for receptions and on-site lodging houses.	info@auburnoaksfarm.com	334-257-1210	https://www.auburnoaksfarm.com
Fountainview Mansion	2700 Mimms Trail	Auburn	Alabama			Historic / Estate				A hilltop English-style mansion in Auburn filled with antiques and set in an English garden.	info@fountainviewmansion.com	334-203-4334	https://www.fountainviewmansion.com
The Bottling Plant Event Center	614 North Railroad Ave	Opelika	Alabama			Ballroom / Hotel	Indoor			A downtown Opelika event venue near Auburn University with an on-site kitchen and full liquor license.	scott@bottlingplanteventcenter.com	334-705-5466	https://www.bottlingplanteventcenter.com
Brunson Farms	6505 Steele Station Road	Rainbow City	Alabama			Barn / Rustic				A family-run farm-setting wedding and event venue open since 2020 that plans events start to finish with preferred vendors.	jcbrunson444@gmail.com	256-490-8282	https://brunsonfarmsal.com/
Pickett Place	438 N Seminary St	Florence	Alabama			Historic / Estate	Indoor & Outdoor			A historic downtown Florence venue dating to 1833 offering indoor and outdoor ceremonies.	info@pickettplaceevents.com	256-668-1777	https://www.pickettplaceevents.com
The Historic Drish House	2300 17th Street	Tuscaloosa	Alabama			Historic / Estate	Indoor & Outdoor			An early-19th-century Tuscaloosa mansion offering indoor rooms and a 40 by 80 party tent on landscaped grounds.		(205) 356-8194	https://historicdrishhouse.com/
Windmill Station Dothan	1369 Headland Ave	Dothan	Alabama			Barn / Rustic				A Dothan wedding venue with several named spaces including The Roosevelt, The Boiler Room and The Bower, plus bridal and private suites.	info@windmillstationdothan.com	334-805-9057	https://windmillstationdothan.com/
Jordan's Barn	10551 County Road 59 South	Midland City	Alabama			Barn / Rustic		300	Simple	A Dothan-area wedding barn on landscaped grounds, with weekend wedding packages listed at $2,500 to $4,000.	patsyjordan191@gmail.com	334-984-0090	https://www.jordansbarn.com
The Eclectic Warehouse	45 Main Street	Eclectic	Alabama			Historic / Estate	Indoor & Outdoor		Simple	A group of seven venues in Eclectic including an indoor warehouse and an outdoor woodland amphitheater.	athornsby@comcast.net		https://www.theeclecticwarehouse.com
Trilogy Hotel Montgomery	116 Coosa Street	Montgomery	Alabama			Ballroom / Hotel				A boutique hotel in Montgomery's historic district housed in three restored historic buildings.		(334) 440-3550	https://trilogyhotelmontgomery.com/wedding-and-social/
`,
  },
];

export default batches;
