import type { VenueBatch } from "@/lib/venue-batches";

// Arizona venue batches. Every row's State is "Arizona". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Phoenix venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Royal Palms Resort and Spa	5200 E Camelback Rd	Phoenix	Arizona			Ballroom / Hotel	Indoor & Outdoor			A 1920s-era winter home turned resort on nine acres of gardens at the base of Camelback Mountain, with Mediterranean-style rooms and garden ceremony sites.		602-283-1234	https://www.royalpalmshotel.com/weddings/
Schnepf Farms	22601 E Cloud Rd	Queen Creek	Arizona			Barn / Rustic	Indoor & Outdoor	250		Family farm with three wedding sites: a 1950s farmhouse beside a peach orchard, a pine-shaded outdoor meadow and a 7,000 sq ft 1960s red barn.	weddings@schnepffarms.com	480-987-3100	https://schnepffarmsweddings.com/
The Farm at South Mountain	6106 S 32nd St	Phoenix	Arizona			Garden / Outdoor	Outdoor	250		Farm on an old riverbed in south Phoenix where ceremonies take place in a pecan grove and dinners are served under a canopy or in a walled garden.	info@thefarmatsouthmountain.com	602-276-6360	https://thefarmatsouthmountain.com/weddings/
Superstition Manor	1220 N Signal Butte Rd	Mesa	Arizona			Historic / Estate	Indoor & Outdoor			Eleven-acre estate facing Superstition Mountain with three reception halls (two villas and a barn), each with its own ceremony yard and covered patio.	info@superstitionmanor.com	480-286-7806	https://superstitionmanor.com/
Venue at the Grove	7010 S 27th Ave	Phoenix	Arizona			Garden / Outdoor	Outdoor	225		Exclusive-use property of just over two acres in south Phoenix, set in a pecan orchard wrapped in lights, with a brick reception patio under the trees.	info@venueatthegrove.com	602-456-0803	https://www.venueatthegrove.com/weddings
Hotel Valley Ho	6850 E Main St	Scottsdale	Arizona			Ballroom / Hotel	Indoor & Outdoor	250		Mid-century modern hotel in Scottsdale with a rooftop terrace, a palm-lined lawn, a citrus grove and a ballroom, plus guest rooms on site.		480-376-2600	https://hotelvalleyho.com/weddings/
Wrigley Mansion	2501 E Telawa Trl	Phoenix	Arizona			Historic / Estate	Indoor & Outdoor			1930s hilltop mansion in Phoenix with views over the city and mountains, its own restaurants and a range of event rooms.		602-955-4079	https://wrigleymansion.com/weddings/
El Chorro	5550 E Lincoln Dr	Paradise Valley	Arizona			Restaurant / Vineyard	Indoor & Outdoor			Supper-club restaurant and lodge in Paradise Valley dating from 1937, hosting weddings and events alongside its dining rooms.		480-948-5170	https://www.elchorro.com/
The Wigwam	300 E Wigwam Blvd	Litchfield Park	Arizona			Ballroom / Hotel	Indoor & Outdoor			West Valley resort in Litchfield Park with more than 100,000 sq ft of indoor and outdoor event space and guest rooms on site.		844-239-1641	https://www.wigwamarizona.com/weddings
`,
  },
  {
    name: "Tucson, Southern Arizona and Northern Arizona venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
White Stallion Ranch	9251 W Twin Peaks Rd	Tucson	Arizona			Barn / Rustic	Indoor & Outdoor	300	Classic	Working guest ranch west of Tucson with a desert pavilion, a Longhorn Room and a bird garden, plus resort lodging for wedding guests.	info@whitestallion.com	(520) 297-0252	https://whitestallion.com/weddings/
Sonoita Vineyards	290 Elgin-Canelo Rd	Elgin	Arizona			Restaurant / Vineyard	Indoor & Outdoor	72	Simple	Vineyard of over 30 acres at 5,000 feet with a Vintage Room and balcony, a lawn and mountain views.	winery@sonoitavineyards.com	520-455-5893	https://www.sonoitavineyards.com/
Cocoraque Ranch	3199 N Reservation Rd	Marana	Arizona			Barn / Rustic	Outdoor	500		Working cattle ranch near Marana with a covered pavilion, desert ceremony sites, a bridal suite and Santa Cruz Valley mountain views.	cocoraque2000@gmail.com	(520) 490-0616	https://cocoraque.com/
The Farm by Miller Made Events	15701 W Avra Ln	Marana	Arizona			Barn / Rustic	Indoor & Outdoor	200		Eighty-acre working farm with a 3,200 sq ft barn that began life as an aircraft hangar, plus a bridal suite.			https://thefarmmarana.com/
Glover Ranch	13400 W Twin Peaks Rd	Marana	Arizona			Barn / Rustic	Indoor & Outdoor	100	Simple	Ranch about nine miles from Tucson with a bistro-lit barn, green fields, antique tractors, a bridal suite and a groom's casita.			https://www.gloverranch.com/weddings
Agua Linda Farm	2643 E Frontage Rd	Amado	Arizona			Historic / Estate	Indoor & Outdoor			Private 63-acre ranch with a historic adobe hacienda, pastures, a cafe-lit reception garden and mountain views.	info.agualindafarm@gmail.com	520-891-5532	https://www.agualindafarm.com/
The Treasury 1929	2 East Congress	Tucson	Arizona			Historic / Estate	Indoor			Former bank opened in 1929 in downtown Tucson, with 22,000 sq ft over three storeys including a marble-columned main hall and mezzanine.	info@thetreasury1929.com	(520) 734-3979	https://www.thetreasury1929.com/
Westward Look Wyndham Grand Resort & Spa	245 E Ina Rd	Tucson	Arizona			Ballroom / Hotel	Indoor & Outdoor	450		Resort on 80 acres of Sonoran Desert that grew from a 1912 hacienda-style family home, with rooftop and ballroom spaces and a chef's garden.		520.297.1151	https://www.westwardlook.com/weddings
Tucson Botanical Gardens	2150 N Alvernon Way	Tucson	Arizona			Garden / Outdoor	Indoor & Outdoor			Central Tucson garden with outdoor garden venues, indoor galleries for receptions and a butterfly greenhouse for cocktail hours in season.	rentals@tucsonbotanical.org	(520) 326-9686	https://tucsonbotanical.org/host-an-event/weddings/
Loews Ventana Canyon Resort	7000 N Resort Dr	Tucson	Arizona			Ballroom / Hotel	Indoor & Outdoor			Foothills resort with 398 guest rooms, 37,000 sq ft of indoor function space, nearly 40,000 sq ft outdoors and two Tom Fazio golf courses.		520-299-2020	https://www.loewshotels.com/ventana-canyon
Historic Bates Mansion		Tucson	Arizona			Historic / Estate	Indoor & Outdoor			Renovated former home of businessman C.T.R. Bates in Tucson, finished in a rustic hacienda style with old pueblo influences.	HistoricBatesMansion@gmail.com	520-221-5555	https://www.thehistoricbates.com/
Hacienda Del Sol Guest Ranch Resort	5501 N Hacienda del Sol Rd	Tucson	Arizona			Historic / Estate	Indoor & Outdoor	175		Foothills guest ranch resort with a historic courtyard and botanical gardens, an indoor-outdoor ballroom and views of the Santa Catalina Mountains.		(520) 299-1501	https://www.haciendadelsol.com/weddings
Tanque Verde Ranch	14301 E Speedway Blvd	Tucson	Arizona			Barn / Rustic	Indoor & Outdoor	350		Dude ranch on Tucson's east side with several indoor and outdoor ceremony venues, guest lodging, dining and desert surroundings.		(520) 296-6275	https://www.tanqueverderanch.com/weddings
Stardance Event Center	8110 N Scenic Dr	Tucson	Arizona			Barn / Rustic	Indoor & Outdoor			Thirty-acre site bordering Saguaro National Park West with a barn-style reception hall, ceremony lawn, courtyard and mountain-view terrace.			https://stardanceweddings.com/
Solana Guest Ranch & Spanish Villas	10700 E Tanque Verde Rd	Tucson	Arizona			Historic / Estate	Indoor & Outdoor			Eleven-acre former guest ranch dating from 1948 in the Tanque Verde Valley, with Spanish-style villas, casitas and lodging for up to 90.	events@solanaspanishvillas.com	(520) 200-2059	https://solanaspanishvillas.com/tucson-wedding-venue/
The Joshua Tree House (JTH Tucson)		Tucson	Arizona			Garden / Outdoor	Indoor & Outdoor	22		Small desert inn bordering Saguaro National Park West that hosts micro-weddings and elopements as a full property buyout.	tucson@thejoshuatreehouse.com		https://www.thejoshuatreehouse.com/tucson/
The Arboretum at Flagstaff	4001 S Woody Mountain Rd	Flagstaff	Arizona			Garden / Outdoor	Outdoor			Two hundred acres of private land inside the Coconino National Forest with curated gardens, patios, wildflower meadows and over 750 plant species.	info@thearb.org	928-774-1442	https://thearb.org/weddings/
The Event Center at Sam Hill Warehouse	232 N Granite St	Prescott	Arizona			Historic / Estate	Indoor & Outdoor			Restored 1903 hardware warehouse with brick-walled rooms, railroad freight doors, a patio and a restored 1893 railway bridge over Granite Creek.		928-515-1381	https://www.samhillwarehouse.com/
The Venue on Cortez	105 W Carleton St	Prescott	Arizona			Garden / Outdoor	Indoor & Outdoor			Former Prescott Wedding Chapel near downtown with indoor and outdoor ceremony spaces and a private two-bedroom residence for guest lodging.	info@thevenueoncortez.com	928.533.4421	https://www.thevenueoncortez.com/
The Wilde Resort and Spa	2250 W State Rte 89A	Sedona	Arizona			Ballroom / Hotel	Indoor & Outdoor			Boutique Sedona resort with about 6,000 sq ft of indoor and outdoor event space, including rooftop and fire-pit areas.		928-203-4111	https://thewilderesort.com/
Sanctuary Camelback Mountain	5700 East McDonald Drive	Paradise Valley	Arizona			Ballroom / Hotel	Indoor & Outdoor	200		Mountainside resort on 53 acres with a wedding lawn, a glass-enclosed ballroom, terraces and landscaped grounds.		1-844-390-4754	https://www.sanctuaryaz.com/weddings
Viola's Weddings & Events (The Gardens at Viola's)	610 S State Route 89A	Flagstaff	Arizona			Garden / Outdoor	Outdoor			Garden wedding site in southwest Flagstaff beside a flower garden, with a second ponderosa-pine venue, Serendipity, in west Flagstaff.	planner@flagstaffweddingvenue.com	928-853-0399	https://www.flagstaffweddingvenue.com/
`,
  },
  {
    name: "Sedona and Flagstaff, Prescott and Phoenix venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Amara Resort and Spa	100 Amara Lane	Sedona	Arizona			Ballroom / Hotel	Indoor & Outdoor	80		Boutique resort tucked beside Oak Creek in Uptown Sedona, with red-rock views and indoor and outdoor spaces for dinners of up to 80.		844-489-9662	https://www.amararesort.com/weddings/
Sky Ranch Lodge	1105 Airport Rd	Sedona	Arizona			Ballroom / Hotel	Indoor & Outdoor	120	Classic	Lodge on top of Airport Mesa with wide red-rock views, an outdoor ceremony site and set wedding packages for 25 to 120 guests.	weddings@skyranchlodge.com	928-282-6400	https://skyranchlodge.com/weddings
Sedona Golf Resort	35 Ridge Trail Dr	Sedona	Arizona			Garden / Outdoor	Indoor & Outdoor	175		Golf course in the Village of Oak Creek whose clubhouse, lawn, patio and Sixth Fairway site all face the surrounding red rocks.		928-284-9355	https://azhideawaycollection.com/sedona-golf-resort/celebrations-gatherings/
The Club at Seven Canyons	625 Golf Club Way	Sedona	Arizona			Garden / Outdoor	Indoor & Outdoor			Private golf club ringed by red-rock canyon walls west of Sedona that opens its clubhouse and grounds for weddings with in-house event planning.		928-203-2000	https://sevencanyons.com/weddings/
Junipine Resort	8351 N Highway 89A	Sedona	Arizona			Garden / Outdoor	Outdoor			Creekside cottages in the pines of Oak Creek Canyon, with a gazebo beside the water for small, rustic weddings and family-sized lodging.	reservations@junipine.com	800-742-7463	https://www.junipine.com/sedona-event-venues
Tlaquepaque Arts & Shopping Village	336 State Route 179	Sedona	Arizona			Historic / Estate	Indoor & Outdoor	100		Mexican village-style arts and shopping centre beside Oak Creek with its own chapel for 45 and cobbled courtyards and terraces for receptions of 100.		928-282-4838	https://tlaq.com/weddings/
Briar Patch Inn	3190 N State Route 89A	Sedona	Arizona			Garden / Outdoor	Outdoor	25	Simple	Nine-acre cottage inn on Oak Creek under old sycamores, hosting elopements and small creekside ceremonies of up to 25 people.		928-282-2342	https://briarpatchinn.com/weddings/
Alcantara Vineyard	3445 S Grapevine Way	Cottonwood	Arizona			Restaurant / Vineyard	Indoor & Outdoor			Verde Valley vineyard and winery near Cottonwood with ceremonies among the vines, receptions on the estate and an option for dry weddings.	sales@alcantaravineyard.com	928-649-8463	https://alcantaravineyard.com/weddings/
The Weatherford	23 N Leroux St	Flagstaff	Arizona			Historic / Estate	Indoor	200		Downtown Flagstaff hotel serving guests since 1897, with five event rooms including a ballroom and a reception hall for up to 200.		928-779-1919	https://weatherfordhotel.com/host-your-event/plan-your-event/weddings/
Arizona Snowbowl	9300 N Snowbowl Rd	Flagstaff	Arizona			Garden / Outdoor	Indoor & Outdoor			Ski area on the San Francisco Peaks where couples marry at 9,300 feet, with lodge seating indoors and out and its own chefs and catering team.		928-447-9928	https://www.snowbowl.ski/weddings/
Lowell Observatory	1400 W Mars Hill Rd	Flagstaff	Arizona			Historic / Estate	Indoor & Outdoor	150	Classic	Working astronomical observatory on Mars Hill above downtown Flagstaff, renting its halls and grounds for weddings with planetarium options for guests.	events@lowell.edu	928-774-3358	https://lowell.edu/visit/venue-rentals/weddings/
Arizona Nordic Village	16848 US-180	Flagstaff	Arizona			Barn / Rustic	Indoor & Outdoor			Cross-country ski centre in the aspens and pines north of Flagstaff with rustic on-site lodging, hosting single-day or multi-day weddings May to October.	weddings@flagstaffnordiccenter.com	928-326-3121	https://www.arizonanordicvillage.com/weddings-events
Prescott Resort and Conference Center	1500 E State Route 69	Prescott	Arizona			Ballroom / Hotel	Indoor & Outdoor	300		Hilltop resort with mountain views over Prescott whose Goldwater Ballroom seats up to 300, with two smaller rooms for 80.	info@prescottresort.com	855-957-4637	https://www.prescottresort.com/weddings
Forest Villas Hotel	3645 Lee Circle	Prescott	Arizona			Ballroom / Hotel	Indoor & Outdoor	50		Mediterranean-style hotel in Prescott that specialises in intimate weddings of 50 or fewer, with chandeliered rooms, patios and gardens.	welcome@forestvillas.com	928-717-1200	https://forestvillas.com/weddings-and-events/
Arizona Grand Resort & Spa	8000 S Arizona Grand Pkwy	Phoenix	Arizona			Ballroom / Hotel	Indoor & Outdoor	1200		Large resort at the foot of South Mountain with a ballroom for receptions of up to 1,200 and smaller rooms and patios for 100 to 400.		602-438-9000	https://www.arizonagrandresort.com/weddings/
The Venue Scottsdale	7117 E 3rd Ave	Scottsdale	Arizona			Ballroom / Hotel	Indoor			Event and concert hall in Old Town Scottsdale that hosts weddings, galas and private celebrations with in-house planning.		480-945-5551	https://thevenuescottsdale.com/planning-your-event/weddings/
SoHo63	63 E Boston St	Chandler	Arizona			Ballroom / Hotel	Indoor			Modern event venue in downtown Chandler, steps from hotels, restaurants and bars, with customisable wedding packages and an in-house team.	celebrate@soho63.com		https://soho63.com/weddings
Saguaro Lake Guest Ranch	13020 N Bush Hwy	Mesa	Arizona			Barn / Rustic	Indoor & Outdoor	200		Historic guest ranch on the Salt River below Saguaro Lake, with 20 cabins sleeping 60 and weekday weddings for up to 200 guests.	info@saguarolakeranch.com	480-984-2194	https://www.saguarolakeranch.com/weddings
Boyce Thompson Arboretum	37615 E Arboretum Way	Superior	Arizona			Garden / Outdoor	Indoor & Outdoor	150		Arizona's oldest botanical garden, below Picketpost Mountain, with garden ceremony sites, a historic greenhouse and a picnic-area lawn for 150.		520-689-2723	https://btarboretum.org/weddings/
Phoenix Zoo	455 N Galvin Pkwy	Phoenix	Arizona			Garden / Outdoor	Indoor & Outdoor			Zoo in Papago Park with more than a dozen rentable spaces, from the Ruby's House garden cottage to an indoor event centre and lawns.		602-914-4301	https://www.phoenixzoo.org/visit/venues-private-events/weddings/
`,
  },
];

export default batches;
