import type { VenueBatch } from "@/lib/venue-batches";

// California venue batches. Every row's State is "California". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Los Angeles",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Carondelet House	627 S Carondelet St	Los Angeles	California			Historic / Estate	Indoor & Outdoor	150		Italian-style 1926 brick building near MacArthur Park with courtyards, parlours and a bridal suite, catered in house.	info@carondelethouse.com	323.310.4700	https://www.carondelethouse.com/weddings
Redbird | Vibiana	114 E 2nd St	Los Angeles	California			Historic / Estate	Indoor & Outdoor	550	Luxury	Former downtown cathedral turned event hall, paired with chef Neal Fraser's restaurant, a garden and several private rooms.	events@redbird.la	(213) 788-1191	https://redbird.la/private-dining-event-venue/
Terranea Resort	100 Terranea Way	Rancho Palos Verdes	California			Beach / Waterfront	Indoor & Outdoor			Clifftop oceanfront resort on the Palos Verdes Peninsula with lawns and points for ceremonies, a large ballroom and villas for guests.		(866) 547-3066	https://www.terranea.com/weddings
Castle Green	99 S Raymond Ave	Pasadena	California			Historic / Estate	Indoor & Outdoor			Victorian-era Pasadena landmark more than a century old, restored in detail and listed on the National Register.	events@castlegreen.com	626-793-0359	https://www.castlegreen.com/weddings
Millwick	800 E 4th Pl	Los Angeles	California			Garden / Outdoor	Indoor & Outdoor	175		Arts District venue whose 7,000 square feet join a grand hall to a garden courtyard.			https://marvimon.com/millwick/
Smogshoppe	2651 S La Cienega Blvd	Los Angeles	California			Garden / Outdoor	Indoor & Outdoor	150		Culver City Arts District venue with a 6,500-square-foot hall opening onto a 2,000-square-foot garden courtyard.			https://marvimon.com/smogshoppe/
Taglyan Complex	1201 Vine St	Los Angeles	California			Ballroom / Hotel	Indoor & Outdoor			Hollywood banquet complex opened in 2008, with a ballroom under a circular stained-glass ceiling and Italian-style gardens with a fountain.		(323) 978-0005	https://www.taglyancomplex.com/
Skirball Cultural Center	2701 N Sepulveda Blvd	Los Angeles	California			Garden / Outdoor	Indoor & Outdoor	670		Fifteen-acre cultural campus in the Sepulveda Pass with courtyards, a lily-pond courtyard, garden terraces and an arched pavilion for up to 670.	private-events@skirball.org	(310) 440-4529	https://www.skirball.org/private-events/overview
The Queen Mary	1126 Queens Hwy	Long Beach	California			Beach / Waterfront	Indoor & Outdoor			Historic ocean liner moored in Long Beach harbour, with ceremonies on the bow, stern or decks, a wedding chapel and staterooms on board.	sales@queenmary.com	562-435-3511	https://www.queenmary.com/weddings.htm
Hotel Casa del Mar	1910 Ocean Way	Santa Monica	California			Beach / Waterfront	Indoor & Outdoor	600		Beachfront hotel in Santa Monica with a colonnade ballroom, a conservatory and terraces facing the sand for ceremonies.	catering@hotelcasadelmar.com	(310) 587-1705	https://www.hotelcasadelmar.com/weddings
The Langham Huntington, Pasadena	1401 S Oak Knoll Ave	Pasadena	California			Ballroom / Hotel	Indoor & Outdoor			Historic hotel in the hills of Pasadena with gardens and period ballrooms for ceremonies and receptions.	tllax.info@langhamhotels.com	(626) 568-3900	https://www.langhamhotels.com/en/the-langham/pasadena/
The Majestic Downtown	650 S Spring St	Los Angeles	California			Historic / Estate	Indoor	600		Historic Spring Street building with more than 30,000 square feet of preserved halls, painted ceilings, marble columns and grand staircases.	info@majesticdowntown.com	(213) 278-7162	https://www.themajesticdowntown.com/
Shutters on the Beach	1 Pico Blvd	Santa Monica	California			Beach / Waterfront	Indoor & Outdoor	400		Shingled beachfront hotel at the foot of Pico Boulevard with a salon, terrace and promenade by the sand, and guest rooms up to beach-house suites.	catering@shuttersonthebeach.com	(310) 587-1705	https://www.shuttersonthebeach.com/weddings
Hotel Figueroa	939 S Figueroa St	Los Angeles	California			Ballroom / Hotel	Indoor & Outdoor	140		Historic 14-storey boutique hotel downtown with an outdoor terrace and a ballroom for up to 140.		213.627.8971	https://www.hotelfigueroa.com/meetings-events/weddings/
Saddle Peak Lodge	419 Cold Canyon Rd	Calabasas	California			Barn / Rustic	Indoor & Outdoor	150		Rustic mountain lodge restaurant in the Santa Monica Mountains with a stone-fireplace dining room, a library and a waterfall patio for up to 150.		(818) 222-3888	https://www.saddlepeaklodge.com/weddings
Natural History Museum of Los Angeles County	900 Exposition Blvd	Los Angeles	California			Historic / Estate	Indoor			Exposition Park museum where ceremonies and receptions use the grand foyer and dinners are set among the North American mammal dioramas.		213.763.3466	https://nhmlac.org/host-event
The Hollywood Roosevelt	7000 Hollywood Blvd	Los Angeles	California			Ballroom / Hotel	Indoor & Outdoor			1920s Hollywood Boulevard hotel where the first Oscars were held, with a chandeliered ballroom, a rooftop facing the Hollywood sign and a pool deck.		(323) 785-7000	https://www.thehollywoodroosevelt.com/weddings/
Rancho Las Lomas	19191 Lawrence Canyon	Silverado	California			Garden / Outdoor	Indoor & Outdoor			Twenty-one-acre Spanish-style property in the Orange County foothills with an open-air theatre, a terrace, a grand salon and two suites for getting ready.	info@rancholaslomas.com	949.888.3080	https://www.rancholaslomas.com/
Westlake Village Inn	31943 Agoura Rd	Westlake Village	California			Garden / Outdoor	Indoor & Outdoor			Lakeside inn on the Ventura County line with arbour, garden and waterfall ceremony spots, six reception rooms including a wine cellar, and guest rooms on site.		(818) 889-1460	https://www.westlakevillageinn.com/weddings
The Maya	700 Queensway Dr	Long Beach	California			Beach / Waterfront	Indoor & Outdoor	400		Waterfront hotel across the harbour from downtown Long Beach with a glass-walled pavilion, a sand beach with fire pits and seven indoor-outdoor event areas.		562.435.7676	https://www.themayalongbeach.com/weddings
Malibu Beach Inn	22878 Pacific Coast Hwy	Malibu	California			Beach / Waterfront	Indoor & Outdoor			Small hotel on Carbon Beach with ceremonies on the sand and indoor rooms for receptions and rehearsal dinners.	events@malibubeachinn.com	310.651.7777	https://www.malibubeachinn.com/weddings
Hart & Main	24217 Main St	Newhall	California			Ballroom / Hotel	Indoor & Outdoor			Mid-century-styled event building in downtown Newhall with indoor and outdoor spaces, a rooftop deck, couple's suites and its own kitchen and bar.	Info@hartandmain.com	661-425-7364	https://hartandmain.com/`,
  },
  {
    name: "San Francisco Bay Area",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Berkeley City Club	2315 Durant Ave	Berkeley	California			Historic / Estate	Indoor & Outdoor	250		A 1920s Gothic-Moorish clubhouse and National Historic Landmark near the UC campus, with ballrooms, a covered terrace and courtyard, and 39 guest rooms upstairs.	reservations@berkeleycityclub.com	510-848-7800	https://www.berkeleycityclub.com/weddings
Outdoor Art Club	1 W Blithedale Ave	Mill Valley	California			Historic / Estate	Indoor & Outdoor	140	Classic	A 1904 Bernard Maybeck Arts and Crafts clubhouse in downtown Mill Valley, listed on the National Register, with a garden terrace and front patio for ceremonies.	rentals@outdoorartclub.org		https://www.outdoorartclub.org/rentals
Nestldown	22420 Old Santa Cruz Hwy	Los Gatos	California			Garden / Outdoor	Indoor & Outdoor	150		A family-owned 180-acre property in the Santa Cruz Mountains with 36 acres of gardens among redwoods, a chapel, meadow, koi pond and a barn that seats dinner in its loft.		408-353-5311	https://www.nestldown.com/weddings/
Hakone Estate and Gardens	21000 Big Basin Way	Saratoga	California			Garden / Outdoor	Indoor & Outdoor			An 18-acre Japanese garden estate begun in 1915 in the Saratoga hills, with a koi pond, moon bridge, bamboo forest and a replica Kyoto tea merchant's house for receptions.	events@hakonegardens.org	408-741-4957	https://www.hakone.com/weddings-and-receptions
Cavallo Point	601 Murray Cir	Sausalito	California			Ballroom / Hotel	Indoor & Outdoor	250		A lodge in the historic Fort Baker army post at the foot of the Golden Gate Bridge, with a historic chapel, a ballroom, bay views and guest rooms on site.	weddings@cavallopoint.com	415-339-4731	https://www.cavallopoint.com/weddings
Montalvo Arts Center	15400 Montalvo Rd	Saratoga	California			Historic / Estate	Indoor & Outdoor			A Mediterranean villa and arts centre in the Saratoga foothills with a great lawn, Spanish courtyard, oval garden and love temple, set among old redwoods and hiking trails.	events@montalvoarts.org	408-961-5800	https://montalvoarts.org/host/weddings/
Elliston Vineyards	463 Kilkare Rd	Sunol	California			Restaurant / Vineyard	Indoor & Outdoor			A winery estate in the Sunol hills with a historic stone mansion, a south lawn and gazebo for ceremonies, and a hillside Terrace Room among oaks and olive trees.	info@elliston.com	925-862-2377	https://ellistonvineyards.com/pages/weddings
Thomas Fogarty Winery	19501 Skyline Blvd	Woodside	California			Restaurant / Vineyard	Indoor & Outdoor	200		A mountaintop winery about 2,000 feet above Silicon Valley with a ceremony lawn facing the bay, a covered pavilion among the vines and the enclosed Hill House and terrace.	events@fogartywinery.com	650-851-6772	https://www.fogartywinery.com/pages/weddings
Murrieta's Well	3005 Mines Rd	Livermore	California			Restaurant / Vineyard	Indoor & Outdoor	120		A historic Livermore Valley estate winery with indoor rooms and a patio near the old well, suited to smaller vineyard weddings with in-house catering.	concierge@wentevineyards.com	925-456-2425	https://murrietaswell.com/weddings/
Julia Morgan Ballroom	465 California St	San Francisco	California			Ballroom / Hotel	Indoor	320		A Beaux-Arts ballroom on the 15th floor of the landmark Merchants Exchange building in the Financial District, with 15,500 square feet of space and its own kitchen.	info@juliamorganballroom.com	415-591-1833	https://www.juliamorganballroom.com/
The City Club of San Francisco	155 Sansome St	San Francisco	California			Ballroom / Hotel	Indoor			A private Art Deco club on the 10th floor of a downtown tower with city views, offering all-inclusive ceremony and reception packages catered by its own chef.		415-362-2480	https://cityclubsf.com/weddings/
Rancho Nicasio	1 Old Rancheria Rd	Nicasio	California			Barn / Rustic	Indoor & Outdoor			A roadhouse dating from 1941 in the rural centre of Marin County, with historic buildings, a restaurant and bar, a dance hall and an outdoor lawn with barbecue.			https://weddings.ranchonicasio.com/
Hiller Aviation Museum	601 Skyway Rd	San Carlos	California			Historic / Estate	Indoor		Simple	An aviation museum on the Peninsula where receptions are held among its aircraft displays in the atrium, gallery and Hall of Fame room.	lanie@hiller.org	650-654-0200	https://www.hiller.org/private-events/
Fairmont San Francisco	950 Mason St	San Francisco	California			Ballroom / Hotel	Indoor	970	Luxury	A landmark hotel atop Nob Hill at the cable car crossing, with a grand ballroom, the Venetian Room and a penthouse suite among its 23 event spaces.	rfp-saf@fairmont.com	415-772-5000	https://www.fairmont.com/san-francisco/weddings/
Palace Hotel	2 New Montgomery St	San Francisco	California			Ballroom / Hotel	Indoor			A historic downtown hotel with chandeliered ballrooms, the Sunset Court and French Parlor among 24 event rooms, and guest rooms on site.		415-512-1111	https://www.sfpalace.com/weddings
Dunsmuir Hellman Historic Estate	2960 Peralta Oaks Ct	Oakland	California			Historic / Estate	Indoor & Outdoor			A city-owned 37-room Neoclassical Revival mansion from 1899 on 50 acres of landscaped grounds in the Oakland foothills.			https://www.oaklandca.gov/Community/Parks-Facilities/Rent-a-Facility-or-Park/Dunsmuir-Hellman-Historic-Estate
Slide Ranch	2025 Shoreline Hwy	Muir Beach	California			Beach / Waterfront	Indoor & Outdoor	150		A nonprofit teaching farm on the coastal bluffs of Muir Beach with Pacific views from a yurt terrace, a meadow and a farm-to-table centre, where couples bring their own caterer.	admin@slideranch.org	415-381-6155	https://www.slideranch.org/weddingvenues
Golden Gate Club	135 Fisher Loop	San Francisco	California			Historic / Estate	Indoor & Outdoor	300		A 1949 Mission-style former enlisted men's club on the Presidio's Main Post, with a courtyard, balcony and tall windows looking out to the Golden Gate Bridge, bay and Alcatraz.			https://www.presidio.gov/venues/golden-gate-club
China Cabin	52 Beach Rd	Belvedere	California			Beach / Waterfront	Indoor & Outdoor	40	Simple	The gilded 1866 saloon of a sidewheel steamship, now standing on pilings in Belvedere Cove with decks on three sides facing the yacht harbour and city skyline, for small weddings.	landmarksrentals@gmail.com	415-272-3816	https://landmarkssociety.com/rentals/china-cabin/
Old St. Hilary's	201 Esperanza St	Tiburon	California			Historic / Estate	Indoor	115	Simple	An 1888 Carpenter Gothic chapel of redwood and fir on a hilltop wildflower preserve above Belvedere, used for ceremonies only, with views toward Angel Island and the Golden Gate.	landmarksrentals@gmail.com	415-272-3816	https://landmarkssociety.com/rentals/st-hilarys/`,
  },
  {
    name: "San Diego",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
San Diego Botanic Garden	300 Quail Gardens Dr	Encinitas	California			Garden / Outdoor	Outdoor	200	Classic	Thirty-seven acres of themed gardens and trails with a walled garden, gazebo lawn and waterfall deck for ceremonies, and evening receptions after the public leaves.		(760) 436-3036	https://sdbg.org/wedding-private-events/
Darlington House	7441 Olivetas Ave	La Jolla	California			Historic / Estate	Indoor & Outdoor			Historic La Jolla house run by a local nonprofit, pairing period architectural detail indoors with a garden for ceremonies a few blocks from the coast.	events@darlingtonhouse.org	(858) 454-7625	https://www.darlingtonhouse.org/
Grand Tradition Estate & Gardens	220 Grand Tradition Way	Fallbrook	California			Garden / Outdoor	Indoor & Outdoor			More than 30 acres of gardens and waterfalls in north county with two separate wedding sites, Beverly Mansion and Arbor Terrace, each with its own ceremony and reception areas.	info@grandtradition.com	(760) 728-6466	https://www.grandtradition.com/
Orfila Vineyards & Winery	13455 San Pasqual Rd	Escondido	California			Restaurant / Vineyard	Outdoor	120		Working winery in the San Pasqual Valley with a lawn among the vines and mountain views for ceremonies and receptions.		(760) 738-6500	https://www.orfila.com/weddings
The Prado at Balboa Park	1549 El Prado	San Diego	California			Historic / Estate	Indoor & Outdoor			Restaurant and event spaces in Balboa Park's House of Hospitality, built for the 1915 Panama-California Exposition with Spanish and Moorish detailing and courtyards.		(619) 557-9441	https://www.balboaparkweddings.com/
Maritime Museum of San Diego	1492 N Harbor Dr	San Diego	California			Beach / Waterfront	Indoor & Outdoor			Weddings aboard historic ships on the downtown bay, including the 1898 Berkeley ferryboat with open decks and stained glass and the 1863 Star of India.			https://sdmaritime.org/event-venues/wedding-receptions/
Milagro Winery	18750 Littlepage Rd	Ramona	California			Restaurant / Vineyard	Indoor & Outdoor	200		Ramona Valley winery holding one event a day across a granite wine cave, an old crush house, a lakeside spot and a sunset ceremony lawn.	hello@cseventservices.com	(760) 313-5539	https://csevenues.com/milagro-winery/
Rancho Guejito Weddings	17224 San Pasqual Valley Rd	Escondido	California			Barn / Rustic	Indoor & Outdoor	300		Blank-canvas site on a 23,000-acre working cattle ranch dating to 1845, with an 1880s farmhouse, vineyard ceremony area, lawns and meadows among orchards.	hello@ranchoguejitoweddings.com	(760) 800-3164	https://www.ranchoguejitoweddings.com/
Estancia La Jolla Hotel & Spa	9700 N Torrey Pines Rd	La Jolla	California			Ballroom / Hotel	Indoor & Outdoor			Hacienda-style resort on 10 acres of gardens near Torrey Pines with 210 guest rooms and both garden and indoor wedding spaces.		(858) 964-6560	https://www.estancialajolla.com/weddings
Sacred Mountain Ranch	2323 Farmer Rd	Julian	California			Barn / Rustic	Indoor & Outdoor	68		Eighty-acre private mountaintop ranch near Julian with three event spaces, a restored historic lodge and six guest homes, so guests stay on site for the weekend.		(760) 765-1800	https://www.sacredmountainjulian.com/
Forgotten Barrel Winery	1120 W 15th Ave	Escondido	California			Restaurant / Vineyard	Indoor & Outdoor			Urban winery and tasting room in Escondido that runs its own wedding programme on site.			https://www.forgottenbarrelweddings.com/
The Crossings at Carlsbad	5800 The Crossings Dr	Carlsbad	California			Ballroom / Hotel	Indoor & Outdoor	225		Golf course clubhouse with a ceremony lawn looking out to the Pacific, a ballroom and smaller fireside rooms, with in-house catering and coordination.	catering@thecrossingsatcarlsbad.com	(760) 444-1800	https://www.thecrossingsatcarlsbad.com/weddings`,
  },
  {
    name: "Sacramento",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Timber Creek Ballroom	7050 Del Webb Blvd	Roseville	California			Ballroom / Hotel	Indoor & Outdoor			Ballroom attached to a lodge and golf club in Roseville, with a rose garden used for outdoor ceremonies.	jenny@timbercreekballroom.com	916-774-3870	https://timbercreekballroom.com/
Old St. Mary's Chapel		Rocklin	California			Historic / Estate	Indoor & Outdoor			Catholic church built in 1883, later moved down Front Street and restored as a non-denominational wedding chapel with a landscaped fountain patio beside the Amtrak station.			https://oldstmaryschapel.com/
Union Brick	240 Conference Center Dr	Roseville	California			Ballroom / Hotel	Indoor & Outdoor	300		Event centre in Roseville with a hardwood-floored ballroom, stone cocktail patios and a ceremony arbor backed by six waterfalls.		866-966-3009	https://www.wedgewoodweddings.com/venues/union-brick
The Maples	40162 Best Ranch Rd	Woodland	California			Barn / Rustic	Indoor & Outdoor	300		Private country estate outside Woodland centred on a ranch house, with indoor and outdoor areas for ceremonies and receptions.	events@themapleswoodland.com	530-379-3681	https://www.themapleswoodland.com/
The Firehouse Restaurant	1112 Second Street	Sacramento	California			Restaurant / Vineyard	Indoor			Long-running restaurant in Old Sacramento that takes private events in its dining rooms.	events@firehouseoldsac.com	916-442-4772	https://www.firehouseoldsac.com/
Serrano Country Club	5005 Serrano Parkway	El Dorado Hills	California			Ballroom / Hotel	Indoor & Outdoor			Private club in El Dorado Hills with a 34,000 square foot clubhouse, terraces and an 18-hole course, with views toward the Sierra Nevada and Folsom Lake.		(916) 933-5005	https://serranocountryclub.org/
Kimpton Sawyer Hotel	500 J Street	Sacramento	California			Ballroom / Hotel	Indoor & Outdoor			Downtown Sacramento hotel beside Golden 1 Center that offers event rooms and an outdoor event space for weddings.		(916) 545-7100	https://www.sawyerhotel.com/
Delta King	1000 Front Street	Sacramento	California			Beach / Waterfront	Indoor & Outdoor			Paddlewheel riverboat built in 1927 and moored on the Old Sacramento waterfront, now a hotel with riverfront decks and private event rooms.	inquiry@deltaking.com	916-444-5464	https://www.deltaking.com/
The Flower Farm	4150 Auburn Folsom Rd	Loomis	California			Barn / Rustic	Indoor & Outdoor	200		A ten-acre citrus-orchard property with an event barn, a farmhouse for the wedding party, garden patios and a boulder lawn, plus seven guest rooms on site.	info@flowerfarminn.com	916-652-4200	https://www.flowerfarminn.com/wedding-and-events
Catta Verdera Country Club	1111 Catta Verdera	Lincoln	California			Ballroom / Hotel	Indoor & Outdoor			A golf club in a Spanish-style setting with banquet halls and outdoor ceremony spaces, offering three set wedding packages.	events@cattaverdera.com	(916) 645-7200	https://www.cattaverdera.com/weddings-banquets/
Newcastle Gardens and Red Horse Barn	950 Taylor Rd	Newcastle	California			Historic / Estate	Indoor & Outdoor	150		A 1906 estate with landscaped gardens, granite boulders, a waterfall and koi pond, an old oak for ceremonies and a rustic barn for receptions.	matt@newcastlebnb.com	916-417-9765	https://newcastlebnb.com/venue/
Gold Hill Gardens	2325 Gold Hill Rd	Newcastle	California			Garden / Outdoor	Outdoor			A 38-acre foothill estate with over eleven acres of tended gardens, several ceremony spots under oaks beside a brook, tented reception areas and a five-bedroom inn.	info@goldhillgardens.com	916-663-3060	https://www.goldhillgardens.com/garden-weddings
Blue Goose Event Center	3550 Taylor Road	Loomis	California			Barn / Rustic	Indoor	375		A former fruit-packing shed from 1945, now a hall with a stage, sound and lighting and a bridal room.	bookingsatbluegooseeventcenter@gmail.com	(916) 672-6675	https://bluegooseeventcenter.com/rent-the-blue-goose/
Helwig Winery	11555 Shenandoah Road	Plymouth	California			Restaurant / Vineyard	Indoor & Outdoor			A Shenandoah Valley winery where ceremonies take place in an amphitheatre, with a wine cave for cocktails and an outdoor pavilion for the reception.	events@helwigwinery.com	(209) 245-5200	https://www.helwigwinery.com/weddings/
The Davies Family Inn at ShadowRidge Ranch	3700 Fort Jim Road	Placerville	California			Barn / Rustic	Indoor & Outdoor	200		A mid-1800s log-cabin homestead on a meadow ringed by pines and oaks, with a lodge, guest cabins, a pony barn, a carriage house and a pavilion tent.	thedaviesfamilyinn@gmail.com	530-295-1000	https://www.thedaviesfamilyinn.com/events
Lake & Wood		Placerville	California			Beach / Waterfront	Outdoor	200		An Apple Hill property with a lakeside ceremony lawn, a reception tent, fire pits and two Airstream getting-ready suites beside a 50-acre lake among pines.			https://www.thelakeandwood.com/weddings
Twin Rocks Estate Winery	6635 Cavitt Stallman Road	Granite Bay	California			Restaurant / Vineyard	Indoor & Outdoor			A vineyard estate with boulders, oak and olive groves, two ponds, a country barn and a tasting room.	info@trwinery.com	916-287-8622	https://www.trwinery.com/weddings
Blessing Hill Estate		Granite Bay	California			Restaurant / Vineyard	Outdoor			A family-run 2.5-acre private estate with vineyard views, redwood and oak trees, gardens, a ceremony site and a bridal suite.	info@blessinghillestate.com		https://blessinghillestate.com/
The Stone Barn Winery at Cosumnes River Ranch	6525 Old Sacramento Rd	Plymouth	California			Barn / Rustic	Indoor & Outdoor	150	Classic	A hand-rebuilt 1920s stone barn on a 150-acre working ranch, with an outdoor patio, indoor bar and upstairs bridal suite.			https://www.cosumnesriverranch.com/weddings
Park Victorian	195 Park Street	Auburn	California			Historic / Estate	Indoor & Outdoor			An 1874 Victorian mansion above Old Town Auburn with gardens and lawns, aimed at elopements, micro-weddings and small gatherings.	missi@parkvictorian.com		https://www.parkvictorian.com/privateevents
Stonum Vineyards	16388 North Alpine Road	Lodi	California			Restaurant / Vineyard	Indoor & Outdoor	150		A family-run winery in the Lodi appellation where couples get a full day on a property with vineyard rows, organic gardens and a tasting room.	kathy@stonumvineyards.com	(209) 224-8130	https://www.stonumvineyards.com/wedding-at-stonum/
Julietta Winery	51221 Clarksburg Road	Clarksburg	California			Restaurant / Vineyard	Indoor & Outdoor	300	Classic	A winery estate in the Delta farming town of Clarksburg with a slow waterway running through the grounds, grapevines, flower beds and lawn space that can take a tent.		(916) 270-9170	https://juliettawinery.com/weddings
Bridgewood Events	9338 Robson Road	Galt	California			Barn / Rustic	Indoor & Outdoor	175	Classic	A 17-acre farm property between vineyards and almond orchards, with a 4,320 sq ft barn, a pond crossed by an arched wooden bridge and a ceremony spot at the water's edge.	bridgewoodevents@gmail.com	(209) 701-3967	https://www.bridgewood-events.com
Scribner Bend Vineyards	9051 River Road	Sacramento	California			Restaurant / Vineyard	Indoor & Outdoor			A sixth-generation Delta farm and winery on the Sacramento River, with vineyard ceremony sites, gardens, a tented dining area and a restored 1918 barn.	info@scribnerbend.com	(916) 744-1803	https://scribnerbend.com/weddings/
The Willow Ballroom	10724 CA-160	Hood	California			Ballroom / Hotel	Indoor			A repurposed historic warehouse in the Delta with exposed brick, draped ceilings and more than twenty vintage chandeliers, laid out so ceremony, cocktails and reception can share one space.			https://www.thewillowballroom.com
Hanford Ranch Winery	13200 Loll Rd	Galt	California			Restaurant / Vineyard	Outdoor			A small vineyard winery on open Galt farmland that holds weddings in a rustic outdoor setting among the vines, with a tasting room on site.		(916) 212-5302	https://www.hanfordranchwinery.com/weddings
The Hanford Garden	128 Hanford Street	Sutter Creek	California			Garden / Outdoor	Outdoor	175		A walled garden estate at the corner of Hanford and Main in the Gold Rush town of Sutter Creek, with terraced lawns, a cocktail grove, a covered pergola and bridal and groom suites.	events@thehanfordgarden.com	(925) 640-6256	https://thehanfordgarden.com
First Dance Ranch	18877 Ponderosa Annex Road	Sutter Creek	California			Barn / Rustic	Indoor & Outdoor			A hilltop ranch in the Sierra foothills with a farmhouse, catering kitchen and bridal and groom's suites, offered as a one-day or multi-day wedding hire.	info@drdranch.com		https://firstdanceranch.com
The Ranch at Lone Oak Longhorns		Marysville	California			Barn / Rustic	Outdoor			A 13-acre private ranch in the Yuba-Sutter area, ringed by walnut orchards and home to a herd of registered Texas Longhorns, with outdoor ceremony and reception spaces.		(530) 415-0361	https://theranchatloneoak.com
Cavaignac, A Country Estate	13530 Leary Road	Walnut Grove	California			Historic / Estate	Indoor & Outdoor	250		A French-style farm estate in the Delta with a chateau-style farmhouse, a tree-lined drive, a Pinot Gris vineyard, a swimming pond with a sandy beach and wide lawns.	info@cavaignac.com		https://www.cavaignac.com/weddings
Wilton Oaks	9001 Clay Station Rd	Wilton	California			Barn / Rustic	Outdoor			A rustic farm-style property in Wilton set among mature oak trees.	wiltonoaksevents@gmail.com	(916) 420-4087	https://www.wiltonoaks.com
Appellation Lodi - Wine & Roses Resort and Spa	2505 W. Turner Road	Lodi	California			Ballroom / Hotel	Indoor & Outdoor			A wine-country resort and spa in Lodi with botanical gardens, a wedding garden, a garden ballroom, a cellar room with patios and guest rooms on site.		(209) 334-6988	https://www.appellationhotels.com/hotels/california-lodi/weddings`,
  },
];

export default batches;
