import type { VenueBatch } from "@/lib/venue-batches";

// Colorado venue batches. Every row's State is "Colorado". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Denver venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Hudson Gardens	6115 S Santa Fe Dr	Littleton	Colorado			Garden / Outdoor	Indoor & Outdoor	175		A 30-acre garden in Littleton with a rose garden, an open-air pavilion, lawns and a small indoor inn among its ceremony and reception spaces.		303-797-8565	https://hudsongardens.org/host/
Boettcher Mansion	900 Colorow Rd	Golden	Colorado			Historic / Estate	Indoor & Outdoor	150	Classic	A stone-and-timber mansion in the forest atop Lookout Mountain, owned by Jefferson County, with a vaulted fireside room and a wooded patio.	BoettcherMansion@jeffco.us	720-497-7630	https://www.jeffco.us/1797/Weddings-Social-Events
Evergreen Lake House	29612 Upper Bear Creek Rd	Evergreen	Colorado			Beach / Waterfront	Indoor & Outdoor	200	Classic	A log lodge on the shore of Evergreen Lake with a stone-fireplace great room, a smaller octagon room and an outdoor deck for ceremonies.	rholterman@eprdco.gov	720-880-1100	https://www.evergreenrecreation.com/Lake-House-Rental
Highlands Ranch Mansion	9950 E Gateway Dr	Highlands Ranch	Colorado			Historic / Estate	Indoor & Outdoor		Classic	A historic mansion on a working ranch inside a planned 250-acre historic park, with landscaped grounds and wide open views.	hrmansionevents@highlandsranch.org	303-791-0177	https://highlandsranchmansion.com/
Moss Denver	200 N Santa Fe Dr	Denver	Colorado			Historic / Estate	Indoor	200	Classic	An industrial brick building in the Santa Fe Art District, booked whole, with a glass-ceilinged ceremony room and a chandelier hall lit by factory windows.	info@mossdenver.com	303-534-5403	https://www.mossdenver.com/
Chief Hosa Lodge	27661 Genesee Ln	Golden	Colorado			Historic / Estate	Indoor & Outdoor	100		Denver's first mountain lodge, opened in 1918 and built of local stone and timber, with fireplaces and a large patio facing the Continental Divide.	Park.Permits@denvergov.org	720-913-0700	https://denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Parks-Recreation/Park-Permits/Event-Facilities/Chief-Hosa-Lodge
`,
  },
  {
    name: "Colorado Springs, Front Range and mountain venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Pikes Peak Ranch	9 County Road 78	Woodland Park	Colorado			Barn / Rustic	Indoor & Outdoor	145	Simple	A 160-acre mountain ranch with hilltop and patio ceremony sites, an indoor reception hall and on-site cabin lodging, with views of Pikes Peak.		(719) 687-9777	https://pikespeakranch.com/weddings/
Red Rocks Barn	2700 Robinson St	Colorado Springs	Colorado			Barn / Rustic	Indoor & Outdoor	150		A rustic barn near Manitou Springs and Old Colorado City, with indoor and outdoor ceremony spaces against red rock and mountain scenery.	redrocksbarn@gmail.com	(719) 360-1555	https://redrocksbarn.com
Tava House	120 S Center St	Woodland Park	Colorado			Restaurant / Vineyard	Indoor			A fine-dining restaurant in Woodland Park whose River Room event space has a fireplace, a waterfall feature and views toward Pikes Peak.		719-428-5352	https://www.tavahouse.com
Flying W Ranch	3330 Chuckwagon Rd	Colorado Springs	Colorado			Barn / Rustic	Indoor & Outdoor	900		A family-run working ranch of more than 1,400 acres in the Pikes Peak foothills, with red rock outcrops, outdoor ceremony sites and a timber-beamed lodge.	reservations@flyingw.com	(719) 598-4000	https://www.flyingw.com
Hillside Gardens	1006 S Institute St	Colorado Springs	Colorado			Garden / Outdoor	Outdoor	150	Classic	A four-acre garden venue in Colorado Springs with a pavilion, ceremony lawns, a wedding cottage and Front Range views.			https://www.hillsidecolorado.com/weddings
The Loft Music Venue	2506 West Colorado Avenue	Colorado Springs	Colorado			Historic / Estate	Indoor	150		An upstairs hall in a historic Old Colorado City building, with exposed brick, chandeliers, a live-music stage and a hidden 1920s-style bar.			https://loftmusicvenue.com/
Pinecrest Weddings & Event Center	106 Pinecrest Way	Palmer Lake	Colorado			Barn / Rustic	Indoor & Outdoor			An all-inclusive wedding property at the base of the Rockies in Palmer Lake, with indoor and outdoor spaces open year-round.	info@pinecrestweddings.com	(719) 357-8613	https://www.pinecrestweddings.com
Hotel Polaris	8989 North Gate Boulevard	Colorado Springs	Colorado			Ballroom / Hotel	Indoor & Outdoor			A hotel in north Colorado Springs with two ballrooms, a 4,000-square-foot event lawn, a spa and a pool, looking toward Pikes Peak.		719.886.1100	https://www.thehotelpolaris.com/weddings/
Flying Horse Resort & Club	1880 Weiskopf Point	Colorado Springs	Colorado			Ballroom / Hotel	Indoor & Outdoor	240		A golf resort with ballrooms, terraces with open fireplaces, a stone wine tower and on-site rooms, set against the Rocky Mountains.	Weddings@FlyingHorseClub.com	844-768-2684	https://flyinghorseresort.com/events/weddings
Spruce Mountain Ranch	14771 Spruce Mountain Road	Larkspur	Colorado			Barn / Rustic	Indoor & Outdoor			A 450-acre ranch in Larkspur split into two separate properties more than a mile apart, each with its own indoor and outdoor event spaces.	info@sprucemountainevents.com	719-484-0800	https://sprucemountainevents.com
The Lyons Farmette	4121 Ute Hwy	Lyons	Colorado			Barn / Rustic	Indoor & Outdoor	125	Classic	A four-acre farm by the St. Vrain River with a modern wood barn, a working flower farm, a vintage Airstream dressing suite and a farmhouse.			https://www.lyonsfarmette.com/farmette-weddings
The Fort	19192 Colorado Highway 8	Morrison	Colorado			Restaurant / Vineyard	Indoor & Outdoor			A restaurant in a replica 19th-century adobe fort in the Morrison foothills, with a covered patio, adobe rooms and a helipad ceremony spot on 50 acres.		303-697-4771	https://www.thefort.com/weddings-at-the-fort/
YMCA of the Rockies Estes Park Center	2515 Tunnel Road	Estes Park	Colorado			Historic / Estate	Indoor & Outdoor			A large mountain campus beside Rocky Mountain National Park with historic ceremony and reception sites, lodge rooms and a range of cabins.		970-586-3341 x1024	https://www.ymcarockies.org/groups/weddings/estes-park-center
Stone Mountain Lodge	18055 North Saint Vrain Drive	Lyons	Colorado			Barn / Rustic	Indoor & Outdoor			A foothills lodge near Lyons with motel rooms, rustic cabins and a pond, offered for exclusive use over several days for camp-style weddings.	info@stonemountainlodge.com	303.823.6091	https://www.stonemountainlodge.com
Lucky 8 Ranch Events	29625 County Road 179	Oak Creek	Colorado			Barn / Rustic	Outdoor	400		A 3,000-acre working bison ranch in Trout Creek Valley with tented ceremony and reception spaces, about 35 minutes from Steamboat Springs.	events@lucky8ranchco.com	(970) 846-3682	https://www.lucky8ranchevents.com
The Barn at Evergreen Memorial Park	26964 North Turkey Creek Road	Evergreen	Colorado			Barn / Rustic	Indoor & Outdoor			A historic barn on a 100-acre memorial park with meadows, rustic cabins, a reservoir and roaming buffalo, elk and deer.	TheBarn@evergreenmemorialpark.com	303-674-0556	https://www.thebarnatemp.com
Breckenridge Nordic Lodge	9 Grandview Drive	Breckenridge	Colorado			Barn / Rustic	Indoor & Outdoor			A 2012 lodge on Peak 8 built largely from recycled and local wood, with a moss-rock fireplace, a bar and views of Peaks 6 and 7.	bestnordicski@gmail.com	(970) 453-6855	https://www.breckenridgenordic.com/event-space-in-breckenridge/
Flying Diamond Ranch	29001 Flying Diamond Trail	Oak Creek	Colorado			Barn / Rustic	Outdoor			A ranch near Steamboat Springs with two ceremony sites, an aspen grove, flower beds and a floored wedding tent among rolling fields.		970.846.9229	https://flyingdiamondevents.com
T-Lazy-7 Ranch	3129 Maroon Creek Road	Aspen	Colorado			Barn / Rustic	Indoor & Outdoor			A ranch on Maroon Creek outside Aspen with a ceremony meadow, a tented meadow, an event lodge and a covered chuckwagon area, ringed by national forest.	events@tlazy7.com	(970) 618-7528	https://www.tlazy7.com/weddings-events/
Boulder Flower Farm	4114 Oxford Road	Longmont	Colorado			Garden / Outdoor	Indoor & Outdoor			A flower farm of more than 35 years with peony, sunflower and lavender fields and a renovated 1887 schoolhouse for day-use getting ready.		303.449.5994	https://www.boulderflowerfarm.com
Rembrandt Yard	1301 Spruce Street	Boulder	Colorado			Ballroom / Hotel	Indoor & Outdoor	150		A two-floor, 6,500-square-foot art-filled event space in Boulder with floor-to-ceiling windows, open-air balconies and Flatiron views.		(720) 260-4194	https://www.rembrandtyard.com
Flagstaff House	1138 Flagstaff Road	Boulder	Colorado			Restaurant / Vineyard	Indoor & Outdoor	150		A restaurant on Flagstaff Mountain at about 6,000 feet with a large wine collection and ceremony space overlooking peaks and meadows.		303-442-4640	https://www.flagstaffhouse.com/private-events
`,
  },
];

export default batches;
