import type { VenueBatch } from "@/lib/venue-batches";

// Connecticut venue batches. Every row's State is "Connecticut". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Hartford and central Connecticut",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Pond House Cafe	1555 Asylum Ave	West Hartford	Connecticut			Garden / Outdoor	Indoor & Outdoor	165		Restaurant inside Elizabeth Park whose Garden Room has cathedral windows and a fieldstone fireplace, with a private terrace over the pond.	cafe@pondhousecafe.com	860-231-8823	https://pondhousecafe.com/weddings/
The Mill on the River	989 Ellington Rd	South Windsor	Connecticut			Beach / Waterfront	Indoor & Outdoor			Riverside banquet house with a waterfront ceremony spot and two reception rooms, the River Room and the upstairs Rafters Room.		860-289-7929	https://www.millweddings.com
Lyman Orchards	70 Lyman Rd	Middlefield	Connecticut			Garden / Outdoor	Indoor & Outdoor	265		Family farm since 1741 spread over 1,100 acres of orchards and golf course, with a tented reception for 265 and the historic Lyman Homestead for smaller parties.	bcritchley@lymanorchards.com	860-349-6046	https://lymanorchards.com/wedding-venues/
Webb Barn at Webb-Deane-Stevens Museum	211 Main St	Wethersfield	Connecticut			Barn / Rustic	Indoor & Outdoor	135		A 19th-century barn with a slate patio on an eight-acre museum campus in Old Wethersfield, beside a Colonial Revival flower garden.	events@wdsmuseum.org	860-529-0612	https://wdsmuseum.org/rent-the-webb-barn/
Butler-McCook House & Garden	396 Main St	Hartford	Connecticut			Historic / Estate	Indoor & Outdoor	225	Simple	Downtown Hartford historic house with a restored garden and the neighbouring Amos Bull House, whose event room keeps its exposed beams and original brick.		860-247-8996	https://ctlandmarks.org/properties/butler-mccook-house-garden/
Phelps-Hatheway House & Garden	55 S Main St	Suffield	Connecticut			Historic / Estate	Indoor & Outdoor	160	Simple	Eighteenth-century house on Suffield green with Federal-period rooms, formal gardens and an 1867 barn that seats 75, tented for larger parties.		860-247-8996	https://ctlandmarks.org/properties/phelps-hatheway-house-garden/
Delamar West Hartford	1 Memorial Rd	West Hartford	Connecticut			Ballroom / Hotel	Indoor & Outdoor	250		Boutique hotel with spa whose 3,700 sq ft Mystic Ballroom has floor-to-ceiling garden windows, plus a Great Lawn and private terrace for warm months.		860-937-2500	https://www.delamar.com/hotels/delamar-west-hartford/wedding-venues-west-hartford
The Hartford Club	46 Prospect St	Hartford	Connecticut			Historic / Estate	Indoor			Private downtown club founded in 1873 that opens its clubhouse and seven-plus event rooms to non-members for weddings.	frontdesk@hartfordclub.com	860-522-1271	https://hartfordclub.com/weddings-events/
Nathan Hale Homestead	2299 South St	Coventry	Connecticut			Barn / Rustic	Indoor & Outdoor	250	Simple	The 1776 family home of Nathan Hale, a National Historic Landmark, with an 18th-century English barn and a 19th-century dairy barn; tented weddings for about 250.		860-247-8996	https://ctlandmarks.org/properties/nathan-hale-homestead/`,
  },
  {
    name: "New Haven, the shoreline and Fairfield County",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Lace Factory	161 River Street	Deep River	Connecticut			Barn / Rustic	Indoor & Outdoor			Converted lace mill in the lower Connecticut River valley, with an industrial interior and several ceremony sites on the grounds.	info@thelacefactory.com		https://www.thelacefactory.com/
Saybrook Point Resort & Marina	2 Bridge Street	Old Saybrook	Connecticut			Beach / Waterfront	Indoor & Outdoor			Resort and marina where the Connecticut River meets Long Island Sound, with a fireplace gallery, dockside lawns and guesthouses for overnight guests.		(860) 395-2000	https://www.saybrook.com/weddings
Amarante's Sea Cliff	62 Cove Street	New Haven	Connecticut			Beach / Waterfront	Indoor & Outdoor	280		Waterfront property on Morris Cove, family-owned since 1957, giving each wedding its own building, deck and lawn ceremony spot.	events@amarantes.com	203-467-2531	https://www.amarantes.com/
The Woodwinds	29 Schoolground Road	Branford	Connecticut			Ballroom / Hotel	Indoor & Outdoor			European manor-style banquet house near the Branford shoreline, with chandeliered rooms, a grand staircase and landscaped gardens for photos.	sales@thewoodwinds.com	(203) 481-6577	https://www.thewoodwinds.com/
Branford House	1084 Shennecossett Road	Groton	Connecticut			Historic / Estate	Indoor & Outdoor	200		1902 mansion on the UConn Avery Point campus overlooking Long Island Sound, where couples bring their own caterer and can tent the lawn for larger parties.	bethany.langenbach@uconn.edu	860-405-9072	https://branfordhouse.averypoint.uconn.edu/weddings-events
Anthony's Ocean View	450 Lighthouse Rd	New Haven	Connecticut			Beach / Waterfront	Indoor & Outdoor			Banquet house on the New Haven shoreline by Lighthouse Point, hosting weddings from small gatherings to large receptions with Sound views.		(203) 469-9010	https://www.anthonysoceanview.com/
Interlaken Inn	74 Interlaken Road	Lakeville	Connecticut			Garden / Outdoor	Indoor & Outdoor			Inn dating from 1892 on 30 acres between two lakes in the Litchfield Hills, with lakeside ceremonies and a garden reception tent.		1-800-222-2909	https://www.interlakeninn.com/weddings/
The Owenego	40 Linden Avenue	Branford	Connecticut			Beach / Waterfront	Indoor & Outdoor	200		Historic inn and beach club with a waterfront lawn on Long Island Sound, gardens and a beach for photos, catering in-house.		203-488-3805	https://owenego.com/weddings/
Haley Mansion	3 Williams Ave	Mystic	Connecticut			Historic / Estate	Indoor & Outdoor			1904 mansion at the Inn at Mystic on 15 acres of lawns and gardens above Mystic Harbor and Fishers Island Sound, with tent options.	sales@innatmystic.com	(860) 536-3400	https://www.haleymansionmystic.com/
Preston Ridge Vineyard	100 Miller Rd	Preston	Connecticut			Restaurant / Vineyard	Indoor & Outdoor	175		Family-owned winery on 60 acres of countryside about 15 miles inland from Long Island Sound, with several outdoor event spots among the vines.		860-383-4278	https://www.prestonridgevineyard.com/
Lounsbury House	316 Main Street	Ridgefield	Connecticut			Historic / Estate	Indoor & Outdoor			1896 landmark house on Ridgefield's Main Street that books one event a day, using its period rooms and formal gardens for ceremonies and receptions.		203-438-6962	https://lounsburyhouse.org/weddings/
Tarrywile Mansion	70 Southern Boulevard	Danbury	Connecticut			Historic / Estate	Indoor & Outdoor	150		Historic mansion in a Danbury park with a foyer for dancing, upstairs rooms for getting ready, a lawn for tents and a grape arbor.	loraine@tarrywile.com	203-744-3130	https://tarrywile.com/weddings/
The Mansion at Bald Hill	29 Plaine Hill Rd	Woodstock	Connecticut			Historic / Estate	Indoor & Outdoor	275	Simple	Historic mansion, restaurant and six-room inn in the Quiet Corner, with a timber-trussed banquet hall, garden ceremony site and patio with outdoor fireplace.	info@mansionatbaldhill.com	860-974-3456	https://www.mansionatbaldhill.com/weddings/
Keeler Tavern Museum Garden House	152 Main Street	Ridgefield	Connecticut			Garden / Outdoor	Indoor & Outdoor	80		Garden house built around 1915 by architect Cass Gilbert on a Ridgefield museum campus, opening onto a walled garden with a reflecting pool and fountain.	events@keelertavernmuseum.org	203.438.5485	https://keelertavernmuseum.org/rentals/weddings/
Delamar Greenwich Harbor	500 Steamboat Road	Greenwich	Connecticut			Ballroom / Hotel	Indoor & Outdoor			Hotel on Greenwich Harbor with a ballroom, a harbour terrace, marina access for guests arriving by boat and an on-site French restaurant.		203.661.9800	https://www.delamar.com/hotels/delamar-greenwich-harbor/greenwich-wedding-venue
Delamar Southport	275 Old Post Road	Southport	Connecticut			Ballroom / Hotel	Indoor & Outdoor	150		Boutique hotel with 46 rooms in Southport village, hosting weddings of up to 150 across its event rooms and an outdoor plaza.		203.259.2800	https://www.delamar.com/hotels/delamar-southport/southport-wedding-venues
Stone Acres Farm	393 North Main Street	Stonington	Connecticut			Historic / Estate	Indoor & Outdoor			Historic manor with seasonal gardens and sweeping lawns in Stonington, paired with a food programme run with visiting chefs.			https://www.stoneacresfarm.com/weddings-events
The VUE	310 West Shepard Avenue	Hamden	Connecticut			Ballroom / Hotel	Indoor & Outdoor			Ballroom venue on a Hamden golf course, ringed by a veranda and set among rolling hills, with indoor and outdoor ceremony options.		203-281-0673	https://www.thevuect.com/
Cascade Fine Catering	480 Sherman Ave	Hamden	Connecticut			Ballroom / Hotel	Indoor			Hamden banquet house with a chandeliered ballroom and a separate, more rustic Garden Room, catering every event in-house.	info@cascade-banquets.com	203-907-0595	https://www.cascade-banquets.com/
Bill Miller's Castle	834 E Main St	Branford	Connecticut			Historic / Estate	Indoor & Outdoor			Castle-style building in Branford with fireplaces and antique decor, plus a barn-style room and both indoor and outdoor ceremony spots.	info@BillMillersCastle.com	(203) 488-4583	https://www.billmillerscastle.com/`,
  },
  {
    name: "Connecticut: river valley, Litchfield and Fairfield County",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Saint Clements Castle & Marina	1931 Portland-Cobalt Rd	Portland	Connecticut			Historic / Estate	Indoor & Outdoor			Stone castle above the Connecticut River in Portland, with ballrooms in the castle and a separate waterfront ballroom at its marina.		860-342-0593	https://www.saintclementscastle.com/weddings/
The Waters Edge at Giovanni's	2748 Boston Post Rd	Darien	Connecticut			Beach / Waterfront	Indoor & Outdoor	450		Family-owned since 1987, a Long Island Sound banquet house in Darien with four event suites, the largest seating up to 450.	sales@watersedgeatgiovannis.com	203-325-9979	https://www.watersedgeatgiovannis.com/weddings/
The Litchfield Inn	432 Bantam Rd	Litchfield	Connecticut			Ballroom / Hotel	Indoor & Outdoor	150		Family-run colonial-style inn on ten acres in the Litchfield Hills, with a garden-view ballroom, tented lawns and 32 guest rooms.	sales@litchfieldinnct.com	860-567-4503	https://litchfieldinnct.com/weddings/
Old Lyme Inn	85 Lyme St	Old Lyme	Connecticut			Historic / Estate	Indoor & Outdoor			Thirteen-room inn in the Old Lyme arts district near the shoreline, hosting weddings since the 1970s, with dining rooms and a jazz club.	guestservices@oldlymeinn.com	860-434-2600	https://www.oldlymeinn.com/1/`,
  },
  {
    name: "Mystic, the lower river valley and eastern Connecticut",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Lake of Isles	1 Clubhouse Dr	North Stonington	Connecticut			Garden / Outdoor	Indoor & Outdoor	250		Golf club in 900 wooded acres beside Foxwoods, with lakeside ceremonies at sunset and a clubhouse room for plated dinners.	info@lakeofislesweddings.com	888-475-3746	https://lakeofislesweddings.com/
Foxwoods Resort Casino	350 Trolley Line Blvd	Mashantucket	Connecticut			Ballroom / Hotel	Indoor			Tribal resort casino with in-house wedding planners, several hotels, spas and restaurants, so the whole weekend stays under one roof.		1-800-369-9663	https://foxwoods.com/weddings
Stonington Vineyards	523 Taugwonk Rd	Stonington	Connecticut			Restaurant / Vineyard	Indoor & Outdoor	50		Family vineyard in the Stonington hills whose tasting room, patios and lawns host small evening weddings after public hours.	events@stoningtonvineyards.com	860-535-1222	https://stoningtonvineyards.com/private-events/
Florence Griswold Museum	96 Lyme St	Old Lyme	Connecticut			Historic / Estate	Indoor & Outdoor	150		Home of the Old Lyme Impressionist art colony on the Lieutenant River, with a tented garden terrace and the Colonial Revival Marshfield house.	Carla@FloGris.org	860-434-5542	https://flogris.org/host-an-event/
Lyman Allyn Art Museum	625 Williams St	New London	Connecticut			Historic / Estate	Indoor & Outdoor	60		Art museum opened in 1932 on a 12-acre park of lawns and sculpture, renting its library and lower-level hall for small ceremonies and dinners.		860-443-2545	https://www.lymanallyn.org/event-rental/
Chamard Vineyards	115 Cow Hill Rd	Clinton	Connecticut			Restaurant / Vineyard	Indoor & Outdoor	70		Shoreline winery on 20 acres of vines edged by stone walls, with a lofty rustic room and patio for intimate receptions.	carianne@chamard.com		https://www.chamard.com/copy-of-events
Eugene O'Neill Theater Center	305 Great Neck Rd	Waterford	Connecticut			Historic / Estate	Indoor & Outdoor	300	Simple	Theatre campus of 19th-century mansions, farmhouses and barns on a lawn that runs down to Long Island Sound, with bridal suites on site.	theaterlives@theoneill.org	860-443-5378	https://www.theoneill.org/rentals
Ocean Beach Park	98 Neptune Ave	New London	Connecticut			Beach / Waterfront	Indoor & Outdoor	500		City beach park on Long Island Sound with an ocean-view ballroom, a smaller balcony room and an open-sided pavilion.		860-447-3031	https://www.ocean-beach-park.com/private-events/
Essex Steam Train & Riverboat	1 Railroad Ave	Essex	Connecticut			Historic / Estate	Indoor & Outdoor			Heritage steam railway and riverboat on the lower Connecticut River that can be chartered for ceremonies and receptions.		860-767-0103	https://essexsteamtrain.com/weddings-events/
The Copper Beech Inn	46 Main St	Ivoryton	Connecticut			Historic / Estate	Indoor & Outdoor			Country inn in Ivoryton village with gardens, a cedar grove and fireplace dining rooms that can be combined for a reception.		860-767-0330	https://www.copperbeechinn.com/weddings.html
White Hart Inn	15 Under Mountain Rd	Salisbury	Connecticut			Historic / Estate	Indoor			Inn and restaurant on Salisbury's village green in the Litchfield Hills, renting its common rooms singly or together for weddings.		860-435-0030	https://www.whitehartinn.com/private-events/
Heritage Hotel	522 Heritage Rd	Southbury	Connecticut			Ballroom / Hotel	Indoor & Outdoor			Southbury golf, spa and conference hotel with landscaped grounds for portraits and room blocks for the whole wedding weekend.	sales@heritagesouthbury.com	203-267-2622	https://www.heritagesouthbury.com/weddings
The Salem Herbfarm	320 Hartford Rd	Salem	Connecticut			Barn / Rustic	Indoor & Outdoor			Herb farm with lawns and gardens for the ceremony and a rustic barn from 1867 for dinner and dancing.	herbfarmweddingplanning@gmail.com	717-368-3261	https://www.salemherbfarm.com/
Pachaug Cottages	1 Cottage Rd	Griswold	Connecticut			Beach / Waterfront	Outdoor			Family lakefront campground with a 40 by 60 ft timber-frame pavilion on the water and seasonal cottages for guests.	info@pachaugcottages.com	860-800-2242	https://pachaugcottages.com/pages/weddings-events
Fox Hopyard Golf Club	1 Fox Hopyard Rd	East Haddam	Connecticut			Garden / Outdoor	Indoor & Outdoor			Golf club whose On the Rocks restaurant sits on a rock ledge with a wraparound porch and a ceremony pavilion over the course.	mglanert@golfthefox.com	860-434-6644	https://www.foxhopyard.com/weddings/
Lyme Art Association	90 Lyme St	Old Lyme	Connecticut			Historic / Estate	Indoor	120	Simple	Historic skylit gallery building of an artists' society founded in Old Lyme, rented in the evenings for ceremonies and small receptions.	sara@lymeartassociation.org	860-434-7802	https://lymeartassociation.org/gallery-rental-2/
Whaler's Inn	20 E Main St	Mystic	Connecticut			Ballroom / Hotel	Indoor			Boutique hotel in downtown Mystic by the drawbridge, with a library, penthouse and restaurant rooms for wedding-weekend dinners and parties.		860-536-1506	https://whalersinnmystic.com/mystic-private-event-venue/
Willow Hill	459 Wolf Den Rd	Brooklyn	Connecticut			Barn / Rustic	Indoor & Outdoor	225		Private 100-acre estate in the Quiet Corner booked for one wedding a weekend, with a barn, tent field, forest garden and rooms for 22.	hello@eventsatwillowhill.com	860-245-9889	https://eventsatwillowhill.com/`,
  },
  {
    name: "Connecticut: Litchfield Hills, Hartford, shoreline, Fairfield County and eastern towns",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Wood Acres Farm	68 Griffin Road	Terryville	Connecticut			Barn / Rustic	Indoor & Outdoor		Classic	A barn and garden venue at the foot of the Litchfield Hills with a wraparound porch, courtyard fire pit and horse-drawn carriage rides.	celebrate@woodacresfarm.com	860-801-2415	https://www.woodacresfarm.com
Wyndcrest Estate	68 Kasson Road	Bethlehem	Connecticut			Barn / Rustic	Indoor & Outdoor	250		A hilltop farm property with a rustic chapel-barn, gazebo, lawns and two guest houses that sleep up to 32.	info@wyndcrestestate.com	(203) 725-6877	https://www.wyndcrestestatevenue.com
19Main	19 Main Street	New Milford	Connecticut			Historic / Estate	Indoor	130		A restored downtown New Milford building with two adjoining rooms and one event booked per day.	kylie@villagegreeneventsct.com	(860) 717-4077	https://19main.com
The Inn at Mount Pleasant		Torrington	Connecticut			Barn / Rustic	Indoor & Outdoor	150		A post-and-beam barn beside a bed and breakfast, with Litchfield Hills views and exclusive use of the property.		860-459-7785	https://theinnatmountpleasant.com
Bond Ballroom	338 Asylum Street	Hartford	Connecticut			Ballroom / Hotel	Indoor	350		A penthouse-floor ballroom in downtown Hartford with a 20 by 40 foot dance floor and two smaller cocktail rooms.	info@bondballroom.com	860-519-5572	https://bondballroom.com
Farmington Gardens	999 Farmington Avenue	Farmington	Connecticut			Garden / Outdoor	Indoor & Outdoor	342		A former garden center turned event venue with a 5,000 square foot dining room, a greenhouse bar, and about an acre of lawn with a pergola and water feature.	info@farmingtongardensct.com	860-678-1353	https://farmingtongardensct.com
Farmington Polo Club	162 Town Farm Road	Farmington	Connecticut			Garden / Outdoor	Indoor & Outdoor			A polo-field clubhouse in the Farmington Valley with a dining room, covered patio and a gazebo ceremony spot.	events@farmingtonpolo.com	860-677-7341	https://www.farmingtonpoloclub.com
The Simsbury Inn	397 Hopmeadow Street	Simsbury	Connecticut			Ballroom / Hotel	Indoor & Outdoor	200		A New England inn with a flower gazebo, a tented lawn and a ballroom, plus guest rooms on site.	sales@simsburyinn.com		https://www.simsburyinn.com
The Hinterland	308 Arch Rd	Avon	Connecticut			Barn / Rustic	Indoor & Outdoor	100	Simple	A small restored barn on five acres in Avon that runs set packages for gatherings from 15 to 100 guests.			https://www.thehinterlandct.com
Rosedale Farms & Vineyards	25 East Weatogue Street	Simsbury	Connecticut			Restaurant / Vineyard	Outdoor	250	Classic	A working Simsbury farm and vineyard hosting outdoor weddings from June through October.	rosedalef@aol.com	860-651-3926	https://www.rosedale1920.com
Hilltop Farm	1616 Mapleton Avenue	Suffield	Connecticut			Barn / Rustic	Indoor & Outdoor			A historic Suffield farm whose open-rafter main barn and silos sit beside fields that can hold tents for 300 or more.	info@fofah.org	(860) 375-3151	https://www.fofah.org
Dudley Farm Munger Barn	2351 Durham Road	Guilford	Connecticut			Barn / Rustic	Indoor	85		An 1890 barn moved onto a historic Guilford farm museum, rented for weddings from May to October.		203-457-9768	https://dudleyfarm.com
The Fields at Van Wilgen's	51 Valley Rd	North Branford	Connecticut			Garden / Outdoor	Outdoor	200		A garden center's field and 8-acre pond where guests ride an antique tractor and wagon to the ceremony.	kate.vanwilgen@gmail.com		https://www.thefieldsatvw.com
Pine Orchard Union Chapel	25 Chapel Drive	Branford	Connecticut			Historic / Estate	Indoor			A Queen Anne-style chapel built in 1897 in the Pine Orchard shoreline neighborhood and restored in 2022.			https://www.pineorchardchapel.com
The Hops Company	77 Sodom Lane	Derby	Connecticut			Garden / Outdoor	Indoor & Outdoor	500		A Derby venue with an outdoor garden and an indoor lodge for parties of 50 to 500 or more.		203-734-1616	https://www.thehopscompany.com
The Whittemore	1365 Whittemore Road	Middlebury	Connecticut			Ballroom / Hotel	Indoor	250		A Middlebury event house with a 250-guest main room, a garden room and a bridal suite.		(203) 518-4000	https://www.thewhittemore.net
Aqua Turf Club	556 Mulberry Street	Plantsville	Connecticut			Ballroom / Hotel	Indoor			A Southington-area banquet club with several reception rooms overlooking a pond and waterfall.	info@aquaturfclub.com	(860) 621-9335	https://www.aquaturfclub.com
Roger Sherman Inn	195 Oenoke Ridge	New Canaan	Connecticut			Historic / Estate	Indoor & Outdoor	200		A New Canaan inn and restaurant with a garden room, terrace and a string-lit lawn pergola.	events@rogershermanrestaurant.com	(203) 966-4541	https://www.rogershermaninn.com
The Knowlton	305 Knowlton St	Bridgeport	Connecticut			Beach / Waterfront	Indoor & Outdoor			A riverfront boathouse and galleries on the Pequonnock with a deck and mural park for ceremonies.			https://theknowlton.com
Bluebird Farm	211 Jared Sparks Rd	Willington	Connecticut			Barn / Rustic	Indoor & Outdoor	150		A working farm with a renovated 1918 barn and on-site lodging including a treehouse.	weddings@bluebirdfarmct.com	(860) 788-5885	https://bluebirdfarmct.com
The Barn at Maple Lane Farms	57 NW Corner Rd	Preston	Connecticut			Barn / Rustic	Indoor & Outdoor			A renovated post-and-beam barn on a 225-acre Preston farm with a colonial house to rent for lodging.		(860) 889-3766	https://maplelane.com
Kingdom of the Hawk	113 Pendleton Hill Road	North Stonington	Connecticut			Restaurant / Vineyard	Indoor & Outdoor			A North Stonington vineyard with a barn-style event building for weddings.	econnery@kingdomct.com	860-328-5331	https://www.kingdomofthehawk.com
Priam Vineyards	11 Shailor Hill Rd	Colchester	Connecticut			Restaurant / Vineyard	Indoor & Outdoor	500		A Colchester winery with a patio overlooking the vineyard and tented sites for events of 30 to 500.		(860) 267-8520	https://www.priam-vineyards.com
The Inn at Woodstock Hill	94 Plaine Hill Road	Woodstock	Connecticut			Historic / Estate	Indoor & Outdoor	150		A hilltop inn on sixteen acres with a banquet room, canopied terrace, gazebo and 21 guest rooms.	innwood@gmail.com	(860) 928-0528	https://www.woodstockhill.com
Gwyn Careg Inn	68 Wolf Den Road	Pomfret Center	Connecticut			Historic / Estate	Indoor & Outdoor			A historic Pomfret Center inn that gives a wedding party exclusive use of the grounds.		860-928-5018	https://www.gwyncareginn.com
Green Haven	44 Bradley Road	Pomfret Center	Connecticut			Garden / Outdoor	Outdoor	50	Simple	A small flower-filled garden in northeast Connecticut for ceremonies and receptions of up to 50.	greenhavenct@gmail.com	860.428.0968	https://www.greenhavenconnecticut.com
Nuzzo's Farm	736 East Main St	Branford	Connecticut			Barn / Rustic	Indoor & Outdoor			A Branford farm with repurposed historic barns and a pondside ceremony spot.		(203) 996-7238	https://www.nuzzosfarm.com
Westbrook Inn	976 Boston Post Rd	Westbrook	Connecticut			Ballroom / Hotel	Indoor & Outdoor	40		A restored shoreline inn with ten rooms that runs all-inclusive weddings for up to 40 guests.	info@westbrookinn.com	860-399-4777	https://www.westbrookinn.com
Guilford Yacht Club	379 Whitfield Street	Guilford	Connecticut			Beach / Waterfront	Indoor & Outdoor			A West River yacht club in Guilford that rents its lawn and reception hall to non-members.	eventsmanager@gyc.com	(203) 453-0070	https://gyc.com`,
  },
];

export default batches;
