import type { VenueBatch } from "@/lib/venue-batches";

// Delaware venue batches. Every row's State is "Delaware". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Delaware venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Chase Center on the Riverfront	815 Justison Street	Wilmington	Delaware			Ballroom / Hotel	Indoor	750		Large event centre on the Christina River with two ballrooms and a connected Westin hotel for guests.		302-425-3929	https://centerontheriverfront.com/special-events/
DuPont Country Club	1001 Rockland Rd	Wilmington	Delaware			Ballroom / Hotel	Indoor			Brandywine Valley country club with the DuPont and Christiana ballrooms plus the separate Brantwyn Estate mansion.		(302) 654-4435	https://www.dupontcountryclub.com/weddings-events
University and Whist Club	805 North Broom Street	Wilmington	Delaware			Historic / Estate	Indoor			Private club in the historic Tilton Mansion and Carriage House that books one all-inclusive wedding per day.		(302) 658-5125	https://www.universityandwhistclub.com/Weddings
Hotel du Pont	42 W. 11th Street	Wilmington	Delaware			Ballroom / Hotel	Indoor	275	Luxury	Downtown hotel opened in 1913 whose gilded French neoclassical Gold Ballroom hosts receptions with rooms upstairs.	reservations@hoteldupont.com	302.594.3100	https://www.hoteldupont.com/weddings-events/weddings
Bellevue Hall	901 Philadelphia Pike	Wilmington	Delaware			Historic / Estate	Indoor & Outdoor	250		1855 former du Pont mansion inside Bellevue State Park with lawn ceremonies, gardens and tented or indoor receptions.		302-305-2657	https://jamhospitality.com/venues/bellevue-hall/
The Barn at Cauffiel Estate	1016 Philadelphia Pike	Wilmington	Delaware			Barn / Rustic	Indoor & Outdoor	150		1928 Colonial Revival estate in Bellevue State Park with a restored bank barn and Delaware River views.		302-305-2657	https://jamhospitality.com/venues/the-barn-at-cauffiel/
The Carriage House at Rockwood Park	4671 Washington Street Extension	Wilmington	Delaware			Garden / Outdoor	Indoor & Outdoor			Carriage house on an 1854 country estate set within a six-acre garden with plantings dating to the 1850s.		302-472-2433	https://rockwoodcarriagehouse.com/weddings/
The Farmhouse	5600 Old Capitol Trail	Wilmington	Delaware			Historic / Estate	Indoor & Outdoor	190		Family-run historic estate on four acres with a willow-shaded ceremony site, terrace hall and wrap-around deck.	info@thefarmhousede.com	302-999-8477	https://www.thefarmhousede.com/weddings
Deerfield Golf Club	507 Thompson Station Road	Newark	Delaware			Ballroom / Hotel	Indoor & Outdoor	500		Public golf club on 145 state-owned acres by White Clay Creek State Park, with a ballroom and outdoor terrace.		302-368-6640	https://www.deerfieldgolfclub.com/weddings/
King Cole Farm	1730 Bayside Drive	Dover	Delaware			Barn / Rustic	Indoor & Outdoor	300	Classic	Dover farm with a climate-controlled pole barn, gazebo, garden room and a main house for weekend stays.		302-405-5595	https://www.kingcolefarm.com/
Loblolly Acres	3893 Turkey Point Road	Viola	Delaware			Barn / Rustic	Indoor & Outdoor	150	Classic	Kent County farm with the chandelier-lit Magnolia Barn, an outdoor stage and a pavilion for larger groups.	loblollyacresevents@gmail.com	302-632-6797	https://www.loblollyacres.com/bookings
Cobalt Manor	47 East Commerce St.	Smyrna	Delaware			Historic / Estate	Indoor & Outdoor	100		Restored 1868 Italianate mansion and cafe in Smyrna with a Victorian patio for small weddings.	bookings@cobaltmanor.com	1-888-272-9812	https://www.cobaltmanor.com/cobalt-weddings
Nassau Valley Vineyards	32165 Winery Way	Lewes	Delaware			Restaurant / Vineyard	Indoor & Outdoor	350	Simple	Lewes winery with an 8,400 sq ft event hall, patios, lawns and a grove of old sycamore trees.	mail@nassauvalley.com	302.645.9463	https://www.nassauvalley.com/facility-rental/
Salero on the Beach	511 North Boardwalk	Rehoboth Beach	Delaware			Beach / Waterfront	Indoor & Outdoor	150		Eighth-floor restaurant in the Henlopen Hotel on the boardwalk, looking out over the ocean, with beach ceremony setups.	dawnhorton@saleroonthebeach.com	(302) 841-2229	https://saleroonthebeach.com/events/weddings/
Atlantic Sands Hotel & Conference Center	1 Baltimore Avenue	Rehoboth Beach	Delaware			Beach / Waterfront	Indoor			Oceanfront boardwalk hotel with conference and banquet space for wedding receptions and rooms for guests.		(302) 227-2511	https://www.atlanticsandshotel.com/
Baywood Weddings	32267 Clubhouse Way	Millsboro	Delaware			Ballroom / Hotel	Indoor & Outdoor	300		Golf clubhouse near Rehoboth with a remodelled 260-guest ballroom, patio, library and a 300-guest tented lawn.	meredith@baywoodclubhouse.com		https://baywoodweddings.com/
Brittingham Farms Lavender & Lambs	22518 Phillips Hill Road	Millsboro	Delaware			Barn / Rustic	Indoor & Outdoor	150	Classic	Fourth-generation family farm founded in 1930 with lavender fields, sheep and a 150-seat wedding barn.	laura@brittinghamfarms.com		https://www.brittinghamfarms.com/weddings`,
  },
  {
    name: "Delaware venues: Wilmington, Brandywine and Delaware Beaches",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Hagley Museum and Library	200 Hagley Creek Road	Wilmington	Delaware			Historic / Estate	Indoor & Outdoor	200		Du Pont powder-works estate on 235 acres of gardens and meadows with three event facilities.	mgarrido@hagley.org	302-658-2400	https://www.hagley.org/weddings
Winterthur Museum, Garden & Library	5105 Kennett Pike	Winterthur	Delaware			Historic / Estate	Indoor & Outdoor			Henry Francis du Pont's country estate with a 60-acre garden, reflecting-pool ceremonies and pavilion receptions.	ccater@winterthur.org		https://winterthurwedding.com/
Delaware Art Museum	2301 Kentmere Parkway	Wilmington	Delaware			Historic / Estate	Indoor & Outdoor	150	Simple	Art museum with galleries, a sculpture garden and outdoor ceremony space; venue rentals start at a $2,000 minimum.	venuerentals@delart.org	302-571-9590	https://www.delart.org/weddings/
The Farm at Coochs Bridge	1771 Old Coochs Bridge Rd	Newark	Delaware			Barn / Rustic	Indoor & Outdoor	170	Simple	Restored farm in the Coochs Bridge Historic District with a barn, farmhouse and pavilion; packages start at $3,000.		302-402-5060	https://thefarmatcoochsbridge.com/
Thousand Acre Farm	260 S. Reedy Point Rd	Middletown	Delaware			Barn / Rustic	Indoor & Outdoor			Waterfront farm with two barns, a covered patio and a deck facing the sunset.		302-455-8880	https://thousandacrefarm.com/
Lavender Fields at Warrington Manor	28376 Martins Farm Road	Milton	Delaware			Garden / Outdoor	Indoor & Outdoor	66	Classic	Working lavender farm where couples marry in a climate-controlled greenhouse hung with olive and lemon trees; $7,500 flat fee in season.		302-684-1514	https://www.lavenderfieldsde.com/book-event/
The Lewes Room at Irish Eyes	213 Anglers Road	Lewes	Delaware			Restaurant / Vineyard	Indoor	200	Simple	Upstairs sunroom of about 1,100 sq ft with a harbor view, full bar and built-in dance floor; buffets from $39 per person plus a 35% venue fee.	banquet@irisheyespub.com	302-448-6137	https://www.irisheyespub.com/about/locations/lewes/lewes-room/weddings/
Grain on the Rocks	43 Cape Henlopen Drive	Lewes	Delaware			Beach / Waterfront	Outdoor	300		Tented receptions at the Lewes Ferry Terminal on Delaware Bay with pier ceremonies and sunset views.		302-291-3900	https://www.grainontherocks.com/weddings
Addy Sea Historic Oceanfront Inn	99 Ocean View Parkway	Bethany Beach	Delaware			Beach / Waterfront	Indoor & Outdoor	120		Historic adults-only oceanfront inn with ceremonies by the dunes under an ornate arch.	guestservices@addysea.com	302-539-3707	https://www.addysea.com/special-events
The Delaware Contemporary	200 South Madison Street	Wilmington	Delaware			Historic / Estate	Indoor	250		Art museum atrium lobby on the Wilmington riverfront with a black-box auditorium for ceremonies.	events@decontemporary.org	302-656-6466	https://www.decontemporary.org/venue-rental
Dogfish Head Brewings & Eats	320 Rehoboth Avenue	Rehoboth Beach	Delaware			Restaurant / Vineyard	Indoor	200		The original Dogfish brewpub, offering buyouts for cocktail, family-style or food-station receptions.			https://www.dogfish.com/visit/weddings-and-private-events
Dogfish Inn	105 Savannah Road	Lewes	Delaware			Ballroom / Hotel	Indoor & Outdoor			Sixteen-room canal-side inn with a two-bedroom bridal suite and ceremonies in the inn cottage.	innkeeper@dogfish.com	302-644-8292	https://www.dogfish.com/inn
Virden Retreat Center	1155 College Drive	Lewes	Delaware			Ballroom / Hotel	Indoor & Outdoor			University of Delaware retreat center with a tented patio, ceremony lawns and 23 guestrooms.		302-645-4100	https://conferences.udel.edu/weddings
Juniper by Tonic	111 West 11th Street	Wilmington	Delaware			Ballroom / Hotel	Indoor & Outdoor	225		Downtown event space with floor-to-ceiling city views, an outdoor patio and an all-inclusive package.		302-777-2040	https://www.juniperbytonic.com/news-item/weddings/
Historic Odessa Foundation	201 Main Street	Odessa	Delaware			Historic / Estate	Indoor & Outdoor	250		Village of restored 18th and 19th century buildings with colonial revival gardens and a stone barn.		302-378-4119	https://historicodessa.org/plan-your-event/weddings
Delaware Agricultural Museum & Village	866 N. Dupont Highway	Dover	Delaware			Historic / Estate	Indoor & Outdoor	220		Lakeside museum village with a church for ceremonies, outdoor spaces and indoor galleries.	director@deagriculturalmuseum.org	302-554-0551	https://deagriculturalmuseum.org/host-an-event/
Newark Country Club	300 W Main Street	Newark	Delaware			Ballroom / Hotel	Indoor			Golf-course clubhouse with an in-house chef, event planner and set wedding packages.		302-731-4251	https://www.newarkcc.com/weddings-and-events
Bayside Resort Golf Club	12021 North Haven Drive	Selbyville	Delaware			Ballroom / Hotel	Indoor & Outdoor			Golf community overlooking Assawoman Bay with wedding and elopement packages.		302-436-9998	https://www.livebayside.com/weddings-events
Seaford Historical Society (Ross Station Event Center)	585 North Market Street Ext.	Seaford	Delaware			Historic / Estate	Indoor & Outdoor	225		3,800 sq ft banquet hall, an 1860 mansion and ten acres of grounds for outdoor ceremonies.		302-396-7260	https://seafordhistoricalsociety.com/?p=676`,
  },
];

export default batches;
