import type { VenueBatch } from "@/lib/venue-batches";

// Florida venue batches. Every row's State is "Florida". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Miami, Orlando and Tampa Bay",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Cooper Estate	14201 SW 248th St	Homestead	Florida			Historic / Estate	Indoor & Outdoor			Century-old oolite limestone house and barn on a working native-plant nursery in the Redland, with live oaks, fish ponds and a sunken grotto.	info@thecooperestate.com	(305) 904-9032	https://thecooperestate.com/weddings/
Miami Beach Botanical Garden	2000 Convention Center Dr	Miami Beach	Florida			Garden / Outdoor	Indoor & Outdoor			Three acres of tropical garden beside the convention centre, with palms, orchids and cycads around its event spaces.	growwithus@mbgarden.org		https://www.mbgarden.org/private-events
Schnebly Redland's Winery	30205 SW 217th Ave	Homestead	Florida			Restaurant / Vineyard	Outdoor			Tropical-fruit winery on thirty acres with a waterfall courtyard for ceremonies and thatched tiki huts for receptions.	info@schneblywinery.com	(305) 242-1224	https://www.schneblywinery.com/weddings-private-events
Coral Gables Country Club	990 Alhambra Circle	Coral Gables	Florida			Ballroom / Hotel	Indoor & Outdoor	600		Club built in 1922 by Coral Gables founder George Merrick beside the Granada golf course, with a ballroom for 600 and an outdoor Granada Garden.	events@coralgablescountryclub.com	(305) 722-8783	https://www.coralgablescountryclub.com/venue
Pinecrest Gardens	11000 Red Rd	Pinecrest	Florida			Garden / Outdoor	Indoor & Outdoor			Village-run botanical garden with the indoor Cypress Hall, outdoor lawns and a 500-seat open-air amphitheatre, the Banyan Bowl.	info@pinecrestgardens.org	(305) 669-6990	https://www.pinecrestgardens.org/Venue-Rental
Hotel Colonnade Coral Gables	180 Aragon Ave	Coral Gables	Florida			Ballroom / Hotel	Indoor & Outdoor			Coral Gables hotel with a rotunda under a 60-foot dome, a Galleria hall and a rooftop terrace.		(305) 441-2600	https://hotelcolonnade.com/gather/weddings/
Coral Gables Woman's Club	1001 E Ponce de Leon Blvd	Coral Gables	Florida			Historic / Estate	Indoor	240		Clubhouse of a women's club over 100 years old, with two wood-beamed ballrooms, one with limestone walls and two fireplaces.	rentals@coralgableswomansclub.com	(305) 448-7080	https://coralgableswomansclub.org/venue/
The Betsy Hotel	1440 Ocean Dr	Miami Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Boutique hotel on Ocean Drive with a rooftop Skyline Deck, an oceanfront deck and a subterranean bar for wedding events.		(305) 531-6100	https://www.thebetsyhotel.com/gather/weddings
Casa Feliz	656 N Park Ave	Winter Park	Florida			Historic / Estate	Indoor & Outdoor	120		1933 James Gamble Rogers II house museum on Park Avenue, moved to save it from demolition, with courtyards, a library and a garden room.		(407) 628-0230	https://www.casafelizvenue.com/casafelizwedding
Paradise Cove	13245 Lake Bryan Dr	Orlando	Florida			Beach / Waterfront	Outdoor			Secluded spot on the shore of Lake Bryan near Lake Buena Vista with a white-sand beach, a tiki bar and a lit pavilion.	info@paradisecoveorlando.com	(407) 239-6939	https://paradisecoveorlando.com/ceremony-reception/
Lake Mary Events Center	260 N Country Club Rd	Lake Mary	Florida			Ballroom / Hotel	Indoor & Outdoor	240	Simple	City-run events centre on West Crystal Lake with a rotunda, a lakeside ceremony lawn under live oaks and a ballroom for 240.		(407) 585-1490	https://www.lakemaryeventscenter.com/101/Weddings
Historic Venue 1902	301 W 7th St	Sanford	Florida			Historic / Estate	Indoor & Outdoor	175		Sanford's former grammar school, restored with a grand ballroom, a library and ceremony spaces.		(407) 986-8600	https://www.venue1902.com/
Gaylord Palms Resort & Convention Center	6000 W Osceola Pkwy	Kissimmee	Florida			Ballroom / Hotel	Indoor & Outdoor			Convention resort with 1,718 rooms, a wedding pavilion, a fort-themed reception space and an outdoor Mangrove Lawn.		(407) 586-0000	https://www.marriott.com/en-us/hotels/mcogp-gaylord-palms-resort-and-convention-center/events/
Heller Hall at Winter Garden Heritage Foundation	21 E Plant St	Winter Garden	Florida			Historic / Estate	Indoor & Outdoor	70		Chandeliered hall with an adjoining pergola on the West Orange Trail in downtown Winter Garden's historic district.	hellerhall@wghf.org	(407) 656-3244	https://www.wghf.org/facility-rentals/
Orlando Museum of Art	2416 N Mills Ave	Orlando	Florida			Historic / Estate	Indoor & Outdoor	200		Art museum in Loch Haven Park with a skylit marble grand gallery, a rotunda and an open-air sculpture plaza.	facilityrentals@omart.org	(407) 896-4231	https://omart.org/facility_rentals/weddings/
The Mennello Museum of American Art	900 E Princeton St	Orlando	Florida			Garden / Outdoor	Indoor & Outdoor		Simple	Small art museum beside Lake Formosa whose sculpture garden hosts ceremonies, with a porch and gallery for smaller groups.	noelia.veras@orlando.gov	(407) 246-4278	https://www.mennellomuseum.org/Rentals/Rentals
Sunken Gardens	1825 4th St N	St. Petersburg	Florida			Garden / Outdoor	Indoor & Outdoor	200	Classic	Sunken botanical garden that has hosted weddings since 1935, with a north lawn, an oak pavilion and an indoor Garden Room.		(727) 551-3106	https://sunkengardens.org/weddings/
Fenway Hotel	453 Edgewater Dr	Dunedin	Florida			Ballroom / Hotel	Indoor & Outdoor	360		Dunedin hotel in a building that housed a radio station in 1925, with eight event rooms and a front lawn for 360.		(727) 683-5999	https://www.fenwayhotel.com/wedding-events/weddings/
Safety Harbor Resort and Spa	105 N Bayshore Dr	Safety Harbor	Florida			Ballroom / Hotel	Indoor & Outdoor			Waterfront spa resort built over natural mineral springs, with the chandeliered Four Springs Ballroom.		(888) 237-8772	https://www.safetyharborspa.com/wedding-facilities-venues
Opal Sands	430 S Gulfview Blvd	Clearwater Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Clearwater Beach resort with its own event lawn for 250, sharing ballrooms with sister hotel Opal Sol.		(727) 450-0380	https://www.opalcollection.com/opal-sands/gather/weddings/
Tampa Bay History Center	801 Water St	Tampa	Florida			Historic / Estate	Indoor & Outdoor	300		History museum on the downtown Tampa waterfront with an atrium, an event hall for 300 and an upper terrace.		(813) 229-5529	https://tampabayhistorycenter.org/private-events-tampa-bay-history-center/
Oxford Exchange	420 W Kennedy Blvd	Tampa	Florida			Restaurant / Vineyard	Indoor			1891 building reworked as a bookshop and restaurant, with a glass-roofed conservatory, an atrium and a library for weddings.			https://oxfordexchange.com/pages/weddings
The Vinoy Resort & Golf Club	501 5th Ave NE	St. Petersburg	Florida			Ballroom / Hotel	Indoor & Outdoor	400		Waterfront hotel in downtown St. Petersburg open since 1925, with ballrooms and lawns for weddings of up to 400.	vinoy.info@thevinoy.com	(727) 894-1000	https://thevinoy.com/weddings/
Le Méridien Tampa, The Courthouse	601 N Florida Ave	Tampa	Florida			Historic / Estate	Indoor & Outdoor			Hotel in Tampa's former federal courthouse with a Courthouse Ballroom and an outdoor terrace overlooking downtown.		(813) 221-9555	https://www.marriott.com/en-us/hotels/tpamd-le-meridien-tampa-the-courthouse/events/
`,
  },
  {
    name: "Naples and Fort Myers, Destin and 30A, Jacksonville and around the state",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Burroughs Home & Gardens	2505 First St	Fort Myers	Florida			Historic / Estate	Indoor & Outdoor	200	Classic	Georgian Revival mansion from 1901 on the Caloosahatchee River in downtown Fort Myers, with a gazebo, a pavilion and riverside gardens.		(239) 337-9505	https://burroughshome.com/
Sidney & Berne Davis Art Center	2301 First St	Fort Myers	Florida			Historic / Estate	Indoor			Arts centre in a columned Neoclassical former federal building in the Fort Myers River District, rented out for weddings and receptions.	calee@sbdac.com	(239) 333-1933	https://www.sbdac.com/rentals/
Naples Grande Beach Resort	475 Seagate Dr	Naples	Florida			Beach / Waterfront	Indoor & Outdoor			Naples resort with a boardwalk through the mangroves to its Gulf beach, plus ballrooms and lawns for ceremonies and receptions.	events@naplesgrande.com	(239) 597-3232	https://www.naplesgrande.com/naples-grande-wedding
LaPlaya Beach & Golf Resort	9891 Gulf Shore Dr	Naples	Florida			Beach / Waterfront	Indoor & Outdoor	450		Vanderbilt Beach resort with 193 rooms whose North and South beaches take ceremonies of up to 450, plus indoor function rooms.	sales@laplayaresort.com	(239) 597-3123	https://www.laplayaresort.com/gather/weddings/
Edgewater Beach Hotel	1901 Gulf Shore Blvd N	Naples	Florida			Beach / Waterfront	Indoor & Outdoor	80		All-suite hotel on Naples' Gulf Shore Boulevard suited to smaller weddings, with a beach, a pool deck and a ballroom each holding 80.		(239) 403-2000	https://www.opalcollection.com/edgewater/gather/weddings/
Naples Princess	550 Port O Call Way	Naples	Florida			Beach / Waterfront	Indoor & Outdoor			Sightseeing and dinner yacht sailing Naples Bay and the Gulf, with wedding packages for ceremonies and receptions on board.		(239) 649-2275	https://www.naplesprincesscruises.com/naples-weddings/
Hilton Marco Island Beach Resort	560 S Collier Blvd	Marco Island	Florida			Beach / Waterfront	Indoor & Outdoor	300		Gulf-front resort with a 10,000 sq ft Great Lawn and an Island Ballroom that each take up to 300, plus wide beaches for sunset ceremonies.		(239) 394-5000	https://www.hiltonmarcoisland.com/beach-weddings/marco-island-venues.shtml
Sandestin Golf and Beach Resort	9300 Emerald Coast Pkwy	Miramar Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			Resort of 2,400 acres running from the Gulf to Choctawhatchee Bay, with beach and bayfront ceremony sites and large ballrooms.		(850) 267-8000	https://www.sandestin.com/gather/weddings
Kelly Plantation Golf Club	307 Kelly Plantation Dr	Destin	Florida			Garden / Outdoor	Indoor & Outdoor	300		Golf club on the site of an old turpentine plantation beside Choctawhatchee Bay, with lawn ceremonies and covered receptions for up to 300.		(850) 650-7600	https://www.kellyplantationgolf.com/destin-wedding-venues
SunQuest Cruises SOLARIS	8330 Mike Hayes Dr	Miramar Beach	Florida			Beach / Waterfront	Indoor & Outdoor	149		Yacht docked at Baytowne Marina that cruises Choctawhatchee Bay, with a dining room seating 100 and an open-air sky deck.		(850) 650-2519	https://sunquestcruises.com/destin-weddings/
The Henderson Park Inn	2700 Scenic Hwy 98	Destin	Florida			Beach / Waterfront	Outdoor			Adults-only inn beside Henderson Beach State Park, with Gulf-front lawns and sand for beach ceremonies.		(888) 836-1105	https://www.hendersonparkinn.com/weddings-celebrations/
Regatta Bay Golf & Yacht Club	465 Regatta Bay Blvd	Destin	Florida			Ballroom / Hotel	Indoor	150		Semi-private golf club near Choctawhatchee Bay whose clubhouse hosts receptions, showers and rehearsal dinners for up to 150.	cking@regattabay.com	(850) 337-8080	https://www.regattabay.com/events/
The Cummer Museum	829 Riverside Ave	Jacksonville	Florida			Garden / Outdoor	Indoor & Outdoor	200	Classic	Riverside art museum on the St. Johns River with historic terraced gardens, a loggia and galleries for receptions of up to 200.	events@cummermuseum.org	(904) 356-6857	https://www.cummermuseum.org/host-an-event/
Casa Monica Resort & Spa	95 Cordova St	St. Augustine	Florida			Historic / Estate	Indoor & Outdoor			Moorish Revival hotel opened in 1888 in St. Augustine's old town, with ballrooms and courtyard spaces for weddings.	cmh-weddings@kesslerhospitality.com	(904) 827-1888	https://www.casamonica.com/weddings
Casa Marina Hotel	691 1st St N	Jacksonville Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Spanish-style oceanfront hotel from the 1920s in Jacksonville Beach, with a courtyard, a dining room and a penthouse for events.		(904) 270-0025	https://www.casamarinahotel.com/weddings
Dune House Hotel & Spa	1 Ocean Blvd	Atlantic Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Oceanfront hotel in Atlantic Beach with a Horizon Ballroom and twelve event spaces, the Atlantic as backdrop.		(904) 249-7402	https://www.dunehousehotelandspa.com/events-groups/
Bowing Oaks	7743 Alphons St	Jacksonville	Florida			Garden / Outdoor	Indoor & Outdoor	200		Five acres among century-old oaks, with a 3,200 sq ft air-conditioned ballroom built in 2014 and two outdoor ceremony sites.	info@bowingoaks.com	(904) 600-5172	https://bowingoaks.com/
The Club Continental	2143 Astor St	Orange Park	Florida			Historic / Estate	Indoor & Outdoor			Riverfront estate on the St. Johns chosen by a Palmolive heir, with a mansion, gardens and ceremonies under a 300-year-old live oak.	carla@clubcontinental.com	(904) 264-6070	https://clubcontinental.com/event-facility/weddings/
Lakeside Inn	100 N Alexander St	Mount Dora	Florida			Historic / Estate	Indoor & Outdoor			Mount Dora hotel dating to 1883 on Lake Dora, with a courtyard lawn, a gazebo under the oaks, a small beach and ten event spaces.		(352) 383-4101	https://lakeside-inn.com/events/weddings/
Wanderlust Okto	6551 New Hope Rd	Orlando	Florida			Barn / Rustic	Indoor & Outdoor			Lake Nona property near the airport with a 4,000 sq ft climate-controlled barn, a pond, a treehouse and on-site stays.	info@wanderlustokto.com	(954) 937-7299	https://oktohospitalitygroup.com/
Crossing Palms	777 Alturas Rd	Bartow	Florida			Barn / Rustic	Indoor & Outdoor	350		Lakefront property of 54 acres in Polk County with a 5,000 sq ft glass barn and an outdoor pavilion, booked as all-inclusive packages.		(863) 537-6590	https://www.crossingpalmsweddings.com/weddings/
The Estate on the Halifax	5123 S Ridgewood Ave	Port Orange	Florida			Historic / Estate	Indoor & Outdoor	200		Ten-acre estate on the Halifax River with a stained-glass chapel, a lakeside gazebo and a Tavern for receptions of up to 200.	info@estateonthehalifax.com	(386) 763-2285	https://www.estateonthehalifax.com/weddings/
Innisbrook Golf Resort	36750 US Hwy 19 N	Palm Harbor	Florida			Ballroom / Hotel	Indoor & Outdoor	300		Wooded golf resort north of Clearwater with ballrooms for up to 300 each, a pool lawn and a smaller Italian-style room.		(888) 794-8627	https://www.innisbrookgolfresort.com/gatherings/weddings/venues
TradeWinds Island Grand	5500 Gulf Blvd	St. Pete Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Gulf-front resort on St. Pete Beach with over 50,000 sq ft of event space across its hotels and beach ceremony sites.		(727) 367-6461	https://www.tradewindsresort.com/weddings
The Luce	6300 Gulf Blvd	St. Pete Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Beachfront hotel with 14,000 sq ft of Gulf-view event space, a Palm Court garden for ceremonies and ballrooms for receptions.	info@thelucehotel.com	(727) 632-3300	https://www.thelucehotel.com/weddings
The Addison	2 E Camino Real	Boca Raton	Florida			Historic / Estate	Indoor & Outdoor			Mizner-era Spanish-style building in Boca Raton with a fountain courtyard under century-old banyans and indoor ballrooms.		(561) 372-0568	https://www.theaddisonofbocaraton.com/weddings
Pier Sixty-Six	2301 SE 17th St	Fort Lauderdale	Florida			Beach / Waterfront	Indoor & Outdoor			Fort Lauderdale resort and marina known for its spire-topped tower, with waterfront lawns and ballrooms by the Intracoastal.	events@piersixtysixresort.com	(954) 525-6666	https://www.piersixtysixweddings.com/
Coral Gables Museum	285 Aragon Ave	Coral Gables	Florida			Historic / Estate	Indoor & Outdoor			Museum in Coral Gables' 1939 former police and fire station, with an open-air loggia, a walled garden and a public plaza for events.		(305) 603-8067	https://coralgablesmuseum.org/weddingsandprivateevents/
`,
  },
  {
    name: "Jacksonville, Destin and 30A, Naples and Fort Myers",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Garden Club of Jacksonville	1005 Riverside Avenue	Jacksonville	Florida			Historic / Estate	Indoor & Outdoor	350		A Riverside clubhouse with a chandeliered grand ballroom, a smaller club room and a flagstone courtyard with a fountain facing the St. Johns River.	events@gardenclubjax.org	(904) 355-4224	https://www.gardenclubjax.org/rent
The Lodge & Club Ponte Vedra Beach	607 Ponte Vedra Blvd	Ponte Vedra Beach	Florida			Beach / Waterfront	Indoor & Outdoor	200		An oceanfront resort with an ocean lawn, a fountain courtyard, a trellis space, a conservatory and two indoor rooms for receptions.		(904) 273-7785	https://www.pontevedra.com/weddings/lodge
Fountain of Youth Archaeological Park	11 Magnolia Avenue	St. Augustine	Florida			Beach / Waterfront	Indoor & Outdoor	300		A 15-acre park above the Matanzas River with a covered air-conditioned pavilion, garden and waterfront ceremony spots, and a bridal dressing room.		(904) 342-8388	https://www.fountainofyouthflorida.com/weddings-events
The Clubhouse at St. Augustine Ocean & Racquet Resort	880 A1A Beach Blvd	St. Augustine	Florida			Ballroom / Hotel	Indoor & Outdoor	80	Simple	A resort clubhouse of about 1,200 square feet with a deck over a fountain pond, a full kitchen, and tables and chairs included in the rental.	info@oceanandracquet.com	(904) 471-0932	https://www.oceanandracquet.com/amenities/clubhouse
Cedar House Inn	79 Cedar Street	St. Augustine	Florida			Historic / Estate	Indoor & Outdoor	30		A downtown bed and breakfast offering small ceremonies for up to 30 guests in a gazebo, garden, fireplace room or stained-glass parlor.	info@cedarhouseinn.com	(904) 829-0079	https://www.cedarhouseinn.com/weddings
Colonial Oak Music Park	33 St. George St	St. Augustine	Florida			Garden / Outdoor	Outdoor	175		An open-air downtown venue under an old oak with an amphitheater, family-style tables, a full bar and an on-site chef.		(904) 315-9728	https://www.thecolonialoakmusicpark.com/private-events
Renaissance St. Augustine Historic Downtown Hotel	6 West Castillo Drive	St. Augustine	Florida			Ballroom / Hotel	Indoor	350		A downtown hotel whose 4,462 sq ft San Marco Ballroom seats 270 for dinner, backed by five breakout rooms and certified wedding planners.		(904) 824-4457	https://www.marriott.com/en-us/hotels/jaxrj-renaissance-st-augustine-historic-downtown-hotel/events
Ancient City Farmstead	395 St. Marks Pond Blvd	St. Augustine	Florida			Barn / Rustic	Indoor & Outdoor	300		A farm property with an air-conditioned barn hall, an open-air barn, a restored farmhouse, bridal and groom suites and a catering prep kitchen.			https://ancientcityfarmstead.com
Museum of Contemporary Art Jacksonville	333 North Laura Street	Jacksonville	Florida			Ballroom / Hotel	Indoor & Outdoor	500		A downtown museum with a lobby, theater, galleries and fifth-floor loft that can be rented for ceremonies and receptions, with in-house catering and a full bar.	mocaevents@unf.edu	(904) 620-3226	https://mocajacksonville.unf.edu/rentals
Hoyt House	804 Atlantic Ave	Fernandina Beach	Florida			Historic / Estate	Indoor & Outdoor			A Victorian mansion in the Fernandina historic district with a porch, landscaped grounds and pool, offering small wedding and elopement packages.	info@hoythouse.com	(904) 277-4300	https://www.hoythouse.com
The Ritz-Carlton, Amelia Island	4750 Amelia Island Parkway	Amelia Island	Florida			Ballroom / Hotel	Indoor & Outdoor			A 26-acre oceanfront resort with beachfront and lawn ceremony sites and several ballrooms that seat from 100 to over 800 for receptions.		(904) 277-1100	https://www.ritzcarlton.com/en/hotels/jaxam-the-ritz-carlton-amelia-island/events/
Sawgrass Marriott Golf Resort & Spa	1000 Tournament Players Club Blvd	Ponte Vedra Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			A golf resort with Champions, Masters and Arbor ballrooms plus the Spa Lawn and Cascades deck for outdoor ceremonies, next to TPC Sawgrass.		(904) 285-7777	https://www.marriott.com/en-us/hotels/jaxsw-sawgrass-marriott-golf-resort-and-spa/events/
Ocean Club of Amelia	2080 South Fletcher Avenue	Fernandina Beach	Florida			Beach / Waterfront	Indoor & Outdoor	130		A two-story oceanfront cottage with an upstairs porch, a dining room and bar, a covered patio and a dune-view lawn, with in-house catering.	Info@shgcollection.com	(904) 601-2226	https://www.shgcollection.com/ocean-club-of-amelia
The Lesesne House	415 Centre Street	Fernandina Beach	Florida			Historic / Estate	Indoor & Outdoor	130		An 1860s Classical Revival house on the National Register with a formal dining room, two parlors, a bridal suite, two courtyards and a grapevine pergola.	Info@shgcollection.com	(904) 601-2226	https://www.shgcollection.com/lesesne-house
The Florida House Inn	22 South 3rd Street	Fernandina Beach	Florida			Historic / Estate	Indoor & Outdoor	150		An 1857 inn with a dining room, the Mermaid Bar, a porch and a courtyard under a 200-year-old live oak for ceremonies and receptions.	Info@shgcollection.com	(904) 601-2226	https://www.shgcollection.com/florida-house-inn
Crosswater Hall at Nocatee	245 Nocatee Center Way	Ponte Vedra	Florida			Ballroom / Hotel	Indoor & Outdoor	180	Simple	A community event hall with a fireplace room seating 180, a catering kitchen, a bridal suite with balcony and an outdoor lawn called The Green.	Roseanna@nocatee.com	(904) 924-6851	https://www.nocatee.com/crosswater-hall
Pier Suite Events	41 Fort Pickens Rd	Pensacola Beach	Florida			Beach / Waterfront	Indoor & Outdoor			A minimalist event suite with floor-to-ceiling windows, a covered balcony over the water and the option to hold the ceremony on the sand below.	info@piersuiteevents.com	(850) 501-0409	https://www.piersuiteevents.com
The Chapel of 30A	61 Topsail Village Dr	Santa Rosa Beach	Florida			Historic / Estate	Indoor & Outdoor			A chapel with vaulted beamed ceilings, oak doors and wrought-iron chandeliers in a European manor style, with outdoor ceremony space and room for the reception on the same site.	info@chapelof30a.com	(850) 842-1188	https://www.chapelof30a.com
The Chapel at Seaside	582 Forest St	Seaside	Florida			Historic / Estate	Indoor	175		An inter-denominational chapel with a bell tower and vaulted ceilings, a few blocks from the Gulf, rented for ceremonies in a three-hour block plus a two-hour rehearsal.	events@thechapelatseaside.com	(850) 633-3392	https://thechapelatseaside.com/the-chapel-at-seaside-weddings/
Hilton Pensacola Beach	12 Via De Luna Dr	Pensacola Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			A Gulf-front hotel on Pensacola Beach with a dedicated wedding and events team, in-house catering and audiovisual support for beach weddings and receptions.	hiltonpensacolabeach@innisfreehotels.com	(850) 916-2999	https://www.hiltonpensacolabeach.com/beach-weddings/
Runaway Island Beach Bar & Grill	14521 Front Beach Rd	Panama City Beach	Florida			Restaurant / Vineyard	Indoor & Outdoor	160		A two-level beachfront restaurant with private rooms of different sizes and a deck with a boardwalk to the sand, used for receptions after a beach ceremony.		(850) 634-4884	https://www.runawayislandpcb.com
Angler's Events	1030 Miracle Strip Pkwy SE	Fort Walton Beach	Florida			Beach / Waterfront	Indoor & Outdoor	150	Simple	A farmhouse-style private room above Angler's Beachside Grill on Okaloosa Island with Gulf views, a tiki bar, a getting-ready suite and beach ceremonies next to the pier.	events@anglersgrill.com	(850) 739-1109	https://anglersevents.com
Hilton Garden Inn Fort Walton Beach	1297 Miracle Strip Pkwy SE	Fort Walton Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			A beachfront hotel on Okaloosa Island offering reception space, on-site catering, guest room blocks and a vendor list for Gulf-side ceremonies.		(850) 362-1000	https://hiltongardeninnfortwaltonbeach.com/beach-weddings/
The Island Resort & Convention Center	1500 Miracle Strip Parkway Southeast	Fort Walton Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			A Gulf-front resort with indoor ballrooms and outdoor beachside, garden and poolside spaces, with catering and event coordination handled in-house.		(800) 874-8962	https://www.theislandfl.com/meet-celebrate/
Portofino Island Resort	10 Portofino Drive	Pensacola Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			A condo-tower resort between the Gulf and Santa Rosa Sound with ceremony and reception spaces, on-site lodging for guests and custom menus from an in-house culinary team.	events@premierisland.com	(850) 916-5000	https://www.portofinoisland.com/weddings
The Alice	109 Calhoun Ave	Destin	Florida			Beach / Waterfront	Indoor & Outdoor	350		A private bayfront venue facing Crab Island, with a 75-seat indoor building, landscaped grounds that seat about 350 outdoors, and eight guest cottages across the street.		(850) 460-0425	https://the-alice.com
Carillon Weddings at Carillon Beach	109 Village Way	Panama City Beach	Florida			Beach / Waterfront	Indoor & Outdoor			A planned beachfront community with several ceremony sites, including the Meeting House, Village Green, Bellview Park Green and the beach, run by an on-site wedding team.	info@carillonweddings.com	(850) 231-0007	https://www.carillonweddings.com
Inn on Fifth	699 Fifth Avenue South	Naples	Florida			Ballroom / Hotel	Indoor & Outdoor	80		Downtown Naples boutique hotel with a Fifth Avenue terrace, courtyard, rooftop club space and Palm Ballroom for smaller weddings.		(239) 403-8777	https://www.innonfifth.com/weddings-in-the-heart-of-naples/
The Ritz-Carlton Naples, Tiburon	2600 Tiburon Drive	Naples	Florida			Ballroom / Hotel	Indoor & Outdoor	1100	Luxury	Golf resort with a large Tiburon Ballroom, a Grand Lawn Pavilion, a Court of Palms patio, and a putting green used for ceremonies of up to 140.		(239) 598-6621	https://www.ritzcarlton.com/en/hotels/rswgr-the-ritz-carlton-naples-tiburon/weddings/
JW Marriott Marco Island Beach Resort	400 South Collier Boulevard	Marco Island	Florida			Beach / Waterfront	Indoor & Outdoor	300		Beach resort on a 10-acre stretch of sand, with Balinese-inspired ballrooms, palm-lined terraces and lawns for ceremonies and receptions.	DL-MRKFLJWMarriottMarcoIslandLeads@marriott.com	(239) 642-2794	https://www.marriott.com/en-us/hotels/mrkfl-jw-marriott-marco-island-beach-resort/events/wedding-paradise/
Sundial Beach Resort & Spa	1451 Middle Gulf Drive	Sanibel	Florida			Beach / Waterfront	Indoor & Outdoor		Classic	Gulf-side resort offering ceremonies on the beach or a lawn, a beach reception area, a garden and ballrooms, with an indoor backup space.	info@SundialResort.com	(239) 472-4151	https://sundialresort.com/events/weddings/
Marriott Sanibel Harbour Resort & Spa	17260 Harbour Pointe Drive	Fort Myers	Florida			Ballroom / Hotel	Indoor & Outdoor	965		Waterfront resort with a 9,684 sq ft Palms Ballroom, a pool deck for outdoor events and a yacht that holds 130 guests.		(239) 466-4000	https://www.marriott.com/en-us/hotels/rswsb-marriott-sanibel-harbour-resort-and-spa/events/
The Alderman House	2572 First Street	Fort Myers	Florida			Historic / Estate	Indoor & Outdoor			Mediterranean Revival house designed by Addison Mizner in 1924, with a front lawn, courtyard, atrium, two getting-ready suites and a Juliet balcony.		(239) 710-6466	https://aldermanhouse.com/
Misty Morning Barn	18810 Misty Morning Lane	Fort Myers	Florida			Barn / Rustic	Indoor & Outdoor	300		Barn venue on 32 private acres with ponds, five ceremony locations, a fire pit and no vendor fees.	mike@mistymorningbarn.com	(815) 693-8443	https://www.mistymorningbarn.com/
La Finka	18051 Nalle Road	Fort Myers	Florida			Garden / Outdoor	Outdoor	120		15-acre North Fort Myers property with lakefront ceremony options, space for 120 guests with dancing, and an estate house that sleeps 12.	hello@lafinkaswfl.com	(215) 584-5086	https://www.lafinkaswfl.com/
Spanish Wells Golf & Country Club	9801 Treasure Cay Lane	Bonita Springs	Florida			Ballroom / Hotel	Indoor			Country club with a renovated Grand Ballroom, a fountain backdrop and golf course views, hosting one event per day.		(239) 992-5100	https://www.spanishwellscountryclub.com/weddings/
The Westin Cape Coral Resort at Marina Village	5951 Silver King Boulevard	Cape Coral	Florida			Ballroom / Hotel	Indoor & Outdoor	1400		Marina resort with a gazebo lawn and rooftop terrace for ceremonies, several ballrooms, and a charter vessel for waterfront events.		(239) 541-5000	https://www.marriott.com/en-us/hotels/rswwi-the-westin-cape-coral-resort-at-marina-village/weddings/
La Venezia Ballroom	4646 SE 10th Place	Cape Coral	Florida			Ballroom / Hotel	Indoor			Cape Coral ballroom offering catered packages with food, servers, full set-up and an open bar.	laveneziaballroom@yahoo.com	(239) 945-0034	https://www.laveneziaballroom.com/
Harborside Garden	33 Tamiami Trail	Punta Gorda	Florida			Beach / Waterfront	Outdoor			Waterfront tiki-hut venue beside TT's Tiki Bar on Charlotte Harbor, with high wood ceilings, warm lighting and harbor views.		(941) 637-6770	https://www.harborsidegarden.net/
Fishermen's Village	1200 W. Retta Esplanade	Punta Gorda	Florida			Beach / Waterfront	Outdoor			Harbor-front village of shops and restaurants where couples can hold ceremonies at the water's edge on Charlotte Harbor.		(800) 639-0020	https://www.fishermensvillage.com/general-1
Peace River Botanical & Sculpture Gardens	5827 Riverside Drive	Punta Gorda	Florida			Garden / Outdoor	Outdoor	300	Simple	27 acres of botanical gardens with a steel palm sculpture for ceremonies and flowering meadows for receptions; a contracted coordinator is required.	info@peacerivergardens.org	(941) 621-8299	https://www.peacerivergardens.org/weddings
Sunseeker Resort Charlotte Harbor	5500 Sunseeker Way	Charlotte Harbor	Florida			Ballroom / Hotel	Indoor & Outdoor	300		Harborfront resort with outdoor lawns for up to 200, a Great Egret Ballroom for up to 300, a bridal suite and a golf club venue.		(833) 914-7300	https://www.sunseekerresort.com/meetings-and-events/weddings/`,
  },
];

export default batches;
