import type { VenueBatch } from "@/lib/venue-batches";

// Florida venue batches. Every row's State is "Florida". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Miami, Orlando and Tampa Bay",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Cooper Estate	14201 SW 248th St	Homestead	Florida			Historic / Estate	Indoor & Outdoor			Century-old oolite limestone house and barn on a working native-plant nursery in the Redland, with live oaks, fish ponds and a sunken grotto.	info@thecooperestate.com	(305) 904-9032	https://thecooperestate.com/weddings/
Miami Beach Botanical Garden	2000 Convention Center Dr	Miami Beach	Florida			Garden / Outdoor	Indoor & Outdoor			Three acres of tropical garden beside the convention centre, with palms, orchids and cycads around its event spaces.	growwithus@mbgarden.org		https://www.mbgarden.org/private-events
Schnebly Redland's Winery	30205 SW 217th Ave	Homestead	Florida			Restaurant / Vineyard	Outdoor			Tropical-fruit winery on thirty acres with a waterfall courtyard for ceremonies and thatched tiki huts for receptions.	info@schneblywinery.com	(305) 242-1224	https://www.schneblywinery.com/weddings-private-events
Coral Gables Country Club	990 Alhambra Circle	Coral Gables	Florida			Ballroom / Hotel	Indoor & Outdoor	600		Club built in 1922 by Coral Gables founder George Merrick beside the Granada golf course, with a ballroom for 600 and an outdoor Granada Garden.	events@coralgablescountryclub.com	(305) 722-8783	https://www.coralgablescountryclub.com/venue
Pinecrest Gardens	11000 Red Rd	Pinecrest	Florida			Garden / Outdoor	Indoor & Outdoor			Village-run botanical garden with the indoor Cypress Hall, outdoor lawns and a 500-seat open-air amphitheatre, the Banyan Bowl.	info@pinecrestgardens.org	(305) 669-6990	https://www.pinecrestgardens.org/Venue-Rental
Hotel Colonnade Coral Gables	180 Aragon Ave	Coral Gables	Florida			Ballroom / Hotel	Indoor & Outdoor			Coral Gables hotel with a rotunda under a 60-foot dome, a Galleria hall and a rooftop terrace.		(305) 441-2600	https://hotelcolonnade.com/gather/weddings/
Coral Gables Woman's Club	1001 E Ponce de Leon Blvd	Coral Gables	Florida			Historic / Estate	Indoor	240		Clubhouse of a women's club over 100 years old, with two wood-beamed ballrooms, one with limestone walls and two fireplaces.	rentals@coralgableswomansclub.com	(305) 448-7080	https://coralgableswomansclub.org/venue/
The Betsy Hotel	1440 Ocean Dr	Miami Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Boutique hotel on Ocean Drive with a rooftop Skyline Deck, an oceanfront deck and a subterranean bar for wedding events.		(305) 531-6100	https://www.thebetsyhotel.com/gather/weddings
Casa Feliz	656 N Park Ave	Winter Park	Florida			Historic / Estate	Indoor & Outdoor	120		1933 James Gamble Rogers II house museum on Park Avenue, moved to save it from demolition, with courtyards, a library and a garden room.		(407) 628-0230	https://www.casafelizvenue.com/casafelizwedding
Paradise Cove	13245 Lake Bryan Dr	Orlando	Florida			Beach / Waterfront	Outdoor			Secluded spot on the shore of Lake Bryan near Lake Buena Vista with a white-sand beach, a tiki bar and a lit pavilion.	info@paradisecoveorlando.com	(407) 239-6939	https://paradisecoveorlando.com/ceremony-reception/
Lake Mary Events Center	260 N Country Club Rd	Lake Mary	Florida			Ballroom / Hotel	Indoor & Outdoor	240	Simple	City-run events centre on West Crystal Lake with a rotunda, a lakeside ceremony lawn under live oaks and a ballroom for 240.		(407) 585-1490	https://www.lakemaryeventscenter.com/101/Weddings
Historic Venue 1902	301 W 7th St	Sanford	Florida			Historic / Estate	Indoor & Outdoor	175		Sanford's former grammar school, restored with a grand ballroom, a library and ceremony spaces.		(407) 986-8600	https://www.venue1902.com/
Gaylord Palms Resort & Convention Center	6000 W Osceola Pkwy	Kissimmee	Florida			Ballroom / Hotel	Indoor & Outdoor			Convention resort with 1,718 rooms, a wedding pavilion, a fort-themed reception space and an outdoor Mangrove Lawn.		(407) 586-0000	https://www.marriott.com/en-us/hotels/mcogp-gaylord-palms-resort-and-convention-center/events/
Heller Hall at Winter Garden Heritage Foundation	21 E Plant St	Winter Garden	Florida			Historic / Estate	Indoor & Outdoor	70		Chandeliered hall with an adjoining pergola on the West Orange Trail in downtown Winter Garden's historic district.	hellerhall@wghf.org	(407) 656-3244	https://www.wghf.org/facility-rentals/
Orlando Museum of Art	2416 N Mills Ave	Orlando	Florida			Historic / Estate	Indoor & Outdoor	200		Art museum in Loch Haven Park with a skylit marble grand gallery, a rotunda and an open-air sculpture plaza.	facilityrentals@omart.org	(407) 896-4231	https://omart.org/facility_rentals/weddings/
The Mennello Museum of American Art	900 E Princeton St	Orlando	Florida			Garden / Outdoor	Indoor & Outdoor		Simple	Small art museum beside Lake Formosa whose sculpture garden hosts ceremonies, with a porch and gallery for smaller groups.	noelia.veras@orlando.gov	(407) 246-4278	https://www.mennellomuseum.org/Rentals/Rentals
Sunken Gardens	1825 4th St N	St. Petersburg	Florida			Garden / Outdoor	Indoor & Outdoor	200	Classic	Sunken botanical garden that has hosted weddings since 1935, with a north lawn, an oak pavilion and an indoor Garden Room.		(727) 551-3106	https://sunkengardens.org/weddings/
Fenway Hotel	453 Edgewater Dr	Dunedin	Florida			Ballroom / Hotel	Indoor & Outdoor	360		Dunedin hotel in a building that housed a radio station in 1925, with eight event rooms and a front lawn for 360.		(727) 683-5999	https://www.fenwayhotel.com/wedding-events/weddings/
Safety Harbor Resort and Spa	105 N Bayshore Dr	Safety Harbor	Florida			Ballroom / Hotel	Indoor & Outdoor			Waterfront spa resort built over natural mineral springs, with the chandeliered Four Springs Ballroom.		(888) 237-8772	https://www.safetyharborspa.com/wedding-facilities-venues
Opal Sands	430 S Gulfview Blvd	Clearwater Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Clearwater Beach resort with its own event lawn for 250, sharing ballrooms with sister hotel Opal Sol.		(727) 450-0380	https://www.opalcollection.com/opal-sands/gather/weddings/
Tampa Bay History Center	801 Water St	Tampa	Florida			Historic / Estate	Indoor & Outdoor	300		History museum on the downtown Tampa waterfront with an atrium, an event hall for 300 and an upper terrace.		(813) 229-5529	https://tampabayhistorycenter.org/private-events-tampa-bay-history-center/
Oxford Exchange	420 W Kennedy Blvd	Tampa	Florida			Restaurant / Vineyard	Indoor			1891 building reworked as a bookshop and restaurant, with a glass-roofed conservatory, an atrium and a library for weddings.			https://oxfordexchange.com/pages/weddings
The Vinoy Resort & Golf Club	501 5th Ave NE	St. Petersburg	Florida			Ballroom / Hotel	Indoor & Outdoor	400		Waterfront hotel in downtown St. Petersburg open since 1925, with ballrooms and lawns for weddings of up to 400.	vinoy.info@thevinoy.com	(727) 894-1000	https://thevinoy.com/weddings/
Le Méridien Tampa, The Courthouse	601 N Florida Ave	Tampa	Florida			Historic / Estate	Indoor & Outdoor			Hotel in Tampa's former federal courthouse with a Courthouse Ballroom and an outdoor terrace overlooking downtown.		(813) 221-9555	https://www.marriott.com/en-us/hotels/tpamd-le-meridien-tampa-the-courthouse/events/
`,
  },
  {
    name: "Naples and Fort Myers, Destin and 30A, Jacksonville and around the state",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Burroughs Home & Gardens	2505 First St	Fort Myers	Florida			Historic / Estate	Indoor & Outdoor	200	Classic	Georgian Revival mansion from 1901 on the Caloosahatchee River in downtown Fort Myers, with a gazebo, a pavilion and riverside gardens.		(239) 337-9505	https://burroughshome.com/
Sidney & Berne Davis Art Center	2301 First St	Fort Myers	Florida			Historic / Estate	Indoor			Arts centre in a columned Neoclassical former federal building in the Fort Myers River District, rented out for weddings and receptions.	calee@sbdac.com	(239) 333-1933	https://www.sbdac.com/rentals/
Naples Grande Beach Resort	475 Seagate Dr	Naples	Florida			Beach / Waterfront	Indoor & Outdoor			Naples resort with a boardwalk through the mangroves to its Gulf beach, plus ballrooms and lawns for ceremonies and receptions.	events@naplesgrande.com	(239) 597-3232	https://www.naplesgrande.com/naples-grande-wedding
LaPlaya Beach & Golf Resort	9891 Gulf Shore Dr	Naples	Florida			Beach / Waterfront	Indoor & Outdoor	450		Vanderbilt Beach resort with 193 rooms whose North and South beaches take ceremonies of up to 450, plus indoor function rooms.	sales@laplayaresort.com	(239) 597-3123	https://www.laplayaresort.com/gather/weddings/
Edgewater Beach Hotel	1901 Gulf Shore Blvd N	Naples	Florida			Beach / Waterfront	Indoor & Outdoor	80		All-suite hotel on Naples' Gulf Shore Boulevard suited to smaller weddings, with a beach, a pool deck and a ballroom each holding 80.		(239) 403-2000	https://www.opalcollection.com/edgewater/gather/weddings/
Naples Princess	550 Port O Call Way	Naples	Florida			Beach / Waterfront	Indoor & Outdoor			Sightseeing and dinner yacht sailing Naples Bay and the Gulf, with wedding packages for ceremonies and receptions on board.		(239) 649-2275	https://www.naplesprincesscruises.com/naples-weddings/
Hilton Marco Island Beach Resort	560 S Collier Blvd	Marco Island	Florida			Beach / Waterfront	Indoor & Outdoor	300		Gulf-front resort with a 10,000 sq ft Great Lawn and an Island Ballroom that each take up to 300, plus wide beaches for sunset ceremonies.		(239) 394-5000	https://www.hiltonmarcoisland.com/beach-weddings/marco-island-venues.shtml
Sandestin Golf and Beach Resort	9300 Emerald Coast Pkwy	Miramar Beach	Florida			Ballroom / Hotel	Indoor & Outdoor			Resort of 2,400 acres running from the Gulf to Choctawhatchee Bay, with beach and bayfront ceremony sites and large ballrooms.		(850) 267-8000	https://www.sandestin.com/gather/weddings
Kelly Plantation Golf Club	307 Kelly Plantation Dr	Destin	Florida			Garden / Outdoor	Indoor & Outdoor	300		Golf club on the site of an old turpentine plantation beside Choctawhatchee Bay, with lawn ceremonies and covered receptions for up to 300.		(850) 650-7600	https://www.kellyplantationgolf.com/destin-wedding-venues
SunQuest Cruises SOLARIS	8330 Mike Hayes Dr	Miramar Beach	Florida			Beach / Waterfront	Indoor & Outdoor	149		Yacht docked at Baytowne Marina that cruises Choctawhatchee Bay, with a dining room seating 100 and an open-air sky deck.		(850) 650-2519	https://sunquestcruises.com/destin-weddings/
The Henderson Park Inn	2700 Scenic Hwy 98	Destin	Florida			Beach / Waterfront	Outdoor			Adults-only inn beside Henderson Beach State Park, with Gulf-front lawns and sand for beach ceremonies.		(888) 836-1105	https://www.hendersonparkinn.com/weddings-celebrations/
Regatta Bay Golf & Yacht Club	465 Regatta Bay Blvd	Destin	Florida			Ballroom / Hotel	Indoor	150		Semi-private golf club near Choctawhatchee Bay whose clubhouse hosts receptions, showers and rehearsal dinners for up to 150.	cking@regattabay.com	(850) 337-8080	https://www.regattabay.com/events/
The Cummer Museum	829 Riverside Ave	Jacksonville	Florida			Garden / Outdoor	Indoor & Outdoor	200	Classic	Riverside art museum on the St. Johns River with historic terraced gardens, a loggia and galleries for receptions of up to 200.	events@cummermuseum.org	(904) 356-6857	https://www.cummermuseum.org/host-an-event/
Casa Monica Resort & Spa	95 Cordova St	St. Augustine	Florida			Historic / Estate	Indoor & Outdoor			Moorish Revival hotel opened in 1888 in St. Augustine's old town, with ballrooms and courtyard spaces for weddings.	cmh-weddings@kesslerhospitality.com	(904) 827-1888	https://www.casamonica.com/weddings
Casa Marina Hotel	691 1st St N	Jacksonville Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Spanish-style oceanfront hotel from the 1920s in Jacksonville Beach, with a courtyard, a dining room and a penthouse for events.		(904) 270-0025	https://www.casamarinahotel.com/weddings
Dune House Hotel & Spa	1 Ocean Blvd	Atlantic Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Oceanfront hotel in Atlantic Beach with a Horizon Ballroom and twelve event spaces, the Atlantic as backdrop.		(904) 249-7402	https://www.dunehousehotelandspa.com/events-groups/
Bowing Oaks	7743 Alphons St	Jacksonville	Florida			Garden / Outdoor	Indoor & Outdoor	200		Five acres among century-old oaks, with a 3,200 sq ft air-conditioned ballroom built in 2014 and two outdoor ceremony sites.	info@bowingoaks.com	(904) 600-5172	https://bowingoaks.com/
The Club Continental	2143 Astor St	Orange Park	Florida			Historic / Estate	Indoor & Outdoor			Riverfront estate on the St. Johns chosen by a Palmolive heir, with a mansion, gardens and ceremonies under a 300-year-old live oak.	carla@clubcontinental.com	(904) 264-6070	https://clubcontinental.com/event-facility/weddings/
Lakeside Inn	100 N Alexander St	Mount Dora	Florida			Historic / Estate	Indoor & Outdoor			Mount Dora hotel dating to 1883 on Lake Dora, with a courtyard lawn, a gazebo under the oaks, a small beach and ten event spaces.		(352) 383-4101	https://lakeside-inn.com/events/weddings/
Wanderlust Okto	6551 New Hope Rd	Orlando	Florida			Barn / Rustic	Indoor & Outdoor			Lake Nona property near the airport with a 4,000 sq ft climate-controlled barn, a pond, a treehouse and on-site stays.	info@wanderlustokto.com	(954) 937-7299	https://oktohospitalitygroup.com/
Crossing Palms	777 Alturas Rd	Bartow	Florida			Barn / Rustic	Indoor & Outdoor	350		Lakefront property of 54 acres in Polk County with a 5,000 sq ft glass barn and an outdoor pavilion, booked as all-inclusive packages.		(863) 537-6590	https://www.crossingpalmsweddings.com/weddings/
The Estate on the Halifax	5123 S Ridgewood Ave	Port Orange	Florida			Historic / Estate	Indoor & Outdoor	200		Ten-acre estate on the Halifax River with a stained-glass chapel, a lakeside gazebo and a Tavern for receptions of up to 200.	info@estateonthehalifax.com	(386) 763-2285	https://www.estateonthehalifax.com/weddings/
Innisbrook Golf Resort	36750 US Hwy 19 N	Palm Harbor	Florida			Ballroom / Hotel	Indoor & Outdoor	300		Wooded golf resort north of Clearwater with ballrooms for up to 300 each, a pool lawn and a smaller Italian-style room.		(888) 794-8627	https://www.innisbrookgolfresort.com/gatherings/weddings/venues
TradeWinds Island Grand	5500 Gulf Blvd	St. Pete Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Gulf-front resort on St. Pete Beach with over 50,000 sq ft of event space across its hotels and beach ceremony sites.		(727) 367-6461	https://www.tradewindsresort.com/weddings
The Luce	6300 Gulf Blvd	St. Pete Beach	Florida			Beach / Waterfront	Indoor & Outdoor			Beachfront hotel with 14,000 sq ft of Gulf-view event space, a Palm Court garden for ceremonies and ballrooms for receptions.	info@thelucehotel.com	(727) 632-3300	https://www.thelucehotel.com/weddings
The Addison	2 E Camino Real	Boca Raton	Florida			Historic / Estate	Indoor & Outdoor			Mizner-era Spanish-style building in Boca Raton with a fountain courtyard under century-old banyans and indoor ballrooms.		(561) 372-0568	https://www.theaddisonofbocaraton.com/weddings
Pier Sixty-Six	2301 SE 17th St	Fort Lauderdale	Florida			Beach / Waterfront	Indoor & Outdoor			Fort Lauderdale resort and marina known for its spire-topped tower, with waterfront lawns and ballrooms by the Intracoastal.	events@piersixtysixresort.com	(954) 525-6666	https://www.piersixtysixweddings.com/
Coral Gables Museum	285 Aragon Ave	Coral Gables	Florida			Historic / Estate	Indoor & Outdoor			Museum in Coral Gables' 1939 former police and fire station, with an open-air loggia, a walled garden and a public plaza for events.		(305) 603-8067	https://coralgablesmuseum.org/weddingsandprivateevents/
`,
  },
];

export default batches;
