import type { VenueBatch } from "@/lib/venue-batches";

// Georgia venue batches. Every row's State is "Georgia". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Savannah and Tybee Island",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Victory North	2603 Whitaker Street	Savannah	Georgia			Historic / Estate	Indoor & Outdoor			Converted early-1900s ice factory with a main hall and mezzanine, a sky loft with bridal suite and an urban garden courtyard for ceremonies.			https://www.victorynorthweddings.com
Bethesda Academy	9520 Ferguson Ave	Savannah	Georgia			Historic / Estate	Indoor & Outdoor			School campus with the historic Whitefield Chapel for ceremonies, plus a dining hall and grounds for receptions.		(912) 438-6600	https://www.bethesdaacademy.org
Kehoe House	123 Habersham Street	Savannah	Georgia			Historic / Estate	Indoor & Outdoor			1892 house built by an iron foundry owner, now a 13-room inn hosting elopements and small weddings in its parlour and garden courtyard.	events@verdigreenhotels.com	(912) 232-1020	https://www.kehoehouse.com/say-i-do
The Chapel by the Sea	1114 US-80	Tybee Island	Georgia			Ballroom / Hotel	Indoor & Outdoor	220		Island chapel with vaulted ceilings and arched windows beside its own Grand Ballroom, so ceremony and reception share one site.	taylor@thechapelga.com	(912) 482-0469	https://tybeeweddingchapel.com/
Hotel Tybee	1401 Strand Avenue	Tybee Island	Georgia			Beach / Waterfront	Indoor & Outdoor	110		Beachfront hotel whose GrandView Event Center looks over the Atlantic, with beachfront outdoor space and guest rooms on site.	bloehr@hoteltybee.com	(912) 786-7777	https://www.hoteltybee.com/weddings
Fort McAllister State Park	3894 Fort McAllister Road	Richmond Hill	Georgia			Beach / Waterfront	Outdoor	150		State park on the Ogeechee River around Civil War earthworks, where weddings need park approval and the group shelter seats 150.		(912) 727-2339	https://gastateparks.org/FortMcAllister
`,
  },
  {
    name: "Atlanta, Savannah, Athens and the North Georgia Mountains",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Park Tavern	500 10th St NE	Atlanta	Georgia			Restaurant / Vineyard	Indoor & Outdoor			Midtown restaurant on the edge of Piedmont Park whose Piedmont Room and garden tent look across the park to the city skyline.	Lauren@piedmontroom.com	404-249-0001	https://www.parktavern.com/weddings/
Primrose Cottage	674 Mimosa Blvd	Roswell	Georgia			Historic / Estate	Indoor & Outdoor			Restored 1839 mansion in historic Roswell with layered gardens, a front lawn and brick terrace for ceremonies, and get-ready suites.		866-966-3009	https://www.wedgewoodweddings.com/venues/primrose-cottage
The West Venue	1710 Defoor Ave NW	Atlanta	Georgia			Ballroom / Hotel	Indoor	300		Upper Westside event space pairing a grand ballroom with 30-foot ceilings and a smaller loft room with a built-in bar for ceremonies or cocktails.	info@thewestvenue.com	678-575-6695	https://www.thewestvenue.com/
Cator Woolford Gardens	1815 S Ponce de Leon Ave NE	Atlanta	Georgia			Garden / Outdoor	Outdoor	180		Former 1920s estate in Druid Hills set in 39 acres of old-growth forest and gardens, with tents, a rain plan and a wedding party suite included.	cwginfo@frazercenter.org	(404) 487-8314	https://www.catorwoolfordgardens.org/weddings-and-events
Ambient + Studio	585 Wells St SW, Unit A	Atlanta	Georgia			Ballroom / Hotel	Indoor			Industrial building in southwest Atlanta with more than 25,000 square feet of open, flexible rental space for weddings and receptions.	ambientplus.studio@gmail.com	404-436-1360	https://www.ambientplusstudio.com/
Monday Night Garage	933 Lee St SW	Atlanta	Georgia			Restaurant / Vineyard	Indoor & Outdoor			Monday Night Brewing's West End brewery on the BeltLine, where the chandelier-hung event room opens onto a courtyard for large receptions.		404.352.7703	https://mondaynightbrewing.com/garage-private-events/
The Estate	3109 Piedmont Rd NE	Atlanta	Georgia			Historic / Estate	Indoor & Outdoor			Gated Buckhead house behind a circular drive of oaks and magnolias, with an art-filled interior and landscaped grounds for outdoor ceremonies.	info@LegendaryEvents.com	404.869.8858	https://estateatlanta.com/
Shiloh Gardens	5235 Union Hill Rd	Cumming	Georgia			Garden / Outdoor	Indoor & Outdoor	284		North-metro garden venue whose event centre seats 284 for dinner, with a breezeway and covered patio, and proceeds going to Furkids animal rescue.		770-613-0880	https://shilohgardens.org/
The Wayne Mansion	204 E Hall St	Savannah	Georgia			Historic / Estate	Indoor & Outdoor			Brick mansion by Forsyth Park rented as a whole-house vacation stay, with a great room and dining room for small weddings and overnight guests.	contact@stayatarise.com	(912) 388-0845	https://www.thewaynemansion.com/weddings
The Gastonian	220 East Gaston Street	Savannah	Georgia			Historic / Estate	Indoor & Outdoor			Historic District bed and breakfast in a 19th-century guest mansion, hosting small courtyard weddings and whole-inn buyouts for guests.	concierge@gastonian.com	(912) 232-2869	https://www.gastonian.com/
Wormsloe State Historic Site	7601 Skidaway Road	Savannah	Georgia			Historic / Estate	Outdoor			State historic site on the Isle of Hope known for its mile-long avenue of live oaks, with weddings arranged through the park near the colonial tabby ruins.	wormsloe.weddings@dnr.ga.gov	912-353-3023	https://gastateparks.org/Wormsloe
The Clyde Venue	223 Martin Luther King Blvd	Savannah	Georgia			Ballroom / Hotel	Indoor			Downtown event space on Martin Luther King Jr Blvd with its own small chapel, Chapel Ann, plus bar packages for receptions.	admin@theclydevenue.com	912-581-6034	https://www.theclydevenue.com/
Savannah Botanical Gardens	1388 Eisenhower Dr	Savannah	Georgia			Garden / Outdoor	Outdoor			Botanical garden on Eisenhower Drive offering garden ceremonies and photo sessions among seasonal beds, mature trees and paths.			https://www.savannahbotanicalgarden.org/weddings
Live Wire Athens	227 W Dougherty St	Athens	Georgia			Ballroom / Hotel	Indoor & Outdoor			Downtown warehouse turned live-music hall with a stage, sound system and garden courtyard, a short walk from the University of Georgia campus.	info@livewireathens.com		https://www.livewireathens.com/weddings
The Venue on Broad	830 W Broad St	Athens	Georgia			Historic / Estate	Indoor & Outdoor			Restored building in the Reese Street Historic District with a New Orleans feel, booked alone or with the neighbouring Veranda and its patio.			https://www.venuesonbroad.com/
The Classic Center	300 North Thomas Street	Athens	Georgia			Ballroom / Hotel	Indoor	800		Downtown convention centre whose divisible ballroom seats up to 800 for dinner, with smaller rooms for 180 to 300 and help with hotel blocks.		706.357.4444	https://www.classiccenter.com/convention-center/weddings
Hadden Estate	1150 Cliff Dawson Road	Watkinsville	Georgia			Garden / Outdoor	Indoor & Outdoor	200	Luxury	Estate on a 25-acre blueberry farm outside Athens, with an Estate Room seating 200, a tented lawn for 300 and a lodge sleeping 22.		(706) 705-6132	https://haddenestate.com/weddings
Vintage Oaks Farm	6305 Hog Mountain Rd	Watkinsville	Georgia			Barn / Rustic	Indoor & Outdoor			Family-run farm venue on Highway 53 with a decorated main hall, bridal and groom's rooms, a props room of décor and Friday rehearsal access.		770-725-1999	https://vintageoaksfarms.com/
The Ashford on Main	5 Harden Hill Road	Watkinsville	Georgia			Historic / Estate	Indoor & Outdoor			Historic private estate minutes from Athens set on four acres of terraced gardens, used for ceremonies, receptions and rehearsal dinners.	hello@ashfordonmain.com	(706) 618-1993	https://www.ashfordonmain.com/
Yonah Mountain Vineyards	1717 Hwy 255 S	Cleveland	Georgia			Restaurant / Vineyard	Indoor & Outdoor			Winery in the Appalachian foothills with lawn and vineyard ceremony sites facing Yonah Mountain, a vineyard ballroom and a wine cave.		706-878-5522	https://www.yonahmountainvineyards.com/weddings
Summit Farm Weddings	3440 Roy Road	Ellijay	Georgia			Barn / Rustic	Indoor & Outdoor			Family-owned cattle farm with outdoor church pews facing the North Georgia mountains, a rustic barn and overnight accommodation.	weddings@summitfarmweddings.com	(706) 669-1883	https://summitfarmweddings.com/
Bull Mountain Lodge	135 Ridgegate Dr	Dahlonega	Georgia			Barn / Rustic				Mountain lodge outside Dahlonega hosting weddings and events, with a cabin on the property as well as the main lodge.		706-867-5831	https://www.bullmountainlodge.com/
Blue Mountain Vineyard		Dahlonega	Georgia			Restaurant / Vineyard	Indoor & Outdoor	250		Small family vineyard near Dahlonega with a hand-built event barn and farmhouse tables made on site, seating up to 250 guests.	jessica@bluemountain.events	(770) 855-1748	https://bluemountainevents.co/
White Oaks Vineyard	211 Burgundy Way	Dahlonega	Georgia			Restaurant / Vineyard	Indoor & Outdoor			130-acre vineyard an hour from Atlanta with an arbour ceremony site facing the mountains, a reception hall, bridal house and on-site bistro.	whiteoaksdahlonega@gmail.com	706-867-6697	https://whiteoaksvineyard.com/
Conley Creek Events	14 Lance Road	Blairsville	Georgia			Barn / Rustic	Indoor & Outdoor			Mountain property near Blairsville with an event barn, a wedding chapel and cabins so guests can stay on site.	info@conleycreekevents.com	706.897.3522	https://conleycreekevents.com/
`,
  },
  {
    name: "Athens, Madison and Middle Georgia",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
SpringHaus Farm	296 Russell Drive	Comer	Georgia			Barn / Rustic	Indoor & Outdoor	200	Simple	Climate-controlled white oak barn and a pine-tree ceremony site on a country property about 15 miles from Athens.		706-843-3276	https://www.shfweddings.com/
Heartland Farms Event Center	4720 Jacks Creek Road Northwest	Monroe	Georgia			Barn / Rustic	Indoor & Outdoor	200	Simple	Family-run venue on 60 acres of pasture with a farmhouse cottage, courtyard, gazebo, woodland ceremony spot and heated reception room.	heartlandfarmseventcenter@gmail.com	912-486-0024	https://www.heartlandfarmseventcenter.com/
Southern Charm Wedding & Event Venue	1012 S. Cherokee Road	Social Circle	Georgia			Barn / Rustic	Indoor & Outdoor			Rolling-hills property with an enclosed barn, a covered pavilion, a big deck and a pond-backed island pergola for ceremonies.		(678) 457-1460	https://www.southerncharmsc.com/
It's The Perfect Space for Events	1221 West Spring Street	Monroe	Georgia			Ballroom / Hotel	Indoor & Outdoor		Simple	Hourly-rate event hall in downtown Monroe with outdoor space, offering box packages that bundle decor for budget weddings.	info@itstheperfectspaceforevents.com	770-895-0111	https://www.itstheperfectspaceforevents.com/
Beautiful Beginnings Farm	3820 Reese Road	Newborn	Georgia			Barn / Rustic	Indoor & Outdoor	146	Simple	Family farm with four ceremony spots, a barn, a furnished bridal suite apartment and a string-lit pavilion, with decor included in every package.	beautifulbeginningsfarm@gmail.com	678-414-9989	https://www.beautifulbeginningsfarm.net/
The Sixty-Two	2761 Athens Highway	Madison	Georgia			Garden / Outdoor	Outdoor			Countryside wedding venue on 62 acres with a private lake and several outdoor ceremony and reception areas.	info@thesixty-two.com	678-898-5649	http://thesixty-two.com/
Historic Smithonia Farm		Colbert	Georgia			Historic / Estate	Indoor & Outdoor			Farm established in 1888 about 20 minutes from Athens, with three brick barns, a landscaped courtyard and 200 acres of pasture.	smithoniafarm@gmail.com		https://www.smithoniafarm.com/
Sowhatchet Plantation		Madison	Georgia			Historic / Estate				Renovated historic plantation in Morgan County hosting weddings and showers, with budget-friendly options for small groups.	sowhatchetplantation@gmail.com		https://www.sowhatchetplantation.com/
The Farm at Wolf Creek	475 Brent Rd	Barnesville	Georgia			Barn / Rustic	Indoor & Outdoor			Waterfront farm venue with a lakeside chapel, a barn and a farmhouse, about an hour south of Atlanta.	info@wolfcreekevents.com	(678) 379-4399	https://www.wolfcreekevents.com/
Lakeside at Five Arrow Farms	499 Hamby Lane	Social Circle	Georgia			Garden / Outdoor	Indoor & Outdoor			Lakefront stone pavilion with a fireplace and weatherproof sides, plus a bridal suite, on a large Walton County property.	lakesideatfivearrowfarms@gmail.com		https://www.lakesideatfivearrow.com/
The Farmhouse Inn at Hundred Acre Farm	1051 Meadow Ln	Madison	Georgia			Barn / Rustic	Indoor & Outdoor	225		Boutique farm stay on 26 acres with a red barn, terrace lawn and gardens, hosting weddings and events near downtown Madison.	innkeeper@thefarmhouseinn.com	706-342-7933	https://www.thefarmhouseinn.com/
The Estate at Stone Creek	5226 Ocmulgee East Boulevard	Macon	Georgia			Historic / Estate	Indoor & Outdoor			100-acre Macon property with a restored lodge of about 100 years, a private lake and a 175-year-old barn.	contact@theestateatstonecreek.com	478-341-2180	https://theestateatstonecreek.com/
`,
  },
];

export default batches;
