import type { VenueBatch } from "@/lib/venue-batches";

// Iowa venue batches. Every row's State is "Iowa". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Des Moines, Ames, Cedar Rapids, Iowa City, Davenport and Dubuque",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Rollins Mansion	2801 Fleur Dr	Des Moines	Iowa			Historic / Estate	Indoor & Outdoor			A 1920s mansion on landscaped grounds near Gray's Lake, with a garden level, great hall, terrace and a separate cottage for getting ready.	info@rollinsmansion.com	515-657-7288	https://www.rollinsmansion.com/weddings
The Keller Brick Barn	25967 T Ave	Dallas Center	Iowa			Barn / Rustic	Indoor & Outdoor	175	Simple	A climate-controlled 1930 brick barn on a family farm west of Des Moines, with a landscaped courtyard, gardens and a fire pit.	kellerbrickbarn@gmail.com	515-897-9828	https://www.kellerbrickbarn.com/weddings
Glen Oaks Country Club	1401 Glen Oaks Dr	West Des Moines	Iowa			Ballroom / Hotel	Indoor & Outdoor	300		A country club clubhouse with a ballroom, covered veranda and a lawn overlooking the golf course for ceremonies.		515-221-9000	https://www.glenoakscc.com/weddings
Bash Events & Catering	1312 Locust St	Des Moines	Iowa			Ballroom / Hotel	Indoor			A multi-level downtown event hall with bridal and groom suites, in-house catering and bar, and tables, chairs and linens included.	info@bashdsm.com	515-330-2848	https://www.bashdsm.com/weddings
Jasper Winery	2400 George Flagg Pkwy	Des Moines	Iowa			Restaurant / Vineyard				An urban winery with a tasting room and events space close to downtown Des Moines that also hosts weddings and private events.	info@jasperwinery.com	515-282-9463	https://www.jasperwinery.com/
The HarMac	411 6th Ave SE	Cedar Rapids	Iowa			Historic / Estate	Indoor & Outdoor			A 1922 hardware warehouse downtown turned industrial-style venue with two adjoining rooms, a bar, getting-ready suites and a rooftop.	hello@theharmac.com	319-895-2429	https://theharmac.com/
Reiman Gardens	1407 University Blvd	Ames	Iowa			Garden / Outdoor	Indoor & Outdoor		Simple	Iowa State University's botanical garden, with a conservatory, a garden room and outdoor ceremony spaces among its flower beds.	rentrg@iastate.edu	515-294-6356	https://reimangardens.com/weddings
The Celebration Farm	4696 Robin Woods Ln NE	Iowa City	Iowa			Barn / Rustic	Indoor & Outdoor	450		A farm north of Iowa City with a Double Round Barn, a timber-frame barn and an outdoor amphitheatre for ceremonies.	events@thecelebrationfarm.com	319-800-9212	https://thecelebrationfarm.com/
Wooden Wheel Vineyards	1179 Hwy 92	Keota	Iowa			Restaurant / Vineyard	Indoor & Outdoor	300		A restored 1860s barn on a vineyard in south-east Iowa, with a bridal suite in the loft, a patio, an arbor and a wedding gazebo.		641-636-2180	https://woodenwheelvineyards.com/weddings
Renwick Mansion	901 Tremont Ave	Davenport	Iowa			Historic / Estate	Indoor & Outdoor	150		An Italian Revival villa on four acres in Davenport with a tower, eight bedrooms to rent, and room for a tent on the grounds.	sarah@renwickmansion.net	563-484-0202	https://renwickmansion.net/weddings/
Hotel Julien Dubuque	200 Main St	Dubuque	Iowa			Ballroom / Hotel	Indoor & Outdoor	300		A historic downtown hotel on the Mississippi with a Grande Ballroom, a River Room and a river terrace.	info@hoteljuliendubuque.com	563-556-4200	https://www.hoteljuliendubuque.com/weddings-special-events
White Knot Barn	11805 R45 Hwy	Prole	Iowa			Barn / Rustic	Indoor & Outdoor			A barn on 140 acres of farmland with a vineyard, bridal suite and groom's room, about twenty minutes south of Des Moines.	kurtis@whiteknotbarn.com	515-971-0408	https://www.whiteknotbarn.com/
Eastbank Venue + Lounge	97 3rd Ave SE	Cedar Rapids	Iowa			Historic / Estate	Indoor		Classic	A restored downtown building with a ceremony and reception hall, a speakeasy-style lounge and two getting-ready lounges overlooking the river.		319-365-0759	https://www.eastbankvenue.com/
Grand River Center	500 Bell St	Dubuque	Iowa			Ballroom / Hotel	Indoor & Outdoor	600		A conference centre on the Mississippi riverfront with a Grand Ballroom, an all-glass River Room with a veranda, and a pre-function patio.		563-690-4500	https://www.grandrivercenter.com/weddings
`,
  },
  {
    name: "Des Moines metro, Cedar Rapids, Iowa City, Amana, Ames, Cedar Falls and central Iowa",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Exchange on Vine	1734 Vine Ave	Riverside	Iowa			Barn / Rustic	Indoor & Outdoor	362	Classic	A white gambrel barn with a climate-controlled ballroom, a veranda and lounge, set among ponds, fields and timber about fifteen minutes from Iowa City.	info@theexchangeonvine.com	319-214-0712	https://theexchangeonvine.com/
Rosedale Park Event Center	5977 Mt Vernon Rd SE	Cedar Rapids	Iowa			Historic / Estate	Indoor & Outdoor		Simple	A converted building that has served as a church, schoolhouse and bar, on two acres of prairie and mature trees with a gazebo and covered pavilion.		319-261-0345	https://www.rosedaleparkevents.com/
Red Acre Barn	4053 Kirkwood St	Prole	Iowa			Barn / Rustic	Indoor & Outdoor		Simple	A barn on 24 acres of countryside with a vineyard, reclaimed-wood interior and a loft, about fifteen minutes south of West Des Moines.	redacrebarn@gmail.com	319-371-8668	https://www.redacrebarn.com/
Carper Winery	4603 Dakota St	Norwalk	Iowa			Restaurant / Vineyard				A winery in Norwalk, south of Des Moines, offering Friday and Saturday ceremony-and-reception packages and a separate two-day rehearsal option.	contactus@carperwinery.com	515-491-2367	https://www.carperwinery.com/
The Monroe	1805 90th St	West Des Moines	Iowa			Ballroom / Hotel	Indoor & Outdoor	250		An event venue in West Des Moines with a ballroom, a courtyard and indoor and outdoor ceremony spaces, plus a catering kitchen and included tables and chairs.		515-519-0336	https://www.themonroevenue.com/services/weddings
The Conrad Mansion	31121 Hawk Ave	Conrad	Iowa			Historic / Estate	Indoor & Outdoor	325		A French provincial estate in central Iowa with eleven guest suites, five ceremony and reception spaces and gardens, rented for a multi-day wedding weekend.	conradmansion1@gmail.com	515-537-6420	https://www.theconradmansion.com/
Northbridge Event Center	4530 E 46th St	Des Moines	Iowa			Ballroom / Hotel	Indoor & Outdoor		Classic	An east-side Des Moines event centre with indoor and outdoor ceremony options, included tables and chairs, and three wedding packages.	info@northbridgedsm.org	515-249-2027	https://www.northbridgedsm.org/wedding
Alta House Event Center	1600 E 36th St S	Newton	Iowa			Ballroom / Hotel	Indoor & Outdoor			An event centre in Newton, east of Des Moines, with pond, park and waterfall backdrops, an on-site decor closet and a 12-passenger guest van.	info@altahouse.com	641-792-2582	https://altahouse.com/
Country Lane Lodge	29300 Prospect Cir	Adel	Iowa			Barn / Rustic	Indoor & Outdoor	360	Classic	A climate-controlled lodge on 40 tree-lined acres west of Des Moines, with a patio, swings, bag games and fire pits for guests.	events@countrylanelodgeiowa.com	515-336-9939	https://countrylanelodgeiowa.com/
Barnes' Place	20932 350th St	Adel	Iowa			Barn / Rustic	Indoor & Outdoor			A family farm of 65 acres west of West Des Moines with a barn, pond, gardens and open farmland for outdoor ceremonies.	barnes.place.ia@gmail.com	515-360-9589	https://www.barnes-place.com/weddings
The 1868 Farmhouse	1411 160th St	Boone	Iowa			Barn / Rustic	Indoor & Outdoor		Classic	A custom-built farmhouse venue near Boone with a bridal bunkhouse, getting-ready suites, fire pits, yard games and overnight rooms for nine.	hello@1868farmhouse.com		https://1868farmhouse.com/weddings
Sherwood Forest Event Center	7400 Hickman Rd	Windsor Heights	Iowa			Ballroom / Hotel	Indoor	250	Simple	A chandelier-lit event hall in Windsor Heights with a 32-foot bar, bridal suite and groom's lounge, beside a public park and trail.	info@sherwoodforesteventcenter.com	515-509-2332	https://www.sherwoodforesteventcenter.com/
Curate		Des Moines	Iowa			Ballroom / Hotel	Indoor & Outdoor	400		An East Village event venue whose 6,000 sq ft single-level Gallery Room has a wedding party suite upstairs and a marble-tile ceremony backdrop.	events@curatedsm.com	515-523-0147	https://www.curatedsm.com/
The Heights Rooftop	901 Melrose Ave	Iowa City	Iowa			Ballroom / Hotel	Indoor & Outdoor	300		An Iowa City event centre with a 5,700 sq ft ballroom, a rooftop patio and smaller rooms for rehearsals or ceremonies, close to Kinnick Stadium.	info@theheightsrooftop.com	319-569-6777	https://theheightsrooftop.com/events/wedding-venue-iowa-city/
The Olympic South Side Theater	1202 3rd St SE	Cedar Rapids	Iowa			Ballroom / Hotel	Indoor	250		A theatre venue in Cedar Rapids' NewBo district with a ballroom, stage and mezzanine, plus a bright getting-ready room with floor-length mirrors.	hello@theolympiccr.com	319-214-0392	https://www.theolympiccr.com/weddings
Windmill Hill Weddings & Events	1713 165th St	Manchester	Iowa			Barn / Rustic	Indoor & Outdoor	250		A mid-century gothic-arch barn and corncrib in Manchester with two indoor levels, patios, a gazebo and an on-site three-bedroom house for lodging.	windmillhillevents@gmail.com	319-290-5113	https://windmillhillbarn.com/
Debbie's Celebration Barn	2162 21st Ave W	Oskaloosa	Iowa			Barn / Rustic	Indoor & Outdoor	325	Simple	A 53-year-old barn in Oskaloosa with a hillside field for ceremonies, a bonfire area, a bridal suite and an octagon swing, with tables, chairs and linens included.		641-660-5535	https://debbiescelebrationbarn.com/
Hotel Millwright	800 48th Ave	Amana	Iowa			Ballroom / Hotel	Indoor	225		A hotel in the Amana Colonies whose second-floor Merino Loft in the historic weaving building has exposed brick, tall windows and room for 225 guests.	stay@hotelmillwright.com	319-838-5015	https://hotelmillwright.com/weddings/
Walker Homestead	3867 James Ave SW	Iowa City	Iowa			Restaurant / Vineyard	Indoor & Outdoor	240	Classic	An 85-acre farm with a barn, grape vines, a wood-fired kitchen and over 5,000 sq ft of covered patio and pavilion beside the outdoor ceremony grounds.	info@walker-homestead.com	319-351-4791	https://www.walker-homestead.com/private-events
The Prelude XII	20632 35th Ave	New Virginia	Iowa			Historic / Estate	Indoor & Outdoor			A European-style wedding venue, deliberately not a barn, in New Virginia about thirty minutes south of Des Moines, with indoor and outdoor spaces and open catering.		515-443-7846	https://www.thepreludexii.com/
Rustic Rose Barn	3275 400th St	Roland	Iowa			Barn / Rustic	Indoor & Outdoor		Classic	A century-old barn with hand-hewn beams and fieldstone walls on a prairie property north of Ames, rented as a three-day package.	susan@rusticrosebarn.com	515-388-4662	https://www.rusticrosebarn.com/
Prairie Links Event Center	19 Eagle Ridge Dr	Waverly	Iowa			Ballroom / Hotel	Indoor & Outdoor			A golf-course event centre in Waverly with a ballroom opening onto a patio and a purpose-built outdoor ceremony and reception space from 2019.		319-242-7675	https://www.prairielinksgolf.com/weddings/
The Black Hawk Hotel	115 Main St	Cedar Falls	Iowa			Ballroom / Hotel	Indoor	65		A historic downtown Cedar Falls hotel whose Empire Room seats 65 for weddings, with guest rooms, a bar and a full hotel buyout option.	booking@theblackhawkhotel.com	319-277-1161	https://theblackhawkhotel.com/empire-room/
Cedar Ridge Distillery & Winery	1441 Marak Rd	Swisher	Iowa			Restaurant / Vineyard	Indoor & Outdoor	200		A vineyard and distillery between Cedar Rapids and Iowa City with a temperature-controlled event centre that seats 200, outdoor terraces and a bridal suite.	events@crwine.com	319-857-4300	https://cedarridgedistillery.com/private-events/
`,
  },
];

export default batches;
