import type { VenueBatch } from "@/lib/venue-batches";

// Maryland venue batches. Every row's State is "Maryland". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Baltimore and Annapolis venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Overhills Mansion	916 S. Rolling Road	Catonsville	Maryland			Historic / Estate	Indoor & Outdoor		Classic	Century-old Catonsville mansion run by Whitehouse Caterers, with a ceremony patio for 180, a reception tent and in-house menus.		410-744-0040	https://overhillsmansion.com/weddings/
The Liriodendron	502 W Gordon Street	Bel Air	Maryland			Historic / Estate	Indoor & Outdoor	120	Simple	1898 Palladian summer home of Hopkins founding doctor Howard Kelly, with a wisteria canopy, two porticos and a fountain garden.	info@liriodendron.com	(410) 879-4424	https://liriodendron.com/weddings/
Baltimore Museum of Industry	1415 Key Highway	Baltimore	Maryland			Historic / Estate	Indoor & Outdoor			1860s oyster cannery on a five-acre harbour campus, with a waterside terrace and galleries that can open to guests.	info@thebmi.org	410.727.4808	https://www.thebmi.org/host-an-event/bmi-weddings/
The Engineers Club	11 West Mount Vernon Place	Baltimore	Maryland			Historic / Estate	Indoor			Gilded Age Garrett-Jacobs Mansion on Mount Vernon Place, home of the Engineering Society of Baltimore since 1961.		(410) 539-6914	https://www.esb.org/weddings
The Grand Baltimore	225 N Charles St	Baltimore	Maryland			Ballroom / Hotel	Indoor			Downtown events building with 19 ballrooms across 45,000 square feet and its own inner chapel.		(410) 826-5368	https://thegrandbaltimore.com/weddings/
Evergreen Museum & Library	4545 N. Charles Street	Baltimore	Maryland			Historic / Estate	Indoor & Outdoor	170	Classic	Garrett family country house of 1878 to 1952, with a fountain terrace, gardens and a brick carriage house with a tented patio.	privateeventsoffice@jhu.edu	(443) 840-9585	https://evergreenevents.library.jhu.edu/rental-information/weddings-at-the-evergreen/
Hotel Revival	101 West Monument St	Baltimore	Maryland			Ballroom / Hotel	Indoor & Outdoor	75		Mount Vernon boutique hotel with event rooms for up to 75 and a rooftop Garden Room for 45.	info@hotelrevivalbaltimore.com	410-727-7101	https://hotelrevivalbaltimore.com/meetings-events/weddings
Kent Island Resort	500 Kent Manor Drive	Stevensville	Maryland			Barn / Rustic	Indoor & Outdoor	275		Resort around a historic manor house on Thompson Creek, with a barn-style Farmstead, a sailcloth Pavilion and a waterside Garden House.	events@kentislandresort.com	(410) 643-5757	https://www.kentislandresort.com/weddings/
Chesapeake Bay Beach Club	500 Marina Club Road	Stevensville	Maryland			Beach / Waterfront	Indoor & Outdoor	310		Bayfront resort past the Bay Bridge with four ballrooms, the largest for 310, and guest rooms across four properties.		(410) 604-5900	https://www.baybeachclub.com/weddings
Tidewater Inn	101 East Dover St.	Easton	Maryland			Ballroom / Hotel	Indoor			Downtown Easton hotel of 86 rooms with two ballrooms and a carriage house a block away at the Tidewater House.	mbennett@tidewaterinn.com	410.822.1300	https://tidewaterinn.com/weddings
Chesapeake Bay Maritime Museum	213 N. Talbot St.	St. Michaels	Maryland			Beach / Waterfront	Indoor & Outdoor			18-acre museum campus on the Miles River with over 2,000 feet of waterfront, a boat shed and cove-side lawns.	lclark@cbmm.org	410.745.4998	https://www.cbmmweddings.com/
Kurtz's Beach	2070 Kurtz Avenue	Pasadena	Maryland			Beach / Waterfront	Indoor & Outdoor	240		Family-run bayfront grounds in Pasadena with the Bay Room ballroom, a gazebo lawn, pavilions and dressing cottages.	info@kurtzsbeach.com	(410) 255-1280	https://www.kurtzsbeach.com/waterfront-weddings-banquets-maryland/
Celebrations at the Bay	2042 Knollview Ave	Pasadena	Maryland			Beach / Waterfront	Indoor & Outdoor	400		All-inclusive Chesapeake Bay venue with a ballroom, a tented ballroom and the smaller Knollview House.	info@celebrationsatthebay.com	301-572-7744	https://www.celebrationsatthebay.com/
Annapolis Waterfront Hotel	80 Compromise Street	Annapolis	Maryland			Ballroom / Hotel	Indoor & Outdoor	450		Downtown hotel on Annapolis Harbor with a ballroom and harbourside patio, each for up to 450.		888-773-0786	https://www.annapoliswaterfront.com/gatherings/weddings-occasions`,
  },
  {
    name: "Baltimore and Annapolis venues, second batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Historic Savage Mill	8600 Foundry Street	Savage	Maryland			Historic / Estate	Indoor			Restored 19th-century textile mill with a Great Room overlooking the river under high ceilings and a small Rosebud room for elopements.	info@savagemill.com	410-792-2820	https://www.savagemill.com/explore/weddings
Grey Rock Mansion	400 Grey Rock Road	Pikesville	Maryland			Historic / Estate	Indoor & Outdoor	250	Classic	1858 Baltimore County manor with a ballroom, a year-round tent, porches and a garden ceremony spot with a gazebo and fountain.	greyrockmansion@gmail.com	410-486-5621	https://www.greyrockmansion.com/weddings-parties/
Union Mills Homestead	3311 Littlestown Pike	Westminster	Maryland			Historic / Estate	Indoor & Outdoor	150		Late-1700s Carroll County homestead with a grist mill, a 1797 tannery used for receptions, and gardens with a goldfish pond and wooden bridge for ceremonies.		410-848-2288	https://unionmills.org/weddings/
Valley Mansion by Martin's	594 Cranbrook Road	Hunt Valley	Maryland			Ballroom / Hotel	Indoor			Large banquet house run by Martin's Caterers with three ballrooms that combine into more than 16,000 square feet, sweeping staircases and in-house catering.		(410) 666-1234	https://www.martinscaterers.com/locations/valley-mansion/
Martin's West	6817 Dogwood Road	Baltimore	Maryland			Ballroom / Hotel	Indoor & Outdoor			Martin's Caterers venue in western Baltimore County with six ballrooms from 1,600 to over 18,000 square feet, a multi-storey lobby and outdoor gazebos.		(410) 944-9433	https://www.martinscaterers.com/locations/west/
George Peabody Library	17 East Mount Vernon Place	Baltimore	Maryland			Historic / Estate	Indoor	170	Classic	Johns Hopkins research library in Mount Vernon with six tiers of cast-iron columns and balconies plus an adjoining exhibit gallery, booked for evening receptions with a catered meal.	privateeventsoffice@jhu.edu	(443) 840-9585	https://peabodyevents.library.jhu.edu/rental-information/weddings-2/
Historic Oakland	5430 Vantage Point Road	Columbia	Maryland			Historic / Estate	Indoor & Outdoor	180		1811 Howard County manor on three floors with a ballroom opening onto a veranda, a secluded garden under a magnolia, and a seasonal tent on the back lawn; bring your own caterer.		(410) 730-4801	https://www.historic-oakland.com/weddings-events/
Annapolis Maritime Museum & Park	723 Second Street	Annapolis	Maryland			Beach / Waterfront	Indoor & Outdoor			Eastport maritime museum on Back Creek with Bay views, a separate 12-acre waterfront park campus with a dock, and a 1940 skipjack available for wedding sails.	office@amaritime.org	410-295-0104	https://amaritime.org/weddings/
Wylder Hotel Tilghman Island	21551 Chesapeake House Drive	Tilghman	Maryland			Beach / Waterfront	Indoor & Outdoor	250		Fifty-room hotel on 9.5 acres with 1,100 feet of Bay shoreline, a private beach and ceremony platform, a waterfront ballroom and a lawn for tented receptions.	GuestServicesTI@WylderHotels.com	410.886.2121	https://wylderhotels.com/tilghman-island/weddings/
Chesapeake Inn	605 2nd Street	Chesapeake City	Maryland			Restaurant / Vineyard	Indoor & Outdoor			Waterfront restaurant and marina in Chesapeake City with a ballroom for receptions and help arranging outdoor ceremonies at nearby garden sites.	info@chesapeakeinn.com	(410) 885-2040	https://www.chesapeakeinn.com/weddings/
Brittland Manor		Chestertown	Maryland			Historic / Estate	Indoor & Outdoor	400	Luxury	Georgian-style manor on more than 500 acres along the Chester River, with five ceremony spots, a brick patio for tented receptions and lodging for 41 in the manor and river lodge.	info@brittlandestates.com	443-282-0860	https://www.brittlandestates.com/brittland-manor
Historic Inns of Annapolis	58 State Circle	Annapolis	Maryland			Ballroom / Hotel	Indoor & Outdoor	400		Group of historic inns in the Annapolis Historic District with seven indoor and outdoor event spaces, including Governor's Hall and its garden terrace, plus in-house catering and room blocks.	reservations@historicinnsofannapolis.com	410-263-2641	https://www.historicinnsofannapolis.com/weddings
Anchor Inn	7617 Water Oak Point Road	Pasadena	Maryland			Beach / Waterfront	Indoor & Outdoor	200		Waterfront hall run by Catering by Uptown, set over the water on Rock Creek with views out to the Chesapeake Bay and all-inclusive wedding packages.	info@anchorinnmd.com	301-572-7744	https://www.anchorinnmd.com/
Atlantic Hotel	2 North Main Street	Berlin	Maryland			Ballroom / Hotel	Indoor & Outdoor			Victorian hotel in downtown Berlin with guest rooms, on-site catering and a ballroom with antique crystal chandeliers, original stained glass and a fireplace, near the Assateague beaches.	info@atlantichotel.com	410-641-1234	https://atlantichotel.com/weddings-and-events/`,
  },
];

export default batches;
