import type { VenueBatch } from "@/lib/venue-batches";

// Massachusetts venue batches. Every row's State is "Massachusetts". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Cape Cod, the Islands and the Boston shores",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Heritage Museums & Gardens	67 Grove Street	Sandwich	Massachusetts			Garden / Outdoor	Indoor & Outdoor			Public gardens in Sandwich with rhododendron and hydrangea collections, nature trails and museums holding a historic carousel and a car collection.	info@heritagemuseums.org	508-888-3300	https://heritagemuseumsandgardens.org/
Highfield Hall & Gardens	56 Highfield Drive	Falmouth	Massachusetts			Historic / Estate	Indoor & Outdoor			Restored Falmouth estate and arts centre with gardens and walking trails, bordered by protected conservation forest.	info@highfieldhall.org	(508) 495-1878	https://highfieldhallandgardens.org/
The Coonamessett	311 Gifford Street	Falmouth	Massachusetts			Ballroom / Hotel	Indoor & Outdoor	300		Falmouth inn on Jones Pond with a 300-guest ballroom, smaller hall and garden rooms, and a deck over the water for ceremonies.	stay@thecoonamessett.com	(508) 548-2300	https://www.larkhotels.com/massachusetts/cape-cod/falmouth/the-coonamessett/weddings
Winnetu Oceanside Resort	31 Dunes Rd	Edgartown	Massachusetts			Beach / Waterfront	Indoor & Outdoor			Martha's Vineyard resort at South Beach with lawn ceremonies, an ocean-view deck, tented or indoor receptions and one- to four-bedroom suites on site.	events@winnetu.com	508.310.1733	https://www.winnetu.com/weddings
The Wauwinet	120 Wauwinet Road	Nantucket	Massachusetts			Beach / Waterfront	Indoor & Outdoor			Nantucket inn first opened in 1875, with an oceanfront lawn, two private beaches and its own restaurant.	reservations@wauwinet.com	508-228-0145	https://www.wauwinet.com/weddings
Lambert's Cove Inn	90 Manaquayak Road	West Tisbury	Massachusetts			Historic / Estate	Indoor & Outdoor			Inn on a former farm in rural up-island Martha's Vineyard, with gardens, its own restaurant and access to Lambert's Cove Beach.		508-422-8051	https://www.lambertscoveinn.com/marthas-vineyard-hotel-weddings
The Red Inn	15 Commercial St	Provincetown	Massachusetts			Restaurant / Vineyard	Indoor & Outdoor			Waterfront inn and restaurant in Provincetown, looking over the harbour and Cape Cod Bay towards the Long Point lighthouse.		(508) 487-7334	https://theredinn.com/special-events/
Dan'l Webster Inn & Spa	149 Main Street	Sandwich	Massachusetts			Historic / Estate	Indoor			Colonial-style inn in the centre of Sandwich, Cape Cod's oldest town, with 48 rooms and suites, a conservatory dining room and a spa.	info@danlwebsterinn.com	(508) 888-3622	https://danlwebsterinn.com/weddings/
The Club at New Seabury	95 Shore Drive West	Mashpee	Massachusetts			Beach / Waterfront	Indoor & Outdoor			Golf and beach club on Nantucket Sound offering a beachfront tent at the Popponesset Inn or a ballroom with a deck over the golf course.		508-539-8322	https://www.newseabury.com/web/pages/weddings
Whaling Museum & Roofwalk	15 Broad Street	Nantucket	Massachusetts			Historic / Estate	Indoor & Outdoor	120		Nantucket Historical Association museum with a whale skeleton in the main hall, an 1847 brick candle factory and a rooftop deck over the harbour.		508-228-1894	https://nha.org/visit/private-events/venue-options/whaling-museum/
Tupper Manor	295 Hale Street	Beverly	Massachusetts			Historic / Estate	Indoor & Outdoor	190		Georgian mansion on ten oceanfront acres at Endicott College, with a conservatory, fountain lawns and the 91-room Wylie Inn next door.		978-867-1800	https://www.tuppermanor.com/
Hammond Castle Museum	80 Hesperus Avenue	Gloucester	Massachusetts			Historic / Estate	Indoor & Outdoor			Medieval-style stone castle and museum on the Gloucester shore, used for elopements, small celebrations and larger weddings.		(978) 283-2080	https://hammondcastle.org/weddings/
Turner Hill	3 Manor House Lane	Ipswich	Massachusetts			Historic / Estate	Indoor & Outdoor			Golf club on about 350 acres built around a 1903 mansion, with a separate ballroom and overnight rooms in The Butler's House.		(978) 356-7070	https://www.turnerhill.com/
Danversport	161 Elliott Street	Danvers	Massachusetts			Beach / Waterfront	Indoor & Outdoor			Large waterfront function hall beside a marina in Danvers, with a ballroom and a ceremony area facing the water.		978.774.8622	https://www.danversport.com/
Granite Links Golf Club	100 Quarry Hills Drive	Quincy	Massachusetts			Ballroom / Hotel	Indoor & Outdoor			Hilltop golf club in Quincy with several ballrooms, a pavilion tent, pergola and balconies looking across the course to the Boston skyline.		617-689-1900	https://www.granitelinks.com/weddings
Hotel 1620 Plymouth Harbor	180 Water St	Plymouth	Massachusetts			Ballroom / Hotel	Indoor & Outdoor			Plymouth harbourfront hotel with over 15,000 square feet of event space, waterfront ceremonies and guest rooms on site.	Tomanderson@hotel1620.com	(508) 747-4900	https://www.hotel1620.com/weddings
Misselwood	407 Hale Street	Beverly	Massachusetts			Historic / Estate	Indoor & Outdoor			Oceanfront estate owned by Endicott College, pairing a historic mansion with tented receptions on the grounds.	misselwoodevents@endicott.edu	978-232-2128	https://misselwood.endicott.edu/
The Garden at Elm Bank	900 Washington Street	Wellesley	Massachusetts			Garden / Outdoor	Indoor & Outdoor			Massachusetts Horticultural Society's 36-acre garden with twelve display gardens, open lawns for tents and indoor rooms in the Hunnewell Building.	functions@masshort.org	617-933-4921	https://www.masshort.org/weddings-events/weddings
Duxbury Bay Maritime School	457 Washington St	Duxbury	Massachusetts			Beach / Waterfront	Indoor & Outdoor	160		Sailing school on Duxbury Bay whose hall has hardwood floors and large windows over the water, with indoor and outdoor spaces for ceremony and reception.		(781) 934-7555	https://www.dbms.org/weddings
Glen Magna Farms	29 Ingersoll Street	Danvers	Massachusetts			Garden / Outdoor	Indoor & Outdoor	200		Historic mansion and gardens run by the Danvers Historical Society, with receptions for up to 200 in a clear-sided sailcloth tent.	info@glenmagnafarms.org	978-774-9165	https://glenmagnafarms.org/weddings/`,
  },
  {
    name: "Massachusetts: Berkshires, Pioneer Valley, Boston and South Coast",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Mount	2 Plunkett St	Lenox	Massachusetts			Historic / Estate	Outdoor			Edith Wharton's Berkshires estate on nearly 50 acres, with ceremonies in its French and Italian formal gardens and cocktails on a terrace facing the hills.	info@edithwharton.org	413-551-5106	https://edithwharton.org/weddings/
Log Cabin	500 Easthampton Rd	Holyoke	Massachusetts			Ballroom / Hotel	Indoor & Outdoor	400		Pioneer Valley banquet complex looking out to Mt. Tom, with the Log Cabin, Upper Vista and Delaney House ballrooms and hotel suites on site.		413-535-5077	https://www.logcabin-delaney.com/weddings
Longfellow's Wayside Inn	72 Wayside Inn Rd	Sudbury	Massachusetts			Historic / Estate	Indoor & Outdoor	200		Inn dating from 1716 on more than 100 acres with nine historic buildings, a chapel, a grist mill and a seasonal event tent.	functions@wayside.org	978-443-1776	https://www.wayside.org/weddings
State Room	60 State St	Boston	Massachusetts			Ballroom / Hotel	Indoor	560		Event floors at the top of a downtown Boston tower, with windows giving 270-degree views over the harbour and city.			https://longwoodvenues.com/venues/boston-event-venue-2/
White's of Westport	66 State Rd	Westport	Massachusetts			Ballroom / Hotel	Indoor			South Coast function hall in Westport, running since 1955, with several function rooms for weddings of different sizes.	whites@lafrancehospitality.com	508-675-7185	https://www.whitesofwestport.com/
Sea Crest Beach Resort	350 Quaker Rd	North Falmouth	Massachusetts			Beach / Waterfront	Indoor & Outdoor	250		Cape Cod resort on Old Silver Beach and Buzzards Bay, with two ballrooms, an oceanfront courtyard and beach ceremonies.		508-540-9400	https://www.seacrestbeachresort.com/weddings`,
  },
  {
    name: "Massachusetts: Berkshires, Worcester County, Boston and Cape Cod",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Barrington Hall	426 Stockbridge Road	Great Barrington	Massachusetts			Ballroom / Hotel	Indoor & Outdoor	300		Great Barrington event hall of 4,500 square feet with a lawn, patio and A-frame ceremony spot, where couples bring their own caterer to its kitchen.	events@barringtonhallgb.com	(413) 645-3116	https://www.barringtonhallgb.com/weddings
Stonover Farm	169 Under Mountain Road	Lenox	Massachusetts			Barn / Rustic	Indoor & Outdoor	175		Five-suite inn on ten acres in Lenox, with ceremonies on the barn ramp, cocktails by the pond and dinner in a barn seating 175.	stonoverfarm@stonoverfarm.com	(413) 637-9100	https://www.stonoverfarm.com/events
Bloom Meadows	2422 Hancock Road	Williamstown	Massachusetts			Barn / Rustic	Indoor & Outdoor	170		Williamstown venue with a white shiplap barn for 170, a glass-walled chapel facing the meadow and mountains, and a Silo Suite for the couple.	info@bloommeadows.com	413-458-4003	https://www.bloommeadows.com/thevenue
Gedney Farm	34 Hartsville-New Marlborough Road	New Marlborough	Massachusetts			Barn / Rustic	Indoor & Outdoor			Turn-of-the-century gentleman's dairy farm in New Marlborough with a renovated event barn and loft, a hilltop ceremony knoll and lodging on site.	frontdesk@gedneyfarm.com	413-229-3131	https://www.gedneyfarm.com/weddings-private-parties
Hotel on North	297 North Street	Pittsfield	Massachusetts			Ballroom / Hotel	Indoor			Boutique hotel in a former 19th-century haberdashery on Pittsfield's main street, hosting receptions, rehearsal dinners and farewell brunches.	info@hotelonnorth.com	(413) 358-4741	https://www.hotelonnorth.com/meet-gather/weddings-celebrations
Bousquet Mountain	101 Dan Fox Dr	Pittsfield	Massachusetts			Garden / Outdoor	Indoor & Outdoor			Pittsfield ski area with a light-filled lodge, fireplaces and a patio, and a mountaintop ceremony spot looking towards Mount Greylock.	Info@bousquetmountain.com	413-442-8985	https://bousquetmountain.com/weddings/
Jiminy Peak Mountain Resort	37 Corey Rd	Hancock	Massachusetts			Ballroom / Hotel	Indoor & Outdoor			Berkshires ski resort with an alpine village of courtyards, banquet rooms and lodging, and mountaintop ceremonies above the valley.		(413) 738-5500	https://www.jiminypeak.com/weddings-events/weddings/
The Inn at Stockbridge	30 East Street	Stockbridge	Massachusetts			Historic / Estate	Indoor & Outdoor	50	Simple	Ten-acre Stockbridge inn with cottage gardens and patios, offering micro-wedding packages for up to 50 guests and rooms for about 32 overnight.		(413) 298-3337	https://www.stockbridgeinn.com/events/
MASS MoCA	1040 MASS MoCA Way	North Adams	Massachusetts			Historic / Estate	Indoor			Contemporary art museum on a former factory campus in North Adams, renting its 250,000 square feet of galleries and buildings for weddings.	info@massmoca.org	413.662.2111	https://massmoca.org/host-event-rent-space/
Publick House Historic Inn	277 Main Street	Sturbridge	Massachusetts			Historic / Estate	Indoor & Outdoor	220		Sturbridge inn with Paige Hall and a historic barn for up to 190, a seasonal garden tent for 220, and rooms across four lodging houses.	sales@publickhouse.com	508-347-7323	https://publickhouse.com/weddings/
Beechwood Hotel	363 Plantation Street	Worcester	Massachusetts			Ballroom / Hotel	Indoor & Outdoor			Worcester boutique hotel with over 8,000 square feet of wedding space, including the cathedral-ceilinged Maria Gill Wilson Chapel and seasonal outdoor sites.		(508) 754-5789	https://www.beechwoodhotel.com/weddings.htm
Mechanics Hall	321 Main Street	Worcester	Massachusetts			Historic / Estate	Indoor	400		Worcester concert hall from 1857 whose Great Hall, with a coffered ceiling and Hook organ, holds dinner and dancing for up to 400.	events@mechanicshall.org	(508) 752-5608	https://mechanicshall.org/booking/weddings/
Wachusett Mountain	499 Mountain Road	Princeton	Massachusetts			Garden / Outdoor	Indoor & Outdoor			Princeton ski area hosting weddings in a tent or on a deck on its lawns, in the Granite Room or base lodge, or up at the summit.	info@wachusett.com	978-464-3175	https://www.wachusett.com/meetings-weddings/weddings/
Salem Cross Inn	260 West Main Street	West Brookfield	Massachusetts			Barn / Rustic	Indoor & Outdoor	200		Colonial farmhouse and post-and-beam barn on 600 acres of farmland, with the barn and loft holding up to 200 and horse-drawn rides in season.		508-867-2345	https://salemcrossinn.com/weddings/
Worcester Art Museum	55 Salisbury Street	Worcester	Massachusetts			Historic / Estate	Indoor			Worcester art museum whose Renaissance Court and galleries host ceremonies and receptions among the collection.		508-799-4406	https://www.worcesterart.org/venue-rental/weddings/
Indian Ranch	200 Gore Road	Webster	Massachusetts			Beach / Waterfront	Indoor & Outdoor	176		Lakeside venue on Webster Lake with Samuel Slater's function hall seating 176 in rounds, a waterfront room for 120 and a paddle-wheeler for cruises.		(508) 943-3871	https://indianranch.com/private-events/
Fruitlands Museum	102 Prospect Hill Road	Harvard	Massachusetts			Historic / Estate	Outdoor	192	Classic	Trustees museum founded in 1843 on over 200 acres above the Nashua River Valley, with lawn ceremonies and tented receptions for up to 192.			https://thetrustees.org/content/fruitlands-venue-rental/
Fern Hill Barn	89 Smithville Road	Spencer	Massachusetts			Barn / Rustic	Indoor & Outdoor	250	Classic	Family-owned hilltop farm in Spencer run as a Wedgewood Weddings venue for up to 250, with all-inclusive packages covering catering and bar.			https://www.wedgewoodweddings.com/venues/fern-hill-barn
Larz Anderson Auto Museum	15 Newton Street	Brookline	Massachusetts			Historic / Estate	Indoor & Outdoor	500		1888 carriage house in Larz Anderson Park holding a car collection, with dinner for 100 in the Main Gallery or tented events on the Great Lawn.	functions@larzanderson.org	617-522-6547	https://www.larzanderson.org/functions
Gore Place	52 Gore Street	Waltham	Massachusetts			Historic / Estate	Indoor & Outdoor			Working farm of over 50 acres around an 1806 Federal-style mansion, with receptions in the Carriage House or a tent and a timber-frame barn backdrop.		781-894-2798	https://goreplace.org/rentals/weddings
Eleanor Cabot Bradley Estate	2468B Washington Street	Canton	Massachusetts			Garden / Outdoor	Indoor & Outdoor	150		Ninety-acre Trustees estate in Canton with a formal parterre garden, pond and mansion, and dinner and dancing under a sailcloth tent.			https://thetrustees.org/content/bradley-estate-venue-rental/
The Lighthouse Inn	1 Lighthouse Inn Road	West Dennis	Massachusetts			Beach / Waterfront	Indoor & Outdoor			Oceanfront inn in West Dennis with lawn ceremonies looking over Nantucket Sound and an indoor room to fall back on in bad weather.	inquire@lighthouseinn.com	(508) 398-2244	https://lighthouseinn.com/weddings/
Chequessett Club	680 Chequessett Neck Rd	Wellfleet	Massachusetts			Beach / Waterfront	Indoor & Outdoor	165		Wellfleet golf and sailing club with beach ceremonies, a barn-style boathouse over the harbour and a clear-sided waterfront tent for 165.	events@chequessettclub.com	508-349-3704	https://chequessettclub.com/weddings/
Red Jacket Beach Resort	1 S Shore Dr	South Yarmouth	Massachusetts			Beach / Waterfront	Indoor & Outdoor	150		South Yarmouth resort on Nantucket Sound with a private beach, an oceanfront lawn, a tented beach pavilion and a ballroom renovated in 2024.	sales@redjacketresorts.com		https://www.redjacketresorts.com/resorts/beach-resort/weddings`,
  },
  {
    name: "Massachusetts: Boston, North Shore, Pioneer Valley, Berkshires and South Coast",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Pierce House	17 Weston Road	Lincoln	Massachusetts			Historic / Estate	Indoor & Outdoor	200		A town-owned vintage estate on about thirty acres of lawns, woodlands and ponds, with a mansion and a tent space.	jenn@piercehouse.com	781-259-9757	https://piercehouse.com/
Inn at Hastings Park	2027 Massachusetts Avenue	Lexington	Massachusetts			Ballroom / Hotel	Indoor & Outdoor			A boutique inn on Lexington's main road with a bistro, porch and gallery rooms plus lawn, garden and pavilion spaces for ceremonies.			https://www.innathastingspark.com/gather/our-venues/
Multicultural Arts Center	41 Second Street	Cambridge	Massachusetts			Historic / Estate	Indoor & Outdoor	200	Classic	A Victorian-style East Cambridge building with a theater, gallery, kitchen and an arbor courtyard in Centanni Park.	info@multiculturalartscenter.org	617-577-1400	https://multiculturalartscenter.org/venue/
Somerville Museum	One Westwood Road	Somerville	Massachusetts			Historic / Estate	Indoor	100	Simple	A local history museum whose renovated Pisa Gallery holds a Bulfinch staircase dating from 1792.	events@somervillemuseum.org	617-666-9810	https://www.somervillemuseum.org/rental-opportunities-1
Hawthorne Hotel	18 Washington Square West	Salem	Massachusetts			Ballroom / Hotel	Indoor			A hotel on Salem Common that hosts weddings and social events in its banquet rooms.	info@hawthornehotel.com	978-744-4080	https://www.hawthornehotel.com/weddings-social-events/
Hamilton Hall	9 Chestnut Street	Salem	Massachusetts			Historic / Estate	Indoor			A red brick historic hall on Salem's Chestnut Street with a ballroom, rented for weddings and other events.	info@hamiltonhall.org	978-744-0805	https://www.hamiltonhall.org
Salem Waterfront Hotel & Suites	225 Derby Street	Salem	Massachusetts			Beach / Waterfront	Indoor & Outdoor	220		A harbourside hotel near Pickering Wharf with a ballroom for receptions and an outdoor ceremony green.		978-740-8788	https://salemwaterfronthotel.com/weddings/
Peabody Essex Museum	161 Essex Street	Salem	Massachusetts			Historic / Estate	Indoor & Outdoor	300		A museum in downtown Salem whose atrium, historic ballroom, galleries and garden are rented for weddings.	events@pem.org	978-542-1615	https://pem.org/event-rentals
Andover Country Club	60 Canterbury Street	Andover	Massachusetts			Ballroom / Hotel	Indoor & Outdoor			A golf club in Andover with ballrooms and outdoor scenery used for wedding receptions.		978-475-1263	https://www.andovercountryclub.com/
Andover Inn	4 Chapel Avenue	Andover	Massachusetts			Historic / Estate	Indoor & Outdoor			A historic inn on the Phillips Academy campus offering an indoor celebration space and landscaped grounds for ceremonies.	frontdesk@andoverinn.com	978-775-4900	https://www.andoverinn.com/
Boston Harbor Hotel	70 Rowes Wharf	Boston	Massachusetts			Beach / Waterfront	Indoor	250		A waterfront hotel at Rowes Wharf with four event rooms looking onto the harbour or the city.		617-439-7000	https://www.bostonharborhotel.com/weddings
Concord's Colonial Inn	48 Monument Square	Concord	Massachusetts			Historic / Estate	Indoor	125		A historic inn on Monument Square in Concord whose function rooms host weddings with on-site event coordinators.	colonial@concordscolonialinn.com	978-369-9200	https://www.concordscolonialinn.com/
The Liberty Hotel	215 Charles Street	Boston	Massachusetts			Ballroom / Hotel	Indoor			A hotel on Charles Street in Boston with meeting and event spaces used for weddings.		617-224-4000	https://www.libertyhotel.com/
Hotel Commonwealth	500 Commonwealth Avenue	Boston	Massachusetts			Ballroom / Hotel	Indoor & Outdoor	600		A hotel in Kenmore Square with over 12,500 square feet of event space, including a ballroom and an outdoor terrace.	sales@hotelcommonwealth.com	617-532-5066	https://www.hotelcommonwealth.com/weddings
Custom House Maritime Museum	25 Water Street	Newburyport	Massachusetts			Beach / Waterfront	Outdoor			A historic waterfront museum in Newburyport whose river-facing lawn takes a wedding tent.	info@thechmm.org	978-462-8681	https://customhousemaritimemuseum.org/
Harding Allen Estate	59 Allen Drive	Barre	Massachusetts			Historic / Estate	Indoor & Outdoor			A 1920s estate house with a ballroom, a pergola ceremony space and gardens for the cocktail hour.	events@hardingallenestate.com		https://www.hardingallenestate.com
Inn on Boltwood	30 Boltwood Avenue	Amherst	Massachusetts			Ballroom / Hotel	Indoor & Outdoor	180		A hotel on Amherst Common beside Amherst College, with a ballroom, a garden tent and a rooftop terrace.		413-256-8200	https://www.innonboltwood.com
Union Station Banquets	125 Pleasant Street	Northampton	Massachusetts			Historic / Estate	Indoor			A former railway station beside the Amtrak platform, now a banquet hall with a wedding suite and a ballroom lounge for the social hour.	sales@unionstationbanquets.com	(413) 287-6872	https://www.unionstationbanquets.com/weddings/
Tekoa Country Club	459 Russell Road	Westfield	Massachusetts			Ballroom / Hotel	Indoor			A championship golf course in the foothills of the Berkshires that hosts wedding receptions.		(413) 568-1636	https://www.tekoacc.com
Storrowton Carriage House	1305 Memorial Avenue	West Springfield	Massachusetts			Historic / Estate	Indoor			A banquet hall across Storrowton Green from the historic tavern, with a covered patio, chandeliers and a private bridal suite.	info@storrowton.com	(413) 732-4188	https://www.storrowton.com
Greylock WORKS	508 State Road	North Adams	Massachusetts			Historic / Estate	Indoor			A former cotton-spinning mill whose Weave Shed and smaller Engine House are used for events.	work@greylockworks.com		https://www.greylockworks.com
Tuckerman Hall	10 Tuckerman Street	Worcester	Massachusetts			Historic / Estate	Indoor	200		A neo-classical hall designed in 1902 by Josephine Wright Chapman.		508-754-1234	https://www.tuckermanhall.com
Worcester Art Museum	55 Salisbury Street	Worcester	Massachusetts			Historic / Estate	Indoor			A museum where receptions are held in the tiled Renaissance Court and guests can walk through the galleries.		(508) 799-4406	https://www.worcesterart.org/rentals/weddings
Hotel Northampton	36 King Street	Northampton	Massachusetts			Ballroom / Hotel	Indoor			A downtown hotel with a Grand Ballroom of arched windows and a smaller Junior Ballroom that can also host a ceremony.		(413) 587-8106	https://www.hotelnorthampton.com/weddings
Stonehouse On The Hill	314 Stonehouse On The Hill	Holden	Massachusetts			Historic / Estate	Outdoor			A country estate with a stone house as its focal point, used for outdoor weddings by appointment.	events@stonehouseonthehill.com	(508) 859-0221	https://www.stonehouseonthehill.com
Chatham Bars Inn	297 Shore Road	Chatham	Massachusetts			Beach / Waterfront	Indoor & Outdoor			Oceanfront resort that hosts one wedding a day, with a private beach for ceremonies and lawn, tented and indoor reception spaces.	welcome@chathambarsinn.com	508-945-0096	https://www.chathambarsinn.com/weddings
Coonamessett Farm	277 Hatchville Road	East Falmouth	Massachusetts			Barn / Rustic	Outdoor			Twenty-acre working farm in East Falmouth that holds weddings and large parties around a wedding pavilion and grape arbor.	events@coonamessett.net	(508) 563-2560	https://www.coonamessettfarm.com/weddings-and-large-eventsnew-page
The Pavilion at Pinehills Golf Club	54 Clubhouse Drive	Plymouth	Massachusetts			Restaurant / Vineyard	Indoor			Rustic-style clubhouse with vaulted ceilings, exposed beams and windows over the golf course.		508-209-3000	https://www.pinehillsgolf.com/weddings
Waypoint Event Center	185 MacArthur Drive	New Bedford	Massachusetts			Historic / Estate	Indoor			Refurbished whaling-era building with original 1830s stone and wood features, now used for weddings and other events.	waypoint@lafrancehospitality.com	(774) 634-2009	https://www.waypointeventcenter.com
Rachel's Lakeside	950 State Road	Dartmouth	Massachusetts			Garden / Outdoor	Indoor & Outdoor			Venue beside Lake Noquochoke with customisable spaces and menus for weddings and other celebrations.	rachels@lafrancehospitality.com	(508) 636-4044	https://www.rachelslakeside.com`,
  },
  {
    name: "Boston, Cape Cod and South Coast: historic estates, country clubs and waterfront",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Castle Hill on the Crane Estate	290 Argilla Road	Ipswich	Massachusetts			Historic / Estate	Outdoor			A coastal estate whose Great House looks along the Grand Allée to Crane Beach, with an Italian Garden and a separate barn beside salt marshes and tidal rivers.	castlehill@thetrustees.org	978-356-4351	https://thetrustees.org/place/castle-hill-on-the-crane-estate/
The Old Manse	269 Monument Street	Concord	Massachusetts			Historic / Estate	Outdoor	50		A Georgian-style clapboard house of 1770 on the Concord River, where ceremonies are held in the apple orchard and riverfront after 5 p.m.	oldmanse@thetrustees.org	978-369-3909	https://thetrustees.org/place/the-old-manse/
Smith Barn at Felton-Smith Historic Site	38 Felton Street	Peabody	Massachusetts			Barn / Rustic	Indoor & Outdoor	240		A heated and air-conditioned barn on a hilltop within about 250 acres of orchards and conservation land, with Woodland Gardens across the road for ceremonies.	info@peabodyhistorical.org	978-531-0805	https://peabodyhistorical.org/weddings/
The River Club	78 Border Street	Scituate	Massachusetts			Restaurant / Vineyard	Indoor & Outdoor	300		A stone-fireplaced hall with vaulted ceilings, a wrap-around deck, and an outdoor pavilion with manicured grounds on the Scituate and Cohasset line.			https://www.theriverclubscituate.com
Scituate Country Club	91 Driftway	Scituate	Massachusetts			Garden / Outdoor	Indoor & Outdoor			A golf course and clubhouse overlooking the mouth of the North River, with tented receptions arranged for sunset views.	CLeary@scituatecc.com		https://www.scituatecountryclub.com/weddings-events
Black Rock Country Club	19 Clubhouse Drive	Hingham	Massachusetts			Garden / Outdoor	Indoor & Outdoor			A family-oriented golf club on Boston's South Shore with a clubhouse for full-service weddings.		781-749-1919	https://www.blackrockcountryclub.com
White Cliffs Country Club	1 East Cliff Drive	Plymouth	Massachusetts			Beach / Waterfront	Indoor & Outdoor			A landscaped club that sits atop a 175-foot cliff with views across Cape Cod Bay.		508-888-8700	https://www.whitecliffscc.com
The 1620 Winery at Cordage Park	55 Cordage Park Circle	Plymouth	Massachusetts			Restaurant / Vineyard	Indoor & Outdoor			A historic winery on the water in Plymouth's Cordage Park, with packages ranging from simple to elaborate.	events@1620winery.com		https://www.1620winery.com
Rotch-Jones-Duff House & Garden Museum	396 County Street	New Bedford	Massachusetts			Historic / Estate	Indoor & Outdoor			A Greek Revival mansion of 1834, built for a whaling merchant, within about an acre of formal gardens.	info@rjdmuseum.org	508-997-1401	https://www.rjdmuseum.org
Shining Tides Weddings	38 Reservation Road	Mattapoisett	Massachusetts			Beach / Waterfront	Outdoor			A harbourside wedding site on Mattapoisett Harbor run by the YMCA South Coast.	weddings@ymcasc.org	508-525-5729	https://www.shiningtidesweddings.com`,
  },
  {
    name: "Berkshires and Worcester: barns, gardens, museums and estates",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Harrington Farm	178 Westminster Rd	Princeton	Massachusetts			Barn / Rustic	Indoor & Outdoor	220		A working-farm style property on the western slope of Wachusett Mountain with a post-and-beam barn, a farmhouse, a meadow and a tented reception area.	info@harringtonfarm.com	978-464-5600	https://harringtonfarm.com/
Charter Oak Country Club	394 Chestnut St	Hudson	Massachusetts			Ballroom / Hotel	Indoor & Outdoor		Simple	A 38,000 square foot Georgian-style clubhouse beside an 18-hole golf course, with a grand ballroom, a smaller living room and an outdoor terrace for ceremonies.	lcunningham@charteroakcc.com	978-562-0800	https://www.charteroakcc.com/weddings
Cottage Farm of the Berkshires	382 Churchill Street	Pittsfield	Massachusetts			Barn / Rustic	Indoor & Outdoor	250	Classic	A 12-acre former Berkshire summer-cottage estate near Onota Lake, with a cedar pavilion barn, a wildflower ceremony field and a three-bedroom guest house.			https://www.cottagefarmberkshires.com/weddings
Magic Wings Butterfly Conservatory	281 Greenfield Rd	South Deerfield	Massachusetts			Garden / Outdoor	Indoor	100	Classic	An indoor tropical conservatory with thousands of free-flying butterflies, plus an atrium and a garden used for receptions.	weddings@magicwings.com	413.665.2805	https://magicwings.com/weddings/
Chesterwood	4 Williamsville Road	Stockbridge	Massachusetts			Garden / Outdoor	Outdoor			An estate with formal perennial gardens, open lawns and woodland walks, and a French sculpture studio and porches, all with mountain views; weddings are held outdoors under a tent.	chesterwood@savingplaces.org	413.298.2023	https://www.chesterwood.org/private-events-rentals
Berkshire Lake Camp	822 Peru Road	Hinsdale	Massachusetts			Beach / Waterfront	Indoor & Outdoor		Classic	A 13-acre lakefront summer camp with new cabins, indoor and outdoor gathering spaces and waterfront for swimming and kayaking, open for weddings from late May to early October.	anthony@campgroup.com	413-655-8020	https://www.berkshirelakecamp.com/events
Stevens Estate at Osgood Hill	723 Osgood Street	North Andover	Massachusetts			Historic / Estate	Indoor & Outdoor	250		A 143-acre estate with a mansion built in 1886, brick and riverstone outbuildings, gardens and wooded trails, where summer weddings use a tent beside the ceremony lawn.	events@stevensestateevents.com	781-738-0511	https://stevensestateevents.com/
Look Park Garden House	300 North Main Street	Florence	Massachusetts			Garden / Outdoor	Indoor & Outdoor	175		A Mission Style banquet hall with a stone fireplace and glazed atrium, built on the site of a 1930 pool building, with a courtyard and a 40 by 60 foot tent in a municipal-style park.	info@lookpark.org	413-584-5457	https://lookpark.org/weddings/`,
  },
];

export default batches;
