import type { VenueBatch } from "@/lib/venue-batches";

// Michigan venue batches. Every row's State is "Michigan". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Metro Detroit and Grand Rapids",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Meadow Brook Hall	350 Estate Dr	Rochester	Michigan			Historic / Estate	Indoor & Outdoor		Luxury	Tudor-revival mansion built 1926-1929 on the Oakland University campus, with a two-storey ballroom, a grand staircase and formal gardens with a climate-controlled garden tent.	mbhevent@oakland.edu	(248) 364-6200	https://www.meadowbrookhall.org/weddings
The Roostertail	100 Marquette Dr	Detroit	Michigan			Beach / Waterfront	Indoor	800		Family-run riverfront event house on the Detroit River since 1958, with the Marine Room surrounded by water on three sides and the larger Palm River Room facing the skyline.	info@roostertail.com	(313) 822-1234	https://www.roostertail.com/
Royal Park Hotel	600 E University Dr	Rochester	Michigan			Ballroom / Hotel	Indoor & Outdoor	550		Boutique hotel of 143 rooms beside the Paint Creek Trail in downtown Rochester, with a grand ballroom, a Belgian glass conservatory over a fountain garden and an open-air pavilion.		(248) 652-2600	https://www.royalparkhotelmi.com/weddings-and-social-events.htm
The Townsend Hotel	100 Townsend St	Birmingham	Michigan			Ballroom / Hotel	Indoor			Downtown Birmingham hotel whose ballroom divides into four salons, with the Tea Lobby, Clancy and Regency rooms for smaller parts of the day and guest room blocks upstairs.	groupres@townsendhotel.com		https://www.townsendhotel.com/weddings
The War Memorial	32 Lake Shore Dr	Grosse Pointe Farms	Michigan			Beach / Waterfront	Indoor	450		Nonprofit on the 1910 Alger Estate on Lake St. Clair, pairing the Italian Renaissance Alger House for small groups with a lakefront ballroom and in-house catering.		(313) 881-7511	https://www.warmemorial.org/weddings
The Whitney	4421 Woodward Ave	Detroit	Michigan			Restaurant / Vineyard	Indoor & Outdoor	350		Restaurant inside the 1894 pink-granite David Whitney Jr. mansion in Midtown, using its many dining rooms and a summer garden for ceremonies and receptions.	events@thewhitney.com	(313) 832-5700	https://www.thewhitney.com/private-dining-1
Cobblestone Farm	2781 Packard Rd	Ann Arbor	Michigan			Barn / Rustic	Indoor	190		City-run historic farm park whose three-storey oak timber-frame barn has a loft, a warming kitchen, climate control and changing rooms.	cfinfo@a2gov.org	(734) 794-6230	https://www.a2gov.org/parks-and-recreation/parks-and-places/cobblestone-farm/
Ford Piquette Avenue Plant	461 Piquette Ave	Detroit	Michigan			Historic / Estate	Indoor			National Historic Landmark factory from 1904 where the Model T was first built, now a car museum that hosts receptions among its early Fords.	gingerzb@fordpiquetteplant.org	(313) 872-8759	https://www.fordpiquetteplant.org/private-rentals/
Frutig Farms: The Valley	7650 Scio Church Rd	Ann Arbor	Michigan			Barn / Rustic	Indoor & Outdoor			Family-owned farm west of Ann Arbor with a restored 19th-century barn, rented for the whole weekend with its outbuildings and outdoor ceremony spaces.		(313) 657-6882	https://www.frutigfarms.com/
Barn 1888	1888 128th Ave	Hopkins	Michigan			Barn / Rustic	Indoor & Outdoor	200		Restored 1888 barn on 20 acres between Grand Rapids and Kalamazoo, with an outdoor chapel garden, a lower level for dancing and a pavilion with a stone fireplace.	barn1888events@gmail.com	(616) 446-5747	https://www.barn1888.com/
The Goei Center	818 Butterworth SW	Grand Rapids	Michigan			Historic / Estate	Indoor	400		Event hall in the former Kindel Furniture building on the West Side, with a 14,000 sq ft main hall, the separate Kindel Room and an in-house bar.	info@thegoeicenter.com		https://www.thegoeicenter.com/
Amway Grand Plaza	187 Monroe Ave NW	Grand Rapids	Michigan			Ballroom / Hotel	Indoor			Downtown hotel by the Grand River with several ballrooms including the Imperial, Ford and Pantlind, an on-site salon and spa, and guest rooms for out-of-town guests.	weddings@ahchospitality.com	(616) 776-6400	https://www.amwaygrand.com/weddings
Hydrangea Blu Barn	5716 11 Mile Rd NE	Rockford	Michigan			Barn / Rustic	Indoor & Outdoor			Barn venue north of Grand Rapids offering barn, barn-and-tent and full-weekend packages, with a bridal suite and groomsmen quarters on site.	events@hydrangeablubarn.com	(616) 255-6716	https://www.hydrangeablubarn.com/weddings
Grand Rapids Public Museum	272 Pearl St NW	Grand Rapids	Michigan			Historic / Estate	Indoor	270	Simple	Riverside history museum whose first-floor galleria under a hanging fin whale skeleton hosts receptions, with ceremonies in its theatre or planetarium.			https://www.grpm.org/rent/`,
  },
  {
    name: "Metro Detroit, Ann Arbor and West Michigan: second batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Detroit Foundation Hotel	250 W Larned St	Detroit	Michigan			Ballroom / Hotel	Indoor & Outdoor	120		A downtown hotel inside the former Detroit Fire Department headquarters, with the Observatory and Borgman Room for receptions and a small terrace.		313-800-5500	https://detroitfoundationhotel.com/celebrations/
The Henry Ford	20900 Oakwood Blvd	Dearborn	Michigan			Historic / Estate	Indoor & Outdoor	400	Classic	A Dearborn museum campus offering receptions in the Henry Ford Museum, the Lovett Hall ballroom or among the historic buildings of Greenfield Village.	sales@thehenryford.org	313-982-6220	https://www.thehenryford.org/host-an-event/weddings
Revel Run	555 S Dancer Rd	Chelsea	Michigan			Garden / Outdoor	Indoor & Outdoor			A family-owned equestrian estate on a former private golf course west of Ann Arbor, with a reception hall built in 2024, the Overlook and a biergarten.	info@revelrun.com	734-255-4148	https://revelrun.com/weddings
Historic Blum Barn	10383 E Austin Rd	Manchester	Michigan			Barn / Rustic	Indoor & Outdoor			A 43-acre farm settled in 1832 by a Bavarian dairy family and later a horse-racing yard, with a restored barn and the new white Stables hall.	Mirela@historicblumbarn.com	734-604-3797	https://www.historicblumbarn.com/
Saint John's Resort	44045 Five Mile Rd	Plymouth	Michigan			Ballroom / Hotel	Indoor & Outdoor	400		A former 1940s Romanesque seminary on 200 acres, now a 118-room resort with its own chapel, a garden pavilion, an atrium and an underground wine grotto.		734-414-0600	https://www.saintjohnsweddings.com/
The Jam Handy	2900 E Grand Blvd	Detroit	Michigan			Historic / Estate	Indoor & Outdoor			A Gothic Revival building in Detroit's North End that was the Jam Handy Organization's film sound stage from the 1930s to the 1960s, with a courtyard.	info@thejamhandy.com		https://thejamhandy.com/
The Felt Estate	6597 138th Ave	Holland	Michigan			Historic / Estate	Indoor & Outdoor		Classic	A 12,000 sq ft, 25-room mansion with a ballroom on 15 acres by the Lake Michigan shore, with a carriage house, an old chapel and lodging for 24.	contact@feltmansion.org	616-335-8982	https://www.feltmansion.org/weddings
CityFlatsHotel Grand Rapids	77 Monroe Center St NW	Grand Rapids	Michigan			Ballroom / Hotel	Indoor	200		A downtown boutique hotel whose 1926 Italian Renaissance ballroom has vaulted ceilings, marble columns, terrazzo floors and a mezzanine bridal suite.		844-550-2489	https://cityflatshotel.com/grand-rapids/events/weddings/
Shoreline Inn Conference Center	730 Terrace Point Rd	Muskegon	Michigan			Beach / Waterfront	Indoor & Outdoor			A Muskegon Lake hotel conference centre beside Terrace Point Marina, with a lake-view ballroom and two outdoor ceremony sites by the water.		231-720-4206	https://www.thelakehousemi.com/home-i/weddings/
The Wickwood Inn	510 Butler St	Saugatuck	Michigan			Historic / Estate	Indoor & Outdoor	28		An 11-room inn in downtown Saugatuck, booked whole for small weddings, with landscaped gardens, an arbor and a terrace for receptions.	guestservices@wickwoodinn.com	269-857-1465	https://wickwoodinn.com/weddings-wickwood/
The Fields of Michigan	154 68th St	South Haven	Michigan			Garden / Outdoor	Indoor & Outdoor	150	Classic	A glamping resort on a blueberry farm outside South Haven, with a woodland river-overlook ceremony spot, a lavender field, a small barn room and tents and cottages.	info@thefieldsofmichigan.com	888-970-9905	https://www.thefieldsofmichigan.com/group-events/
Grand Rapids Art Museum	101 Monroe Center St NW	Grand Rapids	Michigan			Historic / Estate	Indoor & Outdoor			A downtown art museum, the first LEED Gold-certified one, whose 30-foot-high Wege Pavilion lobby, covered dining terrace and raised veranda host receptions.	info@artmuseumgr.org	616-831-1000	https://www.artmuseumgr.org/host-an-event`,
  },
  {
    name: "Metro Detroit, Oakland County and the Lake Michigan shore: third batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Planterra Conservatory	7315 Drake Rd	West Bloomfield	Michigan			Garden / Outdoor	Indoor		Luxury	A glass-roofed greenhouse conservatory filled with tropical plants and trees, booked for one all-inclusive celebration per date.	events@planterra.com	(248) 661-1591	https://www.planterraevents.com/weddings
Detroit Yacht Club	1 Riverbank Rd	Detroit	Michigan			Beach / Waterfront	Indoor	400		A private yacht club clubhouse on Belle Isle with a grand ballroom and smaller rooms overlooking the Detroit River.		(313) 824-1200	https://www.dyc.com/weddings-and-events
Pine Knob Mansion & Carriage House	5580 Waldon Rd	Clarkston	Michigan			Historic / Estate	Indoor & Outdoor	280		A 1927 English manor and carriage house on a 450-acre golf property, with stained glass, carved woodwork, gardens and a gazebo for ceremonies.		(248) 625-0700	https://www.pineknobgolfclub.com/events/packages-pricing
Detroit Zoo	8450 W 10 Mile Rd	Royal Oak	Michigan			Garden / Outdoor	Indoor & Outdoor	215	Simple	A zoo with rentable spaces from a string-lit open-air pavilion and a bronze-bear fountain to a butterfly garden gallery and a polar bear habitat.		(248) 336-5745	https://detroitzoo.org/private-events/wedding/
Weber's Boutique Hotel	3050 Jackson Ave	Ann Arbor	Michigan			Ballroom / Hotel	Indoor & Outdoor	290		A family-run hotel since 1937 with two ballrooms, one a glass-walled atrium opening onto a string-lit patio, plus guest rooms on site.		(734) 769-2500	https://www.webersannarbor.com/weddings/
Wellers Carriage House	555 W Michigan Ave	Saline	Michigan			Historic / Estate	Indoor & Outdoor	186	Simple	A former Henry Ford property on a millpond outside Ann Arbor, with a carriage house, a smaller river room, a dance gazebo and a fire pit.			https://www.wellersweddings.com/
Boatwerks Waterfront Restaurant	216 Van Raalte Ave	Holland	Michigan			Restaurant / Vineyard	Indoor & Outdoor	400		A restaurant on Lake Macatawa with boat docking, a waterfront courtyard and garage-door walls, renting its rooms for events of up to 400.		(616) 396-0600	https://www.boatwerksrestaurant.com/private-dining/
Trillium Catering and Event Center	17246 VanWagoner Rd	Spring Lake	Michigan			Ballroom / Hotel	Indoor & Outdoor	600		A banquet centre between Grand Haven and Muskegon with three ballrooms, landscaped gardens with a gazebo for ceremonies and a tent for outdoor receptions.	randall@trilliumevents.net	(616) 842-8260	https://trilliumevents.com/wedding-venue/
Haworth Hotel	225 College Ave	Holland	Michigan			Ballroom / Hotel	Indoor	250		A Hope College hotel in downtown Holland with a ballroom among more than 10,000 sq ft of event space, in-house catering and room blocks for guests.	haworthevents@hope.edu	(616) 395-7200	https://haworthhotel.com/wedding-special-events/
Wildwood Family Farms	7970 Snow Ave SE	Alto	Michigan			Barn / Rustic	Indoor & Outdoor	220		A 55-acre flower farm southeast of Grand Rapids with an 1893 post-and-beam barn, a modern carriage house, a silo courtyard and pond-side ceremony sites.			https://www.wildwoodfamilyfarms.com/weddings-at-wildwood
Port 393	393 Cleveland Ave	Holland	Michigan			Beach / Waterfront	Indoor & Outdoor	200		A whole-building event space on Lake Macatawa with an indoor harbour room, a rooftop terrace and lounge for ceremonies and a separate cottage for getting ready.		(616) 377-9517	https://port393.com/weddings
Saugatuck Center for the Arts	400 Culver St	Saugatuck	Michigan			Garden / Outdoor	Indoor & Outdoor			A downtown Saugatuck arts centre renting an outdoor pavilion, a theatre stage for ceremonies and a window-lined lobby for receptions.		(269) 857-2399	https://www.sc4a.org/rentals/`,
  },
  {
    name: "Traverse City, Ann Arbor and Metro Detroit: fourth batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Cherry Basket Farm	2027 M-22	Omena	Michigan			Barn / Rustic	Indoor & Outdoor	150	Classic	An 1890s barn and a newer timber-framed upper barn set among orchards, gardens and a pond in the village of Omena, booked for one wedding per weekend.	info@cherrybasketfarm.com	231-492-0462	https://www.cherrybasketfarm.com/
Starry Night Barn & Studios	2363 N Jacobson Rd	Suttons Bay	Michigan			Barn / Rustic	Indoor & Outdoor	299		A restored barn with a 3,600 sq ft upper reception space on the Leelanau Peninsula, with a farmhouse and cottages on site for wedding weekends.		231-357-8714	https://starrynightbarn.com/
White Birch Lodge	571 Meguzee Point Rd	Elk Rapids	Michigan			Beach / Waterfront	Indoor & Outdoor	150		A lakefront family resort on Elk Lake with a historic dining hall and 31 guest accommodations that is closed to the public during a wedding weekend.	info@whitebirchlodge.com	(231) 264-8271	https://whitebirchlodge.com/weddings-events/
Shanahan's Barn		Charlevoix	Michigan			Barn / Rustic	Indoor	361		A barn built in 1913 and restored in 2013, set on the 16th green of a golf course, with cathedral trusses, wagon-wheel chandeliers and a loft.		(231) 675-3342	https://www.shanahansbarn.com/
Aurora Cellars	7788 E Horn Rd	Lake Leelanau	Michigan			Restaurant / Vineyard	Indoor & Outdoor	300		A Leelanau winery estate with a willow-shaded ceremony lawn, a heated 40-by-80-foot reception tent and an 1875 Victorian farmhouse included with the weekend.	tastingroom@auroracellars.com	231-994-3188	https://www.auroracellars.com/weddings-events/
Bay View Weddings at Gallagher Farms	8555 E Lincoln Rd	Cedar	Michigan			Garden / Outdoor	Outdoor			A hilltop wedding site on a 400-acre working farm with an on-site distillery and views over Grand Traverse Bay.		231.645.2732	https://bayviewweddings.com/
The Cathedral Barn at Historic Barns Park	1500 Red Dr	Traverse City	Michigan			Barn / Rustic	Indoor			A renovated cathedral barn event space inside Historic Barns Park on the grounds of the old Traverse City State Hospital campus.		(231) 492-0078	https://www.historicbarnspark.com/weddings/
Fountain Point Resort		Lake Leelanau	Michigan			Historic / Estate	Indoor & Outdoor			A hotel dating to 1889 with 19 cottages on 54 acres and nearly half a mile of Lake Leelanau shoreline, open May through October.	weddings@fountainpointresort.com	231-256-9800	https://www.fountainpointresort.com/weddings/
Garvey Family Wedding Barn	7490 Lautner Rd	Williamsburg	Michigan			Barn / Rustic	Indoor & Outdoor	150		A restored barn from the late 1800s with hand-hewn beams, a 40-by-60-foot main space and a cedar deck, about ten minutes from Traverse City.			https://traversecityweddingbarn.com/
Jacob's Farm	7100 E Traverse Hwy	Traverse City	Michigan			Garden / Outdoor	Outdoor	200	Classic	A 40-acre orchard property with a hilltop reception site, a forest ceremony spot called the Cathedral of Trees and an 1892 barn.	events@jacobsfarmtc.com		https://www.jacobsfarmtc.com/weddings
Kirkbride Hall	700 Cottageview Dr	Traverse City	Michigan			Historic / Estate	Indoor & Outdoor	220		A historic chapel with high ceilings and stained glass plus a front lawn for ceremonies, with a three-bedroom condominium suite on site.	events@thevillagetc.com	(231) 941-1961	https://www.kirkbridehall.com/weddings
The Peninsula Room	13512 Peninsula Dr	Traverse City	Michigan			Historic / Estate	Indoor & Outdoor			An estate on Old Mission Peninsula with ceremony grounds, several reception spaces and Michigan wine, beer and spirits service.		231.223.4333	https://www.peninsularoom.com/peninsula-room-wedding
Mission Table	13512 Peninsula Dr	Traverse City	Michigan			Restaurant / Vineyard	Indoor & Outdoor			The former Bowers Harbor Inn on Old Mission Peninsula, now a farm-to-table venue used only for private events with a great lawn, gardens, vines and a deck facing west bay.		231.223.4333	https://www.missiontable.net/weddings
The Leland Lodge	565 Pearl St	Leland	Michigan			Ballroom / Hotel	Indoor & Outdoor			A hotel established in 1927 beside the Leland Country Club, with an Oak Room, a wine cellar bar and a garden courtyard for events.	brian@lelandlodge.com	(231) 256-9848	https://lelandlodge.com/weddings-and-events/
Timberlee Hills	10484 S Timberlee Dr	Traverse City	Michigan			Garden / Outdoor	Indoor & Outdoor	200		A hilltop lodge northwest of Traverse City with perennial gardens, a pond and waterfall for ceremonies and a covered patio reception space.		231.944.2196	https://timberleehills.com/event-venue/
Park Place Hotel	300 E State St	Traverse City	Michigan			Ballroom / Hotel	Indoor	450		A downtown hotel with 140 rooms and banquet halls with views of the city and Grand Traverse Bay.		(231) 946-5000	https://www.park-place-hotel.com/groups-weddings/weddings
Hagerty Center	715 E Front St	Traverse City	Michigan			Beach / Waterfront	Indoor & Outdoor	200		A waterfront ballroom and courtyard at Northwestern Michigan College overlooking Grand Traverse Bay.		(231) 995-3100	https://www.hagertycenter.com/traverse-city-weddings/
Traverse City Country Club	1725 S Union St	Traverse City	Michigan			Ballroom / Hotel	Indoor & Outdoor	225		A private country club with a divisible banquet room, a private dining room and a patio for receptions.		231-947-9140	https://www.tcgcc.com/banquets
Grand Traverse Resort and Spa	100 Grand Traverse Village Blvd	Acme	Michigan			Ballroom / Hotel	Indoor & Outdoor			A large resort north of Traverse City offering wedding spaces from a beach to a ballroom to a barn, with a spa and three golf courses.		231-534-6000	https://www.grandtraverseresort.com/meet/weddings/
The Homestead	1 Wood Ridge Rd	Glen Arbor	Michigan			Beach / Waterfront	Indoor & Outdoor			A Sleeping Bear Dunes-area resort with several lodges and a lakeside setting, offering lodging in four hotels plus rental homes and condos.		(231) 923-4626	https://www.thehomesteadresort.com/weddings/
Chateau Chantal	15900 Rue de Vin	Traverse City	Michigan			Restaurant / Vineyard	Indoor & Outdoor			An Old Mission Peninsula winery and 12-room inn with vineyard views of both Grand Traverse Bays, where wedding guests stay at the inn.		(231) 223-4110	https://chateauchantal.com/events
The Collins off Main	120 W Middle St	Chelsea	Michigan			Historic / Estate	Indoor & Outdoor	200		Turn-of-the-century brick building in downtown Chelsea that once housed the Overland car company and a Pontiac dealership, now hosting one wedding per day with a separate ceremony chapel.		(734) 531-7722	https://www.collinsoffmain.com/
The Collins at the Clocktower	310 N Main St	Chelsea	Michigan			Historic / Estate	Indoor	270		Landmark 1906 former water tower in Chelsea that later housed a stove factory and a brewery, restored as an industrial-modern wedding space.		(734) 531-7722	https://www.collinsattheclocktower.com/
Stone Chalet Bed and Breakfast Inn and Event Center	1917 Washtenaw Ave	Ann Arbor	Michigan			Historic / Estate	Indoor & Outdoor	100		A 1917 chalet-style inn near the University of Michigan campus with a mid-century event hall, garden gazebo and pond, and guest rooms on site for small weddings.	stay@stonechalet.com	(866) 382-6542	https://www.stonechalet.com/
Robin Hills Farm	20390 M-52	Chelsea	Michigan			Barn / Rustic	Indoor & Outdoor	250		A 129-acre working farm west of Ann Arbor with a timber-frame Pasture Barn, a glass-walled Glasshouse and a beer-garden Nest, plus hiking trails and a pond.	hostyourevents@robinhillsfarm.com	(734) 472-2192	https://www.robinhillsfarm.com/
Tandale Nature Barn	2605 S Old US Highway 23	Brighton	Michigan			Barn / Rustic	Indoor & Outdoor	220	Luxury	A 5,400-square-foot modern rustic barn set in a certified wildlife habitat with waterside and woodland ceremony groves and a treehouse stay.		(810) 222-9704	https://www.tandalenaturebarn.com/venuepricing
Forty Nine South	2527 Helena Ave	Jackson	Michigan			Historic / Estate	Indoor & Outdoor	200	Classic	A renovated former primary school with farmhouse tables, a gymnasium-sized hall, a library lounge and a fenced patio for cocktail hour.		(517) 435-2193	https://fortyninesouth.com/weddings/
Cascades Manor	1970 Kibby Rd	Jackson	Michigan			Historic / Estate	Indoor & Outdoor	250	Simple	A half-timbered historic manor inside Sparks Foundation Park with three event rooms, one with panoramic views, and a ceremony gazebo on park grounds.		(517) 784-1500	https://www.cascadesmanor.com/events/
Waldenwoods Event Venue & Resort	2975 Old US-23 Hwy	Howell	Michigan			Beach / Waterfront	Indoor & Outdoor	300	Simple	A wooded lakeside resort with a lodge-style hall, a 5,000-square-foot lakeview tent, lakeside ceremony sites and on-site lodging.	banquets@waldenwoods.com	(810) 632-6401	https://waldenwoodsevents.com/weddings/
Crystal Gardens Event Center	5768 E Grand River Ave	Howell	Michigan			Ballroom / Hotel	Indoor & Outdoor			A banquet center with several ballrooms, a lobby bar and an open-air wedding chapel seating 170 guests.	info@cgliv.com	(877) 545-1002	https://cgliv.com/weddings/
Columbus Hall & Banquet Center	8265 Dexter Chelsea Rd	Dexter	Michigan			Ballroom / Hotel	Indoor	300		A banquet hall outside Dexter where couples bring their own caterer, decor and drinks, with tables and padded chairs set for a large guest list.	columbushbc@gmail.com	(734) 426-5558	https://columbushbc.com/
Washtenaw Golf Club	2955 Packard Rd	Ypsilanti	Michigan			Ballroom / Hotel	Indoor & Outdoor			A golf club that opened in 1899 with a sunlit ballroom, a private patio and a bar and grill overlooking the course.		(734) 434-2150	https://www.washtenawgolfclub.com/weddings/
Ella Sharp Museum	3225 4th St	Jackson	Michigan			Historic / Estate	Indoor & Outdoor			A history and art museum campus with a community room, a granary, a patio, bridal and groom suites and a farmhouse for wedding photos, plus a planetarium for cocktail-hour shows.		(517) 787-2320	https://ellasharpmuseum.org/host-an-event/weddings/
Sandhill Crane Vineyards	4724 Walz Rd	Jackson	Michigan			Restaurant / Vineyard	Indoor	60		A working farm and winery whose event room has a stage, high ceilings and a wine bar, hosting small weddings from November through April.	sandhillwinez@gmail.com	(517) 764-0679	https://www.sandhillcranevineyards.com/private-events
Lakelands Golf & Country Club	8760 Chilson Rd	Brighton	Michigan			Ballroom / Hotel	Indoor	300		A golf club ballroom overlooking the course that can be opened up to seat 300 or divided into smaller rooms.		(810) 231-3000	https://www.lakelandsgolf.com/Default.aspx?p=DynamicModule&pageid=33&ssid=100043&vnf=1
The Historic Chelsea Depot	125 Jackson St	Chelsea	Michigan			Historic / Estate	Indoor		Simple	A restored railroad depot run by a local association, with two rooms, an on-site kitchen and sound system available for weddings and receptions.	rentals@chelseadepot.com		https://www.chelseadepot.com/rental-information
The Bank	800 Military St	Port Huron	Michigan			Historic / Estate	Indoor	300		A 1927 bank building on the Black River with 30-foot windows, marble columns and the original vault.		810-989-5814	https://thebank.sc4.edu/
Fort Gratiot Light Station	2802 Omar St	Port Huron	Michigan			Historic / Estate		240		A historic lighthouse station run by Port Huron Museums, with views of Lake Huron and the Blue Water Bridge.	reservations@phmuseum.org	810-982-0891	https://www.phmuseum.org/venue-rentals/
Tina's Country House & Gardens	50828 North Ave	Macomb	Michigan			Ballroom / Hotel	Indoor & Outdoor	500		A banquet center with two banquet rooms and a wedding garden holding an Italian fountain and a vine-covered gazebo.		586-949-2280	https://www.tinascountryhouse.com
The Pavilion at Copper Hills Golf Club	2125 Lakeville Rd	Oxford	Michigan			Garden / Outdoor	Indoor & Outdoor	300		A timber-trussed pavilion on a 367-acre golf property, with fairway and sunset views for photos.	info@copperhills.com	248-969-9808	https://copperhills.com/wedding-venues-in-oakland-county-mi/
The Venues at Goldner Walsh	559 Orchard Lake Rd	Pontiac	Michigan			Garden / Outdoor	Indoor & Outdoor	200		A 12-acre former cut-flower greenhouse operation dating to 1890, now with greenhouse event rooms, gardens and an amphitheater.	greenhouse@goldnerwalsh.com	248-332-6430	https://goldnerwalsh.com/greenhouse-wedding-venue-michigan/
Wayne Tree Manor	35100 Van Born Rd	Wayne	Michigan			Ballroom / Hotel	Indoor			A banquet hall with its own chapel for wedding ceremonies and receptions.		734-728-3020	https://waynetreemanor.com/
Chemistry Banquet Hall	35000 Sims St	Wayne	Michigan			Ballroom / Hotel	Indoor	230		A family-owned banquet hall with a full kitchen and room for 230 guests indoors.	info@chemistrybanquethall.com	313-450-3777	https://chemistrybanquethall.com/
Meeting House Grand Ballroom	499 S Main St	Plymouth	Michigan			Ballroom / Hotel	Indoor			A family-run, Victorian-inspired banquet hall open since 1965 in downtown Plymouth.		734-416-5100	https://meetinghousegrandballroom.com/
The Bellflower	4700 West D Ave	Kalamazoo	Michigan			Historic / Estate	Indoor & Outdoor	50	Simple	A restored 1871 schoolhouse on one landscaped acre that suits small weddings and elopements.		269-377-2852	https://www.thebellflowerkzoo.com/weddings
Blue Heron Barn	6464 South 32nd St	Kalamazoo	Michigan			Barn / Rustic	Indoor & Outdoor	200	Classic	A restored barn on five acres with a pergola, wooden bridge and meadows.	blueheronbarn@gmail.com	269-377-3564	https://www.blueheronbarn.com/
The Casnovia Barn	14118 Kenowa Ave	Casnovia	Michigan			Barn / Rustic	Indoor & Outdoor	300	Classic	A modernized barn plus a glass-and-metal ceremony building surrounded by apple orchards.	events@thecasnoviabarn.com		https://www.thecasnoviabarn.com/
Lyon Oaks Event Center	52221 Pontiac Trail	Wixom	Michigan			Ballroom / Hotel	Indoor	250	Simple	A county-run event center with floor-to-ceiling windows over an Arthur Hills golf course; couples bring their own caterer.	lyonoaksgc@oaklandcountymi.gov	248-437-1488	https://www.oaklandcountymi.gov/community/oakland-county-parks/golf/lyon-oaks-golf-course/lyon-oaks-event-center
The Lafayette Grande	1 Lafayette St	Pontiac	Michigan			Historic / Estate	Indoor	500		A historic building with three ballrooms, grand staircases and a vintage elevator.	events@lafayettegrande.com	248-334-6999	https://lafayettegrande.com/lafayette-grande-weddings/
Fox Hills Golf & Banquet Center	8768 N Territorial Rd	Plymouth	Michigan			Ballroom / Hotel		400		A 500-acre golf property with three separate banquet venues for 20 to 400 guests.		734-453-7272	https://www.foxhills.com/
Stonegate Farm Event Center	2681 Hadley Rd	Lapeer	Michigan			Barn / Rustic				A 6,000-square-foot main barn built in 1909 that is rented exclusively for each event.	Stonegatefarmevents@yahoo.com	810-664-6550	https://www.stonegatefarmeventsmi.com/
The English Inn	677 S Michigan Rd	Eaton Rapids	Michigan			Historic / Estate	Indoor & Outdoor	200		A boutique hotel with 20 rooms on the Grand River, with formal English gardens and a hall for up to 200 guests.	info@englishinn.com	517-663-2500	https://www.englishinn.com/weddings
Laurel Manor	39000 Schoolcraft Rd	Livonia	Michigan			Ballroom / Hotel				A multi-ballroom banquet and conference center in Livonia with in-house catering.		734-462-0770	https://laurelmanor.com/livonia-mi/event-venue-in-livonia-mi/
Great Lakes Culinary Center	24101 W Nine Mile Rd	Southfield	Michigan			Restaurant / Vineyard	Indoor & Outdoor			An industrial-style test kitchen and event space with an open kitchen and an outdoor garden.	cassy@glculinarycenter.com		https://glculinarycenter.com/`,
  },
  {
    name: "Detroit, Lansing, West Michigan and the north: fourth batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Heritage Wedding Barns	813 S 32nd Ave	Shelby	Michigan			Barn / Rustic	Indoor & Outdoor	220	Classic	Restored timber-frame barn on 27 acres of a family farm that dates to 1922, a short drive from Lake Michigan and the Silver Lake dunes.	Sarahk@hwbarns.com	231-830-7825	https://www.heritageweddingbarns.com
Record Box Loft	15 Carlyle Street	Battle Creek	Michigan			Historic / Estate	Indoor	250		A restored 1902 riverfront building in downtown Battle Creek, once a cereal-box printing plant, with original hardwood floors and exposed brick.	events@recordboxloft.com	(269) 261-1095	https://www.recordboxloft.com
Frauenthal Center	425 West Western Ave	Muskegon	Michigan			Historic / Estate	Indoor	275	Simple	Historic downtown Muskegon performing arts building that rents its ballroom, reception gallery, lounge and theaters for wedding ceremonies and receptions.	info@frauenthal.org	231-727-8001	https://frauenthal.org/event-hosting/weddings/
Inn at Bay Harbor	3600 Village Harbor Drive	Bay Harbor	Michigan			Beach / Waterfront	Indoor & Outdoor	150		Lake Michigan resort overlooking Little Traverse Bay, with a lakefront ceremony lawn, a brick terrace and the Sagamore Room for receptions.		888-517-3292	https://www.innatbayharbor.com/weddings
Hotel Walloon	4127 N M-75	Walloon Lake	Michigan			Beach / Waterfront	Indoor & Outdoor			Lakeside hotel on Walloon Lake that books weddings across four nearby spaces including the hotel, the Talcott, Walloon Lake Inn and Village Green Park.	concierge@hotelwalloon.com	(231) 535-5000	https://www.hotelwalloon.com
The Island House	6966 Main Street	Mackinac Island	Michigan			Ballroom / Hotel	Indoor & Outdoor	150		Downtown Mackinac Island hotel with a waterfront garden terrace, a historic veranda, an ice house garden and a grill room for receptions.	andrea@theislandhouse.com	1-906-847-3347	https://www.theislandhouse.com/weddings
Ivy House	3291 Blue Star Highway	Saugatuck	Michigan			Garden / Outdoor	Indoor & Outdoor	300	Simple	Seven-acre property with a climate-controlled glass greenhouse for ceremonies, a separate reception hall and two getting-ready suites.		616-377-9517	https://www.ivyhousemi.com/weddings
The 1530 Events	1530 Madison Ave SE	Grand Rapids	Michigan			Historic / Estate	Indoor & Outdoor			A converted furniture factory with a loft-style ballroom, a mezzanine lounge and a rooftop garden patio with a fire pit.		616-500-9931	https://www.the1530events.com/
Grand Rapids Downtown Market	435 Ionia Ave SW	Grand Rapids	Michigan			Ballroom / Hotel	Indoor & Outdoor	180		Public market building with a plant-filled greenhouse, a hardwood banquet room and terraces, plus smaller rooms for rehearsal dinners.	events@downtownmarketgr.com	(616) 805-5308	https://www.downtownmarketgr.com/spaces
Gull Lake Country Club	9725 West Gull Lake Drive	Richland	Michigan			Ballroom / Hotel	Indoor & Outdoor	265		Clubhouse on Gull Lake with a lake-view room, a private patio and a lakeside pavilion that takes tented receptions of up to 300.	glcc@gulllakecc.com	269-629-9714	https://www.gulllakecc.com/weddings
Marquette Regional History Center	145 W Spring St	Marquette	Michigan			Historic / Estate	Indoor & Outdoor	200	Simple	The domed Rydholm Gathering Hall on the first floor of the history center, rented with an adjoining lawn, a conference room and a dome mezzanine.		(906) 226-3571	https://www.marquettehistory.org/gathering-hall-rental.html
South Haven Creations	7379 N Shore Dr	South Haven	Michigan			Garden / Outdoor	Indoor & Outdoor	209		Wooded all-inclusive venue near the Lake Michigan shore, run by a Grand Rapids caterer, with a lawn, deck and woodland ceremony area.		(269) 872-3439	https://southhavencreations.com/
The Barn at the Resort	63600 Co Rd 388	South Haven	Michigan			Barn / Rustic	Indoor & Outdoor			Reclaimed-wood reception barn and a separate Quonset ceremony barn on the grounds of a camp resort a few minutes from downtown South Haven.		269-637-6153	https://thebarnsouthhaven.com/
Inisfree Estate	1073 62nd Street	Pullman	Michigan			Historic / Estate	Indoor & Outdoor	200		Thirty-acre estate between South Haven and Saugatuck with an 1893 barn, a pond pavilion, gardens, a vineyard and ten B&B suites.		269-236-9700	https://inisfreeestate.com/weddings/
Lake Arvesta Farms	06464 Arvesta Drive	South Haven	Michigan			Barn / Rustic	Indoor & Outdoor	300		Private-lake property with a barn, a boat house and several waterside ceremony spots, including an island with its own beach and pavilion.	info@lakearvestafarms.com	(269) 637-6464	https://www.lakearvestafarms.com/weddingvenue-1
Haley Station	1837 3rd Avenue North	Escanaba	Michigan			Ballroom / Hotel	Indoor & Outdoor	125		Boutique event venue in Escanaba with an indoor ceremony and reception space, an outdoor courtyard and optional all-inclusive packages.	events@haleystationevents.com	(906) 261-9159	https://haleystationevents.com/
The Highlands at Harbor Springs	600 Highlands Drive	Harbor Springs	Michigan			Ballroom / Hotel	Indoor & Outdoor			Ski-and-golf resort with hillside overlooks, a historic chapel and indoor venues for weddings in any season.		888-436-2296	https://www.highlandsharborsprings.com/weddings
Longacre House	24705 Farmington Rd	Farmington Hills	Michigan			Historic / Estate	Indoor & Outdoor			City-owned historic banquet house with a stone wall fence and gardens, open for weddings by appointment tour.	rhoke@fhgov.com	(248) 477-8404	https://fhgov.com/facilities/longacre-house/
Woldumar Nature Center	5739 Old Lansing Rd	Lansing	Michigan			Barn / Rustic	Indoor & Outdoor	150	Simple	Nature center with a log cabin porch and an amphitheater for ceremonies and an early 1900s dairy barn for receptions.		517-322-0030	https://www.woldumar.org/wedding-reception-venue.php
Country Barn Estates	6055 W Allan Rd	Henderson	Michigan			Barn / Rustic	Indoor & Outdoor	299		Rural property with a large White Barn and a restored century-old Red Barn, offering a dance floor and live-music setup.	celebrate@cberental.com	(855) 218-1741	https://www.countrybarnestates.com
The Iroquois Club	43248 N Woodward Ave	Bloomfield Hills	Michigan			Historic / Estate	Indoor			Rustic-styled event club on Woodward Avenue that has held weddings since 2006 and offers ceremony and reception in one place.		(248) 451-9653	https://www.theiroquoisclub.com/
The San Marino Club	1685 E Big Beaver Rd	Troy	Michigan			Ballroom / Hotel	Indoor			Mountain-lodge-inspired banquet club with three event rooms and wedding packages.	info@sanmarinoclub.com	(248) 689-4615	http://sanmarinoclub.com/
Packard Proving Grounds	49965 Van Dyke Ave	Shelby Township	Michigan			Historic / Estate	Indoor & Outdoor	296	Classic	Seventeen-acre 1928 automotive test site with Albert Kahn buildings, a tree-lined boulevard for ceremonies and a repair garage for receptions.		(586) 739-4800	https://www.packardprovinggrounds.org/weddings
The Station at Shepherd's Hollow	9085 Big Lake Rd	Clarkston	Michigan			Restaurant / Vineyard	Indoor & Outdoor	350	Luxury	Glass-walled clubhouse set among pines above a lake and golf course, with a fountain terrace for ceremonies and a wraparound veranda.		(248) 963-7065	https://shepherdshollow.com/plan-your-wedding/
Ellis Barn at Springfield Oaks	12451 Andersonville Rd	Davisburg	Michigan			Barn / Rustic	Indoor	250	Simple	Unheated 1884 gambrel-roof barn in a county park, rented May to mid-October for do-it-yourself weddings with your own vendors.	secreservations@oaklandcountymi.gov	248-599-2708	https://www.oaklandcountymi.gov/community/oakland-county-parks/parks-trails/springfield-oaks/ellis-barn
Fenton Winery & Brewery	1370 N Long Lake Rd	Fenton	Michigan			Restaurant / Vineyard	Indoor & Outdoor			Winery and brewery with a garden, courtyard and taproom that also runs a dedicated wedding venue.		(810) 373-4194	https://www.fentonbrewery.com/weddings
Oakhurst Golf & Country Club	7000 Oakhurst Ln	Clarkston	Michigan			Ballroom / Hotel	Indoor & Outdoor			Hillside clubhouse with a veranda overlooking the golf course's rolling hills for ceremonies and receptions.		248-391-3300	https://invitedclubs.com/clubs/oakhurst-golf-country-club/weddings-oakhurst-google
Vale Royal Barn	11009 Old US 23	Fenton	Michigan			Barn / Rustic	Indoor & Outdoor			Prairie-style property on eight acres with a willow-lined river and ceremony sites at a courtyard, woods, riverside and covered bridge.	valeroyalbarn@gmail.com	(810) 265-8481	https://www.thevaleroyalbarn.com
Blossom Heath Inn	24800 Jefferson Ave	St. Clair Shores	Michigan			Historic / Estate	Indoor & Outdoor			Prohibition-era banquet hall near Lake St. Clair with a bookable gazebo and renovated ballroom.	chris.cassetta@encorebanquets.com	(586) 772-0450	https://blossomheathscs.com/
Indianwood Golf & Country Club	1081 Indianwood Rd	Lake Orion	Michigan			Historic / Estate	Indoor & Outdoor	190		1920s clubhouse with castle-like detailing among century-old pines, holding up to 190 for a wedding in its Great Hall.	info@iwgcc.com	248.693.9100	https://iwgcc.com/weddings-corporate-events/
The Palazzo Grande	54660 Van Dyke Ave	Shelby Township	Michigan			Ballroom / Hotel	Indoor	1500		Large banquet center with about 25,000 square feet of ballroom space and an in-house kitchen.		586-731-2100	https://thepalazzogrande.com
Dearborn Inn, Autograph Collection	20301 Oakwood Blvd	Dearborn	Michigan			Ballroom / Hotel	Indoor & Outdoor	800		Hotel on 23 landscaped acres beside Ford's headquarters with two ballrooms plus a garden ceremony space and gazebo.		313-271-2700	https://www.marriott.com/en-us/hotels/dtwdk-dearborn-inn-autograph-collection/events/
Peacock Road Family Farm	11854 Peacock Rd	Laingsburg	Michigan			Barn / Rustic	Indoor & Outdoor			Family farm that hosts weddings with personal attention from the owners, alongside seasonal farm activities.		517-651-9193	https://peacockrff.com
Cross W Ranch	3111 Pinckney Rd	Howell	Michigan			Barn / Rustic	Indoor & Outdoor			Working cattle ranch of 350 acres with woodlands and a private pond, holding weddings in its barn.	weddings@crosswranch.com	517-588-6242	https://crosswranchweddings.com/
The Mirage Banquets	16980 18 Mile Rd	Clinton Township	Michigan			Ballroom / Hotel	Indoor			Banquet venue with ballrooms for ceremony and reception and in-house decor and catering partners.	help@themiragebanquets.com	(586) 228-2222	https://www.themiragebanquets.com/
Kellogg Hotel & Conference Center	219 S Harrison Rd	East Lansing	Michigan			Ballroom / Hotel				Ivy-covered hotel and conference centre on the Michigan State campus with ballroom space and landscaped grounds.		517-884-8177	https://kelloggcenter.com/weddings
Grewal Hall at 224	224 S Washington Sq	Lansing	Michigan			Historic / Estate	Indoor	225		Renovated 1926 downtown Lansing building with banquet seating for up to 225 guests.	info@hall224.com		https://www.grewalhallweddings.com/
The Great Hall Banquet & Convention Center	5121 Bay City Rd	Midland	Michigan			Ballroom / Hotel				Midland banquet hall hosting wedding receptions with full-service catering on site.	sales@GreatHallMi.com	989-496-2158	https://www.greathallmi.com/weddings
Golden Glow Ballroom	2950 S Graham Rd	Saginaw	Michigan			Ballroom / Hotel	Indoor & Outdoor	500		Saginaw ballroom venue for ceremonies and receptions, with its largest room holding up to 500 guests.	info@goldenglow.com	989-781-2120	https://www.goldenglow.com/
Montague Inn Bed & Breakfast	1581 S Washington Ave	Saginaw	Michigan			Historic / Estate				1929 Georgian mansion on Lake Linton set in eight acres of gardens, offering garden ceremonies and lodging.	innkeeper@montagueinn.com	989-752-3939	https://montagueinn.com/
Liberty Harbor Event Center	804 E Midland St	Bay City	Michigan			Ballroom / Hotel				Bay City event space for weddings, ceremonies and banquets, part of a riverside complex with a brewpub.	info@whcmi.com	989-778-2347	https://libertyharboreventcenter.com/
Bucks Run Golf Club	1559 S Chippewa Rd	Mount Pleasant	Michigan			Ballroom / Hotel	Indoor & Outdoor	250		Golf club with an indoor banquet room for up to 250 and a lakeside pergola for ceremonies over Lake Fisher.		989-779-9973	https://www.bucksrun.com/weddings
Little Flower Barn	565 N Coldwater Rd	Lake Isabella	Michigan			Barn / Rustic				Barn venue near Mount Pleasant with a ceremony garden, a reception barn and a pavilion with a bar.	LittleFlowerBarn@gmail.com	989-644-5149	https://www.littleflowerbarn.com/
Round Em Up Ranch	14164 N Clio Rd	Clio	Michigan			Barn / Rustic	Indoor & Outdoor		Simple	7,200 square foot barn on a 17-acre horse farm with an outdoor ceremony arbor and a bring-your-own-vendor policy.		810-397-5105	https://roundemupranch.com/
Redwood	5304 Gateway Centre Dr	Flint	Michigan			Restaurant / Vineyard	Indoor	120		Flint restaurant with three private rooms for receptions of up to 120 guests, plus its own wedding catering.		810-233-8000	https://redwoodflint.com/weddings`,
  },
];

export default batches;
