import type { VenueBatch } from "@/lib/venue-batches";

// Minnesota venue batches. Every row's State is "Minnesota". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Minneapolis–Saint Paul, Stillwater, Duluth and the North Shore",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Hope Glen Farm	10276 East Point Douglas Rd S	Cottage Grove	Minnesota			Barn / Rustic	Indoor & Outdoor	280		Working farm dating to 1860 beside Cottage Grove Ravine Regional Park, with a barn, vineyard ceremony site and a wedding-night suite.		612-202-2886	https://www.hopeglenfarm.com
Union Depot	214 4th St E	Saint Paul	Minnesota			Historic / Estate	Indoor			Restored 1920s railway station whose high-ceilinged Waiting Room hosts ceremonies and receptions, with a smaller Red Cap Room and getting-ready suites.		651-202-2700	https://www.uniondepot.org/plan-your-event/weddings/
Agate Acres Farm	1109 Two Harbors Rd	Two Harbors	Minnesota			Barn / Rustic	Indoor & Outdoor	160		Sixty-acre North Shore flower farm with a historic red barn, forest paths and a half mile of river frontage near Lake Superior.	events@agateacres.com		https://www.agateacres.com/weddingpackages
Pier B Resort	800 W Railroad St	Duluth	Minnesota			Beach / Waterfront	Indoor & Outdoor	180		Harbourside hotel with a ballroom and rooftop deck facing the Duluth marina, Bayfront Park and the Aerial Lift Bridge.		218-481-8888	https://www.pierbresort.com/weddings/
Fitger's Inn	600 E Superior St	Duluth	Minnesota			Ballroom / Hotel	Indoor & Outdoor	150		Lakefront hotel and event complex in a former brewery, with a Lake Superior view room, ballroom and courtyard.		(218) 722-8826	https://fitgers.com/wedding-and-group-private-events/
Lutsen Mountains Summit Chalet	467 Ski Hill Rd	Lutsen	Minnesota			Garden / Outdoor	Indoor & Outdoor	175		Mountaintop chalet with outdoor ceremony spots over Lake Superior and on-site resort lodging for wedding guests.	legendaryweddings@midwestfamilyskiresorts.com	(218) 663-7281	https://www.lutsen.com/plan-purchase/groups-weddings/weddings-at-lutsen
Parley Lake Winery	8280 Parley Lake Rd	Waconia	Minnesota			Restaurant / Vineyard	Indoor & Outdoor	200	Simple	Working vineyard and orchard of about 125 acres with a historic apple barn, several vineyard ceremony spots and a lake-view stage.	info@parleylake.com		https://www.parleylakewinery.com/weddings
The Saint Paul Hotel	350 Market St	Saint Paul	Minnesota			Ballroom / Hotel	Indoor			Historic downtown hotel with over 14,000 square feet of event space, ballroom receptions and guest rooms for the wedding party.		651-228-3886	https://www.saintpaulhotel.com/weddings/
W.A. Frost & Company	374 Selby Ave	Saint Paul	Minnesota			Restaurant / Vineyard	Indoor & Outdoor			Cathedral Hill restaurant in the historic Dacotah Building with private dining rooms, a fireside room and a garden patio for small weddings.	host@wafrost.com	(651) 224-5715	https://www.wafrost.com/private-events
Minnesota Landscape Arboretum	3675 Arboretum Dr	Chaska	Minnesota			Garden / Outdoor	Indoor & Outdoor	300		University of Minnesota arboretum with over 1,200 acres of gardens, a conservatory and nearly two dozen indoor and outdoor wedding spaces.		(612) 301-4353	https://arb.umn.edu/weddings
Lafayette Club	2800 Northview Rd	Minnetonka Beach	Minnesota			Beach / Waterfront	Indoor & Outdoor	500		Lake Minnetonka club whose century-old crystal ballroom has an enclosed veranda, plus a lakeview deck and a bayside garden for ceremonies.		952-471-6411	https://www.lafayetteclub.com/weddings
Bruentrup Heritage Farm	2170 County Road D E	Maplewood	Minnesota			Barn / Rustic	Indoor & Outdoor	160		Historic farmstead on 22 acres of restored prairie and oak savanna, centred on a 1905 barn with Arts and Crafts gardens.	events@MaplewoodMuseum.org	(651) 748-8645	https://maplewoodmuseum.org/site-rental/
Machine Shop	300 2nd St SE	Minneapolis	Minnesota			Historic / Estate	Indoor			Open, flexible industrial hall in Northeast Minneapolis's St. Anthony neighbourhood, a short walk from the Mississippi.	eventmanagers@damico.com	612-238-4444	https://machineshopmpls.com
Oak Glen Golf Course	1599 McKusick Rd N	Stillwater	Minnesota			Garden / Outdoor	Indoor & Outdoor	400		Golf course just outside Stillwater whose Royal Oak reception room has a fireplace and dance floor, with two outdoor ceremony sites.		651-439-6981	https://oakglengolf.com/weddings
`,
  },
  {
    name: "Minneapolis–Saint Paul suburbs, Duluth, the North Shore and Brainerd lakes",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Hutton House	10715 South Shore Dr	Medicine Lake	Minnesota			Ballroom / Hotel	Indoor & Outdoor	250		Event venue near Medicine Lake with about 12,500 square feet of indoor space, private dressing rooms and a bluestone courtyard with a gas fire pit.	hello@thehuttonhousemn.com	952.470.0788	https://thehuttonhousemn.com/
Bavaria Downs	3919 Bavaria Rd	Chaska	Minnesota			Historic / Estate	Indoor & Outdoor			Two-hundred-acre Chaska property with three separate wedding venues: a French-style estate, an equestrian-themed hall and a glass-walled space opened in 2025.			https://www.bavariadowns.com/
Stillwater Event Center	1910 S Greeley St	Stillwater	Minnesota			Ballroom / Hotel	Indoor & Outdoor	225		Event hall near downtown Stillwater with a bridal suite, on-site catering, and a renovated patio with a pergola for ceremonies.	Events@StillwaterEventCenter.com	651-430-3274	https://stillwatereventcenter.com/
Mystic Lake Center	2400 Mystic Lake Blvd	Prior Lake	Minnesota			Ballroom / Hotel	Indoor	800		Resort event centre at Mystic Lake with about 130,000 square feet of flexible space, an on-site hotel and in-house catering.		(866) 832-6402	https://www.mysticlakecenter.com/weddings
Hidden Greens Event Venue	12977 200th St E	Hastings	Minnesota			Garden / Outdoor	Indoor & Outdoor	300		Event venue on the grounds of Hidden Greens Golf Course beside a state game refuge, with a stone patio, a three-tier waterfall and a bridal suite.	hiddengreensweddings@gmail.com	651-437-1813	https://www.hiddengreensevents.com/
The Wexford at Emerald Greens	14425 Goodwin Ave	Hastings	Minnesota			Ballroom / Hotel	Indoor & Outdoor	400		Newer golf-course event venue in Hastings with an indoor hall for up to 400 guests and a patio with fire tables.	thewexford@emeraldgreensgolf.com	(651) 270-9958	https://wexfordweddings.com/
Almquist Farm	21321 Polk Ave	Hastings	Minnesota			Barn / Rustic	Indoor & Outdoor	340		Farm of more than 70 acres with a renovated wedding barn that seats 340, plus outdoor ceremony and dining areas.	Paul@AlmquistFarm.com	651-408-4030	https://www.almquistfarm.com/
Green Acres Event Center	14150 Pioneer Trail	Eden Prairie	Minnesota			Barn / Rustic	Indoor & Outdoor	225	Classic	Historic Eden Prairie barn saved from demolition, with three event spaces across two levels and on-site parking for 60 cars.		952-942-5220	https://www.greenacreseventcenter.com/
Hastings Golf Club	2015 Westview Dr	Hastings	Minnesota			Garden / Outdoor	Indoor & Outdoor	315		Semi-private 18-hole golf club established in 1929, with a restaurant and event facility that takes weddings and banquets.	nicole@hastingsgolfclub.com	(651) 437-4210	https://www.hastingsgolfclub.com/weddings-banquets/
A'BULAE	255 6th St E	Saint Paul	Minnesota			Ballroom / Hotel	Indoor & Outdoor			Sixth-floor loft-style ballroom in downtown Saint Paul with floor-to-ceiling windows, a rooftop deck and views toward the Capitol.	info@abulae.com	651.788.9818	https://www.abulae.com/
Kellerman's Event Center	2222 4th St	White Bear Lake	Minnesota			Historic / Estate	Indoor		Classic	Downtown White Bear Lake building dating from 1907, once a YMCA and a movie theatre, with hardwood floors, fir trusses and separate getting-ready suites.	Inquiries@kellermanseventcenter.com	651-429-9286	https://www.kellermanseventcenter.com/
The Hotel Landing	925 Lake St	Wayzata	Minnesota			Ballroom / Hotel	Indoor & Outdoor	120		Lake Minnetonka hotel in Wayzata offering a Great Lawn and mezzanine porches for weddings of 20 to 120 guests, with in-house catering.		(952) 777-7900	https://www.thehotellanding.com/celebrate/weddings/
Clyde Iron Works	2920 W Michigan St	Duluth	Minnesota			Historic / Estate	Indoor	600		Restaurant and event centre in a steel fabrication works founded in 1889, with 40-foot ceilings, two balconies and private bridal and groom suites.	events@clydeironworks.com	218-727-1150	https://clydeironworks.com/weddings
The Garden	425 Lake Ave S	Duluth	Minnesota			Historic / Estate	Indoor			Event space in a historic Canal Park building, run by the Sports Garden, for wedding receptions and smaller celebrations.	theGarden@grccorp.com	218-722-4724	https://thegardenduluth.com/
Black Woods Event Center		Duluth	Minnesota			Ballroom / Hotel	Indoor & Outdoor	225		Renovated event centre joined to the AmericInn Duluth South, with a private bar, in-house catering and rooms from a Skyline space to a full facility.	banquets@blackwoods.com	218.724.0000	https://www.blackwoodseventcenter.com/
Merryweather Inn	2316 E 1st St	Duluth	Minnesota			Historic / Estate	Indoor & Outdoor			Small bed and breakfast on Duluth's East First Street hosting intimate weddings and elopements, with guest rooms for the wedding party.	innkeeper@merryweatherinn.com		https://www.merryweatherinn.com/weddings-and-parties
Superior Shores Resort	1521 Superior Shores Dr	Two Harbors	Minnesota			Beach / Waterfront	Indoor & Outdoor	225		Lake Superior resort near Two Harbors with a new indoor lakeside ballroom, outdoor lakeside ceremony spots and on-site lodging.		218-530-2250	https://www.superiorshores.com/weddings/
Cragun's Resort	11000 Craguns Dr	Brainerd	Minnesota			Beach / Waterfront	Indoor & Outdoor	450		Gull Lake resort near Brainerd with lakeside ceremony spots, a Cedar Ballroom and dining rooms that can be split into smaller areas.		(218) 829-9188	https://craguns.com/weddings/ceremony-and-reception-venues/
Breezy Point Resort	9252 Breezy Point Dr	Breezy Point	Minnesota			Beach / Waterfront	Indoor & Outdoor	400		Pelican Lake resort with lawn and garden pavilion ceremony sites, a Lakeside Ballroom and conference-centre rooms for up to 400 guests.	info@breezypointresort.com	218-562-7970	https://breezypointresort.com/wed/
Ruttger's Bay Lake Resort	25039 Tame Fish Lake Rd	Deerwood	Minnesota			Beach / Waterfront	Indoor & Outdoor	300		Bay Lake resort with vows on the shore, a 5,300-square-foot Island Ballroom upstairs and cabins, villas and lodge rooms for guests.		218-678-2885	https://www.ruttgers.com/weddings
`,
  },
  {
    name: "Rochester, Red Wing and the Twin Cities",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Mayowood Stone Barn	3385 Mayowood Road SW	Rochester	Minnesota			Historic / Estate	Indoor & Outdoor	300		Stone barn on the historic Mayowood grounds south-west of Rochester, with a two-level main barn, a small blacksmith shop and lawns for outdoor vows.	melissa@mayowoodstonebarn.com	(507) 281-2276	https://mayowoodstonebarn.com/wedding-venue-rentals/
Rochester Event Center	7333 Airport View Drive SW	Rochester	Minnesota			Ballroom / Hotel	Indoor	650		Event centre near Rochester's airport whose 13,000-square-foot Grand Ballroom can be split in two, with in-house catering and free parking.		(507) 529-0033	https://rochestereventcenter.com/weddings/
J Powers	10 E Center St	Rochester	Minnesota			Ballroom / Hotel	Indoor & Outdoor			Downtown Rochester event centre with ballroom-style halls, 19-foot ceilings, floor-to-ceiling city views and an outdoor terrace.		(507) 361-3600	https://jpowers.events/our-spaces/
Blue Moon Ballroom	2030 Hwy 14 East	Rochester	Minnesota			Ballroom / Hotel	Indoor	250		Rochester dance studio and reception hall with a large maple dance floor, tables for 250 and more than 700 receptions behind it.	fred@bluemoonballroom.com	(507) 358-3484	https://www.bluemoonballroom.com/wedding-reception-event-venue-rochester-mn
LC's Venue	316 Broadway Avenue S	Rochester	Minnesota			Barn / Rustic	Indoor	150		Rustic-chic downtown Rochester venue for up to 150 under string lights, offering full-service weddings with its own catering.		(507) 254-4711	https://www.lcsvenue.com/weddings
Bearwood Event Barn	5901 County Road 105 NW	Byron	Minnesota			Barn / Rustic	Indoor & Outdoor			An 8,000-square-foot barn-style venue beside a county park in the Zumbro River valley, under ten minutes from Rochester, with a stamped-concrete patio.	bearwoodeventbarn@gmail.com	(507) 421-7088	https://bearwoodeventbarn.com/weddings-2/
Garten Marketplatz	5225 County Road 15 SW	Byron	Minnesota			Garden / Outdoor	Indoor & Outdoor	150		Family garden centre on ten acres south-west of Rochester with six ceremony and reception spots, from flower gardens and patios to a carriage house.		(507) 365-8891	https://gartenmarketplatz.com/weddings
Pond View Barn	23897 510th St	Pine Island	Minnesota			Barn / Rustic	Indoor & Outdoor	200	Classic	Wooded barn property with a pond near Pine Island that hosts one wedding a week from May to October, with a loft, reception tent and getting-ready cottages.	pondviewbarn@gmail.com	(507) 421-6443	https://www.pondviewbarn.com/pricing
Steeplechase Event Center	59468 423rd Ave	Mazeppa	Minnesota			Garden / Outdoor	Indoor & Outdoor			Ski hill north of Rochester that hosts spring-to-autumn weddings in a timber lodge with arched windows, with outdoor ceremonies overlooking the bluffs.	steeplechaseevents@gmail.com	(507) 261-8033	https://www.steeplechaseevents.com/weddings
Joy Ridge Event Center	273 Mill Creek Road NW	Chatfield	Minnesota			Ballroom / Hotel	Indoor & Outdoor	277		Renovated Chatfield event centre with a ballroom seating up to 277, a lounge, bridal suite and large outdoor patio, plus its own bar service.			https://joyridgeeventcenter.com/weddings/
Four Daughters Vineyard & Winery	78757 State Highway 16	Spring Valley	Minnesota			Restaurant / Vineyard	Indoor & Outdoor	300		Winery south of Rochester with ceremonies down the aisle of a six-acre vineyard and receptions in a barrel room for up to 300, catered by its own chefs.		(507) 346-7300	https://fourdaughtersvineyard.com/weddings/
The Skyroom	1311 W 6th Street	Red Wing	Minnesota			Garden / Outdoor	Indoor & Outdoor			Renovated event room atop the Red Wing Golf Course clubhouse with a skylight and wraparound deck, plus the on-site Walsh House for the wedding party.		(651) 212-4881	https://skyroommn.com/details-or-the-skyroom
St. James Hotel	406 Main Street	Red Wing	Minnesota			Historic / Estate	Indoor & Outdoor	240	Classic	Family-owned Red Wing hotel open since 1875 beside the Mississippi, with five wedding spaces, guest rooms and its own catering.	info@st-james-hotel.com	(651) 388-2846	https://st-james-hotel.com/explore-our-wedding-venues/
The Van Dusen Mansion	1900 Lasalle Ave	Minneapolis	Minnesota			Historic / Estate	Indoor	175		Restored historic mansion near downtown Minneapolis hosting seated dinners for up to 175, or progressive receptions that move through four rooms.	info@thevandusenmansion.com	(612) 871-2702	https://www.thevandusenmansion.com/
The Depot Minneapolis	225 3rd Avenue South	Minneapolis	Minnesota			Historic / Estate	Indoor			Historic railway depot in the Mill District near the Stone Arch Bridge, joined to two hotels, with a banquet captain for each wedding.	Weddings@TheDepotMinneapolis.com	(612) 758-7804	https://thedepotminneapolis.com/weddings/
Hewing Hotel	300 N Washington Ave	Minneapolis	Minnesota			Ballroom / Hotel	Indoor & Outdoor			Hotel in a historic North Loop warehouse with timber beams and exposed brick, hosting weddings across its event rooms, lounges and rooftop.		(651) 468-0400	https://hewinghotel.com/gather/weddings/
Heritage Center of Brooklyn Center	6155 Earle Brown Drive	Minneapolis	Minnesota			Historic / Estate	Indoor & Outdoor			Brooklyn Center venue with rustic, character-rich rooms, a fountain courtyard for outdoor ceremonies and in-house catering by Mintahoe.	sales@heritagecenter.mn	(763) 569-6300	https://heritagecenter.mn/weddings/
Pinewood Weddings & Events	33262 Palm St NW	Cambridge	Minnesota			Garden / Outdoor	Indoor & Outdoor	225		Newly built event centre on ten acres of tall pines north of the Twin Cities, with tables and chairs for 225 and indoor and outdoor bars.			https://pinewoodmn.us/
`,
  },
];

export default batches;
