import type { VenueBatch } from "@/lib/venue-batches";

// Missouri venue batches. Every row's State is "Missouri". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Kansas City and St. Louis",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Guild KC	1621 Locust St	Kansas City	Missouri			Ballroom / Hotel	Indoor & Outdoor	250		A converted automotive warehouse in Kansas City with a 6,500 sq ft hall under exposed trusses and a 5,000 sq ft courtyard garden.	info@theguildkc.com	816-471-8550	https://theguildkc.com/weddings/
Loose Mansion	101 E Armour Blvd	Kansas City	Missouri			Historic / Estate	Indoor			A restored 1907 mansion near Armour Boulevard with about 15,000 sq ft of rooms, carved mahogany woodwork, fireplaces and an on-site bed and breakfast.			https://loosemansion.com/
The Elms Hotel & Spa	401 Regent St	Excelsior Springs	Missouri			Ballroom / Hotel	Indoor & Outdoor			A historic spa hotel open for more than 130 years, with two ballrooms, a garden gazebo for ceremonies and a 28,000 sq ft spa.		816-630-5500	https://www.elmshotelandspa.com/weddings.htm
White Iron Ridge	815 State Route 92 Hwy	Smithville	Missouri			Barn / Rustic	Indoor & Outdoor		Classic	A gambrel-roofed event barn on the edge of Smithville with arched ceilings, iron chandeliers and overnight guest suites on site.	amanda@whiteironridge.com	816-866-8996	https://whiteironridge.com/investment-wedding
Powell Gardens	1609 NW US Highway 50	Kingsville	Missouri			Garden / Outdoor	Indoor & Outdoor	200	Classic	A botanical garden east of Kansas City with a chapel, a lakeside Grand Hall and a Missouri Barn among its themed gardens.	events@powellgardens.org	816-697-2600	https://powellgardens.org/weddings/
Longview Estate	1200 SW Longview Park Dr	Lee's Summit	Missouri			Historic / Estate	Indoor & Outdoor	250		R.A. Long's 1914 mansion on more than 10 acres, with a lawn and sunken garden for ceremonies and a conservatory for receptions.		816-761-6669	https://www.longviewmansion.com/
Chandler Hill Vineyards	596 Defiance Rd	Defiance	Missouri			Restaurant / Vineyard	Indoor & Outdoor	250		A Missouri wine-country winery with a tasting room and covered deck overlooking its vines and the surrounding hills.	brooke@chandlerhillvineyards.com	636-798-2675	https://www.chandlerhillvineyards.com/weddings
The Cheshire	6300 Clayton Rd	St. Louis	Missouri			Ballroom / Hotel	Indoor	250	Classic	A boutique hotel by Forest Park whose upstairs reception room keeps the building's original vaulted, dark-beamed ceiling.	cheshire@cheshirestl.com	314-647-7300	https://www.cheshirestl.com/weddings-events/cheshire-weddings
The Noble	3611 S Grand Blvd	St. Louis	Missouri			Historic / Estate	Indoor	220		A 1928 South Grand bank building restored to its Art Deco detail, keeping the original vault, columns and chandeliers.	info@culinarycanvasstl.com	314-252-8130	https://thenoblestl.com/weddings/
The Hawthorn	2231 Washington Ave	St. Louis	Missouri			Ballroom / Hotel	Indoor	500		A downtown event hall of over 10,000 sq ft near City Stadium, with two full bars and four suites with private showers.	events@thehawthornstl.com	314-887-0877	https://www.thehawthornstl.com/
Missouri Botanical Garden	4344 Shaw Blvd	St. Louis	Missouri			Garden / Outdoor	Indoor & Outdoor			A 79-acre botanical garden in south St. Louis with indoor and outdoor ceremony and reception sites booked through its in-house caterer.		314-577-0200	https://www.missouribotanicalgarden.org/events-classes/private-events-rentals`,
  },
  {
    name: "Kansas City and St. Louis: second batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Bauer	115 W 18th St	Kansas City	Missouri			Historic / Estate	Indoor			An event floor at the top of the former Bauer Machine Works building in the Crossroads Arts District, with a flexible open plan and historic detail.	info@thebrideandthebauer.com	816-984-8533	https://www.thebauereventspace.com/
The Abbott	1901 Cherry St	Kansas City	Missouri			Ballroom / Hotel	Indoor & Outdoor	500		A Crossroads Arts District industrial building with exposed brick and high ceilings, seating up to 500, plus an open-air rooftop terrace with skyline views.		816-332-0274	https://www.theabbottvenue.com/
Nelson-Atkins Museum of Art	4525 Oak St	Kansas City	Missouri			Historic / Estate	Indoor & Outdoor	450	Luxury	An art museum whose 40-foot-high Kirkwood Hall, lined with twelve black-and-white marble columns and tapestries, seats 450, with Rozzelle Court and a modern lobby too.	eventrentals@nelson-atkins.org	816-751-1234	https://nelson-atkins.org/events/event-rental/
Hawthorne House	6008 NW Bell Rd	Parkville	Missouri			Garden / Outdoor	Indoor & Outdoor			A Northland wedding venue running since 1997, with a garden gazebo for outdoor ceremonies, an indoor chapel and a reception hall.	support@thehawthornehouse.com	816-384-3630	https://www.thehawthornehouse.com/
Feasts of Fancy	1427 W 9th St	Kansas City	Missouri			Historic / Estate	Indoor & Outdoor	250		A caterer-run event space in the Historic West Bottoms, open since 2001, with a dance floor and a private walled courtyard garden.			https://feastsoffancy.com/
UNION	1721 Baltimore Ave	Kansas City	Missouri			Historic / Estate	Indoor	200		A 7,500 sq ft Crossroads building put up in 1929 as a film-processing centre, with exposed brick, open beams and wood floors, rented by the day.	party@union.828venues.com	913-213-3494	https://union.828venues.com/
Casa Loma Ballroom	3354 Iowa Ave	St. Louis	Missouri			Ballroom / Hotel	Indoor	850		A south St. Louis ballroom opened in 1927 near Cherokee Street, known for its 5,000 sq ft floating dance floor and still running public dance nights.	pvbrannon@aol.com	314-282-2258	https://www.casalomaballroom.com/
Hotel Saint Louis	705 Olive St	St. Louis	Missouri			Ballroom / Hotel	Indoor & Outdoor			A downtown Autograph Collection hotel offering a ballroom and a rooftop pool terrace for receptions, with a suite for the couple on the night.	stleventsales@hotelsaintlouis.com	314-241-4300	https://www.hotelsaintlouis.com/weddings
Moonrise Hotel	6177 Delmar Blvd	St. Louis	Missouri			Ballroom / Hotel	Indoor & Outdoor			A space-themed boutique hotel on the Delmar Loop with Apollo and Gemini event rooms, a rooftop garden bar and an eighth-floor room under a solar-panel roof.	Catering@MoonriseHotel.com	314-721-1111	https://moonrisehotel.com/meetings-events/weddings/
St. Louis Union Station	1820 Market St	St. Louis	Missouri			Ballroom / Hotel	Indoor			A restored downtown railway terminal, now a Curio Collection hotel, with an arched, mosaic Grand Hall, four ballrooms and the glass-roofed Midway train shed.	info@stlouisunionstation.com	314-923-3900	https://www.stlouisunionstation.com/private-events
Defiance Ridge Vineyards	2711 S Hwy 94	Defiance	Missouri			Restaurant / Vineyard	Indoor & Outdoor			A winery with its own winemaker and kitchen on Highway 94 in St. Charles County wine country, open year-round with indoor and outdoor event space.	info@defianceridge.com	636-798-2288	https://www.defianceridgevineyards.com/weddings-events
The Sheldon	3648 Washington Blvd	St. Louis	Missouri			Historic / Estate	Indoor	350		A Grand Center concert hall and gallery building with a 712-seat hall for ceremonies, a beamed-ceiling ballroom with a stage and a room looking toward the Cathedral Basilica.		314-533-9900	https://www.thesheldon.org/venue-rentals/`,
  },
  {
    name: "Kansas City and St. Louis: third batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Mount Pleasant Estates	5634 High St	Augusta	Missouri			Restaurant / Vineyard	Indoor & Outdoor			Augusta's oldest winery, founded in 1859, on bluffs above the Missouri River Valley with a river-view ceremony site, terrace ballroom and 1881 limestone wine cellars.	info@mountpleasant.com		https://mountpleasant.com/weddings/
Sugar Creek Winery	125 Boone Country Lane	Defiance	Missouri			Restaurant / Vineyard	Indoor & Outdoor		Simple	Family winery on 30 acres in the Defiance wine country, with vineyard, bluff and wine-cellar spots for ceremonies and outside catering allowed.	sugarcreekwineryweddings@gmail.com	(636) 987-2400	https://sugarcreekwines.com/weddings-at-sugar-creek
Foundry Art Centre	520 North Main Center	St. Charles	Missouri			Historic / Estate	Indoor	400		Former railroad manufacturing building turned arts centre beside the Missouri River and Katy Trail in downtown St. Charles, with a Grand Hall and a smaller East Gallery.	PBaker@foundryartcentre.org	636-255-6178	https://foundryartcentre.org/venue-rental-info
Madrid Theatre	3810 Main Street	Kansas City	Missouri			Historic / Estate	Indoor	500	Classic	Historic Spanish-style theatre in Midtown, restored in 2020, with main floor, balcony and mezzanine levels and tables, linens and marquee message included.	info@madridtheatre.com	816-753-8880	https://madridtheatre.com/weddings/
Loews Kansas City Hotel	1515 Wyandotte Street	Kansas City	Missouri			Ballroom / Hotel	Indoor			Downtown hotel connected to the convention district with 60,000 square feet of event space, including the Neptune and City Beautiful ballrooms.		816-897-7087	https://www.loewshotels.com/kansas-city-hotel/weddings
Sunflower Hill Farm	245 Terry Road	Augusta	Missouri			Barn / Rustic	Indoor & Outdoor			130-acre farm in the Augusta wine country with a modern barn-style event centre, an outdoor ceremony site, a wine cellar, produce garden and greenhouse.	contact@sunflowerhillfarm.com	314-461-5131	https://www.sunflowerhillfarm.com/services
The Hilltop KC	6824 Highway 131	Odessa	Missouri			Garden / Outdoor	Indoor & Outdoor	125	Simple	Hilltop venue east of Kansas City off I-70 with a sunset-facing lawn for ceremonies, a windowed sunroom as the rain backup and a separate reception hall.	Info@TheHilltopKc.com	816-286-7839	https://www.thehilltopkc.com/
Alexander Majors Barn	8201 State Line Rd	Kansas City	Missouri			Barn / Rustic	Indoor & Outdoor	150	Simple	Barn beside the historic Alexander Majors house museum, with a loft, a wagon room holding a mid-1800s Conestoga wagon, and a patio, lawn and neighbouring park.	rentals@wornallmajors.org	(816) 444-1858	https://wornallmajors.org/barn-venues-in-kansas-city/
Kauffman Center for the Performing Arts	1601 Broadway Blvd	Kansas City	Missouri			Ballroom / Hotel	Indoor	450		Performing arts centre whose Brandmeyer Great Hall has a four-storey glass wall facing the skyline, with dinners also possible on the Muriel Kauffman Theatre stage and upper balconies.	events@kauffmancenter.org	816.994.7222	https://www.kauffmancenter.org/rent-kauffman-center/
Brookdale Farms	8004 Twin Rivers Road	Eureka	Missouri			Barn / Rustic	Indoor & Outdoor			Farm of nearly 300 acres southwest of St. Louis with two separate wedding sites, a rustic barn and the high-ceilinged Silo Point, plus on-site farmhouse lodging.	info@brookdalefarms.com	636-938-1005	https://www.brookdalefarms.com/wedding-venue
1890 Event Space	15640 92 Hwy Spur	Platte City	Missouri			Historic / Estate	Indoor & Outdoor	300		Estate north of Kansas City with a Victorian house used as the bridal suite, a garden ceremony site with a red stone aisle, a 4,775-square-foot ballroom and overnight lodging for 14.	info@1890kc.com	816-584-1890	https://1890kc.com/venues/eighteen-ninety/
Jewel Box	5600 Clayton Avenue	St. Louis	Missouri			Garden / Outdoor	Indoor	250	Simple	City-run glass conservatory in Forest Park, booked in set ceremony slots by day and for evening receptions, reservable up to two years ahead.	cityparkevents@stlouis-mo.gov	(314) 289-5300	https://www.stlouis-mo.gov/government/departments/parks/parks/rent-jewel-box.cfm`,
  },
];

export default batches;
