import type { VenueBatch } from "@/lib/venue-batches";

// Montana venue batches. Every row's State is "Montana". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Bozeman, Big Sky and Paradise Valley venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Chateau Event Center	1568 Cobb Hill Rd	Bozeman	Montana			Barn / Rustic	Indoor & Outdoor	145		A 2,500 sq ft stone-and-stucco hall with beamed ceilings and a covered patio, set on 40 acres under a conservation easement.	montanachateau@outlook.com	406-600-4161	https://thechateaueventcenter.com/weddings
Rockin' TJ Ranch	651 Lynx Ln	Bozeman	Montana			Barn / Rustic	Indoor & Outdoor			A 10-acre property beside Hyalite Creek with a 4,800 sq ft grand hall, groom's cabin and views of the Bridger Mountains.		406-585-0595	https://rockingtjranch.com/weddings/weddings
Firelight Farm	140 Quentin Way	Bozeman	Montana			Barn / Rustic	Indoor & Outdoor		Classic	A renovated 100-year-old two-story barn with reclaimed wood, a silo and dedicated bridal preparation rooms.		406-600-6762	https://firelightfarmmt.com/weddings
The Woodlands at Cottonwood Canyon	141 Old Timber Way	Bozeman	Montana			Barn / Rustic	Indoor & Outdoor			A forested canyon property about ten miles south of Bozeman with a meadow ceremony site, patio, Great Room and honeymoon cabin.		(406) 763-4542	https://montanawoodlands.com
Bodhi Farms	13624 S Cottonwood Rd	Bozeman	Montana			Garden / Outdoor	Outdoor	125		A 35-acre eco resort beside Cottonwood Creek with hand-built cabins, glamping tipis, a sailcloth-tent event park and an aspen-grove garden.	concierge@bodhi-farms.com	(406) 201-1324	https://www.bodhi-farms.com/weddings
Foster Creek Farm	2577 Foster Creek Road	Belgrade	Montana			Barn / Rustic	Indoor & Outdoor	250		A 130-year-old family farm with a restored barn, bridal suite, groom's cabin and lodging, ringed by four mountain ranges.	info@fostercreekfarm.com	(406) 313-2929	https://fostercreekfarm.com
Big Yellow Barn	9466 Springhill Road	Belgrade	Montana			Barn / Rustic	Indoor & Outdoor	150		A historic barn with a patio, deck and lawn, set in open country with mountain views a few minutes from Bozeman.			https://www.bigyellowbarn.com/wedding-packages
Big Vista Ranch	13720 Portnell Rd	Bozeman	Montana			Barn / Rustic	Indoor & Outdoor	300	Classic	A 60-acre ranch outside Bozeman with a 150-seat event lodge, tent space, several ceremony sites and an on-site guest house.	info@bigvistaranch.com	406-920-8804	https://bigvistaranch.com/weddings
Lone Mountain Ranch	750 Lone Mountain Ranch Road	Big Sky	Montana			Barn / Rustic	Indoor & Outdoor	350		A century-old, 25-cabin guest ranch near Yellowstone with a beamed dining hall, covered Ranch Hall and a mountaintop ceremony site.		406-995-4644	https://lonemountainranch.com/weddings
Sage Lodge	55 Sage Lodge Drive	Pray	Montana			Ballroom / Hotel	Indoor & Outdoor			A resort on more than 1,200 acres along the Yellowstone River with an event barn, lodge rooms and four ranch houses under Emigrant Peak.		855-400-0505	https://sagelodge.com/montana-wedding/
Rainbow Ranch Lodge	42950 Gallatin Road	Gallatin Gateway	Montana			Ballroom / Hotel	Indoor & Outdoor	150		A riverside lodge on the Gallatin beneath the Spanish Peaks, with 21 guest rooms and suites, a restaurant and ceremony sites on the bank.	info@rainbowranchbigsky.com	(406) 995-4132	https://rainbowranchbigsky.com/wedding/
Copper Rose Ranch	2173 East River Road	Livingston	Montana			Barn / Rustic	Indoor & Outdoor	250		A century-old Paradise Valley barn, restored with radiant floor heat, plus ten lodgepole cabins and a farmhouse sleeping up to 66.	info@copperroseranch.com	406-229-2016	https://copperroseranch.com/weddings/
Yellowstone Valley Lodge	3840 Highway 89 South	Livingston	Montana			Barn / Rustic	Indoor & Outdoor	200		A riverside lodge with 22 cabins and the Owl's Rest event barn, which has a balcony, wrap-around patio and fire pit, facing the Absarokas.		+1 (406) 333-4787	https://www.yellowstonevalleylodge.com/weddings-events
Star M Barn	4186 Stimson Lane	Belgrade	Montana			Barn / Rustic	Indoor & Outdoor			A historic hand-raised barn on about 34 acres of farmland, roughly 15 minutes from downtown Bozeman, with mountain views.			https://www.starmbarn.com
1889 Barn	12670 Portnell Road	Bozeman	Montana			Barn / Rustic	Indoor & Outdoor	100		A restored 1889 barn on 21 acres in Gallatin Gateway with a spring-fed creek, covered dance floor and its own licensed bar.	the1889barn@gmail.com	406-579-4865	https://www.1889barn.com
Chico Hot Springs Resort	163 Chico Road	Pray	Montana			Historic / Estate	Indoor & Outdoor	180		A National Register resort in Paradise Valley with two hot spring pools, an event centre, a meadow ceremony site and lodging on 700-plus acres.		(406) 333-4933	https://www.chicohotsprings.com/wedding-venue
Sacajawea Hotel	5 North Main Street	Three Forks	Montana			Historic / Estate	Indoor & Outdoor			A historic hotel refurbished in 2010, offering a lawn courtyard with tent, a lobby and a grill dining room for ceremonies and receptions.	events@sacajaweahotel.com	406-285-6515	https://sacajaweahotel.com/weddings
The Lodge at Whitefish Lake	1380 Wisconsin Ave	Whitefish	Montana			Ballroom / Hotel	Indoor & Outdoor	300		A lakeside resort with a 6,366 sq ft ballroom, a windowed lakeside pavilion, a lawn on Whitefish Lake and on-site rooms and cabins.		1-406-863-4000	https://www.lodgeatwhitefishlake.com/weddings
White Raven	6 Plateau Rd	Alberton	Montana			Ballroom / Hotel	Indoor & Outdoor	125		A mountain-plateau venue and retreat above the Clark Fork River with a ballroom, covered verandas, gardens and trails beside Lolo National Forest.			https://www.whiteravenmontana.com
`,
  },
  {
    name: "Missoula, Bitterroot and Flathead venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Ranch Club	8501 Ranch Club Road	Missoula	Montana			Barn / Rustic	Indoor & Outdoor	300		A golf club event barn west of Missoula that seats 150 inside or up to 300 outdoors, with in-house catering from buffets to plated dinners.		(406) 532-1000	https://ranchclub.com/Events/Barn_Events
Western Cider	501 North California Street	Missoula	Montana			Restaurant / Vineyard	Indoor & Outdoor			A cidery on the Clark Fork River with a tasting room, gallery room and shaded back patio, supplied by its own Bitterroot Valley orchard.	info@westerncider.com	406-540-4477	https://westerncider.com/rentals
Paws Up	40060 Paws Up Road	Greenough	Montana			Barn / Rustic	Indoor & Outdoor	200		A 37,000-acre ranch resort on the Blackfoot River with glamping tents and vacation homes, offering riverside ceremonies and full resort buyouts.		800.210.6445	https://www.pawsup.com/weddings/
Double Arrow Lodge	301 Lodge Way	Seeley Lake	Montana			Ballroom / Hotel	Indoor & Outdoor			A rustic Seeley Lake resort with a main lodge, the Hilltop Lodge and Cougar Cottage for guests, an 18-hole golf course and on-site dining.		(406) 677-2777	https://doublearrowresort.com/weddings/
TimberEdge Meadow		Missoula	Montana			Garden / Outdoor	Outdoor			A forest meadow in the Sapphire Mountains outside Missoula, rented for a 2.5-day weekend with two getting-ready cabins, power, water and room to camp.	lenette@timberedgemeadow.com	(406) 860-7250	https://www.timberedgemeadow.com/
The Barn at Teller	1180 Chaffin Lane	Corvallis	Montana			Barn / Rustic	Indoor & Outdoor			A remodelled event barn with a loft reception space on a historic farmstead at the Teller Wildlife Refuge, with two farm homes sleeping 18.	heather@tellerwildlife.org	406.961.3507	https://www.tellerwildlife.org/weddings
Daly Mansion	251 Eastside Hwy	Hamilton	Montana			Historic / Estate	Outdoor			A historic Bitterroot Valley mansion on 26.5 landscaped acres with some 400 trees, an arbour walkway and a seasonal 40 by 100 ft reception tent.	weddings@dalymansion.org	(406) 363-6004	https://dalymansion.org/weddings/
Bitterroot River Inn & Conference Center	139 Bitterroot Plaza Drive	Hamilton	Montana			Ballroom / Hotel	Indoor & Outdoor			A riverside hotel just north of Hamilton offering ceremonies on its pond lawn facing the Bitterroot Mountains, with guest rooms on site.		(406) 375-2525	https://www.bitterrootriverinn.com/
The Meadows on Rock Creek	100 Hideaway Trail	Philipsburg	Montana			Barn / Rustic	Indoor & Outdoor	220	Luxury	An all-inclusive guest ranch on Rock Creek whose Riversong Barn holds up to 220, with cabins and the Hideaway Lodge sleeping 40 overnight.		(406) 546-2883	https://themeadowsonrockcreek.com/montana-wedding-venue/
Grouse Mountain Lodge	2 Fairway Drive	Whitefish	Montana			Ballroom / Hotel	Indoor & Outdoor	250		A 144-room Whitefish lodge by the golf course whose new 8,250 sq ft event centre, opening fall 2026, seats 250 with indoor-outdoor flow.		844.868.7474	https://www.glacierparkcollection.com/lodging/grouse-mountain-lodge/groups/weddings/
Whitefish Mountain Resort	1015 Glades Drive	Whitefish	Montana			Garden / Outdoor	Indoor & Outdoor	200		A ski resort where ceremonies for up to 200 are held on the summit facing Glacier's peaks, with dinner and dancing at the Base Lodge below.	info@skiwhitefish.com	(406) 862-2900	https://skiwhitefish.com/weddings/
The Hitchin' Post	222 Rusty Spur Trail	Whitefish	Montana			Garden / Outdoor	Outdoor			A private pine-forest setting outside Whitefish for elopements and micro-weddings, beside The Stalls, a horse-barn loft vacation rental.	doug@thestallsatwhitefish.com	(406) 300-2053	https://www.thestallsatwhitefish.com/event
North Forty Resort	3765 MT Hwy 40 West	Columbia Falls	Montana			Barn / Rustic	Indoor & Outdoor			A 40-acre forested resort of handcrafted log cabins with the Snowberry Center, an event hall with a commercial kitchen, and outdoor ceremony space.	events@northfortyresort.com	(406) 862-7740	https://www.northfortyresort.com/weddings-and-events
Ashley Creek Historic Venue	3315 US Highway 93 South	Kalispell	Montana			Historic / Estate	Indoor			The 1939 Kalispell Lumber Co. building, dismantled and rebuilt at Snowline Acres with about 90 percent of its original structure kept.		406-752-1440	https://www.snowlineacres.com/venue
Flathead Lake Lodge	150 Flathead Lodge Rd	Bigfork	Montana			Beach / Waterfront	Indoor & Outdoor			An Averill family guest ranch since 1945 running from the Flathead Lake shore into the Swan Mountains, hosting weddings as three-night buyouts.	info@flatheadlakelodge.com	406-837-4391	https://www.flatheadlakelodge.com/weddings/
The Farmhouse at Flathead Lake	1310 MT Highway 82	Somers	Montana			Barn / Rustic	Outdoor	300	Classic	A farm venue near Somers with a 3,600 sq ft white tent for up to 300, a cocktail lounge with bar, a bridal suite and resident farm animals.	info@flatheadfarmhouse.com	(775) 842-3198	https://www.thefarmhouseatflatheadlake.com/weddings
The Overlook at Flathead Lake		Lakeside	Montana			Historic / Estate	Indoor & Outdoor	200		A private 15-acre estate above Flathead Lake booked one group at a time, sleeping 28 on site, with a heated pool, hot tub and barrel sauna.	theoverlook@luxurylodgingvip.com		https://theoverlookatflatheadlake.com/
Ember & Altar	41500 Stasso Rd	Polson	Montana			Barn / Rustic	Indoor & Outdoor		Simple	A 6,000 sq ft heated and air-conditioned event hall on 60 private acres in the Flathead Valley, with mountain views and horses on the property.	emberandaltar@gmail.com	406.830.4468	https://www.emberandaltar.com/
`,
  },
];

export default batches;
