import type { VenueBatch } from "@/lib/venue-batches";

// Nebraska venue batches. Every row's State is "Nebraska". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Omaha, Lincoln, Kearney and Grand Island",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
A Venue on the Ridge	20033 Elkhorn Ridge Drive	Elkhorn	Nebraska			Ballroom / Hotel	Indoor & Outdoor	300	Simple	Family-run Elkhorn hall with a chandelier-lit ballroom, a bricked outdoor ceremony patio overlooking the ridge, and its own catering and decor team.		402-213-8303	https://www.avenueontheridge.com/
The Steppe Center	11730 Peel Circle	La Vista	Nebraska			Ballroom / Hotel	Indoor	400	Simple	Family-owned banquet hall a few minutes off I-80 in La Vista, with the Birmingham Ballroom, a large service kitchen and a free choice of caterer.	ryan@steppecenter.com	(402) 669-2304	https://www.steppecenter.com/
The Arbor	14040 Arbor Street	Omaha	Nebraska			Garden / Outdoor	Indoor & Outdoor			West Omaha venue run by two sisters, pairing a garden for micro-weddings with an indoor hall that holds parties of up to 300.	info@thearboromaha.com	402-884-2269	https://www.thearboromaha.com/
The Durham Museum	801 S 10th Street	Omaha	Nebraska			Historic / Estate	Indoor			History museum housed in Omaha's Art Deco former Union Station railway terminal, rented out for weddings and receptions.	info@durhammuseum.org	(402) 444-5071	https://durhammuseum.org/museum-rentals/
Omaha Design Center	1502 Cuming Street	Omaha	Nebraska			Ballroom / Hotel	Indoor & Outdoor	550		Industrial 24,000 sq ft building in North Downtown that is home to Omaha Fashion Week, with chandeliers and a patio facing the city skyline.		(402) 819-8792	https://www.omahadesigncenter.com/
Leo Ballroom	2027 Dodge Street	Omaha	Nebraska			Historic / Estate	Indoor	350		Restored 1924 downtown ballroom across from the Joslyn Art Museum, with a working stage, marble staircase and balconies over 12,000 sq ft.		(402) 819-8792	https://www.leoballroom.com/
Lauritzen Gardens	100 Bancroft St.	Omaha	Nebraska			Garden / Outdoor	Indoor & Outdoor		Classic	Omaha's botanical garden, offering themed outdoor gardens, the Quinn Family Oasis and Amphitheater, and indoor rooms for ceremonies and receptions.		402-346-4002	https://www.lauritzengardens.org/space-rental/
Country Pines	6305 West Adams St.	Lincoln	Nebraska			Restaurant / Vineyard	Indoor & Outdoor			Family-owned vineyard venue on 80 acres just outside Lincoln, with a rustic barn, a covered patio and scratch-made catering from its own kitchen.	countrypines1@gmail.com	402-470-3665	https://www.countrypineslincoln.com/
Lincoln Commercial Club	200 N 11th St, Suite 300	Lincoln	Nebraska			Historic / Estate	Indoor			Downtown Lincoln ballroom furnished in turn-of-the-century style, with floor-to-ceiling windows, a mirrored back bar, a library and overnight guest suites.		531-249-1132	https://www.lincolncommercialclub.com/
Seven Willows	7600 Panama Road	Hickman	Nebraska			Barn / Rustic	Indoor & Outdoor	400	Classic	Amish-built post-and-beam barn on a 30-acre horse farm near Hickman, with an outdoor ceremony site among willows beside a pond.	sevenwillowsvenue@gmail.com	(402) 610-3121	https://sevenwillowsvenue.com/
Roca Berry Farm Creekside Barn		Roca	Nebraska			Barn / Rustic	Indoor & Outdoor	400		Restored 1917 barn on a 180-acre family farm south of Lincoln, with a deck overlooking Salt Creek and tiny-home cabins for overnight stays.	Jordan@rocaberryfarm.com	402-525-1999	https://rocaberryfarm.com/pages/weddings
Venue 5 Twenty-Two	1525 Yankee Hill Rd	Lincoln	Nebraska			Ballroom / Hotel	Indoor & Outdoor		Classic	Modern 17,000 sq ft event building in south Lincoln with turfed outdoor spaces, fire pits, a bridal suite and a groom's lounge with putting greens.	lori@venue5twentytwo.com	531-350-5784	https://www.venue5twenty-two.com/
The Village	1920 A Avenue	Kearney	Nebraska			Historic / Estate	Indoor			1940 building in central Kearney converted into an open ballroom with brick walls, wood trusses and steel beams strung with café lights.		(308) 293-0231	https://thevillageevents.com/
Boulder Flatts	4058 Enterprise Avenue	Grand Island	Nebraska			Ballroom / Hotel	Indoor & Outdoor			Modern hall opened in 2022 beside Indianhead Golf Course, with an 8,000 sq ft reception room, 25 chandeliers, a double-sided fireplace and a courtyard.	boulderflatts@gmail.com	308-379-8223	https://www.boulderflatts.com/
Stuhr Museum of the Prairie Pioneer	3133 W US Hwy 34	Grand Island	Nebraska			Historic / Estate	Indoor & Outdoor			Pioneer history museum on more than 200 acres, offering the Stuhr Building, the outdoor Hornady Family Arbor and a small white church for ceremonies.	events@stuhrmuseum.org	(308) 385-5316	https://stuhrmuseum.org/join/weddings/
`,
  },
  {
    name: "Palmyra, York and Hastings",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Glacial Till Vineyard & Winery	344 S 2nd Rd	Palmyra	Nebraska			Restaurant / Vineyard	Indoor & Outdoor	260		Vineyard and cider winery southeast of Lincoln with a ceremony lawn and pavilion, a main hall, two barrel rooms and bridal prep space.	lisa@glacialtillvineyard.com	(402) 610-3068	https://www.glacialtillvineyard.com/vineyard-wedding-venue/
Wessels Living History Farm	5520 S Lincoln Ave	York	Nebraska			Historic / Estate	Indoor & Outdoor	120		Restored 1920s farmstead off Interstate 80 with a post-and-beam barn, a 1905 church sanctuary, a furnished farmhouse and open lawns for ceremonies.	wesselsfarm@gmail.com	(402) 710-0682	https://livinghistoryfarm.org/eventsonthefarm/
Colonial Gardens Event Center	3002 N Baltimore Ave	Hastings	Nebraska			Garden / Outdoor	Indoor & Outdoor	200	Simple	Twelve-acre property northwest of Hastings with a climate-controlled event centre, a main residence, two ponds, a three-hole golf course and lawns for ceremonies.		(402) 469-0888	https://colonialgardensne.com/
`,
  },
  {
    name: "Omaha metro, Lincoln area, Nebraska City, Kearney and Superior",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Venues at the Granary	7401 Main Street	Ralston	Nebraska			Historic / Estate	Indoor & Outdoor	300		Early 20th-century granary building in Ralston converted into event rooms with exposed brick and aged hardwood, plus a 14,000 sq ft heated outdoor green.	events@atthegranary.com	402-943-8387	https://atthegranary.com/
Falconwood Park	905 Allied Road	Bellevue	Nebraska			Barn / Rustic	Indoor & Outdoor			Over 200 acres of wooded grounds south of Omaha with a Bohemian-style lodge nearly a century old, the 2022 Hanke Hall, a woodland pavilion and a dozen ceremony sites.	whatsup@falconwoodpark.com		https://www.falconwoodpark.com/weddings
Bellevue Berry & Pumpkin Ranch	11001 South 48th Street	Papillion	Nebraska			Barn / Rustic	Indoor & Outdoor	400		Working you-pick berry and pumpkin farm with four barn-style lodges of different sizes, each with a country-style outdoor ceremony area.	info@bellevueberryfarm.com	402-661-4786	https://bellevueberryfarm.com/weddings-and-venues
WaConDa Woods & Gardens	2400 WaConDa Road	Union	Nebraska			Garden / Outdoor	Indoor & Outdoor			40 wooded acres of rolling hills with over 5,000 sq ft of indoor reception space, a horse barn with stables and a 1950s one-room schoolhouse used as a bridal suite.	hello@wacondawoodsandgardens.com		https://www.wacondawoodsandgardens.com/
Lilac Hill	14704 156th St	Louisville	Nebraska			Garden / Outdoor	Indoor & Outdoor	300	Classic	Countryside estate near Louisville, about 25 minutes from downtown Omaha, hosting one wedding at a time with an outdoor ceremony lawn and a reception barn.	chris.maxon@thelilachill.com	(402) 215-3365	https://www.thelilachill.com/
Countryside Venue	30030 W Reichmuth Rd	Valley	Nebraska			Barn / Rustic	Indoor & Outdoor	200	Simple	Country event hall west of Omaha near Valley with 4,000 sq ft of indoor space and a large deck that opens up the room to the outdoors.	info@countrysidevenue.com	402-659-1141	https://countrysidevenue.com/
Bliss Barn at Sherwood Forest	13620 A St	Avoca	Nebraska			Barn / Rustic	Indoor & Outdoor		Classic	New barn with exposed timbers, a loft bar and an upstairs bridal suite beside a three-acre pond, roughly halfway between Omaha, Lincoln and Nebraska City.	tammy@blissbarnsherwoodforest.com	(402) 452-9457	https://blissbarnsherwoodforest.com/
Roca Ridge Events	5265 Prairie Sage Drive	Roca	Nebraska			Barn / Rustic	Indoor & Outdoor			Seven-acre property south of Lincoln with a three-story log home, a modern pinewood barn, a west-facing deck, a fire pit and wildflower gardens.	rocaridgeevents@gmail.com	402-405-9212	https://www.rocaridgeevents.com/
Prairie Creek Barn	12296 West Airport Road	Cairo	Nebraska			Barn / Rustic	Indoor & Outdoor			Indoor-outdoor barn on Prairie Creek about eight miles west of Grand Island, with an outdoor ceremony spot and a bridal suite converted from grain bins.	prairiecreekbarn@gmail.com	308-390-9109	https://prairiecreekbarn.com/
The Barn at the Ackerhurst Dairy Farm	15220 Military Road	Bennington	Nebraska			Barn / Rustic	Indoor & Outdoor	450		1935 Dutch gambrel dairy barn 193 feet long, with reception areas on two levels, a hayloft with wooden trusses and a lawn for outdoor ceremonies.	omahabarn@gmail.com	402-250-3139	https://www.omahabarn.com/
Robber's Cave	925 Robbers Cave Road	Lincoln	Nebraska			Historic / Estate	Indoor & Outdoor	300	Simple	Historic Lincoln landmark with a tour-able cave, several rooms seating 80 to 220, a lower level for 300 and the outdoor Dakota Theatre.		(402) 413-7520	https://robberscavelincoln.com/
Le Chateau Venues	2218 Central Ave	Kearney	Nebraska			Historic / Estate	Indoor			Restored downtown Kearney building with skylights, high ceilings, a grand staircase, historic Italian railing spindles and a black-and-white marble dance floor.			https://www.lechateauweddingvenue.com/
Vintage Ballroom	614 South 11th Street	Omaha	Nebraska			Historic / Estate	Indoor			Old Market ballroom in an 1887 former Bemis Bag Company building on the National Register, with original loading-dock floors and an open-vendor, bring-your-own-alcohol policy.	vintageballroom@gmail.com	402-506-6305	https://www.vintageballroom.com/
Arbor Day Farm and Lied Lodge	2700 Sylvan Road	Nebraska City	Nebraska			Garden / Outdoor	Indoor & Outdoor	350		Timber-built lodge hotel on a tree-filled farm with historic barns seating 350, several lawns and groves for ceremonies, and ceremony views of Arbor Lodge Mansion.		402-873-8733	https://www.arbordayfarm.org/weddings
Hillside Events	12400 West Denton Road	Denton	Nebraska			Barn / Rustic	Indoor & Outdoor	250	Simple	Modern-rustic barn venue about ten minutes west of Lincoln, set among pastures, trees, rolling hills and a vineyard.		402-304-3179	https://www.hillsideevents.com/
Superior Estates Winery	200 West 15th Street	Superior	Nebraska			Restaurant / Vineyard	Indoor & Outdoor	250		South-central Nebraska winery whose Chancellor Hall has a timbered cathedral ceiling and vineyard views, with a patio and courtyard beside it.	info@superiorestateswinery.com	402-879-3001	https://superiorestateswinery.com/celebrate-with-us/
Joslyn Art Museum	2200 Dodge Street	Omaha	Nebraska			Historic / Estate	Indoor & Outdoor	300		Art museum made up of three connected buildings from the 1930s to the 21st century, with sculpture grounds and gardens used for wedding ceremonies and receptions.		(402) 342-3300	https://joslyn.org/visit/host-an-event/
Heartland Country Barn	1063 County Road U	Fremont	Nebraska			Barn / Rustic	Indoor & Outdoor	250	Simple	Timber-frame barn event centre outside Fremont with a bridal suite, groom quarters, kitchen and a fire pit.		402-275-6379	https://www.heartlandcountrybarn.com/
Junto Wine	1356 182nd	Seward	Nebraska			Restaurant / Vineyard	Indoor & Outdoor			Eight-acre vineyard and winery near Seward with wedding and event facilities separate from its tasting room, plus hiking trails on the property.	info@juntowine.com	402-303-4871	https://www.juntowine.com/juntoevents
Zenia Omaha	450 S 193rd St	Elkhorn	Nebraska			Ballroom / Hotel	Indoor & Outdoor	350		West Omaha event centre with a 6,000 sq ft ballroom, a pre-function space, a courtyard and a lawn known as the Green.	allison@zeniaomaha.com	402.312.2169	https://zeniaomaha.com/
`,
  },
];

export default batches;
