import type { VenueBatch } from "@/lib/venue-batches";

// Nevada venue batches. Every row's State is "Nevada". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Las Vegas, Reno and Tahoe venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Chapel of the Flowers	1717 Las Vegas Blvd S	Las Vegas	Nevada			Historic / Estate	Indoor & Outdoor	101		Strip chapel founded 65 years ago with ten ceremony spaces, including the Glass Gardens room and an outdoor gazebo, plus on-site reception rooms.	marryme@littlechapel.com	(702) 735-4331	https://www.littlechapel.com
Graceland Wedding Chapel	619 Las Vegas Blvd S	Las Vegas	Nevada			Historic / Estate	Indoor			Small downtown chapel dating to 1939 that began offering Elvis-themed ceremonies in 1977, with a sister chapel nearby seating 32.	weddings@gracelandchapel.com	(702) 382-0091	https://www.gracelandchapel.com
Sunset Gardens	3931 E Sunset Rd	Las Vegas	Nevada			Garden / Outdoor	Indoor & Outdoor			Four-acre garden property open since 1983 with a chapel, terrace and garden rooms, a cellar and a side yard set among twinkle-lit landscaping.	info@sunsetgardens.com	(702) 456-9986	https://www.sunsetgardens.com
Cactus Joe's Blue Diamond Nursery	12740 Blue Diamond Rd	Las Vegas	Nevada			Garden / Outdoor	Indoor & Outdoor			Seven-acre working cactus nursery at the gateway to Red Rock Canyon, with desert garden and greenhouse ceremony spots.	events@cactusjoeslv.com	702-875-1968	https://www.cactusjoeslv.com/weddings-events
A Little White Wedding Chapel	1301 S Las Vegas Blvd	Las Vegas	Nevada			Historic / Estate	Indoor & Outdoor			Chapel operating since 1951 with two indoor chapels, an outdoor gazebo and a drive-through ceremony lane.	reservations@littlewhiteweddingchapel.com	(702) 382-5943	https://www.alittlewhitechapel.com
Lakeside Weddings & Events	2620 Regatta Dr Suite 102	Las Vegas	Nevada			Garden / Outdoor	Indoor & Outdoor			Lakeside property in the Summerlin area with four outdoor garden ceremony sites, an indoor chapel, an atrium and a banquet hall.	Info@lakesideweddings.com	(702) 240-5290	https://lakesideweddings.com
The Grove	8080 Al Carrison St	Las Vegas	Nevada			Garden / Outdoor	Indoor & Outdoor			Outdoor wedding site with an almond orchard, a wooden gazebo, a garden terrace and a water feature, a short drive from the Strip.		702-645-5818	https://www.the-grove.com/wedding-venue-packaging.html
The Terrace Banquet Hall	1361 W Warm Springs Rd	Henderson	Nevada			Ballroom / Hotel	Indoor & Outdoor	380		Henderson banquet hall with a 180-guest Petite Ballroom, a 380-guest Grand Ballroom and a private garden terrace with a waterfall.		702-436-5888	https://theterracelasvegas.com
The Lake Club at SouthShore	100 Strada Di Circolo	Henderson	Nevada			Beach / Waterfront	Indoor & Outdoor			Clubhouse and golf club at Lake Las Vegas with lawn ceremony areas, a sand beach on the lake and mountain views.		(702) 856-8400	https://southshoreccllv.com/events-2/
The Neon Museum	770 Las Vegas Blvd N	Las Vegas	Nevada			Historic / Estate	Indoor & Outdoor	90		Museum of retired Las Vegas signs whose North Gallery holds ceremonies among vintage marquees and neon.		(702) 387-6366	https://www.neonmuseum.org/visit/plan-your-event/sweetheart-weddings
The Mob Museum	300 Stewart Ave	Las Vegas	Nevada			Historic / Estate	Indoor			Museum in a restored 1933 federal courthouse downtown, with ceremonies in the main building and in The Underground speakeasy.	info@themobmuseum.org	702-229-2734	https://themobmuseum.org/events/private-events/weddings/
Forge Social House	553 California Ave	Boulder City	Nevada			Historic / Estate	Indoor & Outdoor	120		Boutique event space in Boulder City with a main hall, a courtyard with bistro lighting and a balcony over the park.		+1 702 293 6743	https://forgesocialhouse.com
The Elm Estate	1401 W 2nd St	Reno	Nevada			Historic / Estate	Indoor & Outdoor	300		Historic property beside the Truckee River with the Elm House, an event centre seating 300 and guest cottages on site.	info@theelmestate.com	(775) 384-9081	https://theelmestate.com
The Chateau at Incline Village	955 Fairway Blvd	Incline Village	Nevada			Garden / Outdoor	Indoor & Outdoor	100		Timber-ceilinged lodge run by the local improvement district, with a golf course tee-box, creekside and beach ceremony spots and lake views.		(775) 832-1240	https://www.yourtahoeplace.com/weddings-venues/the-chateau-at-incline-village/
`,
  },
  {
    name: "Reno, Carson Valley, Tahoe and more Las Vegas venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Red Hawk Golf and Resort	6600 N Wingfield Pkwy	Sparks	Nevada			Restaurant / Vineyard	Indoor & Outdoor	330		Golf resort with an event centre, a lakeside deck, an outdoor lawn with water features and villa lodging beside the course.	dmiller@resortatredhawk.com	(775) 626-6000	https://www.redhawkgolfandresort.com/weddings/
Park Home Ranch	1452 Hwy 88	Minden	Nevada			Barn / Rustic	Indoor & Outdoor		Classic	Family-owned working ranch in Carson Valley with a century-old barn, open-air ceremony sites and views of the Sierra Nevada.	events@parkranch.com	(775) 782-7275	https://www.parkhomeranchvenue.com
Gansberg Ranch	1037 Waterloo Ln	Gardnerville	Nevada			Barn / Rustic	Indoor & Outdoor			Family cattle and horse ranch in Carson Valley with a newer barn, a nineteenth-century stone barn and Sierra views.	TGansberg@hotmail.com	775-220-4310	https://gansbergranch.wixsite.com/gansberg
Cottonwood Cottage	202 Genoa Ln	Genoa	Nevada			Garden / Outdoor	Indoor & Outdoor			Family-run wedding property in Nevada's oldest town, with Sierra views, bridal suites and lawn space, offered as venue-only or all-inclusive.		775-986-4922	https://www.cottonwoodgenoa.com/wedding
Genoa Golf Club	1 Genoa Lakes Dr	Genoa	Nevada			Restaurant / Vineyard	Indoor & Outdoor	200		Golf club at Genoa Lakes with banquet pavilions, smaller private rooms and views of Job's Peak and the fairways.		(775) 782-4653	https://genoagolf.com/event-venue/
The Warehouse	1428 Mission St	Gardnerville	Nevada			Historic / Estate	Indoor & Outdoor	100		Industrial-style event hall of about 1,000 square feet with polished concrete floors and exposed wood walls, plus an adjoining yard with market lights.	hello@thewarehousenv.com		https://www.thewarehousenv.com/
Jacobs Berry Farm	1335 Centerville Ln	Gardnerville	Nevada			Barn / Rustic	Indoor & Outdoor			Working berry and honey farm on an 1887 homestead, with a restored farmhouse, a century-old barn and shaded lawns.	info@jacobsberries.com	(775) 790-0855	https://jacobsberries.com/
The Corley Ranch	859 N Hwy 395	Gardnerville	Nevada			Barn / Rustic	Indoor & Outdoor	200	Classic	Working cattle and hay ranch in Carson Valley with a nineteenth-century barn that seats about 120 and a wedding package covering up to 200 guests.	info@corleyranch.com	775-790-1875	https://corleyranch.com/weddings%2C-event%2C-bus-tour
Whitney Peak Hotel	255 N Virginia St	Reno	Nevada			Ballroom / Hotel	Indoor			Downtown Reno hotel beside the Reno Arch with a 5,125 square foot ballroom, eleven event rooms and two balconies over the arch.	sales@whitneypeakhotel.com	(775) 398-5405	https://www.whitneypeakhotel.com/meet
Carson Valley Inn	1627 Hwy 395 N	Minden	Nevada			Ballroom / Hotel	Indoor & Outdoor	250		Casino hotel in Minden with about 5,000 square feet of banquet space and an outdoor corral area for larger gatherings.	info@carsonvalleyinn.com	775.782.9711	https://www.carsonvalleyinn.com/meetings
National Automobile Museum	1 S Lake St	Reno	Nevada			Historic / Estate	Indoor	157		Downtown Reno museum where receptions are held in the theatre among a collection of more than 240 classic cars.		775-333-9311	https://www.automuseum.org/venue/
White House Inn Genoa		Genoa	Nevada			Historic / Estate	Indoor			Historic inn in Genoa furnished with antiques and chandeliers, hosting weddings, micro weddings and elopements.	Whitehouseinngenoa@yahoo.com	775-870-7203	https://www.whitehouseinngenoanv.com/weddings-events
Wilbur D. May Center	1001 E 9th St	Reno	Nevada			Garden / Outdoor	Indoor & Outdoor			Washoe County park in Reno with a museum event space and several named garden spots in the arboretum for ceremonies.		775-785-5961	https://www.washoecounty.gov/parks/maycenterhome/rentals/index.php
Zephyr Cove Resort	760 Highway 50	Zephyr Cove	Nevada			Beach / Waterfront	Indoor & Outdoor	200		Lake Tahoe east shore resort with a lodge, a lakeside pavilion and wedding cruises on a paddle wheeler and a yacht.			https://www.zephyrcove.com/event/weddings
Sparks Water Bar	325 Harbour Cove Dr	Sparks	Nevada			Restaurant / Vineyard	Indoor			Two-storey waterfront restaurant at Sparks Marina with private banquet rooms facing the lake.			https://www.sparkswaterbar.com
DragonRidge Country Club	552 S Stephanie St	Henderson	Nevada			Restaurant / Vineyard	Indoor & Outdoor	250		Golf club in Henderson on more than 44,000 square feet of event space, with a ballroom, a palm-lined outdoor court and Strip views.	clivingston@dragonridgecc.com	702-835-8148	https://dragonridge.com/las-vegas-wedding-venue-dragonridge-country-club/
Always & Forever Weddings and Receptions	2620 Regatta Dr #109	Las Vegas	Nevada			Garden / Outdoor	Indoor & Outdoor	225		Lakefront venue on Lake Jacqueline in Desert Shores with five ceremony sites, a chapel and three reception spaces.		(702) 318-5683	https://lasvegaswedding4u.com/about-us/
The Resort at Summerlin	221 N Rampart Blvd	Las Vegas	Nevada			Ballroom / Hotel	Indoor & Outdoor	800		JW Marriott resort on 54 acres in Summerlin with 43 event rooms and more than 110,000 square feet of indoor and outdoor space.		702-507-5900	https://theresortatsummerlin.com/meetings-weddings-las-vegas/
Sandy Valley Ranch	1411 Kingston Rd	Sandy Valley	Nevada			Barn / Rustic	Indoor & Outdoor	200	Simple	Western ranch in the Mojave with a ceremony lawn among mesquite trees, a ranch house reception hall for 125 and horseback add-ons.			https://www.sandyvalleyranch.com/western-weddings
Rainbow Gardens	4125 W Charleston Blvd	Las Vegas	Nevada			Garden / Outdoor	Indoor & Outdoor	235		Banquet venue with a covered, climate-controlled botanical garden room, a formal room and a courtyard with a gazebo and waterfall.	info@rainbowgardenslv.com	(702) 878-4646	https://rainbowgardenslv.com/reception-rooms/
GreenGale Farms		Las Vegas	Nevada			Garden / Outdoor	Outdoor			Forty-acre family farm and animal rescue with an olive grove, palm trees, fruit orchards and open meadows, booked by appointment.	info@greengalefarms.com	+1 702-337-3052	https://greengalefarms.com/
Green Valley Ranch Resort	2300 Paseo Verde Pkwy	Henderson	Nevada			Ballroom / Hotel	Indoor & Outdoor	800		Henderson casino resort with ballrooms, a garden amphitheatre, a vineyard ceremony spot and a wedding team on site.		702.617.7788	https://greenvalleyranch.com/wedding-packages/custom-resort-wedding-packages/
`,
  },
];

export default batches;
