import type { VenueBatch } from "@/lib/venue-batches";

// New Hampshire venue batches. Every row's State is "New Hampshire". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Seacoast, lakes and mountains New Hampshire",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Bedford Village Inn	2 Olde Bedford Way	Bedford	New Hampshire			Ballroom / Hotel	Indoor & Outdoor			Inn and boutique hotel built around an original farmhouse, with the Great Hall and Grand Charolais Room for receptions and on-site restaurants for the weekend.	guestservices@bedfordvillageinn.com	603-472-2001	https://www.bedfordvillageinn.com/weddings
LaBelle Winery Amherst	345 State Route 101	Amherst	New Hampshire			Restaurant / Vineyard	Indoor & Outdoor			Winery on 11 acres with two acres of vines, ceremonies among or above the rows, in-house catering and an on-site bistro.		603-672-9898	https://www.labellewinery.com/weddings
Stonehurst Manor	3351 White Mountain Highway	North Conway	New Hampshire			Historic / Estate	Outdoor	100		Country-house inn at the gateway to the White Mountains, hosting tented garden weddings for up to 100 with mountain views and on-site rooms.	stay@stonehurstmanor.com	603-356-3113	https://www.stonehurstmanor.com/weddings
Searles Castle	23 Searles Road	Windham	New Hampshire			Historic / Estate	Indoor & Outdoor			Hilltop stone mansion with gardens and long views, hosting receptions indoors or in a draped tent on the grounds.		(603) 898-6597	https://atthecastle.com/
Saltonstall Farm		Stratham	New Hampshire			Barn / Rustic	Indoor & Outdoor	200	Classic	Third-generation working berry farm with a four-storey, roughly 200-year-old barn and an outdoor ceremony site, booked by the weekend.	sophiesaltonstall@gmail.com	(978) 801-1870	https://www.saltonstallfarm.com/saltonstallfarmbarn
The Barn at Powder Major's Farm		Madbury	New Hampshire			Barn / Rustic	Indoor & Outdoor			Restored 1804 timber-frame barn, 80 by 40 feet, on a Revolutionary-era farm with fields running down to a pond near Durham and Dover.	info@powdermajorsfarm.com	(603) 742-3160	https://www.powdermajorsfarm.com
Timber Hill Farm		Gilford	New Hampshire			Barn / Rustic	Indoor & Outdoor			Conserved hillside farm founded in 1784, with a timber-frame barn milled from its own pines and views over Lake Winnipesaukee to the Presidential Range.	events@timberhillfarm.com	603-409-5557	https://www.timberhillfarm.com/venue
The Victoria Inn	430 High Street	Hampton	New Hampshire			Garden / Outdoor	Indoor & Outdoor	150		Bed and breakfast half a mile from Hampton Beach with a covered garden pavilion, a lawn gazebo, on-site catering and rooms for about 20 guests.	events@thevictoriainn.com		https://thevictoriainn.com/garden-pavilion
Purity Spring Resort	1256 Eaton Rd	Madison	New Hampshire			Beach / Waterfront	Indoor & Outdoor	200		Family resort on Purity Lake since the 1930s, with ceremonies on a lakeside island reached by footbridge, a summit site at King Pine and an indoor hall for 200.	info@purityspring.com	603.367.8896	https://www.purityspring.com/weddings
Van Horn Estate	31 Manor Dr	Holderness	New Hampshire			Historic / Estate	Indoor & Outdoor	140		Historic estate on 10 acres above Squam Lake, with the 140-guest Mirador event space and inn rooms for a full wedding weekend.	info@manorongoldenpond.com	603-968-3348	https://www.vanhornestate.com/wedding-and-events
Ashworth by the Sea	295 Ocean Boulevard	Hampton	New Hampshire			Ballroom / Hotel	Indoor			Oceanfront hotel on Hampton Beach with four function rooms, including the Rose Room, and more than a century of hosting weddings.	frontdesk@ashworthbythesea.com	603-926-6762	https://www.ashworthhotel.com/weddings`,
  },
  {
    name: "New Hampshire: mountains, lakes and Monadnock",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Eagle Mountain House	179 Carter Notch Rd	Jackson	New Hampshire			Ballroom / Hotel	Indoor & Outdoor			White Mountains hotel with a nine-hole golf course, long veranda and renovated carriage house, holding ceremonies on a tee box facing the peaks.		603-383-9111	https://www.eaglemt.com/weddings
The Inn at Pleasant Lake	853 Pleasant St	New London	New Hampshire			Beach / Waterfront	Indoor & Outdoor	200		Lakefront country inn with roots in 1790, a private beach and views across Pleasant Lake to Mount Kearsarge in the Sunapee region.	events@innatpleasantlake.com	800-626-4907	https://www.innatpleasantlake.com/weddings
Three Chimneys Inn	17 Newmarket Rd	Durham	New Hampshire			Historic / Estate	Indoor & Outdoor	200		Seacoast inn built around a 1649 homestead and a 1795 carriage house, with 23 guest rooms, gardens, arbours and a reflection pool.		603-868-7800	https://www.threechimneysinn.com/weddings
Woodbound Inn	247 Woodbound Rd	Rindge	New Hampshire			Ballroom / Hotel	Indoor & Outdoor	200	Simple	Monadnock-region inn on Contoocook Lake with a ballroom, a playbarn, a private beach and lakeside cabins for guests.		603-532-8341	https://www.woodbound.com/weddings`,
  },
  {
    name: "New Hampshire: statewide inns, farms, wineries and estates",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Envio at AC Hotel Portsmouth		Portsmouth	New Hampshire			Ballroom / Hotel	Indoor & Outdoor	300		Waterfront ballroom and event rooms in an AC Hotel by the Piscataqua, with a terrace, rooftop bar and room for up to 300 guests.			https://www.theenvio.com/weddings
The Venue at Portwalk Place		Portsmouth	New Hampshire			Ballroom / Hotel	Indoor & Outdoor	300		Marriott-run event space in downtown Portsmouth with a terrace and over 4,600 square feet, suited to anything from small gatherings to 300 guests.			https://www.thevenueatportwalkplace.com/
Seashell Oceanfront Pavilion at Hampton Beach State Park	180 Ocean Boulevard	Hampton	New Hampshire			Beach / Waterfront	Indoor & Outdoor	100		Oceanfront pavilion in Hampton Beach State Park with a wraparound terrace, beach ceremonies and an indoor reception room for up to 100 guests.	seacoastevents@dncr.nh.gov	603-227-8717	https://www.nhstateparks.org/fees-reservations/rentals/pavilions-group-use-areas/seashell-event-spaces
Sky Meadow Country Club	6 Mountain Laurels Drive	Nashua	New Hampshire			Ballroom / Hotel	Indoor & Outdoor			Country club with a grand ballroom and an outdoor patio and bar, an in-house wedding planning team, and plated or chef-led food station service.		603-888-9000	https://www.skymeadow-weddings.com/
Kimball Jenkins Estate	266 N. Main Street	Concord	New Hampshire			Historic / Estate	Indoor & Outdoor	200		Victorian mansion and carriage house on a historic Concord estate with gardens, hosting weddings from 30 to 200 guests depending on the season.	info@kimballjenkins.com	603-225-3932	https://www.kimballjenkins.com/weddings-and-celebrations
The Derryfield Restaurant	625 Mammoth Road	Manchester	New Hampshire			Restaurant / Vineyard	Indoor & Outdoor			Restaurant on historic farmland beside Derryfield Country Club, with a ballroom and deck for weddings, plus banquet menus and catering.	info@thederryfield.com	603-623-2880	https://www.thederryfield.com/
Indian Head Resort	664 US Route 3	Lincoln	New Hampshire			Ballroom / Hotel	Indoor & Outdoor	160		A White Mountains resort beside Shadow Lake, with an arbor and gazebo for ceremonies and a lakeview hall seating between 85 and 160 guests.		1-888-343-8000	https://www.indianheadresort.com/weddings
Waterville Valley Resort		Waterville Valley	New Hampshire			Garden / Outdoor	Indoor & Outdoor	250		A ski resort in the White Mountain National Forest with a summit ceremony by chairlift, a pondside arbor and a garden tent for receptions.	info@waterville.com	1-800-993-3149	https://www.waterville.com/weddings
White Mountain Hotel & Resort		North Conway	New Hampshire			Ballroom / Hotel				A family-owned resort hotel in North Conway with mountain views, taking wedding and event enquiries through an online request form.	info@whitemountainhotel.com	800-533-6301	https://www.whitemountainhotel.com/weddings
Belknap Mill	25 Beacon Street East	Laconia	New Hampshire			Historic / Estate	Indoor & Outdoor			A historic riverside mill in Laconia, named the state's official meetinghouse, which can be hired for weddings with or without full event planning.	info@belknapmill.org	(603) 524-8813	https://www.belknapmill.org
Alyson's Orchard	57 Alyson's Lane	Walpole	New Hampshire			Barn / Rustic	Indoor & Outdoor			A working apple orchard in Walpole with a post-and-beam reception hall and open lawns, where couples can have their ceremony outdoors.		(603) 756-9800	https://alysonsorchard.com/wedding-pricing/
Four Winds Farm Events	140 Four Winds Farm Rd	Peterborough	New Hampshire			Barn / Rustic	Indoor & Outdoor		Simple	An eighteenth-century barn on over 300 acres of orchards and woodland, with a hilltop maple for ceremonies and views of Pack Monadnock.	events@fourwindsfarmevents.com	(978) 309-9808	https://fourwindsfarmevents.com
Stonewall Farm	242 Chesterfield Rd	Keene	New Hampshire			Barn / Rustic	Indoor & Outdoor			A working farm and education centre in Keene with a timber-frame Grand Room, three ceremony sites and a covered carriage house.		603-357-7278	https://stonewallfarm.org/weddings/
Whiteface Hollow	251 Hackett Hill Rd	South Tamworth	New Hampshire			Barn / Rustic	Indoor & Outdoor	240		A timber-framed barn and restored 1820s farmhouse on a vineyard estate, with lawns for ceremonies and wide views of the mountains.	Events@Whitefacehollow.com	(603) 409-7028	https://www.whitefacehollow.com
The Barn on the Pemi	341 Daniel Webster Highway	Plymouth	New Hampshire			Barn / Rustic	Indoor & Outdoor	300		A restored 1855 barn on a hilltop above the Pemigewasset, with a terrace and seasonal greenhouse and mountain views.	theBarnEvents@theCman.com	(603) 536-3515	https://thebarnonthepemi.com
The Common Man Inn Claremont		Claremont	New Hampshire			Ballroom / Hotel	Indoor & Outdoor	180		A converted textile mill beside the Sugar River, with a brick-walled ballroom, a smaller boardroom and a riverside lawn for ceremonies.	cmclevents@thecman.com	(603) 542-0647	https://thecmaninnclaremont.com
Manchester Country Club	180 South River Road	Bedford	New Hampshire			Ballroom / Hotel	Indoor & Outdoor	260		A Donald Ross golf club hosting one wedding a day, with a glass-walled great room, open terrace and covered pavilion over the fairways.	manchestercc@troongolf.com	(603) 624-4096	https://www.manchestercountryclub.com/weddings-at-manchester
Zorvino Vineyards	226 Main Street	Sandown	New Hampshire			Restaurant / Vineyard	Indoor & Outdoor			A family-run winery and bistro on 80 wooded acres, with a post-and-beam hall and patio spaces for ceremonies and receptions.		(603) 887-8463	https://zorvino.com/weddings/
603 Brewery	42 Main St	Londonderry	New Hampshire			Restaurant / Vineyard	Indoor			A craft brewery whose beer hall, brew house and barrel room can be booked for wedding buyouts, receptions and rehearsal dinners.		603-404-6123	https://www.603brewery.com/private-events
Moffatt-Ladd House & Garden	154 Market Street	Portsmouth	New Hampshire			Historic / Estate	Indoor & Outdoor	150		A Georgian house museum in Portsmouth whose historic gardens suit ceremonies, with a warehouse as the wet-weather fallback.			https://www.moffattladd.org/rentals
Canterbury Shaker Village	288 Shaker Road	Canterbury	New Hampshire			Historic / Estate	Indoor & Outdoor			A National Historic Landmark museum with original Shaker barns and buildings, and a pondside lawn for outdoor ceremonies.		603-783-9511	https://www.shakers.org
Owl's Nest Resort & Golf Club	40 Clubhouse Lane	Thornton	New Hampshire			Ballroom / Hotel	Indoor & Outdoor			A White Mountains golf resort with a hilltop Sunset Pavilion, lakeside spaces and on-site lodging for the wedding party.		(603) 726-3076	https://www.owlsnestresort.com`,
  },
  {
    name: "New Hampshire: Manchester, Derry, lakes, Monadnock and White Mountains",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Hanover Inn Dartmouth	2 East Wheelock Street	Hanover	New Hampshire			Ballroom / Hotel	Indoor		Classic	Historic hotel on the Dartmouth College Green with the Upper Valley's largest ballroom, a grand foyer and smaller rooms for rehearsal dinners		603-643-4300	https://www.hanoverinn.com/weddings
The Gardens at Uncanoonuc Mountain	452 Mountain Road	Goffstown	New Hampshire			Garden / Outdoor	Indoor & Outdoor	200		Fifteen acres of gardens planted since 1979 below Uncanoonuc Mountain, with a woodland ceremony site, a cottage and a sailcloth tent for up to 200			https://gardensatuncanoonuc.com/weddings/
The Fells	456 Route 103A	Newbury	New Hampshire			Historic / Estate				The John Hay family's former summer estate on Lake Sunapee, a conserved property whose gardens and lawns can be rented for weddings	events@thefells.org	603-763-4789	https://thefells.org/weddings
Christmas Farm Inn & Spa	3 Blitzen Way	Jackson	New Hampshire			Barn / Rustic	Indoor & Outdoor	85		Jackson inn and spa with a barn and fieldstone fireplace for receptions of up to 85, ceremony spots on the grounds and cottages for guests		603-383-4313	https://christmasfarminn.com/jackson-nh-weddings/
Colby Hill Inn	33 The Oaks	Henniker	New Hampshire			Historic / Estate		120		Farmhouse inn in Henniker with in-house catering and planning for weddings of up to 120 guests and rooms for an overnight stay		603-428-3281	https://www.colbyhillinn.com/Celebrate--Marry/Weddings.html
Gilmanton Winery	528 Meadow Pond Road	Gilmanton	New Hampshire			Restaurant / Vineyard	Indoor & Outdoor			Working winery with a farm-kitchen restaurant, a newly built ceremony pavilion, in-house catering and an on-site event coordinator	event@gwvineyard.com	603-267-9463	https://www.gilmantonwinery.com/weddings
Snowvillage Inn	136 Stewart Rd	Eaton Center	New Hampshire			Garden / Outdoor	Indoor & Outdoor	100		Ten-acre mountainside inn estate south of Conway with three guest buildings, hosting up to 50 guests indoors or 100 outdoors	info@snowvillageinn.com	603-447-2818	https://www.snowvillageinn.com/events
The Margate on Winnipesaukee	76 Lake St	Laconia	New Hampshire			Beach / Waterfront	Indoor & Outdoor	500		Lakefront resort with a lakeside pavilion and tented lawn for up to 500, a ballroom for about 300 and an optional fireworks finale		603-524-5210	https://www.themargate.com/weddings/
Currier Museum of Art	150 Ash Street	Manchester	New Hampshire			Historic / Estate	Indoor		Classic	Manchester art museum hosting ceremonies and receptions among its galleries, planned through its exclusive wedding planning partner		603-669-6144	https://www.currier.org/weddings
Cranmore Mountain Resort	239 Skimobile Road	North Conway	New Hampshire			Garden / Outdoor	Indoor & Outdoor	200		North Conway ski mountain with several lodge function spaces holding up to 200 wedding guests against the Mount Washington Valley	info@cranmore.com		https://cranmore.com/weddings-and-functions
Dell-Lea Weddings & Events	81 Pleasant Street	Chichester	New Hampshire			Barn / Rustic	Indoor & Outdoor			Renovated post-and-beam barn with heat and air conditioning, a garden ceremony site and in-house catering from a customisable menu	events@dell-lea.com	603-435-8479	https://www.dell-lea.com/weddings-at-dell-lea
Hyla Brook Estate	140 Rockingham Rd	Derry	New Hampshire			Barn / Rustic	Indoor & Outdoor	175		Derry estate whose farmhouse great room seats up to 175 with a dance floor, with a fire pit outside and parking for about 100 cars	info@hylabrookestate.com	603-434-4000	https://www.hylabrookestate.com/
Charmingfare Farm	774 High Street	Candia	New Hampshire			Garden / Outdoor	Outdoor	500		Working farm and zoo near Manchester offering outdoor rustic weddings for 100 to 500 guests, with horse-drawn rides and animals to visit	info@visitthefarm.com	603-483-5623	https://www.visitthefarm.com/farm-weddings/
Atkinson Resort & Country Club	85 Country Club Drive	Atkinson	New Hampshire			Ballroom / Hotel				Golf resort and country club near the Massachusetts line with its own dining and lodging, hosting weddings and rehearsal events	events@atkinsoncc.com	603-362-8700	https://www.atkinsonresort.com/weddings
LaBelle Winery Derry	14 Route 111	Derry	New Hampshire			Restaurant / Vineyard	Indoor & Outdoor	240		LaBelle's second winery, near the Massachusetts border, with all-inclusive wedding packages for 12 to 240 guests and an outdoor ceremony site	kaitlyn@experiencelabelle.com	603-672-9898	https://labellewinery.com/weddings-events/labelle-derry-weddings/
The Wentworth	1 Carter Notch Road	Jackson	New Hampshire			Historic / Estate	Indoor & Outdoor	200		Country inn in Jackson village with a seasonal pavilion for up to 200 guests and a dining room for off-season receptions of up to 80	cita@thewentworth.com	603-383-9700	https://thewentworth.com/celebrate/weddings/
Puritan Backroom	245 Hooksett Rd	Manchester	New Hampshire			Restaurant / Vineyard	Indoor			Long-running Manchester restaurant whose conference and function rooms host wedding receptions and rehearsal dinners with its own menus		603-666-9893	https://puritanbackroom.com/events
`,
  },
];

export default batches;
