import type { VenueBatch } from "@/lib/venue-batches";

// New York venue batches. Every row's State is "New York". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Hudson Valley",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Hasbrouck House	3805 Main Street	Stone Ridge	New York			Historic / Estate	Indoor & Outdoor	150		A mansion turned boutique hotel on 55 acres of gardens and trails, with a great lawn for tented receptions.	hello@hasbrouckhouseny.com	845-687-0736	https://www.hasbrouckhouseny.com/private-events
The Garrison	2015 US 9	Garrison	New York			Ballroom / Hotel	Indoor & Outdoor	200		A 300-acre Hudson Highlands property with golf, an eight-room inn and minimalist indoor event spaces looking across the river to the Catskills.		845-424-3604	https://thegarrison.com/weddings/
Wilderstein Historic Site	330 Morton Road	Rhinebeck	New York			Historic / Estate	Outdoor	200		A riverside historic mansion on 40 landscaped acres, with receptions on the east lawn facing the Hudson and the Esopus Lighthouse.	wilderstein@wilderstein.org	845-876-4818	https://wilderstein.org/weddings/
Millbrook Winery	26 Wing Road	Millbrook	New York			Restaurant / Vineyard	Indoor & Outdoor	120	Simple	A 130-acre Dutchess County winery with a 1940s barn loft for dinners and ceremony sites among the vines and ponds; spring weddings only.	millbrookwinery@millwine.com	845-677-8383	https://www.millbrookwine.com/weddings-site-rentals/
The Kaaterskill	424 High Falls Road Ext	Catskill	New York			Barn / Rustic	Indoor & Outdoor	150		A 40-acre Catskills estate whose wedding barn overlooks a pond, rented for the weekend with a farmhouse and pond house sleeping ten.	kaaterskillreservations@gmail.com	917-225-2635	https://www.thekaaterskill.com/weddings
Falkirk Estate	206 Smith Clove Rd	Central Valley	New York			Ballroom / Hotel	Indoor & Outdoor	300	Classic	An Orange County estate and country club with a licensed glatt kosher kitchen, running one event at a time.		845-928-8060	https://falkirkestate.com/weddings/
The Roundhouse	2 East Main Street	Beacon	New York			Historic / Estate	Indoor & Outdoor	200		A Beacon hotel and restaurant on Fishkill Creek, with receptions in a room overlooking the waterfall.	info@roundhousebeacon.com	845-765-8369	https://www.roundhousebeacon.com/weddings/
Diamond Mills Hotel	25 South Partition Street	Saugerties	New York			Ballroom / Hotel	Indoor & Outdoor	350		A Saugerties hotel above the Esopus Creek falls, with a ballroom and terrace for receptions and a riverside boathouse nearby.	events@diamondmillshotel.com	845-247-0700	https://www.diamondmillshotel.com/weddings-events
Locust Grove Historic Site	2683 South Road	Poughkeepsie	New York			Historic / Estate	Indoor & Outdoor	150		The former Samuel Morse estate on 200 acres, with receptions in the West Gallery and ceremonies on the mansion or garden lawns.	weddings@lgny.org	845-454-4500	https://www.lgny.org/rentals
Bedford Post Inn	954 Old Post Rd	Bedford	New York			Restaurant / Vineyard	Indoor & Outdoor	100		A Relais and Chateaux inn on 20 acres in northern Westchester, with a lawn ceremony, courtyard cocktails and dinner in the farmhouse.		914-234-7800	https://www.bedfordpostinn.com/weddings/
Brotherhood Winery	100 Brotherhood Plaza Dr	Washingtonville	New York			Restaurant / Vineyard	Indoor & Outdoor	220		A winery founded in 1839 whose Grand Salon is a 19th-century stone building with beamed ceilings, beside a cobblestone fountain patio and old hand-dug cellars.	Donny.Nap@brotherhood-winery.com	845-496-3661	https://brotherhood-winery.com/grand-salon
INNESS	10 Bank Street	Accord	New York			Barn / Rustic	Indoor & Outdoor	160		A 220-acre Ulster County resort with golf and a spa, whose 4,000 sq ft event barn in Dutch pegged-timber style opens onto a lawn facing the Catskills.	events@inness.co	845-377-0030	https://www.inness.co/events
Full Moon Resort	1 Valley View Road	Big Indian	New York			Barn / Rustic	Indoor & Outdoor			A 100-acre Catskills resort of meadows, forest and streams, with a wedding pavilion, a barn and on-site lodging.	info@fullmoonresort.com	845-254-5117	https://www.fmrweddings.com/
Tarrytown House Estate	49 East Sunnyside Lane	Tarrytown	New York			Historic / Estate	Indoor & Outdoor	400		A 26-acre Hudson River estate of two mansions and a carriage house, with a ballroom, a glass-walled Winter Palace and a sculpture garden for ceremonies.		914-591-8200	https://www.tarrytownhouseestate.com/weddings
Wylder Windham	19 NY-296	Windham	New York			Ballroom / Hotel	Indoor & Outdoor	300		A 20-acre Catskills resort on the Batavia Kill, dating to 1880, with a lawn ceremony site facing Windham Mountain and lodges for smaller dinners.	salesww@wylderhotels.com	518-734-4510	https://wylderhotels.com/windham/weddings/
The Chapel Restoration	45 Market Street	Cold Spring	New York			Historic / Estate	Indoor	99		A historic riverside chapel by the Cold Spring train station, lit by triple windows, used for ceremonies and small gatherings.		845-265-5537	https://chapelrestoration.org/weddings-and-private-gatherings/
Glynwood	362 Glynwood Rd	Cold Spring	New York			Garden / Outdoor	Outdoor	250		A 250-acre regenerative working farm in the Hudson Highlands, with tented receptions and three historic guest houses sleeping 44.		845-265-3338	https://www.glynwoodevents.org/
Senate Garage	4 N Front St	Kingston	New York			Historic / Estate	Indoor & Outdoor	220		A 9,000 sq ft raw open event space in Kingston, with a vintage lounge and outdoor grounds used from May to October.	Info@senategarage.com	845-802-5900	https://www.senategarage.com/weddings/
Cedar Lakes Estate	1 Team USA Way	Port Jervis	New York			Garden / Outdoor	Indoor & Outdoor			A 500-acre Orange County estate with lakes, camp-style cabins and a glass-ceilinged dining hall, booked privately for wedding weekends.		845-533-3328	https://www.cedarlakesestate.com/weddings
Lambs Hill		Beacon	New York			Garden / Outdoor	Outdoor	50		A private mountainside property on Fishkill Ridge above Beacon, booked for one microwedding or elopement at a time with views over the Hudson Highlands.		845-765-2900	https://www.lambshill.com/`,
  },
  {
    name: "Buffalo and western New York",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Becker Farms	3724 Quaker Road	Gasport	New York			Barn / Rustic	Indoor & Outdoor	250		A 375-acre Niagara County farm with vineyard, orchard and on-site brewery, two open-walled pavilions, ten cabins and an 1830s farmhouse for guests.	customerservice.beckerfarms@gmail.com	716-772-2211	https://www.beckerfarms.com/weddings
Buffalo and Erie County Botanical Gardens	2655 South Park Avenue	Buffalo	New York			Garden / Outdoor	Indoor & Outdoor	120		A 20,000-square-foot historic glass conservatory with domes nearly 70 feet high, plus a courtyard looking onto the Palm Dome.		716-827-1584	https://www.buffalogardens.com/weddings
Freedom Run Winery	5138 Lower Mountain Road	Lockport	New York			Restaurant / Vineyard	Indoor & Outdoor	300		Winery of nearly 100 acres on the Niagara Escarpment, with a barn and manor house built in 1826 from Erie Canal stone, a barrel room and an apple orchard.	yourspecialday@freedomrunwinery.com	(716) 433-4136	https://www.freedomrunwinery.com/weddings-and-events
Kin Loch Farmstead	4299 Ridge Road	Lockport	New York			Barn / Rustic	Indoor & Outdoor			A 30-acre private farm with a modern barn, a woodland ceremony area and more than 3,000 lavender plants, geared to smaller weddings.			https://www.kinlochfarmstead.com/
Buffalo History Museum	1 Museum Court	Buffalo	New York			Historic / Estate	Indoor & Outdoor	120	Simple	The building left from the 1901 Pan-American Exposition, with a two-storey atrium, a ten-column marble portico, park terraces and a Japanese garden.		(716) 873-9644	https://buffalohistory.org/rentals/
Samuel's Grande Manor	8750 Main Street	Williamsville	New York			Ballroom / Hotel	Indoor & Outdoor			Banquet manor with several chandeliered halls, formal gardens with three fountains and a fire bowl, and a gazebo for ceremonies.	info@samuelsgrandemanor.com	(716) 634-8425	https://www.samuelsgrandemanor.com/
Holiday Valley Resort	6557 Holiday Valley Road	Ellicottville	New York			Ballroom / Hotel	Indoor & Outdoor			Ski resort in the hills south of Buffalo with cathedral-ceilinged lodges, outdoor ceremony sites, a spa and on-site lodging.	weddings@holidayvalley.com	716-699-3968	https://www.holidayvalley.com/weddings/`,
  },
  {
    name: "New York City boroughs",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Flushing Town Hall	137-35 Northern Blvd	Flushing	New York			Historic / Estate	Indoor & Outdoor	190	Simple	A community arts center in a historic Queens town hall with a theater, a gallery and a tree-shaded garden that can each host a wedding.			https://www.flushingtownhall.org/venue-event-details/4/weddings
501 Union	501 Union Street	Brooklyn	New York			Ballroom / Hotel	Indoor	160		A Gowanus event space with a glass-walled atrium for ceremonies, an Art Deco-style lounge for cocktails and a skylit brick reception hall.	sales@501union.com	(347) 689-2405	https://www.501union.com/weddings
Terrace on the Park	52-11 111th Street	Flushing	New York			Ballroom / Hotel	Indoor & Outdoor	280		A Flushing Meadows banquet complex with ballrooms, garden suites and a rooftop and penthouse more than 20 stories up.	info@terraceonthepark.com	718-592-5000	https://www.terraceonthepark.com/weddings
Giando on the Water	400 Kent Avenue	Brooklyn	New York			Restaurant / Vineyard	Indoor & Outdoor			A Williamsburg restaurant and banquet hall on the East River with an outdoor patio facing the Manhattan skyline.			https://www.giandoonthewater.com/
Prospect Park Boathouse		Brooklyn	New York			Historic / Estate	Indoor	150		A 1905 Beaux Arts landmark overlooking the Lullwater in Prospect Park that doubles as the park's Audubon Center.		(718) 965-6960	https://www.prospectpark.org/visit-the-park/weddings-and-special-events/boathouse/
Prospect Park Picnic House		Brooklyn	New York			Garden / Outdoor		175		A park pavilion on the Long Meadow near the Fifth Street entrance of Prospect Park, used for dinner-and-dancing receptions.		(718) 965-6960	https://www.prospectpark.org/visit-the-park/weddings-and-special-events/picnic-house/
Alice Austen House	2 Hylan Blvd	Staten Island	New York			Historic / Estate	Outdoor			A Staten Island cottage-style house museum whose gardens look across New York Harbor and are rented for wedding ceremonies.	info@aliceausten.org		https://aliceausten.org/rentals/
Angel Orensanz Foundation	172 Norfolk Street	New York	New York			Historic / Estate	Indoor			A Gothic Revival synagogue from 1849 on the Lower East Side, now an arts and events space.	orensanz@gmail.com	212.253.0452	https://www.orensanz.org/
Merchant's House Museum	29 East Fourth Street	New York	New York			Historic / Estate	Indoor & Outdoor			An 1832 rowhouse museum in the East Village with preserved period rooms and a walled garden.	nyc1832@merchantshouse.org	212-777-1089	https://merchantshouse.org/rentals/private-parties/
The Green-House at Green-Wood	500 25th Street	Brooklyn	New York			Historic / Estate	Indoor			A restored 1895 greenhouse joined to new construction with a gallery and catering kitchen at the edge of Green-Wood Cemetery.	green-wood@purslane.com	(718) 768-7300	https://www.green-wood.com/rentals/
Weylin	175 Broadway	Brooklyn	New York			Historic / Estate	Indoor	450		A former Williamsburgh Savings Bank building from 1875 with a main rotunda, domed halls and small private rooms.	info@weylin.com	(718) 963-3639	https://weylin.com/
Queens Botanical Garden	43-50 Main Street	Flushing	New York			Garden / Outdoor				A Flushing botanical garden that rents space for wedding ceremonies, receptions and cocktail hours.		718.886.3800	https://queensbotanical.org/specialevents/
New York Botanical Garden	2900 Southern Blvd	Bronx	New York			Garden / Outdoor				A Bronx botanical garden that offers its grounds and event spaces for weddings and ceremonies.		718.817.8700	https://www.nybg.org/visit/groups/private-events/
Edison Ballroom	240 West 47th Street	New York	New York			Ballroom / Hotel	Indoor	550		A Times Square ballroom with a stage, LED video walls and a retractable roof, seating 350 on one floor or 550 across both.		212 201 7650	https://www.edisonballroom.com/weddings/
Ziegfeld Ballroom	141 West 54th Street	New York	New York			Ballroom / Hotel	Indoor			A Midtown ballroom with Art Deco interiors and a sweeping staircase, built on the site of the Ziegfeld Theatre legacy.	events@ziegfeldballroom.com	(212) 268-9400	https://www.ziegfeldballroom.com/weddings
New York Marble Cemetery	41 1/2 Second Avenue	New York	New York			Historic / Estate	Outdoor	120	Classic	A half-acre walled garden in the East Village, established in 1830 as a non-denominational cemetery and rented by the day for weddings.	info@marblecemetery.org		https://www.marblecemetery.org/garden`,
  },
  {
    name: "Long Island",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Vanderbilt Museum	180 Little Neck Rd	Centerport	New York			Historic / Estate	Indoor & Outdoor	145		Spanish Revival waterfront estate on Northport Bay with a rose garden, a celebration tent on the former golf course and a domed planetarium for evening receptions.		631-854-5579	https://www.vanderbiltmuseum.org/site-rental-2/
Bedell Cellars	36225 Main Rd	Cutchogue	New York			Restaurant / Vineyard		200		North Fork family winery that hosts vineyard weddings for up to 200 guests.	wine@bedellcellars.com	631-734-7537	https://www.bedellcellars.com/weddings
The Fox Hollow	7725 Jericho Tpke	Woodbury	New York			Ballroom / Hotel	Indoor			Banquet estate with the Somerley and other ballrooms overlooking landscaped gardens along Jericho Turnpike.	foxhollow@scottobrothers.com	516-921-1415	https://www.thefoxhollow.com
Swan Club on the Harbor	90 Glenwood Rd	Roslyn	New York			Beach / Waterfront	Indoor & Outdoor			Seven-acre waterfront property with gardens, fountains and a ceremony pavilion beside two ballrooms.	info@swanclub.com	516-621-7600	https://www.swanclub.com
Topping Rose House	1 Bridgehampton-Sag Harbor Tpke	Bridgehampton	New York			Ballroom / Hotel				Boutique hotel and restaurant in Bridgehampton that hosts weddings and private events.		631-808-2000	https://www.toppingrosehouse.com
Long Island Aquarium (Atlantis Banquets and Events)	431 E Main St	Riverhead	New York			Ballroom / Hotel	Indoor			Riverhead aquarium whose catering arm hosts weddings and proposals in event spaces on the property.		631-208-9200	https://www.longislandaquarium.com/weddings
The Pridwin Hotel and Cottages	81 Shore Rd	Shelter Island	New York			Beach / Waterfront	Indoor & Outdoor	200		Shelter Island hotel with a lawn, terrace, grove and pool looking out over Peconic Bay, the lawn holding 200 guests.		844-200-5001	https://www.caperesorts.com/pridwin/weddings
Sands Point Preserve	127 Middle Neck Rd	Sands Point	New York			Historic / Estate	Indoor & Outdoor			Gold Coast preserve whose Hempstead House and Castle Gould host weddings, with a rose garden and terrace.	hospitality@sandspointpreserve.org	516-304-5365	https://sandspointpreserveconservancy.org/privatecorporate-parties/weddings-parties
Gatsby on the Ocean	2000 Ocean Pkwy	Wantagh	New York			Beach / Waterfront	Indoor & Outdoor			Oceanfront event space inside the historic West Bath House at Jones Beach with Atlantic views.	info@gatsbyontheocean.com	516-785-0012	https://www.gatsbyontheocean.com
The Mansion at Glen Cove	200 Dosoris Ln	Glen Cove	New York			Historic / Estate		300		Gold Coast mansion with more than 25,000 square feet of event space in Glen Cove.	info@glencovemansion.com	646-518-8771	https://www.themansionatglencove.com
Larkfield	507 Larkfield Rd	East Northport	New York			Ballroom / Hotel	Indoor & Outdoor	400		Family-run East Northport venue with several ballrooms and outdoor garden spaces, its largest ballroom seating 400 with a dance floor.	info@larkfield.com	631-368-4422	https://www.larkfield.com/
Harbor Club at Prime	95 New York Ave	Huntington	New York			Beach / Waterfront	Indoor & Outdoor			Contemporary Huntington Harbor venue with floor-to-ceiling windows and an open-air balcony over the water.	harborclubprime@brgroup.biz	631-271-5600	https://www.harborclubatprime.com
Meadowlark North Fork	24385 Main Rd	Cutchogue	New York			Restaurant / Vineyard		200		Two-building Macari property in Cutchogue set up for weddings of 200 or more guests.		631-734-7070	https://macariwines.com/private-events/la-cantina/
Hallockville Museum Farm	6038 Sound Ave	Riverhead	New York			Barn / Rustic		99		Historic North Fork farm of preserved buildings whose barn hosts receptions of up to 99 guests.	asstdirector@hallockville.org	631-298-5292	https://hallockville.org/weddings-parties/
Southampton Inn	91 Hill St	Southampton	New York			Ballroom / Hotel	Indoor & Outdoor			Southampton village inn with indoor and outdoor venues for a customizable wedding weekend.		631-283-6500	https://www.southamptoninn.com
Bailey Arboretum	194 Bayville Rd	Locust Valley	New York			Garden / Outdoor				Locust Valley arboretum that offers its grounds for weddings and private events.	info@baileyarboretum.org	516-801-1458	https://www.baileyarboretum.org
Westbury Manor	1100 Jericho Tpke	Westbury	New York			Ballroom / Hotel	Indoor & Outdoor			Five landscaped acres with several ballrooms and cocktail rooms along Jericho Turnpike.		516-333-7117	https://www.westburymanor.com
Danfords Hotel and Marina	25 E Broadway	Port Jefferson	New York			Ballroom / Hotel	Indoor			Port Jefferson harbor hotel with contemporary ballrooms and water views.	info@danfords.com	631-928-5200	https://www.danfords.com`,
  },
  {
    name: "Finger Lakes",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Geneva On The Lake	1001 Lochland Road	Geneva	New York			Ballroom / Hotel		30		Lakeside Geneva resort that hosts intimate wedding celebrations of up to 30 guests.		(315) 789-7190	https://genevaonthelake.com/weddings/
The Sinclair of Skaneateles	4357 Jordan Road	Skaneateles	New York			Historic / Estate	Indoor & Outdoor	200	Classic	An 1871 chair factory restored as a wedding venue with outdoor grounds, fire pits and an on-site prep suite, hosting one wedding per day.	sinclairofskaneateles@gmail.com	(315) 730-5714	https://sinclairofskaneateles.com/weddings/
Sonnenberg Gardens & Mansion State Historic Park	250 Gibson Street	Canandaigua	New York			Historic / Estate	Indoor & Outdoor			A historic estate where couples marry among the Thompson family's gardens and hold receptions in the mansion and on its veranda.		(585) 394-4922	https://www.sonnenberg.org/weddinginfo/
The Lake House on Canandaigua	770 S Main Street	Canandaigua	New York			Beach / Waterfront	Indoor & Outdoor	200		A lakefront resort whose timber-frame Event Barn has wall-to-wall windows, a built-in bar and gardens running down to Canandaigua Lake.		(585) 394-7800	https://lakehousecanandaigua.com/meetings-events/weddings/
Genesee Country Village & Museum	1410 Flint Hill Road	Mumford	New York			Historic / Estate	Indoor & Outdoor			A 19th-century living-history village offering historic churches, gardens, log cabins and barns as ceremony and reception sites.	info@gcv.org	(585) 538-6822	https://www.gcv.org/weddings/
The Lyon Mansion	1441 East Avenue	Rochester	New York			Historic / Estate	Indoor & Outdoor		Classic	A preserved historic mansion on East Avenue with sweeping staircases and gardens, rented for weddings with a bar credit included.	Ryan.Johnson@thelyonmansion.com	(585) 993-7678	https://thelyonmansion.com/weddings
North Star Venue	743 Snyder Hill Road	Ithaca	New York			Historic / Estate	Indoor & Outdoor	50	Simple	A Victorian house with an art gallery, music room and three and a half acres of formal gardens for small weddings.	info@northstarvenue.com	(607) 323-7684	https://www.northstarvenue.com/weddings-events
Watkins Glen Harbor Hotel	16 North Franklin Street	Watkins Glen	New York			Ballroom / Hotel	Indoor & Outdoor			A lakeside hotel with a waterfront patio and a Harbor Ballroom, part of 6,000 square feet of wedding space.		(607) 535-6116	https://www.watkinsglenharborhotel.com/weddings
Barrelhouse 6 Distillery	9558 Middle Road	Hammondsport	New York			Restaurant / Vineyard	Indoor & Outdoor	200	Simple	A distillery property above Keuka Lake with a ceremony arbor, tasting room deck and a 3,200 square foot event tent.	info@barrelhouse6.com	(607) 868-3310	https://barrelhouse6.com/wedding-and-event-packages/
Dutch Harvest Farm	1487 Ridge Road	Lansing	New York			Barn / Rustic	Indoor & Outdoor			A wedding barn on more than 50 wooded acres with a covered pavilion, patio fireplace, gardens and get-ready suites.	info@dutchharvestfarm.com		https://www.dutchharvestfarm.com/
Izzo's White Barn Winery	6634 Cayuga Road	Cayuga	New York			Restaurant / Vineyard	Indoor & Outdoor	104		A boutique farm winery with a signature white barn, a small vineyard and two ponds, set just off Route 20 between Auburn and Seneca Falls.		(315) 406-7446	https://izzoswhitebarnwinery.com/
Springside Inn	6141 West Lake Road	Auburn	New York			Ballroom / Hotel	Indoor & Outdoor			An inn near Owasco Lake with five acres of lawns, a wooded grove and a Heritage Room ballroom for ceremonies and receptions.	info@springsideinn.com	315-252-7247	https://springsideinn.com/wedding-events-at-springside-inn/
Cobblestone Creek Country Club	100 Cobble Creek Road	Victor	New York			Ballroom / Hotel	Indoor & Outdoor	240		A country club with a banquet facility and ballroom for wedding receptions in the Victor area.		585.924.6464	https://www.cobblestonecreekcc.com/Weddings_Events
Woodcliff Hotel & Spa	199 Woodcliff Drive	Fairport	New York			Ballroom / Hotel	Indoor & Outdoor			A hilltop hotel and spa with a glass-walled Event Center, a ballroom with terrace and the Lookout Point ceremony lawn.		585-381-4000	https://woodcliffhotelspa.com/wedding-venue/
Seward House Museum	33 South Street	Auburn	New York			Historic / Estate	Indoor & Outdoor			An 1816 Italianate mansion and National Historic Landmark whose gardens have hosted weddings since 1955.	info@sewardhouse.org	(315) 252-1283	https://www.sewardhouse.org/visit/rentals/weddings
Sheldrake Point Winery	7448 County Road 153	Ovid	New York			Restaurant / Vineyard	Outdoor			A Cayuga Lake winery offering vineyard and garden ceremony spots and a private dock.		607-532-9401	https://sheldrakepoint.com/private-events/`,
  },
];

export default batches;
