import type { VenueBatch } from "@/lib/venue-batches";

// Ohio venue batches. Every row's State is "Ohio". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Columbus, Cleveland and Cincinnati",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Club at Corazon	7155 Corazon Dr	Dublin	Ohio			Restaurant / Vineyard	Indoor & Outdoor			Dublin club venue with a Tuscan-style clubhouse and both indoor and outdoor ceremony spaces.		614.504.5250	https://www.clubatcorazon.com/weddings
Strongwater	401 W. Town St.	Columbus	Ohio			Restaurant / Vineyard	Indoor & Outdoor			Industrial event space in a Franklinton Arts District warehouse, catered in-house by Milo's Catering.	strongwater@cateringbymilos.com	614-928-3170	https://strongwatercolumbus.com
The Kitchen	231 E. Livingston Ave	Columbus	Ohio			Restaurant / Vineyard	Indoor	140	Classic	German Village cooking venue with two neighbouring event spaces and scratch-made food from local ingredients.	info@thekitchencolumbus.com	614-225-8940	https://www.thekitchencolumbus.com/wedding-venue-columbus-ohio
The Davis-Shai House	301 Central Parkway	Heath	Ohio			Historic / Estate	Indoor & Outdoor	300	Simple	City-owned historic house with two connecting reception rooms, a veranda and landscaped front lawn for ceremonies.	admin@davisshaihouse.com	(740) 788-8942	https://www.davisshaihouse.com/weddings
Landerhaven	6111 Landerhaven Drive	Mayfield Heights	Ohio			Ballroom / Hotel	Indoor & Outdoor			Multi-room banquet centre east of Cleveland with in-house catering, bakery, decor and audio-visual teams.		(440) 449-0700	https://landerhaven.com/wedding-menus/
Stan Hywet Hall & Gardens	714 North Portage Path	Akron	Ohio			Historic / Estate	Indoor & Outdoor	175		Historic manor house and gardens in Akron with garden ceremony sites and receptions in the Manor House or Carriage House.	rentals@stanhywet.org	330-315-3210	https://www.stanhywet.org/weddings
Music Box Supper Club	1148 Main Avenue	Cleveland	Ohio			Restaurant / Vineyard	Indoor & Outdoor	250		Supper club in the Flats on the Cuyahoga riverfront with a rooftop deck for ceremonies and a private bridal suite.		216-242-1250	https://musicboxcle.com/weddings/
Glidden House	1901 Ford Drive	Cleveland	Ohio			Historic / Estate	Indoor & Outdoor	150		1910 French Gothic mansion in University Circle with 60 guest rooms, a garden gazebo and the Juniper Room for receptions.	info@gliddenhouse.com	(216) 231-8900	https://www.gliddenhouse.com/weddings
The Bell Event Centre	444 Reading Rd	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor	300		Former church with stained glass, vaulted ceilings and a cobblestone courtyard, with in-house catering and a day-of coordinator.		513.852.2787	https://belleventcentre.com/events/weddings/
Krohn Conservatory	1501 Eden Park Drive	Cincinnati	Ohio			Garden / Outdoor	Indoor	150	Simple	1933 art deco glasshouse in Eden Park with palm, fern, desert and orchid houses for ceremonies and receptions.		513.221.2610	https://www.premierparkevents.com/venues/
Gorman Heritage Farm	10052 Reading Rd.	Evendale	Ohio			Barn / Rustic	Outdoor			Working farm museum with a West Lawn ceremony site, open pavilion and marquee tents, and caterer of your choice.			https://gormanfarm.org/dream-wedding/`,
  },
  {
    name: "Columbus, Cleveland, Akron and Cincinnati: second batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Lane57 Event Venue	5481 Babbitt Rd	New Albany	Ohio			Barn / Rustic	Indoor & Outdoor	170		Family farm in New Albany with a lofted barn, slate patio, gazebo and fire pit set among lavender, dahlia and sunflower plantings, plus bridal and honeymoon suites.	lane57eventvenues@gmail.com	(614) 778-4312	https://lane57.com/wedding-venues/
Valley Dale Ballroom	1590 Sunbury Rd	Columbus	Ohio			Historic / Estate	Indoor	1000		Big Band era ballroom on the National Register of Historic Places, keeping its original wooden dance floor alongside an updated sound system, second-floor bar and bridal and groom suites.		614-441-1907	https://valleydaleballroom.com/rental-info/
The Athletic Club of Columbus	136 E Broad St	Columbus	Ohio			Ballroom / Hotel	Indoor			Private downtown club established in 1912 on East Broad Street, with ballroom and dining spaces whose staff plan ceremonies, receptions and menus in-house.	kbasar@accolumbus.com	614.545.1370	https://accolumbus.com/weddings
Alum Creek Farm	5887 Greasmar Drive	Delaware	Ohio			Barn / Rustic	Indoor & Outdoor	175	Classic	All-white 4,800 sq ft hall north of Columbus with a vintage greenhouse, barn, estate house and gravel cocktail yard, with a day-of coordinator included.			https://www.alumcreekfarm.com/
The Friesian Empire	4531 E. Walnut Street	Westerville	Ohio			Ballroom / Hotel	Indoor & Outdoor	1888	Luxury	Former Friesian horse farm on about 50 wooded acres turned events centre, with a 20,000 sq ft ballroom, a recreated Old West street and horses that can appear in ceremonies.	info@thefriesianempire.com	(614) 899-2250	https://www.thefriesianempire.com/weddings-and-events/weddings/
Retreat 21	11433 Industrial Pkwy	Marysville	Ohio			Restaurant / Vineyard	Indoor & Outdoor			All-inclusive retreat on 64 acres of meadow and woodland west of Dublin, with a working winery and cidery, a taphouse and onsite cabins for guests.	info@retreat21.com	(614) 321-1713	https://retreat21.com/all-inclusive-wedding-venue-columbus/
Columbus Zoo and Aquarium	4850 W Powell Rd	Powell	Ohio			Garden / Outdoor	Indoor & Outdoor			Zoo grounds north of Columbus where the Africa Event Center hosts indoor or outdoor ceremonies and banquets, with an animal ambassador available at cocktail hour.	columbuszooweddings@thessagroup.com	(614) 724-3679	https://www.columbuszoo.org/weddings
Quaker Station	135 S Broadway St	Akron	Ohio			Historic / Estate	Indoor	850		Industrial-character hall in downtown Akron's Quaker Square, with a 11,900 sq ft Grand Hall that divides in two, a lounge and a platform space, suited to large receptions.	hello@quakerakron.com	(330) 271-8025	https://quakerstation.com/events/weddings/
Akron Art Museum	1 South High Street	Akron	Ohio			Historic / Estate	Indoor & Outdoor			Downtown Akron art museum renting its lobby, grand staircase, skybridge and courtyard garden for ceremonies and receptions among the collection.		330.376.9186	https://akronartmuseum.org/event-rentals/
Cleveland Metroparks Zoo	3900 Wildlife Way	Cleveland	Ohio			Garden / Outdoor	Indoor & Outdoor			City zoo with several event spaces for weddings, including Stillwater Place overlooking Waterfowl Lake and the stone-fireplace Wolf Lodge, plus exhibit buildings like African Elephant Crossing.		216.635.3304	https://www.clevelandmetroparks.com/parks/visit/plan-your-event/zoo-weddings-events
Venues at 78th Street Studios	1305 W. 80th Street	Cleveland	Ohio			Historic / Estate	Indoor	300	Simple	1905 Baker Electric car factory in the Gordon Square Arts District, now an arts complex whose galleries and 6,000 sq ft smARTspace keep hardwood floors, freight elevators and industrial windows.	events@78thstreetstudios.com	(216) 744-4784	https://venuesat78thstreetstudios.com/the-venues
White Birch Barn & Vineyard	7180 West Smith Road	Medina	Ohio			Barn / Rustic	Indoor & Outdoor	200	Classic	Former dairy farm turned family vineyard with a restored 4,200 sq ft timber-framed upper barn, a courtyard and a lake pavilion, rented for a full day with a coordinator included.	samantha@whitebirchbarn.com	(330) 441-0945	https://whitebirchbarn.com/
Windows On The River	2000 Sycamore Street	Cleveland	Ohio			Beach / Waterfront	Indoor		Classic	Banquet rooms inside the FirstEnergy Powerhouse on the Flats, with high ceilings, exposed brick and windows over the Cuyahoga River, its bridges and the skyline.			https://www.windowsontheriver.com/weddings/
La Centre	25777 Detroit Rd	Westlake	Ohio			Ballroom / Hotel	Indoor	800		Family-owned banquet centre west of Cleveland with two ballrooms that combine for large receptions, in-house catering and a full on-site kosher kitchen.	events@lacentre.com	(440) 399-6496	https://www.lacentre.com/bridal-reception-hall
Vinoklet Winery	11069 Colerain Avenue	Cincinnati	Ohio			Restaurant / Vineyard	Indoor & Outdoor	150	Simple	Family winery on more than 30 acres of hills and ponds in Colerain Township, with a private reception room, an outdoor ceremony site and its own wines poured at the bar.	vinokletwinery@fuse.net	513-385-9309	https://www.vinokletwines.com/weddings
Memorial Hall OTR	1225 Elm Street	Cincinnati	Ohio			Historic / Estate	Indoor	208		Century-old hall on Washington Park in Over-the-Rhine with two ballrooms, a park-view room and the 556-seat Anderson Theater for ceremonies.		(513) 977.8838	https://www.memorialhallotr.com/event-space-rental/
Cincinnati Art Museum	953 Eden Park Drive	Cincinnati	Ohio			Historic / Estate	Indoor	150	Classic	Art museum in Eden Park whose Alice Bimel Courtyard, main lobby and Great Hall are rented together for receptions, with a smaller library room for intimate dinners.	special.events@cincyart.org	(513) 639-2347	https://cincinnatiartmuseum.org/events/plan-your-own-event/weddings/
Cincinnati Zoo & Botanical Garden	3400 Vine St	Cincinnati	Ohio			Garden / Outdoor	Indoor & Outdoor	200	Classic	Zoo and botanical garden in Avondale offering an evening Africa deck and patio, an indoor theatre and a large picnic shelter for weddings, with animal appearances available.		513-475-6167	https://cincinnatizoo.org/privateevents/
Taft Museum of Art	316 Pike St	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor	350		Downtown art museum whose landscaped garden and tented brick terrace hold seasonal receptions, with a cherry-panelled hall for smaller indoor dinners.	events@taftmuseum.org	(513) 241-0343	https://www.taftmuseum.org/host-events/
Cedar Bay Farm	2206 Drake Road	Lebanon	Ohio			Barn / Rustic	Indoor & Outdoor	126	Luxury	Restored 19th-century farm estate on 10 acres between Cincinnati and Dayton, run by its owners for small and mid-sized all-inclusive weddings with catering, music and photography bundled.	Info@cedarbayfarm.com		https://www.cedarbayfarm.com/
The Benison	100 S 3rd St	Hamilton	Ohio			Historic / Estate	Indoor	200		Early-1900s former bank in downtown Hamilton with 30-foot ceilings, carved rosettes and the original vault, offering all-inclusive wedding packages.	info@TheBenison.com	(513) 449-1003	https://www.thebenison.com/weddings`,
  },
  {
    name: "Columbus, Cleveland, Cincinnati and Dayton: third batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Bryn Du Mansion	537 Jones Rd	Granville	Ohio			Historic / Estate	Indoor & Outdoor			Circa-1905 Federal-style sandstone mansion on 52 acres in Granville with a 7,200 sq ft field house, carriage house, formal garden and a 32-acre great lawn for tents.	info@bryndu.com	740-587-7053	https://www.bryndu.com/weddings
Gervasi Vineyard	1700 55th St NE	Canton	Ohio			Restaurant / Vineyard	Indoor & Outdoor	300		Tuscan-style winery resort on 55 acres in Canton with a lakeside open-air pavilion, a villa ballroom, a glass conservatory and on-site villas for overnight guests.	info@gervasivineyard.com	330-497-1000	https://gervasivineyard.com/weddings/
Dayton Art Institute	456 Belmonte Park North	Dayton	Ohio			Historic / Estate	Indoor & Outdoor	150		Italian Renaissance-style art museum across the river from downtown Dayton, with a rotunda, a great hall, two cloisters and grand staircases for photos.		937-223-4278	https://www.daytonartinstitute.org/host-toast/weddings
Peterloon	8605 Hopewell Rd	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor	125	Luxury	1928 Georgian and Queen Anne-style country house in Indian Hill with formal grounds, a hidden garden for ceremonies and a terrace that takes a tent for larger receptions.		513-791-7600	https://peterloon.org/weddings
Mapleside Farms	294 Pearl Rd	Brunswick	Ohio			Barn / Rustic	Indoor & Outdoor	300		Family apple orchard on 146 acres south of Cleveland, with a large barn, a lodge, a copper-topped ballroom and barn, and a waterfall ceremony site overlooking the countryside.	info@mapleside.com	330-225-5577	https://mapleside.com/weddings
Benham's Grove	166 N Main St	Centerville	Ohio			Historic / Estate	Indoor & Outdoor	200		City-run 10-acre campus south of Dayton with a restored 19th-century farmhouse, barn and cottage alongside a newer event centre, rentable together or separately.	benhamsgrove@benhamsgrove.com	937-433-1913	https://www.benhamsgrove.com/BENDEV/rental-information/
Ohio Statehouse	1 Capitol Square	Columbus	Ohio			Historic / Estate	Indoor		Classic	The state capitol building in downtown Columbus, where ceremonies and receptions use the atrium and rotunda, with the State Room and Ladies Gallery included in the package.	SpecialEvents@ohiostatehouse.org	614-728-9233	https://www.ohiostatehouse.org/events/weddings
The Junto	77 Belle St	Columbus	Ohio			Ballroom / Hotel	Indoor & Outdoor	300		198-room hotel in Columbus's Scioto Peninsula with a gallery-style ballroom, rooftop terraces overlooking Dorian Green Park and a loft suite for getting ready.	hello@thejuntohotel.com	614-607-6700	https://thejuntohotel.com/weddings
Carillon Historical Park	1000 Carillon Blvd	Dayton	Ohio			Historic / Estate	Indoor & Outdoor			65-acre history park on the Great Miami River with a 1942 carillon bell tower for ceremonies, a two-storey ballroom pavilion and an 1816 homestead with a garden gazebo.	events@daytonhistory.org	937-293-2841	https://daytonhistory.org/private-event-rentals/
Rock & Roll Hall of Fame	1100 Rock & Roll Blvd	Cleveland	Ohio			Beach / Waterfront	Indoor			Music museum in a glass pyramid on Cleveland's Lake Erie shoreline, renting its exhibit floors and plaza spaces for weddings among the memorabilia.	rental@rockhall.org	216-515-1933	https://rockhall.com/private-rentals/
White Willow Meadows	10260 Ballah Rd	Orient	Ohio			Barn / Rustic	Indoor & Outdoor	350		Purpose-built barn south of Columbus with 35-foot ceilings and west-facing glass, a formal garden for ceremonies, an on-site florist and a converted dairy barn that sleeps 14.	AngelaNorman@WhiteWillowMeadows.com	513-507-0005	https://whitewillowmeadows.com/
The Fives	550 Reach Blvd	Columbus	Ohio			Ballroom / Hotel	Indoor & Outdoor	280		Modern multi-level event building on the Scioto Peninsula with a social hall and patio, a covered rooftop terrace with skyline views and an amphitheatre for ceremonies.	info@thefivescolumbus.com	614-882-7323	https://www.thefivescolumbus.com/weddings
Brookside Golf & Country Club	2770 W Dublin-Granville Rd	Columbus	Ohio			Ballroom / Hotel	Indoor & Outdoor			Private club founded in 1927 on 260 acres in north Columbus with an 18-hole tree-lined course, whose banquet rooms are open to non-members for weddings.	chris@brooksidegcc.com	614-889-2581	https://brooksidegcc.com/Wedding_Banquets
Medallion Club	5000 Club Dr	Westerville	Ohio			Ballroom / Hotel	Indoor & Outdoor	360		Golf club north of Columbus with 27 holes, lakes and fountains, a ballroom and a ceremony site on the grounds, booked with custom menus.		614-794-6999	https://www.medallionclub.com/weddings-events
The Club at Tartan Fields	8070 Tartan Fields Dr	Dublin	Ohio			Garden / Outdoor	Indoor & Outdoor	150		Private golf club in Dublin with an Arnold Palmer course, where couples marry on the lawn or terrace by the water and hold receptions in the Nantucket Ballroom.		614-792-0900	https://arcisgolf.com/clubs/the-club-at-tartan-fields/weddings
Cleveland Museum of Natural History	1 Wade Oval Dr	Cleveland	Ohio			Historic / Estate	Indoor & Outdoor			University Circle museum where receptions are held among the dinosaur skeletons in the visitor hall, with an environmental courtyard and live-animal wildlife centre for cocktails.	events@cmnh.org	216-231-4600	https://www.cmnh.org/host-an-event/weddings
Glenmoor Country Club	4191 Glenmoor Rd NW	Canton	Ohio			Ballroom / Hotel	Indoor & Outdoor	250		Canton country club with a Jack Nicklaus course, an on-site hotel and spa, and a castle-style chapel ballroom with cathedral windows and arched bridges for photos.	front.desk@glenmoorcc.com	330-966-3600	https://glenmoorcc.com/Weddings_Events/Wedding_Information
Great Lakes Science Center	601 Erieside Ave	Cleveland	Ohio			Beach / Waterfront	Indoor			Science museum on Cleveland's Lake Erie waterfront with a harbour-view room, a dome theatre and an attached 500-car garage, catered in-house.	SpecialEvents@glsc.org	216-696-4941	https://greatscience.com/visit/private-event-rentals
Fellows Riverside Gardens	123 McKinley Ave	Youngstown	Ohio			Garden / Outdoor	Indoor & Outdoor	220	Simple	Public gardens in Mill Creek Park with a pavilion and a gazebo for ceremonies and receptions in the gardens' education and visitor centre.		330-702-3000	https://www.millcreekmetroparks.org/fellows-riverside-gardens/weddings-and-occasions/
Manor House	7440 S Mason-Montgomery Rd	Mason	Ohio			Ballroom / Hotel	Indoor & Outdoor	500		All-inclusive event centre on 18 acres north of Cincinnati with two ballrooms opening onto covered porches, a glass atrium, a gazebo, a courtyard and a lodge-style carriage house.	info@manorhouseohio.com	513-459-0177	https://manorhouseohio.com/weddings/
Hueston Woods Lodge	5201 Lodge Rd	College Corner	Ohio			Beach / Waterfront	Indoor & Outdoor	200	Simple	State-park lodge on Acton Lake near Oxford with the Teepee Ballroom and Fireside Room, lakeside and woodland ceremony spots, lodge rooms and cabins for guests and an 18-hole course.		513-664-3500	https://www.huestonwoodslodge.com/weddings
21c Museum Hotel Cincinnati	609 Walnut St	Cincinnati	Ohio			Ballroom / Hotel	Indoor & Outdoor	200		Downtown art-museum hotel where couples marry among the contemporary art in a gallery space, with a rooftop overlooking the skyline and rooms upstairs for guests.		513-578-6600	https://21cmuseumhotels.com/cincinnati/meetings-events/`,
  },
  {
    name: "Cleveland, Columbus and Cincinnati-Dayton: fourth batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Barn at Wolf Creek	2361 S. Cleveland-Massillon Rd.	Copley	Ohio			Barn / Rustic				Rustic barn venue in Copley for weddings and events.	info@thebarnatwolfcreek.com	(330) 607-7460	https://www.thebarnatwolfcreek.com/
Peacock Ridge	3249 Alabama Ave NW	North Lawrence	Ohio			Barn / Rustic	Indoor & Outdoor	200		Barn venue between Akron and Canton with a barn that seats 200 and both indoor and outdoor ceremony sites.	info@peacockridge.com	330-936-1266	https://www.peacockridge.com/
The Barn of Canal Fulton	2470 Locust Street South	Canal Fulton	Ohio			Barn / Rustic		250		Family-owned 6,200 sq ft heated and air-conditioned barn and loft on 10 wooded acres.	thebarnCF@gmail.com	(330) 805-1697	https://thebarnofcanalfulton.com/
The Barn at Walnut Drive	2129 Randolph Road	Mogadore	Ohio			Barn / Rustic	Indoor & Outdoor			Mogadore barn with an outdoor chapel and an indoor event space for weddings.	thebarnatwalnutdrive@gmail.com	330-592-1536	https://thebarnatwalnutdrive.com/
Dino's at Manakiki	35501 Eddy Rd.	Willoughby	Ohio			Ballroom / Hotel	Indoor & Outdoor			Golf-course clubhouse ballroom with a covered terrace and a wooded ceremony space called the Grove that has an indoor backup.	info@dinoscatering.com	(440) 944-4664	https://www.dinosatmanakiki.com/weddings/
The Barnstone	4296 Back Orrville Rd	Wooster	Ohio			Barn / Rustic	Indoor & Outdoor	175		Renovated 125-year-old Ohio barn on 50 acres with a carriage house bar and a ceremony green space under oak trees.		330-462-3236	http://thebarnstone.com/
Willow Haven Event Center	3570 W. Smithville Western Road	Wooster	Ohio			Barn / Rustic				Wooster barn venue with a Homestead Barn and a woodland area, offering full setup and cleanup.		330-466-6484	https://willowhaveneventcenter.com/
Greystone Event Center	50 Riffel Rd.	Wooster	Ohio			Ballroom / Hotel	Indoor & Outdoor			Wooster event center with ballrooms, a grand-staircase foyer and an outdoor patio for ceremonies or cocktail hours.		330-345-8333	https://greystoneeventcenter.com/
Columbus Country Club	4831 East Broad Street	Columbus	Ohio			Ballroom / Hotel	Indoor & Outdoor	225		Golf club on the east side whose floor-to-ceiling-windowed ballroom opens onto terraces overlooking the fairways.		(614) 861-0800	https://www.columbuscc.com/weddings-events
Cheers & Lakeside Chalet	1211 Coonpath Rd NW	Lancaster	Ohio			Garden / Outdoor	Indoor & Outdoor			Two banquet halls on 70 acres north of Lancaster with garden arbors, gazebos, a woodland Chapel in the Woods and full on-site catering.		(740) 654-9036	https://www.cheerschalet.com/weddings
Little Brook Meadows	100 Edgewood Drive	Lancaster	Ohio			Barn / Rustic	Indoor			Refurbished 9,000 sq ft barn on a 50-acre ranch a mile south of downtown Lancaster, with an on-site house that sleeps 20.	contact@littlebrookmeadows.com	(740) 215-8004	https://www.littlebrookmeadows.com/
The Barn at Stratford	2690 Stratford Rd.	Delaware	Ohio			Barn / Rustic	Indoor			1840s barn on six acres of an early pioneer homestead beside the Olentangy River, run to support the Delaware County Historical Society.	manager@barnatstratford.org	844-369-2276	https://barnatstratford.org/
The Wenbeck	1940 Little Bear Loop	Lewis Center	Ohio			Ballroom / Hotel	Indoor & Outdoor			Events center on the Little Bear Golf Club grounds with an indoor ballroom, a covered pavilion, a 3,000 sq ft patio and three ponds.		(740) 953-7085	https://thewenbeck.com/
Glass Rooster Cannery	1673 South State Route 605	Sunbury	Ohio			Barn / Rustic	Indoor & Outdoor			Working farm cannery north of New Albany that hosts weddings in a restored barn beside its gardens.	info@glassroostercannery.com	614-499-2958	https://www.glassroostercannery.com/
22 Acres Farm	5455 Davis Dr.	Newark	Ohio			Barn / Rustic	Indoor & Outdoor			Family farm east of Columbus whose customizable barn is surrounded by sunflower and wildflower fields.			https://22acresfarm.com/
Combustion Private Event Space	80 W Church St, Suite 200	Pickerington	Ohio			Restaurant / Vineyard	Indoor	150		Second-floor event room above Combustion Brewery & Taproom with a private bar serving house-brewed beer.	bhufford@combustionbrewing.com	937-360-7797	https://www.combustionbrewing.com/wedding-venue-private-events
Canopy Creek Farm	600 Benner Road	Miamisburg	Ohio			Barn / Rustic	Indoor & Outdoor			Exclusive-use country wedding venue on 24 acres with a reception barn and a partially covered veranda.	Info@CanopyCreekFarm.com	937-602-5867	https://www.canopycreekfarm.com/
The Ohio Barn	8790 Dayton-Springfield Rd.	Fairborn	Ohio			Barn / Rustic	Indoor & Outdoor	180		1895 barn on more than 20 acres with a bunkhouse that has bride and groom suites and onsite lodging.	joshandheidi@theohiobarn.com	937.603.3490	https://www.theohiobarn.com/
The Palomar Cincinnati	2622 Gilbert Avenue	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor	250		1884 limestone cathedral in Walnut Hills, restored for private events, with a main hall, a landscaped garden and a two-story Annex.	info@thepalomarcincinnati.com	513.202.6230	https://www.thepalomarcincinnati.com/
Ivory Meadows	2365 Cortsville Road	Yellow Springs	Ohio			Barn / Rustic	Indoor & Outdoor	300	Classic	Family-owned venue on 83 hilltop acres with an 8,600 sq ft ivory shiplap barn, a covered cocktail patio and three outdoor ceremony options.	info@ivorymeadowsweddings.com	937-624-2137	https://ivorymeadowsweddings.com
The Monastery Event Center	1055 St. Paul Place	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor			Mt. Adams venue in a former Franciscan monastery with Gothic windows, a courtyard and exclusive use of the building and grounds.		513-888-8694	https://monasteryeventcenter.com/weddings/
Magnolia Estate	700 Benner Road	Miamisburg	Ohio			Barn / Rustic	Indoor & Outdoor	250	Classic	Two venues on one Miamisburg property, the contemporary Magnolia Barn and the mansion-style Rosewood Manor, each with getting-ready suites.	weddings@magnoliaestate.com	(937) 269-7163	https://magnoliaestate.com
The Steam Plant	617 E 3rd St	Dayton	Ohio			Historic / Estate	Indoor & Outdoor	400	Classic	Early-1900s downtown Dayton power plant turned event venue with a Grand Hall, historic bar, courtyard and dressing suites.	steamplantdayton@gmail.com	(937) 985-0617	https://steamplantdayton.com
Polen Farm	5099 Bigger Road	Kettering	Ohio			Barn / Rustic	Indoor & Outdoor	175	Simple	City-run 19th-century farmhouse and barn on 15 acres with a gazebo for ceremonies and a seasonal party tent.		937-435-5787	https://www.playkettering.org/polen-farm
The 1859	111 South 3rd Street	Loveland	Ohio			Historic / Estate	Indoor & Outdoor	90		Historic chapel venue in downtown Loveland with a 2,500 sq ft main room and a private garden patio.	info@the1859.com	(513) 426-6771	https://www.the1859.com/details
Little Miami Brewing Company Event Center	208 Mill Street	Milford	Ohio			Restaurant / Vineyard	Indoor & Outdoor	300		Industrial-elegant brewery event space in Old Milford on the Little Miami River with two rooms, garage doors and a patio with fire pits.	Events@littlemiamibrewing.com	513-680-1570	https://littlemiamibrewing.com/event-center/
Krippendorf Lodge at Cincinnati Nature Center	4949 Tealtown Road	Milford	Ohio			Historic / Estate	Indoor & Outdoor			1898-1900 lodge at Rowe Woods with a covered stone terrace, wraparound porch and a second-floor suite for the wedding party.	cnc@cincynature.org	(513) 831-1711	https://www.cincynature.org/events/plan-your-wedding
Oasis Conference Center	902 Loveland-Miamiville Road	Loveland	Ohio			Ballroom / Hotel	Indoor			Event center beside the Oasis Golf Club with three ballrooms that open into one 20,000 sq ft space or divide into seven rooms.		(513) 583-9988	https://www.oasisgolfclub.com/weddings-social
The Honey Farm	6070 Springboro Rd	Lebanon	Ohio			Barn / Rustic	Indoor & Outdoor			Farm with a pond-side gazebo, meadow ceremony site, silo bar, lighted patio and reception barn.		937-557-1033	https://www.thehoneyfarm.com`,
  },
  {
    name: "Ohio: Columbus, Akron, Cleveland, Toledo, Cincinnati and Dayton",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Old Barns at Dry Run Farms	20521 Pherson Pike	Williamsport	Ohio			Barn / Rustic	Indoor & Outdoor	280		A renovated climate-controlled barn on 70 acres of farmland south of Columbus, with on-site lodging and one wedding per weekend.	info@theoldbarnsatdryrunfarms.com	740-202-9161	https://www.theoldbarnsatdryrunfarms.com/
The Century	106 E Moler St.	Columbus	Ohio			Historic / Estate	Indoor & Outdoor	240	Simple	A 1923 building south of downtown Columbus with exposed brick, two large rooms, a cocktail lounge and two outdoor spaces.	arleigh@thecenturyevents.com	216-702-8681	https://www.thecenturyevents.com/
North 4th Corridor	580 N 4th St	Columbus	Ohio			Historic / Estate	Indoor & Outdoor			A complex of three industrial-style event spaces (Brick & Mortar, Post 4 and Revery) in the old Smith Bros. Hardware building.	info@north4thcorridor.com	380-799-7499	https://north4thcorridor.com/
The Reserve at Stone Creek	7840-A Wales Ave NW	North Canton	Ohio			Ballroom / Hotel	Indoor			A contemporary industrial-style North Canton venue with a floor-to-ceiling fireplace and a floating split staircase.		330-806-0264	https://www.reserveatstonecreek.com/
Historic Onesto Event Center	225 2nd Street NW	Canton	Ohio			Historic / Estate	Indoor	375		A historic downtown Canton building in the Arts District with a grand ballroom and a smaller room for up to 50.		330-458-3097	https://www.onestoeventcenter.com/canton-weddings/
Willowdale Lake	610 Willowdale Lake Ave NW	North Canton	Ohio			Beach / Waterfront	Indoor & Outdoor	215		A lakeside North Canton clubhouse in a colonial style, with a ballroom and a gazebo for ceremonies.	event@willowdalelake.com	330-327-4424	https://www.willowdalelake.com/
Magnolia of Wooster	4068 Oil City Road	Wooster	Ohio			Barn / Rustic	Indoor & Outdoor			A private wedding venue set among Wayne County farmland near Wooster.		330-466-6148	https://magnoliaofwooster.com/
Crown Point Ecology Center	3220 Ira Road	Akron	Ohio			Barn / Rustic	Indoor & Outdoor			A 1910 century barn on 115 acres of prairie and woodland beside Cuyahoga Valley National Park, run by an ecology centre.		330-668-8992	https://www.crownpointecology.org/
Pine View Acres	11991 Orrville Street NW	Massillon	Ohio			Barn / Rustic	Indoor & Outdoor			A rustic Massillon property of over 60 acres with an indoor stone hall for ceremonies and receptions.	info@pineviewohio.com	330-809-0707	https://pineviewohio.com/
Ninth Street Event Center	1008 9th St SW	Massillon	Ohio			Ballroom / Hotel	Indoor			A Massillon event hall for weddings and private parties, with on-site catering and bar service.	Ninthstreeteventcenter@gmail.com	330-834-0808	https://ninthstreeteventcenter.com/
Basil Place	13271 Bass Lake Rd	Chardon	Ohio			Historic / Estate	Indoor & Outdoor	250		A 50-acre farm and estate near Chardon with an event centre, a manor house, a pond and a sailcloth tent, plus overnight lodging on site.	info@basilplace.com	(440) 298-2777	https://www.basilplace.com/wedding-venue
Sapphire Creek Winery & Gardens	16965 Park Circle Drive	Chagrin Falls	Ohio			Restaurant / Vineyard	Indoor & Outdoor			A winery with landscaped gardens, an outdoor lawn and pavilion for ceremonies and an indoor room for receptions.	events@sapphire-creek.com	440-543-7777	https://sapphire-creek.com/wedding/
Lady Caroline	1153 Main Ave	Cleveland	Ohio			Beach / Waterfront	Indoor & Outdoor	200		A yacht on the Cuyahoga River that hosts weddings either as a private charter or on a regular cruise.		216-696-8888	https://www.ladycaroline.com/weddings/
Red Space	2400 Superior Ave. E.	Cleveland	Ohio			Ballroom / Hotel	Indoor			A raw warehouse event space and gallery in downtown Cleveland that works with a set of preferred planners and caterers.		216-566-5400	https://www.redspaceevents.com/event-services/
The Lantern Room	2818 Church Ave.	Cleveland	Ohio			Ballroom / Hotel	Indoor & Outdoor	120		A light-filled room with views of downtown Cleveland, a patio for ceremonies and a flat below that couples can use for getting ready.	hello@lanternroomcle.com		https://www.lanternroomcle.com/space
Dino's at Manakiki	35501 Eddy Rd.	Willoughby	Ohio			Ballroom / Hotel	Indoor & Outdoor			A golf-course clubhouse ballroom with a covered terrace and a wooded ceremony grove, catered in house.	info@dinoscatering.com	(440) 944-4664	https://www.dinosatmanakiki.com/
Orchard Hills at Patterson Farm	11414 Caves Rd.	Chesterland	Ohio			Barn / Rustic	Indoor & Outdoor			A venue behind a fruit farm in Chesterland, with rustic orchard surroundings overlooking a nature preserve.	livia.karetka@gmail.com	440-539-1201	https://www.orchardhillscenter.com/
Sun Valley	10000 Edwards Lane	Chagrin Falls	Ohio			Garden / Outdoor	Indoor & Outdoor	300		A private 25-acre wooded property that hosts one event a day, with patio ceremonies and indoor receptions.	hello@sunvalleyohio.com	330.562.6277	https://www.sunvalleyohio.com/
Forever Farms Blueberry Barn	8109 Branch Rd.	Medina	Ohio			Barn / Rustic	Indoor & Outdoor			A bright, rustic barn at a Medina winery, with a wrap-around patio and a bridal suite.		(330) 667-0266	https://foreverfarmsohio.com/barn-weddings-at-forever-farms-winery/
Arlington Acres	3191 West State Route 18	Tiffin	Ohio			Barn / Rustic	Indoor & Outdoor			A white barn on a working farm near Tiffin, with historic beams and indoor and outdoor event spaces.			https://www.arlingtonacresoh.com/
Oakwood Lane Weddings and Events	5615 N. Oakwood Lane	Curtice	Ohio			Garden / Outdoor	Outdoor			A family-run venue near Toledo that specialises in tent weddings.	OakwoodLaneWeddings@Gmail.com	419-344-2444	https://oakwoodlaneweddings.com/
Koelsch Farm Homestead	2365 County Rd. S	Metamora	Ohio			Barn / Rustic	Outdoor	300		A century-old farmhouse property on 10.5 acres with woods, barns and a pond for outdoor ceremonies and receptions.	koelschfarmhomestead@gmail.com		https://www.koelschfarmhomestead.com/
Ken Dale Farms	4172 County Road 1	Edgerton	Ohio			Barn / Rustic	Indoor & Outdoor	275		A climate-controlled barn on a 200-acre farm, with a covered veranda and a secluded setting.		419.212.4068	https://www.kendalefarms.com/
Circle P Reception Hall	5419 County Road 139	Findlay	Ohio			Barn / Rustic	Indoor & Outdoor	200	Simple	A rustic hall on seven acres with a pond and pavilion just outside Findlay.	Circlepreceptionhall@gmail.com	(419) 575-6719	https://circlepreceptionhall.com/
Stillwaters Retreat	7904 Township Rd 120	McComb	Ohio			Garden / Outdoor	Outdoor			A scenic outdoor wedding venue in the countryside near McComb.	newinquiries@stillwatersohio.com	419-408-1132	http://stillwatersohio.com/
Birchwood Meadow	10 Turtle Creek Circle	Swanton	Ohio			Barn / Rustic	Indoor & Outdoor	300		A barn venue in Swanton, now taking bookings for 2027 and 2028.	dpmills@birchwoodmeadow.com	419-704-2511	https://www.birchwoodmeadow.com
Put-in-Bay Winery	392 Bayview Dr.	Put-in-Bay	Ohio			Restaurant / Vineyard	Indoor & Outdoor			A winery on Put-in-Bay offering a gazebo, pavilion and backyard for island weddings.		419-285-3343	https://www.putinbaywinery.com/weddings-events/
Gideon Owen Wine Company	3845 E Wine Cellar Rd	Port Clinton	Ohio			Restaurant / Vineyard	Indoor & Outdoor			A winery with indoor and outdoor spaces and views of vineyards and Lake Erie.	info@gideonowenwine.com	(419) 797-4445	https://www.gideonowenwine.com
Hope's Way Gathering Venue	4177 Amelia Olive Branch Rd	Batavia	Ohio			Barn / Rustic	Indoor & Outdoor	150		A privately owned country property near Cincinnati with a barn for receptions and wooded grounds around a pond.	gayle@hopeswaygather.com		https://hopeswaygather.com/
Heathfields Farm	4211 McKeever Pike	Williamsburg	Ohio			Historic / Estate	Indoor & Outdoor			A farmhouse and barn dating from 1889 on a working farm, with a patio and a large reception tent for outdoor celebrations.	dan@heathfieldsfarm.com	(513) 373-4444	https://www.heathfieldsfarm.com/
Stonelick Meadows	4632 Ross Road	Batavia	Ohio			Barn / Rustic	Outdoor		Simple	An outdoor venue on 25 acres of meadow, woodland and horse pasture, rented without catering, tents or furniture.	stonelickmeadows@gmail.com	(239) 908-1615	https://stonelickmeadows.com/
The Farmhouse at Emmett Ridge Farm	1805 Lindale Nicholsville Road	Amelia	Ohio			Barn / Rustic	Indoor & Outdoor	150		An all-inclusive venue on a 132-acre working farm, with a farmhouse and porch, a lawn for tented receptions and farm-to-table catering.	events@thefarmhouseatemmettridgefarm.com	(513) 491-4997	http://www.thefarmhouseatemmettridgefarm.com
Hanover Reserve	1905 Millville Oxford Rd	Hamilton	Ohio			Barn / Rustic	Indoor & Outdoor	400		A family-owned venue on 45 private acres with a post-and-beam reception space, a two-acre pond and three ceremony options.	Director@hanoverreserve.com	513-910-9574	https://www.hanoverreserve.com/
Mojave East	7202 Main Street	Cincinnati	Ohio			Ballroom / Hotel	Indoor			An 11,000 square foot industrial-style event space with a desert-inspired look that can be used as found or restyled.			https://mojaveeast.com/
The Brightside Music & Event Venue	905 E. Third St	Dayton	Ohio			Ballroom / Hotel	Indoor			A mid-sized independent music venue in downtown Dayton that also hosts weddings and private events.		937-410-0450	https://www.thebrightsidedayton.com/
The Lift	114 S. June St	Dayton	Ohio			Ballroom / Hotel	Indoor			A modern conversion of an early-1900s factory in Dayton's Huffman Historic District, with plenty of natural light.		937-632-1446	https://www.theliftdayton.com/
The Grande Hall at Liberty Tower	120 West 2nd Street	Dayton	Ohio			Ballroom / Hotel	Indoor	300		An Art Deco hall in downtown Dayton with flexible layouts for seated dinners or larger cocktail receptions.	Events@TheGrandeHall.com	937.910.6994	https://www.thegrandehall.com/
Reverie Dayton	9095 Washington Church Road	Miamisburg	Ohio			Ballroom / Hotel	Indoor & Outdoor			A venue inside SouthBrook Christian Church with a chapel, an atrium, a garden courtyard and a reception hall.		937-353-7313	https://www.reveriedayton.com/
Gatherings on the Green	7500 Salem Rd	Lewisburg	Ohio			Garden / Outdoor	Indoor & Outdoor			A storybook-style venue with an on-site decor boutique that couples can borrow from, with tours by appointment only.		(937) 733-8783	https://gatheringsonthegreen.com/
Bushnell Event Center	22 N. Fountain Avenue	Springfield	Ohio			Historic / Estate	Indoor		Simple	A historic downtown Springfield building where the ceremony, cocktail hour and reception can all take place under one roof.		(937) 271-6432	https://bushnelleventcenter.com/weddings/
The Blessing Barn Venue	4405 Spence Rd	Springfield	Ohio			Barn / Rustic	Indoor & Outdoor	230		A barn on 10 acres of farmland with maintained gardens, a screened back porch and indoor or outdoor reception options.			https://www.theblessingbarnvenue.com/
Springfield House Banquet Center	4230 E National Rd	Springfield	Ohio			Ballroom / Hotel	Indoor & Outdoor	225		A ballroom set in landscaped grounds with a pond, rented at a flat rate with couples free to bring their own caterer.		(937) 926-9010	https://www.thespringfieldhouse.com/
The Estate at Sunset Farm	3669 Centerville Rd	Bellbrook	Ohio			Historic / Estate	Indoor & Outdoor	300		A Georgian-style brick mansion on a gated 162-acre equestrian estate with a grand salon, a verandah and garden lawns.	info@sunset.farm	937-800-3661	https://theestate.events/
The Shepard Place	8925 East St. Rt. 55	Casstown	Ohio			Barn / Rustic	Indoor & Outdoor			A rustic venue on 11 acres of farmland with a 3,500 square foot barn, garden ceremony spots and a lawn for receptions.	theshepardplace@gmail.com	937.215.1423	https://theshepardplace.com/
The Oaks at Kiser Lake	4359 Kiser Lake Rd	Saint Paris	Ohio			Garden / Outdoor	Indoor & Outdoor	150	Classic	A 117-acre former camp with a climate-controlled event lodge, outdoor ceremony settings and cabins for overnight guests.	oaksatkiser@yahoo.com	(937) 244-9545	https://theoaksatkiserlake.com/`,
  },
];

export default batches;
