import type { VenueBatch } from "@/lib/venue-batches";

// Ohio venue batches. Every row's State is "Ohio". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Columbus, Cleveland and Cincinnati",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Club at Corazon	7155 Corazon Dr	Dublin	Ohio			Restaurant / Vineyard	Indoor & Outdoor			Dublin club venue with a Tuscan-style clubhouse and both indoor and outdoor ceremony spaces.		614.504.5250	https://www.clubatcorazon.com/weddings
Strongwater	401 W. Town St.	Columbus	Ohio			Restaurant / Vineyard	Indoor & Outdoor			Industrial event space in a Franklinton Arts District warehouse, catered in-house by Milo's Catering.	strongwater@cateringbymilos.com	614-928-3170	https://strongwatercolumbus.com
The Kitchen	231 E. Livingston Ave	Columbus	Ohio			Restaurant / Vineyard	Indoor	140	Classic	German Village cooking venue with two neighbouring event spaces and scratch-made food from local ingredients.	info@thekitchencolumbus.com	614-225-8940	https://www.thekitchencolumbus.com/wedding-venue-columbus-ohio
The Davis-Shai House	301 Central Parkway	Heath	Ohio			Historic / Estate	Indoor & Outdoor	300	Simple	City-owned historic house with two connecting reception rooms, a veranda and landscaped front lawn for ceremonies.	admin@davisshaihouse.com	(740) 788-8942	https://www.davisshaihouse.com/weddings
Landerhaven	6111 Landerhaven Drive	Mayfield Heights	Ohio			Ballroom / Hotel	Indoor & Outdoor			Multi-room banquet centre east of Cleveland with in-house catering, bakery, decor and audio-visual teams.		(440) 449-0700	https://landerhaven.com/wedding-menus/
Stan Hywet Hall & Gardens	714 North Portage Path	Akron	Ohio			Historic / Estate	Indoor & Outdoor	175		Historic manor house and gardens in Akron with garden ceremony sites and receptions in the Manor House or Carriage House.	rentals@stanhywet.org	330-315-3210	https://www.stanhywet.org/weddings
Music Box Supper Club	1148 Main Avenue	Cleveland	Ohio			Restaurant / Vineyard	Indoor & Outdoor	250		Supper club in the Flats on the Cuyahoga riverfront with a rooftop deck for ceremonies and a private bridal suite.		216-242-1250	https://musicboxcle.com/weddings/
Glidden House	1901 Ford Drive	Cleveland	Ohio			Historic / Estate	Indoor & Outdoor	150		1910 French Gothic mansion in University Circle with 60 guest rooms, a garden gazebo and the Juniper Room for receptions.	info@gliddenhouse.com	(216) 231-8900	https://www.gliddenhouse.com/weddings
The Bell Event Centre	444 Reading Rd	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor	300		Former church with stained glass, vaulted ceilings and a cobblestone courtyard, with in-house catering and a day-of coordinator.		513.852.2787	https://belleventcentre.com/events/weddings/
Krohn Conservatory	1501 Eden Park Drive	Cincinnati	Ohio			Garden / Outdoor	Indoor	150	Simple	1933 art deco glasshouse in Eden Park with palm, fern, desert and orchid houses for ceremonies and receptions.		513.221.2610	https://www.premierparkevents.com/venues/
Gorman Heritage Farm	10052 Reading Rd.	Evendale	Ohio			Barn / Rustic	Outdoor			Working farm museum with a West Lawn ceremony site, open pavilion and marquee tents, and caterer of your choice.		513.563.6663	https://gormanfarm.org/dream-wedding/`,
  },
  {
    name: "Columbus, Cleveland, Akron and Cincinnati: second batch",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Lane57 Event Venue	5481 Babbitt Rd	New Albany	Ohio			Barn / Rustic	Indoor & Outdoor	170		Family farm in New Albany with a lofted barn, slate patio, gazebo and fire pit set among lavender, dahlia and sunflower plantings, plus bridal and honeymoon suites.	lane57eventvenues@gmail.com	(614) 778-4312	https://lane57.com/wedding-venues/
Valley Dale Ballroom	1590 Sunbury Rd	Columbus	Ohio			Historic / Estate	Indoor	1000		Big Band era ballroom on the National Register of Historic Places, keeping its original wooden dance floor alongside an updated sound system, second-floor bar and bridal and groom suites.		614-441-1907	https://valleydaleballroom.com/rental-info/
The Athletic Club of Columbus	136 E Broad St	Columbus	Ohio			Ballroom / Hotel	Indoor			Private downtown club established in 1912 on East Broad Street, with ballroom and dining spaces whose staff plan ceremonies, receptions and menus in-house.	kbasar@accolumbus.com	614.545.1370	https://accolumbus.com/weddings
Alum Creek Farm	5887 Greasmar Drive	Delaware	Ohio			Barn / Rustic	Indoor & Outdoor	175	Classic	All-white 4,800 sq ft hall north of Columbus with a vintage greenhouse, barn, estate house and gravel cocktail yard, with a day-of coordinator included.			https://www.alumcreekfarm.com/
The Friesian Empire	4531 E. Walnut Street	Westerville	Ohio			Ballroom / Hotel	Indoor & Outdoor	1888	Luxury	Former Friesian horse farm on about 50 wooded acres turned events centre, with a 20,000 sq ft ballroom, a recreated Old West street and horses that can appear in ceremonies.	info@thefriesianempire.com	(614) 899-2250	https://www.thefriesianempire.com/weddings-and-events/weddings/
Retreat 21	11433 Industrial Pkwy	Marysville	Ohio			Restaurant / Vineyard	Indoor & Outdoor			All-inclusive retreat on 64 acres of meadow and woodland west of Dublin, with a working winery and cidery, a taphouse and onsite cabins for guests.	info@retreat21.com	(614) 321-1713	https://retreat21.com/all-inclusive-wedding-venue-columbus/
Columbus Zoo and Aquarium	4850 W Powell Rd	Powell	Ohio			Garden / Outdoor	Indoor & Outdoor			Zoo grounds north of Columbus where the Africa Event Center hosts indoor or outdoor ceremonies and banquets, with an animal ambassador available at cocktail hour.	columbuszooweddings@thessagroup.com	(614) 724-3679	https://www.columbuszoo.org/weddings
Quaker Station	135 S Broadway St	Akron	Ohio			Historic / Estate	Indoor	850		Industrial-character hall in downtown Akron's Quaker Square, with a 11,900 sq ft Grand Hall that divides in two, a lounge and a platform space, suited to large receptions.	hello@quakerakron.com	(330) 271-8025	https://quakerstation.com/events/weddings/
Akron Art Museum	1 South High Street	Akron	Ohio			Historic / Estate	Indoor & Outdoor			Downtown Akron art museum renting its lobby, grand staircase, skybridge and courtyard garden for ceremonies and receptions among the collection.		330.376.9186	https://akronartmuseum.org/event-rentals/
Cleveland Metroparks Zoo	3900 Wildlife Way	Cleveland	Ohio			Garden / Outdoor	Indoor & Outdoor			City zoo with several event spaces for weddings, including Stillwater Place overlooking Waterfowl Lake and the stone-fireplace Wolf Lodge, plus exhibit buildings like African Elephant Crossing.		216.635.3304	https://www.clevelandmetroparks.com/parks/visit/plan-your-event/zoo-weddings-events
Venues at 78th Street Studios	1305 W. 80th Street	Cleveland	Ohio			Historic / Estate	Indoor	300	Simple	1905 Baker Electric car factory in the Gordon Square Arts District, now an arts complex whose galleries and 6,000 sq ft smARTspace keep hardwood floors, freight elevators and industrial windows.	events@78thstreetstudios.com	(216) 744-4784	https://venuesat78thstreetstudios.com/the-venues
White Birch Barn & Vineyard	7180 West Smith Road	Medina	Ohio			Barn / Rustic	Indoor & Outdoor	200	Classic	Former dairy farm turned family vineyard with a restored 4,200 sq ft timber-framed upper barn, a courtyard and a lake pavilion, rented for a full day with a coordinator included.	samantha@whitebirchbarn.com	(330) 441-0945	https://whitebirchbarn.com/
Windows On The River	2000 Sycamore Street	Cleveland	Ohio			Beach / Waterfront	Indoor		Classic	Banquet rooms inside the FirstEnergy Powerhouse on the Flats, with high ceilings, exposed brick and windows over the Cuyahoga River, its bridges and the skyline.			https://www.windowsontheriver.com/weddings/
La Centre	25777 Detroit Rd	Westlake	Ohio			Ballroom / Hotel	Indoor	800		Family-owned banquet centre west of Cleveland with two ballrooms that combine for large receptions, in-house catering and a full on-site kosher kitchen.	events@lacentre.com	(440) 399-6496	https://www.lacentre.com/bridal-reception-hall
Vinoklet Winery	11069 Colerain Avenue	Cincinnati	Ohio			Restaurant / Vineyard	Indoor & Outdoor	150	Simple	Family winery on more than 30 acres of hills and ponds in Colerain Township, with a private reception room, an outdoor ceremony site and its own wines poured at the bar.	vinokletwinery@fuse.net	513-385-9309	https://www.vinokletwines.com/weddings
Memorial Hall OTR	1225 Elm Street	Cincinnati	Ohio			Historic / Estate	Indoor	208		Century-old hall on Washington Park in Over-the-Rhine with two ballrooms, a park-view room and the 556-seat Anderson Theater for ceremonies.		(513) 977.8838	https://www.memorialhallotr.com/event-space-rental/
Cincinnati Art Museum	953 Eden Park Drive	Cincinnati	Ohio			Historic / Estate	Indoor	150	Classic	Art museum in Eden Park whose Alice Bimel Courtyard, main lobby and Great Hall are rented together for receptions, with a smaller library room for intimate dinners.	special.events@cincyart.org	(513) 639-2347	https://cincinnatiartmuseum.org/events/plan-your-own-event/weddings/
Cincinnati Zoo & Botanical Garden	3400 Vine St	Cincinnati	Ohio			Garden / Outdoor	Indoor & Outdoor	200	Classic	Zoo and botanical garden in Avondale offering an evening Africa deck and patio, an indoor theatre and a large picnic shelter for weddings, with animal appearances available.		513-475-6167	https://cincinnatizoo.org/privateevents/
Taft Museum of Art	316 Pike St	Cincinnati	Ohio			Historic / Estate	Indoor & Outdoor	350		Downtown art museum whose landscaped garden and tented brick terrace hold seasonal receptions, with a cherry-panelled hall for smaller indoor dinners.	events@taftmuseum.org	(513) 241-0343	https://www.taftmuseum.org/host-events/
Cedar Bay Farm	2206 Drake Road	Lebanon	Ohio			Barn / Rustic	Indoor & Outdoor	126	Luxury	Restored 19th-century farm estate on 10 acres between Cincinnati and Dayton, run by its owners for small and mid-sized all-inclusive weddings with catering, music and photography bundled.	Info@cedarbayfarm.com		https://www.cedarbayfarm.com/
The Benison	100 S 3rd St	Hamilton	Ohio			Historic / Estate	Indoor	200		Early-1900s former bank in downtown Hamilton with 30-foot ceilings, carved rosettes and the original vault, offering all-inclusive wedding packages.	info@TheBenison.com	(513) 449-1003	https://www.thebenison.com/weddings`,
  },
];

export default batches;
