import type { VenueBatch } from "@/lib/venue-batches";

// Oregon venue batches. Every row's State is "Oregon". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Portland, Willamette Valley and the Gorge",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
McMenamins Edgefield	2126 SW Halsey St	Troutdale	Oregon			Historic / Estate	Indoor & Outdoor	225		Hotel grounds east of Portland with Ruby's Spa, house-made ales and wine, and event spaces from the Administrator's House yard to Blackberry Hall and its adjoining meadow.		503-492-2777	https://www.mcmenamins.com/private-events/weddings/edgefield
McMenamins Kennedy School	5736 NE 33rd Ave	Portland	Oregon			Historic / Estate	Indoor & Outdoor	112		A 1911 elementary school turned hotel, with weddings held in the old gymnasium, its courtyard and converted classrooms.		503-288-3286	https://www.mcmenamins.com/private-events/weddings/kennedy-school
Abernethy Center	606 15th St	Oregon City	Oregon			Garden / Outdoor	Indoor & Outdoor	250		Event centre running since 2001 with two walled gardens, a historic chapel and a ballroom with full-wall windows and chandeliers, plus in-house catering.	AbernethyCenterKassandra@abernethycenter.com		https://www.abernethycenter.com/
Bridal Veil Lakes		Bridal Veil	Oregon			Beach / Waterfront	Outdoor	250	Classic	Spring-fed three-acre lake ringed by old-growth forest off the Historic Columbia River Highway, with two covered lakeside pavilions and canoes, open mid-May to mid-October.	jennifer@bridalveillakes.com	503-981-3695	https://www.bridalveillakes.com/
Chehalem Cultural Center	415 E Sheridan St	Newberg	Oregon			Historic / Estate	Indoor & Outdoor	300		Arts centre in downtown Newberg whose 5,200 sq ft Grand Ballroom has a stage, adjustable lighting and an outdoor patio, close to wine-country lodging.	rentals@chehalemculturalcenter.org	503-487-2079	https://www.chehalemculturalcenter.org/rentals
Castaway Portland	1900 NW 18th Ave	Portland	Oregon			Historic / Estate	Indoor & Outdoor			Restored 1929 warehouse in Northwest Portland's warehouse district, run by the family-owned Cast + Co venue group.	info@castandcopdx.com	503-224-4898	https://www.castawayportland.com/
Leach Botanical Garden	6704 SE 122nd Ave	Portland	Oregon			Garden / Outdoor	Indoor & Outdoor			Botanical garden in outer southeast Portland with a covered arbor and east terrace for summer weddings and a manor house used year-round for smaller gatherings.	rentals@leachgarden.org	503-208-6030	https://www.leachgarden.org/rent/private-event-rentals
Youngberg Hill	10660 SW Youngberg Hill Rd	McMinnville	Oregon			Restaurant / Vineyard	Indoor & Outdoor	350		Women-owned 50-acre hilltop estate with an organically farmed vineyard, a nine-room inn and indoor and outdoor event spaces.	info@youngberghill.com	503-472-2727	https://youngberghill.com/weddings/
The Allison Inn & Spa	2525 Allison Ln	Newberg	Oregon			Ballroom / Hotel	Indoor & Outdoor	250		Full-service wine-country hotel and spa on 35 hillside acres with four indoor event rooms opening onto terraces and gardens, and JORY restaurant on site.	reservations@theallison.com	877-294-2525	https://theallison.com/meetings-events/weddings/
Langdon Farms Golf Club	24377 NE Airport Rd	Aurora	Oregon			Barn / Rustic	Indoor & Outdoor	250		Golf club south of Portland where receptions are held in the Red Shed barn beside the 18th green, with ceremonies on its lawn or under the orchard's sycamore.	eshorter@langdonfarms.com	503-776-5203	https://www.langdonfarms.com/wedding-venues
Oakwood Gardens Estate	12101 SW River Rd	Hillsboro	Oregon			Historic / Estate	Indoor & Outdoor			A 70-acre countryside estate with a barn, a gathering hall, formal gardens under century-old oaks and an alpaca farm, with farm-to-table catering.	info@oakwoodgardensestate.com	503-941-0049	https://www.oakwoodgardensestate.com/
Scholls Valley Lodge	12840 SW River Rd	Hillsboro	Oregon			Barn / Rustic	Indoor & Outdoor			Rural lodge among vineyards and farmland that sleeps up to 67 guests, suited to small multi-day weddings with rehearsal, ceremony and the morning after on site.	info@schollsvalleylodge.com	503-628-3130	https://www.schollsvalleylodge.com/weddings-at-svl
Sentinel Hotel	614 SW 11th Ave	Portland	Oregon			Ballroom / Hotel	Indoor			Historic downtown hotel with ornate ballrooms and a carved-ceiling Renaissance Room, catered by its own Jake's Grill.	info@sentinelhotel.com	503-224-3400	https://www.sentinelhotel.com/meetings-events/weddings
Evergreen Events	490 NE Captain Michael King Smith Way	McMinnville	Oregon			Ballroom / Hotel	Indoor & Outdoor	250		Venue and caterer on a 300-acre campus beside a space museum, with a rustic lodge, a newer reception hall and an outdoor ceremony site that can be combined for large weddings.	info@evergreenevents.com	503-687-2432	https://evergreenevents.com/weddings-receptions/
Amaterra	8150 SW Swede Hill Dr	Portland	Oregon			Restaurant / Vineyard	Indoor & Outdoor	200		West Hills winery and restaurant hosting one wedding a day across a 7,000 sq ft terrace lawn, a skyline ballroom with deck and a barrel room.	events@amaterrawines.com	503-961-6057	https://amaterrawines.com/host-events/wedding/
The Aerie at Eagle Landing	10220 SE Causey Ave	Happy Valley	Oregon			Historic / Estate	Indoor & Outdoor	160		Chateau-style all-inclusive venue on Mt. Scott with a beamed grand ballroom opening onto a pergola garden, a marquee tent by the golf course and a small cave room.		503-698-8020	https://www.theaerieateaglelanding.com/weddings
Portland Spirit	110 SE Caruthers St	Portland	Oregon			Beach / Waterfront	Indoor & Outdoor			Willamette River cruise company with three yachts offering all-inclusive private wedding charters and small ceremonies for up to 30 on public cruises.		503-224-3900	https://portlandspirit.com/weddings/
Columbia Gorge Hotel & Spa	4000 Westcliff Dr	Hood River	Oregon			Historic / Estate	Indoor & Outdoor			Gorge hotel with 40 rooms and Columbia River views, whose Benson Ballroom sits beside a 208-foot waterfall.			https://www.columbiagorgehotel.com/weddings`,
  },
];

export default batches;
