import type { VenueBatch } from "@/lib/venue-batches";

// Pennsylvania venue batches. Every row's State is "Pennsylvania". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Pittsburgh and western Pennsylvania",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Pittsburgh Botanic Garden	799 Pinkerton Run Road	Pittsburgh	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	220		Sixty-five acres of display gardens and woodland with a restored 1870s barn event centre, a lotus pond and a dogwood meadow gazebo.	events@pittsburghbotanicgarden.org	412-444-4464	https://pittsburghbotanicgarden.org/weddings/
Irons Mill Farmstead Weddings	252 Greenfield Rd	New Wilmington	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Two-storey wedding barn with an outdoor ceremony site on a 150-acre family farm park in Lawrence County, booking April to December.	natalie@ironsmill.com	724-900-9169	https://www.ironsmillfarmsteadweddings.com
Heinz History Center	1212 Smallman Street	Pittsburgh	Pennsylvania			Historic / Estate	Indoor		Classic	Pennsylvania's largest history museum, in a former ice warehouse on the edge of the Strip District, with in-house coordination and exhibit access for guests.	info@heinzhistorycenter.org	(412) 454-6000	https://www.heinzhistorycenter.org/about/event-rentals/weddings/
Armstrong Farms	155 Westminster Road	Saxonburg	Pennsylvania			Barn / Rustic	Indoor & Outdoor	250	Classic	Two restored barns on a 200-year-old Butler County family estate, booked as a weekend package with overnight lodging for the wedding party.			https://www.armstrongfarms.com/
Linden Hall	432 Linden Hall Road	Dawson	Pennsylvania			Historic / Estate	Indoor & Outdoor	300		English Tudor mansion and gardens on a 785-acre Laurel Highlands estate with a golf course, a wedding tent and a 74-room lodge.		724-529-7543	https://lindenhallpa.com/weddings/
Bella Terra Vineyards	121 Sunny Lane	Hunker	Pennsylvania			Restaurant / Vineyard	Indoor & Outdoor	300		Westmoreland County winery with vineyard, a lake and old shade trees, hosting receptions in its air-conditioned main building.	info@bellaterravineyards.com	724-635-3658	https://www.bellaterravineyards.com/weddings
The Barn at Maple Falls		Rockwood	Pennsylvania			Barn / Rustic	Indoor & Outdoor	350		Two-storey barn with a tented patio on 380 acres in Somerset County, with ceremonies by a covered bridge and stone waterfall and a farmhouse for the couple.	thebarnatmaplefalls@gmail.com	(814) 233-9232	https://thebarnatmaplefalls.com/
The Woods at Eisler Farms	531 Dick Road	Butler	Pennsylvania			Garden / Outdoor	Outdoor	200		Wooded Butler County site with a 200-guest tent, fire pit and string lights, with decor, catering and a beverage package included.		(724) 355-4599	https://www.thewoodswedding.com/
The Frick Pittsburgh	7227 Reynolds St.	Pittsburgh	Pennsylvania			Historic / Estate	Indoor & Outdoor			Henry Clay Frick's Point Breeze estate with the Gilded Age Clayton house, gardens, a greenhouse, café and car and carriage museum.	events@thefrickpittsburgh.org	412-371-0600	https://www.thefrickpittsburgh.org/rentals
National Aviary	700 Arch Street	Pittsburgh	Pennsylvania			Garden / Outdoor	Indoor			North Side bird zoo where receptions take place among free-flying birds in its indoor habitats.		412-258-9463	https://www.aviary.org/plan-your-event/weddings/
The Edgewood Club	1 Pennwood Avenue	Pittsburgh	Pennsylvania			Historic / Estate	Indoor & Outdoor			Members' club founded in 1904 in Edgewood Borough, with a club living room for ceremonies, a ballroom, pool and lawns, and limited non-member dates.	info@edgewoodclub.com	412.731.3443	https://www.edgewoodclub.com/weddings-edgewood-club-pittsburgh
Penn Brewery	800 Vinial Street	Pittsburgh	Pennsylvania			Restaurant / Vineyard	Indoor & Outdoor	120		Historic North Side brewery with a German-style beer hall, a loft room with skyline views, a cobblestone biergarten and old lagering caves.			https://www.pennbrew.com/spaces
Lingrow Farm	188 Forks Church Road	Leechburg	Pennsylvania			Barn / Rustic	Indoor & Outdoor	220	Classic	Forty-acre Armstrong County farm with a waterside ceremony site, a banquet barn and on-site lodging.	info@lingrowfarm.com	412.214.7880	https://www.lingrowfarm.com/weddingdetails
Greystone Fields	4085 Sandy Hill Road	Gibsonia	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	225		All-inclusive venue on 21 acres north of Pittsburgh with gazebos, pergolas and water features, holding one event per weekend.	greystonefields@gmail.com	(412) 848-4458	https://greystonefields.com/
Kimpton Hotel Monaco Pittsburgh	620 William Penn Place	Pittsburgh	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Downtown hotel in the 1903 Beaux Arts James H. Reed building, with a rooftop biergarten and in-house wedding specialists.	sales@monaco-pittsburgh.com	(412) 471-1170	https://www.monaco-pittsburgh.com/weddings/pittsburgh-wedding-packages/
Kamin Science Center	1 Allegheny Ave	Pittsburgh	Pennsylvania			Historic / Estate	Indoor			Riverfront science museum on the North Shore (formerly Carnegie Science Center) with exhibit halls available for receptions.		412.237.3431	https://kaminsciencecenter.org/celebrate/weddings/
Cavallo Fields	5021 Pleasant Unity Road	Latrobe	Pennsylvania			Barn / Rustic	Indoor & Outdoor		Classic	Renovated horse and carriage barn and 1860s farmhouse on 10 acres surrounded by 80 acres of Westmoreland County farmland.	hello@cavallofields.com	724-424-2332	https://www.cavallofields.com/barn-weddings
The Barn at Madison	304 Madison Heights Road	Madison	Pennsylvania			Barn / Rustic	Indoor & Outdoor	150		Barn built in 1799 and converted for weddings in Westmoreland County, with grounds for the ceremony and overnight accommodation.	thebarnatmadison@gmail.com	(724) 675-6124	https://thebarnatmadison.com/
Bramblewood	55 Loffert Road	McDonald	Pennsylvania			Barn / Rustic	Indoor & Outdoor	275	Classic	Open-span barn with a 30-foot arched wooden ceiling and a lakeside ceremony site with wooden pews, in Washington County near the airport.	info@bramblewoodweddings.com	724-350-0976	https://www.bramblewoodweddings.com/
Freedom Farms	434 Overbrook Road	Valencia	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Family-owned working farm in Butler County hosting weddings for over a decade, with farm-to-fork catering on site.	events@freedomfarmspa.com	724-586-5551	https://www.freedomfarmsweddings.com/`,
  },
  {
    name: "Lancaster and south-central Pennsylvania",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Riverdale Manor	62 Pitney Road	Lancaster	Pennsylvania			Garden / Outdoor	Indoor & Outdoor			Riverfront grounds on the Conestoga River with an all-season pavilion, a ballroom, a farmhouse and a garden terrace, catered in-house by Thyme & Seasons.	info@riverdalemanor.com	717-394-5554	https://www.riverdalemanor.com/
Cameron Estate Inn	1855 Mansion Lane	Mount Joy	Pennsylvania			Historic / Estate	Indoor & Outdoor	250		Nineteenth-century manor on 15 acres with springs and old oaks, a ballroom and carriage house for receptions, and 22 guest rooms on site.	frontdesk@cameronestateinn.com	717-492-0111	https://cameronestateinn.com/weddings/weddings-at-cameron-estate/
Wyndridge Farm	885 South Pleasant Ave	Dallastown	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Century-old York County estate on 77 acres with a timber-beam barn, an outdoor chapel, a cidery and brewery, and a five-bedroom farmhouse inn.		717-244-9900	https://wyndridge.com/weddings/
Historic Hotel Bethlehem	437 Main Street	Bethlehem	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Main Street hotel in Bethlehem's colonial Moravian district with more than 19,000 square feet of event space, a terrace and rooms for guests.		855-264-2598	https://www.hotelbethlehem.com/bethlehem-wedding-venues
Hershey Gardens	170 Hotel Road	Hershey	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	120		Twenty-three acres of botanical gardens with a large rose collection, a conservatory and butterfly atrium, garden ceremony sites and a seasonal reception tent.		717-534-3492	https://www.hersheygardens.org/weddings/
The Star Barn	1 Hollinger Lane	Elizabethtown	Pennsylvania			Barn / Rustic	Indoor & Outdoor	250	Classic	Restored 1877 Gothic Revival barn on the 280-acre Stone Gables Estate, with a pond and gazebo, a sunken garden, an organic farm and rental houses for guests.	info@stonegablesestate.com	717-902-9791	https://www.stonegablesestate.com/the-star-barn
The Barn at Paradise Station	312 Paradise Lane	Ronks	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200	Classic	Nineteenth-century bank barn on nine acres among Amish farmland, with an upper-level reception hall, a bluestone patio with fire pits and steam-train views.		717-687-5000	https://www.barnatparadisestation.com/
Mount Hope Estate & Winery	2775 Lebanon Road	Manheim	Pennsylvania			Historic / Estate	Indoor & Outdoor			Two-century-old estate and winery, home of the Pennsylvania Renaissance Faire, with a restored two-level barn, a courtyard and the first floor of the mansion.	Nicole@PaRenFaire.com	717-537-8377	https://mounthope.estate/weddings-at-mount-hope/
Valley Run Farm	425 Yocumtown Road	Etters	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200		Family-run farm of 107 acres between York and Harrisburg, with a stone-floored reception barn for 200 and a biergarten-style patio beside grazing cattle.	Valleyrunfarmevents@gmail.com	717-938-6954	https://www.valleyrunfarm.com/weddings
Eden Resort & Suites	222 Eden Road	Lancaster	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	360		Lancaster resort hotel with four reception rooms including a courtyard for 360, an outdoor garden terrace for ceremonies and overnight rooms for guests.	weddings@edenresort.com	717-560-8400	https://www.edenresort.com/weddings
The Yorktowne Hotel	48 E. Market Street	York	Pennsylvania			Ballroom / Hotel	Indoor	240		Downtown York hotel open since 1925 in Renaissance Revival style, with a chandeliered ballroom, 15,000 square feet of event space and 123 guest rooms.	LNSYO-salesadm@hilton.com	717-848-1111	https://yorktowne.com/weddings/
Heritage Hills Resort	2700 Mt. Rose Avenue	York	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	350		Golf resort on the edge of York with a garden ceremony lawn above the course, a terrace room for 350, a ballroom, a spa and a farmhouse rental for wedding parties.		717-718-1502	https://heritagehillsresort.com/wedding-venue-york-pa/
The Inn at Leola Village	38 Deborah Dr	Leola	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Historic Hotels of America inn in the Lancaster countryside with an Italian restaurant, a café, a spa and guest rooms for the wedding party.			https://www.theinnatleolavillage.com/wedding-venue-near-lancaster-pa/
Landis Valley Village & Farm Museum	2451 Kissel Hill Road	Lancaster	Pennsylvania			Historic / Estate	Indoor & Outdoor	225	Simple	State-run living history village on 100 acres, renting its Yellow Barn and courtyard, a firehouse and the old Landis Valley House Hotel, with open choice of vendors.	landisvalley@gmail.com	717-569-0401	https://www.landisvalleymuseum.org/rentals/weddings
Elizabeth Farms	262 Hopeland Road	Lititz	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200		Family Christmas tree farm founded in 1758 on more than 100 preserved acres, with a renovated barn and bar opening onto a covered patio and fire pits.	amy@elizabethfarms.com	717-626-8733	https://www.elizabethfarms.com/thevenue
Elizabeth Furnace	2121 Furnace Hills Pike	Lititz	Pennsylvania			Historic / Estate	Indoor & Outdoor			Private 33-acre estate around the historic Stiegel-Coleman House, with a barn, the Coleman Gardens, a garden folly and woodland paths.	events@elizabethfurnace.com	717-723-8485	https://www.elizabethfurnace.com/
Historic Metzler Homestead	470 West Metzler Road	Ephrata	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Bed and breakfast in a 1700s farmhouse on 24 acres of Lancaster County farmland, with a renovated historic barn for receptions.	METZLERHOMESTEAD470@YAHOO.COM	717-819-7250	https://www.historicmetzlerhomestead.com/`,
  },
];

export default batches;
