import type { VenueBatch } from "@/lib/venue-batches";

// Pennsylvania venue batches. Every row's State is "Pennsylvania". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Pittsburgh and western Pennsylvania",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Pittsburgh Botanic Garden	799 Pinkerton Run Road	Pittsburgh	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	220		Sixty-five acres of display gardens and woodland with a restored 1870s barn event centre, a lotus pond and a dogwood meadow gazebo.	events@pittsburghbotanicgarden.org	412-444-4464	https://pittsburghbotanicgarden.org/weddings/
Irons Mill Farmstead Weddings	252 Greenfield Rd	New Wilmington	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Two-storey wedding barn with an outdoor ceremony site on a 150-acre family farm park in Lawrence County, booking April to December.	natalie@ironsmill.com	724-900-9169	https://www.ironsmillfarmsteadweddings.com
Heinz History Center	1212 Smallman Street	Pittsburgh	Pennsylvania			Historic / Estate	Indoor		Classic	Pennsylvania's largest history museum, in a former ice warehouse on the edge of the Strip District, with in-house coordination and exhibit access for guests.	info@heinzhistorycenter.org	(412) 454-6000	https://www.heinzhistorycenter.org/about/event-rentals/weddings/
Armstrong Farms	155 Westminster Road	Saxonburg	Pennsylvania			Barn / Rustic	Indoor & Outdoor	250	Classic	Two restored barns on a 200-year-old Butler County family estate, booked as a weekend package with overnight lodging for the wedding party.			https://www.armstrongfarms.com/
Linden Hall	432 Linden Hall Road	Dawson	Pennsylvania			Historic / Estate	Indoor & Outdoor	300		English Tudor mansion and gardens on a 785-acre Laurel Highlands estate with a golf course, a wedding tent and a 74-room lodge.		724-529-7543	https://lindenhallpa.com/weddings/
Bella Terra Vineyards	121 Sunny Lane	Hunker	Pennsylvania			Restaurant / Vineyard	Indoor & Outdoor	300		Westmoreland County winery with vineyard, a lake and old shade trees, hosting receptions in its air-conditioned main building.	info@bellaterravineyards.com	724-635-3658	https://www.bellaterravineyards.com/weddings
The Barn at Maple Falls		Rockwood	Pennsylvania			Barn / Rustic	Indoor & Outdoor	350		Two-storey barn with a tented patio on 380 acres in Somerset County, with ceremonies by a covered bridge and stone waterfall and a farmhouse for the couple.	thebarnatmaplefalls@gmail.com	(814) 233-9232	https://thebarnatmaplefalls.com/
The Woods at Eisler Farms	531 Dick Road	Butler	Pennsylvania			Garden / Outdoor	Outdoor	200		Wooded Butler County site with a 200-guest tent, fire pit and string lights, with decor, catering and a beverage package included.		(724) 355-4599	https://www.thewoodswedding.com/
The Frick Pittsburgh	7227 Reynolds St.	Pittsburgh	Pennsylvania			Historic / Estate	Indoor & Outdoor			Henry Clay Frick's Point Breeze estate with the Gilded Age Clayton house, gardens, a greenhouse, café and car and carriage museum.	events@thefrickpittsburgh.org	412-371-0600	https://www.thefrickpittsburgh.org/rentals
National Aviary	700 Arch Street	Pittsburgh	Pennsylvania			Garden / Outdoor	Indoor			North Side bird zoo where receptions take place among free-flying birds in its indoor habitats.		412-258-9463	https://www.aviary.org/plan-your-event/weddings/
The Edgewood Club	1 Pennwood Avenue	Pittsburgh	Pennsylvania			Historic / Estate	Indoor & Outdoor			Members' club founded in 1904 in Edgewood Borough, with a club living room for ceremonies, a ballroom, pool and lawns, and limited non-member dates.	info@edgewoodclub.com	412.731.3443	https://www.edgewoodclub.com/weddings-edgewood-club-pittsburgh
Penn Brewery	800 Vinial Street	Pittsburgh	Pennsylvania			Restaurant / Vineyard	Indoor & Outdoor	120		Historic North Side brewery with a German-style beer hall, a loft room with skyline views, a cobblestone biergarten and old lagering caves.			https://www.pennbrew.com/spaces
Lingrow Farm	188 Forks Church Road	Leechburg	Pennsylvania			Barn / Rustic	Indoor & Outdoor	220	Classic	Forty-acre Armstrong County farm with a waterside ceremony site, a banquet barn and on-site lodging.	info@lingrowfarm.com	412.214.7880	https://www.lingrowfarm.com/weddingdetails
Greystone Fields	4085 Sandy Hill Road	Gibsonia	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	225		All-inclusive venue on 21 acres north of Pittsburgh with gazebos, pergolas and water features, holding one event per weekend.	greystonefields@gmail.com	(412) 848-4458	https://greystonefields.com/
Kimpton Hotel Monaco Pittsburgh	620 William Penn Place	Pittsburgh	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Downtown hotel in the 1903 Beaux Arts James H. Reed building, with a rooftop biergarten and in-house wedding specialists.	sales@monaco-pittsburgh.com	(412) 471-1170	https://www.monaco-pittsburgh.com/weddings/pittsburgh-wedding-packages/
Kamin Science Center	1 Allegheny Ave	Pittsburgh	Pennsylvania			Historic / Estate	Indoor			Riverfront science museum on the North Shore (formerly Carnegie Science Center) with exhibit halls available for receptions.		412.237.3431	https://kaminsciencecenter.org/celebrate/weddings/
Cavallo Fields	5021 Pleasant Unity Road	Latrobe	Pennsylvania			Barn / Rustic	Indoor & Outdoor		Classic	Renovated horse and carriage barn and 1860s farmhouse on 10 acres surrounded by 80 acres of Westmoreland County farmland.	hello@cavallofields.com	724-424-2332	https://www.cavallofields.com/barn-weddings
The Barn at Madison	304 Madison Heights Road	Madison	Pennsylvania			Barn / Rustic	Indoor & Outdoor	150		Barn built in 1799 and converted for weddings in Westmoreland County, with grounds for the ceremony and overnight accommodation.	thebarnatmadison@gmail.com	(724) 675-6124	https://thebarnatmadison.com/
Bramblewood	55 Loffert Road	McDonald	Pennsylvania			Barn / Rustic	Indoor & Outdoor	275	Classic	Open-span barn with a 30-foot arched wooden ceiling and a lakeside ceremony site with wooden pews, in Washington County near the airport.	info@bramblewoodweddings.com	724-350-0976	https://www.bramblewoodweddings.com/
Freedom Farms	434 Overbrook Road	Valencia	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Family-owned working farm in Butler County hosting weddings for over a decade, with farm-to-fork catering on site.	events@freedomfarmspa.com	724-586-5551	https://www.freedomfarmsweddings.com/`,
  },
  {
    name: "Lancaster and south-central Pennsylvania",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Riverdale Manor	62 Pitney Road	Lancaster	Pennsylvania			Garden / Outdoor	Indoor & Outdoor			Riverfront grounds on the Conestoga River with an all-season pavilion, a ballroom, a farmhouse and a garden terrace, catered in-house by Thyme & Seasons.	info@riverdalemanor.com	717-394-5554	https://www.riverdalemanor.com/
Cameron Estate Inn	1855 Mansion Lane	Mount Joy	Pennsylvania			Historic / Estate	Indoor & Outdoor	250		Nineteenth-century manor on 15 acres with springs and old oaks, a ballroom and carriage house for receptions, and 22 guest rooms on site.	frontdesk@cameronestateinn.com	717-492-0111	https://cameronestateinn.com/weddings/weddings-at-cameron-estate/
Wyndridge Farm	885 South Pleasant Ave	Dallastown	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Century-old York County estate on 77 acres with a timber-beam barn, an outdoor chapel, a cidery and brewery, and a five-bedroom farmhouse inn.		717-244-9900	https://wyndridge.com/weddings/
Historic Hotel Bethlehem	437 Main Street	Bethlehem	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Main Street hotel in Bethlehem's colonial Moravian district with more than 19,000 square feet of event space, a terrace and rooms for guests.		855-264-2598	https://www.hotelbethlehem.com/bethlehem-wedding-venues
Hershey Gardens	170 Hotel Road	Hershey	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	120		Twenty-three acres of botanical gardens with a large rose collection, a conservatory and butterfly atrium, garden ceremony sites and a seasonal reception tent.		717-534-3492	https://www.hersheygardens.org/weddings/
The Star Barn	1 Hollinger Lane	Elizabethtown	Pennsylvania			Barn / Rustic	Indoor & Outdoor	250	Classic	Restored 1877 Gothic Revival barn on the 280-acre Stone Gables Estate, with a pond and gazebo, a sunken garden, an organic farm and rental houses for guests.	info@stonegablesestate.com	717-902-9791	https://www.stonegablesestate.com/the-star-barn
The Barn at Paradise Station	312 Paradise Lane	Ronks	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200	Classic	Nineteenth-century bank barn on nine acres among Amish farmland, with an upper-level reception hall, a bluestone patio with fire pits and steam-train views.		717-687-5000	https://www.barnatparadisestation.com/
Mount Hope Estate & Winery	2775 Lebanon Road	Manheim	Pennsylvania			Historic / Estate	Indoor & Outdoor			Two-century-old estate and winery, home of the Pennsylvania Renaissance Faire, with a restored two-level barn, a courtyard and the first floor of the mansion.	Nicole@PaRenFaire.com	717-537-8377	https://mounthope.estate/weddings-at-mount-hope/
Valley Run Farm	425 Yocumtown Road	Etters	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200		Family-run farm of 107 acres between York and Harrisburg, with a stone-floored reception barn for 200 and a biergarten-style patio beside grazing cattle.	Valleyrunfarmevents@gmail.com	717-938-6954	https://www.valleyrunfarm.com/weddings
Eden Resort & Suites	222 Eden Road	Lancaster	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	360		Lancaster resort hotel with four reception rooms including a courtyard for 360, an outdoor garden terrace for ceremonies and overnight rooms for guests.	weddings@edenresort.com	717-560-8400	https://www.edenresort.com/weddings
The Yorktowne Hotel	48 E. Market Street	York	Pennsylvania			Ballroom / Hotel	Indoor	240		Downtown York hotel open since 1925 in Renaissance Revival style, with a chandeliered ballroom, 15,000 square feet of event space and 123 guest rooms.	LNSYO-salesadm@hilton.com	717-848-1111	https://yorktowne.com/weddings/
Heritage Hills Resort	2700 Mt. Rose Avenue	York	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	350		Golf resort on the edge of York with a garden ceremony lawn above the course, a terrace room for 350, a ballroom, a spa and a farmhouse rental for wedding parties.		717-718-1502	https://heritagehillsresort.com/wedding-venue-york-pa/
The Inn at Leola Village	38 Deborah Dr	Leola	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Historic Hotels of America inn in the Lancaster countryside with an Italian restaurant, a café, a spa and guest rooms for the wedding party.			https://www.theinnatleolavillage.com/wedding-venue-near-lancaster-pa/
Landis Valley Village & Farm Museum	2451 Kissel Hill Road	Lancaster	Pennsylvania			Historic / Estate	Indoor & Outdoor	225	Simple	State-run living history village on 100 acres, renting its Yellow Barn and courtyard, a firehouse and the old Landis Valley House Hotel, with open choice of vendors.	landisvalley@gmail.com	717-569-0401	https://www.landisvalleymuseum.org/rentals/weddings
Elizabeth Farms	262 Hopeland Road	Lititz	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200		Family Christmas tree farm founded in 1758 on more than 100 preserved acres, with a renovated barn and bar opening onto a covered patio and fire pits.	amy@elizabethfarms.com	717-626-8733	https://www.elizabethfarms.com/thevenue
Elizabeth Furnace	2121 Furnace Hills Pike	Lititz	Pennsylvania			Historic / Estate	Indoor & Outdoor			Private 33-acre estate around the historic Stiegel-Coleman House, with a barn, the Coleman Gardens, a garden folly and woodland paths.	events@elizabethfurnace.com	717-723-8485	https://www.elizabethfurnace.com/
Historic Metzler Homestead	470 West Metzler Road	Ephrata	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Bed and breakfast in a 1700s farmhouse on 24 acres of Lancaster County farmland, with a renovated historic barn for receptions.	METZLERHOMESTEAD470@YAHOO.COM	717-819-7250	https://www.historicmetzlerhomestead.com/`,
  },
  {
    name: "Philadelphia suburbs, Lehigh Valley and the Poconos",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Brandywine Manor House	120 Germany Hollow Road	Honey Brook	Pennsylvania			Historic / Estate	Indoor & Outdoor			A circa-1740 Chester County property on 105 acres with four outdoor ceremony sites, two indoor ceremony spaces and a barn and tent for receptions.			https://www.brandywinemanorhouse.com
HollyHedge Estate	6987 Upper York Rd.	New Hope	Pennsylvania			Historic / Estate	Indoor & Outdoor			A family-owned 18th-century farm estate in Bucks County with an inn and several buildings on the grounds for weddings and retreats.	events@hollyhedge.com	215-862-3136	https://hollyhedge.com
Downingtown Country Club	93 Country Club Drive	Downingtown	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	300		A Chester County country club with a ballroom and outdoor backdrops for ceremonies and receptions.		610-873-0800	http://www.golfdowningtown.com
Stone Ridge Farm Inn	956 Bypass Road	Perkasie	Pennsylvania			Barn / Rustic	Indoor & Outdoor	25		A renovated two-hundred-year-old barn on ten acres with nine guest bedrooms, rented for exclusive use of the grounds.	lori@stoneridgefarminn.com	215-850-9457	https://www.stoneridgefarminn.com
Pearl S. Buck International	520 Dublin Road	Perkasie	Pennsylvania			Historic / Estate	Indoor & Outdoor			A 67-acre estate with a stone farmhouse, gardens, a cultural center and an estate pavilion available for weddings.	info@pearlsbuck.org	215-249-0100	https://www.pearlsbuck.org
Ash Mill Farm	5358 York Road	Doylestown	Pennsylvania			Barn / Rustic	Indoor & Outdoor	250		A ten-acre working sheep farm with a rustic barn, meadows and an outdoor fireplace, hosting weddings with exclusive weekend use.		215-794-5373	https://www.ashmillfarm.com
The Barn at Stoneybrooke	4740 Lower Valley Road	Atglen	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200		A climate-controlled English Quaker barn with a bridal suite, loft and a handcrafted pergola for outdoor ceremonies.	info@thebarnatstoneybrooke.com		https://www.thebarnatstoneybrooke.com
The Sayre Mansion	250 Wyandotte St.	Bethlehem	Pennsylvania			Historic / Estate	Indoor			An 1858 Lehigh Valley mansion operating as a boutique inn with a rooftop conservatory and event spaces.		610-882-2100	https://sayremansion.com
Glasbern Inn	2141 Packhouse Rd	Fogelsville	Pennsylvania			Historic / Estate	Indoor & Outdoor			A historic hotel in the Lehigh Valley with guest rooms, trails and event spaces used for weddings.			https://www.glasbern.com
Cairnwood Estate	1005 Cathedral Road	Bryn Athyn	Pennsylvania			Historic / Estate	Indoor & Outdoor	250		A Beaux Arts estate designed by Carrère and Hastings, with six historic first-floor rooms, a fountain garden, covered veranda and terrace for receptions.	info@cairnwood.org	(215) 947-2004	https://cairnwood.org/host-an-event/receptions-special-occassions/
The Willows	490 Darby Paoli Rd	Villanova	Pennsylvania			Historic / Estate	Indoor & Outdoor	150		A Spanish Revival mansion set in Willows Park Preserve, with indoor rooms, patios and courtyards plus a hillside tent for dining.	willows@peachtreecatering.com	484.580.8260	https://www.willowsvillanova.com/about
The Manor House at Prophecy Creek Park	205 W Skippack Pike	Ambler	Pennsylvania			Historic / Estate	Indoor & Outdoor			An 82-acre park estate with a manor house, historic barn, ponds and a heated, air-conditioned ballroom tent.	sales@manorhouseprophecycreek.com	(215) 587-4000	https://www.manorhouseprophecycreek.com
Appleford Estate	770 Mt. Moro Road	Villanova	Pennsylvania			Historic / Estate	Indoor & Outdoor			A historic stone home on the Main Line with garden spaces and a tented terrace for celebrations.	info@applefordestate.com	610.527.4280	https://applefordestate.com
Grey Towers Castle	450 S. Easton Road	Glenside	Pennsylvania			Historic / Estate	Indoor & Outdoor			A National Historic Landmark castle on a university campus, with a great hall, mirror room and rose room plus a wraparound porch for ceremonies and cocktails.		(215) 517-2579	https://www.arcadia.edu/about-arcadia/offices-facilities-services/events-space-relations/grey-towers-castle-wedding/
Parque at Ridley Creek		Newtown Square	Pennsylvania			Historic / Estate	Indoor & Outdoor	150		A stone mansion ballroom inside Ridley Creek State Park, with outdoor ceremony areas and patios for cocktails.	parque@peachtreecatering.com	484.580.8260	https://www.parqueridleycreek.com/about
Glen Foerd	5001 Grant Ave	Philadelphia	Pennsylvania			Historic / Estate	Indoor & Outdoor			A riverfront Gilded Age mansion with formal gardens and river views, booked with an exclusive caterer.	info@cescaphe.com	215-632-5330	https://www.glenfoerd.org/plan-an-event
Crescent Boat Club	5 Kelly Drive	Philadelphia	Pennsylvania			Beach / Waterfront	Indoor & Outdoor	140		A rowing club on Boathouse Row with an air-conditioned club room that opens onto a deck over the Schuylkill River.			https://crescentboatclub.org/
The Green Ridge Club	1645 Wyoming Avenue	Scranton	Pennsylvania			Ballroom / Hotel	Indoor	175	Simple	A renovated historic Scranton building with a Grand Ballroom and a bridal suite, offering all-inclusive wedding packages with an event director.	events@thegreenridgeclub.com	570-616-3137	https://www.thegreenridgeclub.com
The Venue at Carley Brook	448 Carley Brook Rd	Honesdale	Pennsylvania			Barn / Rustic	Indoor & Outdoor	185	Classic	A 185-acre estate near Honesdale with a renovated barn, a tall glass atrium and an open-air chapel overlooking the valley.		(512) 210-9831	https://carleybrook.com
Grange Valley Lakeside Inn & Winery	432 Grange Rd	Mount Pocono	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200	Simple	A lakeside country inn and farm estate with a restored Heritage Barn, a Galleria reception space, an estate winery and on-site lodging.	GuestServices@GrangeValley.com	(570) 839-1680	https://grangevalley.com
Tall Timber Barn	5160 Rt 447	Canadensis	Pennsylvania			Barn / Rustic	Indoor & Outdoor	115		A wooded barn venue for micro weddings and celebrations of up to 115, with catering and design help included.	Coordinator@talltimberbarn.com		https://www.talltimberbarn.com
Trout Lake Retreats	1100 Twin Lake Road	Stroudsburg	Pennsylvania			Beach / Waterfront	Indoor & Outdoor	250		A private 500-acre estate on a 100-acre lake that hosts one wedding per day, with a lakeside ceremony and a Lake View Center reception space.		(570) 620-0238	https://troutlakeretreats.com
Magnolia Streamside Resort	2518 Route 390	Canadensis	Pennsylvania			Garden / Outdoor	Indoor & Outdoor	150		A cottage resort on Goose Pond Run with a streamside courtyard for outdoor weddings and a main lodge for smaller indoor gatherings.	celebrate@magnoliastreamside.com	(570) 595-2489	https://www.magnoliastreamside.com
Wallenpaupack Creek Farm	674 S Sterling Road	South Sterling	Pennsylvania			Barn / Rustic	Indoor & Outdoor			A renovated 175-year-old barn with a balcony overlooking 40 acres of pasture, with a free online planning portal for couples.	kelly@wallycreekfarm.com	(570) 230-4025	https://www.wallenpaupackcreekfarm.com
Hawley Silk Mill (The Boiler Room)	8 Silk Mill Drive	Hawley	Pennsylvania			Historic / Estate	Indoor & Outdoor			A former silk mill whose industrial Boiler Room looks out on Paupack High Falls, with dedicated wedding planners.		(570) 226-6130	https://hawleysilkmill.com
Ledges Hotel	119 Falls Avenue	Hawley	Pennsylvania			Ballroom / Hotel	Indoor			A boutique hotel in a restored 1890s glass factory above Paupack High Falls, with an on-site restaurant and bar.		570-226-1337	https://www.ledgeshotel.com
Camelback Resort	193 Resort Drive	Tannersville	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			A mountain resort with a ballroom and a Summit House that has a pergola ceremony site, offering all-inclusive wedding packages.		(855) 515-1283	https://www.camelbackresort.com
Scranton Cultural Center at the Masonic Temple	420 N. Washington Avenue	Scranton	Pennsylvania			Historic / Estate	Indoor			A 1930 Masonic Temple with a Grand Ballroom and several smaller rooms for weddings, plus an events team.		570.346.7369	https://www.scrantonculturalcenter.org`,
  },
  {
    name: "Erie, State College, Harrisburg, Bucks County, Lehigh Valley, Poconos and Pittsburgh",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Phipps Conservatory and Botanical Gardens	One Schenley Park	Pittsburgh	Pennsylvania			Garden / Outdoor	Indoor & Outdoor			A Victorian glasshouse conservatory in Schenley Park with an estate-style outdoor garden and a green-roof cocktail area.		412-622-6914	https://www.phipps.conservatory.org/weddings
Lakeview Farms Events	3440 Admire Rd	Dover	Pennsylvania			Barn / Rustic	Indoor & Outdoor			A farm-based wedding and event venue near York that has hosted celebrations since 2012 and offers planning help.		(717) 214-0500	https://www.lakeviewfarmsevents.com
The Barn at Ivan's Run	5947 Knoyle Road	Erie	Pennsylvania			Barn / Rustic	Indoor & Outdoor			A restored barn in the countryside outside Erie, used for wedding ceremonies and receptions.			https://www.ivansrunbarn.com/
Beach Glass Estates	12424 East Lake Rd	North East	Pennsylvania			Historic / Estate	Indoor & Outdoor			A lakeside estate in Lake Erie wine country, built in 1912 for Episcopal monks and since restored for weddings and events.	beachglassestates@gmail.com		https://www.beachglassestates.com
Mt. Nittany Overlook Event Center	559 N Pennsylvania Ave	Centre Hall	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			A hilltop event centre on the Mt. Nittany ridge with long views, three levels of indoor space and in-house catering.	events@mtnittanyoverlook.com	814-364-9363	https://www.mtnittanyeventcenter.com/
Carnegie House	100 Cricklewood Drive	State College	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			A small inn near Penn State that hosts landscaped outdoor ceremonies, receptions and full-property buyouts with guest suites.		814-234-2424	https://www.carnegiehouse.com/weddings.htm
The Nature Inn at Bald Eagle	201 Warbler Way	Howard	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	150		A LEED Gold inn inside a state park, offering a lakeside lodge, patio and fire ring with lodging and in-house catering.		814-625-2879	https://www.natureinnatbaldeagle.com/our-venue
The Penn Stater Hotel & Conference Center	215 Innovation Blvd	State College	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			A hotel with ballrooms for receptions, an outdoor terrace for ceremonies, on-site rooms and in-house catering.	reservations@scholartps.com	814-863-5000	https://www.thepennstaterhotel.com/weddings/
The Central Hotel	800 East Park Drive	Harrisburg	Pennsylvania			Ballroom / Hotel	Indoor	400		A Harrisburg hotel with a large ballroom, a smaller heritage ballroom, a three-storey atrium and a dedicated wedding coordinator.		(717) 561-1143	https://thecentralhotelharrisburg.com/wedding-receptions/
Willows Hotel and Event Center	1830 Midland Beaver Rd	Industry	Pennsylvania			Ballroom / Hotel	Indoor			A hotel, restaurant and event centre in Beaver County that hosts weddings alongside meetings and private events.	info@willowsofpa.com	724-643-4500	https://willowsofpa.com
The Brasenhill Mansion	104 East Walnut Street	Lebanon	Pennsylvania			Historic / Estate	Indoor & Outdoor	100	Classic	A 1928 mansion with nine bedrooms, gardens and a sun porch, offered for small weddings with a two-night stay.	jasonschwalm@comcast.net	717-507-2375	https://brasenhillmansion.com/
The Club at Blackthorne	1028 Blackthorne Drive	Jeannette	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor	500		A bring-your-own-drinks event venue east of Pittsburgh with a main ballroom, mezzanine, terrace and a pavilion for ceremonies.		(412) 720-1787	https://www.theclubatblackthorne.com
Quentin Grove	2395 Quentin Road	Lebanon	Pennsylvania			Barn / Rustic	Indoor & Outdoor			A restored 1800s barn on about four acres of Lebanon County countryside with a large lawn for outdoor use.	info@quentingrove.com	717-256-1212	https://www.quentingrove.com
Three Gables Barn	2269 Newville Road	Carlisle	Pennsylvania			Barn / Rustic	Indoor & Outdoor			A historic limestone barn on a South Central Pennsylvania farmstead, with hand-hewn beams, a mountain-view patio and open fields.	ted@threegablesbarn.com	717-574-0092	https://www.threegablesbarn.com
The Manor on Saw Mill	636 Saw Mill Road	Mechanicsburg	Pennsylvania			Barn / Rustic	Indoor & Outdoor	150		A rustic barn and renovated 1829 stone farmhouse on wooded acreage, with an outdoor ceremony site overlooking a hillside.	jennifer@themanoronsawmill.com	717-802-0003	https://www.themanoronsawmill.com
The General Potter Farm	612 Old Route 322	Spring Mills	Pennsylvania			Barn / Rustic	Indoor & Outdoor	200		A renovated barn with an upstairs reception room, plus a ceremony meadow and barnyard on farmland near State College.	generalpotterfarm@gmail.com	(814) 364-2474	https://www.generalpotterfarm.com
Goodell Gardens & Homestead	221 Waterford Street	Edinboro	Pennsylvania			Garden / Outdoor	Indoor & Outdoor			A public garden and arboretum in Edinboro with indoor and outdoor event spaces that takes wedding bookings.			https://www.goodellgardens.org
Lake Shore Country Club	5950 Lake Shore Drive	Erie	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			A country club on the Lake Erie shore with a grand ballroom, a smaller banquet room and a lawn.	secretary@lakeshorecountryclub.com	(814) 833-0894	https://www.lakeshorecountryclub.com
32 West Eighth	32 West 8th Street	Erie	Pennsylvania			Historic / Estate	Indoor			A downtown Erie wedding venue in a 1909 building with original woodwork, marble corridors and a grand ballroom.	events@32westeighth.com	814-459-2425	https://www.32westeighth.com/
Watson-Curtze Mansion	356 West 6th Street	Erie	Pennsylvania			Historic / Estate	Indoor & Outdoor	350		An 1891 Victorian mansion and museum on Millionaire's Row, with stained glass, a ballroom, a solarium and a tented garden.	events@eriehistory.org		https://www.erieweddings.net/watson-curtze-mansion/
Durham Hill Farm	6409 Durham Rd	Pipersville	Pennsylvania			Barn / Rustic	Indoor & Outdoor			Veteran-owned farm in Bedminster Township whose 1812 stone bank barn hosts weddings with Bucks County views and add-on packages.		(215) 766-7813	https://www.durhamhillfarm.com
Domaine Pterion Vineyard & Winery	6501 Saint Peters Road	Macungie	Pennsylvania			Restaurant / Vineyard	Indoor & Outdoor			Sixty-acre vineyard and winery in the Lehigh Valley with a restored historic bank barn used for wedding celebrations.		(610) 417-9446	https://www.domainepterion.com
Folino Estate Winery	340 Old Route 22	Kutztown	Pennsylvania			Restaurant / Vineyard	Indoor & Outdoor	220		Berks County winery with a banquet room, vineyard views and an Italian menu, taking wedding parties of up to 220 guests.	info@folinoestate.com	484-452-3633	https://folinoestate.com/weddings
Kraras Hall of Wyomissing		Wyomissing	Pennsylvania			Ballroom / Hotel	Indoor	300		Modern hall renovated in 2023, run by a Greek Orthodox church and available for wedding receptions only, with its own approved caterer list.	krarashall@gmail.com	484-577-3952	https://krarashall.com
The Inn at Centre Park	730 Centre Ave	Reading	Pennsylvania			Historic / Estate	Indoor	70		1877 mansion turned bed and breakfast in Reading, suited to intimate weddings, rehearsal dinners and small receptions with overnight guest suites.	innkeeper@theinnatcentrepark.com	610-374-8557	https://theinnatcentrepark.com/weddings-events
Stoner Commons	605 Granite Run Drive	Lancaster	Pennsylvania			Barn / Rustic	Indoor	150		Restaurant and mini-golf complex in Lancaster whose event barn hosts weddings and receptions for up to 150 guests.		717-208-6623	https://stonercommons.com/weddings
6th & River	525 Church Street	Honesdale	Pennsylvania			Historic / Estate	Indoor	180		Nineteenth-century brick warehouse on the Lackawaxen River, converted for weddings of up to 180 guests with a package that includes the venue.		(570) 616-7134	https://6thandriver.com/weddings
Shawnee Inn & Golf Resort	100 Shawnee Inn Dr	Shawnee on Delaware	Pennsylvania			Ballroom / Hotel	Indoor & Outdoor			Riverside Poconos resort offering wedding ceremonies by the Delaware, a reception hall, golf and full-service planning.	info@shawneeinn.com	570-424-4000	https://www.shawneeinn.com/wedding-venues-poconos-pa
Philadelphia Cricket Club	415 West Willow Grove Avenue	Philadelphia	Pennsylvania			Historic / Estate	Indoor & Outdoor			Private club in Philadelphia with a clubhouse and a second Fort Washington site, both set up for weddings and events.		215.247.6001	https://philacricket.com/weddings-and-events`,
  },
];

export default batches;
