import type { VenueBatch } from "@/lib/venue-batches";

// South Carolina venue batches. Every row's State is "South Carolina". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Charleston and Greenville venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Old Wide Awake	5149 Trexler Ave	Hollywood	South Carolina			Historic / Estate	Indoor & Outdoor	250	Classic	Historic house that once served as a store for the Stono Ferry, rented for the whole day with a bridal suite, travertine patio and built-in bar.		(843) 814-4980	https://oldwideawake.com
Hart Meadows Ranch	2837 Edenvale Rd	Johns Island	South Carolina			Barn / Rustic	Indoor & Outdoor	200		Ten-acre private ranch holding one event a day, with a cypress-ceilinged Oak Hall, a yurt, gardens under live oaks and a small private beach.	contact@hartmeadowsranch.com	843-642-7520	https://www.hartmeadowsranch.com
Avenue	110 E Court St	Greenville	South Carolina			Ballroom / Hotel	Indoor & Outdoor	200		Indoor-outdoor rooftop event space a block from Main Street, designed by Keith Summerour, with catering by Table 301.	info@avenuegreenville.com	864-686-7972	https://www.avenuegreenville.com
Riverain Farm	144 Lindsey Lake Rd	Travelers Rest	South Carolina			Barn / Rustic	Indoor & Outdoor	250	Classic	Family-run farm overlooking Lindsey Lake about 10 miles from downtown Greenville, with lakeside ceremonies and a barn for receptions.	events@riverainfarm.com		https://www.riverainfarm.com
Huguenot Loft at the Peace Center	300 S Main St	Greenville	South Carolina			Historic / Estate	Indoor	200	Classic	Former textile mill loft on the Peace Center campus with wood floors, exposed brick, high ceilings and windows facing the Reedy River.		864-467-3000	https://www.peacecenter.org/host-your-event/huguenot-loft
Lindsey Plantation	750 Camp Creek Rd	Taylors	South Carolina			Historic / Estate	Indoor & Outdoor			Working estate of more than 350 acres with mountain views, an 1890 family home with an indoor chapel, stables, courtyards and five guest bedrooms.	Lindseyplantation@gmail.com	864-304-8664	https://www.lindseyplantation.com
Kersey House	117 W Luke Ave	Summerville	South Carolina			Historic / Estate	Indoor & Outdoor	200		Renovated historic home in downtown Summerville run by chef Nico Romo, with in-house menus and indoor and outdoor event spaces.	info@nicoromohg.com	843-983-1813	https://www.kerseyhousesummerville.com/venue
Wingate Place		Johns Island	South Carolina			Garden / Outdoor	Outdoor	300		Lowcountry property between Charleston and Kiawah with big oaks, a 40x80 framed tent on a concrete pad and a farmhouse for the wedding party.	sarah@wingateplace.com	(843) 408-5963	https://wingateplace.com
Harborside East		Mount Pleasant	South Carolina			Beach / Waterfront	Indoor & Outdoor		Simple	Waterfront event building at Patriots Point facing the harbour and the Ravenel Bridge, with an air-conditioned hall and a partly covered patio.	reservations@harborsideeast.com	843-606-2718	https://www.harborsideeast.com/nav/weddings.html
Old Santee Canal Park	900 Stony Landing Rd	Moncks Corner	South Carolina			Historic / Estate	Indoor & Outdoor			195-acre park on Biggin Creek whose 1840 Stony Landing House on a bluff and creek-view Interpretive Center are rented for weddings and receptions.	parkinfo@oldsanteecanalpark.org	843-899-5200	https://www.oldsanteecanalpark.org/Rentals/Index.aspx
Charlyn Farms	4600 Dacusville Hwy	Marietta	South Carolina			Barn / Rustic	Indoor & Outdoor		Simple	Gated 52-acre property near Table Rock with mountain views and waterfalls, a barn for receptions and an on-site cottage called The Hideaway.	charlynfarms@gmail.com	864-270-1549	https://www.charlynfarms.com
Events at Judson Mill	701 Easley Bridge Rd	Greenville	South Carolina			Historic / Estate	Indoor & Outdoor	500		Refurbished textile mill with two event spaces, the Annex with a terrace and the Smokestack with a courtyard, plus in-house catering and bar.	venues@highspiritshospitality.com	(864) 248-4868	https://www.eventsatjudsonmill.com`,
  },
  {
    name: "Columbia, Myrtle Beach, Charleston and Greenville venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Wintergreen Woods	1032 Corley Mill Rd	Lexington	South Carolina			Garden / Outdoor	Indoor & Outdoor	150		All-inclusive Lexington venue with a garden, covered veranda and lawn for ceremonies, a reception hall opening onto a patio with a cabana bar, and in-house catering.	thevenue@wintergreenwoods.com	(803) 957-8888	https://www.wintergreenwoods.com
The Cotton Press	199 W Church St	Little Mountain	South Carolina			Historic / Estate	Indoor & Outdoor	250		Renovated century-old brick cotton press in the middle of Little Mountain, with a main hall, an outdoor area and separate upstairs suites for each side of the wedding party.		803.546.2494	https://www.thecottonpress.com
Corley Mill House & Gardens	221 Corley Mill Rd	Lexington	South Carolina			Historic / Estate	Indoor & Outdoor			Edwardian house from 1908 with a banquet hall and gardens added later, plus decks with built-in bars inside and out and a balcony for portraits before guests arrive.		803-957-1818	https://www.corleymillhouse.com/weddings
Farm Crafted Events	1127 Corley Mill Rd	Lexington	South Carolina			Barn / Rustic	Indoor & Outdoor	100	Simple	Venue on an eighth-generation family farm whose all-inclusive packages for up to 100 guests are cooked with produce grown on the property, with a small barn-style chapel for rain.	info@farmcraftedevents.com	(803) 250-5797	https://www.farmcraftedevents.com/weddings
City Art	1224 Lincoln St	Columbia	South Carolina			Historic / Estate	Indoor		Simple	Art gallery and supply store in a turn-of-the-century brick building in the Vista, whose main gallery with 14-foot beamed ceilings is rented for receptions among the art.			https://www.cityartonline.com/venue-rental
Stone River	121 Alexander Rd	West Columbia	South Carolina			Beach / Waterfront	Indoor & Outdoor		Simple	Former riverside restaurant on the Congaree beside the Three Rivers Greenway, with a stone fireplace and bar inside, a wrap-around porch and a covered pavilion.		803.727.8047	https://www.stonerivercolumbia.com/weddings
EdVenture	211 Gervais St	Columbia	South Carolina			Garden / Outdoor	Indoor & Outdoor	1500	Simple	Children's museum that rents its 12,000-square-foot evening terrace, looking over the Congaree River and the Gervais Street Bridge, along with lobby and lower-level rooms.			https://edventure.org/rentals/
South Carolina State Museum	301 Gervais St	Columbia	South Carolina			Historic / Estate	Indoor & Outdoor			State museum in a former textile mill on the riverfront, renting its planetarium lobby, observatory terrace and meeting rooms for receptions large and small.		803-898-4921	https://www.scmuseum.org/rent-the-museum
The Millstone at Adams Pond	5301 Bluff Rd	Columbia	South Carolina			Historic / Estate	Indoor & Outdoor			Red-brick building at the edge of a millpond on thirty acres in the Cowasee Basin, recalling the site's old grits mill, with a garden, footbridge and in-house catering.		803.783.1061	https://www.millstoneatadamspond.com
Pine Lakes Country Club	5603 Granddaddy Dr	Myrtle Beach	South Carolina			Historic / Estate	Indoor & Outdoor			Myrtle Beach golf club nicknamed the Granddaddy, its clubhouse on the National Register of Historic Places, with a courtyard garden for ceremonies and the course behind it at sunset.		(843) 315-7700	https://pinelakes.com/wedding/
Kaminski House	1003 Front St	Georgetown	South Carolina			Historic / Estate	Indoor & Outdoor			Eighteenth-century house museum on Georgetown's waterfront whose front porch, lawn and side terrace are used for ceremonies and receptions.	info@thekaminskihouse.com	843-546-7706	https://www.kaminskihouse.org/weddings
Grande Dunes Members Club	1580 Terra Verde Dr	Myrtle Beach	South Carolina			Ballroom / Hotel	Indoor & Outdoor			Private golf club in Grande Dunes that opens its clubhouse to non-members for weddings and smaller private events.		(843) 913-1340	https://www.grandedunesmembersclub.com/weddings-events
Wachesaw Plantation Club	1932 Governors Landing Rd	Murrells Inlet	South Carolina			Beach / Waterfront	Indoor & Outdoor			Private club on a former rice plantation where ceremonies take place under an old oak on a bluff above the water, with receptions in the clubhouse.		(843) 357-1263	https://www.wachesaw.com/Event_Services
Wild Wing	1000 Wild Wing Blvd	Conway	South Carolina			Ballroom / Hotel	Indoor & Outdoor	250		Golf clubhouse off Highway 501 with floor-to-ceiling windows over the course and a large patio, seating up to 250 with room for dancing.		(843) 347-9464	https://www.playwildwing.com/wedding/
Kingston Resorts	9800 Queensway Blvd	Myrtle Beach	South Carolina			Beach / Waterfront	Indoor & Outdoor		Classic	Oceanfront resort with the Hilton and Embassy Suites, three ballrooms including one sixteen floors up, and seven beach and lawn spaces for ceremonies.		843-449-0006	https://www.kingstonresorts.com/gather/weddings/
Ocean Creek Resort	10600 N Kings Hwy	Myrtle Beach	South Carolina			Beach / Waterfront	Indoor & Outdoor	220		Oceanfront resort at the north end of Myrtle Beach with about 6,500 square feet of event space for receptions of 20 to 220 and beach ceremonies.	info@oceancreek.com	800-303-6829	https://www.oceancreek.com/groups/
Litchfield Beach & Golf Resort	14276 Ocean Hwy	Pawleys Island	South Carolina			Beach / Waterfront	Indoor & Outdoor			Resort on the Litchfield coast near Pawleys Island with lawns and beach for ceremonies, in-house catering and rental homes for guests.		(843) 235-4980	https://www.litchfieldbeach.com/groups/
104 Laurel	104 Laurel St	Conway	South Carolina			Historic / Estate	Indoor	120		Restored 1935 warehouse in Conway's riverfront historic district with a flexible open floor, seating 120 for dinner and a short walk from the Riverwalk.	info@104laurel.com	843-503-4110	https://www.104laurel.com
The Historic Peanut Warehouse		Conway	South Carolina			Barn / Rustic	Indoor		Simple	Brick warehouse from around 1900 in downtown Conway near the Riverwalk, renovated in 2021 and rented as a blank space with tables and chairs to set up yourself.			https://peanutwarehouse.com/
Cannon Green	103 Spring St	Charleston	South Carolina			Historic / Estate	Indoor & Outdoor	125		Pair of historic buildings on Spring Street joined by a palm-framed courtyard, with a vaulted Trolley Room and an all-inclusive package for up to 125 guests.	events@cannongreencharleston.com	843.817.6299	https://cannongreencharleston.com/weddings/
The Barn at Reeves Farm	161 Ordie Rd	Reevesville	South Carolina			Barn / Rustic	Indoor & Outdoor		Simple	Barn on an 80-acre farm about an hour inland from Charleston, rented by the day with its grounds and a bridal suite.	thebarnatreevesfarm@gmail.com	843-560-0707	https://www.thebarnatreevesfarm.com
Zen Greenville	924 S Main St	Greenville	South Carolina			Ballroom / Hotel	Indoor & Outdoor		Simple	Modern event space on South Main near Fluor Field with a lounge, a private dining suite and a bamboo garden for outdoor ceremonies.	info@zengreenville.com	(864) 235-5770	https://www.zengreenville.com
The Venue at Cherokee Valley	407 Cherokee Valley Way	Travelers Rest	South Carolina			Ballroom / Hotel	Indoor & Outdoor	130		Golf club event room in the foothills above Travelers Rest with a wrap-around porch, course views and catering from the club's own restaurant.			https://www.thevenueatcherokeevalley.com
The Barn at Sitton Hill Farm	1904 Sitton Hill Rd	Easley	South Carolina			Barn / Rustic	Indoor & Outdoor	250		Family-owned barn on 99 acres of pasture, woods and creek outside Easley, with separate spaces for getting ready, the ceremony and the reception.	sitton@thebarnatsittonhillfarm.com	(864) 787-3608	https://www.thebarnatsittonhillfarm.com`,
  },
  {
    name: "Myrtle Beach: Grand Strand, Pawleys Island, Georgetown and Conway venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Wicklow Hall	91 Wicklow Hall Dr	Georgetown	South Carolina			Historic / Estate	Indoor & Outdoor			Lowcountry estate outside Georgetown with indoor and outdoor spaces, aimed at intimate weddings.	host@wicklowhall.com	843-765-2818	https://wicklowhall.com
The George Hotel	615 Front St	Georgetown	South Carolina			Beach / Waterfront	Outdoor			Waterfront lawn on the Sampit River in Georgetown's historic district, offered for daytime ceremonies and events a short boardwalk stroll from downtown.		843-932-8664	https://www.thegeorgehotelsc.com
Caledonia Golf & Fish Club	369 Caledonia Dr	Pawleys Island	South Carolina			Historic / Estate	Indoor & Outdoor			Golf club on the grounds of an old rice plantation, with live oaks hung with Spanish moss, a clubhouse over the 18th hole and a historic fish shed for events.	info@caledoniawedding.com	(843) 222-9249	https://caledoniagolfandfishclub.com/weddings-and-events/
Litchfield Country Club	619 Country Club Dr	Pawleys Island	South Carolina			Ballroom / Hotel	Indoor	150		Lowcountry club with a chandeliered ballroom, double grand staircase and rocking-chair porch, hosting weddings of up to 150.		843-237-3411	https://www.litchfieldgolf.com/
The Village House at Litchfield	13089 Ocean Hwy Building E	Pawleys Island	South Carolina			Garden / Outdoor	Indoor & Outdoor			Event space in the middle of Pawleys Island with an open indoor floor plan and outdoor areas, used for weddings, elopements and micro-weddings.	julia@villagehouselitchfield.com	843-457-8017	https://villagehouselitchfield.com/
Heritage Club		Pawleys Island	South Carolina			Historic / Estate	Indoor & Outdoor			Golf club in Pawleys Island offering ceremonies under old live oaks and flexible indoor and outdoor spaces, with on-course hospitality.			http://www.legendsgolf.com/heritageclub.cfm
Safe Harbor Reserve Harbor	2040 Willbrook Blvd	Pawleys Island	South Carolina			Beach / Waterfront	Indoor & Outdoor			Marina clubhouse under oak trees with a boardwalk through cypress forest to the Waccamaw River, a private meeting room and a covered fireplace patio.		843-314-5100	https://safeharbor.com/locations/safe-harbor-reserve-harbor/
Inlet Affairs	4024 Highway 17 Business	Murrells Inlet	South Carolina			Restaurant / Vineyard				Murrells Inlet venue and caterer, in business since 2004, handling weddings and events on site and off.	info@inletaffairs.com	(843) 651-2904	https://inletaffairs.com
Pawleys Island Chapel	391 Myrtle Ave	Pawleys Island	South Carolina			Historic / Estate	Indoor			Small sanctuary on Pawleys Island used for weddings, baptisms and other celebrations.		(843) 237-2000	https://www.pawleysislandchapel.com/
Wedgefield Plantation Country Club	129 Clubhouse Ln	Georgetown	South Carolina			Historic / Estate	Indoor & Outdoor			Country club built around the Manor House at Wedgefield Plantation, with live oaks, courtyards, patios and cottages.		843-546-8587	https://www.wedgefieldcountryclub.com/
Lands End Yacht Club	444 Marina Dr	Georgetown	South Carolina			Beach / Waterfront	Indoor & Outdoor	130		Yacht club on the Intracoastal Waterway overlooking Winyah Bay, with two function rooms and a deck, where couples bring their own caterer.	LandsEndYachtClub@gmail.com	(843) 936-1430	https://www.landsendyachtclub.com/
Winyah Bay Club	114 Church St	Georgetown	South Carolina			Beach / Waterfront	Indoor & Outdoor			Riverside Lowcountry venue in historic Georgetown with a Sand Bar Pavilion for ceremonies and receptions and 17 cottages for guests.	reservations@winyahbayclub.com	(843) 410-8991	https://www.winyahbayclub.com/Events-And-Weddings
Winyah Indigo Society Hall	509 Prince St	Georgetown	South Carolina			Historic / Estate	Indoor			Historic hall in Georgetown's old district, among live oaks, rented for receptions and banquets.	winyahindigohall@gmail.com		https://www.winyahindigohall.com/
21 Main Events at North Beach	719 North Beach Blvd	North Myrtle Beach	South Carolina			Beach / Waterfront	Indoor & Outdoor			Resort event venue near the beach with a courtyard and sand for ceremonies, a grand ballroom for receptions, a bridal suite and in-house catering.		(843) 282-7100	https://21maineventsatnorthbeach.com/
The Venue at White Oaks Farm	2275 Old Buck Creek Rd	Longs	South Carolina			Barn / Rustic	Indoor & Outdoor	220		Private 43-acre countryside estate north of Myrtle Beach with a main hall that seats 220 guests.		854-854-2988	https://thevenueatwhiteoaksfarm.com/
The Dunes Golf and Beach Club	9000 N Ocean Blvd	Myrtle Beach	South Carolina			Beach / Waterfront				Oceanfront golf and beach club that has been open since 1948 and promotes itself for weddings.		(843) 449-5236	https://www.thedunesclub.com/
Terrazza 19 at Grande Dunes	8700 Golf Village Ln	Myrtle Beach	South Carolina			Restaurant / Vineyard				Restaurant and private event space at the Grande Dunes golf resort with views of the Intracoastal Waterway.		843-315-0333	https://www.grandedunesgolf.com/
Barefoot Resort Clubhouses	4980 Barefoot Resort Bridge Rd	North Myrtle Beach	South Carolina			Ballroom / Hotel				Golf resort with a Resort clubhouse and a Dye clubhouse that both take wedding functions.		843-390-3200	https://barefootgolf.com/weddings/
The Breakers Resort	2104 N Ocean Blvd	Myrtle Beach	South Carolina			Beach / Waterfront	Indoor & Outdoor			Oceanfront resort with a lawn and wooden bridge for ceremonies, the Farlow oceanfront ballroom and a banquet hall.		(877) 276-8867	https://www.breakers.com/weddings/
The Hall at St. John's	3301 33rd Ave Ext N	Myrtle Beach	South Carolina			Ballroom / Hotel	Indoor			About 7,500 square feet of heated and air-conditioned space behind a Greek Orthodox church, where renters can use the in-house caterer or bring their own.	thehall@stjohn-mb.org	843-283-3087	https://www.thehallatstjohns.com
WildHorse at Parker Farms	595 Parker Dr	Longs	South Carolina			Barn / Rustic		200	Simple	Family-owned covered venue in Longs for up to 200 guests; Friday and Saturday rentals run $4,700.	wildhorse.events@gmail.com	843-653-4079	https://wildhorseatparkerfarms.com
Le Petit Fox Farm	2475 Old Clearpond Rd	Conway	South Carolina			Garden / Outdoor	Indoor & Outdoor			Private 22-acre estate near Myrtle Beach with a Grand Pavilion and a glasshouse in botanical gardens.	hello@lepetitfoxfarm.com	843-246-1930	https://lepetitfoxfarm.com
Laurel Oaks Estate	4025 Copperhead Rd	Conway	South Carolina			Garden / Outdoor				Private Conway property with a fountain pond, pergola, hay field and forest settings, plus glamping, a cabin and RV sites.		(843) 603-1670	https://laureloaksestate.com
voco The Shelby	1802 N Ocean Blvd	Myrtle Beach	South Carolina			Ballroom / Hotel				Oceanfront boutique hotel with flexible event spaces and ocean views.		843-448-7101	https://theshelbymyrtlebeach.com
Carolina Private Events	9911 N Kings Hwy	Myrtle Beach	South Carolina			Historic / Estate	Indoor			Event rooms in a 14,000-square-foot historic building, including a garden room under a stained-glass roof and a lounge with a dance floor.	carolinaprivateevents@gmail.com	(843) 945-9287	https://carolinaprivateevents.com
Marina Inn at Grande Dunes	8121 Amalfi Pl	Myrtle Beach	South Carolina			Ballroom / Hotel				Intracoastal Waterway resort in Grande Dunes with several wedding packages.		843-913-1333	https://marinainnatgrandedunes.com`,
  },
];

export default batches;
