import type { VenueBatch } from "@/lib/venue-batches";

// Texas venue batches. Every row's State is "Texas". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Lubbock, El Paso, Coast and Central Texas",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Spirit Ranch	701 Regis St	Lubbock	Texas			Barn / Rustic	Indoor & Outdoor			Rustic West Texas estate in Escondido Canyon with two venue spaces and old-fashioned hospitality.	info@spiritranch.us	806.762.6201	https://spiritranch.us
Horseshoe Knot Event Center	5618 County Rd 1240	Lubbock	Texas			Barn / Rustic	Indoor & Outdoor	350		A 7,200 sq ft barn on two landscaped acres with a gazebo and pergolas.		806-543-5268	https://horseshoeknoteventcenter.com
English Newsom Cellars	408 E Woodrow Rd	Lubbock	Texas			Restaurant / Vineyard	Indoor & Outdoor			Family winery offering vineyard backdrops, outdoor patio weddings and intimate indoor wine cellars.	info@englishnewsom.com	806-863-2704	https://englishnewsom.com/wp/weddings/venue/
Adelphos Cellars	11206 Indiana Ave	Lubbock	Texas			Restaurant / Vineyard	Indoor & Outdoor	275		Locally owned winery with Mediterranean-style architecture, a Grand Room, courtyard and vineyard ceremony sites.	info@adelphoscellars.com	(806) 370-2915	https://adelphoscellars.com/events/
McPherson Cellars	1615 Texas Ave	Lubbock	Texas			Restaurant / Vineyard	Indoor & Outdoor			Winery in the old Coca-Cola bottling plant in the Depot District, with a lofty interior, tasting room and shaded patio.	info@mcphersoncellars.com	806-687-9463	https://mcphersoncellars.com
The Historic Baker Building	1211 13th St	Lubbock	Texas			Historic / Estate	Indoor			Historic Lubbock hall for weddings and receptions, pitched as a striking photo backdrop.		(806) 218-8428	https://historicbakerbuildingtx.com/
Bella Vie Wedding Venue & Events Center	13603 Slide Rd	Lubbock	Texas			Ballroom / Hotel	Indoor & Outdoor			Lubbock event center with indoor and outdoor spaces for weddings, parties and celebrations.	bellavievenue@gmail.com		https://www.bellavieevents.com/
Twin Lakes Wedding & Event Center	6268 Foster Rd	Ropesville	Texas			Garden / Outdoor	Indoor & Outdoor		Simple	Lakeside venue with indoor and outdoor spaces, bridal and groom suites and included decor.	twinlakesevent@gmail.com	(806) 470-1968	https://twinlakesweddingevents.com
Chateau Event and Wedding Venue	22001 South Eastern St	Canyon	Texas			Historic / Estate	Indoor & Outdoor	300	Classic	Canyon venue with bridal and groom rooms, Chiavari chairs and linens included in its weekend package.	info@chateauvenue.com	806-336-0066	https://www.chateauvenue.com/packages-1
Maple Event Center	10298 FM 2219	Amarillo	Texas			Barn / Rustic	Indoor & Outdoor		Simple	Rustic-country venue built in 2016 between Amarillo and Canyon, with a yard, pergola and catering room.		806-673-8034	https://www.mapleeventcenter.com/
The Barn on Willow Creek	4801 E Willow Creek Dr	Amarillo	Texas			Barn / Rustic	Indoor & Outdoor			All-wooden barn run by its owners, with a patio, bridal and groom rooms and a warming kitchen.	thebarnonwillowcreek@gmail.com	806.663.6327	https://www.thebarnonwillowcreek.com/
Events At The Barn	300 SE 58th Ave	Amarillo	Texas			Barn / Rustic	Indoor & Outdoor	150		Rustic venue with a full kitchen and bar, a dance floor and a covered porch.		(435) 881-8719	https://eventsatthebarntx.com/about-the-venue
EPIC Railyard Event Center	2201 E Mills Ave	El Paso	Texas			Historic / Estate	Indoor & Outdoor	500		Former 1917 industrial building with two event rooms, original hardwood floors and vintage bars.		(915) 373-7840	https://www.epicrailyard.com
El Campanario Ballroom	10142 Socorro Rd	El Paso	Texas			Barn / Rustic	Indoor & Outdoor	400		Rustic hacienda-style ballroom with a 3,000 sq ft dance floor and a garden tent pavilion on 8 gated acres.	elcampanarioballroom@yahoo.com	(915) 858-1419	https://www.elcampanarioballroom.com
The Ranch On Vinton Rd	600 N Vinton Rd	Anthony	Texas			Barn / Rustic	Indoor & Outdoor			Family-run ranch and barn venue with getting-ready suites and an outdoor function area.	TheRanchOnVintonRd@gmail.com	915-588-8221	https://www.theranchonvintonrd.com
Butterfield Trail Golf Club	1858 Cottonwoods Dr	El Paso	Texas			Garden / Outdoor	Indoor & Outdoor	300		Golf clubhouse and restaurant with a lakeside terrace and lawn for ceremonies.		915.772.1038	https://www.butterfieldtrailgolf.com
The Garden Venue	12400 Montwood Dr	El Paso	Texas			Garden / Outdoor	Indoor & Outdoor			All-inclusive wedding venue pairing gardens with indoor spaces and on-site catering.	Events@gardenvenue915.com	(915) 888-6078	https://www.thegardenvenue.com
Plush Garden	10490 Dyer St Ste C	El Paso	Texas			Ballroom / Hotel	Indoor	500		Event hall with a big hall for up to 500 and a small hall for up to 100.		(915) 407-1459	https://www.plushgardenelp.com
Mansion Royal	8001 S Padre Island Dr	Corpus Christi	Texas			Ballroom / Hotel	Indoor			Family-owned ballroom venue with full-service wedding planning, catering and design.	info@corpuschristimansionroyal.com	(361) 985-9955	https://corpuschristimansionroyal.com
The Venue	6181 Saratoga Blvd	Corpus Christi	Texas			Ballroom / Hotel	Indoor	150	Simple	Pre-decorated southside event space with linens, centerpieces and chairs included in its wedding packages.		361-816-5346	https://www.thevenuecc.com/
Texas State Aquarium	2710 N Shoreline Blvd	Corpus Christi	Texas			Beach / Waterfront	Indoor & Outdoor	550		Bayfront aquarium offering all-inclusive reception spaces such as the Water's Edge Boardwalk and Living Shores.		361-653-2627	https://www.texasstateaquarium.org/visit/private-events/weddings/
Knolle Farm & Ranch	13016 FM 70	Sandia	Texas			Barn / Rustic	Indoor & Outdoor	300		Historic South Texas ranch with a chapel, oak-grove ceremony spots and event buildings.	knollefarm@gmail.com	(361) 547-2546	https://www.knolle.com/weddings-events/information/
Seashell Village Resort	502 E Avenue G	Port Aransas	Texas			Beach / Waterfront	Indoor & Outdoor			Resort with a party pavilion, private chapel, courtyard and beach space for ceremonies and receptions.		(361) 749-4294	https://seashellvillage.com/weddings-events-port-aransas-resort/
Sandcastle Resort Condominiums	800 Sandcastle Dr	Port Aransas	Texas			Beach / Waterfront	Indoor & Outdoor			Beachfront condo resort with a 3,500+ sq ft indoor event center and beach ceremony options.		361-749-6201	https://www.sandcastlecondos.com/weddings/port-aransas-indoor-weddings-and-receptions/
Sea Gull Condominiums	6649 Seacomber Dr	Port Aransas	Texas			Beach / Waterfront	Indoor & Outdoor			Gulf-front condos hosting beach ceremonies, with an indoor meeting facility for receptions.		(361) 749-4191	https://www.seagullcondos.com/weddings/
Margaritaville Beach Resort South Padre Island	310 Padre Blvd	South Padre Island	Texas			Ballroom / Hotel	Indoor & Outdoor	500		Beachfront resort with 8,500+ sq ft of ballroom and oceanside space and on-site catering.		956-761-6551	https://www.margaritavilleresorts.com/margaritaville-beach-resort-south-padre-island/events/weddings
Capilla del Rio	6506 US-83	Rio Grande City	Texas			Garden / Outdoor	Indoor & Outdoor	100		18-acre estate with a chapel and indoor and outdoor spaces, about 35 minutes from McAllen.	capilladelrio@outlook.com	956-358-5515	https://www.capilladelrio.com
Level 3 Coworking and Event Center	202 E Central Ave	Belton	Texas			Historic / Estate	Indoor & Outdoor	80		Contemporary, industrial-style event space in historic downtown Belton with a third-floor balcony and a courtyard.		(254) 630-8753	https://level3belton.com/wedding-venue-in-central-texas/
Hotel 1928	701 Washington Ave	Waco	Texas			Ballroom / Hotel	Indoor & Outdoor			Restored 1920s Shrine temple turned boutique hotel, with a nearly 6,000 sq ft ballroom opening to an outdoor terrace.	events@hotel1928.com	254.342.3911	https://www.hotel1928.com/weddings-celebrations
Carleen Bright Arboretum (The Pavilion)	1 Pavilion Way	Woodway	Texas			Garden / Outdoor	Indoor & Outdoor	350		City-run botanical garden with a 10,000 sq ft glass-walled pavilion, a gazebo and an event lawn.	events@woodwaytexas.gov	254.399.9204	https://discoverwoodway.com/venues/
Deerfield Estates	105 Deerfield Rd	Waco	Texas			Barn / Rustic	Indoor & Outdoor			Restored 1840s timber-frame barn with a ballroom, chapel, garden, bridal suite and on-site lodging.	info@deerfieldvenue.com	254.284.0070	https://www.deerfieldvenue.com/
Knoxville Ranch	4899 Leroy Pkwy W	Leroy	Texas			Barn / Rustic	Indoor & Outdoor			Ranch venue on 50 acres outside Waco, with two climate-controlled ballrooms and a bridal suite.	robin@knoxvilleranch.com	254-214-7344	https://www.knoxvilleranch.com/
The Barn on Spring Valley	1900 W Spring Valley Rd	Lorena	Texas			Barn / Rustic	Indoor & Outdoor			Family-run rustic barn near I-35 south of Waco, with a dance floor, band space and bar.	thebarn1900bookings@gmail.com	254-749-7887	https://www.thebarnonspringvalley.com/
The Weinberg at Wixon Valley	7786 Kurten Cemetery Rd	Bryan	Texas			Barn / Rustic	Indoor & Outdoor	450	Classic	18,600 sq ft vineyard-style barn on 100 acres, with a chapel and a pond-view veranda.			https://www.theweinbergatwixon.com/venue-details
Inn at Quarry Ridge	9401 Rust Ln	Bryan	Texas			Historic / Estate	Indoor & Outdoor			Country inn north of Bryan with the 5,000 sq ft Stonehem Hall, a lakeside gazebo and rooms for 25 overnight guests.	info@innatquarryridge.com	(979) 822-8368	https://innatquarryridge.com/facilities
Deep in the Heart Farms	8351 Highway 105	Brenham	Texas			Barn / Rustic	Indoor & Outdoor			Family-owned 150-acre farm with a white chapel, reception hall and bridal suites.	austin@deepintheheartfarms.com	713-817-6317	https://deepintheheartfarms.com/
The Laundry Event Hall	209 S Market St	Brenham	Texas			Historic / Estate	Indoor & Outdoor	150		Event hall in an 1883 industrial building in downtown Brenham, with an upstairs ballroom and a garden patio.	info@thelaundrytx.com	979.217.3088	https://www.thelaundrytx.com/
Ant Street Inn	107 W Commerce St	Brenham	Texas			Ballroom / Hotel	Indoor & Outdoor	250		Historic downtown boutique inn with a 4,000 sq ft stained-glass-domed ballroom, a veranda and garden.	stay@antstreetinn.com	979-836-7393	https://www.antstreetinn.com/venues
The Barnhill Center at Historic Simon Theatre	111 W Main St	Brenham	Texas			Historic / Estate	Indoor	321		Restored 1925 theatre with a 321-seat auditorium and a second-floor ballroom with chandeliers.	info@thebarnhillcenter.com	979-337-7240	https://thebarnhillcenter.com/meetings/`,
  },
  {
    name: "Texas: Tyler, Lubbock, Amarillo, DFW, Houston, Austin and the coast",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Sweet Promise Farm	12571 County Road 313 E	Tyler	Texas			Barn / Rustic	Indoor & Outdoor	150		A farm venue with an insulated indoor hall and a separate outdoor ceremony spot.	hello@sweetpromisefarm.com	(806) 577-2797	https://www.sweetpromisefarm.com/
Miss Mary's Place	1997 FM 2011	Longview	Texas			Barn / Rustic	Indoor & Outdoor	200	Simple	A cedar barn and a smaller bridal hall, with gardens and a ceremony pavilion for outdoor vows.	info@missmarysplace.com	(903) 738-9223	https://missmarysplace.com/
Amarillo Botanical Gardens	1400 Streit Dr	Amarillo	Texas			Garden / Outdoor	Indoor & Outdoor			A public botanical garden that rents out indoor and outdoor spaces for weddings.		(806) 352-6513	https://www.amarillobotanicalgardens.org/
Sophia's Place	7330 19th Street	Lubbock	Texas			Historic / Estate	Indoor & Outdoor	250		A restored warehouse with a large indoor room, full kitchen and a private outdoor patio.			https://sophiasplacevenue.com/
Castle Event Center	6417 County Road 7620	Lubbock	Texas			Historic / Estate			Simple	A castle-themed Lubbock event hall that sells tiered wedding packages with tables and chairs included.	ceclubbock@gmail.com	(806) 224-3927	https://castleeventcenter.com/
Rustic Oak Event Center	7902 FM 2378	Wolfforth	Texas			Barn / Rustic	Indoor & Outdoor			A Wolfforth event center with indoor and outdoor spaces that takes tour requests online.	rusticoak2024@gmail.com	806.241.2517	https://www.rusticoakeventcenter.com/
Vintage Oaks Venue	2712 Happy Swaner Lane	Axtell	Texas			Barn / Rustic	Indoor & Outdoor			A venue just outside Waco with an indoor and outdoor ceremony space, tours by appointment.	info@vintageoaksvenue.com	254-470-8794	https://www.vintageoaksvenue.com/
Triple Mountain Ranch	225 Private Road 4231	Clifton	Texas			Barn / Rustic	Indoor & Outdoor	500		A ranch near Waco with a large event barn, a climate-controlled hall and an open field for big ceremonies.		(254) 707-0224	https://www.triplemountainranch.com/
Earle-Harrison House & Pape Gardens	1901 N. 5th Street	Waco	Texas			Historic / Estate				Two historic homes on more than five acres of gardens in Waco, rented for weddings.	georgia.crowhurst@historicwaco.org	(254) 753-5166	https://www.earleharrisonhouse.com/
Chestnut Square	315 S. Chestnut Street	McKinney	Texas			Historic / Estate				A historic village in McKinney offering a chapel and garden setting for weddings.	info@chestnutsquare.org	972-562-8790	https://www.chestnutsquare.org/
Gather on the Square	207 E Virginia	McKinney	Texas			Historic / Estate				A historic downtown McKinney venue that takes wedding bookings by tour.		972-838-1888	https://www.gatheronthesquare.com/
Sunago Bell	101 S Locust St 8th floor	Denton	Texas			Ballroom / Hotel	Indoor			A 3,200 square foot top-floor event space in downtown Denton with panoramic windows.	events@sunagobell.com	940-999-8547	https://www.sunagobell.com/
Fall Creek Ranch	8220 Langdon Leake Ct	Granbury	Texas			Barn / Rustic	Indoor & Outdoor			A working ranch with an open-air chapel and a reception hall that opens to the outdoors.	Kristyn@FallCreekRanch.com	817-279-3911	https://fallcreekranch.com/
Trickle Creek Ranch & Events	5555 Old Brock Rd	Weatherford	Texas			Barn / Rustic				A Weatherford ranch event venue that offers free tours and a virtual walkthrough.	events@tricklecreekevents.com	(817) 313-1808	https://www.tricklecreekevents.com/
Fort Worth Country Memories	5682 Tenderfoot Trail	Fort Worth	Texas			Barn / Rustic	Indoor & Outdoor	150		A red barn, ballroom and open-air chapel on one Fort Worth property.	events@fortworthcountrymemories.com	(817) 773-6824	https://fortworthcountrymemories.com/
The Ashton Depot	1501 Jones Street	Fort Worth	Texas			Historic / Estate	Indoor & Outdoor			A 10,000 square foot depot event space in Fort Worth with an outdoor courtyard.		(817) 810-9501	https://www.theashtondepot.com/
The Bell Tower on 34th	901 W 34th St	Houston	Texas			Historic / Estate	Indoor & Outdoor	350	Luxury	Mediterranean-style Heights venue with indoor ballrooms, a chapel, garden courtyard and water wall, with in-house catering and coordination.		(713) 868-2355	https://thebelltoweron34th.com
The Bryan Museum	1315 21st Street	Galveston	Texas			Historic / Estate	Indoor & Outdoor			Renaissance Revival museum building with landscaped gardens that hosts weddings in the heart of Galveston's historic district.	info@thebryanmuseum.org	(409) 632-7685	https://thebryanmuseum.org/weddings
Carr Mansion	1103 33rd St	Galveston	Texas			Historic / Estate	Indoor & Outdoor	50		Restored 19th-century Greek Revival mansion and bed and breakfast whose ballroom and solarium suit intimate weddings with open vendor choice.		409-497-4740	https://www.carrmansion.com/events
Star Hill Ranch	15000 Hamilton Pool Rd	Austin	Texas			Barn / Rustic	Indoor & Outdoor			Re-created early-1900s Hill Country town with relocated historic buildings, a chapel, banquet hall and outdoor arbor.		844-777-7827	https://www.starhillranch.com
Old Glory Ranch	3633 River Rd	Wimberley	Texas			Barn / Rustic	Indoor & Outdoor			Riverside Hill Country ranch hosting weddings since 1997, with a chapel hall built from older buildings, an oak grove and a covered stone patio.		512-847-3646	https://www.oldgloryranch.com
The Heritage Society	1100 Bagby Street	Houston	Texas			Historic / Estate	Indoor & Outdoor	300	Simple	Historic campus in downtown Houston's Sam Houston Park offering a plaza, an 1891 church, restored houses and gardens for ceremonies and receptions.	info@heritagesociety.org	713-655-1912	https://www.heritagesociety.org/wedding-special-events
UMLAUF Sculpture Garden + Museum	605 Azie Morton Rd	Austin	Texas			Garden / Outdoor	Outdoor			Austin sculpture garden and museum that lists weddings among its venue rentals.	UMLAUFVenueTours@umlaufsculpture.org	(512) 445-5582	https://www.umlaufsculpture.org
Witte Museum	3801 Broadway	San Antonio	Texas			Historic / Estate	Indoor & Outdoor			Museum beside Brackenridge Park and the river offering ceremony-and-reception, reception-only and ceremony-only packages, including a courtyard under old oaks.	Events@WitteMuseum.org	210-357-1906	https://www.wittemuseum.org/weddings
Rancho La Pergola	26867 N Sam Houston	San Benito	Texas			Garden / Outdoor	Outdoor			Outdoor wedding venue in the Rio Grande Valley that takes quote requests through its site.	rancholapergola@gmail.com	956-617-4180	https://www.rancholapergola.com
The Terrace Club	2600 East Highway 290	Dripping Springs	Texas			Garden / Outdoor	Indoor & Outdoor			Full-service Hill Country venue with indoor and outdoor ceremony spaces where couples bring their own caterer, DJ and photographer.	info@theterraceclub.com	512-894-4009	https://www.theterraceclub.com
Vintage Villas Hotel & Events	4209 Eck Lane	Austin	Texas			Ballroom / Hotel	Indoor & Outdoor	299		Lake Travis bluff venue with a gazebo, arbor and indoor reception rooms, plus a 44-room hotel and in-house catering.	sales@vintagevillas.com	512-266-9333	https://www.vintagevillas.com/weddings
Hotel Emma	136 E Grayson Street	San Antonio	Texas			Ballroom / Hotel	Indoor & Outdoor			Hotel in the historic Pearl brewhouse with indoor spaces, a pool terrace and private suites for weddings.		210-448-8300	https://thehotelemma.com/weddings/
Painted Dunes Desert Golf Course	12000 McCombs St	El Paso	Texas			Garden / Outdoor	Indoor & Outdoor			Desert golf course at the foot of the Franklin Mountains that lists weddings among its events.	misingleton@painteddunes.com	(915) 821-2122	https://www.painteddunes.com
The Gardens of Cranesbury View	1470 S Cranes Mill Road	New Braunfels	Texas			Garden / Outdoor	Indoor & Outdoor			Italian-style garden venue on 32 acres with about three acres of sculpted gardens and a reception house.	cranesburyview@gmail.com	(830) 515-9231	https://thegardensofcranesburyview.com
The Houstonian Hotel	111 N Post Oak Ln	Houston	Texas			Ballroom / Hotel	Indoor & Outdoor			Wooded 27-acre resort with ballrooms, the Manor House and an oak-tree ceremony site, hosting weddings of intimate to 300-plus guests.	reservations@houstonian.com	(713) 680-2626	https://www.houstonian.com/weddings
Texas State Aquarium	2710 N Shoreline Blvd	Corpus Christi	Texas			Beach / Waterfront	Indoor & Outdoor			Bayfront aquarium on the Gulf coast hosting weddings among its exhibits, with on-site catering and all-inclusive options.		361-653-2627	https://www.texasstateaquarium.org/weddings`,
  },
  {
    name: "DFW, Houston, Austin and Hill Country",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Stillwater Meadow	9842 E Bankhead Hwy	Aledo	Texas			Barn / Rustic	Indoor & Outdoor			A family-built wedding property in Aledo with hand-made stained glass, a pond and a field.		(817) 841-9215	https://stillwatermeadow.com
Lazy S Hacienda	410 Weaver Lane	Weatherford	Texas			Garden / Outdoor	Indoor & Outdoor	200		A 70-acre private estate west of Fort Worth with Modern Mexican architecture and country views.	clients@lazyshacienda.com	817-458-8601	https://lazyshacienda.com
Honey Creek Venues	1105 W Cottage Hill Parkway	Celina	Texas			Garden / Outdoor	Indoor & Outdoor	175	Classic	A 26-acre venue in Celina with an open-air pavilion, getting-ready suites and several ceremony spots.	honeycreekvenues@gmail.com	469-431-3208	https://honeycreekvenues.com
Avalon Legacy Ranch	2022 Wayside Trail	McKinney	Texas			Barn / Rustic	Indoor & Outdoor			A wooded lakeside ranch in McKinney with an outdoor chapel, fire pits and a roughly 6,000 sq ft indoor space.		817-223-2992	https://avalonlegacyranch.com
Inn on Lake Granbury	205 W Doyle Street	Granbury	Texas			Beach / Waterfront	Indoor & Outdoor	32		An adults-only boutique hotel on three lakefront acres that hosts small ceremonies by the water.		817-573-0046	https://www.innonlakegranbury.com
Flyin H Ranch	238 County Road 319 W	Tyler	Texas			Barn / Rustic	Indoor & Outdoor			A working ranch near Tyler that hosts rustic weddings and offers on-site cabins.		903-426-5727	https://www.theflyinhranch.com/
The Villa Tyler	7891 Hwy 110 North	Tyler	Texas			Historic / Estate	Indoor & Outdoor			A Tuscan-style wedding venue north of Tyler with a garden pergola and an indoor room as the weather backup.	bookings@thevillatyler.com	903-597-0002	https://www.thevillatyler.com/weddings
The Reserve	7725 U.S. Highway 259 North	Longview	Texas			Ballroom / Hotel	Indoor & Outdoor	300		A Longview event center with a chandelier-lit interior and an outdoor pavilion with a fireplace and courtyard.		903-663-7650	https://bookthereserve.com/
The Sanford House Inn & Spa	506 N Center St	Arlington	Texas			Historic / Estate	Indoor & Outdoor	200		A boutique inn in downtown Arlington that hosts weddings in its Grand Courtyard and indoor spaces.	info@thesanfordhouse.com	817-861-2129	https://www.thesanfordhouse.com/
Sweet Hills Wedding & Event Center	11361 TX 300	Longview	Texas			Garden / Outdoor	Indoor & Outdoor	200		A 32-acre property near Longview with pond-side gazebos for ceremonies, a patio and bridal suites.	Sweethillseventcenter@gmail.com	430-625-2000	https://sweethillsweddingandeventvenue.com/
Circle R Ranch	5901 Cross Timbers Rd	Flower Mound	Texas			Barn / Rustic	Indoor & Outdoor	1500		A 60-acre ranch in Flower Mound with a large enclosed pavilion that opens onto a covered patio.	admin@circlerranch.org	(817) 430-1561	https://circlerranch.org/western-pavilion
The Castle at Rockwall	2071 Clem Road Ext	Rockwall	Texas			Historic / Estate	Indoor & Outdoor	350		A castle-style wedding venue in Rockwall with indoor and outdoor ceremony options.		469-687-2896	https://www.thecastleatrockwall.com/weddings.html
The Abbey Estate	3314 Farm to Market Rd 1446	Waxahachie	Texas			Barn / Rustic	Indoor & Outdoor			A five-acre Waxahachie estate with a modern farmhouse, a party barn and an outdoor pergola and lawn.	info@theabbeyestate.com	972-923-3333	https://www.theabbeyestate.com/
The Graily	716 Dunaway Street	Waxahachie	Texas			Historic / Estate	Indoor & Outdoor	250		A restored historic building in Waxahachie with a reception room and a turfed outdoor courtyard.	info@thegraily.com		https://www.thegraily.com/
The Secret Garden at Roland's	2240 Dallas Hwy	Waxahachie	Texas			Garden / Outdoor	Indoor & Outdoor	150		A garden-themed event space in Waxahachie with climate-controlled indoor and outdoor areas.		(972) 670-5420	https://thesecretgardenatrolands.com/
The Barn at Wolf Ridge Farm	1467 FM1200	Gainesville	Texas			Barn / Rustic	Indoor & Outdoor		Simple	A white barn venue near Gainesville with an indoor chapel, an outdoor ceremony area and an indoor reception hall.	dietershirley64@gmail.com	(940) 768-9122	https://www.thebarnatwolfridgefarm.com/
Katy Depot	101 E Main St	Denison	Texas			Historic / Estate		300		A restored 1911 railroad depot in downtown Denison used for weddings and receptions.	info@katydepottx.com	(903) 463-7729	https://katydepottx.com/the-venue/
The Five01 (501 Yacht Club)	501 Yacht Club Dr.	Rockwall	Texas			Beach / Waterfront				A lakeside yacht-club event venue in Rockwall.	Info@501YachtClub.com	469-769-1148	https://501yachtclub.com/
The Reserve on Cypress Creek	16500 Steinhagen Road	Cypress	Texas			Garden / Outdoor	Indoor & Outdoor			A family-owned wedding and event property in Cypress with a ceremony site and a one-wedding-at-a-time approach.		832-402-6001	https://www.thereserveoncypresscreek.com
Madera Estates Weddings & Events	3201 N. Frazier St.	Conroe	Texas			Historic / Estate	Indoor & Outdoor			A Conroe wedding estate with San Miguel de Allende-inspired architecture that hosts one wedding per day and offers all-inclusive options.	info@maderaestates.com	936-441-9337	https://www.maderaestates.com
Palm Royal Villa	3330 Farm to Market 1463	Katy	Texas			Historic / Estate	Indoor & Outdoor			An event venue on an 8-acre private lot in Katy with indoor and outdoor space, a bridal suite and groom's lounge.		832-855-5520	https://www.palmroyalvilla.com
Inn at Quarry Ridge	9401 Rust Lane	Bryan	Texas			Garden / Outdoor	Indoor & Outdoor	300		A country wedding venue north of Bryan/College Station with a pond-side gazebo, a climate-controlled hall and an eight-bedroom inn for exclusive-use wedding weekends.	info@innatquarryridge.com	979-822-8368	https://www.innatquarryridge.com
Margaritaville Lake Resort, Lake Conroe	600 Margaritaville Parkway	Montgomery	Texas			Ballroom / Hotel	Indoor & Outdoor	600		A lakefront resort on Lake Conroe with several ballrooms and outdoor ceremony sites, including a beach and a wedding circle.		936-448-4400	https://www.margaritavilleresorts.com/margaritaville-lake-resort-lake-conroe/weddings
The Barn at Lacey Farms	4504 Farm to Market Rd 390 W	Burton	Texas			Barn / Rustic	Indoor & Outdoor	182		A rustic barn venue near Burton that sells fixed wedding packages for micro, small and large guest counts.			https://thebarnatlaceyfarms.com
The Venue at Belle Oaks	15075 Country Club Drive	Beaumont	Texas			Historic / Estate	Indoor & Outdoor			A Beaumont wedding and concert venue that mixes rustic and luxury styling and offers a downloadable pricing pamphlet.		409-540-8247	https://thevenueatbelleoaks.com
The Venue at Railfan	101 East Main	Cameron	Texas			Ballroom / Hotel	Indoor	400		A 7,000 square foot event hall on the downtown Cameron square for weddings of 20 to 400 guests.	thevenueatrailfan@gmail.com	254-627-0558	https://thevenueatrailfan.com
Art Museum of Southeast Texas	500 Main Street	Beaumont	Texas			Ballroom / Hotel	Indoor			A downtown Beaumont art museum that rents its grand foyer and courtyard for weddings.	events@amset.org	409-832-3432	https://www.amset.org/facility-rental/
Willowynn Barn	16605 Cowan Rd	Santa Fe	Texas			Barn / Rustic	Indoor & Outdoor	250	Classic	A barn wedding venue on 18 private acres in Santa Fe with a chapel, bride and groom suites and on-site farm stay.	info@willowynnbarn.com	346-816-9911	https://willowynnbarn.com
The Astorian	2500 Summer Street Suite 3-123	Houston	Texas			Historic / Estate	Indoor			A Houston event venue in a landmark building with a gourmet kitchen, bar and downtown skyline views.	hello@astorianevents.com	832-460-6695	https://astorianevents.com
The Farmhouse Events	27135 Old Highway 105 W	Montgomery	Texas			Barn / Rustic	Indoor & Outdoor			A custom-built, all-white farmhouse-style venue with shiplap walls and tall ceilings near Montgomery.	info@thefarmhouseevents.com	936-236-9837	https://thefarmhouseevents.com
Boxwood Manor	945 E Hufsmith	Tomball	Texas			Historic / Estate	Indoor & Outdoor	300		A manor and chapel on almost 10 landscaped acres in Tomball that hosts one event per day.	info@boxwoodmanorevents.com		https://boxwoodmanorevents.com
The Peach Orchard	1737 Sawdust Road	The Woodlands	Texas			Historic / Estate	Indoor & Outdoor	300	Classic	A Northern European-style estate in The Woodlands with a chapel, ballroom and oak-shaded lawns.		832-616-0634	https://thepeachorchard.com
The Ice Plant Bldg.	529 East Colorado	La Grange	Texas			Historic / Estate	Indoor			A converted historic ice plant building in downtown La Grange used for weddings, with listed preferred vendors and nearby lodging.	info@theiceplantbldg.com	979-216-5955	https://theiceplantbldg.com
Tin Spur Ranch	2683 Old Hwy Rd.	Inez	Texas			Barn / Rustic	Indoor & Outdoor			A ranch event center near Victoria on over 40 acres with two ponds and more than 5,000 square feet of indoor space.		361-212-7310	https://tinspurranch.com
Spicewood Vineyards	1419 Co Rd 409	Spicewood	Texas			Restaurant / Vineyard	Indoor & Outdoor	200		Winery on a 32-acre vineyard with a tasting room and an event center used for wedding receptions.		830-693-5328	https://spicewoodvineyards.com
Thistlewood Manor & Gardens	1520 Roland Lane	Kyle	Texas			Historic / Estate	Indoor & Outdoor			Kyle wedding venue with manor-style indoor space and gardens, offering wedding packages.	info@thistlewoodmanor.com	512-268-1900	https://www.thistlewoodmanor.com
Cypress Valley	1223 Paleface Ranch Rd S	Spicewood	Texas			Garden / Outdoor	Outdoor			Treehouse retreat on more than 100 acres with a creek, pond and pool that also hosts weddings and proposals.	admin@cypressvalley.com	512-264-8880	https://www.cypressvalley.com
Carter Creek Winery Resort & Spa	4064 West US Highway 290	Johnson City	Texas			Restaurant / Vineyard	Indoor & Outdoor			Winery resort with villas, a brewery and spa that offers wedding planning on the Highway 290 wine trail.		877-232-0138	https://www.cartercreek.com
Sendera Springs	231 Avery Rd	Kerrville	Texas			Garden / Outdoor	Indoor & Outdoor			Kerrville wedding venue beside a lake with an on-site director and hostess handling day-of setup.		830-895-2691	https://www.senderasprings.com
Ruby Ranch Lodge	292 W. Barlett Drive	Buda	Texas			Barn / Rustic	Indoor & Outdoor			Former hunting-ranch lodge in Buda with a main lodge and kitchen that hosts weddings and lodging.		512-567-6979	https://www.rubyranchlodge.com
Inspiring Oaks Ranch	7901 Farm to Market Rd 2325	Wimberley	Texas			Garden / Outdoor	Outdoor			Wimberley ranch among more than 100 live oaks selling wedding packages that include on-site lodging.	info@inspiringoaksranch.com	512-573-3162	https://www.inspiringoaksranch.com
Red Ridge Receptions	306 KLBJ Road	Smithville	Texas			Barn / Rustic	Indoor & Outdoor			Rustic indoor-outdoor venue in Smithville with views over the Colorado River valley.	redridgereceptions@gmail.com	512-237-3589	https://www.redridgereceptions.com
The Bell House Wimberley	300 River Road	Wimberley	Texas			Historic / Estate	Indoor & Outdoor			Boutique venue near Wimberley Square with flexible indoor and outdoor spaces and micro-wedding options.	Bruce@TheBellHouseWimberley.com	512-557-6730	https://www.thebellhousewimberley.com
The Oaks at Boerne	1244 FM 474	Boerne	Texas			Barn / Rustic	Indoor & Outdoor			Family-owned venue built around a reclaimed barn once a chicken coop, with oak-shaded ceremony space and a fire pit.	info@theoaksatboerne.com	210-410-7300	https://theoaksatboerne.com/
Allegro Wedding & Events Venue	5001 McGregor Ln	Dripping Springs	Texas			Garden / Outdoor	Indoor & Outdoor			Dripping Springs venue with a chapel, event hall, outdoor ceremony sites and five guest cottages.	Info@allegroatx.com	512-813-5915	https://allegroatx.com/
Memory Lane Ranch & Lodge	403 K C Memory Ln	Dripping Springs	Texas			Barn / Rustic				Ten-acre Hill Country ranch among oaks selling all-inclusive wedding packages with lodging for 17 guests.	info@memorylanewedding.com	512-894-0700	https://www.memorylanewedding.com/
Felton Ranch	1100 Lanier Ranch Rd	Driftwood	Texas			Garden / Outdoor	Outdoor			Outdoor venue on over 15 acres of forest and meadow with a garden house and a bad-weather plan.		512-709-5251	https://feltonranch.com/
The Arlo	10700 Signal Hill	Austin	Texas			Ballroom / Hotel	Indoor & Outdoor			Modern 15,000-square-foot venue on the edge of the Hill Country with courtyard gardens and a lawn ceremony area.	info@thearloevents.com	512-215-0691	https://thearloevents.com/
Prospect House	12745 Silver Creek Rd	Dripping Springs	Texas			Garden / Outdoor	Indoor & Outdoor			Contemporary Dripping Springs venue with over 7,000 square feet of indoor and outdoor ceremony space.	events@prospecthousetx.com	512-987-5285	http://www.prospecthousetx.com/
The Lodge Event Center at Country Inn Cottages	3319 Lower Crabapple Rd	Fredericksburg	Texas			Barn / Rustic	Indoor & Outdoor			Fredericksburg event lodge with a dedicated wedding line, hosting destination weddings alongside the inn's cottages.	info@thelodgeeventcenter.com	830-998-6200	https://www.thelodgeeventcenter.com/
Drift Out West	19022 FM 150 W	Driftwood	Texas			Garden / Outdoor	Outdoor			Eleven-acre property on Onion Creek with gardens, a pond and a creekside trail that hosts weddings among other events.	events@driftoutwesttx.com	737-242-1611	https://www.driftoutwesttx.com/`,
  },
  {
    name: "Texas: DFW, East Texas, Houston, Austin, San Antonio, Waco, the Valley and West Texas",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Southfork Ranch	3700 Hogge Road	Parker	Texas			Historic / Estate	Indoor & Outdoor			The ranch long known as the Ewing home in the TV series Dallas, with large indoor halls and sprawling outdoor event grounds northeast of Dallas.	info@southforkranch.com	(972) 442-7800	https://southforkranch.com
Weston Gardens	8101 Anglin Drive	Fort Worth	Texas			Garden / Outdoor	Outdoor			Demonstration gardens that began in the 1930s and 1940s as a private estate, now set up as an outdoor stage for weddings and special events.	specialevents@westongardens.com	817-572-0549	https://www.westongardens.com
Oak Knoll Ranch	478 Three Skillet Rd	Springtown	Texas			Barn / Rustic				A Parker County ranch venue with separate wedding and micro-wedding pricing pages and tours by request.	oakknollranch@live.com	(214) 601-3187	https://www.oakknollranch.com
The Barn at Paradise Place	298 County Road 3673	Paradise	Texas			Barn / Rustic	Indoor & Outdoor			A 49-acre country property with a reception barn, a chapel with a bell tower and ceremony spots by a pond and on a hilltop.	info@thebarnatparadise.com	940-260-0760	https://thebarnatparadise.com
Magnolia Creek Ranch		Princeton	Texas			Barn / Rustic	Indoor & Outdoor	150		A twelve-acre ranch east of McKinney with a climate-controlled barn and a six-bedroom farmhouse for the wedding party.			https://magnoliacreekranch.com
The Fort Worth Club	306 W 7th Street	Fort Worth	Texas			Ballroom / Hotel	Indoor			A private club on the 12th floor of a downtown high-rise, with a 1920s-style ballroom and a contemporary room with city views.		817-336-7211	https://www.fortworthclub.com/Events/Weddings
T&P Station	221 W Lancaster Avenue	Fort Worth	Texas			Historic / Estate	Indoor			A historic downtown Fort Worth building blending period architecture with modern finishes for weddings and events.	info@tandpstation.com	469-246-0295	https://www.tandpstation.com
Southside Preservation Hall	1519 Lipscomb Street	Fort Worth	Texas			Historic / Estate	Indoor & Outdoor			A partly restored historic building run by a nonprofit, with a rose chapel, grand ballroom, reception salon and courtyard.	office@southsidepreservation.com	(817) 926-2800	https://www.southsidepreservation.com
Chateau at Forest Park	1800 N Forest Park Blvd	Fort Worth	Texas			Ballroom / Hotel	Indoor			A Fort Worth ballroom venue operating since 1999, with draped ceilings, accent lighting and tables and setup included.		(817) 878-2515	https://www.chateauatforestpark.com
Southern Bliss Weddings	5419 N US Hwy 59	Nacogdoches	Texas			Barn / Rustic	Indoor & Outdoor			A countryside property with a 7,100 square foot chandeliered barn, a stained-glass chapel area and a gazebo lawn for ceremonies.		(936) 366-0727	https://southernblisswedding.com
The Madory	793 County Road 228	Nacogdoches	Texas			Barn / Rustic	Indoor & Outdoor			A Nacogdoches wedding and event venue open since 2017, with a barn and an open-air pavilion that has an outdoor fireplace.	themadorynac@gmail.com	936-554-2974	https://www.themadory.com
Windham's Yellow Rose	645 County Road 217	Nacogdoches	Texas			Barn / Rustic	Indoor & Outdoor	150		A rustic venue a few miles outside Nacogdoches with a vaulted indoor hall, covered outdoor seating, an outdoor stage and an on-site kitchen.	vondaw1961@yahoo.com	(936) 305-3003	https://www.windhamsyellowrose.com
Steel Pines Venue	563 County Road 630	Nacogdoches	Texas			Barn / Rustic				A 2024-built venue among East Texas pines between Lufkin and Nacogdoches, with a customizable main room plus bridal suite and groom's lounge.		936-240-3717	https://www.steelpinesvenue.com
Mustang Creek Wedding Venue & Event Center	27923 US 82	Sherman	Texas			Ballroom / Hotel				A wedding and event center west of Sherman serving the North Dallas and Texoma area.	info@mceventcenter.com	903 814 0864	https://www.mceventcenter.com
Lucky Spur Ranch Retreat	1780 Strader Rd	Justin	Texas			Barn / Rustic	Indoor & Outdoor	400		A ranch among rolling hills and creeks with outdoor ceremony spots and a newly built reception barn that seats up to 400.		940-315-4094	https://luckyspur.net
Carmela's Magical Venue	6085 US-259	Longview	Texas			Ballroom / Hotel	Indoor & Outdoor			A Longview event center with indoor and outdoor spaces plus on-site catering, bar service and event coordinators.	magicaleventcenter@gmail.com	(903) 668-0268	https://carmelasmagicalvenue.com
Double K Rustic Ranch Venue	1071 County Road 365	Gainesville	Texas			Barn / Rustic	Indoor & Outdoor			A 175-acre ranch of rolling hills with a tree-lined drive, a barn and a lighted outdoor dance floor northwest of Denton.		940-727-4320	https://www.doublekrusticranch.com
The Mason Dallas	115 S Beckley Ave	Dallas	Texas			Historic / Estate	Indoor	200	Classic	A former Oak Cliff Masonic lodge built in 1920, with a ballroom, commercial kitchen and valet parking included in the rental.	info@themasondallas.com	214.730.0005	https://www.themasondallas.com
The Room on Main	2030 Main Street	Dallas	Texas			Ballroom / Hotel	Indoor	320		A sixth-floor downtown ballroom with 30-foot ceilings, tall windows, century-old hardwood floors and skyline views.	info@theroomonmain.com	214-742-1526	https://www.theroomonmain.com
Bella Cavalli Events	1651 West Sherman Drive	Aubrey	Texas			Barn / Rustic	Indoor & Outdoor	200		A 130-acre property with a Carriage House reception space, a pond and several ceremony sites including lakeside and woodland spots.	info@bellacavallievents.com	(940) 257-6382	https://www.bellacavallievents.com
Broussard Farm and Sevenne Hall	10714 East Club Road	Beaumont	Texas			Barn / Rustic	Indoor & Outdoor	300		A working ranch with an 1857 family house as a ceremony backdrop and Sevenne Hall, a dance hall with stage and sound for receptions.	info@broussardfarm.com	(409) 242-9921	https://broussardfarm.com
Reign Hills	9823 Hwy 69	Kountze	Texas			Historic / Estate				A chateau-style venue with gardens in Kountze, about an hour and a half from Houston.			https://www.reignhills.com
7 Oaks Event Garden	14865 Garner Road	Beaumont	Texas			Garden / Outdoor	Indoor & Outdoor			A rural homestead about 90 years old with gardens, a pine pavilion for ceremonies, a greenhouse altar and a small indoor room.	info@7oakseventgarden.com	832-594-7526	https://7oaksweddings.com
Palacio Maria	21728 Highland Knolls	Katy	Texas			Ballroom / Hotel	Indoor & Outdoor	360		Event center in Katy with a large divisible ballroom, a patio and a garden with a gazebo for ceremonies and receptions.	Palaciomaria@comcast.net	(281) 579-9933	https://www.palaciomaria.com
Bingham Ranch Events	901 FM 1331	Taylor	Texas			Historic / Estate	Outdoor			Family-run ranch on the San Gabriel River with an 1850s manor house, a waterfall amphitheater, a courtyard and wooded grounds for outdoor ceremonies.	info@binghamranchevents.com	(512) 750-1958	https://www.binghamranchevents.com
Cowboys & Angels Retreat	6411 Junction Hwy	Mountain Home	Texas			Barn / Rustic	Indoor & Outdoor	150		Hill Country ranch northwest of Kerrville with a small chapel in a 1920s structure, a party barn, an outdoor pavilion and cabins that sleep 36.	info@cowboysandangelsretreat.com	(830) 866-3442	https://www.cowboysandangelsretreat.com/hill-country-weddings/
Texas Hill Country Resort	23195 State Highway 16 N	Medina	Texas			Barn / Rustic	Indoor & Outdoor			About 100 acres of hills and old oaks with a 1948 limestone ranch house, a timbered recreation hall and lodge, cabins, and an infinity pool.	reservations@txhillcountryresort.com	(830) 201-1895	https://www.txhillcountryresort.com/wedding-venues-in-kerrville-tx/
Tank Town	805 N Pecos St	Lockhart	Texas			Barn / Rustic	Indoor	262		Rustic, flexible event space in Lockhart with on-site parking that hosts wedding ceremonies and receptions by appointment.	tanktowntx@gmail.com	512-914-4790	https://www.tanktowntx.com/private-events
The Lasker Inn	1019 16th Street	Galveston	Texas			Historic / Estate				Circa-1870 Galveston bed and breakfast that doubles as a wedding venue, a short way from the beaches and the Strand District.	info@laskerinn.com	409-497-4318	https://www.laskerinn.com
The Milano Event Center	16555 Creekbend Drive	Sugar Land	Texas			Ballroom / Hotel	Indoor & Outdoor	250		About 10,000 square feet in Sugar Land with three ballrooms, two private lounges and an open patio, with red oak beams and crystal chandeliers.	Sales@themilanoevents.com	832-617-2655	https://themilanoevents.com
The Trolley Station	2021 Strand	Galveston	Texas			Historic / Estate	Indoor			Ballroom with balcony, stage and atrium inside an 1894 building on Galveston's Strand, with a bridal room and a caterer's kitchen.		409-771-8252	https://www.galvestonhistoricalweddingvenues.com
Lumberyard Music Hall and Event Center	1109 Main St	Bastrop	Texas			Barn / Rustic	Indoor	150	Simple	Newly opened rustic-modern hall on Main Street in Bastrop with a bridal suite and groom's lounge, offering an all-inclusive package that starts at $7,300 with a plated dinner for 100.		512-321-7529	https://lumberyardmusichallandeventcenter.com
County Line Event Center	18232 County Road 127	Pearland	Texas			Barn / Rustic	Indoor & Outdoor	130		Pearland venue with a ballroom, onsite barn, outdoor pavilion, courtyard and bridal cottage, offered as venue-only or in all-inclusive packages.	Countylineeventcenter@outlook.com	281.482.9000	https://www.countylineeventcenter.com
Maison De Veaux	3907 Old Chocolate Bayou Rd	Pearland	Texas			Historic / Estate				New Orleans-inspired wedding venue in Pearland with white columns, wrought iron French doors and chandeliers.	info@maisondeveaux.com	(832) 637-7450	https://www.maisondeveaux.com
Lindsay Lakes	16536 Mueschke Rd	Cypress	Texas			Garden / Outdoor				Cypress wedding and events property offering ceremonies, receptions and banquets, with wedding packages on its site.	info@lindsaylakes.com	(281) 373-1800	https://www.lindsaylakes.com
Diamond Barrel Wedding and Event Venue	1101 County Road 284	Liberty Hill	Texas			Barn / Rustic	Indoor & Outdoor			Modern 2,400-square-foot barn opened in 2020 among oak trees and Hill Country landscaping, with indoor and outdoor ceremony options.	info@diamondbarrel.com		https://www.diamondbarrel.com
Lone Star Oaks	3354 CR 236	Liberty Hill	Texas			Barn / Rustic	Indoor & Outdoor	200		Climate-controlled chapel that seats 200, outdoor ceremonies under old oaks and a modern farmhouse reception space, with all-inclusive packages.	Mary@LoneStarOaks.com	(832) 483-6115	https://www.lonestaroaks.com
Beauty and the Beach	1586 Hwy 87	Gilchrist	Texas			Beach / Waterfront	Outdoor	200		Beachfront lighthouse built for weddings on the Bolivar Peninsula, with a gazebo ceremony spot, covered reception area, tiki bar and overnight rooms.			https://www.crystalbeachwedding.com
The Retreat at Balcones Springs	104 Balcones Springs Drive	Marble Falls	Texas			Barn / Rustic	Indoor & Outdoor			250-acre Hill Country camp-style property near Marble Falls with nine event venues, on-site lodging and in-house catering, operating since 1993.	info@texasretreat.com	830.693.6639	https://www.texasretreat.com
Moon Flower Hill	14000 FM 2769	Volente	Texas			Historic / Estate	Indoor & Outdoor	350		Private 15-acre estate overlooking Lake Travis with a 6,000-square-foot manor, an open-air pavilion and a veranda, rented for the whole property.		(512) 287-4000	https://www.moonflowerhill.com
Heaven On Earth Oaks	300 Douglas St	Missouri City	Texas			Historic / Estate	Indoor & Outdoor			Victorian mansion with 22-foot cathedral ceilings and a grand staircase, surrounded by a courtyard shaded by 200-year-old oaks.	heavenonearthoaks@gmail.com		https://www.heavenonearthoaks.com
The Gardens at West Green	21650 Milsa Dr	San Antonio	Texas			Garden / Outdoor	Outdoor	80	Simple	A small walled-in garden on two and a half acres west of San Antonio, set up for intimate ceremonies and receptions under mature oaks.	weddings@thegardensatwestgreen.com	(210) 698-9191	https://thegardensatwestgreen.com
The Venue at Mari Springs	11615 Stallion Rd	Temple	Texas			Barn / Rustic	Indoor & Outdoor	450		A Temple wedding ranch pairing a white stone country chapel with a red barn event centre and a corral on open Central Texas land.		(254) 247-1774	https://marisprings.com
Casa Rosa Event Venue	334 W Concho Ave	San Angelo	Texas			Garden / Outdoor	Outdoor	150		A downtown San Angelo property with a lawn for ceremonies and receptions, on a former restaurant site with tacos available from the house caterer.	info@sanangeloweddingsandevents.com	325-500-5379	https://www.casarosaevents.com
The White-Pool House Museum	112 E Martin Luther King Jr St	Odessa	Texas			Historic / Estate	Indoor & Outdoor			An 1887 Victorian farmhouse museum in Odessa whose gardens, gazebo and barn host weddings, with proceeds keeping the museum free to visit.	whitepoolhouse@outlook.com	432-333-4072	https://whitepoolhouse.com
Kessler's Hall	3204 W Wall St	Midland	Texas			Ballroom / Hotel	Indoor & Outdoor	300	Simple	A limestone-floored hall just west of downtown Midland with a chandelier entry and a fountain patio holding a covered ceremony spot.		432-634-5177	https://kesslershall.com
Farmhouse 1905	7582 Spring Valley Rd	Moody	Texas			Barn / Rustic	Indoor & Outdoor	180		A century-old farmhouse and a newly renovated barn side by side near Waco, with rooms in the house for up to 14 guests.	hello@farmhouse1905.com	254-218-3870	https://farmhouse1905.com
Double Creek Crossing	590 FM 1362 N	Caldwell	Texas			Barn / Rustic	Indoor & Outdoor			A rustic-elegant venue in Caldwell near Bryan and College Station, with bridal and groom suites and two private cabins on site.	doublecreekcrossing@gmail.com	979-200-9555	https://doublecreekcrossing.com
Cotton Creek Barn	608 Co Rd J	Tahoka	Texas			Barn / Rustic	Indoor & Outdoor	300		A family-run barn south of Lubbock built from reclaimed gin and farmhouse materials, with an overnight farmhouse and pool for up to 15 guests.	cottoncbarn@gmail.com	979-220-1318	https://cottoncreekbarn.com
Versalles Palace Event Center	1715 Saul Kleinfeld Dr	El Paso	Texas			Ballroom / Hotel	Indoor			An El Paso event hall for weddings and quinceañeras that offers its own decor, catering and a 360-degree photo booth.	versallespalaceevent@gmail.com	915-543-8188	https://versallespalaceeventcenter.com
Settles Point	4120 Stillhouse Lake Rd	Harker Heights	Texas			Historic / Estate	Indoor & Outdoor	150	Simple	A lakeside estate in Harker Heights with a banquet hall, marble-floored atrium and six king-bed suites overlooking Stillhouse Hollow Lake.	sales@settlespoint.com	(254) 698-2938	https://settlespoint.com
The Chapel at Caliber Oak	5235 Royal St	Salado	Texas			Garden / Outdoor	Indoor & Outdoor			A wedding chapel and courtyard in the village of Salado that has been hosting ceremonies since 2010.			https://caliberoak.com
The Reserve at Dancing Elk	313 Co Rd 351	Mathis	Texas			Barn / Rustic	Indoor & Outdoor			A South Texas ranch near Mathis with an event hall, covered pavilion, patio and exotic wildlife to see on the grounds.		(361) 946-4812	https://thereserveatdancingelk.com
Hideout on the Horseshoe	515 FM 2673	New Braunfels	Texas			Beach / Waterfront	Outdoor	250		A riverside Hill Country venue where vows are exchanged on the Guadalupe, with a covered pavilion and nineteen cabins for guests.			https://www.hideoutweddings.com
Cool Breeze Pavilion	7381 FM 775	Seguin	Texas			Barn / Rustic	Indoor & Outdoor			A family-owned 2,600 square foot covered pavilion outside Seguin with a fishing pond, turfed lawn and a full kitchen.	lindsey@coolbreezeliving.com	(210) 326-3148	https://coolbreezepavilion.com
Palacio de Destinee	1502 N Border Ave	Weslaco	Texas			Ballroom / Hotel	Indoor			A Weslaco event hall that hosts weddings and quinceañeras in the Rio Grande Valley.	palaciodedestinee@gmail.com	956-998-1457	https://palaciodedestinee.com
El Gran Marquez Special Events	3410 N Terry Rd	Edinburg	Texas			Ballroom / Hotel	Indoor			An Edinburg event venue with in-house services for weddings, private parties and corporate events in the Rio Grande Valley.	gmarquezevents@gmail.com	(956) 450-2204	https://www.elgranmarquezspecialevents.com
Paisano Ranch Weddings	11948 Knickerbocker Rd	San Angelo	Texas			Barn / Rustic	Indoor & Outdoor			A 1,400-acre working hunting ranch near San Angelo that offers wedding packages, cabins, a pond and an in-house chef.	info@paisanoranchweddings.com	325-315-6020	https://www.paisanoranchweddings.com`,
  },
];

export default batches;
