import type { VenueBatch } from "@/lib/venue-batches";

// Virginia venue batches. Every row's State is "Virginia". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Northern Virginia, Richmond and Charlottesville venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Morven Park	17195 Southern Planter Ln	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor			Estate of 1,000 acres around the Davis Mansion, with walled boxwood gardens, lawns and views of pasture and ridgeline.	events@morvenpark.org	703-777-2414	https://www.morvenpark.org/about/weddings-corporate-events/
Oatlands Historic House & Gardens	20850 Oatlands Plantation Ln	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor			Historic house museum with a 4.5-acre walled garden, carriage house and greenhouse, taking weddings on a limited basis.	info@oatlands.org	703-727-0670	https://oatlands.org/event-rental-spaces/
48 Fields	43372 Spinks Ferry Rd	Leesburg	Virginia			Barn / Rustic	Indoor & Outdoor	125	Classic	Cider house in a renovated two-level dairy barn on Loudoun farmland, for receptions of up to 125.	macy@48fields.com	(571) 277-3252	https://www.48fields.com/
Raspberry Plain Manor	16500 Agape Ln	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor			Historic manor house outside Leesburg where guests gather in a single room and couples may bring their own caterer, including kosher.	info@themanorsva.com	703-777-1888	https://www.raspberryplainmanor.com/
Lansdowne Resort	44050 Woodridge Pkwy	Leesburg	Virginia			Ballroom / Hotel	Indoor & Outdoor			Potomac River valley resort with several ballrooms, outdoor ceremony terraces, golf, a spa and rooms for guests.		703-729-8400	https://www.lansdowneresort.com/weddings
The Jefferson Hotel	101 W Franklin St	Richmond	Virginia			Ballroom / Hotel	Indoor			Downtown Richmond hotel that has hosted weddings for more than 125 years, with an in-house florist and room blocks for guests.		804.649.4750	https://www.jeffersonhotel.com/celebrate/overview
The Mill at Fine Creek		Powhatan	Virginia			Historic / Estate	Indoor & Outdoor	150		Ten historic acres west of Richmond with three ceremony sites, a hall seating 150 and thirteen guest cottages, booked one wedding at a time.		(804) 379-8211	https://themillatfinecreek.com/
Upper Shirley Vineyards	600 Shirley Plantation Rd	Charles City	Virginia			Restaurant / Vineyard	Indoor & Outdoor	300		Winery on the James River with riverfront ceremonies, a banquet room for up to 300, covered porches and in-house catering.		(804) 829-9463	https://www.uppershirleyvineyards.com/weddings
Wilton House Museum	215 S Wilton Rd	Richmond	Virginia			Historic / Estate	Indoor & Outdoor			Colonial-era house museum of the Colonial Dames with terraced lawns above the James River, rented for weddings.	lizf@nscdava.org	(804) 282-5936	https://wiltonhousemuseum.org/visit
Dover Hall	1500 Manakin Rd	Manakin-Sabot	Virginia			Historic / Estate	Indoor & Outdoor			Tudor-inspired 38,000 sq ft estate house on 55 acres in Goochland horse country, with a ballroom, reflecting pool and in-house catering.		(804) 784-6051	https://www.doverhall.com/weddings
Quirk Hotel Richmond	201 W Broad St	Richmond	Virginia			Ballroom / Hotel	Indoor & Outdoor	120		Art-filled boutique hotel downtown with 73 rooms and a rooftop for ceremonies and receptions of up to 120.		804-340-6040	https://www.quirkhotels.com/Event-Planning/weddings
Historic Westover	7000 Westover Rd	Charles City	Virginia			Historic / Estate	Outdoor			Mid-18th-century Byrd family house on the James River, with tented receptions on the riverfront lawn and house tours during cocktail hour.	info@historicwestover.com	804-829-2882	https://historicwestover.com/wedding-events.htm
Mount Ida Farm	6903 Blenheim Rd	Scottsville	Virginia			Barn / Rustic	Indoor & Outdoor			Farm of 5,000 acres south of Charlottesville with a renovated 8,500 sq ft cattle barn, a tent site and several manor houses for guest lodging.	info@mountidafarm.com	(434) 960-4655	https://mountidafarm.com/the-event-barn/
Keswick Hall	701 Club Dr	Keswick	Virginia			Ballroom / Hotel	Indoor & Outdoor	250		Historic resort hotel east of Charlottesville with a divisible ballroom, a Garden Room seating 110 and Blue Ridge views.	sales@keswick.com	434-979-3440	https://www.keswick.com/gather/weddings/
Castle Hill Cider	6065 Turkey Sag Rd	Keswick	Virginia			Barn / Rustic	Indoor & Outdoor	200		Cidery on 650 acres with a climate-controlled reception barn seating 200, a bluestone terrace above the lake and a linden grove for ceremonies.			https://www.castlehillcider.com/venue-spaces
Chiswell Farm & Winery	430 Greenwood Rd	Greenwood	Virginia			Restaurant / Vineyard	Outdoor	200		Outdoor winery venue west of Charlottesville run by the Chiles orchard family, for up to 200 with couples free to bring their own vendors.	wine@chiswellwinery.com	434.252.2947	https://chilesfamilyorchards.com/chiswell/weddings/
Cardinal Point Winery	9423 Batesville Rd	Afton	Virginia			Restaurant / Vineyard	Indoor & Outdoor	120		Family winery near Afton with weddings of up to 120 on the hill by its farmhouse, which sleeps 12, or up to 50 at the winery deck and mezzanine.		540-456-8400	https://www.cardinalpointwinery.com/private-events/
Glass House Winery	5898 Free Union Rd	Free Union	Virginia			Restaurant / Vineyard	Indoor & Outdoor	88		Winery and bed-and-breakfast north-west of Charlottesville whose glass conservatory of tropical plants seats 88, with terraces for more.		(434) 975-0094	https://glasshousewinery.com/weddings/
Afton Mountain Vineyards	234 Vineyard Ln	Afton	Virginia			Restaurant / Vineyard	Indoor & Outdoor	80		Blue Ridge vineyard with a glass climate-controlled pavilion, a ceremony lawn with an arbor and five cottages, for weddings of up to 80.	events@aftonmountainvineyards.com	540.456.8667	https://www.aftonmountainvineyards.com/private-events/
The Greencroft Club	575 Rodes Dr	Charlottesville	Virginia			Ballroom / Hotel	Indoor & Outdoor	225		Country club west of Charlottesville with stone fireplaces and chandeliered rooms, hosting receptions for groups of up to 225.		434-296-5597	https://greencroftclub.com/web/pages/wedding-events
Heigh Torr Estate	13656 Harpers Ferry Rd	Purcellville	Virginia			Historic / Estate	Indoor & Outdoor	180		Historic 178-acre Loudoun estate booked for whole wedding weekends, with overnight lodging, a clear-top pavilion and room for 180.	hello@heightorrestate.com	(540) 227-4033	https://www.heightorrestate.com/
Kalero Vineyard	36140 Charles Town Pike	Purcellville	Virginia			Barn / Rustic	Indoor & Outdoor	150		Vineyard near Harpers Ferry whose restored barn, its cornerstone laid in 1834, seats 150 with Blue Ridge views.		(540) 717-8119	https://www.kalerovineyard.com/weddings
Linden Row Inn	100 E Franklin St	Richmond	Virginia			Ballroom / Hotel	Indoor & Outdoor	125		Historic downtown inn with a garden courtyard, Parlour Suites for elopements and event space for up to 125.		1.804.783.7000	https://www.lindenrowinn.com/weddings
Doukénie Winery	14727 Mountain Rd	Hillsboro	Virginia			Restaurant / Vineyard	Indoor & Outdoor	150		Family winery in western Loudoun with a covered pavilion, gazebo and pond views, taking weddings of up to 150 when the whole site is rented.	info@doukeniewinery.com	540-668-6464	https://doukeniewinery.com/private-events/
The River View at Occoquan	9751 Ox Rd	Lorton	Virginia			Beach / Waterfront	Indoor & Outdoor	500		Regional-park event centre with floor-to-ceiling windows on the Occoquan River, seating 500, with two riverside ceremony areas and a historic cottage for getting ready.	riverview@nvrpa.org	703-690-2121	https://www.novaparks.com/weddings-catering/the-river-view`,
  },
];

export default batches;
