import type { VenueBatch } from "@/lib/venue-batches";

// Virginia venue batches. Every row's State is "Virginia". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Northern Virginia, Richmond and Charlottesville venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Morven Park	17195 Southern Planter Ln	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor			Estate of 1,000 acres around the Davis Mansion, with walled boxwood gardens, lawns and views of pasture and ridgeline.	events@morvenpark.org	703-777-2414	https://www.morvenpark.org/about/weddings-corporate-events/
Oatlands Historic House & Gardens	20850 Oatlands Plantation Ln	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor			Historic house museum with a 4.5-acre walled garden, carriage house and greenhouse, taking weddings on a limited basis.	info@oatlands.org	703-727-0670	https://oatlands.org/event-rental-spaces/
48 Fields	43372 Spinks Ferry Rd	Leesburg	Virginia			Barn / Rustic	Indoor & Outdoor	125	Classic	Cider house in a renovated two-level dairy barn on Loudoun farmland, for receptions of up to 125.	macy@48fields.com	(571) 277-3252	https://www.48fields.com/
Raspberry Plain Manor	16500 Agape Ln	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor			Historic manor house outside Leesburg where guests gather in a single room and couples may bring their own caterer, including kosher.	info@themanorsva.com	703-777-1888	https://www.raspberryplainmanor.com/
Lansdowne Resort	44050 Woodridge Pkwy	Leesburg	Virginia			Ballroom / Hotel	Indoor & Outdoor			Potomac River valley resort with several ballrooms, outdoor ceremony terraces, golf, a spa and rooms for guests.		703-729-8400	https://www.lansdowneresort.com/weddings
The Jefferson Hotel	101 W Franklin St	Richmond	Virginia			Ballroom / Hotel	Indoor			Downtown Richmond hotel that has hosted weddings for more than 125 years, with an in-house florist and room blocks for guests.		804.649.4750	https://www.jeffersonhotel.com/celebrate/overview
The Mill at Fine Creek		Powhatan	Virginia			Historic / Estate	Indoor & Outdoor	150		Ten historic acres west of Richmond with three ceremony sites, a hall seating 150 and thirteen guest cottages, booked one wedding at a time.		(804) 379-8211	https://themillatfinecreek.com/
Upper Shirley Vineyards	600 Shirley Plantation Rd	Charles City	Virginia			Restaurant / Vineyard	Indoor & Outdoor	300		Winery on the James River with riverfront ceremonies, a banquet room for up to 300, covered porches and in-house catering.		(804) 829-9463	https://www.uppershirleyvineyards.com/weddings
Wilton House Museum	215 S Wilton Rd	Richmond	Virginia			Historic / Estate	Indoor & Outdoor			Colonial-era house museum of the Colonial Dames with terraced lawns above the James River, rented for weddings.	lizf@nscdava.org	(804) 282-5936	https://wiltonhousemuseum.org/visit
Dover Hall	1500 Manakin Rd	Manakin-Sabot	Virginia			Historic / Estate	Indoor & Outdoor			Tudor-inspired 38,000 sq ft estate house on 55 acres in Goochland horse country, with a ballroom, reflecting pool and in-house catering.		(804) 784-6051	https://www.doverhall.com/weddings
Quirk Hotel Richmond	201 W Broad St	Richmond	Virginia			Ballroom / Hotel	Indoor & Outdoor	120		Art-filled boutique hotel downtown with 73 rooms and a rooftop for ceremonies and receptions of up to 120.		804-340-6040	https://www.quirkhotels.com/Event-Planning/weddings
Historic Westover	7000 Westover Rd	Charles City	Virginia			Historic / Estate	Outdoor			Mid-18th-century Byrd family house on the James River, with tented receptions on the riverfront lawn and house tours during cocktail hour.	info@historicwestover.com	804-829-2882	https://historicwestover.com/wedding-events.htm
Mount Ida Farm	6903 Blenheim Rd	Scottsville	Virginia			Barn / Rustic	Indoor & Outdoor			Farm of 5,000 acres south of Charlottesville with a renovated 8,500 sq ft cattle barn, a tent site and several manor houses for guest lodging.	info@mountidafarm.com	(434) 960-4655	https://mountidafarm.com/the-event-barn/
Keswick Hall	701 Club Dr	Keswick	Virginia			Ballroom / Hotel	Indoor & Outdoor	250		Historic resort hotel east of Charlottesville with a divisible ballroom, a Garden Room seating 110 and Blue Ridge views.	sales@keswick.com	434-979-3440	https://www.keswick.com/gather/weddings/
Castle Hill Cider	6065 Turkey Sag Rd	Keswick	Virginia			Barn / Rustic	Indoor & Outdoor	200		Cidery on 650 acres with a climate-controlled reception barn seating 200, a bluestone terrace above the lake and a linden grove for ceremonies.			https://www.castlehillcider.com/venue-spaces
Chiswell Farm & Winery	430 Greenwood Rd	Greenwood	Virginia			Restaurant / Vineyard	Outdoor	200		Outdoor winery venue west of Charlottesville run by the Chiles orchard family, for up to 200 with couples free to bring their own vendors.	wine@chiswellwinery.com	434.252.2947	https://chilesfamilyorchards.com/chiswell/weddings/
Cardinal Point Winery	9423 Batesville Rd	Afton	Virginia			Restaurant / Vineyard	Indoor & Outdoor	120		Family winery near Afton with weddings of up to 120 on the hill by its farmhouse, which sleeps 12, or up to 50 at the winery deck and mezzanine.		540-456-8400	https://www.cardinalpointwinery.com/private-events/
Glass House Winery	5898 Free Union Rd	Free Union	Virginia			Restaurant / Vineyard	Indoor & Outdoor	88		Winery and bed-and-breakfast north-west of Charlottesville whose glass conservatory of tropical plants seats 88, with terraces for more.		(434) 975-0094	https://glasshousewinery.com/weddings/
Afton Mountain Vineyards	234 Vineyard Ln	Afton	Virginia			Restaurant / Vineyard	Indoor & Outdoor	80		Blue Ridge vineyard with a glass climate-controlled pavilion, a ceremony lawn with an arbor and five cottages, for weddings of up to 80.	events@aftonmountainvineyards.com	540.456.8667	https://www.aftonmountainvineyards.com/private-events/
The Greencroft Club	575 Rodes Dr	Charlottesville	Virginia			Ballroom / Hotel	Indoor & Outdoor	225		Country club west of Charlottesville with stone fireplaces and chandeliered rooms, hosting receptions for groups of up to 225.		434-296-5597	https://greencroftclub.com/web/pages/wedding-events
Heigh Torr Estate	13656 Harpers Ferry Rd	Purcellville	Virginia			Historic / Estate	Indoor & Outdoor	180		Historic 178-acre Loudoun estate booked for whole wedding weekends, with overnight lodging, a clear-top pavilion and room for 180.	hello@heightorrestate.com	(540) 227-4033	https://www.heightorrestate.com/
Kalero Vineyard	36140 Charles Town Pike	Purcellville	Virginia			Barn / Rustic	Indoor & Outdoor	150		Vineyard near Harpers Ferry whose restored barn, its cornerstone laid in 1834, seats 150 with Blue Ridge views.		(540) 717-8119	https://www.kalerovineyard.com/weddings
Linden Row Inn	100 E Franklin St	Richmond	Virginia			Ballroom / Hotel	Indoor & Outdoor	125		Historic downtown inn with a garden courtyard, Parlour Suites for elopements and event space for up to 125.		1.804.783.7000	https://www.lindenrowinn.com/weddings
Doukénie Winery	14727 Mountain Rd	Hillsboro	Virginia			Restaurant / Vineyard	Indoor & Outdoor	150		Family winery in western Loudoun with a covered pavilion, gazebo and pond views, taking weddings of up to 150 when the whole site is rented.	info@doukeniewinery.com	540-668-6464	https://doukeniewinery.com/private-events/
The River View at Occoquan	9751 Ox Rd	Lorton	Virginia			Beach / Waterfront	Indoor & Outdoor	500		Regional-park event centre with floor-to-ceiling windows on the Occoquan River, seating 500, with two riverside ceremony areas and a historic cottage for getting ready.	riverview@nvrpa.org	703-690-2121	https://www.novaparks.com/weddings-catering/the-river-view`,
  },
  {
    name: "Virginia Beach, Hampton Roads and Northern Virginia venues",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Middleburg Barn		Middleburg	Virginia			Barn / Rustic	Indoor & Outdoor			A post-and-beam event barn built in 2017 with outdoor terraces, a mountain-view patio and green space for weddings.	office@themiddleburgbarn.com		https://www.themiddleburgbarn.com
Foxchase Manor	8310 Chatsworth Drive	Manassas	Virginia			Ballroom / Hotel	Indoor			A Jeffersonian-style manor with multiple ballrooms, a caterer workspace and on-site parking, used for weddings and other events.	info@themanorsva.com	703-369-3638	https://www.foxchasemanor.com
Briar Patch Bed & Breakfast Inn	23130 Briar Patch Lane	Middleburg	Virginia			Historic / Estate	Indoor & Outdoor	200		A circa-1805 farm on 47 acres east of Middleburg with an indoor event building called the Fox Den and guest rooms on site.	info@briarpatchbandb.com	703-327-5911	https://www.briarpatchbandb.com
Sunset Hills Vineyard	38295 Fremont Overlook Ln	Purcellville	Virginia			Restaurant / Vineyard	Indoor & Outdoor			A winery on a restored former Amish farm with a restored barn, lawn areas and mountain views.	information@sunsethillsvineyard.com	540-882-4560	https://www.sunsethillsvineyard.com/weddings
The Manor at Airmont	19246 Ebenezer Church Road	Round Hill	Virginia			Historic / Estate	Indoor & Outdoor			A private countryside estate with a 19th-century manor house and conservatory, hosting indoor receptions and outdoor ceremonies.	info@themanoratairmont.com	703-646-8125	https://www.themanoratairmont.com
Eden Try Winery	6818 River Road	Fredericksburg	Virginia			Restaurant / Vineyard	Indoor & Outdoor			A winery offering vineyard-side vows, receptions in a restored white barn and a manor house for the wedding party.	info@edentrywinery.com	540-321-7972	https://www.edentrywinery.com
Hornsby House Inn	702 Main St	Yorktown	Virginia			Historic / Estate	Indoor & Outdoor			A 1933 Georgian house on Yorktown's Main Street that runs as an inn and hosts weddings, including backyard ceremonies.		757-369-0200	https://www.hornsbyhouseinn.com
New Branch Farms	14509 Lawnes Drive	Smithfield	Virginia			Barn / Rustic	Indoor & Outdoor			Industrial-style farmhouse venue on open farmland with large glass doors that open onto the fields.	info@newbranchfarms.com	(757) 903-5953	https://www.newbranchfarms.com
The Obici House	4700 Sleepy Hole Road	Suffolk	Virginia			Historic / Estate	Indoor & Outdoor	500	Classic	Historic mansion at Sleepy Hole Golf Course overlooking the Nansemond River, seating 150 indoors and up to 500 under a tent.	admin@theobicihouse.com	(757) 335-2773	https://theobicihouse.com
The Maine of Williamsburg	2580 John Tyler Highway	Williamsburg	Virginia			Ballroom / Hotel	Indoor & Outdoor	200		Purpose-built event venue with a grand hall and fireplace, a sunroom, dressing suites, a covered veranda and a covered patio.		757-903-0620	https://www.themaineofwilliamsburg.com
The Gala 417	2105 W Great Neck Rd	Virginia Beach	Virginia			Beach / Waterfront	Indoor			All-inclusive modern wedding venue with chandeliers and floor-to-ceiling windows at the Long Bay Pointe boating resort.	Bookings@thegala417.com	757-995-4007	https://thegala417.com
The Historic Post Office	132 E Queen St	Hampton	Virginia			Historic / Estate	Indoor			Two-story restored post office on Hampton's waterfront offering customizable layouts and coordination services.	info@thehistoricpostoffice.com	(757) 848-3885	https://thehistoricpostoffice.com
Vaux Hall Farm	27698 Bobtown Rd	Melfa	Virginia			Beach / Waterfront	Outdoor	250		Working waterfront property on Pungoteague Creek with a fan-cooled pavilion, private docks and lodging for wedding guests.		757-410-4264	https://vauxhallfarm.com
Yorktown Freight Shed	331 Water Street	Yorktown	Virginia			Beach / Waterfront	Indoor & Outdoor			County-owned 1935 waterfront building at Riverwalk Landing with a brick plaza on the York River.			https://yorkcounty.gov/875/Rent-the-Freight-Shed
Virginia Aquarium & Marine Science Center	717 General Booth Blvd	Virginia Beach	Virginia			Ballroom / Hotel	Indoor	100		Aquarium that hosts ceremonies beside its ray pool, shark exhibit or a creek-view promenade room.	PrivateEvents@VirginiaAquarium.com	(757) 385-3474	https://virginiaaquarium.com/plan-an-event
Event Venues of Smithfield	220 N. Church Street	Smithfield	Virginia			Historic / Estate	Indoor & Outdoor			Downtown Smithfield rentals on the Pagan River, a waterfront event center with a deck and a historic Manor House.	info@EventVenuesofSmithfield.com	757-356-9939	https://www.eventvenuesofsmithfield.com/
Colonial Heritage Club	6500 Arthur Hills Dr	Williamsburg	Virginia			Ballroom / Hotel	Indoor & Outdoor			British-Colonial-style golf clubhouse with a grand ballroom, smaller event rooms, a gazebo and an outdoor ceremony lawn.		757-645-2000	https://www.colonialheritageclub.com/weddings-and-events-overview
Williamsburg Botanical Garden	5537 Centerville Rd	Williamsburg	Virginia			Garden / Outdoor	Outdoor	30	Simple	Two-acre public garden in Freedom Park with a covered pavilion, rented by the hour for small ceremonies.			https://williamsburgbotanicalgarden.org/rental/weddings-private-events/
Kiln Creek Golf Club & Resort	1003 Brick Kiln Blvd	Newport News	Virginia			Ballroom / Hotel	Indoor			Golf resort that offers all-inclusive wedding packages through its Celebrate section.		757-874-2600	https://www.kilncreekgolf.com
The Watermen's Museum	309 Water Street	Yorktown	Virginia			Beach / Waterfront	Indoor & Outdoor			Museum that rents its Carriage House, event tent and deck, and a private York River beach for weddings.	admin@watermens.org	757-887-2641	https://watermens.org/wedding-venue/
Lesner Inn	3319 Shore Drive	Virginia Beach	Virginia			Beach / Waterfront	Indoor & Outdoor	200		Shore Drive event venue between the Chesapeake Bay and Lynnhaven River with a hall, waterside deck and in-house catering.		(757) 481-1122	https://lesnerinn.com`,
  },
  {
    name: "Virginia venues: Northern Virginia, Hampton Roads, Richmond and Shenandoah",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Barn at Willow Brook	15486 Limestone School Road	Leesburg	Virginia			Barn / Rustic	Indoor & Outdoor	150		An intimate luxury wedding barn near Leesburg, with an on-site cottage and packages that include an overnight stay.	betsy@thebarnatwillowbrook.com		https://thebarnatwillowbrook.com/
Halcyon Watson	23528 Watson Rd.	Leesburg	Virginia			Historic / Estate	Indoor & Outdoor	150		A restored historic estate on 22 acres in Loudoun County with a barn that seats up to 150 guests.	info@halcyonwatson.com	571-707-4030	https://halcyonwatson.com/
Still Meadow Farm	18297 Silcott Springs Road	Purcellville	Virginia			Barn / Rustic	Indoor & Outdoor	125		A restored equestrian barn in western Loudoun hunt country, with exclusive weekend use and an estate house that sleeps eight.	stay@stillmeadowfarmva.com	540-456-1950	https://stillmeadowfarmva.com/weddings/
The Oak Barn at Loyalty	14572 Loyalty Rd	Leesburg	Virginia			Barn / Rustic	Indoor & Outdoor			A family-owned boutique barn venue in Loudoun wine country, with mountain views and access to the property for the whole weekend.		571-918-0837	https://theoakbarnatloyalty.com/
Scarlet Springs Farm	39755 Old Wheatland Road	Waterford	Virginia			Barn / Rustic	Indoor & Outdoor			A family-run farm near Waterford that offers weddings in a stone barn or a tent, plus a bed and breakfast and mini-Highland cattle.	info@scarletspringsfarm.com		https://www.scarletspringsfarm.com/weddings
The Manor 1858	21595 Chudleigh Farm Ln.	Aldie	Virginia			Historic / Estate	Indoor & Outdoor	250		A historic farm in Aldie with a manor house and room for a tented celebration of up to 250 guests.	sales@themanor1858.com		https://www.themanor1858.com/gatheringspaces
Inn at Evergreen	15890 Berkeley Dr	Haymarket	Virginia			Ballroom / Hotel	Indoor & Outdoor	180		A country-club inn in Haymarket with a ballroom for receptions of up to 180 guests and eleven guest rooms.	innkeeper@evergreencc.org	703-743-4711	https://innatevergreen.com/weddings
Historic Rosemont Manor	16 Rosemont Manor Lane	Berryville	Virginia			Historic / Estate	Indoor & Outdoor	400		An 1811 estate near Berryville with a manor, a carriage house for 175 and a barn built to hold up to 400 guests.	communications@rosemont1811.com	540-955-2834	https://www.rosemont1811.com/
Landfall Events	350 Chestnut Grove Road	Winchester	Virginia			Barn / Rustic	Indoor & Outdoor	225		A private valley venue near Winchester with an outdoor ceremony island and a rustic barn that seats 200 to 225 guests.		540-335-7721	https://landfallevents.com/weddings/
Oak Creek Farm	25840 Independence Road	Unionville	Virginia			Barn / Rustic	Indoor & Outdoor	120		A family-run barn wedding venue in Unionville that hosts one wedding a week and seats about 120 guests comfortably.	jackie@oakcreekfarmva.com	540-219-1820	https://oakcreekfarmva.com/
The Trellis Venue	1121 John Marshall Highway	Front Royal	Virginia			Garden / Outdoor	Indoor & Outdoor	100		A hillside venue in Front Royal with panoramic views, a main house and five cottages, and room for around 100 guests.	events@thetrellisvenue.com	540-622-7441	https://www.thetrellisvenue.com/
Rock Hill Farm	14461 Norman Rd	Culpeper	Virginia			Barn / Rustic	Indoor & Outdoor	160		A working cattle farm of nearly 300 acres in the Blue Ridge foothills, with a climate-controlled reception space seating up to 160.			https://rockhillfarmevents.com/
Bay Tree Manor	4201 Seaford Road	Seaford	Virginia			Beach / Waterfront	Indoor & Outdoor	160	Classic	A 9.5-acre waterfront estate near Yorktown overlooking Bay Tree Creek, with a pavilion for celebrations of up to 160 guests.	stay@btmanor.com	757-897-6062	https://www.btmanor.com/weddings.html
The Alexandrian	480 King St.	Alexandria	Virginia			Ballroom / Hotel	Indoor & Outdoor	170		A boutique hotel in Old Town Alexandria with a courtyard and a ballroom that suits up to 170 guests.		703-549-6080	https://www.thealexandrian.com/weddings`,
  },
];

export default batches;
