import type { VenueBatch } from "@/lib/venue-batches";

// Wisconsin venue batches. Every row's State is "Wisconsin". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Milwaukee, Waukesha, Madison, Lake Geneva and Door County",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Ivy House	906 S Barclay St	Milwaukee	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Milwaukee event hall with a greenery-filled ballroom and an ivy-covered outdoor patio used for ceremonies.	events@ivyhousemke.com	414-539-3339	https://ivyhousemke.com
The Grain Exchange	225 E Michigan St	Milwaukee	Wisconsin			Historic / Estate	Indoor	350		Three-storey hall of nearly 10,000 square feet in downtown Milwaukee's Mackie Building, with frescoes and stone walls and exclusive in-house catering.	geinfo@bartolottas.com	414-727-6980	https://www.bartolottas.com/catering/venues/grain-exchange
The Pabst Mansion	2000 W Wisconsin Ave	Milwaukee	Wisconsin			Historic / Estate	Indoor	50		Historic brewer's mansion and house museum that rents its period rooms for micro weddings and small receptions.	info@pabstmansion.com	(414) 931-0808	https://www.pabstmansion.com/rental-info
Villa Terrace Museum and Gardens	2220 N Terrace Ave	Milwaukee	Wisconsin			Historic / Estate	Indoor & Outdoor			Mediterranean-style museum villa on a bluff above Lake Michigan, designed by David Adler, with terraced gardens used for ceremonies and receptions.		(414) 293-5678	https://www.villaterrace.org/host_your_event/rental_options_fees/
Rustic Manor 1848	3115 State Road 83	Hartland	Wisconsin			Barn / Rustic	Indoor & Outdoor	275		Event barn on a 12-acre property with a hayloft, outdoor patio with firepit, and a six-bedroom stone house for the wedding party.	hello@rusticmanor1848.com	262-528-3115	https://www.rusticmanor1848.com
Lilac Acres		Waukesha	Wisconsin			Barn / Rustic	Indoor & Outdoor	175		Countryside farm venue with a ceremony barn, reception hall, licensed bar and patio, and an event house where the couple can stay overnight.	info@lilacacres.com	(262) 875-7002	https://www.lilacacres.com
SALT at Newport Shores	320 N Lake St	Port Washington	Wisconsin			Beach / Waterfront	Indoor & Outdoor	125		Modern event space beside the Port Washington marina with Lake Michigan views, a waterfront promenade and exclusive catering by From Scratch.		(262) 618-4661	https://saltatnewportshores.com
Monona Terrace	1 John Nolen Dr	Madison	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Frank Lloyd Wright-designed convention centre on Lake Monona with a Madison Ballroom, rooftop gardens and in-house catering.	info@mononaterrace.com	608-261-4000	https://www.mononaterrace.com/weddings/
The Edgewater	1001 Wisconsin Pl	Madison	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Lakefront hotel on Lake Mendota with a 6,150 square foot Grand Ballroom behind tall windows, lakeside terraces, a plaza and a rooftop bar.		608-535-8200	https://www.theedgewater.com/edgewater-wedding-weekend/
The Madison Club	5 E Wilson St	Madison	Wisconsin			Ballroom / Hotel	Indoor	225		Private downtown Madison club near the lake offering inclusive wedding packages for 50 to 225 guests that bundle in a membership.	reception@madisonclub.org	608-255-4861	https://www.madisonclub.org/madisonclubweddings
Memorial Union	800 Langdon St	Madison	Wisconsin			Historic / Estate	Indoor			University of Wisconsin student union on Lake Mendota, with the Great Hall and Tripp Commons available for receptions to Wisconsin Union members.	events@union.wisc.edu	(608) 262-2511	https://union.wisc.edu/host-your-event/weddings
Olbrich Botanical Gardens	3330 Atwood Ave	Madison	Wisconsin			Garden / Outdoor	Indoor & Outdoor	150		Public botanical garden with a glass-walled Evjue Commons reception room opening onto the Lussier Terrace patio.			https://www.olbrich.org/private-event-rentals
The Abbey Resort	269 Fontana Blvd	Fontana	Wisconsin			Beach / Waterfront	Indoor & Outdoor	400		Lake Geneva resort in Fontana with a Harbor Lawn and West Shore Pavilion for lakeside ceremonies, plus a spa and guest rooms.	info@theabbeyresort.com	800-709-1323	https://www.theabbeyresort.com/lake-geneva-weddings/
The Landmark Resort	4929 Landmark Dr	Egg Harbor	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	200		Door County resort in Egg Harbor with a 200-guest reception room, a terrace over the bay and a Flagship Garden for ceremonies.		920-868-3205	https://www.thelandmarkresort.com/en/weddings/
`,
  },
  {
    name: "Milwaukee and Waukesha counties, Racine, Madison, Baraboo and the Dells, Green Bay, Door County, Lake Geneva and Kohler",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Jennings Holler	W379 S9674 County Rd S	Eagle	Wisconsin			Barn / Rustic	Indoor & Outdoor	400		Thirty-five-acre former ranch in the Kettle Moraine forest, built as a western town with a barn, a 19th-century chapel, a saloon and wooded ceremony sites.			https://jenningsholler.com/weddings/
Badger Farms	1682 County Rd BB	Deerfield	Wisconsin			Barn / Rustic	Indoor & Outdoor	200		Farm venue east of Madison with a barn and a connected shop hall, each with its own full kitchen and a two-day Saturday rental.		608-438-3283	https://www.badgerfarms.com/weddings-events/
Harvest Moon Pond	N3540 State Road 22	Poynette	Wisconsin			Barn / Rustic	Indoor & Outdoor	225	Classic	Historic barn on 18 acres north of Madison with a pond, willow trees, an old sheep barn and a loft ceremony space for wet weather.		608-285-2536	https://harvestmoonpond.com/
The Loft at 132	132 Market St	Sun Prairie	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	135		Second-floor event space in downtown Sun Prairie with cream-brick walls, walnut floors, an elevator and a rooftop garden with a heated bar.	hello@theloftat132.com	608-235-9506	https://theloftat132.com/the-venue
Bridle Barn & Gardens	9736 Blue Valley Rd	Mount Horeb	Wisconsin			Barn / Rustic	Indoor & Outdoor	250		Restored c1870 horse barn outside Mount Horeb with a hilltop pergola ceremony site, formal gardens, a 30 by 20 foot deck and a sunroom suite.			https://www.bridlebarnandgardens.com/
The Swan Barn Door	4161 River Rd	Wisconsin Dells	Wisconsin			Barn / Rustic	Indoor & Outdoor	450	Classic	Newer 12,000 square foot stone-and-timber barn on River Road with a farmhouse and nearby condos for guest lodging.	info@theswanbarndoor.com	608-254-5900	https://theswanbarndoor.com/weddings/
Vennebu Hill	360 County Road A	Baraboo	Wisconsin			Barn / Rustic	Indoor & Outdoor	324	Classic	Restored Gothic cattle barn on a family farm atop a hill overlooking the Baraboo Bluffs, with a walnut-tree ceremony spot and a farmhouse on site.	info@vennebuhill.com	608-253-6349	https://www.vennebuhill.com/wedding-barn-event-center
The Dells Barn	E10918 Moon Rd	Baraboo	Wisconsin			Barn / Rustic	Indoor & Outdoor			Hand-built 1957 barn of reclaimed wood in Baraboo, once a theatre and country-music hall, with a 40-foot stage and vintage theatre-style seats.	dellsbarn@gmail.com		https://www.thedellsbarn.com/
Timmer's Resort	5151 Timmer Bay Rd	West Bend	Wisconsin			Beach / Waterfront	Indoor & Outdoor	300		Lakeside resort dating from 1864 on Big Cedar Lake, with a lakeside lawn for tented weddings, a bocce lawn and historic dining rooms with fireplaces.	events@timmersresort.com	262-338-7710	https://timmersresort.com/events
DeKoven Center	600 21st St	Racine	Wisconsin			Historic / Estate	Indoor & Outdoor	225	Simple	Historic Episcopal campus on Lake Michigan with a Great Hall, Assembly Hall, St. John's Chapel and a courtyard and gardens for ceremonies.		262-633-6401	https://www.dekovencenter.org/wedding
Mercantile Hall	425 N Pine St	Burlington	Wisconsin			Historic / Estate	Indoor & Outdoor	220		Exposed-brick hall in historic downtown Burlington with warm wood floors, high ceilings and a small outdoor garden courtyard.	eventmanagers@mercantilehall.com	262-758-6280	https://mercantilehall.com/all-the-details/
Hamlet Creek Weddings & Events	3562 Finger Rd	Green Bay	Wisconsin			Historic / Estate	Indoor & Outdoor			Converted 1883 chapel with original beams and wood floors, a loft above the Grand Room, a changing suite and a private cedar-pergola patio.	info@hamletcreek.com	920-393-8272	https://www.hamletcreek.com/
Northern Haus	10414 Fieldcrest Rd	Sister Bay	Wisconsin			Barn / Rustic	Indoor & Outdoor	225		New white-walled farmhouse-style barn on 30 acres in Door County with a covered patio, a forest ceremony clearing and a loft for small ceremonies.	info@northernhaus.com	920-401-1044	https://www.northernhaus.com/weddings
The American Club	419 Highland Dr	Kohler	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Resort hotel in the village of Kohler with historic ballrooms, championship golf courses and a 500-acre wildlife preserve close by.		855-444-2838	https://www.kohlerwisconsin.com/weddings
Grand Geneva Resort & Spa	7036 Grand Geneva Way	Lake Geneva	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	400		Large resort on 1,300 acres near Lake Geneva with several ballrooms, a rustic chalet by the ski hill, a golf-course pavilion and four ceremony lawns.	info@grandgeneva.com	262-248-8811	https://www.grandgeneva.com/weddings/venues
National Railroad Museum	2285 S Broadway	Green Bay	Wisconsin			Historic / Estate	Indoor & Outdoor	250		Railway museum on the Fox River where receptions sit among locomotives and rolling stock, with a riverfront space for ceremonies.	info@nationalrrmuseum.org	920-437-7623	https://nationalrrmuseum.org/private-events/
The Valerie	1281 Blue Ribbon Dr	Oconomowoc	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	400	Classic	Modern event venue in the Pabst Farms development with a main hall, a bar, and separate bridal and groom's suites with game rooms.	mcollins@thevalerie.com	262-510-5061	https://thevalerie.com/
The Delafield Hotel	415 Genesee St	Delafield	Wisconsin			Ballroom / Hotel	Indoor	250		Boutique hotel in downtown Delafield with cherry-wood interiors, its own restaurant and kitchen, and ceremony, reception and room block under one roof.	info@thedelafieldhotel.com	262-646-1600	https://www.thedelafieldhotel.com/
Tenzing Events	131 W Seeboth St	Milwaukee	Wisconsin			Historic / Estate	Indoor	200		Milwaukee event building of exposed Cream City brick with the Azara hall, a penthouse micro-wedding loft called The Nest and a bridal suite.	takotaclarke@tenzingevents.com	414-271-5437	https://www.tenzingevents.com/
Delafield Brewhaus	3832 Hillside Dr	Delafield	Wisconsin			Restaurant / Vineyard	Indoor	200		Brewpub in Delafield with a banquet room hosting all-inclusive rehearsal dinners and weddings, with menus set per couple.		262-646-7821	https://www.delafieldbrewhaus.com/banquets-weddings
Pilot Project Brewing Milwaukee	1128 N 9th St	Milwaukee	Wisconsin			Restaurant / Vineyard	Indoor & Outdoor			Brewery incubator and taproom in Milwaukee with a restaurant, a rooftop and a patio that can be booked for weddings and rehearsal dinners.		414-395-1070	https://www.pilotprojectbrewing.com/mkeprivateevents
Garver Events	3241 Garver Green	Madison	Wisconsin			Historic / Estate	Indoor	500		Converted 1906 sugar-beet feed mill on Madison's north side with four event spaces including an atrium, and on-site parking.	events@garverevents.com	901-264-0228	https://garverevents.com/weddings/
Cave of the Mounds	2975 Cave of the Mounds Rd	Blue Mounds	Wisconsin			Barn / Rustic	Indoor & Outdoor	150		Show cave and prairie park west of Madison renting an 1883 hillside barn, a renovated visitor centre, a tent lawn and small cave rooms for ceremonies.		608-437-3038	https://www.caveofthemounds.com/private-events-rentals/
`,
  },
];

export default batches;
