import type { VenueBatch } from "@/lib/venue-batches";

// Wisconsin venue batches. Every row's State is "Wisconsin". Add new batches at the end.
const batches: VenueBatch[] = [
  {
    name: "Milwaukee, Waukesha, Madison, Lake Geneva and Door County",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
The Ivy House	906 S Barclay St	Milwaukee	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Milwaukee event hall with a greenery-filled ballroom and an ivy-covered outdoor patio used for ceremonies.	events@ivyhousemke.com	414-539-3339	https://ivyhousemke.com
The Grain Exchange	225 E Michigan St	Milwaukee	Wisconsin			Historic / Estate	Indoor	350		Three-storey hall of nearly 10,000 square feet in downtown Milwaukee's Mackie Building, with frescoes and stone walls and exclusive in-house catering.	geinfo@bartolottas.com	414-727-6980	https://www.bartolottas.com/catering/venues/grain-exchange
The Pabst Mansion	2000 W Wisconsin Ave	Milwaukee	Wisconsin			Historic / Estate	Indoor	50		Historic brewer's mansion and house museum that rents its period rooms for micro weddings and small receptions.	info@pabstmansion.com	(414) 931-0808	https://www.pabstmansion.com/rental-info
Villa Terrace Museum and Gardens	2220 N Terrace Ave	Milwaukee	Wisconsin			Historic / Estate	Indoor & Outdoor			Mediterranean-style museum villa on a bluff above Lake Michigan, designed by David Adler, with terraced gardens used for ceremonies and receptions.		(414) 293-5678	https://www.villaterrace.org/host_your_event/rental_options_fees/
Rustic Manor 1848	3115 State Road 83	Hartland	Wisconsin			Barn / Rustic	Indoor & Outdoor	275		Event barn on a 12-acre property with a hayloft, outdoor patio with firepit, and a six-bedroom stone house for the wedding party.	hello@rusticmanor1848.com	262-528-3115	https://www.rusticmanor1848.com
Lilac Acres		Waukesha	Wisconsin			Barn / Rustic	Indoor & Outdoor	175		Countryside farm venue with a ceremony barn, reception hall, licensed bar and patio, and an event house where the couple can stay overnight.	info@lilacacres.com	(262) 875-7002	https://www.lilacacres.com
SALT at Newport Shores	320 N Lake St	Port Washington	Wisconsin			Beach / Waterfront	Indoor & Outdoor	125		Modern event space beside the Port Washington marina with Lake Michigan views, a waterfront promenade and exclusive catering by From Scratch.		(262) 618-4661	https://saltatnewportshores.com
Monona Terrace	1 John Nolen Dr	Madison	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Frank Lloyd Wright-designed convention centre on Lake Monona with a Madison Ballroom, rooftop gardens and in-house catering.	info@mononaterrace.com	608-261-4000	https://www.mononaterrace.com/weddings/
The Edgewater	1001 Wisconsin Pl	Madison	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Lakefront hotel on Lake Mendota with a 6,150 square foot Grand Ballroom behind tall windows, lakeside terraces, a plaza and a rooftop bar.		608-535-8200	https://www.theedgewater.com/edgewater-wedding-weekend/
The Madison Club	5 E Wilson St	Madison	Wisconsin			Ballroom / Hotel	Indoor	225		Private downtown Madison club near the lake offering inclusive wedding packages for 50 to 225 guests that bundle in a membership.	reception@madisonclub.org	608-255-4861	https://www.madisonclub.org/madisonclubweddings
Memorial Union	800 Langdon St	Madison	Wisconsin			Historic / Estate	Indoor			University of Wisconsin student union on Lake Mendota, with the Great Hall and Tripp Commons available for receptions to Wisconsin Union members.	events@union.wisc.edu	(608) 262-2511	https://union.wisc.edu/host-your-event/weddings
Olbrich Botanical Gardens	3330 Atwood Ave	Madison	Wisconsin			Garden / Outdoor	Indoor & Outdoor	150		Public botanical garden with a glass-walled Evjue Commons reception room opening onto the Lussier Terrace patio.			https://www.olbrich.org/private-event-rentals
The Abbey Resort	269 Fontana Blvd	Fontana	Wisconsin			Beach / Waterfront	Indoor & Outdoor	400		Lake Geneva resort in Fontana with a Harbor Lawn and West Shore Pavilion for lakeside ceremonies, plus a spa and guest rooms.	info@theabbeyresort.com	800-709-1323	https://www.theabbeyresort.com/lake-geneva-weddings/
The Landmark Resort	4929 Landmark Dr	Egg Harbor	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	200		Door County resort in Egg Harbor with a 200-guest reception room, a terrace over the bay and a Flagship Garden for ceremonies.		920-868-3205	https://www.thelandmarkresort.com/en/weddings/
`,
  },
  {
    name: "Milwaukee and Waukesha counties, Racine, Madison, Baraboo and the Dells, Green Bay, Door County, Lake Geneva and Kohler",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Jennings Holler	W379 S9674 County Rd S	Eagle	Wisconsin			Barn / Rustic	Indoor & Outdoor	400		Thirty-five-acre former ranch in the Kettle Moraine forest, built as a western town with a barn, a 19th-century chapel, a saloon and wooded ceremony sites.			https://jenningsholler.com/weddings/
Badger Farms	1682 County Rd BB	Deerfield	Wisconsin			Barn / Rustic	Indoor & Outdoor	200		Farm venue east of Madison with a barn and a connected shop hall, each with its own full kitchen and a two-day Saturday rental.		608-438-3283	https://www.badgerfarms.com/weddings-events/
Harvest Moon Pond	N3540 State Road 22	Poynette	Wisconsin			Barn / Rustic	Indoor & Outdoor	225	Classic	Historic barn on 18 acres north of Madison with a pond, willow trees, an old sheep barn and a loft ceremony space for wet weather.		608-285-2536	https://harvestmoonpond.com/
The Loft at 132	132 Market St	Sun Prairie	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	135		Second-floor event space in downtown Sun Prairie with cream-brick walls, walnut floors, an elevator and a rooftop garden with a heated bar.	hello@theloftat132.com	608-235-9506	https://theloftat132.com/the-venue
Bridle Barn & Gardens	9736 Blue Valley Rd	Mount Horeb	Wisconsin			Barn / Rustic	Indoor & Outdoor	250		Restored c1870 horse barn outside Mount Horeb with a hilltop pergola ceremony site, formal gardens, a 30 by 20 foot deck and a sunroom suite.			https://www.bridlebarnandgardens.com/
The Swan Barn Door	4161 River Rd	Wisconsin Dells	Wisconsin			Barn / Rustic	Indoor & Outdoor	450	Classic	Newer 12,000 square foot stone-and-timber barn on River Road with a farmhouse and nearby condos for guest lodging.	info@theswanbarndoor.com	608-254-5900	https://theswanbarndoor.com/weddings/
Vennebu Hill	360 County Road A	Baraboo	Wisconsin			Barn / Rustic	Indoor & Outdoor	324	Classic	Restored Gothic cattle barn on a family farm atop a hill overlooking the Baraboo Bluffs, with a walnut-tree ceremony spot and a farmhouse on site.	info@vennebuhill.com	608-253-6349	https://www.vennebuhill.com/wedding-barn-event-center
The Dells Barn	E10918 Moon Rd	Baraboo	Wisconsin			Barn / Rustic	Indoor & Outdoor			Hand-built 1957 barn of reclaimed wood in Baraboo, once a theatre and country-music hall, with a 40-foot stage and vintage theatre-style seats.	dellsbarn@gmail.com		https://www.thedellsbarn.com/
Timmer's Resort	5151 Timmer Bay Rd	West Bend	Wisconsin			Beach / Waterfront	Indoor & Outdoor	300		Lakeside resort dating from 1864 on Big Cedar Lake, with a lakeside lawn for tented weddings, a bocce lawn and historic dining rooms with fireplaces.	events@timmersresort.com	262-338-7710	https://timmersresort.com/events
DeKoven Center	600 21st St	Racine	Wisconsin			Historic / Estate	Indoor & Outdoor	225	Simple	Historic Episcopal campus on Lake Michigan with a Great Hall, Assembly Hall, St. John's Chapel and a courtyard and gardens for ceremonies.		262-633-6401	https://www.dekovencenter.org/wedding
Mercantile Hall	425 N Pine St	Burlington	Wisconsin			Historic / Estate	Indoor & Outdoor	220		Exposed-brick hall in historic downtown Burlington with warm wood floors, high ceilings and a small outdoor garden courtyard.	eventmanagers@mercantilehall.com	262-758-6280	https://mercantilehall.com/all-the-details/
Hamlet Creek Weddings & Events	3562 Finger Rd	Green Bay	Wisconsin			Historic / Estate	Indoor & Outdoor			Converted 1883 chapel with original beams and wood floors, a loft above the Grand Room, a changing suite and a private cedar-pergola patio.	info@hamletcreek.com	920-393-8272	https://www.hamletcreek.com/
Northern Haus	10414 Fieldcrest Rd	Sister Bay	Wisconsin			Barn / Rustic	Indoor & Outdoor	225		New white-walled farmhouse-style barn on 30 acres in Door County with a covered patio, a forest ceremony clearing and a loft for small ceremonies.	info@northernhaus.com	920-401-1044	https://www.northernhaus.com/weddings
The American Club	419 Highland Dr	Kohler	Wisconsin			Ballroom / Hotel	Indoor & Outdoor			Resort hotel in the village of Kohler with historic ballrooms, championship golf courses and a 500-acre wildlife preserve close by.		855-444-2838	https://www.kohlerwisconsin.com/weddings
Grand Geneva Resort & Spa	7036 Grand Geneva Way	Lake Geneva	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	400		Large resort on 1,300 acres near Lake Geneva with several ballrooms, a rustic chalet by the ski hill, a golf-course pavilion and four ceremony lawns.	info@grandgeneva.com	262-248-8811	https://www.grandgeneva.com/weddings/venues
National Railroad Museum	2285 S Broadway	Green Bay	Wisconsin			Historic / Estate	Indoor & Outdoor	250		Railway museum on the Fox River where receptions sit among locomotives and rolling stock, with a riverfront space for ceremonies.	info@nationalrrmuseum.org	920-437-7623	https://nationalrrmuseum.org/private-events/
The Valerie	1281 Blue Ribbon Dr	Oconomowoc	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	400	Classic	Modern event venue in the Pabst Farms development with a main hall, a bar, and separate bridal and groom's suites with game rooms.	mcollins@thevalerie.com	262-510-5061	https://thevalerie.com/
The Delafield Hotel	415 Genesee St	Delafield	Wisconsin			Ballroom / Hotel	Indoor	250		Boutique hotel in downtown Delafield with cherry-wood interiors, its own restaurant and kitchen, and ceremony, reception and room block under one roof.	info@thedelafieldhotel.com	262-646-1600	https://www.thedelafieldhotel.com/
Tenzing Events	131 W Seeboth St	Milwaukee	Wisconsin			Historic / Estate	Indoor	200		Milwaukee event building of exposed Cream City brick with the Azara hall, a penthouse micro-wedding loft called The Nest and a bridal suite.	takotaclarke@tenzingevents.com	414-271-5437	https://www.tenzingevents.com/
Delafield Brewhaus	3832 Hillside Dr	Delafield	Wisconsin			Restaurant / Vineyard	Indoor	200		Brewpub in Delafield with a banquet room hosting all-inclusive rehearsal dinners and weddings, with menus set per couple.		262-646-7821	https://www.delafieldbrewhaus.com/banquets-weddings
Pilot Project Brewing Milwaukee	1128 N 9th St	Milwaukee	Wisconsin			Restaurant / Vineyard	Indoor & Outdoor			Brewery incubator and taproom in Milwaukee with a restaurant, a rooftop and a patio that can be booked for weddings and rehearsal dinners.		414-395-1070	https://www.pilotprojectbrewing.com/mkeprivateevents
Garver Events	3241 Garver Green	Madison	Wisconsin			Historic / Estate	Indoor	500		Converted 1906 sugar-beet feed mill on Madison's north side with four event spaces including an atrium, and on-site parking.	events@garverevents.com	901-264-0228	https://garverevents.com/weddings/
Cave of the Mounds	2975 Cave of the Mounds Rd	Blue Mounds	Wisconsin			Barn / Rustic	Indoor & Outdoor	150		Show cave and prairie park west of Madison renting an 1883 hillside barn, a renovated visitor centre, a tent lawn and small cave rooms for ceremonies.		608-437-3038	https://www.caveofthemounds.com/private-events-rentals/
`,
  },
  {
    name: "Northeast, western and southern Wisconsin: Fox Valley, Door County, La Crosse, Eau Claire, Wausau, Kenosha, Lake Geneva and Dells",
    tsv: `Name	Address	City	State	Latitude	Longitude	Venue type	Setting	Capacity	Price tier	Description	Email	Phone	Website
Homestead Meadows	W7560 West Spencer Rd	Appleton	Wisconsin			Barn / Rustic	Indoor & Outdoor	220	Classic	Restored farm on 50-plus acres with an upper and lower barn, a hayloft reception hall, outdoor ceremony sites, ponds and meadows.		920-205-4200	https://homesteadmeadows.com
Stonewood Venue	850 Kepler Dr	Green Bay	Wisconsin			Ballroom / Hotel	Indoor			Modern banquet and event building with ballroom space, bridal and groom suites and on-site catering.		(920) 770-4033	https://stonewoodvenue.com
Barrel Haus at Badger State Brewing	990 Tony Canadeo Run	Green Bay	Wisconsin			Restaurant / Vineyard	Indoor & Outdoor			Renovated 1960s building at a brewery with a 7,500 sq ft event hall, a long bar, a patio and garden plaza.			https://www.badgerstatebrewing.com
The Waters	1393 Washington Ave	Oshkosh	Wisconsin			Historic / Estate	Indoor & Outdoor	300		Former yacht club built in 1903 on the Lake Winnebago shore, with a second-floor ballroom and a lawn for ceremonies.	audrey@thewatersoshkosh.com	(920) 231-6800	https://thewatersoshkosh.com
Sepia Chapel	1820 Jefferson Street	Two Rivers	Wisconsin			Historic / Estate	Indoor			Historic downtown building of about 8,400 sq ft with high ceilings, chandeliers and modern finishes.	info@sepiachapel.com	(920) 905-4985	https://www.sepiachapel.com
Wisconsin Maritime Museum	75 Maritime Drive	Manitowoc	Wisconsin			Historic / Estate	Indoor & Outdoor			Waterfront museum with a 3,100 sq ft roof deck, a river-view room divisible into three, and the USS Cobia submarine alongside.	tseilheimer@wisconsinmaritime.org	(920) 684-0218	https://www.wisconsinmaritime.org
Blue Harbor Resort	725 Blue Harbor Drive	Sheboygan	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	500		Lake Michigan resort with a ballroom, a waterfront ceremony site, guest rooms and villas on the property.		1-866-701-2583	https://www.blueharborresort.com
Kress Pavilion	7845 Church Street	Egg Harbor	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	200	Simple	Village-owned two-story building with a second-floor Great Hall, exposed beams and wraparound porches facing the bay.	kresspavilion@villageofeggharbor.org	920-868-3334	https://kresspavilion.org
Waverly Beach	N8770 Fire Lane 1	Menasha	Wisconsin			Beach / Waterfront	Indoor & Outdoor	500		Lake Winnebago shoreline restaurant and banquet venue with an 8,200 sq ft ballroom, an outdoor pavilion and a bridal suite.		(920) 883-0530	https://waverlybeachweddings.com
Tundra Lodge Resort	865 Lombardi Ave	Green Bay	Wisconsin			Ballroom / Hotel	Indoor	300		Lodge-style waterpark resort near Lambeau Field with two chandeliered ballrooms and on-site guest rooms.	lharbath@tundralodge.com	920-496-2224	https://www.tundralodge.com
Green Bay Botanical Garden	2600 Larsen Rd	Green Bay	Wisconsin			Garden / Outdoor	Outdoor			47-acre botanical garden with themed plantings that can be rented for weddings.	info@gbbg.org	920.490.9457	https://www.gbbg.org
Court Yard	2100 Dawson Ave	La Crosse	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	325	Simple	Black-and-white reception hall in La Crosse with two bars, bridal and groom suites and a private courtyard for ceremonies.	sales@CelebrationsLaCrosse.com	(608) 783-3335	https://celebrationslacrosse.com/court-yard/
The Greenhouse at Bittersweet	N3075 State Road 16	La Crosse	Wisconsin			Historic / Estate	Indoor & Outdoor			Historic property with a greenhouse and a country barn whose grounds run down to a marsh, used for weddings.	bittersweetgreenhouse@gmail.com	(608) 782-3276	https://www.thegreenhouseatbittersweet.com
The Enchanted Barn	1543 6 1/2 Ave	Hillsdale	Wisconsin			Barn / Rustic	Indoor & Outdoor			Restored dairy barn with a hayloft, an open-air ceremony lawn, bridal and groom suites and on-site lodging.			https://theenchantedbarn.com/weddings
West Creek Event Center	S7650 WI-37	Eau Claire	Wisconsin			Barn / Rustic	Indoor & Outdoor	300		Barn-style event hall south of Eau Claire with vaulted ceilings, covered patios, a bridal suite and on-site catering.	westcreekeventcenter@gmail.com	715-558-1345	https://westcreekec.com
The Barn at Mirror Lake	656 N Eau Claire St	Mondovi	Wisconsin			Barn / Rustic	Indoor & Outdoor	225	Simple	Wedding barn on a working 45-acre farm with 1,200 feet of lakefront, bridal and groom suites and a catering kitchen.		715-461-5397	https://thebarnatmirrorlake.com
Schultz's Wedding & Event Barn		Eleva	Wisconsin			Barn / Rustic	Indoor & Outdoor	200		Heated, refurbished barn south of Eau Claire with indoor and outdoor ceremony options and bride and groom suites.	schultzsweddingbarn@gmail.com	608-792-0487	https://www.schultzsweddingbarn.com
Lilydale Dance Hall & Event Venue	6343 County Highway N	Chippewa Falls	Wisconsin			Barn / Rustic	Indoor & Outdoor			Barn-style dance hall between Eau Claire and Chippewa Falls with a hardwood floor, bridal suite with Juliet balcony and a veranda.		715-456-2328	https://www.lilydalewi.com
Lake Wissota Golf Course	16108 97th Ave	Chippewa Falls	Wisconsin			Ballroom / Hotel	Indoor	313		Golf course with a banquet facility that hosts wedding receptions, with catering planned by its chef and events planner.		(888) 382-4780	https://www.lakewissotagolf.com
Eron's Event Barn	3471 County Road C	Stevens Point	Wisconsin			Barn / Rustic	Indoor & Outdoor	300		Climate-controlled barn on a farm west of Stevens Point with a bridal suite, groom's room and outdoor ceremony areas, hosting one wedding per weekend.	EronsEventBarn@gmail.com		https://www.eronseventbarn.com/
SentryWorld	601 Michigan Ave N	Stevens Point	Wisconsin			Ballroom / Hotel	Indoor & Outdoor	500		Golf resort with several indoor reception rooms, an outdoor pergola, bridal salons and an on-site inn.		715-345-1600	https://www.sentryworld.com/weddings
Jefferson Street Inn	201 Jefferson St	Wausau	Wisconsin			Ballroom / Hotel	Indoor	280		Downtown Wausau hotel with eight event rooms, including a Grand Ballroom set up banquet style for receptions.		715-845-6500	https://jeffersonstreetinn.com/weddings-and-events/
Granite Peak	227200 Snowbird Avenue	Wausau	Wisconsin			Historic / Estate	Indoor & Outdoor	300		Ski area at the foot of Rib Mountain with two wedding chalets, one built in 1939, and a list of approved caterers.	info@skigranitepeak.com	(715) 845-2846	https://www.skigranitepeak.com/plan-purchase/groups-weddings/weddings
Rothschild Pavilion	211 Grand Avenue	Rothschild	Wisconsin			Historic / Estate	Indoor	500		Village-owned 1911 pavilion with a large floating maple dance floor, rented for weddings through the village hall.		715-359-3660	https://rothschildwi.com/residents/amenities/parks_and_recreation/rothschild_pavilion.php
The Lotus Ranch	220 WI-65	River Falls	Wisconsin			Barn / Rustic	Indoor			Barn venue on 22 acres of countryside outside River Falls, serving couples from the Twin Cities, Hudson and River Falls.	Teresa@theLotusRanch.com	651.208.8288	https://www.thelotusranch.com
The Waters of Minocqua	8116 US 51	Minocqua	Wisconsin			Ballroom / Hotel	Indoor	100		Northwoods lodge and indoor waterpark resort with an on-site restaurant that hosts weddings and receptions.		715-358-4000	https://www.thewatersofminocqua.com
Lakewoods Resort & Golf		Cable	Wisconsin			Beach / Waterfront	Indoor & Outdoor	450		Lake Namakagon resort on 300 acres offering ceremony spots from the lodge to an island gazebo and a reception hall for up to 450.		715-794-2561	https://www.lakewoodsresort.com/weddings
Bayfield Lakeside Pavilion	2 Front Street	Bayfield	Wisconsin			Beach / Waterfront	Indoor & Outdoor	200		City-owned heated pavilion on the Bayfield waterfront with a large dance floor, kitchen and a deck overlooking the harbor.		715-779-5712	https://www.cityofbayfield.com/lakeside-pavilion.html
Kemper Center	6501 3rd Avenue	Kenosha	Wisconsin			Historic / Estate	Indoor & Outdoor			Historic 17.5-acre campus on Lake Michigan with seven separate spaces, from a Victorian parlor setting to a banquet hall with gardens.		(262) 925-8040	https://www.kempercenter.com
Palestrina Event Center	1105 Laser Street, Suite 101	Verona	Wisconsin			Ballroom / Hotel	Indoor			Event hall in a Verona business park that hosts one event per day with exclusive use of the space and a preferred vendor list.	info@palestrinaeventcenter.com		https://www.palestrinaeventcenter.com
Glacier Canyon Lodge at the Wilderness Resort	45 Hillman Rd	Wisconsin Dells	Wisconsin			Ballroom / Hotel	Indoor			Resort lodge offering the Sandstone Ballroom, the Wilderness Ballroom and the Wild Rock Clubhouse overlooking the golf course for ceremonies and receptions.		(608) 253-2488	https://www.wildernessresort.com/glacier-canyon-lodge/weddings
Beloit Club	2327 Riverside Drive	Beloit	Wisconsin			Historic / Estate	Indoor			Private club in a 24,000-square-foot historic clubhouse with several dining and event rooms available for weddings.	info@thebeloitclub.com	(608) 364-9000	https://www.beloitclub.com
Ironworks Hotel Beloit	500 Pleasant Street	Beloit	Wisconsin			Ballroom / Hotel	Indoor			Boutique hotel in a converted industrial building on the Rock River with meeting and event space and an on-site steakhouse.	info@ironworkshotel.com	(608) 362-5500	https://www.ironworkshotelbeloit.com
Halverson House	S110W23450 County Line Drive	Waterford	Wisconsin			Barn / Rustic	Indoor & Outdoor			Barn and Victorian-house wedding property with a main ballroom, gardens and several barns, plus bed and breakfast rooms.	info@halversonhouse.com	(262) 706-3414	https://www.halversonhouse.com
The Cupola Barn		Oconomowoc	Wisconsin			Barn / Rustic	Indoor & Outdoor	200	Classic	Restored barn on five landscaped acres in Oconomowoc, rented for weddings and other private events.	events@cupolabarn.com	262-617-4038	https://cupolabarn.com
The Riviera	812 Wrigley Drive	Lake Geneva	Wisconsin			Beach / Waterfront	Indoor			Lakefront event hall on Geneva Lake that offers wedding, corporate and social event packages.	lakegenevariviera@gmail.com	262-344-8246	https://www.lakegenevariviera.com
Barn at Trinity Peak		Oconomowoc	Wisconsin			Barn / Rustic	Indoor & Outdoor			Renovated 1934 dairy barn with pine plank floors and silo restrooms, offering indoor and outdoor ceremony spots on landscaped grounds.	barnattrinitypeak@gmail.com	262-955-8080	https://www.barnattrinitypeak.com
10 South	10 S. High St.	Janesville	Wisconsin			Historic / Estate	Indoor & Outdoor	375		Brick downtown Janesville building with a main hall, private dressing suites and a fireplace patio used for ceremonies.	team@10southvenue.com	608-590-0030	https://10southvenue.com
Circa on Seventh	4902 Seventh Avenue	Kenosha	Wisconsin			Historic / Estate	Indoor			Converted historic theater in Kenosha's Harborside area with 22-foot ceilings and exposed brick, run by Culinary Infusion.	Circa@Culinary-Infusion.com	262-764-0601	https://circaonseventh.com
The Gardens Wedding Center	7003 WI-175	Allenton	Wisconsin			Historic / Estate	Indoor & Outdoor	150	Classic	Family-run property with a restored historic chapel and three acres of gardens with a pond, waterfall and wedding bridge.		(262) 629-4411	https://gardensweddingcenter.com
The Hub at Cedar Creek	1814 Washington	Cedarburg	Wisconsin			Restaurant / Vineyard	Indoor & Outdoor	325		Restaurant and banquet hall on five acres along Cedar Creek with indoor space, patio and tent options for weddings.		262-618-4751	http://www.thehubcedarburg.com
LaRocque Farms	N 1701 Town Hall Road	Walworth	Wisconsin			Barn / Rustic	Indoor & Outdoor			80-acre farm with a timber-framed barn, sailcloth tent, gazebo and orchard, booked as a Friday-to-Sunday weekend package from June to September.			https://www.larocquefarms.com
Historic Courthouse 1893		Waukesha	Wisconsin			Historic / Estate	Indoor	300		Romanesque former courthouse in downtown Waukesha with two levels, bridal rooms and exclusive catering by Chef Jack's.		(262) 574-9170	https://www.courthouse1893.com
The Covenant at Murray Mansion	2219 Washington Avenue	Racine	Wisconsin			Historic / Estate	Indoor	320		Former Danish church with vaulted ceilings, stained glass and a pipe-organ bar, attached to the historic Murray Mansion.	Covenant@Culinary-Infusion.com	262-583-2241	https://thecovenantatmurraymansion.com
`,
  },
];

export default batches;
